### ISSUE TITLE
Send_keys fails to send left parenthesis in Firefox in some cases

### ISSUE THREAD

**Issue by csims** [SeleniumHQ/selenium#674] opened 2015-06-16 15:29 UTC
Using the Ruby bindings with Firefox 38.0.5 and selenium-webdriver gem version 2.46.2, I'm unable to send left parentheses in some cases (ex: on google.com it works, on webjet.com it doesn't).  I've reproduced the issue in Windows 7 64-bit and OS X 10.10.3, and with Ruby 1.9.3 and 2.2.2, with the below example test case, which worked with selenium-webdriver -v 2.44 and Firefox 33 (before native events went away):

require 'selenium-webdriver'
browser = Selenium::WebDriver.for :firefox
browser.navigate.to "http://webjet.com"
element = browser.find_element(:id, 'CityTo')
element.send_keys "(BOS)"

Expected: text field should fill with "(BOS)"
Actual: text field fills with "BOS)"

**Comment by ddavison** [comment] 2015-06-16 17:26
so, i can reproduce this issue, but I'm not sure that this is a Selenium issue.. this seems like it could be the Webjet website doing some javascript in the backend, and stripping it off?

**Comment by crusaders-vsct** [comment] 2015-07-03 09:33
Hello, 

We have exactly the same issue with :
 - Windows 7 64-bit
 - Firefox 38.0
 - "Selenium dependencies" (webdriver, java, firefox-driver, etc.) in version 2.46.0

The left parenthesis is not send (caused by synthetic events ?).

With Firefox 33.0 and dependencies in 2.44.0 (native events), the problem is not present. But if we activate the synthetic events, the problem is reproduced.

This issue is not reproduced on chrome.

For now, we have “fixed” this with this work around (found on https://code.google.com/p/selenium/issues/detail?id=1723#c12) :

````java
String myTextToSend = “Hello (World)”.replaceAll("\\(", Keys.chord(Keys.SHIFT, "9")):
WebElement.sendKeys(myTextToSend);
````
However when this code is executed with native events on Firefox 33, the character "9" is written (instead of '(' ).

**Comment by florentbr** [comment] 2015-09-01 13:06
It is reproducible on Wikipedia.
It occurs when an input field is enhanced with some JavaScript to produce the auto-complete.
This issue doesn't occur with the Chrome, IE and PhantomJS driver.

Environment:
Windows 8.1, Firefox 40.0.2, Selenium 2.27.1

To reproduce (Python):

    import selenium
    from selenium import webdriver
    wd = webdriver.Firefox()
    wd.get("https://en.wikipedia.org/wiki/Main_Page")
    ele = wd.find_element_by_id("searchInput")
    ele.send_keys("a(b)c")
    assert "a(b)c" == e.get_attribute('value')

**Comment by ddavison** [comment] 2015-09-10 21:49
thanks for doing that research @florentbr :+1: I had a feeling something like that might've been happening. 

I'm still not sure if we are going to do anything about this.

**Comment by lukeis** [comment] 2015-11-05 23:13
so... after spending some time trying to trace this down... it appears the javascript on a page (at least to Firefox and in particular the [nsIDOMWindowUtils.sendKeyEvent()](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIDOMWindowUtils#sendKeyEvent()) ) calls event.preventDefault when the keydown event for "(" is fired.

Now... I could not find it in the javascript on a few pages that reproduced this behavior of the preventDefault actually being called. But then again this sendKeyEvent method is deprecated in favor of [nsITextInputProcessor](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsITextInputProcessor).

I think it would be a good idea to change to this method in > v38 of firefox. Except for the fact that marionette is coming soon (well, it has to for other reasons) and the level of effort to change to using this type of sendKeys model is non-trivial. On top of that, I'm not certain that would even fix the issue entirely.

With that being said... I basically think this issue is going to be in a state of "won't fix" and will eventually be closed when marionette becomes the default driver for Firefox / Selenium.

Workarounds are pretty easy, such as using execute script to set the value of the input up to the '(' character that you want to send, and then using send keys for the remaining text (in order to trigger the proper events)

**Comment by barancev** [comment] 2017-08-03 15:55
It's time to close this issue, geckodriver is the default and it passes this test.

(But I should note that legacy driver passed it too on both mentioned sites, wikipedia and webject :))

**Closed by barancev** 2017-08-03 15:55 UTC
Labels: D-firefox
