### ISSUE TITLE
Selenium is flooding /tmp with firefox profiles until no space left

### ISSUE THREAD

**Issue by killown** [SeleniumHQ/selenium#5559] opened 2018-03-01 23:07 UTC
What steps will reproduce the problem?
instantiated FirefoxProfile  creates /tmp files and doesn't delete after quit
example of tmp profile /tmp/tmpaq5z0hj7/webdriver-py-profilecopy/storage/

What is the expected output? What do you see instead?
Either it should not create the directory or it should delete it after finishing it's job

What version of the product are you using? On what operating system?
Archlinux updated
Selenium 3.9.0

Please provide any additional information below.
eats up the system disk space until no space left.

**Comment by tushartyagi** [comment] 2018-03-04 07:25
Is Firefox crashing or not exiting using `driver.quit()`? This might be the case when the browsers don't exit cleanly.

For example, running the following code creates and deletes a temp profile:
```
from selenium import webdriver
def run_selenium(url):
    driver = webdriver.Firefox(firefox_binary = "/usr/local/bin/ff") 
    driver.get(url)        
    driver.quit()
```

I'm using Firefox 58 with geckodriver 0.19.1

**Comment by killown** [comment] 2018-03-04 15:05
Indeed, I am using try: except and sometimes closing the browser manually which throws an error

**Comment by p0deje** [comment] 2018-03-05 08:10
@killown Is this issue not relevant then?

**Comment by killown** [comment] 2018-03-05 13:07
any way to get those tmp dir names so I can remove them in except?

**Comment by barancev** [comment] 2018-03-13 07:20
If you can handle test failure it's easy to call quit(), no need to delete dirs. If you can't or wan't handle test failures -- where and when are you going to clean up the temp dir?

**Comment by barancev** [comment] 2018-04-05 19:40
Closing the issue, it's expected behavior.

**Closed by barancev** 2018-04-05 19:40 UTC
Labels: C-py, D-firefox, R-awaiting answer

**Comment by Uma-divvela** [comment] 2018-11-08 07:47
I tried to put that browser.quit() in "finally block".  Even though when I try hitting it parallelly, many tmp files are being generated in my /tmp folder . Its like for second hundreds of files until no space left. I'm using firefox browser. Do we have any solution to it??.

**Comment by AlekseiMarinichenko** [comment] 2019-03-14 09:40
The same problem. If Firefox failed to load profile, than profile folder will remain. You can not catch this with exception to execute _driver.quit()_ because driver was not loaded!

The only solution I found is to found manually where is this "tmp" folder and create script to clean up it automatically.
