### ISSUE TITLE
[🐛 Bug]: until ExpectedConditions not working with Chrome 117+Selenium4.*+Java11

### ISSUE THREAD

**Issue by msharma2020** [SeleniumHQ/selenium#12911] opened 2023-10-10 07:45 UTC
### What happened?

My Chrome browser recently got updated to Chrome 117.0.5938.150 and dynamic wait i was using stopped working.

My application under test is divided into three Frames, Top Frame, Left Frame and Right Frame. When my web application navigates from one page to another the default control goes to Left Frame, so i was using this line of code frequently to handle it dynamically until Chrome Version 114 and it was working fine with Selenium 4.9.0
WebElement myDynamicElement = (new WebDriverWait(driver, 30)).until(ExpectedConditions.presenceOfElementLocated(By.name("frameMenu")));

However, after upgrade to Chrome 117. The above line of code was not waiting as expected and infact it kept on waiting until 30 seconds in all cases.
Then i made this change.

WebElement myDynamicElement2 = (new WebDriverWait(driver,**Duration.ofSeconds(10)**)).until(ExpectedConditions.presenceOfElementLocated(By.name("frameMenu")));

But result was same, it kept waiting until 30 seconds and then thrown exception.

I tried this as well, but same result.
WebDriverWait wait = new WebDriverWait(driver,Duration.ofSeconds(10));
wait.until(ExpectedConditions.presenceOfElementLocated(By.name("frameMenu")));

Would really appreciate if this can be looked upon.

Selenium 4.9.0
Java 11
Chrome 117.0.5938.150
ChromeDriver 117.0.5938.149

### How can we reproduce the issue?

```shell
Can not share complete code.
WebElement myDynamicElement2 = (new WebDriverWait(driver,Duration.ofSeconds(10))).until(ExpectedConditions.presenceOfElementLocated(By.name("frameMenu")));
```

### Relevant log output

```shell
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting ChromeDriver 117.0.5938.149 (e3344ddefa12e60436fa28c81cf207c1afb4d0a9-refs/branch-heads/5938@{#1539}) on port 21853
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Oct 10, 2023 12:11:28 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find CDP implementation matching 117
Oct 10, 2023 12:11:28 PM org.openqa.selenium.chromium.ChromiumDriver lambda$new$3
WARNING: Unable to find version of CDP to use for . You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.9.0` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.
Exception in thread "main" org.openqa.selenium.TimeoutException: Expected condition failed: waiting for presence of element located by: By.name: frameMenu (tried for 10 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:87)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
	at IntegralILDynamicWaitReTest.main(IntegralILDynamicWaitReTest.java:53)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"*[name='frameMenu']"}
  (Session info: chrome=117.0.5938.150)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [4cd768cf2b23ef82d5ab07e7836e1202, findElement {using=name, value=frameMenu}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 117.0.5938.150, chrome: {chromedriverVersion: 117.0.5938.149 (e3344ddefa1..., userDataDir: C:\Users\MSHARM~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50353}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:50353/devtoo..., se:cdpVersion: 117.0.5938.150, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 4cd768cf2b23ef82d5ab07e7836e1202
	at jdk.internal.reflect.GeneratedConstructorAccessor7.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:193)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:183)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:174)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:171)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	... 1 more
```

### Operating System

Windows 10

### Selenium version

Java 4.9.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 117.0.5938.150

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 117.0.5938.149

### Are you using Selenium Grid?

No

**Comment by pujagani** [comment] 2023-10-11 11:52
Can you please try the latest version of Selenium? 
I have tried running a test that uses `ExpectedConditions.presenceOfElementLocated` with Chrome 117 and it works as expected. The error might be specific to your use case based on the exception logged, Selenium seems to be doing the right thing.

**Comment by pujagani** [comment] 2023-10-11 11:53
We will need a reproducible code example to triage this further.

**Comment by diemol** [comment] 2023-11-24 15:45
I will close this as we did not get more information from the OP. We can reopen it in case more information is provided.

**Closed as not planned by diemol** 2023-11-24 15:45 UTC
Labels: I-defect, J-issue-template
