### ISSUE TITLE
perform() and reset_actions() in ActionChains not working selenium python

### ISSUE THREAD

**Issue by sushen** [SeleniumHQ/selenium#9505] opened 2021-05-22 03:16 UTC
## 🐛 Bug Report

perform() and reset_actions() in ActionChains not working

In that video, I explain more preciously

https://www.youtube.com/watch?v=_jR9IldgacQ

code link: https://github.com/sushen/MiracleExperiments/blob/master/tabeNavigation.py

## To Reproduce

```



import os
import time
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
import random


global chrome_options
chrome_options = Options()
chrome_options.add_argument("--start-maximized")
chrome_options.add_argument('--profile-directory=Default')
prefs = {"profile.default_content_setting_values.notifications": 2}
chrome_options.add_experimental_option("prefs", prefs)
chrome_options.add_argument('disable-infobars')
chrome_options.add_experimental_option("useAutomationExtension", False)
chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])

google_search = [
    "1.' driver.switch_to.active_element' ",
    "2.this code is a one of important snippet for facebook automation.",
]

random_google_search = random.choice(google_search)


global driver
driver = webdriver.Chrome("chromedriver.exe", chrome_options=chrome_options)


global actions
actions = ActionChains(driver)

driver.get("https://google.com")

actions.send_keys(random_profile_post)   




def navigation():
    time.sleep(5)
    actions.reset_actions()

    driver.get("https://google.com")

    actions.send_keys(random_profile_post)

    total_tab = 3
    sleep_time = 1
    implicitly_wait_time = 4

    actions.reset_actions()
    driver.implicitly_wait(implicitly_wait_time)
    time.sleep(sleep_time)

    for i in range(total_tab):
        actions.send_keys(Keys.TAB)
        print("Pressing * " + str(i + 1) + " * No Tab")

    actions.send_keys(Keys.ENTER)
    actions.perform()


for i in range(10):
    navigation()
    print("Pressing * " + str(i + 1) + " * st navigation function")

```
## Environment

OS: Windows 10
Browser:  Chrome  
Browser version: 90.0.4430.212 
Browser Driver version: ChromeDriver 91.0.4472.19
Language Bindings version: Python 3.9

**Comment by bayilyas** [comment] 2021-05-23 15:49
Duplicate of [#6837](https://github.com/SeleniumHQ/selenium/issues/6837).

**Comment by diemol** [comment] 2021-05-24 17:55
Thanks for pointing that out, @bayilyas!

Indeed, @sushen, you are using Selenium [`3.141.0`](https://github.com/sushen/MiracleExperiments/blob/master/requirements.txt#L24), please try with `beta-3`, and if you find any issues, provide the updated code and we will be happy to have a look.

**Closed as completed by diemol** 2021-05-24 17:55 UTC
