### ISSUE TITLE
Python (and thus Java Standalone Server) thinks it cannot go back and forward in Safari

### ISSUE THREAD

**Issue by uchuugaka** [SeleniumHQ/selenium#1243] opened 2015-11-12 06:01 UTC
Python (and thus Java Standalone Server) thinks it cannot go back and forward in Safari.
calling driver.back() or driver.forward() generates an exception with a the message:
selenium.common.exceptions.WebDriverException: Message: Yikes! Safari history navigation does not work. We can go forward or back, but once we do, we can no longer communicate with the page... (WARNING: The server did not provide any stacktrace information)

This is absurd.
The very JavaScript history.back() and history.forward() work just fine.
They work so fine, that they work from driver.execute_script() with either
>>> sg.driver.execute_script('history.forward()')
>>> sg.driver.execute_script('history.back()') 

Should be reasonable to implement.

**Comment by jleyba** [comment] 2015-11-12 17:56
See https://code.google.com/p/selenium/issues/detail?id=3771

The SafariDriver no longer has a maintainer with the Selenium project so this is likely not to be fixed. If you think "this is absurd", feel free to send a patch. This is open source after all.

**Comment by uchuugaka** [comment] 2015-11-12 19:53
Interesting. 
A change will get submitted. 
Is there a list of maintainers?

So you're saying the issue should be with the SafariDriver extension itself and not the Java bindings?
If so that should simplify it a bit. 
Question is do all issues belong with the driver or bindings?

**Comment by jleyba** [comment] 2015-11-12 20:54
> Is there a list of maintainers?

For changes to the Selenium project (which has the SafariDriver), just open a pull request and someone will get around to reviewing it.

> do all issues belong with the driver or bindings?

It depends on the issue. If the issue reproduces with multiple language clients (e.g. ruby and python), then it's probably an issue with the driver implementation. Most issues these days are with the driver and not the client.

**Comment by lukeis** [comment] 2016-09-23 20:14
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.

**Closed by lukeis** 2016-09-23 20:14 UTC
Labels: A-needs new owner, D-safari
