### ISSUE TITLE
SendKeys using incorrect key value for UK layouts

### ISSUE THREAD

**Issue by Tom-Hudson** [SeleniumHQ/selenium#5051] opened 2017-11-13 09:06 UTC
## Meta
**Selenium Version:** v3.6.0 (JS Bindings)
**OS:** Windows 10 (64-bit)
**Chrome:** v61.0.3163.100 (64-bit)
**ChromeDriver:** v2.33
**Firefox :** v56.0.2 (64-bit)
**GeckoDriver:** v0.19.0
**Internet Explorer:** v11.674.15063.0 (64-bit)
**IEDriver:** v3.5.1
**Selenium Standalone Server:** v3.6.0
**Protractor:** v5.2.0
**Node:** v7.10.1

## Expected Behavior
Using `element.sendKeys('@')` should trigger the `keyDown` event with the `event.key` value of '@'.

## Actual Behavior
Using `element.sendKeys('@')` triggers the `keyDown` event with the `event.key` value of '~'.

## Steps to reproduce

1. Windows 10, go to `Settings > Region & Language`
2. Add English (United Kingdom) and set it as the default keyboard layout
3. Perform `sendKeys('@')` on an input/text area which console logs the event
4. Inspect the `event.key` value in the browser

> It is worth mentioning that the `event.keyCode` value is correct, and if I set my keyboard layout to 'English (United States)', then the correct `event.key` value is seen. I raised this issue off the back of a ticket I raised against [angular2-mentions](https://github.com/dmacfarlane/angular2-mentions/issues/53), in which I was unable to trigger the mention behaviour with a Protractor test due to `sendKeys` triggering the keyDown event with the wrong key value.

**Comment by p0deje** [comment] 2017-11-14 07:57
Duplicate of #4523

**Closed by p0deje** 2017-11-14 07:57 UTC
