### ISSUE TITLE
selenium IDE could not be verified for use in Firefox and has been disabled

### ISSUE THREAD

**Issue by tusharpawar77** [SeleniumHQ/selenium#1400] opened 2015-12-21 21:02 UTC
Hi,

I am not able to start test which uses firefox. I logs I found error - org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 

When I checked in firefox Selenium IDE 2.9.0 is disabled with message - selenium IDE could not be verified for use in Firefox and has been disabled

Please let me know How we can resolve this issue.

Thanks & regards,
Tushar

**Comment by crazygoji1** [comment] 2015-12-21 21:35
We just rolled back to Firefox 42 to enable selenium IDE and then turned off updates.  Not the solution I want to go with but people need to be able to do their jobs.

**Comment by tusharpawar77** [comment] 2015-12-21 21:55
Thanks for the solution..

**Comment by lukeis** [comment] 2015-12-21 22:43
duplicate of #1399 (and many others)

**Closed by lukeis** 2015-12-21 22:43 UTC
