### ISSUE TITLE
Not able to send data through nodeConfig.json

### ISSUE THREAD

**Issue by wolfy027** [SeleniumHQ/selenium#3409] opened 2017-01-24 15:12 UTC
## Meta -
OS:  

Selenium Version:  
3.0.1
Browser:  
All

Browser Version:  

## Steps to reproduce -
{
  "capabilities":
  [
    {
      "browserName": "firefox",
      "maxInstances": 0,
      "seleniumProtocol": "WebDriver"
    },
    {
      "browserName": "chrome",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver"
    },
    {
      "browserName": "internet explorer",
      "maxInstances": 0,
      "seleniumProtocol": "WebDriver"
    }
  ],
  "proxy": "com.selenium.security.GenericRemoteProxy",
  "maxSession": 5,
  "port": 5555,
  "register": true,
  "registerCycle": 60000,
  "hub": "http://localhost:4444",
  "nodeStatusCheckTimeout": 5000,
  "nodePolling": 5000,
  "role": "node",
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2,
  "debug": false,
  "servlets" : ["com.selenium.servlet.node.NodeShutDownServlet"],
  "withoutServlets": [],
  "custom"	: {
		 "extraConfig": {
      "testMachine": {
        "ipAddress": "localhost",
        "hostName": "jtjohny",
        "macAddress": "A4-17-31-65-0B-77",
        "platform": "win10"
      },
      "webDriverArray": [
        {
          "excelPropertyIID": "ERS_RESKIN",
          "moduleIID": "ERS_RESKIN",
          "isActive" : true,
          "driverConfig": {
            "webDriverPlatform": "DESKTOP",
            "driverPath": "setup\\driver\\chromedriver.exe",
            "acceptSSLCerts": true,
            "browserName": "chrome",
            "webDriverType": "CHROME_DRIVER",
            "isDeleteCookies": true,
            "isDisableAllPlugins": true,
            "hubURL": "http://localhost:4444/wd/hub",
            "testPlatform": "CHROME"
          }
        }
      ]
    }
}  	
 
}

--That is my nodeConfig.json being passed as -nodeConfig parameter to GridLauncherV3.Main(args)
The problem is that i am not able to send data inside custom object which i need my hub server end code to detect and process the request. The exception is as follows:-

org.openqa.grid.common.exception.GridConfigurationException: Error with the JSON of the config : java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT
	at org.openqa.grid.internal.utils.configuration.GridNodeConfiguration.loadFromJSON(GridNodeConfiguration.java:311)
	at org.openqa.grid.internal.utils.configuration.GridNodeConfiguration.loadFromJSON(GridNodeConfiguration.java:287)
	at org.openqa.grid.selenium.GridLauncherV3$3.setConfiguration(GridLauncherV3.java:261)
	at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:147)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:73)
	at com.selenium.client.TestClientLauncher.main(TestClientLauncher.java:28)

How can i send extra data through from the node to hub end?

**Comment by wolfy027** [comment] 2017-01-24 15:14
The following is the gist file for more clarity on this matter :

https://gist.github.com/anonymous/5a557c4cf557f0150c1d56c4d3552aaa

**Comment by mach6** [comment] 2017-01-24 20:45
```
org.openqa.grid.common.exception.GridConfigurationException: Error with the JSON of the config : java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT
```

This exception is because the `custom` property is not of the correct type in the JSON provided.  The `gist` in your follow on comment fixed this. When I used the JSON in the gist, I do not get a parsing error. Rather, I get an error on the hub `java.security.InvalidParameterException: Error: com.selenium.security.GenericRemoteProxy` which I expect since this is your custom proxy.

**Comment by mach6** [comment] 2017-01-24 20:55
In general, passing all of the `extraConfig` below to the hub with the node's registration request is not supported in Selenium 3. The `extraConfig` is parsed but not stored in memory or passed to the hub. This is a behavioral change from Selenium 2.

```json
    "extraConfig": {
        "testMachine": {
            "ipAddress": "localhost",
            "hostName": "jtjohny",
            "macAddress": "A4-17-31-65-0B-77",
            "platform": "win10"
        },
        "webDriverArray": [{
            "excelPropertyIID": "ERS_RESKIN",
            "moduleIID": "ERS_RESKIN",
            "isActive": true,
            "driverConfig": {
                "webDriverPlatform": "DESKTOP",
                "driverPath": "setup\\driver\\chromedriver.exe",
                "acceptSSLCerts": true,
                "browserName": "chrome",
                "webDriverType": "CHROME_DRIVER",
                "isDeleteCookies": true,
                "isDisableAllPlugins": true,
                "hubURL": "http://localhost:4444/wd/hub",
                "testPlatform": "CHROME"
            }
        }]
    }
```

**Comment by diemol** [comment] 2020-04-07 15:36
Closing as per this is the expected behavior, as said by the last commment.

**Closed by diemol** 2020-04-07 15:36 UTC
Labels: C-grid
