### ISSUE TITLE
[🐛 Bug]: significant performance and memory usage - regressions when switching from Selenium 3 to 4

### ISSUE THREAD

**Issue by christophs78** [SeleniumHQ/selenium#10113] opened 2021-12-04 21:39 UTC
### What happened?

PrimeFaces comes with a suite of integrationstest: https://github.com/primefaces/primefaces/tree/master/primefaces-integration-tests

We currently use Selenium 3.141.59. When i run them on my dev-machine (8C/16T, 32 GB RAM) it looks like this:
![image](https://user-images.githubusercontent.com/10461942/144725101-ff311199-9057-4a6b-a4dc-afb24a9c3cbd.png)

With https://github.com/primefaces/primefaces/pull/8145 we try to upgrade to Selenium 4.1.0. There it looks like this:
![image](https://user-images.githubusercontent.com/10461942/144725218-5703a332-610b-43c5-b0e0-a1c3fcd75ea7.png)

Additional my notebook get´s unresponsive.

We also run this integrationtests on Github actions. They take about twice the time with Selenium 4.1.0. (And we run into some follow-up problems probably because of worse performance due to resource starvation.)

There already has been a (to some degree) similar issue: https://github.com/SeleniumHQ/selenium/issues/9536

### How can we reproduce the issue?

See PrimeFaces-Github-links above.

### Relevant log output

Selenium 4.1.0:
https://github.com/primefaces/primefaces/actions/runs/1539682360

Compare this with a run on 3.141.59:
https://github.com/primefaces/primefaces/runs/4413396941?check_suite_focus=true

### Operating System

Windows 10, Ubuntu 20.04.3

### Selenium version

Java 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 96.0.4664.45, Firefox 94.0.2

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 96.0.4664.45, GeckoDriver 0.30.0

### Are you using Selenium Grid?

No

**Comment by christophs78** [comment] 2021-12-05 08:51
Maybe this issue is somehow related to parallelism / concurrency.
We use `junit.jupiter.execution.parallel.enabled=true` to create one thread / browser instance per hardware-thread. This worked very well with Selenium 3.x. (--> on my dev-machine 16 threads)
Is it possible Selenium 4.1.0 has some issues in this area?

**Comment by cocorossello** [comment] 2021-12-14 09:10
I think this is related to https://github.com/SeleniumHQ/selenium/issues/9359

A workaround is also provided in the issue

**Comment by christophs78** [comment] 2021-12-14 20:30
> I think this is related to #9359
> 
> A workaround is also provided in the issue

Played around with this for one and a half hour. Yes it´s the same issue, but the workaround does not work.
I also checked out https://github.com/titusfortner/bug9359 and tried it on my machine. I reduced his settings from 12 to 2. It does not matter which values are returned by our JUnit5-CustomStrategy-impl.

Ah. It depends on the Java-version. The work-around does not work for Java 8, but it works for Java 11.
Update: It´s also (at least partial) broken for Java 17. (reproduceable with https://github.com/titusfortner/bug9359)

IMO https://github.com/SeleniumHQ/selenium/issues/9359 needs to be reopened.

**Comment by titusfortner** [comment] 2021-12-26 05:15
Well, looks like everyone now has to use Java 11.

I'm dismayed to be able to duplicate your findings.

I'll close this one and re-open that one. :-/

**Comment by pujagani** [comment] 2021-12-31 10:19
@christophs78 Thank you for your findings and effort in solving this! I am sorry the earlier fix was not the perfect fix for this problem. 
https://github.com/junit-team/junit5/issues/1858#issuecomment-1003008244 Mentions that the potential problem lies due to https://github.com/SeleniumHQ/selenium/blob/28070d2de242978beff7f5ffa0c54fbe805df401/java/src/org/openqa/selenium/remote/service/DriverService.java#L67 That change was made to support Junit 5, which now based on your findings works only for Java 11 unfortunately. Apologies that it does not work for all versions.
It was made since https://github.com/SeleniumHQ/selenium/blob/28070d2de242978beff7f5ffa0c54fbe805df401/java/src/org/openqa/selenium/remote/service/DriverService.java#L204 by default uses a ForkJoinPool, and that seemed to be the problem so we switched it to use a fixed thread pool. 
Based on your findings, what do you think is primarily causing the problem? Any suggestions on how we can tackle it?

Thank you!

**Comment by christophs78** [comment] 2021-12-31 16:29
@pujagani Thank´s for your reply. To be honest i currently have no good idea how to fix this within Selenium.
My personal feeling (being a senior java-dev, but not having extensive experience with async on java) is nested thread-pools (ForkJoinPool used buy JUnit 5 and ThreadPoolExecutor used by Selenium 4) is not the best idea. Maybe even OpenJDK is not perfect in this constellation.
I´d liked to play around a bit with Selenium - source and trying ideas, but IntelliJ-Bazel-plugin does not support IntelliJ 2021.3 yet. Maybe i can come back on this in a few weeks.
So I´ll try to do some sandbox-test´s with a sandbox-project where i try to reproduce the ThreadPoolExecutor nested within a ForkJoinPool and come back afterwards.
(Maybe you already saw https://github.com/junit-team/junit5/pull/2805 as an idea how to tackle this issue from the other side. I´ll also look what the JUnit - team thinks about this.)

**Comment by titusfortner** [comment] 2021-12-31 16:42
@christophs78 thanks again for your help with tracking this down.

Fwiw, JetBrains Toolbox makes it really simple to downgrade a minor version to something that supports Bazel. Also, if you can join us on the Selenium chat (IRC or Slack)— https://www.selenium.dev/support/#ChatRoom
Devs hang out in #selenium-tlc chat room, and we'd love to collaborate with you as best we can.

**Comment by christophs78** [comment] 2022-01-01 08:02
Thanks for offering your collaboration. I´ll come back as soon as i have good questions to ask. 

My efforts to reproduce this issue with a sandbox plain-java-project have not been successful yet. At least i understand some previous conversation regarding `ForkJoinPool` and implementing our own `ParallelExecutionConfiguration`, `ParallelExecutionConfigurationStrategy` makes sense.

So i tested https://github.com/titusfortner/bug9359 with each Java-version starting with 13. It work´s up to Java 16 and is broken with Java 17. (I´ll keep Java 8 aside for now. With Java 17 it is broken for Hotspot and J9.) 
Next stop is to look what was modified in OpenJDK regarding concurrency between 16 and 17.

**Comment by christophs78** [comment] 2022-01-01 08:24
Changes within `java.util.concurrent` for Java 17: https://github.com/openjdk/jdk/commits/jdk-17-ga/src/java.base/share/classes/java/util/concurrent
Java 16 was released on 19 Jan 2021. 8 commits between Java 16 GA and Java 17 GA.

https://github.com/openjdk/jdk/commit/5b7b18c5bff575d2e94c5eadb14fcf1400e15d36#diff-85448900741ca0f6d70b61cb62d38bbbd49b015f78c4efa67ea8cdc3ae15e9f4 and https://github.com/openjdk/jdk/commit/5cfa8c94d6765b93f910fc01cd1ac2a56b16d78a#diff-e398beb49cd8d3e6c2f3a8ca8eee97172c57d7f88f3ccd8a3c704632cab32f5f did some sgnificant changes to `ForkJoinPool`.

Any thought´s about this?

Maybe it´s a regression in Java 17. Would help to have a plain Java reproducer for this. If we are able to reproduce this with plain Java we may reach out to the OpenJDK-team.

**Comment by christophs78** [comment] 2022-01-01 11:15
Side-note regarding Java 8: ForkJoinPool does not have a constructor to define things like maxPoolSize. This enhanced constructor was introduced with Java 9. - - > We propably can't fix this issue for Java 8.

**Comment by christophs78** [comment] 2022-01-01 22:03
Java 17 - issue - reproducer: https://github.com/christophs78/ForkJoinPoolReproducer
Any idea how to approach the OpenJDK-team with this? https://bugs.openjdk.java.net/secure/Dashboard.jspa is readonly
(https://dev.karakun.com/rico/2021/02/22/openjdk-bug-tracker.html -> https://bugreport.java.com/bugreport/)

**Comment by cocorossello** [comment] 2022-01-01 22:29
Hi, I'm not really sure if it does solve the selenium problem, but it does solve the reproducer test in JDK11 and 17...
https://github.com/christophs78/ForkJoinPoolReproducer/pull/1

Taken from https://stackoverflow.com/questions/69768534/why-does-java-17-throw-a-rejectedexecutionexception-when-adding-tasks-to-a-forkj

**Comment by titusfortner** [comment] 2022-01-02 00:34
Since we're discussing it here, I'll leave it open, and close the other one. :)

**Comment by titusfortner** [comment] 2022-01-02 00:37
Do I have this right?

Java 8 isn't going to work; need to stick with JUnit 4 or Selenium 3.
Java 9 - 16 work with the approach that was outlined earlier.
Java 17 broke something, but fix needs to be made in the Java code and we just have to figure out how to get them to do that.

All in all this isn't as bad as I feared. The Java 8 thing sucks, but I think there are more 9-16 folks than 17 folks still.

**Comment by christophs78** [comment] 2022-01-02 08:15
> Hi, I'm not really sure if it does solve the selenium problem, but it does solve the reproducer test in JDK11 and 17... [christophs78/ForkJoinPoolReproducer#1](https://github.com/christophs78/ForkJoinPoolReproducer/pull/1)
> 
> Taken from https://stackoverflow.com/questions/69768534/why-does-java-17-throw-a-rejectedexecutionexception-when-adding-tasks-to-a-forkj

Excellent point! 

I´m able to confirm this fixes the issue.

Did following within `org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService`:

```
private ForkJoinPool createForkJoinPool(ParallelExecutionConfiguration configuration) {
	ForkJoinWorkerThreadFactory threadFactory = new WorkerThreadFactory();
	return Try.call(() -> {
		// Try to use constructor available in Java >= 9
		Constructor<ForkJoinPool> constructor = ForkJoinPool.class.getDeclaredConstructor(Integer.TYPE,
			ForkJoinWorkerThreadFactory.class, UncaughtExceptionHandler.class, Boolean.TYPE, Integer.TYPE,
			Integer.TYPE, Integer.TYPE, Predicate.class, Long.TYPE, TimeUnit.class);
		Predicate<? super ForkJoinPool> predicateSaturate = pool -> true;
		return constructor.newInstance(configuration.getParallelism(), threadFactory, null, false,
			configuration.getCorePoolSize(), configuration.getMaxPoolSize(), configuration.getMinimumRunnable(),
			predicateSaturate, configuration.getKeepAliveSeconds(), TimeUnit.SECONDS);
	}).orElseTry(() -> {
		// Fallback for Java 8
		return new ForkJoinPool(configuration.getParallelism(), threadFactory, null, false);
	}).getOrThrow(cause -> new JUnitException("Failed to create ForkJoinPool", cause));
}
```

So i'll try to do a proper JUnit 5 PR.

**Comment by christophs78** [comment] 2022-01-02 09:21
There´s already https://github.com/junit-team/junit5/issues/2787 and https://github.com/junit-team/junit5/pull/2792 covering this. -> We just have to wait for JUnit 5.9.

**Comment by pujagani** [comment] 2022-01-05 03:28
Thank you @christophs78  for digging into this so well. Appreciate the efforts :)

**Comment by tkumar18** [comment] 2022-02-01 15:33
Hello @christophs78 Do we have any workaround for Java 17 or need to wait for Junit 5.9?

**Comment by christophs78** [comment] 2022-02-01 17:01
> Hello @christophs78 Do we have any workaround for Java 17 or need to wait for Junit 5.9?

No good workaround. Disabling ParallelExecution, using Java 11 instead of 17....

**Comment by tkumar18** [comment] 2022-02-02 09:10
@christophs78 I noticed for Java 17, if we keep getMinimumRunnable as 0 in the Custom Strategy it works fine and there is no issue. Can you please check once?

@Override
    public ParallelExecutionConfiguration createConfiguration(ConfigurationParameters arg0) {
        return this;
    }
 
    @Override
    public int getCorePoolSize() {
        return 5;
    }
 
    @Override
    public int getKeepAliveSeconds() {
        return 30;
    }
 
    @Override
    public int getMaxPoolSize() {
        return 5;
    }
 
    @Override
    public int getMinimumRunnable() {
        return 0;
    }
 
    @Override
    public int getParallelism() {
        return 5;
    }

**Comment by christophs78** [comment] 2022-02-02 13:29
@tkumar18 : Excellent point! I´m able to confirm this helps.

**Comment by tkumar18** [comment] 2022-02-02 16:19
@christophs78 Thanks for the confirmation. Will still need to wait for 5.9 though.

**Comment by ramaboddupally** [comment] 2022-02-11 15:03
@tkumar18 @christophs78  can you please confirm if this issue resolved, what is the work around for now.

**Comment by christophs78** [comment] 2022-02-12 10:07
https://github.com/primefaces/primefaces/blob/master/primefaces-integration-tests/src/test/java/org/primefaces/integrationtests/JUnit5Selenium4Strategy.java
works for Java 11 and 17

**Comment by titusfortner** [comment] 2022-02-12 14:48
@christophs78 what will change with JUnit 5.9?

And thanks again for your work on this.

**Comment by christophs78** [comment] 2022-02-12 17:49
Since @tkumar18 figured out returning 0 for `getMinimumRunnable()` makes Java 17 happy, there are IMO no more major reasons to wait for JUnit 5.9.
JUnit 5.9 (as far as we know know) will still require to provide a project-specific implementation of `ParallelExecutionConfiguration` and `ParallelExecutionConfigurationStrategy`. JUnit 5.9 will allow to set `saturate` to false via ParallelExecutionConfiguration. This is an alternative to minimumRunnable = 0.

**Comment by titusfortner** [comment] 2022-02-12 19:29
Excellent. I'll close this issue then if we're not expecting any additional functionality. Thanks everyone for your assistance getting this sorted.

**Closed as completed by titusfortner** 2022-02-12 19:29 UTC
Labels: C-java, I-defect
