### ISSUE TITLE
Python driver : régression when upgrading from 2.52.0 to 3.0.1 with accept_untrusted_certs

### ISSUE THREAD

**Issue by bamthomas** [SeleniumHQ/selenium#3116] opened 2016-11-16 11:28 UTC
## Meta -
OS:  ubuntu 16.04 / Python 3.5.2
Selenium Version:  
3.0.1
Browser:  
Firefox 
Browser Version:  
45-ESR with geckodriver (v0.11.1)

## Expected Behavior -
Accessing https://mysite with self signed certificate

## Actual Behavior -
"Secure Connection Failed" error message

## Steps to reproduce -
    $ pip3 install selenium==2.52.0
    Successfully installed selenium-2.52.0
    $ ipython
    In [1]: from selenium import webdriver
    In [2]: profile = selenium.webdriver.firefox.firefox_profile.FirefoxProfile()
    In [3]: firefox_binary=selenium.webdriver.firefox.firefox_binary.FirefoxBinary("%s/applications/firefox-45-ESR/firefox" % os.environ['HOME'])
    In [4]: profile.accept_untrusted_certs = True
    In [5]: driver = webdriver.Firefox(firefox_binary=firefox_binary, firefox_profile=profile)
    In [6]: driver.get('https://cacert.org/')
    In [7]: driver.title
    Out[8]: 'Bienvenue à CAcert.org'
    ^D
    $ pip3 install --upgrade selenium
    Collecting selenium
      Using cached selenium-3.0.1-py2.py3-none-any.whl
    Installing collected packages: selenium
      Found existing installation: selenium 2.52.0
        Uninstalling selenium-2.52.0:
          Successfully uninstalled selenium-2.52.0
    Successfully installed selenium-3.0.1
    $ ipython
    In [1]: from selenium import webdriver
    In [2]: profile = selenium.webdriver.firefox.firefox_profile.FirefoxProfile()
    In [3]: firefox_binary=selenium.webdriver.firefox.firefox_binary.FirefoxBinary("%s/applications/firefox-45-ESR/firefox" % os.environ['HOME'])
    In [4]: profile.accept_untrusted_certs = True
    In [5]: driver = webdriver.Firefox(firefox_binary=firefox_binary, firefox_profile=profile)
    In [6]: driver.get('https://cacert.org/')
    ---------------------------------------------------------------------------
    WebDriverException                        Traceback (most recent call last)
    <ipython-input-10-69a69bc299e6> in <module>()
    ----> 1 driver.get('https://cacert.org/')
    
    /home/dev/pouet/src/python/venv/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py in get(self, url)
        246         Loads a web page in the current browser session.
        247         """
    --> 248         self.execute(Command.GET, {'url': url})
        249 
        250     @property
    
    /home/dev/pouet/src/python/venv/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py in execute(self, driver_command, params)
        234         response = self.command_executor.execute(driver_command, params)
        235         if response:
    --> 236             self.error_handler.check_response(response)
        237             response['value'] = self._unwrap_value(
        238                 response.get('value', None))
    
    /home/dev/pouet/src/python/venv/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py in check_response(self, response)
        190         elif exception_class == UnexpectedAlertPresentException and 'alert' in value:
        191             raise exception_class(message, screen, stacktrace, value['alert'].get('text')) 
    --> 192         raise exception_class(message, screen, stacktrace)
        193 
        194     def _value_or_default(self, obj, key, default):

    WebDriverException: Message: Error loading page

**Comment by AutomatedTester** [comment] 2016-11-16 13:22
duplicate of #3106

**Closed by AutomatedTester** 2016-11-16 13:22 UTC
