### ISSUE TITLE
Using an existing Firefox profile Ruby gem 'selenium-webdriver', '~> 3.0'

### ISSUE THREAD

**Issue by gabayliran** [SeleniumHQ/selenium#2968] opened 2016-10-19 16:36 UTC
I keep getting an error when I try to use my current firefox profile with `Ruby gem 'selenium-webdriver', '~> 3.0'`.

profile folder’s location:

    ~/.mozilla/firefox/ld771b1q.default-1476574579695/

Profiles.ini file:

```
   ~/.mozilla/firefox/profiles.ini
    [General]
    StartWithLastProfile=1
```
    
    [Profile0]
    Name=default-1476574579695
    IsRelative=1
    Path=ld771b1q.default-1476574579695

My code:

`default_profile = Selenium::WebDriver::Firefox::Profile.from_name "default-1476574579695"`
`default_profile.native_events = true`
 `@driver = Selenium::WebDriver.for(:firefox, :profile => default_profile)`

Error:

`/var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/remote/w3c_bridge.rb:80:in initialize': unknown option: {:profile=>#<Selenium::WebDriver::Firefox::Profile:0x00000003712b88 @model="/home/user/.mozilla/firefox/ld771b1q.default-1476574579695", @native_events=true, @secure_ssl=false, @untrusted_issuer=true, @load_no_focus_lib=false, @additional_prefs={}, @extensions={}>} (ArgumentError`
        
[documentation][1]

Is it related to the issue below ?
`https://github.com/SeleniumHQ/selenium/issues/2933`
[https://github.com/SeleniumHQ/selenium/issues/2933](url)

Thanks!

  [1]: https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings#using-an-existing-profile

**Comment by titusfortner** [comment] 2016-10-19 16:39
Yes, duplicate of #2933; it's being worked on. Thanks.

**Closed by titusfortner** 2016-10-19 16:39 UTC

**Comment by gabayliran** [comment] 2016-10-19 16:43
thank you @titusfortner
