### ISSUE TITLE
 drag and drop doesn't work for Html5's but works for Jquery's in chrome or firefox 

### ISSUE THREAD

**Issue by virtualnode** [SeleniumHQ/selenium#6262] opened 2018-08-09 02:13 UTC
## Meta -
OS:  
Windows 10
Selenium Version:  robotframework-seleniumlibrary 3.0.1

Browser:  
  Firefox,Chrome
Browser Version:  
Firefox 56.0, Chrome 68.0.3440.106 (64-bit)

## Expected Behavior -
Drag and Drop works
## Actual Behavior -
Doesn't work for this html5 drag and drop.
## Steps to reproduce -
Attached Txt file for Html5 source as the object to be tested.
Please removed the last ".txt" when try it.

And Robot Framework Test script as below:
`*** Settings ***
Library		SeleniumLibrary
Suite Setup		Open Browser	about:blank	${BROWSER} 
...				Maximize Browser Window
Suite Teardown	Sleep 	5s
...				Close Browser

*** Variables ***
${url1}		http://demo/exp/drag.html
${BROWSER}	ff

*** Test Cases ***
Drag and drop 1	
	Go To 	${url1}
	Drag And Drop	//img	css:div#div1
	sleep 	1s`
[drag.html.txt](https://github.com/SeleniumHQ/selenium/files/2272595/drag.html.txt)

**Comment by barancev** [comment] 2018-08-09 09:49
Duplicate of #1365

**Closed by barancev** 2018-08-09 09:49 UTC
