### ISSUE TITLE
[🐛 Bug]: Maven cucumber reporting stopped working on update to Selenium 4.14.1 from Selenium 4.13.0

### ISSUE THREAD

**Issue by SeleniumNinja** [SeleniumHQ/selenium#13072] opened 2023-10-31 12:04 UTC
### What happened?

After update to selenium 4.14.1 from selenium 4.13.0 cucumber reporting masterthought maven-cucumber-reporting stopped generating reports with a use of maven command: mvn verify -Dcucumber.filter.tags=@desktop. On selenium 4.13.0 everything was fine.

In target folder /jsonReport both files are empty:

```
cucumber-report.html
cucumber-report.json
```

This is test runner class

```
import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;
import org.junit.runner.RunWith;
```

```
@RunWith(Cucumber.class)
@CucumberOptions(features="src/test/java/features",
        plugin = {"pretty", "json:target/jsonReports/cucumber-report.json",
                "html:target/jsonReports/cucumber-report.html"},
        glue= {"stepDefs"},
        stepNotifications = true,
        monochrome = true
        )
public class TestRunner {
}
```

I am using in POM

```
<dependency>
    <groupId>net.masterthought</groupId>
    <artifactId>maven-cucumber-reporting</artifactId>
    <version>5.7.6</version>
</dependency>
```

### How can we reproduce the issue?

```shell
take a look at what I wrote
```

### Relevant log output

```shell
cucumber-report.html
cucumber-report.json
should not be empty
```

### Operating System

Windows 10

### Selenium version

4.14.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 118

### What are the browser driver(s) and version(s) where you see this issue?

chrome driver 118

### Are you using Selenium Grid?

4.14.1

**Comment by diemol** [comment] 2023-10-31 12:15
Duplicate of #13063 

Check with the owner of the project https://github.com/damianszczepanik/maven-cucumber-reporting

**Closed as not planned by diemol** 2023-10-31 12:15 UTC
Labels: I-defect, A-needs-triaging
