### ISSUE TITLE
Selenium doesnt work 

### ISSUE THREAD

**Issue by cdobarcomaxam** [SeleniumHQ/selenium#4819] opened 2017-10-06 10:56 UTC
I tried to luanch the plugin for firefox 56 and it doesnt work at all. I´ve got the following error:

There was an unexpected error. Msg: TypeError: obj is undefined
Url: chrome://implicit-wait/content/implicit-wait-ide.js?1507287259542, line: 185, column: 9
wrap@chrome://implicit-wait/content/implicit-wait-ide.js?1507287259542:185:9
ImplicitWait/<@chrome://implicit-wait/content/implicit-wait-ide.js?1507287259542:27:9

Thanks,
Carlos.

## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by barancev** [comment] 2017-10-06 13:54
Duplicate of #4406

**Closed by barancev** 2017-10-06 13:54 UTC
