### ISSUE TITLE
IEDriverServer 3.7.0 & 3.8.0 - not possible to enter "@" (email) symbol

### ISSUE THREAD

**Issue by sergmal** [SeleniumHQ/selenium#5176] opened 2017-12-06 09:36 UTC
## Meta -
OS:  Windows 7 64bit

Selenium Version:  3.8.0 **C#**
IEDriverServer 3.8.0 64bit
Webdriver 3.8.0

Browser:  IE 

Browser Version:  11.0.9600.18837 64bit

## Expected Behavior - 
string contains @ symbol (test@test.com)
## Actual Behavior - 
string contains "2" instead of "@" symbol (test2test.com)
## Steps to reproduce -

driver.FindElement(By.Id("somelocator")).SendKeys("test@test.com");

NOTE: Ran same test with IEDriverServer 3.4.0 and there was no such issue

**Comment by p0deje** [comment] 2017-12-07 06:41
Can it be related to #4523?

**Comment by barancev** [comment] 2017-12-07 07:45
Yes, it must be a duplicate of #4523

**Closed by barancev** 2017-12-07 07:45 UTC
Labels: D-IE
