### ISSUE TITLE
IEDriver - getWindowHandles doesn't return handle of newly opened window when protected mode is off

### ISSUE THREAD

**Issue by pradip79** [SeleniumHQ/selenium#1273] opened 2015-11-18 10:01 UTC
Getting this weird problem where after opening the new winow driver.getWindowHandles() returns only 1 handle when protected mode is OFF. Same code works fine when protected mode is ON for all the security zones and returns 2 handles. Not expecting this behavior as we are not ignoring the protected mode setting and keeping it same for all zones. Even IEDriver log indicates "Has Valid Protected Mode Settings: 1" for both the cases. Thanks.
[IEDriverLog_ProtectedModeOff.txt](https://github.com/SeleniumHQ/selenium/files/37707/IEDriverLog_ProtectedModeOff.txt)
[IEDriverLog_ProtectedModeOn.txt](https://github.com/SeleniumHQ/selenium/files/37708/IEDriverLog_ProtectedModeOn.txt)

**Comment by Venkatabalaji90** [comment] 2018-01-11 06:04
Facing the same issue with IE window handles. Not able to get the actual 2 windows instead returing ony 1.
Has the issue resolved?

**Comment by barancev** [comment] 2019-07-14 18:57
Is this issue still actual?

**Comment by Hypnosphi** [comment] 2019-08-25 12:48
@barancev yes, I encounter it on IE8 using `@wdio/cli@5.12.4` npm package

**Comment by diemol** [comment] 2019-08-25 17:57
@Hypnosphi then please report the issue to https://github.com/webdriverio/webdriverio.
Having said that, I will close this one since no reproduction scenario was provided. If the issue is still actual, feel free to open a new one and fill out the whole template.

**Closed by diemol** 2019-08-25 17:57 UTC
Labels: D-IE, R-awaiting answer
