### ISSUE TITLE
Firefox 47.0 and Selenium 2.53.0 seem incompatible

### ISSUE THREAD

**Issue by gopz** [SeleniumHQ/selenium#2258] opened 2016-06-10 13:37 UTC
OS:  OSX
Selenium Version:  2.53.0
Browser:  Firefox
Browser Version: 47.0

Running tests with `rspec` and `selenium` crash firefox with following errors: 

```
Process:               firefox-bin [12045]
Path:                  /Applications/Firefox.app/Contents/MacOS/firefox-bin
Identifier:            org.mozilla.firefox
Version:               47.0 (4716.6.4)
Code Type:             X86-64 (Native)
Parent Process:        ruby [12043]
Responsible:           iTerm2 [229]
User ID:               501

Date/Time:             2016-06-10 09:35:19.249 -0400
OS Version:            Mac OS X 10.11.5 (15F34)
Report Version:        11
Anonymous UUID:        38892878-A3C9-C611-78BB-E6E7950B35F3

Sleep/Wake UUID:       F3C1EB60-3597-47E4-A001-85B1A63D1C42

Time Awake Since Boot: 64000 seconds
Time Since Wake:       1100 seconds

System Integrity Protection: enabled

Crashed Thread:        7  Socket Thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000040
```

**Comment by davehunt** [comment] 2016-06-10 13:46
Another duplicate of #2110

**Closed by davehunt** 2016-06-10 13:46 UTC
