### ISSUE TITLE
Get status code (200/400 etc) for chrome headless [Ruby]

### ISSUE THREAD

**Issue by rusikf** [SeleniumHQ/selenium#4976] opened 2017-10-30 09:16 UTC
## Meta -
OS:  
Ubuntu 17.10
Browser:  
Chrome

There is no ability to get status code for selenium chrome. ( Ruby ) Is it possible or planned?

**Comment by lmtierney** [comment] 2017-10-30 13:23
This will not be implemented.

Duplicate of #3873

**Closed by lmtierney** 2017-10-30 13:23 UTC
