### ISSUE TITLE
[geckodriver] UnknownCommandError: POST /session/{sessionId}/moveto did not match a known command

### ISSUE THREAD

**Issue by zenonwch** [SeleniumHQ/selenium#4181] opened 2017-06-14 12:57 UTC
## Meta -
OS:  
Windows7, Mac OS Sierra 10.12.5
Selenium Version:  
js binding selenium-webdriver@3.4.0
Browser:  
Firefox 54.0
Driverr:
Geckodriver@1.7.0

## Expected Behavior -
No error. Mouse pointer should be moved to an element.

## Actual Behavior -
(node:14196) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): UnknownCommandError: POST /session/b19beeda-ee16-48f7-b6d4-f3e8ab51e4a9/moveto did not match a known command
(node:14196) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Steps to reproduce -
driver.actions()
            .mouseMove(driver.findElement(wd.By.css('.{className}')))
            .perform()

**Comment by AutomatedTester** [comment] 2017-06-14 13:46
duplicate of #3808

**Closed by AutomatedTester** 2017-06-14 13:46 UTC

**Comment by zenonwch** [comment] 2017-06-14 15:29
@AutomatedTester why is it duplicate of https://github.com/SeleniumHQ/selenium/issues/3808? 
My issue doesn't relate to grid.

**Comment by lmtierney** [comment] 2017-06-14 15:42
Actually a duplicate of #3693

**Comment by jpope19** [comment] 2018-05-17 18:20
Not a duplicate. Did you just pick random issues out of a hat?

**Comment by barancev** [comment] 2018-05-17 18:25
@jpope19 Do you have any reason to hijack an issue closed a year ago with no additional information?

**Comment by jpope19** [comment] 2018-05-17 18:32
I'm coming across the same issue as @zenonwch and read through the "related" issues and it ended up just being a waste of 20 minutes. I'm new to the node.js library for selenium. I'm submitting a form and testing the redirect to a new page. Any suggestions?

`   let email = await driver.findElement(By.id('email')).sendKeys('un');
    let pw = await driver.findElement(By.id('pass')).sendKeys('pw');
    let form = await driver.findElement(By.id('login_form'));
    await form.submit();`

**Comment by barancev** [comment] 2018-05-17 18:44
@jpope19 Please open a new issue, and provide information about selenium library version, driver version, and a reproduction scenario.
