### ISSUE TITLE
RemoteWebDriver not opening session with 4.0.0-rc2 in C#

### ISSUE THREAD

**Issue by seanhaydongriffin** [SeleniumHQ/selenium#9891] opened 2021-10-07 13:55 UTC
## 🐛 Bug Report

When I execute a new RemoteWebDriver in C# against a Selenium 4 server for RC 2 running locally on the same computer the call does not resolve (is stuck) until the timeout occurs (default of 60 seconds) and the following C# exception is thrown ...

```
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:4444/session timed out after 60 seconds. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
```

## To Reproduce

Within a project in **Visual Studio Professional 2015** (other versions untested) ensure the NuGet package **Selenium.WebDriver v4.0.0-rc2** is installed (**Install-Package Selenium.WebDriver -Version 4.0.0-rc2**) and the **Target framework** of the project is **.NET Framework 4.7**.

Create a program with the following code ...

```
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium;
```

```
ChromeOptions options = new ChromeOptions();
IWebDriver driver = new RemoteWebDriver(new Uri("http://localhost:4444"), options.ToCapabilities());
```

Ensure the Selenium server **selenium-server-4.0.0-rc-2.jar** exists on the computer (**https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.0.0-rc-2/selenium-server-4.0.0-rc-2.jar**).  Ensure java is installed (version **1.8.0_231** tested).

Start the Selenium server with the following command in a CLI ...

```
"<path to java>\java.exe" -Xmx128m -jar <path to selenium server>\selenium-server-4.0.0-rc-2.jar standalone
```

Ensure Selenium Server has successfully started by observing the message...

```
Started Selenium Standalone 4.0.0-rc-2 ... http://<local computer address>:4444
```

Run the program above in Debug mode in Visual Studio.  Execution of the **new RemoteWebDriver** call above will become stuck for 60 seconds after which time the program will exit (throw an exception) as follows ...

```
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:4444/session timed out after 60 seconds. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.<MakeHttpRequest>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
...
```

No output (connection) message is logged in the Selenium Server process running (above) and no Chrome browser is started.

I have repeated the same test with the following combinations:

- NuGet package 4.0.0-rc1 and Selenium Server 4.0.0-rc1
- NuGet package 4.0.0-alpha7 and Selenium Server 4.0.0 Alpha 7

An existing issue with similar symptoms is as follows...

https://github.com/SeleniumHQ/docker-selenium/issues/1109

## Expected behavior

The "new RemoteWebDriver" instruction in the code snippet above executes within a timely manner and returns a valid IWebDriver instance.

I have however successfully performed a new webdriver request against the same Selenium Server 4.0.0-rc2 via the following cUrl command ...

```
curl -H "Accept: application/json" -H "Content-Type:application/json; charset=utf-8" -X POST -d "{\"desiredCapabilities\":{\"browserName\":\"chrome\"}}" http://localhost:4444/session
```

Chrome browser is started and the Selenium Server responds correctly with ...

```
16:12:01.897 INFO [LocalDistributor.newSession] - Session request received by the distributor:
 [Capabilities {browserName: chrome}]
Starting ChromeDriver 83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}) on port 4944
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
16:12:05.016 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
16:12:05.031 INFO [LocalDistributor.newSession] - Session created by the distributor. Id: f05e25afe7a7ab2c43a58a65465eeed1, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 83.0.4103.97, chrome: {chromedriverVersion: 83.0.4103.39 (ccbf011cb2d2b..., userDataDir: C:\Users\sgriffin\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:8210}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://10.1.1.102:4444/sessio..., se:cdpVersion: 83.0.4103.97, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
```

This seems to indicate that my computer is able to make a HTTP request to the same Selenium Server process outside Visual Studio / C#.

Rolling back the v4.0.0-rc2 NuGet package with the latest stable v3.0.1 package in Visual Studio, and running the Selenium Server Standalone v3.141.59 (selenium-server-standalone-3.141.59.jar) instead of v4.0.0-rc2 is also successful (the IWebDriver instance is returned by the "new RemoteWebDriver" call in C# immediately with no timeout).

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 83.0.4103.97
Browser Driver version: ChromeDriver 83.0.4103.39
Language Bindings version: C# 4.0.0-rc2 
Selenium Grid version (if applicable): 4.0.0-rc2

**Comment by jimevans** [comment] 2021-10-07 16:04
@seanhaydongriffin What happens if you target, say, .NET 5 instead of .NET Framework 4.7? I'm not suggesting this as a fix or workaround, but it's a further data point that would be useful to know.

**Comment by jimevans** [comment] 2021-10-07 21:43
Duplicate of #9277

**Closed as completed by jimevans** 2021-10-07 21:43 UTC
Labels: A-needs-triaging
