### ISSUE TITLE
OpenQA.Selenium.ElementNotVisibleException : element not interactable while clicking in C#

### ISSUE THREAD

**Issue by pgaria** [SeleniumHQ/selenium#6565] opened 2018-10-22 13:21 UTC
OS: Windows 10
Selenium Version: 3.14.0
Browser: Chrome
ChromeDriver : 2.42.0.1

There is a very strange behavior for the C# bindings while trying to click on an element. **I tried the same with java bindings and everything is working smooth and fine with same selector.**

In C# I am getting the following exception while clicking an element:
`Message: OpenQA.Selenium.ElementNotVisibleException : element not interactable
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.14393 x86_64)`

The element looks like below as I can not provide the URl as its an internal project and can not be accessed.
```
<span class="cell indicator-container" style="width:18px;">
<span title="Click to add to basket" class="indicator basket" style=""></span>
</span>
```

I am using this xpath : //div[@data-offset='0']//span[@title='Click to add to basket']

**Not sure what is special here in C# binding and not able to click the element as the element is visable and I can click the element using the Java script (IJavaScriptExecutor) directly**

Expected Behavior -
Element should be clicked 

Actual Behavior -
Exception for the visiblity of the element.
OpenQA.Selenium.ElementNotVisibleException

Steps to reproduce -
Trying to simple click on the element. Please have a look at the Screenshot for the Html as Url can not be accessed from outside.
![click-issue-with-webdriver](https://user-images.githubusercontent.com/4025540/47294643-fbaae500-d60d-11e8-8b68-1f07018750c9.PNG)

**Comment by barancev** [comment] 2018-11-06 05:38
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment] 2018-11-06 05:47
Duplicate of #6566

**Closed by barancev** 2018-11-06 05:47 UTC
Labels: R-awaiting answer
