### ISSUE TITLE
System went to deadlock while using sendKeys for text fields. 

### ISSUE THREAD

**Issue by MrRahulR** [SeleniumHQ/selenium#4733] opened 2017-09-21 07:18 UTC
## Meta -
OS: 
Windows 7
Selenium Version:  
3.4.0 & 3.5.3
Browser:  
Internet Explorer, Google Chrome
Browser Version:  
IE 11 (64-bit), Chrome 56.0 (64-bit)

## Expected Behavior -
SendKeys command should type the value in the field and should move ahead. 
## Actual Behavior -
SendKeys typing the value in the same field continuously. The script went to deadlock as the sendkeys is repeated for the same text field.
## Steps to reproduce -
This issue isn't coming frequently but when it's coming it's making the script in deadlock. 
I'm using the Selenium Standalone Server (3.4.0) with the Java for current automation script. It's the private site on the local server I'm working on automation. I faced sometimes the sendkeys command is repeating only for the same fields continuously. I tried same with Selenium Standalone Server (3.5.3) as well but the things remain same for that as well. 

I'm posting the IE driver logs from the script where you can find about the script repetition on the same field. I'm attaching the video for same as well for more reference. 

Driver Logs : [ieLogs.txt](https://github.com/SeleniumHQ/selenium/files/1320273/ieLogs.txt)
Issue Video : [sel3.5.3.zip](https://github.com/SeleniumHQ/selenium/files/1320264/sel3.5.3.zip)

**Comment by p0deje** [comment] 2017-09-21 09:26
There are multiple tests for sendKeys command passing both for IE and Chrome. I looked at logs and video and can't understand what's going on there. I see it types 10, but then something clears the input. What clears this input?

**Comment by MrRahulR** [comment] 2017-09-21 10:03
I added a 'Type' method instead of SendKeys there. It clears the previous input and enters the new value. 
I'm using the same method in my framework since past 3 years but never had this problem. 
 ```
      /**
	 * Clears and type new value into given text-box.
	 *  @param Web
	 *            Element Locator of element.
	 * @param value
	 *            New text/value.
	 */
	public static void type(WebElement webElement, String value) {
		webElement.clear();
		webElement.sendKeys(value);
	}
```

I also filtered the logs to the particular case where my test is hanging. Check the text file. You'll find the locator is repeating there. 

[ieLogs_filtered.txt](https://github.com/SeleniumHQ/selenium/files/1320740/ieLogs_filtered.txt)

**Comment by jimevans** [comment] 2017-09-21 11:34
I agree that the calls to `clear()` and `sendKeys()` are being repeated. That’s obvious from the logs. What’s causing your `type()` method to get called multiple times? We need more context from your code to be able to figure out what’s happening.

**Comment by MrRahulR** [comment] 2017-09-21 13:54
@jimevans I hope attached code snippets would help you. 
In the file part-i is the actual code which is running and part-ii is the common methods I'm using while running that code. The failure most frequently happening at 

`Common.type(txtPlannedNoOfCranes, cranesNr);`

when I try to run the type method. 

Thanks, 

[sel_issue.txt](https://github.com/SeleniumHQ/selenium/files/1321426/sel_issue.txt)

**Comment by p0deje** [comment] 2017-09-22 09:53
I still can't understand what's causing `type()` to be executed multiple times. Is it called only once and something else causes repeating clear/sendKeys commands?

Is there any way for you to extract a piece of code into a script that we can run by ourselves to reproduce the problem?

**Comment by MrRahulR** [comment] 2017-09-25 05:10
@p0deje I'm afraid I could not share the project or code here as this is the private project, also if I would share the code with you, the application is used on the local server so you won't run the code as well from there. 

If you've any other way to set up the code, please update me.

**Comment by p0deje** [comment] 2017-09-25 10:30
I'm not sure what else can be done here without a test script to reproduce. @jimevans do you see anything interesting in logs or the code attached?

**Comment by barancev** [comment] 2017-10-10 18:30
Closing the issue as there is no reproduction scenario provided. Seems to be an issue in the client code, not Selenium.

**Closed by barancev** 2017-10-10 18:30 UTC
Labels: D-chrome, D-IE, R-awaiting answer
