### ISSUE TITLE
[🐛 Bug]: Getting exceptions for elements that are valid on the website itself

### ISSUE THREAD

**Issue by orbar1** [SeleniumHQ/selenium#11134] opened 2022-10-16 09:36 UTC
Solved

**Comment by titusfortner** [comment] 2022-10-17 14:56
1. What version of Selenium are you using?
2. What is the Selenium error being thrown. The stack trace provided is the message from the chromedriver back to Selenium. There is more information that is being provided. Perhaps not rescuing this error and giving us the native response would be more useful.

**Comment by orbar1** [comment] 2022-10-17 15:16
> 1. What version of Selenium are you using?
> 2. What is the Selenium error being thrown. The stack trace provided is the message from the chromedriver back to Selenium. There is more information that is being provided. Perhaps not rescuing this error and giving us the native response would be more useful.

tbh im not sure what version i used but installed again selenium 4.5.0, as for the error, I couldn't catch it, tried a few extra slenium exceptions with no luck, ill try again with the newer selenium version and will update if it presists.

**Comment by titusfortner** [comment] 2022-10-17 15:44
If you don't rescue any exception the resulting information is likely what we'll need. The issue is likely a bug in chromedriver and/or a race condition in your code. We can't narrow that down without more information.

**Comment by orbar1** [comment] 2022-10-17 15:48
> If you don't rescue any exception the resulting information is likely what we'll need. The issue is likely a bug in chromedriver and/or a race condition in your code. We can't narrow that down without more information.

yea as soon as you asked for selenium version i realised i might have used a relatively old version with some sort of a bug but I just upgraded to the newest one so I will test again.
Thanks mate.

p.s I couldn't handle the exception for some reason but ill try anyway see if i still get errors, if so, ill update.

**Comment by orbar1** [comment] 2022-10-17 20:05
Solved.

**Comment by titusfortner** [comment] 2022-10-18 02:31
I just noticed your code includes `undetected_chromedriver` to get around Reddit's terms of service, so we can't help you with your use case. I'm closing because this is not a bug in Selenium.

**Closed as completed by titusfortner** 2022-10-18 02:31 UTC
Labels: J-awaiting answer, C-py, I-defect
