### ISSUE TITLE
Firefox unable to bind to locking port

### ISSUE THREAD

**Issue by remcowesterhoud** [SeleniumHQ/selenium#1993] opened 2016-04-20 10:22 UTC
## Meta -
OS: Windows Server 2012 R2
Selenium Version: 2.53.0
Browser: Firefox
Browser Version: 45.0.2

Using Selenium Grid and running on Python.

When I start multiple (5) firefox webdrivers at once it throws an WebdriverException. I use Behave as a runner for these tests. However Behave has no support for parallel running (yet), so I've made my own script for this. This will start up to 5 tests by executing a separate command for each of them.

## Expected Behavior -
5 firefox browsers get opened and start executing the tests.

## Actual Behavior -
A WebdriverException gets thrown.
```
selenium.common.exceptions.WebDriverException: Message: Unable to bind to locking port 7054 within 45000 ms
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'WIN-C9MAHQ7GST9', ip: '10.10.200.110', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_65'
Driver info: driver.version: FirefoxDriver
Stacktrace:
    at org.openqa.selenium.internal.SocketLock.lock (SocketLock.java:99)
    at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start (NewProfileExtensionConnection.java:80)
    at org.openqa.selenium.firefox.FirefoxDriver.startClient (FirefoxDriver.java:271)
    at org.openqa.selenium.remote.RemoteWebDriver.<init> (RemoteWebDriver.java:119)
    at org.openqa.selenium.firefox.FirefoxDriver.<init> (FirefoxDriver.java:218)
    at org.openqa.selenium.firefox.FirefoxDriver.<init> (FirefoxDriver.java:211)
    at org.openqa.selenium.firefox.FirefoxDriver.<init> (FirefoxDriver.java:129)
    at sun.reflect.GeneratedConstructorAccessor23.newInstance (None:-1)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (None:-1)
    at java.lang.reflect.Constructor.newInstance (None:-1)
    at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor (FirefoxDriverProvider.java:91)
    at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance (FirefoxDriverProvider.java:68)
    at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance (DefaultDriverFactory.java:60)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call (DefaultSession.java:222)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call (DefaultSession.java:1)
    at java.util.concurrent.FutureTask.run (None:-1)
    at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (None:-1)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (None:-1)
    at java.lang.Thread.run (None:-1)
```
## Steps to reproduce -

Open a bunch of firefox drivers (might be more than 5, I'm thinking my server is too slow too handle 5) all at the same time.

**Comment by remcowesterhoud** [comment] 2016-04-20 12:28
I've downgraded my Firefox to 44.0.2 in a hope to fix this. This changed the exception to:
selenium.common.exceptions.WebDriverException: Message: Unable to connect to host 127.0.0.1 on port 7056 after 45000 ms

**Comment by csnathan** [comment] 2016-05-18 07:28
Hi,

I am also facing similar troubles opening firefox. I am using Firefox 46.0.1 with Selenium 2.53 and running my code from my local using intellij. 

It would be great if someone can show some light on what I am missing.

Thanks!

**Comment by lukeis** [comment] 2016-07-12 02:24
closing as a duplicate of #1915

**Closed by lukeis** 2016-07-12 02:24 UTC
