### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by jorisdas** [SeleniumHQ/selenium#12535] opened 2023-08-11 08:26 UTC
### What happened?

Selenium Manager unable to download ChromeDriver and CFT when upgraded to selenium-java 4.11.0

### How can we reproduce the issue?

```shell
UPdate to Selenium-java 4.11.0 and try to run a script.
```

### Relevant log output

```shell
nested exception is org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: []}}, error Command failed with code: 65, executed: [C:\Users\username\AppData\Local\Temp\1\selenium-manager41857485287009149476778253955822\selenium-manager.exe, --browser, chrome, --output, json]
request or response body error: error reading a body from connection: stream error received: not a result of an error
```

### Operating System

Windows 10

### Selenium version

selenium-java 4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome v115

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver v115

### Are you using Selenium Grid?

no

**Comment by diemol** [comment] 2023-08-11 08:31
I cannot reproduce the same error.

Are you behind a proxy?

**Comment by jorisdas** [comment] 2023-08-11 09:00
will proxy make a difference now?
Its working fine till selenium-java 4.10.0 where my current chrome browser version is 115 and selenium manager is downloading Chromedriver 114.0.5735.90 from https://chromedriver.chromium.org/downloads.
Problem started with selenium-java 4.11.0

**Comment by jorisdas** [comment] 2023-08-11 09:06
I guess Selenium manager is unable to download Chromedriver and CFT from the new dashboard.

**Comment by diemol** [comment] 2023-08-11 09:18
The significant change in 4.11.0 is being able to use Chrome for Testing. The error you are getting seems to be a network issue, hence my question. 

@bonigarcia do you have another assumption of what the issue might be?

**Comment by bonigarcia** [comment] 2023-08-11 09:43
Indeed, as @diemol explained, as of Selenium 4.10.0, Selenium Manager could download up to chromedriver 114 (which uses different network endpoints). With Selenium 4.11.0, Selenium Manager can download chromedriver 115 using the new CfT endpoints, such as:

https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json

So I agree this seems to be a connectivity issue at your end, @jorisdas. Maybe you are behind some proxy or firewall which does not permit making network requests to the new JSON endpoints.

**Comment by jorisdas** [comment] 2023-08-11 10:17
Many Thanks @diemol , @bonigarcia for the quick response. Since the endpoints are changed internally from Selenium 4.11.0 to download the Chromedriver and cft from the new dashboard....it could be a network connectivity from my side.

just curious to understand what is the use of "selenium-manager.json" which is created by selenium manager in local cache ??
I am pasting the content of "selenium-manager.json" getting generated by Selenium 4.10.0 and Selenium 4.11.0....please let me know if this gives a clue so that i can go back to my organization and confirm them a network connectivity from our side..

Selenium 4.10.0
------------------
{
  "browsers": [
    {
      "browser_name": "chrome",
      "browser_version": "115",
      "browser_ttl": 1691745054
    }
  ],
  "drivers": [
    {
      "browser_version": "115",
      "driver_name": "chromedriver",
      "driver_version": "114.0.5735.90",
      "driver_ttl": 1691830364
    }
  ]
}


Selenium 4.11.0
------------------
{
  "browsers": [],
  "drivers": [
    {
      "major_browser_version": "115",
      "driver_name": "chromedriver",
      "driver_version": "115.0.5790.170",
      "driver_ttl": 1691751947
    }
  ]
}

**Comment by bonigarcia** [comment] 2023-08-11 10:31
This file contains the metadata, i.e., the versions discovered by Selenium Manager making network requests, and the time-to-live in which they are valid. I’m currently working on the Selenium Manager doc page to properly explain it.

**Comment by Anilkumar-Shrestha** [comment] 2023-08-16 22:06
I am getting below error while using running remote server using selenium 4.11.0 with chrome as 116 . DId anybody faced and got the issue solved ?  
```    
org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browserName: chrome, goog:chromeOptions: {args: [window-size=1440,900, --use-fake-device-for-media..., --allow-running-insecure-co..., --ignore-certificate-errors, -remote-allow-origins=*, --disable-dev-shm-usage, --no-sandbox, --headless=old, --use-fake-ui-for-media-stream], extensions: [], prefs: {download.default_directory: /usr/src/mymaven/src/test/d..., download.directory_upgrade: true, download.prompt_for_download: false, profile: {managed_default_content_settings: {media_stream: 1}}, profile.default_content_settings.popups: 0, safebrowsing.enabled: true}}}, error Command failed with code: 134, executed: [/tmp/selenium-manager50555212074870083088208847026452790/selenium-manager, --browser, chrome, --output, json]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/files.rs:65:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:25)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:13)
	at org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:99)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83) 
```

**Comment by bonigarcia** [comment] 2023-08-17 09:20
@Anilkumar-Shrestha Selenium Manager downloads the drivers (e.g., chromedriver) in the path `~/.cache/selenium` (equivalent to `%HomeDrive%%HomePath%/.cache/selenium` in Windows). That error happens when creating that folder by Selenium Manager, indicating that your script has no write permissions in your home folder.

The next Selenium Manager release will deliver a new feature to change the default cache path. 

For this release, I believe you need to grant your Selenium script to write in your home.

**Comment by Anilkumar-Shrestha** [comment] 2023-08-17 16:16
@bonigarcia  Thank you so much for pointing that.

**Comment by diemol** [comment] 2023-08-23 15:32
Closing this as questions and comments seem to be resolved.

**Closed as not planned by diemol** 2023-08-23 15:32 UTC
Labels: J-awaiting answer, I-defect

**Comment by harikrishnan1694** [comment] 2023-09-09 07:22
Hi everyone, long story short this ticket captures the entirety of the issue I am faced with.

I tried debugging the selenium-manager from PowerShell for iexplorer and chrome. While with chrome still facing the issue, I don't see any issues with iexplorer.

Please refer the screenshot. Hope this paints the picture of my issue. 

![image](https://github.com/SeleniumHQ/selenium/assets/34878995/885fcec1-00ee-4ec4-9060-80a7c4aac6b1)

Java Version -> 17

`	<dependencies>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.12.1</version>
		</dependency>
	</dependencies>`

Could someone help me narrowing down the issue?
