### ISSUE TITLE
unknown error: session deleted because of page crash from tab crashed with Selenium plugin on Jenkins

### ISSUE THREAD

**Issue by chanelsene** [SeleniumHQ/selenium#1079] opened 2015-09-25 22:58 UTC
Hello,

I'm experiencing issues using chromedriver with Selenium plugin on Jenkins. On my local machine, my tests run with no issues, but as soon I run them remotely, I get this error:

unknown error: session deleted because of page crash
from tab crashed
  (Session info: chrome=45.0.2454.101)
  (Driver info: chromedriver=2.19.346078 (6f1f0cde889532d48ce8242342d0b84f94b114a1),platform=Windows NT 6.2 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 3.81 seconds
Build info: version: '2.41.0', revision: '3192d8a', time: '2014-03-27 17:17:32'
System info: host: 'ECS-8ebd4f06', ip: '127.0.1.1', os.name: 'Windows 8', os.arch: 'x86', os.version: '6.2', java.version: '1.8.0_51'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\tmp}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=45.0.2454.101, platform=WIN8, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]

I have the latest of Selenium and Chrome and the driver but nothing.

Selenium 2.47
Chrome 45
ChromeDriver 2.19
Hub OS: Linux
Slave OS: Windows 7 or 8

I also tried to adjust timeouts but none of that helped either. An interesting thing is that, since it's through Jenkins, you can have a slave on the same server as the hub, and when that is the case, the tests run with no problem. And the same tests run in FF remotely with no problem.

I am at a loss here. Any help would be really appreciated.

Thank you!

**Comment by lukeis** [comment] 2015-09-25 23:10
This is more suited for a discussion on the selenium-users mailing list:
https://groups.google.com/forum/#!forum/selenium-users

Also, it if is a legitimate chromedriver issue, then I suggest logging it with the chromedriver project:
https://code.google.com/p/chromedriver/issues/list
With detailed steps on how to reproduce the issue.

It could also be an issue with the Jenkins plugin, you may want to log a bug with that too:
https://github.com/jenkinsci/selenium-plugin

Nothing suggests the issue is anything that can be fixed in this repo, so I'm going to close the issue here.

**Closed by lukeis** 2015-09-25 23:10 UTC
