### ISSUE TITLE
[🐛 Bug]: Could not start new session. Possible causes are invalid address of the remote server or browser start-up failure.

### ISSUE THREAD

**Issue by primejay24** [SeleniumHQ/selenium#11954] opened 2023-04-26 14:57 UTC
### What happened?

Used selenium code to automate edge in ie mode but it works fine untill RDP session active but once session inactive get above mentioned error .

### How can we reproduce the issue?

```shell
System.setProperty("webdriver.ie.driver", "IE Driver Path"); InternetExplorerOptions ieOptions = new InternetExplorerOptions();

ieOptions.attachToEdgeChrome ();

ieOptions.ignore ZoomSettings ();

ieOptions.withEdgeExecutable Path ("C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe");

driver = new InternetExplorerDriver (ieOptions);

driver.manage().deleteAllCookies();

driver.manage () .window () .maximize();

driver.get("https://www.finacle.com");
```

### Relevant log output

```shell
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: session not created exception
```

### Operating System

Windows 2019 

### Selenium version

4.2.2

### What are the browser(s) and version(s) where you see this issue?

IE11,Edge111

### What are the browser driver(s) and version(s) where you see this issue?

IEServerDriver 4.7.0

**Comment by diemol** [comment] 2023-04-26 15:03
Seems this is a duplicate of #10569, right @primejay24?

**Comment by primejay24** [comment] 2023-04-26 15:24
Seems like similar .

**Comment by diemol** [comment] 2023-04-26 15:32
OK, then please reach out to the Edge team. I will leave the links below. Thanks.

**Closed as completed** 2023-04-26 15:33 UTC
Labels: I-defect, G-msedgedriver
