### ISSUE TITLE
[🐛 Bug]: Error creating bean with name 'firefoxDriver' defined in class path resource

### ISSUE THREAD

**Issue by H-Lo** [SeleniumHQ/selenium#13904] opened 2024-05-03 14:30 UTC
### What happened?

Upgraded from 4.19.1 to 4.20.0 and now I'm getting an exception about FireFox web driver.
Previously everything was working fine.
I can see it's about a proxy, but I don't know what to do with it.

**OS:**
Windows 11 Pro 23H2
OS build 22631.3447
Windows Feature Experience Pack 1000.22688.1000.0

**IDE:**
Spring Tool Suite 4
Version: 4.22.0.RELEASE
Build Id: 202403071427

**Java:**
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

**Spring Boot:***
spring-boot-starter-parent
3.2.5

**Selenium:**
selenium-java
4.20.0

**Firefox web driver**

```
@WebdriverScopeBean
@ConditionalOnProperty(name = "browser", havingValue = "firefox")
@Primary
public WebDriver firefoxDriver() {
	final FirefoxOptions firefoxOptions = new FirefoxOptions();
	final Proxy proxy = new Proxy();
	proxy.setAutodetect(false);
	proxy.setNoProxy("no_proxy-var");
	firefoxOptions.setCapability("proxy", proxy);
	return new FirefoxDriver(firefoxOptions);
}
```

### How can we reproduce the issue?

```shell
Upgrade from 4.19.0 to 4.20.0 and try to run any unit test with given FireFox web driver configuration.
```

### Relevant log output

```shell
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'firefoxDriver' defined in class path resource [com/thevegcat/selenium/configuration/WebDriverConfig.class]: Failed to instantiate [org.openqa.selenium.WebDriver]: Factory method 'firefoxDriver' threw exception with message: Unable to obtain: geckodriver, error Command failed with code: 2, executed: [--browser, firefox, --proxy, --language-binding, java, --output, json]
error: a value is required for '--proxy <PROXY>' but none was supplied

Build info: version: '4.20.0', revision: '866c76ca80'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17'
Driver info: driver.version: FirefoxDriver
```

### Operating System

Windows 11

### Selenium version

4.20.0

### What are the browser(s) and version(s) where you see this issue?

FireFox

### What are the browser driver(s) and version(s) where you see this issue?

gecko but not initialized at all

### Are you using Selenium Grid?

No

**Comment by kora-rider** [comment] 2024-05-16 13:14
Hi, I have the same issue, but only different I am using MacOS Version 14.4.1 (23E224).

**Comment by krmahadevan** [comment] 2024-05-16 13:16
@kora-rider - Can you create a sample project that can be used to reproduce the problem and share it here? That will make it easier for us to figure out what is going wrong.

**Comment by kora-rider** [comment] 2024-05-22 09:00
@krmahadevan I tried some configuration and found out that I need to remove proxy settings. I had these settings for the Firefox driver:
`Proxy ffProxy = new Proxy();
ffProxy.setProxyType(Proxy.ProxyType.AUTODETECT);
ffOptions.setProxy(ffProxy);`

So when I removed these proxy settings then it worked well.

**Comment by pujagani** [comment] 2024-05-22 10:50
> @kora-rider - Can you create a sample project that can be used to reproduce the problem and share it here? That will make it easier for us to figure out what is going wrong.

+1 Please provide a complete reproducible test script/ sample project. I understand that something has worked in the interim but that is not ideal. Ideally, users should be able to set the proxy capability using the Proxy classes exposed by Selenium.

**Comment by diemol** [comment] 2024-07-12 08:24
I am closing this because we have yet to get more information.

**Closed as not planned by diemol** 2024-07-12 08:24 UTC
Labels: C-java, I-defect, J-issue-template, A-needs-triaging
