### ISSUE TITLE
[Issue] Wait for element clickable fail on safari Webdriver, MacOS Sierra

### ISSUE THREAD

**Issue by tathanhphu** [SeleniumHQ/selenium#3555] opened 2017-02-22 03:31 UTC
## Meta -
OS:  Mac Sierra (10.12.3)

Selenium Version:  Python3.6 
Browser:  Safari
Browser Version:  10.0.3 (64 bit)

## Expected Behavior -
The script (attached) should pass
## Actual Behavior -
Fail, at command element_to_be_clickable

## I wrote some logs in code and run it again, the log shows: -
driver_command: isElementDisplayed
params {'id': 'node-64681E7D-D268-429A-9C6F-9908A5D09250', 'sessionId': '7FE8FE61-805E-4B68-9EF5-2C7EA934A382'}
ERROR {'status': 404, 'value': ''}

## Steps to reproduce -
1. Update to MacOS Sierra and Safari 10
2. Install python 3.6
3. Install Python bindings: pip3.6 install -U selenium 
4. Run attached test script: python3.6 test.py
[test.py.zip](https://github.com/SeleniumHQ/selenium/files/792164/test.py.zip)

**Comment by lmtierney** [comment] 2017-02-26 03:39
Duplicate of #3506

**Closed by lmtierney** 2017-02-26 03:39 UTC

**Comment by tathanhphu** [comment] 2017-02-27 02:16
Thank you.

**Comment by MrDefinite** [comment] 2017-10-23 09:11
@tathanhphu Is your issue resolved?

I met a similar issue with code like, on Safari only:
```
WebDriverWait(driver, 20).until(
   EC.element_to_be_clickable((By.ID, buttonID))
)
```

It just cannot find any element.
