### ISSUE TITLE
Getting error msg when using internal java 11 client

### ISSUE THREAD

**Issue by csgbn** [SeleniumHQ/selenium#11589] opened 2023-01-23 23:05 UTC
### What happened?

Starting with java selenium client version 4.7.1 (also confirmed in 4.7.2 and 4.8.0), when using the built in java 11 client, getting this error message although the tests pass fine. There are no errors on the selenium grid side. This error does not exist when not using the internal java 11 client.

We are still troubleshooting but would appreciate any feedback at this point. The error msg for all browsers and tests (using Devtools or not).

### How can we reproduce the issue?

```shell
Using TestNG 7.7.1
Selenium grid distributed
Java 11 client

ClientConfig config = ClientConfig.defaultConfig().readTimeout(Duration.ofMinutes(3));
driver = RemoteWebDriver.builder().address(new URL(hub)).oneOf(options).config(config).build();

Note: we do not use the java 11 option on our selenium grid hub, nodes.
```

### Relevant log output

```shell
Jan 23, 2023 2:10:29 PM org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: java.util.concurrent.RejectedExecutionException: Task jdk.internal.net.http.common.SequentialScheduler$SchedulableTask@6f751b61 rejected from java.util.concurrent.ThreadPoolExecutor@752e0748[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 5]
java.io.IOException: java.util.concurrent.RejectedExecutionException: Task jdk.internal.net.http.common.SequentialScheduler$SchedulableTask@6f751b61 rejected from java.util.concurrent.ThreadPoolExecutor@752e0748[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 5]
	at java.net.http/jdk.internal.net.http.common.Utils.getIOException(Utils.java:306)
	at java.net.http/jdk.internal.net.http.RawChannelTube.read(RawChannelTube.java:306)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$ReceiveTask.run(TransportImpl.java:697)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$ReadEvent.handle(TransportImpl.java:762)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.checkEvents(RawChannelTube.java:174)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.onError(RawChannelTube.java:212)
	at java.net.http/jdk.internal.net.http.common.SSLTube$DelegateWrapper.onError(SSLTube.java:249)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.complete(SSLTube.java:433)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onErrorImpl(SSLTube.java:503)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onError(SSLTube.java:517)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(SubscriberWrapper.java:296)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(SubscriberWrapper.java:261)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.errorCommon(SubscriberWrapper.java:390)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.incomingCaller(SubscriberWrapper.java:409)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.onNext(SubscriberWrapper.java:358)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.onNext(SubscriberWrapper.java:59)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:844)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:763)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:941)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:245)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:968)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:923)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:923)
Caused by: java.util.concurrent.RejectedExecutionException: Task jdk.internal.net.http.common.SequentialScheduler$SchedulableTask@6f751b61 rejected from java.util.concurrent.ThreadPoolExecutor@752e0748[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 5]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:153)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:273)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:242)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.incoming(SSLFlowDelegate.java:298)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.incomingCaller(SubscriberWrapper.java:407)
	... 14 more
```

### Operating System

Windows, Linux

### Selenium version

Java 4.7.2, 4.8.0

### What are the browser(s) and version(s) where you see this issue?

Chrome, Edge, Firefox version 109

### What are the browser driver(s) and version(s) where you see this issue?

Gecko 0.32, Chrome 109.0.5414.74, Edge 109.0.1518.52

### Are you using Selenium Grid?

4.7.2, 4.8.0

**Comment by pujagani** [comment] 2023-01-24 05:47
Thank you for the details. Can you please help me understand "This error does not exist when not using the internal java 11 client."? Not sure what the difference is between "built-in java 11 client" and an "internal java 11 client". I think a reproducible complete test script might help so we can reproduce the issue and triage it further.

**Comment by krmahadevan** [comment] 2023-01-24 06:31
@pujagani - Maybe @csgbn is referring to the JDK client that is part of JDK11. The problem occurs only when using the JDK11 client and not when using the netty client perhaps ?

**Comment by csgbn** [comment] 2023-01-24 06:43
Yes, the issue occurs only when using the internal selenium client:

		<dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-http-jdk-client</artifactId>
      <version>4.8.0</version>
    </dependency>

Passed in with webdriver.http.factory system property.

**Comment by pujagani** [comment] 2023-01-24 07:30
Thank you so much for helping clarify the concern. I am running the latest Grid in standalone mode (without JDK 11 client) and using the example code below: 

```
 public static void main(String[] args) throws MalformedURLException, InterruptedException {

    System.setProperty("webdriver.http.factory", "jdk-http-client");
    ClientConfig config =  ClientConfig.defaultConfig().readTimeout(Duration.ofMinutes(30));
    WebDriver driver = RemoteWebDriver.builder()
      .oneOf(new ChromeOptions())
      .address("http://localhost:4444")
      .config(config)
      .build();

    driver.get("https://www.google.com/");

    driver.getTitle();

    driver.quit();
  }
```
I was unable to reproduce the issue. Can you please provide a reproducible test script or a project setup? It will help us triage and fix the root cause. Thank you!

**Comment by csgbn** [comment] 2023-01-24 18:23
We are running a distributed grid on AWS, dont see how we practically could set one up for you...

The issue is with the client, we can run the grid on 4.7.1, 4.7.2, 4.8.0 and the client on 4.7.0, no error, use client 4.7.1+ the error starts.

**Comment by krmahadevan** [comment] 2023-01-25 04:52
> We are running a distributed grid on AWS, dont see how we practically could set one up for you...
> 
> The issue is with the client, we can run the grid on 4.7.1, 4.7.2, 4.8.0 and the client on 4.7.0, no error, use client 4.7.1+ the error starts.

@csgbn - Can you please help share the following ?

* Details on how you have setup the distributed grid. Specifically we are looking at any config files, command line parameters that you may be using to spawn the distributed grid.
* The selenium jar version that you are using for running the distributed grid (I know you may have already provided, but just trying to ensure that we have all the information that we need)
* A sample test case, which if we run, we can for sure reproduce the problem.
* The selenium dependencies that you are using in your test code. We prefer if you could help share a simple maven/gradle project which we can just run against a grid, and recreate the issue.
* Also, if you spin off a grid (or) a distributed grid on your local machine and run your sample against it, does it still fail with the same errors (or) do you see this ONLY when you run against the Distributed grid setup in AWS.

**Comment by diemol** [comment] 2023-02-20 21:30
Closing as no more information was given.

**Closed as completed by diemol** 2023-02-20 21:30 UTC
Labels: C-java, I-defect, J-issue-template

**Comment by csgbn** [comment] 2023-04-27 15:51
So this warning message is now gone when we upgraded to use Java 17 on the client.
