### ISSUE TITLE
[🐛 Bug]: MS Edge Version 110.0.1587.63 does not work with Selenium.WebDriver 4.8.1

### ISSUE THREAD

**Issue by gkyx** [SeleniumHQ/selenium#11754] opened 2023-03-09 07:18 UTC
### What happened?

Microsoft Edge Version 110.0.1587.63 cannot be used with Selenium.WebDriver v4.8.1. Request to remote WebDriver server gets timed out.

### How can we reproduce the issue?

```shell
using OpenQA.Selenium.Edge;

namespace TAConsoleTrial
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var driver = new EdgeDriver();

            driver.Navigate().GoToUrl("https://selenium.dev");

            driver.Quit();
        }
    }
}
```

### Relevant log output

```shell
Exception thrown: 'OpenQA.Selenium.WebDriverException' in WebDriver.dll
An unhandled exception of type 'OpenQA.Selenium.WebDriverException' occurred in WebDriver.dll
The HTTP request to the remote WebDriver server for URL http://localhost:58445/session timed out after 60 seconds.
```

### Operating System

Windows 10 Version 21H2 (OS Build 19044.2604)

### Selenium version

CSharp 4.8.1

### What are the browser(s) and version(s) where you see this issue?

MS Edge Version 110.0.1587.63

### What are the browser driver(s) and version(s) where you see this issue?

Built-in Edge Driver

**Comment by diemol** [comment] 2023-03-13 10:08
@gkyx I cannot reproduce this with the mentioned versions. You say that it is not working with `4.8.1`. Was it working with a different version?

Can you provide a project in GitHub I can clone and run so I can see the same logs you see?

**Comment by diemol** [comment] 2023-04-25 08:18
Closing, we did not get more information.

**Closed as completed by diemol** 2023-04-25 08:18 UTC
Labels: J-awaiting answer
