### ISSUE TITLE
Webelement.Click() - Getting exception on Webelement.Click() though it clicks the Element

### ISSUE THREAD

**Issue by aniruddhyak** [SeleniumHQ/selenium#2844] opened 2016-09-28 17:22 UTC
## Meta

OS:  Windows
Selenium Version:  2.53.1.0 
IDE: Visual Studio 2013
Browser:  Internet Explorer 11 version 11.420

I am getting an exception when i tried to click an element on webpage. This happens when a link is clicked and it opens a dialog. Webelement.click() function clicks the element and the modal dialog is opened but Click() takes time to return and finally logs exception as '**The HTTP request to the remote WebDriver server for URL "" timed out after 60 seconds.'**
## Expected Behavior -

```
   It should click the "Firefox Beta" download button and "IE tool bar" with RUN and SAVE option will appear
```
## Actual Behavior -

It clicks the "Firefox Beta" download button and "IE tool bar" is coming. **But downloadElement.Click() waits for 60 seconds and throws exception**.
## Steps to reproduce -

**Below is code snippet:**
       string url = "**https://www.mozilla.org/en-US/firefox/channel/#beta**";
            try
            {
                IWebDriver driver = new InternetExplorerDriver();
                driver.Navigate().GoToUrl(url);  
                Thread.Sleep(5000);
                IWebElement downloadElement = driver.FindElement(By.XPath("//div[@id='download-   button-desktop-beta']/ul/li/a/strong"));  
                Thread.Sleep(5000);  
                downloadElement.Click();
            }
            catch{}

**Comment by maeriens** [comment] 2018-01-31 20:15
Sorry this is like a gazillion years old - but you have a typo in the xpath. You have an extra space between 'download-' and button. Right now the ID of such button was changed to `desktop-beta-download`.

As for why that is not working, is because the first `li`, the one you are pointing to, is not present in the page at all. That `li` is the downloader for Windows x64 one - so it may be hidden due to your OS or Browser.

 Checked with IE, FF and Chrome, and if you try to select it, it will fail. The proper xpath to the first `li` element that is visible is `//div[@id='desktop-beta-download']/ul/li[2]/a/strong`, which points to the `win_32` download. If you want a specific one to be downloaded, the element to click could be grabbed via css: `By.cssSelector('#desktop-beta-download .download-list .{os_you_want}')`

**Comment by p0deje** [comment] 2018-02-05 09:44
@maeriens Thank you for investigating the issue - I'll mark this as awaiting answer from reporter!

**Comment by barancev** [comment] 2018-02-25 16:45
Closing the issue as there is no reproduction scenario provided.

**Closed by barancev** 2018-02-25 16:45 UTC
Labels: D-IE, R-awaiting answer
