### ISSUE TITLE
When bad nodes accumulate, normal nodes don't work properly.

### ISSUE THREAD

**Issue by exabugs** [SeleniumHQ/selenium#3120] opened 2016-11-17 06:36 UTC
When bad nodes accumulate, normal node don't work properly.

![_2016-11-17_15_09_09](https://cloud.githubusercontent.com/assets/1234874/20378715/22dd206a-acdb-11e6-8bbf-349fed231965.png)

## Meta -
OS:  
 hub : OSX
 node : Win7 (IEDriverServer)
Selenium Version:  
 3.0.1
Browser:  
 IE
Browser Version:  
 8

**Comment by diemol** [comment] 2020-04-07 15:28
I am going to close this since not enough information was ever provided (how to reproduce, log files, etc...)

**Closed by diemol** 2020-04-07 15:28 UTC
Labels: C-grid
