### ISSUE TITLE
selenium.common.exceptions.WebDriverException:

### ISSUE THREAD

**Issue by jharrison12** [SeleniumHQ/selenium#2262] opened 2016-06-10 19:21 UTC
OS:  Windows 7

Selenium Version:  2.52.0

Browser:  Firefox

Browser Version:  47

**Expected Behavior -**
Python 3.5.1
Django 1.8.4

I'm currently learning TDD using django and python.  Yesterday, webdriver.Firefox() worked perfectly. Today whenever I try to open Firefox from webdriver, I receive the error message below (in Actual Behavior).  I'm also receiving a similar error in when running webdriver.Firefox() from IDLE.  

## Actual Behavior -

```
======================================================================
ERROR: test_can_start_a_list_and_retrieve_it_later (functional_tests.tests.NewVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python33\superlists\functional_tests\tests.py", line 10, in setUp
    self.browser = webdriver.Firefox()
  File "C:\Users\harrisonjd\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 81, in __init__
    self.binary, timeout)
  File "C:\Users\harrisonjd\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium\webdriver\firefox\extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "C:\Users\harrisonjd\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium\webdriver\firefox\firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "C:\Users\harrisonjd\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium\webdriver\firefox\firefox_binary.py", line 98, in _wait_until_connectable
    raise WebDriverException("The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.


----------------------------------------------------------------------
Ran 8 tests in 2.571s

FAILED (errors=1)
Creating test database for alias 'default'...
Destroying test database for alias 'default'...

```
And the IDLE traceback:

```
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    webdriver.Firefox()
  File "C:\Users\harrisonjd\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 81, in __init__
    self.binary, timeout)
  File "C:\Users\harrisonjd\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium\webdriver\firefox\extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "C:\Users\harrisonjd\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium\webdriver\firefox\firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "C:\Users\harrisonjd\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium\webdriver\firefox\firefox_binary.py", line 98, in _wait_until_connectable
    raise WebDriverException("The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

```

**Comment by AutomatedTester** [comment] 2016-06-10 19:22
Duplicate of #2110

**Closed by AutomatedTester** 2016-06-10 19:22 UTC

**Comment by tychovk** [comment] 2016-06-11 00:59
Same problem yes @AutomatedTester  - however, that bug is closed, meaning it's fixed, presumably? 

It doesn't seem fixed for me, at least..

**Comment by AutomatedTester** [comment] 2016-06-11 07:19
@tychovk the big green "open" in #2110 suggests to me that it is open and not closed...
