### ISSUE TITLE
Unable to set_preference('javascript.enabled', False)

### ISSUE THREAD

**Issue by 4rensiker** [SeleniumHQ/selenium#1288] opened 2015-11-19 20:50 UTC
When switching from one website to another, I encounter .on_exit() javascript stuff that I would like to avoid. **So the idea is to disable JS completely. But it is not possible using neither selenium 2.47.3 nor latest 2.48.0 and FF 41.0.1 resp. 42.0** The only thing I would like to do is capturing screenshots... 

    #!/usr/bin/python
    from selenium import webdriver

    profile = webdriver.FirefoxProfile()
    profile.set_preference('javascript.enabled', False)
    profile.update_preferences()

    browser = webdriver.Firefox(firefox_profile=profile)

    print browser.capabilities['javascriptEnabled']

    browser.quit()

The result of the script above should be: *false*, but is *true*  :(

Other javascript.options can be adjusted correctly. 

Why is it not possible to alter 'javascript.enabled'

**Comment by lukeis** [comment] 2015-11-19 20:59
duplicate of #635

**Closed by lukeis** 2015-11-19 20:59 UTC

**Comment by lukeis** [comment] 2015-11-19 21:04
as an alternative, you could execute some javascript to disable the beforeunload handlers. You may have to change it per site though, depending on how they implemented it.
