### ISSUE TITLE
Click is Not Getting Performed

### ISSUE THREAD

**Issue by TARIFABBAS** [SeleniumHQ/selenium#6193] opened 2018-07-23 11:04 UTC
## Meta -
OS: Windows 7

Selenium Version: Selenium 3.13

Browser: Internet Explorer

Browser Version: 11.0.9600.1908015 (64 Bit) and 10.0.9200.17609 (64 Bit)

Driver : IEDriverServer 3.12; IEDriverServer 3.13

## Expected Behavior -
Performing some steps on [this ](https://glip.com/hp_b5)url

## Actual Behavior -
While performing action, click is highlighting object but click action is not getting performed.

## Steps to reproduce -
Steps ::
1> open [This](https://glip.com/hp_b5)
2> Click on "Product"
3> Click on "Facebook link Icon" situated on the Bottom right corner on the page. (A  New Window Opens, Don't switch on this)
4> Click on "Pricing" // Here click is not getting performed if above window is on top, While clicking by javascript it is getting pass.

Please find below code to reproduce the problem::
````
DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
		capabilities.setCapability("native events", false);
		capabilities.setCapability("requireWindowFocus", true);
		capabilities.setCapability("ignoreProtectedModeSettings", true);
		capabilities.setCapability("unexpectedAlertBehaviour", "ignore");		 
  
 capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
		capabilities.setCapability("handlesAlerts", false);
```

		WebDriver driver = new InternetExplorerDriver(capabilities);

		driver.get("https://glip.com/hp_b5");
		System.out.println("Title is as :: " + driver.getTitle());

		// click on product
		driver.findElements(By.xpath("/html/body/div[2]/header/div/nav/ul/li[1]/a")).get(0).click();

		Thread.sleep(5000);

		// click on facebook
		// driver.findElements(By.xpath("/html/body/div[2]/footer/div/div[2]/ul/li[1]")).get(0).click();
		WebElement ele1 = driver.findElement(By.xpath("/html/body/div[2]/footer/div/div[2]/ul/li[1]"));
		new IECrashIssue2().scrollIntoView(ele1);
		ele1.click();

		Thread.sleep(5000);

		// click on pricing
		List<WebElement> ele = driver.findElements(By.xpath("/html/body/div[2]/header/div/nav/ul/li[2]/a"));
		System.out.println(ele.size());
// Action is not performed here, It is clicking by javascript
		ele.get(0).click();

		// JavascriptExecutor jse = (JavascriptExecutor) driver;
		// jse.executeScript("arguments[0].click();", ele.get(0));

		Thread.sleep(15000);
		driver.close();
		driver.quit();
	}

	public void scrollIntoView(WebElement ele) {
		System.out.println("scrollIntoView");
		try {
			((JavascriptExecutor) Finder.findWebDriver()).executeScript("arguments[0].scrollIntoView()", ele);
		} catch (Exception e) {
			Log.debugErr(e);
		}
	}`

**Comment by luke-hill** [comment] 2018-07-24 10:43
Can you avoid posting shortened urls. They could contain anything - including links to malware

**Comment by jimevans** [comment] 2018-07-24 10:49
@luke-hill I’d like to point out that the URL as posted in the code is not shortened. It’s a legitimate full URL that resolves properly. An apology might be in order.

**Comment by luke-hill** [comment] 2018-07-24 10:58
Probably worth pointing that out, but yes, it appears the glip.com website is indeed a legit website.

**Comment by p0deje** [comment] 2018-07-26 06:53
Is this a duplicate of #6192?

**Comment by jimevans** [comment] 2018-07-26 07:09
@p0deje Not really. The other issue is that calling `click()` sometimes crashes the IE driver. I’m mostly sure I fixed that (or at least can no longer repro it with the code provided therein). This issue is the long-standing issue that calling `click()` on an element in a window that doesn’t have the system focus doesn’t fully click the element, but rather just “focuses” the element. I’ve written about this issue [multiple](
http://jimevansmusic.blogspot.com/2012/06/whats-wrong-with-internet-explorer.html) [times](
http://jimevansmusic.blogspot.com/2013/01/revisiting-native-events-in-ie-driver.html) over the last six years. The solution to the issue is using the `requireWindowFocus` capability. The provided code (which ostensibly sets that capability) notwithstanding, if I run the provided sample code with that capability properly set, the issue does not reproduce for me. I’ve not gotten round to commenting on this issue yet, as I had worked on resolving the crash first.

**Comment by TARIFABBAS** [comment] 2018-07-26 10:58
Found one more scenario [Here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox)

While clicking on checkbox with label coding it is not performing action. Using javascript it is working fine.

**Comment by jimevans** [comment] 2018-07-26 12:17
@TARIFABBAS That’s moving the goalposts, to use an American sports colloquialism. Is your issue that the click doesn’t happen in the case you provided, or that a label associated with a checkbox doesn’t select the checkbox? Those are two different scenarios, with two potentially different root causes, and your repro case as submitted in this issue report has nothing to do with the latter.

Feel free to open a new issue about the checkbox (with code demonstrating the problem), but let’s not “what-about” in the comments to this issue. You haven’t addressed my comment, which provided reasoning and documentation for the behavior you claim to see, but which isn’t demonstrated by the code you provided.

**Comment by jimevans** [comment] 2018-07-26 14:20
@TARIFABBAS Moreover, there are tests in the project's test suite that explicitly test that clicking on a checkbox's label selects the check box. In the .NET test suite, the test is in ClickTest.cs, and is called [ClickingLabelShouldSetCheckbox](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/test/common/ClickTest.cs#L155). I can validate that test passes in IE, and is therefore not globally broken for all sites in IE. You can see this for yourself from the results posted on the [WebDriver Herald](http://webdriver-herald.herokuapp.com/) website, which tracks test results for multiple browsers (the first column is for IE11, and if you search the page for "ClickingLabel" you'll see the result for IE is passing).

**Comment by jimevans** [comment] 2018-08-26 18:42
One month since the last reply from the reporter. Closing this issue.

**Closed by jimevans** 2018-08-26 18:42 UTC
Labels: D-IE, R-awaiting answer
