### ISSUE TITLE
scroll-behavior: smooth breaks click

### ISSUE THREAD

**Issue by mihalikv** [SeleniumHQ/selenium#8295] opened 2020-05-11 16:42 UTC
## 🐛 Bug Report

If you use following style:
`
html {
    scroll-behavior: smooth !important;
}
` 
and Robot Framework command `Scroll Element Into View` you get `MoveTargetOutOfBoundsException: Message: move target out of bounds` error. Also if you use `Click Element` command which is  out of screen and Selenium needs to scroll to this element you get ` Element is not clickable at point`.

## To Reproduce

Smooth scrolling example page: https://jsfiddle.net/o8eg7dwh/

Detailed steps to reproduce the behavior:
Try to click button with id='test'

## Expected behavior

Click button

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 81.0.4044.129
Browser Driver version: ChromeDriver
robotframework-selenium2library==3.0.0
robotframework-seleniumlibrary==4.4.0

**Comment by diemol** [comment] 2020-05-22 21:37
@mihalikv could you provide an automation script only using Selenium WebDriver to reproduce the issue?

**Comment by dangoodman** [comment] 2020-06-18 15:14
Same issue here. Removing `scroll-behavior: auto` from the `html` element fixes it. Looks like it doesn't wait enough time for the scroll to complete when `scroll-behavior: smooth` is active and the element to click is not in the viewport.

**Comment by mihalikv** [comment] 2020-06-19 18:36
@dangoodman yes exactly. I am not working directly with selenium so I don't have pure selenium example. Do you have some pure selenium example ?

**Comment by dangoodman** [comment] 2020-06-20 10:21
I have made a small [example project](https://github.com/dangoodman/selenium-issue-8295). Here is the code reproducing the issue:
```php
class Test extends TestCase
{
    // Fails
    public function testScrollBehaviorSmooth(): void
    {
        $this->clickTheButton('https://jingoistcat.htmlpasta.com/');
    }

    // Succeeds
    public function testScrollBehaviorAuto(): void
    {
        $this->clickTheButton('https://unturningsealion.htmlpasta.com/');
    }

    private function clickTheButton(string $url): void
    {
        $driver = RemoteWebDriver::create(
            'http://localhost:9515',
            DesiredCapabilities::chrome(),
            15000,
            15000,
            null,
            null,
            null
        );

        $driver->get($url);

        $driver->findElement(WebDriverBy::id('test'))->click();

        $this->addToAssertionCount(1);
    }
}
```

**Comment by diemol** [comment] 2020-07-04 13:35
@dangoodman does the same thing happen when using any of the Selenium WebDriver bindings?

**Comment by smichae** [comment] 2020-07-04 15:22
@diemol I believe I'm running into the same issue using the selenium/standalone-chrome:latest Docker image, removing the smooth scroll allows a test to complete as expected.  Hope this helps.

**Comment by dangoodman** [comment] 2020-07-06 08:36
> @diemol I believe I'm running into the same issue using the selenium/standalone-chrome:latest Docker image, removing the smooth scroll allows a test to complete as expected. Hope this helps.

Confirming. This is also happening to me with selenium/standalone-chrome and selenium/standalone-chrome-debug docker images. 

@diemol, I'm not sure I understand well enough the Selenium project structure. Didn't I use the Selenium WebDriver binding in the [example project](https://github.com/dangoodman/selenium-issue-8295)? Do you mean the issue is related to WebDriver but not to Selenium?

**Comment by diemol** [comment] 2020-07-13 21:37
@dangoodman no, the PHP bindings belong to Facebook I believe. The idea is to identify if the problem is in the bindings or not. 
@smichae what bindings are you using?

**Comment by diemol** [comment] 2020-08-05 08:45
Closing as we did not get more information.

**Closed by diemol** 2020-08-05 08:45 UTC
Labels: R-awaiting answer

**Comment by dennisreimann** [comment] 2021-04-28 14:03
Can confirm I ran into this as well with Selenium.WebDriver.ChromeDriver -Version 90.0.4430.2400 (NuGet package for C#).
