### ISSUE TITLE
Session was terminated due to BROWSER_TIMEOUT exception occur while taking screenshot

### ISSUE THREAD

**Issue by Manikandan-Zoho** [SeleniumHQ/selenium#5661] opened 2018-03-22 05:58 UTC
## Meta -
OS:  
  MAC & Windows 10 & Linux
Selenium Version:  
   3.8.1
Browser:  
   Google Chrome 
Browser Version:  
     63.0.3239.108 (64-bit)
Expected Behavior -
     Successfully taking screenshot 
## Actual Behavior -
    the session was terminated due to BROWSER_TIMEOUT exception occur.
## Steps to reproduce -
     Run a test with more than 10 browsers parallelly.

HubConfig.json
```
 {
  "host": <hubhost>,
  "port": 3333,
  "newSessionWaitTimeout": -1,
  "servlets" : [],
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "nodePolling": 5000,
  "cleanUpCycle": 5000,
  "timeout": 30000,
  "browserTimeout": 180,
  "maxSession": 40,
  "jettyMaxThreads":-1
}
```
NodeConfig.json
```
{
"capabilities":
      [
        {
          "browserName": "*firefox",
          "maxInstances": 20,
          "seleniumProtocol": "Selenium"
        },
        {
          "browserName": "*googlechrome",
          "maxInstances": 15,
          "seleniumProtocol": "Selenium"
        },
        {
          "browserName": "*iexplore",
          "maxInstances": 1,
          "seleniumProtocol": "Selenium"
        },
        {
          "browserName": "firefox",
          "maxInstances": 20,
          "seleniumProtocol": "WebDriver"
        },
        {
          "browserName": "chrome",
          "maxInstances": 15,
          "seleniumProtocol": "WebDriver"
        },
        {
          "browserName": "internet explorer",
          "maxInstances": 1,
          "seleniumProtocol": "WebDriver"
        }
      ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 20,
  "port": 4444,
  "register": true,
  "registerCycle": 50000,
  "hub": "hubhost:3333",
  "nodeStatusCheckTimeout": 50000,
  "nodePolling": 50000,
  "role": "node",
  "unregisterIfStillDownAfter": 600000,
  "downPollingLimit": 2,
  "debug": false,
  "servlets" : [],
  "withoutServlets": [],
  "custom":{} 
}

**Comment by barancev** [comment] 2018-03-22 06:34
1) Please retest in version 3.11
2) Provide a page where this issue can be reproduced, and what's the browser window size? (how large is the screenshot?)

**Comment by Manikandan-Zoho** [comment] 2018-03-23 09:47
Window Size = 1920 x 1080, It occurs all the pages and also getting a cookie, finding an element, webdriver wait.

**Comment by Jaysheel** [comment] 2018-03-26 05:31
@Manikandan-Zoho You probably are running into https://bugs.chromium.org/p/chromedriver/issues/detail?id=2239.
Please try with updating chrome to v65 & chromedriver to 2.36/2.37.

Also, I assume you must be taking screenshot only when a test fails.
So failing screenshot, would be an effect rather than a cause.
Because browser is already closed with timeout-exception, before taking screenshot.

**Comment by Manikandan-Zoho** [comment] 2018-04-03 09:44
@Jaysheel  We have tested with Chrome v65 and chrome driver 2.37 but still now I got the same issue while taking a screenshot.

**Comment by Jaysheel** [comment] 2018-04-03 11:19
As far as I remember, "browesrTimeout should be always greater than timeout."
So in your case, I think you need to change one of the two timeouts on the hub accordingly. (For testing, you can change browserTimeout to 0 i.e. infinity.)

Also, as per https://github.com/SeleniumHQ/selenium/issues/5218, 
the timeouts from json are supposed to be in sec rather ms, although I'm not sure if it's true.

Still, you can try out the first one, @Manikandan-Zoho

**Comment by Manikandan-Zoho** [comment] 2018-04-25 10:42
I have tried the both but still Im getting the exception . I have added a custom servlet in grid hub & node Is there any chance that the exception occur because of the custom servlet. @Jaysheel @barancev

**Comment by evertones** [comment] 2018-05-16 15:31
I'm experiencing the same issue, but in my case it's intermittent. I cannot manually reproduce in a specific test case.

**Settings**
- Mac Pro (24 CPUs, 64BG RAM)
- Selenium 3.11.0 (tests written in Java/Scala/ScalaTest)
- Selenium Grid running with official Docker image (`3.11.0-californium`)
- Selenium Nodes (20 nodes) running with official Docker image for Chrome (`3.11.0-californium`)

The dimensions of screenshots in my case is `1280 x 1024`.

**File: docker-compose.yml**
```
version: '3.3'

services:
    hub:
        image: selenium/hub:3.11.0-californium
        container_name: selenium-hub
        domainname: mydomain.net
        hostname: hub
        restart: on-failure:10
        ports:
            - 4444:4444
        environment:
            - JAVA_OPTS=-Xms2g -Xmx6g
            - TZ=America/Denver

    chrome:
        image: selenium/node-chrome:3.11.0-californium
        dns: 192.168.1.100
        shm_size: 2g
        depends_on:
            - hub
        volumes:
            - /var/www/files:/var/www/files
            - /dev/shm:/dev/shm 
        environment:
            - TZ=America/Denver
            - JAVA_OPTS=-Xmx4g
            - HUB_PORT_4444_TCP_ADDR=hub
            - HUB_PORT_4444_TCP_PORT=4444
            - DBUS_SESSION_BUS_ADDRESS=/dev/null
```

**Stacktrace**
```
   - the panel has a “Home” button
     org.openqa.selenium.WebDriverException: Session [2c02eb2eee0a71a8a274f978883f835e] was terminated due to BROWSER_TIMEOUT
 Command duration or timeout: 0 milliseconds
 Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
 System info: host: 'myhost', ip: '172.18.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-31-generic', java.version: '1.8.0_151'
 Driver info: org.openqa.selenium.remote.RemoteWebDriver
 Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.37.544315 (730aa6a5fdba15..., userDataDir: /tmp/.org.chromium.Chromium...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 65.0.3325.181, webStorageEnabled: true, webdriver.remote.sessionid: 2c02eb2eee0a71a8a274f978883...}
 Session ID: 2c02eb2eee0a71a8a274f978883f835e
     at sun.reflect.GeneratedConstructorAccessor310.newInstance(Unknown Source)
     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
     at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
     at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
     at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
     at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
     at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
     at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
     at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
     ...
     Cause: org.openqa.grid.common.exception.GridException: Session [2c02eb2eee0a71a8a274f978883f835e] was terminated due to BROWSER_TIMEOUT
     at org.openqa.grid.internal.ActiveTestSessions.getExistingSession(ActiveTestSessions.java:115)
     at org.openqa.grid.internal.DefaultGridRegistry.getExistingSession(DefaultGridRegistry.java:380)
     at org.openqa.grid.web.servlet.handler.RequestHandler.getSession(RequestHandler.java:241)
     at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:123)
     at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:86)
     at org.openqa.grid.web.servlet.DriverServlet.doGet(DriverServlet.java:64)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
     at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
     at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
     ...
```

I'm not sure, but I have the impression that in my case this issue started to happen after upgrading from `Selenium 3.5.3` to `Selenium 3.11.0`.

**Comment by barancev** [comment] 2018-06-12 16:33
Please provide the complete log that ends with "terminated due to BROWSER_TIMEOUT" message, let's look what happened before.

**Comment by barancev** [comment] 2018-07-18 21:45
We still need a log, please.

**Comment by evertones** [comment] 2018-07-23 17:01
@barancev : Sorry for the late message.
I updated my Selenium and Selenium Grid to version `3.12.0` on May 25th and haven't seen the BROWSER_TIMEOUT failure anymore.

I don't have any old LOG that could have all messages around the error, but think this could have been solved by new versions of `ChromeDriver`.

**Comment by pscheit** [comment] 2018-07-23 17:03
I was running the chrome-node in docker and have to mount /dev/shm into the container (to provide more shared memory), that resolved the problem

**Comment by barancev** [comment] 2018-09-23 10:53
Closing the issue as there is no requested information (logs) provided.

**Closed by barancev** 2018-09-23 10:53 UTC
Labels: D-chrome, R-awaiting answer

**Comment by Vinodkomeershetty** [comment] 2018-11-15 06:33
@Manikandan-Zoho @barancev I am facing similar issue as mentioned

Caused by: org.openqa.selenium.WebDriverException: Session [9d4f1df4-8886-440a-aaf2-234e360e1947] was terminated due to BROWSER_TIMEOUT
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'

 os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: unknown
	at org.openqa.grid.internal.ActiveTestSessions.getExistingSession(ActiveTestSessions.java:105)
	at org.openqa.grid.internal.Registry.getExistingSession(Registry.java:404)
	at org.openqa.grid.web.servlet.handler.RequestHandler.getSession(RequestHandler.java:232)
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:117)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:543)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:320)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:112)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.seleniumhq.jetty9.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.seleniumhq.jetty9.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.seleniumhq.jetty9.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)

I am running the issue on appium(1.8.1) Android chrome browser(66) with version chromedriver -3.9 ,

More info I have two testng.xml files

Execution flow 
1st testng has two methods say a and b 
2 testng has two methods  say a and b

1st testng picks  a and executes fine
2nd testng picks a and due to some application issue it fails and browser stays back and throws above error

**Comment by Nekobravo** [comment] 2019-04-16 02:49
Mismo error, alguien supo como arreglarlo ?
