### ISSUE TITLE
Selenium IDE - User no longer able to arrange test steps by dragging and dropping

### ISSUE THREAD

**Issue by vietpham429** [SeleniumHQ/selenium#3154] opened 2016-11-22 19:43 UTC
## Meta -
OS:  Windows 10 OSX
Selenium Version:  2.6.1 IDE
Browser:   Firefox

User no longer able to move test steps through Selenium IDE by drag and drop

## Expected Behavior -
User should be able to arrange and order test steps and test case by dragging them

## Actual Behavior -
User is unable to arrange test steps by dragging them

## Steps to reproduce -
# Create a few test case
# Add a series of test steps for the test case
# Attempt to rearrange the test steps and test case by dragging them

**Comment by lukeis** [comment] 2016-11-22 19:56
duplicate of #3139

**Closed by lukeis** 2016-11-22 19:56 UTC
Labels: C-ide

**Comment by threeedie** [comment] 2016-11-28 19:06
I am also have this issue. It started on 11/23/2016. I am using iOS El Captian 10.11.5 (15F34) and Selenium 2.9.1.1. This issue is very much hampering my work. Your investigation and hopefully a fix would be much appreciated. I consider this a High priority issue. Oh, I have also re-installed Selenium but it did not fix this.
