### ISSUE TITLE
Have GeckoDriver logs and Firefox be redirected by default to disk

### ISSUE THREAD

**Issue by AutomatedTester** [SeleniumHQ/selenium#5129] opened 2017-11-28 13:38 UTC
## Meta -
OS:  All

Selenium Version:  
All
Browser:  
Firefox

Browser Version:  
All

Currently a number of the drivers just pollute logs with Geckodriver output. This should be redirected to a file or somewhere else that people can then go have a look at.

Currently python handles this puts it in `geckodriver.log`

**Comment by barancev** [comment] 2017-11-28 14:19
That's exactly what I suggested to implement in geckodriver -- saving logs to a file (or even to /dev/null) by default. Implementing this feature in one place is easier that changing all bindings.

**Comment by barancev** [comment] 2017-11-28 14:29
On the other hand, I dislike the idea to save logs to a file. If we append to a file -- it gets large. If we recreate the file on each new session -- we lose information collected during previous sessions, and we have issues with parallel runs. Streaming to console is not bad if log level is low enough.

**Comment by AutomatedTester** [comment] 2017-11-28 14:38
@barancev you are discounting any new service that comes along and outputs to stdout. the bindings can easily control this and we never have to worry about new bindings not having their stuff write to file in the first place.

**Comment by barancev** [comment] 2017-12-11 09:04
Duplicate of #2632

**Closed by barancev** 2017-12-11 09:04 UTC
