### ISSUE TITLE
[🐛 Bug]: Redirection browserName to "Chrome" from all other browsers

### ISSUE THREAD

**Issue by redouane07** [SeleniumHQ/selenium#10325] opened 2022-02-04 16:18 UTC
### What happened?

Hi every one,

I'm using Selenium Grid v4.1.0 having **only one** Node with **Chrome** capabilities,  with Test Framework **Protractor v5.4.2**

Currently I m getting a dysfunction that when I launch a test with browserName=Firefox or (=MicrosoftEdge),  normally Grid refuse the request because there is no node that match those capabilities,  but it does not,  the request will be changed by Distributor by putting browserName=Chrome and run a Chrome browser.

What I think that influence this redirection is the **LoggingPrefs** config in **protractor-conf.js**, an extension **goog**: will be added by selenium (instead a firefox extension "moz" or "ms" in case of MicrosoftEge) , and maybe this config that cause this redirection that we can not tolerant it

### How can we reproduce the issue?

```shell
Here you find Capabilities configuration which are in "protractor-conf.js" :

    capabilities: {
        acceptInsecureCerts: browserName === 'firefox',
        browserName: browserName,
        platform: environment_1.Environment.getParam('platform', ''),
        chromeOptions: browserName === 'chrome' ? {
            args: ['--test-type --disable-infobars --start-maximized'],
        } : undefined,
        ignoreProtectedModeSettings: true,
        ensureCleanSession: true,
        ignoreUncaughtExceptions: true,
        loggingPrefs: {
            browser: 'ALL',
            driver: 'INFO',
        },
    },

The Selenium server running as standalone in local:

java -jar selenium-server-4.1.0.jar standalone 


The Test was launched by running this cmd npm:

npm run test -- --params.seleniumAddress=http://IP:4444 '--params.browserName=firefox' --tags=@MY_TAG
```

### Relevant log output

```shell
Here you find Selenium Grid logs, you can see that Distributor receive a request with browserName: firefox and goog:loggingPrefs, after that Distributor will creates a session as browserName: chrome.


17:09:59.368 INFO [LocalDistributor.newSession] - Session request received by the distributor:
 [Capabilities {acceptInsecureCerts: true, browserName: firefox, platformName: }, Capabilities {acceptInsecureCerts: true, browserName: firefox, count: 1, ensureCleanSession: true, ignoreProtectedModeSettings: true, ignoreUncaughtExceptions: true, loggingPrefs: org.openqa.selenium.logging..., platform: WINDOWS, tags: @test_62159}, Capabilities {acceptInsecureCerts: true, goog:loggingPrefs: {browser: ALL, driver: INFO}, platformName: }]
Starting ChromeDriver 96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}) on port 50356

Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping 
ChromeDriver safe.
ChromeDriver was started successfully.
[1643991001.942][WARNING]: This version of ChromeDriver has not been tested with Chrome version 97.

17:10:02.411 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C

17:10:02.479 INFO [LocalDistributor.newSession] - Session created by the distributor. Id: d909232460858181e81a42686b741de5, Caps: Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 97.0.4692.99, chrome: {chromedriverVersion: 96.0.4664.45 (76e4c1bb2ab46..., userDataDir: C:\Users\223039~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:53127}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://192.168.10.16:4444/sess..., se:cdpVersion: 97.0.4692.99, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
```

### Operating System

Windows 10

### Selenium version

Javascript 4.0.0-rc-1

### What are the browser(s) and version(s) where you see this issue?

All

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 96.0.4664.45

### Are you using Selenium Grid?

4.1.0

**Comment by diemol** [comment] 2022-02-04 16:46
Would it be possible for you to share a GitHub repo with the Protactor config ready to use? I cannot reproduce this with Selenium bindings because the capabilities are well structured.

**Comment by redouane07** [comment] 2022-02-07 13:31
I can't unfortunately, its an enterprise code private license,

Also I would like to confirm that I have noticed that when I drop **loggingPrefs** {} section config, there is no more issue (selenium grid refuse request if session does not match capabilities of the node, which is the normal case). So that allows me to say that this redirection issue comes from loggingPrefs code, because it will add the wrong browser name extension.

        loggingPrefs: {
            ...
            ...
        },

**Comment by diemol** [comment] 2022-02-07 13:35
It does not need to be the same code, just something with the same configuration and any dummy test.

**Comment by diemol** [comment] 2022-02-22 12:15
Somehow Protactor is sending `goog:loggingPrefs` when `loggingPrefs` is present in that configuration. Since we did not get a way to replicate that, will close this issue for now. If there is a way to replicate it, please share it and I can reopen.

**Closed as completed by diemol** 2022-02-22 12:15 UTC
Labels: B-grid, J-awaiting answer, I-defect
