### ISSUE TITLE
Different performance between python and dotnet (firefox)

### ISSUE THREAD

**Issue by xAaeEx** [SeleniumHQ/selenium#6597] opened 2018-10-30 13:06 UTC
## Different performance between python and dotnet (firefox)
OS: Windows 10 Enterprise 2016 LTSB (Build: 1607)

Selenium Version:  
3.14.1 (python) - 3.14.0 (dotnet), Visual Studio, Visual Studio Code

Browser:  
Firefox

Browser Version:  
63.0 64-Bit

## Expected Behavior

Expected Behavior is that all Tests (with Firefox) behave the same in dotnet as in python environment.
Which they do on the execution level, but unfortunatly they behave different in performance which I don't comprehend.

### Behavior in Firefox
The performance difference is big! 

|Browser|Time|
|---|---:|
|Firefox (dotnet)|32.40 sec|
|Firefox (python)|11.825 sec|

### Example behavior in Chrome (same test)
It's basically the same (+/- some seconds).

|Browser|Time|
|---|---:|
|Chrome (dotnet)|10.87 sec|
|Chrome (python)|12.174 sec|

## Steps to reproduce this issue
On https://gist.github.com/xAaeEx/2da70dbdf6a55aeebd6ca7ba253341e0 you will find the Test(s) I created which opens Google search for SeleniumHQ and click on the first link.

Both tests are (almost) identical on python aswell as dotnet.

Can someone explain what is happening? Or if this is a firefox/marionette issue I should report?

If this is an issue, we should consider looking into it, as apperently many folks are using more and more dotnet to automate stuff (as am I).

**Comment by AutomatedTester** [comment] 2018-10-30 13:39
Since Python is working faster than .NET and it's doing the same thing it suggests that it is not the remote end (geckodriver and Firefox) that is the issue.

Could you do a test where it is purely instantiating an object and see how long that takes. Under the hood this is starting the browser and getting everything in place. If it is the same at that point then perhaps there are issues with a specific command but if we can narrow that area first then we can move from there. 

Ideally they should be within the same times.

**Comment by shs96c** [comment] 2018-10-30 13:45
Which version of .Net are you using? There's a known performance problem with .Net Core 2, which you might be tickling in the firefox case.

I'd also be interested to know how long the tests took once the browser started --- is the problem with test execution once the browser is stood up, or is it in actually creating the instance in the first place?

**Comment by xAaeEx** [comment] 2018-10-30 14:34
So I updated the tests to give me the time ellapsed when the driver is up and running until the test is complete:

||Time|
|---|---|
|python|1.6514158248901367s|
|dotnet|12.5151790s|

Also here are all requirements I took to write the tests and the environments:

## Requirements for Python:
### Python 3.6.4
* unittest
* selenium (3.14.1)

## Nuget packages for C#:
### dotnet Core 2.1 (2.1.403)
* Microsoft.NET.Test.Sdk (15.8.0)
* MSTest.TestAdapter (1.3.2)
* MSTest.TestFramework (1.3.2)
* Selenium.WebDriver (3.14.0)

## WebDrivers
### geckodriver v0.23.0
### chromedriver v2.43

**Comment by xAaeEx** [comment] 2018-10-30 14:36
Also I noticed that the firefox browser is very slow when you do an findElement and give that element an input (click or sendKeys).

It's almost when you do test against InternetExplorer and it's slow motion.

**Comment by xAaeEx** [comment] 2018-10-30 18:17
@jimevans Sorry man :) it was not intensional to post it as a rant. 
It was just a way to describe the current issue. (I read about the 32/64-Bit problems)

**Comment by xAaeEx** [comment] 2019-02-06 07:34
FYI:
I'm testing this issue with the newest dotnet core version (3.0.100-preview-010184) and it seems not to be fixed yet.

**Comment by xAaeEx** [comment] 2019-05-14 07:23
FYI:

Firefox 66.0.5 (64-bit)
geckodriver 0.24.0 (win64)
dotnet core 3.0.100-preview5-011568 (64-bit)

Issue still remains

**Comment by jimevans** [comment] 2019-05-14 18:35
The problem could be fixed in geckodriver, if the geckodriver team would listen on both the IPv4 and IPv6 loopback connections simultaneously (opening two sockets instead of one, as every other WebDriver remote-end implementation currently does).\

**Comment by sickvisionz** [comment] 2019-12-27 22:35
I was having a similar issue, but in C#.  The answer at https://stackoverflow.com/a/57720610/8056356 solved it for me.

**Comment by AutomatedTester** [comment] 2020-04-03 13:00
Closing as the issue is with Geckodriver and Mozilla needs to fix it. From their side they can enable geckodriver to do that but the pass through to Firefox gets stuck.

**Closed by AutomatedTester** 2020-04-03 13:00 UTC
Labels: C-dotnet, I-performance, R-blocked on external
