### ISSUE TITLE
Actions Class not working with gecko driver

### ISSUE THREAD

**Issue by naveenv20** [SeleniumHQ/selenium#2581] opened 2016-08-08 05:45 UTC
## Meta -
OS:  

Selenium Version:  
3.0.0 beta 2
Browser:  
Firefox 48 and chrome

## Expected Behavior -
Actions class should work properly . We should be able generate the mouse action hovering.

## Actual Behavior -
With  Selenium-Java 2.43.0 , this command is working fine. With the update 3.0.0-beta2, started access firefox driver through gecko driver, in that case we are getting the below excpetion

org.openqa.selenium.UnsupportedCommandException: POST /session/625b7993-e503-4acf-b50e-01ca01690e26/moveto did not match a known command (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7 milliseconds
Build info: version: 'unknown', revision: '31c43c8', time: '2016-08-02 21:57:56 -0700'
System info: host: 'LMTN202461', ip: '10.15.2.63', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20160726073904, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, browserVersion=48.0, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: 625b7993-e503-4acf-b50e-01ca01690e26
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:683)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteMouse.mouseMove(RemoteMouse.java:89)
	at org.openqa.selenium.interactions.MoveMouseAction.perform(MoveMouseAction.java:39)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:50)
	at com.maax.businessmanager.util.TestBase.hovermouse(TestBase.java:225)

## Steps to reproduce -
Actions class not working with new gecko driver.  
Have the below line of code in script  and execute it

Actions act= new Actions(d1);
act.moveToElement(d1.findElement(By.xpath("path of the element")).build().perform();

**Comment by AutomatedTester** [comment] 2016-08-08 10:12
Duplicate of #2285

**Closed by AutomatedTester** 2016-08-08 10:12 UTC
