### ISSUE TITLE
UnhandledPromiseRejectionWarning: NoSuchSessionError: invalid session id while quitting the driver.

### ISSUE THREAD

**Issue by last-stand** [SeleniumHQ/selenium#6673] opened 2018-11-21 14:12 UTC
## NoSuchSessionError: invalid session id
* OS:  
macOS High Sierra

* Selenium Version: 
selenium-webdriver: ^4.0.0-alpha.1

*Browser:  
Google Chrome

I am running integration tests using Cucumber and Selenium. All tests are passing but still getting `UnhandledPromiseRejectionWarning: NoSuchSessionError: invalid session id`. 

I have figured out that it's happening while calling `this.driver.quit()` in After hook. I have checked the driver's sessionId, it's same in **Before** and **After** hooks. Does anyone have any idea how to fix this issue?

I have posted this issue on stackoverflow but no luck. this is the link
[NoSuchSessionError: invalid session id](https://stackoverflow.com/questions/53078373/unhandledpromiserejectionwarning-nosuchsessionerror-invalid-session-id-seleniu)

Package Versions Used:
selenium-webdriver: ^4.0.0-alpha.1
chromedriver: ^2.42.0
cucumber: ^5.0.1

**Comment by barancev** [comment] 2018-12-10 10:11
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by jLouzado** [comment] 2018-12-20 14:10
# System Details

- OS: MacOS High Sierra
- selenium-webdriver: ^4.0.0-alpha.1
- ChromeDriver 2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189)

# Steps

# Steps:
- Install `selenium-webdriver`
- install chromedriver 

```console
brew tap homebrew/cask
brew cask install chromedriver
```

- Run the code shown below

# Example Code

```js
#!/usr/bin/env node

/**
 * Created by joel on 20/12/18.
 */

const {Builder} = require('selenium-webdriver')

const main = () => {
  console.log('"TTI", "DCL", "Complete"')
  new Builder()
    .forBrowser('chrome')
    .build()
    .then(driver =>
      driver
        .get('http://www.google.com/ncr')
        .then(_ => {
          const t = driver
            .executeScript('return window.performance.timing.domInteractive')
            .then(result => console.log(result), err => console.error(`We have an ${err}`))
        })
        .then(_ => driver.quit())
        .catch(err => console.error(err))
    )
}

main()
```

# Error:

```console
We have an NoSuchSessionError: invalid session id
  (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.13.6 x86_64)
```

# Expectation
- the value should resolve and the browser quit gracefully

@barancev would this be sufficient information?

**Comment by kawadhiya21** [comment] 2018-12-23 12:37
facing same issue.

**Comment by doliver3** [comment] 2019-02-17 01:44
I'm experiencing the same problem.

**Comment by Srutherford2407** [comment] 2019-02-21 03:25
@barancev Any update on this issue? I am still seeing this issue today as well.

**Comment by e0holl01** [comment] 2019-03-15 15:33
Experiencing the issue today as well.

**Comment by iivn** [comment] 2019-03-21 10:25
Same here!

**Comment by derit** [comment] 2019-03-21 10:50
same here, for case i using for testing with mocha (node js)

**Comment by a-barbieri** [comment] 2019-03-29 10:49
I was just quitting immediately... See [this comment](https://github.com/SeleniumHQ/selenium/issues/6824#issuecomment-452140621)

```js
driver.quit(); // run this just after your tests are done
```

---

### Cucumber example

```js
// some requirements...
const driver = new webdriver.Builder().forBrowser('firefox').build();

When('I type query as {string}', function (string, next) {
  // some code...
});

Then('I submit', function () {
  driver.findElement(webdriver.By.name("someElement")).click().then(function () {
    driver.wait(function () {
      // finalize your test
      const expectation = driver.findElements(webdriver.By.name("anotherElement")) === 0

      // quit after you've completed the test
      driver.quit();

      return expectation;
    }, 2000);
  });
});
```

**Comment by barancev** [comment] 2019-04-13 20:15
@jLouzado You've misordered then-blocks, here is a fixed version:
```
const {Builder} = require('selenium-webdriver')

const main = () => {
  console.log('"TTI", "DCL", "Complete"')
  new Builder()
    .forBrowser('chrome')
    .build()
    .then(driver =>
      driver
        .get('http://www.google.com/ncr')
        .then(_ => {
          const t = driver
            .executeScript('return window.performance.timing.domInteractive')
            .then(result => {
              console.log(result);
              driver.quit();
            }, err => console.error(`We have an ${err}`))
        })
        .catch(err => console.error(err))
    )
}

main()
```

**Comment by barancev** [comment] 2019-04-13 20:24
Closing the issue because `UnhandledPromiseRejectionWarning` is not related to Selenium internals, it does not have a promise manager and relays on standard JS promises. As stated in the comment on the linked SO page, "without looking in detail on openWindow or your test cases you can already assume that you use Promises the wrong way".

All "same issue" comments are ignored because we can't be sure how "same" they are without reproduction scenarios. Most probably they are caused by using Promises the wrong way too.

**Closed by barancev** 2019-04-13 20:24 UTC
Labels: C-nodejs

**Comment by jLouzado** [comment] 2019-04-14 04:42
@barancev then I think there might be a bug in the basic documentation, because I didn't write out the code-snippet myself; I lifted it from the docs as I was trying to get things set up.

**Comment by barancev** [comment] 2019-04-14 05:23
@jLouzado It might be, yes. Please share the link to the documentation page where you get this snipped from, we'll fix it.
