### ISSUE TITLE
Returned driver instance from switchTo().window() have  0  ImplicityWait timeout

### ISSUE THREAD

**Issue by VladislavLopatynsky** [SeleniumHQ/selenium#509] opened 2015-04-30 11:19 UTC
selenium 2.45.0
firefox 37.0.1

Setting up my implicity wait by
<code>
driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
</code>

then switching to another window and storing returned driver instance to a new variable
<code>WebDriver windowDriver = driver.switchTo().window(handleHash);</code>

When trying to interact with element in another window with windowDriver variable (which we got from switchTo().window()  method) I'm getting NoSuchElement exception with 50-200 miliseconds wait.
<code>windowDriver.findElement()</code>

Problem solved when I put once again implicityWait but directly to new variable windowDriver.
<code>windowDriver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);</code>

P.S. sessionID and objectID in debugging are the same.

**Comment by lukeis** [comment] 2015-04-30 16:27
Can you provide a concise reproducible test case for this? Or even better add it to selenium's tests :)

https://github.com/SeleniumHQ/selenium/blob/master/java/client/test/org/openqa/selenium/ImplicitWaitTest.java

**Comment by VladislavLopatynsky** [comment] 2015-04-30 20:10
Unfortunately don't know how to verify current implicityTime of driver instance:(
Test case:

Precondition:
Set impicity wait to driver before any actions.
After switching to newly opened window and trying to interact with any element(page is still loading, or just try to find element that 100% doesn't exist) you faced with NoSuchElementException and saw in logs -  timeout: 50-200 miliseconds

**Comment by demos74dx** [comment] 2015-09-08 23:36
selenium v.2.47.1
We wrote a test case for this issue at the Become a Committer workshop. commit bf6f68e.

We could not reproduce on this version, there is a chance it has been resolved.  Please provide more information if this is still an issue for you on the latest version.

**Comment by demos74dx** [comment] 2015-09-08 23:48
Pull Request #1016
https://github.com/SeleniumHQ/selenium/pull/1016

**Comment by barancev** [comment] 2015-09-20 11:05
Closing as there is a test that approves the correct behavior.

**Closed by barancev** 2015-09-20 11:05 UTC
Labels: D-firefox
