### ISSUE TITLE
Selenium IDE 2.9.1 will not record or really do any actions

### ISSUE THREAD

**Issue by k15roberts** [SeleniumHQ/selenium#4430] opened 2017-08-09 19:19 UTC
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by k15roberts** [comment] 2017-08-09 19:20
My firefox is 55.0 and I have trying to record in Selenium IDE 2.9.1

**Comment by k15roberts** [comment] 2017-08-09 19:21
Sorry did not mean to close issue

**Comment by ddavison** [comment] 2017-08-09 19:31
duplicate of #4406

**Closed by ddavison** 2017-08-09 19:31 UTC

**Comment by ianchanning** [comment] 2017-08-21 07:16
My rather basic workaround is just to downgrade to Firefox 54. You can install FF 55 and FF 54 side by side, just choose a different installation directory.

You can get the Firefox 54 download from their FTP download site: https://ftp.mozilla.org/pub/firefox/releases/54.0.1/

You then need to quickly go into Options > Advanced > Update (tab), select 'Never check for updates' and uncheck 'use a background service'.

**Comment by stefangrotz** [comment] 2017-08-22 09:32
I just donated to seleniumhq, I would recommend everyone who wants to use this plugin in the future and cannot contribute in other ways to the code to do the same.

**Comment by Gordusha** [comment] 2017-11-14 20:53
Hi, I am on Firefox v 54.01, still Selenium IDE is not recording and gives me following message:
"There was an unexpected error. Msg: TypeError: window.editor.treeView is undefined
Url: chrome://selenium-ide/content/selenium-ide.xul, line: 1, column: 1
oncommand@chrome://selenium-ide/content/selenium-ide.xul:1:1" 
Don't understand what it has to do with Chrome? (yes, I have them both on my machine)

**Comment by karinatech** [comment] 2018-12-21 04:20
I have the same issue Selenium IDE 2.9 and Firefox 54.01 and Selenium doesn't record anything at all. I tried reinstalling it several times but it doesn't help.
