### ISSUE TITLE
Sometimes InternetExplorerDriver.Dispose() takes 1 to 2 miunutes

### ISSUE THREAD

**Issue by drauch** [SeleniumHQ/selenium#1843] opened 2016-03-18 12:43 UTC
## Meta -
OS: Windows Server 2008 R2 Enterprise
Selenium Version: 2.48.0 
Browser: IE11
Browser Version: 11.0.9600.18204 (Update Versions: 11.0.28)

## Expected Behavior -
Dispose() immediately shuts down IE.

## Actual Behavior -
Dispose() takes 1 to 2 minutes, then, finally, IE is shut down (no exception, no problematic log output in InternetExplorerDriver log).

## Steps to reproduce -
Unfortunately, the problem currently occurs on our build server only. IE settings double-checked.

**Comment by drauch** [comment] 2016-03-18 13:00
It looks like our {{SendKeys.SendWait("{F6}{TAB}{ENTER}")}} when accepting the download of a file, somehow & sometimes sets IE in a mode where WebDriver isn't able to communicate with IE anymore (also, e.g., screenshot taking is not possible anymore).

**Comment by drauch** [comment] 2016-03-21 12:17
Oh, forgot: the IEDriverServer version is 2.53 32bit.

**Comment by jimevans** [comment] 2016-03-21 14:45
You'll need to provide a reproducible case for us to be able to take any action on this issue. Interacting with system components (dialogs, info bars, etc.) is strictly unsupported with the IE driver in general, and the file download case is explicitly untested.

**Comment by drauch** [comment] 2016-03-22 11:18
You can download a repro solution here:
https://www.dropbox.com/s/jvk1gn0y7wapnv8/IEDriverServerF6DisposeRepro.zip?dl=0

The solution contains a sample MVC project which is automatically hosted using IIS Express when the web test is executed (using the DryRunner package). So just execute the web test in MyTestFixture.cs and see the magic happen.

By the way, I know of the unsupported download scenario, however, it is not the download per-se which is not working, it is just weird that WebDriver ceases to work completely afterwards.

**Comment by drauch** [comment] 2016-03-22 11:22
On another note: I know it is very hard to fix bugs without being given a repro sample. However, it should still be allowed to _report_ bugs without repro samples. A bug report is valuable in itself! It enables other users to find the problem (if they encounter it themselves) and allows potential future users of a project to see whether there are many open issues or not.

Strangely enough I often get the vibe that reporting a bug without a repro sample is considered rude or even useless (some people even close them as not-reproducible). I posted this message, as I somehow felt this vibe again when reading your message. Maybe it's been just me though.

**Comment by jimevans** [comment] 2016-03-22 11:50
Thank you for the repro case. That will be a big help in investigating the issue.

On a personal note regarding your other comment, I have definite opinions about it, which I will be willing to share privately. There are circumstances involving the general case of issue reports, and other concerns about this particular one.

**Comment by jimevans** [comment] 2016-03-24 21:23
I've added a "fix" for this issue in fa5ac92. The reason for the apparent "hang" is that when a file is downloaded, the info bar causes the `IWebBrowser2::ReadyState` property to never reach a value of `READYSTATE_COMPLETE`. Instead, it stops updating at `READYSTATE_INTERACTIVE`. Thus the driver's wait algorithm would never proceed beyond waiting for this property to reach an expected value. Note that this property is separate and distinct from the DOM's `document.readyState` property.

The proper way to resolve the issue now is to set the `pageLoadStrategy` capability to the value of "eager". In the .NET bindings at least, this can be done by setting the value of `InternetExplorerOptions.PageLoadStrategy` to `InternetExplorerPageLoadStrategy.Eager`. Other language bindings should consult their documentation on how to set desired capabilities for the IE driver. Furthermore, please do understand that this might have side effects on waiting for pages to load after navigation, so do take care to make sure you are properly waiting for elements on the resulting page.

The fix is available in IEDriverServer.exe version 2.53.0.1. As described in the version number strategy documented in the [change log](https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriverserver/CHANGELOG), this indicates that the change has been checked into the source tree, but not publicly distributed via any release mechanisms. This is intentional, and the change will be more widely released once a sufficient number of other fixes have been bundled together to warrant a new release. In the meantime, if you cannot wait for a new release, you can download the intermediate executable [directly from the tree](https://github.com/SeleniumHQ/selenium/blob/master/cpp/prebuilt/Win32/Release/IEDriverServer.exe?raw=true) on Github.

On another note, you can probably avoid needing a separate thread for `System.Windows.Forms.SendKeys.SendWait()` by using the `requireWindowFocus` capability. As with the page load strategy, this would be done by setting a property on the `InternetExplorerOptions` object.

**Closed by jimevans** 2016-03-24 21:23 UTC
Labels: D-IE

**Comment by drauch** [comment] 2016-03-25 10:49
Thank you for the fix, I've got some open questions regarding your description:

1) Am I correct, that setting the PageLoadStrategy to Eager implies that JavaScript in document.load handlers may not have finished executing after page load seems to be "done" and the web test executes?

2) We already using the following combination of options:
* EnableNativeEvents=true (otherwise JavaScript alters hang the test completely)
* EnablePersistentHover=false + RequireWindowFocus=true (seems to reliable allow hovering)

So it looks like RequireWindowFocus still forces me to use an additional thread.

3) After reading your blog posts once again (I think it's been the fifth time now :+1:) I've seen that there are some warnings about native events and require window focus, however, also some markers like "not yet" or "soon to be improved". What is the current state of the IE driver regarding this topics? Maybe it is even time for a new fancy blog post of yours :+1: 

Best regards,
D.R.

**Comment by jimevans** [comment] 2016-03-25 17:15
1. Yes, that may be the case. I suspect that the probability of this happening is pretty small, but you have some alternatives, including use of `WebDriverWait` or using `return document.readyState` via `ExecuteScript`.

2. Interesting. Your example project did not turn on `requireWindowFocus`, and did hang when performing `SendKeys.SendWait`. When I set `requireWindowFocus` on, I no longer required a separate thread.

3. The WebDriver tests in [our CI system](http://ci.seleniumhq.org:8080/) have been running for some time with the `requireWindowFocus` capability set on for IE tests. It's as mature a feature as there is likely to be. As for another blog post, between work at my job (that I actually get paid for), work on the Selenium project (which I don't get paid for), and having a life and family outside of those things (which is frankly more important to me), I wouldn't hold my breath.
