### ISSUE TITLE
Tab clicking not working on version 2.48.1

### ISSUE THREAD

**Issue by mrzacarias** [SeleniumHQ/selenium#1182] opened 2015-10-21 22:58 UTC
When using page-object + cucumber, I tried to find and click a tab using a id and didn't worked. Instead of clicking the tab, selenium clicked the logo on header and got back to homepage and lost the context.

![Cucumber feedback after running with 2.48.1](http://i.imgur.com/X358NNe.png)

I solved this using 2.47.1 again.

**Comment by lukeis** [comment] 2015-10-21 23:08
you'll need to provide a reproducible test case and a sample page or url that can reproduce the issue. Also please mention which browser (and version) you are using and OS info too.

**Comment by titusfortner** [comment] 2015-10-22 00:06
@mrzacarias - As maintainer of Selenium & Watir portions of your code, I'm very interested to know why your test has issues with the latest selenium version. Can you run the test with --backtrace and let me know what it looks like? Thanks.

**Comment by lukeis** [comment] 2015-10-22 18:00
going to close this issue for now, we can reopen it if a reproducible test case is provided.

**Closed by lukeis** 2015-10-22 18:00 UTC
