### ISSUE TITLE
Selenium Click is not working with IE11 in windows 7

### ISSUE THREAD

**Issue by vsplvid** [SeleniumHQ/selenium#5867] opened 2018-05-08 12:20 UTC
## Meta -
OS:  windows 7

Selenium Version:  3.10

Browser:  Internet Explorer

**Comment by lmtierney** [comment] 2018-05-08 12:35
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by mbn217** [comment] 2018-05-08 19:59
@vsplvid can you add this line to you capabilities
dCaps.setCapability("requireWindowFocus", true);
If the issue is inconsistency of the click , then this might fix it

**Comment by vsplvid** [comment] 2018-05-09 12:10
Added this code:dCaps.setCapability("requireWindowFocus", true);not working as expected.


![image](https://user-images.githubusercontent.com/38911734/39813860-cd57def0-53af-11e8-86f8-303db5799167.png)
Still cannot click on X button.

**Comment by cgoldberg** [comment] 2018-05-09 14:26
@vsplvid,

I *think* this combination of settings is causing your click issues:

```
dCaps.setCapability("nativeEvents", false);
dCaps.setJavascriptEnabled(false);
```

You are disabling native events, which means user interaction will be based on synthetic
events (simulating Javascript events directly).  In the next line, you disable JavaScript, preventing the synthetic click to fire.

----

* I'm closing this issue since the OP has not provided a complete testcase and enough details to fully diagnose... happy to re-open if more information is provided.

**Closed by cgoldberg** 2018-05-09 14:26 UTC
Labels: C-java, D-IE, R-awaiting answer
