### ISSUE TITLE
IEDriverServer Issue when working with Multiple Windows

### ISSUE THREAD

**Issue by blueray333** [SeleniumHQ/selenium#4892] opened 2017-10-17 20:52 UTC
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:  

## Expected Behavior -
Able to check the title of the 2nd window

## Actual Behavior -
Two observations:
1. putting a Thread.sleep(5000) after clicking the link for the 2nd window shows only 1 window handle
2. with no Thread.sleep, it is able to store two window handles, but when switching to it, Exception of "No Window Found" is encountered

**Comment by jimevans** [comment] 2017-10-17 22:54
Duplicate of of #4893, which says "corrected," so I will assume this one should be closed.

**Closed by jimevans** 2017-10-17 22:54 UTC
