### ISSUE TITLE
Firefox WebDriver could not be verified for Firefox

### ISSUE THREAD

**Issue by shanewignall** [SeleniumHQ/selenium#2565] opened 2016-08-03 19:49 UTC
## Meta -
OS:  Windows 7

Selenium Version:  2.53.1

Browser:  Firefox

Browser Version:  

47.1 64-bit (same with 48 64-bit)
## Expected Behavior -
Firefox WebDriver addon to work properly, allowing selenium tests to work.
## Actual Behavior -
Firefox WebDriver is disabled with an error message "Firefox WebDriver could not be verified for use in Firefox and has been disabled".
## Steps to reproduce -

Use maven with the following dependency:

<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>2.53.1</version>
</dependency>

Set up a firefox profile using the following method:

FirefoxBinary binary = new FirefoxBinary();
File profileFolder = new File("/pathtofolder/profile");
FirefoxProfile profile = new FirefoxProfile(profileFolder);
profile.setAcceptUntrustedCertificates(true);
final WebDriver driver = new FirefoxDriver(binary, profile);

Load a page with driver.get().
Firefox will load a blank window with no URL in the address bar. If you go to the Extensions in the current firefox window, the Firefox WebDriver error will be displayed.

**Comment by lukeis** [comment] 2016-08-03 20:10
you are probably using FF48... it is not disabled in 47.0.1 and thus this is a duplicate of #2559

**Closed by lukeis** 2016-08-03 20:10 UTC

**Comment by shanewignall** [comment] 2016-08-03 21:01
I am using 47.0.1. I tried it in both, got same result.

**Comment by shanewignall** [comment] 2016-08-03 21:04
Yep, I'm just an idiot and clicked the download link for the wrong firefox version twice.
