### ISSUE TITLE
[🐛 Bug]: no_proxy not working

### ISSUE THREAD

**Issue by jramirezmorales** [SeleniumHQ/selenium#13201] opened 2023-11-24 21:55 UTC
### What happened?

trying to open chrome browser behind a corporate proxy is denying request to localhost ignoring no_proxy setting:
java21
selenium 4.15.0
OS oracle/linux

`Proxy proxy = new Proxy();
      proxy.setHttpProxy(PROXY_SERVER);
      proxy.setNoProxy("localhost; 127.0.0.1");
      ChromeOptions options = new ChromeOptions();
      options.addArguments(
          "--headless",
          "--remote-debugging-port=0",
          "--disable-dev-shm-usage",
          "start-maximized",
          "--incognito",
          "--no-sandbox"
      );
      options.setCapability("proxy", proxy);
      options.setBinary("/usr/bin/google-chrome-stable");
      System.setProperty("webdriver.chrome.driver", KUBERNETES_CHROMEDRIVER);
      driver = new ChromeDriver(options);
      driver.get("google.com");
`
the localhost request to open/create a session in chrome browser fail due to begin denied by corporate proxy
"debugInfo":"org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: Cloudproxy denied this request because it didn\u0027t have basic auth credentials. 

localhost should be bypass corporate proxy and is not doing it.

### How can we reproduce the issue?

```shell
Proxy proxy = new Proxy();
      proxy.setHttpProxy(PROXY_SERVER);//use you own proxy server for testing
      proxy.setNoProxy("localhost; 127.0.0.1");
      ChromeOptions options = new ChromeOptions();
      options.addArguments(
          "--headless",
          "--remote-debugging-port=0",
          "--disable-dev-shm-usage",
          "start-maximized",
          "--incognito",
          "--no-sandbox"
      );
      options.setCapability("proxy", proxy);
      options.setBinary("/usr/bin/google-chrome-stable");
      System.setProperty("webdriver.chrome.driver", KUBERNETES_CHROMEDRIVER);
      driver = new ChromeDriver(options);
      driver.get("google.com");
```

### Relevant log output

```shell
"debugInfo":"org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: Cloudproxy denied this request because it didn\u0027t have basic auth credentials. 
....
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)\n\tat org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)\n\tat org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:200)\n\tat org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:175)\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:607)\n\tat org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)\n\tat org.openqa.selenium.remote.RemoteWebDriver.\u003cinit\u003e(RemoteWebDriver.java:168)\n\tat org.openqa.selenium.chromium.ChromiumDriver.\u003cinit\u003e(ChromiumDriver.java:108)\n\tat org.openqa.selenium.chrome.ChromeDriver.\u003cinit\u003e(ChromeDriver.java:89)\n\tat org.openqa.selenium.chrome.ChromeDriver.\u003cinit\u003e(ChromeDriver.java:84)\n\tat org.openqa.selenium.chrome.ChromeDriver.\u003cinit\u003e(ChromeDriver.java:73)\n\t
```

### Operating System

oracle/linux el8

### Selenium version

java21

### What are the browser(s) and version(s) where you see this issue?

Chrome 116

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0.5845.96

**Comment by titusfortner** [comment] 2023-11-25 19:25
Duplicate of #13154 should be fixed in next release, you can test it out with the nightly jar — https://www.selenium.dev/downloads/#nightly

**Closed as not planned by titusfortner** 2023-11-25 19:25 UTC
Labels: I-defect, A-needs-triaging
