### ISSUE TITLE
Node Registration Sometimes Delayed Several Minutes

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#497] opened 2015-04-27 16:51 UTC
https://github.com/SeleniumHQ/docker-selenium/issues/14

I believe this issue is related to that one. On Ubuntu 14.02 with the default-jre, using selenium-standalone-server-2.45.0, I experienced the same problem. The following solution worked: 

https://github.com/SeleniumHQ/docker-selenium/issues/14#issuecomment-66860079

**Comment by ddavison** [comment] 2015-04-27 16:57
(mekhami, this is sircapsalot from IRC)

as I asked you in the IRC channel, could you provide a clear, [concise reproducible case](http://sscce.org/) to the problem?  Otherwise, this issue will be closed for lack of cogency and reproduction.

(please read the [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports) file on how to contribute to issues)

**Comment by mekhami** [comment] 2015-04-27 17:00
I don't know how to make it more clear than this I suppose:
Fresh ubuntu 14.02 install with default-jre.

java -jar selenium-server-standalone-2.45.0.jar -role hub
java -jar selenium-server-standalone-2.45.0.jar -role node -hub http://localhost:4444/grid/register

The node server would not register to the hub for a seemingly random large amount of time. Sometimes 3 minutes, sometimes 30.

**Comment by mach6** [comment] 2016-09-27 22:23
closing as a duplicate of #14 ... this issue is relaed.

**Closed by mach6** 2016-09-27 22:23 UTC
Labels: C-grid

**Comment by mach6** [comment] 2016-09-27 22:26
from https://github.com/SeleniumHQ/docker-selenium/issues/14#issuecomment-66860079
```
apt-get install haveged
service haveged start
update-rc.d haveged defaults
```
should fix it.
