### ISSUE TITLE
[🐛 Bug]: wait.until is not usable

### ISSUE THREAD

**Issue by Clairwai** [SeleniumHQ/selenium#10606] opened 2022-05-04 06:00 UTC
### What happened?

My "wait.until" function worked fine yesterday, but all a sudden now is not runnable.

Error message: reason: no instance(s) of type variable(s) V exist so that ExpectedCondition<WebElement> conforms to Function<? super WebDriver, V>

I have looked it up online, and people said it is related to the inconsistent versions of Guava and Selenium. However, I have already checked my project structure, and there are no other extra versions of Guava and Selenium.

### How can we reproduce the issue?

I am not sure how to reproduce since I don't know what's wrong. 
The only thing I can provide is what I am using. Sorry and thanks.

Please see my pom.xml below:

```shell     
   <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.1.3</version>
        </dependency>

  <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>31.1-jre</version>
     </dependency>

```

The code I have run:
```shell
public void visibilityOfElementLocatedByXpath(String xpath){
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(xpath)));
    }
```

In addition, I am using JAVA 17, maven project with IntelliJ IDEA with MacBook Air (M1,2020).
```
java: method until in class org.openqa.selenium.support.ui.FluentWait<T> cannot be applied to given types;
  required: java.util.function.Function<? super org.openqa.selenium.WebDriver,V>
  found:    org.openqa.selenium.support.ui.ExpectedCondition<org.openqa.selenium.WebElement>
  reason: cannot infer type-variable(s) V
    (argument mismatch; org.openqa.selenium.support.ui.ExpectedCondition<org.openqa.selenium.WebElement> cannot be converted to java.util.function.Function<? super org.openqa.selenium.WebDriver,V>)
```

### Operating System

MacBook Air (M1,2020) - macOS Monterey 12.2.1

### Selenium version

4.1.3

### What are the browser(s) and version(s) where you see this issue?

Not-related

### What are the browser driver(s) and version(s) where you see this issue?

Not-related

### Are you using Selenium Grid?

No

**Comment by Clairwai** [comment] 2022-05-04 06:28
FYI, I can run the same project in my window computer and Mac with Intel CPU. Thanks.

**Comment by diemol** [comment] 2022-05-04 08:36
Can you please provide a GitHub repository with a sample project we can clone to reproduce the issue?

**Comment by titusfortner** [comment] 2022-05-04 20:43
ExpectedCondition used to extend Guava, but no longer does, so those fixes are old.

I suspect that you have a dependency issue on the machine that is having the problem. Please investigate: https://www.javaadvent.com/2020/12/how-to-debug-dependency-conflicts-in-maven-and-gradle.html

My preferred recommendation is to switch to using the lambdas directly, especially if you are wrapping them in methods like this:

```java
public void visibilityOfElementLocatedByXpath(String xpath){
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

        wait.withMessage("waiting for visibility of element located with By.xpath: " + xpath)
                .until(d -> d.findElement(By.xpath(xpath)).isDisplayed());
    }
```

**Comment by diemol** [comment] 2022-05-22 20:00
Closing as we did not get more information.

**Comment by ammmze** [comment] 2022-05-24 20:07
To reproduce this, it depends on the guava version you are using. I just ran across this in a project that has guava 25.1-android. The `ExpectedConditions` extends only the guava `com.google.common.base.Function`. And in my version of guava, that interface looks like this (note that it does NOT extend `java.util.function.Function`:

```java
package com.google.common.base;

public interface Function<F, T> {
    T apply(@NullableDecl F input);
}
```

But compare that to the non-android version which looks like [this](https://github.com/google/guava/blob/v25.1/guava/src/com/google/common/base/Function.java):

```java
package com.google.common.base;

public interface Function<F, T> extends java.util.function.Function<F, T> {
    T apply(@NullableDecl F input);
}
```

To work around it, you can wrap your expected conditions in a custom method defined as:

```java
public static <T> Function<? super WebDriver, T> toFunc(ExpectedCondition<T> expectedCondition) {
    return expectedCondition::apply;
}
```

And usage would then need to be something like:

```java
new FluentWait<>(driver)
    .withTimeout(Duration.ofSeconds(2))
    .until(toFunc(visibilityOf(menuOptions)))
```

Or use a different version of guava.

Ideally, the `ExpectedCondition` class should have been updated to extend `java.util.function.Function`...either alternative or addition to guava.

**Comment by titusfortner** [comment] 2022-05-24 22:27
@ammmze what version of Selenium is this? We shouldn't be depending on Guava any longer.

**Comment by ammmze** [comment] 2022-05-24 22:53
We started seeing this when I just did an upgrade from 3.x to 4.1.4. The dependency is [here](https://github.com/SeleniumHQ/selenium/blob/535d840ee2ed4b6cbe5d00484b9b9681aee75157/java/src/org/openqa/selenium/support/ui/ExpectedCondition.java#L20).

**Comment by ammmze** [comment] 2022-05-24 23:00
But FWIW, I still [see](https://github.com/SeleniumHQ/selenium/search?p=3&q=%22com.google.common%22) lots of stuff pulling in guava stuff.

**Comment by titusfortner** [comment] 2022-05-25 00:46
Welp, I either misread a while back or missed entirely the note on that page for why Selenium uses the Guava Function instead of the Java one. I still have a lot to learn about our Java code. :) Thanks for the explanation.

**Comment by ammmze** [comment] 2022-05-25 03:10
No worries! I _think_ we should be able to resolve this issue as well as keep the guava functionality if we just update the [`ExpectedCondition` interface](https://github.com/SeleniumHQ/selenium/blob/535d840ee2ed4b6cbe5d00484b9b9681aee75157/java/src/org/openqa/selenium/support/ui/ExpectedCondition.java#L38) from being:

```java
public interface ExpectedCondition<T> extends Function<WebDriver, T> {}
```

to be:

```java
public interface ExpectedCondition<T> extends Function<WebDriver, T>, java.util.function.Function<WebDriver, T> {}
```

This should allow it to work with the versions of guava that don't extend the java native `Function` and allowing it to be compatible with the wait `until` method change in the v4 release.

**Comment by titusfortner** [comment] 2022-05-25 06:23
@ammmze would you mind making a PR with the proposed fix? Not sure how easy it'll be to test.

**Comment by ammmze** [comment] 2022-05-26 15:59
@titusfortner I'm not sure there is a feasible way to test it 🤷🏻‍♂️  but [here's that pr](https://github.com/SeleniumHQ/selenium/pull/10695).

**Comment by diemol** [comment] 2022-05-26 21:14
Reading the comments in `ExpectedCondition`, I see:
```
// NB: this originally extended Guava's Function interface since Java didn't have one. To avoid code
// such as "com.google.common.base.Function condition = ExpectedConditions.elementFound(By);"
// breaking at compile time, we continue to extend Guava's Function interface.
```

I wonder how much users' code we would break if we switch to the Java `Function` one.

**Comment by titusfortner** [comment] 2022-05-26 21:46
yeah, i don't know enough how Java inheritance works to know what that does and/or breaks, so @diemol / @pujagani get to decide on it.
But also, seems like it should be possible to require a specific guava implementation that includes it? Or is Java just weird?

**Comment by ammmze** [comment] 2022-05-27 01:06
> I wonder how much users' code we would break if we switch to the Java `Function` one.

Yea...if this was for the 4.0.0 release, I think it would have been fine to entirely swap to the java native one as that would have been a breaking change in that regard.

The effect of just simply adding the java native `Function` to interface (which technically, the signature of the required method is identical to the guava one) should not break anything. It just allows `ExpectedCondition` objects to be assign to java native `Function` as well as guava `Function`.  So both of these should be valid (the latter one is required to work in order to be used the new wait `until` functions, however does NOT work when using some versions of guava...which is this whole bug):

```java
com.google.common.base.Function condition = ExpectedConditions.elementFound(By);
```

```java
java.util.function.Function condition = ExpectedConditions.elementFound(By);
```

**Comment by diemol** [comment] 2022-06-08 12:07
@ammmze do you know if the exception below happens at compile time or at run time?

```
java: method until in class org.openqa.selenium.support.ui.FluentWait<T> cannot be applied to given types;
  required: java.util.function.Function<? super org.openqa.selenium.WebDriver,V>
  found:    org.openqa.selenium.support.ui.ExpectedCondition<org.openqa.selenium.WebElement>
  reason: cannot infer type-variable(s) V
    (argument mismatch; org.openqa.selenium.support.ui.ExpectedCondition<org.openqa.selenium.WebElement> cannot be converted to java.util.function.Function<? super org.openqa.selenium.WebDriver,V>)
```

**Closed as completed** 2022-06-08 12:43 UTC
Labels: J-awaiting answer, I-defect

**Comment by ammmze** [comment] 2022-06-08 14:53
> @ammmze do you know if the exception below happens at compile time or at run time?
> 
> ```
> java: method until in class org.openqa.selenium.support.ui.FluentWait<T> cannot be applied to given types;
>   required: java.util.function.Function<? super org.openqa.selenium.WebDriver,V>
>   found:    org.openqa.selenium.support.ui.ExpectedCondition<org.openqa.selenium.WebElement>
>   reason: cannot infer type-variable(s) V
>     (argument mismatch; org.openqa.selenium.support.ui.ExpectedCondition<org.openqa.selenium.WebElement> cannot be converted to java.util.function.Function<? super org.openqa.selenium.WebDriver,V>)
> ```

Hmm...I'm not 100% sure. I would guess compile time. Most type issues with java are caught at compile time. Did you trigger this error somewhere?

**Comment by diemol** [comment] 2022-06-08 14:55
It is in the original comment.

**Comment by ammmze** [comment] 2022-06-08 15:12
> It is in the original comment.

Oh right...yea...the issue we were seeing here was compile time. So before this was fixed we couldn't compile successfully.
