### ISSUE TITLE
NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by sils1297** [SeleniumHQ/selenium#1831] opened 2016-03-16 16:46 UTC
Sorry for being so brief, I really wanted to let you know about this issue but have no time to reproduce it with a minimal example for you, I cannot share the source code with you, snippets are attached, I hope it suffices for reproducability.

## Meta -

The issue was tested under all the given OSes and versions.

OS: Mac und Linux
Selenium Version: 2.53.0
Browser: Firefox
Browser Version: 36, 42, 45

## Expected Behavior -

It works.

## Actual Behavior -

I get an exception:

```
    self.browser = webdriver.Firefox(DirectDownloadProfile(self.tempdir))
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/firefox/webdriver.py", line 62, in __init__
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/firefox/webdriver.py", line 62, in __init__
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/firefox/webdriver.py", line 62, in __init__
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
NameError: name 'basestring' is not defined
```

## Steps to reproduce -

Used the selenium webdriver with a firefox download profile. It works totally fine with 2.52.0 but it doesn't with 2.53.0.

**Comment by lukeis** [comment] 2016-03-16 16:47
duplicate of #1820

**Closed by lukeis** 2016-03-16 16:47 UTC
