### ISSUE TITLE
[🐛 Bug]: `Failed to set preferences: unknown error` when specify a profile.

### ISSUE THREAD

**Issue by heckad** [SeleniumHQ/selenium#14652] opened 2024-10-25 22:15 UTC
### What happened?

Expected Behavior -
Firefox run withprovided profile

Actual Behavior -
Firefox is not running

### How can we reproduce the issue?

```python
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

firefox_options = Options()
firefox_options.add_argument("--profile D:\\path\\to\\profile\\dir")
driver = webdriver.Firefox(options=firefox_options)
```

Python's traceback
```
Traceback (most recent call last):
  File "/app/tmp/t.py", line 24, in <module>
    driver = webdriver.Firefox(options=firefox_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Failed to set preferences: unknown error
```

### Relevant log output

```shell
1729892750450	geckodriver	INFO	Listening on 127.0.0.1:58119
1729892753487	webdriver::server	DEBUG	-> POST /session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "firefox", "acceptInsecureCerts": true, ... .active-protocols": 3}, "args": ["--profile D:\\path\\to\\profile\\dir"]}}}}
1729892753487	geckodriver::capabilities	DEBUG	Trying to read firefox version from ini files
1729892753488	geckodriver::capabilities	DEBUG	Found version 131.0.3
1729892753488	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"session not created","message":"Failed to set preferences: unknown error","stacktrace":""}}
```

### Operating System

Windows 11

### Selenium version

python 3.12

### What are the browser(s) and version(s) where you see this issue?

131.0.3

### What are the browser driver(s) and version(s) where you see this issue?

GecoDriver 0.35.0

**Comment by Delta456** [comment] 2024-10-26 11:46
The given code is incomplete.

**Comment by heckad** [comment] 2024-10-26 12:57
No, that's really all except two imports (Updated messaged to add them and add python's traceback).

**Comment by navin772** [comment] 2024-10-26 15:25
Hi @heckad, I was able to reproduce this issue on a Windows machine.

Interestingly, this isn't a problem on macOS; the script worked fine, and the required profile was launched.

**Comment by Delta456** [comment] 2024-10-28 08:29
~~Hi @heckad! Can you try this?~~

```py
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

firefox_options = Options()
firefox_options.add_argument(r"--profile D:\\path\\to\\profile\\dir")
driver = webdriver.Firefox(options=firefox_options)
```

### EDIT: This won't fix it, please ignore.

**Comment by heckad** [comment] 2024-10-28 09:15
Yer, in row string mode you can write a path without double slashes.

**Comment by heckad** [comment] 2024-10-28 09:45
I have the same problem on my Linux machine and in Docker too.
Reproducible dockerfile
```dockerfile
FROM python:3.12

# Install Firefox
ARG FIREFOX_VERSION=131.0
RUN echo "deb http://deb.debian.org/debian/ unstable main contrib non-free" >> /etc/apt/sources.list.d/debian.list
RUN apt-get update -qqy \
  && apt-get -qqy --no-install-recommends install firefox \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/* \
  && wget --no-verbose -O /tmp/firefox.tar.bz2 https://download-installer.cdn.mozilla.net/pub/firefox/releases/$FIREFOX_VERSION/linux-x86_64/en-US/firefox-$FIREFOX_VERSION.tar.bz2 \
  && apt-get -y purge firefox \
  && rm -rf /opt/firefox \
  && tar -C /opt -xjf /tmp/firefox.tar.bz2 \
  && rm /tmp/firefox.tar.bz2 \
  && mv /opt/firefox /opt/firefox-$FIREFOX_VERSION \
  && ln -fs /opt/firefox-$FIREFOX_VERSION/firefox /usr/bin/firefox

RUN pip install selenium

RUN cat <<EOF > main.py
import sys
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service

path = Path(__file__).parent / "firefox_profile"

firefox_options = Options()
firefox_options.add_argument(f"--profile {path}")
firefox_options.add_argument("--headless")
firefox_options.log.level = "trace"
driver = webdriver.Firefox(options=firefox_options, service=Service(log_output=sys.stdout))
driver.get("https://google.com")
driver.quit()
EOF

CMD ["python", "main.py"]
```

**Comment by pujagani** [comment] 2024-12-13 08:18
Have you tried using the Profile class? https://github.com/SeleniumHQ/selenium/blob/744e7d60172fbea1893d501b8641f2aa1e785db6/py/selenium/webdriver/firefox/options.py#L90 
Can you please check if that helps?

**Comment by diemol** [comment] 2024-12-23 22:16
I am closing because the OP did not reply.

**Closed as not planned by diemol** 2024-12-23 22:16 UTC
Labels: J-awaiting answer, C-py, I-defect

**Comment by rayanfer32** [comment] 2025-01-12 14:35
The only way I was able to solve this issue was to replace `\\` with `/` in the path
For example:
Replace
`firefox_profile_path = "C:\\Users\rayan\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\c82gocuv.default-release"`
to
`firefox_profile_path = "C:/Users/rayan/AppData/Roaming/Mozilla/Firefox/Profiles/c82gocuv.default-release"`

**Comment by eugene159** [comment] 2025-01-18 19:46
Is there any way to use specific Firefox profile when using Selenium in Windows? I tried with C# but getting the same error as topic starter.

I can get my profile either like this:

FirefoxProfileManager profileManager = new FirefoxProfileManager();
FirefoxProfile profile = profileManager.GetProfile("my_profile_name");

or like this:

FirefoxProfile profile = new FirefoxProfile("C:\\path_to_my_profile";

but when I use this profile like this:

FirefoxOptions options = new FirefoxOptions();
options.Profile = profile;

_driver = new FirefoxDriver(service, options);

the last line throws an exception:

Failed to set preferences: unknown error (SessionNotCreated)

The only ugly workaround is to specify the path directly with options.AddArgument("--profile C:\\path_to_my_profile");
but this ugly workaround works only if you set your profile as default. Otherwise even though it opens up with Selenium, you can't control the session.

**Comment by Axios-Service** [comment] 2025-02-05 16:49
The below works for me

```
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service
from selenium.webdriver.firefox.firefox_profile import FirefoxProfile

geckodriver_path = r"C:\Tools\geckodriver\geckodriver.exe"  # Ensure this path is correct or replace it

options = Options()

profile_path = r"C:\Users\.... path to the profile"
profile = FirefoxProfile(profile_path)
profile.set_preference("app.update.auto", False)
options.profile = profile

service = Service(geckodriver_path)
driver = webdriver.Firefox(service=service, options=options)

driver.get("https://www.google.com")
```

**Comment by eugene159** [comment] 2025-02-05 17:19
If I add
**profile.SetPreference("app.update.auto", false);**
I'm getting an exception:
Preference app.update.auto may not be overridden: frozen value=False, requested value=False

In my case everything blows up pretty much instantly if I create an instance of FirefoxProfile 
**FirefoxProfile profile = new FirefoxProfile(profilePath);**
and attach it to options
**FirefoxOptions options = new FirefoxOptions();
options.Profile = profile;**

The only way I can run Firefox with specific profile is to use the argument in the command line directly
**options.AddArgument("-profile " + profilePath);**
but it works only with the default profile, you can't switch between multiple profiles programmatically.

I read somewhere that FirefoxProfile is obsolete or depricated. Maybe this is why it's not working anymore.
