### ISSUE TITLE
Clicking Elements Inside a Frame no longer works after the frame refreshes in Safari

### ISSUE THREAD

**Issue by Gio77** [SeleniumHQ/selenium#1947] opened 2016-04-08 14:41 UTC
## Meta -
OS: OSX 10.11
Selenium Version: 2.48.0
Browser: Safari
Browser Version: 9.0

## Expected Behavior -
Clicking Element should click
## Actual Behavior -
Clicking Element has not effect
## Steps to reproduce -
I'm testing a Plug-in for Outlook online
I change frame to the one of the Plug-in
I can Enter the UserName, Password, Click Login Button (Frame refreshes after login)
Problem: After the login  I can no longer click any elements on the page.  I can find them, but when it performs the Click, nothing occurs and no error is returned.  
Note that I've tested this in Chrome and it works fine.

**Comment by 5hawnknight** [comment] 2016-05-30 21:14
can you provide the code in which to reproduce the issue?

**Comment by lukeis** [comment] 2016-09-23 20:22
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.

**Closed by lukeis** 2016-09-23 20:22 UTC
