### ISSUE TITLE
[🐛 Bug]: The selenium will open a Chrome(X86_64 translated) on a Mac with M1 chip and the correct drivers and browser installed

### ISSUE THREAD

**Issue by python-zys** [SeleniumHQ/selenium#12195] opened 2023-06-13 07:25 UTC
### What happened?

I had installed a Chrome(Version 114.0.5735.106 (Official Build) (arm64)) and driver(https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac_arm64.zip) on a Mac with M1 chip. But the Selenium opened a Chrome(Version 114.0.5735.106 (Official Build) (x86_64 translated)) every time.

selenium: 4.9.1

### How can we reproduce the issue?

```shell
import unittest
from selenium import webdriver


class GoogleTestCase(unittest.TestCase):

    def setUp(self):
        self.browser = webdriver.Chrome()
        self.addCleanup(self.browser.quit)

    def test_page_title(self):
        self.browser.get('http://www.google.com')
        self.assertIn('Google', self.browser.title)

if __name__ == '__main__':
    unittest.main(verbosity=2)
```

### Relevant log output

```shell
n/a
```

### Operating System

macOS

### Selenium version

Python 4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 114

### What are the browser driver(s) and version(s) where you see this issue?

chromedrive 114.0.5735.90

### Are you using Selenium Grid?

n/a

**Comment by diemol** [comment] 2023-06-13 08:02
>But the Selenium opened a Chrome(Version 114.0.5735.106 (Official Build) (x86_64 translated)) every time.
How do you know this?

Can you share the log output after increasing the logging level? https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by hcooch2ch3** [comment] 2023-06-13 08:25
I have a same issue too.
I went as far as to set excutable_path to chromedriver for apple arm64, but x86_64 chrome is executed.

**Comment by diemol** [comment] 2023-06-13 08:27
@hcooch2ch3 can you please check the previous comment and add logging?

**Comment by python-zys** [comment] 2023-06-13 08:39
> > But the Selenium opened a Chrome(Version 114.0.5735.106 (Official Build) (x86_64 translated)) every time.
> > How do you know this?
> 
> Can you share the log output after increasing the logging level? https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

INFO:selenium.webdriver.common.selenium_manager:Applicable driver not found; attempting to install with Selenium Manager (Beta)
DEBUG:selenium.webdriver.common.selenium_manager:Executing process: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --output json --debug
DEBUG:selenium.webdriver.common.selenium_manager:Using shell command to find out chrome version
DEBUG:selenium.webdriver.common.selenium_manager:Running command: "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --version"
DEBUG:selenium.webdriver.common.selenium_manager:Output: "Google Chrome 114.0.5735.106 "
DEBUG:selenium.webdriver.common.selenium_manager:The version of chrome is 114.0.5735.106
DEBUG:selenium.webdriver.common.selenium_manager:Detected browser: chrome 114
DEBUG:selenium.webdriver.common.selenium_manager:Required driver: chromedriver 114.0.5735.90
DEBUG:selenium.webdriver.common.selenium_manager:Running command: "chromedriver --version"
DEBUG:selenium.webdriver.common.selenium_manager:Output: ""
DEBUG:selenium.webdriver.common.selenium_manager:chromedriver 114.0.5735.90 already in the cache
DEBUG:selenium.webdriver.common.selenium_manager:Using driver at: /Users/yshzhu/.cache/selenium/chromedriver/mac-arm64/114.0.5735.90/chromedriver
DEBUG:selenium.webdriver.common.service:Started executable: `/Users/yshzhu/.cache/selenium/chromedriver/mac-arm64/114.0.5735.90/chromedriver` in a child process with pid: 85763

**Comment by diemol** [comment] 2023-06-13 08:45
This shows that it is using the ARM variant of ChromeDriver, which is correct.
>DEBUG:selenium.webdriver.common.selenium_manager:Using driver at: /Users/yshzhu/.cache/selenium/chromedriver/mac-arm64/114.0.5735.90/chromedriver
DEBUG:selenium.webdriver.common.service:Started executable: /Users/yshzhu/.cache/selenium/chromedriver/mac-arm64/114.0.5735.90/chromedriver in a child process with pid: 85763

**Comment by diemol** [comment] 2023-06-13 08:46
Thanks for sharing the logs, I will close this as the logs show things are working as expected.

**Closed as not planned by diemol** 2023-06-13 08:46 UTC
Labels: J-awaiting answer, I-defect

**Comment by titusfortner** [comment] 2023-06-13 11:42
Is the issue that it is opening the wrong version of Chrome? Selenium doesn't download the browser for you (yet). You can either uninstall the undesired browser, or you can specify the location of the desired browser with the binary property on the chrome options instance.

**Comment by python-zys** [comment] 2023-06-14 02:21
> Is the issue that it is opening the wrong version of Chrome? Selenium doesn't download the browser for you (yet). You can either uninstall the undesired browser, or you can specify the location of the desired browser with the binary property on the chrome options instance.

Thanks for your reply. The fact is that when I manually opening my local chrome , it was the arm version, but when I opened it with Selennium, it became x86. I'm still analyzing what's going on here

**Comment by jnhyperion** [comment] 2023-06-14 03:19
We found the root cause, it's because our python interpriter is x86_64 version. On Mac M1 the x86_64 python will start subprocess in "x86_64 translated" mode (I guess it's using "arch -x86_64" command).

To fix this, you need to re-install your python with the Mac OS universal version.
correct one:
<img width="409" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/20297196/58046ae5-2793-4a8d-aec1-f7cbf3986922">

wrong one:
<img width="322" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/20297196/bfec14e0-8ebb-4147-9056-1d2e3a4927f2">

you also need to check the python supported arch in installation:
<img width="1180" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/20297196/dabe75ea-36e6-44ac-b707-d59c73368a3d">

**Comment by hcooch2ch3** [comment] 2023-06-14 04:56
@jnhyperion 
It works. Thanks!
I spent the whole day trying to solve this problem, but thanks to your help, I was able to resolve it. It turned out that it wasn't an issue with the Chrome driver or Selenium, but rather a Python problem.
