### ISSUE TITLE
[🐛 Bug]: Selenium 4.22.0 exception when creating an Appium driver

### ISSUE THREAD

**Issue by DanMcNamee42** [SeleniumHQ/selenium#14243] opened 2024-07-09 22:26 UTC
### What happened?

When attempting to create an Appium driver when WebDriver 4.22.0 is installed with the release version of 5.0.0 of Appium, the following exception is generated:

Test method UnitTests.F1Mobile.Android.AndroidUnitTest.AppiumAndroidDriverTest threw exception: 
OpenQA.Selenium.WebDriverException: Your driver may be out of date or unsupported. ---> System.TypeLoadException: Method 'ExecuteAsync' in type 'OpenQA.Selenium.Appium.Service.AppiumCommandExecutor' from assembly 'Appium.Net, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Rolling back to 4.21.0 resolves the issue.  From looking at the error message, the version given for Appium is 5.0.0.0, which contains an extra .0 over the actual Appium version installed, maybe this is the source of the conflict?

### How can we reproduce the issue?

```shell
public static AppiumDriver GetAndroidDriver(Uri mobileHub, AppiumOptions options, TimeSpan timeout)
        {
            return CreateDriver(() =>
            {
                var driver = new AndroidDriver(mobileHub, options, timeout);
                return driver;
            });
        }
```

### Relevant log output

```shell
2024-07-09 22:19:55.791
INFORMATION:	Setup test object for UnitTests.F1Mobile.Android.AndroidUnitTest.AppiumAndroidDriverTest

2024-07-09 22:19:58.512
ERROR:	
Your driver may be out of date or unsupported.
   at F1Mobile.BaseTestAppium.CreateDriver(Func`1 createFunction) in C:\Users\DMcnamee\source\repos\F1 1\F1Mobile\BaseTestAppium.cs:line 62
   at F1Mobile.BaseTestAppium.GetAndroidDriver(Uri mobileHub, AppiumOptions options, TimeSpan timeout) in C:\Users\DMcnamee\source\repos\F1 1\F1Mobile\BaseTestAppium.cs:line 75
   at F1Mobile.BaseTestAppium.GetMobileDevice() in C:\Users\DMcnamee\source\repos\F1 1\F1Mobile\BaseTestAppium.cs:line 155
   at OpenMAQS.Maqs.BaseAppiumTest.BaseAppiumTest.<CreateSpecificTestObject>b__6_0()
   at OpenMAQS.Maqs.BaseTest.DriverManager.GetBase()
   at OpenMAQS.Maqs.BaseAppiumTest.AppiumDriverManager.GetAppiumDriver()
   at OpenMAQS.Maqs.BaseAppiumTest.AppiumTestObject.get_AppiumDriver()
   at UnitTests.F1Mobile.Android.AndroidUnitTest.AppiumAndroidDriverTest() in C:\Users\DMcnamee\source\repos\F1 1\UnitTests\F1Mobile\Android\AndroidUnitTest.cs:line 26
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
  Method 'ExecuteAsync' in type 'OpenQA.Selenium.Appium.Service.AppiumCommandExecutor' from assembly 'Appium.Net, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
     at OpenQA.Selenium.Appium.AppiumDriver..ctor(Uri remoteAddress, ICapabilities appiumOptions, TimeSpan commandTimeout, AppiumClientConfig clientConfig)
   at OpenQA.Selenium.Appium.AppiumDriver..ctor(Uri remoteAddress, ICapabilities appiumOptions, TimeSpan commandTimeout)
   at OpenQA.Selenium.Appium.Android.AndroidDriver..ctor(Uri remoteAddress, DriverOptions driverOptions, TimeSpan commandTimeout)
   at F1Mobile.BaseTestAppium.<>c__DisplayClass1_0.<GetAndroidDriver>b__0() in C:\Users\DMcnamee\source\repos\F1 1\F1Mobile\BaseTestAppium.cs:line 77
   at F1Mobile.BaseTestAppium.CreateDriver(Func`1 createFunction) in C:\Users\DMcnamee\source\repos\F1 1\F1Mobile\BaseTestAppium.cs:line 39

2024-07-09 22:19:58.523
ERROR:	Test failed
```

### Operating System

Windows 11

### Selenium version

C# 4.22.0

### What are the browser(s) and version(s) where you see this issue?

Appium 5.0.0

### What are the browser driver(s) and version(s) where you see this issue?

Appium 5.0.0

### Are you using Selenium Grid?

No Grid.

**Comment by diemol** [comment] 2024-07-10 07:24
Duplicate of #14182

**Closed as not planned by diemol** 2024-07-10 07:24 UTC
Labels: I-defect, A-needs-triaging
