### ISSUE TITLE
Selenium Server - Invalid HTTP method: PATCH

### ISSUE THREAD

**Issue by sebastienbonami** [SeleniumHQ/selenium#652] opened 2015-06-11 19:24 UTC
Hi, some functionalities of our API use the PATCH (HTTP) method. Running our test suites with Selenium IDE works well, but not with Selenium Server (using selenium-server-standalone-2.46.0.jar).

The following error appear in the console:
``java.net.ProtocolException: Invalid HTTP method: PATCH``

In debug mode, I found that the version of Jetty is 5.1.x. It's rather old so maybe it doesn't support the PATCH method? Is it possible to change the version of Jetty?

Thanks in advance!

**Comment by sebastienbonami** [comment] 2015-09-02 21:00
I'm still waiting for an answer on this issue. Can someone help me on that? Thanks.

**Comment by barancev** [comment] 2015-09-20 10:10
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment] 2016-01-27 05:45
Closing the issue as there is no responce from the author for long time.

(BTW, Selenium uses Jetty 9 now, so may be the issue is fixed)

**Closed by barancev** 2016-01-27 05:45 UTC
Labels: C-java, E-less easy, I-defect, R-awaiting answer
