### ISSUE TITLE
Cannot start clean session, nor delete cookies on Safari

### ISSUE THREAD

**Issue by frbk** [SeleniumHQ/selenium#1196] opened 2015-10-27 16:18 UTC
I am using the latest version of selenium driver 2.48 with ruby 2.2.3. 
I have been trying to force Safari to run with ```ensureCleanSession``` but it ignores it.
```delete_all_cookies``` does not work as well. I also tried deleting  ```Cookies.banarycookies``` but Safari still loads with cookies present.

**Comment by titusfortner** [comment] 2015-11-01 16:32
I can add and delete and delete all cookies with 2.48 and ruby 2.2.3. 

Read through [this issue](https://code.google.com/p/selenium/issues/detail?id=5212) to see if it fits the issues you are seeing with your cookies.

[This comment](https://github.com/SeleniumHQ/selenium/issues/821#issuecomment-134720980) indicates that it is working for ruby directly, but not via remote driver; which are you using?

**Comment by rets5s** [comment] 2015-11-02 13:57
I am able to delete cookies with applescript, however, it adds extra 15-20 sec to the test. Capabilities still don't work so I can't enforce clean session. Can you possibly show the way you did it @titusfortner?

**Comment by titusfortner** [comment] 2015-11-02 17:41
rets5s: These specs all pass on Safari - https://github.com/SeleniumHQ/selenium/blob/master/rb/spec/integration/selenium/webdriver/options_spec.rb#L54

The method proscribed above does not work for a new session? Is the use case creating a cookie, killing the driver, initializing a new driver and still seeing the cookies? The selenium specs don't continue to see the cookies, so I can't reproduce it directly. Do you have a test case that I can reproduce to see the problem?

**Comment by PeterMichalko** [comment] 2016-01-22 09:01
I also have problem, 
I set Safari DesiredCapabilities: 'cleanSession' and 'ensureCleanSession' to 'True' from Robot Framework, but the browser ignores it. Local storage is not cleared.

Detected with: selenium (2.49.0)  and Safari Driver 2.48.0 and selenium-server-2.49.1
robotframework-selenium2library (1.7.4)
Safari 9.0.3 (10601.4.4) 

part of execution log:
09:46:37.792 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:54018/wd/hub
09:46:37.793 INFO - Selenium Server is up and running
09:46:47.581 INFO - Executing: [new session: Capabilities [{ensureCleanSession=true, browserName=safari, javascriptEnabled=true, cleanSession=true, version=, platform=MAC}]])
09:46:47.590 INFO - Creating a new session for Capabilities [{ensureCleanSession=true, browserName=safari, javascriptEnabled=true, cleanSession=true, version=, platform=MAC}]
09:46:47.654 INFO - Server started on port 14017
09:46:47.664 INFO - Launching Safari
09:46:47.673 INFO - Waiting for SafariDriver to connect
09:46:48.889 INFO - Connection opened
09:46:48.891 INFO - Driver connected in 1217 ms
09:46:48.932 INFO - Done: [new session: Capabilities [{ensureCleanSession=true, browserName=safari, javascriptEnabled=true, cleanSession=true, version=, platform=MAC}]]

**Comment by appsgodfather** [comment] 2016-01-22 14:54
The same problem with Java and selenium. 
"ensureCleanSession" and "cleanSession" capabilities doesn't help

**Comment by vveliev** [comment] 2016-01-22 15:36
Incorrect use of configs .... note each browser have different options:

Safari : ```@config[:capabilities]['safari.options'] = { cleanSession: true }```
IE : ```@config[:capabilities]['ie.ensureCleanSession'] = true```
Firefox: ```@config[:capabilities][:profile] = Selenium::WebDriver::Firefox::Profile.new```
Edge: ```@config[:capabilities]['ensureCleanSession'] = true```

```caps = Selenium::WebDriver::Remote::Capabilities.send(@browser_name, @config[:capabilities])```

I'm using ruby .... so convert to your needs

**Comment by PeterMichalko** [comment] 2016-01-22 16:37
Please, can anyone advice how to apply this to Robot Framework?
Currently I'm using it as following, but it does not work:
`${dc}    Evaluate    sys.modules['selenium.webdriver'].DesiredCapabilities.SAFARI    sys, selenium.webdriver
Set To Dictionary    ${dc}    ensureCleanSession=${True}    cleanSession=${True} 
Open Browser    ${url}    browser=${browser}    desired_capabilities=${dc}`

**Comment by daluu** [comment] 2016-01-29 18:44
@PeterMichalko for the RobotFramework case, you might want to post the question to RF user groups/forums to confirm the keyword command syntax you used are correct as expected or not. Not a lot of folks use RF in the greater Selenium community.

**Comment by atcarmo** [comment] 2016-07-19 14:43
In fact it is not possible to clear cookies/cache. I tried with Java and C#.

In Java there is a method `setUseCleanSession` that is supposed to delete existing session data (including cookies, cache, and other elements). It simply doesn't work.

In C# there is no such method but I tried various ways of adding the capability to the browser but it also doesn't work.

My environment is:
- SeleniumGrid version 2.53.1 hub started on a Mac
- Selenium Grid node started on a Mac (El Capitan, with Safari 9.1.1 with the WebDriver extension 2.48)
- Tests written in C# or Java (in a Windows Machine) using RemoteWebDriver to start Safari on my SeleniumGrid
- Selenium version 2.53.1

I observed that, while I request the capability `safari.options={cleanSession=true}`, it is not present in the list of capabilities of the actual browser given to me by SeleniumGrid.

**Comment by freezer-glp** [comment] 2016-07-21 10:06
I have the same problem too in using Selenium Grid with c#. I can not clear cookies/cache in remoteDriver. C# even does nos has clear cache method on IE, Edge, Safari.

**Comment by daluu** [comment] 2016-07-21 20:15
With the new Safari driver coming with next Mac OS X (Sierra), perhaps this issue will be solved there. And if not, then pester Apple about it? Since the current SafariDriver this is with respect to is being "deprecated".

On a related note, for those experiencing the issue, can you work around it by specifically deleting cookies with SafariDriver after the browser session is established? Whether deleting all cookies or specific cookies, the trick for this workaround though is that you have to be on the domain you are testing against (or working with) in order to delete cookies for it. So don't expect to be able to delete cookies for Google while on yahoo.com page. I used this workaround to be  a failsafe in test automation, where if the browser is Safari, I would always add this step to navigate to the test site's homepage, then delete all cookies, then refresh page - all as part of test setup, then proceed with the testing. I believe I did this for IE too.

**Comment by freezer-glp** [comment] 2016-07-22 02:08
@daluu Did you mean go to the test page first and then do some cleaning work using js excecutor?
could you give some sample code here? Thx

**Comment by daluu** [comment] 2016-07-22 04:47
@freezer-glp you have 2 options for the cleaning work after landing on the test page 1st:

* call Selenium cookie API method to delete (all) cookies, or delete specific cookie. The syntax varies by language binding. This method works for Selenium RC and WebDriver, but the API syntax is different between the two. An example: ```driver.manage().deleteAllCookies(); //in Java WebDriver```

* execute javascript to do the same thing. Generally best to use the Selenium APIs. But if you did want to go JS route, you could search for things like "javascript clear cookies" and similar terms, which lead me to these for example: http://stackoverflow.com/questions/179355/clearing-all-cookies-with-javascript, http://stackoverflow.com/questions/595228/how-can-i-delete-all-cookies-with-javascript

**Comment by lukeis** [comment] 2016-09-23 20:14
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.

**Closed by lukeis** 2016-09-23 20:14 UTC
Labels: A-needs new owner, D-safari

**Comment by daluu** [comment] 2016-09-23 22:04
FYI, because Apple doesn't share reported bugs and their status updates to the public, only the reporter of the bug, it would be good for those who file bugs to also file a duplicate at

https://openradar.appspot.com/

and update the clone whenever there is an update to the filed bug, so that the rest of the community can check status and not need to file duplicate bugs.

It's unfortunate that Apple chose to have a closed bug reporting system. Confidential bugs may make sense, but many aren't.
