### ISSUE TITLE
Unable to capture full website screenshot using Selenium 3.4 in Firefox (53.0) driver.

### ISSUE THREAD

**Issue by yadavky** [SeleniumHQ/selenium#3952] opened 2017-05-01 17:15 UTC
## Meta -
OS:  
Windows 7
Selenium Version:  
3.4.0
Browser:  
Firefox

Browser Version:  
53.0 (32-bit)

## Expected Behavior -
Unable to capture full website screenshot.
## Actual Behavior -
Firefox driver only capture viewport of the screen.
## Steps to reproduce -
used the following code to capture screenshot:
            var path = String.Format(@"...\Temp\website-Desktop.png");
            var profile = new FirefoxProfile();
            IWebDriver wd = new FirefoxDriver(profile);
            wd.Navigate().GoToUrl(url);
            wd.Manage().Window.Maximize();           
            Screenshot ss = ((ITakesScreenshot)wd).GetScreenshot();            
            ss.SaveAsFile(path, ImageFormat.Png);
            wd.Quit();

**Comment by lmtierney** [comment] 2017-05-01 17:43
Duplicate of #3912

**Closed by lmtierney** 2017-05-01 17:43 UTC

**Comment by yadavky** [comment] 2017-05-01 19:44
@lmtierney You have mentioned that it is very hard to capture the "entire page" since it is hard to define that. What happens if the page is lazy loaded or never-ending? 
But in the earlier version of selenium i.e. 2, it was capable to taking full page screenshot using Firefox. 
Is not there something can do it for latest version of selenium i.e. 3.4?

**Comment by lmtierney** [comment] 2017-05-01 20:35
This is not a selenium issue but a driver issue. You can use the legacy selenium Firefox driver instead of geckodriver. Anything implementing w3c will only take the viewport, see https://w3c.github.io/webdriver/webdriver-spec.html#take-screenshot
