### ISSUE TITLE
[🐛 Bug]: Elements rendered using vue fragment cannot be located using selenium By.LINK_TEXT

### ISSUE THREAD

**Issue by susan20150801** [SeleniumHQ/selenium#11140] opened 2022-10-18 04:05 UTC
### What happened?

Elements rendered using vue fragment cannot be located using selenium By.LINK_TEXT

### How can we reproduce the issue?

```shell
render elements using the vue fragment
```

### Relevant log output

```shell
raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"test-bid-221018115809"}
E         (Session info: chrome=106.0.5249.119)
E       Stacktrace:
E       Backtrace:
E       	Ordinal0 [0x00441ED3+2236115]
E       	Ordinal0 [0x003D92F1+1807089]
E       	Ordinal0 [0x002E66FD+812797]
E       	Ordinal0 [0x003155DF+1005023]
E       	Ordinal0 [0x003157CB+1005515]
E       	Ordinal0 [0x00347632+1209906]
E       	Ordinal0 [0x00331AD4+1120980]
E       	Ordinal0 [0x003459E2+1202658]
E       	Ordinal0 [0x003318A6+1120422]
E       	Ordinal0 [0x0030A73D+960317]
E       	Ordinal0 [0x0030B71F+964383]
E       	GetHandleVerifier [0x006EE7E2+2743074]
E       	GetHandleVerifier [0x006E08D4+2685972]
E       	GetHandleVerifier [0x004D2BAA+532202]
E       	GetHandleVerifier [0x004D1990+527568]
E       	Ordinal0 [0x003E080C+1837068]
E       	Ordinal0 [0x003E4CD8+1854680]
E       	Ordinal0 [0x003E4DC5+1854917]
E       	Ordinal0 [0x003EED64+1895780]
E       	BaseThreadInitThunk [0x77006739+25]
E       	RtlGetFullPathName_UEx [0x779F8FD2+1218]
E       	RtlGetFullPathName_UEx [0x779F8F9D+1165]

..\..\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py:247: NoSuchElementException
```

### Operating System

windows11

### Selenium version

4.5.0和4.1.0

### What are the browser(s) and version(s) where you see this issue?

chrome106

### What are the browser driver(s) and version(s) where you see this issue?

106.0.5249.119

**Comment by susan20150801** [comment] 2022-10-18 04:07
![image](https://user-images.githubusercontent.com/40201838/196333177-a12e289e-78bc-49cb-93db-e7c187c1ed11.png)

![image](https://user-images.githubusercontent.com/40201838/196333198-917a4fae-7481-48c0-bfc3-68875d6d2b5a.png)

**Comment by titusfortner** [comment] 2022-10-18 12:17
This is a duplicate of #9668

TL/DR - It's a bug in Vue that we might be able to compensate for by updating our isDisplayed atom, but that would require a *lot of work and isn't in our immediate future.

**Closed as completed by titusfortner** 2022-10-18 12:17 UTC
Labels: I-defect, A-needs-triaging
