### ISSUE TITLE
[🐛 Bug]: SeleniumLibrary - Edge webdriver failed: KeyError: 'MicrosoftEdge'

### ISSUE THREAD

**Issue by wancy2024** [SeleniumHQ/selenium#13439] opened 2024-01-15 05:17 UTC
### What happened?

I have just update my edge browser to version 120.0.2210.61 and updated edge webdriver to 120.0.2210.133. When i run my automated robot framework test case and i got this error :

20240115 05:24:00.585 :  INFO : ${Selenium2Library} = <Selenium2Library.Selenium2Library object at 0x00000163B2B7F550>
20240115 05:24:00.585 :  INFO : ${Selenium2LibraryCapabilities} = {'acceptInsecureCerts': False, 'browserName': 'MicrosoftEdge', 'browserVersion': '120.0.2210.61', 'fedcm:accounts': True, 'ms:edgeOptions': {'debuggerAddress': 'localhost:64718'}, 'msedge': {'msedgedr...
20240115 05:24:00.601 :  INFO : ${BROWSERtype} = MicrosoftEdge
20240115 05:24:00.601 :  INFO : ${BROWSERversion} = 120.0.2210.61
20240115 05:24:00.601 :  FAIL : Resolving variable '${Selenium2LibraryCapabilities['MicrosoftEdge']}' failed: KeyError: 'MicrosoftEdge'

I have no issue when using Edge browser 115.0.1901.200 with edge webdriver 115.0.1901.200. After this version upgrade, i got this issue.

Can please help to advice what is wrong at here? Thanks in advance.

Here are the version i am using 
robot framework                     6.0.2
robotframework-ride                2.0b3
robotframework-selenium2library    3.0.0
robotframework-seleniumlibrary     6.0.0
selenium                           4.9.0

### How can we reproduce the issue?

```shell
I am using Robot Framework DEBUG button to get the message log.
```

### Relevant log output

```shell
20240115 06:14:09.660 :  FAIL : Resolving variable '${Selenium2LibraryCapabilities['MicrosoftEdge']}' failed: KeyError: 'MicrosoftEdge'
Starting test: Stdsrobot.Testcases.MyStandards.0000 Special Tasks.0000 Log Current Browser.Log Current Browser
Ending test: Stdsrobot.Testcases.MyStandards.0000 Special Tasks.0000 Log Current Browser.Log Current Browser

20240115 06:14:09.680 : DEBUG : DELETE http://localhost:65181/session/9c6e0cf5f91b07c66496f986c841003a/cookie {}
20240115 06:14:09.687 : DEBUG : http://localhost:65181 "DELETE /session/9c6e0cf5f91b07c66496f986c841003a/cookie HTTP/1.1" 200 14
20240115 06:14:09.687 : DEBUG : Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
20240115 06:14:09.687 : DEBUG : Finished Request
20240115 06:14:09.687 :  INFO : ${passed} = True
20240115 06:14:09.688 : DEBUG : Closing all browsers.
20240115 06:14:09.689 : DEBUG : DELETE http://localhost:65181/session/9c6e0cf5f91b07c66496f986c841003a {}
20240115 06:14:09.816 : DEBUG : http://localhost:65181 "DELETE /session/9c6e0cf5f91b07c66496f986c841003a HTTP/1.1" 200 14
20240115 06:14:09.816 : DEBUG : Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
20240115 06:14:09.816 : DEBUG : Finished Request
```

### Operating System

WINS 10

### Selenium version

selenium2library 3.0.0

### What are the browser(s) and version(s) where you see this issue?

Edge browser 120.0.2210.61

### What are the browser driver(s) and version(s) where you see this issue?

Edge webdriver 120.0.2210.133

### Are you using Selenium Grid?

No

**Comment by diemol** [comment] 2024-01-15 09:10
You either need to provide a way to reproduce this only using Selenium or you need to report this to the selenium2library project.

**Comment by diemol** [comment] 2024-01-25 08:49
I am closing this because we did not get more information. We can reopen if more information is provided.

**Closed as not planned by diemol** 2024-01-25 08:49 UTC
Labels: I-defect, J-issue-template
