### ISSUE TITLE
File Uploads Don't Work with Server

### ISSUE THREAD

**Issue by kndani** [SeleniumHQ/selenium#9696] opened 2021-07-29 19:47 UTC
## 🐛 Bug Report

We recently move to Selenium 4.0.0.beta4 and we found that file uploading is not working with Server. It works fine on local but get error `Selenium::WebDriver::Error::UnknownCommandError` with Server. As per issue #8524 this was fixed but somehow I still see this issue with 4.0.0.beta4

## Last working Selenium Version
3.142.7

## Stopped working in version:
4.0.0.beta4

## To Reproduce
I cannot share the details of application but I think you can reproduce it with any uploading option on page

## Error

     unknown command: unknown command: session/8123fe3a92a432334462657c28fa033e/se/file (Selenium::WebDriver::Error::UnknownCommandError)
     #0 0x5645c63e5e89 <unknown>
    /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/response.rb:56:in 'assert_ok'
    /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/response.rb:35:in 'initialize'
    /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/http/common.rb:83:in 'new'
    /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/http/common.rb:83:in 'create_response'
    /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/http/default.rb:109:in 'request'
    /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/http/common.rb:59:in 'call'
    /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/bridge.rb:576:in 'execute'
    /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/bridge.rb:426:in 'upload'
    /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/bridge.rb:410:in 'block in send_keys_to_element'
    /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/bridge.rb:410:in 'map'
    /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/remote/bridge.rb:410:in 'send_keys_to_element'
    /Users/karimnarsindani/.rvm/gems/ruby-3.0.1/gems/selenium-webdriver-4.0.0.beta4/lib/selenium/webdriver/common/element.rb:208:in 'send_keys'

## Expected behavior

File to be successfully upload

## Acutal Behavior
     unknown command: unknown command: session/8123fe3a92a432334462657c28fa033e/se/file (Selenium::WebDriver::Error::UnknownCommandError)
     #0 0x5645c63e5e89 <unknown>

## Environment

OS: All
Browser: Chrome (We only support chrome)
Browser version: 90.0
Language Bindings version: Ruby
Selenoid: Latest Version

**Comment by diemol** [comment] 2021-07-30 20:27
@kndani this is a duplicate of #9350 

You can get more context by reading the comments in the linked issue.

**Closed as completed by diemol** 2021-07-30 20:27 UTC
