### ISSUE TITLE
C# RemoteWebDriver.GetAttribute() Converts Attribute Values That Are ISO DateTimes To Local Culture DateTime Strings

### ISSUE THREAD

**Issue by martincostello** [SeleniumHQ/selenium#1180] opened 2015-10-21 17:52 UTC
Since updating to version 2.48.0 of the Selenium.WebDriver NuGet package earlier today, an assert on a test that I have has started to fail.

The test in question is asserting on the value of a data attribute which holds a date and time in ISO 8601 format (```yyyy-MM-ddTHH:mm:ssZ```). This format is being specifically used to account for differences in time zones so that tests can be run consistently and that times are correctly interpreted as UTC times by relevant application code.

Since the update the value returned by ```RemoteWebDriver.GetAttribute(string)``` has changed format. Where previously the call returned ```2015-11-04T23:59:59``` (the raw value of the relevant attribute) it now returns ```04/11/2015 23:59:59``` on my Windows 7 SP1 computer configured to use UK English.

I'm guessing the offender is [this line of code](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Remote/RemoteWebElement.cs#L428).

If ```commandResponse.Value``` is a ```DateTime``` value, then the default behaviour of ```DateTime.ToString()``` is to format the date string for the current culture. My guess would be that something that has changed which is causing the value to be converted to a ```DateTime```, rather than being left alone as a ```string``` (which is what it is, given attributes are just strings).

Either:

  1. Attribute values should not be converted to any other data type and left as their raw values by whatever the underlying code that is fetching the attribute's value from the browser in the first place;
  1. ```Convert.ToString(object, IFormatProvider)``` should be used with ```CultureInfo.InvariantCulture``` instead of ```object.ToString()``` so that culture-specific formatting rules (commas, decimals, date formats etc.) are not applied when ```commandResponse.Value``` is converted into a ```string```.

There are similar calls to ```commandResponse.Value.ToString()``` throughout the code for this class (lines 83, 99, 428 and 465), so other methods in the ```RemoteWebDriver``` class could be similarly affected depending on the context.

**Comment by jimevans** [comment] 2015-10-21 18:05
Duplicate of #1120

**Closed by jimevans** 2015-10-21 18:05 UTC
