### ISSUE TITLE
[🐛 Bug]: Javascript code from isDisplayed.js defining _ overwrites underscore _ namespace

### ISSUE THREAD

**Issue by isparks-tg** [SeleniumHQ/selenium#12750] opened 2023-09-15 11:42 UTC
### What happened?

Upgraded to selenium=4.12.0 and started to get "_.each" is not defined errors in my tests.

We use underscore.js and the _ object did exist but appeared to be defined as:

`function(a,b){function c(d){if(W(d)&&"none"==Y(d,"display"))return!1;var e;if((e=d.parentNode)&&e.shadowRoot&&void 0!==d.assignedSlot)e=d.assignedSlot?d.assignedSlot.parentNode:null;else if(d.getDestinationInsertionPoints){var f=d.getDestinationInsertionPoints();0<f`

But it is the definition of the function from isDisplayed defined at line 100:

`ba("_",function(a,b){function c(d){if(W(d)&&"none"==Y(d,"display"))return!....`

My hypothesis is that this selenium function is clobbering the _ global but can't see how.

Reverting to selenium==4.11.2 solved this for me with no other code changes.

### How can we reproduce the issue?

```shell
from selenium.webdriver import Chrome
from selenium.webdriver.common.by import By


if __name__ == "__main__":
    browser = Chrome()
    browser.get("https://www.example.com/")

    # Define _ on the window just as underscore does
    browser.execute_script("window._ = function() { return 1 };")
    one = browser.execute_script("return _();")
    assert one == 1

    # Now get a heading and check its displayed
    heading = browser.find_element(By.TAG_NAME, "h1")
    assert heading.is_displayed()

    # Here we go, this works with 4.11.12 but not with 4.12.0
    again = browser.execute_script("return _();")
    assert again == 1


    browser.quit()
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/isparks/.config/JetBrains/PyCharm2023.1/scratches/chrome_test.py", line 21, in <module>
    again = browser.execute_script("return _();")
  File "/home/isparks/envs/nexus3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 404, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "/home/isparks/envs/nexus3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/home/isparks/envs/nexus3.10/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Argument to isShown must be of type Element
  (Session info: chrome=117.0.5938.62)
Stacktrace:
#0 0x561ab133a693 <unknown>
#1 0x561ab10101e7 <unknown>
#2 0x561ab101513e <unknown>
#3 0x561ab1016caa <unknown>
#4 0x561ab1092e0f <unknown>
#5 0x561ab10790c2 <unknown>
#6 0x561ab1092322 <unknown>
#7 0x561ab1078e93 <unknown>
#8 0x561ab104b934 <unknown>
#9 0x561ab104c71e <unknown>
#10 0x561ab12ffc98 <unknown>
#11 0x561ab1303bd0 <unknown>
#12 0x561ab130e17c <unknown>
#13 0x561ab13047e8 <unknown>
#14 0x561ab12d125f <unknown>
#15 0x561ab1328e68 <unknown>
#16 0x561ab1329039 <unknown>
#17 0x561ab1339823 <unknown>
#18 0x7fb406e94b43 <unknown>
```

### Operating System

Ubuntu

### Selenium version

selenium=4.12.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 117 / Chrome 113

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 117.0.5938.62

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment] 2023-09-15 14:06
Thanks for reporting.
Duplicate of #12659 
Already fixed in trunk waiting for next release.

**Closed as completed by titusfortner** 2023-09-15 14:06 UTC
Labels: I-defect, A-needs-triaging
