### ISSUE TITLE
kendo inline editing not working on IE11

### ISSUE THREAD

**Issue by idan1972** [SeleniumHQ/selenium#870] opened 2015-08-02 19:36 UTC
Hi,

I am trying to set value to textarea inside kendo grid.
I chrome it works OK.
In IE I am able to enter the value to the textarea using sendKeys but when click "Save" in my application the data i enter is cleared.

Example for that can be found in the kendo demo page: http://demos.telerik.com/kendo-ui/grid/editing-inline

I use nativeElements= false.

Code I used:
        WebDriver driver = new InternetExplorerDriver(capabilities);
        driver.get("http://demos.telerik.com/kendo-ui/grid/editing-inline");
        driver.findElement(By.xpath(".//_[@id='grid']/div[3]/table/tbody/tr[1]/td[5]/a[1]")).click();
        driver.findElement(By.xpath(".//_[@id='grid']/div[3]/table/tbody/tr[1]/td[1]/input")).sendKeys("newVal");
        driver.findElement(By.xpath(".//*[@id='grid']/div[3]/table/tbody/tr[1]/td[5]/a[1]")).click();

**Comment by barancev** [comment] 2016-12-13 21:43
Is this issue is actual? I can't reproduce it with IEDriverServer 2.53.1

**Comment by jimevans** [comment] 2017-03-19 14:47
No answer since December. Closing.

**Closed by jimevans** 2017-03-19 14:47 UTC
Labels: D-IE, R-awaiting answer
