### ISSUE TITLE
[🐛 Bug]: org.openqa.selenium.WebDriverException: disconnected: not connected to DevTools

### ISSUE THREAD

**Issue by evalalos** [SeleniumHQ/selenium#13348] opened 2023-12-21 17:30 UTC
### What happened?

Hello,

I have project which worked totally fine on MacBook Pro with Intel chip, few days ago I've bought new MacBook Pro with M3 Pro chip and migrated everything using Migration Assistant, and after running the test which worked totally fine on old MacBook, now it keeps failing randomly. So, the test is started, some steps are executed properly, and at some point it fails with 'disconnected: not connected to DevTools' exception. 
Sometimes, but very rarely it works until the end of the test. Checked almost everything, maybe it is not related to the new MacBook. 
My chromedriver is compatible with the Chrome browser (it won't start if it's incompatible, but it is started). 
selenium-java: 3.141.59
selenium-server: 3.141.59

### How can we reproduce the issue?

```shell
The project is very complex, and it will take a lot of time to paste everything here or to create github repo. Also, due to security policy, I cannot share the code.

Thanks for understanding.
```

### Relevant log output

```shell
Connected to the target VM, address: '127.0.0.1:64011', transport: 'socket'
Using following user agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Starting ChromeDriver 120.0.6099.109 (3419140ab665596f21b385ce136419fde0924272-refs/branch-heads/6099@{#1483}) on port 48025
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Dec 21, 2023 6:10:07 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
2023-12-21 18:10:24 [main] INFO  ui.framework.components.CommonAction - Waiting for 2000 seconds
2023-12-21 18:11:10 [main] INFO  ui.framework.components.CommonAction - Waiting for 6000 seconds

org.openqa.selenium.WebDriverException: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=120.0.6099.129)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MacBook-Pro.local', ip: 'fe80:0:0:0:18ad:d7e2:7f80:9465%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '14.2', java.version: '21.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 120.0.6099.129, chrome: {chromedriverVersion: 120.0.6099.109 (3419140ab66..., userDataDir: /var/folders/zp/5nyc0sdd49s...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64026}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 5cf293b93ec12978def203c094c772f0

	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:277)
	at ui.framework.common.WebDriverCreator.openUrl(WebDriverCreator.java:409)
	at common.WebDriverProxy.goToUrl(WebDriverProxy.java:13)
	at jobs.SearchTest.setUp(SearchTest.java:25)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)

Disconnected from the target VM, address: '127.0.0.1:64011', transport: 'socket'

Process finished with exit code 255
```

### Operating System

macOS Sonoma 14.2

### Selenium version

3.141.59

### What are the browser(s) and version(s) where you see this issue?

Chrome 120.0.6099.109 (Official Build) (arm64) 

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 120.0.6099.109 (r1217362)

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment] 2023-12-21 19:21
Let's close as duplicate of #13345 and if we fix that one it fixes this one.

**Closed as completed** 2023-12-21 19:25 UTC
Labels: I-defect, A-needs-triaging
