### ISSUE TITLE
dragAndDrop work and doesn't work with Java and Chrome

### ISSUE THREAD

**Issue by v3g3t4x** [SeleniumHQ/selenium#8624] opened 2020-08-11 14:42 UTC
## 🐛 Bug Report

Simple drag and drop snippet of code doesn't work with Chrome.

## To Reproduce
You can find here code that works on a demo site and a code that doesn't work in other site, what's the issue?
In both case I am using a RemoteWebDriver:

			localDriver = new RemoteWebDriver(new URL(currentHub), capability);
			localDriver.manage().timeouts().implicitlyWait(30000, TimeUnit.SECONDS);
			localDriver.manage().window().maximize();

**SITE AND CODE WORKS**
Demo site URL: http://demo.guru99.com/test/drag_drop.html

			WebElement elementFrom=driver.findElementByXPath("//*[@id='credit2']/a");
			WebElement elementTo=driver.findElementByXPath("//*[@id='bank']/li");			
			Actions dragAndDrop = new Actions(localDriver);
			Action  action      = dragAndDrop.dragAndDrop(elementFrom, elementTo).build();
			action.perform();			

**SITE AND CODE DOESN'T WORK**
Demo site URL: https://www.seleniumeasy.com/test/drag-and-drop-demo.html

			WebElement elementFrom=driver.findElementByXPath("//div[@id='todrag']//span[1]");
			WebElement elementTo=driver.findElement(By.id("mydropzone"));
			Actions dragAndDrop = new Actions(localDriver);
			Action  action      = dragAndDrop.dragAndDrop(elementFrom, elementTo).build();
			action.perform();			
			

##Notes

In both case the code is the same and xpath are valid and correct, I am confused why in the second case doesn't work?
Are there some constrains around webelement type or xpath used or html page structure?

## Environment

OS: Docker Container
Browser: Chrome
Browser version: all version (tested sure on 77/80/84)
Language Bindings version: Java 1.8

**Comment by v3g3t4x** [comment] 2020-08-12 13:12
Updated with new info and 2 cases.

**Comment by Bioshock667** [comment] 2020-08-27 18:26
Greetings @v3g3t4x 
I was able to replicate the same issue on my machine and here is what I found.
To the best of my knowledge, the Selenium Java client library is formatting the "Actions" request correctly before sending to the driver server.  
The issue appears to be related to [ChromeDriver issue 2695](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2695&q=drag%20and%20drop&can=2) and [GeckoDriver issue 1450](https://github.com/mozilla/geckodriver/issues/1450).
From these issues, its seems that both drivers do not support the HTML5 Drag-and-Drop API.  

@AutomatedTester can you triage this as a Chromedriver and GeckoDriver related issue?

**Comment by AutomatedTester** [comment] 2021-02-17 14:00
Duplicate of #8003

**Closed as completed by AutomatedTester** 2021-02-17 14:00 UTC
Labels: D-firefox, D-chrome
