### ISSUE TITLE
Selenium 3 : Virtual - Webdriver unable to switchto iframe 

### ISSUE THREAD

**Issue by naukri-engineering** [SeleniumHQ/selenium#2377] opened 2016-06-25 07:17 UTC
## Meta -

OS:  Win 8.1

Selenium Version:  Selenium Beta 3

Browser:  FF

Browser Version:  45.0.2

## Expected Behavior -

Switchto iframe functionality should work.
## Actual Behavior -

Webdriver unable to switchto iframe and instead execute action on previous element.
## Steps to reproduce -

driver.switchTo().frame(driver.findElement(By.xpath(MailBody_Frame)));
try {
                  WebDriverWait wait = new WebDriverWait(driver, 10);
                  WebElement element = wait.until(ExpectedConditions
                              .visibilityOfElementLocated(mailBody_Txt));
            //    return element;
            } catch (Exception e) {
                  WebElement element = driver.findElement(mailBody_Txt);
                  safeJavaScriptClick(mailBody_Txt);
      //          return element;
            }
Element. getText();

**Comment by lukeis** [comment] 2016-06-25 07:37
can you provide a way for someone else to reproduce the issue? example site? (jsfiddle?)

**Comment by naukri-engineering** [comment] 2016-06-25 08:33
Iframe functionality can be checked on following url:-

http://toolsqa.com/iframe-practice-page/

On following locator path:-
//iframe[@id='IF1']

Code for same:-
driver.get("http://toolsqa.com/iframe-practice-page/");
driver.switchTo().frame(driver.findElement(By.xpath(("//iframe[@id='IF1']")));

driver.findElement(By.xpath(".//*[@id='branding']/a")).click();

**Comment by dragodr93** [comment] 2016-12-15 14:53
Same for me with Firefox 50 and Selenium 3.0.1 on Ubuntu 16.04.

**Comment by himpush** [comment] 2017-12-23 14:13
Any updates on this?

**Comment by p0deje** [comment] 2017-12-28 02:48
I cannot reproduce the issue using:

* geckodriver 0.19.1
* Firefox 57.0
* selenium 3.8.0

Can anybody provide [concise reproducible test case](http://sscce.org/)?

**Comment by barancev** [comment] 2018-01-18 20:21
Closing the issue as reported against outdated (beta) version.

**Closed by barancev** 2018-01-18 20:21 UTC
Labels: D-firefox, R-awaiting answer
