### ISSUE TITLE
Selenium Click is not working with IE11 in Windows 10 locally and also using remotedriver

### ISSUE THREAD

**Issue by salvada** [SeleniumHQ/selenium#6144] opened 2018-07-11 14:00 UTC
This exception is what I get when trying to click on a button or an element on IE11 WINDOWS 10.
I tried also with remote driver and the result is the same.
New version of selenium gives the same as well.

The workaround I am using now with partial success is sendKeys(keys.ENTER), but indeed is a workaround.

org.openqa.selenium.interactions.MoveTargetOutOfBoundsException: Cannot click on element
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: 'PCxxxx', ip: 'xxxxxx', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_172'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {acceptInsecureCerts: false, browserName: internet explorer, browserVersion: 11, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enablePersistentHover: true, ie.browserCommandLineSwitches: , ie.ensureCleanSession: false, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ignoreProtectedModeSettings: false, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:8856/, nativeEvents: true, requireWindowFocus: false}, setWindowRect: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}

**Comment by barancev** [comment] 2018-07-11 19:30
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by salvada** [comment] 2018-07-16 10:02
element.click(); where element is FluentWebElement gives me the exception posted above.
It happens every time I click on a button. 

Given I login as "user"
When I click on login  (this will give the exception above)
Then I am on the PAGE

So I don' t know how to give more info being the problem present for all clicks

**Comment by luke-hill** [comment] 2018-07-16 10:07
Read the link previously posted by barancev.

As a bear minimum we would need (ideally), a GH repo or a sample gist where we could copy the code and run it. It would need to hit a publically available website and shouldn't require any setup from the devs behalf.

Your issue could be local to the page your testing against, in which case this wouldn't be a selenium bug, it could be something weird on the page. We simply don't have enough information to triage.

Read the SSCCE link to inform yourself of what you need to post, then post an update.

**Comment by barancev** [comment] 2018-07-16 14:42
Also version 3.9 is out of date, please retest using the latest version (3.13 at the moment)

**Comment by Skhoshhal** [comment] 2018-07-23 09:42
try to user this one it works for me:
 client.execute(`$('${button-id}').click();`)

**Comment by barancev** [comment] 2018-08-14 07:07
Closing the issue as there is no reproduction scenario provided.

**Closed by barancev** 2018-08-14 07:07 UTC
Labels: D-IE, R-awaiting answer
