### ISSUE TITLE
SendKeys method not working with Selenium 2.46.0 in Firefox 38.0.5

### ISSUE THREAD

**Issue by 1dziubo1** [SeleniumHQ/selenium#682] opened 2015-06-18 13:30 UTC
sendKeys sends inproper signs for every of:
String [] searchtab = {"á","â","ä","ă","ą","?","é","ë","ě","ę","î","í","ô","ó","ö","ő","?","ń","ň","đ","ď","ł","ś","ć","ź","ż"};
for(String search:searchtab) {
webElement.sendKeys(search);
}
Result (for single string):
� or ? 

for "!"
no mark will be entered
using as workaround:
webElement.sendKeys(Keys.SHIFT, "1");

needs sdditional 5sec Thread.sleep for no reason just to work

**Comment by ddavison** [comment] 2015-06-18 13:40
for the code:
```java
public void test682() {
        WebDriver d = new FirefoxDriver();
        d.get("http://google.com");
        WebElement txtSearch = d.findElement(By.name("q"));
        String [] searchtab = {"!","á","â","ä","ă","ą","?","é","ë","ě","ę","î","í","ô","ó","ö","ő","?","ń","ň","đ","ď","ł","ś","ć","ź","ż","!"};
        for(String search:searchtab) {
            txtSearch.sendKeys(search);
        }
    }
```

I can't reproduce with Safari, Chrome, nor Firefox.
![screen shot 2015-06-18 at 09 38 37](https://cloud.githubusercontent.com/assets/2972876/8232469/0926b4ea-159e-11e5-898f-ba327b87d26c.png)
![screen shot 2015-06-18 at 09 39 04](https://cloud.githubusercontent.com/assets/2972876/8232470/09279888-159e-11e5-8835-64fd3d586534.png)
![screen shot 2015-06-18 at 09 39 34](https://cloud.githubusercontent.com/assets/2972876/8232468/092643ca-159e-11e5-8bac-5f99ecd5afd5.png)

**Comment by ddavison** [comment] 2015-06-18 16:02
closing as not reproducible.  if you can tell me more information on how to reproduce this, then i'd be happy to look into it for you

**Closed by ddavison** 2015-06-18 16:02 UTC
