### ISSUE TITLE
Selenium 3.12.0 and Internet Explorer 11 on windows 10

### ISSUE THREAD

**Issue by lorenzomferrigno** [SeleniumHQ/selenium#5952] opened 2018-05-29 15:11 UTC
Hi, I tried to use RemoteWebDriver usind IE11 on windows 10 64b.
My code:

`
DesiredCapabilities cap = DesiredCapabilities.internetExplorer();
		
		WebDriver driver = new RemoteWebDriver(
                 new URL("http://localhost:4444/wd/hub"), 
                 cap);
		driver.get("http://www.google.com");
		
		Thread.sleep(5000);
		
		driver.close();`

Console:
`Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create session from org.openqa.selenium.remote.NewSessionPayload@f4f92e
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:15.31Z'
System info: host: 'CPX-BA8ZZR18OR0', ip: 'XXX.XXX.XXX.XXX', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: unknown
Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700'
System info: host: 'CPX-BA8ZZR18OR0', ip: 'XXX.XXX.XXX.XXX', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: driver.version: RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:161)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:64)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)
	at Test.main(Test.java:13)
Caused by: org.openqa.selenium.SessionNotCreatedException: Unable to create session from org.openqa.selenium.remote.NewSessionPayload@f4f92e
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:15.31Z'
System info: host: 'CPX-BA8ZZR18OR0', ip: 'XXX.XXX.XXX.XXX', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: unknown
Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700'
System info: host: 'CPX-BA8ZZR18OR0', ip: 'XXX.XXX.XXX.XXX', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$4(NewSessionPipeline.java:75)
	at java.util.Optional.orElseThrow(Unknown Source)
	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$5(NewSessionPipeline.java:74)
	at java.util.Optional.orElseGet(Unknown Source)
	at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession(NewSessionPipeline.java:72)
	at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:65)
	at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$1(WebDriverServlet.java:246)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`

Can someone help?
I download the IEDriver for Selenium 3.11.0, version x64

**Comment by lorenzomferrigno** [comment] 2018-05-29 15:47
I resolved by upgrade to selenium 3.12.0 with the correct IEDriver but now i can't navigato to URL, the IE window show the message "This is the initial start page for the WebDriver server."

**Comment by joeyparrish** [comment] 2018-05-29 17:59
It seems that it is WebDriver clients which need to be updated to fix this, assuming Selenium devs don't want to build some compatibility or translation layer.  I have a solution in progress for the node "wd" module, but I'm sure there are others which need to be updated as well.

**Comment by jimevans** [comment] 2018-05-29 18:42
@joeyparrish The guidance from the Selenium project and from the W3C Browser Testing and Tools Working Group (which produces the W3C WebDriver Specification) is that going forward, driver implementations are expected to use the spec-compliant dialect of the wire protocol. The IE and Firefox (geckodriver) implementations already do this; other implementations (Chrome, Edge, and Safari) have this work in progress. Selenium's local-end language bindings for Java, .NET, Python, Ruby, and JavaScript already properly handle the differences between the protocols; it is incumbent on third-party language bindings to do so on their own.

**Comment by shah-ishita** [comment] 2018-05-30 06:17
@lorenzomferrigno
Please check and set your IE driver path, in to System Environment Variable.

**Comment by barancev** [comment] 2018-06-10 17:55
@lorenzomferrigno The message "This is the initial start page for the WebDriver server" is totally legit. What's the issue? Does your scenario fail? What's the exception?

**Comment by barancev** [comment] 2018-06-25 20:17
CLosing the issue as it's not clear what the issue is.

**Closed by barancev** 2018-06-25 20:17 UTC
Labels: D-IE, R-awaiting answer
