### ISSUE TITLE
Clicking only works the first time, and fill_in doesn't work.

### ISSUE THREAD

**Issue by cwardata** [SeleniumHQ/selenium#6922] opened 2019-02-08 17:45 UTC
## 🐛 Bug Report

`.click(x: 0, y: 0)` (Firefox) and some `click_at` method I found (chrome-driver) only worked the first few clicks (from 1 to ~5) then didn't work anymore (returns `nil` but the clicks don't happen)

```
Capybara::Node::Element.class_eval do
  def click_at(x, y)
    right = x - (native.size.width / 2)
    top = y - (native.size.height / 2)
    driver.browser.action.move_to(native).move_by(right.to_i, top.to_i).click.perform
  end
end
```

`fill_in` didn't work (I was getting some weird "value" "recursive" error from chrome driver), so I had to use:

```
def hacked_fill_in(selector, value)
  C.accept_confirm {
    C.execute_script("alert($('#{selector}').val('#{value}'))")
  }
end
```

OS: OSX
Browser: Firefox / Chrome
Browser version: 65.0 / 72.0
Browser Driver version: geckodriver 0.23.0 / ChromeDriver 2.34.522932
Language Bindings version: Ruby 2.5.0 with Capybara

Sorry for filling multiple bugs. I have various more or less hacky workarounds.

**Comment by twalpole** [comment] 2019-02-08 19:57
@cwardata Capybaras built-in click accepts offsets, is there any reason you're creating you're own? Also, if you're having an issue with `fill_in` you're going to be better off reporting it on the Capybara project than on Selenium

**Comment by twalpole** [comment] 2019-02-08 19:59
Closing this since it appears to be about Capybara not about Selenium - and has no way to reproduce

**Closed by twalpole** 2019-02-08 19:59 UTC

**Comment by cwardata** [comment] 2019-02-08 20:43
@twalpole Capybara's offset works in the case of `click(x: 10, y: 10)` for instance. And both bugs are Selenium errors. The code to reproduce is just using `click`, `click_at`, and using `fill_in(name: "name" with: "something')` for instance.

**Comment by twalpole** [comment] 2019-02-08 22:06
@cwardata You haven't provided anything that demonstrates any error (or that it is actually with Selenium) - `click` is tested thoroughly in the Selenium test suite - and `click_at` and `fill_in` are not Selenium methods.  If you really believe this is a Selenium issue then you'll need to provide a self contained example that reproduces the error (Capybara will require the same thing if you file an issue there)
