### ISSUE TITLE
Selenium IEDriver loses window handles with IE Mode for Chromium Edge

### ISSUE THREAD

**Issue by csharsha** [SeleniumHQ/selenium#9517] opened 2021-05-26 16:59 UTC
## 🐛 Bug Report

When using IEDriverServer.exe with C# to launch MS Edge in IE Mode, after clicking on a button in my application which closes the current window and opens a new window, I noticed that when we tried get driver.windowhandles.count it is returning always 0.

## To Reproduce

Detailed steps to reproduce the behavior:

I have used the following code to open MS Edge in IE Mode.

> var ieService = InternetExplorerDriverService.CreateDefaultService(requiredDirPath, iedriverexefilename);
> var ieOptions = new InternetExplorerOptions();
> ieOptions.AddAdditionalCapability("ie.edgechromium", true);
> ieOptions.AddAdditionalCapability("ie.edgepath", @"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe");

> driver  = new InternetExplorerDriver(ieService, ieOptions, TimeSpan.FromSeconds(30));

> driver = new InternetExplorerDriver();
> driver.Navigate().GoToUrl(APP_URL);
>driver.FindElement(By.XPath("//input[@DIKey='txtUserName']")).SendKeys(strUsername);
>driver.FindElement(By.XPath("//input[@DIKey='txtPassword']")).SendKeys(strPassword);
> IJavaScriptExecutor jse1 = (IJavaScriptExecutor)driver;
> jse1.ExecuteScript("arguments[0].scrollIntoView();", driver.FindElement(By.Id("ic_C_C8")));
> jse1.ExecuteScript("arguments[0].click();", driver.FindElement(By.Id("ic_C_C8")));
> System.Threading.Thread.Sleep(2000);
> int count = driver.WindowHandles.Count;

## Expected behavior

> driver.WindowHandles.Count always returns '0' after login button is clicked

## Test script or set of commands reproducing this issue

I have attached the page source code. After clicking on login button, the page is submitted using javascript "document.Logon.Submit();" which closes the login window and opens a home page.

## Environment

OS: Windows 10 2019 (version 1909)
Browser: MS Chromium Edge 
Browser version: 88.0.705.74
Browser Driver version: IEDriverServer.exe 3.150.1.0
Language Bindings version: C# 

[HTMLContent_LogonPage.txt](https://github.com/SeleniumHQ/selenium/files/6548461/HTMLContent_LogonPage.txt)

**Comment by diemol** [comment] 2021-05-28 07:01
Duplicate of #8868

**Closed as completed by diemol** 2021-05-28 07:01 UTC
