### ISSUE TITLE
[🐛 Bug]: (Minor) The example 'request element information' step in 'first_script.py' does not actually request any information from the element.

### ISSUE THREAD

**Issue by Twitch529** [SeleniumHQ/selenium#14555] opened 2024-10-03 13:27 UTC
### What happened?

In the example instructions for getting started with Selenium, [here](https://www.selenium.dev/documentation/webdriver/getting_started/first_script/), it instructs you to: "Request element information" (see step 7). The example script it points to [here](https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/python/tests/getting_started/first_script.py#L18) allegedly does this with the line:

`message = driver.find_element(by=By.ID, value="message")`

However, all this does is create the message object. It does not collect any information about the message or verify any of that information. This line will cause the script to crash if the message doesn't exist, but it's a misleading example for new users of Selenium.

This can be easily fixed by changing this line to something that actually requests some information about the message element rather than just creating it, e.g.

`message = driver.find_element(by=By.ID, value="message")`
`assert message.is_disaplayed()`

### How can we reproduce the issue?

```shell
Read [first_script.py](https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/python/tests/getting_started/first_script.py#L18) and decide if line 18 is actually requesting any information about the element (and why according to the same documentation, line 12 and line 13 are not).
```

### Relevant log output

```shell
Not applicable, I don't think.
```

### Operating System

Windows 11

### Selenium version

Python, selenium 4.25.0

### What are the browser(s) and version(s) where you see this issue?

Not applicable

### What are the browser driver(s) and version(s) where you see this issue?

Not applicable

**Comment by diemol** [comment] 2024-10-03 13:42
"Write your first Selenium script" focuses on enabling first users to automate a browser. Assertions, checks, or testing are not mentioned because not everyone uses Selenium for that purpose. 

We run those scripts daily in GitHub actions to ensure that those examples work and that unrelated errors do not block first users. I will close this because it is not a bug, but I will leave some links below that you can use to join our Slack if you want to continue the conversation.

**Closed as completed** 2024-10-03 13:42 UTC
Labels: I-question
