### ISSUE TITLE
Selenium Hub 4.1.3 not working with Appium 1.22.3 through relay option

### ISSUE THREAD

**Issue by muhammad-ir** [SeleniumHQ/selenium#10549] opened 2022-04-14 18:47 UTC
### What happened?

Android app is keep crashing with below error.

01-20 13:02:22.982 17937 17958 E AndroidRuntime: FATAL EXCEPTION: Instr: androidx.test.runner.AndroidJUnitRunner
01-20 13:02:22.982 17937 17958 E AndroidRuntime: Process: io.appium.uiautomator2.server, PID: 17937
01-20 13:02:22.982 17937 17958 E AndroidRuntime: java.lang.IllegalStateException: UiAutomation not connected!
01-20 13:02:22.982 17937 17958 E AndroidRuntime: 	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1198)
01-20 13:02:22.982 17937 17958 E AndroidRuntime: 	at android.app.UiAutomation.disconnect(UiAutomation.java:294)
01-20 13:02:22.982 17937 17958 E AndroidRuntime: 	at android.app.Instrumentation.finish(Instrumentation.java:248)
01-20 13:02:22.982 17937 17958 E AndroidRuntime: 	at androidx.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:367)
01-20 13:02:22.982 17937 17958 E AndroidRuntime: 	at androidx.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:415)
01-20 13:02:22.982 17937 17958 E AndroidRuntime: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:404)
01-20 13:02:22.982 17937 17958 E AndroidRuntime: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)

### How can we reproduce the issue?

```shell
Environment:
Appium: 1.22.3
Selenium Hub with relay node: 4.1.3
Platform: Android
java_client: 8.0.0
Selenium: 4

We are using DesiredCapabilities class with java_client 8.0.0. 

TOML File:

[server]
port = 4444

[node]
detect-drivers = false

[relay]
# Default Appium server endpoint
url = "http://localhost:4723/wd/hub"
# url = "http://10.0.0.44:5555/wd/hub"
status-endpoint = "/status"
# Stereotypes supported by the service
configs = [
  "1", "{\"browserName\": \"chrome\", \"platformName\": \"android\", \"appium:platformVersion\": \"10\"}"
]
```

### Relevant log output

```shell
NA
```

### Operating System

macOS

### Selenium version

Java Selenium 4

### What are the browser(s) and version(s) where you see this issue?

Android

### What are the browser driver(s) and version(s) where you see this issue?

Android

### Are you using Selenium Grid?

4.0.0

**Comment by diemol** [comment] 2022-04-14 21:10
What happens if you use the Appium server directly? Can you share a test to reproduce the issue? Ideally a GitHub repository with the whole setup.

**Comment by muhammad-ir** [comment] 2022-04-15 09:39
> What happens if you use the Appium server directly? Can you share a test to reproduce the issue? Ideally a GitHub repository with the whole setup.

Working fine with direct Appium server, Grid 3.
Failing with Grid 4 > Grid 3 > Appium

**Comment by muhammad-ir** [comment] 2022-04-15 12:13
Appium logs with/without hub

[appium-logs-with-hub.log](https://github.com/SeleniumHQ/selenium/files/8495819/appium-logs-with-hub.log)
[appium-logs-without-hub.log](https://github.com/SeleniumHQ/selenium/files/8495820/appium-logs-without-hub.log)

**Comment by diemol** [comment] 2022-05-09 23:17
@muhammad-ir still waiting for this as we did not see issues in the logs
>Can you share a test to reproduce the issue? Ideally a GitHub repository with the whole setup.

Or perhaps this can be closed?

**Comment by muhammad-ir** [comment] 2022-05-10 12:20
> @muhammad-ir still waiting for this as we did not see issues in the logs
> 
> > Can you share a test to reproduce the issue? Ideally a GitHub repository with the whole setup.
> 
> Or perhaps this can be closed?

It's a corporate code so I don't think so I can share. App is crashing soon code is making connection with WebDriver and trying to populate login element. 

Let me share some code snippets.

**Line causing the issue:**
public By userIDField() {return AppiumBy.androidUIAutomator("new UiSelector().resourceId(\"username\")");}

**Driver Connection:**
ParameterInitializer.getThreadDriver()
                                       .set(new AndroidDriver(
                                               new URL("http://" + ParameterInitializer.getTestParameters().get("customGrid")+ ":4444/wd/hub" ),
                                               MobileOptions.getBaseOptions()));
**Options:**
private static BaseOptions baseOptions = new BaseOptions();
baseOptions.setCapability(MobileCapabilityType.DEVICE_NAME, MobileParameters.getUdid());
baseOptions.setCapability(MobileCapabilityType.UDID, MobileParameters.getUdid());
baseOptions.setCapability(MobileCapabilityType.PLATFORM_VERSION, MobileParameters.getMobilePlatformVersion());
baseOptions.setCapability("newCommandTimeout", 60000);
baseOptions.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
baseOptions.setCapability(MobileCapabilityType.FULL_RESET, true);
baseOptions.setCapability("automationName", AutomationName.ANDROID_UIAUTOMATOR2);
baseOptions.setCapability("app", MobileParameters.getAndroidApkPath());
baseOptions.setCapability("deviceReadyTimeout", 120);
baseOptions.setCapability("avdReadyTimeout", 120);
baseOptions.setCapability("appWaitPackage", MobileParameters.getAndroidApkPackage());
baseOptions.setCapability("appWaitActivity", MobileParameters.getAndroidApkActivity());

**Comment by diemol** [comment] 2022-05-10 14:00
I do not know what to do with the snippet without an app 🤷 

It does not need to be the same app, any app that can be used to reproduce the issue is fine.

**Comment by titusfortner** [comment] 2022-05-10 14:19
Looks like a duplicate of this bug: https://github.com/SeleniumHQ/selenium/issues/10435
We're still sorting how to get the right thing to work with Appium team.

**Closed as completed by titusfortner** 2022-05-10 14:19 UTC
Labels: B-grid, J-awaiting answer, I-defect
