### ISSUE TITLE
Drag and Drop [Python]

### ISSUE THREAD

**Issue by dunossauro** [SeleniumHQ/selenium#8345] opened 2020-05-26 09:07 UTC
## 🐛 Bug Report

Drag and drop don't release Web Element.

## To Reproduce

Run code in section

## Expected behavior

Move element to another element

## Test script or set of commands reproducing this issue
```python
from selenium.webdriver import Firefox
from selenium.webdriver.common.action_chains import ActionChains

browser = Firefox('http://selenium.dunossauro.live/drag.html')

browser.get(url)
ac = ActionChains(browser)

def drag_and_drop(target, release):
    """Brute force testing."""
    ac = ActionChains(browser)
    ac.click_and_hold(target)
    ac.move_to_element(release)
    ac.release(release)
    ac.perform()

drag_and_drop(
    browser.find_element_by_id('dragA'),
    browser.find_element_by_id('dropBox')
)

ac.drag_and_drop(
    browser.find_element_by_id('dragA'),
    browser.find_element_by_id('dropBox')
).perform()
```
## Environment

OS: ArchLinux
Browser: Firefox and Chrome
Browser version: Firefox 76.0.1 / 81.0.4044.138 (64bits)
Browser Driver version: geckodriver 0.26.0  /ChromeDriver 81.0.4044.138
Language Bindings version: Python 3.8.1
Selenium Versions: tested on 3.141.0 and 4.0.0a5
Selenium Grid version (if applicable): N/A

# gecko log

```
1590483590906	addons.webextension.doh-rollout@mozilla.org	WARN	Loading extension 'doh-rollout@mozilla.org': Reading manifest: Invalid extension permission: networkStatus
1590483591080	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1590483591080	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1590483591080	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1590483591080	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1590483592119	Marionette	INFO	Listening on port 35757
1590483592202	Marionette	WARN	TLS certificate errors will be ignored for this session
1590483592289	Marionette	WARN	TimedPromise timed out after 0 ms: stacktrace:
TimedPromise/<@chrome://marionette/content/sync.js:245:13
TimedPromise@chrome://marionette/content/sync.js:230:10
Sleep@chrome://marionette/content/sync.js:283:10
dispatchPause@chrome://marionette/content/action.js:1482:10
toEvents/<@chrome://marionette/content/action.js:1156:16
action.dispatchTickActions@chrome://marionette/content/action.js:1060:35
action.dispatch/chainEvents<@chrome://marionette/content/action.js:1028:20
action.dispatch@chrome://marionette/content/action.js:1034:5
performActions@chrome://marionette/content/listener.js:853:16
dispatch/</req<@chrome://marionette/content/listener.js:527:14
dispatch/<@chrome://marionette/content/listener.js:520:15
1590483592553	Marionette	WARN	TimedPromise timed out after 0 ms: stacktrace:
TimedPromise/<@chrome://marionette/content/sync.js:245:13
TimedPromise@chrome://marionette/content/sync.js:230:10
Sleep@chrome://marionette/content/sync.js:283:10
dispatchPause@chrome://marionette/content/action.js:1482:10
toEvents/<@chrome://marionette/content/action.js:1156:16
action.dispatchTickActions@chrome://marionette/content/action.js:1060:35
action.dispatch/chainEvents<@chrome://marionette/content/action.js:1028:20
1590483592554	Marionette	WARN	TimedPromise timed out after 0 ms: stacktrace:
TimedPromise/<@chrome://marionette/content/sync.js:245:13
TimedPromise@chrome://marionette/content/sync.js:230:10
Sleep@chrome://marionette/content/sync.js:283:10
dispatchPause@chrome://marionette/content/action.js:1482:10
toEvents/<@chrome://marionette/content/action.js:1156:16
action.dispatchTickActions@chrome://marionette/content/action.js:1060:35
action.dispatch/chainEvents<@chrome://marionette/content/action.js:1028:20
1590483592818	Marionette	WARN	TimedPromise timed out after 0 ms: stacktrace:
TimedPromise/<@chrome://marionette/content/sync.js:245:13
TimedPromise@chrome://marionette/content/sync.js:230:10
Sleep@chrome://marionette/content/sync.js:283:10
dispatchPause@chrome://marionette/content/action.js:1482:10
toEvents/<@chrome://marionette/content/action.js:1156:16
action.dispatchTickActions@chrome://marionette/content/action.js:1060:35
action.dispatch/chainEvents<@chrome://marionette/content/action.js:1028:20
1590483593083	Marionette	WARN	TimedPromise timed out after 0 ms: stacktrace:
TimedPromise/<@chrome://marionette/content/sync.js:245:13
TimedPromise@chrome://marionette/content/sync.js:230:10
Sleep@chrome://marionette/content/sync.js:283:10
dispatchPause@chrome://marionette/content/action.js:1482:10
toEvents/<@chrome://marionette/content/action.js:1156:16
action.dispatchTickActions@chrome://marionette/content/action.js:1060:35
action.dispatch/chainEvents<@chrome://marionette/content/action.js:1028:20
1590483598398	Marionette	INFO	Stopped listening on port 35757
```

**Comment by dunossauro** [comment] 2020-05-26 09:11
maybe related to #8342

**Comment by erik-whiting** [comment] 2021-04-18 05:42
@dunossauro did you ever find a way to work around this? I'm having some issues with drag and drop functionality as well. Simple script I've been using:

```python
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
import time

driver = webdriver.Chrome()
driver.get('https://dineshvelhal.github.io/testautomation-playground/mouse_events.html')
draggable = driver.find_element_by_id('drag_source')
target = driver.find_element_by_id('drop_target')
actions = ActionChains(driver)
actions.drag_and_drop(draggable, target).perform()
time.sleep(5) # To see if it worked
driver.close()
```

**Comment by titusfortner** [comment] 2021-10-20 02:22
This is another duplicate of #8003
Native drag and drop is broken in pretty much all of the drivers right now, and there's not much Selenium can do about it right now: https://wpt.fyi/results/webdriver/tests/perform_actions/pointer.py

**Closed by titusfortner** 2021-10-20 02:22 UTC
Labels: C-py, I-defect
