### ISSUE TITLE
Firefox browser change size  in between running test

### ISSUE THREAD

**Issue by Vinaypawar77** [SeleniumHQ/selenium#4820] opened 2017-10-06 11:35 UTC
OS:
Windows -7 64 bit
Selenium Version:
3.5.1, 3.5.2, 3.5.3, 3.6.0
Gecko Driver
0.18.0
Browser:
Firefox

Browser Version:
55.0.3, 56

Expected Behavior -

Browser should run full Test in maximize.

Actual Behavior -

Firefox minimize in between running test.

[Firefox Minimize.zip](https://github.com/SeleniumHQ/selenium/files/1362539/Firefox.Minimize.zip)

For example:-(Run this code, test case run but firefox minimize)

package testCases;

import org.testng.annotations.Test;

import org.testng.annotations.BeforeTest;

import java.util.List;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterTest;

public class FireFx {

public WebDriver driver;
@test
public void doSearch() throws InterruptedException {

  WebElement element = driver.findElement(By.name("q"));
    element.sendKeys("Cheese!\n"); 
    element.submit();

    // wait until the google page shows the result
    WebElement myDynamicElement = (new WebDriverWait(driver, 10))
              .until(ExpectedConditions.presenceOfElementLocated(By.id("resultStats")));

    List<WebElement> findElements = driver.findElements(By.xpath("//*[@id='rso']//h3/a"));

    // this are all the links you like to visit
    for (WebElement webElement : findElements)
    {
        System.out.println(webElement.getAttribute("href"));
    }
    Thread.sleep(2000);
    WebElement element1 = driver.findElement(By.linkText("Cheese - Wikipedia"));
    element1.click();
    Thread.sleep(2000);
    Assert.assertEquals("Cheese - Wikipedia", driver.getTitle());
  System.out.println("Successfully!!!");
}

@beforetest
public void beforeTest() {

  System.setProperty("webdriver.gecko.driver", "Path\\geckodriver.exe");
  
	driver = new FirefoxDriver();
  driver.get("http://www.google.com");
   driver.manage().window().maximize();
  driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
}

@aftertest
public void afterTest() {

driver.close();
}

}

**Comment by barancev** [comment] 2017-10-07 04:32
Do you mean "normalized", not "minimized"?

**Comment by Vinaypawar77** [comment] 2017-10-09 10:34
Firefox open in maximized mode but after sometime in between firefox minimized, see video i attached aboce- "Firefox Minimize.zip"

**Comment by barancev** [comment] 2017-10-12 18:21
I can't see on the provided video that ther browser window was minimized.

**Comment by Vinaypawar77** [comment] 2017-10-13 07:29
When we run test in browser like,  firefox open already in maximize mode but  in chrome we use driver.manage().window().maximize();  to maximize the browser, I refer minimize to default size in which chrome open. so when i run test in firefox it change the size of the browser maximize mode to some random size and when we remove this line driver.manage().window().maximize(); from the code firefox run in maximize mode but when we add this line firefox change size see video again and thanks for replying

**Comment by warpech** [comment] 2017-10-16 09:31
Perhaps a duplicate of https://github.com/mozilla/geckodriver/issues/900?

**Comment by Vinaypawar77** [comment] 2017-10-17 07:01
@warpech, Perhaps a duplicate of mozilla/geckodriver#900?

Yes

**Comment by barancev** [comment] 2017-10-20 20:48
Closing the issue in favour of the mentioned geckodriver issue report.

**Closed by barancev** 2017-10-20 20:48 UTC
Labels: R-awaiting answer
