### ISSUE TITLE
During uploading of existing file: selenium.common.exceptions.InvalidArgumentException

### ISSUE THREAD

**Issue by dalvarezdc** [SeleniumHQ/selenium#9548] opened 2021-06-04 12:40 UTC
## 🐛 Bug Report

Selenium is telling me that an actual file currently in the system can't be found

During the process of uploading an existing while using selenium-webdriver, I did the test to find is the file actually exists to corroborate that I was actually uploading something and being consistent with it, my testing code:

## To Reproduce

```
def add_profile_picture(self, profile_picture):
        local_photo_path = download_url_photo(profile_picture)
        print(type(local_photo_path), local_photo_path)
        file_inputs = WebDriverWait(self.driver, 5).until(
            EC.presence_of_all_elements_located((
                By.XPATH,
                '//div/input[(@type="file")]'                
            ))
        )        
        print("Is filepath local_photo_path: ", os.path.isfile(local_photo_path))
        print("Is filepath os.path.abspath(local_photo_path): ", os.path.isfile(os.path.abspath(local_photo_path)))
        file_inputs[0].send_keys(os.path.abspath(local_photo_path))
 ```

#### The download_url_photo function is defined this way:

```
def download_url_photo(url, filename=None):
    final_path = None
    base_path = '/tmp/'
    use_custom_filename = filename is not None

    
    response = requests.get(url)
    if response.status_code == 200:
        raw_data = response.content
        parsed_url = urlparse(url)
        if use_custom_filename:
            final_path = filename
        else:
            final_path = base_path + path.basename(parsed_url.path)
        with open(final_path, 'wb') as new_file:
            new_file.write(raw_data)

    if final_path:
        delete_image_exif_data(final_path)

    return final_path
```
   
 As you can see, when I print the file location, the filepath gives me a True value, but the following error occurs: when I try to send_keys() to the file_inputs[0], the file_inputs[0] does exist, I've already checked it in various debugging processes.

```
Is filepath local_photo_path:  True
Is filepath os.path.abspath(local_photo_path):  True

ERROR [_CatchWebDriverError][204] invalid argument: File not found : /tmp/69f9dddf-6f69-490e-9ed3-d9a379e151af.jpg
  (Session info: chrome=89.0.4389.90)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: File not found : /tmp/69f9dddf-6f69-490e-9ed3-d9a379e151af.jpg
  (Session info: chrome=89.0.4389.90)
Stacktrace:
#0 0x56282084f2b9 <unknown>
```

Reading the Selenium documentation, it seems I am doing it correctly, this is the actual selenium function:
Detailed steps to reproduce the behavior:

## Expected behavior

The image should be uploaded or at least Selenium should recognize it

```
def send_keys(self, *value) -> None:
    """Simulates typing into the element.

    :Args:
        - value - A string for typing, or setting form fields.  For setting
          file inputs, this could be a local file path.

    Use this to send simple key events or to fill out form fields::

        form_textfield = driver.find_element(By.NAME, 'username')
        form_textfield.send_keys("admin")

    This can also be used to set file inputs.

    ::

        file_input = driver.find_element(By.NAME, 'profilePic')
        file_input.send_keys("path/to/profilepic.gif")
        # Generally it's better to wrap the file path in one of the methods
        # in os.path to return the actual path to support cross OS testing.
        # file_input.send_keys(os.path.abspath("path/to/profilepic.gif"))

    """
    # transfer file to another machine only if remote driver is used
    # the same behaviour as for java binding
    print('This is send keys')
    if self.parent._is_remote:
        local_files = list(map(lambda keys_to_send:
                               self.parent.file_detector.is_local_file(str(keys_to_send)),
                               ''.join(map(str, value)).split('\n')))
        if None not in local_files:
            remote_files = []
            for file in local_files:
                remote_files.append(self._upload(file))
            value = '\n'.join(remote_files)

    self._execute(Command.SEND_KEYS_TO_ELEMENT,
                  {'text': "".join(keys_to_typing(value)),
                   'value': keys_to_typing(value)})

```

## Environment

OS: Ubuntu 20.04 
Browser:  Chrome 
Browser version: Chrome=89.0.4389.90
Browser Driver version:
Language Bindings version: Python  3.7.7 
selenium==4.0.0b3
I am running inside a Docker container (version: "3.6"), also using rabbitmq, celery services (django-celery-beat==2.1.0) and Django==3.1

**Comment by diemol** [comment] 2021-06-04 12:55
Can you add which versions of components/binddings/docker/etc/... you are using?

**Comment by dalvarezdc** [comment] 2021-06-04 13:00
Versions added! Let me know if you need anything else

**Comment by diemol** [comment] 2021-06-04 13:04
You can also add a complete test script or a GitHub repo that helps to reproduce the issue, because the current code provided is not enough for us to copy & paste and run it to see the issue.

**Comment by dalvarezdc** [comment] 2021-06-04 21:24
I have updated the code, one thing I know for sure is that the error jumps in the line of `file_inputs[0].send_keys(os.path.abspath(local_photo_path))  
`
I checked in repeated times, it jumps just after the filepath print. I added a print statement in the first line of `send_keys()` and never printed it

**Comment by dalvarezdc** [comment] 2021-06-04 22:27
```
  file_inputs[0].send_keys(os.path.abspath(local_photo_path))
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 540, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 693, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 369, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 236, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: File not found : /tmp/young-man-1281282_960_720.jpg
  (Session info: chrome=89.0.4389.90)
Stacktrace:
#0 0x55e202abd2b9 <unknown>


If you suspect this is an IPython 7.23.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```

**Comment by Goraved** [comment] 2021-06-07 16:02
I have the same issue when using `selenoid` and `selenium 4.0.0.a7+`.  Works fine with `4.0.0.a6`.

**Comment by dalvarezdc** [comment] 2021-06-08 02:43
Actually this downgrade to previous version worked @Goraved, this functionality has no issues on Selenium 4.0.0.a6. Please @diemol check it out. Thank you in advance

**Comment by AutomatedTester** [comment] 2021-06-10 13:39
I think this was fixed in #9330. Please can you try b4 and see if it works?

**Comment by Goraved** [comment] 2021-06-10 13:47
Interesting. I've just checked `4.0.0.b4` and got the next issue
```
selenium.common.exceptions.WebDriverException: Message: unknown command: unknown command: session/b50c0fb9ed06945097949d1c0b633195/se/file
```

and `4.0.0.b3` has
```
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: File not found
```

**Comment by diemol** [comment] 2021-06-10 14:24
Are you using Selenium Grid? What version?

**Comment by Goraved** [comment] 2021-06-10 15:25
I use Selenoid 1.10.3

**Comment by diemol** [comment] 2021-06-10 15:28
You'd need to report the error to their project.

**Comment by Goraved** [comment] 2021-06-10 16:05
Answer from the **Aerocube** team

> Guys from Selenium team are from time to time changing their API to upload files. We strictly follow W3C specification (https://www.w3.org/TR/webdriver/#endpoints) and there is nothing about /se/file in this spec. Default API location is just /file and this is how it's implemented in all webdriver binaries.

**Comment by diemol** [comment] 2021-06-10 16:26
File upload endpoint is not part of the W3C spec, therefore is not standard and to make that explicit it was put behind the `se` prefix in the url.

**Comment by diemol** [comment] 2021-06-18 09:54
I'll close this as (based on the comments) the bindings are doing what they need to do, and tasks related to the Selenium project have been implemented.

**Comment by diemol** [comment] 2021-06-18 09:54
If you have any questions or need help, join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well.

**Closed as completed by diemol** 2021-06-18 09:54 UTC
Labels: J-awaiting answer, C-py
