### ISSUE TITLE
Encoding problem. Non latin characters are not supported by Grid

### ISSUE THREAD

**Issue by KirillSokolovsky** [SeleniumHQ/selenium#4535] opened 2017-08-22 09:23 UTC
## Meta -
OS:  Windows 10, Server 2016
Selenium Version:  3.5.+
Browser:  IE, Chrome, FF with latest versions and latest drivers
Platform: .Net, Java

## Expected Behavior -
- Text with non latin characters e.g. "Über", "вебдрайвер" is typed (during send keys) as "Über", "вебдрайвер"
- Locators with non latin characters processed in the same way e.g. ```//*[text()='Über']``` is received by hub/node as ```//*[text()='Über']```

## Actual Behavior -
- Text with non latin characters e.g. "Über", "вебдрайвер" is typed (during send keys) as "�ber", "??????????"
- Locators with non latin characters processed in the same way e.g. ```//*[text()='Über']``` is received by hub/node as ```//*[text()='�ber']```
- In some cases even latin symbols sends with ? e.g. from string "some text" webdriver types "?s?o?m?e? ?t?e?x?t?"

## Steps to reproduce -
for .Net
1. Setup Selenium Grid Hub and Node with default configs.
2. By any way create app that will use WebDriver
3.  Initialize RemoteWebDriver e.g. ```IWebDriver driver = new RemoteWebDriver(gridUri, new FirefoxOptions())``` or ChromeOptions, or IE...
4. Try to do following:

```
                driver.Navigate().GoToUrl("https://google.com");
                driver.Manage().Window.Maximize();
                var el = driver.FindElement(By.XPath("//*[@name='q']"));
                el.SendKeys("Über"); // CHECK typed symbols
                el.Clear(); // PAUSE HERE
                el.SendKeys("вебдрайвер"); // CHECK typed symbols
```
Without grid (using "local" web driver) all work fine.
On selenium grid 3.3.* all work fine.

**Comment by KirillSokolovsky** [comment] 2017-08-22 09:25
Without grid all (using "local" web driver) all works fine.
On selenium grid 3.4.0 all works fine.

**Comment by barancev** [comment] 2017-08-22 14:52
Duplicate of #4462

**Closed by barancev** 2017-08-22 14:52 UTC
