### ISSUE TITLE
[🐛 Bug]: Build WebDriver with authenticated Proxy not working

### ISSUE THREAD

**Issue by erik-rnbt** [SeleniumHQ/selenium#10886] opened 2022-07-18 08:20 UTC
### What happened?

When i try to build a connection to a RemoteWebDriver (provider: Saucelabs) over an authenticated Proxy im getting a SessionNotCreatedException. 

The connection is working with an non authenticated Proxy.

### How can we reproduce the issue?

```shell
//
import java.net.InetSocketAddress;
import java.net.MalformedURLException;
import java.net.Proxy;
import java.util.HashMap;
import java.util.Map;

import org.openqa.selenium.UsernameAndPassword;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.http.ClientConfig;
//

We just try to connect to the provider like they suggest (and i added the part with the authentication):

                        ChromeOptions options = new ChromeOptions();
                        options.setPlatformName("Windows 10");
                        options.setBrowserVersion("latest");

                        Map<String, Object> sauceOptions = new HashMap<>();
                        sauceOptions.put("username", username);
                        sauceOptions.put("accessKey", accessKey);
                        sauceOptions.put("name", name);

                        Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxy, proxyPort));

                        ClientConfig config = ClientConfig.defaultConfig()
                                               .authenticateAs(new UsernameAndPassword(proxyUsername, proxyPassword))
                                               .proxy(proxy);

                        WebDriver driver = RemoteWebDriver.builder()
                                               .oneOf(options)
                                               .setCapability("sauce:options", sauceOptions)
                                               .address(address)
                                               .config(config)
                                               .build();

                        driver.quit();
```

### Relevant log output

```shell
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: <html><body><h1>404 N
ot Found</h1>
The resource could not be found.
</body></html>

            at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:130)
            at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
            at org.openqa.selenium.remote.RemoteWebDriverBuilder.getRemoteDriver(RemoteWebDriverBuilder.java:399)
            at org.openqa.selenium.remote.RemoteWebDriverBuilder.build(RemoteWebDriverBuilder.java:372)
            at Saucelabs.Main.main(Main.java:62)
Caused by: org.openqa.selenium.json.JsonException: Unable to parse: <html><body><h1>404 Not Found</h1>
The resource could not be found.
</body></html>

            at org.openqa.selenium.json.Json.toType(Json.java:57)
            at org.openqa.selenium.json.Json.toType(Json.java:50)
            at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:127)
            ... 4 more
Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: <. Last 1 characters read: <
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: '{---}', ip: '{---}', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: unknown
            at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:126)
            at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:141)
            at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
            at org.openqa.selenium.json.Json.toType(Json.java:71)
            at org.openqa.selenium.json.Json.toType(Json.java:55)
            ... 6 more
```

### Operating System

Windows 10

### Selenium version

Selenium 4.3.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver

**Comment by diemol** [comment] 2022-08-03 21:34
Duplicate of #10231, see final [comment](https://github.com/SeleniumHQ/selenium/issues/10231#issuecomment-1036013964).

**Closed as completed by diemol** 2022-08-03 21:34 UTC
