### ISSUE TITLE
firfox getting crash just after opening once

### ISSUE THREAD

**Issue by AkhileshCh** [SeleniumHQ/selenium#2337] opened 2016-06-22 11:53 UTC
## Meta -
OS:  
< OSX captain >
Selenium Version:  
< 2.53.0, Webdriver, etc >
Browser:  
<  Firefox >

Browser Version:  

## Steps to reproduce -
< try to run a Selenium webdriver script on mac os (captain) It is generated very easly>

**Comment by lukeis** [comment] 2016-06-22 13:07
Likely a duplicate of #2110

**Closed by lukeis** 2016-06-22 13:07 UTC
