### ISSUE TITLE
Static scope of variables are lost inside the Function interface in Selenium Alpha6

### ISSUE THREAD

**Issue by saritapol13** [SeleniumHQ/selenium#8622] opened 2020-08-10 14:21 UTC
## 🐛 Bug Report

The static variables are not accessible inside the Function interface in Selenium alpha6.

## To Reproduce

I've created a sample project(https://github.com/saritapol13/staticScopeIssueInSelenium) to demonstrate the issue.

Detailed steps to reproduce the behavior:

In build.gradle file comment the line for 'selenium-java', version: '3.141.59' and use the one for 'selenium-java', version: '4.0.0-alpha-6'.
Just run the test "**about_tab_is_on_home_page**" from the RemoteBrowserTests class. This will fail as below:
`org.opentest4j.AssertionFailedError: The test failed due to: Expected condition failed: waiting for website.HomePage$1@7293e463 (tried for 30 second(s) with 500 milliseconds interval)
Build info: version: '4.0.0-alpha-6', revision: '5f43a29cfc'
os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11'
Driver info: driver.version: unknown
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:109)
	at product1.RemoteBrowserTests.about_tab_is_on_home_page(RemoteBrowserTests.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
	at `

If you now run the same test using selenium 3.141.59 (uncommenting the line in build.gradle and vice-versa) it works fine

## Expected behavior

Scope of the static variables should be retained in the Function interface.

## Test script or set of commands reproducing this issue
 I've given the steps above. The scope of Multibrowser.getActiveBrowser() which returns the active browser is lost and it returns null. The issue is not related to any browser version like Chrome, Edge and so on but selenium version.

The other way to run test is from the main project(cloned from the github) **gradlew clean test**

## Environment

OS: Windows 10
Browser:  Chrome
Browser version: 84.0.4147.105
Browser Driver version: ChromeDriver 84.0.4147.30
Language Bindings version: Java
Selenium: 4.0.0-alpha-6
Selenium Grid version (if applicable):  e.g.:

**Comment by diemol** [comment] 2020-09-04 22:57
@saritapol13 is there a way to reproduce this with a more simple piece of code? I was browsing through the linked repository and I simply got lost where the flow goes. It'd be nice to have some code only using WebDriver.

**Comment by shs96c** [comment] 2020-09-07 10:50
I think this is a duplicate of #8587. Closing this issue, because of that.

**Closed as completed by shs96c** 2020-09-07 10:50 UTC
Labels: J-awaiting answer
