### ISSUE TITLE
[🐛 Bug]: Grid HUb 4.1.2 becomes unresponsive

### ISSUE THREAD

**Issue by kevnpayx** [SeleniumHQ/selenium#10474] opened 2022-03-24 13:25 UTC
### What happened?

We are seeing the hub become unresponsive after what appears to be invalid request are seen in the log. We are not sure where the odd/bad requests are coming from but we are going with the assumption that is it some sort of security scanning on our end for now based on the fact that these request seem to always happen around the same time each night.

This has been an ongoing issue that we have been tracking here - most notably through issues 1434, 1469, and 9959

We have seen several different issues in the log:

java.lang.IllegalArgumentException: Invalid UUID string: 
        at java.base/java.util.UUID.fromString(UUID.java:215)
        at org.openqa.selenium.events.zeromq.UnboundZmqEventBus$PollingRunnable.run(UnboundZmqEventBus.java:241)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

### How can we reproduce the issue?

```shell
NA
```

### Relevant log output

```shell
java.lang.IllegalArgumentException: Invalid UUID string: 
        at java.base/java.util.UUID.fromString(UUID.java:215)
        at org.openqa.selenium.events.zeromq.UnboundZmqEventBus$PollingRunnable.run(UnboundZmqEventBus.java:241)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829
```

### Operating System

linux

### Selenium version

4.1.2

### What are the browser(s) and version(s) where you see this issue?

NA

### What are the browser driver(s) and version(s) where you see this issue?

NA

### Are you using Selenium Grid?

4.1.2

**Comment by diemol** [comment] 2022-03-24 22:02
Duplicate of https://github.com/SeleniumHQ/docker-selenium/issues/1497, the fix will be in 4.1.3. Ideally, next week.

**Closed as completed by diemol** 2022-03-24 22:02 UTC
