### ISSUE TITLE
[🐛 Bug]: BiDi API console log example doesn't work and is missing info

### ISSUE THREAD

**Issue by Reksa97** [SeleniumHQ/selenium#11244] opened 2022-11-09 10:24 UTC
### What happened?

Tried to run the [bidi console log example in the docs](https://www.selenium.dev/documentation/webdriver/bidirectional/bidi_api/?language=python#listen-to-consolelog-events) but I get 

> AttributeError: 'RunContext' object has no attribute 'runner' when running it.

Is the documentation missing something (other than the imports) or what could be the issue?
Tried with python 3.9.2 and 3.10.6
I can open a pr to fix the documentation if I get this to work first

### How can we reproduce the issue?

```shell
import asyncio
from selenium import webdriver
from selenium.webdriver.common.log import Log
from selenium.webdriver.common.bidi.console import Console

async def main():
    chrome_options = webdriver.ChromeOptions() # this isn't used but it is still in your example
    driver = webdriver.Chrome()
    driver.get("http://www.google.com")
    async with driver.bidi_connection() as session:
        log = Log(driver, session)
        async with log.add_listener(Console.ALL) as messages:
            driver.execute_script("console.log('I love cheese')")
        print(messages["message"])
    driver.quit()

asyncio.run(main())
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/reko/test/iframe-test/t.py", line 18, in <module>
    asyncio.run(main())
  File "/Users/reko/.pyenv/versions/3.10.6/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/reko/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/reko/test/iframe-test/t.py", line 11, in main
    async with driver.bidi_connection() as session:
  File "/Users/reko/.pyenv/versions/3.10.6/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/Users/reko/test/iframe-test/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 1182, in bidi_connection
    async with cdp.open_cdp(ws_url) as conn:
  File "/Users/reko/.pyenv/versions/3.10.6/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/Users/reko/test/iframe-test/env/lib/python3.10/site-packages/selenium/webdriver/common/bidi/cdp.py", line 461, in open_cdp
    async with trio.open_nursery() as nursery:
  File "/Users/reko/test/iframe-test/env/lib/python3.10/site-packages/trio/_core/_run.py", line 882, in open_nursery
    strict_exception_groups = GLOBAL_RUN_CONTEXT.runner.strict_exception_groups
AttributeError: 'RunContext' object has no attribute 'runner'
```

### Operating System

macOS Ventura

### Selenium version

4.6.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 107.0.5304.87 (Official Build) (arm64)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 107.0.5304.62 (1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942})

### Are you using Selenium Grid?

no

**Comment by TamsilAmani** [comment] 2022-11-14 08:37
Looking into this issue

**Comment by maksimovichsam** [comment] 2022-11-28 05:02
I was running into this error too. It looks like this is exception is caused by using `asyncio` to run the async function `main` instead of the `trio` library.  To fix this, make the following changes to the code snippet.
```
- import asyncio
+ import trio
- asyncio.run(main())
+ trio.run(main)
```
Example in the documentation should be more clear.

**Comment by TamsilAmani** [comment] 2022-11-28 06:43
Thank you for the fix @maksimovichsam. I'll update the documentation.

**Comment by diemol** [comment] 2022-12-03 07:12
Linked PR was merged.

**Closed as completed by diemol** 2022-12-03 07:12 UTC
Labels: C-py, I-defect, B-devtools
