### ISSUE TITLE
Win10 64bit  and IE11 throws NoSuchWindowException: Error retrieving current window

### ISSUE THREAD

**Issue by shankarkc** [SeleniumHQ/selenium#4610] opened 2017-08-31 10:10 UTC
## Meta -
OS:  

Windows10
Selenium Version:  
3.4.0

Browser:  Internet Explorer v11

Browser Version:  11.540.15063.0 (64 bit)

## Expected Behavior -
Windows should not throw exception
## Actual Behavior -
windows throws exception
NoSuchWindowException: Error retrieving current window

On node i see this call stack
```
org.openqa.selenium.NoSuchWindowException: Error retrieving current window
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'WIN10NODE', ip: '10.169.55.23', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{proxy=Proxy(manual, http=10.163.3.125:443, ssl=10.163.3.125:443), acceptInsecureCerts=false, browserVersion=11, se:ieOptions={browserAttachTimeout=0.0, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.usePerProcessProxy=false, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000.0, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0.0, ie.browserCommandLineSwitches=, requireWindowFocus=false, initialBrowserUrl=http://localhost:37071/, ignoreProtectedModeSettings=true}, browserName=internet explorer, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss, javascriptEnabled=true, platformName=windows, setWindowRect=true, platform=ANY}]
Session ID: 1da734e8-c3de-4299-a886-f2ec00503672
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.setSize(RemoteWebDriver.java:890)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWindow.setSize(EventFiringWebDriver.java:625)
	at org.openqa.selenium.remote.server.handler.SetWindowSize.call(SetWindowSize.java:53)
	at org.openqa.selenium.remote.server.handler.SetWindowSize.call(SetWindowSize.java:27)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
09:47:40.480 WARN - Exception: Error retrieving current window
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'WIN10NODE', ip: '10.169.55.23', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{proxy=Proxy(manual, http=MyProxyIPHere:443, ssl=MyProxyIPHere:443), acceptInsecureCerts=false, browserVersion=11, se:ieOptions={browserAttachTimeout=0.0, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.usePerProcessProxy=false, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000.0, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0.0, ie.browserCommandLineSwitches=, requireWindowFocus=false, initialBrowserUrl=http://localhost:37071/, ignoreProtectedModeSettings=true}, browserName=internet explorer, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss, javascriptEnabled=true, platformName=windows, setWindowRect=true, platform=ANY}]
Session ID: 1da734e8-c3de-4299-a886-f2ec00503672
```

I have configured IE as mentioned  [here](https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration)

## Steps to reproduce -
On windows10 64bit machine with IE11 installed.....configure IE as mentioned [here](https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration)
Use IE driver iedriver_3.5.1_x64bit for selenium grid.

Here is the code that throws exception
```
		webDriver.get(url);
		// setting browser window size
		webDriver.manage().window().setSize(new Dimension(1600,900));
```

**Comment by jimevans** [comment] 2017-08-31 10:18
If you've configured IE properly, why are you using the `INTRODUCE_FLAKINESS...` setting? Also, there is usually [no reason to use the 64-bit IE driver](http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html) for IE10 or later.

**Comment by barancev** [comment] 2017-08-31 12:39
1) Make sure you can reproduce the issue with 32-bit driver and without `ignoreProtectedModeSettings` capability.

2) Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by shankarkc** [comment] 2017-09-01 03:02
Thanks @jimevans / @barancev i will try your suggestions and update.
Thanks for hints

**Comment by shankarkc** [comment] 2017-09-01 05:49
@jimevans / @barancev as you guys suggested i tried with 

-  win32bit webdriver 
-  removed INTRODUCE_FLAKINESS
-  removed ignoreProtectedModeSettings settings from DesiredCapabilities  class

But I sill see the same behavior


At client i see this call stack
```
org.openqa.selenium.NoSuchWindowException: Error retrieving current window
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'WIN10NODE', ip: 'YourNodeIPHere', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{proxy=Proxy(manual, http=YourProxyIPHere:443, ssl=YourProxyIPHere:443), acceptInsecureCerts=false, browserVersion=11, se:ieOptions={browserAttachTimeout=0.0, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.usePerProcessProxy=false, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000.0, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0.0, ie.browserCommandLineSwitches=, requireWindowFocus=false, initialBrowserUrl=http://localhost:3347/, ignoreProtectedModeSettings=false}, browserName=internet explorer, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss, javascriptEnabled=true, platformName=windows, setWindowRect=true, platform=ANY}]
Session ID: b7bbc3d0-602e-4ac5-8b9c-6ddc7063ba49
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'inll11306565l', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-91-generic', java.version: '1.8.0_144'
Driver info: driver.version: RemoteWebDriver
```
I see exception on node. I do see window popsup on node when session get created but below cod fails
```
DesiredCapabilities caps = new DesiredCapabilities();
caps.setCapability("nativeEvents", false);
caps.setBrowserName(BrowserType.IE);
caps.setCapability("acceptInsecureCerts", false);
WebDriver webDriver = new RemoteWebDriver(new URL(hubUrl), caps);
webDriver.get("MyWebsiteURLHere");
webDriver.manage().window().setSize(new Dimension(1600,900));
```
Here is exception
```
org.openqa.selenium.NoSuchWindowException: Error retrieving current window
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'WIN10NODE', ip: 'YourNodeIPHere', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{proxy=Proxy(manual, http=YourProxyIPHere:443, ssl=YourProxyIPHere:443), acceptInsecureCerts=false, browserVersion=11, se:ieOptions={browserAttachTimeout=0.0, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.usePerProcessProxy=false, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000.0, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0.0, ie.browserCommandLineSwitches=, requireWindowFocus=false, initialBrowserUrl=http://localhost:3347/, ignoreProtectedModeSettings=false}, browserName=internet explorer, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss, javascriptEnabled=true, platformName=windows, setWindowRect=true, platform=ANY}]
Session ID: b7bbc3d0-602e-4ac5-8b9c-6ddc7063ba49
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.setSize(RemoteWebDriver.java:890)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWindow.setSize(EventFiringWebDriver.java:625)
	at org.openqa.selenium.remote.server.handler.SetWindowSize.call(SetWindowSize.java:53)
	at org.openqa.selenium.remote.server.handler.SetWindowSize.call(SetWindowSize.java:27)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
05:11:45.210 WARN - Exception: Error retrieving current window
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'WIN10NODE', ip: 'YourNodeIPHere', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{proxy=Proxy(manual, http=YourProxyIPHere:443, ssl=YourProxyIPHere:443), acceptInsecureCerts=false, browserVersion=11, se:ieOptions={browserAttachTimeout=0.0, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.usePerProcessProxy=false, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000.0, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0.0, ie.browserCommandLineSwitches=, requireWindowFocus=false, initialBrowserUrl=http://localhost:3347/, ignoreProtectedModeSettings=false}, browserName=internet explorer, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss, javascriptEnabled=true, platformName=windows, setWindowRect=true, platform=ANY}]
Session ID: b7bbc3d0-602e-4ac5-8b9c-6ddc7063ba49
```
I tested with below 2 registry entries on Win10 registry (one after another)
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE]
"iexplore.exe"=dword:00000000
```

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE]
"iexplore.exe"=dword:00000000
```
But it didnt help

Please let me know if this is a defect OR i missed something.

**Comment by barancev** [comment] 2017-09-01 06:45
Start remote server that starts IE with extra options to collect IE driver logs:
```
java -Dwebdriver.ie.driver.logfile=iedriver.log -Dwebdriver.ie.driver.loglevel=TRACE -jar selenium-server-standalone.jar
```
run your scenario and attach the collected log file here.

**Comment by shankarkc** [comment] 2017-09-05 11:13
here is the trace log content
```
T 2017-09-05 11:07:33:879 server.cc(183) Process request with: URI: /session/09398a8e-07f7-4abe-9379-28678a65adc5/window/rect HTTP verb: POST
body: {"width":1600,"height":900}
T 2017-09-05 11:07:33:879 server.cc(272) Entering Server::DispatchCommand
T 2017-09-05 11:07:33:879 server.cc(583) Entering Server::LookupCommand
D 2017-09-05 11:07:33:879 server.cc(281) Command: POST /session/09398a8e-07f7-4abe-9379-28678a65adc5/window/rect {"width":1600,"height":900}
T 2017-09-05 11:07:33:879 server.cc(378) Entering Server::LookupSession
T 2017-09-05 11:07:33:879 IESession.cpp(191) Entering IESession::ExecuteCommand
T 2017-09-05 11:07:33:879 IECommandExecutor.cpp(122) Entering IECommandExecutor::OnSetCommand
T 2017-09-05 11:07:33:879 command.cc(31) Entering Command::Deserialize
D 2017-09-05 11:07:33:879 command.cc(36) Raw JSON command: { "name" : "setWindowRect", "locator" : { "sessionid" : "09398a8e-07f7-4abe-9379-28678a65adc5" }, "parameters" : {"width":1600,"height":900} }
T 2017-09-05 11:07:33:879 IECommandExecutor.cpp(133) Entering IECommandExecutor::OnExecCommand
T 2017-09-05 11:07:33:879 IESession.cpp(212) Beginning wait for response length to be not zero
T 2017-09-05 11:07:33:879 IECommandExecutor.cpp(454) Entering IECommandExecutor::DispatchCommand
T 2017-09-05 11:07:33:879 IECommandExecutor.cpp(567) Entering IECommandExecutor::GetCurrentBrowser
T 2017-09-05 11:07:33:879 IECommandExecutor.cpp(573) Entering IECommandExecutor::GetManagedBrowser
W 2017-09-05 11:07:33:879 IECommandExecutor.cpp(581) Browser ID requested was an empty string
W 2017-09-05 11:07:33:879 IECommandExecutor.cpp(497) Unable to find current browser
T 2017-09-05 11:07:33:879 IECommandExecutor.cpp(567) Entering IECommandExecutor::GetCurrentBrowser
T 2017-09-05 11:07:33:879 IECommandExecutor.cpp(573) Entering IECommandExecutor::GetManagedBrowser
W 2017-09-05 11:07:33:879 IECommandExecutor.cpp(581) Browser ID requested was an empty string
T 2017-09-05 11:07:33:879 response.cc(85) Entering Response::SetErrorResponse
T 2017-09-05 11:07:33:879 response.cc(78) Entering Response::SetResponse
T 2017-09-05 11:07:33:879 IECommandExecutor.cpp(567) Entering IECommandExecutor::GetCurrentBrowser
T 2017-09-05 11:07:33:879 IECommandExecutor.cpp(573) Entering IECommandExecutor::GetManagedBrowser
W 2017-09-05 11:07:33:879 IECommandExecutor.cpp(581) Browser ID requested was an empty string
W 2017-09-05 11:07:33:879 IECommandExecutor.cpp(514) Unable to get current browser
T 2017-09-05 11:07:33:879 response.cc(51) Entering Response::Serialize
T 2017-09-05 11:07:33:898 IESession.cpp(221) Found non-zero response length
T 2017-09-05 11:07:33:898 IECommandExecutor.cpp(156) Entering IECommandExecutor::OnGetResponse
T 2017-09-05 11:07:33:898 IECommandExecutor.cpp(285) Entering IECommandExecutor::OnIsSessionValid
D 2017-09-05 11:07:33:898 server.cc(338) Response: {"value":{"data":null,"error":"no such window","message":"Error retrieving current window","stacktrace":""}}
```
I am also attaching full log file for your reference.

 log file

**Comment by shankarkc** [comment] 2017-09-07 06:02
Hi did the callstack help? Why its failing on Win10 & IE11? Are there any workaounds?

**Comment by shankarkc** [comment] 2017-09-11 02:23
@barancev did attached logfile help to find root cause?  Please let me know if you need more details.

**Comment by jimevans** [comment] 2017-09-11 03:24
@shankarkc Please provide the full log, not just the portion of it.

**Comment by shankarkc** [comment] 2017-09-11 06:45
My bad. Sorry @jimevans / @barancev ...Attaching the log file.

[iedriver.txt](https://github.com/SeleniumHQ/selenium/files/1291610/iedriver.txt)

Thanks
Shankar KC

**Comment by sarthak2990** [comment] 2018-04-20 07:14
Is their any fix/solution for this?

**Comment by TychonautVII** [comment] 2019-01-30 22:08
I'm running into a similar issue after applying all the required configuration for IE11, including the registry entry, and trying the methods mentioned here

**Comment by sharmsa66** [comment] 2019-02-09 20:09
I am also having same issue. Please advise.

**Comment by jimevans** [comment] 2019-02-09 23:01
There has yet to be a trace log added with a version of IEDriverServer.exe later than 3.5, which would be required to diagnose the issue any further. Anyone asking “is there any other fix,” or “please advise” will need to provide that information first.

**Comment by TychonautVII** [comment] 2019-02-10 18:08
@jimevans that makes sense! See attached. I'm on windows 10 64bit with IE 11, and have followed the directions in the required config section of the wiki 

[ie_service.log](https://github.com/SeleniumHQ/selenium/files/2849202/ie_service.log)

**Comment by jimevans** [comment] 2019-02-10 18:28
@TychonautVII Looking at the logs you posted, the root cause of your issue is that you’re attempting to navigate to a `file://` URL on your local machine. Local file URLs are parsed into a Protected Mode zone that does not appear in the Internet Explorer UI. What happens when you host the page you’re automating on an actual web server and attempt to automate IE with that?

**Comment by TychonautVII** [comment] 2019-02-10 19:44
Thanks to taking a look at my logs @jimevans!

If I actually host my files on a local server, this does seem to work. 

In my application, these HTML files are actually delivered as files meant to be open by the clients and used in the browser on their computer without a server. They still have JavaScript content though. Serving the files locally makes my tests less like what my users will actually see, but this is a better work around than I had before, which was basically drop Selenium and switch to JavaScript based testing haha.

Is there any way to get this other protected mode zone aligned with the other 4? 

Also I totally get that there might be nothing that can be done on this given how IE works, and my application might be a little fringe. However even so, I think spelling this out is worth a paragraph in the IE Explorer Driver wiki, maybe in the required configuration section. It might be worth adding it to an initialization check or the protect mode check or somewhere else in the code / logs.  That would probably save some people some heartache, particularly given that I think the people most likely to be trying to test local files are people playing around trying to get this to work for the first time.

**Comment by barancev** [comment] 2019-07-14 19:09
Sorry for leaving this issue unanswered. As @jimevans said IE handles file:// protocol in a different mode and we have no plans to improve support for this mode in Selenium. So we'll close this issue.

But you can try to get help of the community, maybe someone knows how to tune IE properly to better handle this protocol:
- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Closed by barancev** 2019-07-14 19:09 UTC
Labels: D-IE
