### ISSUE TITLE
Javascript selenium-webdriver: environment variable SELENIUM_BROWSER does not work when SELENIUM_REMOTE_URL is set

### ISSUE THREAD

**Issue by timoatexove** [SeleniumHQ/selenium#4329] opened 2017-07-18 07:51 UTC
## Meta -
OS:  OSX, Windows 7-10, Linux

Selenium Version:  3.4.0

Browser:  Any supported browser

Browser Version:  

## Expected Behavior 
- the correct browser starts running at the correct remote grid hub slave

## Actual Behavior 
-  WebDriverError: Error forwarding the new session cannot find : Capabilities [{browserName=ie, version=11, platform=WINDOWS}]

## Steps to reproduce 
- use npm-installed js bindings of selenium (selenium-webdriver)
- use selenium-webdriver code with mocha
- override hardcoded browser name with:
SELENIUM_REMOTE_URL=http://classified_url:4444/wd/hub SELENIUM_BROWSER=ie:11:WINDOWS   node_modules/mocha/bin/mocha testfilename.js
- The same error can be produced also with SELENIUM_BROWSER=firefox:54:LINUX, or any browser installed in the slave computers
- PLEASE NOTE THAT IF E.G. 'ie' is hardcoded, the remote execution works, as in 'driver = new selenium.Builder().
  withCapabilities(selenium.Capabilities.ie()).
  build();'
- also note that if SELENIUM_REMOTE_URL is left out, the browser name override works
- THE BUG OCCURS ONLY when both SELENIUM_REMOTE_URL and SELENIUM_BROWSER are given as cmd line parameters.

**Comment by jleyba** [comment] 2017-07-21 18:22
I'm not able to reproduce.

```shell
$ SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub \
SELENIUM_BROWSER=chrome \
node node_modules/selenium-webdriver/example/logging.js
[2017-07-21T18:07:05Z] [FINEST] [webdriver.http] Translating command: newSession
[2017-07-21T18:07:05Z] [FINEST] [webdriver.http] Building HTTP request: {"method":"POST","path":"/session"}
[2017-07-21T18:07:05Z] [FINER] [webdriver.http.Executor] >>> POST /session
[2017-07-21T18:07:07Z] [FINER] [webdriver.http.Executor] >>>
POST /session HTTP/1.1
accept: application/json; charset=utf-8

{"desiredCapabilities":{"browserName":"chrome"}}
<<<
HTTP/1.1 200
connection: close
date: Fri, 21 Jul 2017 18:07:05 GMT
expires: Thu, 01 Jan 1970 00:00:00 GMT
cache-control: no-cache, no-cache
content-type: application/json;charset=utf-8
content-length: 925
server: Jetty(9.4.3.v20170317)

{"state":null,"sessionId":"c887db6a-779b-4e11-8897-699343590aa7","hCode":1219543622,"value":{"applicationCacheEnabled":false,"rotatable":false,"mobileEmulationEnabled":false,"networkConnectionEnabled":true,"chrome":{"chromedriverVersion":"2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57)","userDataDir":"/tmp/.org.chromium.Chromium.Rph1eP"},"takesHeapSnapshot":true,"pageLoadStrategy":"normal","unhandledPromptBehavior":"","databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":true,"version":"59.0.3071.115","platform":"LINUX","browserConnectionEnabled":false,"nativeEvents":true,"acceptSslCerts":true,"webdriver.remote.sessionid":"c887db6a-779b-4e11-8897-699343590aa7","locationContextEnabled":true,"webStorageEnabled":true,"browserName":"chrome","takesScreenshot":true,"javascriptEnabled":true,"cssSelectorsEnabled":true,"unexpectedAlertBehaviour":""},"class":"org.openqa.selenium.remote.Response","status":0}
```

Also works if I specify a version and platform with `SELENIUM_BROWSER`:

```shell
$ SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub \
SELENIUM_BROWSER=chrome:59.0.3071.115:linux \
node node_modules/selenium-webdriver/example/logging.js 
[2017-07-21T18:08:32Z] [FINEST] [webdriver.http] Translating command: newSession
[2017-07-21T18:08:32Z] [FINEST] [webdriver.http] Building HTTP request: {"method":"POST","path":"/session"}
[2017-07-21T18:08:32Z] [FINER] [webdriver.http.Executor] >>> POST /session
[2017-07-21T18:08:34Z] [FINER] [webdriver.http.Executor] >>>
POST /session HTTP/1.1
accept: application/json; charset=utf-8

{"desiredCapabilities":{"browserName":"chrome","version":"59.0.3071.115","platform":"linux"}}
<<<
HTTP/1.1 200
connection: close
date: Fri, 21 Jul 2017 18:08:32 GMT
expires: Thu, 01 Jan 1970 00:00:00 GMT
cache-control: no-cache, no-cache
content-type: application/json;charset=utf-8
content-length: 925
server: Jetty(9.4.3.v20170317)

{"state":null,"sessionId":"213f2c72-f2a2-4b36-8fd8-84efb98352f7","hCode":2087356998,"value":{"applicationCacheEnabled":false,"rotatable":false,"mobileEmulationEnabled":false,"networkConnectionEnabled":true,"chrome":{"chromedriverVersion":"2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57)","userDataDir":"/tmp/.org.chromium.Chromium.pugxjh"},"takesHeapSnapshot":true,"pageLoadStrategy":"normal","unhandledPromptBehavior":"","databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":true,"version":"59.0.3071.115","platform":"LINUX","browserConnectionEnabled":false,"nativeEvents":true,"acceptSslCerts":true,"webdriver.remote.sessionid":"213f2c72-f2a2-4b36-8fd8-84efb98352f7","locationContextEnabled":true,"webStorageEnabled":true,"browserName":"chrome","takesScreenshot":true,"javascriptEnabled":true,"cssSelectorsEnabled":true,"unexpectedAlertBehaviour":""},"class":"org.openqa.selenium.remote.Response","status":0}
```

I changed the example script to:

```js
var driver = new Builder().withCapabilities(Capabilities.firefox()).build();
```

I'm still able to override the config:


```shell
$ node node_modules/selenium-webdriver/example/logging.js 
[2017-07-21T18:11:44Z] [FINEST] [webdriver.http] Translating command: newSession
[2017-07-21T18:11:44Z] [FINEST] [webdriver.http] Building HTTP request: {"method":"POST","path":"/session"}
[2017-07-21T18:11:44Z] [FINER] [webdriver.http.Executor] >>> POST /session
[2017-07-21T18:11:44Z] [FINEST] [webdriver.http] Translating command: getStatus
[2017-07-21T18:11:44Z] [FINEST] [webdriver.http] Building HTTP request: {"method":"GET","path":"/status"}
[2017-07-21T18:11:44Z] [FINER] [webdriver.http.Executor] >>> GET /status
[2017-07-21T18:11:44Z] [FINER] [webdriver.http.Executor] >>>
GET /status HTTP/1.1
accept: application/json; charset=utf-8

{}
<<<
HTTP/1.1 200
connection: close
content-type: application/json; charset=utf-8
cache-control: no-cache
content-length: 37
date: Fri, 21 Jul 2017 18:11:44 GMT

{"value":{"message":"","ready":true}}
[2017-07-21T18:11:47Z] [FINER] [webdriver.http.Executor] >>>
POST /session HTTP/1.1
accept: application/json; charset=utf-8

{"desiredCapabilities":{"browserName":"firefox","moz:firefoxOptions":{}}}
<<<
HTTP/1.1 200
connection: close
content-type: application/json; charset=utf-8
cache-control: no-cache
content-length: 448
date: Fri, 21 Jul 2017 18:11:47 GMT

{"value": {"sessionId":"e5777c16-c068-4651-8d8f-64b4151e0697","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"54.0","moz:accessibilityChecks":false,"moz:processID":32098,"moz:profile":"/tmp/rust_mozprofile.S7EGkoNUnUxf","pageLoadStrategy":"normal","platformName":"linux","platformVersion":"4.4.0-79-generic","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
```

```shell
$ SELENIUM_BROWSER=chrome \
    SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub \
    node node_modules/selenium-webdriver/example/logging.js 
[2017-07-21T18:13:34Z] [FINEST] [webdriver.http] Translating command: newSession
[2017-07-21T18:13:34Z] [FINEST] [webdriver.http] Building HTTP request: {"method":"POST","path":"/session"}
[2017-07-21T18:13:34Z] [FINER] [webdriver.http.Executor] >>> POST /session
[2017-07-21T18:13:36Z] [FINER] [webdriver.http.Executor] >>>
POST /session HTTP/1.1
accept: application/json; charset=utf-8

{"desiredCapabilities":{"browserName":"chrome"}}
<<<
HTTP/1.1 200
connection: close
date: Fri, 21 Jul 2017 18:13:34 GMT
expires: Thu, 01 Jan 1970 00:00:00 GMT
cache-control: no-cache, no-cache
content-type: application/json;charset=utf-8
content-length: 925
server: Jetty(9.4.3.v20170317)

{"state":null,"sessionId":"a721602e-bab6-4dd5-999c-ed62cc4784d0","hCode":1000359814,"value":{"applicationCacheEnabled":false,"rotatable":false,"mobileEmulationEnabled":false,"networkConnectionEnabled":true,"chrome":{"chromedriverVersion":"2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57)","userDataDir":"/tmp/.org.chromium.Chromium.OwpYVD"},"takesHeapSnapshot":true,"pageLoadStrategy":"normal","unhandledPromptBehavior":"","databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":true,"version":"59.0.3071.115","platform":"LINUX","browserConnectionEnabled":false,"nativeEvents":true,"acceptSslCerts":true,"webdriver.remote.sessionid":"a721602e-bab6-4dd5-999c-ed62cc4784d0","locationContextEnabled":true,"webStorageEnabled":true,"browserName":"chrome","takesScreenshot":true,"javascriptEnabled":true,"cssSelectorsEnabled":true,"unexpectedAlertBehaviour":""},"class":"org.openqa.selenium.remote.Response","status":0}
```

As a final test, I changed the script to not specify a browser via code. This causes the script to fail if `SELENIUM_BROWSER` is not set (expected), but it works when set:

```shell
$ node node_modules/selenium-webdriver/example/logging.js 
/usr/local/home/jleyba/dev/scratch/node_modules/selenium-webdriver/index.js:572
      throw TypeError(
      ^

TypeError: Target browser must be a string, but is <undefined>; did you forget to call forBrowser()?
    at Builder.build (/usr/local/home/jleyba/dev/scratch/node_modules/selenium-webdriver/index.js:572:13)
    at Object.<anonymous> (/usr/local/home/jleyba/dev/scratch/node_modules/selenium-webdriver/example/logging.js:30:28)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

```shell
$ SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub \
  SELENIUM_BROWSER=chrome:59.0.3071.115:linux \
  node node_modules/selenium-webdriver/example/logging.js
[2017-07-21T18:18:12Z] [FINEST] [webdriver.http] Translating command: newSession
[2017-07-21T18:18:12Z] [FINEST] [webdriver.http] Building HTTP request: {"method":"POST","path":"/session"}
[2017-07-21T18:18:12Z] [FINER] [webdriver.http.Executor] >>> POST /session
[2017-07-21T18:18:14Z] [FINER] [webdriver.http.Executor] >>>
POST /session HTTP/1.1
accept: application/json; charset=utf-8

{"desiredCapabilities":{"browserName":"chrome","version":"59.0.3071.115","platform":"linux"}}
<<<
HTTP/1.1 200
connection: close
date: Fri, 21 Jul 2017 18:18:12 GMT
expires: Thu, 01 Jan 1970 00:00:00 GMT
cache-control: no-cache, no-cache
content-type: application/json;charset=utf-8
content-length: 924
server: Jetty(9.4.3.v20170317)

{"state":null,"sessionId":"37da2b4d-bb04-46ca-82f3-6a4639796a22","hCode":839051473,"value":{"applicationCacheEnabled":false,"rotatable":false,"mobileEmulationEnabled":false,"networkConnectionEnabled":true,"chrome":{"chromedriverVersion":"2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57)","userDataDir":"/tmp/.org.chromium.Chromium.JQErnm"},"takesHeapSnapshot":true,"pageLoadStrategy":"normal","unhandledPromptBehavior":"","databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":true,"version":"59.0.3071.115","platform":"LINUX","browserConnectionEnabled":false,"nativeEvents":true,"acceptSslCerts":true,"webdriver.remote.sessionid":"37da2b4d-bb04-46ca-82f3-6a4639796a22","locationContextEnabled":true,"webStorageEnabled":true,"browserName":"chrome","takesScreenshot":true,"javascriptEnabled":true,"cssSelectorsEnabled":true,"unexpectedAlertBehaviour":""},"class":"org.openqa.selenium.remote.Response","status":0}
```

I'm going to close this since it's not reproducible, but we can revisit the issue if you can provide a concrete reproducible test case

**Closed by jleyba** 2017-07-21 18:22 UTC
Labels: C-nodejs

**Comment by timoatexove** [comment] 2017-07-31 10:05
Thanks jleyba, I'll try again with complete browser version; the documentation suggests that the major part is sufficient.

**Comment by timoatexove** [comment] 2017-07-31 10:59
I'm sorry but I cannot paste our actual test code here, nor can I give our actual SELENIUM_REMOTE_URL.

However, these commands still fail:

SELENIUM_REMOTE_URL=http://<CLASSIFIED_URL>:4444/wd/hub \ SELENIUM_BROWSER=ie:11:WINDOWS node_modules/mocha/bin/mocha test_file.js

- Produces: "WebDriverError: Error forwarding the new session cannot find : Capabilities [{browserName=ie, version=11, platform=WINDOWS}]"

SELENIUM_REMOTE_URL=http://<CLASSIFIED_URL>:4444/wd/hub \ SELENIUM_BROWSER=chrome:60.0.3112.78-1:LINUX node_modules/mocha/bin/mocha test_file.js

- Produces: "WebDriverError: Error forwarding the new session cannot find : Capabilities [{browserName=chrome, version=60.0.3112.78-1, platform=LINUX}]"

SELENIUM_REMOTE_URL=http://<CLASSIFIED_URL>:4444/wd/hub \ SELENIUM_BROWSER=chrome:60:LINUX node_modules/mocha/bin/mocha test_file.js

- Produces: "WebDriverError: Error forwarding the new session cannot find : Capabilities [{browserName=chrome, version=60, platform=LINUX}]"

This works (probably because chrome is hard-coded in the build command):

SELENIUM_REMOTE_URL=http://<CLASSIFIED_URL>:4444/wd/hub \ SELENIUM_BROWSER=chrome node_modules/mocha/bin/mocha test_file.js

- starts running chrome at one of our Linux slaves

===============================
Conclusion: The only way still for us to run the suite on IE11, at one of our Windows slaves, is to hard-code the 'ie' into the build command, thus: "driver = new selenium.Builder().
  withCapabilities(selenium.Capabilities.ie()).
  build();"

**Comment by timoatexove** [comment] 2017-07-31 11:49
These fail as well:

SELENIUM_REMOTE_URL=http://<CLASSIFIED_URL>:4444/wd/hub \ SELENIUM_BROWSER=firefox:52:LINUX node_modules/mocha/bin/mocha test_file.js

- produces: "WebDriverError: Error forwarding the new session cannot find : Capabilities [{browserName=firefox, moz:firefoxOptions={}, version=52, platform=LINUX}]"

SELENIUM_REMOTE_URL=http://<CLASSIFIED_URL>:4444/wd/hub \ SELENIUM_BROWSER=firefox:52.2.0:LINUX node_modules/mocha/bin/mocha test_file.js

- produces: "WebDriverError: Error forwarding the new session cannot find : Capabilities [{browserName=firefox, moz:firefoxOptions={}, version=52.2.0, platform=LINUX}]"

Likewise, this

SELENIUM_REMOTE_URL=http://<CLASSIFIED_URL>:4444/wd/hub \ SELENIUM_BROWSER=firefox:54.0.1:WINDOWS node_modules/mocha/bin/mocha test_file.js

- produces: "WebDriverError: Error forwarding the new session cannot find : Capabilities [{browserName=firefox, moz:firefoxOptions={}, version=54.0.1, platform=WINDOWS}]"

=================================
It should be noted that we are able to run tests remotely on IE, chrome and firefox, on MAC, Linux and Windows, via Python code, so the slaves and selenium servers and drivers do work.

**Comment by timoatexove** [comment] 2017-08-01 05:26
As I reread jleyba's test run logs, I noticed that jleyba ran the tests on localhost. The bug does not occur on localhost for me either, only on remote host, where there are several slave computers with different OS's, under one selenium grid hub.
