### ISSUE TITLE
Firefox 42.0 Windows 64-bit: Unable to connect to host

### ISSUE THREAD

**Issue by dhoer** [SeleniumHQ/selenium#1287] opened 2015-11-19 18:33 UTC
Firefox 42.0 64bit
Windows Server 2012R2
Selenium 2.48.2
Java JDK 8u66

Note that the 32-bit version seems to work ok.

```
Exception in thread "main" org.openqa.selenium.WebDriverException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"45.0"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1447952464646	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1447952464649	DeferredSave.extensions.json	DEBUG	Starting timer
1447952464649	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1447952464649	DeferredSave.extensions.json	DEBUG	Save changes
1447952464649	DeferredSave.extensions.json	DEBUG	Save changes
1447952464649	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"2WZgrT6JlD7q","location":"app-global","version":"42.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate":1447920834969,"updateDate":1447920834969,"applyBackgroundUpdates":1,"skinnable":true,"size":24301,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"42.0","maxVersion":"42.0"}],"targetPlatforms":[]}
1447952464649	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1447952464650	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1447952464650	addons.xpi-utils	DEBUG	Updating add-on states
1447952464651	addons.xpi-utils	DEBUG	Writing add-ons list
1447952464657	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1447952464658	addons.manager	DEBUG	Provider finished startup: XPIProvider
1447952464658	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1447952464658	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1447952464658	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1447952464658	addons.manager	DEBUG	Starting provider: GMPProvider
1447952464662	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1447952464662	addons.manager	DEBUG	Provider finished startup: GMPProvider
1447952464663	addons.manager	DEBUG	Starting provider: PluginProvider
1447952464663	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1447952464663	addons.manager	DEBUG	Provider finished startup: PluginProvider
1447952464663	addons.manager	DEBUG	Completed startup sequence
1447952464837	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1447952464837	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1447952464837	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1447952464918	DeferredSave.extensions.json	DEBUG	Starting write
1447952465084	addons.repository	DEBUG	No addons.json found.
1447952465084	DeferredSave.addons.json	DEBUG	Save changes
1447952465086	DeferredSave.addons.json	DEBUG	Starting timer
1447952465097	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1447952465097	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1447952465097	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1447952465100	DeferredSave.extensions.json	DEBUG	Write succeeded
1447952465100	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1447952465163	DeferredSave.addons.json	DEBUG	Starting write
1447952465168	DeferredSave.addons.json	DEBUG	Write succeeded

Command duration or timeout: 48.11 seconds
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'N/A', ip: 'N/A', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.1', java.version: '1.7.0_67'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)
	at com.openqa.selenium.example.Selenium2Example.main(Selenium2Example.java:49)
Caused by: org.openqa.selenium.remote.ErrorHandler$UnknownServerException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"45.0"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1447952464646	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1447952464649	DeferredSave.extensions.json	DEBUG	Starting timer
1447952464649	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1447952464649	DeferredSave.extensions.json	DEBUG	Save changes
1447952464649	DeferredSave.extensions.json	DEBUG	Save changes
1447952464649	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"2WZgrT6JlD7q","location":"app-global","version":"42.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate":1447920834969,"updateDate":1447920834969,"applyBackgroundUpdates":1,"skinnable":true,"size":24301,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"42.0","maxVersion":"42.0"}],"targetPlatforms":[]}
1447952464649	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1447952464650	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1447952464650	addons.xpi-utils	DEBUG	Updating add-on states
1447952464651	addons.xpi-utils	DEBUG	Writing add-ons list
1447952464657	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1447952464658	addons.manager	DEBUG	Provider finished startup: XPIProvider
1447952464658	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1447952464658	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1447952464658	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1447952464658	addons.manager	DEBUG	Starting provider: GMPProvider
1447952464662	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1447952464662	addons.manager	DEBUG	Provider finished startup: GMPProvider
1447952464663	addons.manager	DEBUG	Starting provider: PluginProvider
1447952464663	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1447952464663	addons.manager	DEBUG	Provider finished startup: PluginProvider
1447952464663	addons.manager	DEBUG	Completed startup sequence
1447952464837	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1447952464837	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1447952464837	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1447952464918	DeferredSave.extensions.json	DEBUG	Starting write
1447952465084	addons.repository	DEBUG	No addons.json found.
1447952465084	DeferredSave.addons.json	DEBUG	Save changes
1447952465086	DeferredSave.addons.json	DEBUG	Starting timer
1447952465097	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1447952465097	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1447952465097	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1447952465100	DeferredSave.extensions.json	DEBUG	Write succeeded
1447952465100	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1447952465163	DeferredSave.addons.json	DEBUG	Starting write
1447952465168	DeferredSave.addons.json	DEBUG	Write succeeded

Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'N/A', ip: 'N/A', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.1', java.version: '1.7.0_67'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:122)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:129)
	at sun.reflect.GeneratedConstructorAccessor11.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:91)
	at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:68)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by barancev** [comment] 2016-01-25 14:37
Duplicate of #1431

**Closed by barancev** 2016-01-25 14:37 UTC
Labels: D-firefox
