### ISSUE TITLE
[🐛 Bug]: Deadlock in Selenium Java bindings

### ISSUE THREAD

**Issue by asolntsev** [SeleniumHQ/selenium#12576] opened 2023-08-19 17:47 UTC
### What happened?

My Java test opens a browser and **hangs forever**. 

### How can we reproduce the issue?

```shell
I managed to create a simple reproducible example: https://github.com/asolntsev/selenium-deadlock

When running `mvn test`, it hangs immediately.

A sample thread dump is stored [here](https://github.com/asolntsev/selenium-deadlock/blob/main/thread-dump.txt).
It contains two threads blocking each other: "main" #1 and "CDP Connection" #57.
```

### Relevant log output

```shell
https://github.com/asolntsev/selenium-deadlock/blob/main/thread-dump.txt
```

### Operating System

MacOS (no matter)

### Selenium version

4.11.0 - 4.9.0 (probably older versions too)

### What are the browser(s) and version(s) where you see this issue?

Chrome 116, Edge 115 (versions don't really matter)

### What are the browser driver(s) and version(s) where you see this issue?

automatically downloaded by SeleniumManager

### Are you using Selenium Grid?

no

**Comment by joerg1985** [comment] 2023-08-22 19:20
I had a look at this and i could not find the root cause for this on the first look.
But i have done a fix to the code, the listeners where added and called multiple times for each event.

https://github.com/SeleniumHQ/selenium/commit/4641ff189d96d285428459f14fd0694069b37f6e

**Comment by diemol** [comment] 2023-08-23 12:51
@asolntsev does this fix the issue? You can test it with the Nightly release. https://www.selenium.dev/downloads/#nightly

**Comment by asolntsev** [comment] 2023-08-23 14:34
@diemol @joerg1985 No, it doesn't help. I updated my sample project to run on latest Selenium 4.12.0-SNAPSHOT:
https://github.com/asolntsev/selenium-deadlock

Just clone it and run `mvn test`. The deadlock still happens. :(

**Comment by joerg1985** [comment] 2023-08-23 15:49
Sorry i did not post an update here... i had to undo the change as the CI was failing.
I had a closer look at the implementation and there are multiple things to fix:
1. `NetworkInterceptor.close` does set a flag in `Network`, all following uses of `NetworkInterceptor` will not longer log errors because of this.
2. `NetworkInterceptor.prepareToInterceptTraffic` does register the callbacks multiple times.
     The events are processed multiple times and raise a lot of warning logs.
3. The `Network` will block the thread handling the request until the response is comming to replace the response.
    This is not needed we should be able to instantly send fullfilRequest instead.
PS:
4. The original request was not intercepted, there was only the response replaced. 

A first fix is in work at https://github.com/joerg1985/selenium/tree/interceptor

**Comment by BorisOsipov** [comment] 2023-08-24 18:13
@asolntsev It seems to be accidentally closed

**Comment by joerg1985** [comment] 2023-08-24 18:35
Sorry, i think closing the PR did close this too.
I am now working on a minimal fix without fixing the other stuff in
https://github.com/joerg1985/selenium/tree/cnn-deadlock

**Comment by titusfortner** [comment] 2023-08-26 23:42
@joerg1985 does that commit fix this issue or is there more that needs to be done? Thanks.

**Comment by joerg1985** [comment] 2023-08-27 08:38
The code to reproduce is working in debug mode for me, in run mode it still locks up sometimes.
I just pushed another fix for a deadlock when driver.quit is called while responses are pending.
Will need to do further test the network interception to see if all deadlocks are gone now.

**Comment by joerg1985** [comment] 2023-08-28 16:00
@asolntsev Just completed the test with `@RepeatedTest(1000)` without deadlocks.

There is still potential for deadlocks in the class e.g. when createSeMessages fails.
But i think we can close this issue for now.

**Closed as completed by joerg1985** 2023-08-28 16:00 UTC
Labels: C-java, I-defect, B-devtools

**Comment by asolntsev** [comment] 2023-08-29 16:56
I confirm, the problem doesn't happen anymore with the latest nightly build. 

Thumbs up @joerg1985!
