### ISSUE TITLE
Can't run Firefox with Selenium Grid 3.6 implicit_wait did not match a known command

### ISSUE THREAD

**Issue by eugeniominissale** [SeleniumHQ/selenium#4944] opened 2017-10-24 22:33 UTC
OS: OSX 10.12.5
Selenium Version: 3.3.1
Browser: Firefox 56
selenium-server-standalone: 3.6.0
Python 2.7.13
geckodriver 0.19.0

Hello everyone. I can't run firefox with selenium grid.

Python webdriver setup code: 
``
driver = webdriver.Remote(
    command_executor="http://localhost:4444/wd/hub",
    desired_capabilities={
        "browserName": "firefox",
        "marionette": "true",
       "javascriptEnabled": True,
})
``
This is the traceback i get:

```
Traceback (most recent call last):
  File "main_fb_user.py", line 504, in <module>
    callback(message)
  File "main_fb_user.py", line 334, in callback
    wait_fb_login(browser)
  File "/Users/eugenio/hoopygang/crawler_stage_fb/py_fb_crawler/selenium_utils.py", line 47, in wait_fb_login
    browser.implicitly_wait(3)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 694, in implicitly_wait
    'ms': float(time_to_wait) * 1000})
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: POST /session/bfe672e0-a5cd-834b-b47b-f01baa195699/timeouts/implicit_wait did not match a known command
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'MBP.station', ip: 'fe80:0:0:0:1068:d7a:cca3:e867%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '9'
```

**Comment by lmtierney** [comment] 2017-10-25 02:01
Update your selenium version. You're using the latest in grid but your python bindings are pretty old

**Comment by eugeniominissale** [comment] 2017-10-25 08:18
Yes, I have updated Selenium version to 3.6.0. Now I'm able to open Firefox, but I can't make a connection. 
It waits for about a minute and throws the following exception:
``
Message: connection refused
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'MacBook-Pro', ip: 'fe80:0:0:0:1068:d7a:cca3:e867%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '9'
Driver info: driver.version: unknown
remote stacktrace: stack backtrace:
   0:        0x104f8ba8e - backtrace::backtrace::trace::h69682bcb53decaf6
   1:        0x104f8bacc - backtrace::capture::Backtrace::new::hdc9d731a957304a6
   2:        0x104ebc434 - webdriver::error::WebDriverError::new::h930061353eac4c81
   3:        0x104ec3520 - geckodriver::marionette::MarionetteHandler::create_connection::hc09196342b760e35
   4:        0x104ea37d4 - _$LT$webdriver..server..Dispatcher$LT$T$C$$u20$U$GT$$GT$::run::hfda25a6dc0b512aa
   5:        0x104e7b645 - std::sys_common::backtrace::__rust_begin_short_backtrace::h95009c1d3a320838
   6:        0x104e8311d - std::panicking::try::do_call::h8c5f07f1fc714fb2
   7:        0x10503c9cc - __rust_maybe_catch_panic
   8:        0x104e98f55 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h6a96e09ff4d37bff
   9:        0x105038c3b - std::sys::imp::thread::Thread::new::thread_start::h823686b907c11c46
  10:     0x7fffb6c2993a - _pthread_body
  11:     0x7fffb6c29886 - _pthread_start
Stacktrace:
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0 (NativeConstructorAccessorImpl.java:-2)
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance (NativeConstructorAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:488)
    at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0 (W3CHandshakeResponse.java:57)
    at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2 (W3CHandshakeResponse.java:104)
    at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24 (ProtocolHandshake.java:359)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:195)
    at java.util.Spliterators$ArraySpliterator.tryAdvance (Spliterators.java:958)
    at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:127)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:502)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:488)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:474)
    at java.util.stream.FindOps$FindOp.evaluateSequential (FindOps.java:152)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.findFirst (ReferencePipeline.java:476)
    at org.openqa.selenium.remote.ProtocolHandshake.createSession (ProtocolHandshake.java:362)
    at org.openqa.selenium.remote.server.ServicedSession$Factory.apply (ServicedSession.java:185)
    at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$createSession$16 (ActiveSessionFactory.java:171)
    at java.util.Optional.map (Optional.java:257)
    at org.openqa.selenium.remote.server.ActiveSessionFactory.createSession (ActiveSessionFactory.java:171)
    at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute (BeginSession.java:72)
    at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0 (WebDriverServlet.java:232)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:514)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
    at java.lang.Thread.run (Thread.java:844)
Traceback (most recent call last):
  File "main_fb_user.py", line 504, in <module>
    callback(message)
  File "main_fb_user.py", line 332, in callback
    with contextlib.closing(get_browser(debug=DEBUG)) as browser:
  File "/Users/eugenio/hoopygang/crawler_stage_fb/py_fb_crawler/selenium_utils.py", line 22, in get_browser
    "javascriptEnabled": True
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 151, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 240, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
``

**Comment by lmtierney** [comment] 2017-10-25 17:57
`javascriptEnabled` is no longer a valid capability (for w3c)... Can you try without sending that? However, I'm not sure that's the underlying issue. The stacktrace isn't very helpful

**Comment by eugeniominissale** [comment] 2017-10-25 20:31
I agree that the stacktrace doesn't help at all.
Anyway removing `javascriptEnabled ` the error persists.

**Comment by lmtierney** [comment] 2017-10-25 21:13
I am unable to reproduce this with using the same versions and code as you. Are you sure you don't have multiple versions of geckodriver installed and it isn't selecting the wrong one?

**Comment by lmtierney** [comment] 2017-10-25 21:14
Can you start your grid with the `-debug` flag on and post that trace?

**Comment by eugeniominissale** [comment] 2017-10-25 21:40
Here it is.

Hub log: 
```
hub                  | 21:34:13.693 INFO - Got a request to create a new session: Capabilities [{browserName=firefox}]
hub                  | 21:34:13.694 INFO - Trying to create a new session on test slot {seleniumProtocol=WebDriver, browserName=firefox, maxInstances=5, platform=MAC}
hub                  | 21:34:40.178 WARN - session ext. key 429cc0b3e6316e44b9e20259ec690446 has TIMED OUT due to client inactivity and will be released.
```

Node log:

```
23:38:16.363 INFO - Binding default provider to: org.openqa.selenium.chrome.ChromeDriverService
23:38:16.363 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@448a5bd0
23:38:16.364 INFO - /session: Executing POST on /session (handler: BeginSession)
23:38:16.366 INFO - Capabilities are: Capabilities {browserName=firefox}
23:38:16.366 INFO - Capabilities {browserName=firefox} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
23:38:16.366 INFO - Capabilities {browserName=firefox} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
1508967496377	geckodriver	INFO	geckodriver 0.19.0
1508967496383	geckodriver	INFO	Listening on 127.0.0.1:39484
1508967496444	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-profile" "/var/folders/9b/m3_r2_cj1ll2_w8d0vvxwqm80000gn/T/rust_mozprofile.01ryNefK41LS"
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
1508967497164	Marionette	ERROR	Error on starting server: [Exception... "Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]"  nsresult: "0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE)"  location: "JS frame :: chrome://marionette/content/server.js :: MarionetteServer.prototype.start :: line 105"  data: no]
[Exception... "Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]"  nsresult: "0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE)"  location: "JS frame :: chrome://marionette/content/server.js :: MarionetteServer.prototype.start :: line 105"  data: no]
MarionetteServer.prototype.start@chrome://marionette/content/server.js:105:19
MarionetteComponent.prototype.init@resource://gre/components/marionettecomponent.js:184:5
MarionetteComponent.prototype.handle@resource://gre/components/marionettecomponent.js:99:5

2017-10-25 23:38:50.258 firefox-bin[58731:2804038] IMKInputSession presentFunctionRowItemTextInputViewWithEndpoint:completionHandler: : [self textInputContext]=0x114f89990 *NO* NSRemoteViewController to client, NSError=Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 0" UserInfo={NSDebugDescription=connection from pid 0}, com.apple.inputmethod.EmojiFunctionRowItem
```

**Comment by lmtierney** [comment] 2017-10-26 00:17
Looks like Firefox is having troubles starting up. Is something currently using port 2828?

**Comment by barancev** [comment] 2017-11-08 15:24
Closing the issue, seems to be a configuration issue. But if it continues to fail, report it to geckodriver tracker: https://github.com/mozilla/geckodriver/issues

**Closed by barancev** 2017-11-08 15:24 UTC
Labels: C-grid, C-py, R-awaiting answer
