### ISSUE TITLE
Firefox webdriver 'stuck' after navigating away from https://www.google.ca

### ISSUE THREAD

**Issue by chengli86** [SeleniumHQ/selenium#455] opened 2015-04-14 16:53 UTC
Firefox: Tried 33 and 37
Selenium: 2.45.0
OS: Windows 7 64bit
Python 2.7.9 32 bit

Repro steps:

from selenium import webdriver
d = webdriver.Firefox()
d.get('https://www.google.ca')
d.get('https://www.github.com')
d.close()

Expected:
The browser closes after visiting www.github.com.

Actual:
The github page loads but the browser is waiting for www.google.ca, thus the last line never executes and the webdriver is now stuck.

Not sure what the root cause is but I've only been able to reproduce it visiting google's website.

**Comment by lukeis** [comment] 2015-04-14 17:47
something very strange is going on here... and looks like a google issue itself... I can reproduce this manually and see there's 3 resources that make a GET call and get a 206 response (partial content) and causes the browser to think there's still resources to load and no further response comes.

resources in question:
https://www.google.ca/logos/2015/ponyexpress/gallop-loop.ogg
https://www.google.ca/logos/2015/ponyexpress/impact.ogg
https://www.google.ca/logos/2015/ponyexpress/letter.ogg


Also reproduced with google.com in the US.

@jleyba can you forward on to someone?


As for the selenium aspect... this is working as intended (mostly). We "wait" for resources to load, or do a best effort. Here we actually see the browser is waiting for resources (infinitely) and thus we wait too.

**Comment by DannyCork** [comment] 2015-04-21 16:11
Was this a temporary issue with Google? I don't see these resources being loaded on https://www.google.ca/ . If now unpronounceable we could close this issue :)

**Comment by lukeis** [comment] 2015-04-21 17:30
correct, they've changed their doodle and it's no longer an issue with that scenario... as this isn't actually a bug with selenium and rather some bad web-coding practice, I'm going to close this issue.

In the future to attempt to avoid any stuck loading situations that may occur one will be able to set the [Page Load Strategy](https://w3c.github.io/webdriver/webdriver-spec.html#the-page-load-strategy)

See also the [DesiredCapability](https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities#firefoxprofile-settings) "webdriver.load.strategy" that can be set (firefox only) that implement this spec.

**Closed by lukeis** 2015-04-21 17:30 UTC
