### ISSUE TITLE
Communication with IEDriverServer is 3x slower on Windows Server 2008 than Windows 7

### ISSUE THREAD

**Issue by godlark** [SeleniumHQ/selenium#1353] opened 2015-12-07 12:15 UTC
Both systems are 64bit, both has the same version of Selenium (2.48.0), both has the same of IE (IE11). I'm using 32 bit IEDriverServer. I run a test which checks a lot of dynamic elements. On Windows Server I cannot check all elements because they are no longer valid (because communication is so slow). There is no such problem with IE, Firefox, Chrome on Windows 7 or on Linux. 
I'm using Selenium with Python and I've check communication time with CProfile.

**Comment by godlark** [comment] 2015-12-15 14:09
```D 2015-12-15 14:01:02:587 server.cc(281) Command: POST /session/e7b1de29-83aa-46a8-b2a4-eff1f6f450d1/element/08cfd033-bbd6-4fc9-a1bc-65f7c275bcdd/elements {"using": "tag name", "sessionId": "e7b1de29-83aa-46a8-b2a4-eff1f6f450d1", "id": "08cfd033-bbd6-4fc9-a1bc-65f7c275bcdd", "value": "tr"}
T 2015-12-15 14:01:02:587 server.cc(395) Entering Server::LookupSession
T 2015-12-15 14:01:02:587 IESession.cpp(215) Entering IESession::ExecuteCommand
T 2015-12-15 14:01:02:587 IECommandExecutor.cpp(164) Entering IECommandExecutor::OnSetCommand
T 2015-12-15 14:01:02:587 command.cc(31) Entering Command::Deserialize
D 2015-12-15 14:01:02:587 command.cc(36) Raw JSON command: { "name" : "findChildElements", "locator" : { "sessionid" : "e7b1de29-83aa-46a8-b2a4-eff1f6f450d1", "id" : "08cfd033-bbd6-4fc9-a1bc-65f7c275bcdd" }, "parameters" : {"using": "tag name", "sessionId": "e7b1de29-83aa-46a8-b2a4-eff1f6f450d1", "id": "08cfd033-bbd6-4fc9-a1bc-65f7c275bcdd", "value": "tr"} }
T 2015-12-15 14:01:02:587 IECommandExecutor.cpp(175) Entering IECommandExecutor::OnExecCommand
T 2015-12-15 14:01:02:587 IESession.cpp(236) Beginning wait for response length to be not zero
T 2015-12-15 14:01:02:587 IECommandExecutor.cpp(476) Entering IECommandExecutor::DispatchCommand
T 2015-12-15 14:01:02:587 IECommandExecutor.cpp(593) Entering IECommandExecutor::GetCurrentBrowser
T 2015-12-15 14:01:02:587 IECommandExecutor.cpp(599) Entering IECommandExecutor::GetManagedBrowser
T 2015-12-15 14:01:02:587 IECommandExecutor.cpp(549) Entering IECommandExecutor::IsAlertActive
T 2015-12-15 14:01:02:587 Browser.cpp(702) Entering Browser::GetActiveDialogWindowHandle
T 2015-12-15 14:01:02:587 Browser.cpp(200) Entering Browser::GetContentWindowHandle
D 2015-12-15 14:01:02:587 IECommandExecutor.cpp(563) No alert handle is found
T 2015-12-15 14:01:02:587 IECommandHandler.cpp(40) Entering IECommandHandler::GetElement
T 2015-12-15 14:01:02:587 IECommandExecutor.cpp(690) Entering IECommandExecutor::GetManagedElement
T 2015-12-15 14:01:02:587 ElementRepository.cpp(31) Entering ElementRepository::GetManagedElement
T 2015-12-15 14:01:02:587 IECommandExecutor.cpp(593) Entering IECommandExecutor::GetCurrentBrowser
T 2015-12-15 14:01:02:587 IECommandExecutor.cpp(599) Entering IECommandExecutor::GetManagedBrowser
T 2015-12-15 14:01:02:587 Browser.cpp(120) Entering Browser::GetDocument
I 2015-12-15 14:01:02:587 Browser.cpp(124) No child frame focus. Focus is on top-level frame
T 2015-12-15 14:01:02:603 Browser.cpp(602) Entering Browser::GetDocumentFromWindow
T 2015-12-15 14:01:02:618 IECommandExecutor.cpp(753) Entering IECommandExecutor::LocateElements
T 2015-12-15 14:01:02:618 IECommandExecutor.cpp(714) Entering IECommandExecutor::GetElementFindMethod
T 2015-12-15 14:01:02:618 ElementFinder.cpp(106) Entering ElementFinder::FindElements
T 2015-12-15 14:01:02:618 IECommandExecutor.cpp(593) Entering IECommandExecutor::GetCurrentBrowser
T 2015-12-15 14:01:02:618 IECommandExecutor.cpp(599) Entering IECommandExecutor::GetManagedBrowser
D 2015-12-15 14:01:02:618 ElementFinder.cpp(123) Using FindElements atom to locate element having tagName = tr
T 2015-12-15 14:01:02:618 Browser.cpp(120) Entering Browser::GetDocument
I 2015-12-15 14:01:02:618 Browser.cpp(124) No child frame focus. Focus is on top-level frame
T 2015-12-15 14:01:02:618 Browser.cpp(602) Entering Browser::GetDocumentFromWindow
T 2015-12-15 14:01:02:634 Script.cpp(44) Entering Script::Initialize
T 2015-12-15 14:01:02:634 Script.cpp(65) Entering Script::AddArgument(std::wstring)
T 2015-12-15 14:01:02:634 Script.cpp(100) Entering Script::AddArgument(VARIANT)
T 2015-12-15 14:01:02:634 Script.cpp(65) Entering Script::AddArgument(std::wstring)
T 2015-12-15 14:01:02:634 Script.cpp(100) Entering Script::AddArgument(VARIANT)
T 2015-12-15 14:01:02:634 Script.cpp(94) Entering Script::AddArgument(IHTMLElement*)
T 2015-12-15 14:01:02:634 Script.cpp(100) Entering Script::AddArgument(VARIANT)
T 2015-12-15 14:01:02:634 Script.cpp(164) Entering Script::Execute
T 2015-12-15 14:01:02:634 Script.cpp(472) Entering Script::CreateAnonymousFunction
T 2015-12-15 14:01:02:697 Script.cpp(154) Entering Script::ResultIsArray
T 2015-12-15 14:01:02:697 Script.cpp(144) Entering Script::ResultIsElementCollection
T 2015-12-15 14:01:02:697 Script.cpp(421) Entering Script::ConvertResultToJsonValue
T 2015-12-15 14:01:02:697 VariantUtilities.cpp(270) Entering Script::GetArrayLength
T 2015-12-15 14:01:02:946 response.cc(63) Entering Response::SetSuccessResponse
T 2015-12-15 14:01:02:946 response.cc(69) Entering Response::SetResponse
T 2015-12-15 14:01:02:946 IECommandExecutor.cpp(593) Entering IECommandExecutor::GetCurrentBrowser
T 2015-12-15 14:01:02:946 IECommandExecutor.cpp(599) Entering IECommandExecutor::GetManagedBrowser
T 2015-12-15 14:01:02:946 response.cc(51) Entering Response::Serialize
T 2015-12-15 14:01:02:946 IESession.cpp(245) Found non-zero response length
T 2015-12-15 14:01:02:946 IECommandExecutor.cpp(198) Entering IECommandExecutor::OnGetResponse
T 2015-12-15 14:01:02:946 IECommandExecutor.cpp(313) Entering IECommandExecutor::OnIsSessionValid
D 2015-12-15 14:01:02:946 server.cc(355) Response: {"sessionId":"e7b1de29-83aa-46a8-b2a4-eff1f6f450d1","status":0,"value":[]}
```

**Comment by jimevans** [comment] 2015-12-28 18:25
Is the log an attempt to highlight where you think the issue is? Because the lines in the log that you're pointing out have a difference of around _250 milliseconds_. A difference of this magnitude doesn't seem like the kind of performance hit that you're describing as a problem.

**Comment by barancev** [comment] 2016-01-27 05:49
Closing the issue as there is no responce from the author for long period.

**Closed by barancev** 2016-01-27 05:49 UTC
Labels: D-IE, R-awaiting answer

**Comment by godlark** [comment] 2016-02-16 11:04
Sorry for not responding
[ie_logs.txt](https://github.com/SeleniumHQ/selenium/files/132292/ie_logs.txt) - logs from Windows Server
[ie_logs.txt](https://github.com/SeleniumHQ/selenium/files/132293/ie_logs.txt) - logs from Windows 7

There is about 200 requests do IEDriverServer.exe. The average time is 240ms for Windows Server and 190ms for Windows 7. There is only 184 requests on Windows Server, because the test fails, because the webpage is not valid anymore.

**Comment by barancev** [comment] 2016-02-16 11:24
240ms vs 190ms is far from 3x degradation :)

**Comment by godlark** [comment] 2016-02-16 11:53
Yes, but is about 10s difference in the whole proccess.
