### ISSUE TITLE
Unable to open browser in selenium, throws a “null” message

### ISSUE THREAD

**Issue by mohand1714** [SeleniumHQ/selenium#5963] opened 2018-05-30 10:37 UTC
I have a framework that uses POM model and I have used a Utils folder structure which has DriverFactory,Constant and ReadConfigFile java files that configures and opens the browser. (code below)

Now before I did this (introducing the Utils package) the code was running fine and after introducing the Utils package i am getting "Unable to load browsernull" exception.

Not sure what is causing the problem. I am using a Mac machine.

Constant.java file:

   ```
 package Utils;

    public class Constant {

    public final static String CONFIG_PROPERTIES_DIRECTORY = "properties/config.properties";

    public final static String GECKO_DRIVER_DIRECTORY = System.getProperty("user.dir")+"CucumberFramework/src/test/java/Resources/geckodriver";

    public final static String CHROME_DRIVER_DIRECTORY = System.getProperty("user.dir")+"CucumberFramework/src/test/java/Resources/chromedriver";


    }

```
DriverFactory.java file:

   ```
 package Utils;

    //import com.sun.java.util.jar.pack.Instruction;
    import com.sun.tools.javac.code.Attribute;
    import org.openqa.selenium.WebDriver;
    import org.openqa.selenium.chrome.ChromeDriver;
    import org.openqa.selenium.firefox.FirefoxDriver;
    import org.openqa.selenium.remote.DesiredCapabilities;
    import org.openqa.selenium.support.PageFactory;
    import pageObjects.AddIssuePage;
    import pageObjects.Login_Page;

    import java.util.concurrent.TimeUnit;

    public class DriverFactory {

        public static WebDriver driver;
        public static Login_Page login_page;
        public static AddIssuePage addIssuePage;


        public WebDriver getDriver() {        

            try        
            {        
                ReadConfigFile file = new ReadConfigFile();
                String browserName = file.getBrowser();
                switch (browserName) {

                    case "firefox":

                        if (null == driver) {
                            System.setProperty("webdriver.geckodriver", Constant.GECKO_DRIVER_DIRECTORY);
                            DesiredCapabilities capabilities = DesiredCapabilities.firefox();
                            capabilities.setCapability("marionette", true);
                            driver = new FirefoxDriver();

                        }
                        break;

                    case "chrome":

                        if (null == driver) {

                            System.setProperty("webdriver.chromedriver", Constant.CHROME_DRIVER_DIRECTORY);
                            driver = new ChromeDriver();

                        }
                        break;

                }
            } catch (Exception e)

            {
                System.out.println("Unable to load browser" + e.getMessage());

            } finally        
            {
                driver.manage().timeouts().pageLoadTimeout(60, TimeUnit.SECONDS);
                login_page = PageFactory.initElements(driver, Login_Page.class);
            }

            return driver;
        }
    }
```

ReadConfigFile.java file:

```
package Utils;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

public class ReadConfigFile {

    protected InputStream input = null;
    protected Properties prop = null;

    public ReadConfigFile () {

        try {
            ReadConfigFile.class.getClassLoader ().getResourceAsStream (Constant.CONFIG_PROPERTIES_DIRECTORY);
            prop = new Properties();
            prop.load(input);

        } catch (IOException e) {
            e.printStackTrace(); 
        }
    }

    public String getBrowser(){

        if (prop.getProperty("browser") == null)    
            return " ";

        return prop.getProperty("browser");

    }

}
```
Stacktrace:

```
java.lang.NullPointerException
    at Utils.DriverFactory.getDriver(DriverFactory.java:63)
    at Steps.MasterHooks.setup(MasterHooks.java:11)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at cucumber.runtime.Utils$1.call(Utils.java:40)
    at cucumber.runtime.Timeout.timeout(Timeout.java:16)
    at cucumber.runtime.Utils.invoke(Utils.java:34)
    at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
    at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
    at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
    at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
    at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
    at cucumber.runtime.model.CucumberScenarioOutline.run(CucumberScenarioOutline.java:46)
    at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
    at cucumber.runtime.Runtime.run(Runtime.java:122)
    at cucumber.api.cli.Main.run(Main.java:36)
    at cucumber.api.cli.Main.main(Main.java:18)

java.lang.NullPointerException
    at Utils.DriverFactory.getDriver(DriverFactory.java:63)
    at Steps.MasterHooks.setup(MasterHooks.java:11)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at cucumber.runtime.Utils$1.call(Utils.java:40)
    at cucumber.runtime.Timeout.timeout(Timeout.java:16)
    at cucumber.runtime.Utils.invoke(Utils.java:34)
    at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
    at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
    at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
    at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
    at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
    at cucumber.runtime.model.CucumberScenarioOutline.run(CucumberScenarioOutline.java:46)
    at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
    at cucumber.runtime.Runtime.run(Runtime.java:122)
    at cucumber.api.cli.Main.run(Main.java:36)
    at cucumber.api.cli.Main.main(Main.java:18)


Process finished with exit code 1

```
MasterHooks

```
package Steps;

import Utils.DriverFactory;
import cucumber.api.java.After;
import cucumber.api.java.Before;

public class MasterHooks extends DriverFactory {

    @Before
    public void setup() {
        driver = getDriver();

    }

    @After
    public void tearDown() {

        if (driver != null) {
            driver.quit();
        }
    }
}

```

**Comment by mohand1714** [comment] 2018-05-31 03:16
This is the message

`objc[6780]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java (0x1058604c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1058ec4e0). One of the two will be used. Which one is undefined.
java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at Utils.ReadConfigFile.<init>(ReadConfigFile.java:19)
	at Utils.DriverFactory.getDriver(DriverFactory.java:29)
	at Steps.MasterHooks.setup(MasterHooks.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
Unable to load browsernull	at cucumber.runtime.Timeout.timeout(Timeout.java:16)

	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
	at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
	at cucumber.runtime.model.CucumberScenarioOutline.run(CucumberScenarioOutline.java:46)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.runtime.Runtime.run(Runtime.java:122)
	at cucumber.api.cli.Main.run(Main.java:36)
	at cucumber.api.cli.Main.main(Main.java:18)`

**Comment by joerg1985** [comment] 2018-05-31 05:34
Okay, looks like the problem ist inside the ReadConfigFile constructor. 

The variable input is not set and defaults to null. But it is used inside the constructor "prop.load(input);". Just set the value of input and the NPE should bei gone.

This is not a Selenium issue from my Point of view, someone should close this issue.

**Closed** 2018-05-31 14:37 UTC
Labels: C-java
