### ISSUE TITLE
UnknownCommandError on mouse right click perform action

### ISSUE THREAD

**Issue by boolemb** [SeleniumHQ/selenium#2822] opened 2016-09-23 11:35 UTC
Mac OS X, firefox 49, selenium webdriver 3.0.0-beta3 for JAVASCRIPT

Hi, i cannot use selenium webdriver 2.53.3 with firefox 49 (it does not work anymore firefox driver) so i've installed webdriver 3.0.0-beta3 BUT i cannot use it again

i receive an error using right click action:
`UnknownCommandError: POST /session/164f3140-902e-1f4d-8036-bb09daf60982/moveto did not match a known command
    at WebDriverError (/projects/BBWebapp/node_modules/selenium-webdriver/lib/error.js:27:10)
    at UnknownCommandError (/projects/BBWebapp/node_modules/selenium-webdriver/lib/error.js:296:10)
    at Object.throwDecodedError (/projects/BBWebapp/node_modules/selenium-webdriver/lib/error.js:477:11)
    at parseHttpResponse (/projects/BBWebapp/node_modules/selenium-webdriver/lib/http.js:388:15)
    at /projects/BBWebapp/node_modules/selenium-webdriver/lib/http.js:330:11
    at process._tickCallback (node.js:366:9)
From: Task: mouseMove
    at Driver.schedule (/projects/BBWebapp/node_modules/selenium-webdriver/lib/webdriver.js:414:17)
    at /projects/BBWebapp/node_modules/selenium-webdriver/lib/actions.js:121:16
    at Array.forEach (native)
    at /projects/BBWebapp/node_modules/selenium-webdriver/lib/actions.js:120:15
    at TaskQueue.execute_ (/projects/BBWebapp/node_modules/selenium-webdriver/lib/promise.js:2731:14)
    at TaskQueue.executeNext_ (/projects/BBWebapp/node_modules/selenium-webdriver/lib/promise.js:2714:21)
    at /projects/BBWebapp/node_modules/selenium-webdriver/lib/promise.js:2584:27
    at /projects/BBWebapp/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (node.js:366:9)
From: Task: ActionSequence.perform
    at ActionSequence.perform (/projects/BBWebapp/node_modules/selenium-webdriver/lib/actions.js:119:33)
    at getAction (/projects/BBWebapp/specs/page.js:109:22)
    at getMenuAction (/projects/BBWebapp/specs/page.js:114:8)
    at /projects/BBWebapp/specs/fm/fm1_createitems.js:57:14
    at ManagedPromise.invokeCallback_ (/projects/BBWebapp/node_modules/selenium-webdriver/lib/promise.js:1303:14)
    at TaskQueue.execute_ (/projects/BBWebapp/node_modules/selenium-webdriver/lib/promise.js:2731:14)
    at TaskQueue.executeNext_ (/projects/BBWebapp/node_modules/selenium-webdriver/lib/promise.js:2714:21)
    at /projects/BBWebapp/node_modules/selenium-webdriver/lib/promise.js:2584:27
    at /projects/BBWebapp/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (node.js:366:9)`

this is my code (that was working with 2.5 versions)
`        theAction = driver.getAction().click(driver.getDriver().findElement(driver.getWd().By.css(search)), driver.getWd().Button.RIGHT);
    return theAction.perform();
`

and this is the driver build code:
`var Capabilities = require('selenium-webdriver/lib/capabilities').Capabilities;
var capabilities = Capabilities.firefox();
capabilities.set('marionette', true);
var driver = new wd.Builder().withCapabilities(capabilities).build();`

tried also:
`var driver = new wd.Builder().forBrowser('firefox').build();`

but nothing changes....

how can i canghe my code to make it work? Nowadays i'm foced to downgrade to FF 46 and WD 2.53 to use our test environment!
Please help me.
thanks a lot

**Comment by lukeis** [comment] 2016-09-23 15:19
duplicate of #2285

**Closed by lukeis** 2016-09-23 15:19 UTC
