### ISSUE TITLE
WebDriverError: invalid argument: can't kill an exited process

### ISSUE THREAD

**Issue by isakemal** [SeleniumHQ/selenium#7742] opened 2019-11-05 01:37 UTC
We are getting intermittent test failures (<1 out of 50) for Firefox + selenium/webdriver + protractor nodejs on Ubuntu 14.04.   I searched a lot mostly people say incompatible versions between geckodriver and the firefox but that is not the case here. 

> [0] E/launcher - WebDriverError: invalid argument: can't kill an exited process
    at WebDriverError (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.throwDecodedError (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/firefox/index.js:521:41)
    at Direct.getNewDriver (/usr/lib/node_modules/protractor/built/driverProviders/direct.js:105:33)
    at Runner.createBrowser (/usr/lib/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/usr/lib/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/usr/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/lib/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/usr/lib/node_modules/protractor/node_modules/q/q.js:137:13)

Here are the versions  which looks compatible with each other according to https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html
## Environment

[console]# webdriver-manager status
[1:00:11] status selenium standalone version available: 3.141.59 [last]
[1:00:11] I/status  chromedriver version available: 78.0.3904.70 [last]
[1:00:11] I/status geckodriver version available: v0.26.0 [last]
[1:00:11] I/status android-sdk is not present
[1:00:11] I/status  appium is not present
[console]:~# firefox --version
Mozilla Firefox 66.0

## Environment

OS:   Ubuntu 14.04
Browser:   Firefox 
Browser version: 66.0.3
Browser Driver version:   GeckoDriver 0.26.0
Language Bindings version: Javascript selenium standalone version: 3.141.59 [last]

**Comment by ChamRoshi** [comment] 2019-11-06 11:30
I'm having this issue too. I've updated everything to the most up-to-date versions and it's still happening. 

# Environment
OS: Ubuntu 16.04.4 LTS
Browser: Firefox 70.0.1
Browser Driver Version: GeckoDriver 0.26.0
Selenium: Python Selenium 3.141.0, Splinter 0.11.0

**Comment by carmon** [comment] 2020-02-19 17:05
I'm having the same issue executing it from `selenium-webdriver`, here is the stack trace that return when `node example/google_search` is run:

> root@55c8ceb28719:/vrt/node_modules/selenium-webdriver# PATH=$PATH:../../deps node example/google_search
(node:770) UnhandledPromiseRejectionWarning: WebDriverError: invalid argument: can't kill an exited process
    at Object.throwDecodedError (/vrt/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/vrt/node_modules/selenium-webdriver/lib/http.js:563:13)
    at Executor.execute (/vrt/node_modules/selenium-webdriver/lib/http.js:489:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:770) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:770) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:770) UnhandledPromiseRejectionWarning: WebDriverError: invalid argument: can't kill an exited process
    at Object.throwDecodedError (/vrt/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/vrt/node_modules/selenium-webdriver/lib/http.js:563:13)
    at Executor.execute (/vrt/node_modules/selenium-webdriver/lib/http.js:489:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:770) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by nfk** [comment] 2020-04-18 14:21
I can see the same random issue ~2 fails on 30 jobs. This one occurs between 2 tests suite, when the test suite init a new instance of the webdriver. Do you know if this a bug or if I can prevent this issue ?

python bactktrace:
```
driver_class = <class 'selenium.webdriver.remote.webdriver.WebDriver'>
driver_kwargs = {'browser_profile': None, 'command_executor': 'http://172.20.0.31:4444/wd/hub', 'desired_capabilities': {'browserName': 'firefox', 'moz:firefoxOptions': {'args': ['-headless'], 'prefs': {'intl.accept_languages': 'en'}}}}

    @pytest.fixture
    def driver(request, driver_class, driver_kwargs):
        """Returns a WebDriver instance based on options and capabilities"""
>       driver = driver_class(**driver_kwargs)

/usr/local/lib/python3.8/site-packages/pytest_selenium/pytest_selenium.py:189: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py:157: in __init__
    self.start_session(capabilities, browser_profile)
/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py:252: in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py:321: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f3c4af3c430>
response = {'status': 500, 'value': '{\n  "value": {\n    "stacktrace": "org.openqa.selenium.WebDriverException: invalid argument...\nDriver info: driver.version: unknown\\nremote stacktrace: ",\n    "error": "unknown error"\n  },\n  "status": 13\n}'}
```

webdriver backtrace: 
```
E       selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
E       Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
E       System info: host: '9e85f3272827', ip: '172.17.0.5', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-957.5.1.el7.x86_64', java.version: '1.8.0_242'
E       Driver info: driver.version: unknown
E       remote stacktrace: 
E       Stacktrace:
E           at sun.reflect.NativeConstructorAccessorImpl.newInstance0 (NativeConstructorAccessorImpl.java:-2)
E           at sun.reflect.NativeConstructorAccessorImpl.newInstance (NativeConstructorAccessorImpl.java:62)
E           at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
E           at java.lang.reflect.Constructor.newInstance (Constructor.java:423)
E           at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0 (W3CHandshakeResponse.java:62)
E           at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0 (HandshakeResponse.java:30)
E           at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0 (ProtocolHandshake.java:126)
E           at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
E           at java.util.Spliterators$ArraySpliterator.tryAdvance (Spliterators.java:958)
E           at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:126)
E           at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:499)
E           at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:486)
E           at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:472)
E           at java.util.stream.FindOps$FindOp.evaluateSequential (FindOps.java:152)
E           at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
E           at java.util.stream.ReferencePipeline.findFirst (ReferencePipeline.java:531)
E           at org.openqa.selenium.remote.ProtocolHandshake.createSession (ProtocolHandshake.java:128)
E           at org.openqa.selenium.remote.ProtocolHandshake.createSession (ProtocolHandshake.java:74)
E           at org.openqa.selenium.grid.session.remote.RemoteSession$Factory.performHandshake (RemoteSession.java:147)
E           at org.openqa.selenium.grid.session.remote.ServicedSession$Factory.apply (ServicedSession.java:161)
E           at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$12 (ActiveSessionFactory.java:180)
E           at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
E           at java.util.stream.ReferencePipeline$11$1.accept (ReferencePipeline.java:440)
E           at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:175)
E           at java.util.Spliterators$ArraySpliterator.tryAdvance (Spliterators.java:958)
E           at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:126)
E           at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:499)
E           at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:486)
E           at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:472)
E           at java.util.stream.FindOps$FindOp.evaluateSequential (FindOps.java:152)
E           at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
E           at java.util.stream.ReferencePipeline.findFirst (ReferencePipeline.java:531)
E           at org.openqa.selenium.remote.server.ActiveSessionFactory.apply (ActiveSessionFactory.java:183)
E           at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$2 (NewSessionPipeline.java:66)
E           at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
E           at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:175)
E           at java.util.Collections$2.tryAdvance (Collections.java:4719)
E           at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:126)
E           at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:499)
E           at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:486)
E           at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:472)
E           at java.util.stream.FindOps$FindOp.evaluateSequential (FindOps.java:152)
E           at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
E           at java.util.stream.ReferencePipeline.findFirst (ReferencePipeline.java:531)
E           at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$3 (NewSessionPipeline.java:69)
E           at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
E           at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
E           at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
E           at java.util.stream.DistinctOps$1$2.accept (DistinctOps.java:175)
E           at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:175)
E           at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
E           at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:175)
E           at java.util.stream.Streams$StreamBuilderImpl.tryAdvance (Streams.java:405)
E           at java.util.stream.Streams$ConcatSpliterator.tryAdvance (Streams.java:728)
E           at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:126)
E           at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:499)
E           at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:486)
E           at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:472)
E           at java.util.stream.FindOps$FindOp.evaluateSequential (FindOps.java:152)
E           at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
E           at java.util.stream.ReferencePipeline.findFirst (ReferencePipeline.java:531)
E           at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession (NewSessionPipeline.java:72)
E           at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute (BeginSession.java:65)
E           at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0 (WebDriverServlet.java:235)
E           at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
E           at java.util.concurrent.FutureTask.run (FutureTask.java:266)
E           at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
E           at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
E           at java.lang.Thread.run (Thread.java:748)

/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py:242: WebDriverException
```

# Environment

[docker-selenium](https://github.com/SeleniumHQ/docker-selenium/)

* Selenium: 3.141.59
* Mozilla Firefox: 75.0
* GeckoDriver: 0.26.0

**Comment by diemol** [comment] 2020-04-20 20:39
@isakemal how can we reproduce the issue? Is it happening with the latest NodeJS alpha bindings?
@nfk the original issue seems to be happening in JavaScript, is it really the same you are having but now in Python?

**Comment by nfk** [comment] 2020-04-21 10:51
@diemol I had tried a lot of thing trying to reproduce on my local machine but I was not able to find the way to reach this bug easily. On my side, it occurs on gitlab runner where I allow to run 2 concurrents jobs where each job has their own selenium standalone node, maybe it can happen with onlt one job too. Each node uses the same `/dev/shm` partition I don't know if that can affect the Firefox webdriver startup sometime....

The python and js backtrace seems to fail at the same point during the Firefox session creation from the webdriver. Then the issue is random either python or js binding.  @ChamRoshi looks to have the same issue with a python binding.

__python__
```
/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py:252: in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
```
__js__
```
at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
```

**Comment by diemol** [comment] 2020-04-22 13:19
I am still not clear how both issues are related. The one above is using Protractor and plain Ubuntu, and the other one mentions GitLab. 

Regarding GitLab, seems like an environment issue? If it works locally but not on GitLab there is not much we could do, but we would advise to double-check the environment with the GitLab admins.

If there is a way to reproduce this and providing a self-contained automation script, we would be happy to have a look and help to fix it. For now, I will close the issue, but both feel free to open a new one with the complete template filled out.

**Closed by diemol** 2020-04-22 13:19 UTC
Labels: C-nodejs, R-awaiting answer
