### ISSUE TITLE
Firefox find_element_by_xpath(<xpath>).click()  misses selections on borders

### ISSUE THREAD

**Issue by JimHofman** [SeleniumHQ/selenium#1916] opened 2016-04-04 18:14 UTC
## Meta -
OS: 
Selenium Version: 
Browser: 
Browser Version: 

## Expected Behavior -
 find_element_by_xpath(<xpath>).click()  takes me to the new url
## Actual Behavior -
The screen jumps, but there is no action taken.  This only happens when the element I am trying to select is partially visible (an image) or it is very close to a border.  find_element_by_xpath(<xpath>).is_displayed() works fine.

**Comment by lukeis** [comment] 2016-04-04 20:07
please provide a reproducible test script... also this is expected behavior (the scroll that is, but you have some options to change the behavior by setting the 'elementScrollBehavior' capability to 1 or 0).

Closing since there's nothing actionable for us to do without a reproducible test case.

**Closed by lukeis** 2016-04-04 20:07 UTC

**Comment by JimHofman** [comment] 2016-04-12 06:31
Thanks Luke,

I'm not sure how the elementScrollBehavior works but I'll look for it in
the docs.

Jim

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2200-b>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2200-b>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Mon, Apr 4, 2016 at 1:07 PM, Luke Inman-Semerau <notifications@github.com
