### ISSUE TITLE
StackOverflowException : Redirect loop

### ISSUE THREAD

**Issue by VincentCharpentier** [SeleniumHQ/selenium#997] opened 2015-09-02 13:28 UTC
In .NET, with firefox webdriver, if your url cause a rediection loop, you will have a StackOverflowException. (The url I provided as an example may be fixed anytime because I don't own this website)

    var targetUrl = "http://liveskateboardmedia.com/fr/article/a-croquer";
    Navigate().GoToUrl(targetUrl); // StackOverflowException

**Comment by ddavison** [comment] 2015-09-09 15:24
this appears to be just .NET.. can't reproduce in Java using Chrome, Safari, or Firefox.

**Comment by VincentCharpentier** [comment] 2015-09-09 16:00
Sorry, it was the fiddler proxy...

**Comment by jimevans** [comment] 2015-09-09 17:11
Closing, due to new informative

**Closed by jimevans** 2015-09-09 17:11 UTC
Labels: C-dotnet, D-firefox
