### ISSUE TITLE
Driver closing issue with oauth authorization window 

### ISSUE THREAD

**Issue by vladimirWXW** [SeleniumHQ/selenium#9360] opened 2021-04-06 13:00 UTC
## 🐛 Bug Report

Hi!

Our application is using oauth authorization with partners f.e. vk.com
User presses authentication via vk, new window with login and password is opened.
After filling the fields user presses login button and window closing automatically with sending authentication request.

So the issue is that after closing oauth window driveris closing too on any actions with webdriver, and creates new instance of webdriver

The code of the method:

public void switchToNextWindow() {
        for (String winHandle : driver.getWindowHandles()) {
            driver.switchTo().window(winHandle); // switch focus of WebDriver to the next found window handle
        }
    }

public static void withVkontakte(UserData user) {
            kraken.perform().switchToNextWindow();
            kraken.perform().fillField(Elements.Social.Vkontakte.loginField(),user.getLogin());
            kraken.perform().fillField(Elements.Social.Vkontakte.passwordField(),user.getPassword());
            kraken.perform().click(Elements.Social.Vkontakte.submitButton());
        }

Detailed steps to reproduce the behavior:

## Expected behavior
After closing oauth window user focus should be switched to the old window automaticaly, or if a user has old window id he should has possibility to switch back by using code
driver.switchTo().window("windowId");

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS:MacOS 11.2
Browser: Chrome 89
Java: 11.0.8
Selenium: 3.8.1
seleniumChromeDriver: '3.14.0'

I tried in FireFox the same behavior

**Comment by diemol** [comment] 2021-04-07 08:51
How can we reproduce the issue? Could you please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by vladimirWXW** [comment] 2021-04-07 11:51
Yes sure
Manual test case
1) Open https://sbermarket.ru/
2) Press "Войти" button
3) Press Facebook authentication button
New window will be opened
4) Input correct credentials to email and password fields
5) Press "Вход" button
ouatth window will be closed
Automated test case

1) driver.get("sbermarket.ru")
2) driver.click(By.xpath("//header//button[text()='Войти']"));
3) driver.click(By.xpath("//button[@data-qa='facebook']"));
4) switchToNextWindow();
5) fillField(By.xpath("//input[@id='email']"),"some_login");
6) fillField(By.xpath("//input[@id='pass']"),"some_password");
7) driver.click(By.xpath("//input[@type='submit']"))
8) driver.getWindowHandles();

After 8th step Web Driver will be closed and re opened again


public void switchToNextWindow() {
for (String winHandle : driver.getWindowHandles()) {
driver.switchTo().window(winHandle); // switch focus of WebDriver to the next found window handle
}
}

public void fillField(final ElementData element, final String text) {
        log.info("fill field: {}", element.getDescription());
        if (text == null) {
            log.error("> empty value: {}", element);
            Assert.assertNotNull("empty value", text);
        }
        webElement.click();
        webElement.clear();
        webElement.sendKeys(Keys.BACK_SPACE);
//workaround because of bug in sendKeys()
        if(!text.equals("")){
            for (int i = 0; i < text.length(); i++) {
                webElement.sendKeys(text.charAt(i) + "");
            }
        }else webElement.sendKeys(text);
    }

**Comment by diemol** [comment] 2021-04-07 12:07
Apologies if I was not clear. We need a code snippet that reproduces the issue, narrative descriptions leave room for assumptions. Thank you! 🙇

**Comment by vladimirWXW** [comment] 2021-04-07 14:18
Do you need something else for bug reproducing?

**Comment by diemol** [comment] 2021-04-07 14:32
Yes, we need a complete reproduction test case, it could be a GItHub repository or you could paste the complete code we can use to reproduce it. Basically, the Java code that represents the steps you mentioned [here](https://github.com/SeleniumHQ/selenium/issues/9360#issuecomment-814851023).

**Comment by vladimirWXW** [comment] 2021-04-07 15:20
But it's private repository with some sensitive data inside I cannot share it because of security =(

**Comment by vladimirWXW** [comment] 2021-04-07 15:31
Did you try the provided code, if yes did it work for you?

**Comment by diemol** [comment] 2021-04-07 15:50
You do not need to share the exact same code, we need any code snippet that we can use to reproduce the issue, it could be using any given public website or with an attached HTML page. 

I also notice you are using outdated versions of Selenium, perhaps you can update those and if the issue is still there, please provide a code snippet we can use to reproduce the issue.

**Comment by vladimirWXW** [comment] 2021-04-07 15:59
Thanks now I know what to do

**Comment by diemol** [comment] 2021-05-07 20:54
I will close this as we did not get a script to reproduce the issue. However, if this information is provided, we'd be happy to reopen this.

**Closed as completed by diemol** 2021-05-07 20:54 UTC
Labels: J-awaiting answer
