### ISSUE TITLE
timeout when geting url in headless chrome

### ISSUE THREAD

**Issue by fgisslen** [SeleniumHQ/selenium#6288] opened 2018-08-15 20:23 UTC
Anyone knows how to fix this? 

File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 332, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-32-generic x86_64)

**Comment by lmtierney** [comment] 2018-08-15 21:02
Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment] 2018-09-23 10:51
CLosing the issue as there is no reproduction scenario provided.

**Closed by barancev** 2018-09-23 10:51 UTC
Labels: R-awaiting answer

**Comment by LRAbbade** [comment] 2018-10-16 13:11
> Anyone knows how to fix this?
> 
> File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 332, in get
> self.execute(Command.GET, {'url': url})
> File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
> self.error_handler.check_response(response)
> File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.TimeoutException: Message: timeout
> (Session info: headless chrome=68.0.3440.106)
> (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-32-generic x86_64)

I was having a similar problem. Managed to solve it by adding the window size to the driver:

```py
driver.set_window_size(1200, 600)
```
Turns out responsive sites require this line, even if its executing headless.
