### ISSUE TITLE
Selenium Safari click() does not match real Safari behavior

### ISSUE THREAD

**Issue by vr2262** [SeleniumHQ/selenium#385] opened 2015-03-27 19:48 UTC
See this test on Sauce Labs:
https://saucelabs.com/tests/c1d1d933b9b64132b25a2663fe71e52b

On a real Mac, entering a number, clicking next, and clicking submit work fine. In Selenium, it seems like a change event does not fire on the `input` element.

Here is the relevant test code:
https://github.com/SEL-Columbia/dokomoforms/blob/b1204676d74caf1ae52aa7f368c3c92fd8cb0fa0/tests/selenium_test.py#L283-L311

**Comment by lukeis** [comment] 2015-03-27 19:58
can you please provide a [reproducible test case](http://sscce.org/). As nice as it is to have a saucelabs recording of the run, this does not provide us with the html needed to reproduce the issue ourselves. Also please provide a reduced test case, it is not a reasonable request for us to look through your repo to figure out where the issue in selenium is.

closing the issue until that can be provided (and we'll re-open it).

**Comment by jleyba** [comment] 2015-03-27 20:02
Known issue still open on GC: https://code.google.com/p/selenium/issues/detail?id=4061

**Comment by lukeis** [comment] 2015-03-27 20:14
related selenium test:

JavascriptEnabledDriverTest#testChangeEventIsFiredAppropriatelyWhenFocusIsLost

**Comment by lukeis** [comment] 2016-09-23 20:17
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.

**Closed by lukeis** 2016-09-23 20:17 UTC
Labels: A-needs new owner, D-safari
