### ISSUE TITLE
Wrong version on GRID Console

### ISSUE THREAD

**Issue by borbamartin** [SeleniumHQ/selenium#1236] opened 2015-11-10 23:21 UTC
After starting the hub using the selenium-server-standalone-2.48.2.jar, "GRID Console 2.48.0" is displayed. The nodes however, show up as 2.48.2.

**Comment by davehunt** [comment] 2015-11-11 10:01
Duplicate of #1140

**Closed by davehunt** 2015-11-11 10:01 UTC
