### ISSUE TITLE
[🐛 Bug]: Missinng method org.openqa.selenium.remote.http.HttpRequest.forEachHeader in 4.13

### ISSUE THREAD

**Issue by Markedo** [SeleniumHQ/selenium#12865] opened 2023-10-04 14:45 UTC
### What happened?

Selenium is not working because of the missing method HttpRequest.forEachHeader (pls refer to log).
The problem occurs only in Selenium 4.13, **while 4.12 works fine**.

### How can we reproduce the issue?

```shell
1. Software and dependencies used:
Java 19/21
springBootVersion = '3.0.1'
'io.github.bonigarcia:webdrivermanager:5.5.3 'org.apache.httpcomponents.client5:httpclient5:5.2.1'
'org.seleniumhq.selenium:selenium-java:4.13.0'

2. How to reproduce: install the software with provided dependencies and perform WebDriver.get method on any link.
```

### Relevant log output

```shell
INFO  2023-10-04T14:20:18.566Z trace_id: span_id: (ManualRabbitSendingProcessor.java:74)::onSubscribe subscribed on trans_info_service orders parser
INFO  2023-10-04T14:20:29.169Z trace_id: span_id: (WebDriverManager.java:1270)::exportDriver Exporting webdriver.chrome.driver as /home/markedo/.cache/selenium/chromedriver/linux64/117.0.5938.92/chromedriver
Starting ChromeDriver 117.0.5938.92 (67649b10b92bb182fba357831ef7dd6a1baa5648-refs/branch-heads/5938_62@{#14}) on port 16356
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
INFO  2023-10-04T14:20:29.703Z trace_id: span_id: (SeleniumInvoker.java:76)::parse requesting orders with selenium driver ChromeDriver: chrome on LINUX (cf0ca0cb1d4d7284c5467c3dc8bd65bc)
WARN  2023-10-04T14:20:29.717Z trace_id: span_id: (Connection.java:201)::lambda$onText$0 Unable to process: {"method":"Fetch.requestPaused","params":{"requestId":"interception-job-1.0","request":{"url":"sitename.redacted","method":"GET","headers":{"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/117.0.5938.132 Safari/537.36","sec-ch-ua":"\"HeadlessChrome\";v=\"117\", \"Not;A=Brand\";v=\"8\", \"Chromium\";v=\"117\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Linux\""},"initialPriority":"VeryHigh","referrerPolicy":"strict-origin-when-cross-origin"},"frameId":"519915F1BA494CDF63C1D09B4A6CAFE2","resourceType":"Document"},"sessionId":"986FE4A7981278017E930B93EA254F18"}
java.lang.NoSuchMethodError: 'void org.openqa.selenium.remote.http.HttpRequest.forEachHeader(java.util.function.BiConsumer)'
	at org.openqa.selenium.devtools.v117.v117Network.continueRequest(v117Network.java:192) ~[selenium-devtools-v117-4.13.0.jar:na]
	at org.openqa.selenium.devtools.v117.v117Network.continueRequest(v117Network.java:42) ~[selenium-devtools-v117-4.13.0.jar:na]
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$3(Network.java:206) ~[selenium-remote-driver-4.5.3.jar:na]
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56) ~[selenium-http-4.5.3.jar:na]
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$4(Network.java:220) ~[selenium-remote-driver-4.5.3.jar:na]
	at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:288) ~[selenium-remote-driver-4.5.3.jar:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541) ~[na:na]
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:257) ~[selenium-remote-driver-4.5.3.jar:na]
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:58) ~[selenium-remote-driver-4.5.3.jar:na]
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:199) ~[selenium-remote-driver-4.5.3.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1589) ~[na:na]
Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: 'void org.openqa.selenium.remote.http.HttpRequest.forEachHeader(java.util.function.BiConsumer)'
Build info: version: '4.5.3', revision: '4b786a1e430'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.5-zen1-1-zen', java.version: '19.0.2'
Driver info: DevTools Connection
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:202)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.NoSuchMethodError: 'void org.openqa.selenium.remote.http.HttpRequest.forEachHeader(java.util.function.BiConsumer)'
	at org.openqa.selenium.devtools.v117.v117Network.continueRequest(v117Network.java:192)
	at org.openqa.selenium.devtools.v117.v117Network.continueRequest(v117Network.java:42)
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$3(Network.java:206)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$4(Network.java:220)
Caused by: java.lang.NoSuchMethodError: 'void org.openqa.selenium.remote.http.HttpRequest.forEachHeader(java.util.function.BiConsumer)'

	at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:288)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:257)
	at org.openqa.selenium.devtools.Connection.access$200(Connection.java:58)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:199)
	... 3 more
```

### Operating System

Linux Arch

### Selenium version

Java 4.13.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 117

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 117.0.5938.92

**Comment by diemol** [comment] 2023-10-04 15:32
@joerg1985 , do you know? This seems related to https://github.com/SeleniumHQ/selenium/commit/05c148f052e547f06dd6569c21450d2c0f320b1a, but in theory it should work if they only use 4.13.0.

**Comment by joerg1985** [comment] 2023-10-04 21:32
It looks like there are different selenium versions mixed, `selenium-remote-driver-4.5.3.jar` with `selenium-devtools-v117-4.13.0.jar`. I think this is the cause for the issue and using different jar versions is a bad idea.

**Comment by diemol** [comment] 2023-10-04 21:37
You are right, I missed this:
>Build info: version: '4.5.3', revision: '4b786a1e430'

@Markedo please move all your dependencies to `4.13.0`

**Comment by Markedo** [comment] 2023-10-06 05:49
> @Markedo please move all your dependencies to `4.13.0`

Thank you for the answer! I really appreciate this. I'm sorry if this looks little dumb, I just want to help to improve this nice project by providing bug report.

I've tried to update all dependencies and made a "radle --refresh-dependencies". Now I'm receiving another kind of error.
```
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
ERROR 2023-10-06T05:36:20.207Z trace_id: span_id: (SpringApplication.java:820)::reportFailure Application run failed
java.lang.NoSuchMethodError: org.openqa.selenium.chromium.ChromiumDriverCommandExecutor: method 'void <init>(org.openqa.selenium.remote.service.DriverService, java.util.Map, org.openqa.selenium.remote.http.ClientConfig)' not found
	at org.openqa.selenium.chrome.ChromeDriver$ChromeDriverCommandExecutor.<init>(ChromeDriver.java:115) ~[selenium-chrome-driver-4.13.0.jar:na]
	at org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:105) ~[selenium-chrome-driver-4.13.0.jar:na]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88) ~[selenium-chrome-driver-4.13.0.jar:na]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83) ~[selenium-chrome-driver-4.13.0.jar:na]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72) ~[selenium-chrome-driver-4.13.0.jar:na]
	at parser.importers.selenium.SeleniumInvoker.initChromeDriver(SeleniumInvoker.java:52) ~[main/:na]
	at parser.importers.selenium.SeleniumInvoker.parse(SeleniumInvoker.java:71) ~[main/:na]
	at parser.importers.provider.ImportingProcessor.parseOrders(ImportingProcessor.java:30) ~[main/:na]
	at parser.importers.processor.ManualRabbitSendingProcessor.processAvailableOrders(ManualRabbitSendingProcessor.java:34) ~[main/:na]
	at parser.importers.ParsersRunner.run(ParsersRunner.java:54) ~[main/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:758) ~[spring-boot-3.0.1.jar:3.0.1]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:748) ~[spring-boot-3.0.1.jar:3.0.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-3.0.1.jar:3.0.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-3.0.1.jar:3.0.1]
	at parser.importers.ImporterApplication.main(ImporterApplication.java:11) ~[main/:na]
INFO  2023-10-06T05:36:20.217Z trace_id: span_id: (HikariDataSource.java:350)::close some - Shutdown initiated...
INFO  2023-10-06T05:36:20.221Z trace_id: span_id: (HikariDataSource.java:352)::close some - Shutdown completed.
```

The init section looks like this:

```
    private ChromeDriver initChromeDriver() {
        final WebDriverManager driverManager = WebDriverManager.chromedriver().avoidResolutionCache();
        driverManager.setup();
        ChromeOptions options = new ChromeOptions();
        *some options added here, but the problem occurs even if no option provided*
        return new ChromeDriver(options);
    }
```

**Comment by titusfortner** [comment] 2023-10-06 12:09
`WebDriverManager` is not a solution provided by this project. Selenium has its own built in driver manager, and it should work without you doing anything else in your code. Try removing the external dependency.

**Comment by diemol** [comment] 2023-10-17 14:16
@Markedo were you able to solve it? Can we close this issue?

**Comment by diemol** [comment] 2023-11-24 15:36
I will close this as we did not get more information from the OP.

**Closed as not planned by diemol** 2023-11-24 15:36 UTC
Labels: J-awaiting answer, C-java, I-defect
