### ISSUE TITLE
Aliases in /etc/hosts for 127.0.0.1 causes a "Bad request" error

### ISSUE THREAD

**Issue by EmlynK** [SeleniumHQ/selenium#2074] opened 2016-05-10 13:42 UTC
## Meta -

OS:  Debian 7.10

Selenium Version:  2.53.0

Browser:  Firefox

Browser Version:  45 (package is 45.1.0esr-1~bpo70+1)

I've created a daemon which, when run, starts up Xvfb and Selenium 2.53.0 in the background. When I run my test, I get the following error:

```
When I visit "user"                                                                                                                    # Drupal\DrupalExtension\Context\MinkContext::assertAtPath()
      Could not open connection: Bad request
      Command duration or timeout: 11 milliseconds
      Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
      System info: host: 'server.example.net', ip: ‘172.xx.xx.xx', os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.0-4-amd64', java.version: '1.7.0_101'
      Driver info: org.openqa.selenium.firefox.FirefoxDriver (Behat\Mink\Exception\DriverException)
```

After discussing with a colleague, it was determined the error was occurring due to the order of the 127.0.0.1 entry in /etc/hosts, which directly relates to https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3280. I have this in /etc/hosts:

```
127.0.0.1       localhost.localdomain   localhost
```

When I reverse that to be:

```
127.0.0.1       localhost   localhost.localdomain
```

the test runs fine. 

The /etc/hosts file is Puppet managed across our infrastructure, but more importantly, it was correct in the first place: an FQDN should come first followed by the short name.

In the archived issue linked above, this issue seems to have been fixed since 2.43.0, so it looks like there has potentially been a regression of sorts?

Does anyone else still experience this issue using the latest standalone server, 2.53.0?
## Steps to reproduce

This would be to simply adjust your /etc/hosts file and put localhost in front of any other aliases, like so:

```
127.0.0.1       localhost   localhost.localdomain alias etc
```

Thanks,
Emlyn

**Comment by jatitoam** [comment] 2016-08-12 23:15
Confirmed error, tested in Ubuntu Precise (12.04) and Ubuntu Trusty (14.04) with Selenium 2.53.0 and 2.53.1

**Comment by fmrahman** [comment] 2016-11-24 13:54
Yes, We are experiencing the same issue in selenium-server-standalone-2.53.1.jar.
Tried below but it is not working.
FirefoxProfile profile = new FirefoxProfile();
profile.setPreference(FirefoxProfile.ALLOWED_HOSTS_PREFERENCE, "localhost.localdomain");
Ref: https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3280

Environment details:
Browser: Firefox.44.0.1
Jar: selenium-server-standalone-2.53.1.jar

It supposed to work in selenium-server-standalone-2.44.0.jar but now it is not working.

**Comment by Srinivasan69** [comment] 2016-12-08 06:45
I experienced the same issue.   Details are below

Environment details:
Browser: Firefox.44.0.1
Jar: selenium-server-standalone-2.53.1.jar

It will be great if the issue is fixed.

**Comment by bkelley13** [comment] 2017-05-31 20:24
I see same issue sin 2.53.1 as well.  The setPref doesn't fix it for me, only modifying the /etc/hosts, yet since it is puppet managed, that's ephemeral at best.

**Comment by p0deje** [comment] 2017-06-07 10:44
Can anybody provide a test script to reproduce the error? Should I just modify /etc/hosts, start server manually with `java -jar` and request for a remote driver?

**Comment by atul43** [comment] 2017-06-15 06:14
This problem is reproducible easily.  In /etc/hosts entries are like in the format of 
IP_ADDRESS CANONICAL_NAME [aliases...]
So, if the canonical_name against IP 127.0.0.1 doesn't match exactly with "localhost" then this bad request problem occurs. 

Now, in my case, I am using old selenium driver[2.28.0] with the compatible Firefox version. Due to some constraint I can't change driver and etc/hosts file. Is there a workaround to get rid off from this problem? I guess this problem is very much there in the latest selenium driver too. 

I would greatly appreciate any advise here.

**Comment by p0deje** [comment] 2017-06-15 08:32
Everybody keeps telling that it's easy to reproduce the issue, but nobody gives a test script :(

I'm not Java bindings maintainer and doesn't know Java, so can anybody please just provide a simple piece of code that I could run locally with modified /etc/hosts to reproduce and debug the problem?

**Comment by atul43** [comment] 2017-06-15 09:00
I can share very simple Java code that you can compile and run using selenium libraries. 

=================

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class OpenGoogle {
        public static void main(String args[]) {

                WebDriver driver = new FirefoxDriver();
                System.out.println("Hello Google...");
                driver.get("http://google.com");

        }
}
==========================

**Comment by p0deje** [comment] 2017-06-27 06:32
I can't reproduce this using the following environment:

* Selenium 3.4.0
* Firefox 54
* GeckoDriver 0.17

This is a piece of code I use to test:

```java
WebDriver driver = new FirefoxDriver();
driver.get("http://www.google.com");
driver.quit();
```

Here is what I have in /etc/hosts:

```
127.0.0.1       localhost.localdomain localhost
```

I've also tried reversing aliases, but the code never fails.

Can anybody provide more information or point me if I'm doing something wrong? 

There is also a chance this issue is fixed in 3.x when used with GeckoDriver, so I'm not sure that even if 
I can reproduce the bug, it will need a fix.

**Comment by pcooper19** [comment] 2018-09-19 22:19
This happened to me when installing Selenium using PyCharm.

Selenium: 3.14
Pip: 10.0.1
Python: 3.7
Chromium: 2.4.2

My Script:
from selenium import webdriver
BROWSER = webdriver.Chrome(executable_path='/path/to/newest/driver')
BROWSER.get('URL')

It was barfing:
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /path/to/chromedriver

My hosts file in /etc was empty and I copied
"127.0.0.1       localhost.localdomain localhost" into the first line and that fixed it. Removing caused the error again.

Not sure this is helpful at all...sorry if not.

**Comment by diemol** [comment] 2018-09-23 17:45
@pcooper19 the original issue was related to Firefox, if you are facing an problem with Chrome, please open a new issue with all the info required by the template.

Since no one has provided a way to reproduce the issue, and it is mostly related to Selenium versions < 3.0.0, I will close this issue. Feel free to reopen if a complete, step by step way to reproduce is provided.

**Closed by diemol** 2018-09-23 17:45 UTC
Labels: C-server
