### ISSUE TITLE
Cannot access any elements on second IE window

### ISSUE THREAD

**Issue by kphilogene** [SeleniumHQ/selenium#2724] opened 2016-09-06 15:20 UTC
OS:  Microsoft 7
Selenium Version:  2.44.0
Browser:  IE 11, 64 Bit

I am having a major issue running our automation scripts in IE. I am able to access the elements I need in the default IE window. In our application, I click a button, and a new window opens. In that new window I am not able to access ANY of the elements. I've never had this issue in the past as the code is the same and it works fine in FF.

I’m able to switch WebDriver to the new window and close that window so I know I’m where I’m supposed to be. I wrote a method to list all elements on the page but all 2,118 elements/html tags come back blank. The only thing that comes back correct is the title of that window. I executed the same method on the default window and everything comes back correctly.

Any suggestions? I think I've done all the research I can as well as trial and error with switching windows in WebDriver, trying to access the elements, changing Internet Options in IE, enabling/disabling protected modes, etc.

I can provide more info as needed. This is a high priority and a resolution is much appreciated.

**Comment by lukeis** [comment] 2016-09-06 15:39
First, please try using the latest version of Selenium for IE: 2.53.1

When logging an issue it's advantageous to provide a reproducible webdriver script along with link to the page under question (if you can't provide a public link, consider creating one with jsfiddle.net ). 

If you're looking for user support, please consider emailing the user google group:
https://groups.google.com/forum/#!forum/selenium-users

Since there's no way currently for us to reproduce your issue, we will need to close this issue as not actionable until a way to reproduce it is provided. Also be sure to use the latest version of selenium.

**Closed by lukeis** 2016-09-06 15:39 UTC
