### ISSUE TITLE
 invalid argument: can't kill an exited process

### ISSUE THREAD

**Issue by mellansquare** [SeleniumHQ/selenium#6622] opened 2018-11-06 02:18 UTC
## Meta -
OS:  

Selenium Version:  

Browser:  

## Expected Behavior -
I'm currently attempting to get a spec to pass in Cloud9 and running into issues with Selenium.  I've installed firefox and geckodriver into my hosting machine.  The errors relating to those have disappeared bu now I'm getting an error I don't understand:

     Failure/Error: visit project_path(project)
     
     Selenium::WebDriver::Error::UnknownError:
       invalid argument: can't kill an exited process

What does this mean? 

Here's my test
```
require "rails_helper"

RSpec.feature "Users can create new tickets" do
    let(:user) { FactoryBot.create(:user) }
  
  before do
    login_as(user)
    project = FactoryBot.create(:project, name: "Internet Explorer")
    assign_role!(user, :editor, project)
    
    visit project_path(project)
    click_link "New Ticket"
  end

   scenario "with multiple attachment", js: true do
    fill_in "Name", with: "Add documentation for blink tag"
    fill_in "Description", with: "Blink tag's speed attribute"
    
    attach_file "File #1", Rails.root.join("spec/fixtures/speed.txt")
    click_link "Add another file"
    
    attach_file "File #2", Rails.root.join("spec/fixtures/spin.txt")
    click_button "Create Ticket"
    
    expect(page).to have_content "Ticket has been created."
    
    within("#ticket .attachments") do
      expect(page).to have_content "speed.txt"
      expect(page).to have_content "spin.txt"
    end
  end 
end
```

Here's the failure message from running my spec:

```
. (called from block (3 levels) in <top (required)> at /home/ubuntu/workspace/spec/factories/user_factory.rb:7)
...Capybara starting Puma...
* Version 3.12.0 , codename: 
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:40655
F.

Failures:

  1) Users can create new tickets with multiple attachment
     Failure/Error: visit project_path(project)
     
     Selenium::WebDriver::Error::UnknownError:
       invalid argument: can't kill an exited process
     # /usr/local/rvm/gems/ruby-2.3.4/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/bridge.rb:166:in `execute'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/bridge.rb:99:in `create_session'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/firefox/marionette/driver.rb:50:in `initialize'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/firefox/driver.rb:31:in `new'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/firefox/driver.rb:31:in `new'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/driver.rb:52:in `for'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver.rb:86:in `for'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-3.10.1/lib/capybara/selenium/driver.rb:27:in `browser'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-3.10.1/lib/capybara/selenium/driver.rb:46:in `visit'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-3.10.1/lib/capybara/session.rb:265:in `visit'
     # /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-3.10.1/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/creating_tickets_spec.rb:11:in `block (2 levels) in <top (required)>'

Finished in 2.66 seconds (files took 4.28 seconds to load)
5 examples, 1 failure

Failed examples:

rspec ./spec/features/creating_tickets_spec.rb:43 # Users can create new tickets with multiple attachment
```

**Comment by mellansquare** [comment] 2018-11-06 02:19
Sorry the formatting went weird!!!

**Comment by luke-hill** [comment] 2018-11-07 00:10
Given you've got a unit test for what I assume is a locally running rails app, how much of it can you diet down/remove?

The only reason I ask is that we need a reproducible case that we can run, in order to diagnose and reproduce the error (If it is a true error)

Can you re-write the failing scenario as a single unit test without befores. and with as much crud removed (Un-necessary startups e.t.c.)

Also you've got some methods that are obfuscated (`login_as` seems to be one), and it's hard to work out how much complexity is in your single unit test.

**Comment by mellansquare** [comment] 2018-11-07 23:22
I've added the code before the visit line and got the following errors:

`. (called from block (3 levels) in <top (required)> at /home/ubuntu/workspace/spec/factories/user_factory.rb:7)
FFFFF

Failures:

  1) Users can create new tickets with valid attributes
     Failure/Error: Selenum::WebDriver.logger.level = :debug
     
     NameError:
       uninitialized constant Selenum
     # ./spec/features/creating_tickets_spec.rb:11:in `block (2 levels) in <top (required)>'

  2) Users can create new tickets when providing invalid attributes
     Failure/Error: Selenum::WebDriver.logger.level = :debug
     
     NameError:
       uninitialized constant Selenum
     # ./spec/features/creating_tickets_spec.rb:11:in `block (2 levels) in <top (required)>'

  3) Users can create new tickets with an invalid description
     Failure/Error: Selenum::WebDriver.logger.level = :debug
     
     NameError:
       uninitialized constant Selenum
     # ./spec/features/creating_tickets_spec.rb:11:in `block (2 levels) in <top (required)>'

  4) Users can create new tickets with multiple attachment
     Failure/Error: Selenum::WebDriver.logger.level = :debug
     
     NameError:
       uninitialized constant Selenum
     # ./spec/features/creating_tickets_spec.rb:11:in `block (2 levels) in <top (required)>'

  5) Users can create new tickets persisting file uploads across form displays
     Failure/Error: Selenum::WebDriver.logger.level = :debug
     
     NameError:
       uninitialized constant Selenum
     # ./spec/features/creating_tickets_spec.rb:11:in `block (2 levels) in <top (required)>'

Finished in 0.72896 seconds (files took 6.25 seconds to load)
5 examples, 5 failures

Failed examples:

rspec ./spec/features/creating_tickets_spec.rb:16 # Users can create new tickets with valid attributes
rspec ./spec/features/creating_tickets_spec.rb:27 # Users can create new tickets when providing invalid attributes
rspec ./spec/features/creating_tickets_spec.rb:35 # Users can create new tickets with an invalid description
rspec ./spec/features/creating_tickets_spec.rb:44 # Users can create new tickets with multiple attachment
rspec ./spec/features/creating_tickets_spec.rb:62 # Users can create new tickets persisting file uploads across form displays`

My apologies for the over-complex test. I'm just starting to learn ruby on rails so this is the first time I've built a web app using the language.

**Comment by mellansquare** [comment] 2018-11-07 23:22
The full spec:
`require "rails_helper"

RSpec.feature "Users can create new tickets" do
    let(:user) { FactoryBot.create(:user) }
  
  before do
    login_as(user)
    project = FactoryBot.create(:project, name: "Internet Explorer")
    assign_role!(user, :editor, project)
    
    Selenum::WebDriver.logger.level = :debug
    visit project_path(project)
    click_link "New Ticket"
  end

  scenario "with valid attributes" do
    fill_in "Name", with: "Non-standards compliance"
    fill_in "Description", with: "My pages are ugly!"
    click_button "Create Ticket"
  
    expect(page).to have_content "Ticket has been created."
    within("#ticket") do
      expect(page).to have_content "Author: #{user.email}"
    end
  end

  scenario "when providing invalid attributes" do
    click_button "Create Ticket"
  
    expect(page).to have_content "Ticket has not been created."
    expect(page).to have_content "Name can't be blank"
    expect(page).to have_content "Description can't be blank"
  end
  
  scenario "with an invalid description" do
    fill_in "Name", with: "Non=standards compliance"
    fill_in "Description", with: "It Sucks"
    click_button "Create Ticket" 
    
    expect(page).to have_content "Ticket has not been created."
    expect(page).to have_content "Description is too short"
  end
  
  scenario "with multiple attachment", js: true do
    fill_in "Name", with: "Add documentation for blink tag"
    fill_in "Description", with: "Blink tag's speed attribute"
    
    attach_file "File #1", Rails.root.join("spec/fixtures/speed.txt")
    click_link "Add another file"
    
    attach_file "File #2", Rails.root.join("spec/fixtures/spin.txt")
    click_button "Create Ticket"
    
    expect(page).to have_content "Ticket has been created."
    
    within("#ticket .attachments") do
      expect(page).to have_content "speed.txt"
      expect(page).to have_content "spin.txt"
    end
  end
  
  scenario "persisting file uploads across form displays" do
    attach_file "File #1", "spec/fixtures/speed.txt"
    click_button "Create Ticket"
    
    fill_in "Name", with: "Add documentation for blink tag"
    fill_in "Description", with: "The blink tag has a speed attribute"
    click_button "Create Ticket"
    
    within("#ticket .attachments") do
      expect(page).to have_content "speed.txt"
    end
  end
end`

**Comment by p0deje** [comment] 2018-11-08 05:45
It seems like you have an environment problem. When GeckoDriver starts Firefox, it prints:

```
Error: no DISPLAY environment variable specified
```

Which means you have a server without display. This is why Firefox process is exits and nothing works. You need either to use Firefox in headless mode or use something like Xvfb to emulate display. There are a lot of posts explaining how to do that (for example, https://www.koffeinfrei.org/2017/12/22/replace-phantomjs-by-headless-firefox-for-capybara/) and it has been discussed multiple times on [selenium-users](https://groups.google.com/forum/#!searchin/selenium-users) group, so you will find examples there too.

Closing this as it's not Selenium issue, but misconfiguration of environment.

**Closed by p0deje** 2018-11-08 05:45 UTC
Labels: C-rb, R-awaiting answer
