### ISSUE TITLE
standalone-2.52.0: starts up and complains forever for no intelligible reason

### ISSUE THREAD

**Issue by QS-EXT-7NXT** [SeleniumHQ/selenium#2462] opened 2016-07-13 15:07 UTC
## Meta -
OS:  Linux Ubuntu 16.04
Selenium Version:  standalone-2.52.0
Browser:  None yet per session; occurred after using phantomjs first time after firefox

[If the issue is with PhantomJS consider logging an issue with Ghostdriver:
https://github.com/detro/ghostdriver] <-- I cannot imagine how this should work in this case. Which kind of residue should it have left and how? if anyone has a clue, please advise.

## Expected Behavior -
server starts up in debug mode, spits out some lines and shuts up until driver connects

## Actual Behavior -
server starts up in debug mode, spits out some lines and keeps complaining forever (driver to browser control seems to work normally, though)

$ java -jar ../webdriverio-test/selenium-server-standalone-2.52.0.jar  -debug  
16:50:25.504 INFO - Launching a standalone Selenium Server
16:50:25.531 INFO - Java: Oracle Corporation 25.91-b14
16:50:25.532 INFO - OS: Linux 4.4.0-28-generic amd64
16:50:25.542 INFO - v2.52.0, with Core v2.52.0. Built from revision 4c2593c
16:50:25.542 INFO - Selenium server running in debug mode.
16:50:25.604 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform LINUX
16:50:25.604 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform LINUX
16:50:25.605 INFO - Driver class not found: com.opera.core.systems.OperaDriver
16:50:25.605 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
16:50:25.606 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform LINUX
16:50:25.670 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
16:50:25.670 INFO - Selenium Server is up and running
16:50:25.803 DEBUG - Handling: POST /session/a8ca7927-79a7-47e0-be48-28efeab2babb/elements
16:50:25.804 DEBUG - Handling: POST /session/cc258410-a0ae-47fd-8140-a07cba16f59a/elements
16:50:25.835 DEBUG - Error on: POST /session/cc258410-a0ae-47fd-8140-a07cba16f59a/elements
16:50:25.835 DEBUG - Error on: POST /session/a8ca7927-79a7-47e0-be48-28efeab2babb/elements
16:50:25.953 DEBUG - Handling: POST /session/dfc7b147-bcf9-4cc0-acce-13a4bf1aa136/elements
16:50:25.954 DEBUG - Handling: POST /session/a99ffcb6-de0e-40ff-8e84-c174c87d4739/elements
16:50:25.955 DEBUG - Error on: POST /session/dfc7b147-bcf9-4cc0-acce-13a4bf1aa136/elements
16:50:25.955 DEBUG - Error on: POST /session/a99ffcb6-de0e-40ff-8e84-c174c87d4739/elements
16:50:26.172 DEBUG - Handling: POST /session/a8ca7927-79a7-47e0-be48-28efeab2babb/elements
16:50:26.174 DEBUG - Error on: POST /session/a8ca7927-79a7-47e0-be48-28efeab2babb/elements
16:50:26.224 DEBUG - Handling: POST /session/cc258410-a0ae-47fd-8140-a07cba16f59a/elements
16:50:26.225 DEBUG - Error on: POST /session/cc258410-a0ae-47fd-8140-a07cba16f59a/elements
16:50:26.455 DEBUG - Handling: POST /session/dfc7b147-bcf9-4cc0-acce-13a4bf1aa136/elements
16:50:26.457 DEBUG - Handling: POST /session/a99ffcb6-de0e-40ff-8e84-c174c87d4739/elements
16:50:26.460 DEBUG - Error on: POST /session/a99ffcb6-de0e-40ff-8e84-c174c87d4739/elements
16:50:26.457 DEBUG - Error on: POST /session/dfc7b147-bcf9-4cc0-acce-13a4bf1aa136/elements
16:50:26.672 DEBUG - Handling: POST /session/a8ca7927-79a7-47e0-be48-28efeab2babb/elements
16:50:26.675 DEBUG - Error on: POST /session/a8ca7927-79a7-47e0-be48-28efeab2babb/elements
16:50:26.725 DEBUG - Handling: POST /session/cc258410-a0ae-47fd-8140-a07cba16f59a/elements
16:50:26.727 DEBUG - Error on: POST /session/cc258410-a0ae-47fd-8140-a07cba16f59a/elements
16:50:26.955 DEBUG - Handling: POST /session/dfc7b147-bcf9-4cc0-acce-13a4bf1aa136/elements
16:50:26.957 DEBUG - Error on: POST /session/dfc7b147-bcf9-4cc0-acce-13a4bf1aa136/elements
16:50:26.957 DEBUG - Handling: POST /session/a99ffcb6-de0e-40ff-8e84-c174c87d4739/elements
16:50:26.960 DEBUG - Error on: POST /session/a99ffcb6-de0e-40ff-8e84-c174c87d4739/elements

## Steps to reproduce -

On my machine. it's regular behavior now.

**Comment by lukeis** [comment] 2016-07-15 05:02
I'm not sure i understand why you expect to have less logging when you enable -debug?

Closing as working as intended... if you don't want the extra debug lines, don't use the -debug flag.

**Closed by lukeis** 2016-07-15 05:02 UTC

**Comment by QS-EXT-7NXT** [comment] 2016-07-15 08:40
lukeis: there is _no_ _client_ connected_ to the standalone server, so it should not log anything at all, because _there_ _are_ _no_ _events_ _to_ _log_.

So anyone with a sane mind would _expect_ the server to _log_ _nothing_.   How can you declare a source of mindless blabbering 'expected behavior'?  Are you a troll?

**Comment by lukeis** [comment] 2016-07-15 14:53
You obviously have a client connected to the machine, the server doesn't not just start logging on it's own.

**Comment by QS-EXT-7NXT** [comment] 2016-07-19 08:58
lukeis: there is no client connected to the standalone server. The server just starts up from the command line and starts complaining.  No client process is running any more at this point according to the process list.  No relevant ports are allocated.

**Comment by lukeis** [comment] 2016-07-19 13:35
Can you capture the network traffic on the host for port 4444 when this is occurring. Use a tool like wireshark to capture it
