### ISSUE TITLE
[🐛 Bug]: Dim driver2 As New Edge.EdgeDriver(EdgeDriverService2, EdgeOptions2) cause show start up form

### ISSUE THREAD

**Issue by Bradley501** [SeleniumHQ/selenium#10587] opened 2022-04-28 18:00 UTC
### What happened?

Dim EdgeDriverService2 = Edge.EdgeDriverService.CreateDefaultService(Application.StartupPath)
       
 Dim EdgeOptions2 As New Edge.EdgeOptions

        EdgeDriverService2.HideCommandPromptWindow = True
        EdgeOptions2.AddArgument("--headless")
 

        Dim driver2 As New Edge.EdgeDriver(EdgeDriverService2, EdgeOptions2)

Run above code in a Sub in a Module in a Parameterized thread in Visual Studio 2022 in a Visual Basic Windows Forms App , using Selenium Webdriver, last line wrongly  cause show application start up form. Could you fix it by stopping show start up form.

### How can we reproduce the issue?

```shell
Dim EdgeOptions2 As New Edge.EdgeOptions

        EdgeDriverService2.HideCommandPromptWindow = True
        EdgeOptions2.AddArgument("--headless")
 


        Dim driver2 As New Edge.EdgeDriver(EdgeDriverService2, EdgeOptions2)

Run above code in a Sub in a Module in a Parameterized thread in Visual Studio 2022 in a Visual Basic Windows Forms App , using Selenium Webdriver, last line wrongly cause show application start up form. Could you fix it by stopping show start up form.
```

### Relevant log output

```shell
None.
```

### Operating System

Windows 10

### Selenium version

Visual Basic Selenium. WebDriver 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Microsoft Edge Version 100.0.1185.50 (Official build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

Don't know

### Are you using Selenium Grid?

Don't know

**Comment by diemol** [comment] 2022-04-28 19:59
Is it possible for you to elaborate more and explain what the issue is? Please follow the issue template. 

Also, can you please provide a GitHub repository with the whole setup so we can clone it and reproduce the issue?

Without proper information this issue will probably go stale and be closed.

**Comment by titusfortner** [comment] 2022-05-04 22:55
Is the problem that it is supposed to be headless but is not?

**Comment by diemol** [comment] 2022-05-05 10:44
I will close this as there was no more input. We can reopen if needed.

**Closed as completed by diemol** 2022-05-05 10:44 UTC
Labels: I-defect, J-issue-template
