### ISSUE TITLE
Can't click on a URL that spans two physical lines

### ISSUE THREAD

**Issue by kdmurthy** [SeleniumHQ/selenium#3167] opened 2016-11-25 16:30 UTC
## Meta -
OS:  
Windows 10
Selenium Version:  
3.0.1
Browser:  
Firefox 

Browser Version:  
47.0.1

## Expected Behavior -
Using `driver.action.move_to(e).click.perform` should click on the URL.

## Actual Behavior -
Using the code `driver.action.move_to(e).click.perform does not click a URL that is spanned on two lines. However `e.click` works OK.

## Steps to reproduce -
Not sure whether it happens for all the URLs. However, in this case if the `div` containing the URL is resized to have the URL on a single line - it is clicked.

**Comment by lmtierney** [comment] 2016-11-25 20:15
Are you using geckodriver?

**Comment by kdmurthy** [comment] 2016-11-27 12:55
No. I am using Firefox driver with 47.0.1.

-- KD


-- KD

--
Dakshinamurthy Karra
CEO & Managing Director
Jalian Systems Pvt. Ltd.
1st Floor, #457, 3rd Cross
5th Main, 5th Block
H.B.R Layout
Bangalore - 560043
INDIA
W: http://www.jaliansystems.com
W: http://www.marathontesting.com

**Comment by lmtierney** [comment] 2016-11-27 13:29
It's probably due to it not being able to calculate the right point to click since it spans multiple lines. Try adding an offset to your move_to command e.g. `driver.action.move_to(e, 1, 1).click.perform`

**Comment by kdmurthy** [comment] 2016-11-27 16:14
I am already using a workaround `e.click`. Just posting it because it looks like a bug :)

**Comment by lmtierney** [comment] 2016-11-27 16:25
Actions try to put the mouse in the middle of the element based on boundingRect I believe. So it probably is doing that, but your link isn't in the middle of the page. This would probably be a good thing to bring up with the w3c spec when actions are defined

**Comment by lukeis** [comment] 2016-11-28 19:14
reproduced (using python)

    from selenium import webdriver as w
    from selenium.webdriver.common.action_chains import ActionChains as ac
    d = w.Firefox(capabilities={'marionette':False})
    d.get('https://jsfiddle.net/hwg4e8rv/show/')
    d.switch_to_frame(d.find_element_by_tag_name('iframe'))
    link = d.find_element_by_id("link")
    ac(d).move_to_element(link).click().perform() # doesn't work
    link.click() # works

The fiddle html:

    <a id="link" href="javascript:document.getElementById('clicked').innerHTML='clicked';">link<br/>two lines</a>
    <div id="clicked"></div>


The issue is the actions api is a 'do as I say', not do as I mean. When you move to the element and attempt to click it like this, it calculates the click point as the 'center' of the element. But the center is the space between the two lines and thus the click is occuring on the background and not the link itself. Workarounds include using the element.click, like you've done, or if using actions, use the move_to_element_with_offset command (in python) or pass in the right_by / down_by parameters (in ruby).

Because actions is 'do as I say' this isn't a bug, it's doing exactly as you told it to do. Closing for that reason.

**Closed by lukeis** 2016-11-28 19:14 UTC
