### ISSUE TITLE
[🐛 Bug]:  cannot determine loading status from no such window 

### ISSUE THREAD

**Issue by lijingmu** [SeleniumHQ/selenium#13943] opened 2024-05-15 04:15 UTC
### What happened?

Greetings. I am using javascript selenium-webdriver. I encountered one issue in chromium 112, selenium 4.12.0:
```
WebDriverError: unknown error: failed to wait for extension background page to load: chrome-extension://xxxx/_generated_background_page.html from unknown error: cannot determine loading status from no such window
at   Object.throwDecodedError   (xxx/node_modules/selenium-webdriver/lib/error.js:524:15)
at   parseHttpResponse   (xxx/node_modules/selenium-webdriver/lib/http.js:601:13)
at   Executor.execute   (xxx/node_modules/selenium-webdriver/lib/http.js:529:28)
at   process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
The issue is not happened when I use selenium 4.1.2. It happened occasional in long running. 
Any suggestions will be appreciated. Is it possible the version issues? I need to use chrome 112. Which version of selenium-webdriver javascript client is recommended? 

### How can we reproduce the issue?

- Add one chrome extension
- Open one webpage with chromium 112
- Running for 2 hours. 
- It may happen one or two times.

```
options.addExtensions(myExtensionPlugin);
options.addArguments('--allowlisted-extension-id=xxxx');
```

### Relevant log output

```shell
WebDriverError: unknown error: failed to wait for extension background page to load:
chrome-extension://xxxx/_generated_background_page.html   from unknown error:
cannot determine loading status from no such window
at   Object.throwDecodedError   (xxx/node_modules/selenium-webdriver/lib/error.js:524:15)
at   parseHttpResponse   (xxx/node_modules/selenium-webdriver/lib/http.js:601:13)
at   Executor.execute   (xxx/node_modules/selenium-webdriver/lib/http.js:529:28)
at   process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Operating System

Linux x86_64

### Selenium version

javascript selenium-webdriver 4.12.0

### What are the browser(s) and version(s) where you see this issue?

Chromium 112.0.5615.0

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 112.0.5615.0

### Are you using Selenium Grid?

No

**Comment by diemol** [comment] 2024-05-15 04:33
We cannot troubleshoot old versions of Selenium. Please update and provide a way to reproduce the issue, avoid narratives and provide a code snippet with all dependencies to reproduce the issue.

**Comment by lijingmu** [comment] 2024-05-16 05:53
Thanks for your response. I have upgraded selenium-webdriver to 4.20.0 the latest one. Now it is much better. With selenium-webdriver 4.20.0 javascript client + chromium 112, it is more stable. I can isolate the issue to a small scope. The intermittent issue of `unknown error: cannot determine loading status from no such window` happened sometimes when click on the web element and page self-refreshed e.g. click on the `summary` link on the navigation bar [on this page](https://developer.ibm.com/learningpaths/data-analysis-using-python/summary/) . Sample code is as below: 

```
let element = await driver.findElement(By.linkText(`Summary`));
console.log("Scroll down to Summary");
await driver.executeScript("arguments[0].scrollIntoView()", element);
console.log("Click on Summary");
await driver.executeScript("arguments[0].click();", element);
```
Sometimes it failed at click `await driver.executeScript("arguments[0].click();", element);` randomly

```
Failed to execute command executeScript {"script":"arguments[0].click();","args":[{"element-6066-11e4-a52e-4f7 unknown error: cannot determine loading status from no such window
WebDriverError: unknown error: cannot determine loading status
    from no such window
      (Session info: chrome=112.0.5615.0)
        at Object.throwDecodedError (xx/node_modules/selenium-webdriver/lib/error.js:524:15)
        at parseHttpResponse (xx/node_modules/selenium-webdriver/lib/http.js:601:13)
        at Executor.execute (xxx/node_modules/selenium-webdriver/lib/http.js:529:28)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
If you have any suggestions about how to update the test script, it will also be helpful.

**Comment by pujagani** [comment] 2024-05-16 16:36
Thank you for the update. The code snippet shared is not complete. Can you please provide a complete reproducible test script? https://github.com/SeleniumHQ/selenium/issues/13943#issuecomment-2111562793

**Comment by diemol** [comment] 2024-05-16 16:51
What happens when you use the latest Chrome version?

**Comment by diemol** [comment] 2024-07-12 08:24
I am closing this because we have yet to get more information.

**Closed as not planned by diemol** 2024-07-12 08:24 UTC
Labels: I-defect, J-issue-template, A-needs-triaging
