### ISSUE TITLE
[🐛 Bug]: "Unable to parse:" - empty request body

### ISSUE THREAD

**Issue by pajon** [SeleniumHQ/selenium#11188] opened 2022-10-28 12:31 UTC
### What happened?

Hi guys,

i tried to migrate selenium from version 3.141.59 to newer with grid, but i have every CI/CD run some errors.
It seems your httpclient change from 4.5.2 solved some issues, but there are still some issues. Almost for me.

I found how to solve remaining issues, but it is not a good way. All issues have empty request body.

For example, at this place request body is empty and it throw exception 
"org.openqa.selenium.json.JsonException: Unable to parse:"
https://github.com/SeleniumHQ/selenium/blob/cd3e9aea5261fb9ea371b95abe8ae6113241dfb6/java/src/org/openqa/selenium/grid/node/CustomLocatorHandler.java#L116

When i tried to debug this, i accidently found fix. 

Putting code `msg.getContent().get();` before https://github.com/SeleniumHQ/selenium/blob/702b3aae7385adf331d75cdeacd79720cf6b9c84/java/src/org/openqa/selenium/netty/server/SeleniumHandler.java#L44

fixed all issues with empty request body for me.
I'm attaching some logs, but this logs are from older version 4.5.0, but all is the same.

It seems to be a issue in netty. Request body seems to be destroyed earlier than we `get` it.

Can you help me or explain why `get` the request body can fix all issues ? Java is not my main language.

Thank you

P.S. Pardon my mistakes, English is not my first language.

### How can we reproduce the issue?

```shell
Do some tests, it happened randomly.
```

### Relevant log output

```shell
selenium-chrome-1   | 12:13:45.761 DEBUG [SeleniumSpanExporter$1.lambda$export$4] - SpanData{spanContext=ImmutableSpanContext{traceId=a4f175cf5bc027266f487d492d524302, spanId=3908926547870ea8, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.9.0, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.16.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=default, version=null, schemaUrl=null}, name=router.handle_session, kind=INTERNAL, startEpochNanos=1666181625756000000, endEpochNanos=1666181625760906708, attributes=AttributesMap{data={http.target=/session/256abe3b7a7be89941ad777e6cf048a4/elements, error=true, session.id=256abe3b7a7be89941ad777e6cf048a4, http.method=POST}, capacity=128, totalAddedValues=4}, totalAttributeCount=4, events=[ImmutableEventData{name=exception, attributes={exception.message="Unable to execute request for an existing session: Unable to parse: ", exception.stacktrace="org.openqa.selenium.json.JsonException: Unable to parse:
selenium-chrome-1   | 	at org.openqa.selenium.json.Json.toType(Json.java:57)
selenium-chrome-1   | 	at org.openqa.selenium.json.Json.toType(Json.java:50)
selenium-chrome-1   | 	at org.openqa.selenium.grid.node.CustomLocatorHandler.execute(CustomLocatorHandler.java:119)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-chrome-1   | 	at org.openqa.selenium.grid.node.Node.execute(Node.java:240)
selenium-chrome-1   | 	at org.openqa.selenium.grid.web.CombinedHandler.execute(CombinedHandler.java:59)
selenium-chrome-1   | 	at org.openqa.selenium.grid.web.RoutableHttpClientFactory$1.execute(RoutableHttpClientFactory.java:72)
selenium-chrome-1   | 	at org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:92)
selenium-chrome-1   | 	at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:122)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-chrome-1   | 	at org.openqa.selenium.grid.router.Router.execute(Router.java:91)
selenium-chrome-1   | 	at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-chrome-1   | 	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
selenium-chrome-1   | 	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-chrome-1   | 	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-chrome-1   | 	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
selenium-chrome-1   | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
selenium-chrome-1   | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
selenium-chrome-1   | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
selenium-chrome-1   | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
selenium-chrome-1   | 	at java.base/java.lang.Thread.run(Thread.java:829)
selenium-chrome-1   | Caused by: org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read:
selenium-chrome-1   | Build info: version: '4.4.0', revision: 'e5c75ed026a'
selenium-chrome-1   | System info: host: '61933e7009e1', ip: '172.19.0.9', os.name: 'Linux', os.arch: 'aarch64', os.version: '5.10.124-linuxkit', java.version: '11.0.16'
selenium-chrome-1   | Driver info: driver.version: unknown
selenium-chrome-1   | 	at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:307)
selenium-chrome-1   | 	at org.openqa.selenium.json.JsonInput.beginObject(JsonInput.java:229)
selenium-chrome-1   | 	at org.openqa.selenium.json.MapCoercer.lambda$apply$1(MapCoercer.java:64)
selenium-chrome-1   | 	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
selenium-chrome-1   | 	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
selenium-chrome-1   | 	at org.openqa.selenium.json.Json.toType(Json.java:71)
selenium-chrome-1   | 	at org.openqa.selenium.json.Json.toType(Json.java:55)
selenium-chrome-1   | 	... 31 more
selenium-chrome-1   | ", exception.type="org.openqa.selenium.json.JsonException", http.flavor=1, http.handler_class="org.openqa.selenium.grid.router.HandleSession", http.host="selenium-router:4444", http.method="POST", http.request_content_length="39", http.scheme="HTTP", http.target="/session/256abe3b7a7be89941ad777e6cf048a4/elements", session.id="256abe3b7a7be89941ad777e6cf048a4"}, epochNanos=1666181625760898375, totalAttributeCount=11}], totalRecordedEvents=1, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=ERROR, description=Kind: CANCELLED Description:}, hasEnded=true}
selenium-chrome-1   | 12:13:45.761 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to execute request for an existing session: Unable to parse:
selenium-chrome-1   | 12:13:45.761 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.json.JsonException: Unable to parse:
selenium-chrome-1   | 	at org.openqa.selenium.json.Json.toType(Json.java:57)
selenium-chrome-1   | 	at org.openqa.selenium.json.Json.toType(Json.java:50)
selenium-chrome-1   | 	at org.openqa.selenium.grid.node.CustomLocatorHandler.execute(CustomLocatorHandler.java:119)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-chrome-1   | 	at org.openqa.selenium.grid.node.Node.execute(Node.java:240)
selenium-chrome-1   | 	at org.openqa.selenium.grid.web.CombinedHandler.execute(CombinedHandler.java:59)
selenium-chrome-1   | 	at org.openqa.selenium.grid.web.RoutableHttpClientFactory$1.execute(RoutableHttpClientFactory.java:72)
selenium-chrome-1   | 	at org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:92)
selenium-chrome-1   | 	at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:122)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-chrome-1   | 	at org.openqa.selenium.grid.router.Router.execute(Router.java:91)
selenium-chrome-1   | 	at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
selenium-chrome-1   | 	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
selenium-chrome-1   | 	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-chrome-1   | 	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
selenium-chrome-1   | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium-chrome-1   | 	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
selenium-chrome-1   | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
selenium-chrome-1   | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
selenium-chrome-1   | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
selenium-chrome-1   | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
selenium-chrome-1   | 	at java.base/java.lang.Thread.run(Thread.java:829)
selenium-chrome-1   | Caused by: org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read:
selenium-chrome-1   | Build info: version: '4.4.0', revision: 'e5c75ed026a'
selenium-chrome-1   | System info: host: '61933e7009e1', ip: '172.19.0.9', os.name: 'Linux', os.arch: 'aarch64', os.version: '5.10.124-linuxkit', java.version: '11.0.16'
selenium-chrome-1   | Driver info: driver.version: unknown
selenium-chrome-1   | 	at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:307)
selenium-chrome-1   | 	at org.openqa.selenium.json.JsonInput.beginObject(JsonInput.java:229)
selenium-chrome-1   | 	at org.openqa.selenium.json.MapCoercer.lambda$apply$1(MapCoercer.java:64)
selenium-chrome-1   | 	at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
selenium-chrome-1   | 	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
selenium-chrome-1   | 	at org.openqa.selenium.json.Json.toType(Json.java:71)
selenium-chrome-1   | 	at org.openqa.selenium.json.Json.toType(Json.java:55)
selenium-chrome-1   | 	... 31 more
selenium-chrome-1   |
selenium-chrome-1   | 12:13:45.762 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "a4f175cf5bc027266f487d492d524302","eventTime": 1666181625760898375,"eventName": "exception","attributes": {"exception.message": "Unable to execute request for an existing session: Unable to parse: ","exception.stacktrace": "org.openqa.selenium.json.JsonException: Unable to parse: \n\tat org.openqa.selenium.json.Json.toType(Json.java:57)\n\tat org.openqa.selenium.json.Json.toType(Json.java:50)\n\tat org.openqa.selenium.grid.node.CustomLocatorHandler.execute(CustomLocatorHandler.java:119)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.node.Node.execute(Node.java:240)\n\tat org.openqa.selenium.grid.web.CombinedHandler.execute(CombinedHandler.java:59)\n\tat org.openqa.selenium.grid.web.RoutableHttpClientFactory$1.execute(RoutableHttpClientFactory.java:72)\n\tat org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:92)\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:122)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:91)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\nCaused by: org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read: \nBuild info: version: '4.4.0', revision: 'e5c75ed026a'\nSystem info: host: '61933e7009e1', ip: '172.19.0.9', os.name: 'Linux', os.arch: 'aarch64', os.version: '5.10.124-linuxkit', java.version: '11.0.16'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.json.JsonInput.expect(JsonInput.java:307)\n\tat org.openqa.selenium.json.JsonInput.beginObject(JsonInput.java:229)\n\tat org.openqa.selenium.json.MapCoercer.lambda$apply$1(MapCoercer.java:64)\n\tat org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)\n\tat org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)\n\tat org.openqa.selenium.json.Json.toType(Json.java:71)\n\tat org.openqa.selenium.json.Json.toType(Json.java:55)\n\t... 31 more\n","exception.type": "org.openqa.selenium.json.JsonException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.router.HandleSession","http.host": "selenium-router:4444","http.method": "POST","http.request_content_length": "39","http.scheme": "HTTP","http.target": "\u002fsession\u002f256abe3b7a7be89941ad777e6cf048a4\u002felements","session.id": "256abe3b7a7be89941ad777e6cf048a4"}}
```

### Operating System

k8s + x86 or arm8

### Selenium version

4.5.3

### What are the browser(s) and version(s) where you see this issue?

Doesn't matter, it happened across multiple versions

### What are the browser driver(s) and version(s) where you see this issue?

Doesn't matter, it happened across multiple versions

### Are you using Selenium Grid?

Sure, docker tag 4.5.3-20221024

**Comment by titusfortner** [comment] 2022-10-28 21:13
Thanks for the report.
This is a duplicate of https://github.com/SeleniumHQ/docker-selenium/issues/1507

**Closed as completed by titusfortner** 2022-10-28 21:13 UTC
Labels: I-defect, A-needs-triaging
