### ISSUE TITLE
[🐛 Bug]: Chrome driver doesn't respond / getting stuck on 'data' page

### ISSUE THREAD

**Issue by akorzhoffs** [SeleniumHQ/selenium#12730] opened 2023-09-12 13:10 UTC
### What happened?

Hello!

1. I encountered the issue that my Chrome sometimes (randomly appears ~1 of 3 times) getting stuck on 'data;' page and can't navigate to any address then. After that it fails with such message: 'The HTTP request to the remote WebDriver server for URL http://localhost:61654/session/9dbebc44718d5971d2d5e2ea39ebc18d/url timed out after 60 seconds.'
2. I googled the issue and found out that 'no-sandbox' flag could solve my problem. I added this flag to my browser and started encountering another issue: I am getting a completely blank browser window (even without top bar). Then my test fails with a message 'The HTTP request to the remote WebDriver server for URL http://localhost:62920/session timed out after 60 seconds' during the browser initialization.

The issue was also reproduced with other driver and selenium versions.

### How can we reproduce the issue?

```shell
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;

namespace Test;

public class GenericTest
{
    private IWebDriver _driver;

    [SetUp]
    public void Setup()
    {
        var options = new ChromeOptions();
        options.AddArgument("--ignore-ssl-errors=yes");
        options.AddArgument("--ignore-certificate-errors");
        options.AddArgument("--start-maximized");
        options.AddArgument("--incognito");
        // options.AddArgument("--no-sandbox");
        _driver = new ChromeDriver(options);
        _driver.Navigate().GoToUrl("https://example.com/");
    }
    
    [Test]
    public void Test()
    {
        
    }
}
```

### Relevant log output

.NET does not currently have a Logging implementation

So here is the whole stack trace for the 1st issue:

```shell
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:63937/session/6b89c4c46975605b87234eca16060af4/url timed out after 60 seconds.
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.set_Url(String value)
   at OpenQA.Selenium.Navigator.GoToUrl(String url)
   at SystemTests.GenericTest.InitDrivers() in C:\Users\user\source\repos\Tests\SystemTests\Tests\GenericTest.cs:line 198
   at SystemTests.GenericTest.Setup() in C:\Users\user\source\repos\Tests.SystemTests\Tests\GenericTest.cs:line 84
```

And for the 2nd:
```shell
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:62920/session timed out after 60 seconds.
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   at SystemTests.Tests.BrowserFactory.InitializeChromeDriver() in C:\Users\user\source\repos\Tests\SystemTests\Tests\BrowserFactory.cs:line 34
   at SystemTests.Tests.BrowserFactory.GetWebDriver(BrowserType browserType) in C:\Users\user\source\repos\Tests\SystemTests\Tests\BrowserFactory.cs:line 14
   at SystemTests.GenericTest.InitDrivers() in C:\Users\user\source\repos\Tests\SystemTests\Tests\GenericTest.cs:line 197
   at SystemTests.GenericTest.Setup() in C:\Users\user\source\repos\Tests\SystemTests\Tests\GenericTest.cs:line 84
```

### Operating System

Windows 11

### Selenium version

4.11.0

### What are the browser(s) and version(s) where you see this issue?

Version 116.0.5845.142 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

116.0.5845.9600

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment] 2023-09-12 18:58
Since it is reproducible on multiple versions, the answer is likely with the website you are loading, not with your code. You could try setting PageLoadStrategy to eager or none to see if it lets you continue. Most likely some asset isn't getting loaded properly and the driver times out waiting for it: https://www.selenium.dev/documentation/webdriver/drivers/options/#pageloadstrategy

I have no idea why `--no-sandbox` would keep the browser from starting up, that would be an issue for Google.

Either way, there is no bug for us to fix in Selenium code, so I'm closing.

**Closed as not planned by titusfortner** 2023-09-12 18:58 UTC
Labels: I-defect, A-needs-triaging
