### ISSUE TITLE
[🐛 Bug]: After a Timeout exception : Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. Host info: host: 'fv-az395-540', ip: '10.1.0.38'

### ISSUE THREAD

**Issue by HrishikeshRangdale-gep** [SeleniumHQ/selenium#14356] opened 2024-08-08 09:15 UTC
### What happened?

System info: os.name: 'Windows Server 2022', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.12'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 127.0.6533.73, chrome: {chromedriverVersion: 127.0.6533.72 (9755e24ca85a..., userDataDir: C:\Windows\SystemTemp\scope...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49178}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:49178/devtoo..., se:cdpVersion: 127.0.6533.73, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: db87a3f3bcb1d88a7ed9da8db9e8f8e3
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84) ~[selenium-support-4.23.0.jar:?]
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228) ~[selenium-support-4.23.0.jar:?]
	at com.gep.utils.selenium.RenderPageObjectView.waitForPresenceOf(RenderPageObjectView.java:214) ~[smarttest-seleniumcore-QC_LEO-SNAPSHOT.jar:QC_LEO-SNAPSHOT]
	... 31 more
Element  with By.xpath: //span[@id='nexx-btn-Accept']/a|//button[@id='buttonText']|//dm-button//span[@id='nexx-btn-Approve']|//div[@role='listbox']/descendant::a[normalize-space(text())='Accept']|//span[@id='nexx-btn-btnAccept']/a|//span[@id='nexx-btn-reviewaccept']|//span[@id='nexx-btn-fixedassetaccept']|//li[normalize-space(text())='Accept']|//div[normalize-space(text())='Accept'] was not loaded in specified timeout of 120 seconds kindly refer attached screenshot for more clearification
Running test 9 : P2P\InvoiceCM\TC_E2ECreateCreditMemo.smarttest.xml
Aug 08, 2024 8:14:55 AM org.openqa.selenium.concurrent.ExecutorServices shutdownGracefully
WARNING: Failed to shutdown Driver Service Executor
java.lang.InterruptedException

### How can we reproduce the issue?

```shell
after a script fails due to timeoutexception, the new sessions are not getting started and job gets stuck for long time

Aug 08, 2024 8:14:55 AM org.openqa.selenium.concurrent.ExecutorServices shutdownGracefully
WARNING: Failed to shutdown Driver Service Executor
java.lang.InterruptedException
```

### Relevant log output

```shell
System info: os.name: 'Windows Server 2022', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.12'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 127.0.6533.73, chrome: {chromedriverVersion: 127.0.6533.72 (9755e24ca85a..., userDataDir: C:\Windows\SystemTemp\scope...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:49178}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:49178/devtoo..., se:cdpVersion: 127.0.6533.73, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: db87a3f3bcb1d88a7ed9da8db9e8f8e3
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84) ~[selenium-support-4.23.0.jar:?]
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228) ~[selenium-support-4.23.0.jar:?]
	at com.gep.utils.selenium.RenderPageObjectView.waitForPresenceOf(RenderPageObjectView.java:214) ~[smarttest-seleniumcore-QC_LEO-SNAPSHOT.jar:QC_LEO-SNAPSHOT]
	... 31 more
Element  with By.xpath: //span[@id='nexx-btn-Accept']/a|//button[@id='buttonText']|//dm-button//span[@id='nexx-btn-Approve']|//div[@role='listbox']/descendant::a[normalize-space(text())='Accept']|//span[@id='nexx-btn-btnAccept']/a|//span[@id='nexx-btn-reviewaccept']|//span[@id='nexx-btn-fixedassetaccept']|//li[normalize-space(text())='Accept']|//div[normalize-space(text())='Accept'] was not loaded in specified timeout of 120 seconds kindly refer attached screenshot for more clearification
Running test 9 : P2P\InvoiceCM\TC_E2ECreateCreditMemo.smarttest.xml
Aug 08, 2024 8:14:55 AM org.openqa.selenium.concurrent.ExecutorServices shutdownGracefully
WARNING: Failed to shutdown Driver Service Executor
java.lang.InterruptedException
```

### Operating System

Windows Server 2022 (20240729) Image Update

### Selenium version

4.23 and 4.22

### What are the browser(s) and version(s) where you see this issue?

chrome 127.0.6533.73

### What are the browser driver(s) and version(s) where you see this issue?

 127.0.6533.72 and 127.0.6533.99

### Are you using Selenium Grid?

no

**Comment by HrishikeshRangdale-gep** [comment] 2024-08-08 09:40
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1662)
	at java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1464)
	at org.openqa.selenium.concurrent.ExecutorServices.shutdownGracefully(ExecutorServices.java:33)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.close(DriverCommandExecutor.java:221)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:169)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:527)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:435)
	at org.openqa.selenium.chromium.ChromiumDriver.quit(ChromiumDriver.java:435)
	at com.gep.lifecycle.commands.selenium.DriverUtils$1.run(DriverUtils.java:148)

**Comment by HrishikeshRangdale-gep** [comment] 2024-08-08 12:02
at com.gep.utils.selenium.PageElement.isDisabledField(PageElement.java:733) ~[smarttest-seleniumcore-driverquit-SNAPSHOT.jar:driverquit-SNAPSHOT]
	at com.gep.utils.selenium.PageElement$2.apply(PageElement.java:463) ~[smarttest-seleniumcore-driverquit-SNAPSHOT.jar:driverquit-SNAPSHOT]
	at com.gep.utils.selenium.PageElement$2.apply(PageElement.java:460) ~[smarttest-seleniumcore-driverquit-SNAPSHOT.jar:driverquit-SNAPSHOT]
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:203) ~[selenium-support-4.23.0.jar:?]
	at com.gep.utils.selenium.PageElement.waitUntilElementAvailable(PageElement.java:1545) ~[smarttest-seleniumcore-driverquit-SNAPSHOT.jar:driverquit-SNAPSHOT]
	at com.gep.utils.selenium.PageElement.type(PageElement.java:1043) ~[smarttest-seleniumcore-driverquit-SNAPSHOT.jar:driverquit-SNAPSHOT]
	at com.gep.smarttest.selenium.common.Pages.HomePage.verifyDocumentStatusLeo(HomePage.java:7451) ~[smarttest-common-driverquit-SNAPSHOT.jar:driverquit-SNAPSHOT]
	at com.gep.smarttest.selenium.fixtures.smartp2p.VerifyDocumentStatusLeo$exd.execute(VerifyDocumentStatusLeo.java:31) ~[?:driverquit-SNAPSHOT]
	at com.gep.smarttest.spi.StepExecutorClosure.executeStep(StepExecutorClosure.java:168) [smarttest-engine-driverquit-SNAPSHOT.jar:driverquit-SNAPSHOT]
	at com.gep.smarttest.spi.StepExecutorClosure.execute(StepExecutorClosure.java:140) [smarttest-engine-driverquit-SNAPSHOT.jar:driverquit-SNAPSHOT]
	at org.apache.commons.collections.CollectionUtils.forAllDo(CollectionUtils.java:389) [commons-collections-3.2.2.jar:3.2.2]
	at com.gep.smarttest.spi.DefaultSmartTestRunner.executeTestSteps(DefaultSmartTestRunner.java:188) [smarttest-engine-driverquit-SNAPSHOT.jar:driverquit-SNAPSHOT]
	at com.gep.mand.FindAndRunSuite.testABC(FindAndRunSuite.java:139) [smarttest-engine-driverquit-SNAPSHOT.jar:driverquit-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) [testng-6.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) [testng-6.10.jar:?]

**Comment by HrishikeshRangdale-gep** [comment] 2024-08-08 12:03
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095) ~[?:?]
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1662)
	at java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1464)
	at org.openqa.selenium.concurrent.ExecutorServices.shutdownGracefully(ExecutorServices.java:33)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.close(DriverCommandExecutor.java:221)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:169)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:527)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.chromium.ChromiumDriver.quit(ChromiumDriver.java:435)
	at com.gep.lifecycle.commands.selenium.DriverUtils$1.run(DriverUtils.java:148)

**Comment by HrishikeshRangdale-gep** [comment] 2024-08-08 12:16
Already added

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pujagani** [comment] 2024-08-08 14:50
I am sorry I don't see a reproducible test script. We require it so we can reproduce the issue, triage it and then fix it. It is difficult for us to help without a complete reproducible test script. I don't see it as part the issue reported. Please add one.

**Comment by matasaru** [comment] 2024-08-13 02:55
I've been getting this stack trace for a couple of weeks now. I'm not sure if this is started after a Selenium or ChromiumDriver update.

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'c2', ip: '23.105.39.125'
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:563)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:245)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:174)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
        ...
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.23.1', revision: '656257d8e9'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.1.0-23-amd64', java.version: '22.0.2'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:418)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:374)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:89)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:61)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	... 16 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:401)
	... 26 common frames omitted


The InitSession command looks ok in chromedriver.log:
[1723517181.314][INFO]: Starting ChromeDriver 127.0.6533.99 (f31af5097d90ef5ae5bd7b8700199bc6189ba34d-refs/branch-heads/6533@{#1910}) on port 17268
[1723517181.314][INFO]: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1723517181.342][INFO]: [81c736bbd9ef9cd518e2c0d029d695c9] COMMAND InitSession {
   "capabilities": {
      "firstMatch": [ {
         "acceptInsecureCerts": true,
         "browserName": "chrome",
         "goog:chromeOptions": {
            "args": [ "--headless", "--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0", "--no-first-run", "--disable-client-side-phishing-detection", "--disable-popup-blocking", "--disable-default-apps", "--disable-extensions", "--metrics-recording-only", "--no-default-browser-check", "--disable-background-timer-throttling", "--disable-background-mode", "--disable-translate", "--safebrowsing-disable-auto-update", "--disable-background-networking", "--disable-prompt-on-repost", "--disable-sync", "--disable-hang-monitor", "--disable-web-security", "--no-sandbox", "--disable-dev-shm-usage", "--window-size=1920,1080", "--remote-allow-origins=*" ],
            "binary": "/usr/bin/chromium",
            "extensions": [  ]
         },
         "unhandledPromptBehavior": "ignore"
      } ]
   }
}
[1723517181.343][INFO]: Populating Preferences file: {
   "alternate_error_pages": {
      "enabled": false
   },
   "autofill": {
      "enabled": false
   },
   "browser": {
      "check_default_browser": false
   },
   "distribution": {
      "import_bookmarks": false,
      "import_history": false,
      "import_search_engine": false,
      "make_chrome_default_for_user": false,
      "skip_first_run_ui": true
   },
   "dns_prefetching": {
      "enabled": false
   },
   "profile": {
      "content_settings": {
         "pattern_pairs": {
            "https://*,*": {
               "media-stream": {
                  "audio": "Default",
                  "video": "Default"
               }
            }
         }
      },
      "default_content_setting_values": {
         "geolocation": 1
      },
      "default_content_settings": {
         "geolocation": 1,
         "mouselock": 1,
         "notifications": 1,
         "popups": 1,
         "ppapi-broker": 1
      },
      "password_manager_enabled": false
   },
   "safebrowsing": {
      "enabled": false
   },
   "search": {
      "suggest_enabled": false
   },
   "translate": {
      "enabled": false
   }
}
[1723517181.343][INFO]: Populating Local State file: {
   "background_mode": {
      "enabled": false
   },
   "ssl": {
      "rev_checking": {
         "enabled": false
      }
   }
}
[1723517181.343][INFO]: ChromeDriver supports communication with Chrome via pipes. This is more reliable and more secure.
[1723517181.343][INFO]: Use the --remote-debugging-pipe Chrome switch instead of the default --remote-debugging-port to enable this communication mode.
[1723517181.343][INFO]: Launching chrome: /usr/bin/chromium --allow-pre-commit-input --disable-background-mode --disable-background-networking --disable-background-timer-throttling --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-translate --disable-web-security --enable-automation --enable-logging --headless --ignore-certificate-errors --log-level=0 --metrics-recording-only --no-default-browser-check --no-first-run --no-sandbox --no-service-autorun --password-store=basic --remote-allow-origins=* --remote-debugging-port=0 --safebrowsing-disable-auto-update --test-type=webdriver --use-mock-keychain --user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0 --user-data-dir=/tmp/.org.chromium.Chromium.7thYIW --window-size=1920,1080 data:,

but after a while the SessionNotCreatedException gets logged, the chromedriver process dies and I'm left with dangling chromium processes.

These failures seem to happen pretty random and only occasionally, as my app manages to successfully start chromedriver + chromimum instances most of the time.

**Comment by diemol** [comment] 2024-09-17 08:25
We are closing this issue as we didn't get a reply from the original poster. 

If someone is facing this issue, feel free to comment and provide a [concise reproducible test case](http://sscce.org/) that includes the page required to execute the scenario (a sample page or a public site).

If you have any questions or need help, join us in the [IRC/Slack channel](https://www.selenium.dev/support/), where the community can also assist you.

**Closed as not planned by diemol** 2024-09-17 08:25 UTC
Labels: I-defect, J-issue-template
