### ISSUE TITLE
[🐛 Bug]: unknown error: cannot determine loading status from no such window 

### ISSUE THREAD

**Issue by shemeshx** [SeleniumHQ/selenium#12387] opened 2023-07-20 10:04 UTC
### What happened?

This exception occurs when the web app perform sign-out. The sign-out operation changes the URL to different url that cleans the authentication cache and then goes to different route from the original URL. Then we receive the exception "unknown error: cannot determine loading status from no such window". I assume that moving between different routes cause this exception.

### How can we reproduce the issue?

```shell
Cannot provide you any code unfortunately.
```

### Relevant log output

```shell
unknown error: cannot determine loading status from no such window (Session info: chrome=113.0.5672.63)
at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.WebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
at OpenQA.Selenium.WebDriver.ExecuteScript(String script, Object[] args)
at SeleniumLayer.Extension.IWebElementExtension.Click2(IWebElement element)
```

### Operating System

Linux (GRID) 3.10.0-1160.92.1.el7.x86_64

### Selenium version

4.10.0 

### What are the browser(s) and version(s) where you see this issue?

Chrome 113.0.5672.63 and 114 

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 108.0.5359.71

### Are you using Selenium Grid?

4.10.0 (revision c14d967899)

**Comment by titusfortner** [comment] 2023-07-20 10:57
Duplicate of #12277 and nothing we can do without a way to reproduce it or debug into the problem. We need more info.

**Closed as completed by titusfortner** 2023-07-20 10:57 UTC
Labels: I-defect, J-issue-template
