### ISSUE TITLE
UnhandledAlertException.getAlertText() does not return the alert text

### ISSUE THREAD

**Issue by rcesarlumis** [SeleniumHQ/selenium#9477] opened 2021-05-13 22:20 UTC
## 🐛 Bug Report

Using RemoteWebDriver, the UnhandledAlertException.getAlertText() always returns an empty String.

## Test script or set of commands reproducing this issue

```
driver.navigate().to("https://www.google.com.br");
((JavascriptExecutor) driver).executeScript("alert('sometext')");
try {
	driver.findElement(By.tagName("body"));
	Assert.fail();
}
catch (UnhandledAlertException e) {
	assertEquals("sometext", e.getAlertText());   // e.getAlertText() returns empty string here
}
```

## Environment

Browser:  from docker image selenium/standalone-firefox:4.0.0-beta-3-20210426
Browser Driver version: RemoteWebDriver from selenium-java 4.0.0-beta3
Language Bindings version: Java 4.0.0-beta3

**Comment by pujagani** [comment] 2021-05-31 12:13
Thank you for providing the example. I was able to reproduce the issue. However, the issue only exists when tests are run with the Geckodriver. This is due to the reason that the GeckoDriver responds with the following message :

`"500 Internal Server Error {"value":{"error":"unexpected alert open","message":"Dismissed user prompt dialog: sometext","stacktrace":"WebDriverError@chrome://marionette/content/error.js:181:5\nUnexpectedAlertOpenError@chrome://marionette/content/error.js:466:5\nGeckoDriver.prototype._handleUserPrompts@chrome://marionette/content/driver.js:3501:13\n"}}"`

As per the [WebDriver specification](https://www.w3.org/TR/webdriver/#errors), additional data can be optionally provided via the "data" field in the response. This `data` field is used to populate the value obtained from "getAlertText()" in the UnhandledAlertException class. The `data` field is optional so that up to the web driver implementation.

The same issue does not persist with the Chromium-based web drivers since they populate the `data` field.

Closing the issue, since the Selenium code is following the spec correctly.

**Closed as completed by pujagani** 2021-05-31 12:13 UTC
Labels: C-java, D-firefox
