### ISSUE TITLE
[🐛 Bug]: Getting error code: "65: Wrong browser/driver version" while triggering the chromedriver in C# N-unit project

### ISSUE THREAD

**Issue by marupudit** [SeleniumHQ/selenium#14119] opened 2024-06-11 13:35 UTC
### What happened?

I have updated the selenium dependancies to latest version:
Selenium.Webdriver: 4.21.0
Selenium.Support: 4.21.0

and using the chrome Version 125.0.6422.142 (Official Build) (64-bit)

When I execute the tests in this project(C# Nunit Selenium Test solution), getting this error:

Message: 
OpenQA.Selenium.NoSuchDriverException : Unable to obtain chrome using Selenium Manager; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
  ----> OpenQA.Selenium.WebDriverException : Error starting process: 
\bin\Debug\net7.0-windows\selenium-manager/windows/selenium-manager.exe  --browser "chrome" --output json
  ----> OpenQA.Selenium.WebDriverException : Selenium Manager process exited abnormally with 65 code: 
\bin\Debug\net7.0-windows\selenium-manager/windows/selenium-manager.exe  --browser "chrome" --output json
{
  "logs": [
    {
      "level": "ERROR",
      "timestamp": 1718105504,
      "message": "Wrong browser/driver version"
    }
  ],
  "result": {
    "code": 65,
    "message": "Wrong browser/driver version",
    "driver_path": "",
    "browser_path": ""
  }
}

TearDown : OpenQA.Selenium.NoSuchDriverException : Unable to obtain chrome using Selenium Manager; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
  ----> OpenQA.Selenium.WebDriverException : Error starting process: 
\bin\Debug\net7.0-windows\selenium-manager/windows/selenium-manager.exe  --browser "chrome" --output json
  ----> OpenQA.Selenium.WebDriverException : Selenium Manager process exited abnormally with 65 code: 
\bin\Debug\net7.0-windows\selenium-manager/windows/selenium-manager.exe  --browser "chrome" --output json
{
  "logs": [
    {
      "level": "ERROR",
      "timestamp": 1718105505,
      "message": "Wrong browser/driver version"
    }
  ],
  "result": {
    "code": 65,
    "message": "Wrong browser/driver version",
    "driver_path": "",
    "browser_path": ""
  }
}

### How can we reproduce the issue?

```shell
Tried to run the command via CMD:
PS \bin\Debug\net7.0-windows\selenium-manager/windows/selenium-manager.exe  --browser "chrome" --output json                                                                                   {
  "logs": [
    {
      "level": "ERROR",
      "timestamp": 1718112097,
      "message": "Wrong browser/driver version"
    }
  ],
  "result": {
    "code": 65,
    "message": "Wrong browser/driver version",
    "driver_path": "",
    "browser_path": ""
  }
}
```

### Relevant log output

```shell
Tried to run the command via CMD:
PS \bin\Debug\net7.0-windows\selenium-manager/windows/selenium-manager.exe  --browser "chrome" --output json                                                                                   {
  "logs": [
    {
      "level": "ERROR",
      "timestamp": 1718112097,
      "message": "Wrong browser/driver version"
    }
  ],
  "result": {
    "code": 65,
    "message": "Wrong browser/driver version",
    "driver_path": "",
    "browser_path": ""
  }
}
```

### Operating System

Windows 10

### Selenium version

4.21.0

### What are the browser(s) and version(s) where you see this issue?

chrome Version 125.0.6422.142

### What are the browser driver(s) and version(s) where you see this issue?

chrome Version 125.0.6422.142

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment] 2024-06-11 15:55
I think this is duplicate of #14093 
If not, we'll need to see logs at FINE/DEBUG level to differentiate

**Closed as not planned by titusfortner** 2024-06-11 15:55 UTC
Labels: I-defect, A-needs-triaging
