### ISSUE TITLE
Switch to frame failed in safari browser on MAC

### ISSUE THREAD

**Issue by sasank1985** [SeleniumHQ/selenium#4397] opened 2017-08-01 11:39 UTC
OS:  
OSX
Selenium Version:  
V 3.4.0
Browser:  
Safari

#7586

Browser Version:  
10.1.1

## Steps to reproduce -
driver.switchTo().frame(String Frame);

**Comment by p0deje** [comment] 2017-08-01 14:21
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by sasank1985** [comment] 2017-08-02 06:30
![failed to switch to module level frames in safari on mac sierra](https://user-images.githubusercontent.com/22906393/28860400-13a0b1ec-777a-11e7-8d23-dd41912b6871.jpg)

**Comment by sasank1985** [comment] 2017-08-02 06:46
@p0deje Hope the above screen shot helps.

In safari browser on  MAC Sierra.
1.We have 2 <iframe> tags from default content which are switched successfully 
  <iframe id="fraContent" name="fraContent">
  This contains the document in it.
2. In that we have the second iframe
   <iframe id="fraLayoutContent" name="fraLayoutContent">
   This contains the document in it and this iframe can be noticed in attached screenshot also.
3. In the document within this we have a frameset under <head> tag.
   <frameset>id="PatRegFrames">
      <frame id="framPatRegTitle" name="framPatRegTitle">
      <frame id="framPatRegToolBarFrame" name="framPatRegToolBarFrame">
     <frame id="framPatRegWebUITabControl" name="framPatRegWebUITabControl">
     <frame id="framPatRegWebUIFrame" name="framPatRegWebUIFrame">


I need to navigate to the last frame in the frame set i.e., framPatRegWebUIFrame.
After successful navigation of iframe <iframe id="fraContent"> and <iframe id="fraLayoutContent"> it is failing to switch to frame in the  frame set.

Hope this is clear for you.
Let me know if anything else is required.

**Comment by p0deje** [comment] 2017-08-02 08:42
Sorry, but this is not enough. Please, provide a piece of code which I can run on my machine to reproduce the issue. This code would import necessary packages, start the browser, navigate to the page and switch to the correct iframe.

I'm not Java bindings maintainer, so it's not that easy for me to reconstruct the code you'd use.

**Comment by sasank1985** [comment] 2017-08-02 10:08
I can't share the application URL publicly . Its restricted.


But here is the code i am using which may  help you to understand.


//Imports

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.safari.SafariDriver;
import org.openqa.selenium.safari.SafariOptions;


//Code to invoke browser

SafariOptions options = new SafariOptions();
options.setUseCleanSession(true); 
driver = new SafariDriver(options); 
Threa.sleep(2000);

//Access in application
driver.get("Pass URL");

If you have login screen

driver.findElement(By.ID("Login")).sendKeys("Login Value");
driver.findElement(By.ID("Password")).sendKeys("Password Value");

//Selection of module differs from application to application, 

//Swithching to frames
  g_wdBrowserDriver.switchTo().defaultContent();

//Swithching between our application static frames

  driver.switchTo().frame(driver.findElement(By.xpath("//*[@id='fraContent']")));
  driver.switchTo().frame(driver.findElement(By.xpath("//*[@id='fraLayoutContent']")));

//Switching to module frame in the frameset in my case
  g_wdBrowserDriver.switchTo().frame("fraPWebUIFrame");

**Comment by p0deje** [comment] 2017-08-03 06:56
I cannot reproduce this issue.

Please provide:

1. Exact HTML code (since it's private you'll need to extract it from you application).
2. Exact code you use to.
3. Full log of the error.

**Comment by sasank1985** [comment] 2017-08-03 07:11
![failed to switch to module level frames in safari on mac sierra 2](https://user-images.githubusercontent.com/22906393/28910136-1b35c936-7849-11e7-80ca-0406ead4504b.jpg)

**Comment by p0deje** [comment] 2017-08-03 07:13
I'm sorry but how screenshot is what I've asked for?

**Comment by sasank1985** [comment] 2017-08-03 07:31
![image](https://user-images.githubusercontent.com/22906393/28910783-dd617936-784b-11e7-829b-08fc6054fb7b.png)

**Comment by sasank1985** [comment] 2017-08-03 07:32
This was the exception what i am getting...

**Comment by sasank1985** [comment] 2017-08-03 07:40
[HTML Code.txt](https://github.com/SeleniumHQ/selenium/files/1196358/HTML.Code.txt)

**Comment by sasank1985** [comment] 2017-08-03 07:42
Added HTML Code for you which i believe is not suggestible to ask or to post.  Fine for this time. Please check it out.

**Comment by barancev** [comment] 2017-08-03 07:45
1) Use https://jsbin.com/ or a similar service to create sample pages.
2) Provide a concise reproducible test case against these sample pages so that we can reproduce the issue.
3) Provide the complete stack trace of the failure.

**Comment by p0deje** [comment] 2017-08-03 08:01
> Added HTML Code for you which i believe is not suggestible to ask or to post. Fine for this time. Please check it out.

How are we supposed to fix the issue if we can't reproduce? The HTML code you provided cannot be opened in browser so you'll need to extract some part of it that can be used for debugging.

**Comment by sasank1985** [comment] 2017-08-08 12:49
Tried to create sample page to replicate the issue as suggested by @barancev  but not succeeded...
The core is while navigating to the frame within a frameset. like below. Please suggest on it.

<frameset>id="PFrames">
<frame id="fraPTitle" name="fraPTitle">
<frame id="fraPToolBarFrame" name="fraPToolBarFrame">
<frame id="fraPWebUITabControl" name="fraPWebUITabControl">
<frame id="fraPWebUIFrame" name="fraPWebUIFrame">

**Comment by tbc-ats** [comment] 2017-08-13 09:21
I am also getting similar issue in switching frame with webelement. However my issue is coming at compile time. "The method frame(String) is ambitious for the type WebDriver.TargetLocator"... My code is as below.


SDriver.switchTo().defaultContent();
SDriver.switchTo().frame(sDriver.findElement(By.id("frameDialog")));

**Comment by barancev** [comment] 2017-09-05 05:46
@tbc-ats What Java compiled do you use? Take a look at #4447

**Comment by barancev** [comment] 2017-09-05 05:50
Closing the issue as there is no reproduction case provided.
@sasank1985, feel free to reopen it as soon as you get one.

**Closed by barancev** 2017-09-05 05:50 UTC
Labels: C-java, D-safari, R-awaiting answer
