### ISSUE TITLE
[🐛 Bug]: Virus detected with 4.21.0 windows selenium_manager.exe

### ISSUE THREAD

**Issue by Lukenickerson** [SeleniumHQ/selenium#14008] opened 2024-05-21 15:11 UTC
### What happened?

I installed the latest v4.21.0 version of Selenium-webdriver into a new node repo, and attempted to run a jest test that starts up a selenium driver browser (Chrome). The browser never started, and I received the error "Unable to obtain browser driver." at the command line. Meanwhile my virus detection (FortiClient) detected a virus and prevented the `windows/selenium-manager.exe` file from running.

Virus info: https://www.fortiguard.com/encyclopedia/virus/8233130

If I revert back to 4.20.0, there are no issues, and selenium web driver works as expected: browser opens, tests are run, etc.

### How can we reproduce the issue?

1. Have FortiClient installed and running
1. Install v20.5.0 of Node js
1. `npm init`
1. `npm i selenium-webdriver` -- and make sure you have 4.21.0 installed
1. Run a js file that does something like...

```js
import { Builder } from 'selenium-webdriver';
const driver = new Builder().forBrowser('chrome').build();
```

### Relevant log output

```shell
Process: C:\Programs\nvm\v20.5.0\node.exe
Item: ...\node_modules\selenium-webdriver\bin\windows\selenium-manager.exe
Virus: Malicious_Behavior.SB//167591167
Status: Quarantined
```

### Operating System

Windows 10

### Selenium version

selenium-webdriver 4.21.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

No

**Comment by diemol** [comment] 2024-05-21 15:25
This is a duplicate of #12935 

This happens whenever we update dependencies.

**Closed as not planned by diemol** 2024-05-21 15:25 UTC
Labels: I-defect, A-needs-triaging
