### ISSUE TITLE
[🐛 Bug]: Hanging SelectorManager Threads after the request has been processed on selenium grid and the driver is given the quit command.

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#12206] opened 2023-06-15 08:35 UTC
### What happened?

On rendering a url on selenium grid, even after a session is closed and completed, the Selector manager threads in case of jdk http client and in case of default http client, AsycHttpClient threads are hanging even long after the session is closed on the grid. 
<img width="1721" alt="Screenshot 2023-06-15 at 1 56 41 PM" src="https://github.com/SeleniumHQ/selenium/assets/104977653/04e48f35-bdd3-4f7b-b83e-e03167d55999">

### How can we reproduce the issue?

```shell
public Optional<WebData> runSelenium(String domain) {
    var capabilities = Optional.of(new ChromeOptions())
        .map(options -> options.addArguments(List.of("--headless=new",
            "--disable-application-cache",
            "--disable-features=IsolateOrigins,site-per-process",
            "--no-sandbox",
            "--disable-dev-shm-usage",
            "--disable-web-security",
            "--disable-blink-features=AutomationControlled",
            "--disable-site-isolation-trials",
            "--remote-allow-origins=*",
            "--disable-popup-blocking"
        )))
        .map(options -> options.addArguments("--user,agent="
            + "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0"
            + ".3945.117 Safari/537.36"))
        .map(options -> (ChromeOptions) options.setPageLoadStrategy(PageLoadStrategy.fromString("normal")))
        .map(options -> (ChromeOptions) options.setPageLoadTimeout(Duration.ofSeconds(60)))
        .map(options -> (ChromeOptions) options.setUnhandledPromptBehaviour(UnexpectedAlertBehaviour.DISMISS))
        .get();
    var url = new URL("http://localhost:4444/wd/hub");
    var driver = new RemoteWebDriver(url, capabilities, false);

    try {

      driver.switchTo().newWindow(WindowType.WINDOW);
      driver.get("http://" + "google.com");
      driver.close();

      driver.switchTo().newWindow(WindowType.WINDOW);
      driver.get("http://" + "phonepe.com");
      driver.close();
    } catch (Exception e) {

    }


    return Optional.empty();
  }
```

### Relevant log output

```shell
.
```

### Operating System

macOs, Debian GNU/Linux 10

### Selenium version

Java 17

### What are the browser(s) and version(s) where you see this issue?

Chrome 113

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver-113.0-grid-4.9.1-20230508

### Are you using Selenium Grid?

4.9.1-20230508

**Comment by diemol** [comment] 2023-06-15 12:38
This is a duplicate of #11826 
We are having a look soon.

**Closed as completed by diemol** 2023-06-15 12:38 UTC
Labels: I-defect
