### ISSUE TITLE
InvalidArgument # new Actions(driver).moveToElement(element).click().perform() not working with 3.4.0 FF 53.0.2

### ISSUE THREAD

**Issue by vlakkara** [SeleniumHQ/selenium#4049] opened 2017-05-19 18:01 UTC
Specs:
Firefox: 53.0.2 (64 bit windows
Geckodriver 0.16.1  windows 64 bit
Selenium:3.4.0
OS: Windows 10 Enterprise
I am getting org.openqa.selenium.InvalidArgumentException: exception (InvalidArgument)
new Actions(driver).moveToElement(element).click().perform();  is not working but i did work around 
element.click() is working

**Comment by AutomatedTester** [comment] 2017-05-22 14:06
duplicate of #3808

**Closed by AutomatedTester** 2017-05-22 14:06 UTC
