### ISSUE TITLE
Actions KeyDown/KeyUp not supporting all modifier keys

### ISSUE THREAD

**Issue by jvleeuwe** [SeleniumHQ/selenium#3750] opened 2017-04-03 12:28 UTC
## Meta -
OS:  
Windows 7/8/10
Selenium Version:  
DotNet Webdriver 3.3.0.0
Browser:  
Safari
Browser Version:  
10

## Expected Behavior -
I can use any modifier key in "Actions" methods like "KeyDown/KeyUp"
## Actual Behavior -
Only Keys.Shift, Keys.Control, Keys.Alt are supported (See SingleKeyAction.cs)
## Steps to reproduce -
new Actions(Driver).KeyDown(Keys.Command).Perform();

The Java WebDriver implementation has this fixed in "SingleKeyAction.java" since march 2014.
See: https://github.com/SeleniumHQ/selenium/commit/9b57e72b4a75349b0c52b9010be79c2fa68bebee#diff-b99bb200e128addef65be0b35a8c8612

**Comment by prakashfrancis** [comment] 2017-04-05 07:07
I am facing the same issue only with firefox3.3.1 and GeckoDriver v0.15.0

I use Actions & Key events for Keyboard shortcuts like undo/redo/delete

           actions.keyDown(command).sendKeys("z").keyUp(command).perform();

It works fine in Chrome but not in firefox.

**Comment by lmtierney** [comment] 2017-04-05 12:28
@prakashfrancis you are experiencing this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1332279

**Comment by prakashfrancis** [comment] 2017-04-05 17:18
Yes @lmtierney .,

It will be fixed in firefox 55

Thanks

**Comment by lmtierney** [comment] 2017-04-05 18:04
@prakashfrancis Right now that's the target, but it could get uplifted to 53

**Comment by prakashfrancis** [comment] 2017-04-06 05:31
Thats Awesome!

Thanks

**Comment by jvleeuwe** [comment] 2017-10-11 05:48
Will this be fixed anytime soon?
Our tests on safari finally begin to work so this is becomming a real issue now.

**Comment by jvleeuwe** [comment] 2017-10-11 07:58
It is about the following fragment in 
    internal class SingleKeyAction : KeyboardAction
    {
        private static readonly List<string> ModifierKeys = new List<string>() { Keys.Shift, Keys.Control, Keys.Alt };


The "ModifierKeys" list should be extended to also support the Apple keyboard modifier keys like "Command"

**Comment by mykyta-bondarenko-gl** [comment] 2018-02-14 09:54
Hi!
Will this be fixed anytime soon?
It's a very big problem for me because of I am working on tests for macOS applications so I really need work with the "Command" button.

**Comment by lmtierney** [comment] 2018-02-14 14:18
This is an issue with individual vendor webdrivers, please raise an issue with the respective vendor.

**Closed by lmtierney** 2018-02-14 14:18 UTC
Labels: C-dotnet

**Comment by lmtierney** [comment] 2018-02-15 13:33
@mykyta-bondarenko-gl if this is an issue with bindings please raise another issue with a reproducable scenario. As this original issue is state, it is an issue with individual vendor drivers.

**Comment by mykyta-bondarenko-gl** [comment] 2018-02-15 15:59
Thanks, I've created a new one
https://github.com/SeleniumHQ/selenium/issues/5500
