### ISSUE TITLE
safaridriver on Safari 13.0.5 does not find an element

### ISSUE THREAD

**Issue by TatyanaMartynyuk** [SeleniumHQ/selenium#7993] opened 2020-02-03 19:04 UTC
## 🐛 Bug Report
I've been successfully  running e2e (end to end) WEB UI tests on Firefox and Chrome. 
Then I decided to try them on Safari, but encountered an issue.
Safaridriver opens Safari and goes to a url. But then it stops and times out after awhile.
It is supposed to 
_await driver.findElement(By.xpath(locator)).click();_ 
But I feel it finds an element but either does not click it or clicks somewhere else.

First I thought it had some problems with OS and upgraded to the latest one, but it did not help...

Any help/advice will be appreciated! 

## Environment
OS: macOS Catalina Version 10.15.3
Browser: Safari
Browser version: Version 13.0.5 (15608.5.11)
Browser Driver version: safaridriver (the default one)
Language Bindings version: Node.js

**Comment by bluemoon711** [comment] 2020-02-03 19:37
Same here. After updating Safari to 13.0.4(15608.4.9.1.3), all my tests were broken. Those tests ran well on chrome/firefox browser. The error showed  'Driver info: driver.version: unknown'. I re enabled the safari webdriver after updating, but nothing helped.

**Comment by gwpetersenag** [comment] 2020-02-04 02:13
I can also confirm I'm seeing this issue. 
Browser version: Version 13.0.5 (15608.5.11)
macOS Mojave 10.14.6

**Comment by bluemoon711** [comment] 2020-02-13 00:03
After updating the os to 10.15.3, safari is back to work normally. Now the version of safari is 13.0.5.

**Comment by TatyanaMartynyuk** [comment] 2020-02-14 18:46
> After updating the os to 10.15.3, safari is back to work normally. Now the version of safari is 13.0.5.

Nice!
I've tried again but it is still failing... Are you using it with Node.js? Can you please paste few lines of code where Safari finds element and clicks on and safari options if you use any?
Thanks!

**Comment by kharchenkoS** [comment] 2020-02-27 10:12
have the same issue with os 10.15.3, driver 13.0.5  ===>  use Node.Js (webdriver.io)

**Comment by AutomatedTester** [comment] 2020-03-06 12:19
@burg I feel like I have seen you say this was fixed. Am I remembering correctly?

**Comment by barancev** [comment] 2020-03-09 20:21
Someone please provide an SSCCE (http://sscce.org/) otherwise the issue will be closed.

**Comment by TatyanaMartynyuk** [comment] 2020-03-09 21:54
@barancev 
When I run the following code, Safari is being opened but no button is getting clicked. (note, when I change it to chrome, everything works as expected).
```
const seleniumWebdriver = require('selenium-webdriver');
const { By, until } = require('selenium-webdriver');
const safari = require('selenium-webdriver/safari');

const safariOptions = new safari.Options();
const driver = new seleniumWebdriver.Builder().setSafariOptions(safariOptions).build();

const mocha = require('mocha');
const describe = mocha.describe;
const it = mocha.it;

describe('Sign Up button test', () => {
    it('Open github  and click on Sign up, async () => {
      await driver.get('https://github.com');
      await driver.wait(until.elementLocated(By.css("button[type='submit']")), 10 * 1000).isDisplayed();
      await driver.findElement(By.css("button[type='submit']")).click();
   }
} 

```

A snippet from package.json:
```
"devDependencies": {
   ...
   "mocha": "^6.1.4",
   "selenium-webdriver": "latest",
   "chromedriver": "2.42.0",
   ...
}
```

Also:
```
safaridriver --version
Included with Safari 13.0.5 (15608.5.11)
```

**Comment by barancev** [comment] 2020-03-09 21:59
So the title of the report is incorrect. and it's actually a duplicate of #7649

**Closed by barancev** 2020-03-09 21:59 UTC
Labels: D-safari, R-awaiting answer

**Comment by TatyanaMartynyuk** [comment] 2020-03-11 17:46
@barancev thank you for pointing me to #7649.
I managed to click on a button with 
`driver.executeScript('arguments[0].click()', button)`
