### ISSUE TITLE
Double Click not working in Firefox latest versions(48 to 55)

### ISSUE THREAD

**Issue by Anbuchozhan** [SeleniumHQ/selenium#4784] opened 2017-09-29 11:03 UTC
Issue with Mouse Actions event - Double Click 

Browser - Firefox 48 & above Upto Latest version

Driver - gecko Driver

Double Click is not working in Firefox & i tried with even java script there is no solution for double click action in firefox browser. The same script which i developed is working fine in Internet Explorer but with fire fox those scripts get failed due to not triggering the Double click event. Please any one provide the solution or suggestions for this issue.

**Comment by barancev** [comment] 2017-09-29 11:16
Duplicate of https://github.com/mozilla/geckodriver/issues/661

**Closed by barancev** 2017-09-29 11:16 UTC
