### ISSUE TITLE
Object reference not set to an instance of an object.    at OpenQA.Selenium.Interactions.Actions.Perform() 

### ISSUE THREAD

**Issue by Festivejelly** [SeleniumHQ/selenium#4997] opened 2017-11-02 11:11 UTC
## Meta -
OS:  
Windows 10
Selenium Version:  
3.6
Browser:  
Chrome

Browser Version:  
Version 62.0.3202.75 (Official Build) (64-bit)

## Expected Behavior -
When performing an Action i'd expect it to work

## Actual Behavior -
Throws an error:System.NullReferenceException : Object reference not set to an instance of an object.
   at OpenQA.Selenium.Interactions.Actions.Perform() when .Perform is called

## Steps to reproduce -
Using C# bindings create a simple test

            var actions = new Actions(browser);
            actions.MoveToElement(element).Build();
            actions.Perform();

## Notes -

I can get this to work with 3.6 at all.

**Comment by matijalucman** [comment] 2017-11-02 13:34
You have built sequence and than called method `Perform()` which builds sequence again.

Try to build sequence of actions on this way:
```
Actions actions = new Actions(browser);
actions.MoveToElement(element);
Action moveToElement = actions.Build();
moveToElement.Perform();
```
Besides that I recommend you to read this [wiki](https://github.com/SeleniumHQ/selenium/wiki/Advanced-User-Interactions).

**Comment by Festivejelly** [comment] 2017-11-02 15:44
Thats odd it works fine on 3.0.1 i'll try your suggestion.

**Comment by Festivejelly** [comment] 2017-11-02 15:47
the above you quoted wont compile

**Comment by Festivejelly** [comment] 2017-11-02 15:47
btw im using C#

**Comment by matijalucman** [comment] 2017-11-02 19:59
You are right, I made a mistake because I was not able to test the code, this should work:
```
Actions actions = new Actions(driver);
actions.MoveToElement(element);
IAction moveToElement = actions.Build();
moveToElement.Perform();
```
I have also tested your code and I can not reproduce the error.

**Comment by barancev** [comment] 2017-11-08 14:35
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment] 2017-12-02 20:14
Closing the issue, there is no reproduction scenario provided.

**Closed by barancev** 2017-12-02 20:14 UTC
Labels: C-dotnet, R-awaiting answer
