### ISSUE TITLE
Selenium in IPython: Process unexpectedly closed with status 11

### ISSUE THREAD

**Issue by huytrvan** [SeleniumHQ/selenium#8851] opened 2020-11-07 08:57 UTC
## 🐛 Bug Report
I try to run a simple code to open firefox browser in IPython but it gives me the following:

For Gecko 0.28.0 (latest):
```
WebDriverException: Message: Process unexpectedly closed with status 11
```
For Gecko 0.27.0:
```
WebDriverException: Message: invalid argument: can't kill an exited process
```
**Note:** The script works in when run in terminal but not IPython
## To Reproduce

Detailed steps to reproduce the behavior:
* Install official Python extension in VSCode
* Download latest `geckodriver` (0.28.0)
* Run `python3 -m venv .venv`
* Install `Selenium` and `IPython` and `Jupyter Notebook`
* Run this code:
```
# %%
from selenium import webdriver

driver = webdriver.Firefox(
    executable_path='.driver/geckodriver')
```

## Expected behavior
Create new Selenium Firefox instance.

## Test script or set of commands reproducing this issue
```
# %%
from selenium import webdriver

driver = webdriver.Firefox(
    executable_path='.driver/geckodriver')
```
## Environment

OS: Ubuntu 20.10
Browser: Firefox
Browser version:  82.0
Browser Driver version: GeckoDriver 0.28.0
Language Bindings version: Python 3.8.6
Selenium Grid version: 3.141.0
IPython version: 7.19.0

**Comment by AutomatedTester** [comment] 2020-11-10 20:12
Duplicate of #8855

**Closed as completed by AutomatedTester** 2020-11-10 20:12 UTC
Labels: C-py
