### ISSUE TITLE
Drap and Drop is not working within different frames

### ISSUE THREAD

**Issue by vamshikurra** [SeleniumHQ/selenium#945] opened 2015-08-19 19:45 UTC
I am trying to drag an element from one frame and drop it into another frame. But it is not working. I tried in two different ways . 
In one way script failed  and in another way script passed but there is no draganddrop action happened.

Below code failed with error as "org.openqa.selenium.StaleElementReferenceException: Element belongs to a different frame than the current one - switch to its containing frame to use it"

  ```java
WebDriver driver = new FirefoxDriver();
			driver.get("http://www.ankur.com/projects/FrameGlider/demo/complex/a.html");
			//Goto Frame C and locate Dra9 checkbox
			driver.switchTo().frame("win2_content");
			WebElement dragFrom = driver.findElement(By.id("Dra9"));
			System.out.println("dragFrom text is : "+dragFrom.getText());
			driver.switchTo().defaultContent();
			//Goto Top Frame B
			driver.switchTo().frame("win1_content");	
			//Goto Frame D which is inside frame B and locate Dro3 checkbox
			driver.switchTo().frame("win1_content");
			WebElement dropTo =driver.findElement(By.id("Dro3"));
			System.out.println("dragFrom text is : "+dropTo.getText());
			driver.switchTo().defaultContent();
			//Try to move Dra9 element to Dro3
			Actions builder = new Actions(driver);  // Configure the Action
			Action dragAndDrop = builder.clickAndHold(dragFrom)
					.moveToElement(dropTo)
					.release(dropTo)
					.build();  // Get the action
			dragAndDrop.perform(); // Execute the Action
```

Below code passed but drag and drop action not happened on the page.

```java
WebDriver driver = new FirefoxDriver();
driver.get("http://www.ankur.com/projects/FrameGlider/demo/complex/a.html");
//Goto Frame C and locate Dra9 checkbox
driver.switchTo().frame("win2_content");
WebElement dragFrom = driver.findElement(By.id("Dra9"));
System.out.println("dragFrom text is : "+dragFrom.getText());
driver.switchTo().defaultContent();

//Goto Top Frame B
driver.switchTo().frame("win1_content");
//Goto Frame D which is inside frame B and locate Dro3 checkbox
driver.switchTo().frame("win1_content");
WebElement dropTo =driver.findElement(By.id("Dro3"));
System.out.println("dragFrom text is : "+dropTo.getText());
driver.switchTo().defaultContent();
//Try to move Dra9 element to Dro3
Actions builder = new Actions(driver);
Actions action = builder.clickAndHold(dragFrom);
builder.build();
action.perform();
// move and drop
builder.moveToElement(dropTo);
builder.release();
builder.click(dropTo);
builder.build();
action.perform();
```

**Comment by lukeis** [comment] 2015-08-19 19:53
duplicate of #810

**Closed by lukeis** 2015-08-19 19:53 UTC

**Comment by vamshikurra** [comment] 2015-08-19 20:06
thanks thanks thanks for quick response. You saved my time .
