### ISSUE TITLE
[🐛 Bug]: SocketException when webDriver.close()

### ISSUE THREAD

**Issue by hexw** [SeleniumHQ/selenium#13524] opened 2024-01-30 00:33 UTC
### What happened?

org.openqa.selenium.remote.http.WebSocket$Listener onError
警告: Connection reset
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at java.net.http/jdk.internal.net.http.SocketTube.readAvailable(SocketTube.java:1170)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:833)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:181)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:303)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:256)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:774)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:957)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:253)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:979)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:934)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:934)

### How can we reproduce the issue?

```shell
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

public class SeleniumTest2 {
	public static void main(String[] args) {
		       System.getProperties().setProperty("webdriver.chrome.driver", "E:\\tmp\\chromedriver\\win64\\121.0.6167.85\\chromedriver.exe");
		       // 设置浏览器参数
				ChromeOptions options = new ChromeOptions();
				options.addArguments("--no-sandbox");// 禁用沙箱
				options.addArguments("--disable-dev-shm-usage");// 禁用开发者shm
				options.addArguments("--headless"); // 无头浏览器，这样不会打开浏览器窗口
				
				WebDriver webDriver = new ChromeDriver(options);
				webDriver.get("https://www.baidu.com/");
				String source = webDriver.getPageSource();
				webDriver.close();
	}
}
```

### Relevant log output

```shell
org.openqa.selenium.remote.http.WebSocket$Listener onError
警告: Connection reset
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at java.net.http/jdk.internal.net.http.SocketTube.readAvailable(SocketTube.java:1170)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:833)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:181)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:303)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:256)
```

### Operating System

windows 11

### Selenium version

JDK 17

### What are the browser(s) and version(s) where you see this issue?

Chrome  121.0.6167.86

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Driver  121.0.6167.85

### Are you using Selenium Grid?

selenium-java 4.17.0

**Comment by riagrawal-1208** [comment] 2024-02-02 09:12
Getting the same issue with Edge using JDK 11 Windows 11 and selenium-java 4.16.1

**Comment by diemol** [comment] 2024-02-02 09:27
What happens if you let Selenium manage the browser driver? (Remove the line `ystem.getProperties().setProperty("webdriver.chrome.driver", "E:\\tmp\\chromedriver\\win64\\121.0.6167.85\\chromedriver.exe");`)

What happens if you try a different website?

**Comment by hexw** [comment] 2024-02-04 08:51
> What happens if you let Selenium manage the browser driver? (Remove the line `ystem.getProperties().setProperty("webdriver.chrome.driver", "E:\\tmp\\chromedriver\\win64\\121.0.6167.85\\chromedriver.exe");`)
> 
> What happens if you try a different website?

 different website https://stackoverflow.com/  same java.net.SocketException: Connection reset

**Comment by hexw** [comment] 2024-02-04 08:56
> What happens if you let Selenium manage the browser driver? (Remove the line `ystem.getProperties().setProperty("webdriver.chrome.driver", "E:\\tmp\\chromedriver\\win64\\121.0.6167.85\\chromedriver.exe");`)
> 
> What happens if you try a different website?
use  Selenium manage the browser driver same  java.net.SocketException: Connection reset

**Comment by diemol** [comment] 2024-02-05 09:50
I cannot reproduce the issue with the code you are providing. Also, why are you not using `webDriver.quit();`?

Can you please provide a GitHub repository I can clone and reproduce the issue?

**Comment by titusfortner** [comment] 2024-02-05 17:14
Do you get this behavior if you use `--headless=new`?

**Comment by diemol** [comment] 2024-02-28 17:25
I will close this for now, as we have not gotten any updates. I can reopen as soon as more information is provided.

**Closed as not planned by diemol** 2024-02-28 17:25 UTC
Labels: J-awaiting answer, C-java, I-defect
