### ISSUE TITLE
System.Net.WebSockets.WebSocketException [🐛 Bug]: 

### ISSUE THREAD

**Issue by mehranahmadifar** [SeleniumHQ/selenium#10101] opened 2021-11-29 15:43 UTC
### What happened?

when i am using  networkInterceptor.StartMonitoring() this error was thrown:

System.InvalidOperationException: 'There is already one outstanding 'SendAsync' call for this WebSocket instance. ReceiveAsync and SendAsync can be called simultaneously, but at most one outstanding operation for each of them is allowed at the same time.'

### How can we reproduce the issue?

```shell
var handler = new NetworkAuthenticationHandler()
                {
                    UriMatcher = d => true, //d.Host.Contains("google.com"),
                    Credentials = new PasswordCredentials("test", "test")
                };

                var networkInterceptor = driver.Manage().Network;
                networkInterceptor.AddAuthenticationHandler(handler);

                networkInterceptor.StartMonitoring();
```

### Relevant log output

```shell
System.InvalidOperationException
  HResult=0x80131509
  Message=There is already one outstanding 'SendAsync' call for this WebSocket instance. ReceiveAsync and SendAsync can be called simultaneously, but at most one outstanding operation for each of them is allowed at the same time.
  Source=System
  StackTrace:
   at System.Net.WebSockets.WebSocketBase.<SendAsyncCore>d__47.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OpenQA.Selenium.DevTools.DevToolsSession.<SendCommand>d__35.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OpenQA.Selenium.DevTools.DevToolsSession.<SendCommand>d__34`2.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OpenQA.Selenium.DevTools.V96.Fetch.FetchAdapter.<ContinueRequest>d__16.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OpenQA.Selenium.DevTools.V96.V96Network.<ContinueRequestWithoutModification>d__12.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OpenQA.Selenium.NetworkManager.<OnRequestPaused>d__20.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
    [External Code]
```

### Operating System

Windows 10

### Selenium version

4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 96

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 96

**Comment by lopukhDA** [comment] 2021-11-29 19:25
The same [#10054](https://github.com/SeleniumHQ/selenium/issues/10054)

**Comment by jimevans** [comment] 2021-12-03 21:34
Duplicate of #10054. Please try `await networkInterceptor.StartMonitoring();`.

**Closed as completed by jimevans** 2021-12-03 21:34 UTC
Labels: C-dotnet, I-defect
