### ISSUE TITLE
Not able to install Selenium Safari Driver on Safari 9.0

### ISSUE THREAD

**Issue by Roopesht** [SeleniumHQ/selenium#1341] opened 2015-12-03 19:31 UTC
Hi,
I am trying to install Safari Driver (version 2.48.0) on Safari 9.0 but it does not seem they are compatible. Is there is any tweak need to be done before I install Safari Driver on 9.0?
Is there 
Thanks,
Roopesh

**Comment by raistlin7447** [comment] 2015-12-03 22:25
We are experiencing this same problem.  The extension install window pops up asking if you Trust the extension.  Click Trust, then it appears to work, but the extension never shows as installed.

**Comment by vveliev** [comment] 2015-12-03 22:46
duplicate ? #1315

**Comment by raistlin7447** [comment] 2015-12-04 01:03
Definitely sounds like it might be the same issue and appears to be a bug in Safari.

**Comment by ddavison** [comment] 2015-12-04 13:33
it is - closing as dupe of #1315

**Closed by ddavison** 2015-12-04 13:33 UTC
Labels: D-safari
