### ISSUE TITLE
selenium can't drag Canvas elements

### ISSUE THREAD

**Issue by YinChunGuang** [SeleniumHQ/selenium#9581] opened 2021-06-16 04:20 UTC
## 🐛 Bug Report

 
 There are abnormalities in the functions such as click, double-click, drag and drop of Canvas used by Selenium to automate testing.
The specific reason is that Selenium cannot get the elements inside Canvas.

## To Reproduce
Exercising a page's dragging and dropping functionailty used to be simple with
 Seleniums's Action Builder, but sadly ,it won't work with HTML5 drag and drop .

We use the selenium function 'Actions.dragAndDrop(source,target)'  to control the elements inside canvas,it dosen't work that way for selenium can't select the element .

## Expected behavior

 selenium can drap canvas elements

## Test script or set of commands reproducing this issue

```
Actions actions = new Action(driver);
actions.dragAndDrop(source,target)；
```

The code dosen't work ,also no exception.

## Environment
OS: Windows 10
Browser: Chrome
Browser version: 90.0.4430.24
Browser Driver version:  90.0.4430.24  
Language Bindings version:  Java 8  c

**Comment by diemol** [comment] 2021-06-16 07:12
The only difference between the released docker 3.x images and the previous ones is the Chrome and ChromeDriver version, therefore, please submit Chrome/ChromeDriver issues to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.

**Comment by diemol** [comment] 2021-06-16 07:13
Apologies, I wrote my reply in the wrong issue, reopening.

**Comment by diemol** [comment] 2021-06-16 07:14
@YinChunGuang, could you please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by YinChunGuang** [comment] 2021-06-17 12:29
test case :
[](https://github.com/YinChunGuang/selenium_test.git  )
@diemol 

```
public class BaseModel {

    public static ChromeDriver driver;

    public static void main(String[] args) {
        initChromeDriver();
        driver.get("http://localhost:9528");
        WebElement source = driver.findElementByXPath("//*[@id=\"nodes\"]/li[1]");
        WebElement target = driver.findElementByXPath("//*[@id=\"canvas_1\"]");
        Actions actions = new Actions(driver);
        actions.dragAndDrop(source,target);

        driver.quit();
    }

    private static void initChromeDriver() {
        **System.setProperty("webdriver.chrome.driver", "D:\\java\\chromedriver.exe");**
        ChromeOptions options = new ChromeOptions();
        driver = new ChromeDriver(options);
        driver.manage().timeouts().implicitlyWait(10000, TimeUnit.MILLISECONDS);
        driver.manage().window().maximize();
    }
}
```

please set chrome driver for the test !

**Comment by diemol** [comment] 2021-06-17 12:30
What is running in `driver.get("http://localhost:9528");`? We need to have access to the page.
What Selenium version are you using?

**Comment by YinChunGuang** [comment] 2021-06-17 12:40
@diemol 
code : https://github.com/YinChunGuang/selenium_test.git

**Comment by diemol** [comment] 2021-06-17 12:42
Could you please add instructions, either here or at the README showing how to setup and execute everything?

**Comment by YinChunGuang** [comment] 2021-06-19 11:15
# 
#1 cd /selenium_test/vue_example 
#2 npm i
#3 npm run dev
#4 open project "selenium_test\seleniumtest" 
#5 update chromeDriverPath :  BaseModel.DRIVER_PATH
#6 start "BaseModel.main()"  
# result   selenium can't drag the element
#
@diemol

**Comment by AutomatedTester** [comment] 2021-07-01 13:40
I think this might be another version of https://github.com/w3c/webdriver/issues/1488 since it's dragging an element from outside the canvas into the canvas.

**Comment by AutomatedTester** [comment] 2021-07-16 10:45
Duplicate of #8345

**Closed as completed by AutomatedTester** 2021-07-16 10:45 UTC
Labels: G-w3c
