### ISSUE TITLE
[🐛 Bug]: Unable to obtain driver using Selenium Manager: C:\Users\mli86\Anaconda3\lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe is missing.  Please open an issue on https://github.com/SeleniumHQ/selenium/issues

### ISSUE THREAD

**Issue by plsfixthis** [SeleniumHQ/selenium#12084] opened 2023-05-23 00:37 UTC
### What happened?

There's an issue with my selenium where i'm unable to obtain the drive using selenium manager

### How can we reproduce the issue?

```shell
webdriver_service = Service('C:\Desktop\chromedriver.exe')
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--headless")  # Run in headless mode (without opening a browser window)
driver = webdriver.Chrome(service=webdriver_service, options=chrome_options)
```

### Relevant log output

```shell
SeleniumManagerException                  Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_15428/3851760388.py in <module>
     61 
     62 # Initialize ChromeDriver with the configured options
---> 63 driver = webdriver.Chrome(service=webdriver_service, options=chrome_options)
     64 keyword_pattern = re.compile(r'gazette-listing', re.IGNORECASE)
     65 # Visit the URL

~\Anaconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py in __init__(self, executable_path, port, options, service_args, desired_capabilities, service_log_path, chrome_options, service, keep_alive)
     80         if not service:
     81             service = Service(executable_path, port, service_args, service_log_path)
---> 82         service.path = DriverFinder.get_path(service, options)
     83 
     84         super().__init__(

~\Anaconda3\lib\site-packages\selenium\webdriver\common\driver_finder.py in get_path(service, options)
     41         except WebDriverException as err:
     42             logger.warning("Unable to obtain driver using Selenium Manager: " + err.msg)
---> 43             raise err
     44 
     45         return path

~\Anaconda3\lib\site-packages\selenium\webdriver\common\driver_finder.py in get_path(service, options)
     38     def get_path(service: Service, options: BaseOptions) -> str:
     39         try:
---> 40             path = shutil.which(service.path) or SeleniumManager().driver_location(options)
     41         except WebDriverException as err:
     42             logger.warning("Unable to obtain driver using Selenium Manager: " + err.msg)

~\Anaconda3\lib\site-packages\selenium\webdriver\common\selenium_manager.py in driver_location(self, options)
     75         browser = options.capabilities["browserName"]
     76 
---> 77         args = [str(self.get_binary()), "--browser", browser, "--output", "json"]
     78 
     79         if options.browser_version:

~\Anaconda3\lib\site-packages\selenium\webdriver\common\selenium_manager.py in get_binary()
     59         if not path.is_file():
     60             tracker = "https://github.com/SeleniumHQ/selenium/issues"
---> 61             raise SeleniumManagerException(f"{path} is missing.  Please open an issue on {tracker}")
     62 
     63         return path

SeleniumManagerException: Message: C:\Users\mli86\Anaconda3\lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe is missing.  Please open an issue on https://github.com/SeleniumHQ/selenium/issues
```

### Operating System

Windows 10

### Selenium version

Selenium 4.9.1

### What are the browser(s) and version(s) where you see this issue?

Windows Edge

### What are the browser driver(s) and version(s) where you see this issue?

Version 113.0.1774.50 (Official build) (64-bit)

### Are you using Selenium Grid?

Not using selenium grid

**Comment by titusfortner** [comment] 2023-05-23 00:41
Yeah this is a duplicate of #11234 
Anaconda does its own packaging, and we're not sure what needs to happen so that the binary we're including with Selenium wheel gets included by Anaconda as well.

**Closed as completed by titusfortner** 2023-05-23 00:41 UTC
Labels: I-defect, A-needs-triaging
