### ISSUE TITLE
Selenium hangs while initializing the RemoteWebDriver object after 16 test cases run without error.

### ISSUE THREAD

**Issue by burakdLabs** [SeleniumHQ/selenium#9616] opened 2021-06-29 07:12 UTC
## 🐛 Bug Report

Hi,
Selenium hangs while initializing the RemoteWebDriver object after 16 test cases run without error.

## Expected behavior

I am testing a network device's GUI which has capable of switching and routing. I have around 20 selenium test cases runing on the Jenkins environment daily. Recently my test cases started to hang on Jenkins. In the beginning I had no issue running my test cases but after the number of test cases reached 16, 17th test case is not starting because it hangs while creating the RemoteWebDriver object.

## Test script or set of commands reproducing this issue

**These are the Chrome Options I use:**

```
case "chrome":
options = new ChromeOptions();
options.setPageLoadStrategy(PageLoadStrategy.NONE); 
options.addArguments("--no-proxy-server");
options.addArguments("--no-sandbox");
options.addArguments("--enable-automation");
options.addArguments("--headless");
options.addArguments("--disable-dev-shm-usage");
options.addArguments("--disable-browser-side-navigation");
options.addArguments("--ignore-certificate-errors");
options.addArguments("--disable-gpu");
break;
```

**This is how initialize the remote web driver and the session.** 
```
	try {
		URL rURL = new URL(webDriverUrl);
		baseWd = new RemoteWebDriver(rURL, options); // CODE HANGS HERE <--
	} catch (MalformedURLException ex) {
		throw new AccessMethodUnavailabeException(String.format("Remote web driver URL for %s is invalid", name), ex);
		}
	}
		wd=new EventFiringWebDriver(baseWd);
		acts = new Actions(wd);
		wdWait=new WebDriverWait(wd, waitTimeOut);
		wd.manage().timeouts().pageLoadTimeout(READ_TIMEOUT, TimeUnit.MILLISECONDS);
		wd.register(this);
		wd.manage().window().maximize();
		wd.navigate().to(entryPoint);	
```		

**This is how I terminate the sessions.**
```
	public void cleanup(boolean performLogout) {
		if (wdWait != null) {
			wdWait = null;
		}
		if (wd != null) {
			try {
				wd.close();
				logger.info("Web browser closed.");
			} catch (RuntimeException ex) {
				logException(logger, Level.WARN, ex);
			}
			try {
				wd.quit();
				logger.info("Selenium session ended.");
			} catch (RuntimeException ex) {
				logException(logger, Level.WARN, ex);
			}
			wd = null;
		}
		if (baseWd != null) {
			baseWd.quit(); 
			baseWd = null;
		}
	}
```

**This is the hub json config:**
```
{
    "port": 4444,
    "host": "127.0.0.1",
    "newSessionWaitTimeout": -1,
    "servlets" : [],
    "withoutServlets": [],
    "custom": {},
    "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
    "throwOnCapabilityNotPresent": true,
    "cleanUpCycle": 1800,
    "role": "hub",
    "debug": false,
    "log": "C:/WebDriver/bin/logs/hubLog.txt",
    "browserTimeout": 600,
    "timeout": 600
  }
```

**This is the node json config:**
```
{
  "capabilities":
  [
    {
      "browserName": "chrome",
      "maxInstances": 10,
      "seleniumProtocol": "WebDriver",
      "webdriver.chrome.driver": "C:/WebDriver/bin/chromedriver.exe",
      "takesScreenshot": false,
      "cleanSession": true
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 10,
  "port": 5555,
  "host": "127.0.0.1", 
  "register": true,
  "timeout": 600,
  "registerCycle": 5000,
  "hub": "http://localhost:4444",
  "nodeStatusCheckTimeout": 5000,
  "nodePolling": 5000,
  "role": "node",
  "unregisterIfStillDownAfter": 6000,
  "downPollingLimit": 2,
  "debug": false,
  "log": "C:/WebDriver/bin/logs/nodeLog.txt",
  "servlets" : [],
  "withoutServlets": [],
  "custom": {}
}
```

**I collected the debug logs of the both hub and node. This is what I see on the hub log when issue arise:**
> 10:41:29.524 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: chrome, goog:chromeOptions: {args: [--no-proxy-server, --no-sandbox, enable-automation, --headless, --disable-dev-shm-usage, --disable-browser-side-navi..., --ignore-certificate-errors, --disable-gpu], extensions: []}, pageLoadStrategy: none}
> 10:41:29.525 DEBUG [ProxySet.getNewSession] - Available nodes: [http://127.0.0.1:5555]
> 10:41:29.525 DEBUG [BaseRemoteProxy.getNewSession] - Trying to create a new session on node http://127.0.0.1:5555
> 10:41:29.525 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=e28171f1-ccb8-4b0b-8c81-f98b642fc5ba, seleniumProtocol=WebDriver, webdriver.chrome.driver=C:/WebDriver/bin/chromedriver.exe, browserName=chrome, takesScreenshot=false, maxInstances=10, platformName=WIN10, cleanSession=true, platform=WIN10}
> 10:51:31.478 WARN [SessionCleanup.null] - session ext. key 12bcf7df07867b0d973e26690d61de40 has TIMED OUT due to client inactivity and will be released.
> 10:51:31.487 WARN [DefaultRemoteProxy.beforeRelease] - Error releasing the resources on timeout for session ext. key 12bcf7df07867b0d973e26690d61de40

**And node logs:**
> 10:41:29.539 DEBUG [WebDriverServlet.handle] - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@395dc459
> 10:41:29.539 DEBUG [WebDriverServlet.lambda$handle$0] - /session: Executing POST on /session (handler: BeginSession)
> 10:41:29.544 INFO [ActiveSessionFactory.apply] - Capabilities are: {
>   "browserName": "chrome",
>   "goog:chromeOptions": {
>     "args": [
>       "--no-proxy-server",
>       "--no-sandbox",
>       "--enable-automation",
>       "--headless",
>       "--disable-dev-shm-usage",
>       "--disable-browser-side-navigation",
>       "--ignore-certificate-errors",
>       "--disable-gpu"
>     ],
>     "extensions": [
>     ]
>   },
>   "pageLoadStrategy": "none"
> }
> 10:41:29.544 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
> 10:41:29.546 DEBUG [UrlChecker.waitUntilAvailable] - Waiting for [http://localhost:5831/status]
> 10:41:29.547 DEBUG [UrlChecker.lambda$waitUntilAvailable$1] - Polling http://localhost:5831/status
> 10:41:30.061 DEBUG [UrlChecker.lambda$waitUntilAvailable$1] - Polling http://localhost:5831/status
> 10:41:30.068 DEBUG [HttpURLConnection.writeRequests] - sun.net.www.MessageHeader@605447375 pairs: {GET /status HTTP/1.1: null}{User-Agent: Java/1.8.0_282}{Host: localhost:5831}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
> 10:41:30.070 DEBUG [HttpURLConnection.getInputStream0] - sun.net.www.MessageHeader@2556d5594 pairs: {null: HTTP/1.1 200 OK}{Content-Length: 247}{Content-Type: application/json; charset=utf-8}{cache-control: no-cache}
> 10:41:30.782 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
> 10:41:30.783 DEBUG [RemoteWebDriver.log] - Executing: newSession [null, newSession {desiredCapabilities=Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 91.0.4472.106, chrome: {chromedriverVersion: 91.0.4472.19 (1bf021f248676..., userDataDir: C:\Users\ScalanceX\AppData\...}, goog:chromeOptions: {debuggerAddress: localhost:60218}, networkConnectionEnabled: false, pageLoadStrategy: none, platformName: windows, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}}]
> 10:41:30.783 DEBUG [RemoteWebDriver.log] - Executed: [null, newSession {desiredCapabilities=Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 91.0.4472.106, chrome: {chromedriverVersion: 91.0.4472.19 (1bf021f248676..., userDataDir: C:\Users\ScalanceX\AppData\...}, goog:chromeOptions: {debuggerAddress: localhost:60218}, networkConnectionEnabled: false, pageLoadStrategy: none, platformName: windows, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}}]
> 10:41:30.783 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 12bcf7df07867b0d973e26690d61de40 (org.openqa.selenium.chrome.ChromeDriverService)
> 10:51:31.484 DEBUG [WebDriverServlet.handle] - Found handler: org.openqa.selenium.remote.server.commandhandler.NoSessionHandler@6b519ef4
> 10:51:31.486 DEBUG [WebDriverServlet.lambda$handle$0] - /session/12bcf7df07867b0d973e26690d61de40: Executing DELETE on /session/12bcf7df07867b0d973e26690d61de40 (handler: NoSessionHandler)
> 10:51:31.527 INFO [ActiveSessions$1.onStop] - Removing session 12bcf7df07867b0d973e26690d61de40 (org.openqa.selenium.chrome.ChromeDriverService)
> 10:51:31.531 DEBUG [HttpURLConnection.writeRequests] - sun.net.www.MessageHeader@38ddd3487 pairs: {DELETE /session/12bcf7df07867b0d973e26690d61de40 HTTP/1.1: null}{Cache-Control: no-cache}{Pragma: no-cache}{User-Agent: Java/1.8.0_282}{Host: localhost:5831}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
> 10:51:31.557 DEBUG [HttpURLConnection.getInputStream0] - sun.net.www.MessageHeader@361a2a234 pairs: {null: HTTP/1.1 200 OK}{Content-Length: 14}{Content-Type: application/json; charset=utf-8}{cache-control: no-cache}
> 10:51:31.558 DEBUG [ReverseProxyHandler.execute] - To downstream: {"value":null}
> 10:51:31.558 DEBUG [UrlChecker.waitUntilUnavailable] - Waiting for http://localhost:5831/shutdown
> 10:51:31.559 DEBUG [UrlChecker.lambda$waitUntilUnavailable$2] - Polling http://localhost:5831/shutdown
> 10:51:31.560 DEBUG [HttpURLConnection.writeRequests] - sun.net.www.MessageHeader@19570b945 pairs: {GET /shutdown HTTP/1.1: null}{User-Agent: Java/1.8.0_282}{Host: localhost:5831}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
> 10:51:31.581 DEBUG [HttpURLConnection.getInputStream0] - sun.net.www.MessageHeader@1790e6ce3 pairs: {null: HTTP/1.1 200 OK}{Content-Length: 40}{Content-Type: application/json; charset=utf-8}
> 10:51:31.592 DEBUG [UrlChecker.lambda$waitUntilUnavailable$2] - Polling http://localhost:5831/shutdown

**Please let me know do you need anything else.**
[hubLog.txt](https://github.com/SeleniumHQ/selenium/files/6731397/hubLog.txt)
[nodeLog_shortned.txt](https://github.com/SeleniumHQ/selenium/files/6731398/nodeLog_shortned.txt)

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 91.0.4472.114 (Official Build) (32-bit)
Browser Driver version: ChromeDriver 91.0.4472.101
Language Bindings version: Java 3.141.59 
Selenium Grid version: 3.141.59

**Comment by AutomatedTester** [comment] 2021-07-01 13:33
@diemol @shs96c @pujagani Could this be related to #9601 ?

**Comment by diemol** [comment] 2021-07-12 12:59
> @diemol @shs96c @pujagani Could this be related to #9601 ?

No, this is Grid 3.

**Comment by diemol** [comment] 2021-07-13 14:34
@burakdLabs can you provide a complete code snippet to reproduce this? The code added in the issue does not compile by itself, seems a few variables are missing. A GitHub repo with instructions would be ideal.

Regarding the logs, it really looks like the sessions in the Node are not terminating, which hints that the VM is running out of resources.

**Comment by diemol** [comment] 2021-07-27 12:16
Closing this because we did not get more information.

**Closed as completed by diemol** 2021-07-27 12:16 UTC
Labels: B-grid, J-awaiting answer, C-java

**Comment by burakdLabs** [comment] 2021-08-19 11:39
> Closing this because we did not get more information.

Hi @diemol 

Since the company I worked in does not allow me to share any source code due to their policy unfortunately I am not able to provide you any kind of repo information. 

Meanwhile I was digging into more of the problem I discovered some information which maybe useful for you guys.

I collected the java thread dump of the problematic case, as far as I can see the problem creates a traffic jam pattern which is blocking threads makes the application unresponsive.

![image](https://user-images.githubusercontent.com/43272616/130059236-e9d85256-a635-4f47-878d-5eee38cd1275.png)

When I traced back to the first thread which is causing the other thread blocks, it says:

```
pool-5-thread-1
Stack Trace is:
java.lang.Thread.State: RUNNABLE
at java.io.FileOutputStream.writeBytes(Native Method)
at java.io.FileOutputStream.write(FileOutputStream.java:326)
at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
- locked <0x00000006c35f78c0> (a java.io.BufferedOutputStream)
at java.io.PrintStream.write(PrintStream.java:482)
- locked <0x00000006c35f78a0> (a java.io.PrintStream)
at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
```

When I was looking for why this thread is blocking, I have seen same problem observed by Apache team as well back in the the days and it has fixed. Please see the reported problem below (they have the same stack trace as mine)

https://issues.apache.org/jira/browse/STORM-1215
**at java.io.FileOutputStream.writeBytes(Native Method)
at java.io.FileOutputStream.write(FileOutputStream.java:326)
at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)**

It seems synchronous loggers causing some of the daemons slow down.

They overcome the issue by doing the following:
- Turn off immediateFlush.
- Enable async logging.
- Turn off Immediate Fail for log events on syslog logger to avoid making blocking call without timeout.

I don't know does this ring any bell but any suggestion would be great!

By the way I added the stack trace to the case as well if you want a take a look.
[atsnThreadDump3.txt](https://github.com/SeleniumHQ/selenium/files/7014034/atsnThreadDump3.txt)

Just my two cents I find thread.io is very useful to analyze stack traces.
https://fastthread.io/

Could you please re-open the case.

Please let me know if you need more information.

Best regards,
Burak D.

**Comment by diemol** [comment] 2021-08-19 11:44
Thanks for providing that analysis.
However, we were asking for a way to reproduce it so we could help you overcome the issue with a Selenium Grid version that is not under development anymore.
The only alternative for now would be to try Grid 4.

**Comment by burakdLabs** [comment] 2021-08-19 11:48
> Thanks for providing that analysis.
> However, we were asking for a way to reproduce it so we could help you overcome the issue with a Selenium Grid version that is not under development anymore.
> The only alternative for now would be to try Grid 4.

Hi @diemol is there any changes on logging mechanism for Grid4? Otherwise it doesn't make any sense to try the same scenario with Grid4.

**Comment by diemol** [comment] 2021-08-19 11:50
Grid 4 is written from scratch, so most likely many things failing in Grid 3 work in Grid 4.
