### ISSUE TITLE
Mocha BDD wrapping incorrectly for it.only

### ISSUE THREAD

**Issue by noisette44** [SeleniumHQ/selenium#2302] opened 2016-06-16 14:27 UTC
## Meta -
OS:  Windows 7
Selenium Version: 2.53.2 
Mocha version : 2.5.3

## Expected Behavior -

"it.only" function inside [javascript/node/selenium-webdriver/testing/index.js](https://github.com/SeleniumHQ/selenium/blob/ede98def1f85600ec120536bd1f36f244a331b86/javascript/node/selenium-webdriver/testing/index.js) should correctly wrapped for asynchronous code.

```
exports.it = wrapped(global.it);
exports.iit = exports.it.only = wrapped(global.it.only);
```

## Actual Behavior -

Since mocha V2.4.1 and this [commit](https://github.com/mochajs/mocha/commit/08bf74d8440b811e42bf4b8150a4977a05472c9a) "it.only" function is not correctly wrapped because it call original "it" mocha function and no more "it" wrapped function. So, test is not run in asynchronous mode.

```
context.it.only = function(title, fn) {
   var test = it(title, fn); // => Since mocha 2.4.1 - use original mocha "it" function
   var reString = '^' + escapeRe(test.fullTitle()) + '$';
   mocha.grep(new RegExp(reString));
   return test;
}
```
mocha issue : [https://github.com/mochajs/mocha/issues/2157](https://github.com/mochajs/mocha/issues/2157#issuecomment-224475198)

Now using own `it.only` function is necessary instead of wrapping.

**Comment by jleyba** [comment] 2016-06-17 16:45
Do yo have a reduced test case demonstrating the actual problem you are experiencing?

**Comment by jleyba** [comment] 2016-06-17 18:26
To clarify: I need a reproducible test case (selenium-webdriver only, no protractor stuff) to know what I'm looking for. Everything I've tried with `it.only` works as expected.

**Comment by benbracha** [comment] 2016-06-21 20:19
I couldn't reproduce it as well with selenium-webdriver only, without protractor.
@ScottFreeCode, @noisette44 maybe we have a protractor issue here? Can you try to reproduce?

**Comment by jleyba** [comment] 2016-06-21 20:58
Ok, I'm closing this because the supposed issue cannot be reproduced.

For the record, selenium-webdriver does not monkey-patch mocha. It provides an API shim that wraps your functions before calling `global.it`, `global.it.only`, etc.

```javascript
var test = require('selenium-webdriver/testing');
var assert = require('assert');

describe('wrapping', function() {
  it('does not monkey-patch', function() {
    assert.ok(test.it !== global.it);
    assert.ok(test.it.only !== global.it.only);
    console.log('test.it.only:______________');
    console.log(test.it.only + '');
    console.log();
    console.log('it.only:______________');
    console.log(it.only + '');
  });
});
```

```
$ mocha test.js

  wrapping
test.it.only:______________
function () {
    if (arguments.length === 1) {
      return globalFn(makeAsyncTestFn(arguments[0]));
    }
    else if (arguments.length === 2) {
      return globalFn(arguments[0], makeAsyncTestFn(arguments[1]));
    }
    else {
      throw Error('Invalid # arguments: ' + arguments.length);
    }
  }

it.only:______________
function (title, fn) {
      var test = it(title, fn);
      var reString = '^' + escapeRe(test.fullTitle()) + '$';
      mocha.grep(new RegExp(reString));
      return test;
    }
    ✓ does not monkey-patch


  1 passing (9ms)
```

**Closed by jleyba** 2016-06-21 20:58 UTC
Labels: C-nodejs

**Comment by jleyba** [comment] 2016-06-21 21:32
As always, we can revisit this issue if a reproducible test case is provided.

**Comment by ScottFreeCode** [comment] 2016-06-22 05:29
Bother, you're right, this isn't patching -- I misread the exporting of wrapped versions of the functions as replacing the global ones (which in fact it's not doing) when I was trying to understand the reports we were getting pointing at the Selenium wrapper to explain the behavioral differences... But that can't be it since it's just exporting the wrapped functions, not replacing the originals with them.

My bad, sorry about that! I'm thinking, at this point, that unless somebody comes up with a Selenium-only (no Protractor) test demonstrating a problem with Selenium's wrapped `it.only` (I'll see if I can double-check this, but it isn't my main priority at this point as long as I can get the original issue fixed), Selenium's wrapping per se is probably a red herring...

In fact, while Protractor does appear to be using Selenium's wrapped versions (replacing most of Mocha's global functions with them -- this is what I went looking for on a hunch once I realized what Selenium itself doesn't do the global replacement), [it looks like it goes out of its way to keep the original `it.only`](https://github.com/angular/protractor/blob/9144494a28dac5a0409de4c5384e933f2d2f8156/lib/frameworks/mocha.js#L33), which would explain the issue. So, I will try loading up both of these and the example app from the Mocha issue, and see whether I can resolve it just by tinkering with how the Protractor code handles `it.only` (e.g. whether there's any problem with having it just keep Selenium's version). Then I'll report my findings and update all three issues as applicable.

Thanks for pointing me back in the right direction!

**Comment by noisette44** [comment] 2016-06-22 08:18
@jleyba Sorry for the delay - and thanks a lot for your feedback

I agree with @ScottFreeCode - it's a protractor issue since mocha "it.only" no more uses "global.it"

**Comment by ScottFreeCode** [comment] 2016-06-22 21:33
Well, I eventually ended up having to try it in a VM in order to properly test it because my copy of Firefox wasn't cooperating with WebDriver, but I finally managed to confirm that Selenium's `only` wrapper is doing the right thing, and simply changing Protractor to use Selenium's wrapped `only` fixes the issue: https://github.com/angular/protractor/issues/3045#issuecomment-227883093
