### ISSUE TITLE
Firefox quit unexpectedly (OSX 10.11.5 and Firefox 47)

### ISSUE THREAD

**Issue by aluzardo** [SeleniumHQ/selenium#2290] opened 2016-06-15 10:04 UTC
## Meta -
OS:  **OSX 10.11.5**
Selenium Version:  **2.52.0**
Browser:  **Firefox**
Browser Version:  **47.0**

## Expected Behavior -
Able to create new session using the browser Firefox 47.0
## Actual Behavior -
Unable to create new session using the browser Firefox 47.0. Error: "Firefox quit unexpectedly" 
PD: I fixed the problem installing Firefox 46.0.
## Steps to reproduce -
1. Open [http://localhost:4444/wd/hub](http://localhost:4444/wd/hub) 
2. Click on `Create new session` button 
3. Choose `firefox`
4. Click `OK`

**Comment by TJEvans** [comment] 2016-06-15 11:35
Seeing this issue aswell in test environment.  Firefox 47 crashes on startup and also seeing issues with the latest ESR.

[ComposeWithPastedImageDriver.txt](https://github.com/SeleniumHQ/selenium/files/316043/ComposeWithPastedImageDriver.txt)

**Comment by AutomatedTester** [comment] 2016-06-15 11:39
duplicate of #2110

**Closed by AutomatedTester** 2016-06-15 11:39 UTC
