### ISSUE TITLE
org.openqa.selenium.remote.service.DriverService - withLog should support log rotation

### ISSUE THREAD

**Issue by nddipiazza** [SeleniumHQ/selenium#5336] opened 2018-01-12 15:01 UTC
## Meta -
OS:  
any
Selenium Version:  
all
Browser:  
any
Browser Version:  
any

## Expected Behavior -
Example:

When you create a driver service and specify a log file:
```
new GeckoDriverService.Builder()
          .usingDriverExecutable(new File(geckoDriverBinaryPath))
          .withLogFile(geckoLogFile)
          .build();
```

This log file should allow a log rotation to manage many GB of log content.

## Actual Behavior 
The log file specified grows pretty quickly and gets many GB large. Causes issues.

## Steps to reproduce -
Run a really long running test with this log file set. Notice log file grows massive.

**Comment by p0deje** [comment] 2018-01-15 05:59
1. Can you clean log files after every test by yourself?
2. How exactly should this work and look like?

**Comment by nddipiazza** [comment] 2018-01-15 17:41
1. No unfortunately these are 24/7 running CI programs.
2. What logging utility writes these logs? If using log4j, it supports a log rotation feature. same with `logrotate`. it would be nice if it worked using your average every day log rotate

**Comment by barancev** [comment] 2018-01-16 06:44
Selenium itself uses java.util.logging, dependencies can use other logging libraries. If you want to rotate logs, there are (at least) two options:
1. Write logs to a single file and use standard logrotate utility to rotate them
2. Use slf4j with java.util.logging adapter (and may be some other adapters), redirect logs to logback and use RollingFileAppender to rotate them

I'll keep this issue open for now, but can't promice it will be implemented soon.

**Comment by nddipiazza** [comment] 2018-01-16 14:04
yep we are using logrotate now. would be a good enhancement for those dealing with many GB sized logs

**Comment by chabala** [comment] 2018-04-01 19:01
@barancev Would you be open to moving from JUL to SLF4J? Would you accept PRs in that direction?

**Comment by nddipiazza** [comment] 2018-04-07 15:35
@barancev @chabala that would be good.

**Comment by shs96c** [comment] 2019-05-07 12:42
Selenium is widely used in many places. We work hard to ensure we have as few dependencies as possible, particularly when these are likely to conflict with ones that are likely included elsewhere. While JUL is admittedly awful, it's baked into the platform and stable, and therefore not a source of surprising dependency conflicts for our users. Because of this, we'd be very unlikely to accept PRs that move the project away from JUL unless there was a compelling reason.

JUL supports log rotation of the default `FileHandler` using standard properties, which can be set in `logging.properties` or [similar](https://docs.oracle.com/javase/7/docs/api/java/util/logging/FileHandler.html). How geckodriver handles logs is out-of-scope for selenium, and should be raised as a bug on the [geckodriver repo](https://github.com/mozilla/geckodriver).

Closing this issue, since I think everything is working as intended. Please feel free to re-open if I have misunderstood something important.

**Closed by shs96c** 2019-05-07 12:42 UTC
Labels: C-java, I-enhancement

**Comment by chabala** [comment] 2019-05-07 15:24
I can certainly understand your position. There's a lot of effort involved in changing logging with not much immediate upside, and my question was tangential to the specific issue of this ticket.

Limiting dependencies in a popular library is an important goal. Choosing JUL makes that goal harder for dependent projects; they either:
* get on board with using JUL (forcing their choice of logging)
* work around it to get your logging back into a shim ([with a performance penalty](https://www.slf4j.org/legacy.html#jul-to-slf4j))
* just add their own logging framework of choice (adding to the mess, like the adage goes, when a java project reaches a certain size, it will contain all logging frameworks)

It seems to me that the only reasonable choice for library code is to use a shim and defer the choice of logging implementation to the ultimate consumer. SLF4J would be the strong leader in that space. This is the extra fourth option to above, work with your upstream dependencies to get them to use SLF4J. I can open a proper ticket for this, but I was hoping to gauge interest before doing so.
