### ISSUE TITLE
Unable to drag li tags from source list and drop to an empty target list using selenium

### ISSUE THREAD

**Issue by Shebeok** [SeleniumHQ/selenium#7434] opened 2019-07-26 08:36 UTC
I am trying a drag users from one list to another list. The target list is empty. I want to drag the li tags to that empty list. This does not work in either chrome or firefox.

Sample html code to replicate the issue:

```
<html>
<body>
    <div id="sourceDiv" style="border: thick;border-color: black; border-width: thick;">
    <span>Source</span>
        <ul id="optionList">
            <li><span draggable="true">Option1</span></li>
            <li><span draggable="true">Option2</span></li>
            <li><span draggable="true">Option3</span></li>
            <li><span draggable="true">Option4</span></li>
        </ul>
    </div>
    <div id="targetDiv"  style="border: thick;border-color: black;border-width: thick;">
    <span>Target</span>
        <ul id="optionList">

        </ul>
    </div>
</body>

</html>
```
I have tried selenium using draganddrop ,clickandHold along with moveToElement .

Using DragandDropMethod:

```
WebElement source=By.xpath("//div[@id='sourceDiv']//ul//li");
WebElement target=By.xpath("//div[@id='targetDiv']//ul");
Actions actionBuilder = new Actions(driver);
actionBuilder.dragAndDrop(source, target).build().perform();
```
Using MoveToElement:
```

WebElement source=By.xpath("//div[@id='sourceDiv']//ul//li");
    WebElement target=By.xpath("//div[@id='targetDiv']//ul");
    Actions actionBuilder = new Actions(driver);
    actionBuilder.clickAndHold(source).moveToElement(target).release().build().perform();


```
Environment
OS: Windows 7
Browser: Chrome Version:75.0.3770.142, Firefox Quantum Version:68.0.1
Browser Driver version: ChromeDriver  2.43.600210, GeckoDriver 0.23 
Language Bindings version: Java 3.141.59

**Comment by Shebeok** [comment] 2019-08-22 10:05
Hi guys,

I am still facing this issue. The JS workaround mentioned in stackoverflow etc doesn't work for me. Any inputs or workarounds would be highly appreciated.

Thanks!

**Comment by barancev** [comment] 2019-09-29 08:35
Sorry, I overlooked this issue.
Please provide an SSCCE (Short, Self Contained, Correct [compilable] example) http://sscce.org/
If you can't provide a link to the page, consider creating a reproducible page on https://jsfiddle.net/

**Comment by Shebeok** [comment] 2019-10-24 05:53
Hi @barancev ,
PFA the same html to reproduce the issue. I have added the selenium code snippet used to drag and drop in the first comment. Kindly help. 
[Dnd.zip](https://github.com/SeleniumHQ/selenium/files/3765901/Dnd.zip)

**Comment by Shebeok** [comment] 2019-10-30 05:24
Hi @barancev,
Please find the drag and drop example in the below link. 
Expected behaviour: the span should be dragged and dropped.
Actual behviour: It gets clicked but source is not dropped in the target.
https://www.seleniumeasy.com/test/drag-and-drop-demo.html

WebElement source=By.xpath("//span[@draggable='true']");
WebElement target=By.xpath("//div[@id='mydropzone']");
Actions actionBuilder = new Actions(driver);
actionBuilder.dragAndDrop(source, target).build().perform();

**Comment by Shebeok** [comment] 2019-11-05 11:04
Hi guys,

I am still facing this issue. Any inputs or workarounds would be highly appreciated.

Thanks!

**Comment by Shebeok** [comment] 2019-11-18 07:02
Hi guys,

I am still facing this issue. Any inputs or workarounds would be highly appreciated.

Thanks!

**Comment by AutomatedTester** [comment] 2021-02-17 13:47
Duplicate of #8003

**Closed by AutomatedTester** 2021-02-17 13:47 UTC
Labels: C-java
