### ISSUE TITLE
[🐛 Bug]:  Access is denied: 'OpenQA.Selenium.Remote.DesiredCapabilities'. (Selenium 4+, .NET)

### ISSUE THREAD

**Issue by Salomonsson** [SeleniumHQ/selenium#11901] opened 2023-04-14 11:27 UTC
### What happened?

I have for a while tried to go up from version 3.141.0 to 4+ in selenium on a .NET based platform.

I get the error message: _Access is denied: 'OpenQA.Selenium.Remote.DesiredCapabilities'._

I have done my research and it seems that there is some problem with the .NET plaforform/framework and selenium from 4+? Or is there any solution on this out there?

Or is WinAppDriver not supported by Selenium 4 due WinAppDriver is not yet W3C compliant?

### How can we reproduce the issue?

```shell
Some syntax:
protected static WindowsDriver<RemoteWebElement> Driver { get; set; }
AppiumOptions appiumOptions = new AppiumOptions();
appiumOptions.AddAdditionalCapability("app", AppIdentifier);
appiumOptions.AddAdditionalCapability("deviceName", "WindowsPC");
appiumOptions.AddAdditionalCapability("ms:waitForAppLaunch", 5);
Driver = new WindowsDriver<RemoteWebElement>(new Uri("http://127.0.0.1:4723"), appiumOptions);
```

### Relevant log output

```shell
Access is denied: 'OpenQA.Selenium.Remote.DesiredCapabilities'.
```

### Operating System

Windows 11

### Selenium version

4+

### What are the browser(s) and version(s) where you see this issue?

WPF, UWP, Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver

**Comment by titusfortner** [comment] 2023-04-14 16:48
This is a duplicate of https://github.com/appium/dotnet-client/issues/600

Try the v5 beta of Appium .NET client.

**Closed as completed by titusfortner** 2023-04-14 16:48 UTC
Labels: I-defect, A-needs-triaging
