### ISSUE TITLE
Remote session not sending capabilities to node using Selenium (Ruby) 3.4.3

### ISSUE THREAD

**Issue by scoderp** [SeleniumHQ/selenium#4195] opened 2017-06-16 19:08 UTC
OS:  OSX 10.8
Selenium Version:  3.4.3 (Ruby bindings)
Browser:  Chrome / Firefox / IE
Selenium Server Version: 3.4.0 (on hub and nodes)

With 3.4.1 and 3.4.3, I attempted to utilize the new chromeOptions methods of add_argument and add_preference. Locally, these worked fine. When I attempt to run them against my grid, I receive "status error 500" from the hub.

Removing the role of "hub" from the hub VM allows the tests to run successfully on the same VM as a node. Either the grid is attempting to run the session on the hub and getting a 500, or the hub isn't sending the capabilities to the node. I do not see any log on the hub that indicates it's making a request to a node to start the session.

Reverting back to 3.4.0 and using the old style of args and prefs has fixed the issue.

Here's my setup method:

```
def setup_chrome(params={})
  setup = {:selenium_hub => params[:selenium_hub] || SELENIUM_HUB,
                :start_url => params[:start_url] || BASE_URL
  }

  options = Selenium::WebDriver::Chrome::Options.new
  options.add_preference('credentials_enable_service', false)
  options.add_preference('profile.password_manager_enabled', false)
  options.add_argument('disable-infobars')
  options.add_argument('use-fake-device-for-media-stream')
  options.add_argument('use-fake-ui-for-media-stream')

  caps = Selenium::WebDriver::Remote::Capabilities.chrome(:chromeOptions => options.as_json)
  @driver = Selenium::WebDriver.for :remote, :url => setup[:selenium_hub], :desired_capabilities => caps

  @driver.get setup[:start_url]
end
```

**Comment by lmtierney** [comment] 2017-06-17 01:00
Hi, this is actually a duplicate of #3808 since the Ruby bindings are now sending w3c capabilities. Unfortunately it is not fixed yet (hopefully soon). If you want to use 3.4.3 with grid, you'll have to get rid of the `capabilities` key from the desiredCapabilities sent for new session here: https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/remote/bridge.rb#L187-L189

**Closed by lmtierney** 2017-06-17 01:00 UTC
