### ISSUE TITLE
Couldn't create RemoteWebDriver with v 3.4.0. Null pointer exception in Grid server

### ISSUE THREAD

**Issue by KirillSokolovsky** [SeleniumHQ/selenium#4012] opened 2017-05-12 10:56 UTC
## Meta -
OS:  Windows 10 | 8.1 | Server 2016

Selenium Version:  3.4.0

Browser:  IE, Chrome, FF

Browser Version:  latest

Selenium target platform: .Net
## Actual Behavior -

[This commit](https://github.com/SeleniumHQ/selenium/commit/1afc18be518f6e8eb9d574e0e141fce7a045dffb) causes null pointer exception in Grid server that prevents any tries to create RemoteWebDriver.

Some details:
E.g. json sent as payload for command to Grid server to create Chrome instance (stat new session) is following:
```
{
 "desiredCapabilities":
 {
   "browserName":"chrome","version":"","platform":"ANY","javascriptEnabled":true,"chromeOptions":{"args":["disable-infobars"],"prefs":{"download.prompt_for_download":true,"download.default_directory":"NULL"}}
 },
 "capabilities":
 {
  "firstMatch":[{"browserName":"chrome","javascriptEnabled":true,"chromeOptions":{"args":["disable-infobars"],"prefs":{"download.prompt_for_download":true,"download.default_directory":"NULL"}}}]
 }
```
}

According to logic (of mentioned commit) if there is "capabilities" element in json, "desiredCapabilities" element should be found in "capabilities" and parsed as Map
```
if (map.has("capabilities")) {
return new JsonToBeanConverter().convert(Map.class, map.getAsJsonObject("capabilities").getAsJsonObject("desiredCapabilities"));
 }
```
But there is no inner element "desiredCapabilities" in "capabilities" (there is just element "firstMatch").
Verified with creating RemoteWebDriver for FF, Chrome and IE.
So this peace of code return null in all cases of sending request to create new session during creating remote webdriver.
And that cause null pointer exception in Grid.

Actually I could debug just .Net sources and possible I've missed some logic in java code.
But if I remove whole "capabilities" element from request payload all works fine.

Some stacktrace exception info extracted from response in format "{classname} > {method} > {line}":
```
"java.util.HashMap > putMapEntries > -1"
"java.util.HashMap > putAll > -1"
"org.openqa.selenium.remote.DesiredCapabilities > <init> > 55"
"org.openqa.grid.web.servlet.handler.RequestHandler > process > 104"
"org.openqa.grid.web.servlet.DriverServlet > process > 83"
"org.openqa.grid.web.servlet.DriverServlet > doPost > 67"
"javax.servlet.http.HttpServlet > service > 707"
"javax.servlet.http.HttpServlet > service > 790"
"org.seleniumhq.jetty9.servlet.ServletHolder > handle > 841"
"org.seleniumhq.jetty9.servlet.ServletHandler > doHandle > 543"
"org.seleniumhq.jetty9.server.handler.ScopedHandler > nextHandle > 188"
"org.seleniumhq.jetty9.server.session.SessionHandler > doHandle > 1584"
"org.seleniumhq.jetty9.server.handler.ScopedHandler > nextHandle > 188"
"org.seleniumhq.jetty9.server.handler.ContextHandler > doHandle > 1228"
"org.seleniumhq.jetty9.server.handler.ScopedHandler > nextScope > 168"
"org.seleniumhq.jetty9.servlet.ServletHandler > doScope > 481"
"org.seleniumhq.jetty9.server.session.SessionHandler > doScope > 1553"
"org.seleniumhq.jetty9.server.handler.ScopedHandler > nextScope > 166"
"org.seleniumhq.jetty9.server.handler.ContextHandler > doScope > 1130"
"org.seleniumhq.jetty9.server.handler.ScopedHandler > handle > 141"
"org.seleniumhq.jetty9.server.handler.HandlerWrapper > handle > 132"
"org.seleniumhq.jetty9.server.Server > handle > 564"
"org.seleniumhq.jetty9.server.HttpChannel > handle > 320"
"org.seleniumhq.jetty9.server.HttpConnection > onFillable > 251"
"org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback > succeeded > 279"
"org.seleniumhq.jetty9.io.FillInterest > fillable > 112"
"org.seleniumhq.jetty9.io.ChannelEndPoint$2 > run > 124"
"org.seleniumhq.jetty9.util.thread.Invocable > invokePreferred > 122"
"org.seleniumhq.jetty9.util.thread.strategy.ExecutingExecutionStrategy > invoke > 58"
"org.seleniumhq.jetty9.util.thread.strategy.ExecuteProduceConsume > produceConsume > 201"
"org.seleniumhq.jetty9.util.thread.strategy.ExecuteProduceConsume > run > 133"
"org.seleniumhq.jetty9.util.thread.QueuedThreadPool > runJob > 672"
"org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2 > run > 590"
"java.lang.Thread > run > -1"
```

**Comment by KirillSokolovsky** [comment] 2017-05-12 11:04
From code in [RemoteWebDriver.cs](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Remote/RemoteWebDriver.cs) line 1100
you could see that element "capabilities" with inner element "firstMatch" is added during any StartSession method call with any desiredCapabilities
```
protected void StartSession(ICapabilities desiredCapabilities)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("desiredCapabilities", this.GetLegacyCapabilitiesDictionary(desiredCapabilities));

            Dictionary<string, object> firstMatchCapabilities = this.GetCapabilitiesDictionary(desiredCapabilities);

            List<object> firstMatchCapabilitiesList = new List<object>();
            firstMatchCapabilitiesList.Add(firstMatchCapabilities);

            Dictionary<string, object> specCompliantCapabilities = new Dictionary<string, object>();
            specCompliantCapabilities["firstMatch"] = firstMatchCapabilitiesList;
            parameters.Add("capabilities", specCompliantCapabilities);

            Response response = this.Execute(DriverCommand.NewSession, parameters);

            Dictionary<string, object> rawCapabilities = (Dictionary<string, object>)response.Value;
            DesiredCapabilities returnedCapabilities = new DesiredCapabilities(rawCapabilities);
            this.capabilities = returnedCapabilities;
            this.sessionId = new SessionId(response.SessionId);
        }
```

**Comment by jimevans** [comment] 2017-05-12 12:09
Duplicate of #3808

**Closed by jimevans** 2017-05-12 12:09 UTC
