### ISSUE TITLE
`change` event not triggered for input text element

### ISSUE THREAD

**Issue by LiHaoTan** [SeleniumHQ/selenium#5337] opened 2018-01-13 04:52 UTC
## Meta -
**OS**:  macOS, Ubuntu
**Selenium Version**:  Selenium Java 2.53.1
**Browser**:  Firefox 46.0

## Expected Behavior -
`change` event should be triggered.

## Actual Behavior -
`change` event does not trigger.

## Steps to reproduce -
1. Some text input is changed (with sendKeys)
2. Blur the text input (e.g. click another element, press tab, send a blur event)

Sample test:
```Java

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.thoughtworks.selenium.webdriven.JavascriptLibrary;

public class BasicFocusTest {

    public static void main(String[] args) {
        FirefoxProfile profile = new FirefoxProfile();
        profile.setEnableNativeEvents(true);
        // whether focusmanager.testmode is enabled or not select onchange is guaranteed to succeed
        // if using Selenium Select
        profile.setPreference("focusmanager.testmode", true);

        WebDriver driver = new FirefoxDriver(profile);
        driver.manage().window().maximize();

        driver.get("https://jsfiddle.net/LiHaoTan/pn8ozt80/");

        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

        driver.switchTo().frame("result");

        WebDriverWait wait = new WebDriverWait(driver, 4);
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("abc")));
        final WebElement textInputElement = driver.findElement(By.id("abc"));

        // click to focus element
        textInputElement.click();

        // always trigger change event unless text is empty
        // we manually add some text, but this works with the input default attribute too
        //textInputElement.sendKeys("a");
        //textInputElement.clear();

        // If the browser is in focus change event is triggered, otherwise it never triggers even if
        // focusmanger.testmode is set to true
        textInputElement.sendKeys("TESTING!" + Keys.TAB);

        // no matter what other methods used to blur the input element the change event never
        // executes for input text
        //alternativeBlur1(driver);
        //alternativeBlur2(driver, textInputElement);

        // alternatively click on the other element to blur
        //driver.findElement(By.id("ice-cream")).click();

        //manualTriggerChangeEvent(driver, textInputElement);

        // the guaranteed succeeding change event
        //Select select = new Select(driver.findElement(By.id("ice-cream")));
        //select.selectByVisibleText("Chocolate");
    }

    public static void manualTriggerChangeEvent(WebDriver driver, WebElement textInputElement) {
        // manually trigger change event
        JavascriptLibrary javascript = new JavascriptLibrary();
        javascript.callEmbeddedSelenium(driver, "triggerEvent", textInputElement, "change");
    }

    public static void alternativeBlur2(WebDriver driver, WebElement textInputElement) {
        // alternative 2 to blur element
        JavascriptLibrary javascript = new JavascriptLibrary();
        javascript.callEmbeddedSelenium(driver, "triggerEvent", textInputElement, "blur");
    }

    public static void alternativeBlur1(WebDriver driver) {
        // alternative 1 to blur element
        driver.switchTo().activeElement().sendKeys(Keys.TAB);
    }
}

```

**Comment by p0deje** [comment] 2018-01-15 06:01
Can you try reproducing using modern Selenium (3.8.1)?

**Comment by LiHaoTan** [comment] 2018-01-15 08:51
I re-tested with the following:

## Meta -
**OS**:  macOS
**Selenium Version**:  Selenium Java 3.8.1
**Browser**:  Firefox 57.0.4 (geckodriver 0.19.1)


## Reproducible case
```Java
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

public class BasicFocusTest {

    public static void main(String[] args) {
        System.setProperty("webdriver.gecko.driver", "path/to/geckodriver");
        FirefoxProfile profile = new FirefoxProfile();
        // whether focusmanager.testmode is enabled or not select onchange is guaranteed to succeed
        // if using Selenium select
        //profile.setPreference("focusmanager.testmode", false);

        final FirefoxOptions options = new FirefoxOptions();
        options.setProfile(profile);

        WebDriver driver = new FirefoxDriver(options);
        driver.manage().window().maximize();

        driver.get("https://jsfiddle.net/LiHaoTan/pn8ozt80/");

        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

        driver.switchTo().frame("result");

        WebDriverWait wait = new WebDriverWait(driver, 4);
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("abc")));
        final WebElement textInputElement = driver.findElement(By.id("abc"));

        // click to focus element
        textInputElement.click();

        // always trigger change event unless text is empty
        // we manually add some text, but this works with the input default attribute too
        //textInputElement.sendKeys("a");
        //textInputElement.clear();

        // If the browser is in focus change event is triggered, otherwise it never triggers even if
        // focusmanger.testmode is set to true
        textInputElement.sendKeys("TESTING!" + Keys.TAB);

        // no matter what other methods used to blur the input element the change event never
        // executes for input text
        //alternativeBlur1(driver);
        //alternativeBlur2(driver, textInputElement);

        // alternatively click on the other element to blur
        //driver.findElement(By.id("ice-cream")).click();

        //manualTriggerChangeEvent(driver, textInputElement);

        // the guaranteed succeeding change event
        //Select select = new Select(driver.findElement(By.id("ice-cream")));
        //select.selectByVisibleText("Chocolate");
    }

    public static void manualTriggerChangeEvent(WebDriver driver, WebElement textInputElement) {
        // manually trigger change event
        JavascriptExecutor javascriptExecutor = (JavascriptExecutor) driver;
        javascriptExecutor.executeScript("arguments[0].dispatchEvent(new Event('change'));", textInputElement);

    }

    public static void alternativeBlur2(WebDriver driver, WebElement textInputElement) {
        // alternative 2 to blur element
        JavascriptExecutor javascriptExecutor = (JavascriptExecutor) driver;
        javascriptExecutor.executeScript("arguments[0].dispatchEvent(new Event('blur'));", textInputElement);
    }

    public static void alternativeBlur1(WebDriver driver) {
        // alternative 1 to blur element
        driver.switchTo().activeElement().sendKeys(Keys.TAB);
    }
}

```

**Comment by p0deje** [comment] 2018-01-15 09:25
This looks like the same issue as seleniumhq/selenium-google-code-issue-archive#157. However, the original issue mentioned native events as a workaround, so you might raise this against GeckoDriver. Please, log this issue at https://github.com/mozilla/geckodriver.

**Comment by p0deje** [comment] 2018-01-15 09:26
I'll keep this issue open for now.

**Comment by barancev** [comment] 2018-01-16 06:32
Closing the issue here, it's a geckodriver bug.

**Closed by barancev** 2018-01-16 06:32 UTC
Labels: D-firefox

**Comment by LiHaoTan** [comment] 2018-01-16 09:02
Sorry if I'm not getting the right idea but doesn't this apply to Selenium 2 as well which doesn't use geckodriver? Am I right to say that it's Firefox's problem then?

There is at least some strange behavior that `clear` always triggers `change` event though, which made me have the impression that it can be fixed by Selenium WebDriver?

**Comment by barancev** [comment] 2018-01-16 10:02
Speaking about legacy driver -- yes, it's a browser issue, it does not fire blur event if browser window is not in focus. It's supposed that new firefox driver (aka geckodriver) will overcome this issue.

Anyway, legacy driver is in "support mode" now, we fix only critical issues there. And as soon as Selenium 4.0 is out, legacy Firefox driver will be officially deprecated. So, please, consider migration to geckodriver and modern browser versions.

**Comment by dewanprakash** [comment] 2018-01-29 13:12
do we have a way to enable native events for Firefox when using geckodriver? the old api which use to work with FirefoxProfile is no longer valid.

**Comment by barancev** [comment] 2018-01-29 13:19
@dewanprakash Please don't hijack closed issues.

FYI: Native events does not exist in legacy FirefoxDriver since version 3.1.0 in 3.x series and 2.48.0 in 2.x series (and browser version 32 that is waaay old)
