### ISSUE TITLE
C# System.InvalidCastException: 'Unable to cast object of type 'EventFiringWebElement' to type 'OpenQA.Selenium.Internal.IWrapsDriver'.'

### ISSUE THREAD

**Issue by Haxy89** [SeleniumHQ/selenium#7036] opened 2019-03-15 11:55 UTC
```
IWebDriver driver;
driver = new DriverFactory().Init();
this.Driver = new EventListener(driver);
```

```
public static void DoubleClick(this IWebElement webElement)
        {
            var driver = ((IWrapsDriver)webElement).WrappedDriver;
            Actions action = new Actions(driver);
            action.DoubleClick(webElement).Build().Perform();
        }
```

`System.InvalidCastException: 'Unable to cast object of type 'EventFiringWebElement' to type 'OpenQA.Selenium.Internal.IWrapsDriver'.'`

**Comment by jimevans** [comment] 2019-03-15 22:04
Yes, this should be fixed in the library. As a workaround, until that gets done and the fix released, you can conditionally cast using the `as` operator (avoiding the InvalidCastException), and do the right thing, like this:

    public static void DoubleClick(this IWebElement webElement)
    {
        IWebElement targetElement = webElement;
        IWrapsDriver wrapsDriver = webElement as IWrapsDriver;
        if (wrapsDriver == null)
        {
            var wrapsElement = webElement as IWrapsElement;
            if (wrapsElement == null)
            {
                throw new InvalidOperationException("webElement does not implement either IWrapsDriver or IWrapsElement");
            }

            targetElement = wrapsElement.WrappedElement;
            wrapsDriver = targetElement as IWrapsDriver;
            if (wrapsDriver == null)
            {
                throw new InvalidOperationException("webElement wraps another IWebElement, but the wrapped element does not implement IWrapsDriver");
            }
        }

        var driver = wrapsDriver.WrappedDriver;
        Actions action = new Actions(driver);
        action.DoubleClick(targetElement).Build().Perform();
    }

Yes, the checking is verbose, and that is suboptimal. Please note it's provided merely as a workaround until the issue is fixed.

**Comment by Haxy89** [comment] 2019-03-16 09:53
Thanks for answer. I will check your fix on monday and let you know

**Comment by Haxy89** [comment] 2019-03-18 07:33
Fix works, thanks :)

**Comment by diemol** [comment] 2019-03-18 07:57
Closing as solved.

**Closed by diemol** 2019-03-18 07:57 UTC
