### ISSUE TITLE
I have created test cases using selenium webdriver. But as Firefox updated to 36 test cases are not running and showing error.

### ISSUE THREAD

**Issue by Pravin1989patil** [SeleniumHQ/selenium#361] opened 2015-03-24 06:03 UTC
I am using selenium 2.45 web drive and Windows 7 OS.

It  call the browser but didn't navigate to specified URl.  But once I degrade Firefox to 35 I worked.
I want execute my tests on Firefox 36.
Please Help me

**Comment by AutomatedTester** [comment] 2015-03-24 07:35
This bug report has no actionable items in it. What version of selenium are you using, what OS, is there a reproducible way to solve this issue? 




If you can't supply this we will unfortunately have to close this issue



—

**Comment by andreastt** [comment] 2015-03-24 11:53
Please see https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions about contributing an issue.

**Closed by andreastt** 2015-03-24 11:53 UTC

**Comment by WanderingKazuma** [comment] 2015-03-25 14:30
I am seeing the same issue. OSX 10.10.2 Yosemite. Running FF 35 was working fine with 2.45 webdriver. FF upgraded without me knowing it, and things started to stop working. I got an error saying that the firefox binary could not be located even though Firefox did open up a blank window. Checked and found that it was indeed located at /Applications/Firefox.app like it should have been. I even tried uninstalling and re-installing FF36 a few times. I think webdriver is timing out after 45 seconds, but unable to connect or something.

FF version that is causing this for me is: 36.0.4
Addons/Plugins that I'm using are: Firebug and firepath

Downgraded to FF 34 and everything started working again.

Error that I am getting is:
Caused by: org.openqa.selenium.firefox.NotConnectedException at Dashboard.java:25

Referenced line of code in Dashboard.java:25 is:
driver = new FirefoxDriver();

The ReportNG output gives a little more details, but I am not sure how to read this (not familiar with what it is trying to tell me)

org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/Applications/Firefox.app/Contents/MacOS/firefox-bin) on port 7055; process output follows: 
xtensions.json	DEBUG	Starting timer
1427293140263	DeferredSave.extensions.json	DEBUG	Starting write
1427293140279	addons.manager	DEBUG	shutdown
1427293140279	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1427293140279	addons.xpi	DEBUG	shutdown
1427293140280	addons.xpi-utils	DEBUG	shutdown
1427293140280	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1427293140280	addons.manager	DEBUG	Calling shutdown blocker for OpenH264Provider
1427293140281	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1427293140339	DeferredSave.extensions.json	DEBUG	Write succeeded
1427293140339	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 16
1427293140339	addons.xpi	DEBUG	Notifying XPI shutdown observers
1427293140342	addons.manager	DEBUG	Async provider shutdown done
1427293140777	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1427293140778	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1427293140780	addons.xpi	DEBUG	startup
1427293140781	addons.xpi	INFO	Mapping fxdriver@googlecode.com to /var/folders/9p/f4_r4hmd7msgknm37s0312q00000gn/T/anonymous885092362400972721webdriver-profile/extensions/fxdriver@googlecode.com
1427293140781	addons.xpi	DEBUG	Ignoring file entry whose name is not a valid add-on ID: /var/folders/9p/f4_r4hmd7msgknm37s0312q00000gn/T/anonymous885092362400972721webdriver-profile/extensions/webdriver-staging
1427293140781	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}
1427293140781	addons.xpi	DEBUG	Skipping unavailable install location app-system-share
1427293140782	addons.xpi	DEBUG	checkForChanges
1427293140782	addons.xpi	DEBUG	Loaded add-on state from prefs: {"app-profile":{"fxdriver@googlecode.com":{"d":"/var/folders/9p/f4_r4hmd7msgknm37s0312q00000gn/T/anonymous885092362400972721webdriver-profile/extensions/fxdriver@googlecode.com","e":true,"v":"2.43.1","st":1427293139000,"mt":1427293139000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"36.0.4","st":1427210523000,"mt":1427210518000}}}
1427293140783	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1427293140785	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1427293140785	addons.xpi	DEBUG	getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"/var/folders/9p/f4_r4hmd7msgknm37s0312q00000gn/T/anonymous885092362400972721webdriver-profile/extensions/fxdriver@googlecode.com","e":true,"v":"2.43.1","st":1427293139000,"mt":1427293139000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"36.0.4","st":1427210523000,"mt":1427210518000}}}
1427293140786	addons.xpi	DEBUG	No changes found
1427293140788	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1427293140789	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1427293140790	addons.manager	DEBUG	Registering shutdown blocker for OpenH264Provider
1427293140790	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
JavaScript error: file:///var/folders/9p/f4_r4hmd7msgknm37s0312q00000gn/T/anonymous885092362400972721webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js, line 11464: TypeError: this.server_ is undefined
JavaScript error: chrome://fxdriver/content/server.js, line 38: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
*** Blocklist::_preloadBlocklistFile: blocklist is disabled
1427293142042	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>

Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
System info: host: 'sakamoto', ip: '192.168.1.101', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.8.0_25'
Driver info: driver.version: FirefoxDriver
org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:130)
org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:182)
org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:95)
ncr.backoffice.tests.CustomerDashboard.TestSetup(CustomerDashboard.java:25)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:483)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
org.testng.TestRunner.privateRun(TestRunner.java:767)
org.testng.TestRunner.run(TestRunner.java:617)
org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
org.testng.SuiteRunner.run(SuiteRunner.java:240)
org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
org.testng.TestNG.run(TestNG.java:1031)
org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:136)
org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:80)
org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:59)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:483)
org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
com.sun.proxy.$Proxy2.stop(Unknown Source)
org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:116)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:483)
org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
xtensions.json	DEBUG	Starting timer
1427293140263	DeferredSave.extensions.json	DEBUG	Starting write
1427293140279	addons.manager	DEBUG	shutdown
1427293140279	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1427293140279	addons.xpi	DEBUG	shutdown
1427293140280	addons.xpi-utils	DEBUG	shutdown
1427293140280	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1427293140280	addons.manager	DEBUG	Calling shutdown blocker for OpenH264Provider
1427293140281	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1427293140339	DeferredSave.extensions.json	DEBUG	Write succeeded
1427293140339	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 16
1427293140339	addons.xpi	DEBUG	Notifying XPI shutdown observers
1427293140342	addons.manager	DEBUG	Async provider shutdown done
1427293140777	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1427293140778	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1427293140780	addons.xpi	DEBUG	startup
1427293140781	addons.xpi	INFO	Mapping fxdriver@googlecode.com to /var/folders/9p/f4_r4hmd7msgknm37s0312q00000gn/T/anonymous885092362400972721webdriver-profile/extensions/fxdriver@googlecode.com
1427293140781	addons.xpi	DEBUG	Ignoring file entry whose name is not a valid add-on ID: /var/folders/9p/f4_r4hmd7msgknm37s0312q00000gn/T/anonymous885092362400972721webdriver-profile/extensions/webdriver-staging
1427293140781	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}
1427293140781	addons.xpi	DEBUG	Skipping unavailable install location app-system-share
1427293140782	addons.xpi	DEBUG	checkForChanges
1427293140782	addons.xpi	DEBUG	Loaded add-on state from prefs: {"app-profile":{"fxdriver@googlecode.com":{"d":"/var/folders/9p/f4_r4hmd7msgknm37s0312q00000gn/T/anonymous885092362400972721webdriver-profile/extensions/fxdriver@googlecode.com","e":true,"v":"2.43.1","st":1427293139000,"mt":1427293139000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"36.0.4","st":1427210523000,"mt":1427210518000}}}
1427293140783	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1427293140785	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1427293140785	addons.xpi	DEBUG	getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"/var/folders/9p/f4_r4hmd7msgknm37s0312q00000gn/T/anonymous885092362400972721webdriver-profile/extensions/fxdriver@googlecode.com","e":true,"v":"2.43.1","st":1427293139000,"mt":1427293139000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"36.0.4","st":1427210523000,"mt":1427210518000}}}
1427293140786	addons.xpi	DEBUG	No changes found
1427293140788	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1427293140789	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1427293140790	addons.manager	DEBUG	Registering shutdown blocker for OpenH264Provider
1427293140790	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
JavaScript error: file:///var/folders/9p/f4_r4hmd7msgknm37s0312q00000gn/T/anonymous885092362400972721webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js, line 11464: TypeError: this.server_ is undefined
JavaScript error: chrome://fxdriver/content/server.js, line 38: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
*** Blocklist::_preloadBlocklistFile: blocklist is disabled
1427293142042	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>

**Comment by jleyba** [comment] 2015-03-25 16:18
According to your logs, you are using Selenium 2.43.1, not 2.45.0. 2.43.1 will not work with Firefox 36. Upgrade to Selenium 2.45.0

    Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
    System info: host: 'sakamoto', ip: '192.168.1.101', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.8.0_25'
    Driver info: driver.version: FirefoxDriver
