### ISSUE TITLE
Selenium IDE: cannot drag command lines and scripts in the interface

### ISSUE THREAD

**Issue by fherbst** [SeleniumHQ/selenium#3769] opened 2017-04-05 13:11 UTC
## Meta -
OS:  Windows 10
Selenium Version:  IDE 2.9.1.1
Browser:  Firefox

Browser Version:  
52.0.2 32bit

## Expected Behavior -
I can click on a line in the interface and I can drag that line with the mouse to a different location

## Actual Behavior -
I can still select a line, but I cannot drag it anymore.

## Steps to reproduce -
open the interface and load a Suite. Click and drag on any of the lines of the test cases or any of the command lines and try to drag it.

**Comment by lmtierney** [comment] 2017-04-05 13:12
Duplicate of #3139 please see the workaround there

**Closed by lmtierney** 2017-04-05 13:12 UTC
