### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by ashishjoshi27** [SeleniumHQ/selenium#11228] opened 2022-11-07 12:55 UTC
### What happened?

Drag and drop not working with Selenium latest version

### How can we reproduce the issue?

```shell
try to automate any drag and drop control using Selenium.
```

### Relevant log output

```shell
No error. it just not doing the drag and drop
```

### Operating System

Windows10

### Selenium version

selenium-server-4.5.3.jar

### What are the browser(s) and version(s) where you see this issue?

CHROME Version 107.0.5304.88

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 107.0.5304.62 (1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942})

### Are you using Selenium Grid?

Nope

**Comment by diemol** [comment] 2022-11-07 13:03
Duplicate of #10601

https://github.com/SeleniumHQ/selenium/issues/10601#issuecomment-1117937743

**Closed as completed by diemol** 2022-11-07 13:03 UTC
Labels: I-defect
