### ISSUE TITLE
IE10/9 element opacity:0 is incorrectly non-interactable

### ISSUE THREAD

**Issue by kdillon** [SeleniumHQ/selenium#595] opened 2015-06-01 20:54 UTC
Hey team,

I noticed as discrepancy between the behavior of IEDriver and the other browser Drivers with respect to the interactability of invisible states. To be clear, there are several ways to make things invisible in CSS, and each have different attributes.

display:none , for example, is non-interactable and takes no real estate
visibility:hidden, is non-interactable but consumes real estate
opacity:0 is interactable, and consumes real estate

... that is, you can use opacity 0 to overlay, and clicks will hit the "invisible" element. This is true for all the browsers that I have tried, including IE10 & 11, Firefox, Chrome, and Safari. 

Selenium generally gets this right. It correctly identifies invisible nodes as being invisible. However, for Opacity 0, it does not throw an error when trying to click or type into them for Chrome, Firefox, and Safari. But on IE10 (and I think IE9 as well) it throws an org.openqa.selenium.ElementNotVisibleException: Element is not currently visible and so may not be interacted with.

Just to be clear: this error message is incorrect. Certain types of invisible elements CAN be interacted-with, Opacity:0 being one of them. Selenium is interacting with them just-fine in most cases (Firefox, Safari, Chrome). The problem is that IE10 (and IE9 too, I think) is detecting that the element is invisible and throwing a cannot-interact exception, even though it should be able to interact with this element.

Thanks!

**Comment by kdillon** [comment] 2015-06-01 20:56
Also: is there anywhere to upload HTML? I have a demo page that you guys can use which will easily demonstrate this syndrome. It also allows you to rapidly verify that opacity: 0 is human-interactable.

**Comment by jimevans** [comment] 2015-06-01 21:54
Are you certain this isn't a duplicate of #503, which was fixed by revision 698dc42 about a month ago?

**Comment by kdillon** [comment] 2015-06-02 15:01
it might be the same issue. Please feel free to dupe to the closed report

**Comment by jimevans** [comment] 2015-06-02 15:07
Looks very much like a duplicate of #503. If it's not fixed in the next public release of IE driver, please feel free to reopen.

**Closed by jimevans** 2015-06-02 15:07 UTC
