### ISSUE TITLE
Firefox beta 41.0b1: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms

### ISSUE THREAD

**Issue by RayVin** [SeleniumHQ/selenium#927] opened 2015-08-13 20:35 UTC
Selenium 2.47.1 crashes on Windows 7 with Firefox 41.0b1

LOG:

org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
-app-global
1439497690058	addons.xpi-utils	DEBUG	Make addon winreg-app-global:{D19CA586-DD6C-4a0a-96F8-14644F340D60} visible
1439497690058	DeferredSave.extensions.json	DEBUG	Save changes
1439497690058	DeferredSave.extensions.json	DEBUG	Save changes
1439497690058	addons.xpi	DEBUG	Updating XPIState for {"id":"{D19CA586-DD6C-4a0a-96F8-14644F340D60}","syncGUID":"riWnw1mMa93-","location":"winreg-app-global","version":"15.1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":"chrome://vscore/content/ScriptFF.gif","icon64URL":null,"defaultLocale":{"name":"McAfee ScriptScan for Firefox","description":null,"creator":"McAfee, Inc.","homepageURL":null},"visible":true,"active":false,"userDisabled":true,"appDisabled":true,"descriptor":"C:\\Program Files (x86)\\Common Files\\McAfee\\SystemCore","installDate":1424916626178,"updateDate":1424916626178,"applyBackgroundUpdates":1,"bootstrap":false,"size":2304002,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"1.5","maxVersion":"9.9"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":0}
1439497690058	addons.xpi	DEBUG	New add-on {9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8} installed in winreg-app-global
1439497690084	DeferredSave.extensions.json	DEBUG	Starting write
1439497690092	addons.xpi	WARN	Disabling foreign installed add-on {9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8} in winreg-app-global
1439497690092	DeferredSave.extensions.json	DEBUG	Save changes
1439497690092	DeferredSave.extensions.json	DEBUG	Data changed while write in progress
1439497690092	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1439497690092	addons.xpi-utils	DEBUG	Updating add-on states
1439497690096	addons.xpi-utils	DEBUG	Writing add-ons list
1439497690108	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1439497690108	addons.manager	DEBUG	Provider finished startup: XPIProvider
1439497690108	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1439497690108	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1439497690108	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1439497690108	addons.manager	DEBUG	Starting provider: GMPProvider
1439497690113	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1439497690113	addons.manager	DEBUG	Provider finished startup: GMPProvider
1439497690113	addons.manager	DEBUG	Starting provider: PluginProvider
1439497690113	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1439497690113	addons.manager	DEBUG	Provider finished startup: PluginProvider
1439497690113	addons.manager	DEBUG	Completed startup sequence
1439497690796	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1439497690796	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1439497690797	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1439497691292	DeferredSave.extensions.json	DEBUG	Write succeeded
1439497691292	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1439497691292	DeferredSave.extensions.json	DEBUG	Starting timer
1439497691303	addons.repository	DEBUG	No addons.json found.
1439497691304	DeferredSave.addons.json	DEBUG	Save changes
1439497691306	DeferredSave.addons.json	DEBUG	Starting timer
1439497691318	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1439497691319	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1439497691319	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1439497691322	DeferredSave.extensions.json	DEBUG	Starting write
1439497691473	DeferredSave.addons.json	DEBUG	Starting write
1439497691475	DeferredSave.extensions.json	DEBUG	Write succeeded
1439497691664	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:122)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:276)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:223)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:212)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at pages.LocalUse.main(LocalUse.java:32)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
-app-global
1439497690058	addons.xpi-utils	DEBUG	Make addon winreg-app-global:{D19CA586-DD6C-4a0a-96F8-14644F340D60} visible
1439497690058	DeferredSave.extensions.json	DEBUG	Save changes
1439497690058	DeferredSave.extensions.json	DEBUG	Save changes
1439497690058	addons.xpi	DEBUG	Updating XPIState for {"id":"{D19CA586-DD6C-4a0a-96F8-14644F340D60}","syncGUID":"riWnw1mMa93-","location":"winreg-app-global","version":"15.1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":"chrome://vscore/content/ScriptFF.gif","icon64URL":null,"defaultLocale":{"name":"McAfee ScriptScan for Firefox","description":null,"creator":"McAfee, Inc.","homepageURL":null},"visible":true,"active":false,"userDisabled":true,"appDisabled":true,"descriptor":"C:\\Program Files (x86)\\Common Files\\McAfee\\SystemCore","installDate":1424916626178,"updateDate":1424916626178,"applyBackgroundUpdates":1,"bootstrap":false,"size":2304002,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"1.5","maxVersion":"9.9"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":0}
1439497690058	addons.xpi	DEBUG	New add-on {9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8} installed in winreg-app-global
1439497690084	DeferredSave.extensions.json	DEBUG	Starting write
1439497690092	addons.xpi	WARN	Disabling foreign installed add-on {9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8} in winreg-app-global
1439497690092	DeferredSave.extensions.json	DEBUG	Save changes
1439497690092	DeferredSave.extensions.json	DEBUG	Data changed while write in progress
1439497690092	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1439497690092	addons.xpi-utils	DEBUG	Updating add-on states
1439497690096	addons.xpi-utils	DEBUG	Writing add-ons list
1439497690108	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1439497690108	addons.manager	DEBUG	Provider finished startup: XPIProvider
1439497690108	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1439497690108	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1439497690108	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1439497690108	addons.manager	DEBUG	Starting provider: GMPProvider
1439497690113	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1439497690113	addons.manager	DEBUG	Provider finished startup: GMPProvider
1439497690113	addons.manager	DEBUG	Starting provider: PluginProvider
1439497690113	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1439497690113	addons.manager	DEBUG	Provider finished startup: PluginProvider
1439497690113	addons.manager	DEBUG	Completed startup sequence
1439497690796	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1439497690796	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1439497690797	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1439497691292	DeferredSave.extensions.json	DEBUG	Write succeeded
1439497691292	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1439497691292	DeferredSave.extensions.json	DEBUG	Starting timer
1439497691303	addons.repository	DEBUG	No addons.json found.
1439497691304	DeferredSave.addons.json	DEBUG	Save changes
1439497691306	DeferredSave.addons.json	DEBUG	Starting timer
1439497691318	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1439497691319	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1439497691319	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1439497691322	DeferredSave.extensions.json	DEBUG	Starting write
1439497691473	DeferredSave.addons.json	DEBUG	Starting write
1439497691475	DeferredSave.extensions.json	DEBUG	Write succeeded
1439497691664	DeferredSave.addons.json	DEBUG	Write succeeded

Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'XXX', ip: 'XXX.XX.XXX.XXX', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_51'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:134)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:276)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:223)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:212)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at pages.LocalUse.main(LocalUse.java:32)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
-app-global
1439497690058	addons.xpi-utils	DEBUG	Make addon winreg-app-global:{D19CA586-DD6C-4a0a-96F8-14644F340D60} visible
1439497690058	DeferredSave.extensions.json	DEBUG	Save changes
1439497690058	DeferredSave.extensions.json	DEBUG	Save changes
1439497690058	addons.xpi	DEBUG	Updating XPIState for {"id":"{D19CA586-DD6C-4a0a-96F8-14644F340D60}","syncGUID":"riWnw1mMa93-","location":"winreg-app-global","version":"15.1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":"chrome://vscore/content/ScriptFF.gif","icon64URL":null,"defaultLocale":{"name":"McAfee ScriptScan for Firefox","description":null,"creator":"McAfee, Inc.","homepageURL":null},"visible":true,"active":false,"userDisabled":true,"appDisabled":true,"descriptor":"C:\\Program Files (x86)\\Common Files\\McAfee\\SystemCore","installDate":1424916626178,"updateDate":1424916626178,"applyBackgroundUpdates":1,"bootstrap":false,"size":2304002,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"1.5","maxVersion":"9.9"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":0}
1439497690058	addons.xpi	DEBUG	New add-on {9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8} installed in winreg-app-global
1439497690084	DeferredSave.extensions.json	DEBUG	Starting write
1439497690092	addons.xpi	WARN	Disabling foreign installed add-on {9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8} in winreg-app-global
1439497690092	DeferredSave.extensions.json	DEBUG	Save changes
1439497690092	DeferredSave.extensions.json	DEBUG	Data changed while write in progress
1439497690092	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1439497690092	addons.xpi-utils	DEBUG	Updating add-on states
1439497690096	addons.xpi-utils	DEBUG	Writing add-ons list
1439497690108	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1439497690108	addons.manager	DEBUG	Provider finished startup: XPIProvider
1439497690108	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1439497690108	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1439497690108	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1439497690108	addons.manager	DEBUG	Starting provider: GMPProvider
1439497690113	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1439497690113	addons.manager	DEBUG	Provider finished startup: GMPProvider
1439497690113	addons.manager	DEBUG	Starting provider: PluginProvider
1439497690113	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1439497690113	addons.manager	DEBUG	Provider finished startup: PluginProvider
1439497690113	addons.manager	DEBUG	Completed startup sequence
1439497690796	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1439497690796	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1439497690797	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1439497691292	DeferredSave.extensions.json	DEBUG	Write succeeded
1439497691292	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1439497691292	DeferredSave.extensions.json	DEBUG	Starting timer
1439497691303	addons.repository	DEBUG	No addons.json found.
1439497691304	DeferredSave.addons.json	DEBUG	Save changes
1439497691306	DeferredSave.addons.json	DEBUG	Starting timer
1439497691318	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1439497691319	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1439497691319	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1439497691322	DeferredSave.extensions.json	DEBUG	Starting write
1439497691473	DeferredSave.addons.json	DEBUG	Starting write
1439497691475	DeferredSave.extensions.json	DEBUG	Write succeeded
1439497691664	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:122)
	... 7 more

**Comment by DeepaAM** [comment] 2015-08-14 03:56
I also faced the same issue. For the purpose of continuing my work I'm now back on the FireFox 40 stable version.

**Comment by joshbruning** [comment] 2015-08-14 05:37
"signedState":0

Perhaps this is due to https://blog.mozilla.org/addons/2015/02/10/extension-signing-safer-experience/ ?
Perhaps setting xpinstall.signatures.required = false as in https://github.com/SeleniumHQ/selenium/issues/901 will help ?

**Comment by miohtama** [comment] 2015-08-14 07:30
After latest Firefox beta update having an issue.

On OSX, Selenium 2.47.1 + Firefox 41.0b1 - getting with Python WebDrvier: selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.

I guess it is related.

**Comment by tobypinder** [comment] 2015-08-14 10:06
+1, Same on Firefox `42.0a2`

**Comment by JosephCastro** [comment] 2015-08-17 15:33
+1 
Using Firefox Developer Edition 42.0a2

**Comment by joshbruning** [comment] 2015-08-17 19:23
FYI: I verified that https://github.com/SeleniumHQ/selenium/pull/932 allows 41 to work (theoretically allows 42). I didn't make any new release there, though ... I compile things from source.

**Comment by RayVin** [comment] 2015-08-17 20:15
Can you please give the pref to set to 'False'?
Thx.

**Comment by JosephCastro** [comment] 2015-08-17 20:38
@RayVin 
 **xpinstall.signatures.required=false**

**Comment by RayVin** [comment] 2015-08-17 21:14
Thx Joseph.
Tried it, still doesn't run, are you successful after setting this flag?

**Comment by JosephCastro** [comment] 2015-08-18 12:58
Nope, the problem, I think, is that selenium hasn't support this version yet.

**Comment by lukeis** [comment] 2015-08-18 18:09
The fix applied will only work for FF 41. According to this wiki:
https://wiki.mozilla.org/Addons/Extension_Signing

We will need to sign the firefox extension to work with FF 42+

I'm attempting to go through the process with AMO, but have run into an issue with even submitting the xpi.

**Comment by JosephCastro** [comment] 2015-08-18 18:18
I use this preference to desactivate that ( xpinstall.signatures.required = false ) in 42.0a2 (manually), the problem is that selenium tells: can't load the profile, so I can't edit any preference through, for example, python.

**Comment by RayVin** [comment] 2015-08-18 18:54
have FF41, set the flag to 'False'...still doesn't run...says "Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055"
Can provide the log if needed...didn't want to stretch the thread unnecessarily...

**Comment by lukeis** [comment] 2015-08-18 19:58
@RayVin retry with the latest selenium jar:

http://ci.seleniumhq.org:8080/job/Build%20All%20Java/lastSuccessfulBuild/artifact/selenium-server-standalone-latest.jar

if that fails, then please log a new issue.

I'm going to close this bug, because we have Selenium running in CI working with FF 41 (yes, it is even running on windows).

**Closed by lukeis** 2015-08-18 19:58 UTC
