### ISSUE TITLE
Firefox SSL certificate 

### ISSUE THREAD

**Issue by Priya-Ram** [SeleniumHQ/selenium#3106] opened 2016-11-15 08:57 UTC
## Meta -
OS:  Windows 7

Selenium Version:  selenium==3.0.1

Browser:  Firefox 

Browser Version:  47 (64-bit)

## Steps to reproduce - This is an intranet website, so this cant be shared or used by public.

![error](https://cloud.githubusercontent.com/assets/23473395/20299539/6bd55922-ab41-11e6-99f2-245e0a08ba4a.png)

**Comment by mstankovic86** [comment] 2016-11-15 09:00
probably duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1103196

--
*Miloš Stanković*  |  *Team Lead*
Emisia Consulting, Kragujevac, Serbia

**Comment by NishilKumar** [comment] 2016-11-15 09:57
I am also facing similar issue , the firefox is not accepting ssl certs using python with selenium - anyone knows any way in which i can disable ssl checks itself in firefox?

**Comment by AutomatedTester** [comment] 2016-11-16 13:22
duplicate of #2495

**Closed by AutomatedTester** 2016-11-16 13:22 UTC
