### ISSUE TITLE
 Unable to connect to host 127.0.0.1 on port 7056 / Selenium 2.53 with ff 45.0

### ISSUE THREAD

**Issue by andrey2good** [SeleniumHQ/selenium#1915] opened 2016-04-04 18:06 UTC
## Meta -

OS: 
Selenium Version: 
Browser: 
Browser Version: 

**After upgrading from 2.45 jar to 2.53 and ff37 to ff45 I'm getting this error. Please give me a feedback asap. 
I`ve tried 2.52 and ff44 - same issue was raised**
Tests are trigger by a jenkins job, if matters.
## Actual Behavior - Error from summary is thrown

`Caused by: org.openqa.selenium.remote.ErrorHandler$UnknownServerException: Unable to connect to host 127.0.0.1 on port 7056 after 45000 ms. Firefox console output:

Build info: version: '2.53.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'v-is-jk-01.synygy.net', ip: '10.220.10.103', os.name: 'Linux', os.arch: 'amd64', os.version: '3.8.13-55.2.1.el6uek.x86_64', java.version: '1.8.0_31'
Driver info: driver.version: FirefoxDriver
at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:129)
at sun.reflect.GeneratedConstructorAccessor26.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:91)
at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:68)
at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
at java.util.concurrent.FutureTask.run(FutureTask.java:166)
at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
at java.lang.Thread.run(Thread.java:722)`

Here is also my firefox profile:
`private FirefoxProfile getFirefoxProfileSettings() {

```
    FirefoxProfile firefoxProfile = new FirefoxProfile();
    firefoxProfile.setPreference("browser.download.folderList", 2);
    firefoxProfile.setPreference("browser.download.manager.showWhenStarting", false);
    firefoxProfile.setPreference("browser.download.dir",<validPath>);   
    firefoxProfile.setPreference("plugin.disable_full_page_plugin_for_types", "application/pdf,application/vnd.fdf");
    firefoxProfile.setPreference("browser.helperApps.alwaysAsk.force", false);
    firefoxProfile.setPreference("browser.helperApps.neverAsk.saveToDisk", "application/excel,application/vnd.ms-excel,application/x-excel,application/x-msexcel,application/pdf);
    firefoxProfile.setPreference("pdfjs.disabled", true);
    firefoxProfile.setEnableNativeEvents(false);
    firefoxProfile.setPreference("dom.max_script_run_time", 0);
    firefoxProfile.setPreference("dom.max_chrome_script_run_time", 0);
    return firefoxProfile;

}
```

`

**Comment by parag90** [comment] 2016-04-05 10:49
I am facing similar issue: 

Selenium::WebDriver::Error::WebDriverError: unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055)
./features/support/browser.rb:14:in `new'
./features/support/browser.rb:14:in `initialize'

**Comment by testingcode** [comment] 2016-04-05 10:54
Please Install Xvfb plugin and restart.
working for me.

https://wiki.jenkins-ci.org/display/JENKINS/Xvfb+Plugin

**Comment by cgoldberg** [comment] 2016-04-05 17:18
@testingcode Xvfb has nothing to do with the errors shown... and "working for me" is totally unhelpful.

**Comment by parag90** [comment] 2016-04-06 04:45
@testingcode This has nothing to do with xvfb, I downgraded Firefox version to 43 and things are working for me. Seems the lastest firefox (V45) is not yet added in Selenium

**Comment by testingcode** [comment] 2016-04-06 05:27
Apologies, Thanks for the update.

**Comment by andrey2good** [comment] 2016-04-06 06:14
downgraded to ff44 and ff43. Still getting the above error. In addition found the following line. 
`org.openqa.selenium.WebDriverException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
addons.manager	DEBUG	Application has been upgraded
addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
addons.manager	DEBUG	Starting provider: XPIProvider
addons.xpi	DEBUG	startup
addons.xpi	DEBUG	Ignoring file entry whose name is not a valid add-on ID: /tmp/anonymous8013879722049145070webdriver-profile/extensions/webdriver-staging
addons.xpi	INFO	Mapping fxdriver@googlecode.com to /tmp/anonymous8013879722049145070webdriver-profile/extensions/fxdriver@googlecode.com
addons.xpi	INFO	SystemAddonInstallLocation directory is missing
addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /usr/local/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}
addons.xpi	DEBUG	checkForChanges
addons.xpi	DEBUG	Loaded add-on state from prefs: {}
addons.xpi	DEBUG	New add-on fxdriver@googlecode.com in app-profile
addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}`

Can someone give me a workaround ?

**Comment by ranjith36** [comment] 2016-04-07 14:59
facing same issue!!

**Comment by OLibutzki** [comment] 2016-04-15 11:10
After updating to Selenium WebDriver 2.53.0 I encounter this issue, too. Does anyone know which change is responsible for this regression?

**Comment by remcowesterhoud** [comment] 2016-04-19 08:10
Got this same problem. For me it only seems to occur when I'm running multiple instances of firefox at the same time on 1 node

**Comment by mittt** [comment] 2016-04-27 13:19
I'm getting the same issue. My setup is running 13 tests one after the other and if the driver init fails (new WebDriver()) it retrys 3 time with 90s delay between retrys.

The strange thing is the first ~7 of tests fail, but magically FF starts working for the remaining tests. So the driver starts working after many retryes: 7*3 for example. My tests are run every night, but this does not happen every time.

ALSO The same thing is happening with the IE driver, but there, naturally,  the error looks differently: "System.InvalidOperationException: The process has not exited yet therefore no result is available ..."

The thing I have notices is that this behavior is limited only to my Windows 7 machines, but i can't be sure of it.

WebDriver 2.53.0 Node with FF 45.0.2

Please advice. Maybe I should file a separate issus?

**Comment by pgandarillas** [comment] 2016-06-22 14:42
Hi! Is there any update on this I'm using Selenium Webdriver 2.53 and just found out about marionnette driver to handle FF45+ I download it and added to my ruby bin path. Now I'm getting this error: unable to connect to Mozilla geckodriver 127.0.0.1:4444

**Comment by lukeis** [comment] 2016-10-26 17:59
are people still having an issue with 45 ESR here?

Note that in 48+ one must use GeckoDriver.

If you are using 45 + selenium 3.0, you need to make sure you are disabling marionette.

**Comment by psbanka** [comment] 2016-12-20 18:26
I have this issue with Firefox 50 and Selenium 2.53.1. This is on an Ubuntu `16.04` image using xvfb. If I downgrade Firefox to 35 the issue disappears.

**Comment by reach2jeyan** [comment] 2017-01-13 21:37
I am having the same issue too `unable to connect to Mozilla geckodriver 127.0.0.1:4445 (Selenium::WebDriver::Error::WebDriverError)

When I launch the geckodriver installer `1484342822479   geckodriver     INFO    Listening on 127.0.0.1:4444`

**Comment by Gladdy23** [comment] 2017-01-19 17:54
unable to connect to Mozilla geckodriver 127.0.0.1:4444 - getting this error does any one have a work around this ???

**Comment by cgoldberg** [comment] 2017-01-19 19:15
@Gladdy23 without more information, it's unlikely anyone can help you.

**Comment by Gladdy23** [comment] 2017-01-19 20:05
@cgoldberg - I have installed - selenium-cucumber-3.1.5 and selenium Webdriver - when i am trying to just test on locally i keep getting this error first it said download - geckodriver - and then said to add it to my path which i did after which when i am trying to run test using - cucumber i keep getting  this msg - unable to connect to Mozilla geckodriver 127.0.0.1:4444 - getting this error does any one have a work around this ??? please let me know if you need any more information - maybe i missed something

**Comment by twalpole** [comment] 2017-01-19 22:34
@Gladdy23 What versions of FF and selenium-webdriver are you using?

**Comment by reach2jeyan** [comment] 2017-01-20 03:56
@Gladdy23 : Place the required driver in the lib folder of ruby file or the lib folder of whatever programming language you have installed in ur pc.

**Comment by Gladdy23** [comment] 2017-01-20 13:42
@twalpole FireFox Version is 50 and selenium-webdriver is - 3.0.5

**Comment by reach2jeyan** [comment] 2017-01-20 13:46
@Gladdy23 I had the same issue, when I was automating a website in Mozilla. I placed the geckodriver in the lib folder of ruby and it started to work.

**Comment by Gladdy23** [comment] 2017-01-20 13:48
@reach2jeyan Thanks bud i will give that shot and see if it get me going

**Comment by reach2jeyan** [comment] 2017-01-20 13:49
@Gladdy23 Sure, let me know!

**Comment by Gladdy23** [comment] 2017-01-20 14:21
@reach2jeyan thanks for the suggestion  i added the geckodriver to the lib path .rvm/src/ruby-2.1.10/lib  and now its keeps saying that cannot load such file  selenium-cucumber (LoadError) any thoughts

**Comment by reach2jeyan** [comment] 2017-01-20 15:43
@gladdy23: So the geckodriver error is gone?

**Comment by reach2jeyan** [comment] 2017-01-20 15:44
Must be an issue with versions of selenium-webdriver. Can u uninstall the gem and go to rubygems.org and again reinstall the same? In the correct project folder

**Comment by Gladdy23** [comment] 2017-01-20 18:06
@reach2jeyan Thanks for the stepping in a and helping me - got it to work i used the old version of selenium gem thanks again @reach2jeyan

**Comment by reach2jeyan** [comment] 2017-01-20 19:00
@gladdy23: Awesome. :)

**Comment by jbarbera** [comment] 2017-09-29 11:19
Didn t work for me , i ve placed geckodriver in several places /usr/local/bin /usr/share/rvm/rubies/ruby-2.3.0/lib/  but still getting same message.  Firefox 55 selenium-webdriver 3.5.1 .  Any clue on that, with chrome there are no problems

**Comment by p0deje** [comment] 2017-09-29 15:11
Closing since it's not clear what to do.

Please re-open if issue still present on recent Selenium version.

**Closed by p0deje** 2017-09-29 15:11 UTC
Labels: D-firefox
