### ISSUE TITLE
On a screenshot with scroll, the Bootstrap Navbar overlaps a selected element

### ISSUE THREAD

**Issue by estefafdez** [SeleniumHQ/selenium#1687] opened 2016-02-23 14:57 UTC
## Expected Behavior -

The Bootstrap element Navbar is a fixed element on top of the page.

## Actual Behavior -
When a screenshot with scroll is made, the Navbar overlaps a selected element, which makes the element no longer visible or clickable. 

## Steps to reproduce -

1. You have a Bootstrap Navbar on the top of your webpage. 
2. In a page with lot of content, scroll down to check some elements on the bottom of the page. 
3. Try to access to an element near the top of the page, which is not currently visible
4. The element couldn't be found, a screenshot is made, the Navbar overlaps the element. 

The problem appears on a Slave with Windows Server 2008 (Webdriver: 2.52.0 and FF 44.0.2). On our localhost (Windows 7, Webdriver: 2.52.0 and FF 44.0.2) this problem cannot be reproduced. 

![navbarelementhidden](https://cloud.githubusercontent.com/assets/6990209/13255347/17430bba-da46-11e5-8811-de36b47af7d1.png)

**Comment by lukeis** [comment] 2016-02-23 16:21
Please provide either an example website url or provide a sample html document to reproduce the issue.

**Comment by jmrg82** [comment] 2016-03-02 17:01
Hi @lukeis 
It's hard to give you an URL, because this is happening in testing environments, but we can give you the webdriver log (based on listeners) and some screenshots, even videos.

More info: 
This is reproduced in different versions of firefox, different versions of webdriver, different OS (Win server 2008 and Win7 in local), different values for capability "elementScrollBehavior" (0/1)
And recently we found that this is also happening in different apps... that's why we think it's a webdriver bug.

But there are some common elements: long pages with vertical scroll and a fixed top-bar. When we scroll down to an element, all the page scrolls, but this fixed bar, do not disappear, and if we try to access to a new element, positioned above the scroll, webdriver does not find it, and creates a screenshot in which it looks like the constant element (the black top-bar) is moved.

I attach you some files and I hope this will help you understand the problem (and find a solution!)

[Scroll_Bug.zip](https://github.com/SeleniumHQ/selenium/files/155245/Scroll_Bug.zip)

Thank you very much.

**Comment by lukeis** [comment] 2016-03-02 17:12
@jmrg82 sadly screenshots and video's don't help. We need the HTML / Javascript / CSS associated to the page to figure out what's going wrong. Simply doing a "File -> Save Page As..." and providing all the files that generates would help. Or even better would be to recreate a small sample html page that reproduces the problem.

**Comment by jmrg82** [comment] 2016-03-02 17:53
OK, you can find the save page in the attached zip, inside BlueKiwi folder: web_example.7z
The rest of files only can help you to better understand the problem (which we know it's quite weird).
If this does not help, please contact me and we'll try to find a better way to reproduce the issue.
Thanks!!

**Comment by estefafdez** [comment] 2016-03-03 09:08
Hello @lukeis. We notice that the problem can be reproduced on Windows 10 using Microsoft Edge as browser, so, it's not only a Firefox problem. Did the code help you to understand better the problem?

**Comment by pkastner** [comment] 2016-03-04 10:19
It think I run into the same / similar issue today.

## Expected Behavior
Scrolling should be automatically handled by selenium, the correct button gets clicked and you would land on the navbar docs page (https://getbootstrap.com/components/#navbar)

## Actual Behavior
The following exception gets thrown
`org.openqa.selenium.WebDriverException: Element is not clickable at point (289.5, 23.300003051757812). Other element would receive the click: <a href="#"></a>`

(For Chrome it is the same, IE just clicks on the navbar Home item instead of the correct button)

## Steps to reproduce
Short Java snippet to reproduce the problem:
```Java
WebDriver driver = new FirefoxDriver();
driver.get("https://getbootstrap.com/examples/navbar-fixed-top/");
// scroll to bottom of page, same effect as when you would interact with an element down the page
((JavascriptExecutor) driver).executeScript("window.scrollTo(0,document.body.scrollHeight);");		
driver.findElement(By.linkText("View navbar docs »")).click();
```

**Comment by lukeis** [comment] 2016-03-07 23:56
so with the case where the page is scrolled down, but the element to be clicked upon is 'above' in the page, selenium first scrolls the element into view, but because of the top nav bar it is still hidden. In this case using the DesiredCapability "elementScrollBehavior" and setting it to 1 (or any non- 0 value) should have the behavior of scrolling the element to the bottom of the page (or as far down as possible).

If that doesn't work for your situation... you can manually scroll the window to a known location where the element isn't overlapped by the fixed header (see the previous comment with how to do that with execute script).

Selenium can only do so much to attempt to get the element into view and we can't try to auto detect fixed menu bars (there's too many different ways they could manifest itself). So for now, i'm going to close the issue as it's not feasible for selenium to handle all the edge cases here and one should take care to scroll the element into view themselves when these edge cases arise.

**Closed by lukeis** 2016-03-07 23:56 UTC
Labels: D-firefox
