### ISSUE TITLE
Error 403 Forbidden for Proxy

### ISSUE THREAD

**Issue by miguelmota** [SeleniumHQ/selenium#2154] opened 2016-05-23 22:06 UTC
## Meta -
OS:  OSX El Capitan 10.11.13
Selenium Version:  
wdio v4.0.7
Browser:  
Firefox
Browser Version:  
46.0.1

## Expected Behavior -

should run test

## Actual Behavior -

```
ERROR: <html>
<head>
<title>Error 403 Forbidden for Proxy</title>
</head>
<body>
<h2>HTTP ERROR: 403</h2><pre>Forbidden for Proxy</pre>
<p>RequestURI=/session</p>
<p><i><small><a href="http://jetty.mortbay.org">Powered by Jetty://</a></small></i></p>
</body>
</html>
```

## Steps to reproduce -

Test file

```javascript
const assert = require('assert');

describe(`test`, function() {
  it('ok', function() {
    assert.ok(true);
  });
});

module.exports = null;
```

```
./node_modules/.bin/wdio wdio.config.js
```

```
exports.config = {
  specs: [
    `./test/index.js`
  ],
  maxInstances: 10,
  path: '/',
  capabilities: [{
    browserName: `firefox`
  }],
  sync: true,
  logLevel: `error`,
  coloredLogs: true,
  screenshotPath: `./errorShots/`,
  baseUrl: `http://localhost:3000`,
  waitforTimeout: 15000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  mochaOpts: {
    ui: `bdd`
  }
};

**Comment by jleyba** [comment] 2016-05-24 03:46
Closing this issue since it depends on a library we don't maintain (`wdio`). Feel free to refile with a reproducible test case using an officially supported selenium client.

**Closed by jleyba** 2016-05-24 03:46 UTC
