### ISSUE TITLE
[🐛 Bug]: Local Nodes no longer connect to local Hub for some reason

### ISSUE THREAD

**Issue by tking16** [SeleniumHQ/selenium#13621] opened 2024-02-23 11:38 UTC
### What happened?

Setting up Selenium Grid on my mac machine around 2 months ago, everything has been connecting without issue. Now all of a sudden the hub will refuse to register any nodes (these are all done on localhost), output logs just spit out:

```
14:51:35.259 ERROR [NodeServer$1.lambda$start$1] - Node is not alive: http://10.63.141.23:5565/ is DOWN
14:52:21.010 WARN [RelaySessionFactory.isServiceUp] - Error checking service status http://localhost:4733/status. java.io.IOException: HTTP/1.1 header parser received no bytes
14:52:35.203 WARN [RelaySessionFactory.isServiceUp] - Error checking service status http://localhost:4733/status. java.io.IOException: HTTP/1.1 header parser received no bytes
```
Not sure it's a firewall issue, everything seems to be allowed on the domain
![Screenshot 2024-02-23 at 11 21 07](https://github.com/SeleniumHQ/selenium/assets/13576824/148f5485-02a5-4285-a2c8-cce77c662342)

### How can we reproduce the issue?

```shell
Follow this guide to the letter https://appium.io/docs/en/2.1/guides/grid/
```

### Relevant log output

```shell
14:51:35.259 ERROR [NodeServer$1.lambda$start$1] - Node is not alive: http://10.63.141.23:5565/ is DOWN
14:52:21.010 WARN [RelaySessionFactory.isServiceUp] - Error checking service status http://localhost:4733/status. java.io.IOException: HTTP/1.1 header parser received no bytes
14:52:35.203 WARN [RelaySessionFactory.isServiceUp] - Error checking service status http://localhost:4733/status. java.io.IOException: HTTP/1.1 header parser received no bytes
```
```


### Operating System

Mac OS Sonoma 14.3.1

### Selenium version

4.18.1 (same issue on 4.16.1)

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

XCUITest

### Are you using Selenium Grid?

4.18.1 - Selenium Server

**Comment by diemol** [comment] 2024-02-23 11:44
Duplicate of #13481

**Closed as not planned by diemol** 2024-02-23 11:44 UTC
Labels: I-defect, A-needs-triaging
