### ISSUE TITLE
OpenQA.Selenium.Support.UI.SelectElement vanished in 4.0.0-alpha04

### ISSUE THREAD

**Issue by BasHamer** [SeleniumHQ/selenium#7944] opened 2020-01-17 23:07 UTC
## 🐛 Bug Report

SelectElement  does not appear in the namespace OpenQA.Selenium.Support.UI.SelectElement downgrading to 4.0.0-alpha03 makes it show up.

to reproduce

```
class foo {
protected OpenQA.Selenium.Support.UI.SelectElement OldStyleSelect { get; set;}
}
```

OS: Windows 10
Browser: n/a
Browser version: n/a
Browser Driver version: n/a
Language Bindings version: C# netstandard 2.0
Selenium Grid version (if applicable): n/a

**Comment by InkUisitor** [comment] 2020-01-23 09:22
Hi,
The Nuget package is empty for the alpha04. The problem is the same with .net 45/46/47.
The SelectElement is still in the project so the problem is in the package generation.

**Comment by InkUisitor** [comment] 2020-01-23 09:34
You can use this nuget package, the one that is currently published is not correct

[Selenium.Support.4.0.0.nupkg.zip](https://github.com/SeleniumHQ/selenium/files/4102287/Selenium.Support.4.0.0.nupkg.zip)

**Comment by BasHamer** [comment] 2020-01-23 15:01
I'll stick w/ 4.03; thank you.

The new logo looks good tough.

**Comment by Exoow** [comment] 2020-01-30 08:19
Was going to post the same for EventFiringWebDriver. Thanks for the info.

**Comment by nexocentric** [comment] 2020-02-28 18:51
> You can use this nuget package, the one that is currently published is not correct
> 
> [Selenium.Support.4.0.0.nupkg.zip](https://github.com/SeleniumHQ/selenium/files/4102287/Selenium.Support.4.0.0.nupkg.zip)

Is it possible to upload this package to NuGet for consumption?

**Comment by jimevans** [comment] 2020-11-10 18:09
As far as I'm aware, this issue has been fixed in the .NET build process. If you run into other issues, please raise a new issue.

**Closed by jimevans** 2020-11-10 18:09 UTC
Labels: C-dotnet
