### ISSUE TITLE
[🐛 Bug]: v4.16.1 Not able to open a browser with NoSuchDriverException

### ISSUE THREAD

**Issue by letskodeit** [SeleniumHQ/selenium#13263] opened 2023-12-07 15:10 UTC
### What happened?

I have written a very simple code on my Windows system to open a browser and it is not working with any browser, ex: Chrome or Edge when I am using version 4.16.1

**The same code is working without any issues with version 4.11.0 and 4.15.0**

### How can we reproduce the issue?

```shell
Here is the simple code:

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;

public class MSEdgeDriverDemo {
	public static void main(String[] args) {
		
		WebDriver driver = new EdgeDriver();
		driver.manage().window().maximize();
		driver.get("https://www.letskodeit.com");
		driver.quit();
	}
}
```

### Relevant log output

```shell
Here are the errors:

Exception in thread "main" org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [], extensions: []}}, error Command failed with code: -1073741701, executed: [--browser, MicrosoftEdge, --output, json]

Build info: version: '4.16.0', revision: '15400459dd*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: EdgeDriver
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:25)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:13)
	at org.openqa.selenium.edge.EdgeDriver.generateExecutor(EdgeDriver.java:72)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:61)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:57)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:49)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:45)
	at basicweb.MSEdgeDriverDemo.main(MSEdgeDriverDemo.java:9)
Caused by: org.openqa.selenium.WebDriverException: Command failed with code: -1073741701, executed: [--browser, MicrosoftEdge, --output, json]

Build info: version: '4.16.0', revision: '15400459dd*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: EdgeDriver
	at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:157)
	at org.openqa.selenium.manager.SeleniumManager.getDriverPath(SeleniumManager.java:299)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:22)
	... 7 more
```

### Operating System

Windows

### Selenium version

Java 4.16.1

### What are the browser(s) and version(s) where you see this issue?

Edge Version 119.0.2151.97 and Chrome Version 119.0.6045.200

### What are the browser driver(s) and version(s) where you see this issue?

Using Selenium latest version to download drivers automatically

### Are you using Selenium Grid?

N/A

**Comment by titusfortner** [comment] 2023-12-07 18:30
duplicate of #13261

**Closed as not planned by titusfortner** 2023-12-07 18:30 UTC
Labels: I-defect, A-needs-triaging, J-logging

**Comment by letskodeit** [comment] 2023-12-07 19:13
@titusfortner 
Can you please let me know how to enable logging?
I referred to the documentation and tried to enable. I followed these steps:

1. Downloaded the dependency using this:
```
<dependency>
  <groupId>com.titusfortner</groupId>
  <artifactId>selenium-logger</artifactId>
  <version>2.3.0</version>
</dependency>
```

2. Added this line in the code before initializing the driver
`SeleniumLogger.enable();`

Example:
```
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;

import com.titusfortner.logging.SeleniumLogger;

public class MSEdgeDriverDemo {
	public static void main(String[] args) {
		
		SeleniumLogger.enable();
		
		WebDriver driver = new EdgeDriver();
		driver.manage().window().maximize();
		driver.get("https://www.letskodeit.com");
		driver.quit();
	}
}
```

I still see the same error in Console:

```
2023-12-07 11:12:26 FINE Selenium [SeleniumManager getBinary] Selenium Manager binary found at: C:\Users\aniltomar\.cache\selenium\manager\0.4.16\selenium-manager.exe 
2023-12-07 11:12:26 FINE Selenium [SeleniumManager runCommand] Executing Process: [--browser, MicrosoftEdge, --output, json, --debug] 
2023-12-07 11:12:27 FINE Selenium [ExternalProcess] completed to copy the output of process 4848 
Exception in thread "main" org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [], extensions: []}}, error Command failed with code: -1073741701, executed: [--browser, MicrosoftEdge, --output, json, --debug]

Build info: version: '4.16.1', revision: '9b4c83354e'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: EdgeDriver
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:25)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:13)
	at org.openqa.selenium.edge.EdgeDriver.generateExecutor(EdgeDriver.java:72)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:61)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:57)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:49)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:45)
	at basicweb.MSEdgeDriverDemo.main(MSEdgeDriverDemo.java:12)
Caused by: org.openqa.selenium.WebDriverException: Command failed with code: -1073741701, executed: [--browser, MicrosoftEdge, --output, json, --debug]

Build info: version: '4.16.1', revision: '9b4c83354e'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: EdgeDriver
	at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:157)
	at org.openqa.selenium.manager.SeleniumManager.getDriverPath(SeleniumManager.java:299)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:22)
	... 7 more
```

**Comment by titusfortner** [comment] 2023-12-07 20:47
Oh, ok, so Selenium Manager isn't even starting. This failure is before it starts logging anything.

**Comment by dj-luis198** [comment] 2023-12-10 15:36
install VC++ redistributable x86 solves the problem.

**Comment by letskodeit** [comment] 2023-12-10 15:43
@titusfortner @dj-luis198 

Does it mean `4.15 version` doesn't need `Visual C++ Redistributable for Visual Studio 2015-2022`?

**Comment by anjalivaswani8614** [comment] 2023-12-22 10:25
I'm facing the similar issue however for me SeleniumManager Exe is not even getting downloaded. Im working behind the proxy and browser is not getting launched. 


Here is the issue:
 I'm facing the issue where getting the error: org.openqa.selenium.WebDriverException: Unable to obtain Selenium Manager Binary at: C:\Users.cache\selenium\manager\0.4.16\selenium-manager.exe
Build info: version: '4.16.1', revision: '9b4c83354e'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.9'
Driver info: driver.version: unknown
at org.openqa.selenium.manager.SeleniumManager.getBinary(SeleniumManager.java:210)
at org.openqa.selenium.manager.SeleniumManager.getDriverPath(SeleniumManager.java:253)

Browser is not launching .
ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.setCapability("goog:chromeOptions", true);
chromeOptions.addArguments("--no-sandbox");
chromeOptions.addArguments("--remote-allow-origins=*");
chromeOptions.addArguments("--ignore-certificate-errors");
chromeOptions.addArguments("--proxy-server=http://",PROXY_URL_STRING);
chromeOptions.addArguments("--proxy=http://",PROXY_URL);
chromeOptions.addArguments("--start-maximized");

    ChromeOptions ChromeOpt = new ChromeOptions();
    // Pass the ChromeOpt option it takes as a type of Capability.
    String chromeDriverPath = String.valueOf(SeleniumManager.getInstance().getDriverPath(chromeOptions,false));
    System.out.println("chromeDriverPath--" + chromeDriverPath);

    return this.driver= new ChromeDriver(chromeOptions);

Many times selenium chrome driver exe is not getting downloaded without using WebDriver Manager.

**Comment by diemol** [comment] 2023-12-22 10:27
As I replied in the other issue you opened, please use Nightly as a workaround https://www.selenium.dev/downloads/#nightly
