### ISSUE TITLE
[🐛 Bug]:  	ReadTimeoutError: HTTPConnectionPool(host='*.*.*.*', port=80): Read timed out. (read timeout=<object object at 0x7f6cc4b3d270>)

### ISSUE THREAD

**Issue by helloworld213** [SeleniumHQ/selenium#11482] opened 2022-12-26 03:40 UTC
### What happened?

my selenium grid is one hub（8CPUs 16G MEM） ,and 18*node (16CPUs 48G MEM),for example : Open 200 browsers, and often report a timeout error during the opening process. For example, when opening the 20th browser, sometimes it will be the 188th, and sometimes it will all pass, but the probability of errors is very high

Config for the hub : 
browserTimeout : 36000
debug : false
log : ./log/selenium-hub-20221213-103100.log
host : 192.168.122.1
port : 80
role : hub
timeout : 36000
cleanUpCycle : 5000
maxSession : 900
capabilityMatcher : org.openqa.grid.internal.utils.DefaultCapabilityMatcher
newSessionWaitTimeout : -1
throwOnCapabilityNotPresent : true
registry : org.openqa.grid.internal.DefaultGridRegistry
==========================================
**node config:**
browserTimeout: 39000

debug: false

host: nodeip

port: 23318

role: node

timeout: 36000

cleanUpCycle: 5000

maxSession: 90

capabilities: Capabilities {browserName: firefox, maxInstances: 4, platform: LINUX, platformName: LINUX, seleniumProtocol: WebDriver, server:CONFIG_UUID: f5dbec89-6990-4688-b5e2-e5e...}

capabilities: Capabilities {browserName: chrome, maxInstances: 64, platform: LINUX, platformName: LINUX, seleniumProtocol: WebDriver, server:CONFIG_UUID: 3296bdf5-c83c-4e67-bb8d-caa..., version: ANY}

downPollingLimit: 2

hub: http://hubip:80/grid/register/

id: http://nodeip:23318

nodePolling: 5000

nodeStatusCheckTimeout: 5000

proxy: org.openqa.grid.selenium.proxy.DefaultRemoteProxy

register: true

registerCycle: 5000

remoteHost: http://nodeip:23318

unregisterIfStillDownAfter: 60000

### How can we reproduce the issue?

```shell
I dispatch use cases through the keywords of robtoframework, and the keywords that report errors are:Selenium2Library . Capture Page Screenshot
```

### Relevant log output

```shell
ReadTimeoutError: HTTPConnectionPool(host='*.*.*.*', port=80): Read timed out. (read timeout=<object object at 0x7f6cc4b3d270>) in keyword :Selenium2Library . Capture Page Screenshot,No more detailed error reported
```

### Operating System

centos8

### Selenium version

3.141.59

### What are the browser(s) and version(s) where you see this issue?

Google Chrome 97.0.4692.71

### What are the browser driver(s) and version(s) where you see this issue?

97.0.4692.71

### Are you using Selenium Grid?

3.141.59

**Comment by pujagani** [comment] 2022-12-26 06:03
Thank you for sharing the details. The version being used is the old one. We no longer do patch releases to an older version. Please try to use the latest version and see if the error still persists. We will also require a reproducible test script/repo that relies on Selenium and can be supported at a smaller scale to reproduce the issue since the Grid described is being operated at scale. 
Also, the timeout in creating a process to open the browser is most likely related to the resources available.

**Comment by helloworld213** [comment] 2022-12-26 07:30
thanks for answering,  i try the version:4.4.0 ,Still will report timeout error，when testing, iResource monitoring with grafna, and usage are relatively low

**Comment by pujagani** [comment] 2022-12-26 07:48
4.7.2 is the latest version

**Comment by diemol** [comment] 2022-12-27 20:05
I am going to close this and treat this as a question because migrating from Grid 3 to 4 cannot be pointed to a single issue. Please go through the docs for [Grid 4](https://www.selenium.dev/documentation/grid/) and we are happy to solve questions through the links shown below.

**Closed as completed** 2022-12-27 20:05 UTC
Labels: B-grid, I-defect, J-issue-template, I-question
