### ISSUE TITLE
[🐛 Bug]: Unable to obtain: Capabilities, error=26, Text file busy using multiple gradle proccesses 

### ISSUE THREAD

**Issue by namuller30** [SeleniumHQ/selenium#13145] opened 2023-11-13 15:20 UTC
### What happened?

I'm seeing the following error occasionally while running UI tests in our CI pipeline, we are using java and running tests with gradle.  We have the maxParrallelForks set to 3 in our gradle test so my understanding is that 3 independent jvms are started that run a subset of tests.  My guess is that since 3 processes are trying to install / access the driver binary they are fighting with each other and causing this error.  I'm wondering if a file lock should be required before reading / writing the driver binary

`org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browserName: chrome, goog:chromeOptions: {args: [--no-sandbox, --headless, --host-resolver-rules=MAP d..., --remote-allow-origins=*], extensions: []}}, error Failed to run command: [--browser, chrome, --output, json]
08:57:27     Build info: version: '4.15.0', revision: '1d14b5521b'
08:57:27     System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.42.2.el7.x86_64', java.version: '17.0.9'
08:57:27     Driver info: driver.version: ChromeDriver
08:57:27         at app//org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:25)
08:57:27         at app//org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:13)
08:57:27         at app//org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:100)
08:57:27         at app//org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:89)
08:57:27         at app//org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84)
08:57:27         at app//org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:73)
08:57:27         at Script_ffa20a3ace57d727e2a95e189a1edea5$_run_closure2.closure6$_closure9(Script_ffa20a3ace57d727e2a95e189a1edea5.groovy:74)
08:57:27         at app//groovy.lang.Closure.call(Closure.java:427)
08:57:27         at app//groovy.lang.Closure.call(Closure.java:416)
08:57:27         at app//groovy.lang.GString.writeTo(GString.java:194)
08:57:27         at app//groovy.lang.GString.toString(GString.java:157)
08:57:27         at app//geb.error.GebException.<init>(GebException.groovy:24)
08:57:27         at app//geb.driver.CallbackDriverFactory.getDriver(CallbackDriverFactory.groovy:35)
08:57:27         at geb.driver.CachingDriverFactory.getDriver_closure4(CachingDriverFactory.groovy:57)
08:57:27         at geb.driver.CachingDriverFactory.getDriver_closure4(CachingDriverFactory.groovy)
08:57:27         at app//geb.driver.CachingDriverFactory$ThreadLocalCache.get(CachingDriverFactory.groovy:99)
08:57:27         at app//geb.driver.CachingDriverFactory.getDriver(CachingDriverFactory.groovy:56)
08:57:27         at app//geb.Configuration.createDriver(Configuration.groovy:700)
08:57:27         at app//geb.Configuration.getDriver(Configuration.groovy:377)
08:57:27         at app//geb.Browser.getDriver(Browser.groovy:163)
08:57:27         at app//geb.navigator.factory.BrowserBackedNavigatorFactory.<init>(BrowserBackedNavigatorFactory.groovy:32)
08:57:27         at app//geb.Configuration.createNavigatorFactory(Configuration.groovy:436)
08:57:27         at app//geb.Browser.createNavigatorFactory(Browser.groovy:1009)
08:57:27         at app//geb.Browser.getNavigatorFactory(Browser.groovy:173)
08:57:27         at app//geb.Page.init(Page.groovy:141)
08:57:27         at app//geb.Browser.initialisePage(Browser.groovy:1147)
08:57:27         at app//geb.Browser.createPage(Browser.groovy:825)
08:57:27         at app//geb.Browser.getPage(Browser.groovy:142)
08:57:27         at app//geb.Browser.methodMissing(Browser.groovy:226)
08:57:27         at app//geb.spock.GebSpec.methodMissing(GebSpec.groovy:1)
08:57:27         at app//common.BaseWebAdminSpec.setupSpec(BaseWebAdminSpec.groovy:85)
08:57:27 
08:57:27         Caused by:
08:57:27         org.openqa.selenium.WebDriverException: Failed to run command: [--browser, chrome, --output, json]
08:57:27         Build info: version: '4.15.0', revision: '1d14b5521b'
08:57:27         System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.42.2.el7.x86_64', java.version: '17.0.9'
08:57:27         Driver info: driver.version: ChromeDriver
08:57:27             at app//org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:133)
08:57:27             at app//org.openqa.selenium.manager.SeleniumManager.getDriverPath(SeleniumManager.java:287)
08:57:27             at app//org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:22)
08:57:27             ... 30 more
08:57:27 
08:57:27             Caused by:
08:57:27             java.io.UncheckedIOException: java.io.IOException: Cannot run program "/root/.cache/selenium/manager/0.4.15/selenium-manager": error=26, Text file busy
08:57:27                 at org.openqa.selenium.os.ExternalProcess$Builder.start(ExternalProcess.java:193)
08:57:27                 at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:125)
08:57:27                 ... 32 more
08:57:27 
08:57:27                 Caused by:
08:57:27                 java.io.IOException: Cannot run program "/root/.cache/selenium/manager/0.4.15/selenium-manager": error=26, Text file busy
08:57:27                     at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
08:57:27                     at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
08:57:27                     at org.openqa.selenium.os.ExternalProcess$Builder.start(ExternalProcess.java:191)
08:57:27                     ... 33 more
08:57:27 
08:57:27                     Caused by:
08:57:27                     java.io.IOException: error=26, Text file busy
08:57:27                         at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
08:57:27                         at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
08:57:27                         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
08:57:27                         ... 35 more`

### How can we reproduce the issue?

```shell
this does not happen consistently so I don't have a good way to reproduce :(
```

### Relevant log output

```shell
can grab if needed
```

### Operating System

docker on linux

### Selenium version

java 17.

### What are the browser(s) and version(s) where you see this issue?

chrome 119

### What are the browser driver(s) and version(s) where you see this issue?

selenium manager

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment] 2023-11-13 16:27
@bonigarcia do we need to do something more to make sure that only one process is using the binary at a time? Or add automatic retries?

**Comment by bonigarcia** [comment] 2023-11-13 17:38
This error seems related to #13091. We are troubleshooting it.

**Comment by titusfortner** [comment] 2023-11-13 17:46
Let's call this a duplicate of #13091 and if the solution we find for that one doesn't fix this one, we can re-open.

**Closed as not planned by titusfortner** 2023-11-13 17:46 UTC
Labels: C-java, I-defect
