### ISSUE TITLE
IEDriverServer.exe error: "Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host."

### ISSUE THREAD

**Issue by riaalexmoiceanu** [SeleniumHQ/selenium#3124] opened 2016-11-17 09:37 UTC
**OS:**  Windows 8.1
**Selenium Version:**  Selenium WebDriver 3.0.0.0(NuGet package)
**Browser:**  InternetExplorer 11.0.9600.18525
**WebDriverIEDriver:** v.2.45.0  (NuGet package)

## Expected Behavior -
Should not throw a "Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host." error. It should work like on Chrome or Firefox.
The same test suite runs without problems on Chrome and Firefox.

## Actual Behavior -
Throws the following error: "Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host."

## Steps to reproduce -
1. Run some automated tests on IE 11
2. At some point, the test run will crash and it will return the following error:

**_Result StackTrace:	
at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Click()
   at ...:line 34
   at ... in ...:line 33
--WebException
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
--IOException
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Connection.SyncRead(HttpWebRequest request, Boolean userRetrievedStream, Boolean probeRead)
--SocketException
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
--TearDown
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.GetScreenshot()
   at ... in ...line 27
   at ... in C...:line 212
--WebException
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
--SocketException
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
Result Message:	
OpenQA.Selenium.WebDriverException : A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:40139/session/2f536599-92e4-49ad-aeee-284602e98973/element/8c416f32-11ed-4215-a817-4cdfd2261f33/click. The status of the exception was ReceiveFailure, and the message was: The underlying connection was closed: An unexpected error occurred on a receive.
  ----> System.Net.WebException : The underlying connection was closed: An unexpected error occurred on a receive.
  ----> System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
  ----> System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
TearDown : OpenQA.Selenium.WebDriverException : A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:40139/session/2f536599-92e4-49ad-aeee-284602e98973/screenshot. The status of the exception was ConnectFailure, and the message was: Unable to connect to the remote server
  ----> System.Net.WebException : Unable to connect to the remote server
  ----> System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it 127.0.0.1:40139_**

**Comment by Vadimyan** [comment] 2018-01-10 21:58
I have the same issue with Google Chrome for the last month.

**Comment by diemol** [comment] 2020-05-21 10:18
Apologies for the poor handling of this issue on our side. Since no reproduction scenario with clear and detailed steps was provided, or an automated script to reproduce the issue is present, I will close this issue.

In any case, if the issue is still present with the latest versions of Selenium WebDriver and IE driver, please open a new issue with all the required information filled out.

**Closed by diemol** 2020-05-21 10:18 UTC
Labels: C-dotnet, D-IE
