### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by amosrohe** [SeleniumHQ/selenium#13403] opened 2024-01-07 04:47 UTC
### What happened?

when trying to run selenium-manager.exe  i get 
![VmMnQ](https://github.com/SeleniumHQ/selenium/assets/53143420/0d7e8a5f-7d94-4707-9c35-7bee3e2f3f60)

application error

### How can we reproduce the issue?

```shell
run selenium-manager
```

### Relevant log output

```shell
Information	07/01/2024 6:44:12	Application Popup	26	None
Information	07/01/2024 6:43:50	Application Popup	26	None

- System 

  - Provider 

   [ Name]  Application Popup 
   [ Guid]  {47bfa2b7-bd54-4fac-b70b-29021084ca8f} 
 
   EventID 26 
 
   Version 0 
 
   Level 4 
 
   Task 0 
 
   Opcode 0 
 
   Keywords 0x8000000000000000 
 
  - TimeCreated 

   [ SystemTime]  2024-01-07T04:44:12.2923724Z 
 
   EventRecordID 97536 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  7460 
   [ ThreadID]  7844 
 
   Channel System 
 
   Computer Asus-Lap 
 
  - Security 

   [ UserID]  S-1-5-18 
 

- EventData 

  Caption selenium-manager.exe - Application Error 
  Message The application was unable to start correctly (0xc000007b). Click OK to close the application.
```

### Operating System

windows 11

### Selenium version

0.4.16

### What are the browser(s) and version(s) where you see this issue?

all browsers

### What are the browser driver(s) and version(s) where you see this issue?

all browsers

### Are you using Selenium Grid?

no

**Comment by diemol** [comment] 2024-01-07 06:30
This is a duplicate of https://github.com/SeleniumHQ/selenium/issues/13261, this is fixed in the next version (to be released).

**Closed as not planned by diemol** 2024-01-07 06:30 UTC
Labels: I-defect

**Comment by amosrohe** [comment] 2024-01-07 06:38
This is a **not** duplicate of https://github.com/SeleniumHQ/selenium/issues/13261, 
13261 talks on ChromeDriver 
this issue is that the selenium-manager.exe don't start

**Comment by diemol** [comment] 2024-01-07 06:39
It is, see comment:
https://github.com/SeleniumHQ/selenium/issues/13261#issuecomment-1846460373

**Comment by amosrohe** [comment] 2024-01-07 06:41
hi tnx I didnt see this comment:
