### ISSUE TITLE
Chrome driver not properly shut down if re-launched.

### ISSUE THREAD

**Issue by kurmasz** [SeleniumHQ/selenium#742] opened 2015-07-06 15:04 UTC
I have a scenario where the chrome driver for selenium is shutting down before cucumber's `at_exit` block calls it's `#quit` method.   As a result (1) The browser window is left open, and (2) The `#quit` method fails because it can't open a socket to the driver.

The stripped-down example below shows the problem: (The code below is RSpec only because it demonstrates the issue without adding the complexity of Cucumber.)

    require 'selenium-webdriver'
    
    RSpec.configure do |config|
       config.before(:suite) do
           $driver = Selenium::WebDriver.for :chrome
         end
     end
    
    describe "A potential rspec/selenium/chrome driver bug" do 
      it "doesn't play nice with at_exit" do    
        # quit the initial driver and start a new one.
        $driver.quit
        $driver = Selenium::WebDriver.for :chrome    
      end # it
    end # end describe
    
    at_exit do
      $driver.quit
    end

When I run the code above, I get the following error (on both MacOS 10.9.5 and CentOS)

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'

I instrumented the code with come calls to `ps`, and it appears that the chromedriver process is no longer running by the time the `at_exit` block runs.

Adding an `after(:suite)` block in RSpec fixes the problem; but, I don't think Cucumber has a comparable feature (users are simply told to use `at_exit`)

There is clearly a mechanism for shutting down the chrome driver if `#quit` is never called.  My guess is that mechanism is being activated before the `at_exit` block runs.

**Comment by p0deje** [comment] 2015-07-07 04:00
The reason this happens is because ChromeDriver is always killed in `at_exit` hook, but it happens to be called before your own `at_exit` hook, so ChromeDriver is dead and exception is thrown.

The sequence of events are:

1. You define at_exit hook to quit browser.
2. You start new driver.
3. Driver defines at_exit hook to quit itself.
4. Driver's at_exit hook is called.
5. Your at_exit hook is called.

This isn't a typical behavior and I'm not sure selenium-webdriver should handle it. With RSpec, as you mentioned, you'd use `after(:suite)`. With cucumber, since you don't have `:suite` hooks, you'd just start new driver outside any hooks and quit it in `at_exit`. If you start driver in `Before` hook, you need to handle it inside `After`.

In any case, I can dig more if you provide with Cucumber test case to reproduce (at least `env.rb` or `hooks.rb`).

P.S. This has nothing to do with driver quit and reopen in the middle of test.

**Comment by kurmasz** [comment] 2015-07-07 13:27
If I understand your sequence above (and the way `at_exit` hooks are called), the problem is because I launch a driver in the middle of the test.  A typical `env.rb` file looks something like this:

    $driver = Selenium::WebDriver.for :chrome, :switches => %w[--disable-cache --ignore-certificate-errors]

    at_exit do
      $driver.quit
    end

In this typical case, the driver is created (and registers it's own `at_exit`) before `env.rb` registers its `at_exit`.  As a result, `env.rb`'s `at_exit` is called first, shutting down the driver as expected.

If someone creates a driver inside a test (any driver, not necessarily a second/re-launched driver), then the driver's `at_exit` block runs first, which causes the `#quit` method to fail if called later. 

This raises two questions:

(1) The chomedriver's `at_exit` block does not close the browser window it opens.  Should it?  If I write a simple cucumber suite, but omit `at_exit` in `env.rb`, then the chomedriver process exits, but the Chrome window it opens remains (on MacOS 10.9.5 using Chrome 43.0.2357.130.)

(2) Should I need to relaunch chromedriver?  I am trying to verify that my web application behaves correctly when a javascript file containing data is deleted from the server.   Thus, the steps look like this:  (a) visit the page, (b) delete a file, (c) revisit the page.  If I don't quit and re-launch chromedriver, then the application behaves as if the file was never deleted.  I assume this is because the browser is caching the file.  The `--disable-cache` doesn't change this behavior.

If both observed behaviors are correct, then I suggest either (1) having the chromedriver's `at_exit` close the browser window, or (2) allowing the user to suppress the chomedriver's `at_exit` hook.

**Comment by p0deje** [comment] 2015-07-07 17:20
> If someone creates a driver inside a test (any driver, not necessarily a second/re-launched driver), then the driver's at_exit block runs first, which causes the #quit method to fail if called later.

That's correct.

> (1) The chomedriver's at_exit block does not close the browser window it opens. Should it? If I write a simple cucumber suite, but omit at_exit in env.rb, then the chomedriver process exits, but the Chrome window it opens remains (on MacOS 10.9.5 using Chrome 43.0.2357.130.)

This is controlled by `detach` ChromeDriver option (which is set to `true` by default). See [Chrome capabilities](https://sites.google.com/a/chromium.org/chromedriver/capabilities).

**Comment by kurmasz** [comment] 2015-07-07 18:41
I agree that using a second/different driver for some tests (instead of overwriting the global `$driver`) is the best answer. Thanks for the suggestion.

I was curious to try the `detach` parameter, but can't get it to work. Is this the correct syntax for creating a chrome driver in Ruby with detach set to `false`:

    caps = Selenium::WebDriver::Remote::Capabilities.chrome("chromeOptions" => {"detach" => false})
    $driver = Selenium::WebDriver.for :chrome, :desired_capabilities => caps, :switches => %w[--disable-cache --ignore-certificate-errors]

Changing `false` to `true` to doesn't appear to change any behavior (the browser window is left open in both cases).

Also, for what it's worth, the Chrome capabilities page says that the default value for `detach` is `false`.

**Comment by p0deje** [comment] 2015-07-08 04:28
> I was curious to try the detach parameter, but can't get it to work. Is this the correct syntax for creating a chrome driver in Ruby with detach set to false:

It should be `Selenium::WebDriver.for(:chrome, detach: false)`.

> Also, for what it's worth, the Chrome capabilities page says that the default value for detach is false.

Yes, but Ruby bindings [set it to true](https://github.com/seleniumhq/selenium/blob/master/rb/lib/selenium/webdriver/chrome/bridge.rb#L110).

I'm closing issue, looks like we figured it out.

**Closed by p0deje** 2015-07-08 04:28 UTC
Labels: C-rb, R-awaiting answer

**Comment by kurmasz** [comment] 2015-07-08 17:08
Yes, we (well, you) solved my original problem.

I wonder, however, if  `detach` isn't working as expected. 

If I understand correctly, the driver's `at_exit` hook should also close the window.  It doesn't.  Should I report this as a bug?

    require 'selenium-webdriver'
    driver = Selenium::WebDriver.for(:chrome, detach: false)

**Comment by p0deje** [comment] 2015-07-08 17:33
Please report and we'll take a look.

**Comment by parag90** [comment] 2016-05-03 10:21
I am still getting this issue 
Chrome doesnt closed even if I call browser.close

**Comment by parag90** [comment] 2016-05-03 10:22
INFO:Browser is initialized, closing it now
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/default.rb:107:in `response_for'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/default.rb:58:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:664:in `raw_execute'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:642:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:235:in `quit'
