### ISSUE TITLE
Wrong URL Path causes Proxy error.

### ISSUE THREAD

**Issue by marcioarend** [SeleniumHQ/selenium#2437] opened 2016-07-07 15:01 UTC
## Meta - Wrong URL Path causes Proxy error.
OS:  

Selenium Version:  

Browser:  

Browser Version:  

## Expected Behavior -
I am using selenium with Browserstack with Node to test my angular programm.
I am working in a Company and we are behind a Proxy. 
I tested the conection from my computer with Browserstack with Nightwatch and it worked perfect.

But when I tried to use Selenium I faced a Proxy error. I am trying to solve this problem for almost 3 days until today, when I found the problem. 

## Actual Behavior -

The problem was in the URL path:
in the Node.js BrowserStack example we have this URL 
 usingServer('http://hub-cloud.browserstack.com/wd/hub').
but my proxy shown only 
 /wd/hub/session

I think I found the problem by 
http/index.js  (line 273)
` var path = this.options_.path;
    if (path[path.length - 1] === '/' && httpRequest.path[0] === '/') {
      path += httpRequest.path.substring(1);
    } else {
      path += httpRequest.path; // hier we have only the path, without host
    }`

I have done  this 
`  path = "http://" + this.options_.host +  path;`

and its worked

## Steps to reproduce -
Use the example from BrowserStack 
https://www.browserstack.com/automate/node

Set the proxy 
usingWebDriverProxy("your Proxy 8080").

Error 
<p>Der folgende Fehler wurde beim Versuch die URL <a href="/wd/hub/session">/wd/hub/session</a> zu holen festgestellt:</p>

**Comment by jleyba** [comment] 2016-07-08 02:05
Duplicate of #2309

**Closed by jleyba** 2016-07-08 02:05 UTC
Labels: C-nodejs

**Comment by marcioarend** [comment] 2016-07-08 12:08
I have the version selenium-webdriver@2.53.3 and  I still facing the problem. But when I use My workaround it works, 
I think the problem deserve further investigation

As I said, if I change the code to this, its working 

 var path = this.options_.path;
    if (path[path.length - 1] === '/' && httpRequest.path[0] === '/') {
      path += httpRequest.path.substring(1);
    } else {
      path += httpRequest.path;
      path = "http://" + this.options_.host +  path;
      //console.log("index.js line 266 path ------> " + path);
    }

otherwise I recive this error 
Der folgende Fehler wurde beim Versuch die URL /wd/hub/session zu holen festgestellt:

**Comment by jleyba** [comment] 2016-07-08 17:52
The fix is not in 2.53.3. It will be in the next release
