### ISSUE TITLE
Firefox beta 41.0b2: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms

### ISSUE THREAD

**Issue by RayVin** [SeleniumHQ/selenium#944] opened 2015-08-19 14:59 UTC
Selenium 2.47.1 on Windows 7 does NOT run Firefox 41.0b2
Tried with the latest selenium jar provided by Luke:
http://ci.seleniumhq.org:8080/job/Build%20All%20Java/lastSuccessfulBuild/artifact/selenium-server-standalone-latest.jar
LOG:

org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
l\\Temp\\anonymous3748860063833974345webdriver-profile\\extensions\\fxdriver@googlecode.com","e":false,"v":"2.45.0","st":1439995500818,"mt":1439995500683}},"winreg-app-user":{"{9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8}":{"d":"C:\\Program Files (x86)\\HP\\Unified Functional Testing\\Bin\\Mozilla\\Common","e":false,"v":"12.0","st":1431113651911,"mt":1422867636000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"41.0","st":1439990050720,"mt":1439470792935}},"winreg-app-global":{"{D19CA586-DD6C-4a0a-96F8-14644F340D60}":{"d":"C:\\Program Files (x86)\\Common Files\\McAfee\\SystemCore","e":false,"v":"15.1.0","st":1424916626178,"mt":1424916625694},"{9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8}":{"d":"C:\\Program Files (x86)\\HP\\Unified Functional Testing\\\\bin\\Mozilla\\Common","st":1431113651911,"mt":1422867636000}}}
1439995503437	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1439995503438	addons.xpi	DEBUG	getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\username\\AppData\\Local\\Temp\\anonymous3748860063833974345webdriver-profile\\extensions\\fxdriver@googlecode.com","e":false,"v":"2.45.0","st":1439995500818,"mt":1439995500683}},"winreg-app-user":{"{9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8}":{"d":"C:\\Program Files (x86)\\HP\\Unified Functional Testing\\Bin\\Mozilla\\Common","e":false,"v":"12.0","st":1431113651911,"mt":1422867636000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"41.0","st":1439990050720,"mt":1439470792935}},"winreg-app-global":{"{D19CA586-DD6C-4a0a-96F8-14644F340D60}":{"d":"C:\\Program Files (x86)\\Common Files\\McAfee\\SystemCore","e":false,"v":"15.1.0","st":1424916626178,"mt":1424916625694},"{9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8}":{"d":"C:\\Program Files (x86)\\HP\\Unified Functional Testing\\\\bin\\Mozilla\\Common","st":1431113651911,"mt":1422867636000}}}
1439995503440	addons.xpi	DEBUG	No changes found
1439995503446	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1439995503446	addons.manager	DEBUG	Provider finished startup: XPIProvider
1439995503446	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1439995503446	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1439995503447	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1439995503447	addons.manager	DEBUG	Starting provider: GMPProvider
1439995503451	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1439995503451	addons.manager	DEBUG	Provider finished startup: GMPProvider
1439995503451	addons.manager	DEBUG	Starting provider: PluginProvider
1439995503451	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1439995503451	addons.manager	DEBUG	Provider finished startup: PluginProvider
1439995503451	addons.manager	DEBUG	Completed startup sequence
1439995503540	addons.xpi-utils	DEBUG	Starting async load of XPI database C:\Users\username\AppData\Local\Temp\anonymous3748860063833974345webdriver-profile\extensions.json
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1439995503704	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1439995503704	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1439995503705	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1439995503808	addons.xpi-utils	DEBUG	Async JSON file read took 0 MS
1439995503808	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
1439995503808	addons.xpi-utils	DEBUG	Successfully read XPI database
1439995503865	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1439995503865	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1439995503865	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:193)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:182)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:95)
	at pages.LocalUse.main(LocalUse.java:32)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
l\\Temp\\anonymous3748860063833974345webdriver-profile\\extensions\\fxdriver@googlecode.com","e":false,"v":"2.45.0","st":1439995500818,"mt":1439995500683}},"winreg-app-user":{"{9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8}":{"d":"C:\\Program Files (x86)\\HP\\Unified Functional Testing\\Bin\\Mozilla\\Common","e":false,"v":"12.0","st":1431113651911,"mt":1422867636000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"41.0","st":1439990050720,"mt":1439470792935}},"winreg-app-global":{"{D19CA586-DD6C-4a0a-96F8-14644F340D60}":{"d":"C:\\Program Files (x86)\\Common Files\\McAfee\\SystemCore","e":false,"v":"15.1.0","st":1424916626178,"mt":1424916625694},"{9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8}":{"d":"C:\\Program Files (x86)\\HP\\Unified Functional Testing\\\\bin\\Mozilla\\Common","st":1431113651911,"mt":1422867636000}}}
1439995503437	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1439995503438	addons.xpi	DEBUG	getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\username\\AppData\\Local\\Temp\\anonymous3748860063833974345webdriver-profile\\extensions\\fxdriver@googlecode.com","e":false,"v":"2.45.0","st":1439995500818,"mt":1439995500683}},"winreg-app-user":{"{9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8}":{"d":"C:\\Program Files (x86)\\HP\\Unified Functional Testing\\Bin\\Mozilla\\Common","e":false,"v":"12.0","st":1431113651911,"mt":1422867636000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"41.0","st":1439990050720,"mt":1439470792935}},"winreg-app-global":{"{D19CA586-DD6C-4a0a-96F8-14644F340D60}":{"d":"C:\\Program Files (x86)\\Common Files\\McAfee\\SystemCore","e":false,"v":"15.1.0","st":1424916626178,"mt":1424916625694},"{9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8}":{"d":"C:\\Program Files (x86)\\HP\\Unified Functional Testing\\\\bin\\Mozilla\\Common","st":1431113651911,"mt":1422867636000}}}
1439995503440	addons.xpi	DEBUG	No changes found
1439995503446	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1439995503446	addons.manager	DEBUG	Provider finished startup: XPIProvider
1439995503446	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1439995503446	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1439995503447	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1439995503447	addons.manager	DEBUG	Starting provider: GMPProvider
1439995503451	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1439995503451	addons.manager	DEBUG	Provider finished startup: GMPProvider
1439995503451	addons.manager	DEBUG	Starting provider: PluginProvider
1439995503451	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1439995503451	addons.manager	DEBUG	Provider finished startup: PluginProvider
1439995503451	addons.manager	DEBUG	Completed startup sequence
1439995503540	addons.xpi-utils	DEBUG	Starting async load of XPI database C:\Users\username\AppData\Local\Temp\anonymous3748860063833974345webdriver-profile\extensions.json
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1439995503704	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1439995503704	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1439995503705	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1439995503808	addons.xpi-utils	DEBUG	Async JSON file read took 0 MS
1439995503808	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
1439995503808	addons.xpi-utils	DEBUG	Successfully read XPI database
1439995503865	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1439995503865	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1439995503865	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider

Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'LNGDAYD-7004761', ip: '138.12.204.175', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_51'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:130)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:193)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:182)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:95)
	at pages.LocalUse.main(LocalUse.java:32)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
l\\Temp\\anonymous3748860063833974345webdriver-profile\\extensions\\fxdriver@googlecode.com","e":false,"v":"2.45.0","st":1439995500818,"mt":1439995500683}},"winreg-app-user":{"{9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8}":{"d":"C:\\Program Files (x86)\\HP\\Unified Functional Testing\\Bin\\Mozilla\\Common","e":false,"v":"12.0","st":1431113651911,"mt":1422867636000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"41.0","st":1439990050720,"mt":1439470792935}},"winreg-app-global":{"{D19CA586-DD6C-4a0a-96F8-14644F340D60}":{"d":"C:\\Program Files (x86)\\Common Files\\McAfee\\SystemCore","e":false,"v":"15.1.0","st":1424916626178,"mt":1424916625694},"{9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8}":{"d":"C:\\Program Files (x86)\\HP\\Unified Functional Testing\\\\bin\\Mozilla\\Common","st":1431113651911,"mt":1422867636000}}}
1439995503437	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1439995503438	addons.xpi	DEBUG	getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\username\\AppData\\Local\\Temp\\anonymous3748860063833974345webdriver-profile\\extensions\\fxdriver@googlecode.com","e":false,"v":"2.45.0","st":1439995500818,"mt":1439995500683}},"winreg-app-user":{"{9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8}":{"d":"C:\\Program Files (x86)\\HP\\Unified Functional Testing\\Bin\\Mozilla\\Common","e":false,"v":"12.0","st":1431113651911,"mt":1422867636000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"41.0","st":1439990050720,"mt":1439470792935}},"winreg-app-global":{"{D19CA586-DD6C-4a0a-96F8-14644F340D60}":{"d":"C:\\Program Files (x86)\\Common Files\\McAfee\\SystemCore","e":false,"v":"15.1.0","st":1424916626178,"mt":1424916625694},"{9F17B1A2-7317-49ef-BCB7-7BB47BDE10F8}":{"d":"C:\\Program Files (x86)\\HP\\Unified Functional Testing\\\\bin\\Mozilla\\Common","st":1431113651911,"mt":1422867636000}}}
1439995503440	addons.xpi	DEBUG	No changes found
1439995503446	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1439995503446	addons.manager	DEBUG	Provider finished startup: XPIProvider
1439995503446	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1439995503446	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1439995503447	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1439995503447	addons.manager	DEBUG	Starting provider: GMPProvider
1439995503451	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1439995503451	addons.manager	DEBUG	Provider finished startup: GMPProvider
1439995503451	addons.manager	DEBUG	Starting provider: PluginProvider
1439995503451	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1439995503451	addons.manager	DEBUG	Provider finished startup: PluginProvider
1439995503451	addons.manager	DEBUG	Completed startup sequence
1439995503540	addons.xpi-utils	DEBUG	Starting async load of XPI database C:\Users\username\AppData\Local\Temp\anonymous3748860063833974345webdriver-profile\extensions.json
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1439995503704	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1439995503704	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1439995503705	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1439995503808	addons.xpi-utils	DEBUG	Async JSON file read took 0 MS
1439995503808	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
1439995503808	addons.xpi-utils	DEBUG	Successfully read XPI database
1439995503865	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1439995503865	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1439995503865	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
	... 7 more

**Comment by lukeis** [comment] 2015-08-19 16:57
I just tried this on a Windows 7 VM with the jar linked and Firefox version 41.0b2

It worked just fine... I'm not able to reproduce your issue. I was able to install Firefox Beta (to the default install location), start up selenium with `java -jar selenium-server-standalone-latest.jar` and then remotely connect to it (I chose python): `d = webdriver.Remote(desired_capabilities=webdriver.DesiredCapabilities.FIREFOX)`.

I'm seeing some interesting paths in your stacktrace that suggest something else might be going on. Can you troubleshoot your environment a little further, or start over with a 'clean' windows VM from modern.ie

closing, since I can't reproduce.

**Closed by lukeis** 2015-08-19 16:57 UTC

**Comment by RayVin** [comment] 2015-08-19 17:31
I'll try, but the point is that it worked with FF 40.
