### ISSUE TITLE
[🐛 Bug]: Error in pom.xml while building with  Selenium Version 4.20.0

### ISSUE THREAD

**Issue by Shivshive** [SeleniumHQ/selenium#13881] opened 2024-04-26 14:36 UTC
### What happened?

When added selenium version 4.20.0 to the maven project, its giving error in pom.xml
```xml
<dependency>
  <groupId>org.seleniumhq.selenium</groupId>
  <artifactId>selenium-java</artifactId>
  <version>4.20.0</version>
</dependency>
```
![image](https://github.com/SeleniumHQ/selenium/assets/27910727/ab53c9c1-16e6-4f2d-a2d3-30db44846903)

![image](https://github.com/SeleniumHQ/selenium/assets/27910727/30cba40a-cf00-4a90-91dc-7c4a3ebb226e)

### How can we reproduce the issue?

```shell
Create a Maven Project and add the given maven dependency for selenium v 4.20.0
```

### Relevant log output

```shell
This line is giving error in pom.xml

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">


Error screen shot given in description
```

### Operating System

Windows 11 

### Selenium version

4.20.0

### What are the browser(s) and version(s) where you see this issue?

Chrome v124

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver-124

### Are you using Selenium Grid?

No

**Comment by diemol** [comment] 2024-04-26 14:43
Our Java examples are working well and passing with the following [pom](https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/java/pom.xml). Can you please share a complete project to reproduce this issue?

**Comment by diemol** [comment] 2024-04-26 14:44
From the screenshot it looks like a network error on your side.

**Comment by chamiz** [comment] 2024-04-26 23:31
Yes, it's a network issue. @Shivshive Are you using any VPN?
I tried to recreate the issue but failed. 

**OS.**
Windows 11

![image](https://github.com/SeleniumHQ/selenium/assets/5998750/0376a238-34a8-4f25-809d-3ce046039c88)

**Comment by diemol** [comment] 2024-04-27 06:10
Thank you for triaging, @chamiz!

I will close this as it looks like a network issue on @Shivshive's side.

**Closed as not planned by diemol** 2024-04-27 06:10 UTC
Labels: I-defect, A-needs-triaging
