### ISSUE TITLE
[🐛 Bug]: Session queue leak

### ISSUE THREAD

**Issue by tommy0831** [SeleniumHQ/selenium#10551] opened 2022-04-15 05:20 UTC
### What happened?

Looks like there's a session queue leak in Selenium 4 causing it to eat up resources in the long run.  When Selenium 4 grid runs out of sessions, incoming session requests go into the session queue.  When a node is freed it takes from the session queue in a FIFO order.  The problem seems to be Selenium is creating two sessions when it takes from the session queue.  The extra session leaves behind temporary resources (scoped_dir_* folders) in the %TMP% folder that are not deleted.  I'm using Windows 10.

### How can we reproduce the issue?

```shell
1. Start Selenium 4 stand alone.  It creates 5 chrome nodes.
2. Write a simple script to get a session from the grid

        ChromeOptions options = new ChromeOptions();
        options.addArguments("no-sandbox");
        options.addArguments("--headless");
        options.addArguments("--disable-component-update");
        options.addArguments("--disable-extensions");
        options.addArguments("start-maximized");

        options.setExperimentalOption("prefs", chromePref);
        WebDriver driver = new RemoteWebDriver(new URL(hub), options);

        try {
          Thread.sleep(60000);
          // do something
        } catch (Exception ex) {
          ex.printStackTrace();
        }

3. Run 7 instances
4. In http://<standalone hub ip>:4444/ui/index.html#/, it shows 5 running, 2 in queue.
5. Watch this page, when one of the session ends, Selenium should take one off the queue and create a new session.  However, observe that it creates two sessions when it takes from the queue.
6. When your normal sessions are done, notice two extra sessions still show on the page.
7. Go to %TMP% folder (c:\Users\<user id>\AppData\Local\Temp), you will see scoped_dir_* folders not cleaned up.

NOTE: if you run 5 instances, it will NOT leave behind scoped_dir_* folders.

The scoped_dir_* folders can range from 1 MB to ~ 50MB.  It will slowly eat up the system disk space and eventually Selenium won't be able to create new sessions and throw "failed to write prefs file".
```

### Relevant log output

```shell
none
```

### Operating System

Windows 10

### Selenium version

Selenium 4

### What are the browser(s) and version(s) where you see this issue?

chrome 100

### What are the browser driver(s) and version(s) where you see this issue?

chrome driver 100

### Are you using Selenium Grid?

Selenium 4 grid or selenium 4 standalone.

**Comment by pujagani** [comment] 2022-04-18 04:47
Thank you for sharing the details. Can you please try and see if this still happens if you use Selenium Grid 4.1.3? Some changes went in the Grid in optimizing how we consume from the queue after 4.0.0. Just want to make sure if the issue is still persistent.

**Comment by diemol** [comment] 2022-04-21 20:57
Also, please provide a complete and deterministic way to reproduce this issue, ideally through a GitHub repository. I just tried to follow your instructions and I was not able to reproduce this.

**Comment by diemol** [comment] 2022-05-01 20:24
Closing as we did not get more information.

**Closed as completed by diemol** 2022-05-01 20:24 UTC
Labels: B-grid, J-awaiting answer, I-defect
