### ISSUE TITLE
Safari SendKeys() returns WebDriverError: An invalid command response was received: Could not parse response payload

### ISSUE THREAD

**Issue by aozolin** [SeleniumHQ/selenium#8423] opened 2020-06-15 08:15 UTC
## 🐛 Bug Report

When I run my protractor test in Safari, SendKeys() action fails with below error.
The test runs against my Angular 9 application.
The test works fine in Chrome browser.

Mentioned in below error payload could be successfully parsed with JSON.parse(), so looks like it's a selenium-driver issue.

`- WebDriverError: An invalid command response was received: Could not parse response payload: {
            result = "{\"tagName\":\"INPUT\",\"attributes\":{\"_ngcontent-mcu-c7\":null,\"pinputtext\":null,\"class\":\"ng-tns-c78-12 username-value login-field ui-inputtext ui-corner-all ui-state-default ui-widget ng-untouched ng-pristine ng-valid ng-star-inserted\",\"placeholder\":null,\"type\":null}}";
        }
        Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
        System info: host: 'MY-HOST', ip: '192.168.1.3', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.5', java.version: '1.8.0_232'
        Driver info: driver.version: unknown
            at Object.checkLegacyResponse (/e2e/node_modules/selenium-webdriver/lib/error.js:546:15)
            at parseHttpResponse (/e2e/node_modules/selenium-webdriver/lib/http.js:509:13)
            at /e2e/node_modules/selenium-webdriver/lib/http.js:441:30
            at processTicksAndRejections (internal/process/task_queues.js:93:5)
        From: Task: WebElement.sendKeys()
            at thenableWebDriverProxy.schedule (/e2e/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
            at WebElement.schedule_ (/e2e/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
            at WebElement.sendKeys (/e2e/node_modules/selenium-webdriver/lib/webdriver.js:2174:19)`

## Environment

OS: Mac OS X 10.15.5
Browser: Safari
Browser version: 13.1.1 (15609.2.9.1.2)
Browser Driver version: Included with Safari 13.1.1 (15609.2.9.1.2)

**Comment by aozolin** [comment] 2020-06-16 14:02
Hi @Harsha509 

It's a bit difficult to reproduce it by you as it's a private webapp that can't be published...
I'm trying to reproduce it somewhere on public resources. Not sure it will be possible.

**Comment by aozolin** [comment] 2020-06-25 04:38
I found a workaround. In our case input element had attribute `type=''`.
We updated it to `type='text'` and it resolved the issue.

I think this case should be fixed on webdriver side.

**Comment by barancev** [comment] 2020-06-30 04:31
Can you please create an SSCCE (http://sscce.org/) now as soon as you've identified the root cause of the issue?

**Comment by MarcSteven** [comment] 2020-07-10 05:50
@barancev  The issue is existing
<img width="1225" alt="截屏2020-07-10 下午1 50 06" src="https://user-images.githubusercontent.com/13824297/87120963-52f65a80-c2b4-11ea-958e-f9489d97c075.png">
` Got response with status 400: {"value":{"error":"invalid element state","message":"Error Domain=com.facebook.WebDriverAgent Code=1 \"The on-screen keyboard must be present to send keys\" UserInfo={NSLocalizedDescription=The on-screen keyboard must be present to send keys}","traceback":""},"sessionId":"789495B1-39D1-4C19-8EF4-3DD06484CC14"}
[W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[MJSONWP (2fab2758)] Encountered internal error running command: InvalidElementStateError: Error Domain=com.facebook.WebDriverAgent Code=1 "The on-screen keyboard must be present to send keys" UserInfo={NSLocalizedDescription=The on-screen keyboard must be present to send keys}
[MJSONWP (2fab2758)]     at errorFromW3CJsonCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
[MJSONWP (2fab2758)]     at ProxyRequestError.getActualError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
[MJSONWP (2fab2758)]     at JWProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:264:19)
[HTTP] <-- POST /wd/hub/session/2fab2758-9169-4654-bec8-da732f8f3a47/element/55010000-0000-0000-3637-000000000000/value 500 3501 ms - 276
[HTTP] `

**Comment by diemol** [comment] 2020-07-10 07:27
@MarcSteven that looks like Appium, have you also reached out to them?
In addition, as mentioned above, a screenshot is not enough, can you please create an SSCCE (http://sscce.org/) now as soon as you've identified the root cause of the issue?

**Comment by MarcSteven** [comment] 2020-07-10 09:07
@diemol I had noticed the team of Appium, but now don't get any replies about it.
The main issue is as below:
Some elements are visible, but cannot interact with it, for instance, tap or send keys.

**Comment by AutomatedTester** [comment] 2020-07-10 09:12
> @diemol I had noticed the team of Appium, but now don't get any replies about it.
> The main issue is as below:
> Some elements are visible, but cannot interact with it, for instance, tap or send keys.

Hi @MarcSteven , The error messages are unrelated to the original issue and you're now hijacking this one. Could you raise a new bug with an [SSCCE](http://sscce.org/).

**Comment by MarcSteven** [comment] 2020-07-11 23:40
@AutomatedTester Perhaps

**Comment by diemol** [comment] 2020-07-29 21:05
Closing as never got any feedback which could help us to determine if this is an issue or not.

**Closed by diemol** 2020-07-29 21:05 UTC
Labels: R-awaiting answer
