### ISSUE TITLE
latest browser its not work selenium ide

### ISSUE THREAD

**Issue by JayminNarola** [SeleniumHQ/selenium#5005] opened 2017-11-03 10:27 UTC
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by Zaanmedia** [comment] 2017-11-03 11:11
Selenium IDE works till Firefox 54 and lower < Firefox 54+ and up are not working with the old IDE. 

New IDE is being under development for lastest browsers Firefox and Chrome. 
See: https://github.com/SeleniumHQ/selenium-ide

**Comment by lmtierney** [comment] 2017-11-03 13:51
Duplicate of #4406

**Closed by lmtierney** 2017-11-03 13:51 UTC
