### ISSUE TITLE
SlowLoadableComponent::get() problem

### ISSUE THREAD

**Issue by emaks** [SeleniumHQ/selenium#1409] opened 2015-12-22 15:25 UTC
I don't understand logic of [get()](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/ui/SlowLoadableComponent.java#L47) function. why do we try to find element [before](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/ui/SlowLoadableComponent.java#L49) and [after](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/ui/SlowLoadableComponent.java#L70) ['while'](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/ui/SlowLoadableComponent.java#L57) statement. 

I have nested elements structure.

``` java
@FindBy(css = "#elem1")
public class Elem1 extends WebElement{
    privite Elem2 element2;
}
@FindBy(css = "#elem2")
public class Elem2 extends WebElement{
    privite Elem3 element3;
}
@FindBy(css = "#elem3")
public class Elem3 extends WebElement{
    privite Elem4 element4;
}
@FindBy(css = "#elem4")
public class Elem4 extends WebElement{
    @FindBy(css = "#elem5")
    privite WebElement element5;
}
```

I create instance of AjaxElementLocator.class with timeOutInSeconds = 2
when I try to execute `element5.findElement(By.xpath("."))` command in case when there in no this element on the page(last one) then command execution time will much more than 10 seconds

**Comment by emaks** [comment] 2015-12-28 08:16
also If I have problem with parent locator(for exmaple: incorrect locator for Elem3) ``` element5.findElements(By.xpath("#someId")) ``` will return empty array. I expect to get ```NoSuchElementException```

**Comment by barancev** [comment] 2017-08-23 09:48
I understand that we're too late, but...

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by barancev** [comment] 2017-09-06 06:56
Closing the issue, it's not obvious what change or fix is proposed, the original post looks like a question rather than a bug report.

**Closed by barancev** 2017-09-06 06:56 UTC
Labels: C-java, R-awaiting answer
