### ISSUE TITLE
Unable to add new web-extension xpi to Firefox profile (missing install.rdf)

### ISSUE THREAD

**Issue by DiscmanDaemon** [SeleniumHQ/selenium#4184] opened 2017-06-15 03:54 UTC
## Meta -
OS:  FreeBSD 11, Debian Linux

Selenium Version:  3.4.3

Browser:  Firefox

Browser Version:  53.0.3 (64-bit)

## Expected Behavior -
The expected behavior is for selenium to start an instance of Firefox with the web extension as defined in the profile. 
## Actual Behavior -
The following stack trace is produced:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "EnginePlug.py", line 128, in start
    self.web=BrowserControls()
  File "BrowserControlsProf.py", line 11, in __init__
    profile=FirefoxProfile("/home/matthew/basic")
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 92, in add_extension
    self._install_extension(extension)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 271, in _install_extension
    addon_details = self._addon_details(addon)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 348, in _addon_details
    raise AddonFormatError(str(e), sys.exc_info()[2])
selenium.webdriver.firefox.firefox_profile.AddonFormatError: ("[Errno 2] No such file or directory: '/tmp/tmpR1MBsu.auto.xpi/install.rdf'", <traceback object at 0x802baf998>)
`
## Steps to reproduce -
The following section of code is where the error is originating from:
`
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium.webdriver.firefox.webdriver import FirefoxProfile

class BrowserControls():
  browser={}

  def __init__(self):  
    profile=FirefoxProfile("/home/matthew/basic")
    binary=FirefoxBinary('/usr/local/bin/firefox')
    self.browser=webdriver.Firefox(firefox_binary=binary, firefox_profile=profile)
`

The /home/matthew/basic directory is a firefox profile directory with a web-extension I am developing and testing added to it. The web-extension is signed for personal (non-official) distribution. Unfortunately, I am not at liberty to share that snippet of code at the moment, but it is a very, very basic plugin that works fine if manually added to the browser after it is started by selenium, or if added to my normal, non-selenium browser.

However, the issue should be reproducible with the dummy extension described here, since this doesn't produce an install.rdf file in the .xpi bundle
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Your_first_WebExtension

**Comment by DiscmanDaemon** [comment] 2017-06-15 04:06
Curiously, scraping the bottom of the barrel, I tried upgrading to firefox 54.0.1 and this issue no longer appears in firefox 54.0.1

**Comment by phystem** [comment] 2017-06-15 06:49
@DiscmanDaemon  

I'm still facing the same issue. 

I'm using
Selenium 3.4
Firefox 54.0b6 (32-bit) / 55.0b1 (32-bit)
Geckodriver 0.17.0 32-bit
Windows 7 32 bit

Posted about the same in [Gekcodriver's Issue](https://github.com/mozilla/geckodriver/issues/759)

**Comment by barancev** [comment] 2017-09-05 11:31
Duplicate of #4093

**Closed by barancev** 2017-09-05 11:31 UTC
Labels: C-py, D-marionette
