### ISSUE TITLE
scroll-behavior: smooth breaks click

### ISSUE THREAD

**Issue by trenowden** [SeleniumHQ/selenium#8973] opened 2020-12-16 12:14 UTC
## 🐛 Bug Report

If a page uses `style: html { scroll-behavior: smooth; }`  and you attempt to click an element which is currently outside of the viewport, Selenium throws a ElementClickInterceptedError.

## To Reproduce

Smooth scrolling example page: https://jsfiddle.net/o8eg7dwh/
Detailed steps to reproduce the behaviour:  Try to click button with id='test'

## Expected behaviour

Selenium should scroll the element into the viewport and successfully click it.

## Environment

OS: macOS 11.1
Browser: Chrome 
Browser version: 87.0.4280.88
Browser Driver version: Chromedriver 87.0.4
Language Bindings version: Selenium WebDriver Node.JS 4.0.0-alpha.8

**Comment by diemol** [comment] 2020-12-22 23:40
Could you please provide a Selenium WebDriver Script to reproduce this? Does it only happen with the JS bindings? Does it only happen with Chrome or does it also happen with Firefox or Safari?

**Comment by diemol** [comment] 2021-01-07 16:51
Closing as we did not get more information.

**Closed as completed by diemol** 2021-01-07 16:51 UTC
Labels: J-awaiting answer

**Comment by tomevans18** [comment] 2021-02-26 11:43
This is happening in Chrome but I'm unsure about other browser.

I'm new to Selenium so not sure if the below helps and is what you are looking for (its typescript FYI):
```
import { Builder, ThenableWebDriver, By } from "selenium-webdriver";
import until from "selenium-webdriver/lib/until";
import chrome from "selenium-webdriver/chrome";
import "chromedriver";

const chromeCapabilities = new chrome.Options();

export const seleniumBrowser = async ({ url }: { url: string }): Promise<ThenableWebDriver> => {
  const driver = new Builder().setChromeOptions(chromeCapabilities).forBrowser("chrome").build();

  try {
    // Navigate to Url
    await driver.get(url);

    // get checkbox
    const checkbox = await driver.wait(
      until.elementLocated(By.css("[data-testid='checkbox']")),
      10000
    );

    const actions = driver.actions({ async: true });

    // Performs mouse move action onto the element
    await actions.move({ origin: checkbox }).perform();

    return await driver;
  } catch (err) {
    throw new Error(err);
  } finally {
    await driver.close();
  }
};
```

The above will throw the following error:
```
MoveTargetOutOfBoundsError: move target out of bounds
  (Session info: chrome=88.0.4324.192)
```

When you remove the css `scroll-behavior: smooth;` it works as expected.
I believe this is because Selenium isn't waiting for the element to scroll into view before continuing.

**Comment by tomevans18** [comment] 2021-02-26 12:13
The way I have got around this is to use the following:
```
    // Scroll to element
    driver.executeScript("arguments[0].scrollIntoView();", checkbox);
    // pause for 1 second to wait until scroll is completed
    await wait(1000);
```
