### ISSUE TITLE
3.5.0 Grid - Selenium Keys / Unicode Failing

### ISSUE THREAD

**Issue by thomhurst** [SeleniumHQ/selenium#4462] opened 2017-08-15 15:18 UTC
When using the Selenium Grid 3.5.0 then Selenium Keys is failing.

element.sendKeys(Keys.TAB); is instead sending a question mark '?'
An issue with sending unicode over the grid maybe e.g. "\ue004" 

Using the latest ChromeDriver 2.31

**Comment by sgtjim** [comment] 2017-08-15 16:36
I'm also able to reproduce this with 3.5.0 grid, Firefox 54.0.1,  and client-combined-3.5.0-nodeps.jar, and using Microsoft Edge in the same grid setup.

**Comment by shs96c** [comment] 2017-08-16 09:45
Are the grid node and your tests running on the same OS?

**Comment by matthew-horrocks** [comment] 2017-08-16 09:49
Reproducible with Selenium Grid 3.5.1 .NET and Chrome 60 / chromedriver 2.31.

These failures are occurring on two different configurations of Grid:

Grid running Windows 2012r2 with remote Nodes running Windows 10
Grid running Windows 10 with a Node running on the same machine Windows 10

Prior to 3.5.1 this XPATH worked OK ```//ul[@class='currency-list']//li[contains(.,'$')]``` however after upgrading to 3.5.1 I get an element not found exception ```Unable to locate element: {"method":"xpath","selector":"//ul[@class='currency-list']//li[contains(.,'�')]"}```.

This appears to be an issue only with the Grid server. A local instance of 3.5.1 works OK and raises an expected failure of ```Unable to locate element: {"method":"xpath","selector":"//ul[@class='currency-list']//li[contains(.,'£')]"}```

**Comment by sgtjim** [comment] 2017-08-16 12:29
@shs96c  Yes, for me they're both running on Windows 10.  I didn't deploy the update to our Windows Server 2012r2 instances until I had made sure things like this weren't things like this.

**Comment by bjharo** [comment] 2017-08-21 15:44
I'm seeing the same thing. I have a test where I'm entering this string:

♒ берегам ἐξκοισαφῆ तान्यहानि 有朋自遠方來 àéî ¥€®¶¢£¤§Þ﷼ ╬ This is a unicode test.

but the remote Chrome browser is showing this:

? ??????? ????????? ????????? ?????? ��� ���������? ? This is a unicode test.

I'm currently testing against a grid where the hub and node are running Selenium 3.5.  My test code itself is using the 3.5.1 .NET bindings.  Both the hub and node are running Windows 10.  Running these tests locally without the grid results in the correct string being typed into the field.  The problem only happens when using  the grid.

Also, when using a full 3.3 grid setup, this works fine.

**Comment by barancev** [comment] 2017-08-22 14:49
We've found the root cause and fixed it by 9be6e6eacd15c44faf2c8704f73b662f84cdd31e

Until the next release you can use a workaround: start hub with explicit setting of `file.encoding` property:
```
java -Dfile.encoding=UTF-8 -jar selenium-server-standalone-3.5.0.jar -role hub
```

**Comment by thomhurst** [comment] 2017-08-22 15:07
Thanks for the update and fix @barancev

**Comment by barancev** [comment] 2017-08-29 15:31
Version 3.5.3 released with this fix.

**Closed by barancev** 2017-08-29 15:31 UTC
Labels: C-grid

**Comment by mseele** [comment] 2017-09-05 13:52
bug #4523 which has been marked as duplicate of this bug still exists in selenium 3.5.3 (IEDriver sends the wrong keys with german keyboard setting).
