### ISSUE TITLE
Multiple dependency convergency issues in 3.0.1

### ISSUE THREAD

**Issue by mhardin** [SeleniumHQ/selenium#3003] opened 2016-10-25 16:04 UTC
## Meta -

OS:  OSX
Selenium Version:  3.0.1

Hi,

There seem to be multiple dependency convergence issues with Selenium 3.0.1 with 'org.seleniumhq.selenium:selenium-remote-driver', 'org.eclipse.jetty.websocket:websocket-client', and 'org.seleniumhq.selenium:selenium-remote-driver'.  This issue was not present in 3.0.0.  Here is the full list of convergence issues when you pull 'selenium-server' in as a Maven dependency:

```
Dependency convergence error for org.seleniumhq.selenium:selenium-remote-driver:3.0.1 paths to dependency are:
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-org.seleniumhq.selenium:selenium-chrome-driver:3.0.1
        +-org.seleniumhq.selenium:selenium-remote-driver:3.0.1
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-org.seleniumhq.selenium:selenium-edge-driver:3.0.1
        +-org.seleniumhq.selenium:selenium-remote-driver:3.0.1
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-org.seleniumhq.selenium:selenium-firefox-driver:3.0.1
        +-org.seleniumhq.selenium:selenium-remote-driver:3.0.1
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-org.seleniumhq.selenium:selenium-ie-driver:3.0.1
        +-org.seleniumhq.selenium:selenium-remote-driver:3.0.1
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-org.seleniumhq.selenium:selenium-opera-driver:3.0.1
        +-org.seleniumhq.selenium:selenium-remote-driver:3.0.1
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-org.seleniumhq.selenium:selenium-safari-driver:3.0.1
        +-org.seleniumhq.selenium:selenium-remote-driver:3.0.1
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-support:3.0.0
    +-org.seleniumhq.selenium:selenium-remote-driver:3.0.0

[WARNING] 
Dependency convergence error for org.eclipse.jetty.websocket:websocket-client:9.2.18.v20160721 paths to dependency are:
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-net.sourceforge.htmlunit:htmlunit:2.23
        +-org.eclipse.jetty.websocket:websocket-client:9.2.18.v20160721
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-org.eclipse.jetty.websocket:websocket-client:9.2.15.v20160210

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability the error(s) are [
Dependency convergence error for org.seleniumhq.selenium:selenium-remote-driver:3.0.1 paths to dependency are:
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-org.seleniumhq.selenium:selenium-chrome-driver:3.0.1
        +-org.seleniumhq.selenium:selenium-remote-driver:3.0.1
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-org.seleniumhq.selenium:selenium-edge-driver:3.0.1
        +-org.seleniumhq.selenium:selenium-remote-driver:3.0.1
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-org.seleniumhq.selenium:selenium-firefox-driver:3.0.1
        +-org.seleniumhq.selenium:selenium-remote-driver:3.0.1
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-org.seleniumhq.selenium:selenium-ie-driver:3.0.1
        +-org.seleniumhq.selenium:selenium-remote-driver:3.0.1
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-org.seleniumhq.selenium:selenium-opera-driver:3.0.1
        +-org.seleniumhq.selenium:selenium-remote-driver:3.0.1
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-org.seleniumhq.selenium:selenium-safari-driver:3.0.1
        +-org.seleniumhq.selenium:selenium-remote-driver:3.0.1
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-support:3.0.0
    +-org.seleniumhq.selenium:selenium-remote-driver:3.0.0
, 
Dependency convergence error for org.eclipse.jetty.websocket:websocket-client:9.2.18.v20160721 paths to dependency are:
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-net.sourceforge.htmlunit:htmlunit:2.23
        +-org.eclipse.jetty.websocket:websocket-client:9.2.18.v20160721
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-org.eclipse.jetty.websocket:websocket-client:9.2.15.v20160210
```

**Comment by lukeis** [comment] 2016-10-25 16:51
can you show your pom file?  seems like you are including selenium-server 3.0.1 AND selenium-support 3.0.0

**Comment by mhardin** [comment] 2016-10-25 16:53
@lukeis ah, you're right.  I added it to get around another dependency convergence issue.  Here is the latest list of convergence issues:
```
Dependency convergence error for org.eclipse.jetty.websocket:websocket-client:9.2.18.v20160721 paths to dependency are:
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-net.sourceforge.htmlunit:htmlunit:2.23
        +-org.eclipse.jetty.websocket:websocket-client:9.2.18.v20160721
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-org.eclipse.jetty.websocket:websocket-client:9.2.15.v20160210

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability the error(s) are [
Dependency convergence error for org.eclipse.jetty.websocket:websocket-client:9.2.18.v20160721 paths to dependency are:
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-net.sourceforge.htmlunit:htmlunit:2.23
        +-org.eclipse.jetty.websocket:websocket-client:9.2.18.v20160721
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.1
    +-org.seleniumhq.selenium:selenium-java:3.0.1
      +-org.eclipse.jetty.websocket:websocket-client:9.2.15.v20160210
```
Let me know if you need anything else from me.

**Comment by lukeis** [comment] 2016-10-25 16:55
that's a duplicate of #2956  :)  which will be fixed in the next release 3.0.2?  I'll try to get to it later this week

**Comment by mhardin** [comment] 2016-10-25 16:55
@lukeis this isn't a dupe of #2956 is it?  The dependencies are different.

**Comment by lukeis** [comment] 2016-10-25 16:57
you're right, not a dupe... but um, not sure how that's happening?

https://github.com/SeleniumHQ/htmlunit-driver/blob/master/pom.xml#L72-L82

**Comment by lukeis** [comment] 2016-10-25 16:58
i think it will likely be resolved in the next release

**Comment by barancev** [comment] 2017-08-11 15:16
Fixed in htmlunit-driver

**Closed by barancev** 2017-08-11 15:16 UTC
Labels: C-java
