### ISSUE TITLE
[🐛 Bug]: org.openqa.selenium.SessionNotCreatedException when launching the Edge Browser in IE Mode

### ISSUE THREAD

**Issue by PraveenThirumoorthy** [SeleniumHQ/selenium#12171] opened 2023-06-07 14:34 UTC
### What happened?

Am trying to Launch the Edge browser in the IE Mode and below is the code used.
Am using Windows 16 64 Bit machine. Edge Browser 114 Version installed and IE 11 also installed

Getting the below error after a while. Also its launching both IE 11 and Edge Browser in IE Mode together. Howvere i wanted only EDGE Browser in IE Mode alone
But not navigating to the Website i mentioned
![IEMODE_IE](https://github.com/SeleniumHQ/selenium/assets/122547514/865b4b08-b808-4bf5-9275-cd49f3980c3a)
![IEMODE_EDGE](https://github.com/SeleniumHQ/selenium/assets/122547514/a69e9612-eaa0-4ed0-be62-99f824db6409)

Error Message: 
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

### How can we reproduce the issue?

```shell
public static void main(String[] args) {
	System.setProperty("webdriver.ie.driver", "C:\\Automation\\Workspace\\TESTNG_TOWER_LAYER\\drivers\\IEDriverServer.exe");
	InternetExplorerOptions IEOptionsEdge = setInternetExlopererForEdge();
	WebDriver driver = new InternetExplorerDriver(IEOptionsEdge);
	driver.get("https://www.google.com/");
	driver.manage().window().maximize();
}
private static InternetExplorerOptions setInternetExlopererForEdge() 
{
	InternetExplorerOptions IEOptions  = new InternetExplorerOptions();
	IEOptions.attachToEdgeChrome();
	IEOptions.ignoreZoomSettings();
	IEOptions.withEdgeExecutablePath("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
	return IEOptions;
}
```

### Relevant log output

```shell
Started InternetExplorerDriver server (64-bit)
4.8.1.0
Listening on port 63976
Only local connections are allowed
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: '-----------', ip: '--------', os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: internet explorer, se:ieOptions: {ie.edgechromium: true, ie.edgepath: C:\Program Files (x86)\Micr..., ignoreZoomSetting: true}}], desiredCapabilities=Capabilities {browserName: internet explorer, ie.edgechromium: true, ie.edgepath: C:\Program Files (x86)\Micr..., ignoreZoomSetting: true, se:ieOptions: {ie.edgechromium: true, ie.edgepath: C:\Program Files (x86)\Micr..., ignoreZoomSetting: true}}}]
Capabilities {}
```

### Operating System

Windows 16

### Selenium version

Selenium 4

### What are the browser(s) and version(s) where you see this issue?

Edge 114

### What are the browser driver(s) and version(s) where you see this issue?

IEDRIVERSERVER 64 BIT

### Are you using Selenium Grid?

NA

**Comment by titusfortner** [comment] 2023-06-07 14:56
If both Edge & IE are on the system, you need to specify that you want edge by adding:

```
IEOptions.attachToEdgeChrome();
```

**Comment by PraveenThirumoorthy** [comment] 2023-06-07 15:02
@titusfortner I have already mentioned that am using the IEOptions.attachToEdgeChrome(); Can you please read the "How can we reproduce the issue?" section. 

should i log the same issue again?

**Comment by titusfortner** [comment] 2023-06-07 17:02
You're using an old version of Selenium. Please update to 4.10.0

**Comment by PraveenThirumoorthy** [comment] 2023-06-13 13:13
Sure . I will update this and will let you know. I have raised a request in the internal organization to add Selenium 4.10.0 on maven remote repo

**Comment by PraveenThirumoorthy** [comment] 2023-06-15 08:47
Am still getting the same error message after the Selenium 4.10.0 . Still getting Internet explorer opened up along with Edge browser. Also edge browser is not navigating to the Url provided
Note: we are using Java 8

![image](https://github.com/SeleniumHQ/selenium/assets/122547514/53598c48-e36a-470e-987f-c110068be93e)

**Comment by titusfortner** [comment] 2023-06-15 09:54
This should just work:
```
	InternetExplorerOptions IEOptions  = new InternetExplorerOptions();
	IEOptions.attachToEdgeChrome();
	WebDriver driver = new InternetExplorerDriver(IEOptionsEdge);
```

* Lets Selenium download latest IEDriver (
* Options tells IE Driver to use Edge not IE
* Latest IE Driver picks up the default location of Edge without needing to specify it

If you are still getting a problem turn on logging and post the results:
https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by PraveenThirumoorthy** [comment] 2023-06-16 09:06
Thanks @titusfortner  for the details

i have used the below code as you suggested

```
public static void main(String[] args) {

	Logger logger = Logger.getLogger("");
	logger.setLevel(Level.FINER);
	  Arrays.stream(logger.getHandlers()).forEach(handler -> {
	      handler.setLevel(Level.FINE);
	    });
	InternetExplorerOptions IEOptionsEdge = setInternetExlopererForEdge();
	WebDriver driver = new InternetExplorerDriver(IEOptionsEdge);
	driver.get("https://www.google.com");
	driver.manage().window().maximize();
}
private static InternetExplorerOptions setInternetExlopererForEdge() 
{
	InternetExplorerOptions IEOptions  = new InternetExplorerOptions();
	IEOptions.attachToEdgeChrome();
	return IEOptions;
}
```
Ended up in getting the below error
```
Jun 16, 2023 10:01:43 AM org.openqa.selenium.remote.service.DriverService$Builder getLogOutput
INFO: Driver logs no longer sent to console by default; https://www.selenium.dev/documentation/webdriver/drivers/service/#setting-log-output
Jun 16, 2023 10:01:44 AM org.openqa.selenium.manager.SeleniumManager getDriverPath
FINE: Applicable driver not found; attempting to install with Selenium Manager (Beta)
Jun 16, 2023 10:01:44 AM org.openqa.selenium.manager.SeleniumManager runCommand
FINE: Executing Process: [C:\Users\vagrant\AppData\Local\Temp\selenium-manager24925638153555233840213918447655\selenium-manager.exe, --browser, internet explorer, --output, json, --debug]
Exception in thread "main" org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browserName: internet explorer, se:ieOptions: {ie.edgechromium: true}}
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:29)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:136)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:103)
	at selenium.WebDriverFactory.main(WebDriverFactory.java:156)
Caused by: org.openqa.selenium.WebDriverException: Unsuccessful command executed: [C:\Users\vagrant\AppData\Local\Temp\selenium-manager24925638153555233840213918447655\selenium-manager.exe, --browser, internet explorer, --output, json, --debug]
error sending request for url (https://raw.githubusercontent.com/SeleniumHQ/selenium/trunk/common/mirror/selenium): error trying to connect: An existing connection was forcibly closed by the remote host. (os error 10054)
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: InternetExplorerDriver
	at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:130)
	at org.openqa.selenium.manager.SeleniumManager.getDriverPath(SeleniumManager.java:251)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:27)
	... 3 more
```

**Comment by titusfortner** [comment] 2023-06-16 10:13
Is your computer behind a proxy of some kind? 
@bonigarcia do you know common cause of this connection forcibly closed error?

**Comment by bonigarcia** [comment] 2023-06-16 10:38
It is caused when connecting to the mirror metadata, and the response should be quick, so I don't think a timeout causes this. I believe this is caused by some network device (maybe a proxy or firewall).

**Comment by PraveenThirumoorthy** [comment] 2023-06-16 13:31
@titusfortner  and @bonigarcia  Am using the oracle VM machine to automate my test cases and this hosted on my laptop and connected to Internet. 

Can you please guide me what should i check to arrest this issue

**Comment by titusfortner** [comment] 2023-06-16 14:01
What do you get when navigating to site directly? 
https://raw.githubusercontent.com/SeleniumHQ/selenium/trunk/common/mirror/selenium

**Comment by PraveenThirumoorthy** [comment] 2023-06-16 14:10
Am able to access the URL
![image](https://github.com/SeleniumHQ/selenium/assets/122547514/2279f763-a07c-4687-84d8-1bdcaa1f1154)

**Comment by PraveenThirumoorthy** [comment] 2023-06-16 14:26
DO we need to set the proxy for the Selenium Manager to download the drivers? if so can you please let me know how to do that

**Comment by titusfortner** [comment] 2023-06-16 14:31
If you need to go through a proxy to access the internet, then, yes, you need to set that in the Options class and Selenium Manager will use it: https://www.selenium.dev/documentation/webdriver/drivers/options/#proxy

Otherwise, are you getting this error on every run, or is it intermittent?

**Comment by PraveenThirumoorthy** [comment] 2023-06-16 14:49
Am consistently getting this issue. Tried three times. and all three times failed.

Updated the code now
```
private static InternetExplorerOptions setInternetExlopererForEdge() 
{
	InternetExplorerOptions IEOptions  = new InternetExplorerOptions();
	IEOptions.attachToEdgeChrome();
	IEOptions.setCapability(CapabilityType.PROXY, getCBSProxy());
	return IEOptions;
}
  private static Proxy getCBSProxy() {
    Proxy cbsProxy = new Proxy();
    cbsProxy.setProxyType(Proxy.ProxyType.PAC);
    cbsProxy.setProxyAutoconfigUrl("http://1234/live-proxy.pac");
    return cbsProxy;
  }
```
  
  Still facing the same error

```
FINE: Applicable driver not found; attempting to install with Selenium Manager (Beta)
Jun 16, 2023 3:46:21 PM org.openqa.selenium.manager.SeleniumManager runCommand
FINE: Executing Process: [C:\Users\vagrant\AppData\Local\Temp\selenium-manager24154704643808130152559165918837\selenium-manager.exe, --browser, internet explorer, --output, json, --debug]
Exception in thread "main" org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browserName: internet explorer, proxy: Proxy(pac: http://10.27.240..., se:ieOptions: {ie.edgechromium: true}}
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:29)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:136)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:103)
	at selenium.WebDriverFactory.main(WebDriverFactory.java:156)
Caused by: org.openqa.selenium.WebDriverException: Unsuccessful command executed: [C:\Users\vagrant\AppData\Local\Temp\selenium-manager24154704643808130152559165918837\selenium-manager.exe, --browser, internet explorer, --output, json, --debug]
error sending request for url (https://raw.githubusercontent.com/SeleniumHQ/selenium/trunk/common/mirror/selenium): error trying to connect: An existing connection was forcibly closed by the remote host. (os error 10054)
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: InternetExplorerDriver
	at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:130)
	at org.openqa.selenium.manager.SeleniumManager.getDriverPath(SeleniumManager.java:251)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:27)
	... 3 more
```

**Comment by titusfortner** [comment] 2023-06-16 14:54
hmm, Selenium Manager is not picking up that proxy and it should be. Let me look at the code for it again.

**Comment by bonigarcia** [comment] 2023-06-16 15:13
@PraveenThirumoorthy Can you do the following test, please?

1. Download Selenium Manager from:

https://github.com/SeleniumHQ/selenium/blob/trunk/common/manager/windows/selenium-manager.exe

2. Open a shell, navigate to the folder containing that binary, and execute the following:

```
selenium-manager --browser iexplorer --debug 
```

3. If you get a connectivity problem error, you can try using your proxy:

```
selenium-manager --browser iexplorer --debug --proxy http://1234/live-proxy.pac
```

**Comment by PraveenThirumoorthy** [comment] 2023-06-16 15:20
@bonigarcia : My Organization is blocking this site to download the SeleniumManager. SInce its an application file it has been blocked by the Forcepoint. I have raised a request to download it with the internal helpdesk

I have that downloaded as a jar file in the maven repo as shown below
![image](https://github.com/SeleniumHQ/selenium/assets/122547514/7fa83b5b-91e3-41c5-8d85-36f5aa3b6586)

can we try anything with this jar file?

**Comment by titusfortner** [comment] 2023-06-16 16:57
If you extract the jar the binary should be in there.

**Comment by PraveenThirumoorthy** [comment] 2023-06-17 21:35
Thanks @titusfortner  for the idea. I have extracted the Application file using the below command in the cmd

`jar xf selenium-manager-4.10.0.jar`

@bonigarcia  I have execute the below commands and here is the output
`./selenium-manager --browser iexplorer --debug --proxy http://1234/live-proxy.pac`

![image](https://github.com/SeleniumHQ/selenium/assets/122547514/a8328f79-19ba-466c-ba0a-86d7ea985485)

Tried another direct proxy which we usually using another machines and found this
`./selenium-manager --browser iexplorer --debug --proxy http://abcd.efg.site:8080`
![image](https://github.com/SeleniumHQ/selenium/assets/122547514/5407f045-62ff-46c3-8ce4-644a63395ab8)

**Comment by titusfortner** [comment] 2023-06-17 21:44
What do you get without the proxy?

**Comment by titusfortner** [comment] 2023-06-17 21:44
Or do you know now that the machine requires a proxy?

**Comment by bonigarcia** [comment] 2023-06-18 13:30
The URL that Selenium Manager is trying to download is correct:

https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.10.0/IEDriverServer_Win32_4.10.0.zip

Nevertheless, the response to that URL is an HTML page. I suppose it is an HTML page that informs that the downloaded is blocked. 

It seems the proxy is restricted from downloading that zip file (which contains an exe file). I believe it is the same reason your organization is blocking downloading the Selenium Manager binary.

**Comment by PraveenThirumoorthy** [comment] 2023-06-19 16:55
> ./selenium-manager --browser iexplorer --debug

Am getting this when i do without proxy

![image](https://github.com/SeleniumHQ/selenium/assets/122547514/d0bca9b9-537b-4242-8151-f066d834de04)

yes without proxy we cannot access internet. Example when i disable the proxy in the Internet Option. i cannot access the Internet and getting this

![image](https://github.com/SeleniumHQ/selenium/assets/122547514/448aa300-bb03-4a7f-b560-d738a97e26c3)

**Comment by diemol** [comment] 2023-06-19 17:08
I believe the issue is what  @bonigarcia was pointing out, the proxy must be blocking zip files, to do a final check, you could use `wget` in PowerShell to see the returned content https://superuser.com/questions/362152/native-alternative-to-wget-in-windows-powershell/693179#693179. Remember to set the proxy if needed.

**Comment by titusfortner** [comment] 2023-12-28 16:30
Closing as we did not get more information after the previous suggestion.

**Closed as not planned by titusfortner** 2023-12-28 16:30 UTC
Labels: I-defect, A-needs-triaging
