### ISSUE TITLE
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms

### ISSUE THREAD

**Issue by SabariGanesh1987** [SeleniumHQ/selenium#2394] opened 2016-06-28 12:27 UTC
Hi,

I am able to run this code in other browsers but i am not able to run in FireFox. Can any one help on this Issue.

 org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
assic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1465086452000,"updateDate":1465086452000,"applyBackgroundUpdates":1,"skinnable":true,"size":22006,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"47.0","maxVersion":"47.0"}],"targetPlatforms":[],"seen":true}
1467116496271	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1467116496274	DeferredSave.extensions.json	DEBUG	Save changes
1467116496274	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1467116496274	addons.xpi-utils	DEBUG	Updating add-on states
1467116496278	addons.xpi-utils	DEBUG	Writing add-ons list
1467116496284	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1467116496291	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1467116496291	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1467116496293	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1467116496294	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1467116496296	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1467116496331	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1467116496331	addons.manager	DEBUG	Provider finished startup: XPIProvider
1467116496331	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1467116496331	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1467116496332	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1467116496333	addons.manager	DEBUG	Starting provider: GMPProvider
1467116496347	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1467116496348	addons.manager	DEBUG	Provider finished startup: GMPProvider
1467116496348	addons.manager	DEBUG	Starting provider: PluginProvider
1467116496348	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1467116496348	addons.manager	DEBUG	Provider finished startup: PluginProvider
1467116496349	addons.manager	DEBUG	Completed startup sequence
1467116498177	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1467116498177	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1467116498178	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1467116498612	DeferredSave.extensions.json	DEBUG	Write succeeded
1467116498612	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1467116498612	DeferredSave.extensions.json	DEBUG	Starting timer
1467116498633	addons.repository	DEBUG	No addons.json found.
1467116498634	DeferredSave.addons.json	DEBUG	Save changes
1467116498638	DeferredSave.addons.json	DEBUG	Starting timer
1467116498701	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1467116498701	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1467116498702	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1467116498711	DeferredSave.extensions.json	DEBUG	Starting write
1467116498715	DeferredSave.addons.json	DEBUG	Starting write
1467116499072	DeferredSave.extensions.json	DEBUG	Write succeeded
1467116499080	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:124)
	at Practice.main(Practice.java:29)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
assic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1465086452000,"updateDate":1465086452000,"applyBackgroundUpdates":1,"skinnable":true,"size":22006,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"47.0","maxVersion":"47.0"}],"targetPlatforms":[],"seen":true}
1467116496271	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1467116496274	DeferredSave.extensions.json	DEBUG	Save changes
1467116496274	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1467116496274	addons.xpi-utils	DEBUG	Updating add-on states
1467116496278	addons.xpi-utils	DEBUG	Writing add-ons list
1467116496284	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1467116496291	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1467116496291	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1467116496293	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1467116496294	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1467116496296	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1467116496331	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1467116496331	addons.manager	DEBUG	Provider finished startup: XPIProvider
1467116496331	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1467116496331	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1467116496332	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1467116496333	addons.manager	DEBUG	Starting provider: GMPProvider
1467116496347	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1467116496348	addons.manager	DEBUG	Provider finished startup: GMPProvider
1467116496348	addons.manager	DEBUG	Starting provider: PluginProvider
1467116496348	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1467116496348	addons.manager	DEBUG	Provider finished startup: PluginProvider
1467116496349	addons.manager	DEBUG	Completed startup sequence
1467116498177	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1467116498177	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1467116498178	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1467116498612	DeferredSave.extensions.json	DEBUG	Write succeeded
1467116498612	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1467116498612	DeferredSave.extensions.json	DEBUG	Starting timer
1467116498633	addons.repository	DEBUG	No addons.json found.
1467116498634	DeferredSave.addons.json	DEBUG	Save changes
1467116498638	DeferredSave.addons.json	DEBUG	Starting timer
1467116498701	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1467116498701	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1467116498702	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1467116498711	DeferredSave.extensions.json	DEBUG	Starting write
1467116498715	DeferredSave.addons.json	DEBUG	Starting write
1467116499072	DeferredSave.extensions.json	DEBUG	Write succeeded
1467116499080	DeferredSave.addons.json	DEBUG	Write succeeded

Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
System info: host: 'TVMATP403807D', ip: '10.155.245.141', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_77'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:124)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:124)
	at Practice.main(Practice.java:29)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
assic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1465086452000,"updateDate":1465086452000,"applyBackgroundUpdates":1,"skinnable":true,"size":22006,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"47.0","maxVersion":"47.0"}],"targetPlatforms":[],"seen":true}
1467116496271	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1467116496274	DeferredSave.extensions.json	DEBUG	Save changes
1467116496274	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1467116496274	addons.xpi-utils	DEBUG	Updating add-on states
1467116496278	addons.xpi-utils	DEBUG	Writing add-ons list
1467116496284	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1467116496291	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1467116496291	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1467116496293	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1467116496294	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1467116496296	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1467116496331	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1467116496331	addons.manager	DEBUG	Provider finished startup: XPIProvider
1467116496331	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1467116496331	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1467116496332	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1467116496333	addons.manager	DEBUG	Starting provider: GMPProvider
1467116496347	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1467116496348	addons.manager	DEBUG	Provider finished startup: GMPProvider
1467116496348	addons.manager	DEBUG	Starting provider: PluginProvider
1467116496348	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1467116496348	addons.manager	DEBUG	Provider finished startup: PluginProvider
1467116496349	addons.manager	DEBUG	Completed startup sequence
1467116498177	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1467116498177	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1467116498178	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1467116498612	DeferredSave.extensions.json	DEBUG	Write succeeded
1467116498612	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1467116498612	DeferredSave.extensions.json	DEBUG	Starting timer
1467116498633	addons.repository	DEBUG	No addons.json found.
1467116498634	DeferredSave.addons.json	DEBUG	Save changes
1467116498638	DeferredSave.addons.json	DEBUG	Starting timer
1467116498701	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1467116498701	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1467116498702	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1467116498711	DeferredSave.extensions.json	DEBUG	Starting write
1467116498715	DeferredSave.addons.json	DEBUG	Starting write
1467116499072	DeferredSave.extensions.json	DEBUG	Write succeeded
1467116499080	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	... 7 more

**Comment by juangj** [comment] 2016-06-28 18:50
This is a duplicate of #2110.

**Closed by juangj** 2016-06-28 18:50 UTC
