### ISSUE TITLE
Issue with 3.4.0 NuGet Package

### ISSUE THREAD

**Issue by ShamylaS** [SeleniumHQ/selenium#3984] opened 2017-05-06 23:31 UTC
## Meta -
OS:  Windows 10

Selenium Version:  3.4.0 NuGet Package

Browser:  Chrome

Browser Version:  58

## Expected Behavior -
The `RemoteWebDriver` instance should initialise with the `NuGet 3.4.0` package.

## Actual Behavior -
A null exception is returned: `System.NullReferenceException : Object reference not set to an instance of an object.`

Note:  The below code **works** with older `NuGet 3.x` packages running against the `3.x Selenium Standalone Server` .

## Steps to reproduce -

In Visual Studio, open the `NuGet Package Manger` and download `Selenium.Webdriver` and `Selenium.Support` `Version 3.4.0` NuGet packages.

Download `selenium-server-standalone-3.4.0.jar` and set up Selenium Grid locally.

Initialise `RemoteWebDriver` with the following snippet of code:
                
```
                var seleniumURL = "http://localhost:4444/wd/hub";
                var options = new ChromeOptions();

                return new RemoteWebDriver(seleniumURL, options.ToCapabilities());
```

**Comment by jimevans** [comment] 2017-05-07 10:48
Duplicate of #3808.

**Closed by jimevans** 2017-05-07 10:48 UTC
