### ISSUE TITLE
GetWindow handles returns 01 as the count.

### ISSUE THREAD

**Issue by PramodSenda** [SeleniumHQ/selenium#6583] opened 2018-10-26 12:16 UTC
## Meta -
OS:  
Windows 10
Selenium Version:  
2.53.1
Browser:  
Internet Explore  : 2.53.1

Browser Version:  
ie 11.1324.15063.0

## Expected Behavior -
Im using to open an application using ie. When browser launches the URL. it open ups another two windows.
User should be able to switch to launched window.

## Actual Behavior -
driver returns only count as 01 for driver.getWindowhandles().size();
So cannot switch to the window.

As i see application behaviour as below

- Once url launches. Application it self execute a java script as startup();
using that script application is opening the other windows. This might be a reason as i assume.

**Comment by barancev** [comment] 2018-11-06 06:20
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment] 2018-11-06 06:32
Please provide a [concise reproducible test case](http://sscce.org/) instead of a narrative description.

**Comment by mlesyk** [comment] 2018-12-10 00:10
I assume it could be my case. Please see steps and comparisons below:

Reproducing on: 
geckodriver-v0.23.0-win64
Firefox 62.0.3

Not reproducing on:
ChromeDriver 2.42.591088
Chrome 70.0.3538.102

1. Code with issue. If I try to switch to new tab after click() (driver.switchTo()) without Thread.sleep() - it doesn't work:
```
        driver.get("https://hotline.ua/computer-noutbuki-netbuki/vinga-twizzle-j116-j116-c40464b/prices/#cond_new");
        System.out.println("getWindowHandles size with 1 tab = " + driver.getWindowHandles().size());
        driver.findElement(By.xpath("//div[@data-selector='price-line']//div[@class='cell-7 cell-md']/a[@class='btn-orange btn-cell']")).click();
        System.out.println("getWindowHandles size with 2 tab = " + driver.getWindowHandles().size());
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
        }
        System.out.println("getWindowHandles size with 2 tab after Thread.sleep = " + driver.getWindowHandles().size());
```
2. Console output:
> getWindowHandles size with 1 tab = 1
> getWindowHandles size with 2 tab = 1
> 1544398512977	Marionette	DEBUG	[6442450994] Frame script loaded
> 1544398512978	Marionette	DEBUG	[6442450994] Frame script registered
> 1544398513032	Marionette	DEBUG	[6442450999] Frame script loaded
> 1544398513047	Marionette	DEBUG	[6442450999] Frame script registered
> getWindowHandles size with 2 tab after Thread.sleep = 2

3. Same code(issue is not reproducing even in Firefox), but without click() function, simply open new tab using Javascript "window.open(url, '_blank'):
```
        driver.get("https://hotline.ua/computer-noutbuki-netbuki/vinga-twizzle-j116-j116-c40464b/prices/#cond_new");
        System.out.println("getWindowHandles size with 1 tab = " + driver.getWindowHandles().size());
        ((JavascriptExecutor) driver).executeScript("window.open('https://www.itbox.ua/product/Noutbuk_Vinga_Twizzle_J116_J116-C40464B-p487019/?utm_source=Hotline&utm_medium=PriceList_cpc&utm_campaign=noutbuki&utm_content=U0314607&utm_term=Vinga_Twizzle_J116','_blank');");
        System.out.println("getWindowHandles size with 2 tab = " + driver.getWindowHandles().size());
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
        }
        System.out.println("getWindowHandles size with 2 tab after Thread.sleep = " + driver.getWindowHandles().size());

```
4. Console output:
>getWindowHandles size with 1 tab = 1
> 1544398855781	Marionette	DEBUG	[6442450987] Frame script loaded
> 1544398855782	Marionette	DEBUG	[6442450987] Frame script registered
> 1544398855814	Marionette	DEBUG	[6442450994] Frame script loaded
> 1544398855816	Marionette	DEBUG	[6442450994] Frame script registered
> getWindowHandles size with 2 tab = 2
> getWindowHandles size with 2 tab after Thread.sleep = 2

**Comment by barancev** [comment] 2018-12-10 05:30
@mlesyk And what's the issue? How many windows did you expect to obtain in this sample?

**Comment by mlesyk** [comment] 2018-12-10 08:18
@barancev I expect 2 windows in first sample right after `driver.findElement(By.xpath(...)).click();`
But for some reason I have to use `Thread.sleep();` to wait until getWindowHandles is updated.

**Comment by barancev** [comment] 2018-12-10 08:21
Yes, click does not wait for a new window to open, and window opening is not instant. Everything works as expected.

**Comment by barancev** [comment] 2018-12-10 08:32
Because Chrome is faster to open new windows?

**Comment by mlesyk** [comment] 2018-12-10 08:43
@barancev yes, maybe :)
Sorry, I've already read javadoc of WebElement.click() and found peculiarities for it's behavior.
But difference in Firefox and Chrome confused me, thus I thought it could be a bug and wrote here.

**Comment by barancev** [comment] 2018-12-10 11:10
Closing the issue as there is no reproduction scenario provided by the author.

**Closed by barancev** 2018-12-10 11:10 UTC
Labels: R-awaiting answer
