### ISSUE TITLE
Selenium 3: Drag and drop is not working as expected.

### ISSUE THREAD

**Issue by gs-schalla** [SeleniumHQ/selenium#2376] opened 2016-06-25 07:13 UTC
## Meta -
OS:  
Windows 10
Selenium Version:  
3
Browser:  
nigtly mozilla.

Below is the description 

org.openqa.selenium.UnsupportedCommandException: POST /session/9317eb24-e9cb-41d6-b2a1-7a7225da1269/moveto did not match a known command (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2 milliseconds
Build info: version: '2.42.2', revision: '75f266f', time: '2014-07-30 09:11:33'
System info: host: 'GSHYD-PK33NV6', ip: '172.16.1.162', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20160624030212, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=6264, browserVersion=50.0a1, platformVersion=10.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: 9317eb24-e9cb-41d6-b2a1-7a7225da1269

**Comment by lukeis** [comment] 2016-06-25 07:43
duplicate of #2285

**Closed by lukeis** 2016-06-25 07:43 UTC
