### ISSUE TITLE
ChromeDriver leaves alive threads that prevent normal termination of Java applications

### ISSUE THREAD

**Issue by rmunge** [SeleniumHQ/selenium#8258] opened 2020-04-28 15:10 UTC
## 🐛 Bug Report

The Java method ChromeDriver.quit() leaves alive non-daemon threads. This keeps the JVM running. Every Java application that makes use of ChromeDriver is forced to explicitely quit the JVM. JUnit tests only terminate because of JUnit's explicit use of  System.exit.

## To Reproduce

Execute the following Java program. It will not stop, because multiple non-daemon threads are still alive:

```
import org.openqa.selenium.chrome.ChromeDriver;

public class Application {

  public static void main(String[] args) {
    ChromeDriver driver = new ChromeDriver();
    driver.quit();
  }

}
```

## Expected behavior

After calling org.openqa.selenium.chromium.ChromiumDriver.quit() all non-daemon threads that were started by ChromiumDriver are stopped.

## Test script or set of commands reproducing this issue

```
import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.util.Set;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.chrome.ChromeDriver;

public class ChromeDriverTest {

  @Test
  public void noNonDeamonThreadsAliveAfterQuit() throws IOException {

    Set<Thread> threadsBefore = getRunningNonDaemonThreads();

    ChromeDriver driver = new ChromeDriver();
    driver.quit();

    Set<Thread> threadsAfter = getRunningNonDaemonThreads();

    assertThat(threadsAfter).containsOnlyElementsOf(threadsBefore);
  }

  private Set<Thread> getRunningNonDaemonThreads() {
    return Thread.getAllStackTraces().keySet().stream()
        .filter((thread) -> thread.isAlive() && !thread.isDaemon()).collect(Collectors.toSet());
  }

}
```
The following threads are still alive:

   Thread[AsyncHttpClient-3-1,5,main],
    Thread[AsyncHttpClient-3-3,5,main],
    Thread[AsyncHttpClient-3-2,5,main],
    Thread[AsyncHttpClient-timer-1-1,5,main

**Potential root cause:**
Class org.openqa.selenium.remote.http.netty.NettyClient creates an instance of AsyncHttpClient that is never closed. AsyncHttpClient implements java.io.Closable. Depending on the actual implementation, this may also lead to other kinds of resource leaks.

## Environment

OS: Windows 10
Browser: Chrome
Browser Driver version: ChromeDriver 81.0.4044.69
Language Bindings version: 4.0.0-alpha-5.jar

**Comment by diemol** [comment] 2020-05-22 22:26
I can reproduce this with the Alpha 5 but not anymore when I use master, nevertheless I cannot find the commit that fixed it. @barancev do you know?

**Comment by barancev** [comment] 2020-05-23 17:52
I made no attempt to fix this issue because we're going to deprecate and remove this HTTP client as the whole.

**Comment by diemol** [comment] 2020-05-24 10:20
I think the HTTP client is not related to this issue. In any case, I don't see this happening, and the next alpha will be released in around one week.
Feel free to open a new issue if this is present in the next alpha release.

**Closed by diemol** 2020-05-24 10:20 UTC
Labels: C-java
