### ISSUE TITLE
UnsupportedCommandException: mouseMoveTo Driver3.5.3 FF 55.0.3

### ISSUE THREAD

**Issue by kicasta** [SeleniumHQ/selenium#4595] opened 2017-08-30 06:01 UTC
## Meta -
OS:  Windows 7

Selenium Version:  3.5.3

Browser:  Firefox 

Browser Version:  55.0.3

## Expected Behavior -
Perform Hover
## Actual Behavior -
org.openqa.selenium.UnsupportedCommandException: mouseMoveTo
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
## Steps to reproduce -

--EDIT: Added an extract of a Test case and a min class implementation--

As soon as startTest is called it invokes act.moveToElement which fails with the above mentioned exception. 

```
public class BewertungExport extends TestCase {

    @Before
    public void setupTest() {
        Assume.assumeTrue("may not run test due to a previous error", mayRunTest());
    }

    @Test
    public void gesamtBewertung() throws Exception{

        try
        {
            StartPage startPage = new StartPage(driver);
            startPage.login(user.getUsername(), user.getPassword());

            startPage.startTest(4, "Dashboard");
	    startPage.clickElement(By.xpath(("//*[@id=\"abh\"]/div[3]/div/div[2]/div[2]/div[2]/div[3]/div/div/a"));

            ReviewsPage reviewsPage = new ReviewsPage(driver);
            reviewsPage.clickExport();
        }
        catch (Exception e)
        {
            System.err.println("Error while exporting: " + e.getMessage());
            errors.append(e.getMessage());
        }
    }
}


public class StartPage extends BasePage
{
    public StartPage(WebDriver driver)
    {
        super(driver);
    }

   
    public StartPage login(String userName, String password) throws Exception
    {
        fillInput(By.id("passwordinput-rf"), password, "Insert Password");
        fillInput(By.id("user-rf"), userName, "Insert username");
        clickElement(By.id("login-button-rf"), "click login button");
		
        return this;
    }

    public void startTest(int menuIndex, String linkText) throws Exception {
        HomeScreenData hD = TestSuite.getHomeScreenData();
		Actions act = new Actions(driver);
		act.moveToElement(findElement(By.linkText(hD.menuLogin[menuIndex]))).click().build().perform();
		clickElement(By.linkText(linkText));
    }
 
   
}
```

**Comment by barancev** [comment] 2017-08-30 06:55
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

And what geckodriver version do you use?

**Comment by doctordrue** [comment] 2017-08-30 13:06
I gues this is a duplicate of #4589

**Comment by barancev** [comment] 2017-08-30 13:31
@doctordrue May be it's a duplicate. but how can we decide without full reproduction code? We can't see how the driver was initialized.

@kicasta Please provide code that is runnable and does not depend on unknown external classes and methods.

**Comment by barancev** [comment] 2017-09-17 15:46
Closing the issue, there is no reproduction scenario provided.

**Closed by barancev** 2017-09-17 15:46 UTC
Labels: D-firefox, R-awaiting answer
