### ISSUE TITLE
[🐛 Bug]: webdriver exception with selenium 4.1.1 upgrade while launching firefox browser

### ISSUE THREAD

**Issue by Tejareddy1** [SeleniumHQ/selenium#10301] opened 2022-01-28 20:15 UTC
### What happened?

Getting WebDriverException with selenium upgrade from selenium 3.141.59 to 4.1.1 while launching firefox browser in my project.
Please help me with the solution if any configurations are required here.

Caused by: org.openqa.selenium.WebDriverException: Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'l100779min.rpega.com', ip: '2409:4070:2505:a772:57:ecac:b10d:51c0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '1.8.0_292'
Driver info: driver.version: FirefoxDriver
        at java.util.Optional.orElseThrow(Optional.java:290)
        at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:230)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)

### How can we reproduce the issue?

```shell
Getting WebDriverException with selenium upgrade from selenium 3.141.59 to 4.1.1 while launching firefox browser in my project.
Please help me with the solution if any configurations are required here.
I am using geckodriver binary 0.30.0 version

Caused by: org.openqa.selenium.WebDriverException: Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'l100779min.rpega.com', ip: '2409:4070:2505:a772:57:ecac:b10d:51c0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '1.8.0_292'
Driver info: driver.version: FirefoxDriver
        at java.util.Optional.orElseThrow(Optional.java:290)
        at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:230)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
```

### Relevant log output

```shell
Caused by: org.openqa.selenium.WebDriverException: Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'l100779min.rpega.com', ip: '2409:4070:2505:a772:57:ecac:b10d:51c0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '1.8.0_292'
Driver info: driver.version: FirefoxDriver
        at java.util.Optional.orElseThrow(Optional.java:290)
        at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:230)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
```

### Operating System

macOS

### Selenium version

java 1.8

### What are the browser(s) and version(s) where you see this issue?

firefox 96

### What are the browser driver(s) and version(s) where you see this issue?

gecko driver 0.30.0

**Comment by Tejareddy1** [comment] 2022-01-30 16:18
@diemol,  Can you please let me know in what cases we get this exception? Actually, I am not able to provide any reproducible scenario because this is not reproducible in the plain java main program and it is repeated in my project only. The same framework executes fine and is able to launch Firefox with the selenium 3.141.59 version. I am setting the binary path correctly. 
System.setProperty("webdriver.gecko.driver","path/to/binary"). Even I tried with WebdriverManager as well. Same is happening. It works fine within plain java main class but fails in the project.
 This issue is occurring only with the 4.0.0 version and above. I am using firefox-96.0.3. Any suggestions ?

**Comment by Tejareddy1** [comment] 2022-02-01 15:54
@diemol , I think my issue is same as #10312 but it is with gradle

**Comment by Tejareddy1** [comment] 2022-02-05 09:51
Hi @diemol , I am able to reproduce the issue. Please find the project created in the [github](https://github.com/Tejareddy1/FirefoxLaunchIssue). 
Steps to reproduce the issue:
1) clone the project and open the project 
2) run "./gradlew shadowJar" to create the FAT Jar file
3) once you create the jar , navigate to /build/libs folder and execute the created jar. (java -jar simpleProj-1.0-SNAPSHOT-all.jar).
4) you can find the issue.

For ease of the process, I have already created two jar files where one is with seleium-3.141.59 and one with selenium-4.1.1. which are in /build/libs folder, You can directly execute it reproduce the issue.

**Comment by pujagani** [comment] 2022-02-14 04:58
@Tejareddy1  Thank you for providing the details and the project. A working solution was suggested [here](https://github.com/SeleniumHQ/selenium/issues/10132#issuecomment-996893716). I would appreciate it if you can try that and provide feedback if that helped resolved your issue else I will dig into it. Thank you!

**Comment by Tejareddy1** [comment] 2022-02-14 12:38
Hi @pujagani , The actual requirement I had with Jar task type. I still get the issue with the below task. Could you please help to provide a solution for it.
```
task jarcreation(type: Jar){
    project.configurations.implementation.setCanBeResolved(true)
    archiveName "myApp.jar"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    zip64 true
    manifest {
        attributes(
                'Main-Class': 'Example'
        )
    }
        from {
            configurations["implementation"].collect { value -> value.isDirectory() ?
                    value : project.zipTree(value) }
        }

    exclude 'META-INF/*.RSA', 'META-INF/.SF', 'META-INF/*.DSA', 'META-INF/*.SF', 'META-INF/*SF',
            'META-INF/.RSA'

    with jar
}
```

FYI, With shadowJar it works fine with your solution

**Comment by Tejareddy1** [comment] 2022-02-16 14:07
@pujagani , Would you please help me with the above given task?

**Comment by pujagani** [comment] 2022-02-23 11:11
@Tejareddy1  I have attempted to fix the root cause in the above-mentioned PR and that should ideally fix the underlying issue of overwriting the `META-INF` files. The fix should be valid for Gradle and Maven projects. Once merged, it will be available as part of the next release.

**Comment by Tejareddy1** [comment] 2022-02-23 13:52
@pujagani , Thanks for the update. Actually, ServiceLoader is causing the issue. May I know the next release date?

**Comment by Tejareddy1** [comment] 2022-04-12 11:18
@pujagani, Still not able to launch the firefox browser

Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:585)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:248)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:164)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:118)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:106)
	at com.pega.drivers.PegaFirefoxDriver.initializeDriver(PegaFirefoxDriver.java:105)
	at com.pega.TestEnvironmentImpl.createDriverInstance(TestEnvironmentImpl.java:254)
	at com.pega.TestEnvironmentImpl.initializeEnvironment(TestEnvironmentImpl.java:178)
	at com.pega.TestEnvironmentImpl.initializeEnvironment(TestEnvironmentImpl.java:138)
	at com.pega.TestEnvironmentImpl.<init>(TestEnvironmentImpl.java:90)
	at com.pega.config.test.TestBase.<init>(TestBase.java:41)
	
I have tried with 4.1.3

**Comment by pujagani** [comment] 2022-04-12 13:59
The issue seems to be no longer related to running the FirefoxDriver using Selenium. It seems like the code is unable to talk to the geckodriver for some reason. The version of geckodriver to be used is also correct. Locally, I have not faced this problem with geckodriver. Unfortunately, there is no way to triage this without a reproducible code snippet/project. Please provide the same as mentioned in https://github.com/SeleniumHQ/selenium/issues/10301#issuecomment-1024627370

**Comment by germanodulio** [comment] 2022-04-22 13:55
I'm getting a slightly different error using 4.1.3

My capabilities are the following:
![image](https://user-images.githubusercontent.com/34327538/164727923-99dd474b-b97e-47ce-90c4-a17be427f313.png)

But for some reason the sessionId is null at the moment of executing the command to start the session using the capabilities.

The stack trace is the following:

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.1.3', revision: '7b1ebf28ef'
System info: host: 'DESKTOP-DEN36OV', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}, unhandledPromptBehavior: ignore}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}, unhandledPromptBehavior: ignore}}]
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:585)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:248)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:164)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:118)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:106)
        <removed our stacktrace>
Caused by: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableMap.of(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Lcom/google/common/collect/ImmutableMap;
        at org.openqa.selenium.chrome.AddHasCasting.getAdditionalCommands(AddHasCasting.java:38)
        at org.openqa.selenium.remote.Dialect.lambda$bindAdditionalCommands$1(Dialect.java:80)
        at java.lang.Iterable.forEach(Unknown Source)
        at org.openqa.selenium.remote.Dialect.bindAdditionalCommands(Dialect.java:79)
        at org.openqa.selenium.remote.Dialect.access$100(Dialect.java:29)
        at org.openqa.selenium.remote.Dialect$2.getCommandCodec(Dialect.java:54)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:567)
        ... 20 more


Do you think it is related or should I open a new issue?

**Comment by diemol** [comment] 2022-05-09 11:30
We will reopen when a way to reproduce the issue (ideally a GitHub repo) is provided. Thanks.

**Closed as completed by diemol** 2022-05-09 11:30 UTC
Labels: J-awaiting answer, C-java, I-defect
