### ISSUE TITLE
[🐛 Bug]: selenium-manager(1.60or1.61) in selenium-server-4.16.0.jar is not worked

### ISSUE THREAD

**Issue by timely-rain-0325** [SeleniumHQ/selenium#13396] opened 2024-01-05 03:36 UTC
### What happened?

 i used selenium-server-4.16.0.jar to start a node ，at the same time ,there was no driver in this computer and environment is win10 . according to the document(selenium manager), if there is no driver found,selenium-manager will automated download the driver for chrome native application. i typed commond in cmd tool ，"java -jar selenium-server-4.16.0.jar node --selenium-manager ture",
and then ,i get a issue as this,"No drivers have been configured or have been found on PATH". 

### How can we reproduce the issue?

```shell
please show me the reason for issue above. and tell me how to solve the issue,thanks
```

### Relevant log output

```shell
E:\UIProject\driver\serverone>java -jar selenium-server-4.16.1.jar node --selenium-manager true
11:26:10.010 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
11:26:10.026 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
11:26:10.371 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://0.0.0.0:4442 and tcp://0.0.0.0:4443
11:26:10.431 INFO [UnboundZmqEventBus.<init>] - Sockets created
11:26:11.437 INFO [UnboundZmqEventBus.<init>] - Event bus ready
11:26:11.873 INFO [NodeServer.createHandlers] - Reporting self as: http://192.168.0.103:5555
11:26:12.502 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
11:26:12.972 WARN [NodeOptions.addDetectedDrivers] - No drivers have been configured or have been found on PATH
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:119)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:166)
        at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:126)
        at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:184)
        at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:246)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
        ... 14 more
Caused by: org.openqa.selenium.grid.config.ConfigException: No drivers have been configured or have been found on PATH
        at org.openqa.selenium.grid.node.config.NodeOptions.addDetectedDrivers(NodeOptions.java:513)
        at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:232)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:79)
        ... 22 more
Exception in thread "Thread-0" java.lang.NullPointerException
        at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:78)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

### Operating System

windows 10

### Selenium version

only start a node without any language.but my environment variable include java11

### What are the browser(s) and version(s) where you see this issue?

chrome ,version:120.0.6099.200

### What are the browser driver(s) and version(s) where you see this issue?

no driver ,i want selenium-manager automated download.

### Are you using Selenium Grid?

selenium-server-4.16.0.jar and selenium-server-4.16.1.jar

**Comment by diemol** [comment] 2024-01-05 06:37
This is a duplicate of https://github.com/SeleniumHQ/selenium/issues/13261, this is fixed in the next version (to be released).

**Closed as not planned by diemol** 2024-01-05 06:37 UTC
Labels: I-defect

**Comment by timely-rain-0325** [comment] 2024-01-05 06:42
there is another issue ,I have add driver path in environment path,but now , issue is no driver found when start grid 
  
 
  
 
 -- 
 
 
  
  发自新浪邮箱客户端 
  
  
   
   在 今天 14:38，Diego Molina ***@***.***> 写道：  
    
   This is a duplicate of #13261, this is fixed in the next version (to be released).

**Comment by diemol** [comment] 2024-01-05 06:43
Share the logs please

**Comment by timely-rain-0325** [comment] 2024-01-05 06:58
E:\UIProject\driver>chromedriver.exe --version
ChromeDriver 120.0.6099.109 (3419140ab665596f21b385ce136419fde0924272-refs/branch-heads/6099@{#1483})

E:\UIProject\driver>java -jar selenium-server-4.16.1.jar node
14:56:04.148 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
14:56:04.164 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
14:56:04.494 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://0.0.0.0:4442 and tcp://0.0.0.0:4443
14:56:04.549 INFO [UnboundZmqEventBus.<init>] - Sockets created
14:56:05.559 INFO [UnboundZmqEventBus.<init>] - Event bus ready
14:56:06.030 INFO [NodeServer.createHandlers] - Reporting self as: http://192.168.0.103:5555
14:56:06.665 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
14:56:06.667 INFO [NodeOptions.discoverDrivers] - Looking for existing drivers on the PATH.
14:56:06.668 INFO [NodeOptions.discoverDrivers] - Add '--selenium-manager true' to the startup command to setup drivers automatically.
14:56:06.826 WARN [NodeOptions.addDetectedDrivers] - No drivers have been configured or have been found on PATH
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:119)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:166)
        at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:126)
        at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:184)
        at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:246)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
        ... 14 more
Caused by: org.openqa.selenium.grid.config.ConfigException: No drivers have been configured or have been found on PATH
        at org.openqa.selenium.grid.node.config.NodeOptions.addDetectedDrivers(NodeOptions.java:513)
        at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:232)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:79)
        ... 22 more
Exception in thread "Thread-0" java.lang.NullPointerException
        at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:78)
        at java.base/java.lang.Thread.run(Thread.java:834)
addtionally，my local chrome'version is 120.0.6099.200

**Comment by diemol** [comment] 2024-01-05 07:01
Then it does not find it in the PATH. You need to make sure you can execute the browser driver command from anywhere.

**Comment by timely-rain-0325** [comment] 2024-01-05 07:09
yes, i had add driver location to the environment path. now ,i turn to H: ,and execute command "chromedriver.exe" ,detail show as follow:
**H:\>chromedriver.exe
Starting ChromeDriver 120.0.6099.109 (3419140ab665596f21b385ce136419fde0924272-refs/branch-heads/6099@{#1483}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.**

**Comment by diemol** [comment] 2024-01-05 07:21
What happens if you put the file on the same directory where the jar is?

**Comment by timely-rain-0325** [comment] 2024-01-05 07:29
![微信截图_20240105152738](https://github.com/SeleniumHQ/selenium/assets/155626016/5d59f98c-f901-49db-b892-03cfa852883f)
E:\UIProject\driver\serverone>java -jar selenium-server-4.16.1.jar node
15:28:57.660 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
15:28:57.676 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
15:28:58.023 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://0.0.0.0:4442 and tcp://0.0.0.0:4443
15:28:58.095 INFO [UnboundZmqEventBus.<init>] - Sockets created
15:28:59.103 INFO [UnboundZmqEventBus.<init>] - Event bus ready
15:28:59.523 INFO [NodeServer.createHandlers] - Reporting self as: http://192.168.0.103:5555
15:29:00.190 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
15:29:00.192 INFO [NodeOptions.discoverDrivers] - Looking for existing drivers on the PATH.
15:29:00.192 INFO [NodeOptions.discoverDrivers] - Add '--selenium-manager true' to the startup command to setup drivers automatically.
15:29:00.352 WARN [NodeOptions.addDetectedDrivers] - No drivers have been configured or have been found on PATH
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:119)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:166)
        at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:126)
        at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:184)
        at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:246)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
        ... 14 more
Caused by: org.openqa.selenium.grid.config.ConfigException: No drivers have been configured or have been found on PATH
        at org.openqa.selenium.grid.node.config.NodeOptions.addDetectedDrivers(NodeOptions.java:513)
        at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:232)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:79)
        ... 22 more
Exception in thread "Thread-0" java.lang.NullPointerException
        at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:78)
        at java.base/java.lang.Thread.run(Thread.java:834)


**same issue**
