### ISSUE TITLE
IEDriver Connection refused on set_page_load_timeout

### ISSUE THREAD

**Issue by dev-e** [SeleniumHQ/selenium#5082] opened 2017-11-20 11:31 UTC
## Meta -
OS:  
Windows Server 2012 R2
Selenium Version:  
Grid Hub and Node both 3.7.1
Browser:  
Internet Explorer 11
Browser Version:  
11.0.9600.18763 (32-bit)
IEDriver Version:
3.7.0 x32
Python version
3.5.2
Python Selenium bindings Version
3.7.0
## Expected Behavior -
Setting page load timeout correctly and continue test
## Actual Behavior -
On test side:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 827, in set_page_load_timeout
    'pageLoad': int(float(time_to_wait) * 1000)})
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 309, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: java.net.ConnectException: Connection refused: connect
Stacktrace:
    at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0 (WebDriverServlet.java:245)
    at java.util.concurrent.Executors$RunnableAdapter.call (None:-1)
    at java.util.concurrent.FutureTask.run (None:-1)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (None:-1)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (None:-1)
    at java.lang.Thread.run (None:-1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 349, in test_selenium_ie
    self.test_scenario(driver, "INTERNETEXPLORER")
  File "test.py", line 38, in test_scenario
    driver.set_page_load_timeout(35)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 831, in set_page_load_timeout
    'type': 'page load'})
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 309, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: java.net.ConnectException: Connection refused: connect
Stacktrace:
    at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0 (WebDriverServlet.java:245)
    at java.util.concurrent.Executors$RunnableAdapter.call (None:-1)
    at java.util.concurrent.FutureTask.run (None:-1)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (None:-1)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (None:-1)
    at java.lang.Thread.run (None:-1)
```
On Node side:
```
2017-11-20 13:44:26.236:INFO:osjshC.ROOT:qtp631659383-12: org.openqa.selenium.re
mote.server.WebDriverServlet-4550bb58: Initialising WebDriverServlet
13:44:26.306 INFO - Found handler: org.openqa.selenium.remote.server.commandhand
ler.BeginSession@452521e2
13:44:26.321 INFO - /session: Executing POST on /session (handler: BeginSession)

13:44:26.482 INFO - Capabilities are: Capabilities {browserName: internet explor
er, platform: WINDOWS, version: }
13:44:26.490 INFO - Capabilities {browserName: internet explorer, platform: WIND
OWS, version: } matched class org.openqa.selenium.remote.server.ServicedSession$
Factory (provider: org.openqa.selenium.ie.InternetExplorerDriverService)
13:44:26.530 DEBUG - Waiting for [http://localhost:6039/status]
13:44:26.565 DEBUG - Polling http://localhost:6039/status
Started InternetExplorerDriver server (32-bit)
3.7.0.0
Listening on port 6039
Only local connections are allowed
13:44:27.073 DEBUG - sun.net.www.MessageHeader@5990dc685 pairs: {GET /status HTT
P/1.1: null}{User-Agent: Java/1.8.0_101}{Host: localhost:6039}{Accept: text/html
, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
13:44:27.078 DEBUG - sun.net.www.MessageHeader@5757392a7 pairs: {null: HTTP/1.1
200 OK}{Content-Length: 190}{Content-Type: application/json; charset=UTF-8}{Cach
e-Control: no-cache}{Vary: Accept-Charset, Accept-Encoding, Accept-Language, Acc
ept}{Accept-Ranges: bytes}{Connection: close}
13:44:27.130 DEBUG - CookieSpec selected: default
13:44:27.131 DEBUG - Auth cache not set in the context
13:44:27.132 DEBUG - Connection request: [route: {}->http://localhost:6039][tota
l kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
13:44:27.133 DEBUG - Connection leased: [id: 2][route: {}->http://localhost:6039
][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
13:44:27.134 DEBUG - Opening connection {}->http://localhost:6039
13:44:27.136 DEBUG - Connecting to localhost/127.0.0.1:6039
13:44:27.139 DEBUG - Connection established 127.0.0.1:2028<->127.0.0.1:6039
13:44:27.140 DEBUG - http-outgoing-2: set socket timeout to 10800000
13:44:27.141 DEBUG - Executing request POST /session HTTP/1.1
13:44:27.142 DEBUG - Target auth state: UNCHALLENGED
13:44:27.143 DEBUG - Proxy auth state: UNCHALLENGED
13:44:27.144 DEBUG - http-outgoing-2 >> POST /session HTTP/1.1
13:44:27.145 DEBUG - http-outgoing-2 >> Content-Type: application/json; charset=
utf-8
13:44:27.146 DEBUG - http-outgoing-2 >> Content-Length: 314
13:44:27.147 DEBUG - http-outgoing-2 >> Host: localhost:6039
13:44:27.148 DEBUG - http-outgoing-2 >> Connection: Keep-Alive
13:44:27.149 DEBUG - http-outgoing-2 >> User-Agent: Apache-HttpClient/4.5.3 (Jav
a/1.8.0_101)
13:44:27.151 DEBUG - http-outgoing-2 >> Accept-Encoding: gzip,deflate
13:44:27.152 DEBUG - http-outgoing-2 >> "POST /session HTTP/1.1[\r][\n]"
13:44:27.153 DEBUG - http-outgoing-2 >> "Content-Type: application/json; charset
=utf-8[\r][\n]"
13:44:27.154 DEBUG - http-outgoing-2 >> "Content-Length: 314[\r][\n]"
13:44:27.155 DEBUG - http-outgoing-2 >> "Host: localhost:6039[\r][\n]"
13:44:27.156 DEBUG - http-outgoing-2 >> "Connection: Keep-Alive[\r][\n]"
13:44:27.157 DEBUG - http-outgoing-2 >> "User-Agent: Apache-HttpClient/4.5.3 (Ja
va/1.8.0_101)[\r][\n]"
13:44:27.158 DEBUG - http-outgoing-2 >> "Accept-Encoding: gzip,deflate[\r][\n]"
13:44:27.159 DEBUG - http-outgoing-2 >> "[\r][\n]"
13:44:27.160 DEBUG - http-outgoing-2 >> "{[\n]"
13:44:27.161 DEBUG - http-outgoing-2 >> "  "desiredCapabilities": {"browserName"
:"internet explorer","platform":"WINDOWS","version":""},[\n]"
13:44:27.163 DEBUG - http-outgoing-2 >> "  "capabilities": {[\n]"
13:44:27.164 DEBUG - http-outgoing-2 >> "    "desiredCapabilities": {"browserNam
e":"internet explorer","platform":"WINDOWS","version":""},[\n]"
13:44:27.165 DEBUG - http-outgoing-2 >> "    "firstMatch": [[\n]"
13:44:27.166 DEBUG - http-outgoing-2 >> "      {"browserName":"internet explorer
","platformName":"windows"}[\n]"
13:44:27.167 DEBUG - http-outgoing-2 >> "    ][\n]"
13:44:27.168 DEBUG - http-outgoing-2 >> "  }[\n]"
13:44:27.169 DEBUG - http-outgoing-2 >> "}"
13:44:29.203 DEBUG - http-outgoing-2 << "HTTP/1.1 200 OK[\r][\n]"
13:44:29.205 DEBUG - http-outgoing-2 << "Content-Length: 691[\r][\n]"
13:44:29.207 DEBUG - http-outgoing-2 << "Content-Type: application/json; charset
=UTF-8[\r][\n]"
13:44:29.209 DEBUG - http-outgoing-2 << "Cache-Control: no-cache[\r][\n]"
13:44:29.210 DEBUG - http-outgoing-2 << "Vary: Accept-Charset, Accept-Encoding,
Accept-Language, Accept[\r][\n]"
13:44:29.212 DEBUG - http-outgoing-2 << "Accept-Ranges: bytes[\r][\n]"
13:44:29.213 DEBUG - http-outgoing-2 << "Connection: close[\r][\n]"
13:44:29.215 DEBUG - http-outgoing-2 << "[\r][\n]"
13:44:29.217 DEBUG - http-outgoing-2 << "{"value":{"capabilities":{"acceptInsecu
reCerts":false,"browserName":"internet explorer","browserVersion":"11","pageLoad
Strategy":"normal","platformName":"windows","proxy":{},"se:ieOptions":{"browserA
ttachTimeout":0,"elementScrollBehavior":0,"enablePersistentHover":true,"ie.brows
erCommandLineSwitches":"","ie.ensureCleanSession":false,"ie.fileUploadDialogTime
out":3000,"ie.forceCreateProcessApi":false,"ignoreProtectedModeSettings":false,"
ignoreZoomSetting":false,"initialBrowserUrl":"http://localhost:6039/","nativeEve
nts":true,"requireWindowFocus":false},"setWindowRect":true,"timeouts":{"implicit
":0,"pageLoad":300000,"script":30000}},"sessionId":"0473b413-6eeb-4e49-85b2-de52
33703c1e"}}[\n]"
13:44:29.224 DEBUG - http-outgoing-2 << "[\r][\n]"
13:44:29.225 DEBUG - http-outgoing-2 << HTTP/1.1 200 OK
13:44:29.229 DEBUG - http-outgoing-2 << Content-Length: 691
13:44:29.231 DEBUG - http-outgoing-2 << Content-Type: application/json; charset=
UTF-8
13:44:29.233 DEBUG - http-outgoing-2 << Cache-Control: no-cache
13:44:29.234 DEBUG - http-outgoing-2 << Vary: Accept-Charset, Accept-Encoding, A
ccept-Language, Accept
13:44:29.236 DEBUG - http-outgoing-2 << Accept-Ranges: bytes
13:44:29.238 DEBUG - http-outgoing-2 << Connection: close
13:44:29.243 DEBUG - http-outgoing-2: Close connection
13:44:29.246 DEBUG - Connection discarded
13:44:29.247 DEBUG - Connection released: [id: 2][route: {}->http://localhost:60
39][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]

13:44:29.281 INFO - Detected dialect: W3C
13:44:29.319 DEBUG - Executing: newSession [null, newSession {desiredCapabilitie
s=Capabilities {acceptInsecureCerts: false, browserName: internet explorer, brow
serVersion: 11, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(),
 se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enablePersist
entHover: true, ie.browserCommandLineSwitches: , ie.ensureCleanSession: false, i
e.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ignoreProtecte
dModeSettings: false, ignoreZoomSetting: false, initialBrowserUrl: http://localh
ost:6039/, nativeEvents: true, requireWindowFocus: false}, setWindowRect: true,
timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}}]
13:44:29.327 DEBUG - Executed: [null, newSession {desiredCapabilities=Capabiliti
es {acceptInsecureCerts: false, browserName: internet explorer, browserVersion:
11, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:ieOption
s: {browserAttachTimeout: 0, elementScrollBehavior: 0, enablePersistentHover: tr
ue, ie.browserCommandLineSwitches: , ie.ensureCleanSession: false, ie.fileUpload
DialogTimeout: 3000, ie.forceCreateProcessApi: false, ignoreProtectedModeSetting
s: false, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:6039/, n
ativeEvents: true, requireWindowFocus: false}, setWindowRect: true, timeouts: {i
mplicit: 0, pageLoad: 300000, script: 30000}}}]
13:44:29.388 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@657fd79
13:44:29.391 INFO - Handler thread for session 0473b413-6eeb-4e49-85b2-de5233703
c1e (internet explorer): Executing POST on /session/0473b413-6eeb-4e49-85b2-de52
33703c1e/window/maximize (handler: ServicedSession)
13:44:29.400 INFO - To upstream: {"windowHandle": "current", "sessionId": "0473b
413-6eeb-4e49-85b2-de5233703c1e"}
13:44:29.403 DEBUG - sun.net.www.MessageHeader@56cf73ce17 pairs: {POST /session/
0473b413-6eeb-4e49-85b2-de5233703c1e/window/maximize HTTP/1.1: null}{Accept: app
lication/json}{X-Forwarded-Host: selenium-hub-test.domain.ru}{X-Forwarded-Pr
oto: http}{X-Original-URI: /wd/hub/session/0473b413-6eeb-4e49-85b2-de5233703c1e/
window/maximize}{User-Agent: Python http auth}{Accept-Encoding: identity}{X-Forw
arded-Port: 80}{X-Forwarded-For: 172.16.70.36}{X-Real-IP: 172.16.70.36}{X-Scheme
: http}{Content-Type: application/json; charset=utf-8}{Connection: close}{Cache-
Control: no-cache}{Pragma: no-cache}{Host: localhost:6039}{Content-Length: 80}
13:44:29.418 DEBUG - sun.net.www.MessageHeader@5cbd522e7 pairs: {null: HTTP/1.1
200 OK}{Content-Length: 53}{Content-Type: application/json; charset=UTF-8}{Cache
-Control: no-cache}{Vary: Accept-Charset, Accept-Encoding, Accept-Language, Acce
pt}{Accept-Ranges: bytes}{Connection: close}
13:44:29.428 INFO - To downstream: {"value":{"height":1056,"width":1936,"x":-8,"
y":-8}}


13:44:29.466 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@657fd79
13:44:29.468 INFO - Handler thread for session 0473b413-6eeb-4e49-85b2-de5233703
c1e (internet explorer): Executing DELETE on /session/0473b413-6eeb-4e49-85b2-de
5233703c1e/cookie (handler: ServicedSession)
13:44:29.473 DEBUG - sun.net.www.MessageHeader@6145b19916 pairs: {DELETE /sessio
n/0473b413-6eeb-4e49-85b2-de5233703c1e/cookie HTTP/1.1: null}{Accept: applicatio
n/json}{X-Forwarded-Host: selenium-hub-test.amis.domain.ru}{X-Forwarded-Proto: ht
tp}{X-Original-URI: /wd/hub/session/0473b413-6eeb-4e49-85b2-de5233703c1e/cookie}
{User-Agent: Python http auth}{Accept-Encoding: identity}{X-Forwarded-Port: 80}{
X-Forwarded-For: 172.16.70.36}{X-Real-IP: 172.16.70.36}{X-Scheme: http}{Content-
Type: application/json;charset=UTF-8}{Connection: close}{Cache-Control: no-cache
}{Pragma: no-cache}{Host: localhost:6039}
13:44:29.539 DEBUG - sun.net.www.MessageHeader@5a11de4e7 pairs: {null: HTTP/1.1
200 OK}{Content-Length: 15}{Content-Type: application/json; charset=UTF-8}{Cache
-Control: no-cache}{Vary: Accept-Charset, Accept-Encoding, Accept-Language, Acce
pt}{Accept-Ranges: bytes}{Connection: close}
13:44:29.543 INFO - To downstream: {"value":null}


13:44:29.575 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@657fd79
13:44:29.578 INFO - Handler thread for session 0473b413-6eeb-4e49-85b2-de5233703
c1e (internet explorer): Executing POST on /session/0473b413-6eeb-4e49-85b2-de52
33703c1e/timeouts (handler: ServicedSession)
13:44:29.586 INFO - To upstream: {"pageLoad": 35000, "sessionId": "0473b413-6eeb
-4e49-85b2-de5233703c1e"}
13:44:29.588 DEBUG - sun.net.www.MessageHeader@2da43b717 pairs: {POST /session/0
473b413-6eeb-4e49-85b2-de5233703c1e/timeouts HTTP/1.1: null}{Accept: application
/json}{X-Forwarded-Host: selenium-hub-test.amis.domain.ru}{X-Forwarded-Proto: htt
p}{X-Original-URI: /wd/hub/session/0473b413-6eeb-4e49-85b2-de5233703c1e/timeouts
}{User-Agent: Python http auth}{Accept-Encoding: identity}{X-Forwarded-Port: 80}
{X-Forwarded-For: 172.16.70.36}{X-Real-IP: 172.16.70.36}{X-Scheme: http}{Content
-Type: application/json; charset=utf-8}{Connection: close}{Cache-Control: no-cac
he}{Pragma: no-cache}{Host: localhost:6039}{Content-Length: 72}
13:44:30.914 DEBUG - CookieSpec selected: default
13:44:30.916 DEBUG - Auth cache not set in the context
13:44:30.917 DEBUG - Connection request: [route: {}->http://selenium-hub-test.am
is.domain.ru:80][total kept alive: 1; route allocated: 2 of 2000; total allocated
: 2 of 2000]
13:44:30.922 DEBUG - http-outgoing-1 << "[read] I/O error: Read timed out"
13:44:30.923 DEBUG - Connection leased: [id: 1][route: {}->http://selenium-hub-t
est.amis.domain.ru:80][total kept alive: 0; route allocated: 2 of 2000; total all
ocated: 2 of 2000]
13:44:30.926 DEBUG - Stale connection check
13:44:30.929 DEBUG - http-outgoing-1 << "[read] I/O error: Read timed out"
13:44:30.930 DEBUG - http-outgoing-1: set socket timeout to 10800000
13:44:30.931 DEBUG - Executing request GET /grid/api/proxy?id=http://172.16.110.
8:5554 HTTP/1.1
13:44:30.933 DEBUG - Target auth state: UNCHALLENGED
13:44:30.934 DEBUG - Proxy auth state: UNCHALLENGED
13:44:30.936 DEBUG - http-outgoing-1 >> GET /grid/api/proxy?id=http://172.16.110
.8:5554 HTTP/1.1
13:44:30.938 DEBUG - http-outgoing-1 >> Host: selenium-hub-test.amis.domain.ru
13:44:30.939 DEBUG - http-outgoing-1 >> Connection: Keep-Alive
13:44:30.940 DEBUG - http-outgoing-1 >> User-Agent: Apache-HttpClient/4.5.3 (Jav
a/1.8.0_101)
13:44:30.942 DEBUG - http-outgoing-1 >> Accept-Encoding: gzip,deflate
13:44:30.944 DEBUG - http-outgoing-1 >> "GET /grid/api/proxy?id=http://172.16.11
0.8:5554 HTTP/1.1[\r][\n]"
13:44:30.946 DEBUG - http-outgoing-1 >> "Host: selenium-hub-test.amis.domain.ru[\
r][\n]"
13:44:30.948 DEBUG - http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
13:44:30.950 DEBUG - http-outgoing-1 >> "User-Agent: Apache-HttpClient/4.5.3 (Ja
va/1.8.0_101)[\r][\n]"
13:44:30.952 DEBUG - http-outgoing-1 >> "Accept-Encoding: gzip,deflate[\r][\n]"
13:44:30.953 DEBUG - http-outgoing-1 >> "[\r][\n]"
13:44:30.958 DEBUG - http-outgoing-1 << "HTTP/1.1 200 OK[\r][\n]"
13:44:30.960 DEBUG - http-outgoing-1 << "Server: nginx/1.9.13[\r][\n]"
13:44:30.961 DEBUG - http-outgoing-1 << "Date: Mon, 20 Nov 2017 10:44:28 GMT[\r]
[\n]"
13:44:30.963 DEBUG - http-outgoing-1 << "Content-Type: application/json;charset=
utf-8[\r][\n]"
13:44:30.965 DEBUG - http-outgoing-1 << "Content-Length: 941[\r][\n]"
13:44:30.966 DEBUG - http-outgoing-1 << "Connection: keep-alive[\r][\n]"
13:44:30.968 DEBUG - http-outgoing-1 << "[\r][\n]"
13:44:30.969 DEBUG - http-outgoing-1 << "{"success":true,"msg":"proxy found !","
id":"http://172.16.110.8:5554","request":{"class":"org.openqa.grid.common.Regist
rationRequest","name":null,"description":null,"configuration":{"remoteHost":"htt
p://172.16.110.8:5554","hubHost":"selenium-hub-test.amis.domain.ru","hubPort":-1,
"id":"http://172.16.110.8:5554","capabilities":[{"browserName":"internet explore
r","maxInstances":1,"platform":"WINDOWS","seleniumProtocol":"WebDriver","version
":"11"}],"downPollingLimit":2,"hub":"http://selenium-hub-test.amis.domain.ru","no
dePolling":5000,"nodeStatusCheckTimeout":5000,"proxy":"org.openqa.grid.selenium.
proxy.DefaultRemoteProxy","register":true,"registerCycle":5000,"unregisterIfStil
lDownAfter":60000,"cleanUpCycle":null,"custom":{},"host":"172.16.110.8","maxSess
ion":1,"servlets":[],"withoutServlets":[],"browserTimeout":240000,"debug":true,"
jettyMaxThreads":null,"log":null,"port":5554,"role":"node","timeout":60000,"enab
lePassThrough":true}}}"
13:44:30.977 DEBUG - http-outgoing-1 << HTTP/1.1 200 OK
13:44:30.978 DEBUG - http-outgoing-1 << Server: nginx/1.9.13
13:44:30.979 DEBUG - http-outgoing-1 << Date: Mon, 20 Nov 2017 10:44:28 GMT
13:44:30.980 DEBUG - http-outgoing-1 << Content-Type: application/json;charset=u
tf-8
13:44:30.982 DEBUG - http-outgoing-1 << Content-Length: 941
13:44:30.983 DEBUG - http-outgoing-1 << Connection: keep-alive
13:44:30.985 DEBUG - Connection can be kept alive indefinitely
13:44:30.986 DEBUG - Connection [id: 1][route: {}->http://selenium-hub-test.amis
.domain.ru:80] can be kept alive indefinitely
13:44:30.988 DEBUG - Connection released: [id: 1][route: {}->http://selenium-hub
-test.amis.domain.ru:80][total kept alive: 1; route allocated: 2 of 2000; total a
llocated: 2 of 2000]
13:44:30.990 DEBUG - The node is already present on the hub. Skipping registrati
on.
13:44:35.383 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@657fd79
13:44:35.385 INFO - Handler thread for session 0473b413-6eeb-4e49-85b2-de5233703
c1e (internet explorer): Executing POST on /session/0473b413-6eeb-4e49-85b2-de52
33703c1e/timeouts (handler: ServicedSession)
13:44:35.992 DEBUG - CookieSpec selected: default
13:44:35.993 DEBUG - Auth cache not set in the context
13:44:36.009 DEBUG - Connection request: [route: {}->http://selenium-hub-test.am
is.domain.ru:80][total kept alive: 1; route allocated: 2 of 2000; total allocated
: 2 of 2000]
13:44:36.013 DEBUG - http-outgoing-1 << "[read] I/O error: Read timed out"
13:44:36.014 DEBUG - Connection leased: [id: 1][route: {}->http://selenium-hub-t
est.amis.domain.ru:80][total kept alive: 0; route allocated: 2 of 2000; total all
ocated: 2 of 2000]
13:44:36.017 DEBUG - Stale connection check
13:44:36.019 DEBUG - http-outgoing-1 << "[read] I/O error: Read timed out"
13:44:36.020 DEBUG - http-outgoing-1: set socket timeout to 10800000
13:44:36.021 DEBUG - Executing request GET /grid/api/proxy?id=http://172.16.110.
8:5554 HTTP/1.1
13:44:36.023 DEBUG - Target auth state: UNCHALLENGED
13:44:36.026 DEBUG - Proxy auth state: UNCHALLENGED
13:44:36.040 DEBUG - http-outgoing-1 >> GET /grid/api/proxy?id=http://172.16.110
.8:5554 HTTP/1.1
13:44:36.049 DEBUG - http-outgoing-1 >> Host: selenium-hub-test.amis.domain.ru
13:44:36.050 DEBUG - http-outgoing-1 >> Connection: Keep-Alive
13:44:36.051 DEBUG - http-outgoing-1 >> User-Agent: Apache-HttpClient/4.5.3 (Jav
a/1.8.0_101)
13:44:36.053 DEBUG - http-outgoing-1 >> Accept-Encoding: gzip,deflate
13:44:36.055 DEBUG - http-outgoing-1 >> "GET /grid/api/proxy?id=http://172.16.11
0.8:5554 HTTP/1.1[\r][\n]"
13:44:36.057 DEBUG - http-outgoing-1 >> "Host: selenium-hub-test.amis.domain.ru[\
r][\n]"
13:44:36.060 DEBUG - http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
13:44:36.061 DEBUG - http-outgoing-1 >> "User-Agent: Apache-HttpClient/4.5.3 (Ja
va/1.8.0_101)[\r][\n]"
13:44:36.063 DEBUG - http-outgoing-1 >> "Accept-Encoding: gzip,deflate[\r][\n]"
13:44:36.064 DEBUG - http-outgoing-1 >> "[\r][\n]"
13:44:36.068 DEBUG - http-outgoing-1 << "HTTP/1.1 200 OK[\r][\n]"
13:44:36.069 DEBUG - http-outgoing-1 << "Server: nginx/1.9.13[\r][\n]"
13:44:36.070 DEBUG - http-outgoing-1 << "Date: Mon, 20 Nov 2017 10:44:34 GMT[\r]
[\n]"
13:44:36.073 DEBUG - http-outgoing-1 << "Content-Type: application/json;charset=
utf-8[\r][\n]"
13:44:36.074 DEBUG - http-outgoing-1 << "Content-Length: 941[\r][\n]"
13:44:36.075 DEBUG - http-outgoing-1 << "Connection: keep-alive[\r][\n]"
13:44:36.077 DEBUG - http-outgoing-1 << "[\r][\n]"
13:44:36.079 DEBUG - http-outgoing-1 << "{"success":true,"msg":"proxy found !","
id":"http://172.16.110.8:5554","request":{"class":"org.openqa.grid.common.Regist
rationRequest","name":null,"description":null,"configuration":{"remoteHost":"htt
p://172.16.110.8:5554","hubHost":"selenium-hub-test.amis.domain.ru","hubPort":-1,
"id":"http://172.16.110.8:5554","capabilities":[{"browserName":"internet explore
r","maxInstances":1,"platform":"WINDOWS","seleniumProtocol":"WebDriver","version
":"11"}],"downPollingLimit":2,"hub":"http://selenium-hub-test.amis.domain.ru","no
dePolling":5000,"nodeStatusCheckTimeout":5000,"proxy":"org.openqa.grid.selenium.
proxy.DefaultRemoteProxy","register":true,"registerCycle":5000,"unregisterIfStil
lDownAfter":60000,"cleanUpCycle":null,"custom":{},"host":"172.16.110.8","maxSess
ion":1,"servlets":[],"withoutServlets":[],"browserTimeout":240000,"debug":true,"
jettyMaxThreads":null,"log":null,"port":5554,"role":"node","timeout":60000,"enab
lePassThrough":true}}}"
13:44:36.087 DEBUG - http-outgoing-1 << HTTP/1.1 200 OK
13:44:36.088 DEBUG - http-outgoing-1 << Server: nginx/1.9.13
13:44:36.090 DEBUG - http-outgoing-1 << Date: Mon, 20 Nov 2017 10:44:34 GMT
13:44:36.094 DEBUG - http-outgoing-1 << Content-Type: application/json;charset=u
tf-8
13:44:36.097 DEBUG - http-outgoing-1 << Content-Length: 941
13:44:36.099 DEBUG - http-outgoing-1 << Connection: keep-alive
13:44:36.101 DEBUG - Connection can be kept alive indefinitely
13:44:36.102 DEBUG - Connection [id: 1][route: {}->http://selenium-hub-test.amis
.domain.ru:80] can be kept alive indefinitely
13:44:36.105 DEBUG - Connection released: [id: 1][route: {}->http://selenium-hub
-test.amis.domain.ru:80][total kept alive: 1; route allocated: 2 of 2000; total a
llocated: 2 of 2000]
13:44:36.107 DEBUG - The node is already present on the hub. Skipping registrati
on.
13:44:36.435 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@657fd79
13:44:36.436 INFO - Handler thread for session 0473b413-6eeb-4e49-85b2-de5233703
c1e (internet explorer): Executing GET on /session/0473b413-6eeb-4e49-85b2-de523
3703c1e/screenshot (handler: ServicedSession)
13:44:37.491 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@657fd79
13:44:37.494 INFO - Handler thread for session 0473b413-6eeb-4e49-85b2-de5233703
c1e (internet explorer): Executing DELETE on /session/0473b413-6eeb-4e49-85b2-de
5233703c1e (handler: ServicedSession)
13:44:38.507 INFO - Removing session org.openqa.selenium.remote.server.ServicedS
ession@657fd79
```
## Steps to reproduce -
Python code:
```
driver.delete_all_cookies()
driver.set_page_load_timeout(35)
wait = WebDriverWait(driver, 20)
try:
	driver.get("https://google.com")
except TimeoutException:
	print("Failed")
```

**Comment by jimevans** [comment] 2017-11-20 12:13
There are two bugs here. First, the Python bindings appear to be sending invalid payload to the IE driver (`sessionId` should not be part of the payload). Second, the IE driver doesn’t properly handle the invalid input.

**Comment by barancev** [comment] 2017-12-12 21:16
Duplicate of #4620

**Closed by barancev** 2017-12-12 21:16 UTC
Labels: D-IE
