### ISSUE TITLE
[🐛 Bug can't find driver in the path

### ISSUE THREAD

**Issue by timely-rain-0325** [SeleniumHQ/selenium#13441] opened 2024-01-15 08:13 UTC
### What happened?

 i have already rebuid my system win10. this moment , when i run command "java -jar selenium-server-4.16.1.jar", it hints that can't find driver in path. infact,there is already a chromedriver at the directory.
my question is that why it can't find driver in path , why? is it relationship with my rebuilding system or other limits of authority ?
by the way,before rebuilding system ,it running correctly.

### How can we reproduce the issue?

```shell
i don't known what happened , i just want run a selenium server, but failed
```

### Relevant log output

```shell
E:\>java -jar selenium-server-4.16.0.jar node  --selenium-manager true
15:26:19.000 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
15:26:19.016 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
15:26:19.394 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://0.0.0.0:4442 and tcp://0.0.0.0:4443
15:26:19.454 INFO [UnboundZmqEventBus.<init>] - Sockets created
15:26:20.461 INFO [UnboundZmqEventBus.<init>] - Event bus ready
15:26:20.951 INFO [NodeServer.createHandlers] - Reporting self as: http://172.25.96.1:5555
15:26:21.701 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
15:26:21.849 WARN [NodeOptions.addDetectedDrivers] - No drivers have been configured or have been found on PATH
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:119)
        at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:166)
        at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:126)
        at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:184)
        at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:246)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:122)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:51)
        at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:104)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
        at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:99)
        ... 14 more
Caused by: org.openqa.selenium.grid.config.ConfigException: No drivers have been configured or have been found on PATH
        at org.openqa.selenium.grid.node.config.NodeOptions.addDetectedDrivers(NodeOptions.java:513)
        at org.openqa.selenium.grid.node.config.NodeOptions.getSessionFactories(NodeOptions.java:232)
        at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:79)
        ... 22 more
Exception in thread "Thread-0" java.lang.NullPointerException
        at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:78)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

### Operating System

windows 10

### Selenium version

java 11

### What are the browser(s) and version(s) where you see this issue?

chrome ,version:120.0.6099.200

### What are the browser driver(s) and version(s) where you see this issue?

driver 120

### Are you using Selenium Grid?

selenium-server-4.16.0.jar

**Comment by diemol** [comment] 2024-01-15 08:52
This is a duplicate of #13396

**Closed as not planned by diemol** 2024-01-15 08:52 UTC
Labels: I-defect, A-needs-triaging

**Comment by timely-rain-0325** [comment] 2024-01-15 10:12
i am sorry ,i have got the answer . The win10 system‘s version is experience ,so i have rebuilt the system. now ,it is run correctly.
I'm so  sorry for my negligence and disturbing you. thanks very much.
