### ISSUE TITLE
[🚀 Feature]: Process PATH by Selenium Manager

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#11373] opened 2022-12-06 09:52 UTC
### Feature and motivation

Selenium Manager can discover if a driver is in the path and if the version is suitable to drive the browser. If the driver is not compatible (typically, since it is an old version), Selenium Manager should fix the problem (i.e., resolve the proper driver and ignore the driver in the `PATH`).

We can also log a `WARN` in Selenium Manager about it (something similar to mention, e.g., "_you have an old version of ... etc._"). That `WARN` trace should also be parsed in the bindings and logged to the final user again.

### Usage example

```
$ cargo run -- --browser chrome
WARN    Incompatible release of chromedriver (version 104.0.5112.79) detected in PATH (/home/boni/drivers/chromedriver)
INFO    /home/boni/.cache/selenium/chromedriver/linux64/106.0.5249.61/chromedriver
```

**Comment by titusfortner** [comment] 2022-12-06 21:25
fwiw, this is kind of a duplicate of #11356

**Comment by titusfortner** [comment] 2022-12-07 16:42
If we continue in the "fallback-only" mode, then we should only get a new version of the driver if it would otherwise fail (browserVersion - driverVersion > 1). We would also want to parse `--ignore-build-check` for chromium.

Alternately, we can move out of fallback mode and proactively update users to the latest version if any older version is found on PATH. I don't think we're ready for this, yet, though, and we should define what criteria need to be met to change modes.

**Comment by titusfortner** [comment] 2023-02-02 22:37
So, I'm going to close this since the Rust portion was already completed.

Also, fwiw, I've changed my mind about needing to process `--ignore-build-check`. If a user wants to use a specific, outdated version, they can pass it in directly and be responsible for it working or not working.

**Closed as completed by titusfortner** 2023-02-02 22:37 UTC
Labels: I-enhancement, C-rust
