### ISSUE TITLE
Selenium IE Driver Parallel Execution Issue with Grid setup

### ISSUE THREAD

**Issue by ManasBBSR** [SeleniumHQ/selenium#4137] opened 2017-06-06 17:16 UTC
## Meta -
OS:  Windows 7
Selenium Version:  
2.53.1
Browser:  
IE 11 (IE Update version - 11.0.42 KB4018271)
IEDriverServer version: 2.53.0/2.53.1

We are using a custom Selenium framework (xFramium version 1.0.6) which internally uses selenium 2.53.1 version and the RemoteWebDriver. 
We have around 3000 automation scripts which we have executed on Chrome using Selenium grid setup without much issues. But now when we are trying to execute the same set of test cases in IE, the first issue that we faced was with the objects not getting identified because of invalid xpaths which we had to update to CSS selectors for majority of the objects.  After fixing the object identification issues when we started executing the test cases on the Selenium grid with multiple instances the same set of test cases which passed locally are failing and it does not consistently fail on the same screen or the same object. We tried reducing the number of instances per selenium node to 1 the pass rate is better but not significant. 
We have done the standard setup required for IEDrvierServer in registry (Protected mode, BFCache etc.) even the noFrameMerging to allow IE to have a completely new session every time a new IE window is opened but still no luck in achieving higher pass percentage.

We tried updating the IEDriverServer version and Selenium-standalone server version to 3.4 but no improvement.

Below are the registry settings:
REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\0" /v 2500 /t REG_DWORD /d 00000000 /f
REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1" /v 2500 /t REG_DWORD /d 00000000 /f
REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\2" /v 2500 /t REG_DWORD /d 00000000 /f
REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3" /v 2500 /t REG_DWORD /d 00000000 /f
REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4" /v 2500 /t REG_DWORD /d 00000000 /f
REG ADD "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\0" /v 2500 /t REG_DWORD /d 00000000 /f
REG ADD "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1" /v 2500 /t REG_DWORD /d 00000000 /f
REG ADD "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\2" /v 2500 /t REG_DWORD /d 00000000 /f
REG ADD "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3" /v 2500 /t REG_DWORD /d 00000000 /f
REG ADD "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4" /v 2500 /t REG_DWORD /d 00000000 /f
REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\2" /v 2101 /t REG_DWORD /d 00000000 /f
REG ADD "HKCU\Software\Microsoft\Internet Explorer\Zoom" /v ZoomFactor /t REG_DWORD /d 000186a0 /f
REG ADD "HKCU\Software\Microsoft\Internet Explorer\Main" /v FrameMerging /t REG_DWORD /d 00000000 /f

IE Capabilities setting
ie.browserCommandLineSwitches = -private
ie.ensureCleanSession = true    

Appreciate any pointers to help resolve the issue.

**Comment by cgoldberg** [comment] 2017-06-06 22:20
"the same set of test cases which passed locally are failing and it does not consistently fail on the same screen or the same object."

what does failure mean in this context?
what code does it fail on?
what is the output when it fails?  etc etc.

just pointing out that you have a number of arbitrarily failing tests cases doesn't give maintainers a clue about what could be doing wrong or how to fix it.

**Comment by ManasBBSR** [comment] 2017-06-07 00:14
We have a set of steps to create an entity but the script does not complete all the steps successfully for the entity to be created. In one run it might fail in first step and in another run it might fail in step 1 or 2 or any other step. If we run the test case on a laptop or desktop with selenium server running on the same system the test cases might pass in a single with single instance of IE browser but same the same test case if we run on grid setup with virtual machines configured as nodes to run only 1 instance of IE then mostly it does not pass in a single run. If we run 2 test cases on the laptop in parallel with selenium server also running on the same laptop or desktop then it might pass but if we execute it on grid with the same node running both the tests then most likely they will fail.

It fails because of the following reasons:

- element not found
- buttons/links get clicked but it does not navigate to the desired next screen and it remains in the same page. Even though in the selenium node console it gives the message that link or button was clicked.
- clicking of radio button or checkbox but on the screen it does not actually get selected or checked
- not being able to enter values in dynamic webtables that consists of drop downs, textboxes, date fields etc. because of element identification issue.

The application is a packaged insurance product where most of the elements are rendered dynamically based on user action using JavaScript libraries.

Please let me know if any other details are required. Will check and share the logs if it can be shared.

**Comment by luke-hill** [comment] 2017-06-07 08:25
This is a known limitation of the IE driver. I'm sure someone like jimevans probably knows more. But the way in which IE runs as a driver is slower and can't be altered.

The best protocol/s you can introduce are re-running of IE tests, reduction of parallel tests when testing in IE and / or implementing some sort of Make/Rake task which will catch out these errors.

**Comment by ManasBBSR** [comment] 2017-06-07 16:23
@luke-hill thanks a lot for the input. We have tried in certain cases it works but in some cases the retry logic does not work so we have rerun the test cases. In our case cross browser testing is not a requirement but its a corporate mandate to use Internet so we are trying to use IE. Do you think executing the test cases in Chrome is better compared to IE?

**Comment by Xaeroxe** [comment] 2017-06-07 17:37
@ManasBBSR This might help: https://github.com/SeleniumHQ/selenium/pull/4143 it gives the IEDriver a bit better concurrency support.  You might try compiling that branch and using it as the IEDriverServer.  I'm curious if it helps in this instance or not.

**Comment by ManasBBSR** [comment] 2017-06-08 03:31
@Xaeroxe thanks. I don't have any experience with it but we will try and update.

**Comment by luke-hill** [comment] 2017-06-08 08:21
@ManasBBSR At our company we test IE (11), FF(47.0.1 - due to being on Se<3), and Chrome. This is due to our customer requirements.

IE is always the flakiest, and most prone to failures even when nothing has gone wrong (Like a Selenium::UnknownError for example).

After working with our Automation setup and being the main guy for over 6months, I can categorically say that IE will always be flaky the longer or more complicated your tests are, it's just not as good full stop. (From an Automation perspective).

Dependent on your facing-ness (i.e. if multiple users use your site or if you have different browser requirements). You should only use IE if you "have" to.

**Comment by jmresler** [comment] 2017-06-14 13:49
Keep in mind that inconsistent failures may have nothing to do with Selenium and everything to do with how the test cases are written. Several cases in point here are using a Thread.sleep which of course has a fixed wait time. The server may not always respond as quickly and therefore the test can pass one time and fail another. Another example relates to DOM rendering. The Chrome DOM engine is considerably faster than IE and therefore tests which run without conditions to handle the waits in Chrome, may not work at all in IE.

Secondly, Chrome natively supports xpath but IE does not. IE xpath searches use the Selenium framework to search which of course is affected by the IE dom, etc.

This is in no way intended to imply you don't have a real problem, the point here is that you need to do a little more research before the question can be answered accurately.

**Comment by ManasBBSR** [comment] 2017-06-15 04:47
@jmresler - We tried both implicit and explicit waits but inconsistencies were there. With implicit wait we tried waiting for element click-ability and visibility but many times Selenium is identifying the element as clickable but some back-end events are going on because of which the clicks do not work and many times the values we enter in input boxes disappear the moment focus was shifted to some other element. Secondly for dropdowns when we try to check if the value has been set correctly or not most of the time we get stale element reference because at run time the element tags also get changed from div to input and vice versa.

I replaced all Selenium methods with Javascript execute script and I'm getting positive results at-least getting more consistent results with single IE browser instance per node.

**Comment by jfisher446** [comment] 2017-06-18 23:29
@ManasBBSR - I'll echo luke-hill in saying that what you describe is what's been standard-fare when I've moved tests from non-IE execution to IE execution. You'll likely need to massage your tests until they're compatible with each of the drivers that you want to target. Based on what you've provided, I'd reiterate jmresler's comment also - keep in mind that inconsistent failures may have nothing to do with Selenium and everything to do with how the test cases are written.

> but many times Selenium is identifying the element as clickable but some back-end events are going on because of which the clicks do not work

What kind of back end events? Events from your page or what? 

> Secondly for dropdowns when we try to check if the value has been set correctly or not most of the time we get stale element reference because at run time the element tags also get changed from div to input and vice versa.

This sounds to be expected behavior. If the DOM for the element change, the prior reference will go stale and it will need to be located again using the applicable locator statement. I do think it's odd that you mention dropdowns having values but changing from divs to inputs....are you not referring to [Select](https://www.w3schools.com/tags/tag_select.asp) tags? Otherwise, how are these two points related?

> values we enter in input boxes disappear the moment focus was shifted to some other element

Is this consistently happening on specific elements? I'd first suspect the waiting strategies before and after the text input may be contributing to this.

**Comment by jmresler** [comment] 2017-06-19 03:08
@ManasBBSR I don't want to imply this will resolve your problem as I have had many issues with IE that I have not faced with other browsers. It is a different animal. Some things that have fixed issues are that I don't use annotated elements anymore. Although nice to use when they work, I have found that the application I work on has too much scripting going on and as a result I get many StaleElementExceptions with them. As a result we use the driver findBy methods with locators. It may be slower but the truth is that it's still always faster than a manual tester running the test.

I have had my developers not using as much straight scripting to click, instead preferring to use the sendKeys(Keys.SPACE), etc., for clicking. Remember that in the early days Windows was as much a keyboard OS as it was mouse based. Many keyboard events still work in IE. I can't say this with certainty but I suspect it has something to do with IE native events. So clicks and sendKeys are intermingled in our tests to make the test work. I hate the approach to *make the test work* because the truth is we should be testing the application as it is used but management rarely accepts that as an excuse  ;-) so you do what you have to.

I've never had much luck running IE tests in parallel so our current grid architecture runs one browser per machine. I think the behavior is as much caused by the require focus of IE as it is by the protected mode settings. Losing a handle to a window whether it's due to being grabbed by another test or due to the protected mode settings causing a  handle to be lost is difficult to determine but the net result is the same. I'm still working on a solution for us, for this.

I am having great difficulty getting tests to work even unreliably with Windows 10/IE 11 combination and it's confounding. What I have seen on the Selenium site indicates it's not a platform that is tested on. I have heard there is an issue with IE 11 that has recently broken the fixes implemented by the protected mode settings. I don't know if this is why I can't find documentation regarding Windows 10/IE 11 test combinations. If you know where I can find documentation of this I'd be grateful.

**Comment by ManasBBSR** [comment] 2017-06-19 03:46
@jfisher446 - I'm not an expert in Selenium but with my limited understanding I feel that if I write a statement element.click() and that works consistently in Chrome 100% of the time then I expect same thing in IE also but it does not happen. Even the issue does not happen on the same element consistently so it kind of becomes difficult to debug. But now I'm entering the values using JavaScript executor and it seems to be much much better and I have put check for stale element reference after each step based on the recommendation given in Stackoverflow by different people to handle stale element and it seems to work great. 
Secondly in our application we have the drop down values defined as a combination of 3 objects basically. One div tag within which an input tag is defined and on clicking the input tag becomes active and a pop up list appears from which we have to select the elements using text matching so the standard Select does not work.

Now the major challenge is with Parallel execution because we have around 3000 test cases which we need to complete it within 3-4 days which we were able to do with Chrome but with IE since we cannot execute more than 1 instance per machine and we do not have lot of machines available so we are kind of stuck. We have another application also which we have automated and in that we are able to do parallel execution with 3-4 IE instances per machine without any issues and also the inconsistencies that we were having for the current application are also not present which leads to the conclusion that the application is also doing its bit and preventing us to push more instances.

**Comment by ManasBBSR** [comment] 2017-06-19 03:53
@jmresler Now we are also using sendkeys(keys.Enter) for clicking on buttons and in most cases using Javascript clicks to fire the events and it seems to work lot better than the plain selenium element.clcik().

**Comment by luke-hill** [comment] 2017-06-19 09:46
@ManasBBSR - To your 2nd comment above mine. Patently that's not correct.

When you say to Selenium `element.click` what it does is it uses the drivers which are maintained outside of the Selenium project.

It's the same analogy as saying, kicking a football and kicking a rugby ball should have the same results (They're different things, but you provide the same method "kick").

here you're providing the same method `#click`, but you're using `chromedriver` and `IEDriverServer`

I do hope we can put this to bed now.

**Comment by ManasBBSR** [comment] 2017-06-19 16:20
@luke-hill Sure I think our inconsistencies has been resolved to great extent by using JavaScript executor but some help on how to have IE multiple instances executed on single node will have have regression window reduced by 50-60%.

**Comment by jfisher446** [comment] 2017-06-19 18:34
@ManasBBSR When we reached this point at my organization, we looked to stop maintaining our own Selenium Grid. We simply could not scale given our limitations...and we **had** to us IE. The story of how and why we did so are detailed in [this recent talk from SauceCon](https://www.youtube.com/watch?v=zqSdqRyftvU). Once we had this, we just executed one test per container and scaled to run in the time necessary. This alleviates a lot of the constraints that you're having to deal with now and would make life easier - if it's an option for you and the team.

**Comment by Xaeroxe** [comment] 2017-06-19 18:46
Has anyone here tried #4143 ?  I believe it might help here.

The selenium repository is currently responsible for the behavior of the IEDriverServer as Microsoft is no longer maintaining their IEDriverServer.  The whole kicking the football vs the rugby ball analogy isn't helpful in this context because both the football and the rugby ball have a spec for how to respond to "kick", one is following the spec and the other isn't (sometimes).  The one that isn't is maintained in this repository.

**Comment by ManasBBSR** [comment] 2017-06-20 18:34
@jfisher446 Thanks for the link will take a look at that.
@Xaeroxe I have not tried that as I don't have the technical expertise. I'm looking for someone in my organization to help me out and will update the forum if we succeed.

**Comment by diemol** [comment] 2019-03-24 21:20
This [comment](https://github.com/SeleniumHQ/selenium/issues/7025#issuecomment-475998385) applies to this issue as well.
Closing.

**Closed by diemol** 2019-03-24 21:20 UTC
Labels: D-IE
