### ISSUE TITLE
Drag and Drop not working in ChromeDriver 2.45.615291 Selenium

### ISSUE THREAD

**Issue by Pikkurthi** [SeleniumHQ/selenium#6864] opened 2019-01-18 08:45 UTC
## To Reproduce

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by Pikkurthi** [comment] 2019-01-18 08:46
WebElement From = driver.findElement(By.xpath("//*[@id='drag1']"));
WebElement To = driver.findElement(By.xpath("//*[@id='div2']"));

//Tried this
Actions act=new Actions(driver);
act.dragAndDrop(From, To).build().perform();

//Also this
Actions builder = new Actions(driver);
Action dragAndDrop = builder.clickAndHold(From).moveByOffset(-1, -1).moveToElement(To)
        .release(To)
        .build();
dragAndDrop.perform();


HTML
<script>
function allowDrop(ev) {
  ev.preventDefault();
}

function drag(ev) {
  ev.dataTransfer.setData("text", ev.target.id);
}

function drop(ev) {
  ev.preventDefault();
  var data = ev.dataTransfer.getData("text");
  ev.target.appendChild(document.getElementById(data));
}
</script>
</head>
<body>


<div id="div1" ondrop="drop(event)" ondragover="allowDrop(event)">
  <img src="img_w3slogo.gif" draggable="true" ondragstart="drag(event)" id="drag1" width="88" height="31">
</div>

<div id="div2" ondrop="drop(event)" ondragover="allowDrop(event)"></div>

</body>
</html>

**Comment by barancev** [comment] 2019-01-23 07:36
Duplicate of #1365

**Closed by barancev** 2019-01-23 07:36 UTC
