### ISSUE TITLE
FF browser not open using 3.0 beta.....Help me. i am using FF browser 48

### ISSUE THREAD

**Issue by kuttyv** [SeleniumHQ/selenium#2568] opened 2016-08-04 08:43 UTC
## Meta -
OS:  
 window 7 32bit 
Selenium Version:   3.0

Browser:  Firefox 48

Browser Version:   48

**Comment by AutomatedTester** [comment] 2016-08-04 14:03
Duplicate of #2559

**Closed by AutomatedTester** 2016-08-04 14:03 UTC

**Comment by kuttyv** [comment] 2016-08-04 14:24
hello boss tell me the solution..wt is duplicate 2559

**Comment by rlebl21** [comment] 2016-08-22 15:10
You need to get the gekko driver. Your error message should give you a link that directs you to where you can download this driver.
