### ISSUE TITLE
Context Click not working in FF48 (GeckoDriver) with selenium 3.0.0 beta 2

### ISSUE THREAD

**Issue by sunnysachdeva** [SeleniumHQ/selenium#2619] opened 2016-08-17 07:44 UTC
## Meta -
OS:  Windows 10
Selenium Version:  3.0.0-beta2
Browser: Firefox
Browser Version:  48.0 (GeckoDriver version v0.10.0)

## Expected Behavior -
right click should open menu options
## Actual Behavior -
No exception is thrown but Menu Option is NOT opened
## Steps to reproduce -
Test site used is http://automationpractice.com/index.php

// Code for right Click
Actions actions = new Actions(driver);
actions.contextClick(onElement);

**Comment by AutomatedTester** [comment] 2016-08-22 11:24
Duplicate of #2285

**Closed by AutomatedTester** 2016-08-22 11:24 UTC

**Comment by ajayraop** [comment] 2017-08-23 08:32
The below works for me on Firefox 52.3.0 ESR and Selenium 3.5.1

 public void mouseRightClickAndSelectOption(By locator, By contextMenuOption) {
        clickElement(locator);

        String script = "var evt = document.createEvent('MouseEvents');" + "evt.initMouseEvent('contextmenu',true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0,null);" + "arguments[0].dispatchEvent(evt);";

        try {
            ((JavascriptExecutor) driver).executeScript(script, getElement(locator));
        } catch (Exception ignored) {
        }

        clickElementcontextMenuOption);
    }


   public WebElement getElement(By locator) {
        waitForElement(locator);
        fluentWait(locator);
        return driver.findElement(locator);
    }

**Comment by forTestingSites** [comment] 2017-09-08 19:07
@AutomatedTester 

Context click is not working for me either. I have Win10, Sel 3.5.3 and FF 55.  Please open this ticket.

@ajayraop  Thank you for your code but it did not work for me in FF.
