### ISSUE TITLE
[Python] Can't do any operations on Alert objects.

### ISSUE THREAD

**Issue by josephwon0310** [SeleniumHQ/selenium#1493] opened 2016-01-18 16:37 UTC
When I try to do any dismissing, or accepting with alert objects including merely fetching the text, I get the following error:
<code>
Traceback (most recent call last):
  File "crawl.py", line 58, in <module>
    scrape(url.format(player))
  File "crawl.py", line 30, in scrape
    print alert.text
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/common/alert.py", line 65, in text
    return self.driver.execute(Command.GET_ALERT_TEXT)["value"]
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 102, in check_response
    value = json.loads(value_json)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
</code>

**Comment by ddavison** [comment] 2016-01-18 16:41
duplicate of #1478

**Closed by ddavison** 2016-01-18 16:41 UTC
