### ISSUE TITLE
[MacOS] GridLauncher starts on until.stalenessOf execution

### ISSUE THREAD

**Issue by zenonwch** [SeleniumHQ/selenium#3526] opened 2017-02-17 13:08 UTC
OS:  
masOS Sierra 10.12.3
Selenium Version:  
selenium-server-standalone-2.48.2, -3.0.1, -3.1.0
selenium-webdriver@2.48.2, @3.0.1, @3.1.0
Browser:  
Chrome 54-56

Node.js v7
mocha@2.3.4, @3.1.2, @3.2.0

## Expected Behavior -
No GridLaunchV2 (V3) start.

## Actual Behavior -
GridLauncherV2(V3) starts each time if tests execute until.stalenessOf()
Browser loses the focus. Further tests failed.

## Steps to reproduce -

npm install selenium-webdriver
npm install mocha
npm install chromedriver
download selenium-server-standalone

start selenium server:
`java -Dwebdriver.chrome.driver=node_modules/chromedriver/lib/chromedriver/chromedriver -jar .selenium-server-standalone-3.1.0.jar -port 4444 &`

run the following test.js file:
```
let test = require('selenium-webdriver/testing');
let wd = require('selenium-webdriver');
let until = require('selenium-webdriver').until;

let driver = new wd.Builder()
    .usingServer('http://localhost:4444/wd/hub')
    .withCapabilities(wd.Capabilities.chrome())
    .build();

test.describe('StalenessOf test', function () {

    test.before(() => driver.manage().timeouts().implicitlyWait(60000)
        .then(() => driver.manage().timeouts().pageLoadTimeout(60000))
        .then(() => driver.manage().timeouts().setScriptTimeout(60000))
        .then(() => driver.get('https://www.google.com/')));

    test.it('Test', () => driver.findElement(wd.By.id('gb_70'))
        .then(button => button.click()
            .then(() => driver.wait(
                until.stalenessOf(button),
                30000,
                'SignIn button still presents'
                )
            )
            .then(() => driver.sleep(60000))
        )
    );

    test.after(() => driver.quit());
});
```
[screenshot](https://i.imgur.com/80wapyf.png)

**Comment by jleyba** [comment] 2017-02-18 00:18
Sorry, but I can't reproduce this. Are you sure you don't have something else running that is trying to talk to your server?

**Comment by zenonwch** [comment] 2017-02-19 19:40
For start server and tests i'm using Grunt.

```
var path = require('path');

module.exports = function (grunt) {

    grunt.initConfig({
        mochaTest: {
            options: {
                ui: 'bdd',
                reporter: 'spec',
                timeout: 120000,
            },
            test: {
                src: ['test.js']
            }
        }
    });


    grunt.loadNpmTasks('grunt-continue');
    grunt.loadNpmTasks('grunt-mocha-test');

    grunt.registerTask('test', 'run:test');

    grunt.registerTask('run', testName => {
        grunt.task.run('startSelenium');
        grunt.task.run('continue:on');
        grunt.task.run('mochaTest:' + testName);
        grunt.task.run('continue:off');
        grunt.task.run('stopAllJavaProcesses');
        grunt.task.run('getTestStatus:' + testName);
    });

		grunt.registerTask('startSelenium', () => {
        require('child_process').spawn('java', [
            '-Dwebdriver.chrome.driver=node_modules/chromedriver/lib/chromedriver/chromedriver',
            '-jar', '.selenium-server-standalone-3.1.0.jar',
            '-log', 'selenium-server.log',
            '-port', '4444'
        ]);
    });
		
		grunt.registerTask('stopAllJavaProcesses', () => {
				require('child_process').exec('killall -9 java', (err, stdout, stderr) => {});
		});

    grunt.registerTask('getTestStatus', testName => {
        grunt.task.requires('mochaTest:' + testName);
    });
};
```

And running grunt task "test" using WebStorm IDE from JetBrains.

**Comment by diemol** [comment] 2020-04-07 15:49
Is this issue still happening with the latest versions @zenonwch?

**Comment by diemol** [comment] 2020-04-24 08:52
Closing this, for now, feel free to open a new issue in case the issue is still present.

**Closed by diemol** 2020-04-24 08:52 UTC
Labels: C-grid, C-nodejs, R-awaiting answer
