### ISSUE TITLE
[🐛 Bug]: ZScaler login prompt being triggered despite being signed in

### ISSUE THREAD

**Issue by rcornelsen-iccu** [SeleniumHQ/selenium#11516] opened 2023-01-05 18:58 UTC
### What happened?

We are seeing ZScaler login prompts during our test execution where we previously did not. We have confirmed that the browser session already had a valid ZScaler token when it was prompted. Unsure how to troubleshoot this further to identify the issue or if there is a misconfiguration with our proxy settings that's causing this.

### How can we reproduce the issue?

```shell
See description
```

### Relevant log output

```shell
See description
```

### Operating System

Windows 10 Enterprise

### Selenium version

Selenium-Java 4.1.3

### What are the browser(s) and version(s) where you see this issue?

Chrome 107.0.5304.122

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 108.0.5359.71

**Comment by titusfortner** [comment] 2023-01-05 19:32
Also, we can only fix issues in the latest version of Selenium, so please ensure the issue is present in 4.7.2

**Comment by diemol** [comment] 2023-01-09 23:53
Closing as we did not get more details.

**Closed as completed by diemol** 2023-01-09 23:53 UTC
Labels: I-defect, J-issue-template
