### ISSUE TITLE
WebDriver Not Compatible with Chrome/65.0.3325.146 on LINUX

### ISSUE THREAD

**Issue by dipesh17** [SeleniumHQ/selenium#5576] opened 2018-03-07 17:05 UTC
## Meta -
OS:  LINUX
Selenium Version:  3 .7. 1
Browser:  
Chrome/65.0.3325.146

-->

Browser Version:  
Chrome/65.0.3325.146 (64-bit)

## Expected Behavior -
Webdriver should be able to click on webelement
## Actual Behavior -
`Test Failed: org.testng.TestException: The following element is not clickable: [[[ChromeDriver: chrome on LINUX (d03e89e10987409f7705777f68e0204c)] -> id: topbar__login]]`

`searchFuncationality Test Failed: org.openqa.selenium.WebDriverException: unknown error: call function result missing 'value' (Session info: chrome=65.0.3325.146) (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 3.10.0-693.2.2.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 0 milliseconds Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z' System info: host: 'ip-10-30-74-198.eu-west-1.compute.internal', ip: '10.30.74.198', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-693.2.2.el7.x86_64', java.version: '1.8.0_152' Driver info: org.openqa.selenium.chrome.ChromeDriver Capabilities {acceptSslCerts: true, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.33.506092 (733a02544d189e..., userDataDir: /tmp/.org.chromium.Chromium...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 65.0.3325.146, webStorageEnabled: true} Session ID: 56e57cfa83a7d0ff79500c238608a779`

`addProductToCart Test Failed: org.testng.TestException: The following element is not clickable: [[[ChromeDriver: chrome on LINUX (f10c1eab1c3034045e01555ef00bef63)] -> css selector: .product-item-link]]`

## Steps to reproduce -
# Pre-requisite: setup a Linux OS and Chrome/65.0.3325.146 (64-bit)
# Create a selenium script to perform click operation.

## NOTE:
Chrome/65.0.3325.146 (64-bit) and MAC OS: test suite is working as expected on MAC OS.

**Comment by cgoldberg** [comment] 2018-03-07 17:11
you need to upgrade chromedriver to version 2.36 to use Chrome 65

**Comment by EllaVader** [comment] 2018-03-07 19:00
upgrading chrome driver to version 2.36 doesn't fix it.  Also seeing the problem on Windows 10

**Comment by blmstr** [comment] 2018-03-07 21:40
Chrome 65 should not be compatible with chromedriver 2.33 💔

I found the release notes a _kinda_ easy overview to see which versions are compatible: https://chromedriver.storage.googleapis.com/2.36/notes.txt

**Comment by GeorgeKaraszi** [comment] 2018-03-07 21:49
I'm seeing similar issue's too.

```
          Selenium::WebDriver::Error::SessionNotCreatedError:
            session not created exception: Chrome version must be >= 63.0.3239.0
              (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.14.12-041412-generic x86_64)
```

**Comment by EllaVader** [comment] 2018-03-07 21:54
Additionally -- this banner is now a back: "Chrome is being controlled by automated test software" and doing this 
`chromeOptions.AddArgument("--disable-infobars");`
doesn't supress it anymore like it used to.

**Comment by cgoldberg** [comment] 2018-03-07 22:06
@EllaVader the `--disable-infobars` flag was removed from Chrome 65.

**Comment by dipesh17** [comment] 2018-03-08 09:00
@cgoldberg 

- I've tried upgrading the Chrome driver 2.36 on the Linux operating system, however, I am having test failures and reason, "Element not clickable"
- Tried with headless and normal chrome browser

**Comment by herrtunante** [comment] 2018-03-08 17:04
I have also had problems using the CSS selectors to find elemenets (RemoteWebDriver) when upgrading to 2.36 (due to the Chrome 65 update which broke my previous integration with 2.33 )
I moved to 2.35 instead and now everything is working...

**Comment by barancev** [comment] 2018-03-08 17:30
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by tmertens** [comment] 2018-03-08 20:50
I'm seeing a possibly related issue where for Chrome headless v65 on linux, capybara-webkit / selenium-webdriver is reporting elements as non-visible when they are not on the visible portion of the page displayed in the viewport. You must scroll them into view for them to be considered "visible" by the driver:

(`scroll_to` taken from: https://stackoverflow.com/a/38085926)

```ruby
def scroll_to(element)
  script = <<-JS
    arguments[0].scrollIntoView(true);
  JS
  Capybara.current_session.driver.browser.execute_script(script, element.native)
end

top_of_page_element.visible? #=> true
bottom_of_page_element.visible? #=> false, bottom of page is scrolled out of view
scroll_to(bottom_of_page_element)
# Visibility is now reversed, the element at the top of the page is scrolled out of the viewport and reported as non-visible:
top_of_page_element.visible? #=> false
bottom_of_page_element.visible? #=> true
```

Tested with selenium-webdriver 3.10.0 and google-chrome-stable (65.0.3325.146-1) on Debian GNU/Linux 8.9 (jessie)

**Comment by EllaVader** [comment] 2018-03-08 22:55
@cgoldberg Regarding the `--disable-infobars` flag being removed from Chrome 65, what are we supposed to use in it's place to remove that banner?

**Comment by tmertens** [comment] 2018-03-08 23:07
@EllaVader that is unrelated to the original topic, you should open a separate ticket for discussion.

**Comment by lmtierney** [comment] 2018-03-09 02:58
@EllaVader that is a question for the chromium/chrome people. That flag is only passed through selenium.

**Comment by kpmueller** [comment] 2018-03-09 20:59
we are also seeing weird elements not being visible with chrome 65 and chromedriver 2.36

**Comment by cgoldberg** [comment] 2018-03-09 21:16
if you are having issues with chromedriver, you should submit them to the chromedriver tracker.

and when you do... please be much more descriptive than "seeing weird elements not being visible"

**Comment by tmertens** [comment] 2018-03-09 21:18
I am seeing the same behavior with headless firefox v58.0.1 selenium-webdriver 3.10.0 on Debian GNU/Linux 8.9 (jessie) and geckodriver-v0.19.1

**Comment by kpmueller** [comment] 2018-03-09 21:22
@cgoldberg would pasting random CSS visibility failures from our test code be helpful? I'm just saying, we're also having a problem. I will also submit the issues to chromedriver

**Comment by tmertens** [comment] 2018-03-09 22:08
This also appears to affect non-headless chrome v65.

**Comment by cgoldberg** [comment] 2018-03-09 23:17
@tmertens 

> would pasting random CSS visibility failures from our test code be helpful?

What *would* be helpful is a single reproducible example containing webdriver code and a snippet of markup to run it against... along with all relevant environment details and a description of expected and actual results.  see: http://sscce.org/

> I'm just saying, we're also having a problem

"me too" comments are unhelpful.

>  I will also submit the issues to chromedriver

thanks.  a link to the chromedriver bug here might be helpful.

**Comment by barancev** [comment] 2018-03-13 07:04
Please stop writing about all chroime-related problems to the same issue report!

Also, for issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by sbartoloti** [comment] 2018-03-13 12:14
I'm getting this error when I try to run test on linux, did anyone found a solution for this? 

`Test started: Check user account name
[Ljava.lang.StackTraceElement;@1ab06251
null
unknown error: unknown sessionId
  (Session info: chrome=65.0.3325.146)
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.13.0-1008-gcp x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'runner-7899691b-project-5528664-concurrent-065n6r', ip: '10.124.1.167', os.name: 'Linux', os.arch: 'amd64', os.version: '4.13.0-1008-gcp', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.36.540471 (9c759b81a907e7..., userDataDir: /tmp/.org.chromium.Chromium...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 65.0.3325.146, webStorageEnabled: true, webdriver.remote.sessionid: 5728a4d1fc2cdf2d21fac5874c3...}
Session ID: 5728a4d1fc2cdf2d21fac5874c30ac47`

before chrome update, everything was fine... please help?

**Comment by erajkovic** [comment] 2018-03-14 01:33
Sorry, I was assuming that my issue was the same or related, as I was using the same version - chrome=65.0.3325.146 / chromedriver=2.36.540471 
In my case, it turn out that some other code path was still running with 2.33 - Sorry for getting overloaded info in the thread.

**Comment by Lupeipei** [comment] 2018-03-15 08:30
I have got an error: unknown error: call function result missing 'value'.
my  headless chrome version 65.0.3325.162, and chrome driver version 2.34.522932. After google around, I upgrade the chrome driver to 2.36, but it's still not working.  can anyone give an suggestion?

**Comment by alippai** [comment] 2018-03-15 15:50
@Lupeipei It seems if the function result is void, ChromeDriver 2.36 returns the Success response with no 'value' field. Just add the extra check for the existence of the field.

**Comment by Lupeipei** [comment] 2018-03-16 01:23
@alippai Thanks for your help! I really appreciate it. 
I have figured it out yesterday. I have mistaken the version. I thought I have upgraded chrome driver successfully, but actually, I haven't. the old version is still there. After upgrading, everything is ok now.

**Comment by bedus-creation** [comment] 2018-03-18 09:23
Chrome and chromedriver should have matched version.

for example :

Chrome driver 2.37 Supports Chrome v64-66
Chrome driver 2.36 Supports Chrome v63-65
For more Details go to

https://sites.google.com/a/chromium.org/chromedriver/downloads

In your case You are using chrome 65 and driver 2.35 so you need to update driver to 

2.36

Steps:-

Go to https://chromedriver.storage.googleapis.com/index.html?path=2.36/ and download chrome driver .
Now extract the chromedriver and replace the driver inside of /path-to-your-project/vendor/laravel/dusk/bin/chromedriver-linux (Incase of linux)
Now Its done . 
[https://aammui.com/question/cannot-set-property-value-of-null-laravel-dusk](url)

**Comment by Lupeipei** [comment] 2018-03-19 01:29
@bedus-creation  got it!  Thanks a lot!

**Comment by Shubham-Saxena-IGT** [comment] 2018-03-20 10:51
I am using chromedriver 2.37 and chrome browser 65 but still facing the same issue i,e web element is not clickable.

**Comment by rafaelbgil** [comment] 2018-03-20 16:14
I have the same problem, I don't know if my problem is the chromedriver, chrome browser or its relationship.In my tests when I use Selenium with TestNG did not work, when I use only Selenium my tests work fine.

Is possible that the problem can be in my code, but the problem appears after update the chrome browser.

**Comment by cgoldberg** [comment] 2018-03-20 16:20
https://sites.google.com/a/chromium.org/chromedriver/help/clicking-issues

**Comment by Shubham-Saxena-IGT** [comment] 2018-03-21 06:27
I have used chromedriver 2.35 with Chrome 65. Somehow it worked for me. I know that on the official website chromedriver 2.35 only supports till Chrome 64 but my problem resolved after downgrading chromedriver to 2.35.

**Comment by barancev** [comment] 2018-03-21 06:32
Closing the issue as there is no reporoducetion scenario provided.

**Closed by barancev** 2018-03-21 06:32 UTC
Labels: D-chrome, R-awaiting answer

**Comment by NartanVyas** [comment] 2018-03-27 14:41
I can reproduce same error with google chrome v-65 , and I used following chrome driver versions but it is not working with any of them.
chrome driver 2.32, 2.33, 2.34, 2.35, 2.36, 2.37 with google chrome =65.0.3325.181.
selenium web driver: 3.0.1, 3.5.1, 3.6.0, 3.7.1, 3.10.0, 3.11.  
 Can you provide solution?

![image](https://user-images.githubusercontent.com/28960643/37974551-32965b1a-31ab-11e8-99d5-172c4a3c00db.png)

**Comment by kevin2107** [comment] 2018-03-28 16:27
I can also reproduce the error it has something to do with chrome 65. I downgraded my chrome version and the issues were fixed.

**Comment by DhanuRCG** [comment] 2018-03-30 10:08
Now you can use the latest chrome driver 2.37 to fix these issues.

You can find it here.

[https://chromedriver.storage.googleapis.com/index.html?path=2.37/]

**Comment by lucascaton** [comment] 2018-04-16 00:42
I can also reproduce the error here:

```ruby
Selenium::WebDriver::Error::UnknownError:
  unknown error: unknown sessionId
    (Session info: headless chrome=65.0.3325.181)
    (Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85),platform=Mac OS X 10.13.4 x86_64)
```

**Comment by lucascaton** [comment] 2018-04-18 09:14
I found out how to fix it:

Just pass a `user-agent` (you can [find some here](https://github.com/mururu/capybara-user_agent/blob/master/lib/capybara/user_agent.rb)):

```ruby
Capybara.register_driver :chrome do |app|
  Capybara::Selenium::Driver.new app, browser: :chrome,
    options: Selenium::WebDriver::Chrome::Options.new(args:
      ['headless', 'disable-gpu', "--user-agent='Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.7 (KHTML, like Gecko) Chrome/16.0.912.75 Safari/535.7'"])
end

Capybara.javascript_driver = :chrome
```

**Comment by benbonnet** [comment] 2018-04-22 14:05
200% unable to get a correct version of chromedriver via homebrew, ended up using a npm version

After making sure your chromedriver install points to the npm version (`which chromedriver` should output show node_modules in the path), the following comes handy in your rails_helper or support/capybara.rb config file : 

Selenium::WebDriver::Chrome.driver_path = '/path_to_npm_version/v9.3.0/bin/chromedriver'

Which is far from being optimal, but ended up working (after loads of struggle)

**Comment by MonSap** [comment] 2018-07-13 16:52
@dipesh17 Did You got solution for the issue mentioned. I am getting same error .WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 3.10.0-862.el7.x86_64 x86_64).
My browser version is 66.0

**Comment by Galileo1** [comment] 2018-07-25 05:45
same error here - I am using "--no-sandbox" flag even then -

Constructor threw exception; nested exception is org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57),platform=Linux 4.4.0-101-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.10 seconds
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'travis-job-9c490209-933f-4e86-bb9c-10d479d1c97f', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-101-generic', java.version: '1.8.0_151'
Driver info: driver.version: ChromeDriver

**Comment by schnmudgal** [comment] 2019-03-13 13:17
Chrome updated it latest version yesterday, and it not working again for ubuntu at least. Huh.
https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable

**Comment by cgoldberg** [comment] 2019-03-13 13:33
@schnmudgal please submit Chrome and ChromeDriver issues to the Chromium team:
https://bugs.chromium.org/p/chromedriver

When reporting, please be more specific than "not working", and be sure to include detailed version information for Chrome and ChromeDriver.
