### ISSUE TITLE
Not possible to specify client readTimeout via standalone jar

### ISSUE THREAD

**Issue by andrewnicols** [SeleniumHQ/selenium#9126] opened 2021-02-01 04:19 UTC
## 🐛 Bug Report

When starting Selenium via the `java -jar /path/to/jar standalone` approach, it is not possible to specify a read timeout.

I see that commits 8be1107124d1851e7185a17e2b1ce71e27e7bf2e and 46d3642954a3ca35151ca91077bb61804b98b735 have recently been added to allow configuration of the `readTimeout` via `clientConfig`, but this does not seem to be configurable via any documented configuration option.

## To Reproduce

```
java -jar bazel-bin/java/server/src/org/openqa/selenium/grid/selenium_server_deploy.jar standalone --config-help
```

## Expected behavior

A documented way to set `clientConfig.readTimeout`

## Test script or set of commands reproducing this issue

Reproduction available in https://github.com/andrewnicols/selenium-bugs-timeout

## Environment

OS: Mac OSX 11.1
Browser: N/A, but tested with Chrome
Browser version: Chrome 88.0
Browser Driver version: Chromedriver 88.0.4324.96
Language Bindings version: N/A but using php-webdriver/webdriver
Selenium Grid version (if applicable): trunk @ 65b253662f15c433e447ab24b461f9def1bbf6e4

**Comment by pujagani** [comment] 2021-02-01 11:12
Thank you for providing the details of the problem. The `clientconfig` as the name suggests is to help set `readTimeout` value per client. The changes in the commits allow the Selenium Java RemoteDriver to set the timeout per command which in turn sets the `readTimeout` of the underlying AsyntHttpPClient it uses. AFAIK, similar API is not implemented for other Selenium client bindings. To allow each Selenium client to set its own config value, there is no mechanism available to set the client config value while running the Grid in any mode. 

Addressing "It should be possible to configure Selenium's Netty client to wait for at least the timeouts configured via the setTimeouts command" - The setTimeouts purpose is different than interpreted. The implementation is as per the WebDriver specification https://w3c.github.io/webdriver/#set-timeouts.

**Comment by andrewnicols** [comment] 2021-02-01 11:28
Thanks for the detailed response @pujagani,

So in terms of not having tests fail due to the current default value of the `readTimeout`, what would you suggest?

This doesn’t affect us if we go direct to chromedriver or geckodriver because we can set the curl timeout, to a custom value so this problem is unique to Selenium

I’m aware that they’re a W3C specification feature, but as it stands I can set the pageLoad timeout to, for example, 90 seconds, but Selenium will close the connection after 60 well before I reach the pageLoad timeout - are those two things not related?

Is there anything planned to allow setting of the readTimeout in any grid mode?

**Comment by diemol** [comment] 2021-02-01 15:12
This is currently not implemented on the Grid, we have this on our todo list. 
I will close this issue because it is a duplicate of #9045

**Closed as completed by diemol** 2021-02-01 15:12 UTC
Labels: A-needs-triaging
