### ISSUE TITLE
Gets the element value null in headless mode

### ISSUE THREAD

**Issue by vvanglro** [SeleniumHQ/selenium#8603] opened 2020-08-04 13:01 UTC
## 🐛 Bug Report
Null when I use headless mode to get the td value in the third tr in the tbody，No headless mode is normal
The page element structure of a web page is the three tr groups in the tBody tag

## To Reproduce
Part of the code That I wrote：
a=WebDriverWait(driver,20).until(EC.presence_of_element_located((By.XPATH,'//a[text()="music"]//..//..//td[contains(@Class,"current")]'))).text
b = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, '//a[text()="live"]//..//..//td[contains(@Class,"current")]'))).text
c = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, '//a[text()="person"]//..//..//td[contains(@Class,"current")]'))).text
print(a)
print(b)
print(c)
A and B can get values, c can't，I tried to increase the waiting time, but it didn't work，The third td on the page is valuable
I got it right when I removed the headless mode

## Expected behavior

Gets the value of the third td

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: win10
Browser: Chrome
Browser version: 84.0.4147.105
Browser Driver version: 
Language Bindings version: python3.7.3
Selenium Grid version (if applicable): 3.141.0

**Comment by diemol** [comment] 2020-08-10 05:00
@WangHaoz I will close this since no complete reproduction scenario was provided, also given the fact where you mention that it only does not work on headless mode, it could be an issue with the browser driver / browser itself. You can try to open an issue to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.

**Closed as completed by diemol** 2020-08-10 05:00 UTC
