### ISSUE TITLE
Selenium calls intermittently return "value":{"data":null} and throw Selenium::WebDriver::Error::JavascriptError.

### ISSUE THREAD

**Issue by kapoorlakshya** [SeleniumHQ/selenium#4483] opened 2017-08-17 04:54 UTC
## Meta -
OS:  
Windows 7 and 8.1

Watir Version:
6.8.4

Selenium Version:  
3.5.2

Browser:  
IE

Browser Version:  
11.0.45

## Expected Behavior

Return readyState for case 1 and determine if element is displayed in case 2.

## Actual Behavior

**Case 1**

`{"script":"return document.readyState","args":[]}` intermittently returns `{"value":{"data":null,"error":"javascript error","message":"JavaScript error","stacktrace":""}}` when using `Watir::Browser#wait` (https://github.com/watir/watir/blob/master/lib/watir/browser.rb#L221).

```
2017-08-16 16:45:29 INFO Selenium    >>> http://127.0.0.1:5555/session/05af2e49-3ca6-4b54-9e38-8818b193b0e1/execute/sync | {"script":"return document.readyState","args":[]}
2017-08-16 16:45:29 INFO Selenium <- {"value":"loading"}
2017-08-16 16:45:29 INFO Selenium -> POST session/05af2e49-3ca6-4b54-9e38-8818b193b0e1/execute/sync
2017-08-16 16:45:29 INFO Selenium    >>> http://127.0.0.1:5555/session/05af2e49-3ca6-4b54-9e38-8818b193b0e1/execute/sync | {"script":"return document.readyState","args":[]}
2017-08-16 16:45:29 INFO Selenium <- {"value":"loading"}
2017-08-16 16:45:29 INFO Selenium -> POST session/05af2e49-3ca6-4b54-9e38-8818b193b0e1/execute/sync
2017-08-16 16:45:29 INFO Selenium    >>> http://127.0.0.1:5555/session/05af2e49-3ca6-4b54-9e38-8818b193b0e1/execute/sync | {"script":"return document.readyState","args":[]}
2017-08-16 16:45:29 INFO Selenium <- {"value":{"data":null,"error":"javascript error","message":"JavaScript error","stacktrace":""}}
```

**Case 2**

If I remove the `Watir::Browser#wait`,  the `Watir#Waitable#wait_while_present` returns a JavaScriptError as well when waiting while the page load spinner div is present. 

```
2017-08-16 17:01:43 INFO Selenium -> POST session/8c872f78-0e46-468f-8dbc-798931cad218/element
2017-08-16 17:01:43 INFO Selenium    >>> http://127.0.0.1:5555/session/8c872f78-0e46-468f-8dbc-798931cad218/element | {"using":"css selector","value":"#GlobalLoadingDiv"}
2017-08-16 17:01:43 INFO Selenium <- {"value":{"element-6066-11e4-a52e-4f735466cecf":"89c44322-858c-4d0b-8f76-c00581294203"}}
2017-08-16 17:01:43 INFO Selenium -> GET session/8c872f78-0e46-468f-8dbc-798931cad218/element/89c44322-858c-4d0b-8f76-c00581294203/name
2017-08-16 17:01:43 INFO Selenium <- {"value":"div"}
2017-08-16 17:01:43 INFO Selenium -> GET session/8c872f78-0e46-468f-8dbc-798931cad218/element/89c44322-858c-4d0b-8f76-c00581294203/displayed
2017-08-16 17:01:43 INFO Selenium <- {"value":true}
2017-08-16 17:01:43 INFO Selenium -> POST session/8c872f78-0e46-468f-8dbc-798931cad218/element
2017-08-16 17:01:43 INFO Selenium    >>> http://127.0.0.1:5555/session/8c872f78-0e46-468f-8dbc-798931cad218/element | {"using":"css selector","value":"#GlobalLoadingDiv"}
2017-08-16 17:01:43 INFO Selenium <- {"value":{"element-6066-11e4-a52e-4f735466cecf":"89c44322-858c-4d0b-8f76-c00581294203"}}
2017-08-16 17:01:43 INFO Selenium -> GET session/8c872f78-0e46-468f-8dbc-798931cad218/element/89c44322-858c-4d0b-8f76-c00581294203/name
2017-08-16 17:01:43 INFO Selenium <- {"value":"div"}
2017-08-16 17:01:43 INFO Selenium -> GET session/8c872f78-0e46-468f-8dbc-798931cad218/element/89c44322-858c-4d0b-8f76-c00581294203/displayed
2017-08-16 17:01:43 INFO Selenium <- {"value":true}
2017-08-16 17:01:43 INFO Selenium -> POST session/8c872f78-0e46-468f-8dbc-798931cad218/element
2017-08-16 17:01:43 INFO Selenium    >>> http://127.0.0.1:5555/session/8c872f78-0e46-468f-8dbc-798931cad218/element | {"using":"css selector","value":"#GlobalLoadingDiv"}
2017-08-16 17:01:43 INFO Selenium <- {"value":{"element-6066-11e4-a52e-4f735466cecf":"89c44322-858c-4d0b-8f76-c00581294203"}}
2017-08-16 17:01:43 INFO Selenium -> GET session/8c872f78-0e46-468f-8dbc-798931cad218/element/89c44322-858c-4d0b-8f76-c00581294203/name
2017-08-16 17:01:43 INFO Selenium <- {"value":"div"}
2017-08-16 17:01:43 INFO Selenium -> GET session/8c872f78-0e46-468f-8dbc-798931cad218/element/89c44322-858c-4d0b-8f76-c00581294203/displayed
2017-08-16 17:01:44 INFO Selenium <- {"value":{"data":null,"error":"javascript error","message":"Error determining if element is displayed","stacktrace":""}}
```

## Steps to reproduce

**Case 1 Steps**

1. Launch IE
2. Navigate to a page
2. Trigger an event that makes the browser readyState to be "loading" for > 5 seconds
3. Use Watir::Browser#wait to wait for the readyState to be "complete"

**Case 2 Steps**

1. Launch IE
2. Navigate to a page
3. Trigger a page refresh
3. Use Watir::Waitable#wait_while_present to wait on the page load spinner img/div which is present for 3-5 seconds.

Here is the Watir code:

```
# cheezy's page-object model
div(:global_loading_div, id: 'GlobalLoadingDiv')
div(:global_loading_background_div, id: 'GlobalLoadingBackgroundDiv')

# Watir method which makes both the calls that raise the exception.
def wait_for_page_load(timeout = 60)
  start_time = Time.now

  wait(timeout) # Wait for browser ReadyState to be 'complete' - case 1

  # Wait for loading... message to disappear - case 2
  global_loading_div_element.wait_while_present(timeout: timeout) # JSError here
  global_loading_background_div_element.wait_while_present(timeout: timeout)

  (Time.now - start_time)
end
```

Here is what the page loading div looks like. **Both cases fail as soon as this div is displayed.**

![iexplore_2017-08-17_15-00-17](https://user-images.githubusercontent.com/4314581/29435731-0305ebce-835d-11e7-9893-0c90bf642d53.png)

@titusfortner and I chatted on Slack and he thinks it (case 2?) could be related to https://github.com/SeleniumHQ/selenium/issues/4480. Tagging @jimevans.  

_Sent from my OnePlus ONEPLUS A3000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by p0deje** [comment] 2017-08-17 07:14
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by kapoorlakshya** [comment] 2017-08-17 21:22
@p0deje - I have added a short test case based on my Cucumber scenario. This issue is intermittent and I am only able to reproduce this 1/5 times.

**Comment by p0deje** [comment] 2017-08-18 05:24
Can you provide the simple application that will trigger "readyState" change or page refresh? Ideally, we'd use the site you're testing, but something that demonstrates the failure is also good.

**Comment by kapoorlakshya** [comment] 2017-08-23 17:53
@p0deje I don't know enough about JavaScript to do this gracefully, but here is a simple app to mimic how the loading popup in the AUT behaves: https://github.com/kapoorlakshya/selenium-4483

It also has a delayed GIF load (5s) using deelay.me which *I think* switches the browser's readyState to "loading". Hoping that you or @titusfortner could suggest changes or work with this.

**Comment by barancev** [comment] 2017-09-05 05:56
Yes, script execution can throw an exception if one attemprs to run a script while the page is refreshing. It's legit behavior. wait_while_* should suppress this exception

**Comment by p0deje** [comment] 2017-09-09 09:24
I've tried to reproduce the failing using https://github.com/kapoorlakshya/selenium-4483 and the following script:

```ruby
require 'selenium-webdriver'

begin
  driver = Selenium::WebDriver.for(:ie)
  driver.get 'file:///Users/p0deje/Desktop/selenium-4483/index.html'
  driver.find_element(id: 'showSpinner2').click

  loop do
    puts driver.execute_script 'return document.readyState'
  end
ensure
  driver.quit
end
```

However, document state is never changed to `loading` so the script perfectly fine.

@kapoorlakshya Is there any other way for me to reproduce the issue?

**Comment by kapoorlakshya** [comment] 2017-09-19 21:42
`driver.find_element(id: 'showSpinner2').click` is for case 2 - `Error determining if element is displayed`

You are right. I will work on a better example for the `readyState` (case 1).

**Comment by kapoorlakshya** [comment] 2017-09-26 22:45
@p0deje - If I were to give you an application where you could reproduce this, what would you look for? Unfortunately, I am unable to reproduce this behavior outside of my application. Can you please tell me what to look for and I can deliver those findings/logs to you?

**Comment by p0deje** [comment] 2017-09-29 06:09
1. Isolate the failure so that you have a small script that reproduces it.
2. Get rid of Watir, so that you have plain Selenium.
3. Enable full logging for Selenium (`Selenium::WebDriver.logger.level = :debug).
4. Enable full logging for ChromeDriver (`driver_opts: {log_path: 'chromedriver.log'}`).
5. Pull the browser logs `driver.manage.logs.get(:browser)`.

Depending on what you'll get, the further debugging might vary.

**Comment by barancev** [comment] 2017-10-18 11:50
Closing the issue as there is no known way to reproduce it. Feel free to reopen it in case you get new relevant information.

**Closed by barancev** 2017-10-18 11:50 UTC
Labels: C-rb, R-awaiting answer

**Comment by Tomalak** [comment] 2018-11-22 19:05
Seeing the exact same issue with IEDriverServer.exe version 3.9.0 and IE8 (don't ask, but apparently it can happen in IE11 just as well, so the IE version is probably not important). 

I'm using IE Driver with Python+Selenium against two servers (live and uat) that serve virtually identical pages, yet one of them (live) reproducibly works, the other one reproducibly fails. The websites themselves are both fully functional, there are no errors in the browser console. 

Doing a `curl` against the driver server results in:

    C:\>curl "http://127.0.0.1:4370/session/e38841f2-6a9e-412c-be3f-dee58c1fe90d/elements" -H "Content-Type: application/json" -d @data.json
    {"value":{"data":null,"error":"javascript error","message":"","stacktrace":""}}

Here `data.json` is `{"using": "css selector", "value": "body"}`.

A javascript error with no stacktrace at all isn't terribly helpful. How can I help debug this further?

**Comment by Tomalak** [comment] 2018-11-23 11:52
I think I found the reason. It has to do with the IE security zone settings.

To reproduce this we need a local web server (different machine, same LAN) that responds to both its physical server name and to its DNS name. I don't think the authentication scheme is an issue, but in my case the server is IIS with Windows authentication.

We also need a web server that responds to the URL `http://wpad/wpad.dat`, this time without authentication, and serves a file like this:

```
function FindProxyForURL(url, host) {
    return "DIRECT"; // use no proxy
}
```

It can be the same server as above, it doesn't matter. This is just to satisfy the WPAD (web proxy auto detection) mechanism.

In the Internet Options of the machine running webdriver: 

 - "Connections" tab: 
    - Proxy settings to "Automatically detect settings" (this will use the WPAD file)
 - "Security" tab:
    - Reset all zones to default level, just to level the playing field
    - Local Intranet zone set to "Automatically detect intranet network" & make sure the list under "Advanced" is empty.

Now, some tests:

- If a page is loaded with the server's physical name, IE will classify it as "Local intranet", because there is a rule that says *"host names without dots are intranet"*. Webdriver can be queried about the page and responds properly.
- If the same page is loaded with the server's DNS name, IE will *also* classify it as "Local intranet", because there is a rule *"anything that bypasses the proxy is intranet"* (proxy bypass is inferred from the PAC file). But something still is different - webdriver cannot be queried about this page, and returns `{"value":{"data":null,"error":"javascript error","message":"","stacktrace":""}}` instead.

**Solution** After explicitly adding the DNS name in question to the "Local intranet" zone list in the system's Internet Options, webdriver is able to correctly query the page. No reload of IE, webdriver or the page is necessary, just changing the security settings does the trick.

Clearly IE can be in a state where a page is implicitly classified as being "Intranet", but it still prevents access from external agents like webdriver. I suppose this happens only with the "Local intranet" zone, when a page is classified as "Internet", webdriver works fine.
