### ISSUE TITLE
Fixing ChromeDriverService initialization from capabilities

### ISSUE THREAD

**Issue by joegrasse** [SeleniumHQ/selenium#5312] opened 2018-01-09 19:32 UTC
## Meta -
OS:  CentOS 7
Selenium Version:  3.8.1
Browser:  Chrome 
Browser Version:  63.0.3239.108

## Expected Behavior -
Successful launch of chrome binary set by the capabilities flag on the Selenium Grid Node config 

## Actual Behavior -
The chrome version on the default path is launching instead.

## Steps to reproduce -
Start up a selenium grid node with -capabilities "browserName=chrome,chrome_binary=/custom/path/to/binary"

It looks like this was a feature that was in selenium pre 3.x, but then got removed and then added back for Firefox and Safari, but it looks like it might not have gotten added back for chrome.

Safari: [src](https://github.com/SeleniumHQ/selenium/blob/selenium-3.8.1/java/client/src/org/openqa/selenium/safari/SafariDriverService.java#L62)
Firefox: [src](https://github.com/SeleniumHQ/selenium/blob/selenium-3.8.1/java/client/src/org/openqa/selenium/firefox/GeckoDriverService.java#L74)
Chrome: [src](https://github.com/SeleniumHQ/selenium/blob/selenium-3.8.1/java/client/src/org/openqa/selenium/chrome/ChromeDriverService.java#L87)

**Comment by joegrasse** [comment] 2018-12-17 20:54
Just curious if this will get implemented soon?

**Comment by diemol** [comment] 2020-04-08 20:53
@joegrasse is this issue still present in the latest 3.x release or Selenium 4 alphas?

**Comment by diemol** [comment] 2020-04-24 08:55
Closing as we did not get answers, but if the issue is still present, please open a new one with all the requested info.

**Closed by diemol** 2020-04-24 08:55 UTC
Labels: C-grid, D-chrome, R-awaiting answer
