### ISSUE TITLE
Most of the times, unable to Launch the Default Firefox Browser

### ISSUE THREAD

**Issue by chaserocks** [SeleniumHQ/selenium#2306] opened 2016-06-17 06:53 UTC
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
ice\\FF","installDate":1464547452789,"updateDate":1464547452789,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":1877359,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"38.0a1","maxVersion":"43.0"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}
1466191067502	DeferredSave.extensions.json	DEBUG	Save changes
1466191067502	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1466191067502	addons.xpi-utils	DEBUG	Updating add-on states
1466191067503	addons.xpi-utils	DEBUG	Writing add-ons list
1466191067506	addons.xpi	DEBUG	Registering manifest for C:\Users\Chase\AppData\Local\Temp\anonymous1240936652447425222webdriver-profile\extensions\firebug@software.joehewitt.com.xpi
1466191067507	addons.xpi	DEBUG	Calling bootstrap method startup on firebug@software.joehewitt.com version 2.0.17
1466191067525	addons.xpi	DEBUG	Registering manifest for C:\Users\Chase\AppData\Local\Temp\anonymous1240936652447425222webdriver-profile\extensions\AdBlockerLavaSoftFF@lavasoft.com.xpi
1466191067526	addons.xpi	DEBUG	Calling bootstrap method startup on AdBlockerLavaSoftFF@lavasoft.com version 1.1.4
1466191067526	addons.xpi	DEBUG	Registering manifest for C:\Users\Chase\AppData\Local\Temp\anonymous1240936652447425222webdriver-profile\extensions\{e33788ea-0bb9-4502-9c77-bdc551afc8ab}.xpi
1466191067527	addons.xpi	DEBUG	Calling bootstrap method startup on {e33788ea-0bb9-4502-9c77-bdc551afc8ab} version 1.0.2.1
1466191067529	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1466191067529	addons.manager	DEBUG	Provider finished startup: XPIProvider
1466191067529	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1466191067529	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1466191067530	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1466191067530	addons.manager	DEBUG	Starting provider: GMPProvider
1466191067537	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1466191067537	addons.manager	DEBUG	Provider finished startup: GMPProvider
1466191067537	addons.manager	DEBUG	Starting provider: PluginProvider
1466191067538	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1466191067538	addons.manager	DEBUG	Provider finished startup: PluginProvider
1466191067538	addons.manager	DEBUG	Completed startup sequence
1466191067760	DeferredSave.extensions.json	DEBUG	Starting write
1466191067998	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1466191067999	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1466191067999	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1466191068001	DeferredSave.extensions.json	DEBUG	Write succeeded
JavaScript error: chrome://fxdriver/content/server.js, line 61: uncaught exception: [object Object]
JavaScript error: chrome://fxdriver/content/server.js, line 61: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
JavaScript error: chrome://adaware/content/js/https/ChannelReplacement.js, line 18: ReferenceError: Ci is not defined
1466191069240	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1466191069240	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1466191069240	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
JavaScript error: chrome://adaware/content/js/https/IOUtil.js, line 130: SyntaxError: missing ( after for
JavaScript error: chrome://adaware/content/js/https/HTTPSRules.js, line 64: ReferenceError: Cc is not defined
JavaScript error: chrome://adaware/content/js/https/Cookie.js, line 75: SyntaxError: missing ( after for
JavaScript error: chrome://adaware/content/js/https/HTTPS.js, line 159: SyntaxError: missing ( after for

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at Jun17.MaximiseResize.main(MaximiseResize.java:14)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
ice\\FF","installDate":1464547452789,"updateDate":1464547452789,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":1877359,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"38.0a1","maxVersion":"43.0"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}
1466191067502	DeferredSave.extensions.json	DEBUG	Save changes
1466191067502	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1466191067502	addons.xpi-utils	DEBUG	Updating add-on states
1466191067503	addons.xpi-utils	DEBUG	Writing add-ons list
1466191067506	addons.xpi	DEBUG	Registering manifest for C:\Users\Chase\AppData\Local\Temp\anonymous1240936652447425222webdriver-profile\extensions\firebug@software.joehewitt.com.xpi
1466191067507	addons.xpi	DEBUG	Calling bootstrap method startup on firebug@software.joehewitt.com version 2.0.17
1466191067525	addons.xpi	DEBUG	Registering manifest for C:\Users\Chase\AppData\Local\Temp\anonymous1240936652447425222webdriver-profile\extensions\AdBlockerLavaSoftFF@lavasoft.com.xpi
1466191067526	addons.xpi	DEBUG	Calling bootstrap method startup on AdBlockerLavaSoftFF@lavasoft.com version 1.1.4
1466191067526	addons.xpi	DEBUG	Registering manifest for C:\Users\Chase\AppData\Local\Temp\anonymous1240936652447425222webdriver-profile\extensions\{e33788ea-0bb9-4502-9c77-bdc551afc8ab}.xpi
1466191067527	addons.xpi	DEBUG	Calling bootstrap method startup on {e33788ea-0bb9-4502-9c77-bdc551afc8ab} version 1.0.2.1
1466191067529	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1466191067529	addons.manager	DEBUG	Provider finished startup: XPIProvider
1466191067529	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1466191067529	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1466191067530	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1466191067530	addons.manager	DEBUG	Starting provider: GMPProvider
1466191067537	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1466191067537	addons.manager	DEBUG	Provider finished startup: GMPProvider
1466191067537	addons.manager	DEBUG	Starting provider: PluginProvider
1466191067538	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1466191067538	addons.manager	DEBUG	Provider finished startup: PluginProvider
1466191067538	addons.manager	DEBUG	Completed startup sequence
1466191067760	DeferredSave.extensions.json	DEBUG	Starting write
1466191067998	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1466191067999	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1466191067999	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1466191068001	DeferredSave.extensions.json	DEBUG	Write succeeded
JavaScript error: chrome://fxdriver/content/server.js, line 61: uncaught exception: [object Object]
JavaScript error: chrome://fxdriver/content/server.js, line 61: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
JavaScript error: chrome://adaware/content/js/https/ChannelReplacement.js, line 18: ReferenceError: Ci is not defined
1466191069240	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1466191069240	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1466191069240	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
JavaScript error: chrome://adaware/content/js/https/IOUtil.js, line 130: SyntaxError: missing ( after for
JavaScript error: chrome://adaware/content/js/https/HTTPSRules.js, line 64: ReferenceError: Cc is not defined
JavaScript error: chrome://adaware/content/js/https/Cookie.js, line 75: SyntaxError: missing ( after for
JavaScript error: chrome://adaware/content/js/https/HTTPS.js, line 159: SyntaxError: missing ( after for

Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'Chase-PC', ip: '192.168.1.103', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_79'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:124)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at Jun17.MaximiseResize.main(MaximiseResize.java:14)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
ice\\FF","installDate":1464547452789,"updateDate":1464547452789,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":1877359,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"38.0a1","maxVersion":"43.0"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}
1466191067502	DeferredSave.extensions.json	DEBUG	Save changes
1466191067502	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1466191067502	addons.xpi-utils	DEBUG	Updating add-on states
1466191067503	addons.xpi-utils	DEBUG	Writing add-ons list
1466191067506	addons.xpi	DEBUG	Registering manifest for C:\Users\Chase\AppData\Local\Temp\anonymous1240936652447425222webdriver-profile\extensions\firebug@software.joehewitt.com.xpi
1466191067507	addons.xpi	DEBUG	Calling bootstrap method startup on firebug@software.joehewitt.com version 2.0.17
1466191067525	addons.xpi	DEBUG	Registering manifest for C:\Users\Chase\AppData\Local\Temp\anonymous1240936652447425222webdriver-profile\extensions\AdBlockerLavaSoftFF@lavasoft.com.xpi
1466191067526	addons.xpi	DEBUG	Calling bootstrap method startup on AdBlockerLavaSoftFF@lavasoft.com version 1.1.4
1466191067526	addons.xpi	DEBUG	Registering manifest for C:\Users\Chase\AppData\Local\Temp\anonymous1240936652447425222webdriver-profile\extensions\{e33788ea-0bb9-4502-9c77-bdc551afc8ab}.xpi
1466191067527	addons.xpi	DEBUG	Calling bootstrap method startup on {e33788ea-0bb9-4502-9c77-bdc551afc8ab} version 1.0.2.1
1466191067529	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1466191067529	addons.manager	DEBUG	Provider finished startup: XPIProvider
1466191067529	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1466191067529	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1466191067530	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1466191067530	addons.manager	DEBUG	Starting provider: GMPProvider
1466191067537	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1466191067537	addons.manager	DEBUG	Provider finished startup: GMPProvider
1466191067537	addons.manager	DEBUG	Starting provider: PluginProvider
1466191067538	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1466191067538	addons.manager	DEBUG	Provider finished startup: PluginProvider
1466191067538	addons.manager	DEBUG	Completed startup sequence
1466191067760	DeferredSave.extensions.json	DEBUG	Starting write
1466191067998	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1466191067999	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1466191067999	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1466191068001	DeferredSave.extensions.json	DEBUG	Write succeeded
JavaScript error: chrome://fxdriver/content/server.js, line 61: uncaught exception: [object Object]
JavaScript error: chrome://fxdriver/content/server.js, line 61: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
JavaScript error: chrome://adaware/content/js/https/ChannelReplacement.js, line 18: ReferenceError: Ci is not defined
1466191069240	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1466191069240	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1466191069240	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
JavaScript error: chrome://adaware/content/js/https/IOUtil.js, line 130: SyntaxError: missing ( after for
JavaScript error: chrome://adaware/content/js/https/HTTPSRules.js, line 64: ReferenceError: Cc is not defined
JavaScript error: chrome://adaware/content/js/https/Cookie.js, line 75: SyntaxError: missing ( after for
JavaScript error: chrome://adaware/content/js/https/HTTPS.js, line 159: SyntaxError: missing ( after for

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	... 7 more

**Comment by jimevans** [comment] 2016-06-17 13:19
Looks like a duplicate of #2110, so I'm closing for now. If you have reason to believe otherwise, we can discuss further.

**Closed by jimevans** 2016-06-17 13:19 UTC
