### ISSUE TITLE
Selenium Grid 3.0 is closing browser

### ISSUE THREAD

**Issue by filipcynarski** [SeleniumHQ/selenium#3149] opened 2016-11-21 15:12 UTC
## Meta -
OS:  
Linux
Selenium Version:  
3.0.1
Browser:  
Chrome

Browser Version:  
Google Chrome 54.0.2840.100 

## Steps to reproduce -
Run your tests on the Hub picking Chrome browser and doing some findElements using Xpath instead of CSS selector

The result would be:

```
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'MP19779.local', ip: '10.244.250.81', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_111'
Driver info: driver.version: RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e), userDataDir=/tmp/.org.chromium.Chromium.z0eB6N}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=true, version=54.0.2840.100, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=27dd808a-8a8d-4e5d-aa7e-88697d130b84, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 27dd808a-8a8d-4e5d-aa7e-88697d130b84

    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
    at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:393)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementsByCssSelector(RemoteWebDriver.java:469)
    at org.openqa.selenium.By$ByCssSelector.findElements(By.java:441)
    at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:356)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.openqa.selenium.remote.Augmenter$CompoundHandler.intercept(Augmenter.java:189)
    at org.openqa.selenium.remote.RemoteWebDriver$$EnhancerByCGLIB$$b074229.findElements(<generated>)
```

I think such issue shouldn't kill your browser. But the browser dies, when I've figured it out and fixed my By.xpath it stopped killing my browser at all :)

**Comment by lukeis** [comment] 2016-11-21 15:25
This is a duplicate of
https://github.com/SeleniumHQ/selenium/issues/3117

Which is fixed and will be in the next release

**Closed by lukeis** 2016-11-21 15:25 UTC
