### ISSUE TITLE
[🐛 Bug]: Problem with selenium manager 

### ISSUE THREAD

**Issue by SanjaSiskovicVasiljevic** [SeleniumHQ/selenium#11565] opened 2023-01-18 11:18 UTC
### What happened?

I create POM document with dependencies. 
I have this dependency  
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>SlangoUITesting</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>SlangoUITesting</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>19</maven.compiler.source>
    <maven.compiler.target>19</maven.compiler.target>
  </properties>

  <dependencies>
    
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-java</artifactId>
      <version>4.7.2</version>
    </dependency>

    
    
    <dependency>
      <groupId>org.testng</groupId>
      <artifactId>testng</artifactId>
      <version>7.7.1</version>
      <scope>test</scope>
    </dependency>

    
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>2.0.6</version>
      <scope>test</scope>
    </dependency>

    
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi</artifactId>
      <version>5.2.3</version>
    </dependency>

    
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi-ooxml</artifactId>
      <version>5.2.3</version>
    </dependency>

    
    <dependency>
      <groupId>com.github.javafaker</groupId>
      <artifactId>javafaker</artifactId>
      <version>1.0.2</version>
    </dependency>

    
    <dependency>
      <groupId>ru.sbtqa.tag.pagefactory</groupId>
      <artifactId>page-factory-core</artifactId>
      <version>17.0.3</version>
    </dependency>

  </dependencies>
</project>

I run simple code and I get error 
![error](https://user-images.githubusercontent.com/120654458/213156950-2a30b3ad-8f08-4722-9bfb-d0e7ece36d40.png)
I recorded all process
 https://recordit.co/NKC84sjYJM

### How can we reproduce the issue?

```shell
https://recordit.co/NKC84sjYJM
```

### Relevant log output

```shell
Exception in thread "main" java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableMap com.google.common.collect.ImmutableMap.of(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)'
	at org.openqa.selenium.chrome.AddHasCasting.getAdditionalCommands(AddHasCasting.java:38)
	at org.openqa.selenium.chrome.ChromeDriver$ChromeDriverCommandExecutor.getExtraCommands(ChromeDriver.java:99)
	at org.openqa.selenium.chrome.ChromeDriver$ChromeDriverCommandExecutor.<init>(ChromeDriver.java:94)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:50)
	at Test.demo.main(demo.java:10)

Process finished with exit code 1
```

### Operating System

Windows 11

### Selenium version

Java 19 , Selenium 4.7.2

### What are the browser(s) and version(s) where you see this issue?

chrome Version 109.0.5414.75

### What are the browser driver(s) and version(s) where you see this issue?

 ChromeDriver 110.0.5481.30

### Are you using Selenium Grid?

no

**Comment by diemol** [comment] 2023-01-18 11:57
This is a duplicate of #10934 and other similar issues. Please make sure your version of Guava is the same one as the one used by Selenium.

**Closed as completed by diemol** 2023-01-18 11:57 UTC
