### ISSUE TITLE
In Safari - Driver does not support setting HTML5 geolocation information. Use the HasLocationContext property to test for the driver capability

### ISSUE THREAD

**Issue by Elangopalakrishnan** [SeleniumHQ/selenium#5743] opened 2018-04-09 10:18 UTC
## Meta -
OS:  
Mac High Sierra
Selenium Version:  3.11.0
Browser:  
Safari 11.0.3

Here i'm automating the Mac safari browser from windows machine using remotewebdriver.
When i try to navigate some urls driver shows error message **"Driver does not support setting HTML5 geolocation information. Use the HasLocationContext property to test for the driver capability".**

I can understand i need to add some capability to overcome this but i don't know what is that capability.
**capabilities.SetCapability("locationContextEnabled", true);**   
 
I tired to use ,

DesiredCapabilities capabilities = new DesiredCapabilities();
                    capabilities = DesiredCapabilities.Safari();
                    capabilities.SetCapability("locationContextEnabled", true);                   
                    RemoteWebDriver rwd = new RemoteWebDriver(new Uri("http://" + MacIPAddress + ":" + MacPort + "/wd/hub"), capabilities, TimeSpan.FromSeconds(180));
                    mkConstants.webDriver = rwd;
                    rwd.Navigate().GoToUrl("https://****.*****.ca/Login/Login.aspx");                    

And i try to enable/disable the location options in Apple--> preferences->security&privacy-->privacy tab.

But it doesn't help me,

How can i fix this, please suggest me ????????

## Expected Behavior -
It should navigate expected page.
## Actual Behavior -
Showing error - "Driver does not support setting HTML5 geolocation information. Use the HasLocationContext property to test for the driver capability".
## Steps to reproduce -

DesiredCapabilities capabilities = new DesiredCapabilities();
                    capabilities = DesiredCapabilities.Safari();
                    capabilities.SetCapability("locationContextEnabled", true);                   
                    RemoteWebDriver rwd = new RemoteWebDriver(new Uri("http://" + MacIPAddress + ":" + MacPort + "/wd/hub"), capabilities, TimeSpan.FromSeconds(180));
                    webDriver = rwd;
                    rwd.Navigate().GoToUrl("https://****.*****.ca/Login/Login.aspx");                    

Thanks in advance!

**Comment by jimevans** [comment] 2018-04-09 12:59
@Elangopalakrishnan A couple of follow-up questions. First, are you using the Java standalone server to remotely execute against Safari on your Mac from your Windows machine? If so, what version?

Second, there is no capability you can set to force the driver to do something it can’t do. The capability you’re trying to set, `locationContextEnabled`, won’t be recognized as something you can configure. If the driver does not support it, and Apple’s SafariDriver does not, it should be returning capabilities that have that value set to `false`. In either case, having the capability omitted, or with the value of false, the .NET code should take this into account.

Finally, the only place that exception is defined in the source code that I can see is when attempting to call the property getter for the LocationContext property. Are you not sharing the full code that causes the error? Perhaps the full stack trace would be instructive.

**Comment by Elangopalakrishnan** [comment] 2018-04-10 09:27
@jimevans _First, are you using the Java standalone server to remotely execute against Safari on your Mac from your Windows machine? If so, what version?_  - Yes I'm using selenium standalone server in mac.

Selenium standalone version - 3.11.0

My code is 

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities = DesiredCapabilities.Safari();
capabilities.SetCapability("locationContextEnabled", true);
RemoteWebDriver rwd = new RemoteWebDriver(new Uri("http://" + MacIPAddress + ":" + MacPort + "/wd/hub"), capabilities, TimeSpan.FromSeconds(180));
webDriver = rwd;
rwd.Navigate().GoToUrl("https://****.*****.ca/Login/Login.aspx");

Thanks!
Elango

**Comment by jimevans** [comment] 2018-04-10 11:25
And once again, I ask you to please share the full stack trace. I am unable to reproduce the issue, and I’m having trouble seeing how one could even hit the line of code where the exception is thrown. I stand by my original statement, however, that the Safari driver does not support automating geolocation, and cannot be made to do so, no matter what capabilities you try to pass to it.

**Comment by diemol** [comment] 2019-03-24 21:55
Closing as we didn't get more information to reproduce the issue, also due to 
> that the Safari driver does not support automating geolocation, and cannot be made to do so, no matter what capabilities you try to pass to it.

**Closed by diemol** 2019-03-24 21:55 UTC
Labels: R-awaiting answer
