### ISSUE TITLE
ChromeDriver version 77 throws null reference exception on accessing Displayed and LocationOnScreenOnceScrolledIntoView properties

### ISSUE THREAD

**Issue by Szesan** [SeleniumHQ/selenium#7641] opened 2019-10-03 11:05 UTC
![CHromeDriverBug](https://user-images.githubusercontent.com/55020518/66121729-294e2b80-e5de-11e9-8d94-dbb7b28c214e.png)

See attached screenshot! The same code, same element with exactly the same locator works perfectly fine with earlier versions, but now it throws null reference exception. 

I've tried to use different locators, webdriver finds them, but throws these exceptions nevertheless all the time. 

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by barancev** [comment] 2019-10-05 20:13
Duplicate of #7631

**Closed by barancev** 2019-10-05 20:13 UTC
