### ISSUE TITLE
POST /frame 

### ISSUE THREAD

**Issue by miiimooo** [SeleniumHQ/selenium#9044] opened 2021-01-13 12:24 UTC
## 💥 Regression Report

I version 3.14 a test that is switching to an iFrame by making a POST to /frame works (e.g. `http://selenium:4444/wd/hub/session/ae8d437ab9389e07bad222c22cfbe66f/frame`

After upgrading to `Selenium server version: 3.141.59, revision: e82be7d358` the test results in a exception:
```
{
  "state": "invalid argument",
  "sessionId": null,
  "class": "org.openqa.selenium.remote.Response",
  "value": {
    "additionalInformation": "\nDriver info: driver.version: unknown",
    "localizedMessage": "invalid argument: 'id' can not be string\n  (Session info: chrome=87.0.4280.66)\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\nSystem info: host: '59fcecfc051f', ip: '172.19.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-60-generic', java.version: '1.8.0_275'\nDriver info: driver.version: unknown",
    "systemInformation": "System info: host: '59fcecfc051f', ip: '172.19.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-60-generic', java.version: '1.8.0_275'",
    "supportUrl": null,
    "cause": null,
    "stackTrace": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "suppressed": [
    ],
    "message": "invalid argument: 'id' can not be string\n  (Session info: chrome=87.0.4280.66)\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\nSystem info: host: '59fcecfc051f', ip: '172.19.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-60-generic', java.version: '1.8.0_275'\nDriver info: driver.version: unknown",
    "class": "org.openqa.selenium.InvalidArgumentException",
    "buildInformation": null
  },
  "status": 61
}
```

## Last working Selenium version

Worked up to version: Selenium build info: version: '3.14.0', revision: 'aacccce0'

Stopped working in version: Selenium server version: 3.141.59, revision: e82be7d358

## To Reproduce

```
curl -d '{ "id": "stringhere" }' http://selenium:4444/wd/hub/session/ae8d437ab9389e07bad222c22cfbe66f/frame
```

Detailed steps to reproduce the behavior:

Open a session to a page with an iframe, try switching iframe by name in that session

## Expected behavior

It should not give an error

## Environment

OS: Linux
Browser: chrome
Browser version: 87.0.4280.66
Browser Driver version: unknown (docker image krytpon)
Language Bindings version: curl

**Comment by diemol** [comment] 2021-01-13 13:07
Could you please provide a complete script to reproduce the issue? How is the session being created? It is probable that it is a W3C session, therefore this is relevant https://www.w3.org/TR/webdriver1/#switch-to-frame
```
If id is not null, a Number object, or an Object that represents a web element, return error with error code no such frame. 
```

Which explains what you are getting back from ChromeDriver.

**Comment by miiimooo** [comment] 2021-01-14 08:18
If I understand correctly, the problem lies with the behat selenium driver, as it passed the id as a string meaning the HTML id attribute. This worked in the older version. It looks like somewhere along the way this mus have been "rectified". I guess this will need fixing in the behat framework (the selenium driver) at some point. 
I followed the link to the documentation but I couldn't work out what is meant by:
* Number object: if this is literally a number (123..) what does it refer to?
* Object that represents a web element: how does that look in an actual request?

Is there an example somewhere of a script to reproduce selenium things to get me started?

**Comment by diemol** [comment] 2021-01-14 10:30
Probably you are right, maybe that driver is not using W3C? Or it needs to be upgraded? Never used behat.

I think the easiest way to answer your questions is to share the link to the docs with some examples:
https://www.selenium.dev/documentation/en/webdriver/browser_manipulation/#frames-and-iframes

**Comment by diemol** [comment] 2021-01-20 20:49
I'll be closing this as this seems to be an issue with the client bindings being used. If you need any help, please drop by our Slack/IRC channels where members of the community and the project can help, check the links here https://www.selenium.dev/support/

**Closed as completed by diemol** 2021-01-20 20:49 UTC
Labels: J-awaiting answer
