### ISSUE TITLE
selenium.common.exceptions.InvalidArgumentException

### ISSUE THREAD

**Issue by PikoKrs** [SeleniumHQ/selenium#7912] opened 2020-01-04 21:50 UTC
>   File "C:\Users\GGgg\PycharmProjects\ParsMberry\z2gis.py", line 49, in t2gisparse
>     result = res.get_attribute('innerHTML')
>   File "C:\Users\GG\PycharmProjects\ParsMberry\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 139, in get_attribute
>     attributeValue = self.parent.execute_script(
>   File "C:\Users\GGgg\PycharmProjects\ParsMberry\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 634, in execute_script
>     return self.execute(command, {
>   File "C:\Users\GGgg\PycharmProjects\ParsMberry\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "C:\Users\GGgg\PycharmProjects\ParsMberry\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.InvalidArgumentException: Message: unexpected end of hex escape at line 1 column 155266

This error seems to be due to emoji on page.
https://2gis.ua/odessa/branches/1970861708085905/firm/70000001030556211/30.790109%2C46.578724/tab/reviews?m=30.850818%2C46.433337%2F10.61

I tried gecko, chrome, errors are same.

**Comment by diemol** [comment] 2020-01-08 16:18
I will close this since the issue template was completely ignored and it is impossible to understand what the issue is.
@PikoKrs feel free to open a new issue and fill out the complete issue template.

**Closed by diemol** 2020-01-08 16:18 UTC
Labels: needs-triaging
