### ISSUE TITLE
Selenium tests are very-very slow in some networks

### ISSUE THREAD

**Issue by asolntsev** [SeleniumHQ/selenium#489] opened 2015-04-24 14:49 UTC
I am working in hotel on Bali, via public WiFi.
My Selenium tests are incredibly slow (see attached image).
![image](https://cloud.githubusercontent.com/assets/279773/7321190/683b59f4-ead3-11e4-890c-0baec37e5dd5.png)

The problem is in method `org.openqa.selenium.WebDriverException#getSystemInformation`:

``` java
    try{
      host = InetAddress.getLocalHost().getHostName();
    } catch (UnknownHostException throw_away) {}
```

Method `getHostName()` uses system call to get name of current computer, which can be **very-very long**. 
I believe host name is not really needed and can be skipped. Just log IP.

**Comment by asolntsev** [comment] 2015-04-24 15:37
Created pull request for fixing this problem: https://github.com/SeleniumHQ/selenium/pull/490

**Comment by asolntsev** [comment] 2015-05-31 15:00
Created another pull request for this issue: https://github.com/SeleniumHQ/selenium/pull/591
This pull request runs resolving IP/host in a separate background thread.

**Comment by barancev** [comment] 2017-08-02 12:22
Duplicate of #3048

**Closed by barancev** 2017-08-02 12:22 UTC
Labels: C-java
