### ISSUE TITLE
[🐛 Bug]: Selenium hanging to .get in docker?

### ISSUE THREAD

**Issue by LucasTor** [SeleniumHQ/selenium#14868] opened 2024-12-06 13:16 UTC
### What happened?

When running in docker, selenium hangs to fetch the zoom signing URL, but the same does not happen when running outside the container, on my machine.
The code is exactly the same both inside and outside Docker
The code gets stuck on this line:
```
self.driver.get("https://www.zoom.us/signin")
```
And, after a while, it times out in the 3 or 5 minutes default
Any other URL loads fine inside Docker
I have tried using http toolkit to check on the requests, and everything loads normally, but the call to .get hangs

### How can we reproduce the issue?

```shell
Call

self.driver.get("https://www.zoom.us/signin")
```
Both inside and outside docker
```


### Relevant log output

```shell
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 14.588
```

### Operating System

Mac OS and Ubuntu on Docker

### Selenium version

Unsure of the version, but it's for Python

### What are the browser(s) and version(s) where you see this issue?

Chrome 131

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 131

### Are you using Selenium Grid?

No

**Comment by pujagani** [comment] 2024-12-16 10:18
Thank you for sharing the details. This does not seem to be a Selenium issue, since it works outside the container. Hence, I am closing it.

But what I can do is share my experience to help you out.

Can you help check if you can get the URL using curl inside the docker container? If not, then there is a good chance the issue is in the DNS server for the Docker. 

I have faced this in the older version of Docker, and running my container with a DNS server helped fix it. 
Example command:

`docker run --rm -it  --memory=6g --shm-size=2g --dns=8.8.8.8 container-name`

**Closed as completed by pujagani** 2024-12-16 10:18 UTC
Labels: I-defect, A-needs-triaging
