### ISSUE TITLE
table view is not available with this format (selenium ide 2.9.1)

### ISSUE THREAD

**Issue by samfisher24** [SeleniumHQ/selenium#4339] opened 2017-07-19 18:20 UTC
## Meta 
OS:  win 10 pro
Selenium Version:   2.9.1
Browser: Firefox
Browser Version:   55.0 (64-bit)
Expected Behavior - Selenium IDE should work.
Actual Behavior - Selenium IDE not working. The record button doesn't respond once launched. When clicked on clear tab i get a pop up [javascript Application]: There was an unexpected error. Msg: TypeError: window.editor.infoPanel is undefined
Url: chrome://selenium-ide/content/selenium-ide.xul, line: 1, column: 1
oncommand@chrome://selenium-ide/content/selenium-ide.xul:1:1

The above pop up message is shown when clicked on any tab at bottom.
It also shows table view not available with this format when launched. 
The record button is on by default and nothing happens when clicked on it.
![selenium ide](https://user-images.githubusercontent.com/30298668/28382712-b71a7c66-6cdc-11e7-8f41-bcd68dfa8db2.png)
![seleniumide](https://user-images.githubusercontent.com/30298668/28382721-bc7a0afa-6cdc-11e7-9ab2-7c866a6f6670.jpg)

**Comment by DracoThuban** [comment] 2017-07-19 23:26
Same in Debian.

**Comment by samfisher24** [comment] 2017-07-20 12:32
@DracoThuban There is no alternative to solve this problem? are most of them facing this issue?

**Comment by barancev** [comment] 2017-08-04 06:26
Duplicate of #4406

**Closed by barancev** 2017-08-04 06:26 UTC
Labels: C-ide

**Comment by seniortester** [comment] 2017-08-10 00:27
I had not option, downgrade the FireFox version and then it worked.

**Comment by RImpact** [comment] 2017-08-10 16:35
I am having this issue on FF 55.00 in MAC OS.

**Comment by stefangrotz** [comment] 2017-08-22 14:00
There is a project that rewrites the plugin:
https://github.com/ddavison/selenium-ide

**Comment by Daisyhuhu** [comment] 2017-08-25 08:09
Anyone know how to fix this issue?

**Comment by nganugapanta** [comment] 2017-09-14 14:09
what is the solution for this issue?

**Comment by nganugapanta** [comment] 2017-09-14 14:10
![28382721-bc7a0afa-6cdc-11e7-9ab2-7c866a6f6670](https://user-images.githubusercontent.com/31960288/30434296-e5f33850-9934-11e7-8a3b-9a05c461bfc8.jpg)

**Comment by idefix1** [comment] 2017-09-23 21:10
>what is the solution for this issue?

The solution is to downgrade to Firefox 54 or try the [new selenium ide] for Chrome (https://chrome.google.com/webstore/detail/kantu-browser-automation/gcbalfbdmfieckjlnblleoemohcganoc)

Instead of downgrading to Firefox 54, better use Firefox PORTABLE 54.0.1 and install the portable version of Firefox in a separate directory from your main Firefox. This way you can keep auto-updates on for your regular Firefox. This makes sure you are safe when browsing the web.

The technical details are available in this ticket #4406

**Comment by corinthian13** [comment] 2017-10-30 13:56
Christ, why develop a special add-on for Firefox without being sure of the co-operability with current and projected versions ?

**Comment by Jarob22** [comment] 2017-10-30 14:08
@corinthian13 Being rude to developers who give up their SPARE time without being paid to develop an open source solution is neither productive or helpful. Maybe tone it down a bit? IDE hasn't been in active development or maintenance for a rather long time now, and a replacement is currently underway. There is no workaround to make this work on 55, please see the duplicate ticket.

**Comment by corinthian13** [comment] 2017-10-30 17:15
Selenium is a voluntary project ?
Okay. But it's still naive to think that Mozilla (another mostly unpaid project, I believe) is going to always accommodate the needs of the next version of Se. That's not being rude, Jarob - it's just being honest. Neither is it being disrespectful to the work put in after hours by mortgage men and college boys - it's to avoid their efforts going to waste. 
Put it this way: Se-Moz works well, good chance of a donation. Se-Moz fails and Se-Chrome works, donation goes to Kantu or whoever.

**Comment by Jarob22** [comment] 2017-10-30 17:43
Mozilla has nothing to do with IDE. I don't see what you're getting at here - IDE had stopped being worked on by SE devs long before FF55 came around and completely killed it.

**Comment by barancev** [comment] 2017-10-31 06:17
@corinthian13 Keep calm. We're working on a new Selenium IDE implementation, that will be compatible with modern Firefox versions. Until it's ready, there is known workaround -- use Firefox ESR 52, that is officially supported by Mozilla.

Yes, Selenium is a voluntary project. Being rude (or even honest) on us will not add us more enthusiasm or spare time. If you think we're not smart enough or fast enough, you come on board and help us working on the new Selenium IDE version, for everyone's benefit. Or you can choose another tool, there are many of them, we'll be happy if you donate to Kantu or whoever who deserves respect for their excellent work.
