### ISSUE TITLE
Capabilities not being passed to IEDriverServer in latest version

### ISSUE THREAD

**Issue by vibaldem** [SeleniumHQ/selenium#6611] opened 2018-11-02 19:10 UTC
OS:  Windows 10
Selenium Version:  3.14.1
Browser:  Internet Explorer

Browser Version:  
11.55.17763.0

Expected Behavior -
When sending capability flags, they should be set on the driver
Actual Behavior -
Capabilities are never set

Steps to reproduce -

```
from selenium import webdriver
capabilities = webdriver.DesiredCapabilities.INTERNETEXPLORER.copy()
capabilities['ie.ensureCleanSession'] = True
driver = webdriver.Ie(executable_path='e:\\IEDriverServer.exe', capabilities=capabilities)
print driver.capabilities
```

> {u'browserVersion': u'11', u'acceptInsecureCerts': False, u'se:ieOptions': {u'ie.browserCommandLineSwitches': u'', u'browserAttachTimeout': 0, u'nativeEvents': True, **u'ie.ensureCleanSession': False**, u'ignoreZoomSetting': False, u'ie.fileUploadDialogTimeout': 3000, u'ignoreProtectedModeSettings': False, u'requireWindowFocus': False, u'elementScrollBehavior': 0, u'initialBrowserUrl': u'http://localhost:61644/', u'enablePersistentHover': True, u'ie.forceCreateProcessApi': False}, u'timeouts': {u'pageLoad': 300000, u'implicit': 0, u'script': 30000}, u'browserName': u'internet explorer', u'setWindowRect': True, u'proxy': {}, u'pageLoadStrategy': u'normal', u'platformName': u'windows'}

**Comment by jimevans** [comment] 2018-11-02 20:21
@vibaldem Assuming this is Python, I have two questions. First, why aren’t you using the `ie.Options` class? Second, what happens if you do so?

**Comment by vibaldem** [comment] 2018-11-02 20:45
@jimevans Yeah, sorry, my example was for python, but the breaking change is in IEDriver.
I've also tried with the ie.Options class and it is the same result, which makes sense since they all get merged together anyway:

> https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/ie/webdriver.py

```
        if capabilities is None and desired_capabilities:
            capabilities = desired_capabilities

        if options is None:
            if capabilities is None:
                capabilities = self.create_options().to_capabilities()
        else:
            if capabilities is None:
                capabilities = options.to_capabilities()
            else:
                # desired_capabilities stays as passed in
                capabilities.update(options.to_capabilities())
```


It looks like the breaking change is here in cpp/iedriver/CommandHandlers/NewSessionCommandHandler.cpp:

https://github.com/SeleniumHQ/selenium/commit/e60b607a97b9b7588d59e0c26ef9a6d1d1350911#diff-195e5a756c74f4318c75d9e87ed79046


If capabilities is passed in and is processed successfully, then the legacy capabilities are ignored, which is what contains the options I'm trying to use.

**Comment by jimevans** [comment] 2018-11-02 21:31
This “issue” won’t be fixed in the IE driver. The requirement to use spec-compliant capabilities for new session has been implemented since 3.5 of the IE driver. If the Python bindings aren’t sending a proper W3C compliant payload, that’s something that should be fixed in the bindings.

**Comment by vibaldem** [comment] 2018-11-02 21:49
Yeah, I see that now.  I need to read up the w3c webdriver spec, not what makes these legacy IE options non-compliant.

**Comment by lmtierney** [comment] 2018-11-03 02:01
I cannot reproduce this issue with the latest and using the `IeOptions` class

```
>>> from selenium.webdriver import Ie, IeOptions
>>> opts = IeOptions()
>>> opts.ensure_clean_session = True
>>> ie = Ie(options=opts)
>>> ie.capabilities
{'acceptInsecureCerts': False, 'browserName': 'internet explorer', 'browserVersion': '11', 'pageLoadStrategy': 'normal', 'platformName': 'windows', 'p
roxy': {}, 'se:ieOptions': {'browserAttachTimeout': 0, 'elementScrollBehavior': 0, 'enablePersistentHover': True, 'ie.browserCommandLineSwitches': '',
 'ie.ensureCleanSession': True, 'ie.fileUploadDialogTimeout': 3000, 'ie.forceCreateProcessApi': False, 'ignoreProtectedModeSettings': False, 'ignoreZo
omSetting': False, 'initialBrowserUrl': 'http://localhost:58563/', 'nativeEvents': True, 'requireWindowFocus': False}, 'setWindowRect': True, 'timeout
s': {'implicit': 0, 'pageLoad': 300000, 'script': 30000}}
```

**Closed by lmtierney** 2018-11-03 02:01 UTC
