### ISSUE TITLE
[🐛 Bug]:  Unable to create session: Could not start a new session when running parallel tests with Selenium 4.15.0.

### ISSUE THREAD

**Issue by anassibnoualii** [SeleniumHQ/selenium#13182] opened 2023-11-21 21:31 UTC
### What happened?

 I am encountering this issue when attempting to run parallel tests using Selenium 4.15.0 and also the nightly(4.16.0-SNAPSHOT (20231121)) as mentionned by @titusfortner  in  [13091](https://github.com/SeleniumHQ/selenium/issues/13091#issuecomment-1821420308), with  Selenium Grid version 4.15.0-20231110. 
The error message I am receiving is as follows:
`Unable to create session: Could not start a new session. Unable to obtain: Capabilities {browserName: chrome, browserVersion: 119.0, goog:chromeOptions: {args: [], extensions: [], prefs: {download.default_directory: /tmp/uuid224207070901692623..., download.prompt_for_download: false, savefile.default_directory: /tmp/uuid224207070901692623...}}, pageLoadStrategy: normal, platformName: linux, se:downloadsEnabled: true, se:noVncPort: 7900, se:vncEnabled: true}, error Failed to run command: [--browser, chrome, --output, json, --browser-version, 119.0]
`

This issue is related to the following issues:

1. [13091](https://github.com/SeleniumHQ/selenium/issues/13091)
2. [1992](https://github.com/SeleniumHQ/docker-selenium/issues/1992)

### How can we reproduce the issue?

```shell
Setup the selenium dynamic grid stack https://github.com/SeleniumHQ/docker-selenium#dynamic-grid
Then run some parallel tests using multiple browser instances.
```

### Relevant log output

```shell
2023-11-21 14:43:14,872 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
2023-11-21 14:43:14,919 INFO RPC interface 'supervisor' initialized
2023-11-21 14:43:14,920 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-11-21 14:43:14,923 INFO supervisord started with pid 8
2023-11-21 14:43:15,939 INFO spawned: 'xvfb' with pid 9
2023-11-21 14:43:15,943 INFO spawned: 'vnc' with pid 10
2023-11-21 14:43:15,948 INFO spawned: 'novnc' with pid 11
2023-11-21 14:43:15,954 INFO spawned: 'selenium-standalone' with pid 12
Appending Selenium options: --enable-managed-downloads true
2023-11-21 14:43:16,027 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2023-11-21 14:43:16,027 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2023-11-21 14:43:16,028 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2023-11-21 14:43:16,028 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Setting up SE_NODE_GRID_URL...
Selenium Grid Standalone configuration: 
[network]
relax-checks = true

[node]
session-timeout = "300"
override-max-sessions = false
detect-drivers = false
drain-after-session-count = 0
max-sessions = 1

[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "119.0", "platformName": "Linux"},'
max-sessions = 1

Starting Selenium Grid Standalone...
Tracing is disabled
Nov 21, 2023 2:43:24 PM org.openqa.selenium.grid.Bootstrap createExtendedClassLoader
WARNING: Extension file or directory does not exist: /opt/selenium/selenium-http-jdk-client.jar
14:43:25.843 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
14:43:25.870 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
14:43:28.354 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
14:43:28.534 INFO [NodeOptions.report] - Adding chrome for {"browserName": "chrome","browserVersion": "119.0","platformName": "linux","se:downloadsEnabled": true,"se:noVncPort": 7900,"se:vncEnabled": true} 1 times
14:43:28.591 INFO [Node.<init>] - Binding additional locator mechanisms: relative
14:43:28.693 INFO [GridModel.setAvailability] - Switching Node cd71473a-7c58-4d8a-a967-ff6572686f53 (uri: http://172.21.0.12:4444) from DOWN to UP
14:43:28.695 INFO [LocalDistributor.add] - Added node cd71473a-7c58-4d8a-a967-ff6572686f53 at http://172.21.0.12:4444. Health check every 120s
14:43:29.119 INFO [Standalone.execute] - Started Selenium Standalone 4.16.0-SNAPSHOT (revision b9ef666): http://172.21.0.12:4444
14:43:30.103 INFO [LocalDistributor.newSession] - Session request received by the Distributor: 
 [Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: [], prefs: {download.default_directory: /tmp/uuid500577748948212582..., download.prompt_for_download: false, savefile.default_directory: /tmp/uuid500577748948212582...}}, pageLoadStrategy: normal, se:downloadsEnabled: true}]
14:43:30.851 WARN [DriverServiceSessionFactory.apply] - Error while creating session with the driver service. Unable to obtain: Capabilities {browserName: chrome, browserVersion: 119.0, goog:chromeOptions: {args: [], extensions: [], prefs: {download.default_directory: /tmp/uuid140567444314121089..., download.prompt_for_download: false, savefile.default_directory: /tmp/uuid140567444314121089...}}, pageLoadStrategy: normal, platformName: linux, se:downloadsEnabled: true, se:noVncPort: 7900, se:vncEnabled: true}, error Failed to run command: [--browser, chrome, --output, json, --browser-version, 119.0]
Build info: version: '4.16.0-SNAPSHOT', revision: 'b9ef666'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-213-generic', java.version: '11.0.20.1'
Driver info: driver.version: unknown
14:43:30.858 WARN [SeleniumSpanExporter$1.lambda$export$1] - Error while creating session with the driver service. Unable to obtain: Capabilities {browserName: chrome, browserVersion: 119.0, goog:chromeOptions: {args: [], extensions: [], prefs: {download.default_directory: /tmp/uuid140567444314121089..., download.prompt_for_download: false, savefile.default_directory: /tmp/uuid140567444314121089...}}, pageLoadStrategy: normal, platformName: linux, se:downloadsEnabled: true, se:noVncPort: 7900, se:vncEnabled: true}, error Failed to run command: [--browser, chrome, --output, json, --browser-version, 119.0]
Build info: version: '4.16.0-SNAPSHOT', revision: 'b9ef666'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-213-generic', java.version: '11.0.20.1'
Driver info: driver.version: unknown
14:43:30.859 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browserName: chrome, browserVersion: 119.0, goog:chromeOptions: {args: [], extensions: [], prefs: {download.default_directory: /tmp/uuid140567444314121089..., download.prompt_for_download: false, savefile.default_directory: /tmp/uuid140567444314121089...}}, pageLoadStrategy: normal, platformName: linux, se:downloadsEnabled: true, se:noVncPort: 7900, se:vncEnabled: true}, error Failed to run command: [--browser, chrome, --output, json, --browser-version, 119.0]
Build info: version: '4.16.0-SNAPSHOT', revision: 'b9ef666'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-213-generic', java.version: '11.0.20.1'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:25)
        at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:13)
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:135)
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:72)
        at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)
        at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:464)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:645)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:564)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:824)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:784)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.WebDriverException: Failed to run command: [--browser, chrome, --output, json, --browser-version, 119.0]
Build info: version: '4.16.0-SNAPSHOT', revision: 'b9ef666'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-213-generic', java.version: '11.0.20.1'
Driver info: driver.version: unknown
        at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:133)
        at org.openqa.selenium.manager.SeleniumManager.getDriverPath(SeleniumManager.java:287)
        at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:22)
        ... 12 more
Caused by: java.io.UncheckedIOException: java.io.IOException: Cannot run program "/tmp/selenium-manager3101400289769191755/manager/0.4.16/selenium-manager": error=26, Text file busy
        at org.openqa.selenium.os.ExternalProcess$Builder.start(ExternalProcess.java:193)
        at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:125)
        ... 14 more
Caused by: java.io.IOException: Cannot run program "/tmp/selenium-manager3101400289769191755/manager/0.4.16/selenium-manager": error=26, Text file busy
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at org.openqa.selenium.os.ExternalProcess$Builder.start(ExternalProcess.java:191)
        ... 15 more
Caused by: java.io.IOException: error=26, Text file busy
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 17 more

14:43:30.866 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "913b5066b0f1531e9a5560136368cc8a","eventTime": 1700595810852871377,"eventName": "exception","attributes": {"exception.message": "Error while creating session with the driver service. Unable to obtain: Capabilities {browserName: chrome, browserVersion: 119.0, goog:chromeOptions: {args: [], extensions: [], prefs: {download.default_directory: \u002ftmp\u002fuuid140567444314121089..., download.prompt_for_download: false, savefile.default_directory: \u002ftmp\u002fuuid140567444314121089...}}, pageLoadStrategy: normal, platformName: linux, se:downloadsEnabled: true, se:noVncPort: 7900, se:vncEnabled: true}, error Failed to run command: [--browser, chrome, --output, json, --browser-version, 119.0]\nBuild info: version: '4.16.0-SNAPSHOT', revision: 'b9ef666'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-213-generic', java.version: '11.0.20.1'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browserName: chrome, browserVersion: 119.0, goog:chromeOptions: {args: [], extensions: [], prefs: {download.default_directory: \u002ftmp\u002fuuid140567444314121089..., download.prompt_for_download: false, savefile.default_directory: \u002ftmp\u002fuuid140567444314121089...}}, pageLoadStrategy: normal, platformName: linux, se:downloadsEnabled: true, se:noVncPort: 7900, se:vncEnabled: true}, error Failed to run command: [--browser, chrome, --output, json, --browser-version, 119.0]\nBuild info: version: '4.16.0-SNAPSHOT', revision: 'b9ef666'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-213-generic', java.version: '11.0.20.1'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:25)\n\tat org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:13)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:135)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:72)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:464)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:645)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:564)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:824)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:784)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\nCaused by: org.openqa.selenium.WebDriverException: Failed to run command: [--browser, chrome, --output, json, --browser-version, 119.0]\nBuild info: version: '4.16.0-SNAPSHOT', revision: 'b9ef666'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-213-generic', java.version: '11.0.20.1'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:133)\n\tat org.openqa.selenium.manager.SeleniumManager.getDriverPath(SeleniumManager.java:287)\n\tat org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:22)\n\t... 12 more\nCaused by: java.io.UncheckedIOException: java.io.IOException: Cannot run program \"\u002ftmp\u002fselenium-manager3101400289769191755\u002fmanager\u002f0.4.16\u002fselenium-manager\": error=26, Text file busy\n\tat org.openqa.selenium.os.ExternalProcess$Builder.start(ExternalProcess.java:193)\n\tat org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:125)\n\t... 14 more\nCaused by: java.io.IOException: Cannot run program \"\u002ftmp\u002fselenium-manager3101400289769191755\u002fmanager\u002f0.4.16\u002fselenium-manager\": error=26, Text file busy\n\tat java.base\u002fjava.lang.ProcessBuilder.start(ProcessBuilder.java:1128)\n\tat java.base\u002fjava.lang.ProcessBuilder.start(ProcessBuilder.java:1071)\n\tat org.openqa.selenium.os.ExternalProcess$Builder.start(ExternalProcess.java:191)\n\t... 15 more\nCaused by: java.io.IOException: error=26, Text file busy\n\tat java.base\u002fjava.lang.ProcessImpl.forkAndExec(Native Method)\n\tat java.base\u002fjava.lang.ProcessImpl.\u003cinit>(ProcessImpl.java:340)\n\tat java.base\u002fjava.lang.ProcessImpl.start(ProcessImpl.java:271)\n\tat java.base\u002fjava.lang.ProcessBuilder.start(ProcessBuilder.java:1107)\n\t... 17 more\n","exception.type": "org.openqa.selenium.remote.NoSuchDriverException","logger": "org.openqa.selenium.grid.node.config.DriverServiceSessionFactory","session.capabilities": "{\"browserName\": \"chrome\",\"browserVersion\": \"119.0\",\"goog:chromeOptions\": {\"extensions\": [],\"args\": [],\"prefs\": {\"savefile.default_directory\": \"\\u002ftmp\\u002fuuid14056744431412108913702e6e71-b105-43d6-85d8-ac030427ff01\\u002fdownload15348142208675382974\",\"download.prompt_for_download\": false,\"download.default_directory\": \"\\u002ftmp\\u002fuuid14056744431412108913702e6e71-b105-43d6-85d8-ac030427ff01\\u002fdownload15348142208675382974\"},},\"pageLoadStrategy\": \"normal\",\"platformName\": \"linux\",\"se:downloadsEnabled\": \"true\",\"se:noVncPort\": 7900,\"se:vncEnabled\": true}\n"},}

14:43:30.869 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "913b5066b0f1531e9a5560136368cc8a","eventTime": 1700595810867637714,"eventName": "Unable to create session with the driver","attributes": {"current.session.count": 0,"logger": "org.openqa.selenium.grid.node.local.LocalNode","session.request.capabilities": "Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: [], prefs: {download.default_directory: \u002ftmp\u002fuuid500577748948212582..., download.prompt_for_download: false, savefile.default_directory: \u002ftmp\u002fuuid500577748948212582...}}, pageLoadStrategy: normal, se:downloadsEnabled: true}","session.request.downstreamdialect": "[W3C]"},}

14:43:30.873 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "913b5066b0f1531e9a5560136368cc8a","eventTime": 1700595810101289338,"eventName": "Session request received by the Distributor","attributes": {"logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: [], prefs: {download.default_directory: \u002ftmp\u002fuuid500577748948212582..., download.prompt_for_download: false, savefile.default_directory: \u002ftmp\u002fuuid500577748948212582...}}, pageLoadStrategy: normal, se:downloadsEnabled: true}]"},}

14:43:30.873 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to create session: Could not start a new session. Unable to obtain: Capabilities {browserName: chrome, browserVersion: 119.0, goog:chromeOptions: {args: [], extensions: [], prefs: {download.default_directory: /tmp/uuid140567444314121089..., download.prompt_for_download: false, savefile.default_directory: /tmp/uuid140567444314121089...}}, pageLoadStrategy: normal, platformName: linux, se:downloadsEnabled: true, se:noVncPort: 7900, se:vncEnabled: true}, error Failed to run command: [--browser, chrome, --output, json, --browser-version, 119.0]
Build info: version: '4.16.0-SNAPSHOT', revision: 'b9ef666'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-213-generic', java.version: '11.0.20.1'
Driver info: driver.version: unknown 
Host info: host: 'e43aea3fd4f1', ip: '172.21.0.12'
Build info: version: '4.16.0-SNAPSHOT', revision: 'b9ef666'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-213-generic', java.version: '11.0.20.1'
Driver info: driver.version: unknown
14:43:30.874 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to obtain: Capabilities {browserName: chrome, browserVersion: 119.0, goog:chromeOptions: {args: [], extensions: [], prefs: {download.default_directory: /tmp/uuid140567444314121089..., download.prompt_for_download: false, savefile.default_directory: /tmp/uuid140567444314121089...}}, pageLoadStrategy: normal, platformName: linux, se:downloadsEnabled: true, se:noVncPort: 7900, se:vncEnabled: true}, error Failed to run command: [--browser, chrome, --output, json, --browser-version, 119.0]
Build info: version: '4.16.0-SNAPSHOT', revision: 'b9ef666'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-213-generic', java.version: '11.0.20.1'
Driver info: driver.version: unknown 
Host info: host: 'e43aea3fd4f1', ip: '172.21.0.12'
Build info: version: '4.16.0-SNAPSHOT', revision: 'b9ef666'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-213-generic', java.version: '11.0.20.1'
Driver info: driver.version: unknown
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:238)
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:72)
        at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)
        at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:464)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:645)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:564)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:824)
        at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:784)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

14:43:30.875 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "913b5066b0f1531e9a5560136368cc8a","eventTime": 1700595810872297511,"eventName": "exception","attributes": {"exception.message": "Unable to create session: Could not start a new session. Unable to obtain: Capabilities {browserName: chrome, browserVersion: 119.0, goog:chromeOptions: {args: [], extensions: [], prefs: {download.default_directory: \u002ftmp\u002fuuid140567444314121089..., download.prompt_for_download: false, savefile.default_directory: \u002ftmp\u002fuuid140567444314121089...}}, pageLoadStrategy: normal, platformName: linux, se:downloadsEnabled: true, se:noVncPort: 7900, se:vncEnabled: true}, error Failed to run command: [--browser, chrome, --output, json, --browser-version, 119.0]\nBuild info: version: '4.16.0-SNAPSHOT', revision: 'b9ef666'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-213-generic', java.version: '11.0.20.1'\nDriver info: driver.version: unknown \nHost info: host: 'e43aea3fd4f1', ip: '172.21.0.12'\nBuild info: version: '4.16.0-SNAPSHOT', revision: 'b9ef666'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-213-generic', java.version: '11.0.20.1'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to obtain: Capabilities {browserName: chrome, browserVersion: 119.0, goog:chromeOptions: {args: [], extensions: [], prefs: {download.default_directory: \u002ftmp\u002fuuid140567444314121089..., download.prompt_for_download: false, savefile.default_directory: \u002ftmp\u002fuuid140567444314121089...}}, pageLoadStrategy: normal, platformName: linux, se:downloadsEnabled: true, se:noVncPort: 7900, se:vncEnabled: true}, error Failed to run command: [--browser, chrome, --output, json, --browser-version, 119.0]\nBuild info: version: '4.16.0-SNAPSHOT', revision: 'b9ef666'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-213-generic', java.version: '11.0.20.1'\nDriver info: driver.version: unknown \nHost info: host: 'e43aea3fd4f1', ip: '172.21.0.12'\nBuild info: version: '4.16.0-SNAPSHOT', revision: 'b9ef666'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-213-generic', java.version: '11.0.20.1'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:238)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:72)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:464)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:645)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:564)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:824)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:784)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: [], prefs: {download.default_directory: \u002ftmp\u002fuuid500577748948212582..., download.prompt_for_download: false, savefile.default_directory: \u002ftmp\u002fuuid500577748948212582...}}, pageLoadStrategy: normal, se:downloadsEnabled: true}]"},}

14:43:30.900 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "913b5066b0f1531e9a5560136368cc8a","eventTime": 1700595810893295283,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "172.21.0.12:4444","http.method": "POST","http.request_content_length": "758","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f4.16.0-SNAPSHOT (java unix)"},}

Trapped SIGTERM/SIGINT/x so shutting down supervisord...
2023-11-21 14:43:31,177 WARN received SIGTERM indicating exit request
2023-11-21 14:43:31,178 INFO waiting for xvfb, vnc, novnc, selenium-standalone to die
2023-11-21 14:43:31,563 INFO stopped: selenium-standalone (terminated by SIGTERM)
2023-11-21 14:43:31,928 INFO stopped: novnc (terminated by SIGTERM)
2023-11-21 14:43:32,179 INFO stopped: vnc (terminated by SIGTERM)
2023-11-21 14:43:32,184 INFO stopped: xvfb (terminated by SIGTERM)
Shutdown complete
```

### Operating System

Run on docker / Linux

### Selenium version

4.15.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 119, Firefox 119, Edge 119

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver: 119.0.6045.105, EdgeDriver: 119.0.2151.58, GeckoDriver: 0.33.0

### Are you using Selenium Grid?

4.15.0-20231110

**Comment by diemol** [comment] 2023-11-21 21:39
Duplicate of #13091

**Closed as not planned by diemol** 2023-11-21 21:39 UTC
Labels: I-defect

**Comment by anassibnoualii** [comment] 2023-11-22 11:21
Sorry @diemol, Ididn't want to confuse you with this issue. 
But i opened this issue based on @titusfortner  (https://github.com/SeleniumHQ/selenium/issues/13091#issuecomment-1821420308) suggestion to track the second part of the previous issue.
I used the nighly jar(20231121) and the problem is still present as mentionned in the log output above.
I'm tracking the following error:

`
  error Failed to run command: [--browser, chrome, --output, json, --browser-version, 119.0] 
 caused by error=26, Text file busy
`

and not :
`
error Failed to parse json output, executed: [--browser, chrome, --output, json, --browser-version, 119.0]
`

Thanks

**Comment by diemol** [comment] 2023-11-22 16:17
How are you using the nightly jar? With Docker?

**Comment by anassibnoualii** [comment] 2023-11-22 16:32
By building a new image from the offical selenium images. Then replacing the selenium-server.jar in the target image.
Here is an example of hub image. 
```
FROM selenium/hub:4.15.0-20231110
RUN rm /opt/selenium/selenium-server.jar
ADD ["../selenium-server-4.16.0-SNAPSHOT.jar","/opt/selenium/selenium-server.jar"]
```
We do the same for node-docker, standalone-firefox, standalone-chrome and standalone-edge

Note: We did this just to help investigating the issue and not to use it in production.

**Comment by diemol** [comment] 2023-11-22 16:33
OK, I did a release a few moments ago https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.15.0-20231122

The issue should not be present anymore.

**Comment by anassibnoualii** [comment] 2023-11-22 20:55
It works now with the new release [4.15.0-20231122](https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.15.0-20231122)
The issue is no more present.

Thanks
