### ISSUE TITLE
Selenium always throws org.openqa.selenium.NoSuchWindowException when using InternetExplorerDriver

### ISSUE THREAD

**Issue by gunnee** [SeleniumHQ/selenium#3086] opened 2016-11-10 12:25 UTC
## Meta -
**OS:**  
Windows 7 Enterprise
**Selenium Version:**  
3.0.1
**Browser:**  
Internet Explorer 11 
**Browser Version:**  
11.0.9600.18499 (32-bit)
**InternetExplorerDriver Version:**  
3.0 or 2.53.1 (same result)

## Expected Behavior
Getting the window handle (this is just one example; finding web elements results in the same error). 

## Actual Behavior
Browser window is getting opened and the page is being loaded. Afterwards the exception 'org.openqa.selenium.NoSuchWindowException' is being thrown when trying to get the window handle:
```
org.openqa.selenium.NoSuchWindowException: Window is closed (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 47 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: '...', ip: '...', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:30476/, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss}]
Session ID: 02ce74d8-4a27-409c-8839-3ec2b0846649
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
	at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandle(RemoteWebDriver.java:518)
	at com.test.test.automation.TestTest.test1(TestTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

## Steps to reproduce -
Run the following unit test:
```java
public class TestTest {

    @Test
    public void test1() {
        System.setProperty("webdriver.ie.driver", "drivers/internetexplorerdriver-windows-32bit.exe");
        WebDriver driver = new InternetExplorerDriver();
        driver.get("https://www.google.de/");
        try {
            TimeUnit.SECONDS.sleep(5);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        String windowHandle = driver.getWindowHandle();
        Assert.assertNotNull(windowHandle);
    }

}
```

**Comment by barancev** [comment] 2016-12-12 21:55
What is internetexplorerdriver (aka IEDriverSever) version?

**Comment by gunnee** [comment] 2016-12-16 20:58
sorry for the delay. I'm a bit confused as I already posted the driver version.. I checked with both:
3.0 or 2.53.1 (same result)

**Comment by barancev** [comment] 2016-12-17 17:45
Init the driver as
```      InternetExplorerDriverService service = new InternetExplorerDriverService.Builder()
              .withLogLevel(InternetExplorerDriverLogLevel.TRACE)
              .withLogFile(new File("iedriverserver.log"))
              .build();
      WebDriver driver = new InternetExplorerDriver(service);```
run the scenario to fail and attach the generated log file.

**Comment by gunnee** [comment] 2017-01-12 06:36
here you go..: [iedriverserver.txt](https://github.com/SeleniumHQ/selenium/files/700852/iedriverserver.txt)

**Comment by gunnee** [comment] 2017-03-07 16:46
@barancev any updates on this issue? in the meanwhile i tried this with ie driver version 3.2, still same error.

**Comment by diemol** [comment] 2020-05-21 10:07
Apologies for the late reply, I checked the log and didn't see anything strange there.
If the issue is still present with the latest Selenium and IE driver versions, could you please provide a self-contained automation script to reproduce the scenario?

**Comment by diemol** [comment] 2020-06-27 21:05
Closing as we did not get more information.

**Closed by diemol** 2020-06-27 21:05 UTC
Labels: D-IE, R-awaiting answer
