### ISSUE TITLE
Execution error at Linux Ubuntu.

### ISSUE THREAD

**Issue by rodolpholl** [SeleniumHQ/selenium#4616] opened 2017-08-31 21:51 UTC
## Meta -
OS:  
Ubuntu 16.04
Selenium Version:  
WebDriver .NET 3.5.1
Browser:  
Google Chrome

I've made a Console Application to execute Selenium Webdriver in Windows and Linux using ASP.NET Core 2.0.

At Windows, it's works perfectly. But, in Linux Ubuntu, An error of Permission is retrieved. 

This is the source ->

Console.WriteLine("Testing Selenium.");

            IWebDriver driver = new ChromeDriver(AppContext.BaseDirectory);
            

            driver.Navigate().GoToUrl("http://www.google.com");

            Console.WriteLine("Navigated to Google!");
            Console.WriteLine("Searching for Cheese!");
            driver.FindElement(By.Id("lst-ib")).SendKeys("Cheese");
            driver.FindElement(By.XPath("//*[@id=\"tsf\"]/div[2]/div[3]/center/input[1]")).Click();
        
            Console.WriteLine("Searching Successfull!");

-->

This is the Ubuntu Return >

Unhandled Exception: System.ComponentModel.Win32Exception: Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at OpenQA.Selenium.DriverService.Start()
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at TesteDNCore2.Program.Main(String[] args) in D:\Projetos\Estudos\SeleniumTesteDotNetCore2\TesteDNCore2\Program.cs:line 28
Aborted (core dumped)

Regards,

Rodolpho Loreto.

**Comment by rodolpholl** [comment] 2017-08-31 21:52
The erro is throwing when  its pass in ChromeDriver Constructor.

**Comment by p0deje** [comment] 2017-09-03 21:21
Are you sure that your chromedriver executable has permissions for the user you use? Can you try adding permissions for all user to execute? Something like `chmod a+x /usr/bin/chromedriver`.

**Comment by rodolpholl** [comment] 2017-09-04 15:51
I'm Using root user to do this test. But, I'll try to do this.

**Comment by barancev** [comment] 2017-09-23 08:42
Was the issue resolved by adding executable permission?

**Comment by barancev** [comment] 2017-10-10 18:25
Closing the issue, seems to be a misconfiguration

**Closed by barancev** 2017-10-10 18:25 UTC
Labels: C-dotnet, OS-linux, R-awaiting answer

**Comment by HGdsimpson** [comment] 2018-04-24 19:36
I had this issue, as well, confirmed that I no longer have this specific issue after using chmod a+x on chromedriver.
