### ISSUE TITLE
Unexpected UnreachableBrowserExceptions when using FirefoxDriver

### ISSUE THREAD

**Issue by jowerner** [SeleniumHQ/selenium#950] opened 2015-08-20 11:43 UTC
Recently, I ran into some unexpected UnreachableBrowserExceptions. More on this in a second. For context, here is my setup. Imagine a longer-running Java program that uses FirefoxDriver to test a web site. At the end of the test, the program   
- collects some values from the browser,
- takes a last screenshot, and
- finally quits the driver, so the browser process gets removed.

If this program does not run to completion, but is terminated externally (via Ctrl-C or signal), it should nevertheless execute the above steps, so they are implemented as a JVM shutdown hook which is called in any case.

However, since moving the cleanup code to the shutdown hook, the driver receives an UnreachableBrowserException for any command in the shutdown hook, even though the browser is still alive. See the Java class below that demonstrates this behavior.

After some debugging I believe that this issue is caused by the fact that once program termination is initiated, the browser's profile directory gets cleaned immediately, ie. while the browser is still being actively used. This happens via the shutdown hook of class TemporaryFilesystem.

When profile cleaning is disabled temporarily by setting the system property "webdriver.reap_profile = false", no UnreachableBrowserExceptions will be thrown and the cleanup code works fine.

Cleaning up the profile directory should probably be done by quit() alone.

[Tested on Windows 7/Linux with Selenium 2.47.1. ChromeDriver is not affected.]

**Test Case**

``` java
import org.openqa.selenium.OutputType;
import org.openqa.selenium.firefox.FirefoxDriver;

public class UnreachableBrowserExceptionTest
{
    public static void main(String[] args) throws InterruptedException
    {
        // enable this to make the issue go away
        // System.setProperty("webdriver.reap_profile", "false");

        final FirefoxDriver driver = new FirefoxDriver();

        // add a shutdown hook to ensure browser cleanup even in the event of termination
        Runtime.getRuntime().addShutdownHook(new Thread()
        {
            public void run()
            {
                try
                {
                    // wait some time as the issue is slightly timing-dependent
                    Thread.sleep(1000);

                    driver.getScreenshotAs(OutputType.BYTES);
                }
                catch (Exception e)
                {
                    e.printStackTrace();
                }
                finally
                {
                    try
                    {
                        driver.quit();
                    }
                    catch (Exception e)
                    {
                        e.printStackTrace();
                    }
                }
            }
        });

        // here the test begins
        driver.get("https://github.com/SeleniumHQ/selenium");

        // now let the shutdown hook do the cleanup
    }
}
```

**Comment by billccn** [comment] 2015-08-28 14:48
+1

The shutdown hook is entirely unnecessary, as `FirefoxDriver` deletes its profile correctly during `quit()` (after the process disconnects), as shown by the call hierarchy:

```
deleteTempDir(File) : void - org.openqa.selenium.io.TemporaryFilesystem
	clean(File) : void - org.openqa.selenium.firefox.FirefoxProfile
		cleanTemporaryModel() : void - org.openqa.selenium.firefox.FirefoxProfile
		quit() : void - org.openqa.selenium.firefox.internal.MarionetteConnection
		quit() : void - org.openqa.selenium.firefox.internal.NewProfileExtensionConnection
	writeTo(File) : void - org.openqa.selenium.firefox.internal.FileExtension
```

Setting `webdriver.reap_profile` to `false` will unfortunately also disable the `deleteTempDir()` function and leave all the junk behind.

**Comment by barancev** [comment] 2015-09-19 18:14
The issue is not related to shutdown hook.
The operation getScreenshotAs just can't take a picture of this page.

**Comment by jowerner** [comment] 2015-09-21 12:21
Just tested the behavior once again, with latest Firefox 40.0.3. Screenshotting this page works perfectly for me as long as we are in the main thread. Once process shutdown has begun, communicating with the browser fails with UnreachableBrowserExceptions. With webdriver.reap_profile set to false these exceptions go away immediately. So a connection between the exceptions and the automatic profile cleaning during shutdown seems reasonable.

I extended the code sample to demonstrate that screenshotting the page basically works, but fails later on.

```java
import java.io.File;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.firefox.FirefoxDriver;

public class UnreachableBrowserExceptionTest
{
    public static void main(String[] args) throws Exception
    {
        // enable this to make the issue go away
        //System.setProperty("webdriver.reap_profile", "false");

        final FirefoxDriver driver = new FirefoxDriver();

        // add a shutdown hook to ensure browser cleanup even in the event of termination
        Runtime.getRuntime().addShutdownHook(new Thread()
        {
            public void run()
            {
                System.out.println("Entering shutdown hook.");

                try
                {
                    // wait some time as the issue is slightly timing-dependent
                    Thread.sleep(1000);

                    driver.getScreenshotAs(OutputType.BYTES);
                    System.out.println("Last screenshot taken successfully.");
                }
                catch (Exception e)
                {
                    e.printStackTrace();
                }
                finally
                {
                    try
                    {
                        driver.quit();
                    }
                    catch (Exception e)
                    {
                        e.printStackTrace();
                    }
                }
            }
        });

        // here the test begins
        driver.get("https://github.com/SeleniumHQ/selenium");

        byte[] bytes = driver.getScreenshotAs(OutputType.BYTES);
        FileUtils.writeByteArrayToFile(new File("s1.png"), bytes);
        System.out.println("First screenshot taken successfully.");

        bytes = driver.getScreenshotAs(OutputType.BYTES);
        FileUtils.writeByteArrayToFile(new File("s2.png"), bytes);
        System.out.println("Second screenshot taken successfully.");

        // now let the shutdown hook do the cleanup
    }
}
```

**Comment by mfulton26** [comment] 2015-11-30 17:28
+1

I've ran into this as well. Below is a simple demo which I hope will help; no screen-shooting involved.

```java
import com.google.common.base.Predicate;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.FluentWait;

import java.util.Set;
import java.util.concurrent.TimeUnit;

public class FirefoxUnreachableDemo {
    /**
     * Open Firefox and register a runtime shutdown hook to wait for the user
     * to quite the browser (up to 42 days).
     */
    public static void main(String... args) {
        FirefoxDriver firefoxDriver = new FirefoxDriver();
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.out.println("waiting for browser to be closed by user");
            new FluentWait<>(firefoxDriver)
                    .withTimeout(42, TimeUnit.DAYS)
                    .until((Predicate<FirefoxDriver>) input -> {
                        Set<String> windowHandles = firefoxDriver.getWindowHandles();
                        System.out.println("windows open: " + windowHandles.size());
                        return windowHandles.isEmpty();
                    });
        }));
    }
}
```

Running the above fails to wait for Firefox to be closed and leaves the browser open. Below is example output:

```
waiting for browser to be closed by user
windows open: 1
Exception in thread "Thread-2" org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'NTISP138', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:641)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:670)
	at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandles(RemoteWebDriver.java:525)
	at FirefoxUnreachableDemo.lambda$null$0(FirefoxUnreachableDemo.java:20)
	at org.openqa.selenium.support.ui.FluentWait$1.apply(FluentWait.java:178)
	at org.openqa.selenium.support.ui.FluentWait$1.apply(FluentWait.java:176)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:176)
	at FirefoxUnreachableDemo.lambda$main$1(FirefoxUnreachableDemo.java:19)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.NoHttpResponseException: 127.0.0.1:7055 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:161)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:89)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.execute(NewProfileExtensionConnection.java:170)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.execute(FirefoxDriver.java:380)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:620)
	... 9 more
```

I've ran this several times and always get the same exception. Sometimes "windows open: 1" is not printed but I've yet to see "windows open: 2" be printed.

I have not seen this issue with `ChromeDriver` or `InternetExplorerDriver`. Please fix for `FirefoxDriver`.

**Comment by mfulton26** [comment] 2016-03-01 19:53
@barancev can you reassess this issue with the latest examples (specifically the one without using `getScreenshotAs`)? This is problematic for tools built around WebDriver. Thanks.

**Comment by hemanthsridhar** [comment] 2016-05-04 22:41
I am facing the same. Sometimes it works, sometimes it doesn't. The execution suddenly stops out of the blue and provides Unreachable browser exception.

**Comment by serge-nikitin** [comment] 2016-08-02 19:32
Have the same problem with addShutdownHook:

> Exception in thread "Thread-0" org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
> Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
> System info: host: 'mbp', ip: '10.0.1.3', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_92'
> Driver info: driver.version: RemoteWebDriver
> Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={chromedriverVersion=2.22.397929 (fb72fb249a903a0b1041ea71eb4c8b3fa0d9be5a), userDataDir=/var/folders/qg/tgmps1jj5s7b7vswcrcnq7p00000gn/T/.org.chromium.Chromium.8ER0zu}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=52.0.2743.82, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
> Session ID: 5ee09069f06065e5d75b5d165bcd849b
> 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)

**Comment by shabana-parveen** [comment] 2016-10-12 09:04
I m using Appium 1.5.1 version, Android emulator version Nexus 5.1 with selenium latest version(I tried it Selenium 2.53.1 version as well), Getting the same error, just bring you attention sometime it works, somrtime not.

org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'GGNF1882s-MacBook-Pro.local', ip: '172.16.64.102', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_74'
Driver info: driver.version: AndroidDriver
Capabilities [{app=/Users/f2849/Documents/NewVolume/Shine/CandidateBuildsVersionsTimestamp/CandidateBuild_SumoSC/shineV3-original-debug_28thSept.apk, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, deviceName=192.168.56.101:5555, platform=LINUX, desired={app=/Users/f2849/Documents/NewVolume/Shine/CandidateBuildsVersionsTimestamp/CandidateBuild_SumoSC/shineV3-original-debug_28thSept.apk, sendKeyStrategy=setValue, no-reset=true, platformVersion=5.1, full-reset=False, deviceOrientation=portrait, platformName=Android, deviceName=192.168.56.101:5555}, sendKeyStrategy=setValue, no-reset=true, platformVersion=5.1, webStorageEnabled=false, locationContextEnabled=false, full-reset=False, takesScreenshot=true, javascriptEnabled=true, deviceOrientation=portrait, platformName=Android}]
Session ID: b3371f08-6806-43b6-be4f-b3376a0eaefb
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:27)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:413)
at io.appium.java_client.DefaultGenericMobileDriver.findElementById(DefaultGenericMobileDriver.java:47)
at io.appium.java_client.AppiumDriver.findElementById(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.findElementById(AndroidDriver.java:1)
at org.openqa.selenium.By$ById.findElement(By.java:218)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
at com.shineSauceLabs.Main.TestShineApp_MatchedJobs.test40_goto_ShineApp_testMatchedJobs(TestShineApp_MatchedJobs.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
at org.testng.TestRunner.privateRun(TestRunner.java:753)
at org.testng.TestRunner.run(TestRunner.java:607)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
at org.testng.SuiteRunner.run(SuiteRunner.java:270)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
at org.testng.TestNG.runSuites(TestNG.java:1124)
at org.testng.TestNG.run(TestNG.java:1096)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused
at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:140)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
... 39 more
Caused by: java.net.ConnectException: Connection refused
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:117)
... 52 more

**Comment by barancev** [comment] 2017-08-28 12:24
This issue is still actual, but it will never be fixed in legacy Firefox driver.
The new Firefox driver implementation (aka geckodriver) does not suffer from this issue, tested on Firefox 57 + geckodriver 0.18 + Selenium Java 3.5.2

**Closed by barancev** 2017-08-28 12:24 UTC
Labels: D-firefox

**Comment by shabana-parveen** [comment] 2017-08-28 12:31
Does It support with appium?

**Comment by barancev** [comment] 2017-08-28 13:03
Appium is a driver for mobile devices, totally unrelated to Firefox drivers.
