### ISSUE TITLE
IE 11 + Selenium 3.2 + IEDriver 3.2 - file upload (SendKeys) stop/don't work

### ISSUE THREAD

**Issue by Rain9333** [SeleniumHQ/selenium#3609] opened 2017-03-06 15:29 UTC
OS:  Windows 10 x64
Selenium Version:  3.2.0
Browser:  IE 11 32 bits

### Steps to reproduce:
Attempt to upload file (the one with dialog pop-up where you put the path and submit it). E.g. of code used:
```
var element =  FindElement(By.Id("BrowseFileUpload"));
element.SendKeys(pathToZip);
```

## Expected Behavior:
Path is send successfully to the dialog like before & like on Chrome/Firefox.

## Actual Behavior:
Browser hangout (never fail or close itself) with open file upload dialog, no matter that I set that IE option -> FileUploadDialogTimeout = DriverTimeout (TimeSpan of 15 seconds). 

```
Result StackTrace:	
at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.SendKeys(String text)

Result Message:	
OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL 
http://localhost:23595/session/72abf599-4800-4598-a9ad-7442cfc18131/element/a5140863-a7a4-4913-ab74-1f212d4d7687/value timed out after 60 seconds.
  ----> System.Net.WebException : The request was aborted: The operation has timed out.
```

**Comment by lmtierney** [comment] 2017-03-07 04:30
Duplicate of #3587

**Closed by lmtierney** 2017-03-07 04:30 UTC
