### ISSUE TITLE
Getting `SocketError: getaddrinfo: Name or service not known`

### ISSUE THREAD

**Issue by vitorgalvao** [SeleniumHQ/selenium#3030] opened 2016-10-29 12:56 UTC
## Meta

OS: Linux CentOS (`centos-release-6-8.el6.centos.12.3.x86_64`)
Selenium Version: `3.0.0`
Browser: PhantomJS
Browser Version: `2.1.1.1`
## Problem

I have both `selenium-webdriver` and `phantomjs`:

```
$ gem list # removed irrelevant entries
phantomjs-binaries (2.1.1.1)
selenium-webdriver (3.0.0)
```

And I get a `SocketError: getaddrinfo: Name or service not known` error when trying to call the latter with the former:

``` ruby
irb> require 'selenium-webdriver'
=> true
irb> browser = Selenium::WebDriver.for(:phantomjs)
SocketError: getaddrinfo: Name or service not known
    from /home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/common/platform.rb:175:in `getaddrinfo'
    from /home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/common/platform.rb:175:in `localhost'
    from /home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/common/service.rb:43:in `initialize'
    from /home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/phantomjs/bridge.rb:34:in `new'
    from /home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/phantomjs/bridge.rb:34:in `initialize'
    from /home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/common/driver.rb:66:in `new'
    from /home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/common/driver.rb:66:in `for'
    from /home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver.rb:82:in `for'
    from (irb):4
    from /home2/username/_mydirectory/ruby/bin/irb:11:in `<main>'   
```

As far as I can gather, a similar class of errors occurs commonly due to a wrong mapping of `localhost` to `127.0.0.1` in `/etc/hosts`.

In this case, this error is occurring on a shared hosting (so I have limited privileges) and there is no `/etc/hosts` (I’ve contacted support and they told me that is expected for shared accounts). The mapping seems to be correct, anyway:

```
$ host localhost
localhost has address 127.0.0.1
localhost has IPv6 address ::1
```

---

If I install an older version of `selenium-webdriver` (specifically version `2.46.2`), it hangs indefinitely instead of outputting the error.

---

I also found https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/4020 while looking for a resolution. For the command `ruby -rsocket -e 'p IPSocket.getaddress(Socket.gethostname)'`, the output is the correct IP address for the server.

As for `ruby -r selenium-webdriver -e 'p Selenium::WebDriver::Platform.interfaces'`, I get:

``` ruby
/home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/common/platform.rb:198:in `getaddrinfo': getaddrinfo: Name or service not known (SocketError)
    from /home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/common/platform.rb:198:in `interfaces'
    from -e:1:in `<main>'
```

---

Again, this is a shared hosting, _but_ on this exact shared hosting (though with a different account) just a few weeks ago this was working. Unfortunately, I don’t have access to that old account anymore to check the exact versions of the installed gems, but I tried a huge combination of versions and nothing seems to work.

Running `phantomjs` by itself runs fine, hence why I’m submitting here.

**Comment by titusfortner** [comment] 2016-10-29 16:59
Does it work with gem for 2.53?

On Oct 29, 2016 7:56 AM, "Vítor Galvão" <notifications@github.com> wrote:

Meta

OS: Linux CentOS (centos-release-6-8.el6.centos.12.3.x86_64)
Selenium Version: 3.0.0
Browser: PhantomJS
Browser Version: 2.1.1.1
Problem

I have both selenium-webdriver and phantomjs:

$ gem list # removed irrelevant entries
phantomjs-binaries (2.1.1.1)
selenium-webdriver (3.0.0)

And I get a SocketError: getaddrinfo: Name or service not known error when
trying to call the latter with the former:

irb> require 'selenium-webdriver'
=> true
irb> browser = Selenium::WebDriver.for(:phantomjs)SocketError:
getaddrinfo: Name or service not known
    from /home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/common/platform.rb:175:in
`getaddrinfo'    from
/home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/common/platform.rb:175:in
`localhost'    from
/home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/common/service.rb:43:in
`initialize'
    from /home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/phantomjs/bridge.rb:34:in
`new'    from /home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/phantomjs/bridge.rb:34:in
`initialize'    from
/home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/common/driver.rb:66:in
`new'
    from /home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/common/driver.rb:66:in
`for'    from /home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver.rb:82:in
`for'    from (irb):4    from
/home2/username/_mydirectory/ruby/bin/irb:11:in `<main>'

As far as I can gather, a similar class of errors occurs commonly due to a
wrong mapping of localhost to 127.0.0.1 in /etc/hosts.

In this case, this error is occurring on a shared hosting (so I have
limited privileges) and there is no /etc/hosts (I’ve contacted support and
they told me that is expected for shared accounts). The mapping seems to be
correct, anyway:

$ host localhost
localhost has address 127.0.0.1
localhost has IPv6 address ::1

------------------------------

If I install an older version of selenium-webdriver (specifically version
2.46.2), it hangs indefinitely instead of outputting the error.
------------------------------

I also found SeleniumHQ/selenium-google-code-issue-archive#4020
<https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/4020>
while looking for a resolution. For the command ruby -rsocket -e 'p
IPSocket.getaddress(Socket.gethostname)', the output is the correct IP
address for the server.

As for ruby -r selenium-webdriver -e 'p Selenium::WebDriver::Platform.
interfaces', I get:

/home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/common/platform.rb:198:in
`getaddrinfo': getaddrinfo: Name or service not known (SocketError)
from /home2/username/_mydirectory/ruby/gems/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/common/platform.rb:198:in
`interfaces'    from -e:1:in `<main>'

------------------------------

Again, this is a shared hosting, *but* on this exact shared hosting (though
with a different account) just a few weeks ago this was working.
Unfortunately, I don’t have access to that old account anymore to check the
exact versions of the installed gems, but I tried a huge combination of
versions and nothing seems to work.

Running phantomjs by itself runs fine, hence why I’m submitting here.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SeleniumHQ/selenium/issues/3030>, or mute the thread

**Comment by vitorgalvao** [comment] 2016-10-29 18:12
> Does it work with gem for 2.53?

No.

**Comment by p0deje** [comment] 2016-11-15 04:06
Can you try to run the following commands and post output for debugging:

```
$ hostname
$ ifconfig
$ cat /etc/sysconfig/network

$ ruby -rsocket -e 'p Socket.getaddrinfo("localhost", "http", Socket::AF_INET, Socket::SOCK_STREAM)'
$ ruby -rsocket -e 'p Socket.getaddrinfo("localhost", "http", Socket::AF_INET6, Socket::SOCK_STREAM)'

$ ruby -rsocket -e 'p Socket.getaddrinfo("localhost", 80, Socket::AF_INET, Socket::SOCK_STREAM)'
$ ruby -rsocket -e 'p Socket.getaddrinfo("localhost", 80, Socket::AF_INET6, Socket::SOCK_STREAM)'

$ ruby -rsocket -e 'p Socket.getaddrinfo("localhost", 8080, Socket::AF_INET, Socket::SOCK_STREAM)'
$ ruby -rsocket -e 'p Socket.getaddrinfo("localhost", 8080, Socket::AF_INET6, Socket::SOCK_STREAM)'

$ ruby -rsocket -e 'p Socket.getaddrinfo("localhost", nil, Socket::AF_INET, Socket::SOCK_STREAM)'
$ ruby -rsocket -e 'p Socket.getaddrinfo("localhost", nil, Socket::AF_INET6, Socket::SOCK_STREAM)'
```

Is there any other way to debug the problem? For example, connect on IRC and try to debug online.

**Comment by vitorgalvao** [comment] 2016-11-15 16:50
> Can you try to run the following commands and post output for debugging:

**Command:** `hostname`
**Result:** `box839.bluehost.com`

---

**Command:** `ifconfig`
<details><summary>**Result**</summary>
```
eth0      Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:66.147.244.139  Bcast:66.147.247.255  Mask:255.255.252.0
          inet6 addr: fe80::225:90ff:fe56:f40a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4711787638 errors:0 dropped:7661 overruns:399923 frame:0
          TX packets:5947515025 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1952475065934 (1.7 TiB)  TX bytes:7268194364641 (6.6 TiB)
          Memory:fea60000-fea80000

eth0:cp1  Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:67.20.109.125  Bcast:67.20.111.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp2  Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:173.254.35.174  Bcast:173.254.39.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp3  Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:173.254.0.59  Bcast:173.254.3.255  Mask:255.255.252.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp4  Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.136.20  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp5  Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.143.137  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp6  Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.140.127  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp7  Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.142.92  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp8  Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.136.114  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp9  Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.139.20  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp10 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.136.93  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp11 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.137.238  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp12 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:173.254.37.147  Bcast:173.254.39.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp13 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.138.185  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp14 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.136.68  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp15 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.142.145  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp16 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.140.49  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp17 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.139.126  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp18 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.140.129  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp19 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.140.97  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp20 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.137.56  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp21 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.139.177  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp22 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:173.254.3.215  Bcast:173.254.3.255  Mask:255.255.252.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp23 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.138.78  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp24 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:67.20.93.65  Bcast:67.20.95.255  Mask:255.255.252.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp25 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:69.195.91.144  Bcast:69.195.95.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp26 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:69.195.93.239  Bcast:69.195.95.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp27 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.180.155  Bcast:50.87.183.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp28 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.182.23  Bcast:50.87.183.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp29 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:173.254.92.20  Bcast:173.254.95.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp30 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:69.195.121.153  Bcast:69.195.123.255  Mask:255.255.252.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp31 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:173.254.104.89  Bcast:173.254.111.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp32 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.189.157  Bcast:50.87.191.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp33 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:67.222.43.233  Bcast:67.222.43.255  Mask:255.255.252.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp34 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:69.89.28.210  Bcast:69.89.31.255  Mask:255.255.240.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp35 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.22.201  Bcast:50.87.23.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp36 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:67.20.125.142  Bcast:67.20.125.255  Mask:255.255.254.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp37 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:67.20.120.95  Bcast:67.20.123.255  Mask:255.255.252.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp38 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.219.128  Bcast:50.87.223.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp39 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:70.40.218.171  Bcast:70.40.223.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp40 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:67.222.42.228  Bcast:67.222.43.255  Mask:255.255.252.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp41 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.174.75  Bcast:50.87.175.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp42 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:173.254.16.29  Bcast:173.254.23.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp43 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.234.25  Bcast:50.87.239.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp44 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.136.59  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp45 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.234.223  Bcast:50.87.239.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp46 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:69.195.69.136  Bcast:69.195.71.255  Mask:255.255.252.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp47 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:173.254.35.181  Bcast:173.254.39.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp48 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:173.254.12.216  Bcast:173.254.15.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp49 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:69.89.26.197  Bcast:69.89.31.255  Mask:255.255.240.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp50 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:173.254.12.41  Bcast:173.254.15.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp51 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:74.220.211.160  Bcast:74.220.211.255  Mask:255.255.252.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp52 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:69.195.105.189  Bcast:69.195.111.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp53 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.224.125  Bcast:50.87.231.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp54 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.229.125  Bcast:50.87.231.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp55 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:67.20.94.138  Bcast:67.20.95.255  Mask:255.255.252.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp56 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:69.195.74.113  Bcast:69.195.79.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp57 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:70.40.203.236  Bcast:70.40.207.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp58 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:162.144.184.93  Bcast:162.144.187.255  Mask:255.255.252.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp59 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:173.254.23.209  Bcast:173.254.23.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp60 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:162.144.184.221  Bcast:162.144.187.255  Mask:255.255.252.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp61 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:173.254.104.195  Bcast:173.254.111.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp62 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:50.87.138.198  Bcast:50.87.143.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp63 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:173.254.16.65  Bcast:173.254.23.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth0:cp64 Link encap:Ethernet  HWaddr 00:25:90:56:F4:0A
          inet addr:67.20.65.87  Bcast:67.20.67.255  Mask:255.255.252.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          Memory:fea60000-fea80000

eth1      Link encap:Ethernet  HWaddr 00:25:90:56:F4:0B
          inet addr:172.16.6.137  Bcast:172.16.31.255  Mask:255.255.224.0
          inet6 addr: fe80::225:90ff:fe56:f40b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:391583575 errors:0 dropped:0 overruns:171 frame:0
          TX packets:534548157 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:185765463676 (173.0 GiB)  TX bytes:436078428005 (406.1 GiB)
          Memory:feae0000-feb00000

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1074404246 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1074404246 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:4896468140030 (4.4 TiB)  TX bytes:4896468140030 (4.4 TiB)
```
</details>

---

**Command:** `cat /etc/sysconfig/network`
**Result:** `cat: /etc/sysconfig/network: No such file or directory`

---

All the `ruby -rsocket` **commands** give the exact same **result**: 
```
-e:1:in `getaddrinfo': getaddrinfo: Name or service not known (SocketError)
	from -e:1:in `<main>'
```

---

> Is there any other way to debug the problem? For example, connect on IRC and try to debug online.

Yes, possibly. If none of those results gives you a clue let me know, and where to connect to.

**Comment by p0deje** [comment] 2016-12-12 07:48
Maybe the problem is actually with the lack of `/etc/sysconfig/network`. Quick googling shows [this SO question](http://serverfault.com/questions/129556/how-do-i-fix-getaddrinfo-localhost-name-or-service-not-found-for-telnet-serve) so maybe you should try to check it out.

Since that's a general issue reproducible with plain Ruby, I'm going to close this issue as not a bug in Selenium. Sorry, I guess that's not what you expected, but there is not much maintainers can do about it.

**Closed by p0deje** 2016-12-12 07:48 UTC
Labels: C-rb

**Comment by vitorgalvao** [comment] 2016-12-12 12:16
Thank you anyway for looking into it, @p0deje. Not looking forward to picking a new tool and rewriting all those scripts; watir was a pleasure to work with.

**Comment by apast** [comment] 2017-08-18 16:10
Hello @vitorgalvao ,

I experienced the same problem here. I checked my /etc/resolv.conf , and there were a syntax error on file.

Now, I fix syntax and gem is working again.

**Comment by vitorgalvao** [comment] 2017-08-18 20:33
@apast Yes, all solutions I’ve found pertain to that. Problem is, as stated in the top post:

> In this case, this error is occurring on a shared hosting (so I have limited privileges) and there is no `/etc/hosts` (I’ve contacted support and they told me that is expected for shared accounts). The mapping seems to be correct, anyway:

**Comment by apast** [comment] 2017-08-18 21:15
@vitorgalvao 
I just found a reply on superuser with a solution creation Host Aliases.
https://unix.stackexchange.com/a/104511
Do it help in your case?

**Comment by vitorgalvao** [comment] 2017-08-18 22:08
@apast Just checked on the server, and this error is no longer happening (now I have a different one). With or without that solution.
