### ISSUE TITLE
select button issue

### ISSUE THREAD

**Issue by janki3195** [SeleniumHQ/selenium#5036] opened 2017-11-09 05:53 UTC
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by janki3195** [comment] 2017-11-09 05:56
select button in selenium ide is not working. i can not select any target for test case.

**Comment by lmtierney** [comment] 2017-11-09 14:58
Duplicate of #4406

**Closed by lmtierney** 2017-11-09 14:58 UTC
