### ISSUE TITLE
Firefox 47 - Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. 

### ISSUE THREAD

**Issue by mmwwipula** [SeleniumHQ/selenium#2110] opened 2016-05-16 12:54 UTC
## Meta -
OS:  Windows 7

Selenium Version:  2.52.0

Browser:  Firefox

Browser Version:  47.0b5

## Expected Behavior -
Open Browser -> Maximize Window -> Go to Website
## Actual Behavior -
Open Bwoeser -> Exception Message='Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms.

## Additional Information -
Running NUnit Tests using Selenium Grid. Issue cannot reproduce with Firefox 46 or previous versions.

**Comment by adrianer** [comment] 2016-06-03 09:15
The same thing happens with Selenium Version: 2.53.0

When watching the behavior live, then one can see that Firefox hangs right after it is opened by Selenium (the Fx GUI can be seen).

**Comment by davehunt** [comment] 2016-06-03 11:54
You will need to use the new Firefox driver from version 47 onwards. See https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver for details.

**Comment by davehunt** [comment] 2016-06-06 11:45
The add-ons signing feature of Firefox has now been pushed to version 48, so when 47 is released it should still be supported. I'm going to unlock this issue to allow users to report if they are still seeing problems after Firefox 47 is released.

**Comment by omeravni78** [comment] 2016-06-07 06:42
hi all
it happened to me also.
Selenium 2.50.1.0 
ff 47 
win 7 64 bit

**Comment by davehunt** [comment] 2016-06-07 10:32
Firefox 47 has not been released yet (it should be out later today). Please refrain from commenting unless you are using the official release of Firefox 47, preferably with the latest version of Selenium (2.53).

**Comment by adrianer** [comment] 2016-06-07 10:41
> Firefox 47 has not been released yet (it should be out later today). Please refrain from commenting unless you are using the official release of Firefox 47, preferably with the latest version of Selenium (2.53).

I'm using the Fx 47 build that will most likely be declared today as the official one (from here: https://ftp.mozilla.org/pub/firefox/releases/47.0/ ) - and still experiencing the issue here, so it seems the addon signing hasn't been pushed to 48...

**Comment by AutomatedTester** [comment] 2016-06-07 13:19
This issue has nothing to do with addon signing. Something in FirefoxDriver is causing Firefox to have a startup crash.

**Comment by pravinrmali** [comment] 2016-06-07 13:57
I'm Using Firefox 47 and Selenium-Webdriver 2.53.0 and still experiencing the issue mentioned above.

**Comment by AutomatedTester** [comment] 2016-06-07 14:05
Locking this issue to prevent "me too" comments. Please use the subscribe feature to on the right to follow this bug.

**Comment by AutomatedTester** [comment] 2016-06-07 15:54
We appear to be ticking something in the JSRuntime https://gist.github.com/AutomatedTester/8c011e194e6343b6d9bfbda80af76402

**Comment by AutomatedTester** [comment] 2016-06-07 21:03
The issue is that code to support cert override was changed in a way that broke Selenium which in turn then crashed Firefox. There is a fix in the works from Mozilla. 

As a work around you can either revert to Firefox 46 or you can use Marionette*. We have documented how to get set up with Marionette on [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver). 

* **Note :** When [Extension Signing](https://wiki.mozilla.org/Addons/Extension_Signing) ships in Firefox 48 or later the current Selenium WebDriver addon approach will no longer work and you will need to update to Marionette.

**Comment by AutomatedTester** [comment] 2016-06-08 10:20
Looks like this patch, once verified, may only be out next week. I strongly suggest people move over to [Marionette](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver) or downgrade to Firefox 46/ESR 45.

**Comment by AutomatedTester** [comment] 2016-06-08 20:25
This has been fixed in Firefox, will close this bug when it is released

**Comment by AutomatedTester** [comment] 2016-06-28 21:08
Firefox 47.0.1 has been released with a fix. We now need to release client libraries to pick up a version bump in the xpi that is used by FirefoxDriver

**Comment by AutomatedTester** [comment] 2016-06-30 14:57
Most, if not all, of the clients have been released by now

**Closed by AutomatedTester** 2016-06-30 14:57 UTC
Labels: D-firefox, I-regression

**Comment by lukeis** [comment] 2016-06-30 19:55
it's also now in maven central
