### ISSUE TITLE
deleteAllCookies using IEDriverServer hangs during multiple scenarios runs from same story file

### ISSUE THREAD

**Issue by ghprashant** [SeleniumHQ/selenium#1834] opened 2016-03-17 04:02 UTC
## Meta -

OS: Windows 7 64 bit
Selenium Version: IEDriverServer_Win32_2.48.0 
Browser: IE11 64bit
Browser Version: 11.0.9600.18204
## Expected Behavior -

The call to 'deletAllCookies' from multiple scenarios in a story file should work and not make the tests hang.
## Actual Behavior -

When 'deleteAllCookies method is called on the driver, the test hangs. No error is displayed and control never comes back to the calling method. This happens only when a second scenario from the same story file runs. The first thing that happens in this scenario is to delete cookies using this method. The same line of code works fine with the very first scenario from the story file.

With IEDriverServer_Win32_2.45.0, all the scenarios in the stories calling this 'deleteAllCookies' method work fine.
## Steps to reproduce -

create a bdd story file with two or more scenarios.
Ensure all scenarios are defined in the same story file.
Ensure in the Given method of all these scenarios, the call to deleteAllCookies is made.
Then run the tests. You will notice that the first scenario runs fine. The deleteAllCookies method in the Given method works fine. But the same hangs when next scenario runs.

**Comment by jimevans** [comment] 2016-03-24 21:34
Cookie handling in the IE driver changed drastically between 2.46 and 2.47. You mention that you're using 64-bit IE, but the 32-bit IE driver executable. That seems unlikely, given that "64-bit IE" for version 10 or 11 [doesn't really exist](http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html). You'll need to provide a log from `IEDriverServer.exe` displaying the issue.

**Comment by zenonwch** [comment] 2016-10-17 08:56
Faced the same problem on IE_11 x32 with selenium-server-standalone-2.48.2 and IEDriverServer_Win32_2.48.
Tried on the same IE with selenium-server-standalone-2.53.0 and IEDriverServer_Win32_2.53 - works well.

**Comment by zenonwch** [comment] 2016-10-19 11:57
Not all so good :(.
IE 11 hangs if try to manipulate with cookies in new window opened by click link/button in main window.
IE_11 x32, selenium-server-standalone-2.53.0 and IEDriverServer_Win32_2.53.

How to reproduce: 
1. Start driver
2. Go to the page where there is a link/button for authentication via oAuth (e.g. Google)
3. Click the button should open new window
4. Switch to new window using driver.switchTo().window({new_opened_window})
5. Try to manipulate with cookies (e.g. driver.manage().getCookies())

**Comment by zenonwch** [comment] 2016-10-22 19:58
Today tried with next config:
Win7 x64 + IE 11 x64 + IEDriverServer_x64_2.53.1 + selenium-server-standalone-2.53.1
No problem with cookies for newly opened window on click.
But I can't use x64 due to slow sendKey. Either can't use x64 with nativeEvents = false - on some pages got error "Unable to get property 'focus' of undefined or null reference".

**Comment by benzman81** [comment] 2017-03-07 10:03
Also happens with IEDriver 3.1.0.0 32Bit. Unable to reproduce it in a simple snippet, but occurs ervertime we run our tests. We have two suites running with testng. The hang always occurs on deleteAllCookies() in the last test of the first Suite.

**Comment by jimevans** [comment] 2017-03-19 00:12
@benzman81 Can you provide a log displaying the issue?

**Comment by benzman81** [comment] 2017-03-19 00:22
@jimevans: there was no log entry or system out for this. The thread just hung. I needed to work with threaddumps to find that it hangs on deleting cookies. We removed the method call for now to have running tests. No tests hung since then. We use a 2.4x or 2.5x version before (cant remember, but if needed I can look it up) and the issue didt exist there.

**Comment by jimevans** [comment] 2017-03-24 11:35
@benzman81 I think you misunderstood what I was asking for. It's possible for `IEDriverServer.exe` to generate a log file. Manually, this is accomplished via command line switches. In code, it's typically done by modifying the `InternetExplorerDriverService` instance used by your code. That's the log (preferably at a `TRACE` level) I want to see.

**Comment by GitSage** [comment] 2018-09-04 22:03
@jimevans 

You can reliably reproduce the issue like this:

* Go to a web page.
* Open a popup.
* Switch to the popup.
* Try to clear cookies.

I made [this repo](https://github.com/GitSage/webdriver-ie-cookies-bug) to make reproduction easy. In short, given this site:

```
<!-- index.html -->
<html>
<body>
	<a href="popup.html" target="_blank" id="openPopup">Click Me To Open a Popup</a>
</body>
</html>
```

and 

```
<!-- popup.html -->
<html>
<body>
	This is a popup
</body>
</html>
```

run this script:

```
const {Builder, By} = require('selenium-webdriver');

(async function example() {
	let browser = await new Builder()
		.usingServer('http://localhost:5555')
		.forBrowser('internet explorer')
		.build();
	try {
		await browser.get('http://127.0.0.1:8080/index.html');
		await browser.findElement(By.id('openPopup')).click();

		let handles = await browser.getAllWindowHandles();
		await browser.switchTo().window(handles[handles.length - 1]);

		await browser.manage().deleteAllCookies();

	} finally {
		await browser.quit();
	}
})();
```

I've attached logs from IEDriverServer and from webdriver-manager.
[iedriverserver TRACE.log](https://github.com/SeleniumHQ/selenium/files/2350391/iedriverserver.TRACE.log)
[webdriver-manager FINE.log](https://github.com/SeleniumHQ/selenium/files/2350392/webdriver-manager.FINE.log)

**Comment by jimevans** [comment] 2018-09-10 22:07
@GitSage Can you please try 3.14.0.5 of the IE driver? It's checked into the source tree and can be [downloaded there](https://github.com/SeleniumHQ/selenium/blob/master/cpp/prebuilt/Win32/Release/IEDriverServer.exe).

**Comment by barancev** [comment] 2019-07-13 17:43
Is this issue still actual? As @jimevans stated, IE driver was rewritten many times, including the cookie subsystem.

**Comment by barancev** [comment] 2019-07-14 07:47
I run the sample provided in the comment https://github.com/SeleniumHQ/selenium/issues/1834#issuecomment-418532915 many times without a single hang. So the issue must be fixed by now.

**Comment by barancev** [comment] 2019-09-29 18:09
Closing the issue, it's related to antique IE driver versions and seems to be not relevant anymore.

**Closed by barancev** 2019-09-29 18:09 UTC
Labels: D-IE, R-awaiting answer
