### ISSUE TITLE
[🐛 Bug]: Selenium-manager fails on linux when home directory is un-writeable

### ISSUE THREAD

**Issue by bertmad3400** [SeleniumHQ/selenium#12571] opened 2023-08-17 14:32 UTC
### What happened?

It seems that the selenium binary fails with little warning as too what happened if the home directory for the user running it for one reason or another isn't writable. Changing the home directory to being writable for the user fixes the issue.

This can be very problematic, as selenium is often used on servers to - headlessly - scrape information from sites. This is often done using cron-jobs or system timers, using a user that - since this is their only purpose - either has no home directory or has one that - for one reason or another - is un-writable.

### How can we reproduce the issue?

```shell
Simply attempt to create a selenium instance in python on a linux machine, where the home directory of the user running the python code have a home directory that is un-writable.
```

### Relevant log output

```shell
Before correcting the issue:


- From python:
Selenium Manager binary found at: /srv/osinter/backend/venv/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager
Executing process: /srv/osinter/backend/venv/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager --browser firefox --debug --output json
Unable to obtain driver for firefox using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
Traceback (most recent call last):
  File "/srv/osinter/backend/venv/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 126, in run
    output = json.loads(stdout)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/osinter/backend/venv/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/osinter/backend/venv/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 90, in driver_location
    output = self.run(args)
             ^^^^^^^^^^^^^^
  File "/srv/osinter/backend/venv/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 129, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}") from err
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: /srv/osinter/backend/venv/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager --browser firefox --debug --output json


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/osinter/backend/scripts/scraping/articles/__init__.py", line 68, in gather_article_urls
    articles_source = scrape_page_dynamic(
                      ^^^^^^^^^^^^^^^^^^^^
  File "/srv/osinter/backend/scripts/scraping/articles/scraping.py", line 151, in scrape_page_dynamic
    with webdriver.Firefox(
         ^^^^^^^^^^^^^^^^^^
  File "/srv/osinter/backend/venv/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 59, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/osinter/backend/venv/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_locatio


- From the rust binary (selenium-manager) with RUST_BACKTRACE=1
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/files.rs:65:34
Interrupted (SIGABRT)


After correcting the issue:
- From the rust binary (selenium-manager) with RUST_BACKTRACE=1
{
  "logs": [
    {
      "level": "DEBUG",
      "timestamp": 1692282076,
      "message": "Checking geckodriver in PATH"
    },
    {
      "level": "DEBUG",
      "timestamp": 1692282076,
      "message": "Running command: geckodriver --version"
    },
    {
      "level": "DEBUG",
      "timestamp": 1692282076,
      "message": "Output: \"\""
    },
    {
      "level": "DEBUG",
      "timestamp": 1692282076,
      "message": "geckodriver not found in PATH"
    },
    {
      "level": "DEBUG",
      "timestamp": 1692282076,
      "message": "firefox detected at /usr/bin/firefox"
    },
    {
      "level": "DEBUG",
      "timestamp": 1692282076,
      "message": "Using shell command to find out firefox version"
    },
    {
      "level": "DEBUG",
      "timestamp": 1692282076,
      "message": "Running command: /usr/bin/firefox -v"
    },
    {
      "level": "DEBUG",
      "timestamp": 1692282076,
      "message": "Output: \"Mozilla Firefox 116.0.3\""
    },
    {
      "level": "DEBUG",
      "timestamp": 1692282076,
      "message": "Detected browser: firefox 116.0.3"
    },
    {
      "level": "DEBUG",
      "timestamp": 1692282076,
      "message": "Required driver: geckodriver 0.33.0"
    },
    {
      "level": "DEBUG",
      "timestamp": 1692282076,
      "message": "geckodriver 0.33.0 already in the cache"
    },
    {
      "level": "INFO",
      "timestamp": 1692282076,
      "message": "Driver path: /home/user/.cache/selenium/geckodriver/linux64/0.33.0/geckodriver"
    },
    {
      "level": "INFO",
      "timestamp": 1692282076,
      "message": "Browser path: /usr/bin/firefox"
    }
  ],
  "result": {
    "code": 0,
    "message": "/home/user/.cache/selenium/geckodriver/linux64/0.33.0/geckodriver",
    "driver_path": "/home/user/.cache/selenium/geckodriver/linux64/0.33.0/geckodriver",
    "browser_path": "/usr/bin/firefox"
  }
}
```

### Operating System

Arch Linux (kernel 6.4.0) x86

### Selenium version

Python 4.11.2

### What are the browser(s) and version(s) where you see this issue?

Mozilla Firefox 116.0.3

### What are the browser driver(s) and version(s) where you see this issue?

Geckodriver 0.33.0

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment] 2023-08-17 14:40
This is a duplicate of #12535
We'll have a solution when we release 4.12

**Closed as not planned by titusfortner** 2023-08-17 14:40 UTC
Labels: I-defect, A-needs-triaging
