### ISSUE TITLE
Selenium (or Firefox/geckodriver) fails to type space characters

### ISSUE THREAD

**Issue by elliterate** [SeleniumHQ/selenium#4334] opened 2017-07-18 17:37 UTC
## Meta -
OS:  OS X, Linux
Selenium Version:  3.4.3
Browser:  Firefox/geckodriver
Browser Version:  54.0.1/0.18.0

## Expected Behavior -
Given I have a handle on a text field element
When I send `Keys.SPACE` with `send_keys()`
Then I see a space character in the text field

## Actual Behavior -
No space character appears in the text field.

## Steps to reproduce -
```python
from unittest import TestCase, main

from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys


class TestSendKeys(TestCase):
    def setUp(self):
        capabilities = DesiredCapabilities.FIREFOX.copy()
        capabilities["marionette"] = True
        self.browser = webdriver.Firefox(capabilities=capabilities)
        self.browser.get("https://mdn.github.io/learning-area/html/forms/editable-input-example/editable_input.html")
        self.element = self.browser.find_element_by_css_selector("input[type='text']")
        
    def tearDown(self):
        self.browser.quit()

    def test_special_characters(self):
        self.element.send_keys("ocean", Keys.SPACE, "sie", Keys.LEFT, "d")
        self.assertEqual(self.element.get_attribute("value"), "ocean side")

if __name__ == "__main__":
    main()
```

**Comment by p0deje** [comment] 2017-07-26 09:28
I guess this is related to mozilla/geckodriver#777, so you need to use Actions API for entering space character. Not sure how this is done in Python, but in Ruby it looks like this:

```ruby
el = driver.find_element(css: "input[type='text']")
driver.action.send_keys(el, "a", :space, "b").perform
```

I can confirm that this code correctly enters a space character.

I'm going to close this issue for now, however, we need to figure out if we are going to support API compatibility between OSS and W3C implementations. Please, keep an eye on #4349.

**Closed by p0deje** 2017-07-26 09:28 UTC

**Comment by elliterate** [comment] 2017-07-26 12:40
The equivalent in Python would be:

```python
# ...
from selenium.webdriver.common.action_chains import ActionChains
# ...

class TestSendKeys(TestCase):
    # ...

    def test_special_characters(self):
        actions = ActionChains(self.browser)
        actions.click(self.element)
        actions.send_keys("ocean", Keys.SPACE, "sie", Keys.LEFT, "d")
        actions.perform()
        # ...
```

I too can confirm that this correctly enters a space character.

I can see how this might be related to mozilla/geckodriver#777, but I would find it a bit surprising if the explanation were the same. Their issue involves a checkbox, while [the spec][1] mostly restricts the use of `Element#send_keys` to "text input controls." It makes sense, then, that they cannot do what they are trying to do. My scenario, however, involves just such a text input control.

What's more, sending `" "` (rather than `Keys.SPACE`) works as expected—both with and without an action chain. If `" "` and `Keys.LEFT` work in both contexts, then I would expect `Keys.SPACE` to work as well.

  [1]: https://w3c.github.io/webdriver/webdriver-spec.html#element-send-keys

**Comment by p0deje** [comment] 2017-07-26 13:48
Good point, can I ask you to raise the issue for GeckoDriver?

**Comment by elliterate** [comment] 2017-07-26 14:51
Sure thing! Reported as mozilla/geckodriver#846.
