### ISSUE TITLE
Firefox quit with error when disposing Selenium instance with custom profile.

### ISSUE THREAD

**Issue by nirhp** [SeleniumHQ/selenium#4520] opened 2017-08-21 12:54 UTC
## Meta -
OS:  Windows 7

Selenium Version:  3.5.1, 3.5.0

Browser:  Firefox 

Browser Version:  
54.0 32 bit, 55.0.2 32 bit, 55.0.2 64 bit

## Expected Behavior -
Firefox will quit with no errors
## Actual Behavior -
After Firefox windows is closed, a windows error window come up:
![image](https://user-images.githubusercontent.com/14215603/29553844-ac4b2f20-8725-11e7-8c53-d440e2d490f4.png)

## Steps to reproduce -

1. Create Selenium firefox instance with 'firefoxOptions.Profile = new FirefoxProfile()' for example, the bellow C# code:
```
        static void Main(string[] args)
        {
            var firefoxService = FirefoxDriverService.CreateDefaultService();
            var firefoxOptions = new FirefoxOptions() {Profile = new FirefoxProfile() };

            using (var webDriver = new FirefoxDriver(firefoxService, firefoxOptions, TimeSpan.FromMinutes(1)))
            {
                webDriver.Navigate().GoToUrl("http://www.google.com");
            }

            Console.WriteLine("Finished");
        }
```
2. Execute the above code.

When running a under Jenkins and the job passes ('Profile = new FirefoxProfile()' is emitted), its output contains:

> 1503317595886	geckodriver	INFO	geckodriver 0.18.0
> 1503317595901	geckodriver	INFO	Listening on 127.0.0.1:7726
> 1503317596108	geckodriver::marionette	INFO	Starting browser C:\firefox\firefox.exe with args ["-marionette"]
> 1503317600971	Marionette	INFO	Listening on port 7729
> 1503317601223	Marionette	WARN	TLS certificate errors will be ignored for this session
> 1503317604044	Marionette	INFO	New connections will no longer be accepted
> Finished

When the Jenkins job fails, it will plot:

> 1503317485417	geckodriver	INFO	geckodriver 0.18.0
> 1503317485434	geckodriver	INFO	Listening on 127.0.0.1:7681
> 1503317486041	geckodriver::marionette	INFO	Starting browser C:\firefox\firefox.exe with args ["-marionette"]
> 1503317487336	addons.manager	DEBUG	Application has been upgraded
> 1503317487432	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
> 1503317487437	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
> 1503317487447	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
> 1503317487453	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
> 1503317487455	addons.manager	DEBUG	Starting provider: XPIProvider
> 1503317487456	addons.xpi	DEBUG	startup
> 1503317487458	addons.xpi	INFO	Mapping fxdriver@googlecode.com to C:\Users\user123\AppData\Local\Temp\2\rust_mozprofile.7Som4a6hwNz6\extensions\fxdriver@googlecode.com
> 1503317487459	addons.xpi	INFO	Removing all system add-on upgrades.
> 1503317487460	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
> 1503317487462	addons.xpi	INFO	Mapping aushelper@mozilla.org to C:\firefox\browser\features\aushelper@mozilla.org.xpi
> 1503317487463	addons.xpi	INFO	Mapping e10srollout@mozilla.org to C:\firefox\browser\features\e10srollout@mozilla.org.xpi
> 1503317487464	addons.xpi	INFO	Mapping firefox@getpocket.com to C:\firefox\browser\features\firefox@getpocket.com.xpi
> 1503317487465	addons.xpi	INFO	Mapping screenshots@mozilla.org to C:\firefox\browser\features\screenshots@mozilla.org.xpi
> 1503317487465	addons.xpi	INFO	Mapping webcompat@mozilla.org to C:\firefox\browser\features\webcompat@mozilla.org.xpi
> 1503317487467	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
> 1503317487469	addons.xpi	DEBUG	checkForChanges
> 1503317487469	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
> 1503317487471	addons.xpi	DEBUG	Loaded add-on state from prefs: {}
> 1503317487472	addons.xpi	DEBUG	New add-on fxdriver@googlecode.com in app-profile
> 1503317487474	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
> 1503317487484	addons.xpi	DEBUG	New add-on aushelper@mozilla.org in app-system-defaults
> 1503317487485	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
> 1503317487488	addons.xpi	DEBUG	New add-on e10srollout@mozilla.org in app-system-defaults
> 1503317487489	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
> 1503317487490	addons.xpi	DEBUG	New add-on firefox@getpocket.com in app-system-defaults
> 1503317487491	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
> 1503317487492	addons.xpi	DEBUG	New add-on screenshots@mozilla.org in app-system-defaults
> 1503317487493	addons.xpi	DEBUG	getModTime: Recursive scan of screenshots@mozilla.org
> 1503317487494	addons.xpi	DEBUG	New add-on webcompat@mozilla.org in app-system-defaults
> 1503317487495	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
> 1503317487496	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
> 1503317487497	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
> 1503317487498	addons.xpi	DEBUG	getInstallState changed: true, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\user123\\AppData\\Local\\Temp\\2\\rust_mozprofile.7Som4a6hwNz6\\extensions\\fxdriver@googlecode.com","st":1503317486034,"mt":1503317485982}},"app-system-defaults":{"aushelper@mozilla.org":{"d":"C:\\firefox\\browser\\features\\aushelper@mozilla.org.xpi","st":1502797203484},"e10srollout@mozilla.org":{"d":"C:\\firefox\\browser\\features\\e10srollout@mozilla.org.xpi","st":1502797203501},"firefox@getpocket.com":{"d":"C:\\firefox\\browser\\features\\firefox@getpocket.com.xpi","st":1502797203668},"screenshots@mozilla.org":{"d":"C:\\firefox\\browser\\features\\screenshots@mozilla.org.xpi","st":1502797203692},"webcompat@mozilla.org":{"d":"C:\\firefox\\browser\\features\\webcompat@mozilla.org.xpi","st":1502797203712}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","st":1502797203443}}}
> 1503317487518	addons.xpi-utils	DEBUG	Opening XPI database C:\Users\user123\AppData\Local\Temp\2\rust_mozprofile.7Som4a6hwNz6\extensions.json
> 1503317487521	addons.xpi-utils	DEBUG	New add-on fxdriver@googlecode.com installed in app-profile
> *** Blocklist::_loadBlocklistFromFile: blocklist is disabled
> 1503317487567	DeferredSave.extensions.json	DEBUG	Save changes
> 1503317487569	addons.xpi-utils	DEBUG	New add-on aushelper@mozilla.org installed in app-system-defaults
> 1503317487578	DeferredSave.extensions.json	DEBUG	Starting timer
> 1503317487584	DeferredSave.extensions.json	DEBUG	Save changes
> 1503317487585	addons.xpi-utils	DEBUG	New add-on e10srollout@mozilla.org installed in app-system-defaults
> 1503317487599	DeferredSave.extensions.json	DEBUG	Save changes
> 1503317487602	addons.xpi-utils	DEBUG	New add-on firefox@getpocket.com installed in app-system-defaults
> 1503317487620	DeferredSave.extensions.json	DEBUG	Save changes
> 1503317487620	addons.xpi-utils	DEBUG	New add-on screenshots@mozilla.org installed in app-system-defaults
> 1503317487642	DeferredSave.extensions.json	DEBUG	Starting write
> 1503317487727	DeferredSave.extensions.json	DEBUG	Save changes
> 1503317487728	DeferredSave.extensions.json	DEBUG	Data changed while write in progress
> 1503317487728	addons.xpi-utils	DEBUG	New add-on webcompat@mozilla.org installed in app-system-defaults
> 1503317487741	DeferredSave.extensions.json	DEBUG	Save changes
> 1503317487743	addons.xpi-utils	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
> 1503317487752	DeferredSave.extensions.json	DEBUG	Save changes
> 1503317487754	addons.manager	DEBUG	Registering startup change 'installed' for fxdriver@googlecode.com
> 1503317487755	addons.xpi-utils	DEBUG	Make addon app-profile:fxdriver@googlecode.com visible
> 1503317487764	addons.xpi	DEBUG	Add-on fxdriver@googlecode.com blocks e10s rollout.
> 1503317487765	DeferredSave.extensions.json	DEBUG	Save changes
> 1503317487765	addons.manager	DEBUG	Registering startup change 'installed' for aushelper@mozilla.org
> 1503317487787	addons.xpi	DEBUG	Loading bootstrap scope from C:\firefox\browser\features\aushelper@mozilla.org.xpi
> 1503317487800	addons.xpi	DEBUG	Calling bootstrap method install on aushelper@mozilla.org version 2.0
> 1503317487800	addons.xpi-utils	DEBUG	Make addon app-system-defaults:aushelper@mozilla.org visible
> 1503317487801	addons.xpi	DEBUG	Add-on fxdriver@googlecode.com blocks e10s rollout.
> 1503317487801	DeferredSave.extensions.json	DEBUG	Save changes
> 1503317487802	addons.manager	DEBUG	Registering startup change 'installed' for e10srollout@mozilla.org
> 1503317487803	addons.xpi	DEBUG	Loading bootstrap scope from C:\firefox\browser\features\e10srollout@mozilla.org.xpi
> 1503317487809	addons.xpi	DEBUG	Calling bootstrap method install on e10srollout@mozilla.org version 1.50
> 1503317487811	addons.xpi	DEBUG	Add-on fxdriver@googlecode.com blocks e10s rollout.
> 1503317487811	addons.xpi	DEBUG	Add-on fxdriver@googlecode.com blocks e10s rollout.
> 1503317487813	addons.xpi-utils	DEBUG	Make addon app-system-defaults:e10srollout@mozilla.org visible
> 1503317487814	addons.xpi	DEBUG	Add-on fxdriver@googlecode.com blocks e10s rollout.
> 1503317487815	DeferredSave.extensions.json	DEBUG	Save changes
> 1503317487815	addons.manager	DEBUG	Registering startup change 'installed' for firefox@getpocket.com
> 1503317487817	addons.xpi	DEBUG	Loading bootstrap scope from C:\firefox\browser\features\firefox@getpocket.com.xpi
> 1503317487826	addons.xpi	DEBUG	Calling bootstrap method install on firefox@getpocket.com version 1.0.5
> 1503317487826	addons.xpi-utils	DEBUG	Make addon app-system-defaults:firefox@getpocket.com visible
> 1503317487828	addons.xpi	DEBUG	Add-on fxdriver@googlecode.com blocks e10s rollout.
> 1503317487828	DeferredSave.extensions.json	DEBUG	Save changes
> 1503317487829	addons.manager	DEBUG	Registering startup change 'installed' for screenshots@mozilla.org
> 1503317487830	addons.xpi	DEBUG	Loading bootstrap scope from C:\firefox\browser\features\screenshots@mozilla.org.xpi
> 1503317487836	addons.xpi	DEBUG	Calling bootstrap method install on screenshots@mozilla.org version 6.6.0
> 1503317487836	addons.xpi-utils	DEBUG	Make addon app-system-defaults:screenshots@mozilla.org visible
> 1503317487837	addons.xpi	DEBUG	Add-on fxdriver@googlecode.com blocks e10s rollout.
> 1503317487838	DeferredSave.extensions.json	DEBUG	Save changes
> 1503317487838	addons.manager	DEBUG	Registering startup change 'installed' for webcompat@mozilla.org
> 1503317487839	addons.xpi	DEBUG	Loading bootstrap scope from C:\firefox\browser\features\webcompat@mozilla.org.xpi
> 1503317487844	addons.xpi	DEBUG	Calling bootstrap method install on webcompat@mozilla.org version 1.1
> 1503317487845	addons.xpi-utils	DEBUG	Make addon app-system-defaults:webcompat@mozilla.org visible
> 1503317487845	addons.xpi	DEBUG	Add-on fxdriver@googlecode.com blocks e10s rollout.
> 1503317487846	DeferredSave.extensions.json	DEBUG	Save changes
> 1503317487846	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
> 1503317487847	addons.xpi	DEBUG	Add-on fxdriver@googlecode.com blocks e10s rollout.
> 1503317487847	DeferredSave.extensions.json	DEBUG	Save changes
> 1503317487848	addons.xpi	DEBUG	Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"{13414e73-c6f0-4171-8ef2-df7c49f27703}","location":"app-profile","version":"3.5.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Users\\user123\\AppData\\Local\\Temp\\2\\rust_mozprofile.7Som4a6hwNz6\\extensions\\fxdriver@googlecode.com","installDate":1503317486034,"updateDate":1503317486034,"applyBackgroundUpdates":1,"bootstrap":false,"skinnable":false,"size":3279538,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"48.0"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":null},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
> 1503317487849	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
> 1503317487857	addons.xpi	DEBUG	Updating XPIState for {"id":"aushelper@mozilla.org","syncGUID":"{57a80c50-da64-4b37-b9f0-cc3ec331a689}","location":"app-system-defaults","version":"2.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Application Update Service Helper","description":"Sets value(s) in the update url based on custom checks.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\firefox\\browser\\features\\aushelper@mozilla.org.xpi","installDate":1502797203484,"updateDate":1502797203484,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":8486,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
> 1503317487857	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
> 1503317487859	addons.xpi	DEBUG	Updating XPIState for {"id":"e10srollout@mozilla.org","syncGUID":"{2d872e19-f6a6-4727-beb8-e158861fa8a8}","location":"app-system-defaults","version":"1.50","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Multi-process staged rollout","description":"Staged rollout of Firefox multi-process feature.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\firefox\\browser\\features\\e10srollout@mozilla.org.xpi","installDate":1502797203501,"updateDate":1502797203501,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":12517,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
> 1503317487859	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
> 1503317487860	addons.xpi	DEBUG	Updating XPIState for {"id":"firefox@getpocket.com","syncGUID":"{c51005eb-f577-48fe-952f-6ad56e5bc491}","location":"app-system-defaults","version":"1.0.5","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Pocket","description":"When you find something you want to view later, put it in Pocket.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\firefox\\browser\\features\\firefox@getpocket.com.xpi","installDate":1502797203668,"updateDate":1502797203668,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":913904,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
> 1503317487861	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
> 1503317487864	addons.xpi	DEBUG	Updating XPIState for {"id":"screenshots@mozilla.org","syncGUID":"{d104387a-491a-47ee-9bbc-930a832a63ce}","location":"app-system-defaults","version":"6.6.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox Screenshots","description":null,"creator":null,"homepageURL":"https://pageshot.net/"},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\firefox\\browser\\features\\screenshots@mozilla.org.xpi","installDate":1502797203692,"updateDate":1502797203692,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":716271,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"51.0a1","maxVersion":"*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
> 1503317487866	addons.xpi	DEBUG	getModTime: Recursive scan of screenshots@mozilla.org
> 1503317487867	addons.xpi	DEBUG	Updating XPIState for {"id":"webcompat@mozilla.org","syncGUID":"{1d3fc0f2-b917-451d-bbee-91d811785d4e}","location":"app-system-defaults","version":"1.1","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Web Compat","description":"Urgent post-release fixes for web compatibility.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\firefox\\browser\\features\\webcompat@mozilla.org.xpi","installDate":1502797203712,"updateDate":1502797203712,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":9004,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
> 1503317487867	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
> 1503317487869	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"{0224f9e9-385a-4f46-8c8f-0acf28a88c65}","location":"app-global","version":"54.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":"chrome://browser/content/default-theme-icon.svg","icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1502797203443,"updateDate":1502797203443,"applyBackgroundUpdates":1,"skinnable":true,"size":8201,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0","maxVersion":"54.0"}],"targetPlatforms":[],"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"userPermissions":null}
> 1503317487870	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
> 1503317487872	addons.xpi	DEBUG	Add-on fxdriver@googlecode.com blocks e10s rollout.
> 1503317487873	DeferredSave.extensions.json	DEBUG	Save changes
> 1503317487873	addons.xpi	DEBUG	Updating database with changes to installed add-ons
> 1503317487873	addons.xpi-utils	DEBUG	Updating add-on states
> 1503317487876	addons.xpi-utils	DEBUG	Writing add-ons list
> 1503317487882	addons.xpi	DEBUG	Registering manifest for C:\firefox\browser\features\aushelper@mozilla.org.xpi
> 1503317487883	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 2.0
> 1503317487888	addons.xpi	DEBUG	Registering manifest for C:\firefox\browser\features\e10srollout@mozilla.org.xpi
> 1503317487889	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.50
> 1503317487891	addons.xpi	DEBUG	Registering manifest for C:\firefox\browser\features\firefox@getpocket.com.xpi
> 1503317487893	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
> 1503317487896	addons.xpi	DEBUG	Registering manifest for C:\firefox\browser\features\screenshots@mozilla.org.xpi
> 1503317487896	addons.xpi	DEBUG	Calling bootstrap method startup on screenshots@mozilla.org version 6.6.0
> 1503317487898	addons.xpi	DEBUG	Registering manifest for C:\firefox\browser\features\webcompat@mozilla.org.xpi
> 1503317487899	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.1
> 1503317487910	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
> 1503317487911	addons.manager	DEBUG	Provider finished startup: XPIProvider
> 1503317487911	addons.manager	DEBUG	Starting provider: LightweightThemeManager
> 1503317487911	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
> 1503317487912	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
> 1503317487913	addons.manager	DEBUG	Starting provider: GMPProvider
> 1503317487925	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
> 1503317487926	addons.manager	DEBUG	Provider finished startup: GMPProvider
> 1503317487926	addons.manager	DEBUG	Starting provider: PluginProvider
> 1503317487927	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
> 1503317487928	addons.manager	DEBUG	Provider finished startup: PluginProvider
> 1503317487929	addons.manager	DEBUG	Completed startup sequence
> 1503317490442	addons.manager	DEBUG	Starting provider: <unnamed-provider>
> 1503317490443	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
> 1503317490444	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
> 1503317490574	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
> 1503317490575	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
> 1503317490576	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
> 1503317491439	DeferredSave.extensions.json	DEBUG	Write succeeded
> 1503317491440	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
> 1503317491441	DeferredSave.extensions.json	DEBUG	Starting timer
> 1503317491471	DeferredSave.extensions.json	DEBUG	Starting write
> 1503317491504	DeferredSave.extensions.json	DEBUG	Write succeeded
> 1503317495585	Marionette	INFO	Listening on port 7684
> 1503317495933	Marionette	WARN	TLS certificate errors will be ignored for this session
> 1503317496048	Marionette	DEBUG	loaded listener.js
> 1503317496189	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
> 1503317496985	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
> 1503317496986	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
> 1503317497791	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.google.co.il/?gfe_rd=cr&ei=-M2aWZO8FKiP8QeF8LmwBQ&gws_rd=ssl"
> 1503317498472	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "2147483656"
> 1503317498623	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.google.co.il/?gfe_rd=cr&ei=-M2aWZO8FKiP8QeF8LmwBQ&gws_rd=ssl"
> 1503317498683	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.google.co.il/?gfe_rd=cr&ei=-M2aWZO8FKiP8QeF8LmwBQ&gws_rd=ssl"
> 1503317498925	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.google.co.il/?gfe_rd=cr&ei=-M2aWZO8FKiP8QeF8LmwBQ&gws_rd=ssl"
> 1503317498973	Marionette	INFO	New connections will no longer be accepted
> 1503317498999	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 1.1
> 1503317499002	addons.xpi	DEBUG	Calling bootstrap method shutdown on screenshots@mozilla.org version 6.6.0
> 1503317499004	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.5
> 1503317499009	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.50
> 1503317499012	addons.xpi	DEBUG	Calling bootstrap method shutdown on aushelper@mozilla.org version 2.0

Windows event viewer error:

Faulting application name: firefox.exe, version: 54.0.0.6368, time stamp: 0x5939985d
Faulting module name: xul.dll, version: 54.0.0.6368, time stamp: 0x59399963
Exception code: 0x80000003
Fault offset: 0x0035bf6c
Faulting process id: 0x118c
Faulting application start time: 0x01d31b188ebbff35
Faulting application path: C:\firefox\firefox.exe
Faulting module path: C:\firefox\xul.dll
Report Id: cfcf75ce-870b-11e7-8552-a610449ff495

Workaround for the issue: set "browser.tabs.remote.autostart.2 = false":
```
          var firefoxProfile = new FirefoxProfile();
          firefoxProfile.SetPreference("browser.tabs.remote.autostart.2", false);
```

**Comment by barancev** [comment] 2017-09-05 11:38
Duplicate of https://github.com/mozilla/geckodriver/issues/650
See also https://github.com/mozilla/geckodriver/issues/639#issuecomment-326109362

**Closed by barancev** 2017-09-05 11:38 UTC
Labels: D-marionette
