### ISSUE TITLE
[🐛 Bug]: drag_and_drop doesn't work with SortableJS

### ISSUE THREAD

**Issue by yacov-ma** [SeleniumHQ/selenium#12525] opened 2023-08-09 18:00 UTC
### What happened?

I'm trying to use :
ActionChains(self.driver).drag_and_drop(source_element, target_element).pause(5).perform()
but the self.release(target) is released on the wrong element.
issue start when we change the front to use [SortableJS](https://github.com/SortableJS/Sortable) lib.
any suggestion on how to handle it?
I saw https://github.com/SortableJS/Sortable/issues/563
and i wonder if it's not support?

### How can we reproduce the issue?

```shell
on app that use SortableJS
make sure locator is on the right elements.

than run :
ActionChains(self.driver).drag_and_drop(source_element, target_element).pause(5).perform()
```

### Relevant log output

```shell
none
```

### Operating System

mac ventura v 13.5

### Selenium version

4.11.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 115.0.5790.170

### What are the browser driver(s) and version(s) where you see this issue?

chrome driver 114.0.5735.16

**Comment by titusfortner** [comment] 2023-08-09 18:53
Sorry, this still isn't working in any of the drivers.

Duplicate of #10601

**Closed as completed by titusfortner** 2023-08-09 18:53 UTC
Labels: I-defect, A-needs-triaging
