### ISSUE TITLE
Webdriver Cannot Resolve localhost when using IPV6 on Alpine Linux

### ISSUE THREAD

**Issue by ecliptik** [SeleniumHQ/selenium#1767] opened 2016-03-08 20:01 UTC
## Expected Behavior -

Selenium webdriver on Alpine Linux should resolve localhost when using ipv6 address
## Actual Behavior -

Selenium webdriver gives error the following error when `/etc/resolv.conf` containers a ipv6 address for localhost:
- `/etc/hosts`

```
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
- Selenium Error

```
     SocketError:
       getnameinfo: Unrecognized address family or invalid length
     # ./vendor/bundle/ruby/2.2.0/gems/selenium-webdriver-2.52.0/lib/selenium/webdriver/common/platform.rb:188:in `getaddrinfo'
     # ./vendor/bundle/ruby/2.2.0/gems/selenium-webdriver-2.52.0/lib/selenium/webdriver/common/platform.rb:188:in `localhost'
     # ./vendor/bundle/ruby/2.2.0/gems/selenium-webdriver-2.52.0/lib/selenium/webdriver/phantomjs/service.rb:50:in `initialize'
     # ./vendor/bundle/ruby/2.2.0/gems/selenium-webdriver-2.52.0/lib/selenium/webdriver/phantomjs/service.rb:46:in `new'
     # ./vendor/bundle/ruby/2.2.0/gems/selenium-webdriver-2.52.0/lib/selenium/webdriver/phantomjs/service.rb:46:in `default_service'
     # ./vendor/bundle/ruby/2.2.0/gems/selenium-webdriver-2.52.0/lib/selenium/webdriver/phantomjs/bridge.rb:38:in `initialize'
     # ./vendor/bundle/ruby/2.2.0/gems/selenium-webdriver-2.52.0/lib/selenium/webdriver/common/driver.rb:72:in `new'
     # ./vendor/bundle/ruby/2.2.0/gems/selenium-webdriver-2.52.0/lib/selenium/webdriver/common/driver.rb:72:in `for'
     # ./vendor/bundle/ruby/2.2.0/gems/selenium-webdriver-2.52.0/lib/selenium/webdriver.rb:86:in `for'
```
## Steps to reproduce -
- Start an interactive Alpine Linux container on a system with IPV6 configured

`docker run -it --rm alpine /bin/sh`
- Verify `/etc/hosts` has a ipv6 local address for localhost

```
cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2      bc0435cdfe24
```
- Install ruby

```
apk --no-cache add ruby ruby-irb
```
- Run an interactive ruby shell and run the code from https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/common/platform.rb#L196

```
/ # irb
irb(main):001:0> require 'socket'
=> true
irb(main):002:0> Socket.getaddrinfo "localhost", 80, Socket::AF_INET, Socket::SOCK_STREAM
SocketError: getnameinfo: Unrecognized address family or invalid length
        from (irb):2:in `getaddrinfo'
        from (irb):2
        from /usr/bin/irb:11:in `<main>'
irb(main):003:0>
```

This error message comes from musl libc which Alpine Linux uses (https://github.com/BlankOn/musl/blob/master/src/network/gai_strerror.c)

Redis had a similar issue at one point and was updated to account for both ipv4 and ipv6 addresses: https://github.com/redis/redis-rb/issues/393

**Comment by p0deje** [comment] 2016-12-23 09:26
Sorry for getting to this for such a long time.

I can't reproduce the bug using Docker image for Alpine, here is what I get:

```
# cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	7f669fdd938a

# irb
irb(main):001:0> require 'socket'
=> true
irb(main):002:0> Socket.getaddrinfo "localhost", 80, Socket::AF_INET, Socket::SOCK_STREAM
=> [["AF_INET", 80, "localhost", "127.0.0.1", 2, 1, 6]]
```

I guess we could have just changed `Socket::AF_INET` to `Socket::AF_UNSPEC` even though I have no idea what consequences it might actually have. We'll need to thoroughly test it on all the OSes.

**Comment by nirvdrum** [comment] 2016-12-23 14:47
These sorts of bug reports should probably indicate an image tag other than "latest" to aid in reproducibility. In the original report, Ruby 2.2.0 is being used, but as of today, those steps install Ruby 2.3.1p112. Undoubtedly, other things have changed as well. It looks to me like this was fixed upstream in one of the various projects.

**Comment by p0deje** [comment] 2016-12-26 07:37
@nirvdrum Thanks for explanation!

I'm going to close this for now since it's working on latest Alpine + Ruby. Please, re-open if necessary.

**Closed by p0deje** 2016-12-26 07:37 UTC
Labels: C-rb
