### ISSUE TITLE
selenium 2.53 and firefox 47.0.1: WebDriverError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms

### ISSUE THREAD

**Issue by jahnavi310** [SeleniumHQ/selenium#2868] opened 2016-10-03 18:45 UTC
I just upgraded to selenium 2.53 a few days ago and everything was working great until today when FF decided to bomb up and gave the following stack trace:

```
[firefox #01-0]     super(opt_error);
[firefox #01-0]          ^
[firefox #01-0] WebDriverError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
[firefox #01-0] D":"tlyHsFO3o6j1","location":"app-global","version":"47.0.1","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/opt/firefox-47.0.1/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1466731683000,"updateDate":1466731683000,"applyBackgroundUpdates":1,"skinnable":true,"size":5028,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"47.0.1","maxVersion":"47.0.1"}],"targetPlatforms":[],"seen":true}
[firefox #01-0] 1475520048994	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
[firefox #01-0] 1475520048995	DeferredSave.extensions.json	DEBUG	Save changes
[firefox #01-0] 1475520048995	addons.xpi	DEBUG	Updating database with changes to installed add-ons
[firefox #01-0] 1475520048995	addons.xpi-utils	DEBUG	Updating add-on states
[firefox #01-0] 1475520048996	addons.xpi-utils	DEBUG	Writing add-ons list
[firefox #01-0] 1475520048997	addons.xpi	DEBUG	Registering manifest for /opt/firefox-47.0.1/browser/features/e10srollout@mozilla.org.xpi
[firefox #01-0] 1475520048998	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
[firefox #01-0] 1475520048998	addons.xpi	DEBUG	Registering manifest for /opt/firefox-47.0.1/browser/features/firefox@getpocket.com.xpi
[firefox #01-0] 1475520048998	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
[firefox #01-0] 1475520048999	addons.xpi	DEBUG	Registering manifest for /opt/firefox-47.0.1/browser/features/loop@mozilla.org.xpi
[firefox #01-0] 1475520049000	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
[firefox #01-0] 1475520049032	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
[firefox #01-0] 1475520049033	addons.manager	DEBUG	Provider finished startup: XPIProvider
[firefox #01-0] 1475520049033	addons.manager	DEBUG	Starting provider: LightweightThemeManager
[firefox #01-0] 1475520049033	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
[firefox #01-0] 1475520049033	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
[firefox #01-0] 1475520049034	addons.manager	DEBUG	Starting provider: GMPProvider
[firefox #01-0] 1475520049042	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
[firefox #01-0] 1475520049043	addons.manager	DEBUG	Provider finished startup: GMPProvider
[firefox #01-0] 1475520049043	addons.manager	DEBUG	Starting provider: PluginProvider
[firefox #01-0] 1475520049043	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
[firefox #01-0] 1475520049043	addons.manager	DEBUG	Provider finished startup: PluginProvider
[firefox #01-0] 1475520049044	addons.manager	DEBUG	Completed startup sequence
[firefox #01-0] 1475520049491	addons.manager	DEBUG	Starting provider: <unnamed-provider>
[firefox #01-0] 1475520049491	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
[firefox #01-0] 1475520049492	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
[firefox #01-0] 1475520049769	DeferredSave.extensions.json	DEBUG	Write succeeded
[firefox #01-0] 1475520049769	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
[firefox #01-0] 1475520049769	DeferredSave.extensions.json	DEBUG	Starting timer
[firefox #01-0] 1475520049791	DeferredSave.extensions.json	DEBUG	Starting write
[firefox #01-0] 1475520049821	addons.repository	DEBUG	No addons.json found.
[firefox #01-0] 1475520049821	DeferredSave.addons.json	DEBUG	Save changes
[firefox #01-0] 1475520049826	DeferredSave.addons.json	DEBUG	Starting timer
[firefox #01-0] 1475520049859	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
[firefox #01-0] 1475520049859	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
[firefox #01-0] 1475520049860	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
[firefox #01-0] 1475520049873	DeferredSave.extensions.json	DEBUG	Write succeeded
[firefox #01-0] 1475520049920	DeferredSave.addons.json	DEBUG	Starting write
[firefox #01-0] 1475520049981	DeferredSave.addons.json	DEBUG	Write succeeded
```

Anyone having the same issue?

**Comment by lukeis** [comment] 2016-10-03 19:42
this means firefox failed to launch the selenium extension for some reason. Can you describe what's occurring on the machine?

Is the browser launching? If it is, double check the version of it. Check to see if the selenium addon is installed and enabled by going to about:addons
Any other console / browser console log messages in the browser?

**Comment by spiderpug** [comment] 2016-10-04 15:31
We have that problem as well. Going to about:addons shows an error message. Roughly translated into english:

"Some addons could not be verified.
Firefox Webdriver could not be verified for use in Firefox and was disabled."

**Comment by lukeis** [comment] 2016-10-04 17:51
Selenium's FirefoxDriver can no longer work in Firefox 48+ due to extension signing. This is a duplicate of #2750

**Closed by lukeis** 2016-10-04 17:51 UTC
Labels: D-firefox
