### ISSUE TITLE
selenium-webdriver 2.48.2 + protractor + firefox 38...41 = not working

### ISSUE THREAD

**Issue by dnozay** [SeleniumHQ/selenium#1416] opened 2015-12-24 04:49 UTC
see https://github.com/angular/protractor/issues/2784.

```
D:\...\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:108
  var template = new Error(this.message);
                 ^
UnknownError: Permission denied to access property "toString"
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'NAGWS72', ip: '192.168.210.23', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_79'
Driver info: driver.version: unknown
    at new bot.Error (D:\...\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:108:18)
    at Object.bot.response.checkResponse (D:\...\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\response.js:109:9)
    at D:\...\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:379:20
    at [object Object].promise.Promise.goog.defineClass.invokeCallback_ (D:/.../node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1337:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (D:/.../node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (D:/.../node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2758:21)
    at goog.async.run.processWorkQueue (D:\...\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:124:15)
    at process._tickCallback (node.js:366:9)
From: Task: <anonymous>
    at [object Object].pollCondition [as _onTimeout] (D:/.../node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2233:16)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: <anonymous wait>
    at [object Object].promise.ControlFlow.goog.defineClass.getSchedule.indent.wait (D:/.../node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2226:17)
    at [object Object].webdriver.WebDriver.wait (D:\...\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:716:21)
    at [object Object].to.(anonymous function) [as wait] (D:\...\node_modules\grunt-protractor-runner\node_modules\protractor\lib\protractor.js:65:25)
    at global.doLogin (D:\...\nisXplorerConfig.js:44:21)
    at exports.config.onPrepare (D:\...\nisXplorerConfig.js:79:9)
    at D:\...\node_modules\grunt-protractor-runner\node_modules\protractor\lib\util.js:54:41
    at Function.promise (D:\...\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\q\q.js:650:9)
    at Object.exports.runFilenameOrFn_ (D:\...\node_modules\grunt-protractor-runner\node_modules\protractor\lib\util.js:44:12)
    at [object Object].Runner.runTestPreparer (D:\...\node_modules\grunt-protractor-runner\node_modules\protractor\lib\runner.js:76:17)
    at Object.exports.run (D:\...\node_modules\grunt-protractor-runner\node_modules\protractor\lib\frameworks\jasmine.js:89:17)
```

could be related to this commit: https://github.com/SeleniumHQ/selenium/commit/0fa587daec4605adc688e1f736fb9564b37fd044 but that's just a gut feeling.

**Comment by dnozay** [comment] 2015-12-24 04:50
maybe @jleyba  has some ideas what is going on.

**Comment by jleyba** [comment] 2015-12-24 16:09
0fa587daec4605adc688e1f736fb9564b37fd044 isn't in 2.48.2, so it can't be that. It looks like the error is coming from the actual FirefoxDriver implementation. You should be able to verify by seeing what's going across the wire:

```
var logging = require('selenium-webdriver').logging;

logging.installConsoleHandler();
logging.getLogger('webdriver.http').setLevel(logging.Level.ALL);
```

**Comment by jleyba** [comment] 2015-12-24 16:11
By the way, you can enable logging across all components by fetching the root logger (`logging.getLogger()`).  I just wouldn't do it unless you want to be spammed by the promise manager

**Comment by barancev** [comment] 2015-12-25 20:00
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by dnozay** [comment] 2015-12-27 06:09
Please see linked protractor issue for reproducible testcase. Thank you

**Comment by barancev** [comment] 2015-12-27 09:44
Please provide a pure selenium reproduction case. Or at least a pure protractor reproduction case (a scenario file and a conf.js file). Sorry, I couldn't extract this info from the linked issue.

**Comment by NisStrom** [comment] 2016-01-05 15:21
@barancev 

Just download the example from here: https://github.com/CarmenPopoviciu/angular2-go-protractor
Then run the website and execute the protractor against firefox.
Note that problem occurs only if angular2 is on the website.

**Comment by barancev** [comment] 2016-01-05 18:02
OK, I've reproduced the issue, and got more details on the exception:

WebDriverException: Message: Permission denied to access property "toString"
Stacktrace:
    at patchEventTargetMethods/obj.addEventListener (http://127.0.0.1:8080/node_
modules/angular2/bundles/angular2.dev.js:1068)

So it seems to be an Angular issue, it should catch (and ignore?) the exception.

**Comment by NisStrom** [comment] 2016-01-12 12:36
should i add this issue now to angular 2 or what is the current state of it?

**Comment by barancev** [comment] 2016-01-12 12:47
I'm not completely sure that it's an Angular issue, and I'd like somebody more proficient in JavaScript confirm/refect my hypotesis.

**Comment by jleyba** [comment] 2016-01-12 17:37
I ran the tests with logging enabled. This has nothing to do with the WebDriverJS:

```
[2016-01-12T17:35:29Z][FINER][webdriver.http.Executor] >>>
POST /session/40139bbd-6585-4869-9125-7fe498db884e/elements HTTP/1.1
Accept: application/json; charset=utf-8

{"using":"tag name","value":"input"}
[2016-01-12T17:35:29Z][FINER][webdriver.http.Executor] <<<
HTTP/1.1 500
content-type: application/json; charset=UTF-8
connection: close
content-length: 351
server: httpd.js
date: Tue, 12 Jan 2016 17:35:29 GMT

{"name":"findElements","sessionId":"40139bbd-6585-4869-9125-7fe498db884e","status":13,"value":{"message":"Permission denied to access property \"toString\"","stackTrace":[{"methodName":"patchEventTargetMethods/obj.addEventListener","fileName":"http://localhost:8080/node_modules/angular2/bundles/angular2.dev.js","lineNumber":1068,"columnNumber":1}]}}
```

**Comment by jleyba** [comment] 2016-01-12 17:48
Angular 2 is patching EventTarget.prototype, so they are responsible for any bugs caused by their changes.

This is not a Selenium issue, closing the bug.

**Closed by jleyba** 2016-01-12 17:48 UTC
Labels: D-firefox, I-needs investigation

**Comment by dnozay** [comment] 2016-01-22 05:18
Thanks a lot for the root-cause!
