### ISSUE TITLE
[🐛 Bug]: [py] webdriver.get() does not return after pdf download

### ISSUE THREAD

**Issue by luketudge** [SeleniumHQ/selenium#13127] opened 2023-11-09 14:21 UTC
### What happened?

A call to `.get()` for a pdf download url never returns (and eventually raises `TimeoutException`). This occurs despite the fact that the HTTP request succeeds and the complete file content is downloaded correctly. Instead of returning, the `get()` call continues to run long after the file has finished downloading.

A few things I have been able to check:

* Not a general issue with `get()`. Fetching a regular html page with the same driver configuration returns normally.
* Does not seem to be specific to certain pdfs nor dependent on pdf size or content. Occurs even for very small pdfs.
* Not an issue with the request itself timing out. Logs show the request completes, and the pdf content downloads fully and is not truncated or corrupted.

### How can we reproduce the issue?

```shell
import logging
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

logger = logging.getLogger('selenium')
logger.setLevel(logging.DEBUG)
handler = logging.FileHandler('log.log')
logger.addHandler(handler)

options = Options()
options.add_argument('--headless')
options.set_preference(
    'browser.download.folderList',
    2
)
options.set_preference(
    'browser.download.dir',
    '/home/lt/Downloads'
)
options.set_preference(
    'pdfjs.disabled',  # prevents firefox from displaying pdfs inline
    True
)

driver = webdriver.Firefox(options=options)
driver.get('https://africau.edu/images/default/sample.pdf')  # a very small pdf
driver.close()  # this line is never reached
```

### Relevant log output

```shell
# file 'log.log':

Selenium Manager binary found at: /home/lt/Downloads/.venv/lib/python3.10/site-packages/selenium/webdriver/common/linux/selenium-manager
Executing process: /home/lt/Downloads/.venv/lib/python3.10/site-packages/selenium/webdriver/common/linux/selenium-manager --browser firefox --debug --output json
Found geckodriver 0.33.0 in PATH: /usr/bin/geckodriver
firefox detected at /usr/bin/firefox
Running command: /usr/bin/firefox -v
Output: "Mozilla Firefox 119.0.1"
Detected browser: firefox 119.0.1
Required driver: geckodriver 0.33.0
Driver path: /usr/bin/geckodriver
Browser path: /usr/bin/firefox
Using driver at: /usr/bin/geckodriver
Started executable: `/usr/bin/geckodriver` in a child process with pid: 15672
POST http://localhost:56903/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "firefox", "acceptInsecureCerts": true, "moz:debuggerAddress": true, "pageLoadStrategy": "normal", "browserVersion": null, "moz:firefoxOptions": {"binary": "/usr/bin/firefox", "prefs": {"browser.download.folderList": 2, "browser.download.dir": "/home/lt/Downloads", "pdfjs.disabled": true}, "args": ["--headless"]}}}}
Remote response: status=200 | data={"value":{"sessionId":"32760822-e744-44bb-a9d1-adf107406c8a","capabilities":{"browserName":"firefox","browserVersion":"119.0.1","platformName":"linux","acceptInsecureCerts":true,"pageLoadStrategy":"normal","setWindowRect":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"strictFileInteractability":false,"unhandledPromptBehavior":"dismiss and notify","moz:accessibilityChecks":false,"moz:buildID":"20231106151204","moz:debuggerAddress":"127.0.0.1:54377","moz:headless":true,"moz:platformVersion":"6.2.0-36-generic","moz:processID":15675,"moz:profile":"/tmp/rust_mozprofileaUufud","moz:shutdownTimeout":60000,"moz:webdriverClick":true,"moz:windowless":false,"proxy":{},"moz:geckodriverVersion":"0.33.0"}}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '720', 'date': 'Thu, 09 Nov 2023 14:14:08 GMT'})
Finished Request
POST http://localhost:56903/session/32760822-e744-44bb-a9d1-adf107406c8a/url {"url": "https://africau.edu/images/default/sample.pdf"}
Remote response: status=500 | data={"value":{"error":"timeout","message":"Navigation timed out after 300000 ms","stacktrace":"RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:189:5\nTimeoutError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:691:5\nbail@chrome://remote/content/marionette/sync.sys.mjs:211:19\n"}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '377', 'date': 'Thu, 09 Nov 2023 14:14:10 GMT'})
Finished Request


# console:

Traceback (most recent call last):
  File "/home/lt/Downloads/main.py", line 27, in <module>
    driver.get('https://africau.edu/images/default/sample.pdf')  # a very small pdf
  File "/home/lt/Downloads/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/home/lt/Downloads/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/lt/Downloads/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Navigation timed out after 300000 ms
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:189:5
TimeoutError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:691:5
bail@chrome://remote/content/marionette/sync.sys.mjs:211:19
```

### Operating System

Ubuntu 22.04

### Selenium version

Python 4.15.2

### What are the browser(s) and version(s) where you see this issue?

Firefox 119.0.1

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.33.0

**Comment by titusfortner** [comment] 2023-11-09 17:07
Does this code work for Chrome? It seems most likely to be a geckodriver issue.

**Comment by luketudge** [comment] 2023-11-09 17:11
> Does this code work for Chrome? It seems most likely to be a geckodriver issue.

Can't get chromedriver to work at all on my system unfortunately, so I'm not sure. I will try to test it somewhere else.

**Comment by luketudge** [comment] 2023-11-22 14:49
Sorry for the delay in getting back with an answer. I haven't been able to reproduce the same behavior with chromedriver (which I also can't make work for pdf downloads, but for different reasons). So it does seem as you suspected that this is a driver-specific issue. I will try to take it up with geckodriver. Thanks for your help.

**Comment by AutomatedTester** [comment] 2023-11-22 14:56
The issue here is that loading a PDF this way would not fire off the relevant page loading events that are required for Selenium to work. I think it working in Chrome is an accident not by design.

Since the way PDFs work in browsers is not standard I would recommend using a HTTP library to download the file and then a PDF library to make sure that it has the relevant things. 

Closing as there is nothing we can do here.

**Closed as completed by AutomatedTester** 2023-11-22 14:56 UTC
Labels: J-awaiting answer, C-py, I-defect, A-needs-triaging
