### ISSUE TITLE
The newest python version has some problem 

### ISSUE THREAD

**Issue by 1a1a11a** [SeleniumHQ/selenium#1830] opened 2016-03-16 15:38 UTC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/phantomjs/webdriver.py", line 50, in __init__
    service_args=service_args, log_path=service_log_path)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/phantomjs/service.py", line 44, in __init__
    if not self._args_contain("--cookies-file="):
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/phantomjs/service.py", line 54, in _args_contain
    return len(filter(lambda x:x.startswith(arg), self.service_args)) > 0
TypeError: object of type 'filter' has no len()

I install the 2.51.1, the bug is not there.

**Comment by AutomatedTester** [comment] 2016-03-16 15:57
duplicate of #1817

**Closed by AutomatedTester** 2016-03-16 15:57 UTC
