### ISSUE TITLE
POST /session/<sessionid>/moveto did not match a known command

### ISSUE THREAD

**Issue by cambiph** [SeleniumHQ/selenium#6809] opened 2019-01-03 11:30 UTC
## To Reproduce

Detailed steps to reproduce the behavior:

1.  Clone https://github.com/cambiph/se-debug.git
2. Perform `npm install`
3. Start the docker containers using `docker-compose up`
4. Run `grunt builddocker`

## Expected behavior

Firefox browser is opened and `www.angular.io`is loaded.
Then, the mouse is moved to the element with classname `card-text-container`

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

See above

## Environment

Latest build from https://hub.docker.com/u/selenium/
Protractor version used is the latest beta which includes the latest selenium JS bindings (4.0.0-alpha1)
More details can be found in the Twitter discussion: https://twitter.com/shs96c/status/1078794260265218048

**Comment by kaiyoma** [comment] 2019-01-04 00:39
I think this is a known issue. I've opened a similar issue in the past against geckodriver and it was deemed a duplicate of #4564.

**Comment by AutomatedTester** [comment] 2021-01-26 11:08
This change is removing the command from `/javascript/node/` and running the tests with `bazel test //javascript/node/selenium-webdriver:tests`

**Comment by diemol** [comment] 2021-04-08 10:42
Closed via #9362

**Closed by diemol** 2021-04-08 10:42 UTC
Labels: C-nodejs
