### ISSUE TITLE
[🐛 Bug]: Selenium/JavaScript: Unexpected error "Unable to execute request: java.net.ConnectException: Connection refused: no further information: localhost/0:0:0:0:0:0:0:1:29892"

### ISSUE THREAD

**Issue by StanislavKharchenko** [SeleniumHQ/selenium#11720] opened 2023-03-01 11:54 UTC
### What happened?

We have floating issue which happens from time to time on attempt to interact with web-element(-s).
Started to reproduce after selenium-webdriver 4.7.X, still reproduced with v.4.8.0.

I see the similar reported under https://github.com/SeleniumHQ/selenium/issues/10471 , but that issue closed.

### How can we reproduce the issue?

```shell
Initial Conditions:
1. Start selenium standalone server 4.7.0 or higher
2. Use selenium-webdriver for JS binding;

Scenario:
1. Read elements from page.

Actual result:
Unexpected error "Unable to execute request: java.net.ConnectException: Connection refused: no further information: localhost/0:0:0:0:0:0:0:1:29892"

This problem is floating, so could happen from time to time, but not on regular base.
```

### Relevant log output

```shell
10:44:20.951 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to execute request: java.net.ConnectException: Connection refused: no further information: localhost/0:0:0:0:0:0:0:1:29892
10:44:20.953 WARN [SeleniumSpanExporter$1.lambda$export$1] - java.io.UncheckedIOException: java.net.ConnectException: Connection refused: no further information: localhost/0:0:0:0:0:0:0:1:29892
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
        at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:99)
        at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
        at org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:92)
        at org.openqa.selenium.grid.node.ProtocolConvertingSession.execute(ProtocolConvertingSession.java:75)
        at org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:127)
        at org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:470)
        at org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)
        at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.grid.node.Node.execute(Node.java:245)
        at org.openqa.selenium.grid.web.CombinedHandler.execute(CombinedHandler.java:59)
        at org.openqa.selenium.grid.web.RoutableHttpClientFactory$1.execute(RoutableHttpClientFactory.java:72)
        at org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:92)
        at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:122)
        at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.grid.router.Router.execute(Router.java:91)
        at org.openqa.selenium.grid.web.CheckOriginHeader.lambda$apply$0(CheckOriginHeader.java:66)
        at org.openqa.selenium.grid.web.CheckContentTypeHeader.lambda$apply$0(CheckContentTypeHeader.java:70)
        at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:270)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
        at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
        at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection refused: no further information: localhost/0:0:0:0:0:0:0:1:29892
        at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
        at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
        at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
        at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/0:0:0:0:0:0:0:1:29892
Caused by: java.net.ConnectException: Connection refused: no further information
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

### Operating System

Windows 10

### Selenium version

4.8.0 Javascript

### What are the browser(s) and version(s) where you see this issue?

Edge 110.0.1587.57

### What are the browser driver(s) and version(s) where you see this issue?

EdgeDriver 110.0.1587.57

### Are you using Selenium Grid?

Selenium grid 4.8.0

**Comment by StanislavKharchenko** [comment] 2023-03-09 19:45
I see that issue more stable reproduced in case if execute javascript code in driver (call driver.execute):
```
Error :  ScriptTimeoutError: Unable to execute request for an existing session: java.net.ConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:27769
[21:35:00]	[Step 5/5]     at Object.throwDecodedError (C:\Teamcity\BuildAgent3\**\node_modules\selenium-webdriver\lib\error.js:524:15)
[21:35:00]	[Step 5/5]     at parseHttpResponse (C:\Teamcity\BuildAgent3\**\node_modules\selenium-webdriver\lib\http.js:587:13)
[21:35:00]	[Step 5/5]     at Executor.execute (C:\Teamcity\BuildAgent3\**\node_modules\selenium-webdriver\lib\http.js:515:28)
[21:35:00]	[Step 5/5]     at runMicrotasks (<anonymous>)
[21:35:00]	[Step 5/5]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[21:35:00]	[Step 5/5]     at WebDriver.execute (C:\Teamcity\BuildAgent3\**\node_modules\selenium-webdriver\lib\webdriver.js:741:17)
```

Is any possible reasons  and/or workaround how to avoid this issue?

**Comment by diemol** [comment] 2023-03-13 10:49
The problem is that it is hard to understand something when we do not have a way to reproduce it. Sorry. Logs are not very useful either.
A connection refused in this case means that the driver is not accepting connections, maybe the driver binary did not start properly. Seems you are running this in a TeamCIty CI, could it be it is overloaded and it cannot start resources properly.

**Comment by StanislavKharchenko** [comment] 2023-03-13 16:27
According to test case, the issue started to reproduce "in the middle" of test execution. So, the driver instance was up and running, but in the some moment, when we execute JS code in the driver - we got this error.
After this error - the test case continue to execution.

I will try to find a more concrete scenario, but this very hard since issue reproduced sporadically.

**Comment by iamxiaojianzheng** [comment] 2023-03-17 00:41
I have also encountered this problem in Java-selenium, but this problem cannot be reproduced 100%, and similar exceptions occasionally occur.

**Comment by iamxiaojianzheng** [comment] 2023-03-17 00:43
> I have also encountered this problem in Java-selenium, but this problem cannot be reproduced 100%, and similar exceptions occasionally occur.

And I have encountered it in different versions, not a specific version.

**Comment by diemol** [comment] 2023-04-18 08:00
I will close this but we can always reopen or triage a new issue when there is a way to reproduce the problem.

**Closed as completed by diemol** 2023-04-18 08:00 UTC
Labels: I-defect, J-issue-template
