### ISSUE TITLE
Selenium 3.5.0-GeckoDriver 0.18.0-Python 3.6.1 : "OSError: [WinError 6] The handle is invalid" is observed while close() is called through Python PyDev (Eclipse) unittest module

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#4505] opened 2017-08-18 15:50 UTC
## Meta - Selenium 3.5.0-GeckoDriver 0.18.0-Python 3.6.1 : "OSError: [WinError 6] The handle is invalid" is observed while close() is called through Python PyDev (Eclipse) unittest module

OS:  Windows 8 Pro, 64 bit

Selenium Version:  3.5.0 (Python 3.6.1)

Selenium Binding: Python 3.6.1

GeckoDriver Version: 0.18.0

Browser:  Firefox

Browser Version:  Firefox 55.0.2 (64-bit)

## Steps to reproduce -
Code Block:

	import unittest
	from selenium import webdriver
	from selenium.webdriver.common.keys import Keys

	binary = r'C:\Program Files\Mozilla Firefox\firefox.exe'

	class PythonOrgSearch(unittest.TestCase):

	    def setUp(self):
		self.driver = webdriver.Firefox(firefox_binary=binary, executable_path=r'C:\Utility\BrowserDrivers\geckodriver.exe')

	    def test_search_in_python_org(self):
		driver = self.driver
		driver.get("http://www.python.org")
		self.assertIn("Python", driver.title)
		elem = driver.find_element_by_name("q")
		elem.send_keys("pycon")
		elem.send_keys(Keys.RETURN)
		assert "No results found." not in driver.page_source

	    def tearDown(self):
		self.driver.close()

	if __name__ == "__main__":
	    unittest.main()

Error Stack Trace:

	Finding files... done.
	Importing test modules ... done.

	----------------------------------------------------------------------
	Ran 1 test in 12.158s

	OK
	Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x03758970>>
	Traceback (most recent call last):
		File "C:\Python\lib\subprocess.py", line 763, in __del__
			self._internal_poll(_deadstate=_maxsize)
		File "C:\Python\lib\subprocess.py", line 1025, in _internal_poll
			if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
	OSError: [WinError 6] The handle is invalid

**Comment by lmtierney** [comment] 2017-09-08 20:04
You shouldn't be using `self.driver.close()` in your teardown, it should be `self.driver.quit()` as `close` only closes the tab/window and not the driver instance.

**Comment by Debanjan-B** [comment] 2017-09-09 11:36
@lmtierney Thanks. 

The steps I mentioned is the minimal code block to reproduce the exact issue. 

My actual project involves opening multiple tabs, iterating over them, closing the browser session and opening new session through the same `webdriver` instance. Hence, `self.driver.quit()` doesn't fits in my usecase.

**Comment by jimevans** [comment] 2017-09-09 12:38
Why do you think you require the same WebDriver instance? What advantage do you think that gives you over reusing the same instance? Additionally, the semantics of `close()` are such that closing the last active window attempts to close the session, so it may be functionally equivalent.

**Comment by Debanjan-B** [comment] 2017-09-09 14:10
Thanks a lot @jimevans  If you have a look at [mozilla/geckodriver/issues/875](https://github.com/mozilla/geckodriver/issues/875) @andreastt @AutomatedTester and @shs96c we did discuss about `webdriver::server` calling the `/shutdown` EndPoint which is neither implemented by gecko team nor present in the [WebDriver Spec](https://w3c.github.io/webdriver/webdriver-spec.html#list-of-endpoints). Hence the conclusion from Simon was **Selenium should be handling this error cleanly** i.e. at Selenium bindings level. Though with `GeckoDriver 0.18.0`/`Mozilla Firefox 55.0.2`/`Java`  the issue still persists but we upgraded to Mozilla Firefox 55.0.3 where Selenium-Java client successfully managed to escape the error simply by logging it. Additionally there was a log as:

    SEVERE: Unable to kill process with PID 5372

So our understanding was invoking `quit()` method is not that clean. Hence we fell back to `close()` to keep the dangling stuffs minimum in terms of system resources.

Please let me know your suggestion.

**Comment by hazardary** [comment] 2018-01-10 16:41
Hi there,
I have read when you use popen in subprocess, you have to have stdin, stderr, and stdout all in there explicitly. See #5316. In my case I have to modify service.py for one Popen call in line 72. I am sure my solution is not good but it may be in the right direction.

**Comment by p0deje** [comment] 2018-01-12 07:23
Duplicate of #5316

**Closed by p0deje** 2018-01-12 07:23 UTC
Labels: C-py
