### ISSUE TITLE
[🐛 Bug]: setWindowRect:true fails when passed to Browser Drivers

### ISSUE THREAD

**Issue by cocchiarocarl** [SeleniumHQ/selenium#13817] opened 2024-04-12 15:02 UTC
### What happened?

When passing in the setWindowRect:true capability to any of the supported Browsers, it fails on all headed Browsers, throwing exception error "invalid" argument: unrecognized capability: setWindowRect". However, it does pass on headless Firefox.

### How can we reproduce the issue?

```shell
Pass in the setWindowRect:true capability when creating the driver:

ThreadLocal<WebDriver> webDriver = new ThreadLocal<>();
ChromeOptions chromeOpts = new ChromeOptions();

chromeOpts.setCapability(setWindowRect, true);
webDriver.set(new ChromeDriver(chromeOpts));
```

### Relevant log output

```shell
"invalid" argument: unrecognized capability: setWindowRect"
```

### Operating System

macOS Sonoma 14.4.1

### Selenium version

4.18.1

### What are the browser(s) and version(s) where you see this issue?

All

### What are the browser driver(s) and version(s) where you see this issue?

All

### Are you using Selenium Grid?

no

**Comment by diemol** [comment] 2024-04-12 15:05
- Duplicate of #12331

**Closed as not planned by diemol** 2024-04-12 15:05 UTC
Labels: I-defect
