### ISSUE TITLE
There was a problem while loading TestCase 

### ISSUE THREAD

**Issue by pavan93** [SeleniumHQ/selenium#4946] opened 2017-10-25 05:19 UTC
![selenium_web_driver](https://user-images.githubusercontent.com/13575020/31981613-1baea5f8-b972-11e7-8508-ebd324730217.png)
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by barancev** [comment] 2017-10-25 05:27
Duplicate of #4406

**Closed by barancev** 2017-10-25 05:27 UTC

**Comment by pavan93** [comment] 2017-10-25 13:52
see my concern is my firefox is upgrading to 55 versoin automatically so need to be in stable 44 version everytime or everyday I can't install latest version so please kindly tell me procedure to stop continuous upgrade of firefox 
thanks
pavan

**Comment by barancev** [comment] 2017-10-25 13:54
https://www.mozilla.org/en-US/firefox/organizations/faq/

**Comment by pavan93** [comment] 2017-10-26 06:19
OK thanks for you support...
Thanks
pavan

**Comment by pavan93** [comment] 2017-10-26 10:12
Thanks for your support
