### ISSUE TITLE
Firefox incorrectly escaping open parens

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#1225] opened 2015-11-05 17:04 UTC
[This was reported in Watir](https://github.com/watir/watir-webdriver/issues/382), but I've verified it as a Firefox Driver issue.

This is what is getting sent to the endpoint
```
-> POST session/788a90a0-ac72-1e43-ad15-9a117a363765/element/%7Bde758e6a-79b8-584d-9644-f6b5932a429e%7D/value
   >>> http://127.0.0.1:7055/hub/session/788a90a0-ac72-1e43-ad15-9a117a363765/element/%7Bde758e6a-79b8-584d-9644-f6b5932a429e%7D/value | {"value":["("]}
<- {"name":"sendKeysToElement","sessionId":"788a90a0-ac72-1e43-ad15-9a117a363765","status":0,"value":""}
```

**Comment by lukeis** [comment] 2015-11-05 17:14
duplicate of #674

**Closed by lukeis** 2015-11-05 17:14 UTC
Labels: D-firefox
