### ISSUE TITLE
[🐛 Bug]: Dynamic Grid - node parameters for Selenium nodes. Need to pass image specific parameters in config.toml

### ISSUE THREAD

**Issue by pmswatuser** [SeleniumHQ/selenium#9983] opened 2021-10-25 17:49 UTC
### What happened?

Trying to add VNC parameters to node-docker image when running dynamicgrid. But parameters don't take effect. 

example: 
VNC_NO_PASSWORD=1 has no effect. 
Ports: 5900 and 7900 have no effect.
Although SE_NODE_GRID_URL works and allows a live view of a running session on dynamic grid.

While these parameters works in a standard grid 4 (not dynamic), how do we accomplish this using config.toml file? the ports will need to be specific to an image. How do we specify the port mapping in the config file?

### How can we reproduce the issue?

```shell
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.0.0
    volumes:        
      - ./config.toml:/opt/bin/config.toml
      - ./assets:/opt/selenium/assets
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
      - VNC_NO_PASSWORD=1 
    ports:
      - "6900:5900"
      - "7900:7900"

  selenium-hub:
    image: selenium/hub:4.0.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"


config file used:

[docker]
configs = [
    "selenium/standalone-firefox:4.0.0", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:4.0.0", "{\"browserName\": \"chrome\"}",
    "selenium/standalone-edge:4.0.0", "{\"browserName\": \"MicrosoftEdge\"}"
    ]
url = "http://host.docker.internal:2375"
```

### Relevant log output

```shell
Cannot get live view using port 7900. 
Trying to avoid entering password for VNC when launching the session from queue manager on localhost:4444. ALways asks for password.
```

### Operating System

Windows 10

### Selenium version

4

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

NA

### Are you using Selenium Grid?

4.0

**Comment by diemol** [comment] 2021-10-27 09:51
This is a duplicate of https://github.com/SeleniumHQ/docker-selenium/issues/1319, please suscribe to that issue for updates.

**Closed as completed by diemol** 2021-10-27 09:51 UTC
