### ISSUE TITLE
Python - remote connection - can't decode a string in py3

### ISSUE THREAD

**Issue by birdsarah** [SeleniumHQ/selenium#3660] opened 2017-03-15 19:27 UTC
Am getting the following error:

```py
            if parsed_url.username:
                base64string = base64.b64encode('{0.username}:{0.password}'.format(parsed_url).encode())
>               request.add_header('Authorization', 'Basic {}'.format(base64string).decode())
E               AttributeError: 'str' object has no attribute 'decode'

../../../../miniconda3/envs/ap-webqa/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py:480: AttributeError
```

https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/remote_connection.py#L480

I may be missing something, but isn't `'Basic {}'.format(base64string)` going to produce a string, which doesn't have a `decode` method.

@davehunt this was a recent change from you. What am I missing?

(I'm running selenium 3.3.1 with pytest-selenium 1.9.1 on python 3.6)

**Comment by birdsarah** [comment] 2017-03-15 19:29
commit: https://github.com/SeleniumHQ/selenium/commit/55ed929d64e96c518c89244dd4a6fccc85865fc0

**Comment by lmtierney** [comment] 2017-03-15 19:32
This is fixed in master but not released yet.

**Comment by birdsarah** [comment] 2017-03-15 19:35
@lmtierney - please see link above - it is link to line in master - I have done git blame on master. Are you sure it's fixed?

**Comment by lmtierney** [comment] 2017-03-15 19:36
Sorry I thought this was a duplicate of an earlier issue, and the commit is actually in 3.3.1

**Comment by birdsarah** [comment] 2017-03-15 19:36
That's what I'm saying. @davehunt's commit from 5 days ago is the source of my issue.

**Comment by birdsarah** [comment] 2017-03-15 19:37
(just so we're clear - I have a lot of love for @davehunt - I'm going to take a stab at fixing this myself and adding a test)

**Comment by davehunt** [comment] 2017-03-15 21:22
Hmm... I can look into this tomorrow. Strange that my new unit test failed without my fix and passed with it. I must have missed something. If you get to it first Sarah, I'll be very grateful. ☺️

Dave Hunt

**Comment by birdsarah** [comment] 2017-03-15 21:49
Found why the test didn't pick it up.

The test reads:

```python
    with pytest.raises(AttributeError):
        RemoteConnection('http://user:pass@remote', resolve_ip=False) \
            .execute('status', {})
```

But the decode error is an `Attribute Error`

```python
>               request.add_header('Authorization', 'Basic {}'.format(base64string).decode())
E               AttributeError: 'str' object has no attribute 'decode'
```

**Comment by davehunt** [comment] 2017-03-15 21:54
Aha! Yeah, I wasn't too keen on that when I wrote it. The code isn't easy to write tests around... We would either need to mock a suitable return value or be much more specific in the pytest.raises.

Dave Hunt

**Closed** 2017-03-18 12:27 UTC

**Comment by vmalloc** [comment] 2017-03-28 18:12
I'm hitting this bug as well. Any idea when a release is due?

**Comment by mwebcrew** [comment] 2017-03-31 20:06
I've also run up against this bug. Is there a patch/fix for it anytime soon?

**Comment by Sajam** [comment] 2017-04-03 07:22
+1

**Comment by davehunt** [comment] 2017-04-04 13:29
3.3.2 has been released: https://pypi.python.org/pypi/selenium/3.3.2

**Comment by vmalloc** [comment] 2017-04-04 13:50
Thanks @davehunt !
