### ISSUE TITLE
ArgumentError: unknown command: :mouseMoveTo

### ISSUE THREAD

**Issue by cyang023** [SeleniumHQ/selenium#3007] opened 2016-10-25 22:33 UTC
## Meta -
OS:  
OSX
Selenium Version:  
3.0.0
Browser:  
Chrome 54.0.2840.59
Firefox 49.0.1

Browser Version:  
Chrome 54.0.2840.59 (64 bit)
Firefox 49.0.1

Hi,
When using Selenium-Webdriver against a remote Selenium grid, running Linux nodes. Ok when controlling local browser.

`driver.action.move_to(Selenium::WebDriver::Element).perform`

produces 
```
ArgumentError: unknown command: :mouseMoveTo
        from /selenium-webdriver-3.0.0/lib/selenium/webdriver/remote/w3c_bridge.rb:645:in `raw_execute'
        from /selenium-webdriver-3.0.0/lib/selenium/webdriver/remote/w3c_bridge.rb:634:in `execute'
        from /selenium-webdriver-3.0.0/lib/selenium/webdriver/remote/w3c_bridge.rb:435:in `mouse_move_to'
        from /selenium-webdriver-3.0.0/lib/selenium/webdriver/common/mouse.rb:69:in `move_to'
        from /selenium-webdriver-3.0.0/lib/selenium/webdriver/common/action_builder.rb:354:in `block in perform'
        from /selenium-webdriver-3.0.0/lib/selenium/webdriver/common/action_builder.rb:353:in `each'
        from /selenium-webdriver-3.0.0/lib/selenium/webdriver/common/action_builder.rb:353:in `perform'
```

**Comment by lukeis** [comment] 2016-10-25 22:57
duplicate of #2285

**Closed by lukeis** 2016-10-25 22:57 UTC
