### ISSUE TITLE
Change in behaviour breaks clicking on popup span.

### ISSUE THREAD

**Issue by dmk1000** [SeleniumHQ/selenium#1420] opened 2015-12-24 14:25 UTC
Using 2.47.1 with Firefox worked with our website.
Upgrading to 2.48.0 ( or 2.48.1 / 2.48.2) stopped working on a click on a particular element on the website. We use selenium to click on an element and it pops up a series of numbers in spans. The clicking on these spans seems to be broken now in that the onclick doesn't get processed for the span.

I git bisected to commit 0eec81da52ba4dfb16de590e6e82ebafa452416f
Specifically line 202 of javascript/firefox-driver/js/syntheticMouse.js of the above commit. (line 294 of current master)
```javascript
  bot.action.click(element, this.lastMousePosition, this.getMouse_());
```

If I change the line to
```javascript
  bot.action.click(element, this.lastMousePosition, new bot.Mouse(null, this.modifierKeys));
```
it works again.

**Comment by barancev** [comment] 2015-12-25 19:53
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by szimek** [comment] 2015-12-28 22:37
I'm not sure if it's related, but after upgrading webdriver to 2.48.2 from 2.47.x (I'm using Protractor, so after upgrading it to 3.0.0, it updated webdriver to 2.48.2) most of clicks in my tests (I'm using Firefox as well) stopped working. If an element is outside of the viewport, Firefox can still find it, but `element.click()` doesn't do anything at all, there's no error as well. I need to scroll to the element first and then call `click()`. I originally reported it in [Protractor repo](https://github.com/angular/protractor/issues/2800).

**Comment by barancev** [comment] 2015-12-29 07:31
@szimek Selenium should scroll. If it does not, please raise an issue (with a concise reproducible test case)

**Comment by szaluk** [comment] 2015-12-31 02:55
I logged a bug a while back where clicking on something outside of the viewport using FF  is causing issues.  Here is the ticket -> https://github.com/SeleniumHQ/selenium/issues/1156

There is a link to a test case that replicates the issue every time.

It seems like many people have encountered this issue.  FF used to be the most reliable browser but it seems to have really gone down lately.  I have added so many workarounds to make our tests work with FF that I might have to just remove it from our runs.  @lukeis added a comment in https://github.com/SeleniumHQ/selenium/issues/1423 that FF 45+ will not even work with the current FF driver and there won't be a release for Marionette until well after FF 45 so it seems like we are out of luck until that happens.

**Comment by dmk1000** [comment] 2016-01-08 10:41
Sorry. It's taking me longer to create a simple test case than I thought.
It's from a GWT site and unpicking it to a simple web page doesn't appear to be straight forward.

The clicking is inside the view-port so I don't think it's related to that.

**Comment by wdomes** [comment] 2016-01-25 18:12
We're experiencing the same problem as dmk1000 after upgrading from Selenium 2.47.x to 2.48.x (and 2.49.x). Our environment uses Python 2.7, Robot Framework for test execution, FF 38.x, and Linux.

Unfortunately, like dmk1000, the problem page is not easily abstracted into a simple test case and not accessible to the outside. The span with the onclick event that's not firing is generated by Dojo 1.8, which produces fairly complex html/javascript. The span functions as a submit button for an input element. The span and input elements are not part of a form element. The onclick event is added to the span by Dojo and is nested. See the example below:

<span class="dijit dijitReset dijitInline dijitButton" role="presentation" widgetid="actionButton">
<span class="dijitReset dijitInline dijitButtonNode" role="presentation" data-dojo-attach-event="ondijitclick:_onClick">
<span id="actionButton" class="dijitReset dijitStretch dijitButtonContents" aria-labelledby="actionButton_label" role="button" data-dojo-attach-point="titleNode,focusNode" tabindex="0" style="-moz-user-select: none;">
<span class="dijitReset dijitInline dijitIcon dijitNoIcon" data-dojo-attach-point="iconNode"></span>
<span class="dijitReset dijitToggleButtonIconChar">●</span>
<span id="actionButton_label" class="dijitReset dijitInline dijitButtonText" data-dojo-attach-point="containerNode">Create</span>
</span>
</span>
<input class="dijitOffScreen" type="button" data-dojo-attach-point="valueNode" role="presentation" tabindex="-1" value="">
</span>

When our Robot test runs, after navigating to the page, the input element is populated with a value, then the span is clicked. With Selenium 2.47.3, the information from the input element is submitted to the application and the next page is displayed. With Selenium 2.48.x and 2.49.x, nothing happens after the span is clicked. Robot reports that the click action was successful, but the next page is not displayed, and the information from the input field is not submitted to the application.

I also ran the Robot test locally using Mac OS X 10.10.5, FF 43.0.x and Selenium 2.49.x against the same web app and server and experienced the same failure. Downgrading my local environment to FF 42.0 and Selenium 2.47.3 allowed the test to run successfully.

**Comment by barancev** [comment] 2016-01-25 20:22
We hardly can do anything without a reproduction case.

**Comment by wdomes** [comment] 2016-01-26 01:39
Understood, and this is not how I would normally contribute to a bug. However, being resource constrained and unable to generate a sanitized example on my own, I thought adding the small amount of additional information I could (i.e. multiple people experiencing the problem in other environments) had some value. Maybe someone else, who is also having this issue and can create a shareable and reproducible example, as is required, will find this bug report and contribute.

I'm curious to know why no comment has been made about dmk1000's suggested code change? It would be helpful to know if it sheds any light on the problem or creates other problems through unintended consequences.

**Comment by barancev** [comment] 2016-01-26 06:30
@wdomes I got what line of the code causes the effect.

But we're not going back to the old implementation. Instead we'd fix the new one. And this is why we need a reproduction case to debug the issue.

**Comment by barancev** [comment] 2016-03-02 06:09
Closing the issue as there is no reproduction case provided.

**Closed by barancev** 2016-03-02 06:09 UTC
Labels: D-firefox, R-awaiting answer
