### ISSUE TITLE
Invalid inputs are not cleared properly

### ISSUE THREAD

**Issue by MattiSG** [SeleniumHQ/selenium#1214] opened 2015-11-02 17:32 UTC
[Here](https://gist.github.com/MattiSG/0cb11f94237a414c6872) is a test case that uses [Watai](https://github.com/MattiSG/Watai/):

(assuming you have a running Selenium Server)

```shell
$ git clone https://gist.github.com/0cb11f94237a414c6872.git
$ npm install watai@0.7.0-beta.1
$ node_modules/.bin/watai .
```

Sorry, I have long forgotten Selenium’s native API.

Reproduced with v2.45 and v2.48.0, on both Firefox and Chrome.

**Comment by lukeis** [comment] 2015-11-02 20:02
please provide a reproducible test case for us using "Selenium's native API" we don't have the time to look through the other project for a potential bug in it. Can reopen this bug if a concise reproducible test case is provided.

**Comment by MattiSG** [comment] 2015-11-02 20:18
Does a series of JSONwire commands qualify, or do I really need to learn to write Java to contribute bug reports?

**Comment by lukeis** [comment] 2015-11-02 20:40
that could be a start... you don't need java... we also have C#, python, ruby, javascript :)

**Comment by MattiSG** [comment] 2015-11-03 08:40
Test case [updated](https://gist.github.com/MattiSG/0cb11f94237a414c6872#file-selenium-js).

**Comment by lukeis** [comment] 2015-11-03 17:53
thanks for the reproducible test case!

**Comment by lukeis** [comment] 2015-11-03 19:05
since it was fixed in the atoms, this should be fixed in chromedriver the next time they pull in the atoms and do a release.

will be available in firefox in the next release, or you could always build from source.

**Closed** 2015-11-03 19:04 UTC
Labels: D-firefox

**Comment by MattiSG** [comment] 2015-11-04 07:28
Great!

Looking at the referenced commit, I'm wondering if you won't get the exact same issue with all the different input `type`s that are expected to give a value of type other than `String` in JS. WDYT?


Matti Schneider
————
Written on a phone, please excuse the terseness.
Rédigé sur un téléphone, veuillez excuser la brièveté.

**Comment by lukeis** [comment] 2015-11-04 15:45
I tried with a variety of other input types (from the html 5 spec) and only number exhibited this behavior. If others in the future do too, then we'll have to correct it then.

**Comment by MattiSG** [comment] 2015-11-04 16:22
:+1:
