### ISSUE TITLE
Java- ProfilesIni method error

### ISSUE THREAD

**Issue by Edenpac** [SeleniumHQ/selenium#8915] opened 2020-11-27 09:57 UTC
## 🐛 Bug Report

In java, when I call new ProfilesIni(), there is error. The problem is, that in class ProfilesIni , line 60: reader = new BufferedReader(new FileReader(profilesIni, Charset.defaultCharset()));
FileReader method has only one argument. Argument Charset.defaultCharset() should be removed.

## To Reproduce

Detailed steps to reproduce the behavior:

## Expected behavior

In java, when I call new ProfilesIni(), there is error. The problem is, that in class ProfilesIni , line 60: reader = new BufferedReader(new FileReader(profilesIni, Charset.defaultCharset()));
FileReader method has only one argument. Argument Charset.defaultCharset() should be removed.

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10
Browser: Firefox
Browser version: 83.0
Browser Driver version: GeckoDriver 0.28.0
Language Bindings version: Java 1.8.0_241 
Selenium Grid version (if applicable):

**Comment by diemol** [comment] 2020-11-27 10:16
This is a duplicate of #8870, which was fixed in `trunk` via https://github.com/SeleniumHQ/selenium/commit/b338b3396ec1578b396700d93545d5d96c79e0f1 and should be available in the upcoming weeks when the `beta-1` release is done.

**Closed as completed by diemol** 2020-11-27 10:16 UTC
