### ISSUE TITLE
Doesn't work with Firefox 45.0.1

### ISSUE THREAD

**Issue by japgolly** [SeleniumHQ/selenium#1851] opened 2016-03-21 10:23 UTC
Selenium connects to Firefox **45.0** successfully, but fails with Firefox **45.0.1**.

## Meta -
OS: Arch Linux
Selenium Version: 2.49.1
Browser: Firefox
Browser Version: 45.0.1 (64-bit)

## Expected Behavior -
Selenium should be able to establish a connection to Firefox.

## Actual Behavior -
Selenium crashes trying to establish a connection to Firefox.

This is the output:
```
org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 
URI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"45.0a1","maxVersion":"45.0.1"},{"id":"xpcshell@tests.mozilla.org","minVersion":"0","maxVersion":"10"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
1458554861749	addons.xpi	DEBUG	getModTime: Recursive scan of loop@mozilla.org
1458554861749	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"9OOVuBjYD02h","location":"app-global","version":"45.0.1","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1458394183000,"updateDate":1458394183000,"applyBackgroundUpdates":1,"skinnable":true,"size":5028,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"45.0.1","maxVersion":"45.0.1"}],"targetPlatforms":[],"seen":true}
1458554861749	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1458554861750	DeferredSave.extensions.json	DEBUG	Save changes
1458554861750	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1458554861750	addons.xpi-utils	DEBUG	Updating add-on states
1458554861750	addons.xpi-utils	DEBUG	Writing add-ons list
1458554861751	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/loop@mozilla.org.xpi
1458554861751	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 0.1
1458554861759	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1458554861759	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1458554861760	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1458554861768	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1458554861768	addons.manager	DEBUG	Provider finished startup: XPIProvider
1458554861768	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1458554861768	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1458554861768	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1458554861769	addons.manager	DEBUG	Starting provider: GMPProvider
1458554861772	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1458554861772	addons.manager	DEBUG	Provider finished startup: GMPProvider
1458554861772	addons.manager	DEBUG	Starting provider: PluginProvider
1458554861772	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1458554861772	addons.manager	DEBUG	Provider finished startup: PluginProvider
1458554861773	addons.manager	DEBUG	Completed startup sequence
1458554861911	DeferredSave.extensions.json	DEBUG	Starting write
1458554861970	addons.repository	DEBUG	No addons.json found.
1458554861970	DeferredSave.addons.json	DEBUG	Save changes
1458554861972	DeferredSave.addons.json	DEBUG	Starting timer
1458554861986	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1458554861986	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1458554861986	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1458554861989	DeferredSave.extensions.json	DEBUG	Write succeeded
1458554861990	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1458554862036	DeferredSave.addons.json	DEBUG	Starting write
1458554862044	DeferredSave.addons.json	DEBUG	Write succeeded

Build info: version: '2.49.1', revision: '808c23b0963853d375cbe54b90bbd052e2528a54', time: '2016-01-21 09:37:52'
System info: host: 'golly-desktop', ip: '192.168.3.20', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.1-2-ARCH', java.version: '1.8.0_74'
Driver info: driver.version: BrowserDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:135)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at org.scalajs.jsenv.selenium.Firefox$FirefoxDriver.newDriver(Firefox.scala:48)
	at org.scalajs.jsenv.selenium.BrowserDriver.start(BrowserDriver.scala:20)
	at org.scalajs.jsenv.selenium.SeleniumRunner.run(SeleniumRunner.scala:14)
	at org.scalajs.sbtplugin.FrameworkDetector.detect(FrameworkDetector.scala:66)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$59.apply(ScalaJSPluginInternal.scala:736)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$59.apply(ScalaJSPluginInternal.scala:719)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
URI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"45.0a1","maxVersion":"45.0.1"},{"id":"xpcshell@tests.mozilla.org","minVersion":"0","maxVersion":"10"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
1458554861749	addons.xpi	DEBUG	getModTime: Recursive scan of loop@mozilla.org
1458554861749	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"9OOVuBjYD02h","location":"app-global","version":"45.0.1","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1458394183000,"updateDate":1458394183000,"applyBackgroundUpdates":1,"skinnable":true,"size":5028,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"45.0.1","maxVersion":"45.0.1"}],"targetPlatforms":[],"seen":true}
1458554861749	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1458554861750	DeferredSave.extensions.json	DEBUG	Save changes
1458554861750	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1458554861750	addons.xpi-utils	DEBUG	Updating add-on states
1458554861750	addons.xpi-utils	DEBUG	Writing add-ons list
1458554861751	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/loop@mozilla.org.xpi
1458554861751	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 0.1
1458554861759	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1458554861759	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1458554861760	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1458554861768	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1458554861768	addons.manager	DEBUG	Provider finished startup: XPIProvider
1458554861768	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1458554861768	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1458554861768	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1458554861769	addons.manager	DEBUG	Starting provider: GMPProvider
1458554861772	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1458554861772	addons.manager	DEBUG	Provider finished startup: GMPProvider
1458554861772	addons.manager	DEBUG	Starting provider: PluginProvider
1458554861772	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1458554861772	addons.manager	DEBUG	Provider finished startup: PluginProvider
1458554861773	addons.manager	DEBUG	Completed startup sequence
1458554861911	DeferredSave.extensions.json	DEBUG	Starting write
1458554861970	addons.repository	DEBUG	No addons.json found.
1458554861970	DeferredSave.addons.json	DEBUG	Save changes
1458554861972	DeferredSave.addons.json	DEBUG	Starting timer
1458554861986	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1458554861986	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1458554861986	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1458554861989	DeferredSave.extensions.json	DEBUG	Write succeeded
1458554861990	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1458554862036	DeferredSave.addons.json	DEBUG	Starting write
1458554862044	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:123)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at org.scalajs.jsenv.selenium.Firefox$FirefoxDriver.newDriver(Firefox.scala:48)
	at org.scalajs.jsenv.selenium.BrowserDriver.start(BrowserDriver.scala:20)
	at org.scalajs.jsenv.selenium.SeleniumRunner.run(SeleniumRunner.scala:14)
	at org.scalajs.sbtplugin.FrameworkDetector.detect(FrameworkDetector.scala:66)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$59.apply(ScalaJSPluginInternal.scala:736)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$59.apply(ScalaJSPluginInternal.scala:719)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (webapp-client/firefox:loadedTestFrameworks) org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 
[error] URI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"45.0a1","maxVersion":"45.0.1"},{"id":"xpcshell@tests.mozilla.org","minVersion":"0","maxVersion":"10"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
[error] 1458554861749	addons.xpi	DEBUG	getModTime: Recursive scan of loop@mozilla.org
[error] 1458554861749	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"9OOVuBjYD02h","location":"app-global","version":"45.0.1","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1458394183000,"updateDate":1458394183000,"applyBackgroundUpdates":1,"skinnable":true,"size":5028,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"45.0.1","maxVersion":"45.0.1"}],"targetPlatforms":[],"seen":true}
[error] 1458554861749	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
[error] 1458554861750	DeferredSave.extensions.json	DEBUG	Save changes
[error] 1458554861750	addons.xpi	DEBUG	Updating database with changes to installed add-ons
[error] 1458554861750	addons.xpi-utils	DEBUG	Updating add-on states
[error] 1458554861750	addons.xpi-utils	DEBUG	Writing add-ons list
[error] 1458554861751	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/loop@mozilla.org.xpi
[error] 1458554861751	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 0.1
[error] 1458554861759	addons.manager	DEBUG	Starting provider: <unnamed-provider>
[error] 1458554861759	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
[error] 1458554861760	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
[error] 1458554861768	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
[error] 1458554861768	addons.manager	DEBUG	Provider finished startup: XPIProvider
[error] 1458554861768	addons.manager	DEBUG	Starting provider: LightweightThemeManager
[error] 1458554861768	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
[error] 1458554861768	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
[error] 1458554861769	addons.manager	DEBUG	Starting provider: GMPProvider
[error] 1458554861772	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
[error] 1458554861772	addons.manager	DEBUG	Provider finished startup: GMPProvider
[error] 1458554861772	addons.manager	DEBUG	Starting provider: PluginProvider
[error] 1458554861772	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
[error] 1458554861772	addons.manager	DEBUG	Provider finished startup: PluginProvider
[error] 1458554861773	addons.manager	DEBUG	Completed startup sequence
[error] 1458554861911	DeferredSave.extensions.json	DEBUG	Starting write
[error] 1458554861970	addons.repository	DEBUG	No addons.json found.
[error] 1458554861970	DeferredSave.addons.json	DEBUG	Save changes
[error] 1458554861972	DeferredSave.addons.json	DEBUG	Starting timer
[error] 1458554861986	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
[error] 1458554861986	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
[error] 1458554861986	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
[error] 1458554861989	DeferredSave.extensions.json	DEBUG	Write succeeded
[error] 1458554861990	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
[error] 1458554862036	DeferredSave.addons.json	DEBUG	Starting write
[error] 1458554862044	DeferredSave.addons.json	DEBUG	Write succeeded
[error] 
[error] Build info: version: '2.49.1', revision: '808c23b0963853d375cbe54b90bbd052e2528a54', time: '2016-01-21 09:37:52'
[error] System info: host: 'golly-desktop', ip: '192.168.3.20', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.1-2-ARCH', java.version: '1.8.0_74'
[error] Driver info: driver.version: BrowserDriver
```

**Comment by dborne-rs** [comment] 2016-03-21 14:05
Try it with Selenium v 2.52.0

**Comment by OlleJF** [comment] 2016-03-21 14:27
I'm having similiar issues with firefox 45.0.1.
Upgrading to Selenium 2.52.0 or 2.53.0 allows firefox to start, however the driver cant do stuff. It fails already on driver.navigate().GoToUrl. No exception or anything, its just that nothing happens. Like as if the driver cant speak to the browser or something.

**Comment by japgolly** [comment] 2016-03-21 21:35
Upgrading to 2.53.0 solved my use case. Thanks @dborne-rs. (I actually meant to try that before submitting this issue but got distracted and forgot.)

I leave this open for @OlleJF.

**Comment by lukeis** [comment] 2016-03-21 22:04
@OlleJF can you please provide more info / a way to reproduce your issue?

**Comment by soupman99** [comment] 2016-03-23 17:50
+1

**Comment by louis57** [comment] 2016-03-29 08:31
Hi, I have the same issue. I tried with Selenium 2.52.0 and 2.53.0, both of them worked, but unfortunately, some elements with ID don't work anymore (which they worked fine before upgrading to FF 45.0.1). I got exception like: "Element is not reachable, the other element at position received the click etc... "

**Comment by p0deje** [comment] 2016-03-29 08:49
@louis57 That is a completely different issue.

**Comment by louis57** [comment] 2016-03-29 09:04
@p0deje sorry, I thought it could be related somehow. I created new issue for this matter.

**Comment by balasuar** [comment] 2016-04-01 00:13
I can confirm that updating Selenium to 2.53.0 resolves this issue.

**Comment by p0deje** [comment] 2016-04-01 02:49
Closing since works on 2.53

**Closed by p0deje** 2016-04-01 02:49 UTC

**Comment by virendrarawat** [comment] 2016-04-22 02:00
I am facing the same issue with selenium 2.53 and FF version 45.0.2. Should i downgrade FF to 45.0.1

**Comment by mchirlin** [comment] 2016-04-26 22:58
I am facing this issue as well with 2.53 and 45.0.2.

**Comment by virendrarawat** [comment] 2016-04-27 00:22
I reconfigured eclipse and this problem resolved. now selenium 2.53 working fine with FF 45.0.2.

**Comment by DanielSundberg** [comment] 2016-04-27 04:53
@virendrarawat, how did you reconfigure Eclipse?

**Comment by naveenabt** [comment] 2016-05-10 05:17
HI,

It is filling form after that it i s not clicking on "save" button.
I have checked the log, it is showing like "Timed out after 90 seconds".

Please any suggestion?

Thanks,

**Comment by juberjj** [comment] 2016-06-23 20:44
Hi,

Not working with selenium 2.53 and FF 47.0. Windows 7 x64 platform.

Any thoughts, workarounds?

Thanks in advance

**Comment by zaemiel** [comment] 2016-07-24 14:39
Hi,

Also not working with Selenium 2.53.6 and Firefox 47.0 on Mint Cinnamon x64
