### ISSUE TITLE
Cant start a Firefox 72 profile

### ISSUE THREAD

**Issue by SavSanta** [SeleniumHQ/selenium#8018] opened 2020-02-10 13:20 UTC
## 🐛 Bug Report

Selenium crashes and exceptions out with error

```
/home/santa/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py in __init__(self, firefox_profile, firefox_binary, timeout, capabilities, proxy, executable_path, options, service_log_path, firefox_options, service_args, desired_capabilities, log_path, keep_alive)
    172                 command_executor=executor,
    173                 desired_capabilities=capabilities,
--> 174                 keep_alive=True)
    175 
    176         # Selenium remote

/home/santa/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py in __init__(self, command_executor, desired_capabilities, browser_profile, proxy, keep_alive, file_detector, options)
    155             warnings.warn("Please use FirefoxOptions to set browser profile",
    156                           DeprecationWarning, stacklevel=2)
--> 157         self.start_session(capabilities, browser_profile)
    158         self._switch_to = SwitchTo(self)
    159         self._mobile = Mobile(self)

/home/santa/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py in start_session(self, capabilities, browser_profile)
    241         """
    242         import pdb;pdb.set_trace()
--> 243         if not isinstance(capabilities, dict):
    244             raise InvalidArgumentException("Capabilities must be a dictionary")
    245         if browser_profile:

/home/santa/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py in execute(self, driver_command, params)
    320         response = self.command_executor.execute(driver_command, params)
    321         if response:
--> 322             self.error_handler.check_response(response)
    323             response['value'] = self._unwrap_value(
    324                 response.get('value', None))

/home/santa/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py in check_response(self, response)
    240                 alert_text = value['alert'].get('text')
    241             raise exception_class(message, screen, stacktrace, alert_text)
--> 242         raise exception_class(message, screen, stacktrace)
    243 
    244     def _value_or_default(self, obj, key, default):

SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

## To Reproduce
```
from selenium import webdriver                                                                                                         
import selenium
ffw = webdriver.Firefox(firefox_binary="/home/santa/firefox/", firefox_profile='/home/santa/.mozilla/firefox/8lj1dc4h.default-release')
```

Detailed steps to reproduce the behavior:

## Expected behavior

Expect a Firefox instance with the loaded profile.

## Environment

OS: Linux
Browser: Firefox
Browser version:72.0
Browser Driver version: geckodriver 0.25.0 (bdb64cf16b68 2019-09-10) 
Language Bindings version:  Python  3.141.0 

## Extra Notes
The Firefox install not a systemwide package manager install.
The Firefox install is not in the system PATH variable.
One can open a selenium driven Firefox with a blank profile by not supplying the firefox_profile keyword paramater

The profile is about 155 mbs. Here is a short snippet of what the capabilities object looks like when i had it written to file at the time.

$ cut -b -45 /tmp/capabils.txt 
{'acceptInsecureCerts': True,
 'browserName': 'firefox',
 'marionette': True,
 'moz:firefoxOptions': {'binary': '/home/sant
                        'profile': 'UEsDBBQAA [...]

**Comment by AutomatedTester** [comment] 2020-03-25 21:49
Duplicate of #7677

**Closed by AutomatedTester** 2020-03-25 21:49 UTC
Labels: C-py, D-firefox
