### ISSUE TITLE
Safari 9.0.2 failing to respond for Executing: [get 'url']

### ISSUE THREAD

**Issue by vveliev** [SeleniumHQ/selenium#1467] opened 2016-01-13 16:30 UTC
Safari driver start to work and then hangs after some time.

**Comment by mdmmoreno** [comment] 2016-01-13 22:20
I'm having the same issue but with Firefox

**Comment by 5hawnknight** [comment] 2016-01-18 20:23
please provide an example (code and url) that can reproduce your issue

**Comment by mdmmoreno** [comment] 2016-01-18 20:27
I was able to fix my problem by downgrading my Firefox.

**Comment by bmwe30is** [comment] 2016-02-29 17:54
I saw the same issue on our OS X machines and pulled down the latest Selenium source to take a peak at the Safari driver extension. 

I found that we would call: 
`wDriver.get("www.foobar.com"); `

Which would trigger a pageUnload event in Safari.  However, the Safari driver extension was not receiving notification that the page is ready. 

You can view the method here:  https://github.com/SeleniumHQ/selenium/blob/009260c837f371e9b3650e46e6572fbb14fffbec/javascript/safari-driver/extension/tab.js#L98

I removed: `this.notifyUnready();` and ran my test suite multiple times over the weekend without any ill effects and improved test stability. 

No more socket timeouts or hanging GET requests when I drive the browser to a different page or cause elements to unload.  

I'm still keeping a keen eye on the issue but will post back if things change. 

Hope that helps.

**Comment by lukeis** [comment] 2016-09-23 20:15
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.

**Closed by lukeis** 2016-09-23 20:15 UTC
Labels: A-needs new owner, D-safari
