### ISSUE TITLE
problems with button in 4.0.0.alpha01 and 4.0.0.alpha02

### ISSUE THREAD

**Issue by hnestorova** [SeleniumHQ/selenium#7409] opened 2019-07-19 09:43 UTC
## 🐛 Bug Report

We have observed two problems with buttons:
Case1. a Clear button does not become inactive again after a newly entered value in a field is cleared by pressing the Clear button in a pop-up window
Case2. pressing an OK button in a pop-up window makes the button inactive but the window does not close

## To Reproduce
Detailed steps to reproduce the behavior:
Case1:
1. We open up a pop-up window with an empty field
2. We set a value in the empty field with activates the Clear button in the pop-up
3. We press the Clear button, the value entered in the field is Cleared but the button itself remains active while it should again be disabled

Case2:
1. We open up a pop-up window with several items in it that can be selected
2. We select the check-box for one of the items which makes the OK button in the pop-up window become active
3. We press the OK button to confirm the selection and close the pop-up window. As a result, the selection is acknowledged and the user is redirected to another page. However, the pop-up does not close - only the OK appears as disabled.
4. As a result from Step 3, we repeat the selection from Step 2 and again press the OK button which this time closes the pop-up window

## Expected behavior
Case1:
Button Clear becomes inactive when the newly entered values are cleared
Case2:
Pop-up window is closed after pressing the OK button 

## Environment

OS: Windows 7
Browser: Internet Explorer
Browser version: Internet Explorer 11.0.9600.19002
Browser Driver version: IEWebDriver 3.141.59 for 32 bit Windows IE
Language Bindings version: Java 11.0.2
Selenium Grid version (if applicable): 4.0.0.alpha01 and 4.0.0.alpha02

**Comment by barancev** [comment] 2019-07-19 12:21
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by hnestorova** [comment] 2019-07-19 12:51
yes, i understand this but i cannot make our code public. I can provide some code snippets and tell you a version in which these actions with the buttons worked ok

**Comment by barancev** [comment] 2019-07-19 13:08
We don't need your super-secret pages. Create a simplified page that allows to reproduce the issue.

**Comment by hnestorova** [comment] 2019-07-19 15:21
:) I dont have time for pages creation. I have found workarounds for our side, just wanted to help resolve the issues in the framework. If you are ok with those, lets close then.

**Comment by cgoldberg** [comment] 2019-07-19 15:43
> just wanted to help resolve the issues in the framework

nothing was resolved in selenium.

closing this issue since OP refuses to provide necessary details.

**Closed by cgoldberg** 2019-07-19 15:43 UTC
Labels: D-IE, R-awaiting answer
