### ISSUE TITLE
We need an API for toggling extensions and managing. Currently I have to mess to about:addons

### ISSUE THREAD

**Issue by KOLANICH** [SeleniumHQ/selenium#7402] opened 2019-07-17 14:30 UTC
## 🚀 Feature Proposal

An API for managing extensions is needed:
1. installation from AMO
2. switching on
3. switching off
4. switching availability in private mode
5. getting list of permissions

## Motivation
Not to mess to about:addons for that.

## Example
```python
addons.install("addon amo id") -> Addon
addons.list # list of addons
addon.uninstall()
addon.permissions
addon.updateMode
addon.manifest # manifest dict
addon.content # allows accessing files inside of addon, for example getting their URIs
addon.pages # different pages, like setting page
addon.disabled # allows disabling/enabling and getting status
```

**Comment by KOLANICH** [comment] 2021-10-20 19:42
Stale bots are harmful

**Comment by titusfortner** [comment] 2021-12-26 15:21
Can you help me better understand what you're looking for? Tools to build a Firefox addon seems a little out of scope for a browser autoamtion tool. Is your use case needing to zip the directory and pass it to Firefox without needing to have it signed? (as discussed here— https://github.com/SeleniumHQ/selenium/issues/8357#issuecomment-998026524)

**Comment by KOLANICH** [comment] 2021-12-26 17:33
>Tools to build a Firefox addon seems a little out of scope for a browser autoamtion tool.

Clearly, since an addon is just a renamed zip archive.

>Can you help me better understand what you're looking for?

Just a complete cross-browser API for addons management. Since I use Firefox, I used it as an example. I.e. there was (and maybe is) a defect in Firefox causing all the addons to be de-facto disabled when the browser was WebDriver-driven. The workaround for it was to iterate a list of addons and disable each one and then enable each one.

**Comment by titusfortner** [comment] 2021-12-26 20:26
Can you give me a reproducible case for the addon being disabled? Is it an issue of not being signed, or something else?

I'm not an expert on extensions, so I'm trying to understand what the underlying issue is because installing and uninstalling addons works, and creating/manipulating/whatever in Selenium seems out of scope for where we are. Is this something you could create a PR for?

**Comment by KOLANICH** [comment] 2021-12-26 23:47
>creating/manipulating/whatever in Selenium seems out of scope

How can it be out of scope if it is an essential functionality of a browser and doing it by messing with gui instead of using the api is just fragile and 

>Can you give me a reproducible case for the addon being disabled?

https://github.com/mozilla/geckodriver/issues/1517

(disclaimer, I have not tested this now)

But the api is still heeded even after that issue is solved.

**Comment by titusfortner** [comment] 2021-12-27 05:55
Ah, ok, so... there's a push by some on the team for us to get away from supporting profiles entirely and requiring users to pass in the prefs and args as appropriate in capabilities (then addons are installed after the session has started). I think that's going too far, and I'll keep this issue open, but I wouldn't expect this to be priority for the team.

**Comment by KOLANICH** [comment] 2021-12-27 08:13
>there's a push by some on the team for us to get away from supporting profiles entirely

Supporting profiles is gold, but in Firefox they are implemented in the way making them completely unusable (in-memory zipping a profile dir then unzipping it, eats lot of memory, consumes lots of cpu, causes lots of swapping even on Windows). So I just used the main profile, the same I use for browsing, with all  y addons preinstalled. Creating a fresh profile for each session is a lot of trouble out of thin air, because addons and about:config configuration has taken a lot of time for me, and automating it all will cause even more trouble.

**Comment by titusfortner** [comment] 2021-12-27 14:53
Yeah, I've had an open issue in geckodriver for not accepting the zipped profiles sent to a remote machine (probably because they were too large) for a few years. They are essentially unusable on a remote machine. Creating a blank profile and adding things to it would be a much better option, and is more how things were done in the old Firefox driver. I do agree that better tools for this would be useful.

**Comment by diemol** [comment] 2022-12-12 17:12
What is the plan here? Shouldn't this be done in a cross browser way at the WebDriver spec level? Or is this something that needs to be hacked in Selenium directly?

**Comment by titusfortner** [comment] 2023-04-30 22:03
Since this issue was opened, we've added support for unsigned addons in Firefox. You can add and remove signed & unsigned, directories or files. That's what is supported by Mozilla. I think these additional features will have to be managed by Mozilla. If they add this functionality, Selenium will support it.

**Closed** 2023-04-30 22:03 UTC
Labels: I-enhancement, help wanted, G-geckodriver

**Comment by KOLANICH** [comment] 2023-05-01 21:03
>Since this issue was opened, we've added support for unsigned addons in Firefox. You can add and remove signed & unsigned, directories or files. That's what is supported by Mozilla. I think these additional features will have to be managed by Mozilla. If they add this functionality, Selenium will support it.

I don't understand how it is relevant here. This issue is not about addons signing, which is completely different issue, but about managing addons via API, rather than messing with `about:addons` or profile dir manipulation.

**Comment by titusfortner** [comment] 2023-05-02 00:06
Yes, I'm saying that API needs to originate in geckodriver, not Selenium.
