### ISSUE TITLE
TestNG Parallel Execution with Linux machines

### ISSUE THREAD

**Issue by Vishnu1067** [SeleniumHQ/selenium#804] opened 2015-07-17 02:46 UTC
Hi,

Application : GWT 
Environment - Linux 32 bit
Browser - Chrome 43 version
ChromeDriver.exe - 2.16 (Linux 32)
WebDriver
execution mode - Parallel
Thread count - 3
TestNG with Maven mode.

Selenium run with Java scripts.

Issue facing:

When executing parallel with Linux systems, browsers are switching in between based on the steps performed. Due to this, following issue occurred;

Browser 1: Lets say, i am entering Date field (while entering date (17/JU, in the middle of entry switching to broswer 2, this date shows invalid entry
Browser 2: Entering some fields
Browser 3: Entering some fields

All the browsers are switching between based on the steps performing.

When executing the same case in Windows, it works perfectly without switching the browsers and produces the expected results.

Kindly fix this issue with Linux and hope looking forward to hear some fixes.

Regards,
JPV.

**Comment by tarlabs** [comment] 2015-07-17 02:59
@Vishnu1067, Please create a reproducible test case on GitHub, so one of the developers can run and replicate the issue. Without that it is impossible to check for any dev

**Comment by Vishnu1067** [comment] 2015-07-17 08:07
When you run even single test case in Linux, you cannot do any other activity due to browser unable to process selenium commands through background... Or is there any settings in linux to run chrome browser in background? 

But when you run in windows, you can do other activities....

**Comment by cgoldberg** [comment] 2015-07-17 12:33
> "browsers are switching in between based on the steps performed"
> "it works perfectly without switching the browsers"

What does "switching the browsers" mean in this context?  Your entire description is so vague and odd that I can't fathom what you actually mean.  Care to clarify?

> you cannot do any other activity

Why are you trying to do other "activities" on a machine that is executing tests?  I'd suggest running selenium in a headless display so it doesn't interfere.

**Comment by Vishnu1067** [comment] 2015-07-19 04:37
When you run test case in Windows system, you can able to run test cases in background and browser will not interfere with your activities (you can open folders / play games / start scripting).

When you run same in Linux machine, unable to run the browser in background. if i want to open any folder, browser is blocking me.  Hope this clarifies you.

**Comment by lukeis** [comment] 2015-07-19 18:02
I can't reproduce that behavior (of not being able to do anything else on a Linux machine). Granted it is very difficult and not recommended to multi task on a machine that is running selenium scripts, as it will often bring the browser to the foreground and steal focus from what you may be attempting to do manually. 

This is expected behavior, for now I'm going to close this issue as 'won't fix'

**Closed by lukeis** 2015-07-19 18:02 UTC
