### ISSUE TITLE
Update to selenium 2.49 generates an error in Firefox. Was working perfectly in 2.48

### ISSUE THREAD

**Issue by dbenoit** [SeleniumHQ/selenium#1482] opened 2016-01-16 00:24 UTC
My scripts fail in firefox now that I have updated to sel 2.49 from 2.48. Works fine in Chrome thankfully. Using firefox version 43.0.4. I don't know if it is the version of firefox or sel 2.49 causing this bummer.

Using python selenium from a locally driven script get this trackback error:
line 16, in setUp
    self.driver = webdriver.Firefox()
  File "D:\Python27\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 79, in __init__
    self.binary, timeout),
  File "D:\Python27\lib\site-packages\selenium\webdriver\firefox\extension_connection.py", line 47, in __init__
    self.profile.add_extension()
  File "D:\Python27\lib\site-packages\selenium\webdriver\firefox\firefox_profile.py", line 91, in add_extension
    self._install_extension(extension)
  File "D:\Python27\lib\site-packages\selenium\webdriver\firefox\firefox_profile.py", line 287, in _install_extension
    shutil.rmtree(tmpdir)
  File "D:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "D:\Python27\lib\shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "D:\Python27\lib\shutil.py", line 254, in rmtree
    os.rmdir(path)
WindowsError: [Error 145] The directory is not empty: 'c:\\users\\deb\\appdata\\local\\temp\\tmpzmhidv.webdriver.xpi\\components'

i then delete this directory tmpzmhidv.webdriver.xpi\\components run it again
and I get this error:
WebDriverException: Message: Element is not clickable at point (58, 319). Other element would receive the click:

**Comment by caligoig** [comment] 2016-01-16 21:18
I have upgraded to 2.49 and now Firefox (43.0.4 version) on Ubuntu 14.04 running on Python 3.4 isnt working. 
Can you please provide any workarounds? Which is the selenium version I can return to in order to have my old scripts running again? 
Thanks

**Comment by barancev** [comment] 2016-01-17 09:17
FYI:
![17-01-2016 12-15-30](https://cloud.githubusercontent.com/assets/617090/12376721/4455472a-bd14-11e5-9db4-30d48e6d0839.png)

**Comment by vinaya470** [comment] 2016-01-18 15:05
Facing the same  issue. My selenium testcases written in Java are failing after upgrading to Selenium Webdriver 2.49 and Firefox to 43.0.4.
I get the same error:
WebDriverException: Message: Element is not clickable at point .....

Could you please give a work around. From my analysis, it seemed auto scrolling issue(not able to find the element in the small window). So, tried maximizing the Firefox Window, it worked for few parts of the testcase but few are still failing.

**Comment by rserrano** [comment] 2016-01-18 16:15
Also getting this error in python when upgrading
Hi, good day.

I upgraded selenium python yesterday to 2.49.0 and this error started appearing. Not in every test, but on 5 of about 20. Downgrading to 2.48.0 solved the problem. Thanks.

Traceback (most recent call last):
File "xxxx/yyy/tests/test_frontend_simple.py", line 871, in test_add_study
submit.click()
File "xxxx/env/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 75, in click
self.execute(Command.CLICK_ELEMENT)
File "xxxx/env/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 454, in execute
return self._parent.execute(command, params)
File "xxxx/env/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
self.error_handler.check_response(response)
File "xxxx/env/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 102, in check_response
value = json.loads(value_json)
File "/usr/lib/python2.7/json/__init.py", line 338, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by foxrafi** [comment] 2016-01-18 16:18
Hi, the same here, we receive timeout exceptions

**Comment by lukeis** [comment] 2016-01-18 16:35
the json exception in python is a duplicate issue of #1470 
The not clickable at point issue is a duplicate of #1202 

I'll consider the problem with the firefox profile directory transient and some strange permissions issues occurred on your machine.

**Closed by lukeis** 2016-01-18 16:35 UTC
Labels: C-py, D-firefox

**Comment by caligoig** [comment] 2016-01-18 16:42
This is full stack trace of TimeoutExceptions I am receiving
The exact same code is working when I downgrade to Selenium 2.47.3 and FireFox 42.0 !!! 
Following error is only happening on Selenium 2.49 and FireFox 43

Message: 
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///tmp/tmpgdcv1b1b/extensions/fxdriver@googlecode.com/components/driver-component.js:10659)
    at FirefoxDriver.prototype.findElement (file:///tmp/tmpgdcv1b1b/extensions/fxdriver@googlecode.com/components/driver-component.js:10668)
    at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmpgdcv1b1b/extensions/fxdriver@googlecode.com/components/command-processor.js:12534)
    at DelayedCommand.prototype.executeInternal_ (file:///tmp/tmpgdcv1b1b/extensions/fxdriver@googlecode.com/components/command-processor.js:12539)
    at DelayedCommand.prototype.execute/< (file:///tmp/tmpgdcv1b1b/extensions/fxdriver@googlecode.com/components/command-processor.js:12481)

**Comment by caligoig** [comment] 2016-01-18 16:45
This is the full stack trace of errors I think are related to other json issues users have posted here
Again, the exact same code is working on Selenium 2.47.3 and FireFox 42.0 !!!
Following error is only happening on Selenium 2.49 and FireFox 43

Traceback (most recent call last):
 File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webelement.py", line 75, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webelement.py", line 454, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 102, in check_response
    value = json.loads(value_json)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by schmidtkp** [comment] 2016-01-20 21:20
Getting TIMEOUT error with Firefox v43.0.4 and Selenium v2.49.0 when running in a Selenium grid.  I've been successfully running a Firefox v43.0.4 and Selenium v2.48.2 grid without any issue.

In debugging, I can see the browser being abruptly terminating, somewhat randomly, but rather quickly (i.e. by the 1st or 2nd webdriver.findElement() call), which leads to a false InvalidSelectorException.

The tests and grid being run have been in place for several years. The grid configuration is solid and so is the test/locator.

There is clearly something wrong with v2.49.0.

**Comment by davehunt** [comment] 2016-01-21 09:16
Timeouts are most likely due to https://github.com/SeleniumHQ/selenium/issues/1495.

**Comment by schmidtkp** [comment] 2016-01-21 16:14
Yep… that sure looks like the culprit. Thanks.

From: Dave Hunt
Reply-To: SeleniumHQ/selenium
Date: Thursday, January 21, 2016 at 3:17 AM
To: SeleniumHQ/selenium
Cc: Kendall Schmidt
Subject: Re: [selenium] Update to selenium 2.49 generates an error in Firefox. Was working perfectly in 2.48 (#1482)


Timeouts are most likely due to #1495<https://github.com/SeleniumHQ/selenium/issues/1495>.

**Comment by tuulahdus** [comment] 2016-01-26 10:28
@barancev Upgraded from 2.48.2 to version 2.49.1 and caught the same exception: "Element is not clickable at point (972.5, 371). Other element would receive the click" 
At the same time, the element - dropdown list is fully visible. "Other element" is <td> element which contains clickable element. http://take.ms/YbbWx
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:85)
	at org.openqa.selenium.support.ui.Select.setSelected(Select.java:295)
	at org.openqa.selenium.support.ui.Select.selectByIndex(Select.java:179)

**Comment by timespinner** [comment] 2016-01-26 20:16
We are seeing this as well.  In our case, we are locating a span that is directly centered on top of a button, and attempting to click the span, even after waiting for the element to be clickable, results in the code saying that the button will receive the click rather than the span.  The detection for whether an item is clickable is obviously quite wrong in this new version.  Works fine in Chrome and IE.

**Comment by HardenDev** [comment] 2016-02-17 03:25
So what's the final solution? I've encountered the same issue with Firefox 44.0.2 and Selenium 2.52.0

**Comment by caligoig** [comment] 2016-02-17 03:47
I have downgraded to 2.47.3 Selenium and Firefox 43, nothing else worked for me

**Comment by barancev** [comment] 2016-02-17 04:47
@HardenDev @caligoig For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by ryan-blunden** [comment] 2016-06-13 04:46
For anyone coming to this thread as a result of Firefox 47 crashing on Web Driver initialization

> Selenium WebDriver may cause Firefox to crash on startup, use Marionette Web Driver instead.

See https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver for more info.

I've confirmed that running Firefox Beta and the Marionette Web Driver works with Selenium version 2.53.5 for Python.

The need to run a beta version of Firefox should be resolved when Firefox version 48 is released to the stable channel.

**Comment by msttesting** [comment] 2017-02-06 03:14
Issue with firefox. Download the gecko driver. You need to provide the path of the geckodriver in the script. 
See **[this post](http://www.softwaretestingmaterial.com/launching-firefox-using-gecko-driver/)** for detailed explanation.
