### ISSUE TITLE
Command getLocation throwing Null Pointer Exception [Safari 12]

### ISSUE THREAD

**Issue by krish63** [SeleniumHQ/selenium#6975] opened 2019-02-27 11:42 UTC
## 🐛 Bug Report

While executing the getLocation command on Safari 12 OS X Mojave, **java.lang.NullPointerException** is thrown.

**Exception-**

```
Exception in thread "main" java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebElement.getLocation(RemoteWebElement.java:331)
```

## To Reproduce

1. Create Safari driver instance
2. Open URL
3. Find an element
4. Execute getLocation command

## Expected behavior

Point object shold be returned (for step 4) and Null pointer exception should not thrown.

## Test script or set of commands reproducing this issue

GIST =>  [Safari_getLocation_Test.java](https://gist.github.com/krish63/9add9cc119bf106ca5c4bc7846a8a5fb)

## Environment

OS: MacOS Mojave 10.14.3 (Darwin 18.2.0)
Browser: Safari
Browser version: 12.0.3 (14606.4.5)
Java Verison: Java v1.8
Selenium-Java Binding Version: Java 3.14

**Comment by riticar** [comment] 2019-03-06 23:08
I had the same issue and now I use Safari Technology Preview. Its fixed in that as per the comment in the link below
https://github.com/SeleniumHQ/selenium/issues/6637#issuecomment-438769269

**Comment by barancev** [comment] 2019-03-29 13:08
Duplicate of #6637

**Closed by barancev** 2019-03-29 13:08 UTC
