### ISSUE TITLE
[🐛 Bug]: Getting Error: ECONNRESET read while trying to connect to a Selenium Standalone running on a Docker container on Windows 10 host.

### ISSUE THREAD

**Issue by iliaamiri** [SeleniumHQ/selenium#10205] opened 2021-12-31 03:32 UTC
### What happened?
I am running a Selenium Standalone Server as a Docker container on my Windows 10 host. On my host, I have a Node.js script that uses selenium-webdriver package to connect to this Selenium Server container, but the script constantly returns this error:
```
ECONNRESET read ECONNRESET
    at ClientRequest.<anonymous> (C:\path-to-my-script\node_modules\selenium-webdriver\http\index.js:297:15)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
*Please note that I've added a new line of `console.log(e)` after index.js:279 that makes the line numbers different than the original library. For your information, the output of that line shows:*
```
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
```
### A brief quote about the meaning behind this error:
> "ECONNRESET" means the other side of the TCP conversation abruptly closed its end of the connection.
([citation link](https://www.quora.com/What-does-%E2%80%9CError-read-ECONNRESET%E2%80%9D-mean))
### Using a different Webdriver (PHP Webdriver):
When I use PHP Webdriver from (https://github.com/php-webdriver/php-webdriver), everything works perfectly fine. A new instance of a Firefox browser runs and navigates through the URL I want fully-functional, but when I use this library on Node.js, I only get this error, and the Selenium Server doesn't react to anything (The library cannot make this request, therefore throws this ECONNRESET exception).
### Running this Selenium Docker container on a Linux CentOS 7 host:
When I run this Node.js script to connect to the Selenium Standalone Docker container on a CentOS 7 virtual-machine host, everything works perfectly fine. Therefore, it seems to be a problem with this library communicating with Windows [WSL2](https://docs.microsoft.com/en-us/windows/wsl/about).

## My Node.js Code:
```
const {Builder, By} = require('selenium-webdriver');

(function run(){
    try {
        let driver = await new Builder()
        .forBrowser('firefox')
        .usingServer(`http://localhost:4444/wd/hub`)
        .build();
        
        console.log("Done");
    } catch(e) {
        console.log(e);
    }
await driver.get('https://google.com');
})();
```
## My Selenium Standalone bash script:
`java -jar selenium-server-4.0.0.jar standalone --override-max-sessions true --max-sessions 20 --session-timeout 1800`
## My Dockerfile:
*Link: https://github.com/iliaamiri/selenium-on-Linux-setup-dependencies/blob/main/Dockerfile* 
### Script for Linux host: 
`docker run -it -p 4444:4444 -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix redbolder/selenium_standalone_firefox_centos`
### Script for Windows host:
`docker run -it -p 4445:4444 -e DISPLAY=192.168.1.2:0.0 -v c:/tmp/X11-unix:/tmp/.X11-unix redbolder/selenium_standalone_firefox_centos`

## Every information about the technologies I have mentioned above:
**Selenium Standalone Version:** 4.0.0
**Java Version:** JRE 8u311 Linux x64
**Linux Virtual Host:** CentOS 7 (Core)
**Docker on Linux Virtual Host:** Docker Engine - Community - 20.10.10
**Docker on Windows Host:** Docker Engine - Community - 20.10.11
**Windows Host:** Windows 10 Pro
**Docker Container Operation System:** CentOS 8
**Node.js Version:** 14.17.6

### How can we reproduce the issue?

```shell
Please refer to this Github Repository:
https://github.com/iliaamiri/selenium-webdriver-javascript-ECONNRESET-read-issue
```

### Relevant log output

```shell
Error: ECONNRESET read ECONNRESET
    at ClientRequest.<anonymous> (C:\xampp\htdocs\Github-Repositories\a-web-bot-for-booking-the-closest-possible-appointment-on-ICBC-Driver-Licensing\node_modules\selenium-webdriver\http\index.js:297:15)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

### Operating System

CentOS 8 Docker Container on Windows 10 Host

### Selenium version

Java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 91.4.0esr

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.30.0

**Comment by diemol** [comment] 2022-01-20 14:56
What happens when you use the official Docker images?
https://github.com/seleniumhq/docker-selenium/

**Comment by iliaamiri** [comment] 2022-01-21 03:10
This is so interesting. I tried it and it's the same thing. Everything runs smoothly and perfectly with PHP Webdriver, but when I use the `selenium-webdriver` library in Node.js it has the same behavior (i.e. Gives ECONNRESET error code after a few seconds).

**Comment by pujagani** [comment] 2022-02-18 14:27
Thank you for sharing the details. 
```
The test script shared (https://github.com/iliaamiri/selenium-webdriver-javascript-ECONNRESET-read-issue/blob/main/run.js) does not run. It throws the following error: 
        let driver = await new Builder()
                     ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1026:15)
    at Module._compile (node:internal/modules/cjs/loader:1061:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.3.1
```
So I have used the script below: 
```
const webdriver = require('selenium-webdriver');

const BROWSER_NAME = webdriver.Browser.FIREFOX;

async function getDriver() {
  return new webdriver.Builder()
  .usingServer('http://localhost:4444/wd/hub')
  .forBrowser(BROWSER_NAME)
  .build();
}

async function runTestWithCaps () {
 let driver = await getDriver();
 
 let i=0;
 let pass = 0;
 let fail = 0;
 for(i=0; i <= 2; i++) {
  console.log(i);
  try {
  await driver.get("http://www.google.com");
  await driver.getTitle();

  await driver.getCurrentUrl();
  await driver.getWindowHandle();
  await driver.getPageSource();
  await pass++;
  } catch (e) {
    await fail ++;
    console.log(e);
  }
 }

 console.log("Pass -> " + pass);
 console.log("Fail ->" + fail);

 await driver.quit();
}

  runTestWithCaps(); 
```
Unfortunately, after running it several times against the Selenium Standalone Grid 4.2 jar and using the latest docker image. I  am not able to reproduce it. 
OS: MacOS Big Sur 11.4

A Google search led to this thread https://stackoverflow.com/questions/17245881/how-do-i-debug-error-econnreset-in-node-js. A few people faced the issue due to a particular node version. What node version are you using? Apologies if you have already seen the discussion. I am trying to understand if this is OS specific or Node version-specific issue.

**Comment by iliaamiri** [comment] 2022-02-18 17:27
Hello, 

Oh, I will fix the bug ASAP. Thank you for reporting it.

My Node version is v14.17.6.

I believe this is a problem with Selenium Webdriver (`selenium-webdriver`) module on NPM, because as I said, I can use connect to Selenium from any OS as long as I am using PHP Webdriver (https://github.com/php-webdriver/php-webdriver).

Thank you.

**Comment by iliaamiri** [comment] 2022-02-19 03:14
Hi again @pujagani,

Sorry, I didn't realize the problem until I read your comment later today 😅

Alright, so, I didn't use the default selenium docker image. I'm using my own custom one, because of some other reasons. Also, I haven't gotten this problem on any OS other than Windows and haven't tried it on MacOS either.

But, thank you again for the comment.

**Comment by pujagani** [comment] 2022-02-21 04:19
Thank you for fixing the code snippet and providing the updates. I have a few follow up questions:
1. Can you please try with Selenium standalone jar or the Selenium docker image instead of your custom one?  
2. Does it happen when you run it with the ChromeDriver on your machine instead of using the Grid docker or jar?

I am trying to narrow down the problem area. Since the issue seems to be a tricky one to reproduce. Thank you!

**Comment by diemol** [comment] 2022-04-11 15:49
Closing as we did not get more information.

**Closed as completed by diemol** 2022-04-11 15:49 UTC
Labels: B-grid, J-awaiting answer, C-nodejs, I-defect
