### ISSUE TITLE
NullReferenceException exception thrown when getting browser logs

### ISSUE THREAD

**Issue by richja** [SeleniumHQ/selenium#7323] opened 2019-06-24 16:54 UTC
## 🐛 Bug Report

When trying to get AvailableLogTypes from logs. the NullReferenceException is thrown.

Same happens on Chrome and Firefox.
Basically same issue as reported while ago https://github.com/SeleniumHQ/selenium/issues/5842.

## To Reproduce
Try to get log types `driver.Manage().Logs.AvailableLogTypes`
or browser logs directly `driver.Manage().GetLog(LogType.Browser)`

## Expected behavior
Do not throw an exception.

## Test script or set of commands reproducing this issue

```
ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.SetLoggingPreference(LogType.Browser, LogLevel.All);
_driver = new ChromeDriver(chromeOptions);
_driver.Url = "https://github.com";
var logs = _driver.Manage().Logs;
var logTypes = logs.AvailableLogTypes; //NullReferenceException thrown here
```

## Environment

OS: Windows 10
Browser: Chrome, Firefox
Browser version: Chrome 75.0.3770.100, Firefox 67.0.2
Browser Driver version: ChromeDriver 75.0.3770.90, GeckoDriver 0.24
Language Bindings version: C# 3.141

**Comment by jimevans** [comment] 2019-06-24 17:35
Duplicate of #5842. Fixed in 02203c8 (to be released in the forthcoming 4.0alpha02, release date TBD, no further information available on release time frame).

**Closed by jimevans** 2019-06-24 17:35 UTC

**Comment by alex-jitbit** [comment] 2019-07-14 11:59
driver.Manage().Logs.GetLog(LogType.Browser) also throws NullReference exception, I guess it is the same. Any news about the release date?

**Comment by mmerrell** [comment] 2019-07-14 13:42
The only news we have is what Jim said: "no further information available on release time frame)" :)
MM

**Comment by jimevans** [comment] 2019-07-14 14:35
Having said that, 4.0-alpha2 was released last week, and you can find it via NuGet or at http://selenium-release.storage.googleapis.com
