### ISSUE TITLE
@ symbol copies clipboard data

### ISSUE THREAD

**Issue by bernat97** [SeleniumHQ/selenium#9014] opened 2020-12-30 23:57 UTC
## 🐛 Bug Report

I am working on a django project with python 3.9. I tried to test my app with the latest selenium. I followed this tutorial: https://www.ordinarycoders.com/blog/article/testing-django-selenium

The send_keys() method changes the @ symbol in the test email address to the clipboard data. So if I copy “asd” and than run the tests, I get testasdgmail.com instead of test@gmail.com.

If I copy @ and run the tests afterwards, the tests will pass.

## To Reproduce

Detailed steps to reproduce the behavior:

## Expected behavior

Should be test@gmail.com.

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

class PlayerFormTest(LiveServerTestCase):

	def testform(self):
		selenium = webdriver.Chrome()
		#Choose your url to visit
		selenium.get('http://127.0.0.1:8000/')
		#find the elements you need to submit form
		player_email = selenium.find_element_by_id('id_email')
	

		submit = selenium.find_element_by_id('submit_button')

		#populate the form with data
		player_email.send_keys('test@gmail.com')

		#submit form
		submit.send_keys(Keys.RETURN)

		#check result; page source looks at entire html document
		assert 'test@gmail.com' in selenium.page_source

## Environment

OS: Windows 10
Browser: Chrome
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by AutomatedTester** [comment] 2021-01-11 09:16
Duplicate of #8824

**Closed as completed by AutomatedTester** 2021-01-11 09:16 UTC
Labels: A-needs-triaging
