### ISSUE TITLE
Selenium WebDriver hover() are not working on few elements in Chrome 91, everything working fine up-to chrome 89 || manual hovering working fine

### ISSUE THREAD

**Issue by subrato29** [SeleniumHQ/selenium#9591] opened 2021-06-18 00:49 UTC
## 🐛 Bug Report

Selenium WebDriver hover() are not working on few elements in Chrome 91, everything working fine up-to chrome 89 but manual hovering working fine in Chrome 91.
Ref: https://github.com/SeleniumHQ/selenium/issues/9588

div class="abstract-tooltip-container cFWAbstractTooltip" data-aura-class="cFWAbstractTooltip">
button class="slds-button_neutral slds-button" role="button" aria-label="Select From Dropdown Menu">
/div

Environment
OS: Windows 10
Browser: Chrome
Browser version: 91
Browser Driver version: Compatible with Chrome browser 91
Language Bindings version: Java 1.8
Selenium WebDriver version: 3.141.59

**Comment by diemol** [comment] 2021-06-18 09:29
Duplicate of #9588

**Closed as completed by diemol** 2021-06-18 09:29 UTC
