### ISSUE TITLE
[🐛 Bug]: Since 4.4.0 getting a new ``RemoteWebDriver`` takes a lot longer

### ISSUE THREAD

**Issue by AB-xdev** [SeleniumHQ/selenium#11082] opened 2022-10-04 10:44 UTC
### What happened?

We are using [Testcontainers](https://www.testcontainers.org/modules/webdriver_containers/) in combination with selenium.
When a test is started a selenium container is launched that is controlled by a ``RemoteWebDriver``.

Since we updated to Selenium 4.4.0 it takes a lot longer to get a new ``RemoteWebDriver``. 
On 4.3.0 and 4.2.2 it took 2-3 seconds, since 4.4.0 (also in 4.5.0) it takes >10s.

It looks like sometimes the part of Selenium inside Docker (Selenium Server?) needs more than 10s to respond to the initial request (see logs).

See also: https://github.com/testcontainers/testcontainers-java/issues/5833

### How can we reproduce the issue?

```shell
→ https://github.com/testcontainers/testcontainers-java/issues/5833
```

### Relevant log output

```shell
11:06:28 DEBUG [main] [e.testcases.TestPageShown] Getting WebDriver... 
11:06:28 INFO  [ducttape-1] [metry.OpenTelemetryTracer] Using OpenTelemetry for tracing 
11:06:28 DEBUG [ducttape-1] [ing.InternalLoggerFactory] Using SLF4J as the default logging framework 
11:06:28 DEBUG [ducttape-1] [util.ResourceLeakDetector] -Dio.netty.leakDetection.level: simple 
11:06:28 DEBUG [ducttape-1] [util.ResourceLeakDetector] -Dio.netty.leakDetection.targetRecords: 4 
11:06:28 DEBUG [ducttape-1] [sourceLeakDetectorFactory] Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@b353cf9 
11:06:28 DEBUG [ducttape-1] [ternal.PlatformDependent0] -Dio.netty.noUnsafe: false 
11:06:28 DEBUG [ducttape-1] [ternal.PlatformDependent0] Java version: 17 
11:06:28 DEBUG [ducttape-1] [ternal.PlatformDependent0] sun.misc.Unsafe.theUnsafe: available 
...
11:06:28 DEBUG [ducttape-1] [.netty.buffer.ByteBufUtil] -Dio.netty.maxThreadLocalCharBufferSize: 16384 
11:06:29 DEBUG [Forwarding newSession on session null to remote] [.channel.DefaultChannelId] -Dio.netty.processId: 42544 (auto-detected) 
11:06:29 DEBUG [Forwarding newSession on session null to remote] [io.netty.util.NetUtil    ] -Djava.net.preferIPv4Stack: false 
11:06:29 DEBUG [Forwarding newSession on session null to remote] [io.netty.util.NetUtil    ] -Djava.net.preferIPv6Addresses: false 
11:06:29 DEBUG [Forwarding newSession on session null to remote] [il.NetUtilInitializations] Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1) 
11:06:29 DEBUG [Forwarding newSession on session null to remote] [io.netty.util.NetUtil    ] Failed to get SOMAXCONN from sysctl and file \proc\sys\net\core\somaxconn. Default: 200 
11:06:29 DEBUG [Forwarding newSession on session null to remote] [.channel.DefaultChannelId] -Dio.netty.machineId: 00:d8:61:ff:fe:d4:70:fb (auto-detected) 
11:06:29 DEBUG [AsyncHttpClient-1-2] [ty.buffer.AbstractByteBuf] -Dio.netty.buffer.checkAccessible: true 
11:06:29 DEBUG [AsyncHttpClient-1-2] [ty.buffer.AbstractByteBuf] -Dio.netty.buffer.checkBounds: true 
11:06:29 DEBUG [AsyncHttpClient-1-2] [sourceLeakDetectorFactory] Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@462ed7c7 
11:06:29 TRACE [AsyncHttpClient-1-2] [er.logging.LoggingHandler] [id: 0xafb917bd] REGISTERED 
11:06:29 TRACE [AsyncHttpClient-1-2] [er.logging.LoggingHandler] [id: 0xafb917bd] CONNECT: localhost/127.0.0.1:55480 
11:06:29 DEBUG [AsyncHttpClient-1-2] [nnel.NettyConnectListener] Using new Channel '[id: 0xafb917bd, L:/127.0.0.1:55484 - R:localhost/127.0.0.1:55480]' for 'POST' to '/wd/hub/session' 
11:06:29 DEBUG [AsyncHttpClient-1-2] [io.netty.util.Recycler   ] -Dio.netty.recycler.maxCapacityPerThread: 4096 
11:06:29 DEBUG [AsyncHttpClient-1-2] [io.netty.util.Recycler   ] -Dio.netty.recycler.ratio: 8 
11:06:29 DEBUG [AsyncHttpClient-1-2] [io.netty.util.Recycler   ] -Dio.netty.recycler.chunkSize: 32 
11:06:29 DEBUG [AsyncHttpClient-1-2] [io.netty.util.Recycler   ] -Dio.netty.recycler.blocking: false 
11:06:29 TRACE [AsyncHttpClient-1-2] [er.logging.LoggingHandler] [id: 0xafb917bd, L:/127.0.0.1:55484 - R:localhost/127.0.0.1:55480] WRITE: 250B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 50 4f 53 54 20 2f 77 64 2f 68 75 62 2f 73 65 73 |POST /wd/hub/ses|
|00000010| 73 69 6f 6e 20 48 54 54 50 2f 31 2e 31 0d 0a 55 |sion HTTP/1.1..U|
|00000020| 73 65 72 2d 41 67 65 6e 74 3a 20 73 65 6c 65 6e |ser-Agent: selen|
|00000030| 69 75 6d 2f 34 2e 34 2e 30 20 28 6a 61 76 61 20 |ium/4.4.0 (java |
|00000040| 77 69 6e 64 6f 77 73 29 0d 0a 74 72 61 63 65 70 |windows)..tracep|
|00000050| 61 72 65 6e 74 3a 20 30 30 2d 36 32 37 64 31 39 |arent: 00-627d19|
|00000060| 63 64 37 31 36 37 34 36 63 33 33 30 62 34 65 39 |cd716746c330b4e9|
|00000070| 63 32 35 31 64 37 32 61 37 33 2d 30 65 35 65 64 |c251d72a73-0e5ed|
|00000080| 30 36 37 66 35 66 36 39 65 62 61 2d 30 31 0d 0a |067f5f69eba-01..|
|00000090| 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 3a 20 |Content-Length: |
|000000a0| 33 38 31 0d 0a 43 6f 6e 74 65 6e 74 2d 54 79 70 |381..Content-Typ|
|000000b0| 65 3a 20 61 70 70 6c 69 63 61 74 69 6f 6e 2f 6a |e: application/j|
|000000c0| 73 6f 6e 3b 20 63 68 61 72 73 65 74 3d 75 74 66 |son; charset=utf|
|000000d0| 2d 38 0d 0a 68 6f 73 74 3a 20 6c 6f 63 61 6c 68 |-8..host: localh|
|000000e0| 6f 73 74 3a 35 35 34 38 30 0d 0a 61 63 63 65 70 |ost:55480..accep|
|000000f0| 74 3a 20 2a 2f 2a 0d 0a 0d 0a                   |t: */*....      |
+--------+-------------------------------------------------+----------------+ 
11:06:29 TRACE [AsyncHttpClient-1-2] [er.logging.LoggingHandler] [id: 0xafb917bd, L:/127.0.0.1:55484 - R:localhost/127.0.0.1:55480] WRITE: 381B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 7b 0a 20 20 22 64 65 73 69 72 65 64 43 61 70 61 |{.  "desiredCapa|
|00000010| 62 69 6c 69 74 69 65 73 22 3a 20 7b 0a 20 20 20 |bilities": {.   |
|00000020| 20 22 62 72 6f 77 73 65 72 4e 61 6d 65 22 3a 20 | "browserName": |
|00000030| 22 66 69 72 65 66 6f 78 22 2c 0a 20 20 20 20 22 |"firefox",.    "|
|00000040| 6d 6f 7a 3a 64 65 62 75 67 67 65 72 41 64 64 72 |moz:debuggerAddr|
|00000050| 65 73 73 22 3a 20 74 72 75 65 2c 0a 20 20 20 20 |ess": true,.    |
|00000060| 22 6d 6f 7a 3a 66 69 72 65 66 6f 78 4f 70 74 69 |"moz:firefoxOpti|
|00000070| 6f 6e 73 22 3a 20 7b 0a 20 20 20 20 7d 2c 0a 20 |ons": {.    },. |
|00000080| 20 20 20 22 61 63 63 65 70 74 49 6e 73 65 63 75 |   "acceptInsecu|
|00000090| 72 65 43 65 72 74 73 22 3a 20 74 72 75 65 0a 20 |reCerts": true. |
|000000a0| 20 7d 2c 0a 20 20 22 63 61 70 61 62 69 6c 69 74 | },.  "capabilit|
|000000b0| 69 65 73 22 3a 20 7b 0a 20 20 20 20 22 66 69 72 |ies": {.    "fir|
|000000c0| 73 74 4d 61 74 63 68 22 3a 20 5b 0a 20 20 20 20 |stMatch": [.    |
|000000d0| 20 20 7b 0a 20 20 20 20 20 20 20 20 22 61 63 63 |  {.        "acc|
|000000e0| 65 70 74 49 6e 73 65 63 75 72 65 43 65 72 74 73 |eptInsecureCerts|
|000000f0| 22 3a 20 74 72 75 65 2c 0a 20 20 20 20 20 20 20 |": true,.       |
|00000100| 20 22 62 72 6f 77 73 65 72 4e 61 6d 65 22 3a 20 | "browserName": |
|00000110| 22 66 69 72 65 66 6f 78 22 2c 0a 20 20 20 20 20 |"firefox",.     |
|00000120| 20 20 20 22 6d 6f 7a 3a 64 65 62 75 67 67 65 72 |   "moz:debugger|
|00000130| 41 64 64 72 65 73 73 22 3a 20 74 72 75 65 2c 0a |Address": true,.|
|00000140| 20 20 20 20 20 20 20 20 22 6d 6f 7a 3a 66 69 72 |        "moz:fir|
|00000150| 65 66 6f 78 4f 70 74 69 6f 6e 73 22 3a 20 7b 0a |efoxOptions": {.|
|00000160| 20 20 20 20 20 20 20 20 7d 0a 20 20 20 20 20 20 |        }.      |
|00000170| 7d 0a 20 20 20 20 5d 0a 20 20 7d 0a 7d          |}.    ].  }.}   |
+--------+-------------------------------------------------+----------------+ 
11:06:29 TRACE [AsyncHttpClient-1-2] [er.logging.LoggingHandler] [id: 0xafb917bd, L:/127.0.0.1:55484 - R:localhost/127.0.0.1:55480] FLUSH 
11:06:29 TRACE [AsyncHttpClient-1-2] [er.logging.LoggingHandler] [id: 0xafb917bd, L:/127.0.0.1:55484 - R:localhost/127.0.0.1:55480] WRITE: 0B 
11:06:29 TRACE [AsyncHttpClient-1-2] [er.logging.LoggingHandler] [id: 0xafb917bd, L:/127.0.0.1:55484 - R:localhost/127.0.0.1:55480] FLUSH 
11:06:29 TRACE [AsyncHttpClient-1-2] [er.logging.LoggingHandler] [id: 0xafb917bd, L:/127.0.0.1:55484 - R:localhost/127.0.0.1:55480] ACTIVE 
11:06:38 TRACE [ducttape-0] [e.unreliables.Unreliables] Retrying lambda call on attempt 0 
11:06:38 TRACE [AsyncHttpClient-1-3] [er.logging.LoggingHandler] [id: 0x228976cf] REGISTERED 
11:06:38 TRACE [AsyncHttpClient-1-3] [er.logging.LoggingHandler] [id: 0x228976cf] CONNECT: localhost/127.0.0.1:55480 
11:06:38 DEBUG [AsyncHttpClient-1-3] [nnel.NettyConnectListener] Using new Channel '[id: 0x228976cf, L:/127.0.0.1:55486 - R:localhost/127.0.0.1:55480]' for 'POST' to '/wd/hub/session' 
11:06:38 TRACE [AsyncHttpClient-1-3] [er.logging.LoggingHandler] [id: 0x228976cf, L:/127.0.0.1:55486 - R:localhost/127.0.0.1:55480] WRITE: 250B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 50 4f 53 54 20 2f 77 64 2f 68 75 62 2f 73 65 73 |POST /wd/hub/ses|
|00000010| 73 69 6f 6e 20 48 54 54 50 2f 31 2e 31 0d 0a 55 |sion HTTP/1.1..U|
|00000020| 73 65 72 2d 41 67 65 6e 74 3a 20 73 65 6c 65 6e |ser-Agent: selen|
|00000030| 69 75 6d 2f 34 2e 34 2e 30 20 28 6a 61 76 61 20 |ium/4.4.0 (java |
|00000040| 77 69 6e 64 6f 77 73 29 0d 0a 74 72 61 63 65 70 |windows)..tracep|
|00000050| 61 72 65 6e 74 3a 20 30 30 2d 38 35 65 32 61 33 |arent: 00-85e2a3|
|00000060| 39 61 63 35 37 32 35 65 37 38 61 64 33 35 32 61 |9ac5725e78ad352a|
|00000070| 33 34 31 34 38 31 37 61 64 66 2d 61 31 39 38 39 |3414817adf-a1989|
|00000080| 34 61 62 62 35 62 34 38 36 64 61 2d 30 31 0d 0a |4abb5b486da-01..|
|00000090| 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 3a 20 |Content-Length: |
|000000a0| 33 38 31 0d 0a 43 6f 6e 74 65 6e 74 2d 54 79 70 |381..Content-Typ|
|000000b0| 65 3a 20 61 70 70 6c 69 63 61 74 69 6f 6e 2f 6a |e: application/j|
|000000c0| 73 6f 6e 3b 20 63 68 61 72 73 65 74 3d 75 74 66 |son; charset=utf|
|000000d0| 2d 38 0d 0a 68 6f 73 74 3a 20 6c 6f 63 61 6c 68 |-8..host: localh|
|000000e0| 6f 73 74 3a 35 35 34 38 30 0d 0a 61 63 63 65 70 |ost:55480..accep|
|000000f0| 74 3a 20 2a 2f 2a 0d 0a 0d 0a                   |t: */*....      |
+--------+-------------------------------------------------+----------------+ 
11:06:38 TRACE [AsyncHttpClient-1-3] [er.logging.LoggingHandler] [id: 0x228976cf, L:/127.0.0.1:55486 - R:localhost/127.0.0.1:55480] WRITE: 381B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 7b 0a 20 20 22 64 65 73 69 72 65 64 43 61 70 61 |{.  "desiredCapa|
|00000010| 62 69 6c 69 74 69 65 73 22 3a 20 7b 0a 20 20 20 |bilities": {.   |
|00000020| 20 22 62 72 6f 77 73 65 72 4e 61 6d 65 22 3a 20 | "browserName": |
|00000030| 22 66 69 72 65 66 6f 78 22 2c 0a 20 20 20 20 22 |"firefox",.    "|
|00000040| 6d 6f 7a 3a 64 65 62 75 67 67 65 72 41 64 64 72 |moz:debuggerAddr|
|00000050| 65 73 73 22 3a 20 74 72 75 65 2c 0a 20 20 20 20 |ess": true,.    |
|00000060| 22 6d 6f 7a 3a 66 69 72 65 66 6f 78 4f 70 74 69 |"moz:firefoxOpti|
|00000070| 6f 6e 73 22 3a 20 7b 0a 20 20 20 20 7d 2c 0a 20 |ons": {.    },. |
|00000080| 20 20 20 22 61 63 63 65 70 74 49 6e 73 65 63 75 |   "acceptInsecu|
|00000090| 72 65 43 65 72 74 73 22 3a 20 74 72 75 65 0a 20 |reCerts": true. |
|000000a0| 20 7d 2c 0a 20 20 22 63 61 70 61 62 69 6c 69 74 | },.  "capabilit|
|000000b0| 69 65 73 22 3a 20 7b 0a 20 20 20 20 22 66 69 72 |ies": {.    "fir|
|000000c0| 73 74 4d 61 74 63 68 22 3a 20 5b 0a 20 20 20 20 |stMatch": [.    |
|000000d0| 20 20 7b 0a 20 20 20 20 20 20 20 20 22 61 63 63 |  {.        "acc|
|000000e0| 65 70 74 49 6e 73 65 63 75 72 65 43 65 72 74 73 |eptInsecureCerts|
|000000f0| 22 3a 20 74 72 75 65 2c 0a 20 20 20 20 20 20 20 |": true,.       |
|00000100| 20 22 62 72 6f 77 73 65 72 4e 61 6d 65 22 3a 20 | "browserName": |
|00000110| 22 66 69 72 65 66 6f 78 22 2c 0a 20 20 20 20 20 |"firefox",.     |
|00000120| 20 20 20 22 6d 6f 7a 3a 64 65 62 75 67 67 65 72 |   "moz:debugger|
|00000130| 41 64 64 72 65 73 73 22 3a 20 74 72 75 65 2c 0a |Address": true,.|
|00000140| 20 20 20 20 20 20 20 20 22 6d 6f 7a 3a 66 69 72 |        "moz:fir|
|00000150| 65 66 6f 78 4f 70 74 69 6f 6e 73 22 3a 20 7b 0a |efoxOptions": {.|
|00000160| 20 20 20 20 20 20 20 20 7d 0a 20 20 20 20 20 20 |        }.      |
|00000170| 7d 0a 20 20 20 20 5d 0a 20 20 7d 0a 7d          |}.    ].  }.}   |
+--------+-------------------------------------------------+----------------+ 
11:06:38 TRACE [AsyncHttpClient-1-3] [er.logging.LoggingHandler] [id: 0x228976cf, L:/127.0.0.1:55486 - R:localhost/127.0.0.1:55480] FLUSH 
11:06:38 TRACE [AsyncHttpClient-1-3] [er.logging.LoggingHandler] [id: 0x228976cf, L:/127.0.0.1:55486 - R:localhost/127.0.0.1:55480] WRITE: 0B 
11:06:38 TRACE [AsyncHttpClient-1-3] [er.logging.LoggingHandler] [id: 0x228976cf, L:/127.0.0.1:55486 - R:localhost/127.0.0.1:55480] FLUSH 
11:06:38 TRACE [AsyncHttpClient-1-3] [er.logging.LoggingHandler] [id: 0x228976cf, L:/127.0.0.1:55486 - R:localhost/127.0.0.1:55480] ACTIVE 
11:06:41 DEBUG [docker-java-stream-1229649897] [ache.hc.client5.http.wire] http-outgoing-4 << "e5[\r][\n]" 
11:06:41 DEBUG [docker-java-stream-1229649897] [ache.hc.client5.http.wire] http-outgoing-4 << "[0x1][0x0][0x0][0x0][0x0][0x0][0x0]`11:06:41.894 INFO [LocalDistributor.newSession] - Session request received by the Distributor: [\n]" 
11:06:41 DEBUG [docker-java-stream-1229649897] [ache.hc.client5.http.wire] http-outgoing-4 << "[0x1][0x0][0x0][0x0][0x0][0x0][0x0]u [Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}}][\n]" 
11:06:41 DEBUG [docker-java-stream-1229649897] [ache.hc.client5.http.wire] http-outgoing-4 << "[\r][\n]" 
11:06:41 INFO  [docker-java-stream-1229649897] [ontainer.browserwebdriver] STDOUT: 11:06:41.894 INFO [LocalDistributor.newSession] - Session request received by the Distributor:  
11:06:41 INFO  [docker-java-stream-1229649897] [ontainer.browserwebdriver] STDOUT:  [Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}}] 
11:06:41 DEBUG [docker-java-stream-1229649897] [ache.hc.client5.http.wire] http-outgoing-4 << "e5[\r][\n]" 

See also https://github.com/testcontainers/testcontainers-java/issues/5833#issuecomment-1243352747
```

### Operating System

Server: Docker/Linux; Java-Client: OS independent

### Selenium version

Java 4.4.0 / 4.5.0

### What are the browser(s) and version(s) where you see this issue?

The related Chrome and Firefox docker images of the above selenium version

### What are the browser driver(s) and version(s) where you see this issue?

The related Chrome and Firefox docker images of the above selenium version

**Comment by titusfortner** [comment] 2022-10-04 12:21
Thanks. This is a duplicate of #10984

**Closed as completed by titusfortner** 2022-10-04 12:21 UTC
Labels: I-defect, A-needs-triaging
