### ISSUE TITLE
OutOfMemoryError on session creation caused by large JSON

### ISSUE THREAD

**Issue by aekrylov** [SeleniumHQ/selenium#7624] opened 2019-10-01 09:15 UTC
## 🐛 Bug Report

We run Selenium tests in Maven using Junit and RemoteWebDriver, and sometimes it fails with OutOfMemory error. We got a heap dump of one of the failed builds, and Eclipse Memory Analyzer shows that heap space is 95+% occupied by two char arrays. These two arrays look like this:

```
{\u000a  "desiredCapabilities": {\u000a    "acceptInsecureCerts": true,\u000a    "browserName": "firefox",\u000a    "enableLog": false,\u000a    "enableVNC": true,\u000a    "loggingPrefs": {\u000a      "browser": "ALL"\u000a    },\u000a    "enableLog": false,\u000a    "enableVNC": true,\u000a    "loggingPrefs": {\u000a      "browser": "ALL"\u000a    },\u000a    "enableLog": false,\u000a    "enableVNC": true,\u000a    "loggingPrefs": {\u000a      "browser": "ALL"\u000a    },\u000a    "enableLog": false,\u000a    "enableVNC": true,\u000a    "loggingPrefs": {\u000a      "browser": "ALL"\u000a    },\u000a    "enableLog": false,\u000a    "enableVNC": true,\u000a    "loggingPrefs": {\u000a      "browser": "ALL"\u000a    },\u000a    "enableLog": false,\u000a    "enableVNC": true,\u000a    "loggingPrefs": {\u000a      "browser": "ALL"\u000a    },\u000a    "enableLog": false,\u000a    "enableVNC": true,\u000a    "loggingPrefs": {\u000a      "browser": "ALL"\u000a    },\u000a    "enableLog": false,\u000a    "enableVNC": true,\u000a    "loggingPrefs": {\u000a      "browser": "ALL"\u000a    },\u000a    "enableLog": false,\u000a    "enableVNC": true,\u000a    "loggingPrefs": {\u000a      "browser": "ALL"\u000a    },\u000a    "enableLog": false,\u000a    "enableVNC": ...
```

and contain both around 300M characters (Xmx is 1024m). 

[Here ](https://gist.github.com/aekrylov/3517bd168845d3dd96515c8cffa389e4) is a gist with relevant Java code and thread stacktrace from the dump

## To Reproduce

This happens randomly, looks like mostly with Firefox and not Chrome. Capabilities are set up like this:

```java
@RunWith(Parameterized.class)
public abstract class BaseTest {
  protected static final String gridUrl = System.getProperty("selenium.grid.url");
  protected final WebDriver browser;
  protected final DesiredCapabilities capability;

  public BaseTest(DesiredCapabilities capability) throws MalformedURLException {
    this.capability = capability;
    LoggingPreferences logPrefs = new LoggingPreferences();
    logPrefs.enable(LogType.BROWSER, Level.ALL);
      capability.setCapability(CapabilityType.LOGGING_PREFS, logPrefs);
      capability.setCapability("enableLog", System.getProperty("enableLog") != null);
      capability.setCapability("enableVNC", System.getProperty("enableVNC") != null);

    RemoteWebDriver remoteDriver = new RemoteWebDriver(new URL(gridUrl), capability); 
    browser = new Augmenter().augment(remoteDriver);
  }

  @Parameterized.Parameters(name = "{index}: {0}")
  public static LinkedList<DesiredCapabilities[]> getBrowsers() {
    LinkedList<DesiredCapabilities[]> browsers = new LinkedList<>();
      browsers.add(new DesiredCapabilities[] {DesiredCapabilities.chrome()});
      browsers.add(new DesiredCapabilities[] {DesiredCapabilities.firefox()});
    return browsers;
  }
}
```

## Environment

OS: Debian 9.9 stretch
Browser: Firefox
Browser version: 69.0
Browser Driver version: GeckoDriver 0.24.0
Language Bindings version: Java 3.141.0

**Comment by barancev** [comment] 2019-10-05 21:17
Can you please add some details:
1) What part drains the memory -- selenium server or the test?
2) Do you run many tests in parallel or sequentially? Do you run many tests at all? Or a single "unlucky" test hits this failure?

**Comment by barancev** [comment] 2019-10-05 21:23
Can you create and attach a complete sample project that allows to reproduce the issue? In particular it's important to know how do you initialize and finalize the tests.

**Comment by aekrylov** [comment] 2019-10-10 11:59
1. It's the test that runs out of memory
2. We run around 190 tests in total, with up to 10 parallel browser sessions. Sometimes a number of tests fail for this reason, all the other ones pass. Seems like errors are in random tests, 

Here's a minimal project: https://github.com/aekrylov/selenium-7624

**Comment by barancev** [comment] 2019-11-17 18:46
I tried to run tests in the provided sample project in various modes but I could not reproduce the issue. 

We need a better instruction how to achieve the described failure.

According to the stacktrace, you're using RemoteWebDriver and the problem occurs when you create a new session payload. The provided sample project does not use RemoteWebDriver. Can you show a failure log that you've got from this sample project?

**Comment by AutomatedTester** [comment] 2020-03-19 09:56
Closing as requested info was not given

**Closed by AutomatedTester** 2020-03-19 09:56 UTC
Labels: C-grid, C-java, R-awaiting answer
