### ISSUE TITLE
After firefox update, Perform automation, In Search bar the given URL is not loaded.

### ISSUE THREAD

**Issue by vimalvenkat** [SeleniumHQ/selenium#2412] opened 2016-06-30 08:59 UTC
I just updated my firefox browser to 47.0.1. After this update, While automating the selenium scripts. The Browser launches, but doesnot load the URL given in scripts.
Selenium jars used before update was 2.48 and updated it to 2.53.0..

**Comment by sandeepjain1987** [comment] 2016-06-30 14:24
Duplicate of #2110

**Comment by AutomatedTester** [comment] 2016-06-30 14:45
have you got the latest version of Selenium, there was an issue with the FirefoxDriver

**Comment by sandeepjain1987** [comment] 2016-06-30 14:47
Hi @AutomatedTester , Is there any date on defect 2110 fix or for FF 47-selenium compatibility ?

**Comment by AutomatedTester** [comment] 2016-06-30 14:57
Firefox 47.0.1 was released and most, if not all, of the clients have been updated to work with it.

**Closed by AutomatedTester** 2016-06-30 14:57 UTC

**Comment by jimevans** [comment] 2016-06-30 14:58
@sandeepjain1987 https://groups.google.com/forum/#!topic/selenium-users/f6bXeRAnGWM

**Comment by sandeepjain1987** [comment] 2016-06-30 16:22
Thanks @jimevans  @AutomatedTester  for the update. You guys saved my day!
