### ISSUE TITLE
Issue in Multiple file upload

### ISSUE THREAD

**Issue by heyitsmesuraj** [SeleniumHQ/selenium#5079] opened 2017-11-20 07:23 UTC
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2024&can=2&start=0&num=100&q=&colspec=ID%20Status%20Pri%20Owner%20Summary&groupby=&sort=

**Comment by barancev** [comment] 2017-11-20 07:26
Duplicate of #3096

**Closed by barancev** 2017-11-20 07:26 UTC

**Comment by heyitsmesuraj** [comment] 2017-11-20 11:22
But not working in Selenium grid

**Comment by heyitsmesuraj** [comment] 2017-11-20 11:25
Code:
SendKeys(C:\selenium\Documents\Test.txt
C:\selenium\Documents\Test 2.txt);

WebDriver.dll but was not handled in user code

Additional information: invalid argument: File not found : C:\selenium\Documents\Test.txt

  (Session info: chrome=62.0.3202.94)

  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64) (ExpectedError)
