### ISSUE TITLE
Can not use any version of Selenium 3.4.0 with Firefox if test is using window/tab swith

### ISSUE THREAD

**Issue by DavidGangel** [SeleniumHQ/selenium#5834] opened 2018-04-26 10:26 UTC
This is my last trial to point the attention over to this bug:
https://github.com/SeleniumHQ/selenium/issues/5064

Because of the referenced issue we can not upgrade Selenium to any version above 3.4.0 without loosing Firefox browser to run our test cases.

All programming language bindings are affected when running tests on Remote.

**Comment by cgoldberg** [comment] 2018-04-26 16:46
duplicate of #5064

**Closed by cgoldberg** 2018-04-26 16:46 UTC

**Comment by DavidGangel** [comment] 2018-04-26 16:50
@cgoldberg I understand this is a duplicate, but after suffering this issue almost over for half a year, can someone please fix it?

**Comment by cgoldberg** [comment] 2018-04-26 17:05
> I understand this is a duplicate

please don't pollute the issue tracker with dups.

> can someone please fix it?

to expedite, you could diagnose the issue and submit a Pull Request with a fix.
