### ISSUE TITLE
Duplicate filename in selenium-java-4.6.0.zip [🐛 Bug]: 

### ISSUE THREAD

**Issue by wuyongzheng** [SeleniumHQ/selenium#11259] opened 2022-11-13 01:21 UTC
### What happened?

I downloaded the selenium Java version from https://www.selenium.dev/downloads/. The linux unzip tool complains about duplicated file name. I tried 7zip on Windows, same problem. I remember I had this problem in selenium 4.3.0 as well. I'm surprised that this hasn't been fixed for a year.

### How can we reproduce the issue?

```shell
$ wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.6.0/selenium-java-4.6.0.zip
$ unzip -q selenium-java-4.6.0.zip
replace lib/netty-transport-native-epoll-4.1.84.Final.jar? [y]es, [n]o, [A]ll, [N]one, [r]ename: r
new name: lib/netty-transport-native-epoll-4.1.84.Final.jar.1
replace lib/netty-transport-native-kqueue-4.1.84.Final.jar? [y]es, [n]o, [A]ll, [N]one, [r]ename: r
new name: lib/netty-transport-native-kqueue-4.1.84.Final.jar.1
replace lib/netty-transport-native-kqueue-4.1.84.Final.jar? [y]es, [n]o, [A]ll, [N]one, [r]ename: r
new name: lib/netty-transport-native-kqueue-4.1.84.Final.jar.1
replace lib/netty-transport-native-kqueue-4.1.84.Final.jar.1? [y]es, [n]o, [A]ll, [N]one, [r]ename: r
new name: lib/netty-transport-native-kqueue-4.1.84.Final.jar.2
```

### Relevant log output

```shell
$ sha1sum selenium-java-4.6.0.zip
18375980f47bedbe86eb5197af8e2d62a38bdc72  selenium-java-4.6.0.zip
$ unzip -l selenium-java-4.6.0.zip
Archive:  selenium-java-4.6.0.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
   147718  01-01-2010 00:00   CHANGELOG
    11365  01-01-2010 00:00   LICENSE
       89  01-01-2010 00:00   NOTICE
   172062  01-01-2010 00:00   selenium-api-4.6.0-sources.jar
   220240  01-01-2010 00:00   selenium-api-4.6.0.jar
    10285  01-01-2010 00:00   selenium-chrome-driver-4.6.0-sources.jar
    15149  01-01-2010 00:00   selenium-chrome-driver-4.6.0.jar
    20656  01-01-2010 00:00   selenium-chromium-driver-4.6.0-sources.jar
    29368  01-01-2010 00:00   selenium-chromium-driver-4.6.0.jar
   612668  01-01-2010 00:00   selenium-devtools-v105-4.6.0-sources.jar
  1444425  01-01-2010 00:00   selenium-devtools-v105-4.6.0.jar
   615661  01-01-2010 00:00   selenium-devtools-v106-4.6.0-sources.jar
  1451229  01-01-2010 00:00   selenium-devtools-v106-4.6.0.jar
   615686  01-01-2010 00:00   selenium-devtools-v107-4.6.0-sources.jar
  1451560  01-01-2010 00:00   selenium-devtools-v107-4.6.0.jar
   477528  01-01-2010 00:00   selenium-devtools-v85-4.6.0-sources.jar
  1136660  01-01-2010 00:00   selenium-devtools-v85-4.6.0.jar
     8774  01-01-2010 00:00   selenium-edge-driver-4.6.0-sources.jar
    13354  01-01-2010 00:00   selenium-edge-driver-4.6.0.jar
    60898  01-01-2010 00:00   selenium-firefox-driver-4.6.0-sources.jar
   113097  01-01-2010 00:00   selenium-firefox-driver-4.6.0.jar
    31263  01-01-2010 00:00   selenium-http-4.6.0-sources.jar
    59055  01-01-2010 00:00   selenium-http-4.6.0.jar
    11557  01-01-2010 00:00   selenium-ie-driver-4.6.0-sources.jar
    17276  01-01-2010 00:00   selenium-ie-driver-4.6.0.jar
      288  01-01-2010 00:00   selenium-java-4.6.0-sources.jar
      606  01-01-2010 00:00   selenium-java-4.6.0.jar
    35740  01-01-2010 00:00   selenium-json-4.6.0-sources.jar
    69249  01-01-2010 00:00   selenium-json-4.6.0.jar
     2697  01-01-2010 00:00   selenium-manager-4.6.0-sources.jar
  4198449  01-01-2010 00:00   selenium-manager-4.6.0.jar
   263912  01-01-2010 00:00   selenium-remote-driver-4.6.0-sources.jar
   452298  01-01-2010 00:00   selenium-remote-driver-4.6.0.jar
    14942  01-01-2010 00:00   selenium-safari-driver-4.6.0-sources.jar
    24799  01-01-2010 00:00   selenium-safari-driver-4.6.0.jar
    85374  01-01-2010 00:00   selenium-support-4.6.0-sources.jar
   198580  01-01-2010 00:00   selenium-support-4.6.0.jar
   451655  01-01-2010 00:00   lib/async-http-client-2.12.3.jar
     9939  01-01-2010 00:00   lib/async-http-client-netty-utils-2.12.3.jar
   111326  01-01-2010 00:00   lib/auto-common-1.2.1.jar
    12617  01-01-2010 00:00   lib/auto-service-1.0.1.jar
     3174  01-01-2010 00:00   lib/auto-service-annotations-1.0.1.jar
  3952540  01-01-2010 00:00   lib/byte-buddy-1.12.18.jar
   208835  01-01-2010 00:00   lib/checker-qual-3.12.0.jar
    54423  01-01-2010 00:00   lib/commons-exec-1.3.jar
    15979  01-01-2010 00:00   lib/error_prone_annotations-2.11.0.jar
   141332  01-01-2010 00:00   lib/failsafe-3.3.0.jar
     4617  01-01-2010 00:00   lib/failureaccess-1.0.1.jar
  2959479  01-01-2010 00:00   lib/guava-31.1-jre.jar
     8781  01-01-2010 00:00   lib/j2objc-annotations-1.3.jar
    68453  01-01-2010 00:00   lib/jakarta.activation-1.2.2.jar
    88407  01-01-2010 00:00   lib/jcommander-1.82.jar
    19936  01-01-2010 00:00   lib/jsr305-3.0.2.jar
    24744  01-01-2010 00:00   lib/jtoml-2.0.0.jar
     2199  01-01-2010 00:00   lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
   304671  01-01-2010 00:00   lib/netty-buffer-4.1.84.Final.jar
   342911  01-01-2010 00:00   lib/netty-codec-4.1.84.Final.jar
   649082  01-01-2010 00:00   lib/netty-codec-http-4.1.84.Final.jar
   120059  01-01-2010 00:00   lib/netty-codec-socks-4.1.84.Final.jar
   653882  01-01-2010 00:00   lib/netty-common-4.1.84.Final.jar
   540222  01-01-2010 00:00   lib/netty-handler-4.1.84.Final.jar
    24768  01-01-2010 00:00   lib/netty-handler-proxy-4.1.84.Final.jar
    21842  01-01-2010 00:00   lib/netty-reactive-streams-2.0.4.jar
    37776  01-01-2010 00:00   lib/netty-resolver-4.1.84.Final.jar
   487628  01-01-2010 00:00   lib/netty-transport-4.1.84.Final.jar
   142068  01-01-2010 00:00   lib/netty-transport-classes-epoll-4.1.84.Final.jar
   108040  01-01-2010 00:00   lib/netty-transport-classes-kqueue-4.1.84.Final.jar
    37906  01-01-2010 00:00   lib/netty-transport-native-epoll-4.1.84.Final.jar
     5594  01-01-2010 00:00   lib/netty-transport-native-epoll-4.1.84.Final.jar
    25068  01-01-2010 00:00   lib/netty-transport-native-kqueue-4.1.84.Final.jar
    26103  01-01-2010 00:00   lib/netty-transport-native-kqueue-4.1.84.Final.jar
     5621  01-01-2010 00:00   lib/netty-transport-native-kqueue-4.1.84.Final.jar
    43688  01-01-2010 00:00   lib/netty-transport-native-unix-common-4.1.84.Final.jar
   127675  01-01-2010 00:00   lib/opentelemetry-api-1.19.0.jar
    10731  01-01-2010 00:00   lib/opentelemetry-api-logs-1.19.0-alpha.jar
    45617  01-01-2010 00:00   lib/opentelemetry-context-1.19.0.jar
    86452  01-01-2010 00:00   lib/opentelemetry-exporter-common-1.19.0.jar
     7144  01-01-2010 00:00   lib/opentelemetry-exporter-logging-1.19.0.jar
     5173  01-01-2010 00:00   lib/opentelemetry-sdk-1.19.0.jar
    35430  01-01-2010 00:00   lib/opentelemetry-sdk-common-1.19.0.jar
    51937  01-01-2010 00:00   lib/opentelemetry-sdk-extension-autoconfigure-1.19.0-alpha.jar
    11497  01-01-2010 00:00   lib/opentelemetry-sdk-extension-autoconfigure-spi-1.19.0.jar
    43916  01-01-2010 00:00   lib/opentelemetry-sdk-logs-1.19.0-alpha.jar
   283728  01-01-2010 00:00   lib/opentelemetry-sdk-metrics-1.19.0.jar
   115355  01-01-2010 00:00   lib/opentelemetry-sdk-trace-1.19.0.jar
    32067  01-01-2010 00:00   lib/opentelemetry-semconv-1.19.0-alpha.jar
    11640  01-01-2010 00:00   lib/reactive-streams-1.0.4.jar
    61409  01-01-2010 00:00   lib/slf4j-api-2.0.3.jar
---------                     -------
 26739693                     88 files
```

### Operating System

Fedora Linux

### Selenium version

selenium-java-4.6.0

### What are the browser(s) and version(s) where you see this issue?

N.A.

### What are the browser driver(s) and version(s) where you see this issue?

N.A.

**Comment by pujagani** [comment] 2023-01-09 06:29
I was able to reproduce the issue. Thank you for the details. The duplicate jars are due to the dependencies https://github.com/SeleniumHQ/selenium/blob/trunk/java/maven_deps.bzl#L41, which are essential to support unix domain sockets in the Netty client that Selenium uses. Locally, I removed those dependencies and created a pre-release zip file, the same as the one used in the issue and the duplicate warning was not shown.
The dependencies in maven are identified using the classifier for the operating system for UNIX domain sockets. I am guessing that while building the Java bindings, the classifier is not accounted for and I am not sure if it should be accounted for. 
However, we have introduced JDK 11 Http Client and our future plans are to support that and not use the Netty client, so as part of that, this issue will eventually be resolved.
Meanwhile, I see the issue is not blocking in nature and there is a way to get around it so I am closing the issue.

**Closed as completed by pujagani** 2023-01-09 06:29 UTC
Labels: C-java, I-defect
