### ISSUE TITLE
selenium-html-runner-3.0.1 failing on startup

### ISSUE THREAD

**Issue by gchr** [SeleniumHQ/selenium#3076] opened 2016-11-08 15:53 UTC
## Meta -
OS:  Ubuntu Linux 16.04

Selenium Version:  
selenium-html-runner-3.0.1
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

Browser:  
Chrome with chromedriver 2.25
Browser Version:  
53.0.2785.116 (64-bit)

## Expected Behavior -
To open the browser and navigate to google.com

## Actual Behavior -
The browser opens and closes immediately.
The console is showing:

Multi-window mode is longer used as an option and will be ignored.
Starting ChromeDriver 2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e) on port 4407
Only local connections are allowed.
Nov 08, 2016 5:45:09 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Nov 08, 2016 5:45:09 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
2016-11-08 17:45:09.827:INFO::main: Logging initialized @1358ms
2016-11-08 17:45:09.924:INFO:osjs.Server:main: jetty-9.2.z-SNAPSHOT
2016-11-08 17:45:09.947:INFO:osjsh.ContextHandler:main: Started o.s.j.s.h.ContextHandler@1bd4fdd{/tests,null,AVAILABLE}
2016-11-08 17:45:09.959:INFO:osjs.ServerConnector:main: Started ServerConnector@364b5f42{HTTP/1.1}{0.0.0.0:23786}
2016-11-08 17:45:09.960:INFO:osjs.Server:main: Started @1490ms
2016-11-08 17:45:09.972:INFO:osjs.ServerConnector:main: Stopped ServerConnector@364b5f42{HTTP/1.1}{0.0.0.0:23786}
2016-11-08 17:45:09.973:INFO:osjsh.ContextHandler:main: Stopped o.s.j.s.h.ContextHandler@1bd4fdd{/tests,null,UNAVAILABLE}
Nov 08, 2016 5:45:10 PM org.openqa.selenium.server.htmlrunner.HTMLLauncher mainInt
WARNING: Test of browser failed: *googlechrome
java.io.IOException: java.lang.RuntimeException: java.net.BindException: Address already in use
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.determineSuiteUrl(HTMLLauncher.java:180)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:108)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.mainInt(HTMLLauncher.java:245)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.java:273)
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use
	at org.openqa.selenium.net.PortProber.pollPort(PortProber.java:154)
	at org.openqa.selenium.net.PortProber.pollPort(PortProber.java:137)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.determineSuiteUrl(HTMLLauncher.java:174)
	... 3 more
Caused by: java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.Socket.bind(Socket.java:644)
	at org.openqa.selenium.net.PortProber.pollPort(PortProber.java:146)
	... 5 more

The error "Address already in use" is strange since

$ sudo netstat -natp | grep LISTEN
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      1519/master     
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      1575/smbd       
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      1575/smbd       
tcp        0      0 0.0.0.0:5900            0.0.0.0:*               LISTEN      2926/vino-server
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      1039/dnsmasq    
tcp6       0      0 :::25                   :::*                    LISTEN      1519/master     
tcp6       0      0 :::445                  :::*                    LISTEN      1575/smbd       
tcp6       0      0 :::139                  :::*                    LISTEN      1575/smbd       
tcp6       0      0 :::5900                 :::*                    LISTEN      2926/vino-server

## Steps to reproduce -
Place in the same folder all the following files
selenium-html-runner-3.0.1.jar
[chromedriver2.25 ](http://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip)
[selTest.html ](https://gist.githubusercontent.com/gchr/300a16b0b3b5271247609a28b2e98a1f/raw/29ed38cdba0ac92358025b0fec00678570967987/selTest.html)

and inside that folder run:
java -jar selenium-html-runner-3.0.1.jar -htmlSuite "*googlechrome" "http://www.google.com" "./selTest.html" SeResults

**Comment by barancev** [comment] 2016-11-23 11:36
Duplicate of #2978.
Already fixed by not released yet.

**Closed by barancev** 2016-11-23 11:36 UTC
Labels: C-htmlrunner

**Comment by exotlv** [comment] 2016-11-23 13:17
@barancev, when we could see new release, approx.?

**Comment by MikeyCarter** [comment] 2016-12-08 17:58
@exotlv @barancev ,

Any news on the next release?   3.0.1 seems to be unusable if we can run it.
