### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by alikank** [SeleniumHQ/selenium#14515] opened 2024-09-18 09:39 UTC
### What happened?

![YFoSUw0x](https://github.com/user-attachments/assets/8b25ad35-3690-4364-942f-827b1d219caa)

Today, I updated the Chrome browser to the latest version (129). After the update, running Chrome in headless mode produces an unusual result: a blank white window appears, matching the size of the browser. I tried Selenium based on chrome129.

### How can we reproduce the issue?

```shell
-
```

### Relevant log output

```shell
-
```

### Operating System

Windows 10, Windows 11

### Selenium version

all version

### What are the browser(s) and version(s) where you see this issue?

Chrome 129.0.6668.59

### What are the browser driver(s) and version(s) where you see this issue?

129.0.6668.59

### Are you using Selenium Grid?

-

**Comment by diemol** [comment] 2024-09-18 09:41
Duplicate of #14514

**Closed as completed** 2024-09-18 09:42 UTC
Labels: G-chromedriver

**Comment by RubTalha** [comment] 2024-09-20 12:34
https://stackoverflow.com/questions/79006406/chrome-browser-latest-version-129-in-headless-mode-produces-a-blank-white-wind/79006697#79006697
