### ISSUE TITLE
Performance regression on Chrome and Edge browser with Selenium 4 Alpha 5 (Dotnet language binding)

### ISSUE THREAD

**Issue by Shankiv** [SeleniumHQ/selenium#8585] opened 2020-07-29 08:25 UTC
## 💥 Regression Report

Hi,
We have upgraded Selenium 3.14.0.0 to Selenim 4 Apha 5 using the Nuget packages from https://www.nuget.org/profiles/selenium

Above code to create driver instance is working as expected and running automation script fine.
But after replacing the selenium dlls with latest alpha 5 dlls, its running the same script 10 times slower.

Is there any breaking changes in Selenium 4 or do we need to modify any code area?

Thanks

## Last working Selenium version

Worked up to version: Selenium 3.14.0.0

Stopped working in version: Selenium alpha 5 (Note: we have directly upgraded from 3.14.0.0 to Alpha5)

## To Reproduce

    Chrome.ChromeOptions opt = new Chrome.ChromeOptions();
    opt.LeaveBrowserRunning = false;

    Chrome.ChromeDriverService chService;
    Chrome.ChromeDriver ch;

    chService = Chrome.ChromeDriverService.CreateDefaultService(appPath, driverFile);
    chService.HideCommandPromptWindow = true;
    ch = new Chrome.ChromeDriver(chService, opt);

Detailed steps to reproduce the behavior:

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 84.0.4147.105
Browser Driver version: Chrome Driver > 79
Language Bindings version: Dotnet - Selenium 4 alpha 5 
Selenium Grid version (if applicable): NA

**Comment by diemol** [comment] 2020-09-20 14:37
@Shankiv how can we reproduce this? The information provided is very ambiguous.

**Comment by diemol** [comment] 2020-11-10 22:41
I close this for now since we did not get more information, however, if there is more information to reproduce the issue, please feel free to open a new one.

**Closed as completed by diemol** 2020-11-10 22:41 UTC
Labels: J-awaiting answer
