### ISSUE TITLE
No system compiler found. Did you install the JRE instead of the JDK?

### ISSUE THREAD

**Issue by jasonsword** [SeleniumHQ/selenium#5255] opened 2017-12-25 02:19 UTC
execute cmd: go build -t

it always failed here:

python C:/workspace/selenium/buck-out/crazy-fun/be2bf932342e5d67f58c9b26f5065c745d285d0d/buck.pex build --deep //java/client/src/org/openqa/selenium:selenium
PARSING BUCK FILES: FINISHED IN 0.2s (100%)
CREATING ACTION GRAPH: FINISHED IN 0.2s
BUILT 7/37 JOBS 0.3s //java/client/src/org/openqa/selenium:build-stamp
BUILD FAILED: //java/client/src/org/openqa/selenium:primitives failed:
javac -source 8 -target 8 -sourcepath  -g -proc:none -d C:\workspace\selenium\buck-out\bin\java\client\src\org\openqa\selenium\lib__primitives__classes -classpath '' @buck-out\gen\java\client\src\org\openqa\selenium\__primitives__srcs; jar cf buck-out\gen\java\client\src\org\openqa\selenium\lib__primitives__output\primitives.jar  buck-out\bin\java\client\src\org\openqa\selenium\lib__primitives__classes
No system compiler found. Did you install the JRE instead of the JDK?
DOWNLOADED 0.00 BYTES/SEC AVG, 0 ARTIFACTS, 0.00 BYTES
BUILDING: FINISHED IN 4.0s (100%) 7/37 JOBS, 3 UPDATED, 5.4% CACHE MISS
BUILD FAILED

my env:
>java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

>javac -version
javac 1.8.0_152

>python --version
Python 2.7.14

and I Have set JAVA_HOME\bin && watchman && buck/bin in the system PATH

**Comment by barancev** [comment] 2017-12-25 19:29
Duplicate of #4956

**Closed by barancev** 2017-12-25 19:29 UTC
