### ISSUE TITLE
Element not clickable using Selnium

### ISSUE THREAD

**Issue by Jairaj88** [SeleniumHQ/selenium#1891] opened 2016-03-29 10:03 UTC
## Meta -
OS:  Windows 
Selenium Version:  2.53.0
Browser:   Firefox
Browser Version: 43

## Expected Behavior -
Button should be Clicked (Was working fine in older version of selenium 2.45.0)

## Actual Behavior -
Getting error : Element not clickable using Selenium

## Steps to reproduce -
When i try to click on the element (button/ checkbox) through webdriver it is not able to click.
If i scroll to the element and execute that click method it is working.
In the old version of selenium it was working fine. No need to scroll before calling click() method

**Comment by p0deje** [comment] 2016-03-29 10:40
Probably duplicate of #1867.

Please reopen if you can provide [concise reproducible test case](http://sscce.org/) so we can take a look.

**Closed by p0deje** 2016-03-29 10:40 UTC

**Comment by marious88** [comment] 2016-03-29 11:58
@Jairaj88 can I ask you for some example with scroll ?

**Comment by Jairaj88** [comment] 2016-03-30 08:48
i cant be able to share the code. So i will give detailed information so that you can reproduce.
List of checkboxes are in the div but the div height is fixed so only few checkbox will be visible at a moment and have to scroll down for last checkbox to be visible. Check boxes which are at the end will not be visible and i need to click on them.
In the old version of selenium 2.43.0 it was working fine but in the latest version of selenium 2.53.0 is not able to move to element and click.

**Comment by marious88** [comment] 2016-03-30 10:30
@Jairaj88 - thanks, I did it. It works.
