### ISSUE TITLE
Drag and drop is not working for HTML 5 demo site

### ISSUE THREAD

**Issue by ridhdhi85** [SeleniumHQ/selenium#2496] opened 2016-07-20 16:37 UTC
## Meta -
OS:  Mac os
Selenium Version:  
2.53.1
Browser:  
FF 47, Google chrome 
Browser Version:  
47

## Expected Behavior -
Drag and drop should work
## Actual Behavior -
not Dragging content to the drop zone

## Steps to reproduce -

Run Below program

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.interactions.Action;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.By;

import java.awt.*;
import java.util.concurrent.TimeUnit;

public class Automation1 {
    public static void main(String[] args) throws InterruptedException {
        WebDriver driver = new FirefoxDriver();
        driver.manage().timeouts().implicitlyWait(1,TimeUnit.MINUTES);
        driver.get("http://html5demos.com/drag");

        WebElement dragElement = driver.findElement(By.id("one"));
        WebElement dropElement = driver.findElement(By.id("bin"));

        Actions builder = new Actions(driver);
        builder.dragAndDrop(dragElement, dropElement).build().perform();
        driver.close();
    }

}

**Comment by lukeis** [comment] 2016-07-20 17:42
duplicate of #1365

**Closed by lukeis** 2016-07-20 17:42 UTC
