### ISSUE TITLE
IEDriver re-sizes window to dimensions of current frame when taking full page screenshot

### ISSUE THREAD

**Issue by sevaseva** [SeleniumHQ/selenium#703] opened 2015-06-23 21:58 UTC
document_info returned by DocumentHost::GetDocumentDimensions in [this line]
(https://github.com/SeleniumHQ/selenium/blob/05da83d1932969ecab827d0ca03cdfb05852fb2d/cpp/iedriver/CommandHandlers/ScreenshotCommandHandler.h#L125)
is the one of the current frame, not the top level frame/document as that line expects.

So if our current frame was an iframe, smaller in dimensions than the top level context frame, [this line] (https://github.com/SeleniumHQ/selenium/blob/05da83d1932969ecab827d0ca03cdfb05852fb2d/cpp/iedriver/CommandHandlers/ScreenshotCommandHandler.h#L180) will re-size the window to that smaller size, calculated relative to the smaller iframe's size.

[TakesScreenshotTest.testShouldCaptureScreenshotAtIFramePageAfterSwitching] (https://github.com/SeleniumHQ/selenium/blob/653b63408f0e8f33913c0e27409db8e3c4680116/java/client/test/org/openqa/selenium/TakesScreenshotTest.java#L351) is the regression test for this, it is @Ignored on IE browsers currently. (note that entire test class is [@Ignored] (https://github.com/SeleniumHQ/selenium/blob/653b63408f0e8f33913c0e27409db8e3c4680116/java/client/test/org/openqa/selenium/TakesScreenshotTest.java#L75) on IE with that not-very-helpful message; we may want to enable those that currently pass, at least)

**Comment by jimevans** [comment] 2015-06-23 22:06
Good catch. I'm less than enthusiastic about changing it, since the spec says that screenshots are current viewport only, making any changes here throwaway work when the driver becomes spec-compliant.

**Comment by sevaseva** [comment] 2015-06-23 22:43
I think the spec doesn't [currently say] (https://w3c.github.io/webdriver/webdriver-spec.html#current-top-level-browsing-context) screenshot only [1], but you are right in saying that (assuming this iedriver stays around and wants to be w3c compliant) this code will need to be substantially rewritten to at least avoid re-sizing window.

I wonder though if "simply" dropping re-sizing window would both make iedriver (more) w3c compliant and fix this issue? I mean, do everything that it currently does just never re-size the window?

[1] Rather, it says one SHOULD do entire document but if one cannot do that, then MUST do the viewport.

**Comment by jimevans** [comment] 2015-06-23 22:57
The screenshot parts of the spec haven't been updated to include the discussions we had in Santa Clara. At that F2F, it was explicitly decided that screenshots will be view port only. You're right, not resizing the window would solve the issue entirely, but that would be a change in behavior I'm not willing to make until we're ready to explicitly say the driver is spec-compliant. I may simply create a capability for the IE driver to do only view port screenshots. Then again, I'll take a look at making the needed changes sometime soon-ish.

**Comment by jimevans** [comment] 2015-07-14 20:59
Should be fixed in 3fdc4cf

**Closed by jimevans** 2015-07-14 20:59 UTC

**Comment by j0tunn** [comment] 2016-02-03 12:13
@jimevans 
>  I may simply create a capability for the IE driver to do only view port screenshots

Is there any chance for that capability. The problem is we taking screenshots in automated tests to compare them with references. And when window resized before taking screenshot - it just breaks everything.

**Comment by j0tunn** [comment] 2016-02-10 14:47
I've made PR for the capability, that allows to avoid resizing on screenshot: https://github.com/SeleniumHQ/selenium/pull/1620
