### ISSUE TITLE
Selenium Grid servers resolve 'localhost' to a non-functional IP address in VPN configurations

### ISSUE THREAD

**Issue by sbabcoc** [SeleniumHQ/selenium#6967] opened 2019-02-25 18:42 UTC
## 🐛 Bug Report

When running in VPN configurations, the method used by Selenium Grid Server to resolve the IP address of `localhost` returns a non-functional result. Consequently, local Grid instances do not work in VPN configurations. 

This is an issue in both Grid 2 and Grid 3. My code is able to communicate with the Hub and Node servers, but the Node can't communicate with the Hub. The core issue appears to be in the method being use to determine the IP address of `localhost`. I don't know is this is a bug in the Java HTTP stack, but the typical implementation fails gloriously when running in a VPN configuration. The code I use to get the IP address of `localhost` looks like this:

```
/**
 * Get Internet protocol (IP) address for the machine we're running on.
 * 
 * @return IP address for the machine we're running on (a.k.a. - 'localhost')
 */
public static String getLocalHost() {
    try (final DatagramSocket socket = new DatagramSocket()) {
        // use Google Public DNS to discover preferred local IP
        socket.connect(InetAddress.getByName("8.8.8.8"), 10002);
        return socket.getLocalAddress().getHostAddress();
    } catch (SocketException | UnknownHostException eaten) {
        return "localhost";
    }
}
```
As indicated by the code comment, this implementation uses Google Public DNS to acquire the IP address of `localhost`. In my current configuration. this code reports the IP address of `localhost` as 10.228.225.83 (Ethernet adapter), but the Selenium Grid servers insist on trying to use IP address 100.64.24.68 (wireless LAN adapter). With a browser, I'm able to open pages with the IP address I generate with this code. The IP address reported by the Grid servers themselves is non-functional.

If I disconnect from VPN, the local Grid servers work as expected.

## To Reproduce

Download `selenium-server-standalone`.  

### Non-VPN Configuration:
* Launch `selenium-standalone-server`
```
$ java -jar selenium-server-standalone-3.141.59.jar -role hub
10:18:36.120 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
10:18:36.232 INFO [GridLauncherV3.lambda$buildLaunchers$5] - Launching Selenium Grid hub on port 4444
2019-02-25 10:18:36.668:INFO::main: Logging initialized @816ms to org.seleniumhq.jetty9.util.log.StdErrLog
10:18:37.306 INFO [Hub.start] - Selenium Grid hub is up and running
10:18:37.307 INFO [Hub.start] - Nodes should register to http://100.64.24.68:4444/grid/register/
10:18:37.307 INFO [Hub.start] - Clients should connect to http://100.64.24.68:4444/wd/hub
```
* Start a browser and open http://100.64.24.68:4444/grid/console
* You should see the Grid Console page

### VPN Configuration
* Launch `selenium-standalone-server`
```
$ java -jar selenium-server-standalone-3.141.59.jar -role hub
10:29:04.669 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
10:29:04.797 INFO [GridLauncherV3.lambda$buildLaunchers$5] - Launching Selenium Grid hub on port 4444
2019-02-25 10:29:05.177:INFO::main: Logging initialized @766ms to org.seleniumhq.jetty9.util.log.StdErrLog
10:29:05.842 INFO [Hub.start] - Selenium Grid hub is up and running
10:29:05.842 INFO [Hub.start] - Nodes should register to http://100.64.24.68:4444/grid/register/
10:29:05.842 INFO [Hub.start] - Clients should connect to http://100.64.24.68:4444/wd/hub
```
* Start a browser and open http://100.64.24.68:4444/grid/console
* `Your Internet access is blocked`
* Open http://10.228.225.146:4444/grid/console (my current Ethernet adapter IP)
* Grid Console page appears

## Expected behavior

The IP address selected for `localhost` should be functional in VPN configurations.

## Test script or set of commands reproducing this issue

See the `To Reproduce` section above

## Environment

* Virtual Private Network
* Local grid
* Either Grid 2 or Grid 3

## Workaround

This issue can be avoided by adding the `-host` option to the command line, specifying the IP address returned by the `getLocalHost()` method shown above. For example:

```
$ java -jar selenium-server-standalone-3.141.59.jar -role hub -host 10.228.225.146
```

**Comment by sbabcoc** [comment] 2019-02-25 21:57
BTW - The Java code came from here: https://stackoverflow.com/questions/9481865/getting-the-ip-address-of-the-current-machine-using-java/24649380

**Comment by pikomdas** [comment] 2019-02-26 06:27
HUB and node connection set up for grid is successful. 
 
But while HUB is going to create a browser session into node, then 
`Exception in thread "main" org.openqa.selenium.WebDriverException: Error forwarding the new session Error forwarding the request Failed to connect to /192.168.60.121:5566
Command duration or timeout: 21.12 seconds
                at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
                at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
                at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
                at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
                at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$errorHandler$0(JsonWireProtocolResponse.java:54)
                at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
                at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
                at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
                at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
                at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
                at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
                at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
                at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
                at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
                at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
                at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
                at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
                at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
                at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
                at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
                at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
                at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
                at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
                at Demo_Framework.TestRunner.SeleniumGRIDTest.main(SeleniumGRIDTest.java:29)
Caused by: org.openqa.selenium.WebDriverException: Error forwarding the new session Error forwarding the request Failed to connect to /192.168.60.121:5566
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'EC2AMAZ-0ERFAII', ip: '172.31.25.179', os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '10'
Driver info: driver.version: unknown
                at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:118)
                at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
                at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:69)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
                at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
                at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
                at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
                at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
                at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
                at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
                at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
                at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
                at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
                at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
                at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
                at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
                at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
                at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
                at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
                at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
                at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
                at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
                at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
                at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
                at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
                at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
                at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
                at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
                at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
                at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
                at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
                at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
                at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
                at java.lang.Thread.run(Unknown Source)`

**Comment by sbabcoc** [comment] 2019-02-26 17:48
@pikomdas I'm currently running on Windows 7 Pro with Java 8. What platform are you on?

**Comment by diemol** [comment] 2019-02-26 18:29
@sbabcoc what happens if you specify the `-host` and `-port` you want the hub to use? If none of those is specified, it will default to `4444` and will bind to `0.0.0.0`, which results normally in the public interface of the machine.

But in environments like yours (which are not the common rule), I'll try its best to get an appropriate IP. If that one does not suit the one you need, just set it with the `-host` parameter.

**Comment by sbabcoc** [comment] 2019-02-27 17:08
If I add the `-host` argument to the command line, specifying the IP address returned by `getLocalHost()`, everything works as expected in both Grid 2 and Grid 3. This provides a usable workaround, but the defect documented by this report is still valid. 

For the benefit of folks who run into this issue prior to the deployment of a fix, I've added this workaround in the initial description.

**Comment by diemol** [comment] 2019-02-27 17:18
I think it is not a defect, the current grid has many different ways to be customisable and that is just one of them. As I mentioned, it tries to use the public IP of the machine, and this works in most environments. 

But in complex and different network configurations/topologies, the approach that works for most people does not work. That is why anyone can customise it to make it work in their environment, in this case by adding the `-host` parameter. As mentioned in the parameters help:
```
    -host
      <String> IP or hostname : usually determined automatically. Most
      commonly useful in exotic network configurations (e.g. network with VPN)
```

So it is not a workaround, it is how it should be used in complex network configurations.
Closing as this is not a bug/defect itself.

**Closed by diemol** 2019-02-27 17:18 UTC
Labels: R-awaiting answer

**Comment by sbabcoc** [comment] 2019-02-27 18:25
@diemol Given the position that this behavior is by design (or, at least, as expected), I suggest that you expand your documentation of the `-host` option: https://seleniumhq.github.io/docs/grid.html#a_note_about_the_host_flag

No mention is made here of "exotic" network configurations. Also, VPN is far from exotic, especially in enterprise environments.

To provide guidance to users who need to run in VPN configurations, this information should be expanded to specifically call out the issue and to provide an example of a proven technique for operating in this configuration.

**Comment by diemol** [comment] 2019-02-27 18:30
We are an open community where we accept contributions from anyone, if you'd like to make the wording nicer about the bit you mention in the docs, it would be very nice if you can send us a PR :
https://github.com/SeleniumHQ/docs

**Comment by danishS** [comment] 2019-06-11 15:27
hi @diemol,
I'm in the same conundrum as sbabcoc here; and I have tried using both `-host` and `-port` option and I notice the following
`java -jar selenium-server-standalone-3.9.1.jar -role hub -host 172.19.xxx.xxx -port 9000

` Clients should connect to http://172.19.xxx.xxx:9000/wd/hub`
and then I try to register a node like so 
`java -jar .... -role node -hub http://172.19.xxx.xxx/grid/register` and it says it's registered to the hub; however the hub shows the following

`Registered a node http://10.0.x.xx.:5555` and then keeps pinging the following, and of course the tests don't run. 

`Retrying request to {}->http://10.0.x.xx:5555
11:09:29.956 INFO - I/O exception (java.net.SocketException) caught when processing request to {}->http://10.0.0.97:5555: Permission denied: connect`

What's the solution for this?

**Comment by sbabcoc** [comment] 2019-06-27 08:03
@danishS Your node command line doesn't show a port. Is this what you're actually using?
