### ISSUE TITLE
WebExtension not installed in Firefox 65 using .Net WebDriver

### ISSUE THREAD

**Issue by kabilanvk** [SeleniumHQ/selenium#6929] opened 2019-02-12 18:20 UTC
Download any XPI file from https://addons.mozilla.org/en-US/firefox/addon/search-encrypt/?src=hp-dl-promo. Tried to install with Selenium c# driver. It works fine in Firefox 61, but after upgrade to Firefox 65 the extension is not copied to extensions folder of Firefox temporary profile hence extension is not installed. The extension works fine when installed offline outside selenium.

OS: Win 10 Enterprise
Selenium Version: 3.141.0
Browser: Firefox: 65.0
.Net Framework: 4.7.2
Gecko: 0.24.0

The c# driver requires the same change as Java https://github.com/SeleniumHQ/selenium/issues/6403.

**Comment by barancev** [comment] 2019-04-19 10:52
Duplicate of #6548

**Closed by barancev** 2019-04-19 10:52 UTC
Labels: C-dotnet, D-firefox
