### ISSUE TITLE
A socket Warning from remote_connection.py

### ISSUE THREAD

**Issue by 2Niu** [SeleniumHQ/selenium#7035] opened 2019-03-15 09:57 UTC
Environment:
OS: Windows7 with SP1 (64-bit)
Browser: Chrome  73.0.3683.75 (64-bit)
chromedriver: 73.0.3683.68
Python: 3.7 (64-bit)
selenium-server-standalone: 3.14.0

Step 1.   start selenium-server-standalone  using :  java -jar selenium-server-standalone-3.14.0.jar
Step 2.   connect to it :  webdriver.Remote('http://127.0.0.1:4444/wd/hub', {'platform':'WINDOWS', 'browserName':'chrome' } )

All test cases has been executed successfully,but there are many repetitive Warnings:

Warning (from warnings module):
  File "D:\MyProgram\Python37\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 376
    return self._request(command_info[0], url, body=data)
ResourceWarning: unclosed <socket.socket fd=260, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 63869), raddr=('127.0.0.1', 4444)>

Anything wrong here ?

Thank you.

**Comment by diemol** [comment] 2019-03-24 11:06
@2Niu 
Unless someone skilled in Python like @lmtierney or @AutomatedTester can guess if this is a Selenium issue or not with the little information you have provided, I'd recommend that you help us digging into it by providing a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by cgoldberg** [comment] 2019-03-27 03:55
this is a duplicate of #6878

**Closed by cgoldberg** 2019-03-27 03:55 UTC
Labels: C-py, R-awaiting answer
