### ISSUE TITLE
[🐛 Bug]: Cannot create DevTools session twice - NPE thrown

### ISSUE THREAD

**Issue by kkoripl** [SeleniumHQ/selenium#13158] opened 2023-11-16 08:49 UTC
### What happened?

With exact same driver I wanted to track requests comming through 2 pages. The thing was I wanted it to do as this:
- Open page (driver.open()) and get tools (driver.getDevTools())
- Create session (devtools.createSession()) alongside with (sending Network.enable(Optional.empty(), Optional.empty(), Optional.empty());
- Add listener (devTools.addListener())
- Listen
- close devtools (devTools.close())
- switch side (so repeat whole procedure)

The thing is, during the second iteration, there was NPE thrown from within Selenium code, saying that connection client was nullified. I thought that creating new session is possible after closing previous one, cause there was previous issue about it: https://github.com/SeleniumHQ/selenium/issues/11606.

### How can we reproduce the issue?

```shell
public class NotWorkingTest {

    @Test
    public void notWorking() {
        ChromeDriverService.Builder builder = new ChromeDriverService.Builder();
        builder = builder.usingAnyFreePort();
        builder.usingDriverExecutable(new File("your path to chromedriver.exe"));
        ChromeDriverService chromeDriverService = builder.build();
        ChromeDriver chromeDriver = new ChromeDriver(chromeDriverService, new ChromeOptions());
        DevTools devTools = chromeDriver.getDevTools();

        devTools.createSession();
        devTools.close();

        devTools.createSession(); // stacktrace is here
        devTools.close();
    }
}
```

### Relevant log output

```shell
java.lang.NullPointerException: Cannot invoke "java.net.http.HttpClient.newWebSocketBuilder()" because "this.client" is null

	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.openSocket(JdkHttpClient.java:181)
	at org.openqa.selenium.devtools.Connection.reopen(Connection.java:93)
	at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:129)
	at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:117)
```

### Operating System

Windows 10

### Selenium version

Java 4.15.0

### What are the browser(s) and version(s) where you see this issue?

Chrome (but looks like any)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 119.0.6045.105

**Comment by titusfortner** [comment] 2023-11-16 18:35
Thanks for reporting, this is a duplicate of #12882

**Closed as completed by titusfortner** 2023-11-16 18:35 UTC
Labels: I-defect, A-needs-triaging
