### ISSUE TITLE
Single Actions object with chained actions works differently than separate Actions objects (ClickAndHold with MoveByOffset)

### ISSUE THREAD

**Issue by KardoseR** [SeleniumHQ/selenium#7855] opened 2019-12-08 18:26 UTC
## 🐛 Bug Report

Using **separate Action objects** to perform actions on selenium yields to different results than using **one Action object** with the actions chained, in my case tested with **ClickAndHold** and **MoveByOffset** actions.

## To Reproduce

- Create a project with the selenium library from Nuget
- Instantiate ChromeDriver and navigate to https://www.seleniumeasy.com/test/basic-first-form-demo.html, after that just type something on the textbox.
- Get the position for the element "//input[@id='user-message']"
- Move the mouse to the element with an offset
- ClickAndHold on the element
- MoveByOffset to select the text inside

-Then try the same with separate actions object, it won't work.

## Expected behavior

Using both single Actions object with chained actions and separate Actions objects with one action per object should yield the same result 

## Test script or set of commands reproducing this issue

`                    
var driver = new ChromeDriver();
                     driver.Navigate().GoToUrl("https://www.seleniumeasy.com/test/basic-first-form-demo.html");
                    Console.ReadLine();
		    driver.FindElement(By.XPath("//input[@id='user-message']")).SendKeys("dhduUhdsauhduahsduhsaduha");

                    Point pos = driver.FindElement(By.XPath("//input[@id='user-message']")).Location;
		    
                    //Single Actions object with chained actions
                    new Actions(driver).MoveByOffset(pos.X + 100, pos.Y + 5).ClickAndHold().MoveByOffset(-50, 0).Perform();

                    Console.ReadLine();
                    driver.Quit();
                    driver = new ChromeDriver();

                    driver.Navigate().GoToUrl("https://www.seleniumeasy.com/test/basic-first-form-demo.html");
                    Console.ReadLine();

                    driver.FindElement(By.XPath("//input[@id='user-message']")).SendKeys("dhduUhdsauhduahsduhsaduha");
		    
		    //Separate Action objects
                    new Actions(driver).MoveByOffset(pos.X + 100, pos.Y + 5).Perform();
                    new Actions(driver).ClickAndHold().Perform();
                    new Actions(driver).MoveByOffset(-50, 0).Perform();`

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: Latest
Browser Driver version: ChromeDriver 78.0.3904.105
Language Bindings version: 3.141.0
Selenium Grid version (if applicable):

**Comment by KardoseR** [comment] 2019-12-10 15:27
Still don't know the solution for this.

**Comment by KardoseR** [comment] 2019-12-13 14:30
Still looking.

**Comment by jimevans** [comment] 2019-12-13 18:48
As a point of comparison, what happens executing the same code against Firefox? There’s a chance the issue is in chromedriver, and not the .NET bindings.

**Comment by KardoseR** [comment] 2019-12-14 17:14
I am gonna try it and report back!

**Comment by jimevans** [comment] 2019-12-14 19:30
@KardoseR That would indicate a potential issue with chromedriver. Might need to raise the issue in their tracker.

**Comment by KardoseR** [comment] 2019-12-14 20:43
@jimevans Could you please point me to their tracker?

**Comment by diemol** [comment] 2019-12-15 10:11
@KardoseR here it is
https://bugs.chromium.org/p/chromedriver/issues/list
Can you please post the link when you create the issue over there? Thanks!

I will close this issue since it all points out to be a ChromeDriver issue.

**Closed by diemol** 2019-12-15 10:11 UTC
