### ISSUE TITLE
IE 11.1198 alert window hangs indefinitely

### ISSUE THREAD

**Issue by jansohn** [SeleniumHQ/selenium#4094] opened 2017-05-29 13:17 UTC
## Meta -
OS:  
Windows 10.0.14393
Selenium Version:  
3.4.0
Browser:  
Internet Explorer 11

Browser Version:  
11.1198.14393.0

## Expected Behavior -
`driver.switchTo().alert()` returns the BASIC auth security alert window

## Actual Behavior -
`driver.switchTo().alert()` hangs indefinitely

## Steps to reproduce -
Open a web page with BASIC authentication and call `driver.switchTo().alert()` in IE 11.1198.14393.0.
It works as expected on another Windows 10 with Build 10586 (IE 11.0.10586.0).

**Comment by AutomatedTester** [comment] 2017-05-29 17:07
Unfortunately Basic Auth dialogs are not supported currently.

**Comment by AutomatedTester** [comment] 2017-05-29 17:08
duplicate of #453

**Closed by AutomatedTester** 2017-05-29 17:08 UTC
Labels: D-IE

**Comment by jansohn** [comment] 2017-05-30 06:39
Why is it working then until 11.0.x?

**Comment by AutomatedTester** [comment] 2017-05-30 09:46
It was a beta feature and then a security update to IE11 removed our ability to do it. hopefully we can get Edge to implement it with their W3C work
