### ISSUE TITLE
A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:62968/session/5c1df802a19fab49b6a894b3db1af643/url

### ISSUE THREAD

**Issue by Nefcanto** [SeleniumHQ/selenium#8030] opened 2020-02-16 08:25 UTC
## 🐛 Bug Report

I'm trying to automate a process, and I need to:

- Load a URL

- Find an element, and check it's inner text

- Wait for inner text to be populated through AJAX (loop, check, sleep)

- Then when it has value, read that value and save it in database

I have near 50 thousand URLs, and this process works just fine for the first 5 or 10 (non-deterministic) and then I get this error:

```
A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:62968/session/5c1df802a19fab49b6a894b3db1af643/url. The status of the exception was UnknownError, and the message was: An error occurred while sending the request. Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..


   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.set_Url(String value)
```

## To Reproduce

```
public static void Main(string[] args)
{
	GetValues();
}

private static void GetValues()
{
	var entities = GetListOfEntities(); // to be read from database, in an internal system
	var browser = SetupBrowser();
	SetTimeout(browser, 60);
	foreach (var entity in entities)
	{
		try
		{
			GetValue(browser, entity);
		}
		catch (Exception ex)
		{
			Logger.Log(ex); // simple home-made logger
			Logger.LogError($"Error getting value for entity {entity.Id}");
		}
	}
}

private static void GetValue(IWebDriver browser, Recipe entity)
{
	browser.Url = entity.Url;
	var valueDom = browser.FindElement(By.CssSelector(".value-count span[ng-bind]"));
	while (valueDom.Text.IsNothing())
	{
		Logger.LogWarning($"Waiting for value to be loaded...");
		Thread.Sleep(500);
	}
	entity.Value = valueDom.Text.ToInt();
	Logger.LogSuccess($"Value is {entity.Value} for entity {entity.Id}");
	new EntityBusiness().Update(entity);
}

public static IWebDriver SetupBrowser()
{
	int port = 18882;
	var proxy = new OpenQA.Selenium.Proxy
	{
		HttpProxy = $"http://localhost:{port}",
		SslProxy = $"http://localhost:{port}",
		FtpProxy = $"http://localhost:{port}"
	};
	var options = new ChromeOptions
	{
	};
	driver = new ChromeDriver(options);
	return driver;
}

public static void SetTimeout(IWebDriver driver, int timeoutInSeconds)
{
	driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(timeoutInSeconds);
}
```

Please note that I can't create a SSCCE, since a lot of code relates to internal system. But, as the error stack trace shows, it's not related to our code. It's an exception of internal connections between Selenium and ChromeDriver I guess.

The code is simple, get a list of URLs of a dynamic website. For each URL, load it and in a loop-check-sleep structure wait for its inner text to be loaded, and read/store that value, and move to the next URL.
After a couple of times the internal connection is lost.

## Expected behavior

Deterministic behavior. Once a connection is made between internal modules, then it has to persist. I mean, if a port that Selenium is trying to use is already occupied with another software, then it's understandable why it doesn't work.
But as soon as it gets everything up and running, then it shouldn't fail in the middle.

Otherwise, I think having a bunch of clues in the exception message would be very informative. Why the connection is closed and what are the possibilities?

## Test script or set of commands reproducing this issue

Test script is attached. 
[Program.txt](https://github.com/SeleniumHQ/selenium/files/4209502/Program.txt)

Please run it with this `.csproj` configuration:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Selenium.WebDriver" Version="3.141.0" />
    <PackageReference Include="Selenium.Support" Version="3.141.0" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="80.0.3987.1600" />
  </ItemGroup>

</Project>
```

## Environment

OS: Version 1903 (OS Build 18.362.295)
Browser: Google Chrome
Browser version:  Version 80.0.3987.106 (Official Build) (64-bit)
Browser Driver version: 80.0.3987.1600
Language Bindings version: C# 8 (.NET Core 3.1.1)

**Comment by JoeConroy93** [comment] 2020-05-22 13:22
Hi Friend, this issue is also tormenting me! i have automated test suite in cucumber/gherkin which is launching IEDriverServer/Local host per case it seems to work for the first 25% then virtually all cases get this error! cant find anything to resolve. will let you know if i come across something worthwile!

**Comment by nefcanto** [comment] 2020-05-22 15:18
@JoeConroy93 I found no solution.
I just waited for a couple of upgrades and I don't have this problem now.
I don't know what was the cause, and what was the solution.

**Comment by doctor-house** [comment] 2020-06-17 21:07
I ran into this issue this week trying to convert a Selenium test suite in C# from .NET Framework 4.8 to .NET Core 3.1. Under .NET Framework my tests run normally but under Core 3.1 tests return this exception constantly. Some things I have noticed:

1. This error is more likely the more tests are running (so higher outbound traffic). For smaller test runs (5-10 concurrent tests) I never see this but for larger test runs (our grid maxes at around 50 concurrent tests) I see usually around half the tests throw this exception. The errors seem to occur mostly at the start when the test load is max and as the load decreases the errors gradually stop until the remaining tests run normally.

2. Switching the underlying `HttpHandler` seems to have no affect. Per [here](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/networking#usesocketshttphandler) switching to `WinHttpHandler` still produces these errors, just with a slightly different exception message.

3. This issue is reproduce-able on my end by simply changing the target framework (4.8 -> core 3.1), so I think it might have to due with how the internal implementation of HttpClient has changed from framework to core.

I found some similar sounding issues [here](https://github.com/dotnet/runtime/issues/35508) and [here](https://github.com/dotnet/runtime/issues/29038) but I'm not sure how related they are.

**Comment by doctor-house** [comment] 2020-06-18 20:03
I did some more investigating, specifically I looked at socket connections from local runs of my test suite on framework 4.8 vs core 3.1 and I found that on net core socket connections were sitting in `TIME_WAIT`. Here's some output during the test runs from `netstat`:

**.NET Core 3.1**
![image](https://user-images.githubusercontent.com/66467615/85063630-08c80080-b170-11ea-9de7-be5fcb27b4ae.png)

**.NET Framework 4.8**
![image](https://user-images.githubusercontent.com/66467615/85063682-1e3d2a80-b170-11ea-8b6a-441b37040017.png)

In the 3.141 bindings it looks like Selenium is using `HttpWebRequest` to send requests. [(code here)](https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.0/dotnet/src/webdriver/Remote/HttpCommandExecutor.cs#L198) I found this nice blog post that outlines the major changes between `HttpWebRequest` from framework to core, in particular `HttpWebRequest` goes from directly interacting with the sockets to being a wrapper around `HttpClient`.

@nefcanto are you able to try your tests running Selenium 4? The implementation was changed to directly use `HttpClient` and I'm wondering if that could possibly be a fix for this issue?

**Comment by nefcanto** [comment] 2020-06-22 07:48
@doctor-house yeah, basically we updated our libraries, including selenium in hope that this bug gets fixed, and now we're using `Selenium.WebDriver` version `4.0.0-alpha03` and the problem is solved for now.

**Comment by MS-Manikandan** [comment] 2021-06-25 03:39
@doctor-house  I too face this issue in locally and in build agent  and its very bothering. If my local network performance is poor i kind of agree, but when running .net 48 & .net core 3.1 tests on azure build agents when connected to clients network , the internet connection was very good , but the tests  fails when trying to maximize window , switching frames & windows  and threw "OpenQA.Selenium.WebDriverException: 'Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:portnumber", when i do a netstat -bf when running tests on local i got as below, does this makes any difference when the build agent is not console user and rdp tcp as active session user.
[testsite.net48.x86.exe]
TCP    [::1]:61238            user:56078  ESTABLISHED
[chromedriver.exe]
TCP    [::1]:61241            user:61238  TIME_WAIT

**Comment by sebainones** [comment] 2021-11-18 09:00
Im using .NET Core 3.1  and ChromeDriver 95.0.4638.69 running on a Windows Server 2019.
In my case I have DataDriven Tests:
        [DataTestMethod]
        [DynamicData(nameof(GetRealData), DynamicDataSourceType.Property)]
        public void MyTest(MyParameter myParameter)

as @doctor-house  mentioned after my data driven tests run there are a lot of:
...
TCP    [::1]:59189            NIBBLER:55118          TIME_WAIT
TCP    [::1]:59190            NIBBLER:55118          TIME_WAIT
TCP    [::1]:59191            NIBBLER:55118          TIME_WAIT
...

In my case there were as many TIME_WAIT connections  as Tests being run. And the exception happens when I'm trying to Dispose the driver.
So, I _believe_  the driver it's not being able to properly close/release those connections.

Has anyone have more insight on this or some sort of clean way to overcome this situation.

**Comment by diemol** [comment] 2022-05-10 08:11
Is this still happening in the most recent .NET release? If so, please provide a way to reproduce the issue.

**Comment by titusfortner** [comment] 2022-05-19 23:00
This issue is a duplicate of this issue: https://github.com/SeleniumHQ/selenium/issues/4162

Which was solved by Selenium 4. If you are having a problem with Selenium 4, please open a new issue.

**Closed by titusfortner** 2022-05-19 23:00 UTC
Labels: R-awaiting answer, C-dotnet
