### ISSUE TITLE
execute_async_script after time.sleep causes [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by traffisco** [SeleniumHQ/selenium#6238] opened 2018-08-02 06:12 UTC
OS:  Linux 
Selenium Version:  selenium-3.13.0
Browser:  Firefox
Browser Version:  Mozilla Firefox 61.0.1

When sleeping the thread for more then 5 seconds and calling execute_async_script, the function errors with [Errno 32] Broken pipe after script timeout ended without the callback value.
Same code works on macos.

## Expected Behavior
execute_async_script returns the callback from the script without any errors.

## Actual Behavior
execute_async_script waits for script timeout then returns with [Errno 32] Broken pipe.

## Steps to reproduce

    from selenium import webdriver
    from selenium.webdriver.support.ui import WebDriverWait
    import time
    
    driver = webdriver.Firefox()
    
    driver.get('http://example.com')
    time.sleep(6)
    
    try:
        ret = driver.execute_async_script("var callback = arguments[arguments.length - 1];setTimeout(function(){callback('done')}, 7000)")
        print('ret '+ ret)
    except Exception as e:
        print(e)
[Errno 32] Broken pipe

**Comment by lmtierney** [comment] 2018-08-02 11:49
Closing in favor of https://github.com/mozilla/geckodriver/issues/1340 which was closed as a duplicate of https://github.com/mozilla/geckodriver/issues/1304

**Closed by lmtierney** 2018-08-02 11:49 UTC
