### ISSUE TITLE
[🐛 Bug]: ChromeDriver doesn't work on Ubuntu 22.04 when chrome is installed as a snap: `error: unknown flag `port'`

### ISSUE THREAD

**Issue by mvysny** [SeleniumHQ/selenium#10969] opened 2022-08-22 07:17 UTC
### What happened?

Building on https://github.com/SeleniumHQ/selenium/issues/7788 which has been closed and no further comments are allowed.

Using `ChromeDriver` on Ubuntu with Chromium installed via snap doesn't work and will fail with `error: unknown flag `port'`.

The problem is as follows:
1. You set the system property `webdriver.chrome.driver` to `/snap/bin/chromium.chromedriver` since that's where snap installs it.
2. The `/snap/bin/chromium.chromedriver` is a symlink to `/usr/bin/snap` since that's how snap works.
3. `DriverService:91` will call `File.getCanonicalPath()` on `/snap/bin/chromium.chromedriver` which resolves the symlink and turns it into `/usr/bin/snap`
4. `DriverService` now tries to run `/usr/bin/snap` with parameters intended for the chrome driver, and `/usr/bin/snap` will fail.

The workaround mentioned at https://github.com/SeleniumHQ/selenium/issues/7788#issue-522887756 works by overriding `File.getCanonicalPath()` and stopping it from symlink resolving.

The workaround at https://github.com/SeleniumHQ/selenium/issues/7788#issuecomment-1001135162 doesn't work and will fail in the same way as described in this ticket.

### How can we reproduce the issue?

```shell
1. Install Chromium as a snap on Ubuntu: `sudo snap install chromium`
2. Set java system property `webdriver.chrome.driver` to `/snap/bin/chromium.chromedriver`
3. instantiate the ChromeDriver: `new ChromeDriver()`
```

### Relevant log output

```shell
error: unknown flag `port'
Aug 22, 2022 9:56:41 AM org.openqa.selenium.os.OsProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: 64 (Exit value: 64)

org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'mavi-vb', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.13.0-52-generic', java.version: '11.0.15'
Driver info: driver.version: ChromeDriver

	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:202)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:188)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:134)
```

### Operating System

Ubuntu 22.04

### Selenium version

3.141.59

### What are the browser(s) and version(s) where you see this issue?

snap Chromium 104.0.5112.101

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 104.0.5112.101 (0a2e5078088fc9f9a29247aaa40af9e7ada8b79f-refs/branch-heads/5112@{#1477})

**Comment by pujagani** [comment] 2022-09-12 05:07
Since issue 7788 has the context and your problem is not resolved. I can reopen the issue so the conversation and resolution can continue there and close this out in favor of that. Unless this issue has something additional.

**Comment by mvysny** [comment] 2022-09-12 05:13
@pujagani sounds good, I agree. I opened this ticket precisely because I couldn't comment/reopen #7788 ; if 7788 is reopened then this ticket can be closed as duplicate of 7788

**Comment by pujagani** [comment] 2022-09-12 09:53
Got it. Thank you! Closed as duplicate of #7788. Please add more details in the issue as needed via comments.

**Closed as completed by pujagani** 2022-09-12 09:53 UTC
Labels: C-java, I-defect

**Comment by michaelzangl** [comment] 2022-09-13 08:33
@pujagani Did you mean the comments here or in that ticket? That ticket is locked.

@mvysny Do I read it correctly that the first workaround did work for you? The second workaround by @titusfortner is not working, but by the time I was able to test the newest selenium version I was unable to comment on that ticket. As far as I see, nothing has changed on the initial status of the ticket and the bug still exists.

**Comment by mvysny** [comment] 2022-09-13 10:07
@michaelzangl exactly. The strange  "new File() {}" override (AKA the first workaround) works for me; this one doesn't: `new ChromeDriverService.Builder().usingDriverExecutable("/snap/bin/chromium.chromedriver").build();
`.

The bug pretty much still exists; I assume #7788 was closed because of inactivity.

**Comment by michaelzangl** [comment] 2022-09-13 10:10
@mvysny Thanks for the feedback, I was confused because of the comment there by @pujagani. 

> I assume https://github.com/SeleniumHQ/selenium/issues/7788 was closed because of inactivity.

Well, that bug got 11 reactions in the time it was open, so one activity every 2 months should indicate that the problem still exists.

**Comment by pujagani** [comment] 2022-09-13 10:48
Apologies, I thought reopening the ticket would allow comments.

**Comment by michaelzangl** [comment] 2022-09-13 15:52
@pujagani  /  @titusfortner 

Can you add a comment to  #7788 that specifying the driver is required and is included in the workaround code (that code is require due to selenium resolving the symlink itself before calling the executable instead of letting the OS resolve it).

And if you mark it resolved, please mark it as "wontfix" or something so that people know that they still have to use that workaround.

**Comment by titusfortner** [comment] 2022-09-13 16:41
@michaelzangl ah, sorry, I wasn't paying close enough attention about the symlinking issues and I've not worked with snap.

I don't see an obvious way to fix this in Selenium. We don't want a blanket move to `absolutePath()`, and we don't want to maintain a custom list of symlinked implementations to ignore.

Would it be a solution to copy the driver somewhere without a symlink and use that location?

**Comment by titusfortner** [comment] 2022-09-13 16:43
For what it is worth, we are working on a major initiative to improve driver management overall to make all of this more seamless, since none of this bit is fun for anyone.
