### ISSUE TITLE
Chrome Driver not working for chrome options for selenium 3.9.0

### ISSUE THREAD

**Issue by ssurwase** [SeleniumHQ/selenium#5506] opened 2018-02-17 19:11 UTC
Hi barancev,

I have exactly similar issue which is reported here.
selenium 3.9.0
JDK - jdk_1.8_011 (32 bit JRE)
Eclipse - Mars
gauva - 23.2-jre.jar and its dependencies.

ChromeOptions chromeOptions = new ChromeOptions();
driver = new ChromeDriver(chromeOptions);
driver.manage().window().maximize();
threadDriver.set(driver);

getting exception for initiating the driver.
java.lang.AbstractMethodError: org.openqa.selenium.chrome.ChromeOptions.is(Ljava/lang/String;)Z
at org.openqa.selenium.remote.RemoteWebDriver.init(RemoteWebDriver.java:170)
at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:123)
at org.openqa.selenium.chrome.ChromeDriver.(ChromeDriver.java:181)
at org.openqa.selenium.chrome.ChromeDriver.(ChromeDriver.java:168)
at org.openqa.selenium.chrome.ChromeDriver.(ChromeDriver.java:157)

I checked mvn tree dependency. no other selenium version.
java is jdk 1.8 (32 bit)

**Comment by barancev** [comment] 2018-02-25 16:04
Looks like classpath issue, please show your POM file.

**Comment by barancev** [comment] 2018-03-13 07:23
Closing the issue, there is no reproduction scenario provided.

**Closed by barancev** 2018-03-13 07:23 UTC
Labels: C-java, R-awaiting answer
