### ISSUE TITLE
After Update firefox to 47 Selenium webdriver 2.53 is not working. Got the message unable to find host.

### ISSUE THREAD

**Issue by vikrant4224** [SeleniumHQ/selenium#2284] opened 2016-06-14 14:22 UTC
Any help  would be much appreciated. Thanks. org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
ateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":"chrome://ols/skin/icon.png","icon64URL":null,"defaultLocale":{"name":"Browsing Protection by F-Secure","description":"Protects your encrypted browsing.","creator":"F-Secure Corporation","homepageURL":"http://www.f-secure.com/en/web/home_global"},"visible":true,"active":false,"userDisabled":true,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\F-Secure\\NIF\\bin\\browser\\install\\fs_firefox_https\\fs_firefox_https.xpi","installDate":1462802697742,"updateDate":1462802697742,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":125083,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"20.0a1","maxVersion":"44.*"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}
1465905122309	DeferredSave.extensions.json	DEBUG	Save changes
1465905122310	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1465905122310	addons.xpi-utils	DEBUG	Updating add-on states
1465905122310	addons.xpi-utils	DEBUG	Writing add-ons list
1465905122328	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1465905122329	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1465905122329	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1465905122329	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1465905122330	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1465905122331	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1465905122350	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1465905122350	addons.manager	DEBUG	Provider finished startup: XPIProvider
1465905122350	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1465905122350	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1465905122350	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1465905122351	addons.manager	DEBUG	Starting provider: GMPProvider
1465905122356	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1465905122356	addons.manager	DEBUG	Provider finished startup: GMPProvider
1465905122357	addons.manager	DEBUG	Starting provider: PluginProvider
1465905122357	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1465905122357	addons.manager	DEBUG	Provider finished startup: PluginProvider
1465905122357	addons.manager	DEBUG	Completed startup sequence
1465905124059	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1465905124059	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1465905124059	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1465905124321	DeferredSave.extensions.json	DEBUG	Write succeeded
1465905124321	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1465905124321	DeferredSave.extensions.json	DEBUG	Starting timer
1465905124331	addons.repository	DEBUG	No addons.json found.
1465905124331	DeferredSave.addons.json	DEBUG	Save changes
1465905124368	DeferredSave.addons.json	DEBUG	Starting timer
1465905124587	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1465905124587	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1465905124588	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1465905124592	DeferredSave.extensions.json	DEBUG	Starting write
1465905124596	DeferredSave.addons.json	DEBUG	Starting write
1465905124626	DeferredSave.extensions.json	DEBUG	Write succeeded
1465905124634	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at customerpayment.main(customerpayment.java:9)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
ateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":"chrome://ols/skin/icon.png","icon64URL":null,"defaultLocale":{"name":"Browsing Protection by F-Secure","description":"Protects your encrypted browsing.","creator":"F-Secure Corporation","homepageURL":"http://www.f-secure.com/en/web/home_global"},"visible":true,"active":false,"userDisabled":true,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\F-Secure\\NIF\\bin\\browser\\install\\fs_firefox_https\\fs_firefox_https.xpi","installDate":1462802697742,"updateDate":1462802697742,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":125083,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"20.0a1","maxVersion":"44.*"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}
1465905122309	DeferredSave.extensions.json	DEBUG	Save changes
1465905122310	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1465905122310	addons.xpi-utils	DEBUG	Updating add-on states
1465905122310	addons.xpi-utils	DEBUG	Writing add-ons list
1465905122328	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1465905122329	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1465905122329	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1465905122329	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1465905122330	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1465905122331	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1465905122350	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1465905122350	addons.manager	DEBUG	Provider finished startup: XPIProvider
1465905122350	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1465905122350	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1465905122350	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1465905122351	addons.manager	DEBUG	Starting provider: GMPProvider
1465905122356	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1465905122356	addons.manager	DEBUG	Provider finished startup: GMPProvider
1465905122357	addons.manager	DEBUG	Starting provider: PluginProvider
1465905122357	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1465905122357	addons.manager	DEBUG	Provider finished startup: PluginProvider
1465905122357	addons.manager	DEBUG	Completed startup sequence
1465905124059	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1465905124059	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1465905124059	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1465905124321	DeferredSave.extensions.json	DEBUG	Write succeeded
1465905124321	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1465905124321	DeferredSave.extensions.json	DEBUG	Starting timer
1465905124331	addons.repository	DEBUG	No addons.json found.
1465905124331	DeferredSave.addons.json	DEBUG	Save changes
1465905124368	DeferredSave.addons.json	DEBUG	Starting timer
1465905124587	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1465905124587	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1465905124588	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1465905124592	DeferredSave.extensions.json	DEBUG	Starting write
1465905124596	DeferredSave.addons.json	DEBUG	Starting write
1465905124626	DeferredSave.extensions.json	DEBUG	Write succeeded
1465905124634	DeferredSave.addons.json	DEBUG	Write succeeded

Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 16:57:40'
System info: host: 'DESKTOP-E1D40A4', ip: '192.168.1.150', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_91'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:124)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at customerpayment.main(customerpayment.java:9)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
ateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":"chrome://ols/skin/icon.png","icon64URL":null,"defaultLocale":{"name":"Browsing Protection by F-Secure","description":"Protects your encrypted browsing.","creator":"F-Secure Corporation","homepageURL":"http://www.f-secure.com/en/web/home_global"},"visible":true,"active":false,"userDisabled":true,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\F-Secure\\NIF\\bin\\browser\\install\\fs_firefox_https\\fs_firefox_https.xpi","installDate":1462802697742,"updateDate":1462802697742,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":125083,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"20.0a1","maxVersion":"44.*"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}
1465905122309	DeferredSave.extensions.json	DEBUG	Save changes
1465905122310	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1465905122310	addons.xpi-utils	DEBUG	Updating add-on states
1465905122310	addons.xpi-utils	DEBUG	Writing add-ons list
1465905122328	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1465905122329	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1465905122329	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1465905122329	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1465905122330	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1465905122331	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1465905122350	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1465905122350	addons.manager	DEBUG	Provider finished startup: XPIProvider
1465905122350	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1465905122350	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1465905122350	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1465905122351	addons.manager	DEBUG	Starting provider: GMPProvider
1465905122356	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1465905122356	addons.manager	DEBUG	Provider finished startup: GMPProvider
1465905122357	addons.manager	DEBUG	Starting provider: PluginProvider
1465905122357	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1465905122357	addons.manager	DEBUG	Provider finished startup: PluginProvider
1465905122357	addons.manager	DEBUG	Completed startup sequence
1465905124059	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1465905124059	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1465905124059	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1465905124321	DeferredSave.extensions.json	DEBUG	Write succeeded
1465905124321	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1465905124321	DeferredSave.extensions.json	DEBUG	Starting timer
1465905124331	addons.repository	DEBUG	No addons.json found.
1465905124331	DeferredSave.addons.json	DEBUG	Save changes
1465905124368	DeferredSave.addons.json	DEBUG	Starting timer
1465905124587	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1465905124587	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1465905124588	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1465905124592	DeferredSave.extensions.json	DEBUG	Starting write
1465905124596	DeferredSave.addons.json	DEBUG	Starting write
1465905124626	DeferredSave.extensions.json	DEBUG	Write succeeded
1465905124634	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	... 7 more

**Comment by AutomatedTester** [comment] 2016-06-14 14:45
Duplicate of #2110

**Closed by AutomatedTester** 2016-06-14 14:45 UTC
