### ISSUE TITLE
[🐛 Bug]: Typescript(NodeJS) stack trace is missing source code information

### ISSUE THREAD

**Issue by kristijorgji** [SeleniumHQ/selenium#11756] opened 2023-03-09 10:54 UTC
### What happened?

Typescript errors miss source code stack trace and only show the error and traces from selenium library

```
no such element: Unable to locate element: {"method":"css selector","selector":"span > span"}
  (Session info: chrome=110.0.5481.177)
NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"span > span"}
  (Session info: chrome=110.0.5481.177)
    at Object.throwDecodedError (/Users/k/Desktop/test/e2e_tests/node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (/Users/k/Desktop/test/e2e_tests/node_modules/selenium-webdriver/lib/http.js:587:13)
    at Executor.execute (/Users/k/Desktop/test/e2e_tests/node_modules/selenium-webdriver/lib/http.js:515:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Driver.execute (/Users/k/Desktop/test/e2e_tests/node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at async toWireValue (/Users/k/Desktop/test/e2e_tests/node_modules/selenium-webdriver/lib/webdriver.js:145:15)
    at async /Users/k/Desktop/test/e2e_tests/node_modules/selenium-webdriver/lib/webdriver.js:195:16
    at async forEachKey (/Users/k/Desktop/test/e2e_tests/node_modules/selenium-webdriver/lib/webdriver.js:189:9)
    at async convertKeys (/Users/k/Desktop/test/e2e_tests/node_modules/selenium-webdriver/lib/webdriver.js:194:3)
```

### How can we reproduce the issue?

```shell
Try to get one element that does not exist to cause an error, and in the error trace will not be your source code file.

index.ts


await driver.findElement(By.css('span > span'));
```

In the thrown error you will not see mentioned index.ts nor the line the error happend.
```


### Relevant log output

```shell
no such element: Unable to locate element: {"method":"css selector","selector":"span > span"}
  (Session info: chrome=110.0.5481.177)
NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"span > span"}
  (Session info: chrome=110.0.5481.177)
    at Object.throwDecodedError (/Users/k/Desktop/test/e2e_tests/node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (/Users/k/Desktop/test/e2e_tests/node_modules/selenium-webdriver/lib/http.js:587:13)
    at Executor.execute (/Users/k/Desktop/test/e2e_tests/node_modules/selenium-webdriver/lib/http.js:515:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Driver.execute (/Users/k/Desktop/test/e2e_tests/node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at async toWireValue (/Users/k/Desktop/test/e2e_tests/node_modules/selenium-webdriver/lib/webdriver.js:145:15)
    at async /Users/k/Desktop/test/e2e_tests/node_modules/selenium-webdriver/lib/webdriver.js:195:16
    at async forEachKey (/Users/k/Desktop/test/e2e_tests/node_modules/selenium-webdriver/lib/webdriver.js:189:9)
    at async convertKeys (/Users/k/Desktop/test/e2e_tests/node_modules/selenium-webdriver/lib/webdriver.js:194:3)
```
```


### Operating System

macOS

### Selenium version

Typescript Node v16.14.0

### What are the browser(s) and version(s) where you see this issue?

not a browser issue

### What are the browser driver(s) and version(s) where you see this issue?

not a browser issue

### Are you using Selenium Grid?

_No response_

**Comment by diemol** [comment] 2023-03-13 10:13
This is a duplicate of #11080

**Closed as completed by diemol** 2023-03-13 10:13 UTC
Labels: I-defect, A-needs-triaging
