### ISSUE TITLE
[🐛 Bug]: InvalidArgumentException occurs if find element from shadow root using tag name

### ISSUE THREAD

**Issue by jiawei-wang-SH** [SeleniumHQ/selenium#10127] opened 2021-12-10 06:04 UTC
### What happened?

InvalidArgumentException occurs when I find element from shadow root using tag name with Selenium 4.1.0.

(Looks like only By.cssSelector and By.id works.)

### How can we reproduce the issue?

```shell
WebElement shadowHost = driver.findElement(By.tagName("print-preview-app"));
SearchContext shadowRoot = shadowHost.getShadowRoot();
WebElement shadowContent = shadowRoot.findElement(By.tagName("print-preview-sidebar"));
```

### Relevant log output

```shell
org.openqa.selenium.InvalidArgumentException: invalid argument: invalid locator
  (Session info: chrome=96.0.4664.93)
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'Jiaweis-MacBook-Pro.local', ip: 'fe80:0:0:0:40e:e02d:e55f:b96a%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.5', java.version: '16.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [d8b30fee8e8a7f6a1c696dafe0ac9084, findElementFromShadowRoot {shadowId=f92c3eb8-b7b7-410b-9cf5-4cc6147c304d, using=tag name, value=print-preview-sidebar}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 96.0.4664.93, chrome: {chromedriverVersion: 96.0.4664.45 (76e4c1bb2ab46...}, goog:chromeOptions: {debuggerAddress: 127.0.0.1:9222}, javascriptEnabled: true, pageLoadStrategy: normal, platform: ANY, platformName: ANY, proxy: Proxy(), se:cdp: ws://127.0.0.1:9222/devtool..., se:cdpVersion: 96.0.4664.93, setWindowRect: false, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: d8b30fee8e8a7f6a1c696dafe0ac9084

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:139)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:383)
	at org.openqa.selenium.remote.ShadowRoot.findElement(ShadowRoot.java:55)
```

### Operating System

macOS

### Selenium version

Selenium 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 96.0.4664.93

### What are the browser driver(s) and version(s) where you see this issue?

96.0.4664.45

### Are you using Selenium Grid?

No

**Comment by AutomatedTester** [comment] 2021-12-10 09:28
Duplicate of #10025.

Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)

**Closed as completed by AutomatedTester** 2021-12-10 09:28 UTC
Labels: I-defect, A-needs-triaging
