### ISSUE TITLE
[🐛 Bug]: issue 9586 - still happening - version 4.20.0 - Unable to register node to OpenShift hub 

### ISSUE THREAD

**Issue by e-dsouza** [SeleniumHQ/selenium#13958] opened 2024-05-17 15:14 UTC
### What happened?

Unable to register node - hub in OCP pod, Node on windows server - image used - 4.20.0-20240505

Command run to register node:

java -jar selenium-server-4.20.0.jar node --publish-events tcp://publish-events-xxx-xxx.apps.ocp4- xxx.xxxint.net:443--subscribe-events tcp://subscribe-events-xxx-xxx.apps.ocp4-xxx.xxxint.net:443

Stuck at INFO [NodeServer$1.lambda$start$1] - **Sending registration event** no info on Hub OCP Pod log

**when you try curl on publish event OCP route, pointed to hub port 4442**

C:\>curl-i https://publish-events-xxx-xxx.apps.ocp4-xxx.xxxint.net

HTTP/1.1 502 Bad Gateway

content-length: 107

cache-control: no-cache

content-type: text/html

Set-Cookie: BIGipServerwildcard-apps-ocp4-xx-443=!N/xx+xx; path=/; Httponly; Secure

<html><body><h1>502 Bad Gateway</h1>

The server returned an invalid or incomplete response.

</body></html>

****Curl within OCP hub Pod:****

$ curl localhost:4444 -verbose

*Trying 127.0.0.1:4444...

*Connected to localhost (127.0.0.1) port 4444 (#0)

>GET/HTTP/1.1

> Host: localhost:4444

> User-Agent: curl/7.81.0

> Accept: */*

Mark bundle as not supporting multiuse

<HTTP/1.1 302 Found

<content-length:0

<Location: /ui/
<
*Connection #0 to host localhost left intact

$ curl localhost:4442 -verbose

* Trying 127.0.0.1:4442...

* Connected to localhost (127.0.0.1) port 4442 (#0)

>GET/HTTP/1.1

> Host: localhost:4442

> User-Agent: curl/7.81.0

> Accept: */*

**Received HTTP/0.9 when not allowed**

* Closing connection 0

<

curl: (1) Received HTTP/0.9 when not allowed

$ curl localhost:4443-verbose Trying 127.0.0.1:4443...

* Connected to localhost (127.0.0.1) port 4443 (#0)

> GET/HTTP/1.1

> Host: localhost:4443

> User-Agent: curl/7.81.0

> Accept: */*

>

Received HTTP/0.9 when not allowed**

Closing connection 0

curl: (1) Received HTTP/0.9 when not allowed

### How can we reproduce the issue?

```shell
Info provided above. same issue as this - https://github.com/SeleniumHQ/selenium/issues/9586 , 502 Bad Gatway
```

### Relevant log output

```shell
C:\Users\Public\Selenium Grid>java -jar selenium-server-4.20.0.jar node-publish-events tcp://publish- events-xxx-xxx.apps.ocp4-xxx.xxxint.net:443-subscribe-events tcp://subscribe-events-xxx- xxxx.apps.ocp4-xxx.xxxint.net:443

10:35:33.398 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding

10:35:33.415 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing

10:35:33.827 INFO [UnboundZmqEventBus.<init>]-Connecting to tcp://publish-events-xxx-

xxx.apps.ocp4-xxx.xxxint.net:443 and tcp://subscribe-events-xxx-xxx.apps.ocp4-xxx.xxxint.net:443

10:35:33.976 INFO [UnboundZmqEventBus.<init>] - Sockets created

10:35:34.990 INFO [UnboundZmqEventBus.<init>] - Event bus ready

10:35:35.242 INFO [NodeServer.createHandlers] - Reporting self as: http://xx.xx.xx.xx:5555

10:35:35.460 INFO [NodeOptions.getSessionFactories] Detected 2 available processors

10:35:35.476 INFO [NodeOptions.discoverDrivers] - Looking for existing drivers on the PATH.

10:35:35.476 INFO [NodeOptions.discover Drivers) - Add-selenium-manager true' to the startup command to setup drivers automatically.

10:35:37.273 WARN [SeleniumManager.lambda$runCommand$1] - Unable to discover proper chromedriver version in offline mode

10:35:39.601 WARN [SeleniumManager.lambdaŞrunCommand$1] - Exception managing Microsoft Edge:

Unable to discover proper msedgedriver version in offline mode

10:35:39.601 WARN [SeleniumManager.lambdaSrunCommand$1] The msedgedriver version (112.0.1722.11) detected in PATH at C:\Users\Public\Selenium Grid\msedgedriver.exe might not be

compatible with the detected Microsoft Edge version (124.0.2478.105); currently, msedgedriver is recommended for Microsoft Edge 124.*, so it is advised to delete the driver in PATH and retry

10:35:41.650 WARN [SeleniumManager.lambda$runCommand$1] - Unable to discover proper

geckodriver version in offline mode 10:35:43.227 WARN [SeleniumManager.lambda$runCommand$1] - Unable to discover proper IEDriver Server version in offline mode

10:35:43.545 INFO [NodeOptions.report] - Adding Edge for ("browserName":

"MicrosoftEdge", "platformName": "Windows XP"} 2 times

10:35:43.758 INFO [Node.<init>]-Binding additional locator mechanisms: relative

10:35:44.368 INFO [NodeServer$1.start]-Starting registration process for Node http://xxx.xx.xxx.xxx:5555

10:35:44.377 INFO [NodeServer.execute) - Started Selenium node 4.20.0 (revision 866c76ca80):

http://xxx.xxx.xx.xx:5555

10:35:44.399 INFO [NodeServer$1.lambda$start$1]-Sending registration event...

10:35:54.448 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
```

### Operating System

Windows 2022 server, Linux (OCP pod -hub)

### Selenium version

4.20.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

4.20.0-20240505

**Comment by e-dsouza** [comment] 2024-05-17 17:07
@pujagani Thanks for your response.

This is the command I ran to register node to hub
java -jar selenium-server-4.20.0.jar node --publish-events tcp://publish-events-xxx-xxx.apps.ocp4-xxx.xxxint.net:443 --subscribe-events tcp://subscribe-events-xxx- xxxx.apps.ocp4-xxx.xxxint.net:443

I do not have any github repo/code, I am trying to setup Grid. Hub is running as Openshift Pod. Now trying to add windows server 2022 as node

my issue is exactly same as issue [9586](https://github.com/SeleniumHQ/selenium/issues/9586)

Thanks for your time.

**Comment by diemol** [comment] 2024-05-17 17:38
You should run the Hub and the Nodes in debug mode to understand missing information. The Node sends a message through the event bus, so you need to see that message incoming and being read by the Hub. Then, the Hub will make an HTTP call to the Node to confirm its existence. 

This issue happens when network permissions are not properly set, which ends up as `HTTP/1.1 502 Bad Gateway`

**Comment by e-dsouza** [comment] 2024-05-17 18:45
Okay, I'll have to check OCP team, I believe, how to run container in debug mode.

My guess is that the OCP route isnt getting right response from hub so it is giving 502 Bad gatway error, see below when I do curl within the OCP Pod.

$ curl localhost:4442 -verbose
Trying 127.0.0.1:4442...
Connected to localhost (127.0.0.1) port 4442 (#0)
GET/HTTP/1.1
Host: localhost:4442
User-Agent: curl/7.81.0
Accept: /
Received HTTP/0.9 when not allowed

@KrzysztofC were you able to resolve this?

**Comment by diemol** [comment] 2024-05-17 18:51
The Hub does not reply with 5xx, it should be layer you have on top of it.

**Comment by e-dsouza** [comment] 2024-05-17 19:00
Okay. it doesnt give 5xx but should it not give valid one? again I am just guessing 000 converted to 502 by route

$ curl -o /dev/null -s -w "%{http.code}\n" localhost:4442
000
$ curl -o/dev/null -s -w "%{http code}\n" localhost:4444
302
$ curl -o /dev/null -s -w "%{http_code}\n" localhost:4443
000

**Comment by diemol** [comment] 2024-05-17 19:02
4442 and 4443 are TCP, not HTTP.

**Comment by e-dsouza** [comment] 2024-05-17 19:11
Okay, I may need to check OCP route?

My command is doing TCP using route url

java -jar selenium-server-4.20.0.jar node --publish-events tcp://publish-events-xxxx-xxxx.apps.ocp4-

xxx.xxxint.net:443 --subscribe-events tcp://subscribe-events-xxx-xxxx.apps.ocp4-xxxx.xxxint.net:443

**Comment by e-dsouza** [comment] 2024-05-28 16:00
This isn't resolved yet. I'm still working with OCP admin team to assist with 502 gateway error. So far no positive outcome.

**Comment by diemol** [comment] 2024-07-12 08:25
I will close this issue because the cause of it is outside Selenium's scope. If you have any questions, please use the links shown below.

**Closed as completed** 2024-07-12 08:26 UTC
Labels: B-grid, I-defect, J-issue-template, I-question
