### ISSUE TITLE
[🐛 Bug]: Application hangs on GetDevToolsSession()

### ISSUE THREAD

**Issue by maestroant** [SeleniumHQ/selenium#11785] opened 2023-03-16 16:33 UTC
### What happened?

I ran into a problem when creating a C# WinForm application. In console this is not a problem. Tried on different frameworks all the same. When devTools.GetDevToolsSession() is called, the application hangs and no longer returns.

I'm using the latest version of Visual Studio.
1. Create a new WinForm project
2. Add Nuget Selenium.WebDriver
3. I write this code on the button...

### How can we reproduce the issue?

```shell
private void button1_Click(object sender, EventArgs e)
        {
            IWebDriver driver = new ChromeDriver();
            IDevTools devTools = driver as IDevTools;
            DevToolsSession session = devTools.GetDevToolsSession();   // <-- application freeze!!!
        }
```

### Relevant log output

```shell
-
```

### Operating System

Windows 11

### Selenium version

4.8.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 110.0.5481.78

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 110.0.5481.77

**Comment by diemol** [comment] 2023-03-16 16:41
This is a duplicate of #10008, we would appreciate any help debugging and triaging it.

**Closed as completed by diemol** 2023-03-16 16:41 UTC
Labels: I-defect

**Comment by maestroant** [comment] 2023-03-16 17:26
the odd thing is that it was a working draft. Everything worked. And at some point it stopped.

**Comment by maestroant** [comment] 2023-03-16 17:43
> This is a duplicate of #10008, we would appreciate any help debugging and triaging it.

Running on a thread does not solve the problem!
https://github.com/SeleniumHQ/selenium/issues/10008#issuecomment-1257146263
session == null
