### ISSUE TITLE
Keys didn't match a known command using Firefox

### ISSUE THREAD

**Issue by jonatasnardi** [SeleniumHQ/selenium#2976] opened 2016-10-20 18:00 UTC
Hello,

I am having a problem when I run the selenium with node in Firefox geckodriver.

When I send a simple command "browser.keys(''REGION'');", I get the following error: 
Error: https://files.slack.com/files-pri/T0UB14NFP-F2QU9LZGT/error-selenium.png

"keys did not match a known command"

It happens only in Firefox geckodriver, in Chrome it runs normally.

Help me please, I need to use the Firefox.

I'm using selenium version 3.0.0 and Firefox version 46.

Jonatas Nardi

**Comment by lukeis** [comment] 2016-10-20 18:20
duplicate of #2611

**Closed by lukeis** 2016-10-20 18:20 UTC

**Comment by Gaurav-Ambasta** [comment] 2017-07-19 10:20
@jonatasnardi I am facing the exact same issue, Did you able to figure out a solution for this ?
Appreciate your support.

**Comment by GuhaPrashanthini** [comment] 2018-03-07 05:03
Downgrade your selenium version according to Firefox version.
For instance ,Firefox version :52.0.2 must have  Selenium 3.4.3  along with geckodriver version 0.15.0
