### ISSUE TITLE
[🐛 Bug]: Gekodriver no longer works since 4.0.0 RC1

### ISSUE THREAD

**Issue by Bllacky** [SeleniumHQ/selenium#10014] opened 2021-11-05 08:54 UTC
### What happened?

Environment:
Centos 7
Python 3.8
Firefox 91.2
geckodriver 0.30

What happens?
Firefox will refuse to work after RC2 and above, says "No matching capabilities found'".

Error:
`CEx:SessionNotCreatedException('session not created: No matching capabilities found', None, ['#0 0x5602f0959f93 <unknown>', '#1 0x5602f0434908 <unknown>', '#2 0x5602f048cadc <unknown>', '#3 0x5602f048bee2 <unknown>', '#4 0x5602f048d56d <unknown>', '#5 0x5602f0487973 <unknown>', '#6 0x5602f045ddf4 <unknown>', '#7 0x5602f045ede5 <unknown>', '#8 0x5602f09892be <unknown>', '#9 0x5602f099eba0 <unknown>', '#10 0x5602f098a215 <unknown>', '#11 0x5602f099ffe8 <unknown>', '#12 0x5602f097e9db <unknown>', '#13 0x5602f09bb218 <unknown>', '#14 0x5602f09bb398 <unknown>', '#15 0x5602f09d66cd <unknown>', '#16 0x7f201f087ea5 <unknown>', ''])
`
Code used:
```
    options = FirefoxOptions()
    try:
        driver = webdriver.Firefox(options=options,log_path=TMP_DIR_LOG+'ff_webdriver-%s.log' % randomString(4))
        time.sleep(1)
    except TimeoutException:
        print("Firefox took more than 60 seconds start!")
        print("FFEx:"+repr(e))
    except Exception as e:
        print("FFEx:"+repr(e))
```

### How can we reproduce the issue?

```shell
Try the simple code above with Selenium 4.0.0 RC2 and Python 3.8

The above code works fine with Selenium 4.0.0. RC1
```

### Relevant log output

```shell
CEx:SessionNotCreatedException('session not created: No matching capabilities found', None, ['#0 0x5602f0959f93 <unknown>', '#1 0x5602f0434908 <unknown>', '#2 0x5602f048cadc <unknown>', '#3 0x5602f048bee2 <unknown>', '#4 0x5602f048d56d <unknown>', '#5 0x5602f0487973 <unknown>', '#6 0x5602f045ddf4 <unknown>', '#7 0x5602f045ede5 <unknown>', '#8 0x5602f09892be <unknown>', '#9 0x5602f099eba0 <unknown>', '#10 0x5602f098a215 <unknown>', '#11 0x5602f099ffe8 <unknown>', '#12 0x5602f097e9db <unknown>', '#13 0x5602f09bb218 <unknown>', '#14 0x5602f09bb398 <unknown>', '#15 0x5602f09d66cd <unknown>', '#16 0x7f201f087ea5 <unknown>', ''])
Unable to start driver UnboundLocalError("local variable 'driver' referenced before assignment").
```

### Operating System

Centos 7

### Selenium version

Python 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 91

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.30

**Comment by AutomatedTester** [comment] 2021-11-05 08:59
what is `FirefoxOptions`? That is likely the cause of your problem but it doesn't come from Selenium.

I tried to reproduce your error and couldn't.

```python
davidburns in ~/development/selenium on trunk ● λ python3
Python 3.9.4 (default, Apr  5 2021, 01:50:46) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> from selenium.webdriver.firefox.options import Options
>>> webdriver.__version__
'4.0.0'
>>> driver = webdriver.Firefox(options=Options())
>>> driver.quit()
>>> 
```

**Comment by Bllacky** [comment] 2021-11-05 09:09
```
from selenium.webdriver.firefox.options import Options as FirefoxOptions
```
Also forgot to mention I am running in a venv with the geckodriver binary in venv/bin , but I don't think that's the problem.

> 
> 
> what is `FirefoxOptions`? That is likely the cause of your problem but it doesn't come from Selenium.
> 
> I tried to reproduce your error and couldn't.
> 
> ```python
> davidburns in ~/development/selenium on trunk ● λ python3
> Python 3.9.4 (default, Apr  5 2021, 01:50:46) 
> [Clang 12.0.0 (clang-1200.0.32.29)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from selenium import webdriver
> >>> from selenium.webdriver.firefox.options import Options
> >>> webdriver.__version__
> '4.0.0'
> >>> driver = webdriver.Firefox(options=Options())
> >>> driver.quit()
> >>> 
> ```

**Comment by machinexa2** [comment] 2021-11-05 10:28
My geckodriver didnt work in 4.0.0 so i downloaded it again and it works

**Comment by machinexa2** [comment] 2021-11-05 10:29
redownload geckodriver, it worked for me

**Comment by Bllacky** [comment] 2021-11-05 10:53
> 
> 
> redownload geckodriver, it worked for me. Old geckodriver gave -64 status code

I just tried that, didn't work. 
I downloaded the latest gekodriver from here: https://github.com/mozilla/geckodriver/releases

EDIT: Everthing works fine with selenium 4.0.0 RC1

**Comment by AutomatedTester** [comment] 2021-11-05 11:02
Are you trying to run this in a headless environment?

**Comment by AutomatedTester** [comment] 2021-11-05 11:04
Could you also rebuild your venv to make sure there are no weird old versions being used

**Comment by Bllacky** [comment] 2021-11-05 11:11
> 
> 
> Are you trying to run this in a headless environment?

Yes, I am. I can try to rebuild the venv, but later on, I will keep you posted.

**Comment by AutomatedTester** [comment] 2021-11-19 14:43
@Bllacky could you update the issue please?

**Comment by Bllacky** [comment] 2021-11-19 17:15
> @Bllacky could you update the issue please?

Sorry, been busy. Will try during the weekend.

**Comment by AutomatedTester** [comment] 2021-11-24 11:22
Closing as not reproducible. Please try with 4.1 which is the latest to see if this can recreate the issue.

**Closed as completed by AutomatedTester** 2021-11-24 11:22 UTC
Labels: J-awaiting answer, I-defect

**Comment by Bllacky** [comment] 2021-11-24 12:28
> Closing as not reproducible. Please try with 4.1 which is the latest to see if this can recreate the issue.

I was in the process of testing as you closed this ticket.

I redid the venv, here is the working one:
async-generator==1.10
attrs==21.2.0
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.7
click==8.0.3
cryptography==36.0.0
decorator==5.1.0
fake-useragent==0.1.11
Flask==2.0.2
h11==0.12.0
idna==3.3
itsdangerous==2.0.1
Jinja2==3.0.3
MarkupSafe==2.0.1
outcome==1.1.0
pdfminer.six==20200517
pdfplumber==0.5.28
Pillow==8.4.0
pycparser==2.21
pycryptodome==3.11.0
pyOpenSSL==21.0.0
requests==2.26.0
selenium==4.0.0rc1
six==1.16.0
sniffio==1.2.0
sortedcontainers==2.4.0
trio==0.19.0
trio-websocket==0.9.2
urllib3==1.26.7
validators==0.18.2
Wand==0.6.7
Werkzeug==2.0.2
wsproto==1.0.0

I redid the venv, here is the non-working one:
async-generator==1.10
attrs==21.2.0
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.7
click==8.0.3
cryptography==36.0.0
decorator==5.1.0
fake-useragent==0.1.11
Flask==2.0.2
h11==0.12.0
idna==3.3
itsdangerous==2.0.1
Jinja2==3.0.3
MarkupSafe==2.0.1
outcome==1.1.0
pdfminer.six==20200517
pdfplumber==0.5.28
Pillow==8.4.0
pycparser==2.21
pycryptodome==3.11.0
pyOpenSSL==21.0.0
requests==2.26.0
selenium==4.1.0
six==1.16.0
sniffio==1.2.0
sortedcontainers==2.4.0
trio==0.19.0
trio-websocket==0.9.2
urllib3==1.26.7
validators==0.18.2
Wand==0.6.7
Werkzeug==2.0.2
wsproto==1.0.0


The only difference is selenium version.

**Comment by Bllacky** [comment] 2021-11-24 12:40
I have two Centos servers running Selenium. One physical with Centos 7 and one in AWS with Centos Stream, both have the same problem with selenium above 4.0.0rc1.
