### ISSUE TITLE
Selenium latest Webdriver not supporting Chrome(V-68) in Windows 10(V-1803) ,Session timed out while launching the chrome and doesnot navigates to respective URl

### ISSUE THREAD

**Issue by manyamdeepa** [SeleniumHQ/selenium#6358] opened 2018-09-03 09:26 UTC
## Meta -
OS:  Windows 10(V-1803) 
Selenium Version: Latest(3.5.1)
ChromeDriver 2.41
Browser:Chrome Version -68(64 -bit)

**## Expected Behavior -**
Browser should launch and navigate to respective URl provided

## Actual Behavior -
Selenium latest Webdriver not supporting Chrome(V-68) in Windows 10(V-1803) 

Below is the exception message and stack trace:
Message : The HTTP request to the remote WebDriver server for URL http://localhost:53184/session timed out after 60 seconds.
StackTrace :    at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)

kindly let us know if any solution for the above exception

**Comment by cgoldberg** [comment] 2018-09-03 13:09
Please fill out the issue template.  Include the version of chromedriver you are using along with all other details.

**Comment by lmtierney** [comment] 2018-09-18 01:49
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by manyamdeepa** [comment] 2018-10-08 11:52
Hi please find the requested details as below:

1>use the below mentioned combination of browser and selenium versions.
OS: Windows 10(V-1803)
Selenium Version: Latest(3.5.1)
ChromeDriver 2.41 or (Latest)
Browser:Chrome Version -68(64 -bit) or (latest)
2>Try navigating to the localhost URL in the chrome browser
**Below is the  code used:**

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;

namespace DemoPurpose
{
    public class Program
    {
        public static void Main(string[] args)
        {

            IWebDriver driver = new ChromeDriver();
            driver.Navigate();
            driver.Url = "https://localhost";

        }
    }
}

Expected Result:
should Navigate to respective URL page

Actual:Exception Message
Message : The HTTP request to the remote WebDriver server for URL http://localhost:53184/session timed out after 60 seconds.

Regards,
Deepa

**Comment by nroeper** [comment] 2018-10-22 14:21
Hi all, 
a few colleagues of us have the same issues on some machines. I guess its not the fault of Selenium but of an unexpected system configuration. Any ideas or experience how debug/resolve such issues?

regards,
Nicolas

**Comment by barancev** [comment] 2018-11-06 07:50
@manyamdeepa Latest Selenium version is not 3.5.1, but 3.14.0 (or newer), please retest if the issue is actual for the actual latest version.

**Comment by nroeper** [comment] 2018-11-14 08:59
In our case, the anti virus software was responsible for the sporadic timouts. Maybe this information helps others. 

regards,
Nicolas

**Comment by barancev** [comment] 2019-01-23 09:12
Closing the issue as it was reported against an outdated (and not supoprted anymore) version of software.

**Closed by barancev** 2019-01-23 09:12 UTC
Labels: R-awaiting answer
