### ISSUE TITLE
Firefox 38 crashes on launch with Selenium RC (v1.0) and Selenium Server v2.46.0

### ISSUE THREAD

**Issue by coolgary** [SeleniumHQ/selenium#691] opened 2015-06-20 03:02 UTC
This is basically issue https://github.com/SeleniumHQ/selenium/issues/437, which was closed as fixed (I'm guessing); I tried to reopen it, but I don't have permission.

Note: We have our own Framework built on RC (v1.0), as well as lots of JS user extensions.  We have significant legacy code running RC and will not be migrating it.  Please fix this crash.  Thanks.

I suspect I don't have permission to port the fix myself, but that's also an option, perhaps.

Selenium 2.46.0
Firefox 38.0.1
OpenSUSE 13.1

**Comment by barancev** [comment] 2015-06-20 06:37
This is a duplicate of the issue #627

Selenium RC is deprecated, that implies that it has low priority, so we'll not make a new release just for this fix.

If you're in urgency you can download and use the latest selenium build:
http://ci.seleniumhq.org:8080/job/Build%20All%20Java/lastSuccessfulBuild/artifact/selenium-server-standalone-latest.jar

**Closed by barancev** 2015-06-20 06:37 UTC
