### ISSUE TITLE
[🚀 Feature]: Error message with minimal expected capabilities or wrong ones

### ISSUE THREAD

**Issue by ath0mas** [SeleniumHQ/selenium#13195] opened 2023-11-23 23:13 UTC
### Feature and motivation

Running docker-selenium standalone up to v4.10 I was able to request a session without any _capabilities_, connecting properly to the only node available in the grid.
I got the info from SeleniumHQ/docker-selenium#2023 that since v4.11 some w3c _capabilities_ are required, or an error is returned.
So a minimal set of _capabilities_ seems to be necessary: `"browserName"` only from my tests.
And if wrong _capabilities_ are sent, an error blocks session creation too.

For the first part, about the minimal set of _capabilities_, I suggest to make the error message more explicit.
In my issue in docker-selenium you can see I got a long message for `Error 500` and part of it like `Chrome failed to start: exited normally`.
A good example what we could expect is the same request but made to Appium. The error in this case is really helpful `Failed to create session. 'automationName' can't be blank; 'platformName' can't be blank`.

For the second part, if wrong ones really interrupt session creation, it would be better to have clear information to help fix what is needed.
Is it about non standard _capabilities_, unknown, missing prefixes, and maybe understand how it is resolved (allow list, or at the opposite excluded values, etc)?

### Usage example

Start docker container and try to create a session:
1. `docker run -d -it -p 4444:4444 -p 7900:7900 --shm-size 2g selenium/standalone-chrome:4.15.0-20231122`
1. then, for basic testing I use [appium-inspector](https://github.com/appium/appium-inspector) and set 127.0.0.1, port 4444, and path /wd/hub. Click "Start Session".

The error message returned should be clear about minimal required _capabilities_, and then if some are wrong and how.

**Comment by titusfortner** [comment] 2023-12-31 19:56
First, I don't see anything in the spec that prevents a user from sending an empty JSON object and getting any available node.  (@diemol as best I can tell this is in fact w3c compliant capabilities — https://github.com/SeleniumHQ/docker-selenium/issues/2023#issuecomment-1824238920). But that isn't your issue.

Looking at your error message in the docker repo, it is a duplicate of #12841 which is a Google bug.

**Closed as not planned by titusfortner** 2023-12-31 19:56 UTC
Labels: B-grid, I-enhancement, A-needs-triaging

**Comment by ath0mas** [comment] 2024-01-05 18:36
@titusfortner my point was for a feature or enhancement request, not to declare a bug. My case and log were just here to give context and example.
So, this should be reopened please, as not being a duplicate of the issue you mentioned.

**Comment by titusfortner** [comment] 2024-01-05 18:48
I'm saying there is no feature. The minimal expected capabilities is an empty object. I believe Diego was incorrect that the cause of your issue was invalid W3C, the cause of your issue was with that duplicated bug.

**Comment by ath0mas** [comment] 2024-01-07 17:06
I understand, and you are right. I just tried the same empty request but to standalone-firefox and it's working fine as expected. So my original issue with docker standalone-chrome is indeed a duplicate, and this feature request has no point. 👍 Thanks
