### ISSUE TITLE
GeckoDriver: MoveToElement throwing error

### ISSUE THREAD

**Issue by DestinationQA1** [SeleniumHQ/selenium#3348] opened 2017-01-10 10:07 UTC
OS:  Windows 8.1
Selenium Version:  3.0.1 Selenium Standalone jar
Browser:  Firefox 50.1.0
Browser Version: 50.1.0

## Actual Behavior - Exception is thrown
Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: POST /session/efb411a1-e38b-4eb6-a743-670396e51016/moveto did not match a known command
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'Aparna-PC', ip: '192.168.137.1', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], prefs={}}, appBuildId=20161208153507, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=3628, browserVersion=50.1.0, platformVersion=6.3, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt}]
Session ID: efb411a1-e38b-4eb6-a743-670396e51016
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteMouse.mouseMove(RemoteMouse.java:89)
	at org.openqa.selenium.interactions.MoveMouseAction.perform(MoveMouseAction.java:39)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:50)
	at advanced.ActionMove.main(ActionMove.java:26)
## Steps to reproduce -
System.setProperty("webdriver.gecko.driver","D:\\Selenium\\geckodriver-v0.11.1-win64\\geckodriver.exe");
		
		WebDriver driver = new FirefoxDriver();
		driver.get("http://www.flipkart.com/");
		
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		
		WebElement ElectronicsLink = driver.findElement(By.xpath(".//*[text()='Electronics']"));
		Actions myAction = new Actions(driver);
		myAction.moveToElement(ElectronicsLink).build().perform();

**Comment by traupf** [comment] 2017-01-10 10:57
this is reproduced with geckodriver a new version 0.13.0, not only version 0.11.1

**Comment by AutomatedTester** [comment] 2017-01-10 11:16
Duplicate of ##2285

**Closed by AutomatedTester** 2017-01-10 11:16 UTC

**Comment by Alenguard** [comment] 2017-04-06 16:42
I have the same problem with GeckoDriver version 0.15.
Do you have an issue ?
Thanks.
