### ISSUE TITLE
selenium-webdriver gem version jumped from 3.14.1 to 3.141.0.

### ISSUE THREAD

**Issue by anovadox** [SeleniumHQ/selenium#6626] opened 2018-11-06 21:45 UTC
Seems like we may have skipped 127 minor versions or made a typo.
https://rubygems.org/gems/selenium-webdriver

**Comment by lmtierney** [comment] 2018-11-06 22:34
Duplicate of #6607 an #6613

**Closed by lmtierney** 2018-11-06 22:34 UTC
