### ISSUE TITLE
[🐛 Bug]: Different io.netty (dependency) versions conflict in Selenium 4.5.0 with Java Module System

### ISSUE THREAD

**Issue by Eikthyrnir** [SeleniumHQ/selenium#11153] opened 2022-10-20 15:43 UTC
### What happened?

Error occurred during initialization of boot layer
`java.lang.module.ResolutionException`: Modules `io.netty.transport.epoll` and `io.netty.transport.classes.epoll` export package `io.netty.channel.epoll` to module `org.seleniumhq.selenium.chrome_driver`

### How can we reproduce the issue?

```shell
Require a project uses Java modules system.
Use java 16 or higher (m.b. not necessary).
Create maven project with 
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>4.5.0</version>
</dependency>
and simple entry point like

public static void main(String[] args) {
    System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
    ChromeDriver driver = new ChromeDriver();
}

add module-info.java with requires org.seleniumhq.selenium.chrome_driver;
e.g.
module foo.bug.report {
    requires org.seleniumhq.selenium.chrome_driver;
}
```

### Relevant log output

```shell
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules io.netty.transport.epoll and io.netty.transport.classes.epoll export package io.netty.channel.epoll to module org.seleniumhq.selenium.chrome_driver
```

Using maven dependency analyze command `mvn dependency:tree -Dincludes=*netty*`:
```shell
foo.bug.report:selenium-bug-report:jar:1.0
[INFO] \- org.seleniumhq.selenium:selenium-java:jar:4.5.0:compile
[INFO]    \- org.seleniumhq.selenium:selenium-remote-driver:jar:4.5.0:compile
[INFO]       +- io.netty:netty-buffer:jar:4.1.79.Final:compile
[INFO]       +- io.netty:netty-codec-http:jar:4.1.79.Final:compile
[INFO]       |  +- io.netty:netty-codec:jar:4.1.79.Final:compile
[INFO]       |  \- io.netty:netty-handler:jar:4.1.79.Final:compile
[INFO]       +- io.netty:netty-common:jar:4.1.79.Final:compile
[INFO]       +- io.netty:netty-transport-classes-epoll:jar:4.1.79.Final:compile
[INFO]       +- io.netty:netty-transport-classes-kqueue:jar:4.1.79.Final:compile
[INFO]       +- io.netty:netty-transport-native-epoll:jar:4.1.79.Final:linux-x86_64
[INFO]       +- io.netty:netty-transport-native-kqueue:jar:4.1.79.Final:osx-x86_64
[INFO]       +- io.netty:netty-transport-native-unix-common:jar:4.1.79.Final:compile
[INFO]       +- io.netty:netty-transport:jar:4.1.79.Final:compile
[INFO]       |  \- io.netty:netty-resolver:jar:4.1.79.Final:compile
[INFO]       \- org.asynchttpclient:async-http-client:jar:2.12.3:compile
[INFO]          +- io.netty:netty-codec-socks:jar:4.1.60.Final:compile
[INFO]          +- io.netty:netty-handler-proxy:jar:4.1.60.Final:compile
[INFO]          +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.60.Final:compile
[INFO]          +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.60.Final:compile
[INFO]          \- com.typesafe.netty:netty-reactive-streams:jar:2.0.4:compile
```
we can see, that there are 2 io.netty version in selenium dependencies: 4.1.79 and 4.1.60 (which causes bug).
### Operating System

Windows 10

### Selenium version

4.5.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 106

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 106

### Are you using Selenium Grid?

No

**Comment by Eikthyrnir** [comment] 2022-10-20 15:59
With `exclusions` bug can be fixed (not sure if this is a reliable fix)
exclude dependencies that causes bug (`netty-transport-native-epoll` and `netty-transport-native-kqueue` from v4.1.60)
```
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.5.0</version>
            <exclusions>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-transport-native-epoll</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-transport-native-kqueue</artifactId>
                </exclusion>
            </exclusions>
</dependency>
```
and than add them with version 4.1.79 which is used in other selenium 4.5.0 dependencies:
```
<dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-epoll</artifactId>
            <version>4.1.79.Final</version>
            <scope>compile</scope>
</dependency>
<dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-kqueue</artifactId>
            <version>4.1.79.Final</version>
            <scope>compile</scope>
</dependency>
```

After that fix we can successfully run main, but will obtain runtime error described in recently closed issue #11069

**Comment by Eikthyrnir** [comment] 2022-10-20 16:09
Example project (created with IntelliJ IDEA), chromedriver.exe can be placed to the root directory (near pom.xml file).
To reproduce the bug/fix, comment out/uncomment the exclusions and dependencies from my comment above, i.e. https://github.com/SeleniumHQ/selenium/issues/11153#issuecomment-1285801851

[11153_selenium_issue.zip](https://github.com/SeleniumHQ/selenium/files/9831885/11153_selenium_issue.zip)

**Comment by pujagani** [comment] 2022-10-21 05:29
Thank you for the details. Appreciate the reproducible repo. 
If the error is exactly as described in #11153 then the fix for it is released in 4.5.1. Please try it and let us know if the error still persists.

**Comment by pujagani** [comment] 2022-10-21 05:53
The dependency version difference you see is due to the use of async-http-client library in Selenium. The library is no longer maintained and hence the underlying Netty version it uses is old. We use netty for selenium server as well and try to keep those dependencies to the latest versions. This is causing a version mismatch. Our goal is to move to Java 11 HTTP Client and not depend on the async-http-client. As a first step towards it, we do have Java 11 HTTP client for use https://www.selenium.dev/blog/2022/using-java11-httpclient/. However, currently, the way the jar is prepared, there is a good chance you might face dependency conflicts with it as well. I am afraid till we move to Java 11, there isn't much that can be done except excluding dependencies as you have figured out.

**Comment by Eikthyrnir** [comment] 2022-10-22 00:30
Without exclude/re-include fix I still have same errors caused by Netty dependency version difference. Both in 4.5.1 and 4.5.2. It doesn't matter if we use Java 11+ HTTP Client with
```
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-http-jdk-client</artifactId>
    <version>4.5.1</version>
</dependency>
```

But now with excluding/re-including fix there is no runtime error, thank you. Maybe this exclude/re-include method can be temporary used in selenium jar preparing process to prevent such Netty dependency conflicts?

**CC**: @pujagani

**Comment by pujagani** [comment] 2022-10-27 05:56
I understand your point. The jar packaging is mainly done by bazel and I am not sure how much of that we control. I don't understand much on that front, but I will take a look to see if it is a simple fix. But again cannot promise to invest a lot of time into it since our long-term goal is only to support Java 11 client. I understand the issue persists currently with it because of how things are packaged but when async-http-client is no longer used then it will go away.

**Comment by Eikthyrnir** [comment] 2022-10-27 23:34
@pujagani Ok, I understand, thanks one more time and good luck with the Java 11 HTTP Client ;)

**Closed as completed** 2022-11-01 10:32 UTC
Labels: J-awaiting answer, C-java, I-defect
