### ISSUE TITLE
[🐛 Bug]: Not stable when tested in Edge IE mode with IEDriver 4.0.0.0

### ISSUE THREAD

**Issue by fujimotosts** [SeleniumHQ/selenium#10144] opened 2021-12-14 05:34 UTC
### What happened?

Since previous IEDriver had a problem with opening child windows in Edge IE mode, we have downloaded the new IEDriver 4.0.0.0 and been testing the stablility.
Recursively accessing a page with window.open and calling getWindowHandler through the new IEDriver, selenium access will become unstable in 2 ways.

First, when recursive access reaches about 20 times, it will be unable to get the window handle.
Using the normal IE or normal Edge, the problem with not occur and could get the child window handle permanently, so this problem seems only to occur in IE mode.

Second, selenium timeout occurs.
Exception example)
Exception in thread "main" org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
The timeout occurs in many methods, like close(closing driver), getWindowhandlers, findelement(xpath), possibilty the driver control has a problem.

In closing we want to know if this problem reproduces in every windows environment, and the cause of this problem.

[Test.txt](https://github.com/SeleniumHQ/selenium/files/7708951/Test.txt)
[IEMode_1st.txt](https://github.com/SeleniumHQ/selenium/files/7708952/IEMode_1st.txt)
[IEMode_2nd.txt](https://github.com/SeleniumHQ/selenium/files/7708947/IEMode_2nd.txt)
[IEMode_3rd.txt](https://github.com/SeleniumHQ/selenium/files/7708948/IEMode_3rd.txt)
[IEMode_4th.txt](https://github.com/SeleniumHQ/selenium/files/7708949/IEMode_4th.txt)
[IEmode_timeout.txt](https://github.com/SeleniumHQ/selenium/files/7708950/IEmode_timeout.txt)

### How can we reproduce the issue?

```shell
We have made a simple test program Test.java(Test.txt) that recurisively window.open and get handler of the child window.
When it fails to get the handle, the program will retry 10 times to get the window handle, but in this case no matter you retry you wouldn't be able to get the window handle.
On failing the 10 time retry, it will abort and end the program.
When ending the program it will output which loop it failed to get the handle.
(Otherwise it means it successed n-1 loops to get the handle.)

The result, we have tried about 4 cycles, each cycle was
1st. 38 loops
2nd. 34 loops
3rd. 45 loops
4th. 5 loops

For the timeout occasion sample, please refer IEmode_timeout.txt
```

### Relevant log output

```shell
Refer to the attached file
IEMode_1st.txt
IEMode_2nd.txt
IEMode_3rd.txt
IEMode_4th.txt
IEmode_timeout.txt
```

### Operating System

Windows 10

### Selenium version

Java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Edge v.96.0.1054.43 (IE Mode)

### What are the browser driver(s) and version(s) where you see this issue?

Internet Explorer Driver 4.0.0(32bit)

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment] 2021-12-26 02:34
Are you sure it is an issue of not getting the window handle and not an issue of sending the `\n` key to the link not opening another window?

You can turn on logging in the driver to see what is going on, but it might not log the crash: https://www.selenium.dev/documentation/ie_driver_server/#command-line-switches

When it comes down to it, IE Driver was written to drive IE. If it is working in IE, but broken in IE mode on Edge, it's likely an issue with IE Mode in Edge, not in IE Driver, which means we'd need to get Microsoft involved.

**Comment by yagitk** [comment] 2021-12-29 11:53
I am a colleague of fujimotosts. Thank you for your reply.

There are 2 symptoms, the main one is it could not get the child window handle, 
obviously the child window is open so the \n key is sent. 

As in the previous sentence we have checked out normal IE and normal edge, basically the problem will not occur and works fine, this is a problem only for IE mode in edge.

As with the sample program, we would be glad if you could check reproduction of the problem.
Thank you for your logging inforamtion,
please excuse us Japan is in a new year holiday, for new evidence we will contact you after new year.

**Comment by fujimotosts** [comment] 2022-01-05 04:51
I attached the following logs.
①console_windohandle.txt
②driver_windowhandle.txt
③java_windowhandle.txt
④console_timeout.txt
⑤driver_timeout.txt
⑥java_timeout.txt

The top three are logs that can not get the window handle.(①～③)
The bottom three are logs that timeout occurs.(④～⑥)
② and ⑤ are IEdriver trace logs.

[console_windohandle.txt](https://github.com/SeleniumHQ/selenium/files/7812064/console_windohandle.txt)
[driver_windowhandle.txt](https://github.com/SeleniumHQ/selenium/files/7812065/driver_windowhandle.txt)
[java_windowhandle.txt](https://github.com/SeleniumHQ/selenium/files/7812066/java_windowhandle.txt)
[console_timeout.txt](https://github.com/SeleniumHQ/selenium/files/7812067/console_timeout.txt)
[driver_timeout.txt](https://github.com/SeleniumHQ/selenium/files/7812068/driver_timeout.txt)
[java_timeout.txt](https://github.com/SeleniumHQ/selenium/files/7812069/java_timeout.txt)

**Comment by titusfortner** [comment] 2022-01-05 14:23
This appears to be a duplicate of #8868 
Look at this comment for details from Microsoft — https://github.com/SeleniumHQ/selenium/issues/8868#issuecomment-978217729

**Closed as completed by titusfortner** 2022-01-05 14:23 UTC
Labels: D-IE, I-defect
