### ISSUE TITLE
command line server for the IE driver has stopped working

### ISSUE THREAD

**Issue by CellOcean** [SeleniumHQ/selenium#6154] opened 2018-07-13 03:32 UTC
## Meta -
OS:  win7
Selenium Version:  3.12.1
Browser:  ie11

Browser Version:  
11.0.9600.190351S 32-bit

## Actual Behavior -
"command line server for the IE driver has stopped working" dialog appeared,and IEDriverServer.exe crashed randomly.

logs from iedriverserver
I 2018-07-13 11:18:56:441 c:\projects\webdriver\cpp\iedriver\variantutilities.cpp(257) Unknown type of dispatch is found in result, assuming IHTMLElement
I 2018-07-13 11:18:56:457 c:\projects\webdriver\cpp\iedriver\script.cpp(257) Exception message was: '088EC0FC'
I 2018-07-13 11:18:56:458 c:\projects\webdriver\cpp\iedriver\script.cpp(258) Exception source was: '088E89DC'
W 2018-07-13 11:18:56:468 c:\projects\webdriver\cpp\iedriver\elementfinder.cpp(293) Unable to get 14 found element

logs from client
2018-07-13 11:18:49,443 [4] INFO  SeleniumPolice.StatusCrawler: OpenQA.Selenium.WebDriverException: Error executing JavaScript
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.get_Displayed()
   at OpenQA.Selenium.Support.UI.ExpectedConditions.<>c.<VisibilityOfAllElementsLocatedBy>b__8_1(IWebElement element)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenQA.Selenium.Support.UI.ExpectedConditions.<>c__DisplayClass8_0.<VisibilityOfAllElementsLocatedBy>b__0(IWebDriver driver)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   at SeleniumPolice.StatusCrawler.FetchData() in E:\jiancezhan\2.0\gongan\selenium\SeleniumPolice\StatusCrawler.cs:line 243
2018-07-13 11:19:56,250 [4] INFO  SeleniumPolice.StatusCrawler: OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:60873/session/967bbda3-e503-4318-9d46-70b706b4280e/element/c81e7bde-1dad-4c68-b0a0-63e7b824e489/elements timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.FindElements(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebElement.FindElementsByTagName(String tagName)
   at OpenQA.Selenium.By.<>c__DisplayClass22_0.<TagName>b__1(ISearchContext context)
   at OpenQA.Selenium.By.FindElements(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebElement.FindElements(By by)
   at SeleniumPolice.StatusCrawler.FetchData() in E:\jiancezhan\2.0\gongan\selenium\SeleniumPolice\StatusCrawler.cs:line 275

**Comment by seanksullivan** [comment] 2018-07-23 15:21
I experienced this problem, too.  I didn't have time to diagnose, so, I reverted the Selenium.WebDriver.IEDriver from 3.13.0 to 3.11.1 (what my project was using successfully, previously) - with success.

**Comment by zshel** [comment] 2018-07-23 19:04
I had the same issue on both 3.12 and 3.13 (server and driver) on Windows 10 and with IE version 11.371.16299.0
It seems to be related to running parallel IE browser sessions, because if I limit it to 5 IE sessions per machine, everything runs fine.  But once I start pushing past that, things start going haywire and IE sessions start crashing left in right.
Plenty of resources are left too cpu is below 40% and ram is less than 20%, so it's not the machine choking.
The same machines are also able to run 20 chrome browsers in parallel no problem, with the same test.

**Comment by zshel** [comment] 2018-08-06 18:04
@barancev Just bumping to figure out if there is any update on this...

**Comment by barancev** [comment] 2018-08-14 07:08
Closing the issue as there is no reproduction scenario provided.

**Closed by barancev** 2018-08-14 07:08 UTC
Labels: D-IE, R-awaiting answer
