### ISSUE TITLE
Setting user error during remote driver creation

### ISSUE THREAD

**Issue by WarleyGabriel** [SeleniumHQ/selenium#5026] opened 2017-11-07 17:00 UTC
## Meta -
OS: Linux
Selenium Version: 3.7.0
Browser: Firefox
Browser Version: 56.0.2 (32-bit)

## Expected Behavior -
To create driver in a Selenium grid on Firefox using an user profile
- Use a container with a Selenium grid
- Create an user and set its extension configurations
- Execute tests, passing as parameter the user created in the previous step
Obs.: It works when driver is locally created.

## Actual Behavior -
```
DesiredCapabilities capabilities
capabilities = DesiredCapabilities.firefox()
FirefoxOptions firefoxOptions = new FirefoxOptions()
FirefoxProfile profile = new ProfilesIni().getProfile("profile_name")
firefoxOptions.setProfile(profile)
capabilities.setCapability(FirefoxOptions.FIREFOX_OPTIONS, firefoxOptions)

def d = new RemoteWebDriver(
        new URL(gridUri), capabilities
    )
```
## Result -
During debug, the extension is set on its profile, but no extensions are visible.
![extension](https://user-images.githubusercontent.com/30508069/32506694-67a123aa-c3cc-11e7-8538-5db12ecd02fe.png)
![profile without extension](https://user-images.githubusercontent.com/30508069/32506703-69c4ba20-c3cc-11e7-93af-eb0a06a73b5d.png)

Browser is open without user's extension.

**Comment by barancev** [comment] 2017-11-08 13:15
Duplicate of #4664

**Closed by barancev** 2017-11-08 13:15 UTC
Labels: C-grid, D-firefox
