### ISSUE TITLE
Trying to install an extension through selenium, not working in firefox

### ISSUE THREAD

**Issue by vivekprm** [SeleniumHQ/selenium#7080] opened 2019-04-02 06:36 UTC
## 🐛 Bug Report

Installation of modheader extension in firefox through selenium (using below code) not working:

```groovy
        def profile = new FirefoxProfile()
        URL url = this.getClass().getResource(System.getProperty("user.dir") + "/src/test/resources/extensions/modheader-2.2.5-an+fx.xpi")
        def modifyHeaders = new File(url.toURI())
        try {
            profile.addExtension(modifyHeaders)
        } catch (IOException e) {
            e.printStackTrace()
        }
        profile.setPreference("extensions.modify_headers.currentVersion", "2.2.5-an+fx")
        profile.setPreference("modifyheaders.headers.count", 1)
        profile.setPreference("modifyheaders.headers.action0", "Add")
        profile.setPreference("modifyheaders.headers.name0", "X-Nitra-Side")
        profile.setPreference("modifyheaders.headers.value0", "passive")
        profile.setPreference("modifyheaders.headers.enabled0", true)
        profile.setPreference("modifyheaders.config.active", true)
        profile.setPreference("modifyheaders.config.alwaysOn", true)

        def capabilities = new DesiredCapabilities()
        capabilities.setBrowserName("firefox")
        capabilities.setPlatform(org.openqa.selenium.Platform.ANY)
        capabilities.setCapability(FirefoxDriver.PROFILE, profile)

        driver = { new FirefoxDriver(capabilities) }
```
However if I try to install through browser, I am able to install it successfully.

## To Reproduce

Just add above code in GebConfig.groovy while setting up firefox driver.

## Expected behavior

Should be able to see the addon installed and request header added.

## Environment

OS: MacOS 10.13.06
Browser: Firefox 
Browser version: 66.0.2
Browser Driver version: GeckoDriver 0.24
Language Bindings version: Java 8 
Selenium Grid version (if applicable): 3.141.59

**Comment by barancev** [comment] 2019-04-09 19:54
Please define "not working". It thows an exception, which one? It does not throw, but the extension is not installed? Anything else?

**Comment by vivekprm** [comment] 2019-04-17 08:26
Thanks for the response. I am not seeing plugin installed in firefox and in log I am seeing below warnings, but doesn't seem related to modheader plugin:

`13:48:27.215 [DEBUG] [TestEventLogger]     1555489107214        addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
13:48:27.216 [DEBUG] [TestEventLogger]     1555489107215        addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
13:48:27.216 [DEBUG] [TestEventLogger]     1555489107215        addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*`

**Comment by barancev** [comment] 2019-04-19 10:51
It seems to be a known issue, a duplicate of #6548

**Closed by barancev** 2019-04-19 10:51 UTC
Labels: C-java, D-firefox, R-awaiting answer
