### ISSUE TITLE
Firefox 38 doesn't work with WebDriver 2.45.1

### ISSUE THREAD

**Issue by szimek** [SeleniumHQ/selenium#437] opened 2015-04-09 07:23 UTC
Firefox beta has been just updated to version 38 and it no longer works with WebDriver 2.45.1. I'm getting the following error:

```
Using FirefoxDriver directly...
[launcher] Running 1 instances of WebDriver
ERROR - Unable to start a WebDriver session.

/Users/.../node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877
      var result = fn();
                   ^
Error: Failed to install profile; firefox terminated with Result(code=null, signal=SIGSEGV)
    at Error (<anonymous>)
    at /Users/.../node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/firefox/binary.js:238:15
    at [object Object].promise.ControlFlow.runInFrame_ (/Users/.../node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)
    at [object Object].promise.Callback_.goog.defineClass.notify (/Users/.../node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:2464:25)
    at [object Object].promise.Promise.notify_ (/Users/.../node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:563:12)
    at Array.forEach (native)
    at Object.goog.array.forEach (/Users/.../node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/array/array.js:203:43)
    at [object Object].promise.Promise.notifyAll_ (/Users/.../node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:552:16)
    at [object Object].goog.async.run.processWorkQueue [as _onTimeout] (/Users/.../node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/Users/.../node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:155:22)
    at Function.webdriver.WebDriver.createSession (/Users/.../node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:129:30)
    at new Driver (/Users/.../node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/firefox/index.js:272:36)
    at [object Object].DirectDriverProvider.getNewDriver (/Users/.../node_modules/gulp-protractor/node_modules/protractor/lib/driverProviders/direct.js:75:16)
    at [object Object].Runner.createBrowser (/Users/.../node_modules/gulp-protractor/node_modules/protractor/lib/runner.js:180:37)
    at /Users/.../node_modules/gulp-protractor/node_modules/protractor/lib/runner.js:257:21
    at _fulfilled (/Users/.../node_modules/gulp-protractor/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/Users/.../node_modules/gulp-protractor/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/Users/.../node_modules/gulp-protractor/node_modules/protractor/node_modules/q/q.js:759:13)
    at /Users/.../node_modules/gulp-protractor/node_modules/protractor/node_modules/q/q.js:573:44
    at flush (/Users/.../node_modules/gulp-protractor/node_modules/protractor/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3
```

The latest stable version of Firefox (37.01) works fine. I'm using OS X 10.10.2, protractor 2.0.0 and selenium-webdriver 2.45.1.

**Comment by andreastt** [comment] 2015-04-09 10:03
@barancev?

**Comment by barancev** [comment] 2015-04-09 11:13
Summoning @jleyba, it seems to be a javascript binding issue.

**Comment by barancev** [comment] 2015-04-09 12:32
By the way, do you use a custom Firefox profile or just allow Selenium to create a new empty profile?

**Comment by szimek** [comment] 2015-04-09 13:06
I'm not sure, I guess (hope) it's creating a new empty one.

**Comment by jleyba** [comment] 2015-04-09 15:59
All Selenium 2.45.1 tests pass against Firefox 38.0b1 on Ubuntu 14.04.

Will check OSX when I have a chance, but it may be a few days.

**Comment by szimek** [comment] 2015-04-09 16:07
Sorry, false alarm. I've just reinstalled Firefox 38 beta on top of 37 stable (previously it updated itself automatically) and everything works fine. Most likely it was some issue with permissions caused by Firefox updater.

**Comment by mzgol** [comment] 2015-05-14 18:48
I experience the same issue, see https://github.com/angular/protractor/issues/2134. I got my Firefox 37 updated to v38 normally. I think this issue should be reopened.

**Comment by markvantilburg** [comment] 2015-05-14 19:48
2.45.0: Firefox 38 crashes after every test.
Windows 2012 R2 server, Firefox 38, empty profile.

**Comment by tobli** [comment] 2015-05-15 20:50
Same issue, running on OS X 10.10.3

**Comment by feigaochn** [comment] 2015-05-16 02:47
same issue,
selenium 2.45.0
firefox 38.0
os x 10.9.5

**Comment by szimek** [comment] 2015-05-18 07:05
Actually I still have this issue as well. I tried reinstalling Firefox 38(.0.1), but it fails with the same error message.

**Comment by scypio** [comment] 2015-05-18 14:58
Firefox auto-updated today to version 38  and selenium stopped working immediately after.

I needed to downgrade it to version 37 and disable auto-updates.

**Comment by kcyeu** [comment] 2015-05-18 15:25
Same issue on Windows.
* Selenium v2.45.0, with Core v2.45.0. Built from revision 5017cb8
* Firefox 38.0.1
* Windows 7 x86

**Comment by theansaname** [comment] 2015-05-18 15:47
Having the same issues tho not a severe as some of you folks.  
firefox crash report

Process:               firefox-bin [47293]
Path:                  /Applications/Firefox.app/Contents/MacOS/firefox-bin
Identifier:            org.mozilla.firefox
Version:               38.0.1 (3815.5.13)
Code Type:             X86-64 (Native)
Parent Process:        ruby [47290]
Responsible:           iTerm [1602]
User ID:               502

Date/Time:             2015-05-18 11:19:30.437 -0400
OS Version:            Mac OS X 10.10.3 (14D136)
Report Version:        11

Time Awake Since Boot: 170000 seconds
Time Since Wake:       8200 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000

**Comment by CITguy** [comment] 2015-05-18 16:16
same issue,
selenium 2.45.0
firefox 38.0.1
os x 10.8.5

It doesn't seem to block interaction with the browser, it just brings up the crash report window every time I run protractor tests.

**Comment by ericmandel** [comment] 2015-05-19 01:12
same issue after last night's auto-update
selenium 2.45.1
firefox 38.0.1
os x 10.10.3

**Comment by nareshrao** [comment] 2015-05-19 06:13
Facing the same issue with firefox 38.0.1 and mac os x 10.9.5

**Comment by yabab** [comment] 2015-05-19 11:54
Facing the same issue with Firefox 38.0.1, OSX 10.10.1 and Webdriver 2.45.0

**Comment by sunqing99** [comment] 2015-05-19 17:20
I got the same issue on my Windows 7 machine. The issue happens only for Firefox 38 (including 38.0, 38.0.1, and a number of betas). Firefox 37 was fine.

Here is the steps to reproduce:

Save below code as StartFirefox.java
/////////////////////
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxProfile;

public class StartFirefox {
public static void main(String[] args) {
String startURL = "http://www.seleniumhq.org/";
FirefoxProfile profile = new FirefoxProfile();
profile.setAcceptUntrustedCertificates(true);
WebDriver wd = new FirefoxDriver(profile);
wd.get(startURL);
}
}
////////////////

Then run it as follows,
SET PATH=%PATH%;"C:\Program Files (x86)\Java\jdk1.8.0_45\bin"
javac -cp selenium-java-2.45.0.jar StartFirefox.java
java -cp .;selenium-java-2.45.0.jar;libs\* StartFirefox

With Firefox 37 it will just open up Firefox and get the URL. But with Firefox 38, what I got is a popup saying "Firefox has stopped working", with the following in event log:

<?xml version="1.0"?>
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error"/>
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-05-19T16:58:18.000000000Z"/>
    <EventRecordID>3413</EventRecordID>
    <Channel>Application</Channel>
    <Computer>93SYLX1mymachine</Computer>
    <Security/>
  </System>
  <EventData>
    <Data>firefox.exe</Data>
    <Data>38.0.1.5611</Data>
    <Data>55540a1a</Data>
    <Data>xul.dll</Data>
    <Data>38.0.1.5611</Data>
    <Data>55541969</Data>
    <Data>c0000005</Data>
    <Data>0035669b</Data>
    <Data>11a0</Data>
    <Data>01d09254ff17c382</Data>
    <Data>C:\Program Files (x86)\Mozilla Firefox\firefox.exe</Data>
    <Data>C:\Program Files (x86)\Mozilla Firefox\xul.dll</Data>
    <Data>3ef8ffc6-fe48-11e4-b97f-24fd5232421b</Data>
  </EventData>
</Event>

**Comment by mcwp** [comment] 2015-05-19 20:27
Same.
selenium 2.45.0
firefox 38.0.1
os x 10.9.5

**Comment by rdharrison2** [comment] 2015-05-19 21:21
I raised a bug on Firefox a while ago for this I think: https://bugzilla.mozilla.org/show_bug.cgi?id=1157672

Sadly no one has commented on it but not surprising as there are so many open bugs.

**Comment by sataris** [comment] 2015-05-20 13:05
Same, 

Selenium 2.45.0
firefox 38
Ubuntu 15.0.4

**Comment by jayp-ezdi** [comment] 2015-05-20 13:43
Same,

Selenium 2.45.0
firefox 38
windows 7

**Comment by imtihoss** [comment] 2015-05-20 18:35
Same issue

selenium 2.45.0
firefox 38.0.1
OSX 10.10.1

**Comment by andreastt** [comment] 2015-05-20 18:39
I’m locking this issue due to all the people repeating themselves in the comments.  If the issue is confirmed by a developer, it’s fine.

**Comment by jleyba** [comment] 2015-05-22 17:54
Fixed for
- java in 6fc17a0cba238af9d76f5fe6e32f73ac8958c19e
- python/ruby in 9160eaba5a983ae06050078ec0e03b10654a5eb6
- js in 144f5ee7eb7d705bad90346bb2b494ff8212fb4c

.NET client needs to be updated then we should be able to close this.

**Comment by jleyba** [comment] 2015-05-22 18:29
.NET updated in 04e68154a6d57d737aa64304312137d55d6ae897

**Closed by jleyba** 2015-05-22 18:29 UTC
Labels: D-firefox
