### ISSUE TITLE
[🐛 Bug]: Getting Nullpointer execption when I am trying to use devtools with selenium4 java

### ISSUE THREAD

**Issue by bachhavdipak** [SeleniumHQ/selenium#10246] opened 2022-01-12 13:15 UTC
### What happened?

I am trying to use dev tools with the help of the remote driver. I am facing a Nullpointer exception.

### How can we reproduce the issue?

```shell
Please go through the below repo to find a reproducible example.
https://github.com/bachhavdipak/devtoolSelenium4
```

### Relevant log output

```shell
java.lang.NullPointerException
	at org.google.pageObjects.HomePage.navigateTo(HomePage.java:28)
	at org.google.pageDefinitions.HomePageSteps.navigateToPage(HomePageSteps.java:14)
	at org.google.pageDefinitions.HomePageSteps$ByteBuddy$oppLuclh.navigateToPage$accessor$slrDMVOm(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:504)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:484)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:458)
	at net.thucydides.core.steps.StepInterceptor.runOrSkipMethod(StepInterceptor.java:210)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:197)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:85)
	at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)
	at org.google.pageDefinitions.HomePageSteps$ByteBuddy$oppLuclh.navigateToPage(Unknown Source)
	at org.google.stepDefinitions.StepDefinitions.theGuestUserIsOnContactPage(StepDefinitions.java:25)
	at ✽.the Guest user is on the google page(file:///C:/Users/username/serenityDevtools/src/test/resources/features/Google.feature:5)
```

### Operating System

Windows10

### Selenium version

Java

### What are the browser(s) and version(s) where you see this issue?

 ChromeDriver 97

### What are the browser driver(s) and version(s) where you see this issue?

 ChromeDriver 97.0.4692.71 

### Are you using Selenium Grid?

4

**Comment by titusfortner** [comment] 2022-01-12 17:53
Can you provide a more concise code example that reproduces the behavior?

**Comment by bachhavdipak** [comment] 2022-01-13 11:35
Hi,

I have provided github repo which we will help you to understand y issue. I
am trying to use devtool with experitest. I am using webdriver manager
dependency. WebDriverManager is an open-source Java library that carries
out the management (i.e., download, setup, and maintenance) of the drivers
required by Selenium.

While executing my test throwing a null pointer exception.

Regards,
Dipak

**Comment by titusfortner** [comment] 2022-01-13 13:41
That stack trace doesn't have any lines related to Selenium. 
I'm not going to pull down a full repo with a bunch of dependencies and wade through the results to figure out if it is even a Selenium issue. If you can extract a specific instance of the problem, we can duplicate it and pinpoint the problem. http://sscce.org/

**Comment by titusfortner** [comment] 2022-02-07 01:46
Closing due to lack of reproducible use case

**Closed as completed by titusfortner** 2022-02-07 01:46 UTC
Labels: J-awaiting answer, C-java, I-defect, B-devtools
