### ISSUE TITLE
Drivers should throw "invalid argument" error on an attempt to click file input

### ISSUE THREAD

**Issue by jiteshsojitra** [SeleniumHQ/selenium#4843] opened 2017-10-10 14:52 UTC
Selenium leaves control after clicking to file explorer Browse button in MS Edge. This works fine in Chrome and Firefox but absolutely blocking to run next step in the code.  I tried code via all possible ways and below code works to click  to Browse button but after this step selenium leaves control because  file explorer window opens. Is this Selenium or MS Edge driver issue? 

**Environment:**
    Selenium version - Latest 3.6.0
    Browser - MS Edge
    MS Edge Driver - Latest Release 15063
    Application type - Ajax web

**Steps:**
    1. Open ajax web application through MS Edge (works)
    2. Click to browse button through web driver core or java script method (works)
    3. Selenium gone, leaves control till we close file explorer button (doesn't work) - this works fine in GC and FF.
    **4 (Blocked).** Send key to type file name or implement AutoIt script (works)
    **5 (Blocked).** Click to open button via AutoIt script (works)
    **6 (Blocked).** File attached fine (works)

**Working code:**
    driver.findElement(By.id("browseID")).click();
And
    WebElement we = null;
((JavascriptExecutor)ClientSessionFactory.session().webDriver()).executeScript("document.getElementsByName('browseName')[0].click()", we);

![selenium or ms edge leaves control](https://user-images.githubusercontent.com/21263826/31393157-b42900ba-adf8-11e7-98ee-4755d8873865.png)

This is actually blocking attachment functionality and it would be great if selenium will fix this. So far i just see Autoit is the solution as a 3rd party software but it is very tedious to add separate scripts for every browse buttons in the application, any code by selenium blocks due to OS dialog appearance. Anyone faced this issue?

**Comment by barancev** [comment] 2017-10-10 17:48
Don't click file inputs, just sendKeys to them.

**Comment by jiteshsojitra** [comment] 2017-10-10 18:13
Sorry but its not good to close the major issue like this where execution gets blocked. There must be some issue from Selenium or MS Edge driver side which needs to be put on attention to them.

**Comment by barancev** [comment] 2017-10-10 18:18
It's not an issue, but intended behavior. To enter a value to a file input one have to sendKeys to it. Click to a file input raises a native file selection dialogue that can't be handled by selenium.

**Comment by jiteshsojitra** [comment] 2017-10-10 18:19
This is working fine in Chrome and Firefox so i'm pretty sure this is an issue with MS Edge. Please re-read the issue.

**Comment by barancev** [comment] 2017-10-11 14:42
You're right, I was too hasty closing the issue. But I have to reframe it.

In original Selenium API it was implicitly prohibited to click file input fields, behavior was undefined, and drivers could autoclose file selectoin dialogue, or block on it, any behavior was "allowed".

But W3C WebDriver standard is mode definitive, it says "If the element is an input element in the file upload state return error with error code invalid argument." [1]

None of the drivers implemens this requirement yet. So I'll reopen this issue on legacy Firefox driver and IE driver developed by Selenium team. And I'll raise new issues on other drivers in the corresponding trackers.

[1] https://w3c.github.io/webdriver/webdriver-spec.html#element-click

**Comment by barancev** [comment] 2017-10-11 19:56
Test for this feature: d48e75b4c3e8bde3001eb002bd4f93360c895ab9
Legacy Firefox driver: 0e680bca1047d1809d142ce86f4c83f4cb30659d

**Comment by barancev** [comment] 2017-10-12 05:59
Issue on chromedriver: https://bugs.chromium.org/p/chromedriver/issues/detail?id=2073
Issue on geckodriver: https://github.com/mozilla/geckodriver/issues/1011

**Comment by KS261187** [comment] 2017-12-22 05:01
I tried passing in the send keys and still it leaves the browser open. I can use autoit for the file upload control but it is getting timed out, since it is not leaving the control on sendkeys.

**Comment by chintan1904** [comment] 2018-07-05 10:11
Any update on this issue? or any workaround that can be used for Edge browser

**Comment by barancev** [comment] 2021-01-26 20:40
According to the current test status it's fixed in both Firefox and Chrome drivers.

**Closed by barancev** 2021-01-26 20:40 UTC
Labels: D-chrome
