### ISSUE TITLE
[🐛 Bug]: Can't load the url with CFT version 116 using mac M2 and selenium 4.11

### ISSUE THREAD

**Issue by hoa-pham82** [SeleniumHQ/selenium#12503] opened 2023-08-06 16:56 UTC
### What happened?

I'm new to Selenium and I'm trying to run this code:

```
`import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.manager.SeleniumManager;

import java.time.Duration;

public class Test {
    public static void main(String[] args) {
        ChromeOptions options = new ChromeOptions();
       options.setBrowserVersion("116");
        String driverPath = SeleniumManager.getInstance().getDriverPath(options, false ).driverPath;
        WebDriver driver = new ChromeDriver(options);
        driver.get("https://google.com");
        driver.manage().timeouts().implicitlyWait(Duration.ofMillis(500));
        System.out.println(driverPath);
        driver.quit();
}}`
```

And I got this issue:

`Exception in thread "main" java.lang.IllegalArgumentException: http://:-1/json/version could not be parsed into a proper Uri, missing host
	at org.asynchttpclient.uri.Uri.create(Uri.java:73)
	at org.asynchttpclient.uri.Uri.create(Uri.java:62)
	at org.asynchttpclient.RequestBuilderBase.setUrl(RequestBuilderBase.java:147)
	at org.asynchttpclient.Dsl.request(Dsl.java:73)
	at org.openqa.selenium.remote.http.netty.NettyMessages.toNettyRequest(NettyMessages.java:57)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:55)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:48)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:96)
	at org.openqa.selenium.devtools.CdpEndpointFinder.getCdpEndPoint(CdpEndpointFinder.java:58)
	at org.openqa.selenium.chromium.ChromiumDriver.lambda$new$3(ChromiumDriver.java:144)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:144)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
	at Test.main(Test.java:13)`

### How can we reproduce the issue?

```shell
Please use the above code to reproduce the issue. 
Note about my environment: 

- MacOS M2 Ventura 13.5
- Selenium v4.11
- Java JDK v17
- Installed Chrome browser: Version 115.0.5790.114 (Official Build) (arm64)
```

### Relevant log output

```shell
- I can run the code with my installed chrome v115
- Chrome v116 is already downloaded in my folder: ./cache/selenium..
```

### Operating System

MacOS

### Selenium version

Selenium 4.11.0

### What are the browser(s) and version(s) where you see this issue?

I'm using chrome 115

### What are the browser driver(s) and version(s) where you see this issue?

I test with chrome 116

### Are you using Selenium Grid?

N/A

**Comment by diemol** [comment] 2023-08-06 17:06
Duplicate of #12457

**Closed as completed** 2023-08-06 17:06 UTC
Labels: I-defect
