### ISSUE TITLE
[🚀 Feature]: Provide snapshot builds of the trunk branch

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#11397] opened 2022-12-09 08:48 UTC
### Feature and motivation

It might be usefull to provide snapshot builds of the trunk branch to get faster user feedback.

Maven has support for SNAPSHOT releases to ensure they get only temprary cached.
https://maven.apache.org/guides/getting-started/index.html#What_is_a_SNAPSHOT_version

I guess the other deployment systems should also support this.

### Usage example

Currently the user must setup a local bazel installation to build a snapshot and test if an issue is gone.
Or the users will wait for the next release to test if the issue is gone, slowing down the retest of issues.

**Comment by diemol** [comment] 2022-12-09 08:50
Duplicate of #11355

**Closed as completed by diemol** 2022-12-09 08:50 UTC
Labels: I-enhancement

**Comment by joerg1985** [comment] 2022-12-09 08:53
@diemol sorry, had this in mind for some days and did not check if someone did open a new issue regarding this

**Comment by diemol** [comment] 2022-12-09 08:54
No worries, thanks for sharing your thoughts!

**Comment by titusfortner** [comment] 2022-12-09 13:05
Actually if mvnrepository has a way to do this without polluting the entire list of versions, that might be better then storing on github?

Either way, any help investigating a way to do this is appreciated.
