### ISSUE TITLE
Actions.keyDown doesn't work in IE driver, cannot make Ctrl+Click. RequireWindowFocus and Robot are not appropriate

### ISSUE THREAD

**Issue by naiad09** [SeleniumHQ/selenium#4296] opened 2017-07-12 11:05 UTC
Hello, all.

Problem:
Actions Chain 'Pressing a key -> clicking the element -> releasing the key' behaves as
there is no pressing a key in Internet Explorer.
```
System.setProperty("webdriver.ie.driver", "C:\iedriverserver.exe");
WebDriver driver = new InternetExplorerDriver();
driver.get("http://seleniumhq.org/")

WebElement element = driver.find_element(By.LINK_TEXT,"Selenium WebDriver")
new Actions(driver)
    .keyDown(Keys.LEFT_CONTROL)
    .click(element)
    .keyUp(Keys.LEFT_CONTROL)
    .build().perform();
```
Expected result: Link is opened in a new tab.
Actual result: Link is opened in the same tab (click was applied without Ctrl).

I know that there were many the same issue reports, i.e. https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/3734

I know possible **workarounds**: RequireWindowFocus capability and awt.Robot. I'd underline what it's not a fix, just workaround.
Unfortunately, it doesn't appropriate for our project. We have many UI autotests (about 1500 TestNG methods), they run about 20 hours. We run our autotests with Jenkins and slave virtual machines. And these both workarounds doesn't work then **VM is disconnected** (usual situation, we cannot hold connection for long time).
RequireWindowFocus on disconnected VM blocks all the clicks: **VM doesn't have GUI**, and IE driver cannot make any clicks.
awt.Robot doesn't work **without GUI** too. Click is just processed without Ctrl (expected multiple elements selected, but clicks are applied to elements one by one, and in the end only the last element selected).

Please help to address this issue. Let me know if you need additional information.

Win 7/8/10
Java JDK 1.8.0_131
Selenium 2.53.1
IE driver 3.3.0.0
IE browser: 11.962.10586.0

**Comment by p0deje** [comment] 2017-07-12 14:34
Reading through the conversations in other issues, I think this issue will be closed as "won't fix" because that is currently an expected behavior. If I understand correctly, there is no way to send "CTRL" key event to a non-focused window using Windows API, so there is not much we can do about that.

I'll keep it hanging in case Jim has anything to add.

**Comment by naiad09** [comment] 2017-07-12 14:50
@p0deje do you mean it's a technology limitation?

**Comment by p0deje** [comment] 2017-07-12 15:01
Yes, that's how I understand it from reading https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/3734.

**Comment by barancev** [comment] 2017-07-16 18:55
IEDriverServer requires GUI too, it's a requirement. We definetly are not going to spend effort to make it work in GUI-less environment. But, yes, let Jim say the last word.

**Comment by diemol** [comment] 2020-05-21 10:40
This issue has gone stale and it is pretty much clear that it is the expected behavior after reading the comments above.

**Closed by diemol** 2020-05-21 10:40 UTC
Labels: A-needs decision, D-IE
