### ISSUE TITLE
[🐛 Bug]: In Visual Studio in Visual Basic in Selenium Webdriver In New Edge.EdgeDriver

### ISSUE THREAD

**Issue by Bradley501** [SeleniumHQ/selenium#10580] opened 2022-04-27 09:55 UTC
### What happened?

In Visual Studio, in Visual Basic.Net in NuGet Selenium.Webdriver:

In New Edge.EdgeDriver, correctly getting 
Dim driver = New Edge.EdgeDriver(EdgeDriverService, EdgeOptions)
locally, and  wrongly getting 

 Public  driver = New Edge.EdgeDriver(EdgeDriverDirectory, EdgeOptions) if declared globally.

Should be always 
driver = New Edge.EdgeDriver(EdgeDriverService, EdgeOptions)
and not driver = New Edge.EdgeDriver(EdgeDriverDirectory, EdgeOptions).

Could someone fix this problem.

### How can we reproduce the issue?

```shell
Declare
Public EdgeDriverService2 = Edge.EdgeDriverService.CreateDefaultService(Application.StartupPath)
    Public EdgeOptions2 = New Edge.EdgeOptions
Public driver = New Edge.EdgeDriver(EdgeDriverService2, EdgeOptions2) in a VB module.

Visual Studio incorrectly made 
Public driver = New Edge.EdgeDriver(EdgeDriverDirectory, EdgeOptions2)

Could you fix this.


In a Module in a Sub, following works okay

Dim EdgeDriverService2 = Edge.EdgeDriverService.CreateDefaultService(Application.StartupPath)
    Dim EdgeOptions2 = New Edge.EdgeOptions
Dim driver = New Edge.EdgeDriver(EdgeDriverService2, EdgeOptions2) 
in a VB module.
```

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error	BC30519	Overload resolution failed because no accessible 'New' can be called without a narrowing conversion:
    'Public Overloads Sub New(edgeDriverDirectory As String, options As EdgeOptions)': Argument matching parameter 'edgeDriverDirectory' narrows from 'Object' to 'String'.
    'Public Overloads Sub New(edgeDriverDirectory As String, options As EdgeOptions)': Argument matching parameter 'options' narrows from 'Object' to 'EdgeOptions'.
    'Public Overloads Sub New(service As EdgeDriverService, options As EdgeOptions)': Argument matching parameter 'service' narrows from 'Object' to 'EdgeDriverService'.
    'Public Overloads Sub New(service As EdgeDriverService, options As EdgeOptions)': Argument matching parameter 'options' narrows from 'Object' to 'EdgeOptions'.	WindowsApp5	C:\Users\davie\source\repos\WindowsApp1\Module1.vb	25	Active
```

### Operating System

Windows 10

### Selenium version

Selenium.Webdriver 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Edge Version 100.0.1185.50

### What are the browser driver(s) and version(s) where you see this issue?

I don't know

### Are you using Selenium Grid?

I don't know

**Comment by Bradley501** [comment] 2022-04-27 10:27
Put
Public EdgeDriverService2 = Edge.EdgeDriverService.CreateDefaultService(Application.StartupPath)
    Public EdgeOptions2 = New Edge.EdgeOptions
Public driver = New Edge.EdgeDriver(EdgeDriverService2, EdgeOptions2)
 in a VB module.
Error as Visual Studio is trying find an EdgeDriverDirectory variable where EdgeDriverService2 variable is in line
Public driver = New Edge.EdgeDriver(EdgeDriverService2, EdgeOptions2)

**Comment by diemol** [comment] 2022-04-28 19:58
Is it possible for you to elaborate more and explain what the issue is? Please follow the issue template. 

Also, can you please provide a GitHub repository with the whole setup so we can clone it and reproduce the issue?

Without proper information this issue will probably go stale and be closed.

**Comment by diemol** [comment] 2022-05-05 10:43
I will close this as there was no more input.

**Closed as completed** 2022-05-05 10:44 UTC
Labels: I-defect, J-issue-template
