### ISSUE TITLE
[🐛 Bug]: Error using user-data-dir= in Chrome 103.0.5060.53

### ISSUE THREAD

**Issue by cjdduarte** [SeleniumHQ/selenium#10799] opened 2022-06-23 00:28 UTC
### What happened?

When using **chrome_options.add_argument('user-data-dir='** in Chrome 103 the error occurs:

Selenium.common.exceptions.WebDriverException: Message: unknown error: unexpected command response
  (Session info: chrome=103.0.5060.53)

**if I remove this parameter, it works.**

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('user-data-dir=C:\\Perfil')

driver_path = 'chromedriver.exe'
service = Service(driver_path)
driver = webdriver.Chrome(service=service,options=chrome_options)

driver.get("https://google.com")
```

### Relevant log output

```shell
elenium.common.exceptions.WebDriverException: Message: unknown error: unexpected command response
  (Session info: chrome=103.0.5060.53)
Stacktrace:
Backtrace:
	Ordinal0 [0x007E6463+2188387]
	Ordinal0 [0x0077E461+1762401]
	Ordinal0 [0x00693D78+802168]
	Ordinal0 [0x00687210+750096]
	Ordinal0 [0x0068675A+747354]
	Ordinal0 [0x00685D3F+744767]
	Ordinal0 [0x0068557C+742780]
	Ordinal0 [0x00699BF3+826355]
	Ordinal0 [0x006ECF6D+1167213]
	Ordinal0 [0x006DC5F6+1099254]
	Ordinal0 [0x006B6BE0+945120]
	Ordinal0 [0x006B7AD6+948950]
	GetHandleVerifier [0x00A871F2+2712546]
	GetHandleVerifier [0x00A7886D+2652765]
	GetHandleVerifier [0x0087002A+520730]
	GetHandleVerifier [0x0086EE06+516086]
	Ordinal0 [0x0078468B+1787531]
	Ordinal0 [0x00788E88+1805960]
	Ordinal0 [0x00788F75+1806197]
	Ordinal0 [0x00791DF1+1842673]
	BaseThreadInitThunk [0x75F7FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77987A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77987A6E+238]
```

### Operating System

Windows 10 and Manjaro

### Selenium version

Python (Selenium 4)

### What are the browser(s) and version(s) where you see this issue?

Chrome 103

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 103.0.5060.53

**Comment by amark720** [comment] 2022-06-23 08:18
Me too facing this same issue! 

OS- Windows 10, Language- Python
Here is the Traceback of my device:

 ```
 File "C:/Users/gs-2764/PycharmProjects/TestProject/StudyBullet/StudyBullet_Rss_Post.py", line 320, in <module>
    driver.close()
  File "C:\Users\gs-2764\PycharmProjects\TestProject\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 688, in close
    self.execute(Command.CLOSE)
  File "C:\Users\gs-2764\PycharmProjects\TestProject\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gs-2764\PycharmProjects\TestProject\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unexpected command response
  (Session info: chrome=103.0.5060.53)
```

**Comment by diemol** [comment] 2022-06-23 08:59
Is this happening only with Chrome 103? Did it happen with Chrome 102?

**Comment by dianis55** [comment] 2022-06-23 08:59
![image](https://user-images.githubusercontent.com/107199631/175260308-a1e457f9-8c59-4e91-905e-12982d9c1de8.png)
+
Having a same problem now

**Comment by amark720** [comment] 2022-06-23 09:02
> Is this happening only with Chrome 103? Did it happen with Chrome 102?

Not faced this issue in Chrome 102 version. I'm seeing this issue after updating to chrome 103.

**Comment by cjdduarte** [comment] 2022-06-23 09:04
Only on 103.
On 102 it works.

**Comment by cjdduarte** [comment] 2022-06-23 09:07
I found this:
[https://bugs.chromium.org/p/chromedriver/issues/detail?id=4121](https://bugs.chromium.org/p/chromedriver/issues/detail?id=4121)

**Comment by diemol** [comment] 2022-06-23 09:25
Nice, there is already a Chromium issue. I will close this and then you can all follow that one.

**Closed as completed by diemol** 2022-06-23 09:25 UTC

**Comment by nyteghost** [comment] 2022-06-23 12:17
I found this:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4121 

This is from May 20th. Is it still relevant?

**Comment by Biswajeet-webonise** [comment] 2022-06-23 13:32
> ![image](https://user-images.githubusercontent.com/107199631/175260308-a1e457f9-8c59-4e91-905e-12982d9c1de8.png) + Having a same problem now

I am facing the same issue

**Comment by caocanhlinh** [comment] 2022-06-23 13:44
I am also facing this same issue!

**Comment by tamabytedev** [comment] 2022-06-23 13:58
Is there a temporary fix?

**Comment by jedwible** [comment] 2022-06-23 14:20
Same error here.

WebDriverError: unknown error: unexpected command response
  (Session info: chrome=103.0.5060.53)
      at Object.throwDecodedError (node_modules\selenium-webdriver\lib\error.js:522:15)
      at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:549:13)
      at Executor.execute (node_modules\selenium-webdriver\lib\http.js:475:28)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Driver.execute (node_modules\selenium-webdriver\lib\webdriver.js:735:17)
      at async Driver.findElements (node_modules\selenium-webdriver\lib\webdriver.js:1061:17)

**Comment by diemol** [comment] 2022-06-23 15:13
There is nothing we can do at the Selenium project because this is a bug in Chrome. Please post your comments and ways to reproduce it in the linked Chromium issue above.

**Comment by saybinem** [comment] 2022-06-23 15:28
I am facing the same issue in Ubuntu 20.04 with Chrome 103. My quick fix was downgrading to 102.
`site-packages/selenium/webdriver/remote/webdriver.py", line 324, in get
    self.execute(Command.GET, {'url': url})
site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unexpected command response
  (Session info: chrome=103.0.5060.53)`

**Comment by imhighyat** [comment] 2022-06-23 16:45
Having the same issue here, using .NET + Specflow. I had Chrome 102 yesterday and it was working fine. Updated to 103 today and started seeing this same error.

**Comment by diemol** [comment] 2022-06-23 16:47
Folks, posting "I have the same issue" does not help much, we cannot do anything because this is a Chrome issue. Please add yourself as a watcher to https://bugs.chromium.org/p/chromedriver/issues/detail?id=4121

**Comment by TrueObsidian** [comment] 2022-06-24 18:46
Fixed in version 104. "Resolved issue 4121: WebDriver command sometimes fails with "unexpected command response" [Pri-1]"
I chose to upgrade to chrome beta (104.0.5112.20) and point to it with: 
`options.binary_location = r"C:\Program Files\Google\Chrome Beta\Application\chrome.exe"`
Using the matching chromedriver [https://chromedriver.storage.googleapis.com/index.html?path=104.0.5112.20/](url)

**Comment by ancineart** [comment] 2022-06-25 18:59
Hi!
Not shure, got a close problem :"Message: unknown error: cannot determine loading status from unknown error: unexpected command response", as I think after yesterday update ChromeDriver 103.0.5060.53. Spent half day with troubleshooting. For me fix  is just: adding 

time.sleep(9)
#before line 
browser.get(url)

Now it works. Changes before:
a)
pip3 install chromedriver --upgrade
pip3 install chromedriver-binary  --upgrade
pip3 install selenium-wire --upgrade
pip3 install selenium --upgrade
b)
pip3 uninstall selenium-wire #4.6.4
c)
pip3 install selenium-wire #4.3.0
d)again
pip3 install selenium-wire #4.6.4

I think a)-d) is wrong way,  just add time.sleep(9) and go sleep;) Hope it help...

**Comment by ShunyaWatanabe** [comment] 2022-06-28 08:19
Still happening with the error message below for me

```
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: unexpected command response
  (Session info: chrome=104.0.5112.20)
```

**Comment by RKorets** [comment] 2022-06-28 20:27
me helps this solution
Chrome(service=Service(ChromeDriverManager(version='104.0.5112.20').install()), options=option)

**Comment by mmani648** [comment] 2022-06-29 13:09
> 

yeah on 103

**Comment by sjafroudi** [comment] 2022-06-29 17:47
A temporary fix I've found is to just quit webdriver and create a new instance whenever you encounter a WebDriverException or InvalidSessionIdException.

**Comment by RKorets** [comment] 2022-06-29 19:55
option.add_argument("--incognito")
this partly fix problem too

**Comment by aleem11** [comment] 2022-06-29 20:59
Just add a little pause hold before the place when the driver initiates an URL, as I got success in java using this technique:
```
//Java code
Thread.sleep(5000);
driver.get("https://www.google.com");
```

**Comment by kfc9999** [comment] 2022-06-30 02:00
I have encountered exactly same issue. 
I then upgrade the Chromedriver to 104 and Chrome Browser to 104 beta.
All are working fine now. 

### **Updated at 17:38 on 30.6.2022:** Seem even Chrome 104 still has problem. Finally, I have switched to Microsoft Edge and then my script is working well now...

**Comment by otomikesuy** [comment] 2022-07-01 10:25
## My current best practice.


1. Delete google chrome.
2. Download chrome version `102.0.5005.63` from here([windows](https://google-chrome.en.uptodown.com/windows/versions) /[mac](https://google-chrome.en.uptodown.com/mac/versions))
3. then use chrome driver version `102.0.5005.27`. see the example below.
```python
driver = webdriver.Chrome(executable_path=ChromeDriverManager(version='102.0.5005.27').install(), chrome_options=options)
```
4. don't forget to disable google chrome's auto-update.

**Comment by kfc9999** [comment] 2022-07-01 13:12
> ## My current best practice.
> 1. Delete google chrome.
> 2. Download chrome version `102.0.5005.63` from here([windows](https://google-chrome.en.uptodown.com/windows/versions) /[mac](https://google-chrome.en.uptodown.com/mac/versions))
> 3. then use chrome driver version `102.0.5005.27`. see the example below.
> 
> ```python
> driver = webdriver.Chrome(executable_path=ChromeDriverManager(version='102.0.5005.27').install(), chrome_options=options)
> ```
> 
> 4. don't forget to disable google chrome's auto-update.

Thanks a lot. 
But I have switched to Edge already.

**Comment by ghost** [comment] 2022-07-01 18:40
I am also facing this issue since 2022/06/30.

**Comment by kfc9999** [comment] 2022-07-02 01:45
> I am also facing this issue since 2022/06/30.

You can follow this https://github.com/SeleniumHQ/selenium/issues/10799#issuecomment-1172194912.
Downgrade to 102 and disabled auto-update.

I couldn't find the offline installer of Chrome 102 so I gave up and I have switched to Edge.

THen it works great..!

**Comment by TruongHaiDang** [comment] 2022-07-02 03:21
> Just add a little pause hold before the place when the driver initiates an URL, as I got success in java using this technique:
> 
> ```
> //Java code
> Thread.sleep(5000);
> driver.get("https://www.google.com");
> ```

This solution is good. working without remove "user-data-dir=" in C#

**Comment by kfc9999** [comment] 2022-07-02 04:16
> > Just add a little pause hold before the place when the driver initiates an URL, as I got success in java using this technique:
> > ```
> > //Java code
> > Thread.sleep(5000);
> > driver.get("https://www.google.com");
> > ```
> 
> This solution is good. working without remove "user-data-dir=" in C#

Thanks for sharing!
I am using Python. Seem the behaviour is so strange,
I have the same script to scrape data from two different sites. 
One is working fine with Chrome 103 but another had some problems.
I observed that Chrome 103 cannot read user cookie data in the dir so some setting lost and cannot scrape accurate data.

**Comment by abhishek9556** [comment] 2022-07-04 08:24
Tried with different combinations using webdriver manager and facing the same issue. Selenium grid with chrome nodes are also not working, as code is thrwoing 504 gateway error. It was working fine before the update.

**Comment by kevinl1210** [comment] 2022-07-07 10:07
> option.add_argument("--incognito") this partly fix problem too

This solution works for me.

**Comment by cansalih17** [comment] 2022-07-29 12:58
> ### What happened?
> When using **chrome_options.add_argument('user-data-dir='** in Chrome 103 the error occurs:
> 
> Selenium.common.exceptions.WebDriverException: Message: unknown error: unexpected command response (Session info: chrome=103.0.5060.53)
> 
> **if I remove this parameter, it works.**
> 
> ### How can we reproduce the issue?
> ```shell
> from selenium import webdriver
> from selenium.webdriver.chrome.service import Service
> 
> chrome_options = webdriver.ChromeOptions()
> chrome_options.add_argument('user-data-dir=C:\\Perfil')
> 
> driver_path = 'chromedriver.exe'
> service = Service(driver_path)
> driver = webdriver.Chrome(service=service,options=chrome_options)
> 
> driver.get("https://google.com")
> ```
> 
> ### Relevant log output
> ```shell
> elenium.common.exceptions.WebDriverException: Message: unknown error: unexpected command response
>   (Session info: chrome=103.0.5060.53)
> Stacktrace:
> Backtrace:
> 	Ordinal0 [0x007E6463+2188387]
> 	Ordinal0 [0x0077E461+1762401]
> 	Ordinal0 [0x00693D78+802168]
> 	Ordinal0 [0x00687210+750096]
> 	Ordinal0 [0x0068675A+747354]
> 	Ordinal0 [0x00685D3F+744767]
> 	Ordinal0 [0x0068557C+742780]
> 	Ordinal0 [0x00699BF3+826355]
> 	Ordinal0 [0x006ECF6D+1167213]
> 	Ordinal0 [0x006DC5F6+1099254]
> 	Ordinal0 [0x006B6BE0+945120]
> 	Ordinal0 [0x006B7AD6+948950]
> 	GetHandleVerifier [0x00A871F2+2712546]
> 	GetHandleVerifier [0x00A7886D+2652765]
> 	GetHandleVerifier [0x0087002A+520730]
> 	GetHandleVerifier [0x0086EE06+516086]
> 	Ordinal0 [0x0078468B+1787531]
> 	Ordinal0 [0x00788E88+1805960]
> 	Ordinal0 [0x00788F75+1806197]
> 	Ordinal0 [0x00791DF1+1842673]
> 	BaseThreadInitThunk [0x75F7FA29+25]
> 	RtlGetAppContainerNamedObjectPath [0x77987A9E+286]
> 	RtlGetAppContainerNamedObjectPath [0x77987A6E+238]
> ```
> 
> ### Operating System
> Windows 10 and Manjaro
> 
> ### Selenium version
> Python (Selenium 4)
> 
> ### What are the browser(s) and version(s) where you see this issue?
> Chrome 103
> 
> ### What are the browser driver(s) and version(s) where you see this issue?
> ChromeDriver 103.0.5060.53
> 
> ### Are you using Selenium Grid?
> _No response_

is the problem fixed? could you give information

**Comment by kfc9999** [comment] 2022-07-31 02:45
I don't know. Some ppl said this problem would be fixed in Chrome version 104 but I have tried the beta and still have problem. I hope the final version of 104 would fix.

However, I have switched to Edge driver and it works well.
