### ISSUE TITLE
[🐛 Bug]:  Unable to create session: Could not start a new session. (when opening more than 32 sessions at once)

### ISSUE THREAD

**Issue by GuntramG** [SeleniumHQ/selenium#12233] opened 2023-06-20 12:48 UTC
### What happened?

We are trying to process many pages through Selenium at the same time. We can get up to 32 sessions, but as soon as we try to increase the session count further, all sessions start becoming janky, they are error prone and crash. Also, we get many errors that the sesssion cannot be started (error log at the bottom)

I've tried more then 5 versions of selenium (between 102 and latest 114) with the appropriate chrome driver and chrome version, but sooner or later the whole thing ends up with the errors above. Chrome is always crashing. I've also tried running in hub - node configuration, or standalone.

Why is chrome crashing? I am certain that memory is not a problem because I've also tried increasing jvm heapsize adding "-Xms64g -Xmx80g" in the command line above, but it didn;t help. Following selenium's requirements I have installed and use oracle jdk (not jre) but still no help or whatsoever. What can I do to run multiple sessions (more then 32 i.e.)?

### How can we reproduce the issue?

```shell
OS: Ubuntu 22.04.2 LTS, running on a 32-Core Ryzen™ 9 and 128GB RAM. 

java: java version "20.0.1" 2023-04-18 Java(TM) SE Runtime Environment (build 20.0.1+9-29) Java HotSpot(TM) 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)

Google Chrome 114.0.5735.133

command to launch selenium:
xvfb-run -a java -Dwebdriver.chrome.driver="/home/forge/domain/storage/selenium/chromedriver-114.0.5735.16" -jar "/home/forge/domain/storage/selenium/selenium-server-4.10.0.jar" standalone --override-max-sessions true --max-sessions 60 --port 4646 --allow-cors true

I am creating the session like RemoteWebDriver::create($host, $capabilities,3600000,3600000);

            '--remote-allow-origins=*',
            '--window-size=1920,1080',
            '--enable-experimental-extension-apis',
            '--disable-infobars',
            '--disable-notifications',
            '--disable-device-discovery-notifications',
            '--disable-gpu',
            '--allow-outdated-plugins',
            '--disable-web-security',
            '--allow-running-insecure-content',
            '--allow-file-access-from-log_files',
            '--audio-output-channels=0',
            '--ignore-certificate-error',
            '--disable-dev-shm-usage',
            '--disable-browser-side-navigation',
            '--dns-prefetch-disable',
            '--disable-geolocation',
            '--disable-search-geolocation-disclosure',
            '--enable-strict-powerful-feature-restrictions',
            '--disable-translate',
            '--disable-sync',
            '--mute-audio',
            '--lang=en-US',
            '--use-fake-ui-for-media-stream',
            '--use-fake-device-for-media-stream',
            '--allow-file-access-from-files',
            '--reduce-security-for-testing',
            '--allow-insecure-localhost',
            '--allow-legacy-extension-manifests',
            '--allow-loopback-in-peer-connection',
            '--allow-outdated-plugins',
            '--allow-unsecure-dlls',
            '--alsa-mute-device-name',
            '--also-emit-success-logs',
            '--alsa-mute-element-name',
            '--no-first-run',
            '--disable-default-apps',
            '--disable-extensions-http-throttling',
            '--disable-blink-features=AutomationControlled',
```

### Relevant log output

```shell
mem stats 
Mem:       131576260    15530844    76271352       82296    39774064   114669600
Swap:        5237752           0     5237752


10:39:23.636 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to create session: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: 
Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
Host info: host: 'domain', ip: '127.0.0.1'
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-75-generic', java.version: '20.0.1'
Driver info: driver.version: unknown
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-75-generic', java.version: '20.0.1'
Driver info: driver.version: unknown
10:39:23.636 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. 
Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
Host info: host: 'domain', ip: '127.0.0.1'
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-75-generic', java.version: '20.0.1'
Driver info: driver.version: unknown
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-75-generic', java.version: '20.0.1'
Driver info: driver.version: unknown
	at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:210)
	at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:69)
	at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:147)
	at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:467)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:643)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:560)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:814)
	at org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:773)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

### Operating System

Ubuntu 22.04.2 LTS

### Selenium version

Java selenium-server-4.10.0.jar

### What are the browser(s) and version(s) where you see this issue?

google-chrome-stable_114.0.5735.133-1_amd64.deb (tried other versions too)

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver-114.0.5735.16

### Are you using Selenium Grid?

4.10.0 (tried with and without grid)

**Comment by diemol** [comment] 2023-06-21 08:14
The rule of thumb is to have 1CPU and 1GB per session. Which makes sense that things start failing when you go over 32 sessions, as you have 32 CPU. When the session starts (Chrome opening) is when more CPU is used, sometimes 1.5 or 2 CPU. With 128GB the issue is around CPU, not memory.

The approach would be to diagnose the situation, start measuring disk, CPU, and RAM. So you understand what resources are being used when things start to crash. With that, you might combine those values to understand when it better to start sessions. 

An alternative might be to use [Docker containers](https://github.com/SeleniumHQ/docker-selenium) and set a limit of 1CPU and 1GB RAM to each one, with that you will be sure that you don't go over the 32 CPUs. Sessions might take a bit longer to start since there is less CPU available per session request, but it could bring more stability. 

I will close this issue as there is not much we can do about it, as it is a resources issue. I will leave some links below in case you want to join our Slack channel and ask more questions.

**Closed as completed** 2023-06-21 08:14 UTC
Labels: I-question
