### ISSUE TITLE
Not able to login to the website using Alert.send_keys() in google chrome

### ISSUE THREAD

**Issue by arunkrh** [SeleniumHQ/selenium#7017] opened 2019-03-10 11:27 UTC
I am not able to login to the site using Alert.send_keys()
My System configuration:
OS: Windows10 64bit
Browser Version: 72.0.3
Selenium: 3.141
Python: 3.7
Chrome Driver: 72.0.3

Code tried:1
+++++++++++
browser = webdriver.Chrome()
browser.get('http://10.179.230.232/desktop/')

alert = Alert(browser)
alert.send_keys("apc"+str(Keys.TAB)+"apc")
alert.accept()
++++++++
Code Tried: 2
++++++++
browser = webdriver.Chrome()
browser.get('http://10.179.230.232/desktop/')

Alert.send_keys("apc")
browser.switch_to.alert()
Alert.send_keys("apc")
+++++++++
Error:
Traceback (most recent call last):
File "C:/DataVerificationSQA/UITest/dceUITest.py", line 47, in 
alert.send_keys("apc"+str(Keys.TAB)+"apc")
File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\common\alert.py", line 105, in send_keys
self.driver.execute(Command.SET_ALERT_VALUE, {'text': keysToSend})
File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoAlertPresentException: Message: no such alert
(Session info: chrome=72.0.3626.121)
(Driver info: chromedriver=72.0.3626.69 (3c16f8a135abc0d4da2dff33804db79b849a7c38),platform=Windows NT 10.0.14393 x86_64)

__
git

Firefox is working fine.
++++++++++
browser = webdriver.Firefox()
browser.get(r'http://10.179.230.232/desktop/')
alert = Alert(browser)
alert.send_keys(f'apc{Keys.TAB}apc')
alert.accept()
++++++++++++

Please help me to solve this issue.
Thanks

**Comment by rapidroamer** [comment] 2019-03-24 11:46
Possible duplicate of : https://github.com/SeleniumHQ/selenium/issues/5137

Handling authentication is out of the scope of Selenium.

If your query is related to usage , please send questions to the [selenium user group](
https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

**Comment by diemol** [comment] 2019-03-24 18:37
@arunkrh 

We have spent some time improving the issue templates in order to allow users to provide enough information when an issue is reported, which will end up helping the maintainers and collaborators to provide a better answer when an issue is created. Why did you delete the template? When possible, please provide the information requested in the original template. Until then, we cannot continue.

Additionally, please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by barancev** [comment] 2019-03-29 15:20
Duplicate of #5137
Yes, support for native auth dialogs is out of scope for the moment,
It should be added to the specification first: https://github.com/w3c/webdriver/issues/385

**Closed by barancev** 2019-03-29 15:20 UTC
Labels: R-awaiting answer
