### ISSUE TITLE
Drag and drop issue 

### ISSUE THREAD

**Issue by srinivasgoud-n** [SeleniumHQ/selenium#6131] opened 2018-07-09 10:48 UTC
Drag and drop issue.

Issue: Drag and drop is not working. 

Please find below code snippet:

String selectElement= "testing";
WebElement source = driver.findElement(by.xpath("//*[text()='"+selectElement+"']"));
WebElement source = driver.findElement(by.xpath("(//div[@class='viewlet-svg'])[1]"));

Actions builder = new Actions(driver);
builder.dragAndDrop(source, target).build().perform();

**Comment by barancev** [comment] 2018-07-09 11:32
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by pradeep636** [comment] 2018-07-10 07:12
@barancev Actually the application is not available publicly. But here is the problem we faced. It is basically a ReactJS application and we tried all the drag and drop options. But none of them worked. So is there any such limitation for drag and drop for ReactJS application?

The HTML of the draggable element looks is below.

<div draggable="true" class="1531206764" style="position: relative; width: 100%; height: 36px; line-height: 36px; vertical-align: middle;"><span class="icon-table" style="color: rgb(102, 102, 102); position: relative; font-size: 24px; display: inline-block; user-select: none; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; width: 24px; height: 24px; padding: 6px;"></span><p class="viewlet-title" title="Viewlet-1" style="height: 36px; line-height: 36px; vertical-align: middle; padding: 0px; margin: 0px; position: absolute; left: 36px; top: 0px; bottom: 0px; right: 72px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; font-size: 12px; font-family: &quot;clear sans regular&quot;; color: rgb(102, 102, 102);">Viewlet-1</p><div class="list-tools"><div style="display: block;"><button tabindex="0" type="button" style="border: 10px; box-sizing: border-box; display: inline-block; font-family: &quot;clear sans regular&quot;; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); cursor: pointer; text-decoration: none; margin: 0px; padding: 6px; outline: none; font-size: 0px; font-weight: inherit; position: absolute; overflow: visible; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; width: 36px; height: 36px; right: 9px; top: 0px; bottom: 0px; background: none;"><div><span class="icon-delete" color="#d8d8d8" style="color: rgb(216, 216, 216); position: relative; font-size: 15px; display: inline-block; user-select: none; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms;"></span></div></button></div><button value="1531206764" tabindex="0" type="button" style="border: 10px; box-sizing: border-box; display: inline-block; font-family: &quot;clear sans regular&quot;; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); cursor: pointer; text-decoration: none; margin: 0px; padding: 6px; outline: none; font-size: 0px; font-weight: inherit; position: absolute; overflow: visible; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; width: 36px; height: 36px; right: 45px; top: 0px; bottom: 0px; background: none;"><div><span class="icon-edit" color="#d8d8d8" style="color: rgb(216, 216, 216); position: relative; font-size: 15px; display: inline-block; user-select: none; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms;"></span></div></button></div><span class="icon-choose" color="#00b4d0" style="color: rgb(0, 180, 208); position: absolute; font-size: 36px; display: none; user-select: none; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; right: 0px; top: 0px; width: 24px; height: 36px; margin: 0px;"></span></div>

**Comment by curtisy1** [comment] 2018-07-11 06:49
@pradeep636 I'm not sure if that's just me but I'm seeing two issues in your code/HTML:
```
WebElement source = driver.findElement(by.xpath("(//div[@Class='viewlet-svg'])[1]"));
```
Are you actually changing the source there? Or is that just a typo and it's supposed to be the target?

2. There's no class with the name ```viewlet-svg``` in your posted HTML, so naturally the XPath wouldn't return any element in that case. Why not just use a ```By.CssSelector("[draggable='true']")```?

In any case, a test case would actually help the devs figure out what's wrong much faster. Since you already posted some HTML here, you could try extracting a small amount of the code you need to reproduce as well, even if it's a static GitHub page like I did under curtisy1.github.io/demo/indexof for example.

**Comment by barancev** [comment] 2018-07-11 07:50
@pradeep636 We don't need you actual site, just create a simplified sample page that can be used to replicate the issue.

**Comment by pradeep636** [comment] 2018-07-11 10:54
@curtisy1 
I guess Srinivas mentioned it wrong by mistake. The second one is target element.

source element xpath : //*[@title="Viewlet-1"]/..
target element xpath : (//div[@class='viewlet-svg'])[1]/../..

source element HTML: 

`<div draggable="true" class="1531305067" style="position: relative; width: 100%; height: 36px; line-height: 36px; vertical-align: middle;"><span class="icon-table" style="color: rgb(102, 102, 102); position: relative; font-size: 24px; display: inline-block; user-select: none; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; width: 24px; height: 24px; padding: 6px;"></span><p class="viewlet-title" title="Viewlet-1" style="height: 36px; line-height: 36px; vertical-align: middle; padding: 0px; margin: 0px; position: absolute; left: 36px; top: 0px; bottom: 0px; right: 72px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; font-size: 12px; font-family: &quot;clear sans regular&quot;; color: rgb(102, 102, 102);">Viewlet-1</p><div class="list-tools"><div style="display: block;"><button tabindex="0" type="button" style="border: 10px; box-sizing: border-box; display: inline-block; font-family: &quot;clear sans regular&quot;; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); cursor: pointer; text-decoration: none; margin: 0px; padding: 6px; outline: none; font-size: 0px; font-weight: inherit; position: absolute; overflow: visible; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; width: 36px; height: 36px; right: 9px; top: 0px; bottom: 0px; background: none;"><div><span class="icon-delete" color="#d8d8d8" style="color: rgb(216, 216, 216); position: relative; font-size: 15px; display: inline-block; user-select: none; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms;"></span></div></button></div><button value="1531305067" tabindex="0" type="button" style="border: 10px; box-sizing: border-box; display: inline-block; font-family: &quot;clear sans regular&quot;; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); cursor: pointer; text-decoration: none; margin: 0px; padding: 6px; outline: none; font-size: 0px; font-weight: inherit; position: absolute; overflow: visible; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; width: 36px; height: 36px; right: 45px; top: 0px; bottom: 0px; background: none;"><div><span class="icon-edit" color="#d8d8d8" style="color: rgb(216, 216, 216); position: relative; font-size: 15px; display: inline-block; user-select: none; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms;"></span></div></button></div><span class="icon-choose" color="#00b4d0" style="color: rgb(0, 180, 208); position: absolute; font-size: 36px; display: none; user-select: none; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; right: 0px; top: 0px; width: 24px; height: 36px; margin: 0px;"></span></div>`

target element HTML: 
This has draggable=false as this is target element and not a source element. But once source is dragged onto here, draggable is set true and this element also becomes draggable.

`<div value="row0,0,0" class="" draggable="false" style="position: absolute; top: 5px; bottom: 5px; left: 5px; right: 5px; background: rgb(244, 245, 246); border: 1px solid rgb(224, 227, 238);"><span class="icon-text" style="display: none; width: 24px; height: 24px; padding: 6px; font-size: 24px; color: rgb(0, 180, 208);"></span><div class="viewlet-title" style="padding: 0px 5px; height: 36px; line-height: 36px; margin: 0px; vertical-align: middle; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; font-family: &quot;clear sans regular&quot;; color: rgb(68, 68, 68);"></div><div style="position: absolute; left: 0px; right: 0px; top: 36px; bottom: 0px;"><div class="viewlet-svg" style="width: 98%; height: 98%; margin: 0px 1%; overflow: hidden; position: relative;"></div></div><div class="dnd-item-tool" style="position: absolute; bottom: 0px; left: 0px; right: 0px; display: block;"><div style="display: block;"><button value="row0,0,0" tabindex="0" type="button" style="border: 10px; box-sizing: border-box; display: inline-block; font-family: &quot;clear sans regular&quot;; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); cursor: pointer; text-decoration: none; margin: 0px; padding: 6px; outline: none; font-size: 0px; font-weight: inherit; position: relative; overflow: visible; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; width: 36px; height: 36px; background: none;"><div><span class="icon-add" color="#666" style="color: rgb(102, 102, 102); position: relative; font-size: 15px; display: inline-block; user-select: none; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms;"></span></div></button></div><div style="display: block;"><button tabindex="0" type="button" style="border: 10px; box-sizing: border-box; display: inline-block; font-family: &quot;clear sans regular&quot;; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); cursor: pointer; text-decoration: none; margin: 0px; padding: 6px; outline: none; font-size: 0px; font-weight: inherit; position: absolute; overflow: visible; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; width: 36px; height: 36px; left: 36px; bottom: 0px; background: none;"><div><span class="icon-text" color="#666" style="color: rgb(102, 102, 102); position: relative; font-size: 15px; display: inline-block; user-select: none; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms;"></span></div></button></div><button value="" tabindex="0" type="button" style="border: 10px; box-sizing: border-box; display: none; font-family: &quot;clear sans regular&quot;; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); cursor: pointer; text-decoration: none; margin: 0px; padding: 6px; outline: none; font-size: 0px; font-weight: inherit; position: relative; overflow: visible; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; width: 36px; height: 36px; background: none;"><div><span class="icon-edit" color="#666" style="color: rgb(102, 102, 102); position: relative; font-size: 15px; display: inline-block; user-select: none; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms;"></span></div></button><button value="row0,0,0" tabindex="0" type="button" style="border: 10px; box-sizing: border-box; display: inline-block; font-family: &quot;clear sans regular&quot;; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); cursor: pointer; text-decoration: none; margin: 0px; padding: 6px; outline: none; font-size: 0px; font-weight: inherit; position: absolute; overflow: visible; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; width: 36px; height: 36px; right: 0px; bottom: 0px; background: none;"><div><span class="icon-disconnect" color="#666" style="color: rgb(102, 102, 102); position: relative; font-size: 15px; display: inline-block; user-select: none; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms;"></span></div></button></div></div>`

**Comment by pradeep636** [comment] 2018-07-11 11:01
@barancev 
Actually it is ReactJS appplication and login is required for any page and i really doubt i can create a demo page and share. I have provided the html of source and target elements.

**Comment by barancev** [comment] 2018-07-11 11:07
HTML source of a React application is unusable, you can't "run" it. We need an actual sample page.

**Comment by barancev** [comment] 2018-08-09 09:50
Closing the issue as there is no reproduction scenario provided.
Can be a duplicate of #1365

**Closed by barancev** 2018-08-09 09:50 UTC
Labels: R-awaiting answer
