### ISSUE TITLE
[🐛 Bug]: I use grid4 to start ie11, driver Get (URL), prompt "parameters property of command is not a valid JSON object"

### ISSUE THREAD

**Issue by tianyao1111** [SeleniumHQ/selenium#10421] opened 2022-03-08 13:44 UTC
### What happened?

- hub(10.22.64.60):

`java -jar selenium-server-4.1.1.jar hub`

- node(11.204.111.8):

web1.tom:
```
[server]
port = 5556

[node]
detect-drivers = false
grid-url = "http://10.22.64.60:4444"
hub = "http://10.22.64.60:4444"

[[node.driver-configuration]]
display-name = "internet explorer"
max-sessions = 1
stereotype = "{\"browserName\": \"internet explorer\", \"browserVersion\": \"11\", \"platformName\": \"WINDOWS\"}"
webdriver-executable = '节点机driver地址'

[events]
publish = "tcp://10.22.64.60:4442"
subscribe = "tcp://10.22.64.60:4443"
```
`java -jar selenium-server-4.1.1.jar node --config  web1.toml`

- clent(10.22.64.60):

```
def get_web_driver(url,data=None,kill_all_ie=True):
	chrome_capabilities = {
				"browserName": "internet explorer",		# 浏览器名称
				"version": "11",				  # 操作系统版本
				"platform": "WINDOWS",			  # 平台，这里可以是windows、linux、andriod等等
				"javascriptEnabled": True,	  # 是否启用js
				#"webdriver.chrome.driver": chrome_driver
			}
	driver = webdriver1.Remote('http://localhost:4444/wd/hub', desired_capabilities=chrome_capabilities)
	driver.get(url)
	driver.maximize_window()
	driver.implicitly_wait(global_wait)
	#等待页面加载
	driver.find_element_by_xpath('//a[@id="overridelink"]')

	#点击详细信息
	driver.execute_script("javascript:expandCollapse('infoBlockID', true);")

	#转到此网页
	WebDriverWait(driver, global_wait).until(EC.visibility_of_element_located((By.XPATH, '//a[@id="overridelink"]')))
	ele=driver.find_element_by_xpath('//a[@id="overridelink"]')
	str1='return arguments[0].click();'
	driver.execute_script(str1, ele)
	return driver
```

- error:

```
ft1.1: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\public\MyTestCase.py", line 27, in testPartExecutor
    yield
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\public\MyTestCase.py", line 184, in run
    self.setUp()
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\test_case\YZB_CB_HKT_case_01.py", line 70, in setUp
    self.driver=get_web_driver(self.data['web_CB_url'])
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\public\get_driver.py", line 87, in get_web_driver
    driver.get(url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: parameters property of command is not a valid JSON object
```

### How can we reproduce the issue?

```shell
def get_web_driver(url,data=None,kill_all_ie=True):
	chrome_capabilities = {
				"browserName": "internet explorer",		# 浏览器名称
				"version": "11",				  # 操作系统版本
				"platform": "WINDOWS",			  # 平台，这里可以是windows、linux、andriod等等
				"javascriptEnabled": True,	  # 是否启用js
				#"webdriver.chrome.driver": chrome_driver
			}
	driver = webdriver1.Remote('http://localhost:4444/wd/hub', desired_capabilities=chrome_capabilities)
	driver.get(url)
	driver.maximize_window()
	driver.implicitly_wait(global_wait)
	#等待页面加载
	driver.find_element_by_xpath('//a[@id="overridelink"]')

	#点击详细信息
	driver.execute_script("javascript:expandCollapse('infoBlockID', true);")

	#转到此网页
	WebDriverWait(driver, global_wait).until(EC.visibility_of_element_located((By.XPATH, '//a[@id="overridelink"]')))
	ele=driver.find_element_by_xpath('//a[@id="overridelink"]')
	str1='return arguments[0].click();'
	driver.execute_script(str1, ele)
	return driver
```

### Relevant log output

```shell
ft1.1: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\public\MyTestCase.py", line 27, in testPartExecutor
    yield
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\public\MyTestCase.py", line 184, in run
    self.setUp()
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\test_case\YZB_CB_HKT_case_01.py", line 70, in setUp
    self.driver=get_web_driver(self.data['web_CB_url'])
  File "C:\Users\Administrator\Desktop\UITestAND_PICC_YZB\public\get_driver.py", line 87, in get_web_driver
    driver.get(url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: parameters property of command is not a valid JSON object
```

### Operating System

HUB:windows server 2008 R2;NODE:win7;clent:windows server 2008 R2

### Selenium version

python3.8.5 selenium3.14.1

### What are the browser(s) and version(s) where you see this issue?

IE11

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer_win32_3.141.0

### Are you using Selenium Grid?

selenium-server-4.1.1.jar

**Comment by titusfortner** [comment] 2022-03-08 16:17
Duplicate of #8530 
Update your IE Driver

**Closed as completed by titusfortner** 2022-03-08 16:17 UTC
Labels: I-defect, A-needs-triaging

**Comment by tianyao1111** [comment] 2022-03-09 01:22
> Duplicate of #8530 Update your IE Driver

Thank you so much, you solved my 2 weeks of problems!
