### ISSUE TITLE
Selenium IDE - sendKeys fails on <input type="email">

### ISSUE THREAD

**Issue by machtyn** [SeleniumHQ/selenium#4109] opened 2017-05-30 21:05 UTC
OS:  OSX
Selenium Version:  Selenium IDE 2.9.1
Browser:  Firefox
Browser Version:  53.0.3 (64-bit)

## Expected Behavior -
sendKeys should send keypresses to an input of type email.

## Actual Behavior -
sendKeys fails to send the keypresses to an input of type email. (It works fine with type="tel" or "password". And type works.)

## Steps to reproduce -
1. Open https://jsfiddle.net and put `<input id="query" type="email">` in the html block and run it.
2. In Selenium IDE enter
```
<tr>
	<td>sendKeys</td>
	<td>id=query</td>
	<td>a@b.c</td>
</tr>
<tr>
	<td>type</td>
	<td>id=query</td>
	<td>z@y.x</td>
</tr>
```
And run the two lines individually.

Note that `sendKeys` fails, but `type` works fine.

**Comment by thechairman007** [comment] 2017-06-29 23:04
Is there a workaround for this?

**Comment by cryanjohnson** [comment] 2017-07-27 18:39
I ran into this issue recently as well. The work around was simple - use the Type method to send the value to the field you'd like to populate, then perform a FireEvent on the field's input event.

`
<tr>
	<td>type</td>
	<td>id=myEmailInputField</td>
	<td>some.one@gmail.com</td>
</tr>
<tr>
	<td>fireEvent</td>
	<td>id=myEmailInputField</td>
	<td>input</td>
</tr>
`

**Comment by barancev** [comment] 2017-08-04 06:33
Duplicate of #4361 that provides more details.

**Closed by barancev** 2017-08-04 06:33 UTC
Labels: C-ide
