### ISSUE TITLE
Unable to launch webbrowser, using selenium webdriver

### ISSUE THREAD

**Issue by shans0535** [SeleniumHQ/selenium#9136] opened 2021-02-03 09:24 UTC
Unable to launch Edge browser, using selenium webdriver

from selenium import webdriver
>>> d=webdriver.Edge()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\test\flasky\venv\lib\site-packages\selenium\webdriver\edge\webdriver.py", line 61, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\test\flasky\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\test\flasky\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\test\flasky\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\test\flasky\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 208, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: Unknown error

## To Reproduce

Detailed steps to reproduce the behavior:
The script suppose to open Edge browser, but unfortunately it exited with an error

from selenium import webdriver
driver=webdriver.Edge(executable_apth='msedgedriver.exe')

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: windows 10
Browser: Edge
Browser version: 87.0.664.75
Browser Driver version: 87.0.664.0/
Language Bindings version: python 3.8
Selenium Grid version (if applicable):

**Comment by diemol** [comment] 2021-02-03 09:42
Could you please fill out all the template details? We have no information to reproduce the issue and give you feedback.

**Comment by shans0535** [comment] 2021-02-03 12:34
OS: windows 10
Browser: Edge
Browser version: 87.0.664.75
Browser Driver version: 87.0.664.0/
Language Bindings version: python 3.8
Selenium Grid version (if applicable):

**Comment by diemol** [comment] 2021-02-03 12:39
What code can we use to reproduce the issue? 

These sections of the template were left empty:

> ## To Reproduce
> 
> 
> 
> Detailed steps to reproduce the behavior:
> 
> ## Test script or set of commands reproducing this issue
> 
> Please provide a test script to reproduce the issue you are reporting, if the 
> setup is more complex, GitHub repo links with are also OK.
> 
> Issues without a reproduction script are likely to stall and eventually be closed.

**Comment by shans0535** [comment] 2021-02-03 12:43
I tried below codes, but the script launched the Edge browser, but exited with an error

from selenium import webdriver
driver=webdriver.Edge()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\test\test32\lib\site-packages\selenium\webdriver\edge\webdriver.py", line 61, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\test\test32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\test\test32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\test\test32\\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\test\test32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 208, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: Unknown error

**Comment by shans0535** [comment] 2021-02-03 12:48
Later I downloaded msedgedriver.exe and added to the path
from selenium import webdriver
driver=webdriver.Edge(executable_path='msedgedriver.exe')

the Edge browser is launched in remote debugging mode, because of this remote debugging mode I'm unable to navigate websites which supports only IE

**Comment by diemol** [comment] 2021-02-03 15:21
It is not clear what the issue is, seems you are actually able to launch the browser, right?

**Comment by shans0535** [comment] 2021-02-03 16:26
with MicrosoftWebDriver.exe, I was not able to open Edge browser, then I downloaded 'msedgedriver.exe' and added to the path, was able to launch the browser, but the browser opens in remote debugging mode, because of which url's which work Internet browser does not work in Edge browser. Is there a way to avoid remote debugging mode ?

**Comment by diemol** [comment] 2021-02-03 16:40
OK, so this seems that this issue is a question and a bug in Selenium.

MicrosoftWebDriver is for the "old" EdgeHTLM, and msedgedriver is for the new Chromium Edge. I think there is a way to enable the new Edge to load pages as if it was IE11, but I am not sure how to do it. 

Please join our Slack/IRC community channels where others are present and we can help you further. Check the links here: https://www.selenium.dev/support/

Closing this issue as it is not a bug in Selenium.

**Closed as completed by diemol** 2021-02-03 16:40 UTC
Labels: J-awaiting answer

**Comment by shans0535** [comment] 2021-02-03 17:25
Thank you
