### ISSUE TITLE
[🐛 Bug]: Current version of chrome is not supporting by Selenium Manager

### ISSUE THREAD

**Issue by jeetjddas** [SeleniumHQ/selenium#11302] opened 2022-11-23 18:18 UTC
### What happened?

I was trying to simply open chrome browser and open a website. But i am getting an error on my console.
OS: Windows
Editor: Pycharm
Language: Python

**Note**: Firefox browser is working fine with the new feature of Selenium Manager

### How can we reproduce the issue?

```shell
from selenium import webdriver

driver = webdriver.Chrome()
driver.get("https://www.google.com/")
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\jeet\PycharmProjects\NufDemo\tests\Sel_New_Fea.py", line 3, in <module>
    driver = webdriver.Chrome()
  File "C:\Users\jeet\PycharmProjects\NufDemo\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    super().__init__(
  File "C:\Users\jeet\PycharmProjects\NufDemo\venv\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 106, in __init__
    super().__init__(
  File "C:\Users\jeet\PycharmProjects\NufDemo\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\jeet\PycharmProjects\NufDemo\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\jeet\PycharmProjects\NufDemo\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\jeet\PycharmProjects\NufDemo\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 96
Current browser version is 107.0.5304.107 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
	Ordinal0 [0x00946903+2517251]
	Ordinal0 [0x008DF8E1+2095329]
	Ordinal0 [0x007E2848+1058888]
	Ordinal0 [0x00800B9D+1182621]
	Ordinal0 [0x007FCA60+1165920]
	Ordinal0 [0x007FA2CF+1155791]
	Ordinal0 [0x0082AAAF+1354415]
	Ordinal0 [0x0082A71A+1353498]
	Ordinal0 [0x0082639B+1336219]
	Ordinal0 [0x008027A7+1189799]
	Ordinal0 [0x00803609+1193481]
	GetHandleVerifier [0x00AD5904+1577972]
	GetHandleVerifier [0x00B80B97+2279047]
	GetHandleVerifier [0x009D6D09+534521]
	GetHandleVerifier [0x009D5DB9+530601]
	Ordinal0 [0x008E4FF9+2117625]
	Ordinal0 [0x008E98A8+2136232]
	Ordinal0 [0x008E99E2+2136546]
	Ordinal0 [0x008F3541+2176321]
	BaseThreadInitThunk [0x763AFEF9+25]
	RtlGetAppContainerNamedObjectPath [0x77C37BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77C37B8E+238]
```

### Operating System

Windows 10

### Selenium version

Selenium 4.6.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 107.0.5304.107

### What are the browser driver(s) and version(s) where you see this issue?

No driver has been used

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment] 2022-11-23 19:46
It's very likely that you have an old version of chromedriver in some random directory that is on PATH. Please check and let us know.

**Comment by jeetjddas** [comment] 2022-11-24 11:18
I have checked for the same for the above solution, but I do not have anything on PATH related to chromedriver. 
Actually, it's opening the browser and closing instantly. After that I am getting the above-mentioned error in bug report.

**Comment by titusfortner** [comment] 2022-11-25 18:06
You only get that error from chromedriver v96. Somewhere on your system there is a chromedriver v96 binary that is getting located. Try calling `gcm chromedriver.exe` to find it.

**Comment by titusfortner** [comment] 2022-11-26 01:35
fyi @bonigarcia I think this is a good use case for the manager to also process `PATH`.

We could provide a better error message:

> The version of the driver located at /path/to/old/driver is XX, which is not compatible with the version of the browser located at /path/to/chrome, which is YY. Please delete this driver or specify the location of a compatible browser in the code: see examples here...

**Comment by Umutayb** [comment] 2022-11-28 10:31
It makes sense to point out that this issue is highly reproducible, and @bonigarcia's WDM does not have this issue.

**Comment by titusfortner** [comment] 2022-11-28 13:55
Keep in mind that the two products are intentionally using different prioritizations.
WDM is a user-opt-in feature that takes priority in managing drivers.
Selenium Manager is an always-on feature that is only used if code would have otherwise failed.

I'm still not getting a reproducible idea of what is going on.

What do you get from:
```
gcm chromedriver.exe
```
or
```
chromedriver.exe --version
```
What is the `dir` results from:
```
%HOMEPATH%\.cache\selenium\windows\chromedriver
```

**Comment by Umutayb** [comment] 2022-11-28 17:19
My attempt was to give some insight on the issue. 
I have an open source library using selenium 4.6, about 40 percent of people who used the new version that is packing selenium 4.6 faced this issue where selenium detects and older version of chrome driver vs the one that is being used. 

I too suspect that this is caused by some leftover chrome drivers in the system/PATH. Considering most of the adopters will have some version of chrome driver installed somewhere, it makes sense to debug this.

**Comment by titusfortner** [comment] 2022-11-28 18:07
Thanks for clarifying.

Yeah, there are several options for how we could move forward with this.

1. Have users opt-in to using Selenium Manager in the code somehow (similar to WDM)
2. Have Selenium Manager first locate/use drivers on PATH (better errors and auto-fixes)
3. Have Selenium Manager ignore what's on PATH and just download what it needs

My preference right now is for 2, but we're not ready for that, yet, either.

**Comment by Umutayb** [comment] 2022-11-28 18:14
Looking forward to see how you fix it!

**Comment by bonigarcia** [comment] 2022-11-30 15:52
It is easy to implement that Selenium Manager processes the PATH, so we can do it. As I see it, Selenium Manager can discover if a driver is in the path and if the version is suitable to drive the browser. If the driver is not compatible (typically, since it is an old version), IMO, Selenium Manager should fix the problem (i.e., resolve the proper driver and ignore the driver in the PATH).

Then, we can also log a `WARN` in Selenium Manager about it (something similar to mention, e.g., "you have an old version of <chromedriver> ... etc."). In that case, that `WARN` trace should also be parsed in the bindings and logged to the final user again.

**Comment by Umutayb** [comment] 2022-11-30 16:01
Sounds pretty straight forward!

**Comment by titusfortner** [comment] 2022-11-30 18:28
@bonigarcia I like that solution! Some of the bindings will have an easier time outputting the logging of that than others, so we need to figure out how to make that look good.

**Comment by bonigarcia** [comment] 2022-12-06 09:53
I have created a feature request for this (#11373). Maybe it can be part of Selenium Manager M3.

**Comment by titusfortner** [comment] 2022-12-06 16:51
Ok, let's close this issue, then. We didn't get more info about this specific case to be able to do more with it.

**Closed as completed by titusfortner** 2022-12-06 16:51 UTC
Labels: J-awaiting answer, I-defect

**Comment by Umutayb** [comment] 2022-12-07 07:28
I have seen this issue with almost every M1 MacBook we have used so far, fyi

**Comment by titusfortner** [comment] 2022-12-07 12:42
Yes, selenium manager does not support arm64 at all, yet. See #11357

**Comment by mraphael2101** [comment] 2022-12-19 15:50
Hi everyone, @titusfortner @bonigarcia 

I am getting the same problem on my work computer. In my case, I am working on a Mac with an Intel chip.
I have followed the below tutorial to remove any other versions of chrome that may have been installed which might confuse Selenium Manager. However, it appears that there was only one instance running and nothing else to uninstall.
https://rk.md/2017/delete-old-versions-chrome-macos

The odd thing is that it is working on my personal mac book which also has the same intel chip. 
Both machines have the identical version of chrome installed (108.0.5359.124) and are using a common Maven project template.

I have checked several directories to see if chrome is hidden somewhere else but cannot find anything. That leaves me at a dead end. Any ideas, please?

P.S. I have checked $PATH and it was not there.

**Comment by mraphael2101** [comment] 2022-12-19 16:42
Not to worry I have fixed it. 
The conflicting version was in /local/bin
