### ISSUE TITLE
[🐛 Bug]: '--window-size' option does not work when used in combination with '--headless=new' option

### ISSUE THREAD

**Issue by msanchezBek** [SeleniumHQ/selenium#11803] opened 2023-03-22 22:32 UTC
### What happened?

After I updated to use chromedriver 111 I tried to switch the '--headless' option on my webdriver instance to use '--headless=new' argument. I also use the '--window-size=1920x1080' option. This fixes the issue I was having where 'download.default_directory' wasn't working but now the window maximization option is not working and elements which were being accessed by their position are not being accessed.

### How can we reproduce the issue?

```shell
chrome_options = Options()
chrome_options.add_argument("--headless=new")
chrome_options.add_argument("--window-size=1920x1080")
chrome_options.add_experimental_option('prefs', prefs)
driver = webdriver.Chrome(options=chrome_options)

# element selected which was previously working without issue
self.driver.find_element(By.ID, "loginButton").click()
```

### Relevant log output

```shell
Message: element click intercepted: Element <a href="#" id="loginButton" class="loginButton" onclick="javascript:executeOKCommand();">...</a> is not clickable at point (531, 441). Other element would receive the click: <p>...</p>
```

### Operating System

Amazon Linux 2

### Selenium version

4.8.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 111.0.5563.64

**Comment by diemol** [comment] 2023-03-22 22:58
Duplicate of #11706

**Closed as completed by diemol** 2023-03-22 22:58 UTC
