### ISSUE TITLE
Firefox stopped working error message after firefox update to 47.0

### ISSUE THREAD

**Issue by rakslalsangi** [SeleniumHQ/selenium#2307] opened 2016-06-17 09:11 UTC
When I update Firefox to 47.0 , it giving error message Firefox stopped working error message after Selenium script run  .

When I downgrade firefox version , then its working fine .

OS : Windows 10
Firefox version : 47.0 
Selenium version : 2.53.0

**Comment by StoyanIvanovI** [comment] 2016-06-17 13:00
I can confirm Selenium webdriver 2.53.0 and 2.53.3 do not work with Firefox 47 on Ubuntu 14.04 or 16.04 as well.

**Comment by jimevans** [comment] 2016-06-17 13:15
Duplicate of #2110

**Closed by jimevans** 2016-06-17 13:15 UTC
