### ISSUE TITLE
problems with $ in a string 

### ISSUE THREAD

**Issue by nma123** [SeleniumHQ/selenium#1389] opened 2015-12-17 02:15 UTC
Runing firefox 42.0 and Next Generation Java Plug-in 10.80.2 for Mozilla browsers Webdriver version 2.47.1

When I send the driver a string with an embedded $ character it cause the webdriver to exit to the parent string.

I can see from the wireshark trace below the $ charcaters is being sent to the local loopback for the wed driver.

On the screen I just see”sparky1” and then it exits.

I have tried all of the normal escape sequences and nothing seems to work. How can I send the string "sparky$1' as just ascii text?

 

Wireshark trace 

bytes: b'POST /hub/session/dd854199-8912-4eb1-b4c6-6060ab2a7fc8/element/{c58d697c-1c4f-43ba-97cd-3a561f059c3a}/value HTTP/1.1\r\nHost: 127.0.0.1:59649\r\nAccept-Encoding: identity\r\nContent-Length: 152\r\nAccept: 
 application/json\r\nContent-type: application/json;charset="UTF-8"\r\nUser-Agent: Python http auth\r\nPOST: 
 /hub/session/dd854199-8912-4eb1-b4c6-6060ab2a7fc8/element/{c58d697c-1c4f-43ba-97cd-3a561f059c3a}
/value\r\nConnection: keep-alive\r\n\r\n{"sessionId": "dd854199-8912-4eb1-b4c6-6060ab2a7fc8", "value": ["s", "p", "a",  "r", "k", "y", "$", "1"], "id": "{c58d697c-1c4f-43ba-97cd-3a561f059c3a}"}'

str.join Found at: http.client
msg = b"\r\n".join(self._buffer)

Webdriver code 

    def _send_output(self, message_body=None):
        """Send the currently buffered request and clear the buffer.
        Appends an extra \\r\\n to the buffer.
        A message_body may be specified, to be appended to the request.
        """
        self._buffer.extend((b"", b""))
        msg = b"\r\n".join(self._buffer)
        del self._buffer[:]
        # If msg and message_body are sent in a single send() call,
        # it will avoid performance problems caused by the interaction
        # between delayed ack and the Nagle algorithm. However,
        # there is no performance gain if the message is larger
        # than MSS (and there is a memory penalty for the message
        # copy).
        if isinstance(message_body, bytes) and len(message_body) < self.mss:
            msg += message_body
            message_body = None
        self.send(msg)
        if message_body is not None:
            # message_body was not a string (i.e. it is a file), and
            # we must run the risk of Nagle.
            self.send(message_body)
 
    def putrequest(self, method, url, skip_host=0, skip_accept_encoding=0):
        """Send a request to the server.
        `method' specifies an HTTP request method, e.g. 'GET'.
        `url' specifies the object being requested, e.g. '/index.html'.
        `skip_host' if True does not add automatically a 'Host:' header
        `skip_accept_encoding' if True does not add automatically an
           'Accept-Encoding:' header
        """
        # if a prior response has been completed, then forget about it.
        if self.__response and self.__response.isclosed():
            self.__response = None

**Comment by barancev** [comment] 2016-02-01 17:12
This information is not enough to reproduce the issue.

I can't reproduce it on a simple text input and Selenium 2.50:
![01-02-2016 20-09-17](https://cloud.githubusercontent.com/assets/617090/12724679/1327aefa-c920-11e5-9701-47a983b52d2a.png)

**Comment by nma123** [comment] 2016-02-01 18:22
I was able to work around it by sending the keys above the numbers separately
send_keys.(‘sparky’)
send.keys(‘$’)
send_keys(‘1’)

Also tried chord but it does not appear to supported in python version.
Peter Farley
Element Communicator/ OCS
Senior Quality, Performance and System Engineer
Ericsson
New Number  913-241-6200
Peter.Farley@ericsson.com<mailto:Peter.Farley@ericsson.com>
www.ericsson.com<http://www.ericsson.com/>
[Description: http://insite.telcordia.com/corporate/pr/brand/downloads/templates/EricssonLogo.gif]

**Comment by ddavison** [comment] 2016-02-01 18:30
Still is an interesting issue.  You shouldn't have to work around it like that.

**Comment by lukeis** [comment] 2016-02-01 20:05
@nma123 can you please provide a way for us to reproduce the issue, with either a public link or sample html + javascript + css that causes your issue.

**Comment by nma123** [comment] 2016-02-01 20:11
I will see what I can do. It is propriety application.

Peter Farley
Element Communicator/ OCS
Senior Quality, Performance and System Engineer
Ericsson
New Number  913-241-6200
Peter.Farley@ericsson.com<mailto:Peter.Farley@ericsson.com>
www.ericsson.com<http://www.ericsson.com/>
[Description: http://insite.telcordia.com/corporate/pr/brand/downloads/templates/EricssonLogo.gif]

**Comment by barancev** [comment] 2016-03-02 06:09
Closing the issue as there is no reproduction case provided.

**Closed by barancev** 2016-03-02 06:09 UTC
Labels: C-py, R-awaiting answer
