### ISSUE TITLE
The Selenium Python release 3.5.0 has in __init__.py __version__ = "3.4.3"

### ISSUE THREAD

**Issue by aaltat** [SeleniumHQ/selenium#4632] opened 2017-09-04 19:41 UTC
When I do: `pip freeze` then I see `selenium==3.5.0`. But when I look at the `__init__.py` file, I see `__version__ = "3.4.3"`. This seems to be true also in the repository: https://github.com/SeleniumHQ/selenium/blob/selenium-3.5.0/py/selenium/__init__.py Could you be next time more careful with the versions, thank you.

**Comment by davehunt** [comment] 2017-09-04 20:32
Duplicate of #4502

**Closed by davehunt** 2017-09-04 20:32 UTC
