### ISSUE TITLE
In remote driver InvalidArgumentException: Message: missing field `handle` at line 3 column 1 in switch driver.switch_to.window and _driver.switch_to._w3c_window

### ISSUE THREAD

**Issue by abhayp505** [SeleniumHQ/selenium#8649] opened 2020-08-27 05:08 UTC
## 🐛 Bug Report
OS: macOS 10.13
Browser: firefox
Browser version: Version 80.0 (64-bit)
Browser Driver version:
Language Bindings version: python
Selenium version (if applicable): version = '3.141.0'

Summary:

Message: missing field handle at line 3 column 1 in driver.switch_to.window while switching tab.
InvalidArgumentException: Message: Expected "handle" to be a string, got [object Undefined] undefined
Note:
With Firefox version 79 it is working fine and the issue is with remote driver, in local it is working fine

**Comment by abhayp505** [comment] 2020-08-27 05:16
OS: macOS 10.13
Browser: firefox 
Browser version: Version 80.0 (64-bit)
Browser Driver version: 
Language Bindings version: python
Selenium version (if applicable): __version__ = '3.141.0'


Summary:
1. Message: missing field `handle` at line 3 column 1 in driver.switch_to.window while switching tab.
2. InvalidArgumentException: Message: Expected "handle" to be a string, got [object Undefined] undefined

Note:
With Firefox version 79 it is working fine and the issue is with remote driver, in local it is working fine

Stack trace: with driver.switch_to.window()

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py:782: in switch_to_window
    self._switch_to.window(window_name)
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/switch_to.py:117: in window
    self._driver.execute(Command.SWITCH_TO_WINDOW, data)
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py:321: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fd7e6efbcd0>
response = {'status': 500, 'value': '{"status": 61, "state": "invalid argument", "sessionId": null, "value": {"stackTrace": [null...6\', java.version: \'9.0.4\'", "suppressed": [], "supportUrl": null}, "class": "org.openqa.selenium.remote.Response"}'}

    def check_response(self, response):
        """
        Checks that a JSON response from the WebDriver does not have an error.
    
        :Args:
         - response - The JSON response from the WebDriver server as a dictionary
           object.
    
        :Raises: If the response contains an error message.
        """
        status = response.get('status', None)
        if status is None or status == ErrorCode.SUCCESS:
            return
        value = None
        message = response.get("message", "")
        screen = response.get("screen", "")
        stacktrace = None
        if isinstance(status, int):
            value_json = response.get('value', None)
            if value_json and isinstance(value_json, basestring):
                import json
                try:
                    value = json.loads(value_json)
                    if len(value.keys()) == 1:
                        value = value['value']
                    status = value.get('error', None)
                    if status is None:
                        status = value["status"]
                        message = value["value"]
                        if not isinstance(message, basestring):
                            value = message
                            message = message.get('message')
                    else:
                        message = value.get('message', None)
                except ValueError:
                    pass
    
        exception_class = ErrorInResponseException
        if status in ErrorCode.NO_SUCH_ELEMENT:
            exception_class = NoSuchElementException
        elif status in ErrorCode.NO_SUCH_FRAME:
            exception_class = NoSuchFrameException
        elif status in ErrorCode.NO_SUCH_WINDOW:
            exception_class = NoSuchWindowException
        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:
            exception_class = StaleElementReferenceException
        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:
            exception_class = ElementNotVisibleException
        elif status in ErrorCode.INVALID_ELEMENT_STATE:
            exception_class = InvalidElementStateException
        elif status in ErrorCode.INVALID_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:
            exception_class = InvalidSelectorException
        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:
            exception_class = ElementNotSelectableException
        elif status in ErrorCode.ELEMENT_NOT_INTERACTABLE:
            exception_class = ElementNotInteractableException
        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:
            exception_class = InvalidCookieDomainException
        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:
            exception_class = UnableToSetCookieException
        elif status in ErrorCode.TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.SCRIPT_TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.UNKNOWN_ERROR:
            exception_class = WebDriverException
        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:
            exception_class = UnexpectedAlertPresentException
        elif status in ErrorCode.NO_ALERT_OPEN:
            exception_class = NoAlertPresentException
        elif status in ErrorCode.IME_NOT_AVAILABLE:
            exception_class = ImeNotAvailableException
        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:
            exception_class = ImeActivationFailedException
        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:
            exception_class = MoveTargetOutOfBoundsException
        elif status in ErrorCode.JAVASCRIPT_ERROR:
            exception_class = JavascriptException
        elif status in ErrorCode.SESSION_NOT_CREATED:
            exception_class = SessionNotCreatedException
        elif status in ErrorCode.INVALID_ARGUMENT:
            exception_class = InvalidArgumentException
        elif status in ErrorCode.NO_SUCH_COOKIE:
            exception_class = NoSuchCookieException
        elif status in ErrorCode.UNABLE_TO_CAPTURE_SCREEN:
            exception_class = ScreenshotException
        elif status in ErrorCode.ELEMENT_CLICK_INTERCEPTED:
            exception_class = ElementClickInterceptedException
        elif status in ErrorCode.INSECURE_CERTIFICATE:
            exception_class = InsecureCertificateException
        elif status in ErrorCode.INVALID_COORDINATES:
            exception_class = InvalidCoordinatesException
        elif status in ErrorCode.INVALID_SESSION_ID:
            exception_class = InvalidSessionIdException
        elif status in ErrorCode.UNKNOWN_METHOD:
            exception_class = UnknownMethodException
        else:
            exception_class = WebDriverException
        if value == '' or value is None:
            value = response['value']
        if isinstance(value, basestring):
            if exception_class == ErrorInResponseException:
                raise exception_class(response, value)
            raise exception_class(value)
        if message == "" and 'message' in value:
            message = value['message']
    
        screen = None
        if 'screen' in value:
            screen = value['screen']
    
        stacktrace = None
        if 'stackTrace' in value and value['stackTrace']:
            stacktrace = []
            try:
                for frame in value['stackTrace']:
                    line = self._value_or_default(frame, 'lineNumber', '')
                    file = self._value_or_default(frame, 'fileName', '<anonymous>')
                    if line:
                        file = "%s:%s" % (file, line)
                    meth = self._value_or_default(frame, 'methodName', '<anonymous>')
                    if 'className' in frame:
                        meth = "%s.%s" % (frame['className'], meth)
                    msg = "    at %s (%s)"
                    msg = msg % (meth, file)
                    stacktrace.append(msg)
            except TypeError:
                pass
        if exception_class == ErrorInResponseException:
            raise exception_class(response, message)
        elif exception_class == UnexpectedAlertPresentException:
            alert_text = None
            if 'data' in value:
                alert_text = value['data'].get('text')
            elif 'alert' in value:
                alert_text = value['alert'].get('text')
            raise exception_class(message, screen, stacktrace, alert_text)
>       raise exception_class(message, screen, stacktrace)
E       InvalidArgumentException: Message: missing field `handle` at line 3 column 1
E       Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
E       System info: host: 'itako5442.prod.miso', ip: 'fe80:0:0:0:1086:ea65:fdc1:7032%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '9.0.4'
E       Driver info: driver.version: unknown
E       Stacktrace:

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py:242: InvalidArgumentException


Stack trace:  with _driver.switch_to._w3c_window()
    self._driver.execute(Command.SWITCH_TO_WINDOW, data)
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py:321: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f83f66fb850>
response = {'status': 500, 'value': '{"status": 61, "state": "invalid argument", "sessionId": null, "value": {"stackTrace": [null...6\', java.version: \'9.0.4\'", "suppressed": [], "supportUrl": null}, "class": "org.openqa.selenium.remote.Response"}'}

    def check_response(self, response):
        """
        Checks that a JSON response from the WebDriver does not have an error.
    
        :Args:
         - response - The JSON response from the WebDriver server as a dictionary
           object.
    
        :Raises: If the response contains an error message.
        """
        status = response.get('status', None)
        if status is None or status == ErrorCode.SUCCESS:
            return
        value = None
        message = response.get("message", "")
        screen = response.get("screen", "")
        stacktrace = None
        if isinstance(status, int):
            value_json = response.get('value', None)
            if value_json and isinstance(value_json, basestring):
                import json
                try:
                    value = json.loads(value_json)
                    if len(value.keys()) == 1:
                        value = value['value']
                    status = value.get('error', None)
                    if status is None:
                        status = value["status"]
                        message = value["value"]
                        if not isinstance(message, basestring):
                            value = message
                            message = message.get('message')
                    else:
                        message = value.get('message', None)
                except ValueError:
                    pass
    
        exception_class = ErrorInResponseException
        if status in ErrorCode.NO_SUCH_ELEMENT:
            exception_class = NoSuchElementException
        elif status in ErrorCode.NO_SUCH_FRAME:
            exception_class = NoSuchFrameException
        elif status in ErrorCode.NO_SUCH_WINDOW:
            exception_class = NoSuchWindowException
        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:
            exception_class = StaleElementReferenceException
        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:
            exception_class = ElementNotVisibleException
        elif status in ErrorCode.INVALID_ELEMENT_STATE:
            exception_class = InvalidElementStateException
        elif status in ErrorCode.INVALID_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:
            exception_class = InvalidSelectorException
        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:
            exception_class = ElementNotSelectableException
        elif status in ErrorCode.ELEMENT_NOT_INTERACTABLE:
            exception_class = ElementNotInteractableException
        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:
            exception_class = InvalidCookieDomainException
        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:
            exception_class = UnableToSetCookieException
        elif status in ErrorCode.TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.SCRIPT_TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.UNKNOWN_ERROR:
            exception_class = WebDriverException
        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:
            exception_class = UnexpectedAlertPresentException
        elif status in ErrorCode.NO_ALERT_OPEN:
            exception_class = NoAlertPresentException
        elif status in ErrorCode.IME_NOT_AVAILABLE:
            exception_class = ImeNotAvailableException
        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:
            exception_class = ImeActivationFailedException
        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:
            exception_class = MoveTargetOutOfBoundsException
        elif status in ErrorCode.JAVASCRIPT_ERROR:
            exception_class = JavascriptException
        elif status in ErrorCode.SESSION_NOT_CREATED:
            exception_class = SessionNotCreatedException
        elif status in ErrorCode.INVALID_ARGUMENT:
            exception_class = InvalidArgumentException
        elif status in ErrorCode.NO_SUCH_COOKIE:
            exception_class = NoSuchCookieException
        elif status in ErrorCode.UNABLE_TO_CAPTURE_SCREEN:
            exception_class = ScreenshotException
        elif status in ErrorCode.ELEMENT_CLICK_INTERCEPTED:
            exception_class = ElementClickInterceptedException
        elif status in ErrorCode.INSECURE_CERTIFICATE:
            exception_class = InsecureCertificateException
        elif status in ErrorCode.INVALID_COORDINATES:
            exception_class = InvalidCoordinatesException
        elif status in ErrorCode.INVALID_SESSION_ID:
            exception_class = InvalidSessionIdException
        elif status in ErrorCode.UNKNOWN_METHOD:
            exception_class = UnknownMethodException
        else:
            exception_class = WebDriverException
        if value == '' or value is None:
            value = response['value']
        if isinstance(value, basestring):
            if exception_class == ErrorInResponseException:
                raise exception_class(response, value)
            raise exception_class(value)
        if message == "" and 'message' in value:
            message = value['message']
    
        screen = None
        if 'screen' in value:
            screen = value['screen']
    
        stacktrace = None
        if 'stackTrace' in value and value['stackTrace']:
            stacktrace = []
            try:
                for frame in value['stackTrace']:
                    line = self._value_or_default(frame, 'lineNumber', '')
                    file = self._value_or_default(frame, 'fileName', '<anonymous>')
                    if line:
                        file = "%s:%s" % (file, line)
                    meth = self._value_or_default(frame, 'methodName', '<anonymous>')
                    if 'className' in frame:
                        meth = "%s.%s" % (frame['className'], meth)
                    msg = "    at %s (%s)"
                    msg = msg % (meth, file)
                    stacktrace.append(msg)
            except TypeError:
                pass
        if exception_class == ErrorInResponseException:
            raise exception_class(response, message)
        elif exception_class == UnexpectedAlertPresentException:
            alert_text = None
            if 'data' in value:
                alert_text = value['data'].get('text')
            elif 'alert' in value:
                alert_text = value['alert'].get('text')
            raise exception_class(message, screen, stacktrace, alert_text)
>       raise exception_class(message, screen, stacktrace)
E       InvalidArgumentException: Message: Expected "handle" to be a string, got [object Undefined] undefined
E       Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
E       System info: host: 'itako3740.prod.miso', ip: 'fe80:0:0:0:1058:84d3:7e6:ab3e%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '9.0.4'
E       Driver info: driver.version: unknown
E       Stacktrace:

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py:242: InvalidArgumentException

**Comment by OndraM** [comment] 2020-08-27 16:09
This may be Geckodriver issue, we got similar report for [php-webdriver](https://github.com/php-webdriver/php-webdriver/issues/817#issuecomment-682026354). According to comment there it seems to be an issue in Java bindings as well.

**Comment by diemol** [comment] 2020-09-04 22:23
This sounds like it could be a GeckoDriver issue (based on the comments and a quick look to the error), what do you think @whimboo @AutomatedTester?

**Comment by AutomatedTester** [comment] 2020-09-07 10:13
This might be a geckodriver issue but it might also be a selenium issue.

Unfortunately, we have had a lot of comments on this issue but not minimised test case to help fix.

**Comment by diemol** [comment] 2020-09-07 22:32
Good point. @abhayp505 please provide a self contained script that allow us to reproduce it and potentially fix it.

**Comment by whimboo** [comment] 2020-09-08 09:24
The appropriate issue for geckodriver was https://github.com/mozilla/geckodriver/issues/1424. But note that it is invalid because everyone so far used a [non-supported version of geckodriver](https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html) together with Firefox 80. So I'm fairly sure that this is the same underlying reason here and makes this issue invalid.

To verify that people would have to attach a [trace level log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) for geckodriver - most of the times the claim like `I'm using the 0.27.0 release of geckodriver` are simply wrong.

**Comment by abhayp505** [comment] 2020-09-21 05:56
Hello @diemol 
here is a script to reproduce the issue.
I repeat the issue is not seen while running script locally on firefox80, it is seen on remote driver execution.

```

browser.go_to_url('https://www.google.co.in/')
    time.sleep(2)
    browser.open_new_tab()
    browser.switch_back_to_parent_tab(1200)



def open_new_tab(self):
        def tab_opened(driver):
            driver.execute_script('window.open()')
            return driver.title == ''
        WebDriverWait(self._driver, 10, 1).until(tab_opened)

def switch_back_to_parent_tab(self,wait_time):
        sleep(wait_time/1000)
        current_handle = self._driver.current_window_handle
        self.switch_to_tab_or_window_with_handle(current_handle)



        def switch_to_tab_or_window_with_handle(self, current_handle):
        if (self._driver.name.lower() == 'chrome' or self._driver.name.lower() == 'msedge' or self._driver.name.lower() == 'internet explorer'):
            self._driver.switch_to.window(str(current_handle))
        else:
            self._driver.switch_to._w3c_window(current_handle)

```

**Comment by abhayp505** [comment] 2020-09-21 06:01
Info about the env

HTTP Status: 200

{
	"moz:shutdownTimeout": 60000,
	"rotatable": false,
	"browserVersion": "80.0",
	"timeouts": {
		"pageLoad": 10000,
		"implicit": 500,
		"script": 10000
	},
	"strictFileInteractability": false,
	"acceptInsecureCerts": true,
	"moz:headless": false,
	"moz:geckodriverVersion": "0.24.0",
	"moz:webdriverClick": true,
	"moz:profile": "/var/folders/vl/hxyc1ht91p143px0y2f1fm3h0000kr/T/rust_mozprofile.PytrWW7NyIYg",
	"moz:accessibilityChecks": false,
	"browserName": "firefox",
	"setWindowRect": true,
	"moz:useNonSpecCompliantPointerOrigin": false,
	"moz:buildID": "20200818235255",
	"moz:processID": 4825,
	"pageLoadStrategy": "normal",
	"platformName": "mac",
	"platformVersion": "17.7.0",
	"unhandledPromptBehavior": "dismiss and notify"
}

**Comment by diemol** [comment] 2020-09-21 06:50
Ok, so this is only happening when using RemoteWebDriver then. Are you using Selenium Grid? If so, what is the configuration of the hub and nodes? Can you please provide the logs of the Grid as well?

**Comment by whimboo** [comment] 2020-09-21 08:13
@abhayp505 please have a look at your last comment. The log clearly tells that you are using a very outdated version of geckodriver:

> "moz:geckodriverVersion": "0.24.0",

Update it to 0.27.0 and it will all work.

**Comment by abhayp505** [comment] 2020-09-21 13:55
Missed the previous comment, thanks for update.

**Comment by diemol** [comment] 2020-09-21 15:20
Good catch, @whimboo!

Closing as this was not a Selenium or GeckoDriver bug.

**Closed as completed by diemol** 2020-09-21 15:20 UTC
Labels: J-awaiting answer, D-firefox
