### ISSUE TITLE
UnsupportedCommandException mouseMoveTo with 3.4 on firefox with geckodriver 0.16.1

### ISSUE THREAD

**Issue by sdarshanam** [SeleniumHQ/selenium#4008] opened 2017-05-11 22:01 UTC
OS:  Windows Server 2012
Selenium Version:  3.4.0
Browser:  Firefox v53.0
Browser Driver : geckodriver-v0.16.1-win64
Maven Java Bindings : 3.4.0

Selenium grid setup. Both the hub and node are running on different machines with the same OS.

Step to Reproduce:

		Actions act=new Actions(driver);
		act.moveToElement(projectDropDown);
		act.click(projectDropDown).build().perform();

Exception:
`
14:43:08.215 INFO - Executing: [mousemove: 22 false])
14:43:08.219 WARN - Exception thrown
org.openqa.selenium.UnsupportedCommandException: mouseMoveTo
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'WIN-AHNG9735N3J', ip: '10.237.194.162', os.name: 'Windows Server 2012', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_131'
Driver info: driver.version: RemoteWebDriver
        at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:220)
        at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:118)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
        at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
        at org.openqa.selenium.remote.RemoteMouse.mouseMove(RemoteMouse.java:89)
        at org.openqa.selenium.support.events.internal.EventFiringMouse.mouseMove(EventFiringMouse.java:58)
        at org.openqa.selenium.remote.server.handler.interactions.MouseMoveToLocation.call(MouseMoveToLocation.java:59)
        at org.openqa.selenium.remote.server.handler.interactions.MouseMoveToLocation.call(MouseMoveToLocation.java:32)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
14:43:08.229 WARN - Exception: mouseMoveTo
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'WIN-AHNG9735N3J', ip: '10.237.194.162', os.name: 'Windows Server 2012', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_131'
Driver info: driver.version: RemoteWebDriver
`

**Comment by jimevans** [comment] 2017-05-12 12:13
#3808 is the root cause. This will be fixed when that issue is.

**Closed by jimevans** 2017-05-12 12:13 UTC

**Comment by minnujp** [comment] 2017-06-15 05:20
hellow..
     Mouse hovering is not working in selenium 3.4.1 ,gecko driver .16 and firefox 52.What will do?can anybody help me?

**Comment by elarichev** [comment] 2017-07-14 09:38
Hi! I have same problem on
Windows 7 x64
Selenium 3.4.0
Firefox 55.0b8 (64-bit)
Geckodriver 0.18

How can I resolve this?

**Comment by Reedlee** [comment] 2017-07-19 11:58
+1
ubuntu 16.04 
selenium 3.4.0
Firefox 54
Geckodriver 0.18
run selenium as grid

when Behat executed to click or press it would responded with error mouseMoveTo
How can I replace this step?

**Comment by gwtuser** [comment] 2017-09-08 06:53
Issue #3808 seems to be referring to Grid, and Standalone Selenium.  Right now, they claim in that thread that a workaround is to pass -enablePassThrough true using Selenium JARS v3.5, but I'm just running Selenium directly by configuring geckodriver and then creating a FirefoxDriver() in Java.

How do I pass "-enablePassThrough true" to FirefoxDriver?  I don't see "enablePassThrough" amongst the DesiredCapabilities.
