### ISSUE TITLE
[🐛 Bug]: my python script not working suddenly

### ISSUE THREAD

**Issue by mhussein1984** [SeleniumHQ/selenium#11972] opened 2023-04-30 21:23 UTC
### What happened?

======================================================
this is my script but i replaced web because i'm using DVRs Ips 
this script it was working perfectly but now i got this error 
======================================================
Unable to obtain driver using Selenium Manager: internet explorer is not a valid browser.  Choose one of: ['chrome', 'firefox', 'edge', 'MicrosoftEdge', 'ie']
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\pythonProject\test66.py", line 14, in <module>
    driver = webdriver.Ie(options=ie_options)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\ie\webdriver.py", line 127, in __init__
    self.iedriver.path = DriverFinder.get_path(self.iedriver, options)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\common\driver_finder.py", line 43, in get_path
    raise err
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\common\driver_finder.py", line 40, in get_path
    path = shutil.which(service.path) or SeleniumManager().driver_location(options)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 84, in driver_location
    raise SeleniumManagerException(
selenium.common.exceptions.SeleniumManagerException: Message: internet explorer is not a valid browser.  Choose one of: ['chrome', 'firefox', 'edge', 'MicrosoftEdge', 'ie']

Process finished with exit code 1

### How can we reproduce the issue?

```shell
import time
from selenium import webdriver

ie_options = webdriver.IeOptions()
ie_options.attach_to_edge_chrome = True
ie_options.edge_executable_path = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"
driver = webdriver.Ie(options=ie_options)
ie_options.add_additional_option("useAutomationExtension", False)
ie_options.add_additional_option("excludeSwitches", ['enable-automation'])

username1 = "admin"
password1 = "admin123"
driver.maximize_window()

links = ["http://web1.com", "http://web2.com", "http://web3.com"]
count = 1
for link in links:
     time.sleep(1)
     driver.get(link)
     windows_before = driver.current_window_handle
     elem1 = driver.find_element("id", "username").send_keys(username1)
     elem2 = driver.find_element("id", "password").send_keys(password1)
     time.sleep(1)

    if count == 1:
        driver.execute_script('document.title = "web1"')
    elif count == 2:
        driver.execute_script('document.title = "web2"')
    else:
        driver.execute_script('document.title = "web3"')
    if count == 3:
      break
    driver.execute_script("window.open('');")
    new_window = driver.window_handles[count]
    count += 1
    driver.switch_to.window(new_window)
```

### Relevant log output

```shell
Unable to obtain driver using Selenium Manager: internet explorer is not a valid browser.  Choose one of: ['chrome', 'firefox', 'edge', 'MicrosoftEdge', 'ie']
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\pythonProject\test66.py", line 14, in <module>
    driver = webdriver.Ie(options=ie_options)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\ie\webdriver.py", line 127, in __init__
    self.iedriver.path = DriverFinder.get_path(self.iedriver, options)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\common\driver_finder.py", line 43, in get_path
    raise err
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\common\driver_finder.py", line 40, in get_path
    path = shutil.which(service.path) or SeleniumManager().driver_location(options)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 84, in driver_location
    raise SeleniumManagerException(
selenium.common.exceptions.SeleniumManagerException: Message: internet explorer is not a valid browser.  Choose one of: ['chrome', 'firefox', 'edge', 'MicrosoftEdge', 'ie']

Process finished with exit code 1
```

### Operating System

windows 10 and 11

### Selenium version

python 3

### What are the browser(s) and version(s) where you see this issue?

Internet explorer mode on Edge

### What are the browser driver(s) and version(s) where you see this issue?

webdriver 4.8

**Comment by diemol** [comment] 2023-04-30 22:03
Duplicate of https://github.com/SeleniumHQ/selenium/issues/11928.

Please use the previous version while we release a bug fix.

**Closed as completed** 2023-04-30 22:04 UTC
