### ISSUE TITLE
--session-timeout does not close the browser, if the browser is still trying to load the resource

### ISSUE THREAD

**Issue by JannisBush** [SeleniumHQ/selenium#9498] opened 2021-05-21 11:02 UTC
## 🐛 Bug Report

If a browser is still trying to load a resource and the timeout specified by `--session-timeout` is reached, the closing of the browser will fail, but the selenium server will reopen the slot potentially leading to many still opened stale browsers.
(Same issue first opened in the docker repository: https://github.com/SeleniumHQ/docker-selenium/issues/1283)

## To Reproduce
 
- Start selenium: `java -jar selenium-server-4.0.0-beta-3.jar standalone --session-timeout 5` (needs chrome and chrome driver in path, probably other browsers are affected too)
- Start a web server that will take a long time to answer
- Run a selenium script that tries to load a resource of the slow web server
- Wait for the timeout
- Result: closing fails (browser still opened), selenium has reopened the slot (http://localhost:4444/ui/index.html#/)

## Expected behavior

Selenium closes the browser correctly after the session times out.

## Test script or set of commands reproducing this issue

`server.py`:
```python
from http.server import BaseHTTPRequestHandler,HTTPServer
import time

class Handler(BaseHTTPRequestHandler):
    def do_GET( self ):
        time.sleep(6000)
        self.send_response(200)
        self.send_header( 'Content-type', 'text/html' )
        self.end_headers()

httpd = HTTPServer( ('127.0.0.1', 8080), Handler )
httpd.serve_forever()
```
`test.py`:
```python
import os
from selenium import webdriver

grid_url = "http://localhost:4444/wd/hub"
def get_driver():
    return webdriver.Remote(
        command_executor=grid_url,
        options=webdriver.ChromeOptions())
try:    
    driver = get_driver()
    driver.get("http://127.0.0.1:8080")
except Exception as e:
        print(e)
```
- Run `java -jar selenium-server-4.0.0-beta-3.jar standalone --session-timeout 5`
- Run `python3 server.py`
- Run `python3 test.py`

## Environment

OS: Linux
Browser: Chrome
Browser version: 90.0.4430.212
Browser Driver version: ChromeDriver 90.0.4430.24
Language Bindings version: python-4.0.0.b3
Selenium Grid version (if applicable): 4.0.0-beta-3

**Comment by JannisBush** [comment] 2021-05-21 11:07
- Logs:
    - `test.py`: [out.txt](https://github.com/SeleniumHQ/selenium/files/6522052/out.txt)
    - `selenium server`: [out-server.txt](https://github.com/SeleniumHQ/selenium/files/6522063/out-server.txt)

**Comment by diemol** [comment] 2021-05-31 10:07
@JannisBush, thank you for providing enough information to reproduce the issue.

I was able to see the same behaviour you describe, and after double checking the code and going through the code flow, I can conclude that this is one of the reasons why the session timeout is configurable. 

Let me describe the code flow:

Session starts -> load url command sent by client -> Grid forwards command to ChromeDriver (or GeckoDriver, browser is not relevant in this case) -> ChromeDriver tells Chrome to load url -> Long wait due to the page loading slowly

At this point, the request is waiting for the page to load. The session timeout triggers and the session is [stopped](https://github.com/SeleniumHQ/selenium/blob/47824b377592e4949af94327fb559483830176f6/java/server/src/org/openqa/selenium/grid/node/local/LocalNode.java#L161). When the session is stopped, one of the steps is to [shutdown](https://github.com/SeleniumHQ/selenium/blob/49f706f436b7c97d5ac39596d141d345aef58b79/java/client/src/org/openqa/selenium/remote/service/DriverService.java#L276) the browser driver. 

That shutdown is an http request to the browser driver, but the browser driver is blocked since it is still loading the page, therefore the shutdown will most likely timeout (which is what you see in the logs), and the browser & browser driver will remain open. 

This scenario can happen with any interaction that eventually needs a long time to process. Which is why the session timeout is configurable, to allow a proper timeout depending on your environment. This also helps to spot issues on your infrastructure or potential bugs in the application under test, as it should not be normal for a request to take longer than the session timeout. So, if you see often browsers left open, session timeout needs to be adjusted or the network connections need to be double checked or the application under test is having issues.

I will close this issue as there it no needed change in the Grid, but if you want to propose an alternative that still keeps the Grid code simple and maintanable, feel free to comment and we can see if there is a way to add your suggestion.

**Closed as completed by diemol** 2021-05-31 10:07 UTC
Labels: B-grid
