### ISSUE TITLE
OpenQA.Selenium.Internal.FileUtilities.CopyDirectory BUG ?

### ISSUE THREAD

**Issue by StoicaNicusor** [SeleniumHQ/selenium#5780] opened 2018-04-15 18:12 UTC
So this is the source code :

`
		public static bool CopyDirectory(string sourceDirectory, string destinationDirectory)
		{
			DirectoryInfo directoryInfo = new DirectoryInfo(sourceDirectory);
			DirectoryInfo directoryInfo2 = new DirectoryInfo(destinationDirectory);
			if (directoryInfo.Exists)
			{
				if (!directoryInfo2.Exists)
				{
					directoryInfo2.Create();
				}
				foreach (FileInfo fileInfo in directoryInfo.GetFiles())
				{
					fileInfo.CopyTo(Path.Combine(directoryInfo2.FullName, fileInfo.Name));
				}
				foreach (DirectoryInfo directoryInfo3 in directoryInfo.GetDirectories())
				{
					FileUtilities.CopyDirectory(directoryInfo3.FullName, Path.Combine(directoryInfo2.FullName, directoryInfo3.Name));
				}
			}
			return true;
		}
`

Calling profile.WriteToDisk() (where profile = FirefoxProfile()) should copy from %temp%\anonymous.4f674f34eace416bbe61b9ff8449a7bb.webdriver-profile to my profile dir path, witch is just an empty directory; so tring sourceDirectory should be %temp%\anonymous.4f674f34eace416bbe61b9ff8449a7bb.webdriver-profile and string destinationDirectory should be "C:\seleniumFF\profiles\newProfileWithExtensions\" but the values are swapped (source = destibation and destination = source).
Every time I call profile.WriteToDisk() , nothing happens.
This is my profile code :

`
            OpenQA.Selenium.Firefox.FirefoxProfile profile = new OpenQA.Selenium.Firefox.FirefoxProfile(@"C:\seleniumFF\profiles\newProfileWithExtensions\", false);
            profile.AcceptUntrustedCertificates = true;
            profile.AlwaysLoadNoFocusLibrary = true;
            profile.SetPreference("dom.ipc.plugins.enabled.libflashplayer.so", false);
            profile.AddExtension(@"....xpi");
            profile.AddExtension(@"....xpi");
            profile.AddExtension(@"....xpi");
            profile.AcceptUntrustedCertificates = true;
            profile.WriteToDisk();
`

**Comment by diemol** [comment] 2020-09-19 21:42
@StoicaNicusor is this issue still valid with the latest versions of the dot net bindings?

**Comment by diemol** [comment] 2020-11-10 22:40
I close this for now since we did not get more information, however, if the issue is still valid with the most recent versions, please feel free to open a new issue.

**Closed by diemol** 2020-11-10 22:40 UTC
Labels: C-dotnet, R-awaiting answer
