### ISSUE TITLE
IE driver crashes when accessing an element during page load

### ISSUE THREAD

**Issue by a-ctor** [SeleniumHQ/selenium#4204] opened 2017-06-20 12:02 UTC
## Meta
OS:  
Windows 10

Selenium Version:  
3.4

Browser:  
Internet Explorer

Browser Version:
11.1198.14393.0 (64-bit)

## Expected Behavior
When starting an action during a browser page load the driver waits until the page is loaded and then returns the result of the action.

## Actual Behavior
The IE driver crashes instead of returning a result.

## Steps to reproduce
> index.html
```
<form id="form" method="get">
	<input id="value" type="text" />
</form>

<script>
    setTimeout(function () {
        document.getElementById("form").submit(); 
    }, 500);
</script>
```

> script.csx
```
#r "WebDriver.dll"

using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.IE;

var driver = new InternetExplorerDriver();
driver.Navigate().GoToUrl("http://localhost:8000");

for (var i = 0; i < 1000; i++)
{
	try
	{
	  var textBox = driver.FindElementById ("value");
	  textBox.Click();
	}
	catch (Exception)
	{
	}
}
```

with `WebDriver.dll` (v3.4.0.0) and `IEDriverServer.exe` (v3.4.0.0) in the same folder.

 - Host `index.html` on port 8000 (e.g. `python -m http.server 8000`)
 - Start the script (e.g. `csi script.csx`)
 - `IEDriverServer.exe` crashes after ~ 3 seconds after the page is loaded.

**Comment by barancev** [comment] 2017-07-17 15:27
I can't reproduce it with the Java binding. Is it a .Net specific issue?

**Comment by barancev** [comment] 2019-07-14 18:54
Is this issue still actual? I can't reproduce it with C# too.

**Comment by Stefan-Ilic** [comment] 2019-08-29 13:52
We cannot reproduce this issue anymore either, neither with the WebDriver and IEDriverServer versions in this issue, nor with newer versions. We suspect this issue is connected to the IE version used. Since there is no easy way to download older IE versions, we did not try running the sample with the IE version provided when this issue was originally reported.

**Comment by jimevans** [comment] 2019-08-29 17:04
If it’s no longer reproducible, we’ll close this one then.

**Closed by jimevans** 2019-08-29 17:04 UTC
Labels: D-IE, R-awaiting answer
