### ISSUE TITLE
Chrome Driver - not using download.default_directory

### ISSUE THREAD

**Issue by vinsguru** [SeleniumHQ/selenium#5551] opened 2018-03-01 05:53 UTC
I am overriding the chrome driver download dir using below code.

```
            HashMap<String, Object> chromePrefs = new HashMap<String, Object>();
            chromePrefs.put("profile.default_content_settings.popups", 0);
            chromePrefs.put("download.default_directory", "/home/seluser/downloads");
            chromePrefs.put("download.prompt_for_download", "false");
            ChromeOptions options = new ChromeOptions();
            options.setExperimentalOption("prefs", chromePrefs);
            options.addArguments("--test-type");
            dc.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
            dc.setCapability(ChromeOptions.CAPABILITY, options);

           driver = new RemoteWebDriver(new URL("http://remotehost:4444/wd/hub"), dc);
```

However the file always gets download into **/home/seluser/Downloads** even if the **/home/seluser/downloads** exists with enough permission.

Selenium version 3.9.1
Chrome driver version 2.35

**Comment by gaffney** [comment] 2019-02-08 07:38
This is almost a year old - any updates?

**Comment by cgoldberg** [comment] 2019-02-08 16:31
closing as dupe of #5292  ... please track it there.

**Closed by cgoldberg** 2019-02-08 16:31 UTC
Labels: C-java, D-chrome

**Comment by Infinity86** [comment] 2019-02-20 09:32
Nice, 5551 is closed as duplicate od 5292.
5292 is closed as duplicate od 5551.
Are you kidding me ?
