### ISSUE TITLE
selenium can no longer send keys to Firefox after upgrading selenium and geckodriver

### ISSUE THREAD

**Issue by mo** [SeleniumHQ/selenium#5715] opened 2018-04-01 19:17 UTC
minimal testcase repro here (just run "npm test"):
https://github.com/mo/e2e-bug-repro

When I upgraded "wdio-selenium-standalone-service" from 0.0.9 to 0.0.10 I stopped being able to send keys to Firefox via geckodriver.

wdio-selenium-standalone-service 0.0.9 uses "selenium-standalone" 6.5.0 which in turn uses selenium 3.4.0 and geckodriver 0.16.1

wdio-selenium-standalone-service 0.0.10 uses "selenium-standalone" 6.13.0 which in turn uses selenium 3.8.1 and geckodriver 0.19.1

If you want to downgrade the "wdio-selenium-standalone-service" npm package run "npm install --save wdio-selenium-standalone-service@0.0.9"

If you want to look at the selenium / geckodriver logs, open the "e2e-bug-repro" directory in another terminal and then run "./node_modules/.bin/selenium-standalone start -- -debug" and then run "npm run test-firefox-only" to trigger the bug.

I have also tried to upgrade to geckodriver 0.20.0 with selenium 3.8.1, but the testcase still does not pass in Firefox. I also built selenium from git and tried that, and it still doesn't pass in Firefox.

The selenium log (including geckodriver at TRACE level) outputs this:
```
19:15:31.766 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@dee028a
19:15:31.766 INFO - Handler thread for session d58c9d0f-8eb5-49fa-88d5-1149cd2ece79 (firefox): Executing POST on /session/d58c9d0f-8eb5-49fa-88d5-1149cd2ece79/keys (handler: ServicedSession)
19:15:31.770 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@dee028a
19:15:31.770 INFO - Handler thread for session d58c9d0f-8eb5-49fa-88d5-1149cd2ece79 (firefox): Executing POST on /session/d58c9d0f-8eb5-49fa-88d5-1149cd2ece79/actions (handler: ServicedSession)
19:15:31.881 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@dee028a
19:15:31.882 INFO - Handler thread for session d58c9d0f-8eb5-49fa-88d5-1149cd2ece79 (firefox): Executing DELETE on /session/d58c9d0f-8eb5-49fa-88d5-1149cd2ece79 (handler: ServicedSession)
19:15:31.882 DEBUG - CookieSpec selected: default
19:15:31.882 DEBUG - Auth cache not set in the context
19:15:31.882 DEBUG - Connection request: [route: {}->http://localhost:2790][total kept alive: 5; route allocated: 0 of 2000; total allocated: 5 of 2000]
19:15:31.882 DEBUG - Connection leased: [id: 39][route: {}->http://localhost:2790][total kept alive: 5; route allocated: 1 of 2000; total allocated: 6 of 2000]
19:15:31.882 DEBUG - Opening connection {}->http://localhost:2790
19:15:31.883 DEBUG - Connecting to localhost/127.0.0.1:2790
19:15:31.883 DEBUG - Connection established 127.0.0.1:60258<->127.0.0.1:2790
19:15:31.883 DEBUG - http-outgoing-39: set socket timeout to 10800000
19:15:31.883 DEBUG - Executing request DELETE /session/d58c9d0f-8eb5-49fa-88d5-1149cd2ece79 HTTP/1.1
19:15:31.883 DEBUG - Target auth state: UNCHALLENGED
19:15:31.883 DEBUG - Proxy auth state: UNCHALLENGED
19:15:31.883 DEBUG - http-outgoing-39 >> DELETE /session/d58c9d0f-8eb5-49fa-88d5-1149cd2ece79 HTTP/1.1
19:15:31.883 DEBUG - http-outgoing-39 >> Host: localhost:2790
19:15:31.883 DEBUG - http-outgoing-39 >> Connection: Keep-Alive
19:15:31.883 DEBUG - http-outgoing-39 >> User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_161)
19:15:31.883 DEBUG - http-outgoing-39 >> Accept-Encoding: gzip,deflate
19:15:31.883 DEBUG - http-outgoing-39 >> "DELETE /session/d58c9d0f-8eb5-49fa-88d5-1149cd2ece79 HTTP/1.1[\r][\n]"
19:15:31.883 DEBUG - http-outgoing-39 >> "Host: localhost:2790[\r][\n]"
19:15:31.884 DEBUG - http-outgoing-39 >> "Connection: Keep-Alive[\r][\n]"
19:15:31.884 DEBUG - http-outgoing-39 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_161)[\r][\n]"
19:15:31.884 DEBUG - http-outgoing-39 >> "Accept-Encoding: gzip,deflate[\r][\n]"
19:15:31.884 DEBUG - http-outgoing-39 >> "[\r][\n]"
1522602931884	webdriver::server	DEBUG	-> DELETE /session/d58c9d0f-8eb5-49fa-88d5-1149cd2ece79 
1522602931884	geckodriver::marionette	TRACE	-> 37:[0,3,"quit",{"flags":["eForceQuit"]}]
1522602931884	Marionette	TRACE	0 -> [0,3,"quit",{"flags":["eForceQuit"]}]
1522602931886	Marionette	DEBUG	New connections will no longer be accepted
1522602931924	Marionette	TRACE	0 <- [1,3,null,{"cause":"shutdown"}]
1522602931936	geckodriver::marionette	TRACE	<- [1,3,null,{"cause":"shutdown"}]
1522602931936	webdriver::server	DEBUG	Deleting session
1522602931936	geckodriver::marionette	DEBUG	Stopping browser process
[Child 70176, Chrome_ChildThread] WARNING: pipe error (15): Connection reset by peer: file /build/firefox-MBnaRH/firefox-59.0.2+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
[Child 70176, Chrome_ChildThread] WARNING: pipe error (3): Connection reset by peer: file /build/firefox-MBnaRH/firefox-59.0.2+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
1522602931962	webdriver::server	DEBUG	<- 200 OK {"value": {}}
19:15:31.962 DEBUG - http-outgoing-39 << "HTTP/1.1 200 OK[\r][\n]"
19:15:31.962 DEBUG - http-outgoing-39 << "Connection: close[\r][\n]"
19:15:31.962 DEBUG - http-outgoing-39 << "Content-Type: application/json; charset=utf-8[\r][\n]"
19:15:31.962 DEBUG - http-outgoing-39 << "Cache-Control: no-cache[\r][\n]"
19:15:31.962 DEBUG - http-outgoing-39 << "Content-Length: 13[\r][\n]"
19:15:31.963 DEBUG - http-outgoing-39 << "Date: Sun, 01 Apr 2018 17:15:31 GMT[\r][\n]"
19:15:31.963 DEBUG - http-outgoing-39 << "[\r][\n]"
19:15:31.963 DEBUG - http-outgoing-39 << "{"value": {}}"
19:15:31.963 DEBUG - http-outgoing-39 << HTTP/1.1 200 OK
19:15:31.963 DEBUG - http-outgoing-39 << Connection: close
19:15:31.963 DEBUG - http-outgoing-39 << Content-Type: application/json; charset=utf-8
19:15:31.963 DEBUG - http-outgoing-39 << Cache-Control: no-cache
19:15:31.963 DEBUG - http-outgoing-39 << Content-Length: 13
19:15:31.963 DEBUG - http-outgoing-39 << Date: Sun, 01 Apr 2018 17:15:31 GMT
19:15:31.963 DEBUG - http-outgoing-39: Close connection
19:15:31.963 DEBUG - Connection discarded
19:15:31.964 DEBUG - Connection released: [id: 39][route: {}->http://localhost:2790][total kept alive: 5; route allocated: 0 of 2000; total allocated: 5 of 2000]
19:15:31.964 DEBUG - Decoding response. Response code was: 200 and content: {"value": {}}
19:15:31.965 INFO - Removing session org.openqa.selenium.remote.server.ServicedSession@dee028a
19:15:31.965 DEBUG - CookieSpec selected: default
19:15:31.965 DEBUG - Auth cache not set in the context
19:15:31.966 DEBUG - Connection request: [route: {}->http://localhost:2790][total kept alive: 5; route allocated: 0 of 2000; total allocated: 5 of 2000]
19:15:31.966 DEBUG - Connection leased: [id: 40][route: {}->http://localhost:2790][total kept alive: 5; route allocated: 1 of 2000; total allocated: 6 of 2000]
19:15:31.966 DEBUG - Opening connection {}->http://localhost:2790
19:15:31.966 DEBUG - Connecting to localhost/127.0.0.1:2790
19:15:31.966 DEBUG - Connection established 127.0.0.1:60260<->127.0.0.1:2790
19:15:31.966 DEBUG - http-outgoing-40: set socket timeout to 10800000
19:15:31.967 DEBUG - Executing request DELETE /session/d58c9d0f-8eb5-49fa-88d5-1149cd2ece79 HTTP/1.1
19:15:31.967 DEBUG - Target auth state: UNCHALLENGED
19:15:31.967 DEBUG - Proxy auth state: UNCHALLENGED
19:15:31.967 DEBUG - http-outgoing-40 >> DELETE /session/d58c9d0f-8eb5-49fa-88d5-1149cd2ece79 HTTP/1.1
19:15:31.967 DEBUG - http-outgoing-40 >> Host: localhost:2790
19:15:31.967 DEBUG - http-outgoing-40 >> Connection: Keep-Alive
19:15:31.967 DEBUG - http-outgoing-40 >> User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_161)
19:15:31.967 DEBUG - http-outgoing-40 >> Accept-Encoding: gzip,deflate
19:15:31.968 DEBUG - http-outgoing-40 >> "DELETE /session/d58c9d0f-8eb5-49fa-88d5-1149cd2ece79 HTTP/1.1[\r][\n]"
19:15:31.968 DEBUG - http-outgoing-40 >> "Host: localhost:2790[\r][\n]"
19:15:31.968 DEBUG - http-outgoing-40 >> "Connection: Keep-Alive[\r][\n]"
19:15:31.968 DEBUG - http-outgoing-40 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_161)[\r][\n]"
19:15:31.968 DEBUG - http-outgoing-40 >> "Accept-Encoding: gzip,deflate[\r][\n]"
19:15:31.968 DEBUG - http-outgoing-40 >> "[\r][\n]"
1522602931968	webdriver::server	DEBUG	-> DELETE /session/d58c9d0f-8eb5-49fa-88d5-1149cd2ece79 
1522602931969	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"session not created","message":"Tried to run command without establishing a connection","stacktrace":"stack backtrace:\n   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e\n   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46\n   2:           0x4409a1 - webdriver::error::WebDriverError::new::h81babdd86c977032\n   3:           0x4280ea - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193\n   4:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25\n   5:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba\n   6:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic\n                        at /checkout/src/libpanic_unwind/lib.rs:99\n   7:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473\n   8:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /checkout/src/liballoc/boxed.rs:692\n                         - std::sys_common::thread::start_thread\n                        at /checkout/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /checkout/src/libstd/sys/unix/thread.rs:84"}}
19:15:31.970 DEBUG - http-outgoing-40 << "HTTP/1.1 500 Internal Server Error[\r][\n]"
19:15:31.970 DEBUG - http-outgoing-40 << "Connection: close[\r][\n]"
19:15:31.970 DEBUG - http-outgoing-40 << "Content-Type: application/json; charset=utf-8[\r][\n]"
19:15:31.970 DEBUG - http-outgoing-40 << "Cache-Control: no-cache[\r][\n]"
19:15:31.970 DEBUG - http-outgoing-40 << "Content-Length: 1296[\r][\n]"
19:15:31.970 DEBUG - http-outgoing-40 << "Date: Sun, 01 Apr 2018 17:15:31 GMT[\r][\n]"
19:15:31.970 DEBUG - http-outgoing-40 << "[\r][\n]"
19:15:31.971 DEBUG - http-outgoing-40 << "{"value":{"error":"session not created","message":"Tried to run command without establishing a connection","stacktrace":"stack backtrace:\n   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e\n   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46\n   2:           0x4409a1 - webdriver::error::WebDriverError::new::h81babdd86c977032\n   3:           0x4280ea - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193\n   4:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25\n   5:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba\n   6:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic\n                        at /checkout/src/libpanic_unwind/lib.rs:99\n   7:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473\n   8:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /checkout/src/liballoc/boxed.rs:692\n                         - std::sys_common::thread::start_thread\n                        at /checkout/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /checkout/src/libstd/sys/unix/thread.rs:84"}}"
19:15:31.971 DEBUG - http-outgoing-40 << HTTP/1.1 500 Internal Server Error
19:15:31.971 DEBUG - http-outgoing-40 << Connection: close
19:15:31.971 DEBUG - http-outgoing-40 << Content-Type: application/json; charset=utf-8
19:15:31.971 DEBUG - http-outgoing-40 << Cache-Control: no-cache
19:15:31.971 DEBUG - http-outgoing-40 << Content-Length: 1296
19:15:31.971 DEBUG - http-outgoing-40 << Date: Sun, 01 Apr 2018 17:15:31 GMT
19:15:31.972 DEBUG - http-outgoing-40: Close connection
19:15:31.972 DEBUG - Connection discarded
19:15:31.972 DEBUG - Connection released: [id: 40][route: {}->http://localhost:2790][total kept alive: 5; route allocated: 0 of 2000; total allocated: 5 of 2000]
19:15:31.972 DEBUG - Decoding response. Response code was: 500 and content: {"value":{"error":"session not created","message":"Tried to run command without establishing a connection","stacktrace":"stack backtrace:\n   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e\n   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46\n   2:           0x4409a1 - webdriver::error::WebDriverError::new::h81babdd86c977032\n   3:           0x4280ea - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193\n   4:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25\n   5:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba\n   6:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic\n                        at /checkout/src/libpanic_unwind/lib.rs:99\n   7:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473\n   8:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /checkout/src/liballoc/boxed.rs:692\n                         - std::sys_common::thread::start_thread\n                        at /checkout/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /checkout/src/libstd/sys/unix/thread.rs:84"}}
19:15:31.972 DEBUG - Processing an error
```

In the webdriver.io end, the interesting part of the code is located at: node_modules/webdriverio/build/lib/protocol/keys.js:70 ... on this location is tries to submit the (legacy?) /keys command, and when geckodriver says unknown command it quote "tries to use the W3C path". I've tried various variants of this code, for example sending the W3C request directly etc but I keep running into the same issue. Code from keys.js:70 below:

```js
    return this.requestHandler.create('/session/:sessionId/keys', { value: key }).catch(function (err) {
        /**
         * use W3C path if old path failed
         */
        if ((0, _utilities.isUnknownCommand)(err)) {
            var keyDownActions = key.map(function (value) {
                return { type: 'keyDown', value };
            });
            var keyUpActions = key.map(function (value) {
                return { type: 'keyUp', value };
            });

            return _this.actions([{
                type: 'key',
                id: 'keys',
                actions: [].concat((0, _toConsumableArray3.default)(keyDownActions), (0, _toConsumableAr$
            }]);
        }

        throw err;
    });
```

Should key events be going to /actions? Could it be that selenium corrupts the actions command somehow?

**Comment by lmtierney** [comment] 2018-04-02 00:18
The only endpoint used for actions in w3c drivers is `/actions`. `/keys` is no longer an endpoint.

**Comment by mo** [comment] 2018-04-02 12:56
Both "keys" and "actions" are visible in the first 5 lines above even though github makes you scroll horizontally to see it :-(

Is it possible to enable more detailed logging in selenium? I passed "-debug" when I started the server at least.

**Comment by lmtierney** [comment] 2018-04-02 13:13
Not that I'm aware of, there should be some client-side logging in your bindings that would show the outgoing request though.

**Comment by barancev** [comment] 2018-04-02 13:47
Can we have a reproduction scenario without webdriver.io?

**Comment by mo** [comment] 2018-04-02 18:32
I took a stab at reproducing this bug via the official python bindings but it works fine there.

When I run my repro using selenium 3.4.0 (where there is no bug), then /actions results in the following:

```
20:15:14.635 DEBUG - Handling: POST /session/1577d671-959a-46bc-a82e-e288f0596d44/actions
20:15:14.637 INFO - Executing: org.openqa.selenium.remote.server.handler.W3CActions@6d4ec6c8)
20:15:14.638 DEBUG - CookieSpec selected: default
20:15:14.638 DEBUG - Auth cache not set in the context
20:15:14.638 DEBUG - Connection request: [route: {}->http://localhost:13527][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
20:15:14.638 DEBUG - Connection leased: [id: 2][route: {}->http://localhost:13527][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
20:15:14.638 DEBUG - Opening connection {}->http://localhost:13527
20:15:14.639 DEBUG - Connecting to localhost/127.0.0.1:13527
20:15:14.639 DEBUG - Connection established 127.0.0.1:35882<->127.0.0.1:13527
20:15:14.639 DEBUG - http-outgoing-2: set socket timeout to 10800000
20:15:14.639 DEBUG - Executing request POST /session/0b920d15-7b26-4d49-a504-067912f44741/actions HTTP/1.1
20:15:14.639 DEBUG - Target auth state: UNCHALLENGED
20:15:14.639 DEBUG - Proxy auth state: UNCHALLENGED
20:15:14.640 DEBUG - http-outgoing-2 >> POST /session/0b920d15-7b26-4d49-a504-067912f44741/actions HTTP/1.1
20:15:14.640 DEBUG - http-outgoing-2 >> Content-Type: application/json; charset=utf-8
20:15:14.640 DEBUG - http-outgoing-2 >> Content-Length: 112
20:15:14.640 DEBUG - http-outgoing-2 >> Host: localhost:13527
```

However, with selenium 3.8.1 I only get this:

```
20:13:13.599 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@1eb8a5a9
20:13:13.599 INFO - Handler thread for session f7b8d017-90e7-496e-bd6c-40fea14316f7 (firefox): Executing POST on /session/f7b8d017-90e7-496e-bd6c-40fea14316f7/actions (handler: ServicedSession)
20:13:13.712 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@1eb8a5a9
20:13:13.712 INFO - Handler thread for session f7b8d017-90e7-496e-bd6c-40fea14316f7 (firefox): Executing DELETE on /session/f7b8d017-90e7-496e-bd6c-40fea14316f7 (handler: ServicedSession)
20:13:13.713 DEBUG - CookieSpec selected: default
20:13:13.714 DEBUG - Auth cache not set in the context
20:13:13.714 DEBUG - Connection request: [route: {}->http://localhost:1340][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
20:13:13.714 DEBUG - Connection leased: [id: 2][route: {}->http://localhost:1340][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
20:13:13.714 DEBUG - Opening connection {}->http://localhost:1340
20:13:13.714 DEBUG - Connecting to localhost/127.0.0.1:1340
20:13:13.715 DEBUG - Connection established 127.0.0.1:38362<->127.0.0.1:1340
20:13:13.715 DEBUG - http-outgoing-2: set socket timeout to 10800000
20:13:13.715 DEBUG - Executing request DELETE /session/f7b8d017-90e7-496e-bd6c-40fea14316f7 HTTP/1.1
20:13:13.715 DEBUG - Target auth state: UNCHALLENGED
20:13:13.715 DEBUG - Proxy auth state: UNCHALLENGED
20:13:13.715 DEBUG - http-outgoing-2 >> DELETE /session/f7b8d017-90e7-496e-bd6c-40fea14316f7 HTTP/1.1
20:13:13.715 DEBUG - http-outgoing-2 >> Host: localhost:1340
20:13:13.716 DEBUG - http-outgoing-2 >> Connection: Keep-Alive
```

So for selenium 3.4.0 I can see the actual "http-outgoing-2 >> POST /session/0b920d15-7b26-4d49-a504-067912f44741/actions" part where the command is forwarded to geckodriver. With selenium 3.8.1 I see that selenium received the /actions command and that it is "handled by ServicedSession" but it seems like no http call to geckodriver is made and no error is printed either; it just moves on to process the session delete command right away.

Is there some additional trick to enable more log output from ServicedSession ?

**Comment by mo** [comment] 2018-04-02 20:11
I added some debug code on top of selenium git HEAD, like this:
https://github.com/mo/selenium/commit/25af5e777ee06f04538b17c40bf88750fe6883f3

I built it using ```./go selenium-server-standalone```

I started it using:

```/usr/bin/java -Dwebdriver.gecko.driver=/path/to/geckodriver/0.19.1-x64-geckodriver -jar /path/to/src/selenium/buck-out/gen/java/server/src/org/openqa/grid/selenium/selenium.jar -debug
```
And when I run that version of selenium I get a little bit more details:

```
21:57:05.663 DEBUG [WebDriverServlet.handle] - Found handler: 887edc87-0100-44ab-98c7-614e899b0c17 (org.openqa.selenium.firefox.GeckoDriverService)
21:57:05.663 DEBUG [WebDriverServlet.lambda$handle$1] - Handler thread for session 887edc87-0100-44ab-98c7-614e899b0c17 (firefox): Executing POST on /session/887edc87-0100-44ab-98c7-614e899b0c17/actions (handler: ServicedSession)
21:57:05.663 DEBUG [WebDriverServlet.lambda$handle$1] - preparing wrappers
21:57:05.664 DEBUG [WebDriverServlet.lambda$handle$1] - about to execute
21:57:05.664 DEBUG [AbstractHttpCommandCodec.decode] - path=/session/887edc87-0100-44ab-98c7-614e899b0c17/actions
21:57:05.664 DEBUG [AbstractHttpCommandCodec.decode] - AbstractHttpCommandCodec.decode throwing UnsupportedCommandException
21:57:05.665 DEBUG [WebDriverServlet.lambda$handle$1] - catching: org.openqa.selenium.UnsupportedCommandException: POST /session/887edc87-0100-44ab-98c7-614e899b0c17/actions
```

So selenium does receive the /actions command but AbstractHttpCommandCodec.decode() throws UnsupportedCommandException because /actions is not listed among the defineCommand() calls that are made in this file.

I can see it defined in http/W3CHttpCommandCodec.java but perhaps webdriverio has done something that causes selenium to initialize the wrong dialect?

**Comment by lmtierney** [comment] 2018-04-02 20:56
Possibly, doesn't the log say which dialect it uses? Or did we get rid of that INFO

**Comment by mo** [comment] 2018-04-02 21:01
I'm seeing this in the logs:
22:33:11.391 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C

I also added logging in the constructors of JsonHttpCommandCodec and W3CHttpCommandCodec and I can see that both are created when I run my testcase.

To debug it a bit further I added this logging in RemoteSession.java:

```
          LOG.fine("creating ProtocolConverter with downstream==" + downstream + " and upstream==" + upstream);
          codec = new ProtocolConverter(
              url,
              getCommandCodec(downstream),
              getResponseCodec(downstream),
              getCommandCodec(upstream),
              getResponseCodec(upstream));
```

...and it prints:

22:33:11.392 DEBUG [RemoteSession$Factory.performHandshake] - creating ProtocolConverter with downstream==OSS and upstream==W3C

It looks like in my case "downstreamDialects" is empty.

I dug a bit more and found that this value is coming from NewSessionPayload.java where it says among other things:

```
    if (getAlwaysMatch() != null || getFirstMatches() != null) {
      dialects.add(Dialect.W3C);
    }
```

I tried wrapping my capabilties into a "alwaysMatch": {} dict but that wasn't enough to make it switch to W3C mode it seems.

**Comment by christian-bromann** [comment] 2018-04-03 11:45
> So it looks a lot like webdriverio wrapped my capabilities in "desiredCapabilities" even though my wdio.conf.js does not mention it.

That is correct.

I is not an error with Selenium. It is most likely a problem with WebdriverIO not sending correct action command parameters. Since you raised an issue already here (webdriverio/webdriverio#2675), we can close this thread.

**Comment by barancev** [comment] 2018-04-03 12:09
@christian-bromann Thank you for clarification!

**Closed by barancev** 2018-04-03 12:09 UTC
Labels: R-awaiting answer
