### ISSUE TITLE
Issues accessing stripe iframe over capybara/selenium hub

### ISSUE THREAD

**Issue by HoneyryderChuck** [SeleniumHQ/selenium#8091] opened 2020-03-05 12:19 UTC
## 🐛 Bug Report

We're setting up functional tests for our payment journeys using the Stripe widget. Our application is a ruby application, and our tests use these gems:

* capybara 3.31.0
* selenium-webdriver 3.142.7
* cucumber 3.1.2

Our CI pipeline runs tests using docker-compose. We're using the image `selenium/standalone-chrome-debug:3.141.59-oxygen` to load selenium, and we setup hub communication using the following configuration for ruby:

```ruby
Capybara.javascript_driver = :selenium_remote_chrome
Capybara.match = :prefer_exact
Capybara.default_max_wait_time = 15

Capybara.register_driver :selenium_remote_chrome do |app|
  arguments = %w[no-default-browser-check start-maximized auto-open-devtools-for-tabs ignore-certificate-errors]
  arguments = %w[headless disable-gpu disable-dev-shm-usage no-sandbox window-size=1920,1200] if ENV["HEADLESS"] == "true"

  capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
    "chromeOptions" => { "args" => arguments }
    # acceptInsecureCerts: true,
  )
  
  Capybara::Selenium::Driver.new(
    app,
    browser: :remote,
    url: "http://selenium:4444/wd/hub",
    desired_capabilities: capabilities
  )
end
```

## The problem

Accessing elements within the stripe widget iframe isn't working. We use something similar to the following snippet:

```ruby
def pay_stripe
    sleep(0.7) # wait for the js to create the popup in response to pressing the button
    within_frame '__privateStripeFrame5' do # must be selenium
      # fill_in 'card_number', with: '4242424242424242' no longer works
      4.times {page.driver.browser.find_element(:name, 'cardnumber').send_keys('4242')}

      # fill_in 'cc-exp', with: '5/2018' no longer works
      page.driver.browser.find_element(:name, 'exp-date').send_keys '5/24'
      page.driver.browser.find_element(:id, 'cvc').send_keys '18'
    end
  end
```

however, this fails with the following error:

```
no such element: Unable to locate element: {"method":"name","selector":"cardnumber"}
        (Session info: chrome=74.0.3729.169)
        (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.19.76-linuxkit x86_64) (Selenium::WebDriver::Error::NoSuchElementError)
```

As far as I could tell, the remote driver sends http requests to selenium hub, which performs the `find` on demand, and hub can't look into the iframe.

We could verify that running selenium locally and running the selenium driver, we could fill in fields within the iframe. 

So, this either seems like a limitation of hub, or can we configure it so that we can access elements within the iframe?

**Comment by twalpole** [comment] 2020-03-05 15:29
Swapping to making driver direct ‘find_element’ calls directly isn’t going to make any difference because that’s what capybaras methods end up calling when using selenium. Have you tried extending your sleep length to see if it’s just a timing issue with iframe loading? Have you taken a screenshot to confirm what’s actually on the page? Have you confirmed that your CI machines can reach stripe? 

This is highly unlikely to be a selenium issue.

**Comment by HoneyryderChuck** [comment] 2020-03-05 16:25
swapping was necessary at the time to determine if this was an issue with capybara or the internal driver. 

> Have you tried extending your sleep...

yes.

> Have you taken a screenshot to confirm what’s actually on the page?

I'm actually getting these errors running with headless mode off (I use VNC viewer to reach the browser instance), so I can see it happening. The error posted above happens on the `find` call for the input field inside the iframe.

> Have you confirmed that your CI machines can reach stripe?

I can confirm that the CI machines can load the widget.


However, since I've posted this issue, I've noticed that I only get that error when headless mode is off, i.e. when I run the test in headless mode, I can access and fill in the input details from the iframe, and I did confirm it by taking a screenshot. So whatever error I'm having, it's only happening when I'm looking at the browser.

**Comment by twalpole** [comment] 2020-03-06 03:01
Have you output the source  of the frame -  `page.html` - while running the tests in  non-headless mode to make sure the fields are what you expect - it is easy for code to detect headless mode and render different output.

**Comment by HoneyryderChuck** [comment] 2020-03-06 16:20
I did, and the iframe is included there.

**Comment by p0deje** [comment] 2020-04-08 12:32
Do you mean https://stripe.com/docs/stripe-js by "Stripe iframe"? Can you create a sample code that fails with the demo provide on that page?

**Comment by diemol** [comment] 2020-04-24 08:53
Based on the comments and the absence of the requested sample code, I'll close this. Feel free to open a new one with the complete info in case this still happens.

**Closed by diemol** 2020-04-24 08:53 UTC
Labels: C-rb, R-awaiting answer
