### ISSUE TITLE
IllegalArgumentException thrown when using Relative Locators in alpha-6 version

### ISSUE THREAD

**Issue by Trollistar** [SeleniumHQ/selenium#8380] opened 2020-06-01 14:27 UTC
## 🐛 Bug Report

When using any Relative Locator with the alpha-6 version, I am getting the following exception **java.lang.IllegalArgumentException: Argument is of an illegal type: org.openqa.selenium.By$ByTagName** .

The code that you will find below throws the aforementioned exception in version **alpha-6**, but it works properly in alpha-5 and alpha-4.

## To Reproduce

```java
import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.locators.RelativeLocator;
import org.testng.annotations.Test;

public class BasicTests {

    @Test
    public void theBestTest() {
        WebDriverManager.chromedriver().setup();
        ChromeDriver driver = new ChromeDriver();
        driver.get("https://mvnrepository.com/");
        WebElement parentElement = driver.findElement(By.xpath("(//a[@href='/open-source'])[2]"));
        RelativeLocator.RelativeBy by = RelativeLocator.withTagName("a").below(parentElement);
        driver.findElement(by).click();
    }
}
```

Detailed steps to reproduce the behavior: Run the tests using the alpha-6 version of Selenium and the exception will occur.

## Expected behavior

"Aspect Oriented" link should should be successfully located and clicked, like when using alpha-5 or alpha-4.

## Actual behavior

The following exception is thrown:

```
java.lang.IllegalArgumentException: Argument is of an illegal type: org.openqa.selenium.By$ByTagName

	at org.openqa.selenium.remote.internal.WebElementToJsonConverter.apply(WebElementToJsonConverter.java:85)
	at org.openqa.selenium.remote.internal.WebElementToJsonConverter.apply(WebElementToJsonConverter.java:79)
	at org.openqa.selenium.remote.internal.WebElementToJsonConverter.apply(WebElementToJsonConverter.java:79)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:514)
	at org.openqa.selenium.support.locators.RelativeLocator$RelativeBy.findElements(RelativeLocator.java:176)
	at org.openqa.selenium.By.findElement(By.java:132)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:325)
	at BasicTests.theBestTest(BasicTests.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
```

## Environment

OS: MacoS Catalina
Browser: Chrome, Firefox
Browser version: Chrome 83.0.4103.61, Firefox 76.0.1 (64-bit)
Browser Driver version: ChromeDriver 83.0.4103.39, Geckodriver 0.26.0
Language Bindings version: Java 14.0.1
Selenium Grid version (if applicable): N/A

**Comment by seanpoulter** [comment] 2020-06-05 03:22
I've started working with the repo and found the JavaScript and Java builds fail the same way.

See #8375.

**Comment by barancev** [comment] 2020-06-16 19:22
Duplicate of #8368

**Closed by barancev** 2020-06-16 19:22 UTC
Labels: needs-triaging
