### ISSUE TITLE
[🐛 Bug]: ERROR	error sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE_108): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

### ISSUE THREAD

**Issue by vicozohili** [SeleniumHQ/selenium#11406] opened 2022-12-10 13:34 UTC
### What happened?

Dec 10, 2022 1:30:28 PM org.openqa.selenium.remote.service.DriverService findExecutable
WARNING: Unable to obtain driver using Selenium Manager: Unsuccessful command executed: [C:\Users\<user>\AppData\Local\Temp\selenium-manager17283176393723006992415082342136659\selenium-manager.exe, --driver, chromedriver]
WARN	Sending fatal alert BadCertificate
ERROR	error sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE_108): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

Build info: version: '4.7.1', revision: 'c6795baf1a3'
System info: os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_341'
Driver info: driver.version: unknown

### How can we reproduce the issue?

```shell
Using Selenium Manager 4.7.1 to launch chrome v108
```

### Relevant log output

```shell
Dec 10, 2022 1:30:28 PM org.openqa.selenium.remote.service.DriverService findExecutable
WARNING: Unable to obtain driver using Selenium Manager: Unsuccessful command executed: [C:\Users\<user>\AppData\Local\Temp\selenium-manager17283176393723006992415082342136659\selenium-manager.exe, --driver, chromedriver]
WARN	Sending fatal alert BadCertificate
ERROR	error sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE_108): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

Build info: version: '4.7.1', revision: 'c6795baf1a3'
System info: os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_341'
Driver info: driver.version: unknown
```

### Operating System

Windows

### Selenium version

4.7.1

### What are the browser(s) and version(s) where you see this issue?

chrome 108

### What are the browser driver(s) and version(s) where you see this issue?

NA

### Are you using Selenium Grid?

4.7.1

**Comment by vicozohili** [comment] 2022-12-10 13:41
Workaround, switch pom to release 4.6.0, run test to launch chrome then switch back to 4.7.1 and browser seems to launch.

**Comment by bonigarcia** [comment] 2022-12-13 17:42
It seems a connectivity problem related to the TLS certificate when trying to connect to the chromedriver online repository:

```
invalid peer certificate: UnknownIssuer
```

Maybe it is a temporary problem.

@vicozohili Is it working now, right?

**Comment by vicozohili** [comment] 2022-12-14 12:35
@bonigarcia On a daily basis since the issue was raised, I get the invalid peer certificate error and have to revert to 4.6.0 and then back to 4.7.1 before it starts working again.

**Comment by bonigarcia** [comment] 2022-12-16 14:45
I would like to know if this issue is consistent with version 4.7.x at your end. @vicozohili: To check that, could you please do the following?

1. Clear the Selenium Manager cache, i.e., remove the folder `C:\Users\<your-user>\.cache\selenium`
2. Rerun your tests using Selenium 4.7.x

And share the results here. Thanks.

**Comment by vicozohili** [comment] 2022-12-17 15:13
@bonigarcia , I performed the above steps and the result is still the same

Dec 17, 2022 3:10:19 PM org.openqa.selenium.remote.service.DriverService findExecutable
WARNING: Unable to obtain driver using Selenium Manager: Unsuccessful command executed: [C:\Users\<user>\AppData\Local\Temp\selenium-manager23391045110620002025040880721906655\selenium-manager.exe, --driver, chromedriver]
WARN	Sending fatal alert BadCertificate
ERROR	error sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE_108): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

Build info: version: '4.7.2', revision: '4d4020c3b7'
System info: os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_341'
Driver info: driver.version: unknown

In addition, I also include clearing of C:\Users\<user>\AppData\Local\Temp with no luck until I performed the said workaround of reverting back to 4.6.0 and then back to 4.7.x

**Comment by diemol** [comment] 2022-12-17 20:11
@bonigarcia would it be a good idea to print Selenium Manager's version in the log?

**Comment by titusfortner** [comment] 2022-12-17 20:38
So far the Manager version is dependent on Selenium version, so shouldn't matter at this point...

@vicozohili 
1. it sounds like you have a proxy on your machine, can you verify? 
2. When you switch back to 4.6 then upgrade to 4.7 does it stop working again the next day?

**Comment by vicozohili** [comment] 2022-12-18 14:20
@titusfortner , see response below
it sounds like you have a proxy on your machine, can you verify? 
Not a proxy, but connecting via company VPN
When you switch back to 4.6 then upgrade to 4.7 does it stop working again the next day? 
Yes

@bonigarcia selenium manager version is 4.7.2

**Comment by bonigarcia** [comment] 2022-12-19 11:56
The Selenium Manager logs show the following:

```
WARN Sending fatal alert BadCertificate
ERROR error sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE_108): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
```

I looked into that, and it seems a problem related to `rustls`. It happens in Selenium Manager 4.7 since we moved from native TLS (used in version 4.6) to `rusttls` (to avoid shared libraries issues). I have just committed a patch to try to solve it for the next release of Selenium Manager:

https://github.com/SeleniumHQ/selenium/compare/trunk...se_mgr_http_client

@vicozohili Could you please try to debug it? To do it, please download [selenium-manager_windows-x64](https://github.com/SeleniumHQ/selenium/suites/9945322254/artifacts/481596033), execute the following, and share the results here. Thanks in advance:

```
selenium-manager --browser chrome --debug --clear-cache
```

**Comment by vicozohili** [comment] 2022-12-20 12:57
@bonigarcia see below for results of executing
selenium-manager --browser chrome --debug --clear-cache

C:\Users\<user>\Downloads>selenium-manager --browser chrome --debug --clear-cache
DEBUG   Clearing cache at: C:\Users\<user>\.cache\selenium
DEBUG   Using shell command to find out chrome version
DEBUG   Running cmd command: "wmic datafile where name='%PROGRAMFILES:\\=\\\\%\\\\Google\\\\Chrome\\\\Application\\\\chrome.exe' get Version /value"
DEBUG   Output { status: ExitStatus(ExitStatus(0)), stdout: "\r\r\n\r\r\n\r\r\n", stderr: "No Instance(s) Available.\r\r\n" }
DEBUG   Running cmd command: "wmic datafile where name='%PROGRAMFILES(X86):\\=\\\\%\\\\Google\\\\Chrome\\\\Application\\\\chrome.exe' get Version /value"
DEBUG   Output { status: ExitStatus(ExitStatus(0)), stdout: "\r\r\n\r\r\nVersion=108.0.5359.125\r\r\n\r\r\n\r\r\n\r\r\n", stderr: "" }
DEBUG   The version of chrome is 108.0.5359.125
DEBUG   Detected browser: chrome 108
DEBUG   Reading chromedriver version from https://chromedriver.storage.googleapis.com/LATEST_RELEASE_108
DEBUG   starting new connection: https://chromedriver.storage.googleapis.com/
DEBUG   No cached session for DnsName(DnsName(DnsName("chromedriver.storage.googleapis.com")))
DEBUG   Not resuming any session
DEBUG   Using ciphersuite TLS13_AES_256_GCM_SHA384
DEBUG   Not resuming
DEBUG   TLS1.3 encrypted extensions: []
DEBUG   ALPN protocol is None
DEBUG   Ticket saved
DEBUG   Ticket saved
DEBUG   Required driver: chromedriver 108.0.5359.71
DEBUG   Driver URL: https://chromedriver.storage.googleapis.com/108.0.5359.71/chromedriver_win32.zip
DEBUG   starting new connection: https://chromedriver.storage.googleapis.com/
DEBUG   Resuming session
DEBUG   Using ciphersuite TLS13_AES_256_GCM_SHA384
DEBUG   Resuming using PSK
DEBUG   TLS1.3 encrypted extensions: []
DEBUG   ALPN protocol is None
DEBUG   Ticket saved
DEBUG   File extracted to C:\Users\<user>\.cache\selenium\chromedriver\win32\108.0.5359.71\chromedriver.exe (12358144 bytes)
INFO    C:\Users\<user>\.cache\selenium\chromedriver\win32\108.0.5359.71\chromedriver.exe

C:\Users\<user>\Downloads>

**Comment by bonigarcia** [comment] 2022-12-20 13:35
Great, thanks a lot, @vicozohili. It seems the new change fixes the issue.

I have just created a PR about it (#11449). It will be available for the next version of Selenium.

**Comment by vicozohili** [comment] 2022-12-20 14:10
@bonigarcia Great thanks. Will look out for the next version.

**Comment by santhosh0419** [comment] 2023-01-23 19:02
Is this issue fixed? I still see it reproducible with 4.7.2 version. 

WARNING: Unable to obtain driver using Selenium Manager: Unsuccessful command executed: [C:\Users\username\AppData\Local\Temp\selenium-manager56723551864420016803617694157295156\selenium-manager.exe, --driver, chromedriver]
WARN	Sending fatal alert BadCertificate
ERROR	error sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE_108): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

My code is running behind company VPN

**Comment by bonigarcia** [comment] 2023-01-23 20:40
@santhosh0419 Please try with Selenium 4.8.0, released today.

**Comment by santhosh0419** [comment] 2023-01-24 08:21
@bonigarcia Thanks for pointing to it. Its working with Selenium 4.8.0.

**Comment by diemol** [comment] 2023-01-24 08:39
Thanks for confirming, @santhosh0419.

**Comment by santhosh0419** [comment] 2023-01-24 08:42
@SeleniumHQ team, I would like to know any plans to mark Selenium Manager the stable version (to my knowledge there are no active issues, you can correct me). We do use the latest version in many of our projects, but to push it to few of the projects client needs stable version.
Thank you.

**Comment by vicozohili** [comment] 2023-01-24 13:24
I think this was closed too quickly.
The issue still exists with selenium 4.8.0

Jan 24, 2023 1:14:37 PM org.openqa.selenium.remote.service.DriverService findExecutable
WARNING: Unable to obtain driver using Selenium Manager: Unsuccessful command executed: [C:\Users\<user>\AppData\Local\Temp\selenium-manager177642339278600389374573545870465\selenium-manager.exe, --driver, chromedriver]
WARN	Sending fatal alert BadCertificate
ERROR	error sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE_109): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: driver.version: unknown

**Comment by diemol** [comment] 2023-01-24 13:26
It was closed because we got feedback, but if it is still happening, we can reopen.

**Comment by jorisdas** [comment] 2023-01-24 13:32
The issue is still reproducible with selenium grid 4.8.0

**Comment by titusfortner** [comment] 2023-01-24 16:11
There are some bug fixes in latest Selenium Manager code (in trunk), but the Selenium Manager binaries checked into trunk / released with 4.8 are the same one that were released with 4.7. So, unfortunately, you'll need to wait for 4.9 at this point. 

> any plans to mark Selenium Manager the stable version

fwiw, this shouldn't matter to the end-user.

Right now Selenium Manager is completely transparent to the end user. It is only used in the case that the code would otherwise fail. It is "opt-in" because users just need to remove driver manager references / delete direct references / remove driver from PATH to use it.

I'm not sure we'll refer to it as a "production release" until we can reasonably make it the default and require users to "opt-out." That likely means implementing automatic browser downloads as well, which will be a while. Potentially this might coincide with a Selenium 5 release, depending on what all we decide to do for that.

**Comment by farhansyaah** [comment] 2023-02-11 19:41
i have any issue like this in selenium 4.8.0

`Feb 12, 2023 2:35:45 AM org.openqa.selenium.remote.service.DriverService findExecutable
WARNING: Unable to obtain driver using Selenium Manager: Unsuccessful command executed: [C:\Users\User\AppData\Local\Temp\selenium-manager14832897572053007174880647792501858\selenium-manager.exe, --driver, chromedriver]
ERROR	error sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE_110): error trying to connect: An existing connection was forcibly closed by the remote host. (os error 10054)

Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: driver.version: ChromeDriver
Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://chromedriver.chromium.org/. The latest version can be downloaded from https://chromedriver.chromium.org/downloads
	at org.openqa.selenium.internal.Require$StateChecker.nonNull(Require.java:314)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:149)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:42)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:315)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:456)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:147)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:50)
	at introduction.Seleniumintro.main(Seleniumintro.java:11)
![issue2](https://user-images.githubusercontent.com/49035748/218278006-1231d74a-ebda-4f06-8953-15099a00a214.PNG)
`

any advice to fix this guys ?

**Comment by aerfalwl** [comment] 2023-02-15 02:01
I have any issue like this in selenium 4.8.0, but I sove it in the following way.

The issue occured mainly because you could not connet the Internet, for example, you are in a local network which could not connect the Internet but only some local services.

To solve it, you can install the browser webdriver, let's use the chrome as an example, you can also refers [this:](https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/#4-hard-coded-location) 

1. Clear cache in C:/Users/yourusername/.cache/selenium
2. Download the webdriver, refers [this](https://chromedriver.chromium.org/downloads);
3. Use the webdriver in this way:
    ```python
   from selenium.webdriver.chrome.service import Service
   from selenium import webdriver

   service = Service(executable_path="/path/to/chromedriver.exe")
   driver = webdriver.Chrome(service=service)
    ```

**Comment by diemol** [comment] 2023-02-17 23:13
A new release has been done including a newer version of Selenium Manager. If this is still happening after trying 4.8.1 or higher, please let us know and we will be happy to reopen.

**Closed as completed by diemol** 2023-02-17 23:13 UTC
Labels: I-defect, C-rust

**Comment by patilpratikn** [comment] 2023-03-09 16:12
Hello Team, 

I am facing this issue tried with 4.6.0, 4.7.1, 4.8.0, 4.8.1 all these versions. Also tried with steps mentioned above and still it is same.

Mar 09, 2023 9:37:37 PM org.openqa.selenium.remote.service.DriverService findExecutable
WARNING: Unable to obtain driver using Selenium Manager: Unsuccessful command executed: [C:\Users\PRATIK~1.PAT\AppData\Local\Temp\selenium-manager463476442275007050614320311602215\selenium-manager.exe, --driver, chromedriver]
WARN	Sending fatal alert BadCertificate
ERROR	error sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE_111): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.12'
Driver info: driver.version: ChromeDriver

java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://chromedriver.chromium.org/. The latest version can be downloaded from https://chromedriver.chromium.org/downloads

**Comment by titusfortner** [comment] 2023-03-10 17:34
@patilpratikn can you download the latest version from here https://github.com/SeleniumHQ/selenium/blob/trunk/common/manager/windows/selenium-manager.exe

and run:
```
selenium-manager.exe --browser chrome --debug --clear-cache
```

**Comment by patilpratikn** [comment] 2023-03-13 13:05
Thank you @titusfortner above step resolved issue.
