### ISSUE TITLE
Python: Proxy connection doesn't work

### ISSUE THREAD

**Issue by saitam1** [SeleniumHQ/selenium#7351] opened 2019-07-02 16:56 UTC
## 🐛 Bug Report

I can't connect using proxies via Selenium Firefox WebDriver.

## To Reproduce
There are two ways to connect to a proxy server, none of them work.

1.
```
profile = webdriver.FirefoxProfile()
profile.set_preference('network.proxy.type', 1)
profile.set_preference('network.proxy.http', '93.41.248.119')
profile.set_preference('network.proxy.http_port', 8080)
profile.update_preferences()
#binary = FirefoxBinary('/home/johnjackson/code/scraping/spotify/geckodriver')
browser = webdriver.Firefox(firefox_profile=profile)
browser.get("http://whatismyipaddress.com")
```

2.
```
proxy_to_use= "93.41.248.119:8080"
desired_capability = webdriver.DesiredCapabilities.FIREFOX
desired_capability['proxy'] = {
    'proxyType': "manual",
    'httpProxy': proxy_to_use
        }
browser = webdriver.Firefox(capabilities=desired_capability)
browser.get("http://whatismyipaddress.com")
```
## Expected behavior

Show proxy IP address

## Environment

OS: Ubuntu 19.04
Browser: Firefox
Browser version: 67.0.4 (64-bit)
Browser Driver version: 0.24.0
Language Bindings version: Python 3.7.3
Selenium Grid version (if applicable):

**Comment by cgoldberg** [comment] 2019-07-04 19:41
> Language Bindings version: **Python 3.7.3**

please update to the latest version and try to reproduce.

**Comment by traverseda** [comment] 2019-07-05 21:58
This is working for me

``
        profile.set_preference("network.proxy.type", 1)
        profile.set_preference("network.proxy.http", 'localhost')
        profile.set_preference("network.proxy.http_port", self.port)
        profile.set_preference("network.proxy.ssl", 'localhost')
        profile.set_preference("network.proxy.ssl_port", self.port)
        profile.update_preferences()
``

Under Mozilla Firefox 67.0.4

OS: Arch Linux
Browser: Firefox
Browser version:  Mozilla Firefox 67.0.4
Browser Driver version:  Mozilla Firefox 67.0.4
Language Bindings version: python selenium 3.141.0

**Comment by traverseda** [comment] 2019-07-05 21:59
> > Language Bindings version: **Python 3.7.3**
> 
> please update to the latest version and try to reproduce.

That is the latest version of python.

**Comment by diemol** [comment] 2019-07-06 16:47
Closing as the community provided a solution, thanks @traverseda 

Also, what was meant by "please update to the latest version and try to reproduce", was to use https://pypi.org/project/selenium/3.141.0/, since this was not clear in the initial report.

**Closed by diemol** 2019-07-06 16:47 UTC
