### ISSUE TITLE
Drag and drop does not work properly in chrome (remote within docker container and locally via chromedriver)

### ISSUE THREAD

**Issue by leoc** [SeleniumHQ/selenium#5429] opened 2018-02-02 11:28 UTC
## Meta -
OS:  Archlinux
Selenium Version:  ruby gem selenium-webdriver 3.9
Browser:  Chrome 
Browser Version:  Google Chrome 63.0.3239.132
Chromedriver version: ChromeDriver 2.33

Otherwise in Docker: latest `selenium/chrome-standalone-debug`

## Expected Behavior -

When I run:

```
driver.action.drag_and_drop(draggable, droppable).perform
```

It should move the mouse to the `droppable` element and release the mouse button. Then the two elements should switch order.

## Actual Behavior -

When I run:

```
driver.action.drag_and_drop(draggable, droppable).perform
```

The mouse is not moved. The Ghost for the element currently being dragged is at the position, where the mouse was before I ran the tests. Release is not working either.

(When I configure the VNC viewer to send pointer events, the dragging is still going on, following the mouse if I move into the vnc viewer window.)

## Steps to reproduce -

I wrote a script for reproduction here:

https://gist.github.com/leoc/1837a0d1066fba1fd5649dc9dd196f5b

I attached screenshots to the gist to show the situation before the `drag_and_drop` invocation and after. Unfortunately `scrot` does not capture the mouse pointer of my local system. But the situation is the same locally as it is within the docker container. The mouse is not moved, but `click and hold` seems to have been started dragging, thus chrome displays the dragged element at the position where the mouse was earlier, before the method invocation.

**Comment by p0deje** [comment] 2018-02-05 10:10
Thank you for a great issue and reproducible test case!

I can confirm this as not working, but it seems like ChromeDriver issue. Sending the following commands to it seems to be correct, but they don't execute correctly inside the browser:

```
2018-02-05 15:55:08 INFO Selenium -> POST session/4d8aa00aff181395796bfffd02305049/moveto
2018-02-05 15:55:08 INFO Selenium    >>> http://127.0.0.1:9515/session/4d8aa00aff181395796bfffd02305049/moveto | {"element":"0.9289266576263173-2"}
2018-02-05 15:55:08 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"34"}
2018-02-05 15:55:08 INFO Selenium <- {"sessionId":"4d8aa00aff181395796bfffd02305049","status":0,"value":null}
2018-02-05 15:55:08 INFO Selenium -> POST session/4d8aa00aff181395796bfffd02305049/buttondown
2018-02-05 15:55:08 INFO Selenium <- {"sessionId":"4d8aa00aff181395796bfffd02305049","status":0,"value":null}
2018-02-05 15:55:08 INFO Selenium -> POST session/4d8aa00aff181395796bfffd02305049/moveto
2018-02-05 15:55:08 INFO Selenium    >>> http://127.0.0.1:9515/session/4d8aa00aff181395796bfffd02305049/moveto | {"element":"0.9289266576263173-1"}
2018-02-05 15:55:08 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"34"}
2018-02-05 15:55:08 INFO Selenium <- {"sessionId":"4d8aa00aff181395796bfffd02305049","status":0,"value":null}
2018-02-05 15:55:08 INFO Selenium -> POST session/4d8aa00aff181395796bfffd02305049/moveto
2018-02-05 15:55:08 INFO Selenium    >>> http://127.0.0.1:9515/session/4d8aa00aff181395796bfffd02305049/moveto | {"element":"0.9289266576263173-1"}
2018-02-05 15:55:08 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"34"}
2018-02-05 15:55:08 INFO Selenium <- {"sessionId":"4d8aa00aff181395796bfffd02305049","status":0,"value":null}
2018-02-05 15:55:08 INFO Selenium -> POST session/4d8aa00aff181395796bfffd02305049/buttonup
dummy2018-02-05 15:55:08 INFO Selenium <- {"sessionId":"4d8aa00aff181395796bfffd02305049","status":0,"value":null}
```

I also tried to test this in Firefox, but it seems that the test case doesn't work there and I cannot drag&drop elements in Firefox.

In any event, this seems like ChromeDriver issue, so can you raise it to their [bug tracker](https://sites.google.com/a/chromium.org/chromedriver/help)? I'll keep this issue open for now in the event I'm wrong.

**Comment by Zap4ick** [comment] 2018-05-14 15:16
Is the problem solved? Can't find any related issue in chromedriver bugtracker, abut dragndrop doesn't work.

**Comment by gartenkralle** [comment] 2018-05-14 17:15
I tried with chromdriver 2.38 and chrome 66. Still **not working**...

**Comment by leoc** [comment] 2018-05-15 05:02
Sorry I haven't had the time to report a bug to chromedriver bugtracker.
I will see what I can do this week. Still not working ...

Thanks for your patience! :-)

----- original message -----

**Comment by Zap4ick** [comment] 2018-05-16 10:16
The strange thing dragndrop works here https://jqueryui.com/droppable/ :)

**Comment by vladdex** [comment] 2018-05-16 10:45
I think the main problem is related to this issue
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3604

**Comment by Zap4ick** [comment] 2018-05-16 13:00
Actually workaround from the link above works on test sites when dragndrop didn't worked.
But not in my case 'cause of functions tied to "drop" event :) Maybe it's another problem though. 
Still chromedriver doesn't dragndrop via actions.

**Comment by dreyks** [comment] 2018-06-08 11:34
ok so I think I know the reason for this [here](https://github.com/SeleniumHQ/selenium/blob/084ed59c7990ac810e2f614f66ee7610f8cc64df/rb/lib/selenium/webdriver/common/action_builder.rb#L322) we can see that drag_and_drop issues a `release(target)` and the release which in turn calls [up](https://github.com/SeleniumHQ/selenium/blob/084ed59c7990ac810e2f614f66ee7610f8cc64df/rb/lib/selenium/webdriver/common/mouse.rb#L51) has the `move_if_needed element`. And if the target element has already switched places with source - it just moves the mouse back

which actually can be seen on @p0deje log (two moveto's in a row)

the solution would be to change the drag_and_drop to either

```ruby
click_and_hold source
move_to        target
release
```

or
```ruby
click_and_hold source
release          target
```

**Comment by Kalyan1989** [comment] 2018-09-21 11:32
Any update on this issue, as I can reproduce it with Chrome driver version 2.42 released on 13 September.

**Comment by dreyks** [comment] 2018-09-21 11:45
i'm just using the monkeypatch
```rb
Selenium::WebDriver::ActionBuilder.class_eval do
  # selenium has a bug in drag_and_drop with moving elements
  #
  # @see https://github.com/SeleniumHQ/selenium/issues/5429
  def drag_and_drop(source, target)
    click_and_hold source
    move_to target
    release

    self
  end
end
```

**Comment by p0deje** [comment] 2018-09-22 02:42
@dreyks Thank you for investigating the issue and providing a workaround. I've applied your changes and all tests are passing, so I'm going to keep this change. Hopefully, it will resolve all the non-working drag&drops and won't break existing ones.

**Comment by p0deje** [comment] 2018-09-22 04:50
Fixed in dbe5d01c93b54958c3955b36f5166a3f704b74c1.

**Closed by p0deje** 2018-09-22 04:50 UTC
Labels: D-chrome, R-blocked on external

**Comment by yearnath** [comment] 2018-10-19 18:05
This still seems to be an issue on macOS with chromedriver 2.43 released October 17.

This is the workaround I've had to use (java):
```
new Actions(driver)
		.dragAndDropBy(element, -333, 1)
		.build().perform();
utils.driver.executeScript("alert('Focus window')");
utils.driver.switchTo().alert().accept();```

**Comment by p0deje** [comment] 2018-10-20 02:31
@yearnath Please provide a test case to reproduce the issue.
