### ISSUE TITLE
 Firefox 52 + Selenium 3.3.0 + WebDriver 0.15.0 cannot start

### ISSUE THREAD

**Issue by algot** [SeleniumHQ/selenium#3658] opened 2017-03-15 18:03 UTC
## Meta -
OS:  
Windows 10? OSX?
Selenium Version:  
3.3.0
Browser:  
Firefox
Browser Version:  
52.0 32-bit

## Expected Behavior -
Create FirefoxDriver instance
## Actual Behavior -
Test fails on 'new FirefoxDriver' step
## Steps to reproduce -
Install Visual Studio 2017.
Create new Console Application project in "C:\dev\Selenium\QaShahin\WebDriverFramework" folder.
Add following packages by nuget:
    Selenium.Firefox.WebDriver.0.15.0
    Selenium.Support.3.3.0
    Selenium.WebDriver.3.3.0
    Selenium.WebDriver.ChromeDriver.2.28.0
    Selenium.WebDriver.IEDriver.3.3.0
    Selenium.WebDriver.PhantomJS.Xplatform.2.45.0.1

Run the simplest code:

[http://pastebin.com/yB09c2Zn](http://pastebin.com/yB09c2Zn)

Error appears

'Cannot find a file named 'C:\dev\Selenium\QaShahin\WebDriverFramework\WebDriverFramework\bin\Debug\webdriver.json' or an embedded resource with the id 'WebDriver.FirefoxPreferences'. '

Geckodriver team mentioned that it's related to Selenium itself
[https://github.com/mozilla/geckodriver/issues/539](https://github.com/mozilla/geckodriver/issues/539)

**Comment by fimash** [comment] 2017-03-15 19:33
Fixed in 3.3.1. http://selenium-release.storage.googleapis.com/index.html?path=3.3/

**Comment by algot** [comment] 2017-03-15 19:44
@fimash As I can see .NET version still unavailable?
Am I right?

**Comment by Namita-Garg** [comment] 2017-03-29 16:55
Hi,

I am unable to setup selenium in my system..following are the details-

OS:Windows 10
Selenium Version:3.3.1
Gecko driver Version:v0.15.0
Browser:Firefox
Browser Version:52.0 
System_type:64-bit

Please help to setup the same.Thanks in advance

![code_file](https://cloud.githubusercontent.com/assets/26773236/24466442/7dfcc3e6-14ce-11e7-91b6-65afb5e9a4d6.png)
![console_output](https://cloud.githubusercontent.com/assets/26773236/24466438/7de4caf2-14ce-11e7-8aa0-fbb5e3678201.png)
![file_path](https://cloud.githubusercontent.com/assets/26773236/24466440/7de56d9a-14ce-11e7-9ed4-db2e35d23a13.png)
![firefox_browser_version](https://cloud.githubusercontent.com/assets/26773236/24466443/7e6e511e-14ce-11e7-89dd-72b641e07fd8.png)
![firefox_error](https://cloud.githubusercontent.com/assets/26773236/24466441/7de693d2-14ce-11e7-9bdc-fd75c2db90ba.png)
![system_properties](https://cloud.githubusercontent.com/assets/26773236/24466439/7de5240c-14ce-11e7-80ce-fa615eb8a6d6.png)

**Comment by jimevans** [comment] 2017-04-29 18:52
This is entirely unreproducible using the 3.4 release.

**Closed by jimevans** 2017-04-29 18:52 UTC
Labels: C-dotnet

**Comment by darakeon** [comment] 2017-07-30 01:48
I'm using 3.4 release...

**Comment by phenomenological** [comment] 2017-07-31 15:45
I am also receiving this error with the 3.4 release and Firefox 54.

**Comment by mgrybyk** [comment] 2017-08-15 14:48
Same issue, firefox 55.0.1 x64, marionette == false, firefox driver 3.4.0
simply doesn't work.

with marionette == true, it works, but who needs that? Marionette itself is absolutely unusable.

Working well with 52.3.0 ESR

**Comment by lmtierney** [comment] 2017-08-15 15:40
@mgrybyk how exactly is Marionette _**absolutely unusable**_? I'm sure Mozilla would like to know where their deficiencies are

**Comment by barancev** [comment] 2017-08-15 16:23
@mgrybyk Legacy Firefox driver does not support FF 55. Use FF ESR 52.
And don't hijack closed issues totally unrelated to your problem, please.

**Comment by mgrybyk** [comment] 2017-08-15 16:59
@barancev thanks for letting me know. It is hard to get information.

**Comment by mgrybyk** [comment] 2017-08-15 17:04
@lmtierney probably Mozilla should test it by themselves? 

Example: there is nothing you can do with drag'n'drop. There are many other annoying issues. This and other issues are showstoppers for me, that's why I said it is absolutely unusable. Yes it works, somehow/somewhat... maybe some happy path.

I'm pretty sure they know about it. Anyway, it is not a valid place to discuss it.
Thanks

**Comment by jimevans** [comment] 2017-08-16 11:52
@mgrybyk I generally avoid replying to comments like yours, but I'm genuinely interested. I'd like an enumerated list of your showstoppers with geckodriver. I'm genuinely curious, because drag-and-drop has been working in geckodriver for a few months now, and people claiming it's globally broken are likely working with outdated information. You're right, this probably isn't the place for it, but you can feel free to use any medium you like.

**Comment by mgrybyk** [comment] 2017-08-16 14:33
@jimevans not sure where is it working.
I'm using webdriver 3.4.0, geckodriver 0.18.0. Java. With such config it wasn't ever working and doesn't work right now.

**Comment by jimevans** [comment] 2017-08-16 15:29
@mgrybyk I'm using 3.5.1 of the .NET bindings, Java remote server 3.5, geckodriver 0.18.0, with Firefox 55 (current release channel as of this writing), and drag-and-drop work perfectly fine for me using the `RemoteWebDriver` class in the .NET bindings.

**Comment by mgrybyk** [comment] 2017-08-16 21:01
@jimevans 
I'll try 3.5.x once it will be available.
The latest I can use is 3.4.0 - https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java

**Comment by barancev** [comment] 2017-08-17 20:46
FYI: version 3.5.1 is available in maven central
