### ISSUE TITLE
Failed to connect to SafariDriver 

### ISSUE THREAD

**Issue by Elisena** [SeleniumHQ/selenium#1313] opened 2015-11-25 12:22 UTC
Hello,

I need some help. I use Selenium Grid v 2.48.2. I try to run my tests on Yosemate 10 with Safari 9.0.1 and receive this exception:  
" Failed to connect to SafariDriver after 10084 ms"

backtrace:
22:57:37.277 INFO - Launching a Selenium Grid node
Setting system property webdriver.Safari.driver to /users/admin/Downloads/selenium-master/build/javascript/safari-driver/SafariDriver.safariextension
22:57:53.393 INFO - Java: Oracle Corporation 25.60-b23
22:57:53.393 INFO - OS: Mac OS X 10.10.5 x86_64
22:57:53.641 INFO - v2.48.0, with Core v2.48.0. Built from revision 41bccdd
22:57:55.726 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
22:57:55.726 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
22:57:55.726 INFO - Driver class not found: com.opera.core.systems.OperaDriver
22:57:55.726 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
22:57:57.950 INFO - Version Jetty/5.1.x
22:57:57.957 INFO - Started HttpContext[/selenium-server,/selenium-server]
22:57:59.889 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@b59d31
22:57:59.889 INFO - Started HttpContext[/wd,/wd]
22:57:59.889 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
22:57:59.889 INFO - Started HttpContext[/,/]
22:57:59.961 INFO - Started SocketListener on 0.0.0.0:5555
22:57:59.961 INFO - Started org.openqa.jetty.jetty.Server@4f063c0a
22:57:59.962 INFO - Selenium Grid node is up and ready to register to the hub
22:58:01.825 INFO - Starting auto registration thread. Will try to register every 5000 ms.
22:58:01.825 INFO - Registering the node to the hub: http://myhubip:4444/grid/register
22:58:01.906 INFO - The node is registered to the hub and ready to use
Executing: [new session: Capabilities [{rotatable=false, nativeEvents=false, browserName=safari, takesScreenshot=true, javascriptEnabled=true, nonistall=true, version=, platform=ANY, cssSelectorsEnabled=true, timeoutInSeconds=30}]])
23:08:24.249 INFO - Creating a new session for Capabilities [{rotatable=false, nativeEvents=false, browserName=safari, takesScreenshot=true, javascriptEnabled=true, nonistall=true, version=, platform=ANY, cssSelectorsEnabled=true, timeoutInSeconds=30}]
23:08:32.116 INFO - Server started on port 49107
23:08:32.508 INFO - Launching Safari
23:08:32.707 INFO - Waiting for SafariDriver to connect
23:09:09.887 INFO - Shutting down
23:09:09.887 INFO - Stopping Safari
23:09:09.942 INFO - Stopping server
23:09:09.942 INFO - Stopping server
23:09:09.970 INFO - Shutdown complete
23:09:09.971 INFO - Shutting down
23:09:09.971 INFO - Stopping server
23:09:09.971 INFO - Shutdown complete
23:09:10.320 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'ip', ip: 'ip', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_60'
Driver info: driver.version: unknown
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
        at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
        at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
        at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:124)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:58)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
        at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:175)
        at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:202)
        at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:164)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:130)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
        at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
        at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
        at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
        at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
        at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
        at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
        at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
        at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
        at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
        at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
        at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'ip', ip: 'ip', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_60'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:113)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:97)
        at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:103)
        ... 9 more
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Failed to connect to SafariDriver after 10084 ms
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'ip', ip: 'ip', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_60'
Driver info: driver.version: SafariDriver
        at org.openqa.selenium.safari.SafariDriverCommandExecutor.start(SafariDriverCommandExecutor.java:121)
        at org.openqa.selenium.safari.SafariDriver.startClient(SafariDriver.java:76)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
        at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:62)
        at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:53)
        ... 14 more
23:09:10.326 WARN - Exception: Failed to connect to SafariDriver after 10084 ms
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'ip', ip: 'ip', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_60'
Driver info: driver.version: SafariDriver

safari:  
<img width="571" alt="kmqo9ax" src="https://cloud.githubusercontent.com/assets/16016245/11397087/d2f019f8-9387-11e5-883d-5011a905a49b.png">

For Safari 8 this exception is reproduced.
Could somebody helps me? Thank you.

**Comment by lukeis** [comment] 2015-11-25 18:48
duplicate of #1185

**Closed by lukeis** 2015-11-25 18:48 UTC

**Comment by vveliev** [comment] 2015-11-25 18:58
@lukeis , this is different issue ... as it failing to find extension. I have created #1315 
The issue is that extension is untrusted. I cannot install it to the Safari 9.0.1  , the only way is use developer extension builder , to build it from source. but it's only lasting for current safari run.

**Comment by titusfortner** [comment] 2015-11-25 20:18
Are you downloading the [latest Safari driver](http://www.seleniumhq.org/download/) and manually installing it? That one should be trusted.

**Comment by vveliev** [comment] 2015-11-25 20:29
Safari version 9.0.1 (10601.2.7.2) and C cannot install latest driver. It does ask if i want to trust it and nothing happen after. I do not see any plugins installed
My solution was to compile it from source.

**Comment by Elisena** [comment] 2015-11-26 05:30
@lukeis, this is different issue because in #1185 connection to Safari extension is succesed
@titusfortner, I try to do it but I have same issue as #1315. I compile it from source.

**Comment by NickTomlin** [comment] 2015-12-30 18:54
I am seeing this issue with OSX `10.10.05`, safari `9.0.2` and webdriver `2.48.2`. I can resolve it by manually installing the extension and then disabling/enabling the extension in safari preferences (at least temporarily).

Can we re-open this? I'm happy to help investigate if someone can give me pointers.

**Comment by anthonygreen** [comment] 2016-02-25 15:18
>  I am seeing this issue with OSX 10.10.05, safari 9.0.2 and webdriver 2.48.2. I can resolve it by manually installing the extension and then disabling/enabling the extension in safari preferences (at least temporarily).

As am I

**Comment by Mansik8** [comment] 2017-01-13 23:38
I am also facing the same issue with mac OS 10.12.2 (16C68) and Safari 10.0.2.

Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Failed to connect to SafariDriver after 10064 ms
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 's-MacBook-Pro.hsd1.ca.comcast.net', ip: '10.81.249.107', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.2', java.version: '1.8.0_65'
Driver info: driver.version: TestDriver
	at org.openqa.selenium.safari.SafariDriverCommandExecutor.start(SafariDriverCommandExecutor.java:121)
	at org.openqa.selenium.safari.SafariDriver.startClient(SafariDriver.java:76)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:62)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:42)
	at test.TestDriver.<init>(TestDriver.java:11)
	... 26 more

**Comment by joesanford** [comment] 2017-03-30 18:39
@Mansik8 I'd edit your message as it has your public IP address in it
