### ISSUE TITLE
Selenium Multiple Instances - Cannot start the driver service on http://localhost:port

### ISSUE THREAD

**Issue by BainsDev** [SeleniumHQ/selenium#8961] opened 2020-12-12 05:46 UTC
## 🐛 Bug Report

Attempting to launch multiple instances of Geckodriver or Chromedriver at once causes the following error:

```
OpenQA.Selenium.WebDriverException: Cannot start the driver service on http://localhost:55867/
       at OpenQA.Selenium.DriverService.Start()
       at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
       at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
       at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
       at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
```

## To Reproduce

```
class Program
    {
        static void Main(string[] args)
        {
            for (int i = 1; i <= 15; i++)
            {
                Task.Run(() => DriverStuff());
            }
            Console.ReadLine();
        }

        public static void DriverStuff()
        {
            FirefoxDriver driver = new FirefoxDriver();
            driver.Navigate().GoToUrl("https://www.bing.com");
        }
    }
```

Note: I found the "limit" of multiple instances at once varies based on what machine I test on. You may need to up the limit from 15 to 30 to reproduce.

While in practice i'm not launching 15 instances (i'm only launching 5 at once in Production via a scheduled task that starts a console application which makes 5 HTTP requests to a web service, which starts 5 selenium sessions), I'm still receiving this error on my Production server with only 5 instances.

Also note that this error only happens on my Production server 60% of the time or so, meaning most of the runs will fail because of this error, but other times i won't get this error and it will succeed.

## Expected behavior

Successful launch of all instances without error.

## Environment

OS: Windows 10, Windows Server 2016
Browser: Firefox, Chrome
Browser Driver version: GeckoDriver 0.28.0, ChromeDriver 87.0.4280.88

**Comment by pujagani** [comment] 2020-12-24 10:41
Thank you for providing the details. What Selenium version are you using?

**Comment by BainsDev** [comment] 2020-12-25 19:24
> 
> 
> Thank you for providing the details. What Selenium version are you using?

3.141.0

**Comment by diemol** [comment] 2020-12-25 23:34
@BainsDev, the error you see above is shown while waiting for the service to start. Which brings a few questions:

- Is that the complete script? Is there no  `driver.Quit()` in your code? 
- Is it reproducible 100% of the time? Or does it work a couple of times and then it start failing?
- What is the CPU/RAM available on the machine when that happens?
- Was this workiing before and it started failing recently? Or has it always failed?

My guess is that if no `Quit()` is called, the machine is running out of resources.

**Comment by BainsDev** [comment] 2020-12-25 23:38
@diemol 
1) That is the complete reproduceable script, however after each run I manually killed every running geckodriver and firefox instance. There's no Geckodriver / Firefox instance running in the background when I attempt to reproduce it.
2) It is reproduceable 100% of the time with my posted script, but the instance limit may vary depending on your machine.
3) I have a a Ryzen 7 2700x, I don't see any maxed out CPU / RAM usage when it occurs.
4) This has always been the case for me when trying to launch multiple instances at the same time.

**Comment by diemol** [comment] 2020-12-25 23:42
Is that the complete stacktrace or are there more details?
Also, what happens if you add the `driver.Quit()`? Does it get better? At least the manual tasks should be gone.

**Comment by BainsDev** [comment] 2020-12-25 23:46
> 
> 
> Is that the complete stacktrace or are there more details?
> Also, what happens if you add the `driver.Quit()`? Does it get better? At least the manual tasks should be gone.

Adding the driver.Quit() doesn't change anything. 

Are you able to reproduce the error on your end? If you can't try upping the iterations from 15 to 50.

Here's the additional stacktrace but it's not very helpful:

```  
   at OpenQA.Selenium.DriverService.Start()
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service, FirefoxOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxOptions options)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor()
   at WebDriverTests.Program.DriverStuff() in C:\Users\Administrator\source\repos\WebDriverTests\WebDriverTests\Program.cs:line 22
   at WebDriverTests.Program.<>c.<Main>b__0_0() in C:\Users\Administrator\source\repos\WebDriverTests\WebDriverTests\Program.cs:line 15
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by diemol** [comment] 2020-12-26 14:41
I went and tried the sample code with a few modifications:

```csharp
using System.Collections.Generic;
using System.Threading.Tasks;
using OpenQA.Selenium.Firefox;
using System;

namespace issue_8961
{
    class Program
    {
        static void Main(string[] args)
        {
            List<Task> tasks = new List<Task>();
            for (int i = 1; i <= 15; i++)
            {
                Task t = Task.Run(() => DriverStuff());
                tasks.Add(t);
            }
            Task.WaitAll(tasks.ToArray());
        }

        public static void DriverStuff()
        {
            FirefoxDriver driver = new FirefoxDriver();
            driver.Navigate().GoToUrl("https://www.bing.com");
            driver.Quit();
        }
    }
}

```

and I start to see the same when I get to 15 tasks. 

I went to check the C# bindings and I see that the message `Cannot start the driver service on...` happens when GeckoDriver does not respond after 2 seconds. Which totally makes sense, starting a GeckDriver and Firefox should not take longer than that.

However, in this scenario, the first tasks are getting created and system resources are getting used, to a point where it is not possible to have GeckoDriver ready in less than 2 seconds. For a stable test execution, normally a browser needs 1 CPU to be available (it could be less in some cases). Therefore, this comes to the point where the machine is simply responding slowly to the current load.

What we recommend for parallel execution is to use [Selenium Grid](https://www.selenium.dev/documentation/en/grid/), which for Selenium 4 is currently on a prerelease-beta-1 state (you could also use Grid 3 if you'd like). Grid 4 waits a bit longer for the browser to get started, and also takes into account the number of available cores to start tests.

A quick set of scripts, if you'd like to go the Grid way, can be seen here:
- Download the most recent prerelease from this [link](https://github.com/SeleniumHQ/docker-selenium/tree/beta-jars)
- Start the Grid with the following command: 
```shell
 java -jar selenium-server-4.0.0-prerelease-beta-1-1f4909f59c.jar standalone --relax-checks true
```
- Use the adjusted code snippet:
```csharp
using System.Collections.Generic;
using System.Threading.Tasks;
using OpenQA.Selenium.Remote;
using System;

namespace issue_8961
{
    class Program
    {
        static void Main(string[] args)
        {
            List<Task> tasks = new List<Task>();
            for (int i = 1; i <= 20; i++)
            {
                Task t = Task.Run(() => DriverStuff());
                tasks.Add(t);
            }
            Task.WaitAll(tasks.ToArray());
        }

        public static void DriverStuff()
        {
            Uri grid = new Uri("http://localhost:4444");
            RemoteWebDriver driver = new RemoteWebDriver(grid, new FirefoxOptions());
            driver.Navigate().GoToUrl("https://www.bing.com");
            driver.Quit();
        }
    }
}
``` 
With this setup, Grid handles the concurrency based on available resources, it should work better for you.

To wrap up, it seems you are bumping into the issue due to the 2 seconds timeout, which is reasonable for local testing, because GeckDriver cannot start faster, probably due to the current system resources. But for parallel testing, I'd recomment using Grid. 

Let me know if there is something else we can help with or if we could close this issue.

For more detailed troubleshooting, you can join our Slack/IRC channels, see the links here https://www.selenium.dev/support/

**Comment by BainsDev** [comment] 2020-12-26 17:27
@diemol Thanks for the detailed explanation. In my Production environment, I was actually getting this error while only trying to launch 5 instances at once, not even 15. Seems like spawning a new IIS worker process with IIS "idle timeout" enabled puts even more load on the system within that 2 second window.

When I turned off "idle timeout" in IIS, the issue went from occurring every run to once every 20 runs. 

Is there any way to override that 2 second timeout for the GeckoDriver? Otherwise Selenium Grid is definitely an option.

**Comment by diemol** [comment] 2021-01-07 17:01
I am not familiar with the "idle timeout" setting  in ISS, not sure how it can affect.

However, it does not seem that you can increase the timeout in the C# bindings. From my point of view, I think the setup you are looking for would benefit from using the Grid.

**Comment by diemol** [comment] 2021-01-07 17:04
Please let us know if there is something else we can help with, otherwise you can always drop by our Slack/IRC channel in case more questions arise. Links for the channels can be seen here https://www.selenium.dev/support/

**Closed as completed by diemol** 2021-01-07 17:04 UTC
Labels: J-awaiting answer, C-dotnet
