### ISSUE TITLE
chromedriver.exe is not killable in widows after calling driver.quit()

### ISSUE THREAD

**Issue by sureshkumar-skc** [SeleniumHQ/selenium#6474] opened 2018-10-03 06:33 UTC
## Meta -
OS:  
Windows 7
Selenium Version:  
2.37
Browser:  
Chrome version 69

Browser Version:  
69

## Expected Behavior -
driver.quit() should kill the chromedriver.exe 

## Actual Behavior -
driver.quit() is not killing the chromedriver.exe but it closes the browser.

## Steps to reproduce -

I am calling driver.quit() in all my script under finally block.

But still, after some periodic run I am able to see many chromedriver.exe is piled up on my task manager. Sometimes I am getting the exception when I call driver.quit() not always.
The error is 

> Error communicating with the remote browser. It may have died.

Whenever I get the above exception then, I am not able to end the process using task manager. I am not able to kill using taskkill command also.

If I kill using taskkill command(taskkill /F /IM chromedriver.exe) it says ERROR: The process "chromedriver.exe" with PID 4052 could not be terminated. Reason: There is no running instance of the task.

If I use taskkill /F /PID 4052 ERROR: The process with PID 4052 could not be terminated. Reason: There is no running instance of the task.

Still many chromedriver was listed under task manager

![taskkill not working](https://user-images.githubusercontent.com/12427607/46393778-4b2f7c80-c704-11e8-8017-b1f80c000e18.png)

**Comment by p0deje** [comment] 2018-10-03 06:56
What language do you use?

**Comment by sureshkumar-skc** [comment] 2018-10-03 07:31
@p0deje I use java.

**Comment by dewanprakash** [comment] 2018-10-03 09:19
We are facing identically same issue with 
Selenium v3.8.1
Chrome drvier v2.41.x
Chrome browser v69  
Windows 7

**Comment by barancev** [comment] 2018-10-03 09:33
I suppose it's a duplicate of #6317

**Closed by barancev** 2018-10-03 09:33 UTC
Labels: R-awaiting answer
