### ISSUE TITLE
 session cookie lost when click made to a link that opens a window with window.open()  

### ISSUE THREAD

**Issue by murty1982** [SeleniumHQ/selenium#1356] opened 2015-12-08 08:46 UTC
Hi There,

I am facing a problem when some IE window is opened before executing selenium script. Application is showing Login page if a link is being clicked with selenium which suspends a new window.
1. Open some IE window. (Does not even need to navigate anywhere, just a blank IE window)
2. Run test 
   -> During test, windows. Open creates a new window and no JSESSIONID is passed in the request 
   -> BASIC authentication popup appears in the new window

Thanks,
Murty

**Comment by murty1982** [comment] 2015-12-08 08:55
I learn form below url that this is an existing issue, if so any plans on the date of completion and availability of the fix.

https://github.com/SeleniumHQ/selenium/issues/1356

Thanks

**Comment by murty1982** [comment] 2015-12-10 19:12
Any Update on above issue please, it is a blocker for our project

**Comment by jimevans** [comment] 2015-12-10 20:32
This issue is due to a quirk of IE itself and how the driver creates the popup window for the browser. The workaround is to ensure there are no `iexplore.exe` processes running when you start the session with the driver. See [this MSDN blog post](https://blogs.msdn.microsoft.com/ie/2009/05/06/session-cookies-sessionstorage-and-ie8-or-how-can-i-log-into-two-webmail-accounts-at-the-same-time/) for a more technical discussion of the root cause.

**Comment by murty1982** [comment] 2015-12-11 18:31
Thanks for update. We have used ie11 with no merge option even though we are getting same issue.

**Comment by murty1982** [comment] 2015-12-11 18:35
The work around is good when we execute single browser instace we are trying to execute the tests in parallel and when we are launching 2browsers at same time we are getting the issue. We have used no merge option but no luck

**Comment by gallak87** [comment] 2016-08-29 19:15
I'm also experiencing this. The workaround of ensuring only 1 iexplore.exe process is running is NOT a solution for us.

**Comment by jimevans** [comment] 2016-11-17 04:04
I'm closing this issue as it's a browser issue, and not one that can easily be fixed in the driver.

**Closed by jimevans** 2016-11-17 04:04 UTC
Labels: D-IE

**Comment by LalitBohra1979** [comment] 2017-07-12 12:43
https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver

Required Configuration
•	The IEDriverServer exectuable must be downloaded and placed in your PATH.
•	On IE 7 or higher on Windows Vista or Windows 7, you must set the Protected Mode settings for each zone to be the same value. The value can be on or off, as long as it is the same for every zone. To set the Protected Mode settings, choose "Internet Options..." from the Tools menu, and click on the Security tab. For each zone, there will be a check box at the bottom of the tab labeled "Enable Protected Mode".
•	Additionally, "Enhanced Protected Mode" must be disabled for IE 10 and higher. This option is found in the Advanced tab of the Internet Options dialog.
•	The browser zoom level must be set to 100% so that the native mouse events can be set to the correct coordinates.
•	For IE 11 only, you will need to set a registry entry on the target computer so that the driver can maintain a connection to the instance of Internet Explorer it creates. For 32-bit Windows installations, the key you must examine in the registry editor is HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE. For 64-bit Windows installations, the key is HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE. Please note that the FEATURE_BFCACHE subkey may or may not be present, and should be created if it is not present. Important: Inside this key, create a DWORD value named iexplore.exe with the value of 0.
