### ISSUE TITLE
[🐛 Bug]: Selenium 4.0 (or one of its dependencies) breaks junit parallelism

### ISSUE THREAD

**Issue by cocorossello** [SeleniumHQ/selenium#9957] opened 2021-10-20 09:39 UTC
### What happened?

Take a look at:

https://github.com/cocorossello/junit-parallel-broken-when-using-selenium

It's basically a parallel test suite with 8 tests throttled to 2 threads that sleeps for 2 seconds, total execution time should be >= 8 seconds.

It works when no selenium is used at all. When I open a selenium window that throttling is broken.

So, I guess that selenium (or one of its dependencies... maybe asynchttpclient) must be doing something weird with the ForkJoinPool used by junit

### How can we reproduce the issue?

```shell
Check out the sample project and do a 
./gradlew test

It will fail.

Remove the line simulateOpenSelenium(); and it will work
```

### Relevant log output

```shell
Whithout selenium:

[INFO ] 2021-10-20 11:25:41.150 [ForkJoinPool-1-worker-3] ParallelTest - Starting all tests
[INFO ] 2021-10-20 11:25:41.162 [ForkJoinPool-1-worker-3] ParallelTest - Starting
[INFO ] 2021-10-20 11:25:41.162 [ForkJoinPool-1-worker-1] ParallelTest - Starting
[INFO ] 2021-10-20 11:25:43.174 [ForkJoinPool-1-worker-1] ParallelTest - Ending
[INFO ] 2021-10-20 11:25:43.174 [ForkJoinPool-1-worker-3] ParallelTest - Ending
[INFO ] 2021-10-20 11:25:43.177 [ForkJoinPool-1-worker-3] ParallelTest - Starting
[INFO ] 2021-10-20 11:25:43.178 [ForkJoinPool-1-worker-1] ParallelTest - Starting
[INFO ] 2021-10-20 11:25:45.187 [ForkJoinPool-1-worker-3] ParallelTest - Ending
[INFO ] 2021-10-20 11:25:45.187 [ForkJoinPool-1-worker-1] ParallelTest - Ending
[INFO ] 2021-10-20 11:25:45.188 [ForkJoinPool-1-worker-3] ParallelTest - Starting
[INFO ] 2021-10-20 11:25:45.188 [ForkJoinPool-1-worker-1] ParallelTest - Starting
[INFO ] 2021-10-20 11:25:47.202 [ForkJoinPool-1-worker-3] ParallelTest - Ending
[INFO ] 2021-10-20 11:25:47.202 [ForkJoinPool-1-worker-1] ParallelTest - Ending
[INFO ] 2021-10-20 11:25:47.203 [ForkJoinPool-1-worker-3] ParallelTest - Starting
[INFO ] 2021-10-20 11:25:47.203 [ForkJoinPool-1-worker-1] ParallelTest - Starting
[INFO ] 2021-10-20 11:25:49.204 [ForkJoinPool-1-worker-3] ParallelTest - Ending
[INFO ] 2021-10-20 11:25:49.216 [ForkJoinPool-1-worker-1] ParallelTest - Ending
[INFO ] 2021-10-20 11:25:49.217 [ForkJoinPool-1-worker-3] ParallelTest - Ending all tests
BUILD SUCCESSFUL in 9s
3 actionable tasks: 2 executed, 1 up-to-date
11:25:49: Task execution finished ':test --tests "org.example.ParallelTest"'.


With Selenium: 

[INFO ] 2021-10-20 11:38:57.831 [ForkJoinPool-1-worker-3] ParallelTest - Starting all tests
oct 20, 2021 11:38:57 A. M. org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFO: Using OpenTelemetry for tracing
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO ] 2021-10-20 11:38:58.782 [ForkJoinPool-1-worker-3] ParallelTest - Starting
[INFO ] 2021-10-20 11:38:58.782 [ForkJoinPool-1-worker-11] ParallelTest - Starting
[INFO ] 2021-10-20 11:38:58.782 [ForkJoinPool-1-worker-15] ParallelTest - Starting
[INFO ] 2021-10-20 11:38:58.782 [ForkJoinPool-1-worker-5] ParallelTest - Starting
[INFO ] 2021-10-20 11:38:58.782 [ForkJoinPool-1-worker-13] ParallelTest - Starting
[INFO ] 2021-10-20 11:38:58.782 [ForkJoinPool-1-worker-1] ParallelTest - Starting
[INFO ] 2021-10-20 11:38:58.782 [ForkJoinPool-1-worker-7] ParallelTest - Starting
[INFO ] 2021-10-20 11:38:58.790 [ForkJoinPool-1-worker-9] ParallelTest - Starting
[INFO ] 2021-10-20 11:39:00.783 [ForkJoinPool-1-worker-5] ParallelTest - Ending
[INFO ] 2021-10-20 11:39:00.784 [ForkJoinPool-1-worker-3] ParallelTest - Ending
[INFO ] 2021-10-20 11:39:00.785 [ForkJoinPool-1-worker-11] ParallelTest - Ending
[INFO ] 2021-10-20 11:39:00.785 [ForkJoinPool-1-worker-15] ParallelTest - Ending
[INFO ] 2021-10-20 11:39:00.790 [ForkJoinPool-1-worker-1] ParallelTest - Ending
[INFO ] 2021-10-20 11:39:00.790 [ForkJoinPool-1-worker-13] ParallelTest - Ending
[INFO ] 2021-10-20 11:39:00.790 [ForkJoinPool-1-worker-7] ParallelTest - Ending
[INFO ] 2021-10-20 11:39:00.793 [ForkJoinPool-1-worker-9] ParallelTest - Ending
[INFO ] 2021-10-20 11:39:00.793 [ForkJoinPool-1-worker-3] ParallelTest - Ending all tests

Parrallel execution should be throttled to 2 threads, throttling not working, took 2956 ms
java.lang.Exception: Parrallel execution should be throttled to 2 threads, throttling not working, took 2956 ms
	at org.example.ParallelTest.tearup(ParallelTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeAfterAllMethods$9(ClassTestDescriptor.java:387)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeAfterAllMethods$10(ClassTestDescriptor.java:386)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeAfterAllMethods(ClassTestDescriptor.java:386)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.after(ClassTestDescriptor.java:217)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.after(ClassTestDescriptor.java:74)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:119)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:119)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:169)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:113)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:169)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

ParallelTest > executionError FAILED
    java.lang.Exception at ParallelTest.java:36
```

### Operating System

doesn't matter

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

doesn't matter

### What are the browser driver(s) and version(s) where you see this issue?

doesn't matter

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment] 2021-10-20 13:11
This is a duplicate of #9359

You can see the conversation linked in the JUnit team's issue, and the required code to get it to work with Maven Surefire.

**Closed as completed by titusfortner** 2021-10-20 13:11 UTC
Labels: C-java, I-defect

**Comment by cocorossello** [comment] 2021-10-20 14:29
Thank you! I can confirm that the custom strategy works as expected

**Comment by cocorossello** [comment] 2021-10-20 15:03
I can work it out in the sample, however in my project I get the exception:

`    java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
        at java.base/java.util.concurrent.ForkJoinPool.tryCompensate(ForkJoinPool.java:1819)
        at java.base/java.util.concurrent.ForkJoinPool.compensatedBlock(ForkJoinPool.java:3446)
        at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3432)
        at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1939)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
        at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:66)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
        at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:119)
        at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
        at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:39)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:246)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:168)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:146)
`
I'm trying to isolate an example, but I have no idea on where to look, there must be something different... maybe another dependecy playing with that pool, I will open another issue if I can isolate a reproducible test
