### ISSUE TITLE
WebDriverJS - capabilities.merge does not merge child objects

### ISSUE THREAD

**Issue by juliemr** [SeleniumHQ/selenium#389] opened 2015-03-30 17:40 UTC
For example, if one capabilities object is
```js
chromeOptions: {
  args: '--foo'
}
```

and the other is 
```js
chromeOptions: {
  binary: '/path/to/chrome'
}
```

then `capabilities.merge` will override the entire `chromeOptions` object instead of combining into one with both properties.

I'm not sure if this is working as intended or not, but it's causing some unexpected effects when merging.

**Comment by lukeis** [comment] 2015-03-30 17:59
java does the same thing, it's not intended to be a "smart" merge. In java at least, it will always 'choose' the capabilities from the one passed into the argument  (cap1.merge(cap2); will choose cap2).

I'm going to close this as working as intended. If you feel strongly otherwise, please start a conversation about this on the [selenium-developers google group](https://groups.google.com/forum/#!forum/selenium-developers)

**Closed by lukeis** 2015-03-30 17:59 UTC
