### ISSUE TITLE
getting this error when trying to nav 

### ISSUE THREAD

**Issue by hcolonna** [SeleniumHQ/selenium#4835] opened 2017-10-09 20:12 UTC
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:  

## Steps to reproduce -

![image](https://user-images.githubusercontent.com/12549463/31356594-93f82d58-ad0c-11e7-8321-3c500c1a4b01.png)
![image](https://user-images.githubusercontent.com/12549463/31356602-9b850672-ad0c-11e7-8c75-ca474acded5c.png)

**Comment by hcolonna** [comment] 2017-10-09 20:13
getting this when ever I navigate . Also nothing records

**Comment by lmtierney** [comment] 2017-10-09 21:08
Duplicate of #4406

**Closed by lmtierney** 2017-10-09 21:08 UTC
