### ISSUE TITLE
Logs stopped working in ChromeDriver (c#)

### ISSUE THREAD

**Issue by alex-jitbit** [SeleniumHQ/selenium#7390] opened 2019-07-15 14:46 UTC
## 🐛 Bug Report

`driver.Manage().Logs.GetLog(LogType.Browser)` throws this exception now.

`System.NotImplementedException: unknown command: unknown command: session/f3cbd0a8ba58e1fe3e1e6d36dbdaf28e/se/logs`

OS: Windows 10
Browser: Chrome
Browser version: 75.0.3770.100
Browser Driver version: ChromeDriver 75.0.3770.140
Selenium.WebDriver: 4.0.0-alpha02

**Comment by seky16** [comment] 2019-07-29 14:45
As per [changelog](https://github.com/SeleniumHQ/selenium/blob/db9ce7fd52a6fea12be7121ff7cba1ab8d8d1771/dotnet/CHANGELOG#L19) I tried

> setting the UseSpecCompliantProtocol property of ChromeOptions to false

but it throws `OpenQA.Selenium.WebDriverException: invalid session id`.

Even tho `driver is ISupportsLogs` returns `true` (see [changelog](https://github.com/SeleniumHQ/selenium/blob/db9ce7fd52a6fea12be7121ff7cba1ab8d8d1771/dotnet/CHANGELOG#L24)) and `driver.Manage().Logs.AvailableLogTypes` returns both `browser` and `driver`, `driver.Manage().Logs.GetLog(logKind)` throws the mentioned `System.NotImplementedException` for both listed available types.

OS: Windows 10
Browser: Chrome
Browser version: 75.0.3770.142
Browser Driver version: ChromeDriver 75.0.3770.140
Selenium.WebDriver: 4.0.0-alpha02

**Comment by lmtierney** [comment] 2019-08-01 15:23
Please try this again with chrome 76

**Comment by ashiitaka** [comment] 2019-08-02 11:59
Got same issue 

System.NotImplementedException: 'unknown command: unknown command: session/35a408e6da14ce20d92c8ccb05e1d948/se/logs'

with 
WebDriver.Manage().Logs.GetLog(LogType.Browser);

OS: Windows 10
Browser: Chrome
Browser version:  76.0.3809.87
Browser Driver version: ChromeDriver 76.0.3809.68
Selenium.WebDriver: 4.0.0-alpha02

**Comment by alex-jitbit** [comment] 2019-08-02 14:46
@lmtierney me too, getting the same issue.

Chrome 76.0.3809.87
Chromedriver: 76.0.3809.68-beta

`System.NotImplementedException: unknown command: unknown command: session/a80253d342e550f398b1537cfafe9702/se/logs`

**Comment by Gironte** [comment] 2019-08-02 14:47
@lmtierney 
Got them issue too
`unknown command: unknown command: session/186a2f952d2c2e104136cee2f61bd0c7/se/logs`

my chrome driver settings:

` var chromeOptions = new ChromeOptions
		    {
		        PageLoadStrategy = PageLoadStrategy.Normal,
		    };
			chromeOptions.AddArgument("no-sandbox");
			
			if (enablePerformanceLogs)
			{
				var perfLogPrefs = new ChromiumPerformanceLoggingPreferences();
				perfLogPrefs.AddTracingCategories("devtools.network");

                chromeOptions.PerformanceLoggingPreferences = perfLogPrefs;
				chromeOptions.AddAdditionalOption(CapabilityType.EnableProfiling, true);
				chromeOptions.SetLoggingPreference("performance", LogLevel.Info);
`

**Comment by lmtierney** [comment] 2019-08-02 14:55
Are any of you going through the selenium-standalone or grid? I'm no C# expert so I may need some help from @jimevans

**Comment by lmtierney** [comment] 2019-08-02 15:01
I believe the issue is that the `GetLog` command should be a `PostCommand` but is currently a `GetCommand`

https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Remote/RemoteWebDriver.cs#L175

**Comment by Anusha-Srinivasan** [comment] 2019-08-04 23:58
> I believe the issue is that the `GetLog` command should be a `PostCommand` but is currently a `GetCommand`
> 
> https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Remote/RemoteWebDriver.cs#L175

Hi,

Is this being fixed please?

Thanks!

**Comment by JohnChen0** [comment] 2019-08-05 22:44
> I believe the issue is that the `GetLog` command should be a `PostCommand` but is currently a `GetCommand`
> 
> https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Remote/RemoteWebDriver.cs#L175

Also the URL of the command is different from what ChromeDriver expects. The expected URL is `"/session/{sessionId}/se/log"` (without the trailing `s`). (Note that the Java binding at https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/codec/w3c/W3CHttpCommandCodec.java#L158 uses the URL expected by ChromeDriver, so it would be easier to fix the discrepancy in the .NET binding instead of modifying ChromeDriver.)

**Comment by jimevans** [comment] 2019-08-06 01:12
It’s a mistake, y’all. I’ve been on holiday, and I’m very sick right now. Patience would be appreciated.

**Comment by szamacz** [comment] 2019-08-08 12:04
Please fix ASAP

**Comment by modernn** [comment] 2019-08-08 12:34
Dude, this is an open source project. Let's appreciate all the work that has been put into this and be respectful of the creators time. If it's too much of a problem you can figure out how to fix it and submit a pull request with the fix, hire someone to fix it, or just be patient.

**Comment by fedorc** [comment] 2019-08-08 19:08
facing same issue
@jimevans , get better soon

**Comment by jimevans** [comment] 2019-08-08 19:54
Resolved in #26d8b67. Thank you for your patience.

**Closed by jimevans** 2019-08-08 19:54 UTC
Labels: C-dotnet, D-chrome
