### ISSUE TITLE
WebElement.click does not work properly with goog.ui.Select

### ISSUE THREAD

**Issue by drobota** [SeleniumHQ/selenium#1856] opened 2016-03-21 23:22 UTC
## Meta

OS: Any
Selenium Version: 2.48 + (python)
Browser: Only firefox
Browser Version: 43,44,45 
## Expected Behavior

Menu item should be clicked
## Actual Behavior

Click passes however nothing element remains unselected 

Run my script and it will fail in combination of any firefox and selenium 2.48+ 
However it works in chrome, ie11 
Moreover if use selenium 2.47.3 or lower and  firefox it will work 

``` python
import unittest
import atexit
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By


TEXT = "Citizen Kane"


class TestGoogSelect(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        wd = webdriver.Firefox()
        atexit.register(wd.quit)
        wd.maximize_window()
        wd.get("https://google.github.io/closure-library/"
               "source/closure/goog/demos/select.html")
        cls.wd = wd

    def test_001(self):
        best_movie_select = self.wd.find_element_by_css_selector(
            "#select1 .goog-menu-button-caption")
        best_movie_select.click()
        menu_items = self.wd.find_elements_by_css_selector(
                                                ".goog-menuitem")
        for item in menu_items:
            if item.is_displayed() and item.text == TEXT:
                item.click()
                print "Item clicked"

        span = WebDriverWait(
                    self.wd, timeout=10).until(
                        EC.visibility_of_element_located(
                            (By.CSS_SELECTOR, "#value1")
                        )
        )

        self.assertIn(TEXT, span.text)


if __name__ == "__main__":
    unittest.main()
```

PS. I have this problem only during test execution when I try to repro this from python cli it always works

**Comment by titusfortner** [comment] 2016-03-22 00:06
Firefox clicking has been updated since 2.48, try with the latest version of Selenium - 2.53.

**Comment by drobota** [comment] 2016-03-22 00:17
@titusfortner I've tried lot's of times with different versions 
the last one which I used was 2.53.1

**Comment by p0deje** [comment] 2016-03-22 03:17
I'm pretty sure it is some timing issue (e.g. JS not yet initialized), because I can reproduce the problem using you test case locally, but if I add `import time; time.sleep(1)` before locating `best_movie_select` it starts to pass. I'm not sure how changes of Firefox click behavior that were introduced in 2.48 relate to this though.

Closing this as not a Selenium issue.

**Comment by drobota** [comment] 2016-03-22 04:26
@p0deje  That is definitely selenium issue because it works well in other browsers with different versions of selenium even selenium 2.47 works well with firefox. The problem appears only in selenium 2.48+ and only for Firefox

**Comment by p0deje** [comment] 2016-03-22 04:30
Different browsers have different implementations, some drivers/browsers might be faster that others, so it can lead to potential race condition (not saying that's exactly this case). Significant changes in Selenium 2.48 may also do.

> PS. I have this problem only during test execution when I try to repro this from python cli it always works

This also mans that you're hitting race condition.

**Comment by drobota** [comment] 2016-03-22 04:47
Using sleep not the best solution whenever in my cases it won't work 100% in all cases. I have tried out lots of different workaround and no one worked for me well. That is real pain in the ass as we heavily use this component.

**Comment by p0deje** [comment] 2016-03-22 04:56
I'm not suggesting to use sleep, I was just demonstrating that you are facing race condition, which has probably always been there but until 2.48 it was not a problem.

I understand that it's painful, but it has to be handled in client code, not Selenium. If you just want to make the code more reliable without going deeper and trying to understand what causes the issue, you can just click in the loop until select is opened.

**Comment by drobota** [comment] 2016-03-22 05:07
Select always opens and menu-item is being clicked the problem that these actions do not have any affect. I would still insist that it is selenium issue because there is a clear repro case which proves that problem  comes from selenium. Because when use firefox 41 and selenium 2.47.3 - test passes. However when update version to 2.48 test fails nevertheless with  chrome, safari or ie test passes despite on selenium version.

**Comment by p0deje** [comment] 2016-03-22 09:32
My bad, I now see that sometimes `goog.ui` doesn't see `action` event triggered or FirefoxDriver doesn't trigger it somehow, so I'm reopening this issue and will investigate more.

Sorry for misunderstanding!

**Comment by pumano** [comment] 2016-03-24 12:46
#1867 if you mean html select element problem checkout my workaround, maybe it helps you.

**Comment by drobota** [comment] 2016-03-24 17:52
this approach do work for me

**Comment by p0deje** [comment] 2016-03-25 07:05
For the record, I'm trying to nail down this issue and it looked like a bug in atoms, but the [test I have created](https://gist.github.com/p0deje/6e7e105c31da69419e5c) passes and works fine. Will keep debugging.

**Comment by p0deje** [comment] 2016-03-29 06:59
This is some really weird behavior which only happens when browser window is focused. Unfortunately, I still don't have that to tell you, but can you confirm the bug doesn't reproduce when different window is focused?

Also, Selenium is going to get rid of its own FirefoxDriver implementation in favor of [Marionette](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver). Can you try to use it instead (assuming you're already in Firefox 45)?

I will continue investigating the issue, but pretty sure it won't be resolved quick enough.

**Comment by drobota** [comment] 2016-03-29 07:07
@p0deje 
Thanks for your replay
I did try to run tests in `Mozilla Firefox 45.0` + selenium-2.53.1(python) and problem is still present

**Comment by p0deje** [comment] 2016-03-29 07:37
Were you running it using Marionette? It can be run both with and without it.

**Comment by drobota** [comment] 2016-03-29 18:25
No I did not however I did run my example and it works! Hope it will work further. Thanks

**Comment by p0deje** [comment] 2016-03-30 01:31
What do you mean "it works"? What have you done to make it work?
On Ср, 30 марта 2016 г. at 0:25, Dmitriy Robota <notifications@github.com>
wrote:

> No I did not however I did run my example and it works! Hope it will work
> further. Thanks
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/SeleniumHQ/selenium/issues/1856#issuecomment-203038351>
>
-- 
Alex

**Comment by drobota** [comment] 2016-03-30 02:01
I mean that test which  I provided works If I use marrionete

**Comment by p0deje** [comment] 2016-03-30 02:47
Cool. Would switching to Marionette in your test suite be a solution for you?

**Comment by drobota** [comment] 2016-03-30 04:16
I hope that it would work for me but it does not as marionette does not support all feature and it does not work stable for instance simple set_window_size does not work properly(https://github.com/jgraham/wires/issues/56)

**Comment by p0deje** [comment] 2016-03-30 04:18
Ok, I'll continue investigating the original issue.

Can you confirm that everything works fine when browser window is not
focused?
On Ср, 30 марта 2016 г. at 10:16, Dmitriy Robota <notifications@github.com>
wrote:

> I hope that it would work for me but it does not as marionette does not
> support all feature and it does not work stable for instance simple
> set_window_size does not work properly(jgraham/wires#56
> <https://github.com/jgraham/wires/issues/56>)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/SeleniumHQ/selenium/issues/1856#issuecomment-203238574>
>
-- 
Alex

**Comment by drobota** [comment] 2016-03-30 04:23
Thanks for you effort. 
Yeah. I can confirm this I think that is the reason why it does work when I test my code in cli.

**Comment by gabecase** [comment] 2016-04-08 04:32
We are experiencing the same issue issue on the ruby web driver version 2.48+ with goog.ui.Select elements remaining un-selected after a click. We also are able to get our tests to work only when running them locally and clicking outside of our browser to remove focus, this is a huge blocking issue for us as we cant upgrade web driver until we resolve this. Marionette lacking some of the features we need could be an issue as well.

**Comment by p0deje** [comment] 2016-04-08 04:33
@AutomatedTester Do you have any clue about what can be wrong with it?

**Comment by gabecase** [comment] 2016-04-08 13:44
Here is the issue reproduced:
I added a sleep and a hover before we click to show the element is supposed to be selected but after it is clicked you notice the value does not change
![](http://19aa15d9760e52e9d7a6-6bf9c89be6f9d48237983c051ac7f055.r89.cf1.rackcdn.com/wtfocus2.gif)

In web driver versions prior to 2.48 this would work with zero problems, no combination of additional waits and changing of selectors in the page object has worked, the only thing that has worked is clicking on a window outside of the browser to lose focus. I cant seem to find anything in the release notes for [2.48](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/rb/CHANGES) that indicates any of the click behavior has changed.

**Comment by p0deje** [comment] 2016-04-11 07:51
Click behavior has been significantly changed in 2.48 and now is mostly happening using Firefox internal APIs. So far I've debugged the issue and it looks like a problem in Firefox itself (or APIs that Selenium use), not the Selenium. I'm not that familiar and after chatting with @barancev we thought that the best you guys could do about this issue is switch to Marionette because current FirefoxDriver won't be supported once Firefox 44esr support is eneded. After that, we're probably going to remove FirefoxDriver from Selenium code and everyone should be prepared to use Marionette by that time.

I'm still willing to fix the issue, but I've hit the wall trying to debug it.

**Comment by barancev** [comment] 2019-04-17 20:39
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.

**Closed by barancev** 2019-04-17 20:39 UTC
Labels: D-firefox
