### ISSUE TITLE
The HTTP request to the remote WebDriver server for URL http://localhost:51197/session/../elements timed out after 60 seconds.

### ISSUE THREAD

**Issue by AutomatorNew** [SeleniumHQ/selenium#6283] opened 2018-08-14 22:00 UTC
## Meta -
OS:  

Selenium Version:  

Browser:  

Code Base:
.Net471,C#,Specflow

My code was working fine till lately. Only change I had recently is an update to Windows 10.
SUT has no changes. Following is the error I am getting trying to find webtable elements.
Message: OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:51197/session/9b01b266-9990-46e6-9557-66b2762d4011/element/6ad00a15-b5cd-49af-ae97-d3a128ca9151/elements timed out after 60 seconds.
---- System.Net.WebException : The request was aborted: The operation has timed out.

case BrowserType.InternetExplorer:
                    InternetExplorerOptions options = new InternetExplorerOptions();
                    options.IgnoreZoomLevel = true;
                    options.EnsureCleanSession = true;                  
                    options.EnableNativeEvents = true;
                    options.EnablePersistentHover = true;                
                    options.RequireWindowFocus = false;
                    options.BrowserAttachTimeout = TimeSpan.FromSeconds(120);

                     DriverContext.Driver = new InternetExplorerDriver(options);
                     DriverContext.Driver.Manage().Timeouts().AsynchronousJavaScript = TimeSpan.FromSeconds(120);                    
                    DriverContext.Driver.Manage().Timeouts().PageLoad = TimeSpan.FromSeconds(120);
                    DriverContext.Driver.Manage().Timeouts().ImplicitWait= TimeSpan.FromSeconds(120);
                    DriverContext.Browser = new Browser(DriverContext.Driver);
                    DriverContext.Driver.Manage().Window.Maximize();
.................
--------------------
 public static void  NavigateToURL(string url)
        {
            DriverContext.Browser = new Browser(DriverContext.Driver);
            DriverContext.Browser.GoToUrl(url);
            LogHandler.Logger.Debug("Url :" + url);          
        }
---------------------
//Get all the columns from the table
            var columns = table.FindElements(By.TagName("th"));
            //Get all the rows
            var rows = table.FindElements(By.TagName("tr"));
            //Create row index
            int rowIndex = 0;
            bool rowFound = false;

            foreach (var row in rows)
            {
                int colIndex = 0;

                var colDatas = row.FindElements(By.TagName("td"));  //**Here is where it times out
                               if (colDatas.Count != 0)
                    foreach (var colValue in colDatas)
                    {...}

------------------------
In above code , when it tries to find "td" elements, I am getting time out saying The HTTP request to the remote WebDriver server for URL http://localhost:51197/session/9b01b266-999....../elements timed out after 60 seconds. I tried to add webdriver wait loop for this elements more than 60 seconds, but that too is not working.
Can somebody please help me out?

**Comment by AutomatorNew** [comment] 2018-08-14 22:02
OS:  
 Windows 10 
Selenium Version:  
 Selenium.WebDriver.IEDriver 3.11, Selenium.Webdriver 3.11Browser:  
 Internet Explorer 11.547.16299.0CO 
Code Base:
.Net471,C#,Specflow

**Comment by Flipbed** [comment] 2018-08-15 08:58
Having a similar issue.
.Net C# here as well.
Works fine on Windows 10 OEM but on out Windows Server 2008 R2 Enterprise build server it fails.

I was able to pinpoint the issue to the following:
If we get the webDriver.Url before doing webDriver.TakeScreenshot() we get the HTTP request timeout exception (60 second timeout).

We use the chrome driver. 

Selenium.WebDriver 3.12.1
Selenium.Support 3.12.1
Selenium.WebDriver.ChromeDriver 2.40.0
Selenium.WebDriver.MicrosoftDriver 17.17134.0

**Comment by lmtierney** [comment] 2018-08-15 12:49
This is because the default timeout for HTTP requests is 60. If your page takes longer to load than 60 seconds, then a timeout will occur. You need to increase the command timeout in the driver constructor. Examples:

https://github.com/SeleniumHQ/selenium/blob/0b310c111486897cc7c711855ee9dc9005fc2dc3/dotnet/src/webdriver/Remote/RemoteWebDriver.cs#L128
https://github.com/SeleniumHQ/selenium/blob/9f126d3a700d36693229e1267334a9c07a35c97a/dotnet/src/webdriver/Chrome/ChromeDriver.cs#L124

**Comment by AutomatorNew** [comment] 2018-08-16 19:06
Also noticed when loading url (Driver.Url =url)on windows 10 & windows 2016 servers with IE 11, it takes 60 seconds to complete it. This is not happening on windows 8 & IE11. All these are related? Some one please help me...
I tried to upgrade selenium and IEdriver (version 3.14) and added "/options.PageLoadStrategy = PageLoadStrategy.None" to achieve faster loading of URL, but it makes the tests flaky. If I use any other Pageloadstartegy, url wont get loaded at all.

**Comment by lmtierney** [comment] 2018-08-16 19:57
This would have nothing to do with Selenium or IEDriver but rather IE itself and the web page you are attempting to view

**Comment by AutomatorNew** [comment] 2018-08-16 20:33
There is no issue loading manually the webpage. It happens only when I run automation. That too started after installing one of the windows update.

**Comment by lmtierney** [comment] 2018-08-16 21:06
Closing as this is environment related (windows update). Please open a new issue if you have a reproducible case otherwise.

**Closed by lmtierney** 2018-08-16 21:06 UTC
Labels: C-dotnet, R-awaiting answer

**Comment by jepperaskdk** [comment] 2019-08-15 11:17
Seing this error on Ubuntu 18.04, after having run tests a couple of times. I think this should be reopened.

**Comment by pavlexander** [comment] 2019-08-17 11:54
Seeing this issue on home Linux server. All works fine on Windows machine.
I guess is that this is related to RAM consumption/swap space or something hardware related.

The Linux environment has been working fine for me with < 1-5 tabs opened in Chrome. Now I have faced a situation that Chrome instance needs to have 10 tabs opened and the issue appeared. 

@AutomatorNew try running tests on a higher spec PC.

I am also willing to know how I can optimize chromedriver/chrome to work with 5+ tabs simultaneously.

**Comment by kotprav** [comment] 2019-08-28 13:40
Hello, we see the same issue for several monthes.

We use Windows Server 2016 Datacenter. 
IE11 - 11.3143.14393.0, update versions 11.0.140
IE Driver server - 3.141.0.0
c# project.
