### ISSUE TITLE
Using get_attribute("value") will cause a data type error bug

### ISSUE THREAD

**Issue by iwqian** [SeleniumHQ/selenium#8724] opened 2020-09-22 17:10 UTC
## 🐛 Bug Report

Using get_attribute("value") will cause a data type error bug.

When the string in the value value starts with a number, the data type will be recognized as int, resulting in the truncation of letters and subsequent strings. When len is used to obtain the length of the string, an error is reported:
TypeError("object of type 'int' has no len()")

Code ：

```python

'''
Use Language：Python 3.8.3
Chrome Version：版本 85.0.4183.102（正式版本） （64 位）
'''

# HTML Tag:
<li  value="4b273a33fbbd29013nN93dy4F1A~" class="cur"></li>

# Python Code:
logger.info(e_li.get_attribute("value"))
logger.info(len(e_li.get_attribute("value")))
logger.info(e_li.get_property("value"))           
logger.info(len(e_li.get_property("value")))

#Console Log:
[2020-09-23 01:05:54] [INFO] 4
[2020-09-23 01:05:54] [INFO] 1
[2020-09-23 01:05:54] [INFO] 4
[2020-09-23 01:05:54] [INFO] TypeError("object of type 'int' has no len()")
```

![image](https://user-images.githubusercontent.com/16589026/93914578-50df5c00-fd39-11ea-9a18-3201d7438134.png)

**Comment by diemol** [comment] 2020-09-28 20:44
@wangqian0628 what language bindings were used to get this behavior? What browser version, etc... Most of the issue template was deleted. 
Please take into account that without this information and a reproduction scenario we cannot check if this is a bug or not.

**Comment by iwqian** [comment] 2020-09-30 05:38
Use Language：Python 3.8.3
Chrome Version：版本 85.0.4183.102（正式版本） （64 位）

**Comment by iwqian** [comment] 2020-10-09 01:25
This bug is real and has a great impact on the program. I hope to speed up the processing. Thank you!

**Comment by AutomatedTester** [comment] 2020-10-09 06:49
One of things that you deleted from the template was asking for a minimal page that reproduces the issue as well as a minimal selenium script.

I’m sure the issue is there but the template is there for a reason, it would have saved 3 comments so far.

**Comment by AutomatedTester** [comment] 2020-11-26 14:51
I've had a look at this issue and it appears to be an issue with the way that drivers process the response. I have checked and all drivers work this way so will need to write a web platform test to fix this

**Comment by iwqian** [comment] 2020-11-26 15:10
Thank you very much，I hope you can solve this bug as soon as possible.

**Comment by iwqian** [comment] 2020-11-26 15:11
Thank you very much，I hope you can solve this bug as soon as possible.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SeleniumHQ/selenium"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月26日(星期四) 晚上10:51
收件人:&nbsp;"SeleniumHQ/selenium"<selenium@noreply.github.com&gt;;
抄送:&nbsp;"王骞"<wangqian0628@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [SeleniumHQ/selenium] Using get_attribute("value") will cause a data type error bug (#8724)





 
I've had a look at this issue and it appears to be an issue with the way that drivers process the response. I have checked and all drivers work this way so will need to write a web platform test to fix this

**Comment by AutomatedTester** [comment] 2021-04-27 14:13
I have submitted 2 new tests to wpt under https://github.com/web-platform-tests/wpt/pull/28715. Since this is a driver issue I am closing

**Closed as completed by AutomatedTester** 2021-04-27 14:13 UTC
Labels: C-py
