### ISSUE TITLE
Cannot specify browser version in DesiredCapabilities

### ISSUE THREAD

**Issue by schmidtkp** [SeleniumHQ/selenium#3942] opened 2017-04-28 16:27 UTC
## Meta -
OS:  OSX
Selenium Version:  3.4.0 (Java bindings)
Browser:  Firefox 
Browser Version: 53.0 
GeckoDriver Version: 0.16.1
 
## Expected Behavior -
Should be able to create a new session, via FirefoxDriver(DesiredCapabilities) or RemoteWebDriver(URLAddress, DesiredCapabilities), with a specific browser version specified in the DesiredCapabilities.
## Actual Behavior -
org.openqa.selenium.WebDriverException: Unrecognized channel: 53.0
## Steps to reproduce -
DesiredCapabilities desiredCapabilities = DesiredCapabilities.firefox();
desiredCapabilities.setVersion("53.0");
FirefoxDriver firefoxDriver = new FirefoxDriver(desiredCapabilities);

--or -- 

RemoteWebDriver remoteWebDriver = new RemoteWebDriver(hubUrl, desiredCapabilities);

**Comment by dordnung** [comment] 2017-05-03 11:42
I have exactly the same problem, see here: https://github.com/SeleniumHQ/selenium/issues/3941

**Comment by p0deje** [comment] 2017-06-08 04:37
Duplicate of #3941

**Closed by p0deje** 2017-06-08 04:37 UTC
