### ISSUE TITLE
Webdriver automatically clears Text entered in TextBox

### ISSUE THREAD

**Issue by Anbuchozhan** [SeleniumHQ/selenium#4785] opened 2017-09-29 11:16 UTC
**Browser: IE/Firefox
Web Application Design - Dojo Toolkit Based Application**

Issue: With selenium sendText or through Java script i can able enter the text in text box which is present in Dynamic widget. Once i submit the page the **entered text get automatically clears**, since whatever changes happened in text box is not know by UI. I have tried with many options(listed below) to resolve this issue, but nothing worked out.
1. SendText
2. Java script
3. Click the text Box before send text/java script
4. Click some where outside of text box after sending text
 I have found the temporary solution of 'Robot class' to pass the value to text box. But this will not be a perfect solution since robot class has few limitations.
**Observation of Issue:** Whatever changes happened is not getting updated in UI so while submitting the page that entered text get vanished. But entering text through manual stork or Robot class works fine.

Can anyone face this kind of issue? Please provide suggestions/comments on the above issue.

**Comment by barancev** [comment] 2017-09-29 11:16
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by Anbuchozhan** [comment] 2017-09-29 11:27
Scenario - Have to check functionality(which i should not reveal) of web application. So coming to the point the functionality of scenario doesn't matter, to check the functionality i have to fill specific details in drop downs, date fields & few texts box-in that only the text boxes present in Widget is clears the text entered while submitting the page(click the submit button to get the results) . Due to text gets cleared automatically the results leads to failed since that text field is mandatory.

**Error:** No error is thrown on part of this issue, i debug the execution while submitting the entered text gets cleared out.

Expectation result - Text entered in that field should not cleared automatically.

locator which i have used to identify the web element - './/*[@class='dijitStackContainerChildWrapper dijitVisible']//*[contains(@class,'test')]//*[@class='DetailsContainer']/div[1]/div[@class='dgrid-scroller']/div[1]/div["+i+"]/table/tr/td[5]/input[@type='text'][@class='dgrid-input']'

**I can locate the element & able to send the text.**

**Comment by luke-hill** [comment] 2017-09-29 11:42
@Anbuchozhan A Reproducible test case should include as the bear minimum
- Website / Application that can be consumed by a neutral person (Read committer)
- Step by step instructions of what needs to be pre-installed (If anything)
- Full code (ideally), that can be just copied and pasted
- Steps to reproduce

As well as this you should include your environment. Read the link pasted by @barancev for more info

**Comment by Anbuchozhan** [comment] 2017-09-29 13:01
Below is my code: Text get reflected only if use the Robot class. In the below code i have commented robot class keys

 LOS = GetSet.getDriver().findElements(By.xpath(".//*[@class='dijitStackContainerChildWrapper dijitVisible']//*[contains(@class,'testPrice dijitStackContainer')]//*[@class='stayDetailsContainer']/div[1]/div[@class='dgrid-scroller']/div[1]/div")).size();
		    
		  
		    loop:
		    for(int i = 1;i <= LOS; i++){
		    	
		    	WebElement Rooms = GetSet.getDriver().findElement(By.xpath(".//*[@class='dijitStackContainerChildWrapper dijitVisible']//*[contains(@class,'testPrice dijitStackContainer')]//*[@class='stayDetailsContainer']/div[1]/div[@class='dgrid-scroller']/div[1]/div["+i+"]/table/tr/td[5]/input[@type='text'][@class='dgrid-input']"));
		    	
		    			
		    	Rooms.click();
		    	Rooms.clear();
		    	
		    Rooms.sendText(value);
		 	  /* Robot r = new Robot();
		   
		    	r.keyPress(KeyEvent.VK_3);
		    	r.keyPress(KeyEvent.VK_0);
		    	r.keyPress(KeyEvent.VK_ENTER);
		    	r.keyRelease(KeyEvent.VK_ENTER);*/
		    	
		    	System.out.println("ValueEntereAfter"+Rooms.getAttribute("value"));
		    
		    	//jse.executeScript("arguments[0].value.change()", Rooms);
		    	
		    	//Actions act=new Actions(GetSet.getDriver());
		    //	act.moveToElement(GetRecommendationBtn_TestPricePage).click();
		    	
		    	//((JavascriptExecutor) GetSet.getDriver()).executeScript( "$(arguments[0]).change(); return true;" , Rooms);
		    //	GetSet.getDriver().findElement(By.xpath(".//*[@class='dijitStackContainerChildWrapper dijitVisible']//*[contains(@class,'testPrice dijitStackContainer')]/*[@class='exploreOptions']//*[@class='modifyOptionsStepIcon']")).click();
		    	
		    	
		    	
		    	//GetSet.getDriver().findElement(By.xpath(".//*[@class='arrivalDateForm']/*[contains(text(),'Update')]")).click();
		    	
		    	System.out.println("ValueEntereAfterChangeEvent"+Rooms.getAttribute("value"));
		    	
		    	/*myExecutor.executeScript("arguments[1].value = arguments[0];",value, Rooms);
		    	Actions act = new Actions(GetSet.getDriver());
		    	act.click();*/
		    	 //setAttributeValue(Rooms,StayDetailsRoom);
		    	Thread.sleep(2000);
		    	
		    	
		    	
		    	
		    	
		    	
		   
		    	
		    	
		    	//Rooms.sendKeys(""+value);
		    	//break loop;
		    }

**Comment by barancev** [comment] 2017-09-29 13:11
And what's the page to run this scenario on?

**Comment by lmtierney** [comment] 2017-09-29 13:11
This isn't Selenium at fault, this is the fault of the browser and the framework. One suggestion would be to trigger a change on the element by executing javascript. Something along the lines of:

```
var evt = document.createEvent('HTMLEvents');
evt.initEvent('change', false, true);
dojo.query(\"<your selector here>\").dispatchEvent(evt);
```

**Comment by Anbuchozhan** [comment] 2017-10-01 03:24
In my observation its not framework fault. 
@imtierney
How could i use the above code in my java project. I tried to use that but it's not responding.

I need to inform the browser that change is happened in text box. 
Can please you share me the exact code for that's ?
Thank you

**Comment by lmtierney** [comment] 2017-10-01 04:00
That is javascript, you would use the `JavascriptExecutor`. I do not have exact code for it. I'm closing this as you cannot give us a reproducible test case.

**Comment by lmtierney** [comment] 2017-10-01 04:01
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by lmtierney** [comment] 2017-10-01 04:34
Sorry, thought I was in a different issue. Please provide a reproducible scenario

**Comment by Anbuchozhan** [comment] 2017-10-02 03:03
First i would like to Thanks for spending time to resolve this issue.
Actually i have used Java script executor to inform the UI on change is happened but this itself throwing Java script executor Error. Below is that Java script:

(JavascriptExecutor) GetSet.getDriver()).executeScript( "$(arguments[0]).change(); return true;" , Rooms);

1 . WebDriver can identify the Text box

2. WebDriver can pass the value through SendText to the Correct Textbox

3. But the entered text get erased once i give the submit Button

4. Dojo based Application - Text Box present in Dynamic Widget

5. Works fine with Robot Class & below is the Code  for that

WebElement Rooms = GetSet.getDriver().findElement(By.xpath(".//*[@class='dijitStackContainerChildWrapper dijitVisible']//*[contains(@class,'testPrice dijitStackContainer')]//*[@class='stayDetailsContainer']/div[1]/div[@class='dgrid-scroller']/div[1]/div["+i+"]/table/tr/td[5]/input[@type='text'][@class='dgrid-input']"));
	    	
	    			
	    	Rooms.click();
	    	Rooms.clear();
	    Rooms.sendText(value);
	 	  Robot r = new Robot();
	    	r.keyPress(KeyEvent.VK_3);
	    	r.keyPress(KeyEvent.VK_0);
	    	r.keyPress(KeyEvent.VK_ENTER);
	    	r.keyRelease(KeyEvent.VK_ENTER);

6 . Also works fine in manual interaction

7 . So my observation is application or UI comes to know the value only during manual keystrokes or from Robot keys (Which more or less similar to Manual keystrokes) but through sendtext the value is not getting informed to UI/Application

8. It might be application Issue/Selenium can't handle such text boxes

I have provided the detailed scenario of my issue. Also i have provided the code which i have used in this comments chain.

Please provide me the solution or suggestion.

**Comment by barancev** [comment] 2017-10-10 18:36
Selenium is supported by community.
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Closed by barancev** 2017-10-10 18:36 UTC
Labels: R-awaiting answer

**Comment by npsullia** [comment] 2018-10-27 02:00
So, we dont have a resolution yet?  per my onsevervation, if you execute a java script in this code, and again run the same commands ( sendkeyc()) this may work

**Comment by npsullia** [comment] 2018-10-27 02:07
This might be causing due to a JS involved in this textbox for validating the contents sent to this box. Double check the source
