### ISSUE TITLE
ruby: ChromeOptions: setting camera permission no longer works in 3.142.7

### ISSUE THREAD

**Issue by jstefek** [SeleniumHQ/selenium#7896] opened 2019-12-29 16:18 UTC
## 🐛 Bug Report
With ruby selenium-webdriver `3.142.7` I cannot set camera permission with ChromeOptions. Worked in older versions, e.g. `3.142.6`

## Test script or set of commands reproducing this issue
Install `watir` gem and run the below code. With  selenium-webdriver `3.142.7 it should fail on timeout.

Used gems:
gem 'watir', '6.16.5'
gem 'selenium-webdriver', '3.142.7'

```
require 'watir'

options = Selenium::WebDriver::Chrome::Options.new
options.add_preference(:profile, {default_content_setting_values: {media_stream_camera: 1}})
br = Watir::Browser.new(Selenium::WebDriver.for(:chrome, options: options))

br.goto('https://webrtc.github.io/samples/src/content/getusermedia/resolution/')
br.wait
br.button(id: 'qvga').click
# this will time-out in 3.142.7 and leave the browser opened, because the camera permission was not set
br.video(id: 'gum-res-local').wait_until(timeout: 10, message: 'the video element should be present', &:present?)
br.close
```
## Environment

OS :Linux 4.18.19-100.fc27.x86_64 GNU/Linux
Browser: Chrome
Browser version: 79.0.3945.79 
Browser Driver version: ChromeDriver 79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945)
Language Bindings version: ruby 2.6.5p114,  selenium-webdriver 3.142.7

**Comment by jstefek** [comment] 2020-03-03 08:50
@p0deje @connorshea

**Comment by p0deje** [comment] 2020-03-03 12:07
As a workaround, please use strings instead of symbols for keys:

```ruby
options.add_preference(:profile, {'default_content_setting_values' => {'media_stream_camera' => 1}})
```

Duplicate of #7917

**Closed by p0deje** 2020-03-03 12:07 UTC
Labels: needs-triaging
