### ISSUE TITLE
[🚀 Feature]: Python Service class Properties

### ISSUE THREAD

**Issue by gauravgandhi1315** [SeleniumHQ/selenium#13391] opened 2024-01-03 19:33 UTC
### Feature and motivation

Python Driver Services can only have parameters set in the constructor

### Usage example

service = webdriver.ChromeService()
service.service_args = ['--log', 'debug']

**Comment by iampopovich** [comment] 2024-06-12 18:07
@titusfortner it seems like a duplicate of https://github.com/SeleniumHQ/selenium/issues/12760

**Comment by titusfortner** [comment] 2024-06-13 15:25
huh, and it uses the same wording and examples... weird. Thanks for pointing it out.

**Closed as not planned by titusfortner** 2024-06-13 15:25 UTC
Labels: C-py, I-enhancement, R-help wanted
