### ISSUE TITLE
IE11: UnreachableBrowserException: Error communicating with the remote browser. It may have died.

### ISSUE THREAD

**Issue by LucasException** [SeleniumHQ/selenium#4929] opened 2017-10-23 14:05 UTC
## Meta -
OS:  Windows 10 Enterprise
Selenium Version:  3.6.0 WebDriver
Browser:  Internet Explorer 11
Browser Version:  11.953.14393.0 (32-bit) 

## Information -

I face kinda the same issue as mentioned [here](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/4319).

However, this problem occurres with Internet Explorer 11.
It happens randomly in approximately 1 out of 10 test runs. Restarting this failed test run usually leads to the repeated test passing.
I already tried the solutions mentioned in the issue linked above, but none of them worked so far. The InternetExplorerDriver is initialized with default values.

Unfortunately, my company's rules do not allow me to publish our test code.
What I can say so far is that the exception mostly occurres when calling the webdriver's .get(String url) method, so there is no complex code behind this.

Do you know why the webdriver loses the connection to the browser irregularly and how I can resolve this issue?

Thanks in advance!

**Comment by luke-hill** [comment] 2017-10-24 07:59
IE is the flakiest of all the modern browsers (Chrome / FF). And there are a few different blog posts by jimevans (One of the contributors here), that explains why (`send_keys` being slower e.t.c.)

Whilst not a contributor, I would let you know that you'll need "some" form of SSCCE for them to even consider looking into this, as if they can't reproduce this it's hard for them to act on it.

You mention you can't share test code. Can you create a new page/html/source files that they can use?

**Comment by LucasException** [comment] 2017-10-24 11:21
That's what I realized as well... Chrome and Firefox tests are running fantastically and the Internet Explorer test fails randomly from time to time and is therefore not reliable enough.
I circumvent the sendkeys problem by using Java robot, which I already have to use for mouse simulation because of the "Browser Focus" problem, that is mentioned in the wiki.

I tried to reproduce the error with a simple website, but unfortunately I did not succeed. As a reason of this, I think that my problem is most probably caused by some timing issues, but I cannot find the exact cause of it for now. ._.


Is there any way to force the internet explorer to open links in tabs instead of windows? I know that there is no difference between those two methods in theory, but I have to run my tests in fullscreen mode (for further image comparison of the taken screenshots) and handling another window instead of "just" a tab seems to be more error-prone (in respect to the timing).

**Comment by smrtyviks** [comment] 2017-11-25 20:17
I am also facing the same issue with Firefox browser.Here is the error i am getting:

org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'DK005898', ip: '10.128.2.1', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_151'
Driver info: driver.version: RemoteWebDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=45.0.2, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 7abcb33c-9c4b-4bdb-996c-25d93e2e30f6
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:701)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:526)
	at FirewallTest.quitDriver(FirewallTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:731)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 88; received: 0
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:180)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:200)
	at org.apache.http.impl.io.ContentLengthInputStream.close(ContentLengthInputStream.java:103)
	at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:140)
	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:174)
	at org.apache.http.util.EntityUtils.consume(EntityUtils.java:88)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.createResponse(ApacheHttpClient.java:113)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:94)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.execute(NewProfileExtensionConnection.java:160)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.execute(FirefoxDriver.java:380)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 30 more

The issue occurs only when i am connected to my office network, but verified this with chromedriver and it works fine on office network as well. So not able to figure out what the root cause of the issue is.

Any help around this would be highly appreciated.

**Comment by cgoldberg** [comment] 2017-11-26 13:31
@smrtyviks,
your firewall is blocking the socket connection to the browser.

**Comment by smrtyviks** [comment] 2017-11-27 07:56
Hi Corey,

Thank you very much for uour response!!

What steps should be followed inorder to make that working?

Because i have tried with profile, desiredcapability, Registry entry etc.

Best Regards,
Vikrant Sarkaniya

**Comment by cgoldberg** [comment] 2017-11-27 15:02
> What steps should be followed inorder to make that working

for Firefox...
Selenium uses HTTP to communicate with geckodriver and it looks like this socket connection is getting blocked.  You likely need to disable your firewall or create a rule to allow access.  (Since you didn't paste the complete stacktrace, I can't be sure of the exact issue.  Your testcase is named " FirewallTest"...  but I really don't know what you are doing with regards to your firewall) 

btw, this sounds environment related and not an issue with Selenium

**Comment by smrtyviks** [comment] 2017-11-27 18:54
[Firewalltest.txt](https://github.com/SeleniumHQ/selenium/files/1507160/Firewalltest.txt)
Hi Corey,
I am attaching the sample script that i used to try some of the workarounds to overcome the issue.
one thing to notice is that the AppURL gives certificate error on Internet Explorer.

Also could you explain more about the Firewall rule that need to be created to resolve this issue?

Best Regards,
Vikrant.

**Comment by smrtyviks** [comment] 2017-11-29 12:02
Hi,

I tried stopping the Firewall Service on my machine but still gives me the same Error.
Also i am not able to understand how it works fine with Chrome Webdriver and fails with Firefox, If firewall is blocking the socket then why does it work with Chrome and also after stopping the service i face same issue.

please let me know if you have any clue about this issue, thanks in advance!

**Comment by p0deje** [comment] 2017-12-01 03:06
@smrtyviks You should consider upgrading if you want to use GeckoDriver - according to logs you're still on Selenium 2.53. If the issue persists, you need to open a new issue.

@LucasException At the moment, I don't see a way to work on this issue because there is no scenario to reproduce it. I'm going to close this, but I'll re-open once there is a way for us to reproduce this issue somehow.

**Closed by p0deje** 2017-12-01 03:06 UTC
Labels: D-IE
