### ISSUE TITLE
EventFiringWebDriver: does not wrap elements in executeScript result

### ISSUE THREAD

**Issue by mfulton26** [SeleniumHQ/selenium#3380] opened 2017-01-18 22:21 UTC
## Meta -
OS:  Windows 10

Selenium Version:  3.0.1

Browser:  n/a

Browser Version:  n/a

## Expected Behavior -

Executing a script (synchronous or asynchronous) that returns a `WebElement` or an object containing one or more `WebElement` instances should wrap those `WebElement` instances in `EventFiringWebElement` instances and return a result object containing it/them.

## Actual Behavior -

`executeScript` and `executeAsyncScript` pass their `result` object through without transforming `WebElement` instances to `EventFiringWebElement` instances.

## Steps to reproduce -

```kotlin
val result = eventFiringWebDriver.executeScript("return [document.head, document.body];")
result as List<*>
check(result.all { element ->
    element as WebElement
    element.javaClass.simpleName == "EventFiringWebElement"
})
```

**Comment by barancev** [comment] 2017-08-04 15:07
What language are you using? It looks like some JVM based language. We'd like to have a reproduction scenario in pure Java,

**Comment by mfulton26** [comment] 2017-08-04 15:30
The example is in Kotlin.

I believe that similar code in Java using Guava would be as follows:

```java
Object result = eventFiringWebDriver.executeScript("return [document.head, document.body];");
List<?> list = (List<?>) result;
Preconditions.checkState(list.stream()
        .allMatch(o -> o.getClass().getSimpleName().equals("EventFiringWebElement")));
```

**Comment by joshbruning** [comment] 2017-08-19 00:34
I've reopened this issue because the fix is incorrect. I can't put together a pull request at the moment (if no one else does in the next couple of days, I should be able to get to it).

The issue is that the proposed fix runs afoul of:
https://bugs.openjdk.java.net/browse/JDK-8148463

This makes Selenium Server choke on null values in objects. (selenium/java/server/src/org/openqa/selenium/remote/server/DefaultSession.java uses EventFiringWebDriver).

Here is a test case that should be added:

```
  @SuppressWarnings("unchecked")
  @Test
  public void testShouldBeAbleToExecuteSimpleJavascriptAndReturnAnObjectWithANullValue() {
    driver.get(pages.javascriptPage);

    Object result = executeScript("return {'key': null };");

    assertTrue("result was: " + result + " (" + result.getClass() + ")", result instanceof Map);
    Map<String, Object> map = (Map<String, Object>) result;
    assertNull(map.get("key"));
  }
```

Here is a fix to the map portion of wrapResult:

```
    if (result instanceof Map) {
      Set<Entry<String, Object>> entrySet = ((Map<String, Object>) result).entrySet();
      Map<String, Object> resultMap = new HashMap<>();
      for (Entry<String, Object> entry : entrySet) {
        resultMap.put(entry.getKey(), wrapResult(entry.getValue()));
      }
      return resultMap;
    }
```

**Closed** 2017-08-21 18:48 UTC
Labels: C-java
