### ISSUE TITLE
python GhostDriver fails in send_keys to GitHub signin

### ISSUE THREAD

**Issue by tlee5794** [SeleniumHQ/selenium#456] opened 2015-04-14 19:30 UTC
Trying to automate a GitHub login with PhantomJS 2.0 with the following python script snippet:

```
class GitHubLogIn(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.PhantomJS('./phantomjs/bin/phantomjs')
        self.driver.set_window_size(1000, 1000)
        self.driver.implicitly_wait(30)
        self.base_url = "https://github.com/"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_git_hub_log_in(self):
        driver = self.driver
        driver.get(self.base_url + "/")
        driver.find_element_by_link_text("Sign in").click()
        time.sleep(10)
        element = driver.find_element_by_id("login_field")
        element.click()
        element.clear()
        element.send_keys("username") 
```

The send_keys fails with:

```
======================================================================
ERROR: test_git_hub_log_in (__main__.GitHubLogIn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "scripts\Test4.py", line 72, in test_git_hub_log_in
    element.send_keys("username")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 318, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': typing})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 402, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 175, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 136, in check_response
    raise exception_class(value)
WebDriverException: Message: TypeError - undefined is not a constructor (evaluating '_getTagName(currWindow).toLowerCase()')
```

The send_keys works fine with the Chrome or the Firefox WebDriver. Any ideas how to get the send_keys above to work with GhostDriver or what the possible issue would be?

**Comment by barancev** [comment] 2015-04-14 19:37
A duplicate of https://github.com/detro/ghostdriver/issues/445

**Closed by barancev** 2015-04-14 19:37 UTC
