### ISSUE TITLE
Permission denied to access property "handleEvent"

### ISSUE THREAD

**Issue by XSchelin** [SeleniumHQ/selenium#1813] opened 2016-03-15 17:19 UTC
## Setup -
- Windows 7
- Firefox 45.0
- Python 2.7.10
## Expected Behavior -

The exported Python test case attempts to log into the Slack group.
## Actual Behavior -

Failure:

```
E
======================================================================
ERROR: test_why (__main__.TestWhy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\XScripts\WorkScripts\User Audit\testWhy.py", line 21, in test_why
    driver.find_element_by_id("email").clear()
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", l
ine 234, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", l
ine 712, in find_element
    {'using': by, 'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", l
ine 201, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py"
, line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Permission denied to access property "handleEvent"
Stacktrace:
    at <anonymous> (https://slack.slack.com//?redir=%2Fteam:434)

----------------------------------------------------------------------
Ran 1 test in 5.482s

FAILED (errors=1)
```
## Steps to reproduce -
- Open Firefox.
- Open Selenium for recording.
- Open any Slack login page. (For example: https://slack.slack.com/ )
- Enter any username and password.
- Click Submit.
- Export the test case to Python 2 / unittest / WebDriver.
- In a command prompt, run the test case.

**Comment by XSchelin** [comment] 2016-03-15 17:19
I note that this doesn't happen with other websites, so far. It appears to just be Slack.

**Comment by lukeis** [comment] 2016-10-26 19:59
also related to #2019

seems some javascript on the page is causing the issue.

**Comment by barancev** [comment] 2017-12-04 05:40
Duplicate of #2019

**Closed by barancev** 2017-12-04 05:40 UTC
Labels: D-atoms, D-firefox
