### ISSUE TITLE
process.env['PATH'] return undefined if the system environment key [PATH] is not strictly upcased

### ISSUE THREAD

**Issue by zzhengjian** [SeleniumHQ/selenium#5913] opened 2018-05-18 09:54 UTC
Hi, 

In below code, when my system environment key [PATH] is written as **Path**, it cause process.env['PATH'] to return undefined. Can someone please take a look?

exports.findInPath = function(file, opt_checkCwd) {
  let dirs = [];
  if (opt_checkCwd) {
    dirs.push(process.cwd());
  }
  dirs.push.apply(dirs, **process.env['PATH']**.split(path.delimiter));

  let foundInDir = dirs.find(dir => {
    let tmp = path.join(dir, file);
    try {
      let stats = fs.statSync(tmp);
      return stats.isFile() && !stats.isDirectory();
    } catch (ex) {
      return false;
    }
  });

  return foundInDir ? path.join(foundInDir, file) : null;
};

![image](https://user-images.githubusercontent.com/5183080/40228644-6c3b1ac6-5ac4-11e8-83c1-b661f47fcdf8.png)

![image](https://user-images.githubusercontent.com/5183080/40228694-8bfedfb4-5ac4-11e8-9e5b-795fdfaa2f6c.png)

https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/io/index.js

**Comment by zzhengjian** [comment] 2018-08-31 02:44
Hi, 

I can access with process.env.PATH and process.env['PATH'] with node command line,
![image](https://user-images.githubusercontent.com/5183080/44889901-95d76680-ad0a-11e8-88bd-b5a65f437d47.png)

But still gets failed when launch selenium-webdriver, can we make this case-insensitive?

**Comment by diemol** [comment] 2021-03-24 09:52
I cannot reproduce this, could you please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment] 2021-04-16 22:41
Closing this as we did not get more information, please feel free to open a new issue if the problem still persists after trying with the most recent versions.

**Closed by diemol** 2021-04-16 22:41 UTC
Labels: C-nodejs, R-awaiting answer
