### ISSUE TITLE
Selenium Version 3.6 causes Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones.

### ISSUE THREAD

**Issue by hnestorova** [SeleniumHQ/selenium#6634] opened 2018-11-08 17:08 UTC
## Meta -
OS:  
Windows 7 Professional
Selenium Version:  
3.6
Browser:  
Internet Explorer

Browser Version:  
11.0.9600.19002 (32-bit) -->

## Expected Behavior -
Tests will run successfully

## Actual Behavior -
Tests fail to run with the error below and all protected mode settins are the same across different zones. The problem is not present when I run the tests with version 3.5. What i see in the error is Driver info: driver.version: unknown maybe there we have some problem?

Caused by: org.openqa.selenium.SessionNotCreatedException: Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones.
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'PRIVATE', ip: 'PRIVATE', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_45'
Driver info: driver.version: unknown
remote stacktrace: 
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'PRIVATE', ip: 'PRIVATE', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_45'
Driver info: driver.version: unknown
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse$$Lambda$106/1129313041.apply(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.W3CHandshakeResponse$$Lambda$108/774200139.apply(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at org.openqa.selenium.remote.ProtocolHandshake$$Lambda$109/1110098350.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.server.ServicedSession$Factory.apply(ServicedSession.java:185)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$createSession$16(ActiveSessionFactory.java:171)
	at org.openqa.selenium.remote.server.ActiveSessionFactory$$Lambda$86/2020031778.apply(Unknown Source)
	at java.util.Optional.map(Unknown Source)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.createSession(ActiveSessionFactory.java:171)
	at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:72)
	at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:232)
	at org.openqa.selenium.remote.server.WebDriverServlet$$Lambda$59/1201588213.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by hnestorova** [comment] 2018-11-08 17:10
![1](https://user-images.githubusercontent.com/30794708/48214999-f37ed380-e389-11e8-907d-daf5c768063f.PNG)
![2](https://user-images.githubusercontent.com/30794708/48215000-f4176a00-e389-11e8-821b-ae768fcebc17.PNG)
![3](https://user-images.githubusercontent.com/30794708/48215001-f4176a00-e389-11e8-9acd-ef9866fcc8d6.PNG)
![4](https://user-images.githubusercontent.com/30794708/48215002-f4176a00-e389-11e8-80a5-239f93536c9d.PNG)

**Comment by cgoldberg** [comment] 2018-11-09 05:12
> all protected mode settins are the same across different zones

you must set all of them to the same level.  your screenshots show 3 *different* security mode settings (medium, medium-high, custom)

**Comment by hnestorova** [comment] 2018-11-09 07:46
I will try this but if you examine the thrown error, it says - "to the same
value (enabled or disabled)" . That's why I think i don't have problems
with version 3.5 or lower. If we should not only have them all
enabled/disabled but also on the same level (low/medium/high) then I think
the error message should be corrected.

На пт, 9.11.2018 г. в 7:12 ч. Corey Goldberg <notifications@github.com>
написа:

**Comment by barancev** [comment] 2018-11-09 07:58
Is there any reason to use outdated version 3.6? The latest version is 3.14, and many bugs were fixed since 3.6, may be this one is fixed too.

**Comment by barancev** [comment] 2018-11-09 07:58
Don't forget to upgrade IEDriverServer to the latest version too.

**Comment by hnestorova** [comment] 2018-11-09 08:20
@barancev yes, the reason is that this is the version since which the tests fail to run. For any version higher than 3.6 including it, I face the same problem. For versions 3.5 and lower I successfully run the tests

**Comment by jimevans** [comment] 2018-11-09 11:37
@hnestorova What code are you using to launch the IE driver? Also, the driver is doing nothing but a check of the registry to discover those settings, so it’s possible the driver is looking in the wrong place in the registry.

**Comment by hnestorova** [comment] 2018-11-09 12:58
@jimevans  here is some code sample:
DesiredCapabilities ieCapabilities = DesiredCapabilities.internetExplorer();
        ieCapabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
        ieCapabilities.setCapability(InternetExplorerDriver.REQUIRE_WINDOW_FOCUS, true);
        ieCapabilities.setCapability(InternetExplorerDriver.ENABLE_PERSISTENT_HOVERING, false);
        ieCapabilities.setCapability(CapabilityType.TAKES_SCREENSHOT, true);
        ieCapabilities.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
        ieCapabilities.setCapability(InternetExplorerDriver.ENABLE_ELEMENT_CACHE_CLEANUP, true);
[GRID-IE-DEBUG.txt](https://github.com/SeleniumHQ/selenium/files/2565901/GRID-IE-DEBUG.txt)


        for (int i = 0; i < 5; i++) {
            try {
                return new RemoteWebDriver(new URL(serverURL), ieCapabilities);
            } catch (Exception e) {
                e.printStackTrace();
                try{ Thread.sleep(30000);} catch (InterruptedException ie) {}
            }
        }

i tried @cgoldberg  suggestion to enable not only the protected mode on all time zones but also to set the same security level for those. The following exception below was thrown. I am also attaching the debug log. 
org.openqa.selenium.SessionNotCreatedException: Unable to create new service: InternetExplorerDriverService
Build info: version: '3.10.0', revision: '176b4a9', time: '2018-03-02T19:11:12.151Z'
System info: host: 'PRIVATE', ip: 'PRIVATE', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_45'
Driver info: driver.version: unknown
Command duration or timeout: 0 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:367)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:113)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
	at com.bravogroup.cognity.web.selenium.tests.BaseTest.createIEDriver(BaseTest.java:364)
	at com.bravogroup.cognity.web.selenium.tests.BaseTest.checkSixProxyState(BaseTest.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by hnestorova** [comment] 2018-11-14 13:54
@cgoldberg , @jimevans , @barancev , any suggestions/update?

**Comment by barancev** [comment] 2019-04-13 14:27
I want to reiterate that we don't accept reports against outdated versions (3.6 or 3.10). Use the latest available version.

According to the comment on 9 Nov 2018 you've resolved the original issue, so I'm going to close this report. If you have a different issue can can be reproduced with the latest IEDriverServer please open a new report.

**Closed by barancev** 2019-04-13 14:27 UTC
Labels: D-IE
