### ISSUE TITLE
cant load such file selenium/webdriver/phantomjs 

### ISSUE THREAD

**Issue by sampathmende** [SeleniumHQ/selenium#5516] opened 2018-02-21 04:47 UTC
I am using arachni1.4 gem  web scanner to scan web application. As part of its dependency it is downloading selenium-webdriver 3.8.0 from rebygems.org website. and when i ran the scanner it is throwing the below error. on windows machine 8.1 64 bit

cant load such file selenium/webdriver/phantomjs 
I checked the gem contents that phantomjs folder is missing but when i checked the source code github theat folder is there. pls tell me reason why it is missing from selenium-webdriver 3.8.0  gem downloaded from rubygems.org.
pls suggest any alternate i cant change gem file because i am not a owner of it. Is there any way to set the path of phantomjs??

**Comment by barancev** [comment] 2018-02-21 05:40
Duplicate of #5505

**Closed by barancev** 2018-02-21 05:40 UTC

**Comment by lmtierney** [comment] 2018-02-21 13:57
@sampathmende phantomjs support was removed from the gem. It is still in the codebase, but it does not get built into the gem.
