### ISSUE TITLE
"Command line server for the IE driver has stopped working" with IEDriverServer.exe since upgrade to 2.53.0.0

### ISSUE THREAD

**Issue by johnnyreilly** [SeleniumHQ/selenium#1973] opened 2016-04-15 08:44 UTC
## Meta -
OS: Windows Server 2008 R2 Standard 64 bit
Selenium Version: 2.53.0.0
Browser: IE
Browser Version: IE 11.0.9600.17801

## Expected Behavior -
Tests to run reliably on build server

## Actual Behavior -
Tests fail sporadically with "Command line server for the IE driver has stopped working"

## Steps to reproduce -
Migrate to 2.53.0.0
Use IEDriver - these are my packages:

```xml
  <package id="Selenium.Support" version="2.53.0" targetFramework="net452" />
  <package id="Selenium.WebDriver" version="2.53.0" targetFramework="net452" />
  <package id="Selenium.WebDriver.IEDriver" version="2.53.0.0" targetFramework="net452" />
```

![image](https://cloud.githubusercontent.com/assets/1010525/14556062/17dc65dc-02ee-11e6-9d38-da4860ad6999.png)

I'm going to try and rollback to using 2.50.1 (which I don't remember presenting this error)

**Comment by johnnyreilly** [comment] 2016-04-15 08:47
I was also have a dump file (55Mb) which I can share if useful.  Don't want to dump this on GitHub though - so get it contact and I'll hold onto it.

**Comment by jimevans** [comment] 2016-04-15 08:49
With no more information than this to go on, it's impossible to take any action on this issue report. Please provide code that causes the issue, along with an HTML page to test against, and/or a log file from IEDriverServer.exe from when the problem occurs.

**Comment by johnnyreilly** [comment] 2016-04-15 09:00
Hi @jimevans,

I'm afraid it's code that I'm not permitted to share :disappointed: 

I appreciate that doesn't help a great deal and that probably means you can't take any action.  But there's been no changes in the test pack apart from upgrading the packages and so it seems likely there is some kind of problem.  

Sorry I can't be more helpful but I'm afraid my hands are tied.  Thanks for Selenium by the way - it's great!

**Comment by johnnyreilly** [comment] 2016-04-15 09:46
Looks like the problem may be in `Selenium.WebDriver.IEDriver`.  I've just moved to these package versions:

```xml
  <package id="Selenium.Support" version="2.53.0" targetFramework="net452" />
  <package id="Selenium.WebDriver" version="2.53.0" targetFramework="net452" />
  <package id="Selenium.WebDriver.IEDriver" version="2.49.0.0" targetFramework="net452" />
```

And it's initially looking okay (no sign of that error so far).  Going to keep clear of 

```xml
<package id="Selenium.WebDriver.IEDriver" version="2.53.0.0" targetFramework="net452" />
```

for now.

**Comment by benzman81** [comment] 2016-06-30 15:36
Same happend to us today, but not reproducible. I wouldn't even have noticed it, but I was looking at that machine to see, why my test hung. And the error was shown.

**Comment by benzman81** [comment] 2016-07-02 08:42
The issue occurs since we updated webdriver from 2.48.2 to 2.53.0 and IEDriver from 2.48.0 to 2.53.1.
Yesterday, we downgraded from IEDriver 2.53.0 to 2.50.0 and the issue still occurs. Today we changed back to IEDriver 2.48.0. If the issue still exists using this IEDriver, it might be an issue of the webdriver as we did not have this issue with the old version of webdriver and IEDriver. I'll report back after the next build results.

**Comment by jimevans** [comment] 2016-07-02 12:55
I'm going to close this issue. A report saying "the IE driver executable crashed" with no indication of what WebDriver commands one is using, nor with any indication of the structure of the HTML page being automated is not actionable. The root cause of such a crash could be an innumerable number of things, and the absence of a repro case makes it impossible to even know where to start.

@johnnyreilly There's no need to share your **actual** code, which your higher-ups regrettably and erroneously put such a value on that they prevent you from getting the help you need to resolve issues. A simple set of HTML pages and simple WebDriver script are often all that's required to reproduce most issues, and while, yes, that takes time and effort, it's often not as hard as one might think.

Other commenters (@benzman81): Simply replying with the equivalent of "me, too" doesn't add anything to the investigation. There's no way to know if the root cause of your error is the same as or different from the original reporter's. What helps is a repro case. Other comments generally don't, and that includes adding them out of some misguided sense of obligation to "make it clear how serious the issue is because of how many people it affects."

Issue reports like this are taken seriously. Please keep in mind, however, that the Selenium development team is an unpaid volunteer organization, and those volunteers often have other obligations, leaving limited time for Selenium work. A lack of a quick repro case will naturally cause such issues to get less attention. Piling on with pleas to really notice how serious an issue will not increase that attention.

**Closed by jimevans** 2016-07-02 12:55 UTC

**Comment by dekelb** [comment] 2017-07-11 13:44
Having similar issue.
After several tests that pass IE11 just crash.

Selenium hub & node version = 3.4.0
IEDriverServer version = 3.4.0
IE Version = 11.0.9600.18697 Update version=11.0.43

    Files that help describe the problem:
        C:\...\Temp\WER55FB.tmp.WERInternalMetadata.xml
        C:\...\Temp\WER6049.tmp.appcompat.txt
        C:\...\Temp\WER6059.tmp.mdmp

Content of the WER6049.tmp.appcompat.txt:
```
<?xml version="1.0" encoding="UTF-16"?>
<DATABASE>
<EXE NAME="SYSTEM INFO" FILTER="CMI_FILTER_SYSTEM">
    <MATCHING_FILE NAME="kernel32.dll" SIZE="872448" CHECKSUM="0x3A0A495D" BIN_FILE_VERSION="6.1.7601.23775" BIN_PRODUCT_VERSION="6.1.7601.23775" PRODUCT_VERSION="6.1.7601.18015" FILE_DESCRIPTION="Windows NT BASE API Client DLL" COMPANY_NAME="Microsoft Corporation" PRODUCT_NAME="Microsoft® Windows® Operating System" FILE_VERSION="6.1.7601.18015 (win7sp1_gdr.121129-1432)" ORIGINAL_FILENAME="kernel32" INTERNAL_NAME="kernel32" LEGAL_COPYRIGHT="© Microsoft Corporation. All rights reserved." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x40004" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0xE0278" LINKER_VERSION="0x60001" UPTO_BIN_FILE_VERSION="6.1.7601.23775" UPTO_BIN_PRODUCT_VERSION="6.1.7601.23775" LINK_DATE="04/17/2017 15:15:06" UPTO_LINK_DATE="04/17/2017 15:15:06" EXPORT_NAME="KERNEL32.dll" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
    <MATCHING_FILE NAME="ntdll.dll" SIZE="1310528" CHECKSUM="0x9B7D4C81" BIN_FILE_VERSION="6.1.7601.23807" BIN_PRODUCT_VERSION="6.1.7601.23807" PRODUCT_VERSION="6.1.7600.16385" FILE_DESCRIPTION="NT Layer DLL" COMPANY_NAME="Microsoft Corporation" PRODUCT_NAME="Microsoft® Windows® Operating System" FILE_VERSION="6.1.7600.16385 (win7_rtm.090713-1255)" ORIGINAL_FILENAME="ntdll.dll.mui" INTERNAL_NAME="ntdll.dll" LEGAL_COPYRIGHT="© Microsoft Corporation. All rights reserved." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x40004" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x146322" LINKER_VERSION="0x60001" UPTO_BIN_FILE_VERSION="6.1.7601.23807" UPTO_BIN_PRODUCT_VERSION="6.1.7601.23807" LINK_DATE="05/12/2017 18:05:03" UPTO_LINK_DATE="05/12/2017 18:05:03" EXPORT_NAME="ntdll.dll" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
</EXE>
</DATABASE>
<EXE NAME="IED6528.tmp" FILTER="CMI_FILTER_THISFILEONLY">
    <MATCHING_FILE NAME="IED6528.tmp" SIZE="2463232" CHECKSUM="0xC1DF277E" MODULE_TYPE="WIN32" PE_CHECKSUM="0x0" LINKER_VERSION="0x0" LINK_DATE="04/21/2017 14:27:27" UPTO_LINK_DATE="04/21/2017 14:27:27" EXPORT_NAME="IEDRIVER.dll" EXE_WRAPPER="0x0" />
</EXE>
</DATABASE>
```

Content of WER55FB.tmp.WERInternalMetadata.xml:
```
<?xml version="1.0" encoding="UTF-16"?>
<WERReportMetadata>
	<OSVersionInformation>
		<WindowsNTVersion>6.1</WindowsNTVersion>
		<Build>7601 Service Pack 1</Build>
		<Product>(0x4): Windows 7 Enterprise</Product>
		<Edition>Enterprise</Edition>
		<BuildString>7601.23807.x86fre.win7sp1_ldr.170512-0600</BuildString>
		<Revision>1130</Revision>
		<Flavor>Multiprocessor Free</Flavor>
		<Architecture>X86</Architecture>
		<LCID>1033</LCID>
	</OSVersionInformation>
	<ParentProcessInformation>
		<ParentProcessId>2700</ParentProcessId>
		<ParentProcessPath>C:\ProgramData\Oracle\Java\javapath_target_1134657\java.exe</ParentProcessPath>
		<ParentProcessCmdLine>&quot;C:\ProgramData\Oracle\Java\javapath\java.exe&quot; -Dwebdriver.ie.driver=C:\Windows\System32\IEDriverServer.exe -jar selenium-server-standalone-3.4.0.jar -role node -hub http://HUBIP:4444/grid/register -browser &quot;browserName=internet explorer, version=11, platform=WINDOWS, maxInstances=1&quot;</ParentProcessCmdLine>
	</ParentProcessInformation>
	<ProblemSignatures>
		<EventType>APPCRASH</EventType>
		<Parameter0>IEDriverServer.exe</Parameter0>
		<Parameter1>3.4.0.0</Parameter1>
		<Parameter2>58fa16d4</Parameter2>
		<Parameter3>IED6528.tmp</Parameter3>
		<Parameter4>0.0.0.0</Parameter4>
		<Parameter5>58fa16cf</Parameter5>
		<Parameter6>c0000005</Parameter6>
		<Parameter7>00058856</Parameter7>
	</ProblemSignatures>
	<DynamicSignatures>
		<Parameter1>6.1.7601.2.1.0.256.4</Parameter1>
		<Parameter2>1033</Parameter2>
		<Parameter22>0a9e</Parameter22>
		<Parameter23>0a9e372d3b4ad19135b953a78882e789</Parameter23>
		<Parameter24>0a9e</Parameter24>
		<Parameter25>0a9e372d3b4ad19135b953a78882e789</Parameter25>
	</DynamicSignatures>
	<SystemInformation>
		<MID>9EAE4F63-9716-4A89-BE78-B4C56F114835</MID>
		<SystemManufacturer>VMware, Inc.</SystemManufacturer>
		<SystemProductName>VMware Virtual Platform</SystemProductName>
		<BIOSVersion>6.00</BIOSVersion>
	</SystemInformation>
</WERReportMetadata>
```

**Comment by dekelb** [comment] 2017-07-12 17:23
Following my comment above and the code in PR #4143 I can confirm that after applying the code in the that PR running tests in IE11 works as expected and there are no more crashes.

**Comment by abioneperhobby** [comment] 2017-10-19 09:30
@johnnyreilly take a look at https://github.com/SeleniumHQ/selenium/issues/4901

**Comment by nageshreddy** [comment] 2018-07-05 07:21
I had same issue in selenium box. After clearing all the IE* temp data in C:/ resolved the problem.
