### ISSUE TITLE
java.lang.IllegalAccessError: tried to access method com.google.common.util.concurrent.SimpleTimeLimiter.(Ljava/util/concurrent/ExecutorService;)V from class org.openqa.selenium.net.UrlChecker

### ISSUE THREAD

**Issue by cankush625** [SeleniumHQ/selenium#7807] opened 2019-11-23 06:17 UTC
## Last working Selenium version

Worked up to version: Not exactly known

Stopped working in version: 3.141.59

## Expected behavior

The chrome browser should be open.

## Actual behavior 

Throwing the above-mentioned error

## Issue I found

This can be fixed by downgrading to guava version 22.0
But if we upgrade to the later versions of guava then it throws the above-mentioned error

## Environment

OS: Windows 10
Browser: Chrome
Browser version: Version 78.0.3904.97 (Official Build) (64-bit)
Browser Driver version: Chromedriver 78.0.3904.105
Language Bindings version: Java 1.8
Selenium Grid version (if applicable): 3.141.59

**Comment by cankush625** [comment] 2019-11-23 06:23
I have found the solution to this issue. Just have to install the following dependencies

## This will fix the error for google gson
    `<dependency>
	    <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.5</version>
    </dependency>`

## This wil fix the error for google guava
	`<dependency>
	    <groupId>com.google.guava</groupId>
	    <artifactId>guava</artifactId>
	    <version>22.0</version>
	</dependency>`

**Comment by barancev** [comment] 2019-11-29 09:50
Run `mvn depencency:tree` and show the result.

**Comment by sbabcoc** [comment] 2019-12-10 00:08
The issue is that the **SimpleTimeLimiter** constructor being invoked is now `private` as of Guava 23.0

This constructor was getting called from the `UrlChecker` class, but this code was updated at Selenium 3.5.0 to use the current static `create` method instead. This suggests that the code encountering this issue is from some prior Selenium release.

FYI - As of Selenium 4.0.0-alpha-3, the `UrlChecker` class no longer relies on `SimpleTimeLimiter`.

**Comment by sbabcoc** [comment] 2019-12-10 13:58
On a different but related note, how would I go about publishing a patch to Selenium 2.53.1 that upgrades Guava to the latest version?

**Comment by AutomatedTester** [comment] 2020-03-25 21:19
Closing as the issue was due to external dependencies.

**Closed by AutomatedTester** 2020-03-25 21:19 UTC
Labels: R-awaiting answer
