### ISSUE TITLE
keyDown() does not work with Internet Explorer Driver

### ISSUE THREAD

**Issue by Miro-H** [SeleniumHQ/selenium#1351] opened 2015-12-07 07:49 UTC
I have tried to do it in different ways, but what works on Chrome (version 46.0.2490.86 m) and Firefox (version 42.0) won't work with IE 9.
Neither
```javascript
browser.actions()
			.sendKeys(protractor.Key.chord(protractor.Key.CONTROL, '1'))
			.perform()
```
nor
```javascript
browser.actions()
			.keyDown(protractor.Key.CONTROL)
			.sendKeys('1')
			.keyUp(protractor.Key.CONTROL)
			.perform();
```
work. I use protractor to send my tests to the selenium standalone server (which is on a VM which runs win7). Please tell me in case I overlooked something or if there is a workaround for this issue.

Full test:
```javascript
describe('keyDown', function () {
    browser.ignoreSynchronization = true;
    browser.get('http://ci.seleniumhq.org:2310/common/keyboard_shortcut.html');

	it('should work with IE9', function () {
		browser.actions()
			.sendKeys(protractor.Key.chord(protractor.Key.CONTROL, '1'))
			.perform()

		expect(element(by.tagName('body')).getAttribute('style')).toContain('background: red');
	});
});
```
Thank you in advance,
Miro

**Comment by jimevans** [comment] 2015-12-07 11:25
What happens if you start your IE session with setting the `requireWindowFocus` capability to `true`?

**Comment by Miro-H** [comment] 2015-12-07 12:14
Nothing happens, still the same behavior. (tested with both browser action snippets)

**Comment by jimevans** [comment] 2015-12-07 19:21
I'm unable to reproduce with IE11 with IEDriverServer.exe 2.48.0.4 and setting `requireWindowFocus` to `true`. Given that Microsoft is dropping support for IE9 in less than six weeks as of this writing, I'm disinclined to fix for this specific case. Here is my code (in C#, using NUnit) for proof:

    [Test]
    public void ModifierKeysTest()
    {
        // This list is solely for failure reporting purposes.
        List<string> keyComboNames = new List<string>()
        {
            "Control",
            "Shift",
            "Control + Shift",
            "Alt",
            "Control + Alt",
            "Shift + Alt",
            "Control + Shift + Alt"
        };

        // This list is solely for failure reporting purposes.
        List<string> colorNames = new List<string>()
        {
            "red",
            "green",
            "yellow",
            "lightblue",
            "lightgreen",
            "silver",
            "magenta"
        };

        // List of expected background color values after keystrokes sent to browser.
        List<string> expectedColors = new List<string>()
        {
            "rgba(255, 0, 0, 1)",
            "rgba(0, 128, 0, 1)",
            "rgba(255, 255, 0, 1)",
            "rgba(173, 216, 230, 1)",
            "rgba(144, 238, 144, 1)",
            "rgba(192, 192, 192, 1)",
            "rgba(255, 0, 255, 1)"
        };

        // List of combinations of modifier keys.
        List<List<string>> modifierCombinations = new List<List<string>>()
        {
            new List<string>() { Keys.Control },
            new List<string>() { Keys.Shift },
            new List<string>() { Keys.Control, Keys.Shift },
            new List<string>() { Keys.Alt },
            new List<string>() { Keys.Control, Keys.Alt },
            new List<string>() { Keys.Shift, Keys.Alt },
            new List<string>() { Keys.Control, Keys.Shift, Keys.Alt}
        };

        bool passed = true;
        string errors = string.Empty;

        // This sets the requireWindowFocus capability. It is required to set this 
        // capability to get modifier keys to work properly.
        InternetExplorerOptions options = new InternetExplorerOptions();
        options.RequireWindowFocus = true;

        IWebDriver driver = new InternetExplorerDriver(options);
        driver.Url = "http://ci.seleniumhq.org:2310/common/keyboard_shortcut.html";
        IWebElement body = driver.FindElement(By.CssSelector("body"));
        Actions actions = new Actions(driver);
        for (int i = 0; i < keyComboNames.Count; i++)
        {
            // Press all modifier keys for this case.
            for (int j = 0; j < modifierCombinations[i].Count; j++)
            {
                actions.KeyDown(modifierCombinations[i][j]);
            }

            actions.SendKeys("1");
                
            // Release all modifier keys.
            // Alternatively, the following single line of code would release
            // all modifier keys, instead of looping through each key.
            // actions.SendKeys(Keys.Null);
            for (int j = 0; j < modifierCombinations[i].Count; j++)
            {
                actions.KeyUp(modifierCombinations[i][j]);
            }

            actions.Perform();

            // Check that the background color of the body element has been set properly.
            string background = body.GetCssValue("background-color");
            passed = passed && background == expectedColors[i];
            if (background != expectedColors[i])
            {
                if (errors.Length > 0)
                {
                    errors += "\n";
                }

                errors += string.Format("Key not properly processed for {0}. Background should be {1}, Expected: '{2}', Actual: '{3}'",
                    keyComboNames[i],
                    colorNames[i],
                    expectedColors[i],
                    background);
            }
        }

        Assert.IsTrue(passed, errors);
    }

**Closed by jimevans** 2015-12-07 19:21 UTC

**Comment by Miro-H** [comment] 2015-12-10 10:42
Hm very strange that you couldn't reproduce it. I invested some more time and tested it with IE11 too. But by me the problem is still the same: The background is still unchanged.

**Comment by pavoltravnik** [comment] 2018-05-24 14:43
requireWindowFocus capability to true helped
