### ISSUE TITLE
Chrome - Exception when trying to get an embeded flash object

### ISSUE THREAD

**Issue by andreidrc** [SeleniumHQ/selenium#1333] opened 2015-12-02 16:11 UTC
I'm trying to assert that an embedded object appears on the page, I'm using python bindings and selector xpath, on chrome version 46.0.2490.86 worked without a hitch, doesn't work after upgrading to version 47.0.2526.73.

Still working on Firefox, so far tested on win 10 and win 7 same issue on both

Selenium server version 2.48.2

10:50:32.570 INFO - Executing: [find element: By.xpath: //embed])
10:50:33.351 ERROR - Unexpected exception during findElement
org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {}
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: '----', ip: '---', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_66'
Driver info: driver.version: EventFiringWebDriver
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:360)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:490)
        at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:345)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:102)
        at com.sun.proxy.$Proxy1.findElement(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:187)
        at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:48)
        at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:1)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to org.openqa.selenium.WebElement
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:358)
        ... 17 more
10:50:33.366 WARN - Exception thrown
org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {}
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: '-----', ip: '-----', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_66'
Driver info: driver.version: EventFiringWebDriver
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:360)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:490)
        at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:345)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:102)
        at com.sun.proxy.$Proxy1.findElement(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:187)
        at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:48)
        at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:1)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to org.openqa.selenium.WebElement
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:358)
        ... 17 more
10:50:33.380 WARN - Exception: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to org.openqa.selenium.WebElement

**Comment by andreidrc** [comment] 2015-12-03 08:27
Adding the html snippet and the code:

<object classid="clsid:<id>" codebase="http://fpdownload.adobe.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0" width="320" height="185" id="myMovieName"> <param name="Wmode" value="Opaque"> 
<param name="movie" value=<value>;wmode=Opaque">
<param name="FlashVars" value="">
<param name="quality" value="high">
<param name="bgcolor" value="#FFFFFF">
<param name="play" value="true">
<param name="loop" value="true">
<param name="bgcolor" value="#FFFFFF">
<embed wmode="Opaque" src=<app-url>;wmode=Opaque" quality="high" bgcolor="#FFFFFF" width="1024" height="768" name="myMovieName" align="" type="application/x-shockwave-flash" play="true" loop="true" flashvars="" pluginspage="http://www.adobe.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash">

</object>

Code:
report = self.browser.driver.find_element(By.XPATH, "//embed[@type='application/x-shockwave-flash']")
self.assertTrue(report.is_displayed())

I tried using different selectors(eg. different xpath and by.name) same issue

**Comment by andreidrc** [comment] 2015-12-03 15:02
Update:
Might be a chromedriver issue
```
driver.get('http://www.sdn.sap.com/irj/scn/go/portal/prtroot/docs/library/uuid/f0c4ca79-62c0-2e10-34b5-c1e518798140?QuickLink=index&overridelayout=true&52239688305579')
elem = driver.execute("return document.getElementsByTagName('embed')")
```
elem is empty.
Returns a web element for any other tags (eg.'body').

**Comment by turzait** [comment] 2015-12-03 15:15
Hi,
We ran into the same issue after the Chrome update:
Problematic html:

'''
<object id="topics_visu" width="100%" height="100%" type="application/x-shockwave-flash" data="/chs/flash/carrot2/com.carrotsearch.visualizations.circles.swf" style="visibility: visible;">
<param name="wmode" value="transparent">
<param name="flashvars" value="documentsPanel=HIDE&logo=custom%3A%2Fchs%2Fimages%2Fchlogo.gif&attributionEnabled=true&attributionText=Circles%20Visualization%2C%20%3F%3F%20Carrot%20Search%20s.c.&attributionUrl=http%3A%2F%2Fcarrotsearch.com%2Fcircles&disableLogging=true&forceRenderEvent=true&hideMenuItems=false&gui_backgroundColor=0x00ffffff&backgroundColorForImageExport=0xffffffff&gui_colorModel=hsv&gui_hsv_start=0.7%2C%200.55%2C%200.85%2C%201&gui_hsv_end=0.7%2C%200.5%2C%201%2C%201&gui_hsv_text_dark=0xd0000000&gui_hsv_text_light=0xd0c0c...deFontSize=72&minOutsideFontSize=2&maxOutsideFontSize=32&weightFunction=document-count&maxNegativeSizeRatio=0.1&upperCaseLabels=true&callback_onInitialized=__carrotsearchvisualization__topicsvisu__onInitialize&callback_onGroupSelection=__carrotsearchvisualization__topicsvisu__onGroupSelectionChanging&useEchoServiceForSaveAsMenu=true&callback_imageData=__carrotsearchvisualization__topicsvisu__imageDataCallback&useImageDataCallbackForSaveAsMenu=true&onPreinit=__carrotsearchvisualization__topicsvisu__preinit">
</object>
'''

Exception:
'''
org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {}
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'NoName2', ip: '192.168.56.1', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_31'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:360)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:482)
	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:430)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:345)
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy12.toString(Unknown Source)
	at java.lang.String.valueOf(String.java:2981)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at test.java.com.ch.forsight.main.PageUtils.waitForElementToAppearCustomWaitTime(PageUtils.java:583)
	at test.java.com.chRE.forsight.pageobject.monitorDetails.pageInterfaces.topicWheelInterfaces.TopicWheelInterfaceImpl.waitForTopicWheelTabToLoad(TopicWheelInterfaceImpl.java:75)
	at test.java.com.chRE.forsight.pageobject.monitorDetails.buzzMonitorDetails.TopicWheelBuzzPage.waitForTopicWheelTabToLoad(TopicWheelBuzzPage.java:42)
	at test.java.com.ch.forsight.exploreTabTests.ExploreTabTopicsTests.testMonitorDetailsTopicsTabAPIUI(ExploreTabTopicsTests.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at test.java.com.ch.forsight.main.rules.TestRule$1.evaluate(TestRule.java:60)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to org.openqa.selenium.WebElement
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:358)
	... 41 more
'''

**Comment by ddavison** [comment] 2015-12-04 14:24
I have this same issue as well - will advise.

**Comment by ddavison** [comment] 2015-12-04 14:28
my guess is that it's rooted in chromedriver

**Comment by andreidrc** [comment] 2015-12-04 14:30
I've opened the issue there as well. https://bugs.chromium.org/p/chromedriver/issues/detail?id=1276

**Comment by Spitigala** [comment] 2015-12-04 15:57
Experiencing the same problem on the latest Chrome version (47.0.2526.73) running on a mac. Downgraded to the previous version of Chrome (46.0.2490.86) and it worked just fine. But this is an issue for us because we always run our automated tests on the latest versions of the browsers.

Exception:

```
MiniTest::Assertion: Is video player displayed?.
Exception raised:
<#<Selenium::WebDriver::Error::UnknownError: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to org.openqa.selenium.WebElement (java.lang.ClassCastException)>>.

Stack trace:
[remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):387:in `findElements'
[remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):486:in `findElementsByCssSelector'
[remote server] org.openqa.selenium.By$ByCssSelector(By.java):441:in `findElements'
[remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):341:in `findElements'
[remote server] sun.reflect.GeneratedMethodAccessor39():-1:in `invoke'
[remote server] sun.reflect.DelegatingMethodAccessorImpl(DelegatingMethodAccessorImpl.java):43:in `invoke'
[remote server] java.lang.reflect.Method(Method.java):606:in `invoke'
[remote server] org.openqa.selenium.support.events.EventFiringWebDriver$2(EventFiringWebDriver.java):102:in `invoke'
[remote server] com.sun.proxy.$Proxy1():-1:in `findElements'
[remote server] org.openqa.selenium.support.events.EventFiringWebDriver(EventFiringWebDriver.java):176:in `findElements'
[remote server] org.openqa.selenium.remote.server.handler.FindElements(FindElements.java):50:in `call'
[remote server] org.openqa.selenium.remote.server.handler.FindElements(FindElements.java):1:in `call'
[remote server] java.util.concurrent.FutureTask(FutureTask.java):262:in `run'
[remote server] org.openqa.selenium.remote.server.DefaultSession$1(DefaultSession.java):176:in `run'
[remote server] java.util.concurrent.ThreadPoolExecutor(ThreadPoolExecutor.java):1145:in `runWorker'
[remote server] java.util.concurrent.ThreadPoolExecutor$Worker(ThreadPoolExecutor.java):615:in `run'
[remote server] java.lang.Thread(Thread.java):745:in `run'
/Users/teamcity/.rvm/gems/jruby-1.7.21@player/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
/Users/teamcity/.rvm/gems/jruby-1.7.21@player/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
/Users/teamcity/.rvm/gems/jruby-1.7.21@player/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/common.rb:78:in `create_response'
/Users/teamcity/.rvm/gems/jruby-1.7.21@player/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
/Users/teamcity/.rvm/gems/jruby-1.7.21@player/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/Users/teamcity/.rvm/gems/jruby-1.7.21@player/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:657:in `raw_execute'
/Users/teamcity/.rvm/gems/jruby-1.7.21@player/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:635:in `execute'
/Users/teamcity/.rvm/gems/jruby-1.7.21@player/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:613:in `find_elements_by'
/Users/teamcity/.rvm/gems/jruby-1.7.21@player/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/common/search_context.rb:81:in `find_elements'
/Users/teamcity/Agent/software/buildAgent/work/7f03edba22f1e7/lib//qa/psd_components/waiting.rb:63:in `wait_for_elements'
```

**Comment by lukeis** [comment] 2015-12-06 01:20
issues with chromedriver are tracked in their own project. Thanks for logging the bug there and follow it for updates. Since there appears nothing to be done on the client library side, I'm going to close this issue here.

**Closed by lukeis** 2015-12-06 01:20 UTC
