### ISSUE TITLE
@ sign not sent using sendkeys in 3.5.2 but it works in 3.4.0

### ISSUE THREAD

**Issue by xpagedeveloper** [SeleniumHQ/selenium#4723] opened 2017-09-20 07:57 UTC
## Meta -
OS:  
Windows 10 English with Swedish Keyboard
Selenium Version:  
3.5.1 vs 3.40
Browser:  
Internet Explorer

Browser Version:  
11.608.150630 updateversion 11.046

## Expected Behavior -
Sending the string <**sending at sign @ to the field**> to the query field on bing shows up with @ sign
## Actual Behavior -
this string is shown <**sending at sign 2 to the field**>
## Steps to reproduce -
Run this code with the IE webdriver 32bit version 3.4.0 works but doesn't work with 3.5.1 version

  IWebDriver browser = new OpenQA.Selenium.IE.InternetExplorerDriver();
            browser.Navigate().GoToUrl("https://www.bing.com/");
            IWebElement query = browser.FindElement(By.Id("sb_form_q"));
            query.SendKeys("sending at sign @ to the field");

**Comment by p0deje** [comment] 2017-09-21 09:48
Duplicate of #4523

**Closed by p0deje** 2017-09-21 09:48 UTC
Labels: C-dotnet, D-IE
