### ISSUE TITLE
Selenium hangs for a minute sometimes on DELETE /session/{session_id}

### ISSUE THREAD

**Issue by remorhaz** [SeleniumHQ/selenium#8992] opened 2020-12-22 13:18 UTC
## 🐛 Bug Report

I've upgraded to latest `selenium/standalone-firefox:4.0.0-beta-1-prerelease-20201208` image and noticed that sometimes when I call `DELETE /session/{session_id}` Selenium hangs for 60 seconds and reports an error. When I repeat the failed call, I get an `invalid session id` error - that probably means that session was closed successfully by the previous call, regardless of the error it has reported.

## To Reproduce

The bug occurs irregularly, but when it occurs - the way to reproduce is just:
- call `GET /session/{session_id}/screenshot`
- call `DELETE /session/{session_id}` where `{session_id}` is a valid ID of an open session.

## Expected behavior

Session is closed, and no error is reported.

## Test script or set of commands reproducing this issue

The bug occurs irregularly, but often enough and always after taking a screenshot. I wonder if [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1477550) is related.

## Environment

OS: Ubuntu + docker-compose
Browser: Firefox
Browser version: 83.0
Browser Driver version: GeckoDriver 0.28.0
Language Bindings version: custom PHP binding via HTTP
Selenium Grid version (if applicable): 4.0-beta1

## Logs
Here's the related fragment of Selenium logs:
```
selenium_1       | 12:38:05.702 INFO [LoggingOptions$1.lambda$export$0] - {"traceId": "0d21265ccecf3d060418748465e335f6","spanId": "ccffd56469e25171","spanKind": "INTERNAL","eventTime": 1608640685701260378,"eventName": "HTTP request execution complete","attributes": {"http.status_code": 200,"http.target": "\u002fsession\u002f1d20c7da-477a-430a-92f4-01d7cae955c1\u002fscreenshot","http.flavor": 1,"http.user_agent": "GuzzleHttp\u002f7","http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.method": "GET","http.host": "selenium:4444","http.scheme": "HTTP"}}
selenium_1       | 
selenium_1       | 1608640685711	Marionette	INFO	Stopped listening on port 44356
selenium_1       | console.warn: services.settings: main/partitioning-exempt-urls sync interrupted by shutdown
selenium_1       | console.error: "Could not load engine bing@search.mozilla.org: TypeError: AddonManagerInternal._getProviderByName(...) is undefined"
selenium_1       | console.error: "Could not load engine ddg@search.mozilla.org: TypeError: AddonManagerInternal._getProviderByName(...) is undefined"
selenium_1       | console.warn: SearchService: "_init: abandoning init due to shutting down"
selenium_1       | JavaScript error: resource://gre/modules/DeferredTask.jsm, line 215: Error: Unable to arm timer, the object has been finalized.
selenium_1       | JavaScript error: resource://gre/modules/DeferredTask.jsm, line 215: Error: Unable to arm timer, the object has been finalized.
selenium_1       | JavaScript error: resource://gre/modules/DeferredTask.jsm, line 215: Error: Unable to arm timer, the object has been finalized.
selenium_1       | JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 554: uncaught exception: 2147500036
selenium_1       | JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 554: uncaught exception: 2147500036
selenium_1       | JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 554: uncaught exception: 2147500036
selenium_1       | JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 554: uncaught exception: 2147500036
selenium_1       | JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 554: uncaught exception: 2147500036
selenium_1       | JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 554: uncaught exception: 2147500036
selenium_1       | JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 554: uncaught exception: 2147500036
selenium_1       | JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 554: uncaught exception: 2147500036
selenium_1       | JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 554: uncaught exception: 2147500036
selenium_1       | JavaScript error: resource://gre/modules/osfile/osfile_async_front.jsm, line 426: Error: OS.File has been shut down. Rejecting post to stat
selenium_1       | 12:39:05.786 WARN [SpanWrappedHttpHandler.execute] - Unable to execute request: NettyHttpHandler request execution error
selenium_1       | java.lang.RuntimeException: NettyHttpHandler request execution error
selenium_1       | 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:76)
selenium_1       | 	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
selenium_1       | 	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
selenium_1       | 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)
selenium_1       | 	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
selenium_1       | 	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
selenium_1       | 	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:60)
selenium_1       | 	at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)
selenium_1       | 	at org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:100)
selenium_1       | 	at org.openqa.selenium.grid.node.ProtocolConvertingSession.execute(ProtocolConvertingSession.java:75)
selenium_1       | 	at org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:115)
selenium_1       | 	at org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:317)
selenium_1       | 	at org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)
selenium_1       | 	at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:364)
selenium_1       | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
selenium_1       | 	at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
selenium_1       | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium_1       | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
selenium_1       | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
selenium_1       | 	at org.openqa.selenium.grid.node.Node.execute(Node.java:202)
selenium_1       | 	at org.openqa.selenium.grid.web.CombinedHandler.execute(CombinedHandler.java:59)
selenium_1       | 	at org.openqa.selenium.grid.web.RoutableHttpClientFactory$1.execute(RoutableHttpClientFactory.java:66)
selenium_1       | 	at org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:100)
selenium_1       | 	at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:102)
selenium_1       | 	at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:364)
selenium_1       | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
selenium_1       | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
selenium_1       | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
selenium_1       | 	at org.openqa.selenium.grid.router.Router.execute(Router.java:90)
selenium_1       | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium_1       | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)
selenium_1       | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:67)
selenium_1       | 	at org.openqa.selenium.grid.server.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:30)
selenium_1       | 	at org.openqa.selenium.grid.server.WrapExceptions.lambda$apply$0(WrapExceptions.java:36)
selenium_1       | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
selenium_1       | 	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:46)
selenium_1       | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
selenium_1       | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
selenium_1       | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
selenium_1       | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
selenium_1       | 	at java.lang.Thread.run(Thread.java:748)
selenium_1       | Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to localhost/127.0.0.1:31836 after 60000 ms
selenium_1       | 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
selenium_1       | 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
selenium_1       | 	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
selenium_1       | 	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)
selenium_1       | 	... 40 more
selenium_1       | Caused by: java.util.concurrent.TimeoutException: Request timeout to localhost/127.0.0.1:31836 after 60000 ms
selenium_1       | 	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
selenium_1       | 	at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
selenium_1       | 	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
selenium_1       | 	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
selenium_1       | 	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
selenium_1       | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
selenium_1       | 	... 1 more
selenium_1       | 12:39:05.787 WARN [LoggingOptions$1.lambda$export$0] - {"traceId": "effb3ffb5ce42724dc93082fe7890237","spanId": "3f0409c167314677","spanKind": "INTERNAL","eventTime": 1608640745785704841,"eventName": "exception","attributes": {"http.target": "\u002fsession\u002f1d20c7da-477a-430a-92f4-01d7cae955c1","exception.type": "java.lang.RuntimeException","http.flavor": 1,"http.user_agent": "GuzzleHttp\u002f7","exception.message": "Unable to execute request: NettyHttpHandler request execution error","http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","exception.stacktrace": "java.lang.RuntimeException: NettyHttpHandler request execution error\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:76)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:49)\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)\n\tat org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:60)\n\tat org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:55)\n\tat org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:100)\n\tat org.openqa.selenium.grid.node.ProtocolConvertingSession.execute(ProtocolConvertingSession.java:75)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:115)\n\tat org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:317)\n\tat org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:364)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:67)\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:67)\n\tat org.openqa.selenium.grid.node.Node.execute(Node.java:202)\n\tat org.openqa.selenium.grid.web.CombinedHandler.execute(CombinedHandler.java:59)\n\tat org.openqa.selenium.grid.web.RoutableHttpClientFactory$1.execute(RoutableHttpClientFactory.java:66)\n\tat org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:100)\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:102)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:364)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:67)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:67)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:90)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:327)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:67)\n\tat org.openqa.selenium.grid.server.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:30)\n\tat org.openqa.selenium.grid.server.WrapExceptions.lambda$apply$0(WrapExceptions.java:36)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:46)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to localhost\u002f127.0.0.1:31836 after 60000 ms\n\tat java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)\n\tat java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)\n\tat org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)\n\tat org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:59)\n\t... 40 more\nCaused by: java.util.concurrent.TimeoutException: Request timeout to localhost\u002f127.0.0.1:31836 after 60000 ms\n\tat org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)\n\tat org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)\n\tat io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)\n\tat io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)\n\tat io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\t... 1 more\n","http.method": "DELETE","http.host": "selenium:4444","http.scheme": "HTTP"}}
selenium_1       | 
selenium_1       | ExceptionHandler::GenerateDump cloned child 1365
selenium_1       | ExceptionHandler::SendContinueSignalToChild sent continue signal to child
selenium_1       | ExceptionHandler::WaitForContinueSignal waiting for continue signal...
selenium_1       | 12:39:09.969 INFO [LoggingOptions$1.lambda$export$0] - {"traceId": "fc363ec4fe25944138cc26bb1b264b24","spanId": "59415c52ff14b91e","spanKind": "INTERNAL","eventTime": 1608640749969122282,"eventName": "Deleted session from local session map","attributes": {"logger": "org.openqa.selenium.grid.sessionmap.local.LocalSessionMap","session.id": "1d20c7da-477a-430a-92f4-01d7cae955c1"}}
```

**Comment by diemol** [comment] 2020-12-22 23:07
Duplicate of https://github.com/SeleniumHQ/docker-selenium/issues/1146

(Seems to be a Firefox/GeckoDriver issue)

**Closed as completed by diemol** 2020-12-22 23:07 UTC
