### ISSUE TITLE
Cannot click on elements via Actions

### ISSUE THREAD

**Issue by JamJar00** [SeleniumHQ/selenium#7865] opened 2019-12-16 10:48 UTC
## 🐛 Bug Report

As reported [here](https://github.com/SeleniumHQ/selenium/issues/7049), the latest selenium (3.141.59) cannot click on elements when using Actions:

```
new Actions(world.getWebDriver()).moveToElement(world.getWebDriver().findElement(By.id("map")), (int) x, (int) y)
                                         .click()
                                         .perform();
```
We are only testing chrome so I am unsure if this affects other platforms. Reproducible both locally and on selenium grid. Not reproducible on 3.141.5.

## To Reproduce
Run the above snippet (modified appropriately) where you use `Actions` to click on an element.

## Expected behavior
The element is clicked on correctly in the browser.

## Actual behavior
Nothing is clicked.

## Environment

OS: Ubuntu and dockerised selenium grid.
Browser: Chrome, possibly others)
Browser version: 79.0.3945.79
Browser Driver version: ChromeDriver 79.0.3945.36 and selenium grid
Language Bindings version: Java 3.141.59
Selenium Grid version (if applicable): 3.141.59

**Comment by AutomatedTester** [comment] 2019-12-16 14:42
Seeing as clicks are working there is something different between our setup and yours. This bug report has nothing that allows us to reproduce the error and therefore can not fix it

**Comment by JamJar00** [comment] 2019-12-16 15:04
What else do you need to be able to reproduce it? I'll gladly supply more information if I can but I can't provide fully fledged examples or code as it's a commercial product we're experiencing this on.

I should have added that 'map' in the example is a canvas rendered by mapbox, I imagine there could be differences in behaviour because of that.

**Comment by diemol** [comment] 2019-12-16 19:59
@JamJar00 neither in the referenced issue nor in this one a complete self-contained script and an HTML page (public or just attache it to the issue), that reproduces the issue has been provided.
I hope it is understandable that narrative descriptions of issues are really hard to use, it is always better when the exact scripts and pages are provided.

**Comment by JamJar00** [comment] 2019-12-17 11:19
It is understandable, and I would love to be able to provide a full example but I'm afraid I simply don't have the time to produce one.

I would expect this to be reproducible on a simple page such as the following when combined with the above Java code:
```html
<html>
<body>
    <canvas id="map" width="200" height="200" />
    <script>
        const elem = document.getElementById('map');
        elem.addEventListener('click', function(event) {
            alert("hasdfasdf");
        }, false);
    </script>
</body>
</html>
```
When run with a local browser instance then you should obviously see the alert pop up, however I don't think it will. If absolutely necessary, I can try to write a quick Java program to do it but realistically it won't happen until January at the earliest.

I did a quick git diff yesterday and searched for the word 'click' and there were changes in 3.141.59 around clicking logic but I didn't dive into the code to understand the implications of the change or if if could actually cause something like this.

**Comment by JamJar00** [comment] 2019-12-17 11:26
In clarification of the last paragraph there and to reiterate, this is working completely fine on our infrastructure since downgrading to 3.141.5, it's only 3.141.59 that has this issue!

**Comment by diemol** [comment] 2019-12-22 04:40
OK, since it is not possible for different reasons to provide a way to reproduce the issue, and adding to the fact that Grid 4.x is a completely new code base... Can you please try with the latest alpha release of Selenium 4?

**Comment by barancev** [comment] 2020-03-18 17:49
Closing the issue as there is no reproduction scenario provided.

**Closed by barancev** 2020-03-18 17:49 UTC
Labels: R-awaiting answer
