### ISSUE TITLE
selenium-html-runner throws BindException

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#3352] opened 2017-01-11 07:07 UTC
# Meta

OS: Windows 8.1 Pro
Selenium Version: selenium-html-runner-3.0.1
Browser: Firefox
Browser Version: 50.1.0

# Expected Behavior -

Seeing new Firefox opening and browsing to www.google.com

# Actual Behavior -

Firefox opens and then closes immediately with following error message.

Steps to reproduce -

With latest geckodriver and simple IDE test. Execute command:
`>java -jar selenium-html-runner-3.0.1.jar -htmlSuite "*firefox" "https://www.google.com" "google.html" "result.html"`

Executing selenium-html-runner causes following error:

`
Multi-window mode is longer used as an option and will be ignored.
1484118145013   geckodriver     INFO    Listening on 127.0.0.1:12600
jan 11, 2017 8:02:25 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1484118145627   mozprofile::profile     INFO    Using profile path C:\Users\rene\AppData\Local\Temp\rust_mozprofile.sYz653mEXGuD
1484118145647   geckodriver::marionette INFO    Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe
1484118145659   geckodriver::marionette INFO    Connecting to Marionette on localhost:61756
1484118146005   addons.manager  DEBUG   Application has been upgraded
1484118146079   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1484118146081   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1484118146087   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1484118146091   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1484118146092   addons.manager  DEBUG   Starting provider: XPIProvider
1484118146093   addons.xpi      DEBUG   startup
1484118146094   addons.xpi      INFO    SystemAddonInstallLocation directory is missing
1484118146096   addons.xpi      INFO    Mapping aushelper@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1484118146097   addons.xpi      INFO    Mapping e10srollout@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1484118146098   addons.xpi      INFO    Mapping firefox@getpocket.com to C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1484118146098   addons.xpi      INFO    Mapping webcompat@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1484118146100   addons.xpi      INFO    Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{972ce4c6-7e
08-4474-a285-3208198ce6fd}.xpi
1484118146101   addons.xpi      DEBUG   checkForChanges
1484118146101   addons.xpi      DEBUG   Loaded add-on state from prefs: {}
1484118146103   addons.xpi      DEBUG   New add-on aushelper@mozilla.org in app-system-defaults
1484118146104   addons.xpi      DEBUG   getModTime: Recursive scan of aushelper@mozilla.org
1484118146105   addons.xpi      DEBUG   New add-on e10srollout@mozilla.org in app-system-defaults
1484118146105   addons.xpi      DEBUG   getModTime: Recursive scan of e10srollout@mozilla.org
1484118146106   addons.xpi      DEBUG   New add-on firefox@getpocket.com in app-system-defaults
1484118146106   addons.xpi      DEBUG   getModTime: Recursive scan of firefox@getpocket.com
1484118146107   addons.xpi      DEBUG   New add-on webcompat@mozilla.org in app-system-defaults
1484118146107   addons.xpi      DEBUG   getModTime: Recursive scan of webcompat@mozilla.org
1484118146108   addons.xpi      DEBUG   New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1484118146109   addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1484118146109   addons.xpi      DEBUG   getInstallState changed: true, state: {"app-system-defaults":{"aushelper@mozilla.org":{"d":"C:\\Program Files (x86)\\Moz
illa Firefox\\browser\\features\\aushelper@mozilla.org.xpi","st":1482224058971},"e10srollout@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browse
r\\features\\e10srollout@mozilla.org.xpi","st":1482224058970},"firefox@getpocket.com":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\firefox
@getpocket.com.xpi","st":1482224058968},"webcompat@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\webcompat@mozilla.org.xpi","s
t":1482224058904}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-44
74-a285-3208198ce6fd}.xpi","st":1482224058973}}}
1484118146120   addons.xpi-utils        DEBUG   Opening XPI database C:\Users\rene\AppData\Local\Temp\rust_mozprofile.sYz653mEXGuD\extensions.json
1484118146122   addons.xpi-utils        DEBUG   New add-on aushelper@mozilla.org installed in app-system-defaults
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1484118146133   DeferredSave.extensions.json    DEBUG   Save changes
1484118146134   addons.xpi-utils        DEBUG   New add-on e10srollout@mozilla.org installed in app-system-defaults
1484118146141   DeferredSave.extensions.json    DEBUG   Starting timer
1484118146142   DeferredSave.extensions.json    DEBUG   Save changes
1484118146142   addons.xpi-utils        DEBUG   New add-on firefox@getpocket.com installed in app-system-defaults
1484118146154   DeferredSave.extensions.json    DEBUG   Save changes
1484118146155   addons.xpi-utils        DEBUG   New add-on webcompat@mozilla.org installed in app-system-defaults
1484118146163   DeferredSave.extensions.json    DEBUG   Save changes
1484118146164   addons.xpi-utils        DEBUG   New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1484118146172   DeferredSave.extensions.json    DEBUG   Save changes
1484118146173   addons.manager  DEBUG   Registering startup change 'installed' for aushelper@mozilla.org
1484118146181   addons.xpi      DEBUG   Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1484118146190   addons.xpi      DEBUG   Calling bootstrap method install on aushelper@mozilla.org version 1.0
1484118146190   addons.xpi-utils        DEBUG   Make addon app-system-defaults:aushelper@mozilla.org visible
1484118146190   DeferredSave.extensions.json    DEBUG   Save changes
1484118146191   addons.manager  DEBUG   Registering startup change 'installed' for e10srollout@mozilla.org
1484118146192   addons.xpi      DEBUG   Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1484118146209   addons.xpi      DEBUG   Calling bootstrap method install on e10srollout@mozilla.org version 1.5
1484118146210   addons.xpi-utils        DEBUG   Make addon app-system-defaults:e10srollout@mozilla.org visible
1484118146211   DeferredSave.extensions.json    DEBUG   Save changes
1484118146212   addons.manager  DEBUG   Registering startup change 'installed' for firefox@getpocket.com
1484118146213   addons.xpi      DEBUG   Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1484118146224   addons.xpi      DEBUG   Calling bootstrap method install on firefox@getpocket.com version 1.0.5
1484118146224   addons.xpi-utils        DEBUG   Make addon app-system-defaults:firefox@getpocket.com visible
1484118146224   DeferredSave.extensions.json    DEBUG   Save changes
1484118146225   addons.manager  DEBUG   Registering startup change 'installed' for webcompat@mozilla.org
1484118146226   addons.xpi      DEBUG   Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1484118146231   addons.xpi      DEBUG   Calling bootstrap method install on webcompat@mozilla.org version 1.0
1484118146231   addons.xpi-utils        DEBUG   Make addon app-system-defaults:webcompat@mozilla.org visible
1484118146232   DeferredSave.extensions.json    DEBUG   Save changes
1484118146232   addons.xpi-utils        DEBUG   Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1484118146232   DeferredSave.extensions.json    DEBUG   Save changes
1484118146233   addons.xpi      DEBUG   Updating XPIState for {"id":"aushelper@mozilla.org","syncGUID":"{8161a9e0-1499-4eba-982c-780ff51e26c4}","location":"app-
system-defaults","version":"1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"
icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Application Update Service Helper","description":"Sets value(s) in the update url based on cu
stom checks.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mo
zilla Firefox\\browser\\features\\aushelper@mozilla.org.xpi","installDate":1482224058971,"updateDate":1482224058971,"applyBackgroundUpdates":1,"bootstrap":true,
"skinnable":false,"size":5975,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibili
ty":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"50.1.0","maxVersion":"50.*"}],"targetPlatforms":[],"mu
ltiprocessCompatible":true,"seen":true}
1484118146233   addons.xpi      DEBUG   getModTime: Recursive scan of aushelper@mozilla.org
1484118146235   addons.xpi      DEBUG   Updating XPIState for {"id":"e10srollout@mozilla.org","syncGUID":"{11f84ce4-9312-4820-b502-b7bd31aab866}","location":"ap
p-system-defaults","version":"1.5","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null
,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Multi-process staged rollout","description":"Staged rollout of Firefox multi-process featur
e.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Fire
fox\\browser\\features\\e10srollout@mozilla.org.xpi","installDate":1482224058970,"updateDate":1482224058970,"applyBackgroundUpdates":1,"bootstrap":true,"skinnab
le":false,"size":7210,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":fals
e,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"50.1.0","maxVersion":"50.*"}],"targetPlatforms":[],"multiproce
ssCompatible":false,"seen":true}
1484118146235   addons.xpi      DEBUG   getModTime: Recursive scan of e10srollout@mozilla.org
1484118146238   addons.xpi      DEBUG   Updating XPIState for {"id":"firefox@getpocket.com","syncGUID":"{83d0a0bd-0851-44b0-8201-5c0b04ec9a43}","location":"app-
system-defaults","version":"1.0.5","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null
,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Pocket","description":"When you find something you want to view later, put it in Pocket.","
creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\
browser\\features\\firefox@getpocket.com.xpi","installDate":1482224058968,"updateDate":1482224058968,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":fal
se,"size":917619,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"lo
cales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"50.1.0","maxVersion":"50.*"}],"targetPlatforms":[],"multiprocessCom
patible":false,"seen":true}
1484118146238   addons.xpi      DEBUG   getModTime: Recursive scan of firefox@getpocket.com
1484118146239   addons.xpi      DEBUG   Updating XPIState for {"id":"webcompat@mozilla.org","syncGUID":"{faf4a0dd-b724-42c8-a86d-7d1be0983c4e}","location":"app-
system-defaults","version":"1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"
icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Web Compat","description":"Urgent post-release fixes for web compatibility.","creator":null,"
homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\featur
es\\webcompat@mozilla.org.xpi","installDate":1482224058904,"updateDate":1482224058904,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":1502,
"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"target
Applications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"50.1.0","maxVersion":"50.*"}],"targetPlatforms":[],"multiprocessCompatible":false,"s
een":true}
1484118146239   addons.xpi      DEBUG   getModTime: Recursive scan of webcompat@mozilla.org
1484118146241   addons.xpi      DEBUG   Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"{7a94b50e-ebc8-4fd2-aec9-7c78d784b13c}"
,"location":"app-global","version":"50.1.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"
aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","c
reator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor"
:"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1482224058973,"updateDate":1482224058
973,"applyBackgroundUpdates":1,"skinnable":true,"size":21152,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryCompo
nents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"50.1.0","maxVersion":"50
.1.0"}],"targetPlatforms":[],"seen":true}
1484118146257   addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1484118146260   DeferredSave.extensions.json    DEBUG   Save changes
1484118146260   addons.xpi      DEBUG   Updating database with changes to installed add-ons
1484118146260   addons.xpi-utils        DEBUG   Updating add-on states
1484118146262   addons.xpi-utils        DEBUG   Writing add-ons list
1484118146276   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1484118146277   addons.xpi      DEBUG   Calling bootstrap method startup on aushelper@mozilla.org version 1.0
1484118146279   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1484118146281   addons.xpi      DEBUG   Calling bootstrap method startup on e10srollout@mozilla.org version 1.5
1484118146282   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1484118146284   addons.xpi      DEBUG   Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1484118146288   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1484118146289   addons.xpi      DEBUG   Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1484118146293   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1484118146293   addons.manager  DEBUG   Provider finished startup: XPIProvider
1484118146293   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1484118146294   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1484118146294   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1484118146295   addons.manager  DEBUG   Starting provider: GMPProvider
1484118146354   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1484118146355   addons.manager  DEBUG   Provider finished startup: GMPProvider
1484118146355   addons.manager  DEBUG   Starting provider: PluginProvider
1484118146355   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1484118146355   addons.manager  DEBUG   Provider finished startup: PluginProvider
1484118146357   addons.manager  DEBUG   Completed startup sequence
1484118146879   Marionette      INFO    Listening on port 61756
1484118147400   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1484118147400   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1484118147400   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1484118147450   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1484118147451   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1484118147452   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
1484118147458   DeferredSave.extensions.json    DEBUG   Starting write
1484118148250   DeferredSave.extensions.json    DEBUG   Write succeeded
1484118148250   addons.xpi-utils        DEBUG   XPI Database saved, setting schema version preference to 17
jan 11, 2017 8:02:29 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
2017-01-11 08:02:30.015:INFO::main: Logging initialized @6551ms
2017-01-11 08:02:30.148:INFO:osjs.Server:main: jetty-9.2.z-SNAPSHOT
2017-01-11 08:02:30.173:INFO:osjsh.ContextHandler:main: Started o.s.j.s.h.ContextHandler@e6fdee{/tests,null,AVAILABLE}
2017-01-11 08:02:30.236:INFO:osjs.ServerConnector:main: Started ServerConnector@1e53c76{HTTP/1.1}{0.0.0.0:14460}
2017-01-11 08:02:30.237:INFO:osjs.Server:main: Started @6774ms
2017-01-11 08:02:30.245:INFO:osjs.ServerConnector:main: Stopped ServerConnector@1e53c76{HTTP/1.1}{0.0.0.0:14460}
2017-01-11 08:02:30.246:INFO:osjsh.ContextHandler:main: Stopped o.s.j.s.h.ContextHandler@e6fdee{/tests,null,UNAVAILABLE}
[Child 1508] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056

###!!! [Child][MessageChannel] Error: (msgtype=0x420003,name=PCompositable::Msg_Destroy) Channel error: cannot send/recv

###!!! [Child][MessageChannel] Error: (msgtype=0x420003,name=PCompositable::Msg_Destroy) Channel error: cannot send/recv

jan 11, 2017 8:02:31 AM org.openqa.selenium.server.htmlrunner.HTMLLauncher mainInt
WARNING: Test of browser failed: *firefox
java.io.IOException: java.lang.RuntimeException: java.net.BindException: Address already in use: JVM_Bind
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.determineSuiteUrl(HTMLLauncher.java:180)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:108)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.mainInt(HTMLLauncher.java:245)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.java:273)
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use: JVM_Bind
        at org.openqa.selenium.net.PortProber.pollPort(PortProber.java:154)
        at org.openqa.selenium.net.PortProber.pollPort(PortProber.java:137)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.determineSuiteUrl(HTMLLauncher.java:174)
        ... 3 more
Caused by: java.net.BindException: Address already in use: JVM_Bind
        at java.net.DualStackPlainSocketImpl.bind0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
        at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
        at java.net.PlainSocketImpl.bind(Unknown Source)
        at java.net.Socket.bind(Unknown Source)
        at org.openqa.selenium.net.PortProber.pollPort(PortProber.java:146)
        ... 5 more`

**Comment by AmolSG** [comment] 2017-02-22 14:51
I am also getting the same printed on the console

**Comment by barancev** [comment] 2017-08-02 10:44
Duplicate of #2978.
Fixed in 3.1

**Closed by barancev** 2017-08-02 10:44 UTC
Labels: C-htmlrunner, D-firefox
