### ISSUE TITLE
Can not preform actions. Bad endpoint call

### ISSUE THREAD

**Issue by avner-solomon** [SeleniumHQ/selenium#5067] opened 2017-11-16 17:21 UTC
## System
* gekodriver: 0.19.1
* Platform: Windows Server 2012 R2
* Firefox: 57
* Selenium: 3.7.1 with Node.js (selenium-webdriver)

creating a set of actions sends commands to /keys endpoint instead of actions /actions

## Testcase

await driver.actions().
				keyDown(webdriver.Key.CONTROL).
				keyDown(webdriver.Key.ALT).
				sendKeys('m').
				keyUp(webdriver.Key.CONTROL).
				keyUp(webdriver.Key.ALT).
				perform()

## Stacktrace

{ UnknownCommandError: POST /session/e18dd3e1-5bd4-4090-91e9-a752f40b9824/keys did not match a known command
    at Object.throwDecodedError (C:\eater\node_modules\selenium-webdriver\lib\error.js:514:15)
    at parseHttpResponse (C:\eater\node_modules\selenium-webdriver\lib\http.js:519:13)
    at doSend.then.response (C:\eater\node_modules\selenium-webdriver\lib\http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: sendKeys
    at thenableWebDriverProxy.schedule (C:\eater\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at actions.map.action (C:\eater\node_modules\selenium-webdriver\lib\actions.js:124:23)
    at Array.map (<anonymous>)
    at C:\eater\node_modules\selenium-webdriver\lib\actions.js:123:29
    at TaskQueue.execute_ (C:\eater\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\eater\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\eater\node_modules\selenium-webdriver\lib\promise.js:2974:25)
    at C:\eater\node_modules\selenium-webdriver\lib\promise.js:668:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: ActionSequence.perform
    at ActionSequence.perform (C:\eater\node_modules\selenium-webdriver\lib\actions.js:122:33)
    at C:\eater\selenium.js:55:5
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'UnknownCommandError',
  remoteStacktrace: 'stack backtrace:\n   0:           0x47e934 - <no info>\n   1:           0x47f0a3 - <no info>\n   2:           0x442649 - <no info>\n   3:           0x43c3f0 - <no info>\n   4:           0x40530f - <no info>\n   5:           0x40d01a - <no info>\n   6:           0x6bef19 - <no info>\n   7:           0x420b85 - <no info>\n   8:           0x6b96e0 - <no info>\n   9:     0x7ff871c413d2 - BaseThreadInitThunk' }

**Comment by avner-solomon** [comment] 2017-11-17 04:44
By reading the changelog am I right to assume this is fixed in v4.0.0-dev ?

**Comment by MagicPoulp** [comment] 2017-12-14 12:07
On HEAD (what would become v4.0), it seems to me that it is fixed for firefox but it becomes broken for chrome.

I proposed in a new issue to document how users should proceed.
https://github.com/SeleniumHQ/selenium/issues/5222

**Comment by jleyba** [comment] 2018-01-08 02:00
Closing issue. This is a duplicate of #4564

**Closed by jleyba** 2018-01-08 02:00 UTC
Labels: C-nodejs
