### ISSUE TITLE
Selenium 4 Alpha-1 leaves many AsyncHttpClient threads

### ISSUE THREAD

**Issue by KarelHaruda** [SeleniumHQ/selenium#9316] opened 2021-03-21 13:26 UTC
## 🐛 Bug Report
We have used selenium 3 for taking rendered SVG image from page. It works fine without any problems. Now I upgraded selenuim to version 4 alpha -1 and we started use selenium for printing page to PDF. Since now in tomcat threads we can see many of threads AsyncHttpClient in Runnable state. In maven dependency i can se that only Selenium use AsyncHttpClient.

![image](https://user-images.githubusercontent.com/19901055/111906559-54863e00-8a51-11eb-827f-847e23e2eee7.png)

![image](https://user-images.githubusercontent.com/19901055/111906584-754e9380-8a51-11eb-9985-03799938fbfe.png)

Now after few days there are about 200 of threads ..

**Comment by diemol** [comment] 2021-03-21 13:55
Please upgrade to beta 2. If the issue is still present, it would be helpful if you provide a way to reproduce the issue.

**Comment by KarelHaruda** [comment] 2021-03-21 14:11
I did upgrade .. we will see in few days :)

**Comment by diemol** [comment] 2021-03-21 19:14
This was not clear for me. Which version is showing the bug? Is it `beta-2`? If so, how can we reproduce it?

**Comment by KarelHaruda** [comment] 2021-03-22 06:00
Update to last version 4.0.0-beta-2 does not solve the problem. In 16 hours there are 9 new thrads AsyncHttpClient in runable state.
![image](https://user-images.githubusercontent.com/19901055/111946725-58ab6d80-8adc-11eb-9ace-63d182f73303.png)

**Comment by diemol** [comment] 2021-03-22 06:55
This is the expected behavior, the maximum number of threads that will get created is: available # of processors * 2. 

What is not normal at all is to have 200 threads as you reported before.

**Comment by diemol** [comment] 2021-03-22 06:56
The AsyncHttpClient keeps them in a runnable state for performance reasons.

**Comment by diemol** [comment] 2021-03-22 14:01
@KarelHaruda, please let us know if the number of threads goes above (available # of processors * 2).

**Comment by KarelHaruda** [comment] 2021-03-22 14:25
In this version 4.0.0-beta-2 is still 8 RUNNABLE threads. Version before had hundreds of threads. It looks well.

**Comment by diemol** [comment] 2021-03-22 16:45
Thank you for replying, @KarelHaruda. 
I will close this for now, but we are always open to more feedback and comments.

**Closed as completed by diemol** 2021-03-22 16:45 UTC
Labels: J-awaiting answer
