### ISSUE TITLE
Unable to execute Selenium (3.5.0) Grid Hub-Node configuration when "desired_capabilities=cap" is passed as an argument in "webdriver.Remote()" method through Python PyDev (Eclipse) unittest module

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#4526] opened 2017-08-21 16:29 UTC
## Meta - Unable to execute Selenium (3.5.0) Grid Hub-Node configuration when "desired_capabilities=cap" is passed as an argument in "webdriver.Remote()" method through Python PyDev (Eclipse) unittest module

OS: Windows 8 Pro, 64 bit

Selenium Version: 3.5.0 (Python 3.6.1)

Selenium Binding: Python 3.6.1

IEDriverServer Version: 3.5.0.0

Browser: INTERNETEXPLORER

Browser Version: INTERNETEXPLORER 10.0

## Expected Behavior - The documentation of [**`webdriver.Remote()`**](https://seleniumhq.github.io/selenium/docs/api/py/webdriver_remote/selenium.webdriver.remote.webdriver.html#module-selenium.webdriver.remote.webdriver) clearly mentions as follows:

    class selenium.webdriver.remote.webdriver.WebDriver(command_executor='http://127.0.0.1:4444/wd/hub', desired_capabilities=None, browser_profile=None, proxy=None, keep_alive=False, file_detector=None)

So, IEDriverServer.exe (3.5.0.0) with Selenium (3.5.0) should successfully call the `selenium.webdriver.remote.webdriver.WebDriver()` and Selenium Grid should respond to  Selenium Node request sent through Python PyDev (Eclipse).

## Steps to reproduce -
Minimum Code Block:

	import unittest
	from selenium import webdriver
	from selenium.webdriver.common.keys import Keys
	from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

	class PythonOrgSearch(unittest.TestCase):

	    def setUp(self):
		cap = DesiredCapabilities().INTERNETEXPLORER
		cap['platform'] = "Win8"
		cap['version'] = "10"
		cap['browserName'] = "internet explorer"
		cap['ignoreProtectedModeSettings'] = True
		cap['IntroduceInstabilityByIgnoringProtectedModeSettings'] = True
		cap['nativeEvents'] = True
		cap['ignoreZoomSetting'] = True
		cap['requireWindowFocus'] = True
		cap['INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS'] = True
		self.driver = webdriver.Remote(command_executor='http://127.0.0.1:4444/wd/hub', desired_capabilities=cap)
		print("Internet Explorer Browser Invoked")

	    def test_search_in_python_org(self):
		driver = self.driver
		driver.get("http://www.python.org")
		print("Application Accessed")
		self.assertIn("Python", driver.title)
		print("Page Title Validated")
		elem = driver.find_element_by_name("q")
		elem.send_keys("pycon")
		elem.send_keys(Keys.RETURN)
		assert "No results found." not in driver.page_source
		print("Page Source Validated")

	    def tearDown(self):
		self.driver.quit()
		print("IEDriver Killed")

	if __name__ == "__main__":
	    unittest.main()

Error Stack Trace:

	Finding files... done.
	Importing test modules ... done.

	======================================================================
	ERROR: test_search_in_python_org (readthedocs.SeleniumGridIE.PythonOrgSearch)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "C:\Users\AtechM_03\LearnAutmation\PythonProject\readthedocs\SeleniumGridIE.py", line 19, in setUp
	    self.driver = webdriver.Remote(command_executor='http://127.0.0.1:4444/wd/hub', desired_capabilities=cap)
	  File "C:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 140, in __init__
	    self.start_session(desired_capabilities, browser_profile)
	  File "C:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 229, in start_session
	    response = self.execute(Command.NEW_SESSION, parameters)
	  File "C:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 297, in execute
	    self.error_handler.check_response(response)
	  File "C:\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
	    raise exception_class(message, screen, stacktrace)
	selenium.common.exceptions.WebDriverException: Message: Error forwarding the new session cannot find : Capabilities [{IntroduceInstabilityByIgnoringProtectedModeSettings=true, nativeEvents=true, requireWindowFocus=true, browserName=internet explorer, ignoreZoomSetting=true, ignoreProtectedModeSettings=true, platformName=WIN8, version=10, INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS=true, platform=WIN8}]
	Stacktrace:
	    at org.openqa.grid.web.servlet.handler.RequestHandler.process (RequestHandler.java:110)
	    at org.openqa.grid.web.servlet.DriverServlet.process (DriverServlet.java:84)
	    at org.openqa.grid.web.servlet.DriverServlet.doPost (DriverServlet.java:68)
	    at javax.servlet.http.HttpServlet.service (HttpServlet.java:707)
	    at javax.servlet.http.HttpServlet.service (HttpServlet.java:790)
	    at org.seleniumhq.jetty9.servlet.ServletHolder.handle (ServletHolder.java:841)
	    at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle (ServletHandler.java:535)
	    at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:188)
	    at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle (SessionHandler.java:1595)
	    at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:188)
	    at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle (ContextHandler.java:1253)
	    at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope (ScopedHandler.java:168)
	    at org.seleniumhq.jetty9.servlet.ServletHandler.doScope (ServletHandler.java:473)
	    at org.seleniumhq.jetty9.server.session.SessionHandler.doScope (SessionHandler.java:1564)
	    at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope (ScopedHandler.java:166)
	    at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope (ContextHandler.java:1155)
	    at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle (ScopedHandler.java:141)
	    at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle (HandlerWrapper.java:132)
	    at org.seleniumhq.jetty9.server.Server.handle (Server.java:564)
	    at org.seleniumhq.jetty9.server.HttpChannel.handle (HttpChannel.java:317)
	    at org.seleniumhq.jetty9.server.HttpConnection.onFillable (HttpConnection.java:251)
	    at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:279)
	    at org.seleniumhq.jetty9.io.FillInterest.fillable (FillInterest.java:110)
	    at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run (ChannelEndPoint.java:124)
	    at org.seleniumhq.jetty9.util.thread.Invocable.invokePreferred (Invocable.java:128)
	    at org.seleniumhq.jetty9.util.thread.Invocable$InvocableExecutor.invoke (Invocable.java:222)
	    at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce (EatWhatYouKill.java:294)
	    at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run (EatWhatYouKill.java:199)
	    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:672)
	    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run (QueuedThreadPool.java:590)
	    at java.lang.Thread.run (<anonymous>:-1)

	----------------------------------------------------------------------
	Ran 1 test in 0.031s

	FAILED (errors=1)

**Comment by WahidAbdullahK** [comment] 2017-08-31 13:06
I am also facing this issue, from my debugging, it looks like `webdriver.remote.sessionid ` is not getting generated in my case. Buy other capabilities are generating.

```
[1] pry(#<#<Class:0x0000000046b540>>)> @browser.driver.capabilities['webdriver.remote.sessionid']
=> nil
```

**Comment by lmtierney** [comment] 2017-09-08 19:58
@Debanjan-B 
Since the latest IEDriverServer is w3c compatible, `platformName` needs to be in lowercase. I'd suggest trying with `win8` instead of `WIN8`, and if that doesn't work, see if `windows` even works.

**Comment by Debanjan-B** [comment] 2017-09-09 12:15
@lmtierney I am afraid. I wanted to pass `platform` as `WIN8` in the `DesiredCapabilities` not `platformName` as you pointed out.

**Comment by lmtierney** [comment] 2017-09-10 01:05
@Debanjan-B you should be passing `platformName` and not `platform` since IE `3.5` is w3c compliant. Since you did only send `platform` but `platformName` is in the stacktrace, there may be an underlying issue with the grid so I'll leave this open.

> As per the current W3C Specs, supported values for platformName key are linux, mac and windows

Read my comment in #4669 for that point

**Comment by Debanjan-B** [comment] 2017-09-11 09:41
Thanks @lmtierney 

A quick look at the recently released Selenium Java Client 3.5.3 still provides us the intelligence with **`cap.setPlatform(Platform.WIN8);`** which means **`platform`** is a valid choice.

![capability](https://user-images.githubusercontent.com/26503213/30268356-072795cc-9703-11e7-8af6-b006f666c904.png)


Additionally we can set the `platform` capability as well : 
![platform](https://user-images.githubusercontent.com/26503213/30268386-22a18088-9703-11e7-8006-658c3b1f9149.png)

**Comment by lmtierney** [comment] 2017-09-11 13:15
`platform` is still valid for non-w3c implemented webdrivers (e.g. Chrome). I will remove myself from this thread now however as I do not know enough about how the grid innards handle oss vs w3c for platform matching

**Comment by Debanjan-B** [comment] 2017-09-11 15:03
@lmtierney Since I started interacting in this forum your suggestions cleared a lot of my doubts and helped me to understand better. So irrespective of being aware or unaware, request to you to help us out.

**Comment by lmtierney** [comment] 2017-09-11 15:40
@Debanjan-B per https://github.com/SeleniumHQ/selenium/issues/4669#issuecomment-328541996 use `platformName` instead, and make it lowercase. If that still gives you issues then @barancev will probably need to take a look

**Comment by barancev** [comment] 2017-09-11 15:57
@Debanjan-B Please show your grid configuration, take a screenshot of http://localhost:4444/grid/console page with Configuration tab open.

**Comment by barancev** [comment] 2017-10-10 18:26
@Debanjan-B Please show your grid configuration, take a screenshot of http://localhost:4444/grid/console page with Configuration tab open.

**Comment by barancev** [comment] 2017-10-18 11:55
Closing the issue as there is no known way to reproduce it.

**Closed by barancev** 2017-10-18 11:55 UTC
Labels: C-py, R-awaiting answer
