### ISSUE TITLE
chrome will never get feedback after first TimeoutException happened 

### ISSUE THREAD

**Issue by yundongxiao** [SeleniumHQ/selenium#5890] opened 2018-05-13 01:54 UTC
## Meta -
OS:  
win7
Selenium Version:  

Browser Version:  

## Expected Behavior -
page can refresh or get again after timeoutException happen
Please help  , Thank you very much

## Actual Behavior -
no any responses in chrome 
no page loading / refreshing
even no response to driver.close

## Steps to reproduce -
Here is my API to load page with some times if timeout happen.

```
def try_to_load_page(page_url, try_times=5):
    while True:
        try:
            if try_times == 0:
                break
            if try_times % 2 == 0:
                old_handle = driver.window_handles #change to driver.get(url) or refresh() will always return 
                                                                  #timeoutException, and  it seems page didn't reload actually.
                script = "window.open('" + page_url + "');"
                driver.execute_script(script)                              #will timeout
                driver.switch_to.window(old_handle[-1])
                driver.close()
            else:
                driver.get(page_url)
            return True
        except TimeoutException:
            print "TimeoutException"
            try_times -= 1
            time.sleep(60)
        except ErrorInResponseException:
            print "ErrorInResponseException"
            try_times -= 1
            time.sleep(180)
```

**Comment by lmtierney** [comment] 2018-05-13 02:40
Possible duplicate of #5888. Either way, a bug with chromedriver.

Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list

**Closed by lmtierney** 2018-05-13 02:40 UTC
