### ISSUE TITLE
Firefox 38 breaks with WebDriver 2.45.0

### ISSUE THREAD

**Issue by niranjala** [SeleniumHQ/selenium#571] opened 2015-05-26 18:23 UTC
The webdriver 2.45 (FF) throws the following exception when trying to launch FF 38. 

org.openqa.selenium.WebDriverException: Error forwarding the new session cannot find : Capabilities [{browserName=firefox, version=, platform=WINDOWS, firefox_profile=UEsDBBQACAgIAJtyukYAAAAAAAAAA...}]
Command duration or timeout: 979 milliseconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: '0108M303077D', ip: '10.75.27.34', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.remote.RemoteWebDriver

**Comment by jleyba** [comment] 2015-05-26 18:37
Duplicate of #437

**Closed by jleyba** 2015-05-26 18:37 UTC

**Comment by niranjala** [comment] 2015-05-26 18:45
What is the resolution for this. I was not able to find a resolution at issue #437 either

**Comment by jleyba** [comment] 2015-05-26 19:06
Fixed and will be included in the next release

**Comment by niranjala** [comment] 2015-05-26 19:36
Thank you for your reply. Which release will this be 2.46 ??, and do you know when this will come out ..a rough time frame

**Comment by ddavison** [comment] 2015-05-26 19:39
when they get to it :+1:  remember you can always build your own with `./go release` if this is a blocker for you

**Comment by niranjala** [comment] 2015-05-26 19:48
It is a blocker as all our test suites on FF does not work... but if they are targeting a release soon I would rather wait for it .. thus the question for a time frame

**Comment by ipennino** [comment] 2015-07-10 13:03
I had the same problem. 
The version 2.46 of WebDriver actually solved it but, in my case, brought a less deterministic issue (about the staleness of web elements).

Waiting for a time frame big enough to work out the new issue introduced by 2.46 in my project, I am still working with 2.45 and firefox > 37 adding the following instruction before the initialization of the driver:

System.setProperty("webdriver.firefox.profile", "default");

This avoided the issue described here and in #437
