### ISSUE TITLE
moveToElement is not working

### ISSUE THREAD

**Issue by SantoshSarma** [SeleniumHQ/selenium#2552] opened 2016-08-02 10:31 UTC
while executing below command it is throwing exception

> new Actions(driver).moveToElement(locator).perform();

**Exception** 
```
org.openqa.selenium.UnsupportedCommandException: POST /session/51fc473e-8059-ac4d-87bf-f69c78e95fd3/moveto did not match a known command (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1 milliseconds
**Build info: version: '3.0.0-beta1', revision: '8e4315c', time: '2016-07-28 18:04:05 -0700'
System info: host: 'test', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_91'**
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, loggingPrefs={browser=ALL}, appBuildId=20160726073904, version=, platform=MAC, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, browserVersion=48.0, platformVersion=15.3.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Darwin, device=desktop, firefox_profile=UEsDBBQACAgIAM51AkkAAAAAAAAAA..., unexpectedAlertBehaviour=accept}]
Session ID: 51fc473e-8059-ac4d-87bf-f69c78e95fd3
	at sun.reflect.GeneratedConstructorAccessor9.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:683)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteMouse.mouseMove(RemoteMouse.java:89)
	at org.openqa.selenium.interactions.MoveMouseAction.perform(MoveMouseAction.java:39)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:50)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:373)
```

P.S : the same is happening with dragAndDrop command also

> (new Actions(driver)).dragAndDrop(element1, element2).perform();

**Comment by lukeis** [comment] 2016-08-02 13:28
Duplicate of #2285

**Closed by lukeis** 2016-08-02 13:28 UTC

**Comment by DDNoida** [comment] 2016-11-04 12:37
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


driver = webdriver.Firefox()
driver.get("http://www.tradeindia.com/Seller-3077216-A-B-Shenzhen-Battery-Co-Ltd-/")

wait = WebDriverWait(driver, 10)
accept = wait.until(EC.element_to_be_clickable((By.ID, "h2h_form")))
closePopup = driver.find_element_by_xpath("/html/body/div[3]/div/table/tbody/tr[3]/td/table/tbody/tr[1]/td[2]/table/tbody/tr[1]/td/div/div[1]/div[1]")

#actions = ActionChains(driver)
#actions.move_to_element(closePopup).click()

menu = driver.find_element_by_css_selector("#h2h_form > h2")
hidden_submenu = driver.find_element_by_css_selector(".close-btn")
actions = ActionChains(driver)
driver.implicitly_wait(10)
actions.move_to_element(hidden_submenu)

actions.click(hidden_submenu)
actions.perform()

Traceback (most recent call last):
  File "D:\Python Files\Selenium\Trade_subSite.py", line 25, in <module>
    actions.perform()
  File "C:\Users\DDSHARMA\Documents\pymote_env\lib\site-packages\selenium\webdriver\common\action_chains.py", line 74, in perform
    action()
  File "C:\Users\DDSHARMA\Documents\pymote_env\lib\site-packages\selenium\webdriver\common\action_chains.py", line 225, in <lambda>
    Command.MOVE_TO, {'element': to_element.id}))
  File "C:\Users\DDSHARMA\Documents\pymote_env\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DDSHARMA\Documents\pymote_env\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: POST /session/db99985b-4532-43a6-8b6c-b798c9694c64/moveto did not match a known command
still issue is not solved

**Comment by ranjprashant** [comment] 2016-11-18 09:42
I am getting the same issue on using new Actions(driver).moveToElement(tempHeaderElement).perform();

Log:
org.openqa.selenium.UnsupportedCommandException: POST /session/58fec78f-ac07-4815-87ab-2bcd6686a200/moveto did not match a known command
Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700'
System info: host: 'DC4-QVM-TRBW-02', ip: '10.111.106.196', os.name: 'Windows Server 2012', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], profile=UEsDBBQACAgIAFsjckkAAAAAAAAAAAAAAAAHAAAAdXNlci5qc61XTW/jNhC991csfGqBmE023cv25F0nQIFgUyQbZA8BCJoaWYwpkuVQlv3vO6Ss+EuWnHZPlugZUjPz3pthheC585D/Opp5W9MbQ5FDelZmzkqha+GBgREzDdno4kMuNMJvf/5SbT0zEcjGWR+iSwFCh6J5Z2S0VHLAvz25AO3AT5xDFo9d4wQXLLdewtl+Bpb0RG4olvDdThUuyHcknNNKiqCs+b3E2vrs4sPumsTlxYcAq9A87f61NBkrcQwrCfr4H+vArEpNH1mKgGOb5xRtZmVVgqHo6TtFhgVAKDVLvxcdeztbg3dWmbB/gMvy/YXV+HAJ0x7Hhhr3F0pMAYz2E2ggUC4WrAjBMVcoLNbj+LcTiGMNZh4Kyt7HT5+68x6Do58MAsgA2a3yGCYEAqljwYKvDnFiSwLUisvC2xI4Sq9c4L4yPKgyulxfdh8UxAwZ4dDcm6/a4gAcMlsbbQWlVhgxj4gubP1cgHkkmEaIdrs7+igXMB7GS5sJPQB6WAZrNTLwniBKpbB6F+fH4aOaG2soayWUM/CP6RX7Y0FAjGUOlkjoAQlXPKcP5dILLPp9tTKLBFBOwAZvhI7FfDd181jWh8p0H1bDLPOKSMeFlEDlrAxFjgQHLsEH7M5EszUyXBvJ4trm8X+W8M1dodNiDdnN1eXjN0uIjJD5o9uYlrJ786wMHYpXl4xo6O3Tw13SjZmtwueZFmYxOsZykygutOavyCPBXOJkZ8wrp6iMZMvqQgXQCgNt8E+l/CmERXgtVGAblrapoOAixjoPeSu9oIITsfohjDGZlWMFsdHR3rwGLSMzKx+hMhoN8Cu3mvh/R5EcAytCziTossoRyoAZqkO+fiKTM+nbPkxV9BhNP7+8fH/4widVsGVStfS+fb31ooSYKf4N6peX1v2wcKcRX7lof9ObMpCVV2FNrNBATwyDVzJw69VcGe4sKe66Pz4DNUkM2+S4B2F7H9rszOLiYzUrVZKFv9PiJBHvvObcuU1vxG9KtAFLBApZnlDqreZQmHXi1DE2qEuSHYxF0+m1rflszTPIRaXDCcHYpF2i22D6nT2AbJ7bz+nwO4ZrL3NaahKPSc2DX7OmeyT7j0O2Zw1DRxHI2PmiBk6tGYj+5uluwq6Z2ALjOKWvYimaDtzbtA7L32pFP3aPY/bwmoaE3kMaasTt+3O0Uy1B9J82ivgoCXhRfK8uT/WoZlduSC+WwGlWNCc6VMfkcU+oPle5GijfJn38idq1E/dMW7lITeQsNCEIL4sNtoeiKFnDXJZVpTsLHdvIf6pWk0CcRcc93FsqtFdZd4M80u9D4b7unpAbEo5b5SI2hGpgdNvYnlDlzSg8PAPvDFiYxr/tgEXqXZ3qpjupixTpNtrRANuMLmnQ+st8bcbZ82reClRO1x4cHtJi6JsZhqdOkVEdzJyn+ndP5ln+iq3PmUDcHRwnmiZRujqQQmsYgj/d0mhGkwXIxbSh8Zfmn/fPUExkmYppFQOtvvPq/V+v3NrO53FxcyXpbe47gpIijikifs6Ujhwxal4EfWKc2XFtT3yXUrQFEk1xbn7cDAvsUbJbrtMtOjRdcRRvVR4OErwdvuMljLhLV6mB6XurnDrHyjUD4nYu/hdQSwcIZ7FvAMMEAAA5EQAAUEsBAhQAFAAICAgAWyNySWexbwDDBAAAOREAAAcAAAAAAAAAAAAAAAAAAAAAAHVzZXIuanNQSwUGAAAAAAEAAQA1AAAA+AQAAAAA}, appBuildId=20161104212021, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=8104, browserVersion=50.0, platformVersion=6.2, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt}]

**Comment by DDNoida** [comment] 2016-11-18 10:58
Sir
Perform is not working as I know from my limited knowledge 
Thanks
DD Sharma

**Comment by natgho-reidin** [comment] 2017-01-04 14:51
I have same problem, have any solution?

**Comment by drewrice2** [comment] 2017-01-11 21:26
Running into a similar error upon calling webdriver.switch_to_active_element()

**selenium.common.exceptions.WebDriverException: Message: POST /session/4168ca49-0bdc-4445-8f5e-870f869fb580/element/active did not match a known command**

**Comment by handles-aus** [comment] 2017-01-16 07:36
Same here...
selenium.common.exceptions.WebDriverException: Message: POST /session/b33fdc0b-17a9-4636-98f3-f074ee2eae0b/alert/credentials did not match a known command

**Comment by ddavison** [comment] 2017-01-16 12:18
@handles-aus , @drewrice2 , @natgho-reidin , @ranjprashant , @DDNoida ,

as lukeis has pointed out, the issue is known about. please refer to the issue #2285.

locking this issue.
