### ISSUE TITLE
Firefox 47 does not work with 2.53 version

### ISSUE THREAD

**Issue by murdog05** [SeleniumHQ/selenium#2257] opened 2016-06-10 13:11 UTC
## Meta -
OS:  
Windows 10
Selenium Version:  
2.53.0
Browser:  
FireFox

Browser Version:  
47.0.0

## Expected Behavior -
When I run my test I expect firefox to open and the test should navigate to my system's login page.

## Actual Behavior -
Firefox either won't open or it will crash soon after opening.

## Steps to reproduce -
1. Upgrade for FIrefox 47
2. Run any test that uses firefox web driver.

NOTE: downgrading back to Firefox 46.0.1 fixed the issue (for now).

**Comment by davehunt** [comment] 2016-06-10 13:25
Another duplicate of #2110

**Closed by davehunt** 2016-06-10 13:25 UTC

**Comment by buminda** [comment] 2016-06-14 04:51
Yes, the browser hangs up saying "Firefox has stopped working".

**Comment by vikrant4224** [comment] 2016-06-14 14:26
Hi can anyone please show me how to downgrade to version 46.

**Comment by parvatis** [comment] 2016-06-14 14:56
I have to downgrade firefox by one version because of the same issue. where to find v46 of firefox? I don't see on it on there website. Please suggest.

**Comment by murdog05** [comment] 2016-06-14 15:09
https://support.mozilla.org/en-US/kb/install-older-version-of-firefox

**Comment by parvatis** [comment] 2016-06-14 18:45
Got the older version. Thank you.

**Comment by orbennatan** [comment] 2016-06-15 06:45
Downgrading to 46 was not stable enough. The crashes started happening again after 2 days of working, so I downgraded again to 45.

**Comment by marleitao** [comment] 2016-06-16 14:52
In case you want to know what's going on https://www.mozilla.org/en-US/firefox/47.0/releasenotes/ know issue!

**Comment by orbennatan** [comment] 2016-06-16 15:05
I did, I may be totally wrong about it, but if I were Firefox I would not
release anything before some major plug in have already made themselves
ready with a release. You can't just break everyone. The total number of
hours going away are incalculable. I myself spent a couple to debut what
was happening to me. Selenium seems to me a pretty major platform that is
very popular with people, so just breaking it just doesn't cut it for me.
BTW, quite interesting, the developer version of FF did not work for me as
well together with selenium.
Anyhow, I moved to 45 and will keep using FF because it is still the best
choice for my project. I would love to be on some mailing list telling me
when this particular problem is resolved.
Thanks.




*Or Bennatan - Opera singer, bass <http://www.harzaa.com>*0544997092
------------------------------------------------
Look at our vacation property: stayhere.co.il שקט בזכרון
<http://www.stayhere.co.il>

**Comment by Mahimalokre** [comment] 2016-06-20 07:07
I am also degraded firefox version to 46.0.1 but then also exception is coming frequently 5-6 times then once it launch firefox but if we restart system then also exception is coming so what will be the solution to handle exception because i am not able to run my selenium script properly.
I am using 2.53 selenium webdriver in windows 10(32 bits).

Please help if someone knows solution because i am stuck here from long time and tried so many ways but then also still exception is coming.

**Comment by ljgww** [comment] 2016-06-28 06:46
When downgrading to 46.0.1 it is important to understand that firefox will silently upgrade itself to V.47. Stopping silent upgrade seems to be difficult (firefox will find any possible way to upgrade itself to v.47).

Suggested path for ff47 seems to be moving to marionette driver. But, I have found out that latest marionette (wires) crashes on win7, therefore in my case it is useless. Also tried to do alternatives e.g. using web driver with ff Nightly and ff Developer versions - but results are not great, some functionality fails.

**Comment by myzrahi** [comment] 2016-06-28 15:15
For me, the problems stopped the moment I downgraded to 46.0.1. An obvious but important thing, make sure your settings do not auto-update you to version 47.0 :-)

**Comment by ddingemanse4c** [comment] 2016-08-25 06:57
I also seeing issues with starting Firefox (46) combined with selenium 2.53.1 with a non-standard-user profile in an automated test run in a virtual image (base on Windows 8.1).
The "Firefox has stopped working" problem is solved temporarily by rebooting the virtual image, but after a while returns. Although we heavily use Chome and chromedriver as browsers under test, on a few occasions we need to use Firefox which then crashes and consequently blocks the entire test run.

I don't have this problem starting Firefox as a user.

Firefox is definitely unstable dealing with (temporary) profiles and needs to improve

**Comment by zakalei** [comment] 2016-08-27 12:36
Firefox just released 47.1 which fixes this bug. 
It works now but just opens two tabs, one is blank page, another one is the proper page. 

windows 10 64 bit
selenium-webdriver 25.3.3
Firefox 47.1

**Comment by Anushr1** [comment] 2016-12-19 09:15
ghj
