### ISSUE TITLE
[🚀 Feature]: Selenium Manager - Provide an easy way to execute selenium-server from bindings

### ISSUE THREAD

**Issue by lprimak** [SeleniumHQ/selenium#13361] opened 2023-12-26 07:22 UTC
### Feature and motivation

Currently, it's possible to call `SeleniumManager.getInstance().getDriverPath()` to get a path to the driver.
What that does is actually downloads the `selenium-manager` executable and I can call it with `--grid` option to download  the selenium-server JAR.

There needs to be an easier way to download and get the path of the JAR `selenium-server-4.16.1.jar`.

### Usage example

Currently, I am forced to write code like this to achieve this goal:

```
    static Path downloadManager() {
        Path managerPath = getManagerPath();
        managerPath.getParent().toFile().mkdirs();
        System.out.printf("ChromeDriver path: %s, Selenium Manager Path: %s\n",
                SeleniumManager.getInstance().getDriverPath(new ChromeOptions(), false).getDriverPath(),
                managerPath);
        return managerPath;
    }

    static private Path getManagerPath() {
        String cachePath = "~/.cache/selenium".replace("~", System.getProperty("user.home"));
        String cachePathEnv = System.getenv("SE_CACHE_PATH");
        if (cachePathEnv != null) {
            cachePath = cachePathEnv;
        }
        Path cacheParent = Paths.get(cachePath);
        String binaryName = "selenium-manager" + (Platform.getCurrent().is(Platform.WINDOWS) ? ".exe" : "");
        var releaseLabel = new BuildInfo().getReleaseLabel();
        int lastDot = releaseLabel.lastIndexOf(".");
        String minorVersion = releaseLabel.substring(0, lastDot);
        String seleniumManagerVersion = "0." + minorVersion;
        return Paths.get(cacheParent.toString(), String.format("/manager/%s/%s", seleniumManagerVersion, binaryName));
    }
}
```

Then execute `selenium-manager` from further Java code to download the selenium server JAR and execute that.
This is error-prone and needlessly copies existing code from the bindings.

**Comment by titusfortner** [comment] 2023-12-26 14:12
There's two things. 

First, this specific request is a duplicate of https://github.com/SeleniumHQ/selenium/issues/12305. At this point it is also dependent on doing this: https://github.com/SeleniumHQ/selenium/issues/13022. It will happen, soon-ish, not sure exact timeframe.

The second thing, is if you're in Java, you can use the jar directly...

```
import org.openqa.selenium.grid.Main;
```
Use it like this: https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/java/src/test/java/dev/selenium/BaseTest.java#L76-L95

**Closed as not planned by titusfortner** 2023-12-26 14:12 UTC
Labels: I-enhancement, A-needs-triaging

**Comment by lprimak** [comment] 2023-12-27 06:35
Thanks Titus, that helped!
