### ISSUE TITLE
BiDi tests failing with Firefox browser (Ruby)

### ISSUE THREAD

**Issue by MatzFan** [SeleniumHQ/selenium#13080] opened 2023-11-01 14:43 UTC
### What happened?

I've followed the build instructions for Ruby and when I run the integration tests with the `--define browser=firefox` flag the following tests fail:-
`//rb/spec/integration/selenium/webdriver:bidi`
`//rb/spec/integration/selenium/webdriver/bidi:browsing_context`
`//rb/spec/integration/selenium/webdriver/bidi:log_inspector`

10 specs fail in the three tests and all of them are either `TimeoutError` or `Errno::ECONNREFUSED` at 127.0.0.1:9222 - which makes me think there is something wrong with my build environment.

I've shared the log output from the first test with an example of both failure types.

### How can we reproduce the issue?

```shell
bazel test //rb/spec/integration/... --define browser=firefox # with my build environment
```

### Relevant log output

```shell
INFO: From Testing //rb/spec/integration/selenium/webdriver:bidi:
==================== Test output for //rb/spec/integration/selenium/webdriver:bidi:

Running Ruby specs:

 browser: firefox
  driver: firefox
 version: 115.4.0
platform: linux
      ci: 
    ruby: ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]

FF..

Failures:

  1) Selenium::WebDriver::BiDi gets session status
     Failure/Error: status = driver.bidi.session.status

     Selenium::WebDriver::Error::TimeoutError:
       timed out after 30 seconds
     # ./rb/lib/selenium/webdriver/common/wait.rb:73:in `until'
     # ./rb/lib/selenium/webdriver/common/websocket_connection.rb:63:in `send_cmd'
     # ./rb/lib/selenium/webdriver/bidi.rb:45:in `send_cmd'
     # ./rb/lib/selenium/webdriver/bidi/session.rb:31:in `status'
     # ./rb/spec/integration/selenium/webdriver/bidi_spec.rb:34:in `block (2 levels) in <module:WebDriver>'

  2) Selenium::WebDriver::BiDi can navigate and listen to errors
     Failure/Error: log_inspector = BiDi::LogInspector.new(driver)

     Errno::ECONNREFUSED:
       Connection refused - connect(2) for "127.0.0.1" port 9222
     # ./rb/lib/selenium/webdriver/common/websocket_connection.rb:150:in `initialize'
     # ./rb/lib/selenium/webdriver/common/websocket_connection.rb:150:in `new'
     # ./rb/lib/selenium/webdriver/common/websocket_connection.rb:150:in `socket'
     # ./rb/lib/selenium/webdriver/common/websocket_connection.rb:76:in `process_handshake'
     # ./rb/lib/selenium/webdriver/common/websocket_connection.rb:41:in `initialize'
     # ./rb/lib/selenium/webdriver/bidi.rb:28:in `new'
     # ./rb/lib/selenium/webdriver/bidi.rb:28:in `initialize'
     # ./rb/lib/selenium/webdriver/common/driver_extensions/has_bidi.rb:31:in `new'
     # ./rb/lib/selenium/webdriver/common/driver_extensions/has_bidi.rb:31:in `bidi'
     # ./rb/lib/selenium/webdriver/bidi/log_inspector.rb:49:in `initialize'
     # ./rb/spec/integration/selenium/webdriver/bidi_spec.rb:41:in `new'
     # ./rb/spec/integration/selenium/webdriver/bidi_spec.rb:41:in `block (2 levels) in <module:WebDriver>'

Finished in 1 minute 5.73 seconds (files took 0.36799 seconds to load)
4 examples, 2 failures

Failed examples:

rspec ./rb/spec/integration/selenium/webdriver/bidi_spec.rb:33 # Selenium::WebDriver::BiDi gets session status
rspec ./rb/spec/integration/selenium/webdriver/bidi_spec.rb:39 # Selenium::WebDriver::BiDi can navigate and listen to errors
```

### Operating System

LMDE 6 (Faye) built on Debian 12

### Selenium version

selenium-webdriver (4.14.0) gem

### What are the browser(s) and version(s) where you see this issue?

Firefox 115.4.0esr

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 118.0.5993.88,  geckodriver 0.33.0

### Are you using Selenium Grid?

n/a

**Comment by MatzFan** [comment] 2023-11-01 17:32
Further info: If I run each of the tests separately they pass*, so is the problem related to their parallel running?

*except for:
```
INFO: From Testing //rb/spec/integration/selenium/webdriver:bidi:
==================== Test output for //rb/spec/integration/selenium/webdriver:bidi:

Running Ruby specs:

 browser: firefox
  driver: firefox
 version: 115.4.0
platform: linux
      ci: 
    ruby: ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]

.F..

Failures:

  1) Selenium::WebDriver::BiDi can navigate and listen to errors
     Failure/Error: expect(info.navigation_id).not_to be_nil

       expected: not nil
            got: nil
     # ./rb/spec/integration/selenium/webdriver/bidi_spec.rb:48:in `block (2 levels) in <module:WebDriver>'

Finished in 24.49 seconds (files took 0.22998 seconds to load)
4 examples, 1 failure

Failed examples:

rspec ./rb/spec/integration/selenium/webdriver/bidi_spec.rb:39 # Selenium::WebDriver::BiDi can navigate and listen to errors

```

**Comment by titusfortner** [comment] 2023-11-01 19:07
duplicate of #13079 
Yes, I believe it is a parallel issue as I replied there.

**Closed as not planned by titusfortner** 2023-11-01 19:07 UTC
Labels: I-defect, A-needs-triaging

**Comment by titusfortner** [comment] 2023-11-01 19:23
That failure is a result of using 115 instead of 118, which I guess is a good point, I should put stable for the browserVersion on everything...
