### ISSUE TITLE
Element.clear() doesn't work on React elements

### ISSUE THREAD

**Issue by jklingen92** [SeleniumHQ/selenium#6863] opened 2019-01-17 19:07 UTC
## 🐛 Bug Report

The WebElement clear() command doesn't work on certain inputs.

I believe it is related to React Components.

## To Reproduce
Run the following script

```
from selenium import webdriver
from time import sleep


driver = webdriver.Chrome() #Can be Firefox as well
driver.get('https://reactjs.org/')

name_field = driver.find_element_by_id("algolia-doc-search")
print(name_field.get_property('value'))

name_field.send_keys('hello')
print(name_field.get_property('value'))

sleep(1)

name_field.clear()
print(name_field.get_property('value'))

driver.close()
```

Run the script. It will type 'hello' into the search bar, pause, and then send the clear command. The search bar will remain filled.

## Expected behavior

clear() should empty the search bar.

## Test script or set of commands reproducing this issue
`python tmp.py`

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment
OS: Linux pop-os 4.18.0-13-generic
Browser: Chrome
Browser version: 71.0.3578.98 (64-bit)
Browser Driver version: ChromeDriver 2.45
Language Bindings version: Python 3.141.0

-- or --

OS: Linux pop-os 4.18.0-13-generic
Browser: Firefox
Browser version: 64.0
Browser Driver version: GeckoDriver 0.23.0
Language Bindings version: Python 3.141.0

**Comment by ckzgraphics** [comment] 2019-01-23 06:46
You may review this one- [6741](https://github.com/SeleniumHQ/selenium/issues/6741)

**Comment by p0deje** [comment] 2019-01-23 07:33
Duplicate of #6741

**Closed by p0deje** 2019-01-23 07:33 UTC
