### ISSUE TITLE
executeCdpCommand is not present in remote_connection.py#L114

### ISSUE THREAD

**Issue by abdelrahman-t** [SeleniumHQ/selenium#7959] opened 2020-01-25 17:14 UTC
## 🐛 Bug Report

Executing "executeCdpCommand" results in the following exception
```
File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 316, in execute
response = self.command_executor.execute(driver_command, params)
File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/remote_connection.py", line 340, in execute
command_info = self._commands[command]
KeyError: 'executeCdpCommand'
```
pip freeze | grep "selenium":  selenium==4.0.0a3

## To Reproduce

```
session = webdriver.Remote(command_executor=f'{SELENIUM}:4444/wd/hub',
                                               options=SELENIUM_OPTIONS,
                                               desired_capabilities=webdriver.DesiredCapabilities.CHROME) 

session.execute(
    'executeCdpCommand',
    {
        'cmd': 'Page.addScriptToEvaluateOnNewDocument',
        'params':
        {
            'source': '''
                Object.defineProperty(navigator, "webdriver", {
                get: () => undefined
                })
            '''
        }
    }
)
```
Detailed steps to reproduce the behavior:

### Background
It seems that the base class "RemoteConnection" class is used for all connection regardless of the browser passed in desired_capabilities, So for instance IF the user passes ```desired_capabilities=webdriver.DesiredCapabilities.CHROME``` while initializing the session, The generic RemoteConnection is still used, despite not supporting the commands specific to Chromium.

### Expectation
I expect a suitable RemoteConnection subclass (ChromiumRemoteConnection, FirefoxRemoteConnection, SafariRemoteConnection, etc...) to be used based on the specified desired_capabilities. 

### Workaround
Current workaround requires explicitly passing a RemoteConnection object (of ChromiumRemoteConnection subclass), Which seems redundant given that I have explicitly specified Chrome/Chromium as being the desired driver)
```
session = webdriver.Remote(command_executor=ChromiumRemoteConnection(f'{SELENIUM}:4444/wd/hub'),
                            desired_capabilities=webdriver.DesiredCapabilities.CHROME,
                            options=SELENIUM_OPTIONS)
```

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

**Comment by Dude-X** [comment] 2020-02-06 05:52
Yes this is problem with RemoteConnection when used with the standard `Remote` convenience class. This will be a problem for any browser subclass that has subtypes of Remote objects because class inheritance is agnostic of its children. The fix for this is to add code to introspect the browser type and patch in the right subclass to use. The hard part is to make something generic in this regard. We can do the simple approach of just substituting the subtype if necessary. 

As far as I know, we have subclasses for RemoteConnection, and RemoteWebElement.

**Comment by abdelrahman-t** [comment] 2020-02-06 22:15
Yes, there are ChromiumRemoteConnection, FirefoxRemoteConnection, SafariRemoteConnection, ...
Should be just a matter of inspecting the desired_capabilities (or browser-specific options classes since **desired_capabilities is now deprecated**), and choosing the appropriate RemoteConnection subclass.

**Comment by abdelrahman-t** [comment] 2020-02-06 22:21
I am happy to submit a pull request for this btw.

**Comment by AutomatedTester** [comment] 2020-02-07 08:03
This is in https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/chromium/webdriver.py#L128

At the moment only Chromium based browsers can do this command so I don’t think it should be in ‘remote_connection.py’.

What is the use case we’re missing?

**Comment by abdelrahman-t** [comment] 2020-02-07 13:08
Problem arises when [class Remote](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#L98) is used which uses a generic RemoteConnection class that does not support chromium-specific commands like "executeCdpCommand".

What I am proposing is instead of using the generic RemoteConnection class (used [here](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#L146)), An appropriate RemoteConnection (ChromiumRemoteConnection) class is used based on the passed browser-specific options classes or desired_capabilities.

**Comment by AutomatedTester** [comment] 2020-02-07 13:13
Oh I see. Happy to take a PR and we can discuss the technicalities there

**Comment by abdelrahman-t** [comment] 2020-02-07 13:15
Great! I will submit a PR.

**Comment by AutomatedTester** [comment] 2020-03-25 21:39
Duplicate of #7914

**Closed by AutomatedTester** 2020-03-25 21:39 UTC
Labels: C-py
