### ISSUE TITLE
Unexpected modal dialog - Python - Firefox default driver

### ISSUE THREAD

**Issue by FrnkVieira** [SeleniumHQ/selenium#1096] opened 2015-10-02 12:21 UTC
Unexpected modal dialog (text: 83) The alert could not be closed. The browser may be in a wildly inconsistent state, and the alert may still be open. This is not good. If you can reliably reproduce this, please report a new issue at https://code.google.com/p/selenium/issues/entry with reproduction steps. Exception message: TypeError: a.document.getElementsByTagName(...)[0].getButton is not a function"

Crashes really fast after loading the following URL and sending any JS to scroll the page:
http://img.mediaplex.com/content/0/12255/130971/EPSILON_NA_NA_BR_CONS_BAU_redirect.html?mpck=adfarm.mediaplex.com%2Fad%2Fck%2F12255-130971-25987-11%3FVEN1%3D11156994%26VEN2%3D100727703%26SUB%3D185694727%26CID%3D292377%26LID%3D5601280%26dgc%3DEM%26url_str%3Dhttp%253A%252F%252Fwww.dell.com%252Fbr%252Fp%252Fdm-campaign-deals-3%257C%26mpcr%3D36453455%26mpcrset%3Droot&VEN1=11156994&VEN2=100727703&SUB=185694727&CID=292377&LID=5601280&dgc=EM&url_str=http%3A%2F%2Fwww.dell.com%2Fbr%2Fp%2Fdm-campaign-deals-3%7C

**Comment by lukeis** [comment] 2015-10-02 16:27
I could not reproduce that error:

```
>>> from selenium import webdriver as w
>>> d = w.Firefox()
>>> d.get("http://img.mediaplex.com/content/0/12255/130971/EPSILON_NA_NA_BR_CONS_BAU_redirect.html?mpck=adfarm.mediaplex.com%2Fad%2Fck%2F12255-130971-25987-11%3FVEN1%3D11156994%26VEN2%3D100727703%26SUB%3D185694727%26CID%3D292377%26LID%3D5601280%26dgc%3DEM%26url_str%3Dhttp%253A%252F%252Fwww.dell.com%252Fbr%252Fp%252Fdm-campaign-deals-3%257C%26mpcr%3D36453455%26mpcrset%3Droot&VEN1=11156994&VEN2=100727703&SUB=185694727&CID=292377&LID=5601280&dgc=EM&url_str=http%3A%2F%2Fwww.dell.com%2Fbr%2Fp%2Fdm-campaign-deals-3%7C")
>>> d.execute_script("window.scrollTo(0,1000)")
```

can you provide some kind of script to reproduce?

**Comment by lukeis** [comment] 2015-10-02 22:20
closing for now, will reopen when a way to reproduce is provided

**Closed by lukeis** 2015-10-02 22:20 UTC
