### ISSUE TITLE
selenium-2.45.0 is not compatible with phantomjs-2.0.0

### ISSUE THREAD

**Issue by sarbbottam** [SeleniumHQ/selenium#375] opened 2015-03-26 19:04 UTC
Please refer the update section at [Webdriver unable to create session with phantomjs](http://stackoverflow.com/questions/29219075/webdriver-unable-to-create-session-with-phantomjs/29221466#29221466)

**Comment by lukeis** [comment] 2015-03-26 20:59
please provide clear steps to reproduce here, linking to stackoverflow is not a good idea as any content there can quickly be edited / deleted and lost from scope of this issue.

Also, I don't see how this is selenium's issue, and rather an issue that should be logged with phantomjs / ghostdriver.

(closing for now until adequate reproducibility is posted here)

**Comment by sarbbottam** [comment] 2015-03-27 00:31
Came across [Issue 8102:PhantomJS Doesn't Work on Selenium Grid 2.44.0](https://code.google.com/p/selenium/issues/detail?id=8102).

[Comment #5](https://code.google.com/p/selenium/issues/detail?id=8102#c5) states
>> We incorporate the fixed PhantomJSDriver as soon as it is released.

Does this imply [ghostdriver](https://github.com/detro/ghostdriver) need to update the PhantomJSDriver?

**Comment by lukeis** [comment] 2015-03-27 02:56
Yes, ghostdriver needs to update their Java client bindings.

**Comment by barancev** [comment] 2015-03-27 13:40
Selenium 2.45 incorporates an updated (inofficial) release of PhantomJsDriver so the issue 8102 resolved.

I bet this one is a different issue especially because downdrading PhantomJS helps.

**Comment by lukeis** [comment] 2015-03-27 15:27
@barancev why did you re-open, there's still insufficient information in this issue. I still don't see how this is our issue vs. phantomjsdriver's.

**Comment by sarbbottam** [comment] 2015-03-27 18:02
Steps to reproduce:

Please refer the instruction to setup protractor and write a basic test at http://angular.github.io/protractor/#/

Once you are done with the above steps.

Install ``phantomjs`` locally via ``npm`` https://www.npmjs.com/package/phantomjs

```
npm install phantomjs
```

It will install ``phantomjs-1.9.8``

Update the ``conf.js`` with the below content.

```
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['todo-spec.js'],
  capabilities: {
    'browserName': 'phantomjs',
    'phantomjs.binary.path': require('phantomjs').path
  }
};
```

Now run the test again with
```
protractor conf.js
```

You will find all the test are passing.

----

Now remove the installed the locally installed ``phantomjs``

```
npm remove phantomjs
```

Clone the **phantomjs npm wrapper** repository from https://github.com/Medium/phantomjs

Update the ``exports.version`` at https://github.com/Medium/phantomjs/blob/master/lib/phantomjs.js#L29 to ``2.0.0``.

Now navigate back to the **test directory** created while setting up protractor.

And install ``phantomjs`` for the local repository.

```
npm i path/to/phantomjs/directroy
```

Now run the test again with
```
protractor conf.js
```

Following error will be displayed:

```sh
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'rushpress-lm', ip: '10.73.199.247', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.8.0_25'
Driver info: driver.version: unknown
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:175)
    at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:111)
    at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:88)
    at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:108)
    at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:57)
    at org.openqa.12:41:41.059 WARN - Exception: org.openqa.selenium.browserlaunchers.Proxies
```

**Comment by lukeis** [comment] 2015-03-27 21:51
is that a standard selenium server standalone used? 

I still don't see concise reproduction steps here... (and no... i'm not going to load up protractor to attempt to reproduce this issue) unless someone else seems willing?

What I'm looking for here is something along the lines of run selenium-server-standalone-2.45.0.jar with phatonmjs (version) on the system path, then attempt to start a new Remote webdriver for phantomjs.

I'm currently able to (on OSX) Run Selenium standalone 2.45 with PhantomJS 2.0.0 and successfully launch a new remote webdriver / navigate to google / get the title (using python).

So... I'm not able to reproduce.

**Comment by sarbbottam** [comment] 2015-03-27 23:02
Let me try it with [WebDriverJS](https://code.google.com/p/selenium/wiki/WebDriverJs) and update the thread.

**Comment by scott2449** [comment] 2015-03-28 14:02
Just to backup @sarbbottam I agree that I could not get it to work with 2.0.0 no matter how hard I tried it just hung and the phantom process did not even open. I can come up with a concise reproduction if @sarbbottam can't get around to it. My first focus is #378 though ;) Let me know how either is going, since I am doing this for work I can definitely devote time to PRs if either turn out to be lower priority or a non trivial amount of work :smile:

**Comment by barancev** [comment] 2015-03-28 15:30
OK, I was wrong reopening it, according to the exception message you're on 2.44 yet:

    Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'

**Closed by barancev** 2015-03-28 15:30 UTC

**Comment by sarbbottam** [comment] 2015-03-28 20:05
@barancev, sorry about copy/pasting the ``exception log`` from the [stackoverflow post](http://stackoverflow.com/questions/29219075/webdriver-unable-to-create-session-with-phantomjs/29221466).

Please find the ``exception log`` w.r.t ``selenium-2.45.0`` below:

```sh
13:03:02.980 INFO - Executing: [new session: Capabilities [{phantomjs.binary.path=/Users/sarbbo/GitHub/protractor/node_modules/phantomjs/lib/phantom/bin/phantomjs, count=1, browserName=phantomjs}]])
13:03:02.996 INFO - Creating a new session for Capabilities [{phantomjs.binary.path=/Users/sarbbo/GitHub/protractor/node_modules/phantomjs/lib/phantom/bin/phantomjs, count=1, browserName=phantomjs}]
13:03:03.007 INFO - executable: /Users/sarbbo/GitHub/protractor/node_modules/phantomjs/lib/phantom/bin/phantomjs
13:03:03.008 INFO - port: 38547
13:03:03.008 INFO - arguments: [--webdriver=38547, --webdriver-logfile=/Users/sarbbo/phantomjsdriver.log]
13:03:03.008 INFO - environment: {}
13:03:23.273 ERROR - org.apache.commons.exec.ExecuteException: Process exited with an error: 137 (Exit value: 137)
13:03:23.277 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'rushpress-lm', ip: '192.168.0.12', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.8.0_25'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:175)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:111)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:88)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:109)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:57)
	at org.openqa.s13:03:23.286 WARN - Exception: null
```

**Comment by sarbbottam** [comment] 2015-03-28 20:07
The issue may be with ``pahntomjs-2.0.0``, Please refer https://github.com/ariya/phantomjs/issues/13116.

**Comment by sarbbottam** [comment] 2015-03-28 20:51
To confirm, the issue was with the ``phantomjs binary`` downloaded from  https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-macosx.zip

@soda-wy's [solution](https://github.com/ariya/phantomjs/issues/12928#issuecomment-72457801) works perfectly for me.
>> the download link https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-macosx.zip on http://phantomjs.org/ failed with "Killed: 9".

>> https://github.com/eugene1g/phantomjs/releases works, thanks.

Thank you all, for your concerns.
