### ISSUE TITLE
[🐛 Bug]: 4.1.0 regression: driver.switchTo().defaultContext() causes connection to drop

### ISSUE THREAD

**Issue by idontusenumbers** [SeleniumHQ/selenium#10133] opened 2021-12-10 19:49 UTC
### What happened?

I just upgraded `org.seleniumhq.selenium:selenium-java:4.0.0` to `org.seleniumhq.selenium:selenium-java:4.1.0` and a handful of my tests reliably fail now on my local and teamcity due to:

```
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: '8047a03e41c1', ip: '172.18.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-77-generic', java.version: '11.0.11'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [3fc45f3d5ac035225b03bc0b897d575e, switchToFrame {id=null}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 95.0.4638.54, chrome: {chromedriverVersion: 95.0.4638.17 (a9d0719444d4b..., userDataDir: /tmp/.com.google.Chrome.OOxXgg}, goog:chromeOptions: {debuggerAddress: localhost:40969}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), se:cdp: ws://172.24.0.12:4444/sessi..., se:cdpVersion: 95.0.4638.54, se:vnc: ws://172.24.0.12:4444/sessi..., se:vncEnabled: true, se:vncLocalAddress: ws://172.24.0.12:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 3fc45f3d5ac035225b03bc0b897d575e
```

I reverted back to `org.seleniumhq.selenium:selenium-java:4.0.0` and tests work fine in both places now.

### How can we reproduce the issue?

```shell
driver.switchTo().defaultContext()
```

### Relevant log output

```shell
Nothing on the container running selenium standalone driver
```

### Operating System

BigSur (local) and Ubuntu docker container on Ubuntu (teamcity)

### Selenium version

Java 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 95.0.4638.54

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 95.0.4638.17

**Comment by idontusenumbers** [comment] 2021-12-11 07:30
My apologies, I thought it would be a lot harder to get a nice sample test together. It turns out it wasn't too hard.

This seems to do it every time:
```
driver.switchTo().defaultContext()
```

Navigating around using `driver.switchTo().parentFrame()` seems to be an okay workaround for now.

**Comment by diemol** [comment] 2021-12-13 16:48
This is a duplicate of #10116, we have already a fix that will be released in the upcoming days.

**Closed as completed by diemol** 2021-12-13 16:48 UTC
Labels: I-defect
