### ISSUE TITLE
Selenium Does not support Chrome 123[🐛 Bug]: 

### ISSUE THREAD

**Issue by thomaskast** [SeleniumHQ/selenium#13719] opened 2024-03-21 21:53 UTC
### What happened?

I have a large selenium java test suite running under junit windows which I run every day (over 1000 tests).  Today various selecters stopped working such as  by.id, by.linktext, select.getFirstSelectedOption(), etc...   It seems to be related ot the chrome update to v123. 

I see others are having similar problems:
https://youtrack.jetbrains.com/issue/AQUA-858

All kinds of selectors are failing, not all the time, and if I run the same selenium test under junit in eclipse in debug mode, usually the problems with selectors go away only if I step through the selenium test, so it seems like some kind of race-condition-bug; if you slow the test way down, the problem goes away.

### How can we reproduce the issue?

```shell
Please just try any basic test suite with HTML selectors such as by.id, by.linktext, select.getFirstSelectedOption(), etc... Does selenium 4.18.1 (latest) java windows work with chrome 123 for you?
```

### Relevant log output

```shell
From JUNIT standard output running from Windows Command Prompt (no eclipse, open jdk 11)

java] Session ID: 68cba6d9e2527bddcef83b0147703e44
[java] RUNNING TEST: com.xxxxxxxxxxx.xxxx.systemtest.reporting.DecorationSummaryScheduleReportTest
[java] Mar 21, 2024 3:14:59 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
[java] WARNING: Unable to find an exact match for CDP version 123, returning the closest version; found: 122; Please update to a Selenium version that supports CDP version 123
[java] Mar 21, 2024 3:15:49 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
[java] WARNING: Unable to find an exact match for CDP version 123, returning the closest version; found: 122; Please update to a Selenium version that supports CDP version 123
```

### Operating System

Windows 10

### Selenium version

Open JDK 11/ Selenium 4.18.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 123

### What are the browser driver(s) and version(s) where you see this issue?

chromdrive_64 123

### Are you using Selenium Grid?

No

**Comment by hoant2010** [comment] 2024-03-22 06:56
I have the same issue on Chrome Driver for .NET
```
OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:22054/session timed out after 60 seconds.
---- System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.
-------- System.TimeoutException : The operation was canceled.
------------ System.Threading.Tasks.TaskCanceledException : The operation was canceled.
---------------- System.IO.IOException : Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
-------------------- System.Net.Sockets.SocketException : The I/O operation has been aborted because of either a thread exit or an application request.
```

**Comment by diemol** [comment] 2024-03-22 16:42
It looks like Chrome 123 came with this issue.

Duplicate of #13712

**Closed as not planned by diemol** 2024-03-22 16:42 UTC
Labels: I-defect, A-needs-triaging

**Comment by 0MuhammadAbdullah0** [comment] 2024-03-23 01:36
the issue hasnt been resolved yet and i am facing the same problem.kindly fix asap

**Comment by diemol** [comment] 2024-03-23 06:56
It hasn't been resolved, did you see we created an issue in the ChromeDriver issue tracker?

Feel free to comment over there.

**Comment by mihailgabriel** [comment] 2024-03-25 13:05
Use this for the tests to run, as a workaround: 
WebDriverManager.chromedriver().clearDriverCache().setup();

**Comment by olyanasennik** [comment] 2024-03-25 16:08
> Use this for the tests to run, as a workaround: WebDriverManager.chromedriver().clearDriverCache().setup();

<img width="1037" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/159495492/05b5b120-c52f-42e8-bc64-2478376b18d5">

It throws me below:
java: cannot find symbol
  symbol:   method chromedriver()
  location: variable WebDriverManager of type java.lang.Object

**Comment by mihailgabriel** [comment] 2024-03-25 16:21
The context is Selenium Java on Eclipse with Maven. I also use a webdriver manager https://mvnrepository.com/artifact/io.github.bonigarcia

**Comment by OTEPOLA** [comment] 2024-03-27 10:39
Hello I am stuck here setting up my selenium for the first time. 

(WARNING: Unable to find an exact match for CDP version 123, returning the closest version; found: 122; Please update to a Selenium version that supports CDP version 123
Mar 27, 2024 11:37:29 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 123, returning the closest version; found: 122; Please update to a Selenium version that supports CDP version 123)

I tried this work around (Use this for the tests to run, as a workaround:
WebDriverManager.chromedriver().clearDriverCache().setup();) I got this
java: cannot find symbol 
  symbol:   variable WebDriverManager
  location: class com.test1.Main

**Comment by mihailgabriel** [comment] 2024-03-27 12:41
It said it won't find the manager because you don't have one. So try this in your chain commands chromedriver().clearDriverCache().setup() instead of  chromedriver().setup()
