### ISSUE TITLE
Get selenium-grid node id and dockers-novnc port id mapping

### ISSUE THREAD

**Issue by nilanjan-mandal03** [SeleniumHQ/selenium#13620] opened 2024-02-23 10:46 UTC
### Feature and motivation

I have started selenium docker compose file with novnc enabled and scaled the browser from 1 to 3.

I can see the real time test happening in localhost:7901, localhost:7902, localhost:7903

But i dont know which test is getting triggered in which node and which node is being mapped to which port (7901/7902/7903)

I can get the session id and node id from the api http://localhost:4444/status. 

But is there any way i can get the port mapping wrt node id?

Can we have a mapping for this as well so that we know which port of 790x should be opened to view the test case

### Usage example

These novnc ports can be exposed as public IPs for each sessions that is running on a remote url.

**Comment by diemol** [comment] 2024-02-23 10:49
Duplicate of #12075

**Closed as not planned by diemol** 2024-02-23 10:49 UTC
