### ISSUE TITLE
[🐛 Bug]: C# Selenium.Webdriver broke on code with embedded web browser control starting at version  4.11

### ISSUE THREAD

**Issue by budcribar** [SeleniumHQ/selenium#13172] opened 2023-11-19 22:06 UTC
### What happened?

I have an application which uses an embedded web browser control via the Microsoft.AspNetCore.Components.WebView.Wpf package. I have recently updated from version 8.0.0-rc.2.9373 (Webview 14) to version 8.0.0 (Webview 19) which then requires me to update Selenium.Webdriver version 4.10 to a later version. 

I specify UseWebView since I am using an embedded webview control (Blazor) in my wpf app and I specify the location of my
application's executable using the BinaryLocation property.

The code looks like:
  EdgeOptions options = new EdgeOptions
  {     
       
      UseWebView = true,
      BinaryLocation = binaryLocation
  };

  try
  {
      driver = new EdgeDriver(options);
  }
  catch (Exception ex)
  {
      Console.WriteLine($"An error occurred while setting up the Edge driver: {ex.Message}");
  }

However, in versions after 4.10 the BinaryLocation does not work as expected.  I am getting this error:
OpenQA.Selenium.WebDriverException: 'unknown error: no msedge binary at C:\Users\budcr\source\repos\RemoteBlazorWebView\testassets\NUnitTestProject\bin\Debug\net8\..\..\..\..\..\..\RemoteBlazorWebViewTutorial\RemoteBlazorWebViewTutorial.WpfApp\bin\publish\RemoteBlazorWebViewTutorial.WpfApp.exe\119.0.2151.72\msedge.exe'

Instead of  starting my application with the embedded webview control  "RemoteBlazorWebViewTutorial.WpfApp.exe" as it has done in versions previous to 4.11 it is apparently taking BinaryLocation  as the location of msedge.exe!!!!

### How can we reproduce the issue?

```shell
Working on that if needed. The issue seems to isolated to the change in the BinaryLocation property which is incorrectly using it as a path to determine where msedge is located instead of the executable to launch when UseWebView is true.
```

### Relevant log output

```shell
OpenQA.Selenium.WebDriverException: 'unknown error: no msedge binary at C:\Users\budcr\source\repos\RemoteBlazorWebView\testassets\NUnitTestProject\bin\Debug\net8\..\..\..\..\..\..\RemoteBlazorWebViewTutorial\RemoteBlazorWebViewTutorial.WpfApp\bin\publish\RemoteBlazorWebViewTutorial.WpfApp.exe\119.0.2151.72\msedge.exe'
```

### Operating System

Windows 11

### Selenium version

C#  Selenium.WebDriver" Version="4.11.0" or later

### What are the browser(s) and version(s) where you see this issue?

Embedded web browser control 119 from Microsoft.AspNetCore.Components.WebView.Wpf" Version="8.0.3

### What are the browser driver(s) and version(s) where you see this issue?

Selenium.WebDriver.ChromeDriver" Version="119.0.6045.10500"

### Are you using Selenium Grid?

n/a

**Comment by titusfortner** [comment] 2023-11-21 18:20
To double check, you've tried this with 4.15 specifically?

**Comment by budcribar** [comment] 2023-11-21 20:19
I think I checked every release since 4.10 and all received the "unknown error: no msedge binary at... " exception

**Comment by titusfortner** [comment] 2023-11-26 23:46
Ok, verified this but it is a duplicate of #12738

**Closed as not planned by titusfortner** 2023-11-26 23:46 UTC
Labels: C-dotnet, I-defect, A-needs-triaging
