### ISSUE TITLE
selenium issue

### ISSUE THREAD

**Issue by sakshichauhan07** [SeleniumHQ/selenium#4984] opened 2017-10-31 05:47 UTC
There was an unexpected error. Msg: TypeError: window.editor.infoPanel is undefined
Url: chrome://selenium-ide/content/selenium-ide.xul, line: 1, column: 1
onclick@chrome://selenium-ide/content/selenium-ide.xul:1:1
![sq](https://user-images.githubusercontent.com/20639824/32209196-ff8b9d08-be2c-11e7-995a-c02fff5e3f95.png)

**Comment by barancev** [comment] 2017-10-31 06:04
Duplicate of #4406

**Closed by barancev** 2017-10-31 06:04 UTC
