### ISSUE TITLE
[🐛 Bug]: CFT version 116 is not getting download with selenium 4.11

### ISSUE THREAD

**Issue by soni-123** [SeleniumHQ/selenium#12496] opened 2023-08-04 17:07 UTC
### What happened?

When I run the below code
<img width="566" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/22731397/1b14c677-81ff-443a-9d83-9e8fdf1ea06b">

It throw below error
<img width="946" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/22731397/59bd00eb-8ac1-41e0-b248-e1d2575d207d">

### How can we reproduce the issue?

```shell
I am trying to run the below code but it throwing an error
package SeleniumPractice;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.manager.SeleniumManager;

public class ChromeOpening {

	public static void main(String[] args) {
		ChromeOptions co=new ChromeOptions();
		co.setBrowserVersion("116");
		String browserPath=SeleniumManager.getInstance().getDriverPath(co, false).browserPath;
		String driverPath=SeleniumManager.getInstance().getDriverPath(co, false).driverPath;
		System.out.println(browserPath);
		System.out.println(driverPath);
		
		WebDriver driver=new ChromeDriver(co);
		driver.get("https://www.google.com");
		driver.findElement(By.name("q")).sendKeys("Selenium");
		System.out.println(driver.getTitle());	

	}

}
```

### Relevant log output

```shell
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Failed to create Chrome process. 
Host info: host: 'DESKTOP-QJST469', ip: '192.168.0.105'
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, browserVersion: 116, goog:chromeOptions: {args: [--remote-allow-origins=*], binary: C:\Users\LENOVO\.cache\sele..., extensions: []}}]}]
```

### Operating System

Window 10

### Selenium version

Selenium 4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 116

### What are the browser driver(s) and version(s) where you see this issue?

116.0.5845.62

### Are you using Selenium Grid?

NA

**Comment by titusfortner** [comment] 2023-08-04 17:29
This might be a permissions issue.
Can you turn on logging so we can see the details?
https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by soumyajit0905** [comment] 2023-08-05 20:55
@soni-123 please try using "Beta" or mention the complete version number 116.x as I am able to run using chromedriver.exe and chrome for testing browser downloaded in my local cache. 
Thanks 
cc @titusfortner

**Comment by diemol** [comment] 2023-08-23 15:29
I will close this as no more activity was logged. If the issue is still present, please let us know, and we can reopen.

**Closed as not planned by diemol** 2023-08-23 15:29 UTC
Labels: J-awaiting answer, I-defect
