### ISSUE TITLE
In FireFox WebDriver After SwitchToFrame(id) is done, it comes out of Frame randomly.

### ISSUE THREAD

**Issue by LakshmanShiva** [SeleniumHQ/selenium#2596] opened 2016-08-10 15:09 UTC
## Meta -

OS:  
Windows Server 2008
Selenium Version:  
WebDriver-2.53.1
Programming Language - C# .net
Browser:  
Firefox (46.0.1)
## Description.

In FireFox WebDriver After SwitchToFrame("") is done, it comes out of IFrame randomly. And then exception unable to locate element is thrown.

In Reference to the Issue Raised before (SwitchTo losing context when using a frame id #4876) a Javascript patch file is given in this issue. But how to apply this patch in C# binding as there is only dlls included. Also when I downloaded the Source code for .Net I couldn't find any java script files in .Net Folder.

Reference Issue:
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/4876

This happens when the webpage has only one OuterFrame. And this doesn't happens when web pages have Multiple inner frame. Is there a appropriate patch for C# WebDriver Bindings?
## Expected Behavior -

When SwitchToFrame("") is done it should not come out of frame till SwicthTo().DefaultContenet() is given but it comes out of the frame randomly.
## Actual Behavior -

When SwitchToFrame("") is done it should not come out of frame till SwicthTo().DefaultContenet() is given but it comes out of the frame randomly.
## Steps to reproduce -

Run Automation Tests in continuous batch with an application which has webpages with only one Outer Frame.

**Comment by LakshmanShiva** [comment] 2016-08-12 03:13
Hi, Could you anyone help me on this, is there a way to solve this problem in Firefoxdriver?

**Comment by LakshmanShiva** [comment] 2016-08-16 13:20
Hi, Could anyone update me on this? I also tried Marionette driver but I found that it does't support Actions MoveToElement() methods and also it is given that Actions is not supported yet. Hence is there a way to fix the Frame switching out issue in firefox driver?

**Comment by malafeev01** [comment] 2016-10-13 12:01
Hi, I see the same issue on FF 43.0.1, selenium 2.51.0.

**Comment by barancev** [comment] 2017-12-09 20:40
The patch mentioned in the original post was applied in 2013, it was incorporated into firefox driver that is a browser addon independent on the client binding language. 

If the issue is still actual please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment] 2019-04-17 21:06
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.

**Closed by barancev** 2019-04-17 21:06 UTC
Labels: D-firefox
