### ISSUE TITLE
Out-of-the-box Selenium webdriver for FF does not work on Linux

### ISSUE THREAD

**Issue by debbiesrain** [SeleniumHQ/selenium#1403] opened 2015-12-22 08:05 UTC
Setup: Selenium Webdriver 2.48.2, FFv42, Xvfb (installed and running), mocha-v2.3.4, node-v4.2.2, Linux machine (Red Hat 7)

This setup worked perfectly fine in my windows local machine. But when I set this up in Linux and run my nodejs/mocha tests, I get this error:

Error: Timed out waiting for the WebDriver server at http://127.0.0.1:56318/hub
[11:51:10][npm test]       at Error (native)
[11:51:10][npm test]       at onResponse (/home/teamcity/buildagent2/node_modules/selenium-webdriver/http/util.js:89:11)
[11:51:10][npm test]       at /home/teamcity/buildagent2/node_modules/selenium-webdriver/http/util.js:44:21
[11:51:10][npm test]       at /home/teamcity/buildagent2/node_modules/selenium-webdriver/lib/webdriver/http/http.js:140:5
[11:51:10][npm test]       at ClientRequest.<anonymous> (/home/teamcity/buildagent2/shimano_b2b-test/node_modules/selenium-webdriver/http/index.js:174:7)
[11:51:10][npm test]       at Socket.socketErrorListener (_http_client.js:259:9)
[11:51:10][npm test]       at emitErrorNT (net.js:1253:8)
[11:51:10][npm test]   From: Task: WebDriver.createSession()

I just used the out-of-the-box selenium webdriver for Firefox. And like I said, it works fine in my windows local machine, because it can fire up a native server inside it and listen to the localhost's ip address for browser requests.

After so many hours spent in investigation and analysis, here's the code written by the selenium guys behind the scenes rendering this:

File path & name: /node_modules/selenium-webdriver/firefox/index.js
  
var serverUrl = this.command_
      .then(function() { return freePort; })
      .then(function(port) {
        var serverUrl = url.format({
          protocol: 'http',
          hostname: net.getLoopbackAddress(), <------------------------------ renders 127.0.0.1
          port: port,
          pathname: '/hub'
        });
        return httpUtil.waitForServer(serverUrl, 45 * 1000).then(function() {
          return serverUrl;                                   <---------------------------waitForServer() throws the error
        });
      });

QUESTIONS: 
1.) In a Linux machine, is this also returning this loopbackaddress as 127.0.0.1?
2.) Do I need a Selenium standalone server to run to serve http client requests? 
3.) Did I miss a step in configuring my set-up and tests?

I would appreciate any help from anybody. Thanks!

**Comment by jleyba** [comment] 2015-12-22 17:13
1) Depends on your machine configuration. 127.0.0.1 is the norm
2) No. See the [examples](https://github.com/SeleniumHQ/selenium/tree/master/javascript/node/selenium-webdriver/example) (which are included in the npm distribution)
3) Don't know, you haven't provided enough information. Are you using Firefox 43 or 42?

**Comment by debbiesrain** [comment] 2015-12-23 10:43
Thanks for the answers. Here's my setup:

Selenium Webdriver 2.48.2, 
Firefox version 42, 
Xvfb (installed, exported and running), 
mocha-v2.3.4, 
node-v4.2.2, 
Linux machine (Red Hat 7)

1.) I checked the Linux machine configuration and it is correct with the loopback pointing to 127.0.0.1.

2.) At this point, I don't need the selenium standalone server. Because it will fire up the native server for firefox webdriver to be running in http://127.0.0.1:56318/hub. The port is dynamic and is automatically assigned to listen from. This works fine in my windows local machine but continues to fail in Linux.

3.) I am using FF 42, and also tried in FF 38.4.0. Both versions worked fine in windows machine, but not in Linux. 

So, In Linux, I checked if port is open and listening, it is not. That's why I get this time out error:

"Error: Timed out waiting for the WebDriver server at http://127.0.0.1:45669/hub"

Is there anything I can do to make this work? Thank you.

**Comment by deckar01** [comment] 2016-01-06 16:50
I am seeing the same behavior.

```
Error: Timed out waiting for the WebDriver server at http://127.0.0.1:56934/hub
```

Firefox 43.0 works fine with selenium-webdriver 2.48.2 on OSX, but times out during the initial driver creation on Linux.

**Comment by deckar01** [comment] 2016-01-06 17:21
To debug I am running a standalone instance of the server so I can debug the output:
`xvfb-run java -jar selenium-server-standalone-2.48.2.jar`

These errors seem to indicate an incompatibility between the version of Firefox and the selenium-webdriver.
http://stackoverflow.com/a/22869400

[Gist of selenium server errors](https://gist.github.com/deckar01/0beeed241c5926e1dc1d)

**Comment by deckar01** [comment] 2016-01-06 17:27
Debugging against Firefox 42.0 produces the same results.

**Comment by deckar01** [comment] 2016-01-06 18:17
Related issue https://code.google.com/p/selenium/issues/detail?id=4193

**Comment by deckar01** [comment] 2016-01-06 21:55
I got it working with a standalone selenium server and a standalone Xvfb display server, then worked backwards until I found the minimum set of changes that worked.

My issue was a combination of not properly setting up xvfb-run and a rather obscure selenium bug.

`xvfb-run` needed to be started with a server number. If you run the `firefox` command you will probably get `Error: no display specified` and `xvfb-run` doesn't seem to give it a `DISPLAY` env variable unless this parameter is explicitly provided.
```bash
xvfb-run --server-num=11 node index.js
```

`localhost` needs to be the first alias for `127.0.0.1` in `/etc/hosts`.
https://code.google.com/p/selenium/issues/detail?id=3280#c5

**Comment by deckar01** [comment] 2016-01-06 22:08
There may be a cleaner fix (not changing the hosts file) for specifying the host alias in the driver profile, but I am not clear on what the key is supposed to be.

http://seleniumhq.github.io/selenium/docs/api/javascript/module_selenium-webdriver_firefox_class_Profile.html#setPreference

**Comment by jleyba** [comment] 2016-01-06 23:14
```
const firefox = require('selenium-webdriver/firefox');

let profile = new firefox.Profile();
profile.setPreference('webdriver_firefox_allowed_hosts', 'foo.bar.baz');

let options = new firefox.Options().setProfile(profile);
let driver = new firefox.Driver(options);
```

I'm not a fan of hidden configuration keys, so this should be surfaced in the profile API

**Comment by deckar01** [comment] 2016-01-07 21:41
@debbiesrain Have you had a chance to try setting the hostname in the firefox profile or reordering the host aliases?

**Comment by debbiesrain** [comment] 2016-01-20 07:24
@deckar01 Thanks for all the help. Just got back from holidays. I will try out all your suggested solutions and get back to you as soon as I can.

Thanks.

**Comment by debbiesrain** [comment] 2016-01-20 12:44
@deckar01 

I tried the xvfb-run command written above and made sure my /etc/hosts alias is localhost. But still im getting this error: 

<blockquote>
UnknownError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:<br>
[13:36:07][npm test] Error: no display specified
</blockquote>

@jleyba 
I can't modify the out-of-the-box firefox profile because it is only installed during runtime when I run my tests. My tests are completely dependent on the OTB selenium webdriver.

I am really desperate to get this working and I still couldn't make this work even after dozens and dozens of trial and error and combing thru the web for solutions.

**Comment by deckar01** [comment] 2016-01-20 13:18
The key to getting Firefox to recognize the virtual display is to make sure the `DISPLAY` environment variable is set when Firefox is called. It should look like `DISPLAY=:11`.

I would try logging `process.env` in your node script to check.

`xvfb-run --server-num=11 ...` should work as long as the selenium server is being started in the same node script.

You could cut out the middleman and try running Firefox straight from the command line. Just `firefox` should give you the error, but `xvfb-run --server-num=11 firefox` should work.

**Comment by debbiesrain** [comment] 2016-01-20 13:46
I have this 2-step command:
<code>
xvfb-run --server-num=11 firefox & 
</code>
<code>
export DISPLAY=:11.0
</code>

It worked fine.I checked if they are running by firing this commands:
<code>
pgrep Xvfb >/dev/null 2>&1 && echo "XVFB is running!" || echo "XVFB failed!"
</code>
<code>
pgrep firefox >/dev/null 2>&1 && echo "FF is running!" || echo "FF failed!"
</code>

And I get the message, both are running. I have my selenium standalone server start up during runtime before running tests (code below). And I have checked that server is successfully running. 
<pre>
<code>
var SeleniumServer = require('selenium-webdriver/remote').SeleniumServer; <br><br>
var server = new SeleniumServer("../seleniumServer/selenium-server-standalone-2.48.2.jar", { loopback: false, port: 4444 });
server.start(60000);
</code>
</pre>

ReSULT same error:
<pre>
UnknownError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output: <br>
[14:38:59][npm test] Error: no display specified
</pre>

**Comment by deckar01** [comment] 2016-01-20 15:41
`xvfb-run` doesn't require `Xvfb` to be running in the background. It also sets the `DISPLAY` variable for the process it runs based on the `--server-num` parameter, so `export DISPLAY=:11.0` wasn't really necessary, and I'm not sure abut the `.0`. For future reference you can use `VARIABLE=value command` to set an environment variable just for that command's process.

I'm not sure why you are using `selenium-webdriver/remote`. Checkout the [README](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/README.md) for the standard setup.

I would guess you started a standalone selenium server in the background without using `xvfb-run`. Since this process locked in its environment variables when it started it doesn't have a `DISPLAY`. So when you remotely connect to it, `firefox` inherits the environment variables without a `DISPLAY`.

Either don't use a remote server so that when node is run with `xvfb-run` the display will propagate to the selenium server then to firefox OR restart the standalone selenium server with `xvfb-run`.

**Comment by debbiesrain** [comment] 2016-01-21 13:34
Thank you very much for your help. I got it working somehow. 
I have these commands now:
<pre><code>
xvfb-run --server-num=11 node
xvfb-run firefox &
xvfb-run java -jar selenium-server-standalone-2.48.2.jar &
</code></pre>

I have to add <code>&</code> because my next steps will not get executed, so I have to run them in the background. And these processes are actually running by using the commands:
<pre><code>
pgrep Xvfb >/dev/null 2>&1 && echo "XVFB is running!" || echo "XVFB failed!" 
pgrep firefox >/dev/null 2>&1 && echo "FF is running!" || echo "FF failed!" 
</code></pre>

My tests are now running and I can actually get now a pass or fail response. Sample output:
<pre><code>
[14:20:31][npm test]     ✓ can test google (2121ms)
[14:23:35][npm test]     1) can login to Test
[14:23:43][npm test]     ✓ can login to Accept (6137ms)
[14:23:55][npm test]     ✓ can login to Production (9681ms)
[14:23:55][npm test] 
[14:23:55][npm test] 
[14:23:55][npm test]   3 passing (4m)
[14:23:55][npm test]   1 failing
</code></pre> 

However, there were still a lot of hit and miss configuration that I have to tweak to make sure I am not running multiple processes of FF and XVFB and Selenium server in my system everytime I run my tests and these steps are being fired again.  

On the second attempt to run my tests using the same steps WITHOUT changing anything, I get this error: Do you know why?

<pre><code>
[14:28:45][npm test]      UnknownError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
[14:28:45][npm test] .xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
[14:28:45][npm test] 1453382881854	DeferredSave.extensions.json	DEBUG	Starting timer
[14:28:45][npm test] 1453382881855	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
[14:28:45][npm test] 1453382881855	DeferredSave.extensions.json	DEBUG	Save changes
[14:28:45][npm test] 1453382881855	DeferredSave.extensions.json	DEBUG	Save changes
[14:28:45][npm test] 1453382881855	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"fSFZZK969J-z","location":"app-global","version":"42.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/local/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate":1446160646000,"updateDate":1446160646000,"applyBackgroundUpdates":1,"skinnable":true,"size":5022,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"42.0","maxVersion":"42.0"}],"targetPlatforms":[]}
[14:28:45][npm test] 1453382881888	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
[14:28:45][npm test] 1453382881889	addons.xpi	DEBUG	Updating database with changes to installed add-ons
[14:28:45][npm test] 1453382881889	addons.xpi-utils	DEBUG	Updating add-on states
[14:28:45][npm test] 1453382881889	addons.xpi-utils	DEBUG	Writing add-ons list
[14:28:45][npm test] 1453382882179	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
[14:28:45][npm test] 1453382882179	addons.manager	DEBUG	Provider finished startup: XPIProvider
[14:28:45][npm test] 1453382882179	addons.manager	DEBUG	Starting provider: LightweightThemeManager
[14:28:45][npm test] 1453382882179	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
[14:28:45][npm test] 1453382882180	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
[14:28:45][npm test] 1453382882180	addons.manager	DEBUG	Starting provider: GMPProvider
[14:28:45][npm test] 1453382882225	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
[14:28:45][npm test] 1453382882226	addons.manager	DEBUG	Provider finished startup: GMPProvider
[14:28:45][npm test] 1453382882226	addons.manager	DEBUG	Starting provider: PluginProvider
[14:28:45][npm test] 1453382882226	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
[14:28:45][npm test] 1453382882226	addons.manager	DEBUG	Provider finished startup: PluginProvider
[14:28:45][npm test] 1453382882227	addons.manager	DEBUG	Completed startup sequence
[14:28:45][npm test] 1453382882451	DeferredSave.extensions.json	DEBUG	Starting write
[14:28:45][npm test] 1453382882600	addons.manager	DEBUG	shutdown
</code></pre>

**Comment by cgoldberg** [comment] 2016-01-21 15:56
> xvfb-run --server-num=11 node
> xvfb-run firefox &
> xvfb-run java -jar selenium-server-standalone-2.48.2.jar &

2 observations:

1) don't start firefox manually like in the lines above.  You want selenium to start firefox for you as part of a test case.

2) if you don't stop Xvfb,  running tests again (using the commands above) will try to reuse the same display number that Xvfb is already attached to... and it will fail.

**Comment by debbiesrain** [comment] 2016-01-21 16:08
@cgoldberg 

Thanks for the comment. However, if I don't start firefox, I get this error:

<pre><code>
Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
[17:02:10][npm test]       at ClientRequest.<anonymous> (/home/teamcity/buildagent2/buildAgent-BUILD_32407/work/5daf40b4303992e4/shimano_b2b-test/node_modules/selenium-webdriver/http/index.js:174:16)
[17:02:10][npm test]       at Socket.socketErrorListener (_http_client.js:259:9)
[17:02:10][npm test]       at emitErrorNT (net.js:1253:8)
[17:02:10][npm test]   From: Task: WebDriver.createSession()
</code></pre>

I have to have both Firefox and XVFB and Selenium server running in the background before the nodejs tests are executed.

However, I issue a KILL process command after the tests so that there are no processes hanging in the background.

<pre><code>
pkill -f Xvfb
pkill -f firefox
pkill -f selenium
</code> </pre>

But still, I'm having a difficulty having Firefox get running again if I repeat running my tests.My guess was because Firefox does an automatic update on the second call that's why I get the stacktrace of

<pre><code>
[14:28:45][npm test]      UnknownError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
[14:28:45][npm test] .xpi   DEBUG   New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
[14:28:45][npm test] 1453382881854  DeferredSave.extensions.json    DEBUG   Starting timer
</code></pre>

Do you know how I can fix this?

**Comment by deckar01** [comment] 2016-01-22 05:34
I made a project that demonstrates the bare minimum configuration required to run firefox headless using selenium-webdriver on Linux:

https://github.com/deckar01/webdriver-linux-example

I started on a fresh copy of Ubuntu 14.04 to make sure I didn't forget anything.

You might need to kill some of those background processes that you started.
https://www.digitalocean.com/community/tutorials/how-to-use-ps-kill-and-nice-to-manage-processes-in-linux#how-to-use-ps-to-list-processes

**Comment by debbiesrain** [comment] 2016-01-22 09:04
@deckar01 

This is what my package.json looked like:

My script test is run by mocha in this line:
<code>"test": "mocha -t 600000 LoginTest.js"</code>

I saw yours was this:
<code>"example": "xvfb-run --server-num=11 nodejs index.js"</code>

Not sure how I can make this the same in my steps. My xvfb command is executed in the command line before my test script is executed.

Your <code>index.js</code> is almost similar as mine except that I don't have a firefox profile customized. I know there is something wrong, but can't figure out where.

I really appreciate your help. I'm almost there but still something is wrong. Thanks in advance.

<pre><code>
{
  "name": "selenium-webdriver",
  "version": "2.48.2",
  "description": "The official WebDriver JavaScript bindings from the Selenium project",
  "license": "Apache-2.0",
  "keywords": [
    "automation",
    "selenium",
    "testing",
    "webdriver",
    "webdriverjs"
  ],
  "main": "./index",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/SeleniumHQ/selenium.git"
  },
  "engines": {
    "node": ">= 0.12.x"
  },
  "dependencies": {
    "adm-zip": "0.4.4",
    "mocha": "^2.3.4",
    "rimraf": "^2.2.8",
    "tmp": "0.0.24",
    "ws": "^0.8.0",
    "xml2js": "0.4.4"
  },
  "devDependencies": {
    "express": "^4.11.2",
    "mocha": ">= 1.21.x",
    "multer": "^0.1.7",
    "promises-aplus-tests": "^2.1.0",
    "serve-index": "^1.6.1"
  },
  "scripts": {
    "test": "mocha -t 600000 LoginTest.js"
  },
  "_id": "selenium-webdriver@2.48.2",
  "_shasum": "b26a4631430d0a9f36284ee0cfe09676e8f348ca",
  "_from": "selenium-webdriver@*",
  "_npmVersion": "2.14.7",
  "_nodeVersion": "4.2.1"
}
</code></pre>

**Comment by debbiesrain** [comment] 2016-01-22 10:26
@cgoldberg 

I think you are right, Firefox is fired up during the node script execution. I don't need to start it up manually. However, it doesn't recognize my display: <code>[Step 8/12] Error: cannot open display: :99</code>

**Comment by debbiesrain** [comment] 2016-01-22 12:21
After so much analysis and work....Yeheey!! I got it running!

So, in my package.json, I changed my test call from 
<code>"test": "mocha -t 600000 LoginTest.js"</code> 
to this 
<code>"test": "xvfb-run --server-num=11 mocha -t 600000 LoginTest.js"</code>

then I don't have to do this:
<pre><code>
xvfb-run --server-num=11 node
xvfb-run firefox &
</code></pre>

but I still need to fire up my server before executing test scripts by doing this:
<code>
xvfb-run java -jar selenium-server-standalone-2.48.2.jar &
</code>

**Comment by deckar01** [comment] 2016-01-22 12:42
If you let selenium-webdriver start the server instead of giving it remote configuration options you won't have to start a standalone server.
https://github.com/deckar01/webdriver-linux-example/blob/master/index.js

**Comment by debbiesrain** [comment] 2016-01-26 14:11
@deckar01 

Yes, you are correct. I don't need the standalone server anymore. So In short, all I needed to fix was the test call:

<code>"test": "xvfb-run --server-num=11 mocha -t 600000 LoginTest.js"</code>

Can't thank you enough for helping me out! Have a good one!

Debbie

**Comment by deckar01** [comment] 2016-01-26 15:07
@jleyba I opened #1529 to document/expose the profile keys.

@debbiesrain I'm glad to hear you got it working. I opened #1529 to help prevent the underlying issue in the future. Feel free to close this issue since it was mainly caused by our system configuration.

**Closed** 2016-01-26 16:00 UTC
Labels: D-firefox

**Comment by mr-nilesh** [comment] 2018-03-29 20:45
Sorry to comment on this discussion after long time but I am facing the same issue. In my scenario I need to open multiple headless firefox to run multiple sessions at a time. Using xvfb I am able to run it but only one instance at a time. Is there any work around to run parallel firefox instances.
Thanks in advance.

**Comment by deckar01** [comment] 2018-03-29 21:00
@mr-nilesh You may want to open a dedicated issue for that. It does not seem to match the scope of the original issue.

**Comment by BramVanroy** [comment] 2019-06-06 14:58
> Sorry to comment on this discussion after long time but I am facing the same issue. In my scenario I need to open multiple headless firefox to run multiple sessions at a time. Using xvfb I am able to run it but only one instance at a time. Is there any work around to run parallel firefox instances.
> Thanks in advance.

Did you find an answer to your issue?
