### ISSUE TITLE
Safari Driver hangs on not finding an element

### ISSUE THREAD

**Issue by vbhojaraja** [SeleniumHQ/selenium#1367] opened 2015-12-11 15:10 UTC
Hi,
   This issue is related to the latest safari driver 2.48 wherein the driver hangs on not finding a desired element in the page. The script execution is paused and will not timeout and will not continue or end till we manually quit the safari driver.

**Comment by ddavison** [comment] 2015-12-11 15:17
we'll need a little bit more detail.. please post some code of where the issue is, the given HTML that you are *trying* to find, as well as some OS info please

**Comment by vbhojaraja** [comment] 2015-12-11 15:24
OS: OSX El Capitan version 10.11.1
safari version: 9.0.1
Safari extension version : 2.48.0
When i try to access the below url and the driver is unable to load the page. It gets stuck there and doesnt fail or quit the driver.
driver.get("http://airbornemedia.gogoinflight.com")

**Comment by ddavison** [comment] 2015-12-11 15:35
I can't even load that page. Is it internal?  If not, then that's your problem :) you cannot navigate to a site that's "not a site"

**Comment by vbhojaraja** [comment] 2015-12-11 15:43
yes its an internal site, but we can simulate this in other normal websites as well. when we try to access google or yahoo site when the network is down the same issue occurs.

**Comment by roshanhadal** [comment] 2015-12-16 12:11
Even I noticed this issue. I have attached the screenshot. I have installed the latest extension. Protractor is working fine with Chrome and Firefox. I am new to this but I have debugged to my knowledge. I am stuck. I even installed the 2.48.2 selenium server jar. Any pointers will help.
 
<img width="1440" alt="safari_wd_issue_2_48" src="https://cloud.githubusercontent.com/assets/8522615/11840003/548072a6-a418-11e5-8633-e57c45f3756a.png">

**Comment by lukeis** [comment] 2016-09-23 20:15
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.

**Closed by lukeis** 2016-09-23 20:15 UTC
Labels: A-needs new owner, D-safari, E-hard
