### ISSUE TITLE
Unable to execute Selenium (3.5.0) Grid when "chrome_options=options" is passed as an argument in "self.driver = webdriver.Remote(command_executor='http://127.0.0.1:4444/wd/hub', chrome_options=options, desired_capabilities=DesiredCapabilities.CHROME)" method through Python PyDev (Eclipse) unittest module

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#4507] opened 2017-08-18 16:50 UTC
## Meta - Unable to execute Selenium (3.5.0) Grid when "chrome_options=options" is passed as an argument in "self.driver = webdriver.Remote(command_executor='http://127.0.0.1:4444/wd/hub', chrome_options=options, desired_capabilities=DesiredCapabilities.CHROME)" method through Python PyDev (Eclipse) unittest module

OS: Windows 8 Pro, 64 bit

Selenium Version: 3.5.0 (Python 3.6.1)

Selenium Binding: Python 3.6.1

GeckoDriver Version: 0.18.0

Browser: Firefox

Browser Version: Firefox 55.0.2 (64-bit)

## Expected Behavior -

As a result of #3884  and #685 while using Python 3.6.1  bindings we have been using the following configuration while initializing the `chromedriver`:

- Chrome:

        driver = webdriver.Chrome(chrome_options=options, executable_path=r'C:\Utility\BrowserDrivers\chromedriver.exe')

While using unittest in Python 3.6.1 we used:

    self.driver = webdriver.Chrome(chrome_options=options, executable_path=r'C:\Utility\BrowserDrivers\chromedriver.exe')

So when we use `self.driver = webdriver.Remote()` the following should work as:

    self.driver = webdriver.Remote(command_executor='http://127.0.0.1:4444/wd/hub', chrome_options=options, desired_capabilities=DesiredCapabilities.CHROME)

## Actual Behavior -

But while trying to use `self.driver = webdriver.Remote()` as:

    self.driver = webdriver.Remote(command_executor='http://127.0.0.1:4444/wd/hub', chrome_options=options, desired_capabilities=DesiredCapabilities.CHROME)

The following error is observed on the console:

	Finding files... done.
	Importing test modules ... done.

	======================================================================
	ERROR: test_search_in_python_org (readthedocs.SeleniumGridChrome.PythonOrgSearch)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "C:\Users\AtechM_03\LearnAutmation\PythonProject\readthedocs\SeleniumGridChrome.py", line 14, in setUp
	    self.driver = webdriver.Remote(command_executor='http://127.0.0.1:4444/wd/hub', chrome_options=options, desired_capabilities=DesiredCapabilities.CHROME)
	TypeError: __init__() got an unexpected keyword argument 'chrome_options'

	----------------------------------------------------------------------
	Ran 1 test in 0.009s

	FAILED (errors=1)

## Steps to reproduce -
Minimal Code Block:

	import unittest
	from selenium import webdriver
	from selenium.webdriver.common.keys import Keys
	from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
	from selenium.webdriver.chrome.options import Options

	class PythonOrgSearch(unittest.TestCase):

	    def setUp(self):
		options = Options()
		options.add_argument("start-maximized")
		options.add_argument("disable-infobars")
		options.add_argument("--disable-extensions")
		self.driver = webdriver.Remote(command_executor='http://127.0.0.1:4444/wd/hub', chrome_options=options, desired_capabilities=DesiredCapabilities.CHROME)

	    def test_search_in_python_org(self):
		driver = self.driver
		driver.get("http://www.python.org")
		self.assertIn("Python", driver.title)
		elem = driver.find_element_by_name("q")
		elem.send_keys("pycon")
		elem.send_keys(Keys.RETURN)
		assert "No results found." not in driver.page_source

	    def tearDown(self):
		self.driver.quit()

	if __name__ == "__main__":
	    unittest.main()

**Comment by lmtierney** [comment] 2017-08-21 01:35
Duplicate of #4506

**Closed by lmtierney** 2017-08-21 01:35 UTC
Labels: C-py, D-chrome

**Comment by Debanjan-B** [comment] 2017-08-22 05:02
@lmtierney I think this issue have no relation with #4506 which dealt with `options.binary` or `options.binary_location`. This issue was all about passing the `chrome_options` class object along with `desired_capabilities` object while invoking `self.driver = webdriver.Remote()`. But the documentation of [`webdriver.Remote()`](https://seleniumhq.github.io/selenium/docs/api/py/webdriver_remote/selenium.webdriver.remote.webdriver.html#module-selenium.webdriver.remote.webdriver) doesn't mentions about this. Hence **Not A Bug**

Thanks for all the help.

**Comment by humble-student** [comment] 2018-07-09 20:55
I am also encountering this issue.  Was there any solution for this?

**Comment by marcelocecin** [comment] 2018-09-26 18:17
`options = webdriver.ChromeOptions() 
options.add_argument("user-data-dir=.chrome_profile")
browser = webdriver.Remote(command_executor=selenium_server, desired_capabilities=options.to_capabilities())`
