### ISSUE TITLE
Selenium version 2.9.1 is not recording on firefox 55.0.3 (64-bit)

### ISSUE THREAD

**Issue by vipin0803** [SeleniumHQ/selenium#4775] opened 2017-09-28 11:49 UTC
Selenium version 2.9.1 is not recording on firefox 55.0.3 (64-bit)
Recording button is not clickable.

**Comment by lmtierney** [comment] 2017-09-28 13:02
Duplicate of #4406

**Closed by lmtierney** 2017-09-28 13:02 UTC
