### ISSUE TITLE
[🐛 Bug]: Remote login with basic authentication blocks jobs in the Grid

### ISSUE THREAD

**Issue by MarcJagtInfor** [SeleniumHQ/selenium#12962] opened 2023-10-18 06:48 UTC
### What happened?

The test opens a Chrome browser and needs to log in with basic authentication. At that specific moment the error comes in.
I cannot determine if this is a chromedriver issue.

### How can we reproduce the issue?

```shell
// Login code for basic authentication

                Platform remotePlatform = Platform.getCurrent();
                switch (getProperty("platform"))
                {
                case "WINDOWS":
                    remotePlatform = Platform.WINDOWS;
                    break;
                default:
                    remotePlatform = Platform.WINDOWS;
                }

                String seleniumGridHub = getProperty("seleniumGridHub");

                AtomicReference<DevTools> devToolsAtomicReference = new AtomicReference<>();

                driver = RemoteWebDriver.builder().augmentUsing(new Augmenter().addDriverAugmentation("chrome", HasAuthentication.class, (caps, exec) -> (whenThisMatches, useTheseCredentials) ->
                {
                    devToolsAtomicReference.get().createSessionIfThereIsNotOne();
                    devToolsAtomicReference.get().getDomains().network().addAuthHandler(whenThisMatches, useTheseCredentials);
                })).oneOf(chromeOptions).address(seleniumGridHub).build();

                devToolsAtomicReference.set(((HasDevTools) driver).getDevTools());

        LOG.info("Login in as Administrator");
        String userName = getProperty("username");
        String password = getProperty("password");

        // Register the driver with the given credentials.
        ((HasAuthentication) s_driver).register(UsernameAndPassword.of(userName, password));

        // Load the application url
        String currentURL = s_driver.getCurrentUrl();
        s_driver.get(currentURL);  // <<<< ---- The error happens at this line
```

### Relevant log output

```shell
Oct 18, 2023 7:55:49 AM org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: Unexpected frame CONTINUATION (fin=true)
java.net.ProtocolException
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.processError(WebSocketImpl.java:487)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.run(WebSocketImpl.java:454)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.trySetState(WebSocketImpl.java:837)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.signalError(WebSocketImpl.java:714)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$SignallingMessageConsumer.onError(WebSocketImpl.java:825)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$ReceiveTask.run(TransportImpl.java:671)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$ReadEvent.handle(TransportImpl.java:762)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.checkEvents(RawChannelTube.java:174)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.onNext(RawChannelTube.java:204)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.onNext(RawChannelTube.java:157)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:844)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:763)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:941)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:245)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:957)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:912)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:912)
Caused by: jdk.internal.net.http.websocket.FailWebSocketException: Unexpected frame CONTINUATION (fin=true)
	at java.net.http/jdk.internal.net.http.websocket.MessageDecoder.opcode(MessageDecoder.java:133)
	at java.net.http/jdk.internal.net.http.websocket.Frame$Reader.readFrame(Frame.java:391)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$ReceiveTask.run(TransportImpl.java:665)
	... 20 more

Oct 18, 2023 7:55:59 AM org.openqa.selenium.devtools.Connection$Listener lambda$onText$0
WARNING: Unable to process: {"method":"Fetch.requestPaused","params":{"requestId":"interception-job-2.0","request":{"url":"http://nlbavwebui01.infor.com:24312/webui/gwtui/gwtui.nocache.js","method":"GET","headers":{"Accept":"*/*","Cookie":"JSESSIONID=B70DB6E511E48A25BF025A7D7DA5B91D","Referer":"http://nlbavwebui01.infor.com:24312/webui/servlet/admin","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/118.0.0.0 Safari/537.36"},"initialPriority":"High","referrerPolicy":"strict-origin-when-cross-origin"},"frameId":"3022173EF8413AB9614DCF4830E2F348","resourceType":"Script"},"sessionId":"AA15CF1C62EDCA20B0F1A01BB6D9D5DC"}
org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.20.1'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:183)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:89)
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$5(Network.java:258)
	at org.openqa.selenium.devtools.Connection.lambda$handle$4(Connection.java:330)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1621)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:296)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:224)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:172)
	... 18 more

Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: java.util.concurrent.TimeoutException
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.20.1'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:227)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.20.1'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:183)
	at org.openqa.selenium.devtools.DevTools.send(DevTools.java:89)
	at org.openqa.selenium.devtools.idealized.Network.lambda$prepareToInterceptTraffic$5(Network.java:258)
	at org.openqa.selenium.devtools.Connection.lambda$handle$4(Connection.java:330)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1621)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:296)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:224)
	... 3 more
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:172)
	... 18 more
```

### Operating System

Windows Server 2022 Standard

### Selenium version

Selenium Java 4.14.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 118.0.5993.71 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

Comes with Selenium Grid

### Are you using Selenium Grid?

Selenium Grid 4.14.1

**Comment by MarcJagtInfor** [comment] 2023-10-18 06:55
Additional: Running the test from Eclipse on my desktop with ChromeDriver 118.0.5993.70 does not produce the issue

**Comment by pujagani** [comment] 2023-10-18 09:45
Thank you for the details. If the test passes on IDE and does not pass otherwise, it seems unlikely that it is a Selenium bug. Did you see this error with other versions of the browser?

**Comment by baflQA** [comment] 2023-10-18 11:16
For ```Unexpected frame CONTINUATION (fin=true)``` I think that might help https://github.com/SeleniumHQ/selenium/issues/11408#issuecomment-1345401948

The timeout looks similar to what I already reported https://github.com/SeleniumHQ/selenium/issues/12689
Is there any chance that You are using dynamic grid with docker?

**Comment by MarcJagtInfor** [comment] 2023-10-18 11:58
The problem is not in Selenium Java 4.13.0  and Selenium Grid 4.13.0 using Chrome 117.
I do not use docker on any level.

**Comment by titusfortner** [comment] 2023-10-18 13:12
When you use `RemoteWebDriverBuilder` it should do all the augmentation for you automatically, what is the need for `addDriverAugmentation()`?

Also, do you want those headers sent every request, or does it make sense to set a `Predicate` to limit when it's sent?

```java
    Predicate<URI> uriPredicate = uri -> uri.toString().contains(authSite);
    Supplier<Credentials> authentication = UsernameAndPassword.of(username, password);

    ((HasAuthentication) driver).register(uriPredicate, authentication);
```

**Comment by MarcJagtInfor** [comment] 2023-10-18 13:19
> When you use `RemoteWebDriverBuilder` it should do all the augmentation for you automatically, what is the need for `addDriverAugmentation()`?
> 
> Also, do you want those headers sent every request, or does it make sense to set a `Predicate` to limit when it's sent?
> 
> ```java
>     Predicate<URI> uriPredicate = uri -> uri.toString().contains(authSite);
>     Supplier<Credentials> authentication = UsernameAndPassword.of(username, password);
> 
>     ((HasAuthentication) driver).register(uriPredicate, authentication);
> ```

Hi @titusfortner , It can be true that this is not needed but I have no clue what this has to do with the reported issue. Can you explain?

**Comment by titusfortner** [comment] 2023-10-18 16:10
I'm looking for the minimum reproducible example so that it is easy to pinpoint the problem. Remove code that isn't needed in case it did something weird to cause the problem.

**Comment by titusfortner** [comment] 2023-10-18 16:12
There are 3 different ways to do basic auth in our documentation - https://www.selenium.dev/documentation/webdriver/bidirectional/chrome_devtools/bidi_api/#basic-authentication

I've seen some odd differences between the CDP API and BiDi API ones that I'd like to see more examples to investigate.

**Comment by pujagani** [comment] 2023-10-19 07:54
I am able to reproduce the error with Chrome 118 with the example below:
```
       ChromeOptions chromeOptions = new ChromeOptions();

        WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444"), chromeOptions);

        Augmenter augmenter = new Augmenter();
        driver = augmenter.augment(driver);

        DevTools devTools = ((HasDevTools) driver).getDevTools();
        devTools.createSession();

        ((HasAuthentication) driver).register(UsernameAndPassword.of("admin", "admin"));
        driver.get("https://the-internet.herokuapp.com/basic_auth");
        System.out.println(driver.findElement(By.tagName("p")).getText());
        driver.quit();
```
The error has the same stack trace as shared in this issue.
 I have not tried with previous version of Chrome.

**Comment by pujagani** [comment] 2023-10-19 08:03
Sharing the Grid logs : 

```
 Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 118.0.5993.88, chrome: {chromedriverVersion: 118.0.5993.70 (e52f33f30b91..., userDataDir: /var/folders/nq/0wvwsptj559...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64913}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://192.168.31.118:4444/se..., se:cdpVersion: 118.0.5993.88, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
13:28:49.973 INFO [ProxyNodeWebsockets.createWsEndPoint] - Establishing connection to ws://localhost:64913/devtools/browser/01e0c10d-6cb9-4f55-bbc9-f22fd561f8d5
13:28:56.759 WARN [DefaultChannelPipeline.onUnhandledInboundException] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalStateException: expected a continuation frame
	at org.openqa.selenium.netty.server.MessageInboundConverter.channelRead0(MessageInboundConverter.java:99)
	at org.openqa.selenium.netty.server.MessageInboundConverter.channelRead0(MessageInboundConverter.java:38)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.openqa.selenium.netty.server.WebSocketUpgradeHandler.handleWebSocketFrame(WebSocketUpgradeHandler.java:165)
	at org.openqa.selenium.netty.server.WebSocketUpgradeHandler.channelRead(WebSocketUpgradeHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by pujagani** [comment] 2023-10-19 08:09
The error occurs only when used with Grid and therefore Augmenter.

**Comment by pujagani** [comment] 2023-10-19 08:39
@joerg1985 Based on the stack trace, I tried to go through the code. Though I am not familiar with that area of code but willing to dig in. Before I do that, I wanted to ask you, if you have encountered this before or may have an idea what could be wrong. Essentially, after debugging I see that the value of `next` is set to `text` and `frame is an instance of CloseWebSocketFrame` in https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/netty/server/MessageInboundConverter.java.

**Comment by joerg1985** [comment] 2023-10-19 15:25
@pujagani I think this is just the shutdown of the client that we do not expect at that state, it will probably send the close right after detecting the protocol error, rather than finish sending the current message.
The `} else if (frame instanceof CloseWebSocketFrame) {` should be move to the top of the if statement and logging a warning about the unexpected shutdown (when next is != None) of the websocket should be enough.

It would be interesting to see what the client is receiving, `System.setProperty("jdk.internal.httpclient.websocket.debug", "true");` could help to log this.

**Comment by pujagani** [comment] 2023-10-20 05:57
Thank you for the insights. That was my initial fix but if we close the socket at that point, then CDP session close called afterwards fails because the socket is closed. I will check if this is Chrome version-specific issue and if this is a regression from their end.

**Comment by joerg1985** [comment] 2023-10-23 16:34
@pujagani i think the line linked below is not correct, this should be `ctx.fireChannelRead(frame);`

https://github.com/SeleniumHQ/selenium/blob/fd9fbaaff4a3fa4e0d2970a8e07d3f8a0cd2d86c/java/src/org/openqa/selenium/netty/server/WebSocketUpgradeHandler.java#L169

**Comment by pujagani** [comment] 2023-10-25 15:11
Thank you! I will take a look.

**Comment by joerg1985** [comment] 2023-10-25 15:43
@pujagani i just have pushed it as i had unexpected some time

**Comment by pujagani** [comment] 2023-10-25 15:49
That's great. Thank you! Will try the fix out to see if it solves the issue at hand.

**Comment by pujagani** [comment] 2023-10-26 05:52
Thank you for the fix @joerg1985. I checked with an example code snippet, it fixes the issue reported here.

**Comment by joerg1985** [comment] 2023-10-26 20:12
@MarcJagtInfor thanks for reporting the issue, it has been fixed now.

**Closed as completed by joerg1985** 2023-10-26 20:12 UTC
Labels: J-awaiting answer, C-java, I-defect, B-devtools

**Comment by MarcJagtInfor** [comment] 2023-10-27 06:16
Great!. Many thanks.
