### ISSUE TITLE
browser.get doesn't refresh page using IE driver on IE 11

### ISSUE THREAD

**Issue by DK15** [SeleniumHQ/selenium#1443] opened 2016-01-05 17:15 UTC
I am performing cross browser testing on windows 2012 server R2 and IE 11 combination. The protractor tests are on a linux machine and am executing those on windows VM as mentioned above. 

My _protractorConf.js_ file looks like below 

`seleniumAddress: 'http://<windows VM ip>:4444/wd/hub'`
`baseUrl: 'http://<linux VM ip>:8000'`
`capabilities: { browserName: 'internet explorer', platform: 'ANY', version: '11'}`

I also have configured the security settings as prescribed here : https://code.google.com/p/selenium/wiki/InternetExplorerDriver

The test which fails shows error as _: Error : AddCompanySuite should redirect to email sent page on successful added company account_
 `- Expected 'http://10.81.78.137:8000/#/addCompany' to match /.*#\/emailSent/.`

On firefox,  before, the test `‘Should redirect to email sent page on successful added company account’` is executed, the screen is refreshed and clears the inputs present in all the fields.  Protractor then inputs valid inputs in all fields, clicks Add which redirects users towards email sent page.

But on IE 11, before the test `‘Should redirect to email sent page on successful added company account’` is executed, the screen is not refreshed, fields are not cleared and protractor enters input values on the fields again which already has existing values from the test `‘Should disable create new account button before all inputs are valid’`.  Hence, the ‘Add’ button is shown as disabled. The screen looks like  below :
![ie11](https://cloud.githubusercontent.com/assets/16548367/12121737/81840d9c-b39c-11e5-96b7-35f912aaf484.png)

Hence, protractor fails the test by saying ‘addCompany’ doesn’t match with ‘emailSent’ url.

Here is the code which is executed 

``````
//3. email addresses do not match
    addCompanyPageObj.email.clear();
    addCompanyPageObj.email.sendKeys(badEmail1);
    addCompanyPageObj.retypeEmail.clear();
    addCompanyPageObj.retypeEmail.sendKeys(retypeEmail);
    browser.sleep(5000);
expect(addCompanyPageObj.emailMatchMsg.getText()).toContain(translations.ACCOUNT.TIPS.EMAIL_MATCH);
    expect(addCompanyPageObj.registerButton.getAttribute('disabled')).toBeTruthy();
    browser.sleep(5000);
   });```

  fit('should redirect to email sent page on successful added company account', function () {
  browser.sleep(10000);
    addCompanyPageObj.companyName.sendKeys(companyName);

    addCompanyPageObj.email.sendKeys(email);

    addCompanyPageObj.retypeEmail.sendKeys(retypeEmail);
    browser.pause();

    global.setHttpReturnStatus(mockDataSource, '201');
    global.scrollIntoViewAndClick(addCompanyPageObj.registerButton).then(function() {
      browser.getCurrentUrl().then(function (url) {
        expect(url).toMatch(/.*#\/emailSent/);

Note : Selenium standalone server version is 2.48.2
          IEdriver version is 2.48

I am starting the selenium server from command prompt as : java -jar selenium-sevrer-standalone-2.48.2.jar -port 4444 -Dwebdriver.ie.driver="C:\<path of IEdriver\IEDriverServer.exe"

Please advise on this issue if you guys have encountered this before and a possible solution on this.

@juliemr ;
``````

**Comment by barancev** [comment] 2017-09-05 06:56
I'm sorry we're too late, but we need a sample page that behaves as described to reproduce the issue.

Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment] 2017-09-21 05:12
Closing the issue, there is no reproduction scenario provided.
If the issue is still actual please drop a comment and we'll reopen it.

**Closed by barancev** 2017-09-21 05:12 UTC
Labels: D-IE, R-awaiting answer
