### ISSUE TITLE
Getting text from alert raise exception

### ISSUE THREAD

**Issue by Zelgadiss** [SeleniumHQ/selenium#1499] opened 2016-01-19 08:06 UTC
If I call  **driver.switch_to.alert** and get text then alert is not present in browser, it raise exception:

>File "c:\python33\lib\site-packages\selenium\webdriver\common\alert.py", line 65, in text
 >   return self.driver.execute(Command.GET_ALERT_TEXT)["value"]
 > File "c:\python33\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 201, in execute
  >  self.error_handler.check_response(response)
  >File "c:\python33\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 164, in  check_response
  >  if 'screen' in value:
>TypeError: argument of type 'NoneType' is not iterable

webselenium: 2.49.1
browser: chrome 47.0.2526.106 m
OS: windows 7 x64

**Comment by AutomatedTester** [comment] 2016-01-19 14:27
duplicate of #1500 

In future please give clear steps to reproduce this.

**Closed by AutomatedTester** 2016-01-19 14:27 UTC
