### ISSUE TITLE
Marking the node http://172.17.0.50:5555 as down: cannot reach the node for 2 tries

### ISSUE THREAD

**Issue by trixprod** [SeleniumHQ/selenium#3744] opened 2017-04-02 12:53 UTC
OS:  Linux
Selenium Version: 3.3.1
Browser:  Hub related issue

I have pulled the last version of the docker image : selenium/hub

In the docker hub log i got:

```
12:43:35.509 WARN - Cleaning up stale test sessions on the unregistered node http://172.17.0.50:5555
12:43:40.514 INFO - Registered a node http://172.17.0.50:5555
12:43:50.535 INFO - Marking the node http://172.17.0.50:5555 as down: cannot reach the node for 2 tries
12:44:50.613 INFO - Unregistering the node http://172.17.0.50:5555 because it's been down for 60078 milliseconds
12:44:50.613 WARN - Cleaning up stale test sessions on the unregistered node http://172.17.0.50:5555
12:44:55.610 INFO - Registered a node http://172.17.0.50:5555
12:45:05.626 INFO - Marking the node http://172.17.0.50:5555 as down: cannot reach the node for 2 tries
12:46:05.694 INFO - Unregistering the node http://172.17.0.50:5555 because it's been down for 60068 milliseconds
12:46:05.694 WARN - Cleaning up stale test sessions on the unregistered node http://172.17.0.50:5555
12:46:05.719 INFO - Registered a node http://172.17.0.50:5555
12:46:15.733 INFO - Marking the node http://172.17.0.50:5555 as down: cannot reach the node for 2 tries
```

I'm not the one having that issue, see in comments place :
https://hub.docker.com/r/selenium/hub/

A workaround might be to tweak :
nodeStatusCheckTimeout
unregisterIfStillDownAfter ( default 60 seconds )

Thx for help, trix

**Comment by tparikka** [comment] 2017-04-02 17:13
This issue has been reported to the docker-selenium team as SeleniumHQ/docker-selenium#425. Based on my testing when I reported the issue it seems to be specific to the Docker environment - I have a Grid based on a Windows Server 2008 VM running the 3.3.1 hub and a set of Windows 7 VMs running node 3.3.1 and am able to run end-to-end tests through the grid at saturation without any problems. Same successful results on 3.3.0-americium as well. Based on the logs it looked to me like there is a communication issue between the node and hub containers, which likely wouldn't be fixed by changing the status check timeout or how long to wait before unregistering the node, because the communications are still going to be broken. If anyone more knowledgeable knows otherwise, please correct me.

**Comment by trixprod** [comment] 2017-04-02 19:53
Hello,

Thanks for your anwser.

Indeed, i have found something wrong in two Docker files:
Https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeChrome/generate_config
Https://github.com/SeleniumHQ/docker-selenium/blob/master/Hub/generate_config

Check the line in the hub generate config:
\ "UnregisterIfStillDownAfter \": $ GRID_UNREGISTER_IF_STILL_DOWN_AFTER

For me, that line should be in the NodeChrome generate_config file and not in the generate_config hub file.

Set the line in the good file so you can set high values ​​(60 s by default) and that's fix the issue.

I don't know if it's the right way, but that's a real docker config issue and that's ok for that issue.

**Comment by lmtierney** [comment] 2017-04-05 12:46
Closing as this is a docker-selenium issue

**Closed by lmtierney** 2017-04-05 12:46 UTC

**Comment by tparikka** [comment] 2017-04-05 12:57
@trixprod this issue is being tracked at SeleniumHQ/docker-selenium#425 :)

**Comment by tparikka** [comment] 2017-04-17 20:00
@trixprod I misunderstood your initial issue, it was not at all related to docker-selenium 425. The issue you reported here has now been fixed and merged in under SeleniumHQ/docker-selenium#455 and is available in selenium/hub:3.3.1-cesium. Happy testing!

**Comment by mishrasanjeetr** [comment] 2018-07-19 07:46
Marking the node as down: cannot reach the node for 2 tries
I am also facing same issue on Windows 10 .

**Comment by barancev** [comment] 2018-07-19 11:10
@mishrasanjeetr: Please stop hijacking closed issues! Raise a new one and provide a reproduction scenario.
