### ISSUE TITLE
IEServerDriver unable to locate elements

### ISSUE THREAD

**Issue by ns162002** [SeleniumHQ/selenium#1041] opened 2015-09-15 22:01 UTC
Hi all,

Has anyone experienced issues using the IExplorer web driver with WebComponents? (http://webcomponents.org/)

I've been developing a test suite to perform IT on chrome, firefox and iexplorer (v11.) All tests succeed on chrome and firefox, but the iexplorer web driver does not like some of our pages and is unable to locate elements. The following stack trace shows where the project hangs:

---

Thread [Forwarding findElement on session 66bcb78e-59d1-49ea-b7d4-6f64298a9b47 to remote](Suspended)  
    SocketInputStream.socketRead0(FileDescriptor, byte[], int, int, int) line: not available [native method]  
    SocketInputStream.read(byte[], int, int, int) line: not available  
    SocketInputStream.read(byte[], int, int) line: not available  
    SessionInputBufferImpl.streamRead(byte[], int, int) line: 139  
    SessionInputBufferImpl.fillBuffer() line: 155  
    SessionInputBufferImpl.readLine(CharArrayBuffer) line: 284  
    DefaultHttpResponseParser.parseHead(SessionInputBuffer) line: 140  
    DefaultHttpResponseParser.parseHead(SessionInputBuffer) line: 57  
    DefaultHttpResponseParser(AbstractMessageParser<T>).parse() line: 261  
    LoggingManagedHttpClientConnection(DefaultBHttpClientConnection).receiveResponseHeader() line: 165  
    CPoolProxy.receiveResponseHeader() line: 167  
    HttpRequestExecutor.doReceiveResponse(HttpRequest, HttpClientConnection, HttpContext) line: 272 
    HttpRequestExecutor.execute(HttpRequest, HttpClientConnection, HttpContext) line: 124  
    MainClientExec.execute(HttpRoute, HttpRequestWrapper, HttpClientContext, HttpExecutionAware) line: 271  
    ProtocolExec.execute(HttpRoute, HttpRequestWrapper, HttpClientContext, HttpExecutionAware) line: 184  
    RetryExec.execute(HttpRoute, HttpRequestWrapper, HttpClientContext, HttpExecutionAware) line: 88  
    RedirectExec.execute(HttpRoute, HttpRequestWrapper, HttpClientContext, HttpExecutionAware) line: 110  
    InternalHttpClient.doExecute(HttpHost, HttpRequest, HttpContext) line: 184  
    InternalHttpClient(CloseableHttpClient).execute(HttpHost, HttpRequest, HttpContext) line: 71  
    InternalHttpClient(CloseableHttpClient).execute(HttpHost, HttpRequest, HttpContext) line: 55  
    ApacheHttpClient.fallBackExecute(HttpContext, HttpUriRequest) line: 143 
    ApacheHttpClient.execute(HttpRequest, boolean) line: 89 
    DriverCommandExecutor(HttpCommandExecutor).execute(Command) line: 134  
    DriverCommandExecutor.execute(Command) line: 67 
    InternetExplorerDriver(RemoteWebDriver).execute(String, Map<String,?>) line: 578  
    InternetExplorerDriver(RemoteWebDriver).findElement(String, String) line: 358  
    InternetExplorerDriver(RemoteWebDriver).findElementByCssSelector(String) line: 447  
    By$ByCssSelector.findElement(SearchContext) line: 426  
    InternetExplorerDriver(RemoteWebDriver).findElement(By) line: 350  
    WebDriverFacade.findElement(By) line: 226  
    Actions.moveToElement(By) line: 244 
    DashboardPage.selectMenuProile() line: 71  
    DashboardPageUserSteps$$EnhancerByCGLIB$$f5cae76c(DashboardPageUserSteps).logout() line: 27 
    DashboardPageUserSteps$$EnhancerByCGLIB$$f5cae76c.CGLIB$logout$0() line: not available  
    DashboardPageUserSteps$$EnhancerByCGLIB$$f5cae76c$$FastClassByCGLIB$$b3244328.invoke(int, Object, Object[]) line: not available 
    MethodProxy.invokeSuper(Object, Object[]) line: 228 
    StepInterceptor.invokeMethod(Object, Object[], MethodProxy) line: 310  
    StepInterceptor.executeTestStepMethod(Object, Method, Object[], MethodProxy, Object) line: 295  
    StepInterceptor.runTestStep(Object, Method, Object[], MethodProxy) line: 272  
    StepInterceptor.testStepResult(Object, Method, Object[], MethodProxy) line: 130 
    StepInterceptor.intercept(Object, Method, Object[], MethodProxy) line: 56  
    DashboardPageUserSteps$$EnhancerByCGLIB$$f5cae76c.logout() line: not available  
    LogoutUserSteps.whenUserClicksLogout() line: 45 
    NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]  
    NativeMethodAccessorImpl.invoke(Object, Object[]) line: not available  
    DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: not available  
    Method.invoke(Object, Object...) line: not available  
    StepCreator$ParametrisedStep.perform(UUIDExceptionWrapper) line: 595  
    StoryRunner$FineSoFar.run(Step) line: 566  
    StoryRunner.runStepsWhileKeepingState(RunContext, List<Step>) line: 546 
    StoryRunner.runScenarioSteps(RunContext, Scenario, Map<String,String>) line: 510  
    StoryRunner.runStepsWithLifecycle(RunContext, Lifecycle, Map<String,String>, Scenario, Meta) line: 476  
    StoryRunner.runCancellable(RunContext, Story, Map<String,String>) line: 336 
    StoryRunner.run(RunContext, Story, Map<String,String>) line: 239  
    StoryRunner.run(Configuration, InjectableStepsFactory, Story, MetaFilter, StoryRunner$State) line: 182  
    StoryManager$EnqueuedStory.call() line: 266 
    StoryManager$EnqueuedStory.call() line: 233 
    FutureTask<V>.run() line: not available 
    ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: not available 
    ThreadPoolExecutor$Worker.run() line: not available 
##     Thread.run() line: not available    

I've ensured all special configuration requirements are set correctly for iexplorer (protection mode, zoom, BFCache etc...) and even tried the Microsoft OE WebDriver tool for IExplorer 11 (http://www.microsoft.com/en-us/download/details.aspx?id=44069). Although it is difficult to determine if VENDOR mode is actually used.

I have a workaround that involves using DOM methods to query for elements on these pages (wrapped in override Actions methods). However, this approach breaks consistency with how all other tests are written.

Any suggestions or advice welcomed.

Many thanks.

Neil

**Comment by zoechi** [comment] 2015-09-16 05:27
I had similar experience recently. IE seems to support shadow DOM now which prevents normal selectors from finding elements hidden in shadow DOMs. The shadow piercing selector `/deep/` works in JS but not in webdriver. A workaround is to use JS (executeScript) like `return document.querySelector('someSelector').shadowRoot.querySelector('someOtherSelector'); ` (nested as deep as the elements you are looking for are nested in shadow DOMs) 

I also run into this in Firefox recently (I think v 40.0.0) but worked again in 40.0.3. It seems they enabled shadow DOM by mistake (can still be enabled in preferences) . 

Maybe this is related to recent spec changes where `/deep/` is no longer supported in CSS but only in JS. I don't know how WebDriver implements `findElement()`. 
Chrome also has already started working on removing `/deep/` (and `::shadow`) from CSS.

**Comment by ns162002** [comment] 2015-09-16 09:20
Hi Günter

Thanks for taking the time to respond to my query. It’s comforting to know I’m not alone in experiencing this issue with the IEServerDriver. It’s also good to know that /deep/ is no longer supported in CSS.

The solution I’ve implemented is the exact same as your proposal. I was hoping to avoid implementing custom behaviour for different browsers, but it looks like this is the only option.

Does anyone know what the limitation with the IEServerDriver is? And if it’s likely to be solved?

Thanks again,

Neil

**Comment by jimevans** [comment] 2015-09-22 17:46
@zoechi Where did you get the information that IE supports Shadow DOM? All of the searching I've found (see, for example, [Can I Use](http://caniuse.com/#feat=shadowdom)) indicates that no version of IE supports Shadow DOM.

**Comment by zoechi** [comment] 2015-09-22 19:25
I just found that I have to use `/deep/` to get elements back from 'querySelector()`

**Comment by jimevans** [comment] 2015-09-22 19:42
If, somewhere in your application, you're using a Shadow DOM polyfill, like the one provided by [WebComponents.js](http://webcomponents.org/polyfills/), it may be overriding `document.querySelector()` to support Shadow DOM behavior. In which case, the driver will not have any knowledge of that, mostly because the JavaScript executed by the driver is (correctly!) isolated from the global environment.

**Comment by zoechi** [comment] 2015-09-22 20:13
With polyfills non-shadow-DOM selectors still work, they just rewrite selectors containing `/deep/`, `::shadow`, `::content` and `:host` to equivalent non-shadow-DOM selectors.

**Comment by ns162002** [comment] 2015-10-05 18:50
I can indeed access all elements (in or out of the Shadow) using JavaScript and selector queries. 

To make it easier for our test engineers I also wrapped this complexity into a Selenium artifact, which allows us to have one implementation for all modern browsers too. However, there are still gaps in the implementation and it is proving a lot more effort than expected :( 

Is there anything documented on Selenium's website about these limitations (even if it's the vendor's web drivers). Or are WebComponents not widely used?

**Comment by ns162002** [comment] 2015-11-04 18:58
Hi Jim,

Is it possible to programmatically select the legacy implementation (which injects java script) from JAVA API?

This feature may solve a lot (if not all) of the issues I'm seeing on IE with WebComponents.

If not, please can you point me to location of source that injects the javascript?

Thanks,

Neil

**Comment by ns162002** [comment] 2015-11-07 11:59
I'm guessing the answer to my query above is SeleneseCommandExecutor.

I'll be trying this out very soon, but any feedback welcome on this approach.

**Comment by indolering** [comment] 2015-11-17 19:14
I've tried to implement this workaround and it fails on Safari and IE, something @zoechi [appears to have confirmed on StackOverflow](https://stackoverflow.com/questions/29806506/how-to-properly-translate-shadow-dom-css-selectors-to-non-shadow-dom-selectors/32068762?noredirect=1#comment55267275_32068762).

@jimevans do you know if it is possible to use the native query selector (untouched by the webcomponents.js polyfill) using the browser console?  It's very difficult to debug a selector if you can't access the query selector Selenium is using.

@jimevans would it be difficult to have Selenium use of the client's polyfilled selector?

**Comment by barancev** [comment] 2017-11-27 06:44
Apparently there is no reproduction scenario in this issue. Can anybody create one? We'll transform it to a test case and add it to the selenium test suite to track current status of polyfill support.

**Comment by barancev** [comment] 2019-07-13 05:18
I'm closing this issue because there is no reproduction scenario that we could use to create a regression tests.

**Closed by barancev** 2019-07-13 05:18 UTC
Labels: D-IE
