### ISSUE TITLE
error

### ISSUE THREAD

**Issue by huamgg** [SeleniumHQ/selenium#4967] opened 2017-10-27 04:14 UTC
## Meta -
OS:  

Selenium Version:  IDE.2.9.1

Browser:  Firefox

Browser Version:  

## Actual Behavior -

There was an unexpected error. Msg: TypeError: window.editor.suiteTreeView is undefined
Url: chrome://selenium-ide/content/selenium-ide.xul, line: 1, column: 1
oncommand@chrome://selenium-ide/content/selenium-ide.xul:1:1

**Comment by lmtierney** [comment] 2017-10-27 04:48
Duplicate of #4406

**Closed by lmtierney** 2017-10-27 04:48 UTC
