### ISSUE TITLE
[🐛 Bug]: Module not found: Error: Can't resolve 'fs' in '...\node_modules\selenium-webdriver'

### ISSUE THREAD

**Issue by murcinar** [SeleniumHQ/selenium#13655] opened 2024-03-05 20:58 UTC
### What happened?

Getting the following error during build with Yarn after installing selenium-webdriver package from npm:
Module not found: Error: Can't resolve 'fs' in '...\node_modules\selenium-webdriver'

### How can we reproduce the issue?

```shell
execute:  npm install selenium-webdriver

Then run a build with Yarn
```

### Relevant log output

```shell
Module not found: Error: Can't resolve 'fs' in '...\node_modules\selenium-webdriver'
```

### Operating System

Yarn

### Selenium version

^4.18.1

### What are the browser(s) and version(s) where you see this issue?

Build pipeline

### What are the browser driver(s) and version(s) where you see this issue?

N/A

**Comment by diemol** [comment] 2024-03-05 21:01
Our JS code examples are passing on Linux, macOS, and Windows. You'll need to provide a way to reproduce this.

**Comment by diemol** [comment] 2024-03-11 21:13
I am closing this because we did not get more information to reproduce the issue.

**Closed as not planned by diemol** 2024-03-11 21:13 UTC
Labels: I-defect, J-issue-template
