### ISSUE TITLE
UnsupportedCommandException on MouseMove by using Selenium 3, Firefox and geckodriver.exe

### ISSUE THREAD

**Issue by dgofman** [SeleniumHQ/selenium#3382] opened 2017-01-19 04:24 UTC
OS: Windows 7 and 10
Selenium Drivers: 3.0.1
Browser: Firefox 50.1.0
Browser Drivers: geckodriver-v0.13.0-win32.zip

Step to Reproduce:

Actions action = new Actions(driver);
action.moveToElement(element, 10, 10);
action.build().perform();

Exception:

org.openqa.selenium.UnsupportedCommandException: POST /session/f8fc621e-69fc-4544-8293-782166ff4b01/moveto did not match a known command
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, appBuildId=20161208153507, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=12952, browserVersion=50.1.0, platformVersion=10.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt}]
Session ID: f8fc621e-69fc-4544-8293-782166ff4b01
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteMouse.mouseMove(RemoteMouse.java:97)
	at org.openqa.selenium.interactions.MoveToOffsetAction.perform(MoveToOffsetAction.java:41)
	**at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:50)**

**Comment by lmtierney** [comment] 2017-01-19 10:52
Just as the exception states, actions are not supported in geckodriver + Firefox yet. They are being added now but require API updates to the client bindings first

**Comment by AutomatedTester** [comment] 2017-01-19 11:25
really wish Github would do fuzzy matching when people raise bugs and suggest bugs that it could be.

Duplicate of #2285

**Closed by AutomatedTester** 2017-01-19 11:25 UTC

**Comment by dgofman** [comment] 2017-01-19 18:49
Can we get Selenium 2 drivers working on latest Firefox or at least exposed built in Firefox drivers in Selenium 2 as external file.

**Comment by lmtierney** [comment] 2017-01-19 18:58
The instructions on how to do this are here if you're so inclined #2942

**Comment by dgofman** [comment] 2017-01-19 19:11
To much instructions and people trying and failing. Can someone post an article how we can use Selenium 2 drivers in latest Firefox

**Comment by lmtierney** [comment] 2017-01-19 19:27
That is the only way, in that issue I just linked

**Comment by xikandar** [comment] 2017-01-21 11:15
Getting Same error **"keys did not match a known command"**

Such a luck.... just started selenium learning 3.0.1 to minimize the bugs by using automation testing and here... I got bugs in automation tools as well ;)

Anyway, switching to FireFox45 along with selenium 2.x would work ? I just need to continue my learning and can't afford to be de tracked by such bugs !

**Comment by lmtierney** [comment] 2017-01-21 15:28
Yes, using FF45 ESR and Selenium < 3.0 would work. Alternatively, using FF45 ESR and Selenium 3 will work as long as you pass `false` to the `marionette` capability. Selenium 3 defaults this capability to `true`

**Comment by lkende** [comment] 2018-03-02 17:08
It's now a over a year later, any update on support for mouseMove?  Not seeing it addressed in changelog.

**Comment by jleyba** [comment] 2018-03-02 20:02
https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG#L89
