### ISSUE TITLE
[🐛 Bug]: DevToolsActivePort file doesn't exist using newheadless in linux

### ISSUE THREAD

**Issue by vicozohili** [SeleniumHQ/selenium#11874] opened 2023-04-08 01:05 UTC
### What happened?

When using --headless=new in RemoteWebDriver the error "DevToolsActivePort file doesn't exist"a occurs.
If I use the old --headless the browser launches.

### How can we reproduce the issue?

```shell
Use --headles=new in Linux with RemoteWebdriver.
```

### Relevant log output

```shell
.
```

### Operating System

Linux

### Selenium version

4.8.3

### What are the browser(s) and version(s) where you see this issue?

112

### What are the browser driver(s) and version(s) where you see this issue?

112

### Are you using Selenium Grid?

4.8.3

**Comment by vicozohili** [comment] 2023-04-08 11:36
Chrome is started in linux using the below code:

ChromeOptions options = new ChromeOptions();
options.setPlatformName(Platform.ANY.name());
options.setPageLoadStrategy(PageLoadStrategy.NORMAL);
options.addArguments("--headless=new"); // open headless browser
options.addArguments("--start-maximized"); // open browser in maximized mode
options.addArguments("--window-size=1920,1080"); // browser resolution
options.addArguments("--enable-automation");
options.addArguments("--disable-infobars"); // disabling infobars
options.addArguments("--disable-extensions"); // disabling extensions
options.addArguments("--disable-gpu"); // applicable to windows os only
options.addArguments("--disable-dev-shm-usage"); // overcome limited resource problems
options.addArguments("--no-sandbox"); // bypass OS security model
options.addArguments("--disable-browser-side-navigation");
options.addArguments("--whitelisted-ips"); // bypass whitelisted ips
options.setExperimentalOption("excludeSwitches", new ArrayList<String>(Arrays.asList("disable-popup-blocking"))); // disable Pop-ups
options.setExperimentalOption("prefs", browserPrefs); // browser preferences
options.setAcceptInsecureCerts(true); // bypass SSL certs
WebDriver driver = new RemoteWebDriver(url, options);

Below is the error received when using --headless=new (note this issue does not occur with --headless)

12:33:03.524 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "a359c78a5e92956bc1f7800b75700ba1","eventTime": 1680953583107281378,"eventName": "Session request received by the Distributor","attributes": {"logger": "org.openqa.selenium.grid.distributor.local.LocalDistributor","request.payload": "[Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --headless=new, --start-maximized, --window-size=1920,1080, --enable-automation, --disable-infobars, --disable-extensions, --disable-gpu, --disable-dev-shm-usage, --no-sandbox, --disable-browser-side-navi..., --whitelisted-ips], excludeSwitches: [disable-popup-blocking], extensions: [], prefs: {download.default_directory: \u002fopt\u002finternal\u002fma\u002fjenkins\u002fwo...}}, goog:loggingPrefs: {browser: ALL, client: ALL, driver: ALL, performance: ALL, profiler: ALL, server: ALL}, pageLoadStrategy: normal, platformName: ANY}, Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --headless=new, --start-maximized, --window-size=1920,1080, --enable-automation, --disable-infobars, --disable-extensions, --disable-gpu, --disable-dev-shm-usage, --no-sandbox, --disable-browser-side-navi..., --whitelisted-ips], excludeSwitches: [disable-popup-blocking], extensions: [], prefs: {download.default_directory: \u002fopt\u002finternal\u002fma\u002fjenkins\u002fwo...}}, goog:loggingPrefs: {browser: ALL, client: ALL, driver: ALL, performance: ALL, profiler: ALL, server: ALL}, pageLoadStrategy: normal}]"}}

12:33:03.525 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to create session: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '4.8.3', revision: 'b19b418e60'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.6.1.el7.x86_64', java.version: '17.0.5'
Driver info: driver.version: unknown

**Comment by titusfortner** [comment] 2023-04-10 13:53
I believe this is a duplicate of #11741

**Closed as completed by titusfortner** 2023-04-10 13:53 UTC
Labels: I-defect, J-issue-template
