### ISSUE TITLE
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

### ISSUE THREAD

**Issue by appunikki** [SeleniumHQ/selenium#2569] opened 2016-08-04 08:59 UTC
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by lukeis** [comment] 2016-08-04 15:08
likely ff48 and a duplicate of #2559

**Closed by lukeis** 2016-08-04 15:08 UTC
