### ISSUE TITLE
Unable to free up slot if close the browser manually

### ISSUE THREAD

**Issue by rarelam** [SeleniumHQ/selenium#2939] opened 2016-10-17 04:04 UTC
## Meta -
OS:  
Window 7

Selenium Version:  
Selenium 3

Browser:  
FF, tried with FF only at the moment

FIREFOX 48+ IS ONLY COMPATIBLE WITH GECKODRIVER. Any issue logged here for 48+ will be closed as a duplicate of #2559

If the issue is with Google Chrome consider logging an issue with chromedriver instead:
https://sites.google.com/a/chromium.org/chromedriver/help

If the issue is with Microsoft Edge consider logging an issue with Microsoft instead:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

If the issue is with Firefox GeckoDriver (aka Marionette) consider logging an issue with Mozilla:
https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette

If the issue is with Safari, only Safari 10+ is supported. Please log any Safari issue with Apple:
https://bugreport.apple.com/

If the issue is with PhantomJS consider logging an issue with Ghostdriver:
https://github.com/detro/ghostdriver

-->

Browser Version:  
<49.0.1 (x86)>

## Expected Behavior -
Selenium grid should able to free up browser slot after the browser is closed manually

## Actual Behavior -
Selenium grid is not able to free up browser slot after few minutes

## Steps to reproduce -
1) Write a python script to start FF remotely
2) Close the FF manually after python script is done

![1](https://cloud.githubusercontent.com/assets/1460421/19425151/dcec63fe-9461-11e6-94dc-c07c1cdb2ff8.png)

**Comment by andreicristianpetcu** [comment] 2016-10-17 07:10
You can install WebDriver in Firefox 48+ but not the version shipped by Selenium since it is not signed. If Selenium signed their extension it would work. I have [a signed unlisted version](https://my.owndrive.com/index.php/s/cEXRnP1Y6rLeDEV) of WebDriver but protractor keeps installing the broken one each time I start Firefox instead of using the already installed one.

**Comment by rarelam** [comment] 2016-10-18 06:10
Tried this on Chrome and it has the same problem too... So I think this is not solely by the unlisted FF xpi.

**Comment by andreicristianpetcu** [comment] 2016-10-18 06:18
sorry @rarelam I saw "FIREFOX 48+ IS ONLY COMPATIBLE WITH GECKODRIVER. Any issue logged here for 48+ will be closed as a duplicate of #2559" and I was taught it was related.

**Comment by rarelam** [comment] 2016-10-18 14:36
It is ok @andreicristianpetcu, thank you for your help and solution too

**Comment by lukeis** [comment] 2016-10-18 15:38
this feature of grid is disabled by default. You must (either on the hub, which applies to all nodes that connect, or on the node) specify the -cleanUpCycle and -timeout options.

cleanUpCycle is the time the grid waits before polling if any session is timed out. It is in milliseconds. I would recommend setting it to something like 5000.

timeout is the time in seconds the the grid will allow a session to sit without any new commands that come to it. Default is 1800 (30 minutes!). If you want to see things happen quickly, you will want to reduce this number. Saucelabs for example times out sessions after 15 minutes (900 seconds).

Here for example, I'll configure the hub to time out sessions when 1 minute of inactivity occurs and it will check for that state every 5 seconds. (so theoretical max inactive session timeout is 1min 5sec.)

    java -jar selenium-server-standalone-3.0.0.jar -role hub -cleanUpCycle 5000 -timeout 60

    java -jar selenium-server-standalone-3.0.0.jar -role node


>>> from selenium import webdriver as w
>>> d = w.Remote(desired_capabilities={'browserName':'chrome'})
>>> d.get('http://google.com')
>>> import time
>>> time.sleep(60)
>>> d.title
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 257, in title
    resp = self.execute(Command.GET_TITLE)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Session [97514e4b-a20c-4131-8fb6-18e4e77e9335] was terminated due to TIMEOUT
Stacktrace:
    at org.openqa.grid.internal.ActiveTestSessions.getExistingSession (ActiveTestSessions.java:105)
    at org.openqa.grid.internal.Registry.getExistingSession (Registry.java:404)
    at org.openqa.grid.web.servlet.handler.RequestHandler.getSession (RequestHandler.java:234)
    at org.openqa.grid.web.servlet.handler.RequestHandler.process (RequestHandler.java:120)
    at org.openqa.grid.web.servlet.DriverServlet.process (DriverServlet.java:83)
    at org.openqa.grid.web.servlet.DriverServlet.doGet (DriverServlet.java:61)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:687)
    at javax.servlet.http.HttpServlet.service (HttpServlet.java:790)
    at org.seleniumhq.jetty9.servlet.ServletHolder.handle (ServletHolder.java:808)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle (ServletHandler.java:587)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle (SessionHandler.java:221)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle (ContextHandler.java:1127)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doScope (ServletHandler.java:515)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doScope (SessionHandler.java:185)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope (ContextHandler.java:1061)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle (ScopedHandler.java:141)
    at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle (HandlerWrapper.java:97)
    at org.seleniumhq.jetty9.server.Server.handle (Server.java:499)
    at org.seleniumhq.jetty9.server.HttpChannel.handle (HttpChannel.java:310)
    at org.seleniumhq.jetty9.server.HttpConnection.onFillable (HttpConnection.java:257)
    at org.seleniumhq.jetty9.io.AbstractConnection$2.run (AbstractConnection.java:540)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:635)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run (QueuedThreadPool.java:555)
    at java.lang.Thread.run (Thread.java:745)


Grid terminal output when this occurred:

08:34:07.181 INFO - Got a request to create a new session: Capabilities [{browserName=chrome}]
08:34:07.182 INFO - Trying to create a new session on test slot {seleniumProtocol=WebDriver, browserName=chrome, maxInstances=5, platform=MAC}
08:35:12.637 WARN - session ext. key 97514e4b-a20c-4131-8fb6-18e4e77e9335 has TIMED OUT due to client inactivity and will be released.

Node output:

08:34:07.974 INFO - Done: [new session: Capabilities [{browserName=chrome}]]
08:34:10.777 INFO - Executing: [get: http://google.com])
08:34:11.388 INFO - Done: [get: http://google.com]
08:35:12.641 INFO - Executing: [delete session: 97514e4b-a20c-4131-8fb6-18e4e77e9335])
08:35:12.716 INFO - Done: [delete session: 97514e4b-a20c-4131-8fb6-18e4e77e9335]


As you can see, the hub timed out the session after 1 minute 5 seconds :)

**Closed by lukeis** 2016-10-18 15:38 UTC
Labels: C-grid
