### ISSUE TITLE
ElementNotInteractableException - Can't click on <tr> elements within table

### ISSUE THREAD

**Issue by buekera** [SeleniumHQ/selenium#5782] opened 2018-04-16 13:23 UTC
## Meta
OS:  Arch Linux x64 Kernel 4.15.15
Selenium Version: tested with 3.8.1/3.11.0
Browser: tested with Firefox 59.0.2/60.0b8 x64
GeckoDriver: tested with 0.18.0/0.20.1

## Additional info

I'm using Geb (http://www.gebish.org) for my GUI tests which actually only wraps the `click()` function of selenium. A traceback shows that the exception is thrown by selenium itself, which led me to the issue section of selenium instead of Geb.

## Workaround

Using javascript to perform the click works flawlessly as a workaround but is not very desirable as it leads to ugly code and puts all tests into a briddle state.

## Expected Behavior

Element in table should be selected

## Actual Behavior

Element in table will not be selected and exception `org.openqa.selenium.ElementNotInteractableException: Element <tr class=""> could not be scrolled into view` will be thrown.
The table has no scroll bar and the `<tr>` elements are neither hidden in any way nor disabled or something similar.

## DOM structure

![image](https://user-images.githubusercontent.com/12516018/38811431-c02d7bf0-4189-11e8-9b23-a9867030a177.png)

```html
<table cellspacing="0">
            <colgroup>
                <col width="90px">
	        	<col>
            	<col width="60px">
            </colgroup>
            <tbody>
            	<tr class="active" onclick="location.href='/some/domain/administration/tabelle/anrede/edit.do?admintabelle_anrede=167809'" style="cursor: pointer;">
                        <td class="first">
                            anderes</td>
                        <td>
                            </td>
                        <td class="last">
                            2</td>
                    </tr>
                <tr class="" onclick="location.href='/some/domain/administration/tabelle/anrede/edit.do?admintabelle_anrede=289429'" style="cursor: pointer;">
                        <td class="first">
                            weiblich</td>
                        <td>
                            Geänderter Eintrag</td>
                        <td class="last">
                            4</td>
                    </tr>
                <tr class="" onclick="location.href='/some/domain/administration/tabelle/anrede/edit.do?admintabelle_anrede=167810'" style="cursor: pointer;">
                        <td class="first">
                            männlich</td>
                        <td>
                            Herr</td>
                        <td class="last">
                            </td>
                    </tr>
                <tr class="" onclick="location.href='/some/domain/administration/tabelle/anrede/edit.do?admintabelle_anrede=167811'" style="cursor: pointer;">
                        <td class="first">
                            weiblich</td>
                        <td>
                            Frau</td>
                        <td class="last">
                            </td>
                    </tr>
                <tr class="" onclick="location.href='/some/domain/administration/tabelle/anrede/edit.do?admintabelle_anrede=224435'" style="cursor: pointer;">
                        <td class="first">
                            weiblich</td>
                        <td>
                            Frau</td>
                        <td class="last">
                            </td>
                    </tr>
                <tr class="" onclick="location.href='/some/domain/administration/tabelle/anrede/edit.do?admintabelle_anrede=328816'" style="cursor: pointer;">
                        <td class="first">
                            männlich</td>
                        <td>
                            Eintrag löschen</td>
                        <td class="last">
                            </td>
                    </tr>
                </tbody>
        </table>
```

## Steps to reproduce -

Create a table with similar structure as showed above and try to select an entry using the `click()` method provided by selenium.

**Comment by barancev** [comment] 2018-04-17 10:06
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by buekera** [comment] 2018-04-17 12:44
I will create an example when I have time. This may take a while.

**Comment by barancev** [comment] 2018-05-03 07:13
Closing the issue as there is no reproduction scenario. Feel free to reopen it once you have got one.

**Closed by barancev** 2018-05-03 07:13 UTC
Labels: R-awaiting answer

**Comment by snowymike** [comment] 2018-05-18 14:54
ok, here's the html
```
<html>
<body>
	<table cellspacing="0">
		<tbody>
			<tr onclick="window.alert('hi')" style="cursor: pointer;">
				<td>Column 1</td>
				<td>Column 2</td>
			</tr>
		</tbody>
	</table>
</body>
</html>
```

and here's the test code showing the problem.

```
		driver.get("file:///C:/PATH/geckoTrClick.html");
		WebElement element = browser.findElement(By.tagName("tr"));
		element.click();		
```

passes in chrome, fails in gecko

**Comment by snowymike** [comment] 2018-05-18 14:55
doesn't appear i have the ability to reopen myself.  let me know if any part of my steps above are unclear.

**Comment by snowymike** [comment] 2018-05-19 00:00
also, i see that clicking the first child of the tr works fine in gecko.  it's the tr in particular that cannot be clicked without getting the exception originally reported.
```
org.openqa.selenium.ElementNotInteractableException: Element <tr> could not be scrolled into view
```

**Comment by snowymike** [comment] 2018-05-22 14:07
@buekera @barancev either of you have the ability to reopen?

**Comment by barancev** [comment] 2018-05-22 14:40
After some triaging I've found that it's a known issue in geckodriver: https://bugzilla.mozilla.org/show_bug.cgi?id=1448825

I'll not reopen it here because there is nothing we can do on Selenium side, it should be fixed in browser.
