### ISSUE TITLE
[🐛 Bug]: [Python] [Remote Driver] Unable to use devtools for network operations 

### ISSUE THREAD

**Issue by kenjke** [SeleniumHQ/selenium#11230] opened 2022-11-07 15:30 UTC
### What happened?

I'm using Selenium for web automation testing. I have a case to emulate "throttle" in browser. When I tried to use devtools with Google chrome driver, it worked fine. But for remote driver it didn't work at all.

### How can we reproduce the issue?

```shell
docker pull selenium/hub:4.5.0
docker pull selenium/node-crhome:4.5.0

docker run -d -p 4442-4444:4442-4444 --name selenium-hub-example -l example selenium/hub:4.5.0 and get HUB_IP 
docker run -d -e SE_EVENT_BUS_HOST=${HUB_IP} --shm-size="2g" -e JAVA_OPTS="-Xmx6g" -e VNC_NO_PASSWORD=1 -p 5901:5900 -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -e SCREEN_WIDTH=1920 -e SCREEN_HEIGHT=1080 -v /dev/shm:/dev/shm -l example --name selenium-chrome-example-5901 selenium/node-chrome:4.5.0

Run any test using any test library (e.g. pytest) and use remove driver.
Execute below code:
    def set_network_conditions(
            self, offline, latency=5, throughput=512 * 1024
    ):
        async def net_cond():
            async with self.driver.bidi_connection() as session:
                cdpSession = session.session
                c1 = await cdpSession.execute(
                   devtools.emulation.set_geolocation_override(
                   latitude=41.8781, longitude=-87.6298, accuracy=100)
                )
                c2 = await cdpSession.execute(devtools.network.enable())
                c3 = await cdpSession.execute(devtools.network.can_emulate_network_conditions())
                c4 = await cdpSession.execute(
                    devtools.network.emulate_network_conditions(
                        offline=offline,
                        latency=latency,
                        download_throughput=throughput,
                        upload_throughput=-throughput
                    )
                )

        trio.run(net_cond)
        self.driver.get("https://my-location.org/")
```

### Relevant log output

```shell
If I set on pdb for trio.run(net_cond), I will receive (None, None, True, None). "Throttle" won't work.
```

### Operating System

macOS Monterrey 12.6.1, Ubuntu 18.04.5 LTS

### Selenium version

Selenium 4.5.0, Python 3.9.5

### What are the browser(s) and version(s) where you see this issue?

Chrome 106

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 106

### Are you using Selenium Grid?

4.5.0

**Comment by symonk** [comment] 2022-11-07 17:11
would need to debug, but the actual `async` support is lacking at the moment

edit: ignore, previous advice was not relevant.  will take a look this evening for `Remote` based examples

**Comment by kenjke** [comment] 2022-11-07 17:26
@symonk set geo location works fine for remote driver. All network operations don't work for remote driver.

**Comment by kenjke** [comment] 2022-12-07 09:00
@diemol @symonk can we have an update on this issue? I can reproduce it on latest selenium version (4.7.0)

**Comment by diemol** [comment] 2022-12-07 09:16
Most likely the issue is because you need to set the Grid Url https://github.com/SeleniumHQ/docker-selenium#grid-url-and-session-timeout 
I did not read this through last time. I do not think it is related to Python.

**Comment by diemol** [comment] 2023-05-04 09:11
Closing as we never got feedback after the last comment.

**Closed as completed by diemol** 2023-05-04 09:11 UTC
Labels: J-awaiting answer, I-defect
