### ISSUE TITLE
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by LirazShay** [SeleniumHQ/selenium#4091] opened 2017-05-28 09:48 UTC
## Meta -
OS:  Windows 7

Selenium Version:  3.4.0.0

Browser:  Chrome

Sometimes I'm getting this exception that is thrown from selenium:
--InvalidOperationException
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at OpenQA.Selenium.Support.PageObjects.DefaultPageObjectMemberDecorator.CreateTypeForASingleElement()
   at OpenQA.Selenium.Support.PageObjects.DefaultPageObjectMemberDecorator.get_InterfaceProxyType()
   at OpenQA.Selenium.Support.PageObjects.DefaultPageObjectMemberDecorator.CreateProxyObject(Type memberType, IElementLocator locator, IEnumerable`1 bys, Boolean cache)
   at OpenQA.Selenium.Support.PageObjects.DefaultPageObjectMemberDecorator.Decorate(MemberInfo member, IElementLocator locator)
   at OpenQA.Selenium.Support.PageObjects.PageFactory.InitElements(Object page, IElementLocator locator, IPageObjectMemberDecorator decorator)
   at OpenQA.Selenium.Support.PageObjects.PageFactory.InitElements(ISearchContext driver, Object page)
   at CommonLogic.PageObject.PageObjectBase..ctor(MyWebDriver driver) in C:\Git\auto-tests\Shared\CommonLogic\CommonLogic\PageObject\PageObjectBase.cs:line 35
   at BEPortalPageObject.LoginPage..ctor(MyWebDriver driver) in C:\Git\auto-tests\Tests\BEPortal\BEPortalPageObject\LoginPage.cs:line 25
Result Message:	
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
## Expected Behavior -
I'm using PageFactory in my page object and it's happens sometimes
```cs
  public class LoginPage
    {
       [FindsBy(How = How.CssSelector, Using = @"a[href='/register?redirect=/']")]
        private IWebElement _newUserButton;

        [FindsBy(How = How.Name, Using = "password")]
        private IWebElement _passwordTextField;
    }
```
## Actual Behavior -
No exception should be thrown, or more meaningful exception should be thrown with help how to avoid it. 
## Steps to reproduce -
Happens sometimes for unknown reason.

**Comment by jfisher446** [comment] 2017-06-07 06:42
@AutomatedTester This issue appears to be dotnet related and is incorrectly labeled with Java.

**Comment by p0deje** [comment] 2017-06-07 10:31
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by LirazShay** [comment] 2017-06-07 15:57
@p0deje 
I cannot reproduce it.
I've written:
"Happens sometimes for unknown reason."

**Comment by p0deje** [comment] 2017-06-07 16:12
Well, I'm going to keep that open but I guess @jimevans might just close this as it's very hard to almost impossible to debug issues without an SSCCE.

**Comment by awilliams722** [comment] 2017-10-18 16:51
Will this issue be investigated?
  
We have experienced this twice today. Our test suite has around 600 tests and gets kicked off at least 4 times a day.  We see this error at least once a day at the minimum.  It's frustrating.  I hope someone at least tries to investigate the issue.  

We are using:
(Session info: chrome=61.0.3163.100)
(Driver info: chromedriver=2.33.506120 
(platform=Windows NT 10.0.14393 x86_64)

One of our devs investigated and gave me this info:  

-- Might have something to do with running tests with page objects concurrently. The exception is thrown from `DefaultPageObjectMemberDecorator.cs` (Selenium's file) in the `CreateTypeForASingleElement()` method, at the foreach loop. The loop is going through a list interface types (IWebElement, ILocatable, etc.), and the list is being changed while the loop is running. --

**Comment by bronumski** [comment] 2017-11-08 19:10
Same issue here. Happens when calling `PageFactory.InitElements(driver, this);` in a constructor. Not had any problems before. This is the first failure noticed without any code changes.
Selenium packages
```
  <package id="Selenium.RC" version="3.1.0" targetFramework="net451" />
  <package id="Selenium.Support" version="3.5.2" targetFramework="net451" />
  <package id="Selenium.WebDriver" version="3.5.2" targetFramework="net451" />
  <package id="Selenium.WebDriver.ChromeDriver" version="2.32.0" targetFramework="net451" />
  <package id="Selenium.WebDriverBackedSelenium" version="3.5.2" targetFramework="net451" />
```
Stack trace.
```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at OpenQA.Selenium.Support.PageObjects.DefaultPageObjectMemberDecorator.CreateTypeForASingleElement()
   at OpenQA.Selenium.Support.PageObjects.DefaultPageObjectMemberDecorator.get_InterfaceProxyType()
   at OpenQA.Selenium.Support.PageObjects.DefaultPageObjectMemberDecorator.CreateProxyObject(Type memberType, IElementLocator locator, IEnumerable`1 bys, Boolean cache)
   at OpenQA.Selenium.Support.PageObjects.DefaultPageObjectMemberDecorator.Decorate(MemberInfo member, IElementLocator locator)
   at OpenQA.Selenium.Support.PageObjects.PageFactory.InitElements(Object page, IElementLocator locator, IPageObjectMemberDecorator decorator)
   at OpenQA.Selenium.Support.PageObjects.PageFactory.InitElements(ISearchContext driver, Object page)
```

**Comment by cgoldberg** [comment] 2017-11-09 18:18
>  Might have something to do with running tests with page objects concurrently. 

yup.. the .NET Page Object classes are not thread safe.
https://github.com/SeleniumHQ/selenium/issues/1607

**Comment by bronumski** [comment] 2017-11-09 19:08
@cgoldberg - Yep that's what it is. We are running tests in parallel.

**Comment by jimevans** [comment] 2018-03-29 04:00
Since .NET PageFactory is deprecated, closing this issue.

**Closed by jimevans** 2018-03-29 04:00 UTC
Labels: C-dotnet
