### ISSUE TITLE
[🐛 Bug]: Initialization of WebDriver failed when executed tests in parallel

### ISSUE THREAD

**Issue by nvborisenko** [SeleniumHQ/selenium#11226] opened 2022-11-06 18:01 UTC
### What happened?

Selenium Manager is not ready to be executed simultaneously.

### How can we reproduce the issue?

```shell
Execute tests in parallel using .NET binding when cache of Selenium Manager is empty.
```

### Relevant log output

```shell
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: Uncategorized, message: "The process cannot access the file because it is being used by another process." }', src\files.rs:70:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Operating System

Windows 10

### Selenium version

4.6.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Selenium Manager

**Comment by nvborisenko** [comment] 2022-11-11 21:44
@diemol so is it binding related? I can provide a fix for this in .Net: this binding will never execute Selenim Manager simultaneously. But it will be scoped to process, what means user might even execute his application in different processes simultaneously. I think better place for fix is Selenium Manager itself, it will fix parallel tests execution in all bindings implicitly.

**Comment by diemol** [comment] 2022-11-14 16:04
I guess I did not read the error provided properly, I assumed it was .NET. Sorry.

@bonigarcia , can you please have a look?

**Comment by bonigarcia** [comment] 2022-11-15 12:41
I cannot reproduce this issue. How exactly did run the tests, @nvborisenko?

**Comment by nvborisenko** [comment] 2022-11-15 12:47
@bonigarcia empty cache of Selenium Manager, and then execute selenium manager many times in parallel.

**Comment by bonigarcia** [comment] 2022-11-15 13:10
@nvborisenko Still, I cannot reproduce it with that description, sorry. An executable piece of code (i.e, a test or script) will be helpful.

**Comment by nvborisenko** [comment] 2022-11-15 13:32
[ConsoleApp4.zip](https://github.com/SeleniumHQ/selenium/files/10013039/ConsoleApp4.zip)

This example starts 10 chrome browsers in parallel. To run it in console `dotnet run`.

![image](https://user-images.githubusercontent.com/22616990/201932141-c5e36319-b386-43fb-872f-078f8372ed72.png)

**Comment by bonigarcia** [comment] 2022-11-16 14:42
There was a condition race when trying to uncompress/execute the resulting driver (chromedriver, in this case) in parallel for the first time. I have just committed a [patch](https://github.com/SeleniumHQ/selenium/compare/trunk...se_mrg_fix_parallel) to fix this issue.

@nvborisenko I tested with the project you provided (thanks for that!) and the solution seems to work nicely. Can you please test it on your side? To do that, you can get the new binary of Selenium Manager from [here](https://github.com/SeleniumHQ/selenium/actions/runs/3480237123). You need to download the Windows binary from that page and compress it to the nuget repo in your computer (overwriting the previous `selenium-manager.exe`) :

`%userprofile%\.nuget\packages\selenium.webdriver\4.6.0\manager\windows`

Then, clear the Selenium Manager cache and run your project again. Please let me know the result, thanks.

**Comment by nvborisenko** [comment] 2022-11-16 14:55
@bonigarcia I tested it as well, works good. Thanks.

**Closed as completed** 2022-11-17 15:52 UTC
Labels: C-dotnet, I-defect, C-rust
