### ISSUE TITLE
Basic Auth with invalid credentials hangs infinitely

### ISSUE THREAD

**Issue by nathanjohnson320** [SeleniumHQ/selenium#1979] opened 2016-04-17 04:05 UTC
## Meta -
OS: Windows 10
Selenium Version: 2.53.0
Browser: Firefox
Browser Version: 45.0.2 (64-bit)

## Expected Behavior -
Invalid credentials should terminate when the browser timeout is passed or delete session is called.

## Actual Behavior -
Invalid credentials hang infinitely.

## Steps to reproduce -
1. Send navigate request with invalid credentials in url.
2. Send delete session call
3. Wait infinitely

I'm using the standalone webdriver sending requests with JSONwire protocol.

Output is the following:
03:46:15.979 INFO - Executing: [get: http://user:invalidpass@test.localserver.com])
03:47:15.976 INFO - Executing: [delete session: ae722ff5-111c-42f3-ad04-64062a27976f])

Neither completes since it's hung at the "get"

**Comment by lukeis** [comment] 2016-10-25 05:09
duplicate of #453

**Closed by lukeis** 2016-10-25 05:09 UTC
