### ISSUE TITLE
shadowroot via execute script not working in powershell.

### ISSUE THREAD

**Issue by wrharper** [SeleniumHQ/selenium#8726] opened 2020-09-22 23:54 UTC
## 🐛 Bug Report

If the issue is with Google Chrome consider logging an issue with chromedriver instead:
https://chromedriver.chromium.org/help
^i have also done this just in case...

## Expected behavior

When trying to get a shadowroot within powershell it always returns null even though the path has been verified and is correct..

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

ExecuteScript is not working in powershell? i have tried quite a few different versions of selenium using the latest .net frameworks possible for each version.

```
function expandShadow($element){[OpenQA.Selenium.Remote.RemoteWebElement]$s_root = $ChromeDev.ExecuteScript("return arguments[0].shadowroot", $element); return $s_root;}
$initRoot = $ChromeDev.FindElementByTagName("sn-workspace-content") #<---works
$shadow1 = expandShadow($initRoot)
$shadow1.gettype() #<---null????
```

```
html is like this:
<sn-workspace-content blah blah>
   #shadow-root (open) <---can't see in here...
```

```
a more direct approach with the same result:
$ChromeDev.ExecuteScript("return document.getElementsByTagName('sn-workspace-content').shadowroot"
^ returns null
$ChromeDev.ExecuteScript("return document.getElementsByTagName('sn-workspace-content')"
^returns correctly
".shadowroot is not working in powershell!"
```

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 85.0.4183.121 64-bit
Browser Driver version: 85.0.4183.37 (latest avaiable...)
Language Bindings version: PowerShell Win 10 
Selenium Grid version (if applicable): TRIED TONS OF VERSIONS

**Comment by jdpurcell** [comment] 2020-09-23 19:42
.shadowRoot should have an uppercase R.

**Comment by wrharper** [comment] 2020-09-24 20:06
The issue still persists. I have had had to manually do execute script to the entire path because of 5-10 shadow nested.... I basically can’t even program in PowerShell at this point and am just creating LONG direct paths for each object slowly. Kind of defeating the entire purpose of all “findelementby” possibilities.When you can’t you find by id/class and then just do .shadowRoot on the object? Why all of this crazy workaround stuff? Doesn’t that defeat the whole purpose of object orientation?Just adding .shadowRoot even with the correct spelling doesn’t work I have to crazy stuff like $Driver.ExecuteScript(“return document.querySelector(‘body > div > div’).shadowRoot.querySelector(‘ div, div’).shadowRoot”) and so on like 10 layers deep. It’s kinda crazy 😃I can’t even pick a root path like $root = $Driver.ExecuteScript(“return document.querySelector(‘body > div > div’).shadowRoot.querySelector(‘ div, div’).shadowRoot”); $root.executescript(“continue here…blah blah”) because after you create and object out of the $driver.executescript it’s not the drive type anymore and something else. So I have to manually do the entire path for every single object with executescript. On Wed, Sep 23, 2020, 3:42 PM J.D. Purcell <notifications@github.com> wrote:.shadowRoot should have an uppercase R.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by diemol** [comment] 2020-09-28 20:41
@ziron999 please correct me if I am wrong, but I don't see where you are using Selenium in this bug report. 
I'll go ahead and close this, but if the issue is actually related to Selenium, please feel free to comment and post some code to reproduce the issue using Selenium.

**Closed as completed by diemol** 2020-09-28 20:41 UTC
Labels: A-needs-triaging

**Comment by wrharper** [comment] 2020-09-29 08:32
Actually it's 100% selenium... websites with shadowroot do not work right in powershell and you end up stringing extremely long executescripts.
