### ISSUE TITLE
Copy paste not working using Robot Class: Ctrl+C; content is not saving into clipboard, but it used to work perfectly fine few days back

### ISSUE THREAD

**Issue by praveenreddygm** [SeleniumHQ/selenium#5328] opened 2018-01-11 15:06 UTC
OS: Windows 10
Selenium Version: 3.5.3; WebDriver
Browser: NA; Trying to copy text from outlook/Any file using Robot class and its features; Basically we can open outlook using Sikuli or Winnium; here problem is about Robot class and its features that "Using Robot class i have copied content during run time BCDE and trying to retrieve it from clipboard to print again in console or any other file. But it's fetching old value from the clip board? but it used to work perfectly fine few days back.
Expected Output is: BCDE"

its copying text and not storing text into clipboard using robot class Key Events, but it used to working fine previously

robot.keyPress(KeyEvent.VK_SHIFT);
robot.keyPress(KeyEvent.VK_RIGHT);
robot.keyPress(KeyEvent.VK_SHIFT);
robot.keyPress(KeyEvent.VK_RIGHT);
robot.keyPress(KeyEvent.VK_SHIFT);
robot.keyPress(KeyEvent.VK_RIGHT);
robot.keyPress(KeyEvent.VK_SHIFT);
robot.keyPress(KeyEvent.VK_RIGHT);

Thread.sleep(2000);
robot.keyRelease(KeyEvent.VK_RIGHT);
robot.keyRelease(KeyEvent.VK_SHIFT);
Thread.sleep(2000);
robot.keyPress(KeyEvent.VK_CONTROL);
robot.keyPress(KeyEvent.VK_C);
Thread.sleep(2000);
robot.keyRelease(KeyEvent.VK_CONTROL);
robot.keyRelease(KeyEvent.VK_C);
Thread.sleep(2000);
robot.keyPress(KeyEvent.VK_RIGHT);
robot.keyRelease(KeyEvent.VK_RIGHT);

String str=(String)Toolkit.getDefaultToolkit().getSystemClipboard().getData(DataFlavor.stringFlavor);

**Console**:

Exception in thread "main" java.awt.datatransfer.UnsupportedFlavorException: Unicode String
at sun.awt.datatransfer.SunClipboard.getData(Unknown Source)

**Comment by lmtierney** [comment] 2018-01-11 15:56
Please don't just open a new issue when your last one was closed. Duplicate of #5327

**Closed by lmtierney** 2018-01-11 15:56 UTC
