### ISSUE TITLE
SetCookies is not accepting extra keys in a cookie

### ISSUE THREAD

**Issue by dira1122** [SeleniumHQ/selenium#7054] opened 2019-03-22 19:58 UTC
## 💬 Questions and Help
Currently when I set sookies I want to add the specific website cookie keys that are not supported by Cookies constructor.
The Cookies constructor is currently only accepting following keys- 
name, value, domain, path, expiry, isSecure, isHttpOnly

I cannot find any option to add more keys that specific websites are expecting. 

Kindly let me know if there is any option to add more keys to the cookies

**Comment by rapidroamer** [comment] 2019-03-23 15:00
I did some digging in WebDriver Code. It appears that by design the cookie can have only these attributes at least from Webdriver perspective.

Are you sure about the specific keys that you want to add.. May be they are part of the Cookie Value ?

I did some JS injection but that did not go anywhere.

                  ```
 Cookie ck = new Cookie(name,value,domain,path,expiry,isSecure);
                    driver.manage().addCookie(ck); // This will add the stored cookie to your current session

                    String myCookieValue = driver.manage().getCookieNamed(name).toString();
                    System.out.println(myCookieValue);

                    myCookieValue = myCookieValue + ";myKey=myValue";

                    JavascriptExecutor js = (JavascriptExecutor) driver;
                    js.executeScript(" document.cookie = '"+name+"="+myCookieValue+"';");
```

**Comment by jimevans** [comment] 2019-03-23 15:30
I’m confused. A cookie can only have one value. When you call `document.cookie` In JavaScript, and you receive a string that contains a list of key/value pairs separated by semicolons (`;`), _each_ pair represents a cookie. The string lists _all_ of the cookies defined on the page (that aren’t HTTP-only cookies, since those aren’t accessible in JavaScript). What “other keys” would one be expecting in a cookie?

**Comment by rapidroamer** [comment] 2019-03-23 16:05
Hi @jimevans. I think the questioner is trying to ask if it’s possible have custom attribute value pairs for a given cookie. And I made a rudimentary attempt to check if I can add any. 

I think the cookie attributes are fixed by RFC spec. 

@dira1122 can you please have a look at https://tools.ietf.org/html/rfc6265#section-4.1 and tell if that helps.

**Comment by rapidroamer** [comment] 2019-03-23 16:13
cookie-av         = expires-av / max-age-av / domain-av /
                     path-av / secure-av / httponly-av /
                     extension-av

I see something called extension av ; I don’t understand it fully from RFC. Not sure it will help the questioner. Just putting it out here.

**Comment by dira1122** [comment] 2019-03-23 21:27
Thank you. @rapidroamer you are right, I am looking to add custom attribute that is currently not supported by Selenium Cookies class. 
These are the attributes that the website is expecting. I am not sure how to pass the extra attributes 

 "domain": "",
    "hostOnly": false,
    "httpOnly": true,
    "name": "exp_rt",
    "path": "/",
    "sameSite": "",
    "secure": false,
    "session": true,
    "storeId": "",
    "value": "",
    "id": ""

**Comment by diemol** [comment] 2019-03-24 10:56
@dira1122 
You could try to set those values and see if it works for you.
One of the constructors accepts the name and value of the cookie, I am not sure why you need more.
```
  /**
   * Create a cookie for the default path with the given name and value with no expiry set.
   *
   * @param name The cookie's name
   * @param value The cookie's value
   */
  public Cookie(String name, String value) {
    this(name, value, "/", null);
  }
```

Moreover, this is not really an issue with Selenium and it is more a question on its usage. Keep in mind that this is not a help forum, please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

**Closed by diemol** 2019-03-24 10:56 UTC
