### ISSUE TITLE
selenium-html-runner throws BindException

### ISSUE THREAD

**Issue by vainikkaj** [SeleniumHQ/selenium#2706] opened 2016-09-02 12:42 UTC
## Meta -
OS:  Ubuntu 16.04

Selenium Version:  3.0.0-beta3

Browser:  Firefox 

Browser Version:  48.0

## Expected Behavior -

Seeing new Firefox opening and browsing to www.google.com

## Actual Behavior -

Firefox opens and then closes immediately with following error message. 

## Steps to reproduce -

With latest geckodriver and simple IDE test.

```
vainiju@vainiju-ThinkPad-P50 ~/selenium-html
» l
yhteensä 19M
-rw-r--r-- 1 vainiju vainiju  763 2016-09-02 12:41 simple-ide-generated-test.html
-rwxrwxr-x 1 vainiju vainiju 3.7M 2016-08-03 01:49 geckodriver
-rw-r----- 1 vainiju vainiju  15M 2016-09-02 01:29 selenium-html-runner-3.0.0-beta3.jar
```

Executing selenium-html-runner causes following error.

```
vainiju@vainiju-ThinkPad-P50 ~/selenium-html 
» /opt/tools/oracle-jdk/jdk1.8.0_91/bin/java -jar selenium-html-runner-3.0.0-beta3.jar /tmp/output-selenium simple-ide-generated-test.html http://www.google.com false *firefox

Sep 02, 2016 1:37:41 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1472812662277	Marionette	INFO	Listening on port 42734
1472812663347	Marionette	INFO	startBrowser d26740c7-6738-4f90-8628-dd5fecdbf346
1472812663355	Marionette	INFO	sendAsync d26740c7-6738-4f90-8628-dd5fecdbf346

(process:7296): GLib-CRITICAL **: g_path_get_basename: assertion 'file_name != NULL' failed
Sep 02, 2016 1:37:43 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
2016-09-02 13:37:43.549:INFO::main: Logging initialized @2243ms
2016-09-02 13:37:43.577:INFO:osjs.Server:main: jetty-9.2.z-SNAPSHOT
2016-09-02 13:37:43.590:INFO:osjs.ServerConnector:main: Started ServerConnector@1ddf84b8{HTTP/1.1}{0.0.0.0:7330}
2016-09-02 13:37:43.591:INFO:osjs.Server:main: Started @2284ms
2016-09-02 13:37:43.592:INFO:osjs.ServerConnector:main: Stopped ServerConnector@1ddf84b8{HTTP/1.1}{0.0.0.0:7330}
[Child 7296] ###!!! ABORT: Aborting on channel error.: file /build/firefox-6p7T67/firefox-48.0+build2/ipc/glue/MessageChannel.cpp, line 2046
[Child 7296] ###!!! ABORT: Aborting on channel error.: file /build/firefox-6p7T67/firefox-48.0+build2/ipc/glue/MessageChannel.cpp, line 2046
Sep 02, 2016 1:37:43 PM org.openqa.selenium.server.htmlrunner.HTMLLauncher mainInt
WARNING: Test of browser failed: *firefox
java.io.IOException: java.lang.RuntimeException: java.net.BindException: Osoite on jo käytössä
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.determineSuiteUrl(HTMLLauncher.java:188)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:120)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:85)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.mainInt(HTMLLauncher.java:239)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.java:251)
Caused by: java.lang.RuntimeException: java.net.BindException: Osoite on jo käytössä
	at org.openqa.selenium.net.PortProber.pollPort(PortProber.java:154)
	at org.openqa.selenium.net.PortProber.pollPort(PortProber.java:137)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.determineSuiteUrl(HTMLLauncher.java:182)
	... 4 more
Caused by: java.net.BindException: Osoite on jo käytössä
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.Socket.bind(Socket.java:644)
	at org.openqa.selenium.net.PortProber.pollPort(PortProber.java:146)
	... 6 more
```

**Comment by lukeis** [comment] 2016-09-02 16:11
you have some kind of port conflict here, "Osoite on jo käytössä" -> "The address is already in use" (thanks google translate!).

Although it doesn't say which port, which it normally should, i see 7330 used in there, maybe that was the problem?

**Comment by vainikkaj** [comment] 2016-09-05 06:36
This happens every time with Chrome and Firefox when suite is given as a file.

After digging into the source code, it seems that test suite is expected to given as an URL.
Both Firefox and Chrome work with suite parameter `http://localhost:1234/suite.html`.

However, I fell that serving suite over http is more of a workaround and I'll leave this ticket open.

**Comment by lukeis** [comment] 2016-09-05 15:22
file:///absolute/path/to/file is also a valid url

But I agree this should be more forgiving

**Comment by shs96c** [comment] 2016-09-09 16:21
Just pushed a change to make this more forgiving, and to correctly serve content off the local disk.

**Comment by shs96c** [comment] 2016-09-09 16:21
I think that the change fixes the problem. Closing for now, but if you continue having problems, please let me know.

**Closed by shs96c** 2016-09-09 16:21 UTC

**Comment by karthiks3000** [comment] 2016-09-25 21:21
Hello,

I am getting below error.

Sep 25, 2016 5:19:08 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1474838349352	Marionette	INFO	Listening on port 49383
1474838350525	Marionette	INFO	startBrowser 4618baef-3f2a-4a69-ade1-2ad107deaca2
Sep 25, 2016 5:19:10 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
JavaScript error: chrome://marionette/content/listener.js, line 958: NS_ERROR_MALFORMED_URI:

**Comment by karthiks3000** [comment] 2016-09-25 21:21
my code is:

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class testSample {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		//FirefoxDriver driver = new FirefoxDriver()
		//WebDriver driver;
		System.setProperty("webdriver.gecko.driver", "C:\\Users\\Shayn\\Downloads\\geckodriver-v0.10.0-win64 (1)\\geckodriver.exe");
		WebDriver driver = new FirefoxDriver();
		driver.get("www.gmail.com");
	}

}

**Comment by lukeis** [comment] 2016-09-25 22:37
@karthiks3000 the url needs to be fully qualified "http://www.gmail.com"

also... don't try to automate gmail with selenium, use their REST api - 
https://developers.google.com/gmail/api/

**Comment by mcalello** [comment] 2016-10-25 14:11
Simon, did this fix make it into 3.0.1?

When I switch from a URL http path to my test suite, to a local filesystem path, I still get the following error when running selenium-html-runner-3.0.1.jar:

`Oct 25, 2016 10:03:40 AM org.openqa.selenium.server.htmlrunner.HTMLLauncher mainInt
WARNING: Test of browser failed: *googlechrome
java.io.IOException: java.lang.RuntimeException: java.net.BindException: Address already in use: JVM_Bind
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.determineSuiteUrl(HTMLLauncher.java:180)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:108)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.mainInt(HTMLLauncher.java:245)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.java:273)
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use: JVM_Bind
        at org.openqa.selenium.net.PortProber.pollPort(PortProber.java:154)
        at org.openqa.selenium.net.PortProber.pollPort(PortProber.java:137)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.determineSuiteUrl(HTMLLauncher.java:174)
        ... 3 more
Caused by: java.net.BindException: Address already in use: JVM_Bind
        at java.net.DualStackPlainSocketImpl.bind0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
        at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
        at java.net.PlainSocketImpl.bind(Unknown Source)
        at java.net.Socket.bind(Unknown Source)
        at org.openqa.selenium.net.PortProber.pollPort(PortProber.java:146)
        ... 5 more`

**Comment by bperel** [comment] 2016-12-08 14:05
I have this error in 3.0.1 as well

**Comment by javapapo** [comment] 2016-12-14 09:12
+1 on 3.0.1 still this error

**Comment by petegibbins** [comment] 2016-12-16 17:59
I'm trying to run automation from command line using selenium-html-runner-301 and getting "Address already in use: JVM_Bind"

Command line:
`java -jar selenium-html-runner-3.0.1.jar -htmlSuite "*firefox" http://192.168.42.33:8105/Login/Login "C:\tests\workspace\suite.html" "c:\tests\seleniumResults.html"`

Firefox launches briefly then closes with the bind error in the command window.

**Comment by schunt1** [comment] 2016-12-26 21:23
Me too, firefox opens and closes straight away. I'm using similar syntax to the above.

**Comment by rfrijbroek** [comment] 2017-01-09 13:34
Having the same problem here. Can someone reopen this issue? Or has someone created a new one?

**Comment by akshay243** [comment] 2017-01-12 14:40
I got this error can any help me

Exception in thread "main" org.openqa.selenium.NoSuchElementException: Unable to locate element: //*[@id='Email']
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'User-PC', ip: '192.168.0.100', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], prefs={}}, appBuildId=20161208153507, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=324, browserVersion=50.1.0, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt}]
Session ID: 75c3fc55-9770-46fa-90ba-dfb4c25fc5dd
*** Element info: {Using=xpath, value=//*[@id='Email']}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:473)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:360)
	at firstjava.troo.main(troo.java:14)

**Comment by Jith85** [comment] 2017-01-18 01:14
Got the same error message while trying with TestNG. Its not yet fixed

code used :
package firsttestng;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.Assert;
import org.testng.annotations.Test;


public class NewTest {
	{ System.setProperty("webdriver.gecko.driver","E:\\Jithin\\academy\\Selenium new\\geckodriver.exe");}
	public String baseurl="https://www.google.co.in";
	public WebDriver driver= new FirefoxDriver();
  @Test
  public void f() {
	  driver.get(baseurl);
	  String expectedtitle="Google";
	  String actualtitle=driver.getTitle();
	  Assert.assertEquals(actualtitle, expectedtitle);
	  driver.quit();
  }
}


####
getting below error
###

1484701201412	geckodriver	INFO	Listening on 127.0.0.1:25252
Jan 18, 2017 6:30:01 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1484701202086	mozprofile::profile	INFO	Using profile path C:\Users\USER\AppData\Local\Temp\rust_mozprofile.hoqR8CcfRBdG
1484701202088	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe
1484701202092	geckodriver::marionette	INFO	Connecting to Marionette on localhost:61422
1484701203567	Marionette	INFO	Listening on port 61422
Jan 18, 2017 6:30:07 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
[TestNG] Running:
  C:\Users\USER\AppData\Local\Temp\testng-eclipse--1600924961\testng-customsuite.xml

[Child 6832] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056
Jan 18, 2017 6:30:17 AM org.openqa.selenium.os.UnixProcess destroy
SEVERE: Unable to kill process with PID 1680
PASSED: f

===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@32502377: 9 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@7bab3f1a: 86 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@4d5650ae: 43 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 1 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@6221a451: 7 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@4d154ccd: 6 ms

**Comment by GrayedFox** [comment] 2017-02-03 20:24
Can confirm this same error in our Jenkins CI pipeline bulids

**Comment by AnanyaTesting** [comment] 2017-05-28 06:46
i am stuck terribly....is any one there to help

**Comment by AnanyaTesting** [comment] 2017-05-28 06:47
1495952161955	geckodriver	INFO	Listening on xxxx
1495952162685	geckodriver::marionette	INFO	Starting browser \\?\C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
1495952163695	addons.manager	ERROR	startup failed: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIFile.create]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/moduJavaScrilpet esrr/oFri:l erUetsiolusr.cjes:m/ /:g:r eF/imloedUutlielss/_AgdedtoDniMra n:a:g elri.njes m7,0 "l i ndea t1a6:5 no] Stack trac7e::  FNS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
ileUtils_getDir()@resource://gre/modules/FileUtils.jsm:70 < FileUtils_getFile()@resource://gre/modules/FileUtils.jsm:42 < validateBlocklist()@resource://gre/modules/AddonManager.jsm:674 < startup()@resource://gre/modules/AddonManager.jsm:837 < startup()@resource://gre/modules/AddonManager.jsm:3145 < observe()@resource://gre/components/addonManager.js:65
[GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU
1495952167511	Marionette	INFO	Listening on port 57274
JavaScript error: resource://gre/modules/AddonManager.jsm, line 2572: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
May 28, 2017 11:46:08 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C

**Comment by ganilreddy** [comment] 2017-05-28 08:35
@AnanyaTesting 👍  Even i am also facing same kind of issues, these errors because of Mozilla compatibility. i think we can ignore it.

**Comment by VikasSalunke** [comment] 2017-07-12 08:44
I am also facing similar issue.

2125988	geckodriver	INFO	Listening on 127.0.0.1:32468
1499842126381	geckodriver::marionette	INFO	Starting browser /usr/lib/firefox/firefox with args ["-marionette"]
1499842130360	Marionette	INFO	Listening on port 43966
Jul 12, 2017 12:18:50 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1499842177170	Marionette	INFO	New connections will no longer be accepted

I am getting the above error after executing the Program. I guess it is not related to Program.
System Configuration:
Ubuntu 16.04
Selenium 3.4
Java 1.8
Mozilla FF 54.0(64 bit)
Also, I am New to Selenium Webdriver world.

**Comment by TinaMartin** [comment] 2017-11-06 17:54
Hi,
I'm getting the below error


Nov 06, 2017 6:47:08 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
