### ISSUE TITLE
IE Window is getting closed during test execution in Windows 10 64 bit machine

### ISSUE THREAD

**Issue by csharsha** [SeleniumHQ/selenium#8994] opened 2020-12-22 20:08 UTC
## 🐛 Bug Report

IE Window is getting closed during test execution in Windows 10 64 bit machine. I tried using IEDriverServer version 2.52, 3.7, 3.8 and 3.9.

## To Reproduce

I have an application in which once user enters username and password and clicks login, Login window closes and application home page is displayed. When I tested this scenario in Windows 7 and IE 11 with IEDriverServer 2.52.2 version, everything worked as expected. But when I tried the same flow in Windows 10 64 bit and IE 11 (both 32 and 64) with Driver versions 2.52.2, 3.7 - 3.9, IE window is closing immediately after click on login button and I am getting 'Unable to get browser' NoSuchWindow Exception on execution of next command. 

## Expected behavior

Login window closes and application home window should be displayed.

## Test script or set of commands reproducing this issue

            driver = new InternetExplorerDriver();
            driver.Navigate().GoToUrl(<URL>);

            driver.FindElement(By.XPath("//input[@ID='UserName']")).SendKeys(<Username>);
            driver.FindElement(By.XPath("//input[@Id='Password']")).SendKeys(<Password);

            driver.FindElement(By.Id("login")).Click();

            System.Threading.Thread.Sleep(5000);

            int count = driver.WindowHandles.Count;
            count = count - 1;
            string LatestWindow = driver.WindowHandles[count];
            driver.SwitchTo().Window(LatestWindow);

            driver.FindElement(By.Id("ic_C_C30")).Click();

            System.Threading.Thread.Sleep(5000);

            count = driver.WindowHandles.Count;
            count = count - 1;

            //This line gives error since window is closed and count will be 0
            var window = driver.WindowHandles[count];

## Environment

OS: Windows 10 64 Bit
Browser: Internet Explorer
Browser version: 11.0.205
Browser Driver version: IEDriverServer 2.52.2, 3.7.0, 3.8.0, 3.9.0

**Comment by jimevans** [comment] 2020-12-22 20:54
The most recent IE driver is 3.150.1. What happens when you use that version?

**Comment by csharsha** [comment] 2020-12-23 04:39
Yes I tried with both 64 and 32 bit of 3.150.1 version drivers but the result is same. Also I have created 'FEATURE_BFCACHE' regedit key to retain ie instance but no luck.

**Comment by diemol** [comment] 2021-01-17 19:58
@csharsha, could you please provide a complete script? For example, this line `driver.Navigate().GoToUrl(<URL>);`, which `URL`? 
We'd be happy to have a look once a complete script is provided.

**Comment by jimevans** [comment] 2021-01-17 20:35
@csharsha Also:

    ReadOnlyCollection<string> windowHandles = driver.WindowHandles
    driver.SwitchTo().Window(windowHandles[windowHandles.Count - 1]);

is _**NOT**_ guaranteed to give you the most recently opened window. That's probably not germane to this particular issue, but it's a poor practice that you'll want to avoid.

**Comment by csharsha** [comment] 2021-01-23 14:38
> @csharsha, could you please provide a complete script? For example, this line `driver.Navigate().GoToUrl(<URL>);`, which `URL`?
> We'd be happy to have a look once a complete script is provided.

Thanks for your reply but I cannot disclose the URL and also its the application hosted on our company LAN and hence cannot be accessed outside our infrastructure.

**Comment by csharsha** [comment] 2021-01-23 14:42
> @csharsha Also:
> 
> ```
> ReadOnlyCollection<string> windowHandles = driver.WindowHandles
> driver.SwitchTo().Window(windowHandles[windowHandles.Count - 1]);
> ```
> 
> is _**NOT**_ guaranteed to give you the most recently opened window. That's probably not germane to this particular issue, but it's a poor practice that you'll want to avoid.

Yes @jimevans  it might not give me the instance of recently opened window but it should not crash all the IE windows opened. As I mentioned in the issue it is working as expected in older IE versions.

**Comment by diemol** [comment] 2021-01-23 15:02
@csharsha, well, without a public URL or an HTLM page we cannot run the test script you provided. 

Should we close this issue since it is not possible to reproduce it?

**Comment by csharsha** [comment] 2021-01-25 12:42
> @csharsha, well, without a public URL or an HTLM page we cannot run the test script you provided.
> 
> Should we close this issue since it is not possible to reproduce it?

Please give me some time, so that I can try to recreate my application and submit for your evaluation.

**Comment by AutomatedTester** [comment] 2021-02-17 14:14
Closing as we haven't had any reply in a while. please raise a new bug when you have got the steps to replicate.

**Closed as completed by AutomatedTester** 2021-02-17 14:14 UTC
Labels: J-awaiting answer

**Comment by csharsha** [comment] 2021-05-26 16:36
Hi the new window is opened using javascript "document.Logon.submit();". I have attached the source code for your reference. I have unchecked "Enable Protected Mode" for all Zones and also have set "FEATURE_BFCACHE" in RegEdit as well. Any help would be a life saver.

[HTMLContent_LogonPage.txt](https://github.com/SeleniumHQ/selenium/files/6548344/HTMLContent_LogonPage.txt)
