### ISSUE TITLE
Selenium Grid Chrome Node - Chrome failed to start

### ISSUE THREAD

**Issue by DavidStahl97** [SeleniumHQ/selenium#9440] opened 2021-05-04 16:57 UTC
## 🐛 Bug Report

Since a view days running tests with a chrome node in selenium grid doesn't work for me anymore. The last line of the chrome node logs says that chrome crashed (Response code 500. Message: unknown error: Chrome failed to start: crashed.\n (chrome not reachable)).

It works for me fine when using a firefox node or when using a chrome driver locally without using selenium grid.

```
2021-05-04 16:10:28,041 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing

2021-05-04 16:10:28,043 INFO supervisord started with pid 8

2021-05-04 16:10:29,046 INFO spawned: 'xvfb' with pid 10

2021-05-04 16:10:29,047 INFO spawned: 'vnc' with pid 11

2021-05-04 16:10:29,049 INFO spawned: 'novnc' with pid 12

2021-05-04 16:10:29,050 INFO spawned: 'selenium-node' with pid 13

2021-05-04 16:10:29,064 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2021-05-04 16:10:29,064 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2021-05-04 16:10:29,065 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2021-05-04 16:10:29,065 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

Configuring server...

Setting up SE_NODE_HOST...

Setting up SE_NODE_PORT...

Setting up SE_NODE_GRID_URL...

Starting Selenium Grid Node with configuration:

[events]

publish = "tcp://selenium-hub:4442"

subscribe = "tcp://selenium-hub:4443" 

[node]

session-timeout = "300"

override-max-sessions = false

max-sessions = 1 

16:10:29.815 INFO [LogManager$RootLogger.log] - Using the system default encoding

16:10:29.818 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing

16:10:29.919 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443

16:10:29.979 INFO [UnboundZmqEventBus.<init>] - Sockets created

16:10:30.081 INFO [UnboundZmqEventBus.<init>] - Event bus ready

16:10:30.156 INFO [NodeServer.createHandlers] - Reporting self as: http://172.21.0.3:5555

16:10:30.172 INFO [NodeOptions.getSessionFactories] - Detected 12 available processors

16:10:30.187 INFO [NodeOptions.discoverDrivers] - Discovered 1 driver(s)

16:10:30.212 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome","platformName": "LINUX"} 1 times

16:10:30.221 INFO [Node.<init>] - Binding additional locator mechanisms: name, id

16:10:30.395 INFO [NodeServer$1.start] - Starting registration process for node id bed65ecd-2b24-44a8-af66-02216a6fd137

16:10:30.396 INFO [NodeServer.execute] - Started Selenium node 4.0.0-beta-3 (revision 5d108f9a67): http://172.21.0.3:5555

16:10:30.411 INFO [NodeServer$1.lambda$start$1] - Sending registration event...

16:10:31.023 INFO [NodeServer.lambda$createHandlers$1] - Node has been added

Starting ChromeDriver 90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}) on port 27869

Only local connections are allowed.

Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.

ChromeDriver was started successfully.

[1620144666.519][SEVERE]: bind() failed: Cannot assign requested address (99)

16:11:08.209 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "f27e54c48a0b4f927df64f30c126a00a","spanId": "d8b7c6d8cdc1175f","spanKind": "INTERNAL","eventTime": 1620144668194799300,"eventName": "exception","attributes": {"driver.url": "http:\u002f\u002flocalhost:27869","exception.message": "Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.\n (chrome not reachable)\n (The process started from chrome location \u002fusr\u002fbin\u002fgoogle-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nBuild info: version: '4.0.0-beta-3', revision: '5d108f9a67'\nSystem info: host: '987a00db7242', ip: '172.21.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.128-microsoft-standard', java.version: '1.8.0_282'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.\n (chrome not reachable)\n (The process started from chrome location \u002fusr\u002fbin\u002fgoogle-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nBuild info: version: '4.0.0-beta-3', revision: '5d108f9a67'\nSystem info: host: '987a00db7242', ip: '172.21.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.128-microsoft-standard', java.version: '1.8.0_282'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:128)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:63)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:143)\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:325)\n\tat org.openqa.selenium.grid.node.NewNodeSession.execute(NewNodeSession.java:52)\n\tat org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.security.RequiresSecretFilter.lambda$apply$0(RequiresSecretFilter.java:64)\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.node.Node.execute(Node.java:240)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.node.config.DriverServiceSessionFactory","session.capabilities": "{\"browserName\": \"chrome\",\"goog:chromeOptions\": {}}\n"}} 

Starting ChromeDriver 90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}) on port 7430

Only local connections are allowed.

Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.

C[hro1m62e0D1r4i4v6e7r1 .w4a2s started successfully.

7][SEVERE]: bind() failed: Cannot assign requested address (99)

16:11:12.780 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "012dd4050fdd434ad31e59719d041c6f","spanId": "ea6ca3f338ee0f80","spanKind": "INTERNAL","eventTime": 1620144672766739400,"eventName": "exception","attributes": {"driver.url": "http:\u002f\u002flocalhost:7430","exception.message": "Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.\n (chrome not reachable)\n (The process started from chrome location \u002fusr\u002fbin\u002fgoogle-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nBuild info: version: '4.0.0-beta-3', revision: '5d108f9a67'\nSystem info: host: '987a00db7242', ip: '172.21.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.128-microsoft-standard', java.version: '1.8.0_282'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.\n (chrome not reachable)\n (The process started from chrome location \u002fusr\u002fbin\u002fgoogle-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nBuild info: version: '4.0.0-beta-3', revision: '5d108f9a67'\nSystem info: host: '987a00db7242', ip: '172.21.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.128-microsoft-standard', java.version: '1.8.0_282'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:128)\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:63)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:143)\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:325)\n\tat org.openqa.selenium.grid.node.NewNodeSession.execute(NewNodeSession.java:52)\n\tat org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.security.RequiresSecretFilter.lambda$apply$0(RequiresSecretFilter.java:64)\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.node.Node.execute(Node.java:240)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.node.config.DriverServiceSessionFactory","session.capabilities": "{\"browserName\": \"chrome\",\"goog:chromeOptions\": {}}\n"}}
```

## To Reproduce

```yml
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"

  firefox:
    image: selenium/node-firefox:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6902:5900"

  selenium-hub:
    image: selenium/hub:4.0.0-beta-3-20210426
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

With C# (Selenium.WebDriver 4.0.0-beta2):
```csharp
var options = new ChromeOptions();

using var driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"),
    options.ToCapabilities(), TimeSpan.FromMinutes(6));

driver.Navigate().GoToUrl("https://www.selenium.dev/");

driver.Close();
```

Or Python (selenium==4.0.0.b3):
```python
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = Options()

driver = webdriver.Remote(
   command_executor='http://127.0.0.1:4444/wd/hub',
   options=chrome_options)

try:
    driver.get('https://www.selenium.dev/')
finally:
    driver.close()
```

## Expected behavior

Should run without errors

**Comment by diemol** [comment] 2021-05-07 09:16
What OS are you using?

**Comment by DavidStahl97** [comment] 2021-05-07 13:41
Windows 10 Enterprise
Version 1903
OS build 18362.1256

**Comment by diemol** [comment] 2021-05-10 11:24
Then this is a duplicate of https://github.com/SeleniumHQ/docker-selenium/issues/1267, please check the last comment to see how to fix it.

**Closed as completed by diemol** 2021-05-10 11:24 UTC
Labels: J-awaiting answer
