### ISSUE TITLE
Node Firefox Profile - Sample Code does not run, 

### ISSUE THREAD

**Issue by cminion** [SeleniumHQ/selenium#3408] opened 2017-01-24 12:42 UTC
## Meta -
OS: OSX  
Selenium Version:   Latest
Browser:  Firefox - latest

## Expected Behavior -
I expect to see http://www.google.com to be loaded in a firefox window with the firefox profile having the property security.ssl.enable_ocsp_stapling set to false. 
## Actual Behavior -
Errors when running 
node index.js 
/Users/chris/src/seleniumAPIC/node_modules/selenium-webdriver/lib/promise.js:2517
        throw error;
        ^

TypeError: Cannot read property 'execute' of undefined
    at /Users/chris/src/seleniumAPIC/node_modules/selenium-webdriver/lib/webdriver.js:822:24
From: Task: WebDriver.navigate().to(http://google.com)
    at Driver.schedule (/Users/chris/src/seleniumAPIC/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
    at Navigation.to (/Users/chris/src/seleniumAPIC/node_modules/selenium-webdriver/lib/webdriver.js:1140:25)
    at Driver.get (/Users/chris/src/seleniumAPIC/node_modules/selenium-webdriver/lib/webdriver.js:997:28)
    at Object.<anonymous> (/Users/chris/src/seleniumAPIC/index.js:44:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
## Steps to reproduce -
Run this code based on the sample.

var firefox = require('selenium-webdriver/firefox');

var profile = new firefox.Profile();
profile.setPreference('security.ssl.enable_ocsp_stapling', false);

var options = new firefox.Options().setProfile(profile);
var driver = new firefox.Driver(options);

 driver.get('http://google.com');

**Comment by lmtierney** [comment] 2017-01-24 13:24
I'm guessing this is the duplicate of #3377, see the commit that fixed it

**Closed** 2017-01-30 18:56 UTC
