### ISSUE TITLE
Selenium 3.5.0 Grid with Firefox (Session was terminated due to BROWSER_TIMEOUT )

### ISSUE THREAD

**Issue by vveliev** [SeleniumHQ/selenium#4508] opened 2017-08-18 17:56 UTC
## Meta -
OS:  Linux/Windows

Selenium Version:  3.5.0

Browser:  Firefox 

Browser Version:  54/55

## Expected Behavior -
When using the browser with selenium grid , expecting it to keep session when element now found on the page.
## Actual Behavior -
after first element that was not found on the page:
```
@browser.status
*** Selenium::WebDriver::Error::UnknownError Exception: Session [05da79a0-bfae-4f9a-808f-77d5e5f7fbcd] was terminated due to BROWSER_TIMEOUT
```

## Steps to reproduce -
1. setup selenium grid, with firefox
2. run script against grid (go to some page)
3. search for the element that is not present on the page
4. try to do anything after (Session [05da79a0-bfae-4f9a-808f-77d5e5f7fbcd] was terminated due to BROWSER_TIMEOUT)

https://github.com/mozilla/geckodriver/issues/881

**Comment by matthew-horrocks** [comment] 2017-08-21 07:53
This is probably the same as #4454

**Comment by vveliev** [comment] 2017-08-22 22:37
same for selenium 3.5.2

**Comment by barancev** [comment] 2017-08-29 15:32
Duplicate of #4454

**Closed by barancev** 2017-08-29 15:32 UTC
Labels: C-grid
