### ISSUE TITLE
[🐛 Bug]: Not able to view Grid Dashboard with version 4.19.1

### ISSUE THREAD

**Issue by VasanthVJ** [SeleniumHQ/selenium#13818] opened 2024-04-12 15:34 UTC
### What happened?

Hi, While I try to run the Selenium Hub with the latest version, the Dashboard is not loading and gives a blank page. However, it works fine with the previous version(4.18.1). Also, I didn't face any issue in connecting the nodes with the latest version. Issue is observed only on latest version.

### How can we reproduce the issue?

```shell
Download the latest version and I'm using .bat file to start the Hub. In the batch file I have added details of port and events details along with the selenium server .jar version details. So, double click on the .bat to start and check if Dashboard page loads.
```

### Relevant log output

```shell
Couldn't share at the moment.
```

### Operating System

10

### Selenium version

4.19.1

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

chrome

### Are you using Selenium Grid?

4.19.1

**Comment by diemol** [comment] 2024-04-14 11:59
I cannot reproduce the issue, please share the command you are using to start the Grid.

**Comment by csgbn** [comment] 2024-04-15 16:59
This has already been reported https://github.com/SeleniumHQ/selenium/issues/13757

**Comment by VietND96** [comment] 2024-04-15 23:03
I think most users usually access localhost:4444, it can redirect to ui

In your case, lets open chrome dev tool, then access localhost:4444/ui, when the page is blank, is there any error in console or 404 request in network tab

**Comment by diemol** [comment] 2024-04-16 08:01
OK, then duplicate of https://github.com/SeleniumHQ/selenium/issues/13757

**Closed as not planned by diemol** 2024-04-16 08:01 UTC
Labels: I-defect, A-needs-triaging

**Comment by feller-kristina** [comment] 2024-04-24 23:55
@VasanthVJ was you able to find the fix? I see exact the same issue.
