### ISSUE TITLE
SelectElement with xpath not working

### ISSUE THREAD

**Issue by kbourro** [SeleniumHQ/selenium#7292] opened 2019-06-14 14:00 UTC
Selecting an element with xpath returns an IWebElement then SelectElement returns an error "the path is not of a legal form". Exist and Enabled works correctly.
SelectElement select = new SelectElement(_driver.FindElements(By.XPath("xpath-string"))[0]);

**Comment by jimevans** [comment] 2019-06-14 14:11
This is not globally broken for all users and all sites for all XPath values. You'll need to provide more information to have a chance of tracking down what the issue is. Please provide a full example, complete with an HTML page (or URL to a public site) that can reproduce the issue.

**Comment by kbourro** [comment] 2019-06-14 14:31
SelectElement select = new SelectElement(_driver.FindElements(By.XPath("//select[@id='sex']"))[0]);

HTML:
<select name="sex" id="sex"><option value="unknown" selected="">Please select</option><option value="male">Male</option><option value="female">Female</option></select>

**Comment by lmtierney** [comment] 2019-06-14 14:56
> Please provide a full example, complete with an HTML page (or URL to a public site) that can reproduce the issue.

The HTML as given works fine for selecting by xpath. Please provide an actual failing page.

**Comment by barancev** [comment] 2019-07-15 19:40
Closing the issue as there is no reproduction scenario provided.

**Closed by barancev** 2019-07-15 19:40 UTC
Labels: R-awaiting answer
