### ISSUE TITLE
getAllCookies returns new issue for Windows 10 and IE11

### ISSUE THREAD

**Issue by reekic** [SeleniumHQ/selenium#5301] opened 2018-01-08 08:45 UTC
## Meta:
OS:   64bit Windows 10  Pro  version 1709 (OS Build 16299.15)
Selenium Version:   3.8.1
Browser:   Internet Explorer 11.15.16299.0 
WebDriver: InternetExplorerDriver  32 bit

## Reproduce process:
1. on local,  using new InternetExplorerDriver() and  navigate().to("http://xxxxx")
2. Send message :  Get localhost:xxxx/session/xxxxxxxxxxx/cookie 
3. The listening port is shut down

## Error Log:
Started InternetExplorerDriver server (32-bit)
3.8.0.0
Listening on port 43088
Only local connections are allowed
Jan 08, 2018 4:18:06 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Exception in thread "main" org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:43088 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'DESKTOP-UDKNAH9', ip: '172.21.123.189', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_152'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions.getCookies(RemoteWebDriver.java:748)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions.getCookieNamed(RemoteWebDriver.java:783)
	at self.test.App.main(App.java:25)

**Comment by eyal919** [comment] 2018-05-22 12:07
+1

**Comment by jimevans** [comment] 2018-05-22 12:13
This should be fixed in 3.11.1 of the IEDriverServer.exe. If the issue is still happening using that version or later of the driver executable, please open a new issue with a full repro case.

**Closed by jimevans** 2018-05-22 12:13 UTC
Labels: D-IE
