### ISSUE TITLE
Click on map of OpenLayers 3 not working!

### ISSUE THREAD

**Issue by cpsTinK** [SeleniumHQ/selenium#2029] opened 2016-04-29 14:36 UTC
## Meta -
OS: Windows 7
Selenium Version:  2.53.0
Browser:  Firefox
Browser Version:  46.0

## Expected Behavior -
Click and Double Click on map of OpenLayers 3 for testing drawing features

## Actual Behavior -
Click and Double Click on map of OpenLayers 3 not working!

## Steps to reproduce -
firefox = new FirefoxDriver();
firefox.Navigate().GoToUrl( @"http://test.domain" );

//firefox.FindElementByClassName( "ol-zoom-in" ).Click();      // it is working  (click on control OL3)
//firefox.FindElementByClassName( "ol-zoom-out" ).Click();     // it is working

// create interaction Modify .......

Actions actions = new Actions( firefox );
actions.MoveToElement( firefox.FindElementByCssSelector( "#map" ) ).MoveByOffset( 300, 300 ).Click().Build().Perform();
// it is not working

var elAction = actions.MoveToElement( firefox.FindElementByCssSelector( "#map" ), 500, 200 ).ClickAndHold();
elAction.Release();
elAction.Build().Perform();
// it is not working

Actions action = new Actions( firefox );
action.MoveToElement( firefox.FindElement( By.Id( "map" ) ) ).Perform();
action.Click().Perform();
action.MoveByOffset( 100, 300 ).Perform();
action.Click().Perform();
action.MoveByOffset( 200, -200 ).Perform();
action.DoubleClick().Perform();
action.Click().DoubleClick().Build().Perform();
// it is not working

**Comment by AlexLuya** [comment] 2016-06-15 04:32
same problem here,dragAndDrop doesn't also

**Comment by lukeis** [comment] 2016-10-25 04:23
dragAndDrop is a duplicate of #1365

I can't tell if this is truly the case or not, since the test case isn't completely reproducible. You must provide a real link or create one using jsfiddle.net in order for us to investigate further.

**Closed by lukeis** 2016-10-25 04:23 UTC
