### ISSUE TITLE
[🐛 Bug]: release selenium-java-4.3.0.zip contains duplicate files

### ISSUE THREAD

**Issue by martin-juhlin** [SeleniumHQ/selenium#10877] opened 2022-07-14 14:18 UTC
### What happened?

I downloaded selenium-java-4.3.0.zip from below URL. 
https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.3.0/selenium-java-4.3.0.zip
MD5 sum: acc0dd39d95b184d0bc2bc3c8e329ffe

When uncompressed with unzip under MacOS 12.13.1, the files "lib/netty-transport-native-epoll-4.1.78.Final.jar" and "lib/netty-transport-native-kqueue-4.1.78.Final.jar" exist multiple times and unzip ask if I want to overwrite files. A file should be unique and only exist once.

### How can we reproduce the issue?

```shell
Download the release file and check with unzip and zipinfo commands available in the OS. Se output log below.
```

### Relevant log output

```shell
bash-3.2$ curl -L "https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.3.0/selenium-java-4.3.0.zip" --output selenium-java-4.3.0.zip 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 21.1M  100 21.1M    0     0  11.8M      0  0:00:01  0:00:01 --:--:-- 21.7M

bash-3.2$ md5 selenium-java-4.3.0.zip 
MD5 (selenium-java-4.3.0.zip) = acc0dd39d95b184d0bc2bc3c8e329ffe

bash-3.2$ unzip -v -l selenium-java-4.3.0.zip "*native*"
Archive:  selenium-java-4.3.0.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
   37668  Stored    37668   0% 01-01-2010 00:00 0e0d741d  lib/netty-transport-native-epoll-4.1.78.Final.jar
    5594  Stored     5594   0% 01-01-2010 00:00 ce54b85b  lib/netty-transport-native-epoll-4.1.78.Final.jar
   24656  Stored    24656   0% 01-01-2010 00:00 26fa2ae5  lib/netty-transport-native-kqueue-4.1.78.Final.jar
   25740  Stored    25740   0% 01-01-2010 00:00 adb94c88  lib/netty-transport-native-kqueue-4.1.78.Final.jar
    5510  Stored     5510   0% 01-01-2010 00:00 6424f8fc  lib/netty-transport-native-kqueue-4.1.78.Final.jar
   43215  Stored    43215   0% 01-01-2010 00:00 43db1b3c  lib/netty-transport-native-unix-common-4.1.78.Final.jar
--------          -------  ---                            -------
  142383           142383   0%                            6 files

bash-3.2$ zipinfo -v selenium-java-4.3.0.zip lib/netty-transport-native-epoll-4.1.78.Final.jar
Archive:  selenium-java-4.3.0.zip
There is no zipfile comment.

End-of-central-directory record:
-------------------------------

  Zip archive file size:                  22162804 (0000000001522D74h)
  Actual end-cent-dir record offset:      22162782 (0000000001522D5Eh)
  Expected end-cent-dir record offset:    22162782 (0000000001522D5Eh)
  (based on the length of the central directory and its expected offset)

  This zipfile constitutes the sole disk of a single-part archive; its
  central directory contains 86 entries.
  The central directory is 6928 (0000000000001B10h) bytes long,
  and its (expected) offset in bytes from the beginning of the zipfile
  is 22155854 (000000000152124Eh).


Central directory entry #68:
---------------------------

  lib/netty-transport-native-epoll-4.1.78.Final.jar

  offset of local header from start of archive:   21212780
                                                  (000000000143AE6Ch) bytes
  file system or operating system of origin:      Unix
  version of encoding software:                   0.0
  minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
  minimum software version required to extract:   1.0
  compression method:                             none (stored)
  file security status:                           not encrypted
  extended local header:                          no
  file last modified on (DOS date/time):          2010 Jan 1 00:00:00
  32-bit CRC value (hex):                         0e0d741d
  compressed size:                                37668 bytes
  uncompressed size:                              37668 bytes
  length of filename:                             49 characters
  length of extra field:                          0 bytes
  length of file comment:                         0 characters
  disk number on which file begins:               disk 1
  apparent file type:                             binary
  Unix file attributes (100555 octal):            -r-xr-xr-x
  MS-DOS file attributes (00 hex):                none

  There is no file comment.

Central directory entry #69:
---------------------------

  lib/netty-transport-native-epoll-4.1.78.Final.jar

  offset of local header from start of archive:   21250527
                                                  (00000000014441DFh) bytes
  file system or operating system of origin:      Unix
  version of encoding software:                   0.0
  minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
  minimum software version required to extract:   1.0
  compression method:                             none (stored)
  file security status:                           not encrypted
  extended local header:                          no
  file last modified on (DOS date/time):          2010 Jan 1 00:00:00
  32-bit CRC value (hex):                         ce54b85b
  compressed size:                                5594 bytes
  uncompressed size:                              5594 bytes
  length of filename:                             49 characters
  length of extra field:                          0 bytes
  length of file comment:                         0 characters
  disk number on which file begins:               disk 1
  apparent file type:                             binary
  Unix file attributes (100555 octal):            -r-xr-xr-x
  MS-DOS file attributes (00 hex):                none

  There is no file comment.

bash-3.2$
```

### Operating System

MacOS 12.13.1

### Selenium version

Java 4.3.1

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

N/A

**Comment by asolntsev** [comment] 2022-08-26 15:37
@shs96c  I confirm `selenium-java-4.4.0.zip` contains duplicate files _with exactly the same name_: 

1. `wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.4.0/selenium-java-4.4.0.zip`
2. `jar -tf selenium-java-4.4.0.zip | grep netty-transport-native-epoll`

> lib/netty-transport-native-epoll-4.1.78.Final.jar
> lib/netty-transport-native-epoll-4.1.78.Final.jar

**Comment by diemol** [comment] 2022-11-13 21:42
Closing in favor of #11259

**Closed as completed by diemol** 2022-11-13 21:42 UTC
Labels: C-java, I-defect

**Comment by asolntsev** [comment] 2022-11-14 20:55
@diemol It's not important, of course, but I am just curious. :) 
What's the logic here: why the older issue is closed in favor of a newer one (which is exactly the same)?
I would rather close the new issue marking it as duplicate.

**Comment by diemol** [comment] 2022-11-15 09:01
Because we do not triage or backport fixes, so if the issue is still present in a more recent version, that is already a way of knowing that it is still valid.
