### ISSUE TITLE
[🐛 Bug]: PyPI: selenium 4.17.0 whl is not defining strong version requirement to typing-extensions

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#13488] opened 2024-01-23 09:07 UTC
### What happened?
https://pypi.org/project/selenium/#history

After release of selenium 4.17.0 our builds started failing due to the conflict between versions of selenium and typing extensions. Starting from 4.17.0 selenium requires typing-extensions in version 4.9.0.

Using selenium 4.17.0 with older typing-extensions (matched by PIP) ends with build errors. Enforcing selenium==4.16.0 fixes the issue.
Selenium wheel package should define strong requirement on typing-extensions version in metadata.

### How can we reproduce the issue?

```shell
Build a project using the newest version selenium and old version of typing_extensions (for example, typing-extensions-3.10.0.2).
```

### Relevant log output

```shell
[2024-01-23T06:55:46.907Z] Traceback (most recent call last):
[2024-01-23T06:55:46.907Z]   File "/apps/superset/virtualenv/bin/superset", line 5, in <module>
[2024-01-23T06:55:46.907Z]     from superset.cli.main import superset
[2024-01-23T06:55:46.907Z]   File "/apps/superset/virtualenv/lib/python3.8/site-packages/superset/__init__.py", line 21, in <module>
[2024-01-23T06:55:46.907Z]     from superset.app import create_app
[2024-01-23T06:55:46.907Z]   File "/apps/superset/virtualenv/lib/python3.8/site-packages/superset/app.py", line 23, in <module>
[2024-01-23T06:55:46.907Z]     from superset.initialization import SupersetAppInitializer
[2024-01-23T06:55:46.907Z]   File "/apps/superset/virtualenv/lib/python3.8/site-packages/superset/initialization/__init__.py", line 33, in <module>
[2024-01-23T06:55:46.907Z]     from superset.extensions import (
[2024-01-23T06:55:46.907Z]   File "/apps/superset/virtualenv/lib/python3.8/site-packages/superset/extensions/__init__.py", line 35, in <module>
[2024-01-23T06:55:46.907Z]     from superset.utils.machine_auth import MachineAuthProviderFactory
[2024-01-23T06:55:46.907Z]   File "/apps/superset/virtualenv/lib/python3.8/site-packages/superset/utils/machine_auth.py", line 24, in <module>
[2024-01-23T06:55:46.907Z]     from selenium.webdriver.remote.webdriver import WebDriver
[2024-01-23T06:55:46.907Z]   File "/apps/superset/virtualenv/lib/python3.8/site-packages/selenium/webdriver/__init__.py", line 29, in <module>
[2024-01-23T06:55:46.907Z]     from .firefox.firefox_profile import FirefoxProfile  # noqa
[2024-01-23T06:55:46.907Z]   File "/apps/superset/virtualenv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 31, in <module>
[2024-01-23T06:55:46.907Z]     from typing_extensions import deprecated
[2024-01-23T06:55:46.907Z] ImportError: cannot import name 'deprecated' from 'typing_extensions' (/apps/superset/virtualenv/lib/python3.8/site-packages/typing_extensions.py)
```

### Operating System

Linux

### Selenium version

Python 4.17.0

### What are the browser(s) and version(s) where you see this issue?

Firefox

### What are the browser driver(s) and version(s) where you see this issue?

Any

**Comment by diemol** [comment] 2024-01-23 09:10
Duplicate of #13486

**Closed as not planned by diemol** 2024-01-23 09:10 UTC
Labels: I-defect, A-needs-triaging

**Comment by ghost** [comment] 2024-01-23 09:17
@diemol  Do you plan to release a revised version of wheel file on PyPI in the near future?

**Comment by diemol** [comment] 2024-01-23 09:19
After the PR that fixes the issue is merged, I will do a release.
