### ISSUE TITLE
[🐛 Bug]: EventFiringDecorator - Application doesn't fail upon NoSuchElementException / TimeoutException

### ISSUE THREAD

**Issue by leRobbe** [SeleniumHQ/selenium#9966] opened 2021-10-21 09:30 UTC
### What happened?

Hello,

We are upgrading the rougly 10 years old Selenium tests in an existing project. Since we noticed that Selenium4 was released last week we wanted to give it a try, since the version we initially started upgrading with (3.141.59) has been around for quite a while already.

With version 3.141.59 we had an _EventFiringWebDriver_ and a _Listener_ with a custom method with a _FluentWait_ that waits for JQuery etc to be finished, as well as for the element in question to be present (the application is a dinosaur and can be a tad bit slow at times, which would make tests fail every time when simply using _.findElement(By. ...)_ without the wait(s).
With aforementioned version this worked great, however, with Selenium4 the EventFiringWebDriver is marked as deprecated and usage of _EventFiringDecorator_ is recommended.

So we wrote a new Listener since the API seems to have changed entirely (methods & parameters) and employed the EventFiringDecorator as instructed.

The tests seem to work at first glance, BUT:
Tests don't fail anymore upon _NoSuchElementException_ or _TimoutException_ thrown by the FluentWait in the implemented listener - we can see stacktraces of elements that caused these errors to be thrown, but the application progresses until at some point an element is not clickable, which does ultimately cause the test to fail. (On a side note, tests failing at the respective points in the application is "intentional" since we are still in progress of upgrading - the old selenium just continued when an element wasn't found).
Test code itself hasn't changed when we went from 3.141.59 to 4.0.0, only the usage of EventFiringDecorator and new implementation of the listener as mentioned above were altered.

**Stacktraces look like the following:**
```
Okt 21, 2021 10:39:03 AM org.openqa.selenium.support.events.EventFiringDecorator callListenerMethod
WARNING: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.openqa.selenium.support.events.EventFiringDecorator.callListenerMethod(EventFiringDecorator.java:311)
	at org.openqa.selenium.support.events.EventFiringDecorator.fireBeforeEvents(EventFiringDecorator.java:231)
	at org.openqa.selenium.support.events.EventFiringDecorator.lambda$beforeCall$0(EventFiringDecorator.java:170)
	at org.openqa.selenium.support.events.EventFiringDecorator$$Lambda$305.000000001203FC80.accept(Unknown Source)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:4224)
	at org.openqa.selenium.support.events.EventFiringDecorator.beforeCall(EventFiringDecorator.java:170)
	at org.openqa.selenium.support.decorators.DefaultDecorated.beforeCall(DefaultDecorated.java:43)
	at org.openqa.selenium.support.decorators.WebDriverDecorator.lambda$createProxy$0(WebDriverDecorator.java:293)
	at org.openqa.selenium.support.decorators.WebDriverDecorator$$Lambda$304.000000001203D690.invoke(Unknown Source)
	at com.sun.proxy.$Proxy15.findElement(Unknown Source)
	...
Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for de.base.DriverEventListener$$Lambda$318/0000000012A415D0@77ab27fb (tried for 4 second(s) with 1000 milliseconds interval)
	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:263)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
	at de.base.DriverEventListener.waitForElement(DriverEventListener.java:58)
	at de.base.DriverEventListener.beforeFindElement(DriverEventListener.java:142)
	... 28 more
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: (//.[somexpath])[1]
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'removed', ip: 'removed', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [d1d54a7b-1543-4bcb-8c40-e10686f91d91, findElement {using=xpath, value=(//.somexpath)[1]}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 92.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20210922161155, moz:debuggerAddress: localhost:57008, moz:geckodriverVersion: 0.30.0, moz:headless: false, moz:processID: 7128, moz:profile: D:\Users\removed\..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 6.3, proxy: Proxy(), se:cdp: ws://localhost:57008/devtoo..., se:cdpVersion: 85, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: d1d54a7b-1543-4bcb-8c40-e10686f91d91
	at sun.reflect.GeneratedConstructorAccessor25.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:437)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:139)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:383)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:375)
	at de.base.DriverEventListener.lambda$1(DriverEventListener.java:59)
	at de.base.DriverEventListener$$Lambda$318.0000000012A415D0.apply(Unknown Source)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	... 30 more
```

**The code snippet for the wait method in the listener:**
```
private void waitForElement(WebDriver driver, By selector) {

        Wait<WebDriver> wait = new FluentWait<>(driver).withTimeout(Duration.ofSeconds(4))
            .pollingEvery(Duration.ofSeconds(1)).ignoring(NoSuchElementException.class);

        JSWaiter.waitForJS();

        if (selector != null) {
            wait.until(ExpectedConditions.presenceOfElementLocated(selector));
            wait.until(driver1 -> {
                WebElement element = driver1.findElement(selector);
                return (element != null && element.isEnabled() ? element : null);
            });
        }
    }
```

**Using wait method in listener:**
```
@Override
    public void beforeFindElement(WebDriver driver, By locator) {
        waitForElement(driver, locator);
    }
```

**Initializing the driver:**
```
FirefoxDriver temp = new FirefoxDriver();
WebDriver browser = new EventFiringDecorator(new DriverEventListener()).decorate(temp);
```

Since Selenium4 is so new I couldn't find any solutions to this issue, so I figured I'd open one here.

My question is, what changed that we might be missing that causes tests to not fail at mentioned exceptions anymore?
(Also, the _WARNING: null_ in the stacktrace provided above looks weird to me)

### What browsers and operating systems are you seeing the problem on?

Browser: Firefox
Gedockeriver version 0.30.0
OS: Win8.1

**Comment by diemol** [comment] 2021-12-09 21:05
@leRobbe, thanks for the details. Since this issue was transferred from another repo, it does not have all the information we need to troubleshoot this. Can you please add a complete code snippet (if more than one file, please provide a GitHub repo with instructions) way to reproduce it and what versions of the different components you are using.

**Comment by diemol** [comment] 2021-12-09 21:08
Ok, seems this issue is a duplicate of #9974

**Closed as completed by diemol** 2021-12-09 21:08 UTC
Labels: J-awaiting answer, C-java
