### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 244: ordinal not in range(128)

### ISSUE THREAD

**Issue by drobota** [SeleniumHQ/selenium#1776] opened 2016-03-09 23:17 UTC
## Expected Behavior -
No errors

## Actual Behavior -
I am running lots of tests and these problem appears only in firefox 

## Steps to reproduce -
`UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 244: ordinal not in range(128)`  error appears only If I try to save screenshot when wait or kill script alert is present 

## Binding 
python 2.7
selenium 2.52, 2.51, 2.47 

## Stack trace 
```
<ipython-input-5-b75a09801eb1> in <module>()
----> 1 ff.save_screenshot("1.png")

/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.pyc in get_screenshot_as_file(self, filename)
    756             driver.get_screenshot_as_file('/Screenshots/foo.png')
    757         """
--> 758         png = self.get_screenshot_as_png()
    759         try:
    760             with open(filename, 'wb') as f:

/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.pyc in get_screenshot_as_png(self)
    775             driver.get_screenshot_as_png()
    776         """
--> 777         return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
    778 
    779     def get_screenshot_as_base64(self):

/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.pyc in get_screenshot_as_base64(self)
    785             driver.get_screenshot_as_base64()
    786         """
--> 787         return self.execute(Command.SCREENSHOT)['value']
    788 
    789     def set_window_size(self, width, height, windowHandle='current'):

/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.pyc in execute(self, driver_command, params)
    199         response = self.command_executor.execute(driver_command, params)
    200         if response:
--> 201             self.error_handler.check_response(response)
    202             response['value'] = self._unwrap_value(
    203                 response.get('value', None))

/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.pyc in check_response(self, response)
    178             raise exception_class(response, message)
    179         elif exception_class == UnexpectedAlertPresentException and 'alert' in value:
--> 180             raise exception_class(message, screen, stacktrace, value['alert'].get('text'))
    181         raise exception_class(message, screen, stacktrace)
    182 

<type 'str'>: (<type 'exceptions.UnicodeEncodeError'>, UnicodeEncodeError('ascii', u"Alert Text: A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.\n\nScript: http://*.js:34615\n<super: <class 'WebDriverException'>, <UnexpectedAlertPresentException object>>", 211, 212, 'ordinal not in range(128)'))

```

**Comment by lukeis** [comment] 2016-03-10 03:59
This is expected behavior (except for your exact stacktrace, not sure how you get the UnicodeEncodeError in there, more of the code to reproduce it would be helpful. Otherwise here's how it looks normally:

    >>> d = webdriver.Firefox()
    >>> d.execute_script("alert('hi')")
    u'hi'
    >>> d.save_screenshot("test.png")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 758, in get_screenshot_as_file
        png = self.get_screenshot_as_png()
      File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 777, in get_screenshot_as_png
        return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
      File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 787, in get_screenshot_as_base64
        return self.execute(Command.SCREENSHOT)['value']
      File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
        self.error_handler.check_response(response)
      File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
        raise exception_class(message, screen, stacktrace)
    selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: None
    <super: <class 'WebDriverException'>, <UnexpectedAlertPresentException object>>


If there is an alert dialog present you will receive this exception. Note that in your example it shows that the alert dialog was a browser based Runaway Javascript timer, which I would consider a serious bug in the application you're testing.

Since this is expected behavior i'm going to close the issue. If you can provide a script to reproduce the unicode issue you've seen (instead of the UnexpectedAlertPresentException exception getting raised appropriately) we can reopen the issue.

**Closed by lukeis** 2016-03-10 03:59 UTC

**Comment by drobota** [comment] 2016-03-10 05:34
@lukeis In your case everything works as expected however in case if there is an [Alert like this](https://app.roll20.net/forum/post/2310357/unresponsive-script-freezing-firefox/?pageforid=2431778#post-2431778) you will get `UnexpectedAlertPresentException`  
Link on symbol [Unicode Character 'HORIZONTAL ELLIPSIS' (U+2026)](http://www.fileformat.info/info/unicode/char/2026/index.htm)
f.e 
```
In [28]: u"…".encode("ascii")
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-28-cc4604e575a5> in <module>()
----> 1 u"…".encode("ascii")

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 0: ordinal not in range(128)
```
This symbol appears if you have very long script f.e in my case it looks like(I replaced some pieces  with `*` )
```
Alert Text: A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: http://*:8001/cachedjs/…y-build.*-*/*.js:28096
```
I would suggest to add in selenium/webdriver/remote/webdriver.py:777
`return base64.b64decode(self.get_screenshot_as_base64().encode('ascii', ignore'))`
```
In [30]: u"…".encode("ascii", "ignore")
Out[30]: ''
```
I can make a pr for that.

Thanks

**Comment by lukeis** [comment] 2016-03-10 06:00
I'm still unsure how you're script is getting there. The UnhandledAlertException should be raised in the get_screenshot_as_base64 call, then 'encode' method should not be executing at all.

**Comment by drobota** [comment] 2016-03-10 06:24
I agree it should be fixed here 
```
raise exception_class(message, screen, stacktrace, value['alert'].get('text').encode("ascii", "ignore"))
```

**Comment by lukeis** [comment] 2016-03-10 18:07
@drobota seems like a bug in that library then, log an issue there?

https://github.com/robotframework/Selenium2Library

**Comment by lukeis** [comment] 2016-03-10 18:45
@drobota where is that encoding happening? because in the exception creation the call to .get('text') doesn't perform that. I can only assume it's something in the Selenium2Library doing it at that point

**Comment by drobota** [comment] 2016-03-10 18:49
@lukeis In my first comment there is a stack trace where I reproduced issue from iptyhon using only selenium with out any other libs

**Comment by drobota** [comment] 2016-03-10 18:50
```
In [2]: raise AssertionError(u"…")
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-2-bef07d1237eb> in <module>()
----> 1 raise AssertionError(u"…")

<type 'str'>: (<type 'exceptions.UnicodeEncodeError'>, UnicodeEncodeError('ascii', u'\u2026', 0, 1, 'ordinal not in range(128)'))
```

**Comment by lukeis** [comment] 2016-03-10 19:11
i haven't been able to reproduce your stacktraces exactly... but I found that if you have the UnexpectedAlertException object and call  str(exception). This causes a unicode error.... but calling  excetion.__str__()  does not produce the error. I haven't been able to figure out why, seems something odd in python 2.

Can you make sure your code calls __str__ on the error, rather than str() of it?

**Comment by Dude-X** [comment] 2016-03-10 22:42
@drobota I have found the issue that is causing the error. I will put in a fix this evening. The issue is not with the code to save a screenshot but the Exception class for unhandled alerts.

**Comment by Handsome2734** [comment] 2016-03-11 01:44
When using python2.7, never use str() to convert a unicode to string. It
sucks!

> On Mar 11 2016, at 6:42 am, Isaul Vargas &lt;notifications@github.com&gt;
wrote:  

>

> [@drobota](https://github.com/drobota) I have found the issue that is
causing the error. I will put in a fix this evening. The issue is not with the
code to save a screenshot but the Exception class for unhandled alerts.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/Seleniu
mHQ/selenium/issues/1776#issuecomment-195083535).![](https://github.com/notifi
cations/beacon/AFT1UUjOEGtoFcfxeamb0D3fV6ftMT3wks5psJ5LgaJpZM4HtQZO.gif)

**Comment by Dude-X** [comment] 2016-03-11 21:47
@drobota The UnicodeDecodeError is kind of a bug in Exceptions in Python 2. Only going to fix a minor issue in the code, but otherwise this is a won't fix since to fully fix it would mean having to put a lot of effort to disambiguate python 2 byte strings  and python 3 unicode strings.
