### ISSUE TITLE
Element.Displayed return "the path is not of a legal form"

### ISSUE THREAD

**Issue by kbourro** [SeleniumHQ/selenium#7291] opened 2019-06-14 12:46 UTC
Selecting an element with xpath returns an IWebElement then element.Displayed returns an error "the path is not of a legal form". Exist and Enabled works correctly.

**Comment by jimevans** [comment] 2019-06-14 14:11
This is not globally broken for all users and all sites for all XPath values. You'll need to provide more information to have a chance of tracking down what the issue is. Please provide a full example, complete with an HTML page (or URL to a public site) that can reproduce the issue.

**Comment by barancev** [comment] 2019-07-15 19:40
Closing the issue as there is no reproduction scenario provided.

**Closed by barancev** 2019-07-15 19:40 UTC
Labels: R-awaiting answer
