### ISSUE TITLE
keepAlive Failure Exception in middle of iOS test run after installation of  webdriver 3.4.0

### ISSUE THREAD

**Issue by Elangopalakrishnan** [SeleniumHQ/selenium#4168] opened 2017-06-13 03:13 UTC
Hi ,

I'm automating the iOS devices using appium 1.6.6 beta with selenium webdriver 3.4.0 in c#.
I'm getting the keepAlive failure exception whenever i launch the browser.

**Environmet**
OS:  Windows, 
Selenium Version:  EI Capitan 10.11.6
Browser:  iOS Device Safari Browser
After updating the Selenium webdriver 3.4.0, i cannot launch the browser in my iOS devices,

I'm sure, I'm getting this type of exception after installation of webdriver 3.4.0, i tested it revert back previous version,

is there any changes on hub connections code in new webdriver ??

**My exception :**
**"A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://17.18.45.21:4723/wd/hub/session/3c75a67b-5965-4935-9c96-535e86d10cab/element. The status of the exception was KeepAliveFailure, and the message was: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server."**

I have filed issue in appium/issues also,
Please refer issue #https://github.com/appium/appium/issues/8643
-->

 Expected Behavior - Have to Launch safari browser in iOS device

 Actual Behavior - Throwing keepAlive failure exception.

Thanks!
Elango

**Comment by diemol** [comment] 2020-04-07 16:08
Sadly no logs or a way to reproduce the issue have been provided, either here or in the Appium issue. 
I will close this for now, but if the issue is still present, please feel free to open a new one with all the template fields filled out.

**Closed by diemol** 2020-04-07 16:08 UTC
Labels: C-grid
