### ISSUE TITLE
Issue invoking edge browser 17763 using selenium server 3.5 and above

### ISSUE THREAD

**Issue by srinidhi158** [SeleniumHQ/selenium#7589] opened 2019-09-22 17:07 UTC
Unfortunately i have issue mentioned in ticket https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/21072833/ but i cant quiet reopen ticket.
So i thought ill open new one as the resolution didn’t work for me.

I have win10 and edge browser version 17763. My automation framework used custom location for MicrosoftWebdriver.exe and so i copied the same from it’s location C:\Windows\SysWOW64 .

I tried different selenium server versions from 3.5.3 , 3.11, 3.14 and so on All of which say same error as below. The error slightly varies with 3.14.

With 3.5.3 and 3.11 , 3.12 error is:
2019-09-18 10:14:21.220:INFO:osjshC.ROOT:qtp1101288798-12: org.openqa.selenium.remote.server.WebDriverServlet-26be92ad: Initialising WebDriverServlet
10:14:21.267 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.Status@7dff184
10:14:21.283 INFO - /status: Executing GET on /status (handler: Status)
10:14:21.361 INFO - Binding default provider to: org.openqa.selenium.chrome.ChromeDriverService
10:14:21.361 INFO - Found handler: org.openqa.selenium.remote.server.BeginSession@56c1172
10:14:21.361 INFO - /session: Executing POST on /session (handler: BeginSession)
10:14:21.392 INFO - Capabilities are: Capabilities {proxy={}, acceptSslCerts=true, browserName=MicrosoftEdge, javascriptEnabled=true, platformName=ANY, version=, platform=ANY, }
10:14:21.392 INFO - Capabilities {proxy={}, acceptSslCerts=true, browserName=MicrosoftEdge, javascriptEnabled=true, platformName=ANY, version=, platform=ANY, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.edge.EdgeDriverService)
10:14:21.392 INFO - Capabilities {proxy={}, acceptSslCerts=true, browserName=MicrosoftEdge, javascriptEnabled=true, platformName=ANY, version=, platform=ANY, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
[10:14:21.502] - Listening on http://127.0.0.1:12978/
[10:14:21.502] - Listening on http://[::1]:12978/
[10:14:22.470] - Invalid capabilities

With 3.14:
10:27:59.783 INFO [ActiveSessionFactory.apply] - Capabilities are: {
"acceptSslCerts": true,
"browserName": "MicrosoftEdge",
"javascriptEnabled": true,
"proxy": {
},
"version": “”
}
10:29:31.397 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.edge.EdgeDriverService)
[10:29:31.507] - Listening on http://127.0.0.1:3986/
[10:29:31.507] - Listening on http://[::1]:3986/
[10:29:32.382] - Invalid capabilities
10:29:32.397 INFO [ServicedSession$Factory.apply] - The specified arguments passed to the command are invalid.
Build info: version: '3.141.59’, revision: 'e82be7d358’, time: ‘2018-11-14T08:25:53’
System info: host: 'DESKTOP-I4FJPQS’, ip: '10.96.199.60’, os.name: 'Windows 10’, os.arch: 'amd64’, os.version: '10.0’, java.version: ‘1.8.0_161’
Driver info: driver.version: unknown
remote stacktrace:
org.openqa.selenium.InvalidArgumentException: The specified arguments passed to the command are invalid.
Build info: version: '3.141.59’, revision: 'e82be7d358’, time: '2018-11-14T08:25:5

Also in the end it says:
The following JSON wire protocol command endpoint is not allowed when server is running in W3C mode.

**Comment by srinidhi158** [comment] 2019-10-01 10:13
Guys, any  update?

**Comment by srinidhi158** [comment] 2019-10-03 05:55
Hi anyone help me

**Comment by srinidhi158** [comment] 2019-10-03 05:55
i am doing something wrong.

**Comment by germanodulio** [comment] 2019-11-27 19:37
I'm having same issue. 

The test executes correctly but when I call driver.Quit() driver logs A LOT of "The following JSON wire protocol command endpoint is not allowed when server is running in W3C mode 
GET /shutdown". By a lot I mean 15654 times logging that.
This amount of logs only happens in .net driver. With Java only logs once.

I am using Edge 44.18362.449.0 and Selenium.Webdriver 3.11.2
MicrosoftWebDriver version is 10.0.18362.1

**Comment by diemol** [comment] 2020-09-20 17:24
@srinidhi158 The link provided above is not valid anymore. Could you please provide enough information for us to reproduce the issue?

**Comment by diemol** [comment] 2020-11-10 22:40
I close this for now since we did not get more information, however, if the issue is still valid with the most recent versions, please feel free to open a new issue.

**Closed by diemol** 2020-11-10 22:40 UTC
Labels: D-edge, R-awaiting answer
