### ISSUE TITLE
Firefox 47 crashing a few seconds after launch by Selenium 2.53.0 on OSX 10.11.5

### ISSUE THREAD

**Issue by samyun** [SeleniumHQ/selenium#2231] opened 2016-06-07 23:26 UTC
## Meta -
OS:  OSX 10.11.5
Selenium Version:  
2.53.0
Browser:  
Firefox
Browser Version:  
47.0

## Expected Behavior -
Firefox doesn't crash shortly after launch.

## Actual Behavior -
Shortly after webdriver.Firefox() is called, Firefox is launched. Sometimes almost immediately, sometimes after first URL is navigated to, Firefox crashes, and the following problem report comes up:

        Process:               firefox-bin [50402]
        Path:                  /Applications/Firefox.app/Contents/MacOS/firefox-bin
        Identifier:            org.mozilla.firefox
        Version:               47.0 (4716.6.4)
        Code Type:             X86-64 (Native)
        Parent Process:        Python [50397]
        Responsible:           Terminal [25432]
        User ID:               501
        
        Date/Time:             2016-06-07 16:08:22.955 -0700
        OS Version:            Mac OS X 10.11.5 (15F34)
        Report Version:        11
        Anonymous UUID:        FB1ED8A9-3A61-DC92-F91C-55B2A620E6CF
        
        Sleep/Wake UUID:       84C91FD4-D04B-41C6-995F-9BE9447F3B85
        
        Time Awake Since Boot: 23000 seconds
        Time Since Wake:       6500 seconds
        
        System Integrity Protection: enabled
        
        Crashed Thread:        7  Socket Thread
        
        Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
        Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
        
        VM Regions Near 0:
        --> 
            __TEXT                 0000000100000000-0000000100004000 [   16K] r-x/rwx SM=COW  /Applications/Firefox.app/Contents/MacOS/firefox-bin

        Thread 0:: Dispatch queue: com.apple.main-thread
        0   libsystem_kernel.dylib        	0x00007fff8cb84f72 mach_msg_trap + 10
        1   libsystem_kernel.dylib        	0x00007fff8cb843b3 mach_msg + 55
        2   com.apple.CoreFoundation      	0x00007fff817a81c4 __CFRunLoopServiceMachPort + 212
        3   com.apple.CoreFoundation      	0x00007fff817a768c __CFRunLoopRun + 1356
        4   com.apple.CoreFoundation      	0x00007fff817a6ed8 CFRunLoopRunSpecific + 296
        5   com.apple.HIToolbox           	0x00007fff84901935 RunCurrentEventLoopInMode + 235
        6   com.apple.HIToolbox           	0x00007fff8490176f ReceiveNextEventCommon + 432
        7   com.apple.HIToolbox           	0x00007fff849015af         _BlockUntilNextEventMatchingListInModeWithFilter + 71
        8   com.apple.AppKit              	0x00007fff927eddf6 _DPSNextEvent + 1067
        9   com.apple.AppKit              	0x00007fff927ed226 -[NSApplication         _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
        10  XUL                           	0x0000000102eea262 0x1012b6000 + 29573730
        

## Steps to reproduce -
Call Firefox webdriver, crashes shortly after.

**Comment by lukeis** [comment] 2016-06-07 23:31
duplicate of #2110

**Closed by lukeis** 2016-06-07 23:31 UTC
