### ISSUE TITLE
Unable to navigate to url using chrome driver 78.0.3904.11 or 78.0.3904.70

### ISSUE THREAD

**Issue by kiranbhaga** [SeleniumHQ/selenium#7789] opened 2019-11-14 18:23 UTC
I'm unable to navigate and take screenshots. 
Chrome driver: 78.0.3904.11 and 78.0.3904.70
Chrome version: 78.0.3904.97 

ChromeOptions options = new ChromeOptions();
                options.AddArguments("window-size=1920x1080");
                options.AddArguments("headless");
                options.AddArgument("no-sandbox");
                IWebDriver driver = new ChromeDriver(options);

driver.Navigate().GoToUrl("https://www.google.com");

Fails with ErrorType.FailToNavigate. It was working before not sure what's wrong now. Running this on windows 10 and windows server 2019. Fails both places.

Exception details:
invalid argument
  (Session info: chrome=78.0.3904.97)

   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.set_Url(String value)
   at OpenQA.Selenium.Remote.RemoteNavigator.GoToUrl(String url)

**Comment by diemol** [comment] 2019-12-06 21:27
Hi @kiranbhaga,

Could you please add a complete test case to reproduce the issue? There is a lot of information missing, most of the bug template was deleted 😢

**Comment by BilalKamran** [comment] 2019-12-25 15:33
I'm facing the same issue with Chromedriver 79.0.3945.36 for mac and Chrome 79.0.3945.79 for mac, on Mac Sierra. When the driver is loaded, I only see the page with "data;", not the url I used. I am not having this issue with Chromedriver 79.0.3945.36 for Win64 and Chrome 79.0.3945.79 for Win, on Windows 10. No Exception from webdriver.

`String url = "www.google.com";
ChromeOptions options = new ChromeOptions();
options.addArguments("--no-sandbox");
options.addArguments("--disable-gpu");
options.addArguments("start-maximized");
options.setExperimentalOption("excludeSwitches", new String[]{"enable-automation"});
options.addArguments("--homepage \"" + url + "\"");
options.addExtensions(new File(GlobalDataAccess.extensionPath));
options.addArguments("--disable-web-security");
options.addArguments("--allow-running-insecure-content");
driver = new ChromeDriver(options);`

**Comment by diemol** [comment] 2019-12-26 21:50
I just tried a simple script and it is working for me, I will close this since we did not get a self-contained automated to reproduce the issue. If someone is bumping into this potential issue, please feel free to open a new issue with the complete template filled out.

**Closed by diemol** 2019-12-26 21:50 UTC
Labels: R-awaiting answer
