### ISSUE TITLE
[🐛 Bug]:  The browser is automatically closed after the code is executed

### ISSUE THREAD

**Issue by lqyiwwx** [SeleniumHQ/selenium#11325] opened 2022-11-27 01:21 UTC
### What happened?

edge 107.0.1418.56  and above 4.6.0   The browser is automatically closed after the code is executed

### What browsers and operating systems are you seeing the problem on?

edge 107.0.1418.56  and above 4.6.0   The browser is automatically closed after the code is executed

**Comment by titusfortner** [comment] 2022-11-27 15:54
Likely a duplicate of #11303.

**Closed as completed by titusfortner** 2022-11-27 15:54 UTC
Labels: A-needs-triaging
