### ISSUE TITLE
UnhandledPromiseRejectionWarning: NoSuchSessionError: no such session

### ISSUE THREAD

**Issue by betweenbrain** [SeleniumHQ/selenium#7538] opened 2019-09-05 10:12 UTC
## 🐛 Bug Report

Tests written without async and not chained with `.then()`, which work fine with v3.6.0, throw a `UnhandledPromiseRejectionWarning: NoSuchSessionError: no such session` error with 4.0.0-alpha.4

## To Reproduce
Run the following test using selenium-webdriver v3.6.0, then again with v4.0.0-alpha.4.
```
const {Builder, By, Key, until} = require('selenium-webdriver');
const driver = new Builder().forBrowser('chrome').build();

driver.get('http://www.google.com');
driver.findElement(By.name('q')).sendKeys('webdriver', Key.RETURN)
driver.wait(until.elementLocated(By.css('title')), 1000)
driver.getTitle().then(function (title) {
  if (title === 'webdriver - Google Search') {
    console.log('Test passed');
  } else {
    console.log('Test failed');
  }
});
driver.quit();
```
## Expected behavior

I would expect the test to complete successfully. Please note that I could not find any documentation stating that tests written this way would not work with v4.0.0-alpha.4. With v3.6.0, I see _node_modules/selenium-webdriver/example/parallel_flows.js_ demonstrates the above test should work, but I do not see that example included with v4.0.0-alpha.4. 

## Environment

OS: OSX 10.13.6
Browser: Chrome
Browser version: 76.0.3809.132
Selenium Grid version (if applicable): n/a

**Comment by Harsha509** [comment] 2019-09-05 12:27
@betweenbrain, you may need to enclose code in try catch block to avoid that error. nodejs expects to handle the error

**Comment by betweenbrain** [comment] 2019-09-05 14:09
@Harsha509 thanks for the response. Unfortunately, that does not resolve the issue. I get the same error when using try/catch. Any idea why the code works fine with selenium-webdriver v3.6.0 though?

**Comment by pittgoose** [comment] 2019-11-10 09:52
@betweenbrain Pretty sure one of the biggest things in Node JS's v4.x selenium bindings is that it dropped support for the promise manager and that you _must_ use async/await or chain with `.then()`. Presumably, there's no session because the commands are all run asynchronously and the session ends before the promises can be handled.

**Comment by Harsha509** [comment] 2020-02-27 08:35
Hi @betweenbrain,

Here is the code which worked for me with selenium-4-alpha-5

const {Builder, By, Key, until} = require('selenium-webdriver');
const driver = new Builder().forBrowser('chrome').build();

(async function example() {
  await driver.get('http://www.google.com');
  await driver.findElement(By.name('q')).sendKeys('webdriver', Key.RETURN);
  await driver.wait(until.elementLocated(By.css('title')), 1000);
  await driver.getTitle().then(function (title) {
    if (title === 'webdriver - Google Search') {
      console.log('Test passed');
    } else {
      console.log('Test failed');
    }
  });
  await driver.quit();
})();

**Comment by harsha509** [comment] 2020-09-23 17:45
Hi @betweenbrain ,

This is expected behaviour in Selenium 4 JS bindings. As per the conversion in [here](https://github.com/SeleniumHQ/selenium/issues/2969), WebDriver control flow is deprecated/removed.

so you have to use nodejs async/awaits. Here is the code sample of yours tested with selenium 4 looks like

```
const {Builder, By, Key, until} = require('selenium-webdriver');
const driver = new Builder().forBrowser('chrome').build();

(async function example() {
  try {
    await driver.get('http://www.google.com');
    await driver.findElement(By.name('q')).sendKeys('webdriver', Key.RETURN);
    await driver.wait(until.elementLocated(By.css('title')), 1000)
    let title = await driver.getTitle();
    if (title === 'webdriver - Google Search') {
      console.log('Test passed');
    } else {
      console.log('Test failed');
    }
    await driver.quit();
  }
  catch (e) {
    console.log(e);
  }
})();
```

Hence closing the issue, as this is expected behaviour.

Thank you !

**Closed by harsha509** 2020-09-23 17:45 UTC
Labels: C-nodejs
