### ISSUE TITLE
[🐛 Bug]: Unable to upload file to a Mac Safari node when using selenium Grid.

### ISSUE THREAD

**Issue by vvbisht** [SeleniumHQ/selenium#14620] opened 2024-10-18 13:41 UTC
### What happened?

Selenium version : 4.24.0
Java : 11
Platform : MAC Sonoma 14.0
Browser : Safari v 17

I have setup a Selenium Grid with a MAC hub and multiple mac nodes. When i am trying to perform a file upload operation through grid it's failing and throwing following exception. 
**org.openqa.selenium.InvalidArgumentException: An invalid command argument was specified: One or more files could not be selected.**

Please note that on running the test without grid this seems to be working fine. I have tried changing the path with "/" and "\\" but nothing seems to be working.

### How can we reproduce the issue?

```shell
String hub = "http://*.*.*.*:4444/wd/hub";
            SafariOptions options = new SafariOptions();
            options.setCapability("browserName", "safari");
            options.setCapability("platformName", "mac");
            WebDriver driver = null;
            //driver = new RemoteWebDriver(new URL(hub), options);
            RemoteWebDriver driver = new RemoteWebDriver(new URL(hub), options);
            driver.setFileDetector(new LocalFileDetector());
        String filePath = "C:/sample.txt";
        driver.get("https://the-internet.herokuapp.com/upload");
        WebElement element = driver1.findElement(By.id("file-upload"));
        element.sendKeys(filePath);
```
```


### Relevant log output

```shell
org.openqa.selenium.InvalidArgumentException: An invalid command argument was specified: One or more files could not be selected.
Build info: version: '4.24.0', revision: '748ffc9bc3'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.23'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [BB0D158E-6371-4143-A373-9A3E5296337F, sendKeysToElement {value=[Ljava.lang.CharSequence;@2bd08376, id=node-D15E858C-69C7-4467-8D03-373A0981CD24}]
Capabilities {acceptInsecureCerts: false, browserName: Safari, browserVersion: 17.0, platformName: mac, safari:automaticInspection: false, safari:automaticProfiling: false, safari:diagnose: false, safari:platformBuildVersion: 23A344, safari:platformVersion: 14.0, safari:useSimulator: false, se:bidiEnabled: false, se:cdpEnabled: false, setWindowRect: true, strictFileInteractability: false, webkit:WebRTC: {DisableICECandidateFiltering: false, DisableInsecureMediaCapture: false}}
Element: [[RemoteWebDriver: Safari on mac (BB0D158E-6371-4143-A373-9A3E5296337F)] -> id: file-upload]
Session ID: BB0D158E-6371-4143-A373-9A3E5296337F
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:53)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:110)
```

### Operating System

macOS

### Selenium version

4.24.0

### What are the browser(s) and version(s) where you see this issue?

Safari

### What are the browser driver(s) and version(s) where you see this issue?

Safari 17

### Are you using Selenium Grid?

4.24.0

**Comment by pujagani** [comment] 2024-11-06 05:00
I tried to reproduce it locally but I was not able to. My local OS is MacOS and I created a Hub and 2 Nodes. The code shared worked as expected with a minor tweak to point to the correct driver variable. 
This is the code snippet:
```
  public class SafariGridFileUpload {
  public static void main(String[] args) throws MalformedURLException {
    String hub = "http://localhost:4444";
    SafariOptions options = new SafariOptions();
    RemoteWebDriver driver = new RemoteWebDriver(new URL(hub), options, false);
    driver.setFileDetector(new LocalFileDetector());
    String filePath = "/Users/puja/Downloads/profile_photo.jpeg";
    driver.get("https://the-internet.herokuapp.com/upload");
    WebElement element = driver.findElement(By.id("file-upload"));
    element.sendKeys(filePath);
  }
}
```

From the logs shared, I observe that the OS is Windows `System info: os.name: 'Windows 11'`.  Also, the path passed is Windows file system path. For a MAC Hub, it needs to be MAC based path. Please share your setup of the Grid so we can understand this better.

**Comment by pujagani** [comment] 2024-11-06 05:48
If you are using a virtual machine, then you might need to add files to the virtual machine and accordingly set the path and upload it.

**Comment by vvbisht** [comment] 2024-11-06 07:00
> I tried to reproduce it locally but I was not able to. My local OS is MacOS and I created a Hub and 2 Nodes. The code shared worked as expected with a minor tweak to point to the correct driver variable. This is the code snippet:
> 
> ```
>   public class SafariGridFileUpload {
>   public static void main(String[] args) throws MalformedURLException {
>     String hub = "http://localhost:4444";
>     SafariOptions options = new SafariOptions();
>     RemoteWebDriver driver = new RemoteWebDriver(new URL(hub), options, false);
>     driver.setFileDetector(new LocalFileDetector());
>     String filePath = "/Users/puja/Downloads/profile_photo.jpeg";
>     driver.get("https://the-internet.herokuapp.com/upload");
>     WebElement element = driver.findElement(By.id("file-upload"));
>     element.sendKeys(filePath);
>   }
> }
> ```
> 
> From the logs shared, I observe that the OS is Windows `System info: os.name: 'Windows 11'`. Also, the path passed is Windows file system path. For a MAC Hub, it needs to be MAC based path. Please share your setup of the Grid so we can understand this better.

Here's how we can configured our setup.

1. There's a windows VM which will execute the tests which are triggered using a Jenkins job.
2. There are separate hub/nodes created for Linux, Windows and MAC.
3. Windows VM sends the command to respective hub which is then propagated to nodes.

In Windows and Linux setup same code works just fine, but only in MAC it's failing. 
The code that i have shared is just an eg. in our framework we are using "user.dir" property to fetch the path of the file.

**Comment by vvbisht** [comment] 2024-11-06 07:01
> If you are using a virtual machine, then you might need to add files to the virtual machine and accordingly set the path and upload it.

Will it not work with LocalFileDetector, is it required to place the files in all the nodes? It works well in Windows and Linux.

**Comment by pujagani** [comment] 2024-11-06 10:52
Thank you for sharing the details! I understand this better. However, I cannot reproduce the same setup locally, considering there are so many pieces and I don't have access to a Windows machine. As far as I understand, the issue is the path for MacOS in the shared code. A MAC Grid does not understand the path pass since it is not a MAC OS path. So you will need to fix that bit to solve the problem. The LocalFileDetector tries to detect the file on the local disk.
I am closing the issue since this is not a Selenium problem. But feel free to discuss this further and get help from the community in our Slack channel.

**Closed as completed by pujagani** 2024-11-06 10:52 UTC
Labels: B-grid, I-defect, J-issue-template, I-question, A-needs-triaging, G-safaridriver

**Comment by vvbisht** [comment] 2024-11-06 16:43
Yeah that i understood it's not able to recognize the path, but how is it possible it works fine in Linux system(given path is similar to what we have in Mac) but fails in Mac.

**Comment by pujagani** [comment] 2024-11-07 06:13
I understand your concern. Can you try running a simple Java code on MAC OS that reads the file from your Windows VM? Selenium code is simply trying to do that https://github.com/SeleniumHQ/selenium/blob/3589d3f500862471b2fcd9f26fe3740920941181/java/src/org/openqa/selenium/remote/LocalFileDetector.java#L42. Please try to understand it is difficult for me to say why it works and why it fails for your setup.

**Comment by pujagani** [comment] 2024-11-07 06:34
I understand your concern. You have a valid point.I am trying to think if it is not the path then what could it be, it could be a SafariDriver issue. Can you try the same code but with Chrome/Firefox on Mac? It will help narrow down the issue. Since, the error message when I give a wrong path is different than what is reported in the issue. So good chances path is fine but SafariDriver is not supporting it.

**Comment by pujagani** [comment] 2024-11-07 06:37
Stacktrace if I pass the same path in the code example of the issue (that is a wrong path for my system)

```
Exception in thread "main" org.openqa.selenium.InvalidArgumentException: An invalid command argument was specified: The file 'C:/sample.txt -- file:///' does not exist or could not be read.
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.5', java.version: '17.0.12'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [20D7B854-3F79-4B9E-A353-5E2910900D88, sendKeysToElement {id=node-19304210-52D1-4794-A44F-0A83044C3B2A, value=[Ljava.lang.CharSequence;@117e949d}]
Capabilities {acceptInsecureCerts: false, browserName: Safari, browserVersion: 17.5, platformName: mac, safari:automaticInspection: false, safari:automaticProfiling: false, safari:diagnose: false, safari:platformBuildVersion: 23F79, safari:platformVersion: 14.5, safari:useSimulator: false, se:bidiEnabled: false, se:cdpEnabled: false, setWindowRect: true, strictFileInteractability: false, webkit:WebRTC: {DisableICECandidateFiltering: false, DisableInsecureMediaCapture: false}}
Element: [[RemoteWebDriver: Safari on mac (20D7B854-3F79-4B9E-A353-5E2910900D88)] -> id: file-upload]
Session ID: 20D7B854-3F79-4B9E-A353-5E2910900D88
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:110)
	at com.company.safari.SafariGridFileUpload.main(SafariGridFileUpload.java:21)
```

**Comment by vvbisht** [comment] 2024-11-07 07:21
> I understand your concern. You have a valid point.I am trying to think if it is not the path then what could it be, it could be a SafariDriver issue. Can you try the same code but with Chrome/Firefox on Mac? It will help narrow down the issue. Since, the error message when I give a wrong path is different than what is reported in the issue. So good chances path is fine but SafariDriver is not supporting it.

Looks like this issue is specific to Safari browser, I tried the same code on Chrome in MAC and it's working as expected, able to upload files without making any changes in the path of file.

**Comment by pujagani** [comment] 2024-11-07 07:32
Thank you for the quick response. Can you try updating it to the latest version and see if that helps? I am trying to find out the version which supports sendKeys.

**Comment by pujagani** [comment] 2024-11-07 07:32
Glad we were able to narrow the root cause.

**Comment by vvbisht** [comment] 2024-11-07 07:40
> it to the latest version and see if that helps?

I am already on latest Safari version i.e. 18, tried on v17 as well, no luck.

**Comment by pujagani** [comment] 2024-11-07 07:43
Ahh okay. Because it works for me on v17.5 so latest versions should support it. Not sure if some permissions need to be set to allow access to files via automation.

**Comment by vvbisht** [comment] 2024-11-07 07:54
> Ahh okay. Because it works for me on v17.5 so latest versions should support it. Not sure if some permissions need to be set to allow access to files via automation.

So if i try with executing my code on Mac(with a hub and a node) it works fine, the problem is when code is executing on Windows and commands are propagated to Mac hub there it's failing.
As per the documentation LocalFileDetector should take care of this flow as mentioned in https://www.selenium.dev/documentation/webdriver/drivers/remote_webdriver/

**Comment by pujagani** [comment] 2024-11-07 08:10
Thank you for verifying it works on Mac. RemoteWebDriver is browser-agnostic. Since it works for Chrome/Firefox, that proves that it is doing the right thing and it is not a Selenium bug. It fails at the point where the command goes to SafariDriver and it does not support it. It could be a case of Windows Mac flow and something in SafariDriver that does not work in that case. I would suggest asking in the SafariDriver forums.

**Comment by pujagani** [comment] 2024-11-07 09:46
One thing you can do is compare what is being sent when running on Mac and when running on Windows Mac flow. Debugging or stepping through (https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/remote/RemoteWebElement.java#L90)  to compare might help. Just a suggestion that popped into my head. Good luck!
