### ISSUE TITLE
Chromedriver 2.36 + Chrome 65 + Web driver 3.10.0 --disable-infobar stopped working 

### ISSUE THREAD

**Issue by vvmmvv** [SeleniumHQ/selenium#5573] opened 2018-03-07 09:13 UTC
## Meta -
OS:  
Windows 10
Selenium Version:  
2.36
Browser:  
Chrome 65 

## Expected Behavior -
Info bar with the following :" Chrome is being controlled by automated machine" should not appear ! 
## Actual Behavior -
Info bar appear! 

## Steps to reproduce -
Chromedriver 2.36 + Chrome 65 + Web driver 3.10.0

**Comment by ricardoperovano** [comment] 2018-03-07 11:36
@vvmmvv this flag was removed. See https://chromium.googlesource.com/chromium/src/+/d869ab3350d8ebd95222b4a47adf87ce3d3214b1

**Comment by barancev** [comment] 2018-03-07 13:06
Duplicate of #5572

Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list

**Closed by barancev** 2018-03-07 13:06 UTC

**Comment by soulgalore** [comment] 2018-03-07 13:29
@vvmmvv you can try to remove the --enable-automation switch from Chromedriver. Something like:
` chromeOptions.excludeSwitches('enable-automation');`

**Comment by vvmmvv** [comment] 2018-03-08 06:44
I added (c#)
opt.AddExcludedArgument("enable-automation")

Worked.
Thank you

**Comment by vvmmvv** [comment] 2018-03-08 07:01
It worked but now the Developer pop up appears although I have in code:

options.AddArgument("disable-extensions");

**Comment by selenium-makeiteasy** [comment] 2018-03-15 05:23
In Java, try this, it worked for me.
ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.addArguments("enable-automation");

**Comment by mani86** [comment] 2018-03-19 05:30
Hi @selenium-makeiteasy the above code did not work for me. Can you confirm the version of chrome? Currently, i am on the following version: 65.0.3325.162 and Chromedriver: 2.37.

Thanks

**Comment by vvmmvv** [comment] 2018-03-19 07:05
I still have chrome developer extension at the side of chrome . ( extension are disabled in code ). 

My Chrome version : 
65.0.3325.162 
Chrome Driver 2.36.540470
Webriver.dll 3.11

![image](https://user-images.githubusercontent.com/37139633/37582228-a961d3c6-2b54-11e8-8560-b9ea72953738.png)

**Comment by selenium-makeiteasy** [comment] 2018-03-19 07:15
@mani86 i am using ChromeDriver 36 on Mac and it's working fine with Chrome 65.0.33. Could you please try once with driver 36.

**Comment by nroeper** [comment] 2018-04-09 06:32
I also get the dialog "Disable developer mode extensions" I have the same configuarion as vvmmvv. I use the .net bindings. Due to this issue we cannot update Chrome and the ChromeDriver. Any tips are appreciated.

Thanks!
