### ISSUE TITLE
[🐛 Bug]: current_url unknown error 

### ISSUE THREAD

**Issue by seungoh-lee** [SeleniumHQ/selenium#13115] opened 2023-11-08 14:02 UTC
### What happened?

Using the Python binding of Selenium (4.12.0), calling driver.current_url returns unknown error

### How can we reproduce the issue?

```shell
from selenium.webdriver import Remote, ChromeOptions
from selenium.webdriver.chromium.remote_connection import ChromiumRemoteConnection


def main():
    connection = ChromiumRemoteConnection("PROXY", 'goog', 'chrome')
    with Remote(connection, options=ChromeOptions()) as driver:
        print('Connected! Navigating to https://example.com...')
        driver.get('https://www.google.com/')
        print(driver.current_url)


if __name__ == '__main__':
    main()
```

### Relevant log output

```shell
selenium.common.exceptions.WebDriverException: Message: unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=119.0.6045.106)
```

### Operating System

macOS

### Selenium version

python 4.12.0

### What are the browser(s) and version(s) where you see this issue?

chrome=119.0.6045.106

### What are the browser driver(s) and version(s) where you see this issue?

chrome=119.0.6045.106

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment] 2023-11-08 14:10
Looks like a duplicate of #13084

Turn on logging and make sure you are actually using chrome and chromedriver 119: 
https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by seungoh-lee** [comment] 2023-11-08 14:38
I checked the normal operation when I approached it in a different version (117.0.5938.62)
Is it error in the 119.0.6045.xxx version?

**Comment by seungoh-lee** [comment] 2023-11-08 14:47
upgrade chrome version 119.0.6045.123 it works

**Closed as completed** 2023-11-08 14:47 UTC
Labels: J-awaiting answer, I-defect, J-issue-template
