### ISSUE TITLE
[🚀 Feature]: Give us a way to completely clear the cache at the end of a test run

### ISSUE THREAD

**Issue by jmkingsf** [SeleniumHQ/selenium#13682] opened 2024-03-11 21:13 UTC
### Feature and motivation

It's common practice at my company to delete any files we create as part of our test runs in pipelines. Using the new Selenium Manager I can automate the download of the appropriate driver for the OS. I would like to have a way to clear out these files after I've completed my tests.

### Usage example

In dotnet, implementing DriverFinder.ClearCache() would solve the problem. Where calling ClearCache would remove all files found in the cache location. (~/.cache/selenium)

**Comment by diemol** [comment] 2024-03-11 21:20
This is a duplicate of #13657. In general, the request is to find a way to expire the cache.

**Closed as not planned by diemol** 2024-03-11 21:20 UTC
Labels: I-enhancement
