### ISSUE TITLE
[🐛 Bug]: Nuget package doesn't contain inline documentation (xml file)

### ISSUE THREAD

**Issue by nvborisenko** [SeleniumHQ/selenium#10375] opened 2022-02-18 22:16 UTC
### What happened?

Visual Studio doesn't highlight members inline documentation.

### How can we reproduce the issue?

```shell
Use `Selenium.WebDriver` nuget package.
```

### Relevant log output

```shell
any
```

### Operating System

any

### Selenium version

4.1.0

### What are the browser(s) and version(s) where you see this issue?

any

### What are the browser driver(s) and version(s) where you see this issue?

any

**Comment by titusfortner** [comment] 2022-02-18 23:12
This is a duplicate of #10126

**Closed as completed by titusfortner** 2022-02-18 23:12 UTC
Labels: I-defect, A-needs-triaging
