### ISSUE TITLE
[🐛 Bug]: Unable to execute request for an existing session: GET /session/f77974f3-032d-4f3d-b6df-bbed7e364f8e/window/rect

### ISSUE THREAD

**Issue by sushobhit-lt** [SeleniumHQ/selenium#10378] opened 2022-02-19 12:06 UTC
### What happened?

Get Window Rect Command(`/window/rect`) is giving RuntimeException with Selenium standalone version 4.0.0

**Error Response**:
```
{
    "value": {
        "error": "script timeout",
        "message": "Unable to execute request for an existing session: GET /session/f77974f3-032d-4f3d-b6df-bbed7e364f8e/window/rect\nBuild info: version: '4.0.0', revision: '3a21814679'\nSystem info: host: 'Sanjays-MacBook-Pro.local', ip: 'fe80:0:0:0:8e5:9ede:9c54:e086%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.4', java.version: '1.8.0_292'\nDriver info: driver.version: unknown",
        "stacktrace": "java.lang.RuntimeException: Unable to execute request for an existing session: GET /session/f77974f3-032d-4f3d-b6df-bbed7e364f8e/window/rect\nBuild info: version: '4.0.0', revision: '3a21814679'\nSystem info: host: 'Sanjays-MacBook-Pro.local', ip: 'fe80:0:0:0:8e5:9ede:9c54:e086%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.4', java.version: '1.8.0_292'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:139)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:91)\n\tat org.openqa.selenium.grid.web.CheckOriginHeader.lambda$apply$0(CheckOriginHeader.java:66)\n\tat org.openqa.selenium.grid.web.CheckContentTypeHeader.lambda$apply$0(CheckContentTypeHeader.java:70)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:270)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"
    }
}
```

"stacktrace": "java.lang.RuntimeException: Unable to execute request for an existing session: GET /session/f77974f3-032d-4f3d-b6df-bbed7e364f8e/window/rect\nBuild info: version: '4.0.0', revision: '3a21814679'\nSystem info: host: 'Sanjays-MacBook-Pro.local', ip: 'fe80:0:0:0:8e5:9ede:9c54:e086%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.4', java.version: '1.8.0_292'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:139)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:91)\n\tat org.openqa.selenium.grid.web.CheckOriginHeader.lambda$apply$0(CheckOriginHeader.java:66)\n\tat org.openqa.selenium.grid.web.CheckContentTypeHeader.lambda$apply$0(CheckContentTypeHeader.java:70)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"

### How can we reproduce the issue?

```shell
### Steps

- Start Standalone Selenium 4.0.0 server, using command


java -Dwebdriver.gecko.driver="geckodriver" -jar selenium-server-4.0.0.jar standalone   --driver-configuration display-name="Firefox"    stereotype='{"browserName": "firefox", "browserVersion": "97", "moz:firefoxOptions": {"binary":"/Applications/Firefox.app/Contents/MacOS/firefox-bin"}}' --log-level=FINE
```

- After that Create New Firefox Session

```
curl --location --request POST 'http://localhost:4444/wd/hub/session' \
--header 'Accept: application/json; charset=utf-8' \
--header 'Content-Type: application/json; charset=utf-8' \
--data-raw '{
    "desiredCapabilities": {
        "browserName": "firefox"
    }
}'
```

- Once session created, the hit `/session/{session id}/window/rect` API Call
```
curl --location --request GET 'http://localhost:4444/wd/hub/session/f77974f3-032d-4f3d-b6df-bbed7e364f8e/window/rect' \
--header 'Content-Type: application/json; charset=utf-8'
```

Error Response :

```{
    "value": {
        "error": "script timeout",
        "message": "Unable to execute request for an existing session: GET /session/f77974f3-032d-4f3d-b6df-bbed7e364f8e/window/rect\nBuild info: version: '4.0.0', revision: '3a21814679'\nSystem info: host: 'Sanjays-MacBook-Pro.local', ip: 'fe80:0:0:0:8e5:9ede:9c54:e086%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.4', java.version: '1.8.0_292'\nDriver info: driver.version: unknown",
        "stacktrace": "java.lang.RuntimeException: Unable to execute request for an existing session: GET /session/f77974f3-032d-4f3d-b6df-bbed7e364f8e/window/rect\nBuild info: version: '4.0.0', revision: '3a21814679'\nSystem info: host: 'Sanjays-MacBook-Pro.local', ip: 'fe80:0:0:0:8e5:9ede:9c54:e086%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.4', java.version: '1.8.0_292'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:139)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:91)\n\tat org.openqa.selenium.grid.web.CheckOriginHeader.lambda$apply$0(CheckOriginHeader.java:66)\n\tat org.openqa.selenium.grid.web.CheckContentTypeHeader.lambda$apply$0(CheckContentTypeHeader.java:70)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$NestedRoute.handle(Route.java:270)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"
    }
}```
```

### Relevant log output

```shell
17:21:19.711 WARN [SpanWrappedHttpHandler.execute] - Unable to execute request: GET /session/f77974f3-032d-4f3d-b6df-bbed7e364f8e/window/rect
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'Sanjays-MacBook-Pro.local', ip: 'fe80:0:0:0:8e5:9ede:9c54:e086%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.4', java.version: '1.8.0_292'
Driver info: driver.version: unknown
org.openqa.selenium.UnsupportedCommandException: GET /session/f77974f3-032d-4f3d-b6df-bbed7e364f8e/window/rect
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'Sanjays-MacBook-Pro.local', ip: 'fe80:0:0:0:8e5:9ede:9c54:e086%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.4', java.version: '1.8.0_292'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.codec.AbstractHttpCommandCodec.decode(AbstractHttpCommandCodec.java:293)
	at org.openqa.selenium.remote.codec.AbstractHttpCommandCodec.decode(AbstractHttpCommandCodec.java:127)
	at org.openqa.selenium.grid.web.ProtocolConverter.execute(ProtocolConverter.java:123)
	at org.openqa.selenium.grid.node.ProtocolConvertingSession.execute(ProtocolConvertingSession.java:75)
	at org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:123)
	at org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:388)
	at org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)
	at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.grid.node.Node.execute(Node.java:240)
	at org.openqa.selenium.grid.web.CombinedHandler.execute(CombinedHandler.java:59)
	at org.openqa.selenium.grid.web.RoutableHttpClientFactory$1.execute(RoutableHttpClientFactory.java:72)
	at org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:92)
	at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:110)
	at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.grid.router.Router.execute(Router.java:91)
	at org.openqa.selenium.grid.web.CheckOriginHeader.lambda$apply$0(CheckOriginHeader.java:66)
	at org.openqa.selenium.grid.web.CheckContentTypeHeader.lambda$apply$0(CheckContentTypeHeader.java:70)
	at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17:21:19.712 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "36e0eaaeb0d50e837f0b801c3abfb50a","eventTime": 1645271479711205999,"eventName": "exception","attributes": {"exception.message": "Unable to execute request: GET \u002fsession\u002ff77974f3-032d-4f3d-b6df-bbed7e364f8e\u002fwindow\u002frect\nBuild info: version: '4.0.0', revision: '3a21814679'\nSystem info: host: 'Sanjays-MacBook-Pro.local', ip: 'fe80:0:0:0:8e5:9ede:9c54:e086%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.4', java.version: '1.8.0_292'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.UnsupportedCommandException: GET \u002fsession\u002ff77974f3-032d-4f3d-b6df-bbed7e364f8e\u002fwindow\u002frect\nBuild info: version: '4.0.0', revision: '3a21814679'\nSystem info: host: 'Sanjays-MacBook-Pro.local', ip: 'fe80:0:0:0:8e5:9ede:9c54:e086%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.4', java.version: '1.8.0_292'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.remote.codec.AbstractHttpCommandCodec.decode(AbstractHttpCommandCodec.java:293)\n\tat org.openqa.selenium.remote.codec.AbstractHttpCommandCodec.decode(AbstractHttpCommandCodec.java:127)\n\tat org.openqa.selenium.grid.web.ProtocolConverter.execute(ProtocolConverter.java:123)\n\tat org.openqa.selenium.grid.node.ProtocolConvertingSession.execute(ProtocolConvertingSession.java:75)\n\tat org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:123)\n\tat org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:388)\n\tat org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.node.Node.execute(Node.java:240)\n\tat org.openqa.selenium.grid.web.CombinedHandler.execute(CombinedHandler.java:59)\n\tat org.openqa.selenium.grid.web.RoutableHttpClientFactory$1.execute(RoutableHttpClientFactory.java:72)\n\tat org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:92)\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:110)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:373)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:91)\n\tat org.openqa.selenium.grid.web.CheckOriginHeader.lambda$apply$0(CheckOriginHeader.java:66)\n\tat org.openqa.selenium.grid.web.CheckContentTypeHeader.lambda$apply$0(CheckContentTypeHeader.java:70)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n","exception.type": "org.openqa.selenium.UnsupportedCommandException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "localhost:4444","http.method": "GET","http.scheme": "HTTP","http.target": "\u002fsession\u002ff77974f3-032d-4f3d-b6df-bbed7e364f8e\u002fwindow\u002frect","http.user_agent": "PostmanRuntime\u002f7.28.2"}}
```

### Operating System

MacOS Catalina

### Selenium version

Postman/Java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 97

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.30.0 

### Are you using Selenium Grid?

Standlone 4.0.0

**Comment by titusfortner** [comment] 2022-02-19 22:09
Why are you using curl for this? `window/rect` is a w3c endpoint, but you are not sending w3c compliant capabilities. I think this should still work, but the Selenium classes ensure the correct code is being used, and would be easier for us to troubleshoot. Also, can you please try this with the latest version of Grid (4.1.2)?

**Comment by sushobhit-lt** [comment] 2022-02-23 16:21
@titusfortner I've tried with latest version of Grid (4.1.2), but same issue persist with `/window/rect` command,
```
org.openqa.selenium.UnsupportedCommandException: GET /session/9925de69-ce0e-4b9f-b523-f7be6c8d4bb7/window/rect
```

**Comment by chandrajeetn** [comment] 2022-02-23 16:27
I am facing the same issue with setup. Although i am able to resize my window by sending a curl request to selenium 4 for request window/current/size. Would it be feasible to always convert the selenium request of window/rect to window/current/size ? or are there any precautions which needs to be taken care as well.

**Comment by diemol** [comment] 2022-02-23 19:37
The problem is that when you send this payload requesting a new session:
```json
{
	"desiredCapabilities": {
		"browserName": "firefox"
	}
}
```
You are telling Grid that you speak JsonWireProtocol (JWP), so Grid takes that and translates internally the session creation to be W3C for GeckoDriver. Therefore, Grid describes the session as JWP on the client side, and W3C on the browser driver side. This means that Grid will expect the client to speak JWP and will then do its best to translate it to W3C for GeckoDriver.

Now, when you do `GET /session/{sessionId}/window/rect`, you are sending a W3C command. This confuses Grid because it is expecing a JWP command. That is why you get the error. Using the Selenium bindings instead of curl avoids that pain.

If you still want to use curl and send the W3C command, it is better to create the session with the following W3C compliant payload:
```json
{
	"capabilities": {
		"alwaysMatch": {
			"browserName": "firefox"
		}
	}
}
```
Then, the session will be W3C both on the client and browser driver side, and the command will work.

Please note that the translation done by Grid is far from perfect and there might be cases like this one where it won't work. Also, as all browser drivers speak W3C and the usage of JWP only clients is being reduced  as time passes, the translation will be eventually removed from Grid. Relying on it in the long term is not a good idea.

Closing this as it gets solved if the session is created as W3C.

**Closed as completed by diemol** 2022-02-23 19:37 UTC
