### ISSUE TITLE
Firefox: synthetic keyboard events do not set KeyboardEvent.key property properly

### ISSUE THREAD

**Issue by mkresin** [SeleniumHQ/selenium#386] opened 2015-03-28 18:03 UTC
Selenium 2.45.0 uses synthetic keyboard events for Firefox 36.0.4 on all(?) platforms. These synthetic keyboard events set the javascript [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) property always to 'Unidentified' instead of the expected character.

Using native events with Firefox <= 34.0.5 on Windows 7 the following phpunit test run successfully:

``` php
<?php
class KeyTest extends PHPUnit_Extensions_Selenium2TestCase
{
    protected function setUp()
    {
        $this->setBrowser('firefox');
        $this->setHost('localhost');
        $this->setBrowserUrl('http://unixpapa.com/js/testkey.html');
    }

    public function testKeys()
    {
        $this->url('http://unixpapa.com/js/testkey.html');

        $this->byName('classic')->click();
        $this->byName('dom3')->click();

        $this->keys('z');
        $this->assertContains('key=z', $this->byTag('textarea')->value());
    }
}
```

As far as I can see, it's related to the use of `sendKeyEvent` in favour to `sendNativeKeyEvent` in https://github.com/SeleniumHQ/selenium/blob/cf26e94543b7c838996a21995fcb8bbe11a800bd/javascript/firefox-driver/js/utils.js#L671.

While testing `sendNativeKeyEvent` in Firefox's Scratchpad I had mixed results:
- Windows: working
- Linux: Exception
- MacOS: obviously working (key is send to scratchpad window instead of webpage)

**Comment by barancev** [comment] 2015-03-31 16:26
Switching to sendNativeKeyEvent requires significant amount of work to map Selenium key codes to Firefox ones.

**Comment by wongterrencew** [comment] 2015-09-09 18:13
This pull request should be for: https://github.com/SeleniumHQ/selenium/issues/588

**Comment by goldylucks** [comment] 2016-07-17 01:13
is this issue dead?
any ETA on that?

**Comment by goldylucks** [comment] 2016-07-17 01:15
is this issue dead?
any ETA on that?

I'm not a java developer, tho if it's a small fix I'll make a PR with some guidance.
I have a semi completed mapping of keycodes to keys

**Comment by lukeis** [comment] 2016-07-17 16:25
@goldylucks it's kind of dead... the problem is one would need to refactor the code, since sendKeyEvent is deprecated in firefox and it suggest to use this:
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsITextInputProcessor

I tried to take a stab at that a long time ago, and ended up not having the time or energy to follow through with it. Also since after FF48, this driver will essentially be dead and GeckoDriver will need to be used in the future, I didn't think it seemed worth it to invest the time in it.

Also, the fix would not be in java at all, purely JavaScript.

**Comment by goldylucks** [comment] 2016-07-19 09:01
@lukeis thanks for the response
it's not only firefox
I'm having the same issue in chrome

do u have an estimation on how much time it will take to fix?

and if so, could u point me where to begin with it?

**Comment by lukeis** [comment] 2016-07-19 15:53
'less easy' aka 'non-trivial', it will take a decent amount of time... where decent is quite a few hours for someone who knows what they are doing.

This bug has been entirely for firefox and references to firefox driver code. Chrome has a different code path and you'd need to first start looking at the chromium source to figure out how it's exactly doing the sendKey event(s).

Here's where I've been able to trace the function call to in chromedriver down to creating events:
https://cs.chromium.org/chromium/src/chrome/test/chromedriver/key_converter.cc?rcl=1468912738&l=193
And then it sends those key events:
https://cs.chromium.org/chromium/src/chrome/test/chromedriver/chrome/web_view_impl.cc?rcl=1468912738&l=400

Which is a remote request to the Chrome Inspector... to which I don't know exactly where that source code is, but somewhere in the chromium repo.

hope you're good at C? :)

**Comment by lukeis** [comment] 2016-07-19 15:57
btw "quite a few" is a gross understatement, it could take someone days (for firefox), chrome may be less (in the range of hours), since it doesn't likely require the extensive refactor of the mechanism that is creating the key events

**Comment by goldylucks** [comment] 2016-07-19 18:42
Thanks for the pointers.
Sadly I don't know any C

maybe it's better to close this issue?

**Comment by lukeis** [comment] 2016-07-19 19:03
I intend to close this issue (and really all FirefoxDriver issues logged against this repo) when GeckoDriver is the default and Firefox no longer works with the FirefoxDriver here.

**Comment by barancev** [comment] 2017-08-03 15:25
It's time to close this issue, geckodriver is the default and it passes this test.

**Closed by barancev** 2017-08-03 15:25 UTC
Labels: D-firefox, E-less easy, I-defect
