### ISSUE TITLE
SessionNotCreatedException: with firefox 80.0+

### ISSUE THREAD

**Issue by pva** [SeleniumHQ/selenium#8709] opened 2020-09-17 10:00 UTC
## 🐛 Bug Report

I've upgraded firefox to 80.0 and now to 80.0.1 and started to receive error:

```
>>> from selenium import webdriver
>>> webdriver.Firefox()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peter/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 191, in __init__
    keep_alive=True)
  File "/home/peter/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 184, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/peter/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 281, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/peter/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 350, in execute
    self.error_handler.check_response(response)
  File "/home/peter/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 240, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

```

## To Reproduce

Detailed steps to reproduce the behavior:
$ python
>>> from selenium import webdriver
>>> webdriver.Firefox()

## Expected behavior

Something should work.

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

>>> from selenium import webdriver
>>> webdriver.Firefox()

## Environment

OS: Gentoo Linux, Debian 10
Browser: Firefox 
Browser version: 80.0.1
geckodriver 0.26.0
Language Bindings version: python 3.7

## Additional important information

My distribution is Gentoo Linux while I found similar reports for Debian:
https://stackoverflow.com/questions/63820763/debian-10-selenium-firefox-driver-incompatible-with-firefox-esr/63934063

I've tried selenium 3.141.0-r1 and now I built from git, selenium-4.0.0.a6-py2.py3-none-any.whl, and still have the same problem. I've tried to update geckodriver to 0.27.0, still same issue (binary from https://github.com/mozilla/geckodriver/releases).

**FF downgrade to 68.12.0 fixed** this problem.

**Comment by diemol** [comment] 2020-09-20 11:00
@pva how can we reproduce the issue? I just tried the provided two lines of code and it works.
Which was the last version of Firefox where this worked? Seems that you are mixing Firefox and Firefox ESR?

**Comment by pva** [comment] 2020-09-22 19:50
> @pva how can we reproduce the issue? I just tried the provided two lines of code and it works.

Have you tried with firefox 80.0.1?

> Which was the last version of Firefox where this worked?

It worked with www-client/firefox-75.0-r2.

> Seems that you are mixing Firefox and Firefox ESR?

Well, I was just upgrading gradually:

2020-02-26T11:54:36 >>> www-client/firefox-73.0.1: 2′18″
2020-03-11T09:54:24 >>> www-client/firefox-73.0.1: 1′36″
2020-03-19T23:20:05 >>> www-client/firefox-74.0-r1: 1′52″
2020-04-16T14:51:41 >>> www-client/firefox-75.0: 1′24″
2020-05-02T10:26:43 >>> www-client/firefox-75.0-r2: 1′10″
2020-09-09T11:24:40 >>> www-client/firefox-80.0.1-r1: 4′59″ 
2020-09-17T12:25:36 >>> www-client/firefox-68.12.0: 57s

With version 80.0.1-r1 it started to fail so I reverted back on 68.12.0 where it works. So yes, maybe I'm mixing, but is that a problem?

**Comment by diemol** [comment] 2020-09-28 21:05
@pva yes, I tried with those versions and it worked. It is hard to find a way to help if we do not have a way to reproduce the issue. It'd be great if you can provide a way to do that.

**Comment by diemol** [comment] 2020-10-10 15:10
I will close this because we don't have a way to reproduce the issue.

**Closed as completed by diemol** 2020-10-10 15:10 UTC
Labels: J-awaiting answer

**Comment by pva** [comment] 2020-10-23 14:27
Just to note: After I've upgraded to firefox to version 82.0 everything works!
