### ISSUE TITLE
Unable to add cookie

### ISSUE THREAD

**Issue by jwerkau** [SeleniumHQ/selenium#4980] opened 2017-10-30 16:51 UTC
## Meta -
OS:  
Windows 10
Selenium Version:  
3.5.3
Browser:  
Chrome

Browser Version:  
62.0.3202.75 (Official Build) (64-bit)

## Expected Behavior -
Manually add cookie after starting webdriver.

## Actual Behavior -
No cookie is being added to the browser.  There is no error or stacktrace info.

## Steps to reproduce -
1) Start a webdriver instance
WebDriver chrome = new ChromeDriver();

2) Create the cookie
Cookie apiCookie = new Cookie.Builder("my_cookie", "my_value"))
            .domain("mydomain")
            .isHttpOnly(false)
            .isSecure(true)
            .path("/")
            .build();

3) Add the cookie
chrome.manage().addCookie(apiCookie);

When running this code after chrome version 62 the cookie is no longer added.  It also appears that when running the default function the cookie is added.  It is only when you add the options that this appears to fail (i.e. domain, isHttpOnly, etc).

**Comment by p0deje** [comment] 2017-11-01 03:22
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by jwerkau** [comment] 2017-11-01 22:07
@p0deje My apologies.  Long time listener first time caller.  I tried to update the best I can.  The issue appears to be simply creating the Cookie object.  In any fashion that I create the object without the defaults it does not appear to be adding the cookie to the browser.  This can be done in numerous fashions but as noted above in my case I start the webdriver, create the cookie and then try adding it through the webdriver.

**Comment by p0deje** [comment] 2017-11-02 03:34
> When running this code after chrome version 62 the cookie is no longer added.

Does it work with Chrome < 62?

**Comment by jwerkau** [comment] 2017-11-02 03:38
Correct from 61 and before this same code worked.

**Comment by p0deje** [comment] 2017-11-02 04:27
What ChromeDriver version do you use?

**Comment by jwerkau** [comment] 2017-11-02 04:29
Chromedriver 2.33

**Comment by p0deje** [comment] 2017-11-02 04:35
I see that ChromeDriver 2.33 changed the way add cookie worked (https://chromedriver.storage.googleapis.com/2.33/notes.txt). It looks like a regression in ChromeDriver (see https://bugs.chromium.org/p/chromedriver/issues/detail?id=2002 for details).

Closing as there is nothing to do on Selenium side.

**Closed by p0deje** 2017-11-02 04:35 UTC
Labels: R-awaiting answer
