### ISSUE TITLE
FirefoxDriver fails to identify an element based on XPath, which is getting uniquely identified in FirePath and ChromeDriver

### ISSUE THREAD

**Issue by kcomkar** [SeleniumHQ/selenium#4156] opened 2017-06-10 15:24 UTC
## OS:  
_Windows 10 64-bit_

## Selenium Version:  
_WebDriver for Java v3.4_

## Browser:  
_Firefox_ 

## Browser Version:  
_53.0.3 (64-bit)_

## Test Script Source Code -

1. 		System.setProperty("webdriver.chrome.driver", "D:\\selenium\\drivers\\chromedriver.exe");
2. 		WebDriver driver = new ChromeDriver();
3. 		//System.setProperty("webdriver.gecko.driver", "D:\\selenium\\drivers\\geckodriver.exe");
4. 		//WebDriver driver = new FirefoxDriver();
5. 		driver.get("http://www.amazon.in/");
6. 		driver.findElement(By.xpath(".//input[@id='twotabsearchtextbox']")).click();
7. 		driver.findElement(By.xpath(".//input[@id='twotabsearchtextbox']")).sendKeys("iPhone 7 256GB");
8. 		driver.findElement(By.xpath("(.//input[@class='nav-input'])[1]")).click();
9. 		driver.findElement(By.xpath(".//*[@id='result_1']/div/div/div/div[2]/div[1]/div[1]/a/h2")).click();

## Expected Behavior -
Line 9 of source code should identify an element uniquely based on XPath. It was inspected and found to be getting identified uniquely using Firebug & Firepath in Firefox browser. 

## Actual Behavior -
Line 9 of source code identifies an element uniquely based on XPath. It was inspected and found to be getting identified uniquely using Firebug & Firepath in Firefox browser. 
But, when the test script runs it is showing an exception at Line 9 saying ElementNotFound.
However, the same code runs well in Chrome using ChromeDriver, i.e., the element is getting identified uniquely in chrome.

## Steps to reproduce -

1. Create a java source file importing all selenium libraries.
2. Create a class with Main method
3. Paste the source code given above
4. Compile and run the program
5. Uncomment chrome driver code, and comment firefox driver code and re-compile and re-run, and see the difference in outcome for both drivers.

**Comment by p0deje** [comment] 2017-06-11 08:47
I just ran this code using Firefox 53 and GeckoDriver 0.16.1 and it works perfectly fine.

It's likely to be a timing issue, so if you can add some waiting before clicking result, that might help.

Closing this because cannot reproduce, but will reopen if something new comes up.

**Closed by p0deje** 2017-06-11 08:47 UTC
