### ISSUE TITLE
Firefox 44.0.2 does not launch on OSX

### ISSUE THREAD

**Issue by divmgl** [SeleniumHQ/selenium#1743] opened 2016-03-04 16:45 UTC
## Expected Behavior 
Firefox launches when Firefox binary is installed in `/Applications` and set in `PATH`.

## Actual Behavior
Firefox does not launch, gives the following error.

```
UnknownError: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: MAC
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
```

## Steps to reproduce
Install Firefox 44.0.2 and attempt to run any test suite on OSX with Firefox.

**Comment by lukeis** [comment] 2016-03-04 17:01
it works for me... can you verify this file exists:

/Applications/Firefox.app/Contents/MacOS/firefox-bin

**Comment by divmgl** [comment] 2016-03-04 18:15
```
$ pwd
/Applications/Firefox.app/Contents/MacOS
$ ls
XUL                             firefox-bin                     libmozglue.dylib                libnssdbm3.dylib                plugin-container.app
crashreporter.app               libfreebl3.dylib                libnss3.dylib                   libplugin_child_interpose.dylib updater.app
firefox                         liblgpllibs.dylib               libnssckbi.dylib                libsoftokn3.dylib
$ ./firefox-bin
```

**Comment by lukeis** [comment] 2016-03-04 18:16
which programming language are you using? (sample code on how you start it?)

**Comment by divmgl** [comment] 2016-03-04 18:22
Sure. I'm using it through Protractor. Here's the configuration file.

```
exports.config = {
  framework: 'jasmine2',
  capabilities:  {
    browserName: 'firefox'
  }
}
```

**Comment by krmahadevan** [comment] 2016-03-06 04:20
@divmgl 
I am not able to recreate this problem. Here's what I have [ am using FF 44.0.2 on OSX ]

```
krmahadevan@localHost playground $ protractor --version
Version 3.1.1
krmahadevan@localHost playground $ cat conf.js
// conf.js
exports.config = {
  framework: 'jasmine',
  seleniumAddress: 'http://localhost:4444/wd/hub',
  capabilities:  {
    browserName: 'firefox'
  },
  specs: ['spec.js']
}
krmahadevan@localHost playground $ cat spec.js
// spec.js
describe('Protractor Demo App', function() {
  it('should have a title', function() {
    browser.get('http://juliemr.github.io/protractor-demo/');

    expect(browser.getTitle()).toEqual('Super Calculator');
  });
});
```

Here's the script execution output
```
protractor conf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Started
.


1 spec, 0 failures
Finished in 0.796 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] firefox #1 passed
```

and here's the output [ At the server side ]
```
webdriver-manager start
seleniumProcess.pid: 3700
09:41:46.193 INFO - Launching a standalone Selenium Server
Setting system property webdriver.chrome.driver to /usr/local/lib/node_modules/protractor/selenium/chromedriver
09:41:46.260 INFO - Java: Oracle Corporation 25.66-b17
09:41:46.260 INFO - OS: Mac OS X 10.11.3 x86_64
09:41:46.268 INFO - v2.51.0, with Core v2.51.0. Built from revision 1af067d
09:41:46.341 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
09:41:46.342 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
09:41:46.342 INFO - Driver class not found: com.opera.core.systems.OperaDriver
09:41:46.342 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
09:41:46.599 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
09:41:46.599 INFO - Selenium Server is up and running
09:45:20.065 INFO - Executing: [new session: Capabilities [{count=1, browserName=firefox}]])
09:45:20.117 INFO - Creating a new session for Capabilities [{count=1, browserName=firefox}]
09:45:26.317 INFO - Done: [new session: Capabilities [{count=1, browserName=firefox}]]
09:45:26.337 INFO - Executing: [set script timeout: 11000])
09:45:26.373 INFO - Done: [set script timeout: 11000]
09:45:26.649 INFO - Executing: [get: data:text/html,<html></html>])
09:45:26.709 INFO - Done: [get: data:text/html,<html></html>]
09:45:26.717 INFO - Executing: [execute script: window.name = "NG_DEFER_BOOTSTRAP!NG_ENABLE_DEBUG_INFO!" + window.name;window.location.replace("http://juliemr.github.io/protractor-demo/");, []])
09:45:26.730 INFO - Done: [execute script: window.name = "NG_DEFER_BOOTSTRAP!NG_ENABLE_DEBUG_INFO!" + window.name;window.location.replace("http://juliemr.github.io/protractor-demo/");, []]
09:45:26.739 INFO - Executing: [execute script: return window.location.href;, []])
09:45:27.800 INFO - Done: [execute script: return window.location.href;, []]
09:45:27.807 INFO - Executing: [execute async script: try { return (function (attempts, asyncCallback) {
```

**Comment by jleyba** [comment] 2016-03-07 05:19
I'm not able to reproduce this (OSX 10.11.3)

```
$ npm install selenium-webdriver
selenium-webdriver@2.52.0 node_modules/selenium-webdriver
├── tmp@0.0.24
├── adm-zip@0.4.4
├── ws@1.0.1 (options@0.0.6, ultron@1.0.2)
├── rimraf@2.5.2 (glob@7.0.3)
└── xml2js@0.4.4 (sax@0.6.1, xmlbuilder@5.0.0)
$ node node_modules/selenium-webdriver/example/google_search
$ SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub node node_modules/selenium-webdriver/example/google_search
$ SELENIUM_SERVER_JAR="$(pwd)/../selenium-server-standalone-2.52.0.jar" node node_modules/selenium-webdriver/example/google_search
```

**Comment by jleyba** [comment] 2016-03-08 18:45
What version of selenium-webdriver are you/protractor actually using?

**Comment by jleyba** [comment] 2016-03-15 17:55
Closing this bug due to lack of information needed to reproduce/investigate the issue.

**Closed by jleyba** 2016-03-15 17:55 UTC
Labels: C-nodejs
