### ISSUE TITLE
artifact version 4.3.0 not committed to org.seleniumhq.selenium yet [🐛 Bug]: 

### ISSUE THREAD

**Issue by hollyw2025** [SeleniumHQ/selenium#10809] opened 2022-06-24 19:34 UTC
### What happened?

same issue with 
https://github.com/SeleniumHQ/selenium/issues/10803 
still can't checkout 4.3.0 from artifact 

### How can we reproduce the issue?

```shell
same issue with 
https://github.com/SeleniumHQ/selenium/issues/10803 
still can't checkout 4.3.0 from artifact
```

### Relevant log output

```shell
same issue with 
https://github.com/SeleniumHQ/selenium/issues/10803 
still can't checkout 4.3.0 from artifact
```

### Operating System

MAC

### Selenium version

4.3.0

### What are the browser(s) and version(s) where you see this issue?

MAC

### What are the browser driver(s) and version(s) where you see this issue?

chrome

**Comment by symonk** [comment] 2022-06-25 13:49
been a while since I looked at anything java, but is this not what you need @hollyhw15 https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-api/4.3.0

**Comment by pujagani** [comment] 2022-06-28 06:38
As Simon rightly pointed out. Everything for 4.3.0 is published in Maven. I tried to reproduce it @hollyhw15  and I am able to pull 4.3.0 dependencies into a maven project.
```
 <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-java</artifactId>
      <version>4.3.0</version>
    </dependency>
```

```
 <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-api</artifactId>
      <version>4.3.0</version>
    </dependency>
```
What particular error are you facing? Please provide more details about your project setup to triage this.

**Comment by diemol** [comment] 2022-06-28 11:29
To be honest, if the the version was not available. We would be getting tons of issues right now. I will close this as a question so the OP can get links to reach out to us if they have more queries.

**Closed as completed** 2022-06-28 11:29 UTC
Labels: I-question
