### ISSUE TITLE
[🐛 Bug]:  File Downloads using 4.8.2

### ISSUE THREAD

**Issue by csgbn** [SeleniumHQ/selenium#11845] opened 2023-03-30 19:44 UTC
### What happened?

In 4.8.2 the file downloads functionality using 
node --downloads-path 
was removed and replaced with 
node --enable-manage-downloads

File downloads worked fine using 4.8.1 but we are unable to get the new 4.8.2 functionality to work, keep getting the error:

{value={error=script timeout, message=Cannot find downloads file system for session id: 22e4b95d-110c-44cb-baed-b5962d226e4b
Build info: version: '4.8.2', revision: '826dbfc730'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1025-aws', java.version: '11.0.14.1'
Driver info: driver.version: unknown, stacktrace=org.openqa.selenium.WebDriverException: Cannot find downloads file system for session id: 22e4b95d-110c-44cb-baed-b5962d226e4b

Is this functionality complete? Can you update the example https://www.selenium.dev/documentation/grid/configuration/cli_options/#start-the-node-with-downloads-path-specified which is what we are using.

Same result using Chrome, Firefox, Edge on linux and windows.

We are running a remote distributed grid.

### How can we reproduce the issue?

```shell
Use 4.8.2 download a file using this example https://www.selenium.dev/documentation/grid/configuration/cli_options/#start-the-node-with-downloads-path-specified
```

### Relevant log output

```shell
{value={error=script timeout, message=Cannot find downloads file system for session id: 22e4b95d-110c-44cb-baed-b5962d226e4b
Build info: version: '4.8.2', revision: '826dbfc730'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-1025-aws', java.version: '11.0.14.1'
Driver info: driver.version: unknown, stacktrace=org.openqa.selenium.WebDriverException: Cannot find downloads file system for session id: 22e4b95d-110c-44cb-baed-b5962d226e4b
```

### Operating System

Windows 10, Linux

### Selenium version

4.8.2

### What are the browser(s) and version(s) where you see this issue?

Chrome, Edge, firefox 111

### What are the browser driver(s) and version(s) where you see this issue?

Latest

### Are you using Selenium Grid?

4.8.2

**Comment by titusfortner** [comment] 2023-03-31 18:21
We made some changes to make this feature more flexible, and we're hoping to provide direct support for it in the bindings. I'm not sure about the documentation. @krmahadevan does this need updating?

**Comment by krmahadevan** [comment] 2023-04-02 04:01
@titusfortner - I have raised a PR that updates the documentation so that it reflects the complete behaviour as of `4.8.3`

PR link: https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1351

The only thing that is still pending is the built in support to list files/download a particular file in the client bindings.

**Comment by diemol** [comment] 2023-04-03 15:50
Thanks @krmahadevan!
Docs PR has been merged and published.

**Closed as completed by diemol** 2023-04-03 15:50 UTC
Labels: I-defect

**Comment by patilsha** [comment] 2023-04-20 20:30
@csgbn I am also getting the same error while listing the files on grid version 4.8.3
Did you get any solution for this issue? Can someone help, Thanks
@diemol 

`"The remote server returned an error: (500) Internal Server Error.{\n  \"value\": {\n    \"error\": \"script timeout\",\n  
  \"message\": \"Cannot find downloads file system for session id: 995fa302650a746d38bf81473f873e34\\nBuild info: version: '4.8.3',
  revision: 'b19b418e60'\\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', 
  java.version: '11.0.18'\\nDriver info: driver.version: unknown\",\n    \"stacktrace\": \"org.openqa.selenium.WebDriverException: 
  Cannot find downloads file system for session id: 995fa302650a746d38bf81473f873e34\\nBuild info: version: '4.8.3', revision: 
  'b19b418e60'\\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', 
  java.version: '11.0.18'\\nDriver info: driver.version: unknown\\n\\tat 
  org.openqa.selenium.grid.node.local.LocalNode.downloadFile(LocalNode.java:609)\\n\\tat 
  org.openqa.selenium.grid.node.DownloadFile.execute(DownloadFile.java:39)\\n\\tat 
  org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)\\n\\tat 
  org.openqa.selenium.remote.http.Route.execute(Route.java:68)\\n\\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)\\n\\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\\n\\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\\n\\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\\n\\tat org.openqa.selenium.grid.node.Node.execute(Node.java:255)\\n\\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)\\n\\tat org.openqa.selenium.remote.http.Route.execute(Route.java:68)\\n\\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\\n\\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\\n\\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\\n\\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\\n\\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)\\n\\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\\n\\tat java.base\\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\\n\\tat java.base\\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\\n\\tat java.base\\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\\n\\tat java.base\\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\\n\\tat java.base\\u002fjava.lang.Thread.run(Thread.java:829)\\n\"\n  }\n}"`

**Comment by diemol** [comment] 2023-04-20 20:45
Seems you are asking for the file after the session ended.

**Comment by patilsha** [comment] 2023-04-20 21:05
Node session still shows alive on grid also I can see the downloaded file still available at path home\seluser\downloads
One thing I'm not sure how to set capability in C# webdriver which is only missing in my code because there is no way to set capability 'se:downloadsEnabled'
Is there any other way we can set this value?

When session expires I get below error so the error I posted is something different than session expired
`{
  "value": "\u002fsession\u002f244937065952cb8fd2f9ba204d69c252\u002fse\u002ffiles",
  "message": "Unable to execute request for an existing session: Unable to find session with ID: 244937065952cb8fd2f9ba204d69c252\nBuild info: version: '4.8.3', revision: 'b19b418e60'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.16.3-microsoft-standard-WSL2', java.version: '11.0.18'\nDriver info: driver.version: unknown",
  "error": "invalid session id"
}`

**Comment by diemol** [comment] 2023-04-20 22:52
Feel free to share the complete code to reproduce the problem in the issue you created.

**Comment by patilsha** [comment] 2023-04-21 19:27
Thanks @diemol for all your help.
This feature is now working perfect for me as well. The missing part in my code was as below
`ChromeOptions options = new ChromeOptions();
 options.AddAdditionalOption("se:downloadsEnabled", true);`
After adding the above line while setting-up chrome-options, file download and list of files APIs are working fine for me. 
Thanks again!

**Comment by krob1** [comment] 2023-05-31 10:51
Had a similar problem, thanks for your help. In case it helps: I had to use this
`options.setCapability("se:downloadsEnabled", true);`
to set the Chrome options (4.8.1).
