### ISSUE TITLE
Selenium Java Client (v3.9.1) with IEDriverServer v3.9.0.0 (64-bit) crashes with org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:28286

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#5519] opened 2018-02-21 12:12 UTC
## Meta - Selenium Java Client (v3.9.1) with IEDriverServer v3.9.0.0 (64-bit) crashes with org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:28286

IEDriverServer [CHANGELOG](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/cpp/iedriverserver/CHANGELOG) mentions : 

```
The "major" and "minor" fields are synchronized to releases of the Selenium
project. Changes in the "build" field indicate interim releases made publicly
available via the project downloads page. Changes in "revision" field indicate
private releases checked into the prebuilts directory of the source tree, but
not made generally available on the downloads page.
```
But **IEDriverServer_Win32_3.9.0** and **IEDriverServer_x64_3.9.0** was never pushed to [Download](https://docs.seleniumhq.org/download/) TAB of [seleniumhq.org](https://docs.seleniumhq.org/)

@jimevans on stackoverflow discussion [Can't launch Selenium IE Driver after upgrading to version 3.9](https://stackoverflow.com/questions/48895895/cant-launch-selenium-ie-driver-after-upgrading-to-version-3-9/48899810#comment84814851_48899810) confirmed **3.9.0.0** is official.

Thought **IEDriverServer_Win32_3.9.0** executes smooth but **IEDriverServer_x64_3.9.0** crashes with `org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:28286`

OS:  Windows 8 - Pro
Selenium Version:  3.9.0.1
Browser:   Internet Explorer v10.x

Browser Version:  Internet Explorer v10.x

## Steps to reproduce -
MCVE : 

```
package demo;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.ie.InternetExplorerOptions;
import org.openqa.selenium.remote.DesiredCapabilities;

public class A_IE_simple
{
	public static void main(String[] args) 
	{
			System.setProperty("webdriver.ie.driver", "C:\\Utility\\BrowserDrivers\\IEDriverServer.exe");
	        WebDriver driver = new InternetExplorerDriver();
			driver.get("https://www.google.co.in");
			System.out.println("Google Home Page Opened");
			driver.quit();
			System.out.println("Driver Closed");
	}
}
```

Error Stack Trace : 

```
	Started InternetExplorerDriver server (64-bit)
	3.9.0.0
	Listening on port 28286
	Only local connections are allowed
	Exception in thread "main" org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:28286
	Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:28.403Z'
	System info: host: 'ATECHM-03', ip: '192.168.1.35', os.name: 'Windows 8', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_144'
	Driver info: driver.version: InternetExplorerDriver
		at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
		at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
		at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:223)
		at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:215)
		at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:152)
		at demo.A_IE_simple.main(A_IE_simple.java:13)
	Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:28286
		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)
		at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
		at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
		at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
		at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
		at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
		at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
		at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
		at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
		at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
		at okhttp3.RealCall.execute(RealCall.java:77)
		at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:104)
		at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:54)
		at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:101)
		at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
		at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:138)
		at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
		... 6 more
	Caused by: java.net.ConnectException: Connection refused: connect
		at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
		at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
		at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
		at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
		at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
		at java.net.PlainSocketImpl.connect(Unknown Source)
		at java.net.SocksSocketImpl.connect(Unknown Source)
		at java.net.Socket.connect(Unknown Source)
		at okhttp3.internal.platform.Platform.connectSocket(Platform.java:125)
		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
		... 29 more

```

**Comment by jamiebarnett** [comment] 2018-02-23 11:27
I also am having this exact issue

**Comment by jimevans** [comment] 2018-02-23 11:34
As an additional data point, what happens if you set the `java.net.preferIPv4Stack` system property to `true`?

**Comment by Debanjan-B** [comment] 2018-02-23 12:02
Setting up _java_net_preferIPv4Stack_ through the following line : 

```
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.ie.InternetExplorerOptions;
import org.openqa.selenium.remote.DesiredCapabilities;

public class A_IE_simple
{
	public static void main(String[] args) 
	{
			System.setProperty("java.net.preferIPv4Stack", "true");
			System.setProperty("webdriver.ie.driver", "C:\\Utility\\BrowserDrivers\\IEDriverServer_64.exe");
	        WebDriver driver = new InternetExplorerDriver();
			driver.get("https://www.google.co.in");
			System.out.println("Google Home Page Opened");
			driver.quit();
			System.out.println("Driver Closed");
	}
}

```
Two popup comes out as follows : 

java_net_preferIPv4Stack
![java_net_preferipv4stack](https://user-images.githubusercontent.com/26503213/36593372-6d710f50-18bf-11e8-87f1-e5f3748c01b1.png)

**Comment by carlosmarcos** [comment] 2018-03-01 09:39
Same problem here. Downgrading to 3.8 now

**Comment by vrommer** [comment] 2018-03-04 13:44
I had the same problem. Switching to a different WebDriver (to 3.7.0) solved the problem for me (IE 11).

**Comment by jimevans** [comment] 2018-03-04 17:50
Can someone please generate a TRACE-level log file from IEDriverServer.exe showing a session that reproduces the crash? I am utterly unable to reproduce the issue in my environment.

**Comment by tkanafa** [comment] 2018-03-09 08:14
could you try to set up 
        System.setProperty("webdriver.http.factory", "apache");
and see if the error goes away ?
I had similar problems and from what I remember the culprit was smaller timeout on okhttp client and switching to older one fixed it as it has longer timeout

**Comment by jochemd** [comment] 2018-03-11 11:35
I have seen the same problem with Selenium 3.10.0 in combination with the IEDriverServer 3.9.0 and 3.10.0 x64. With an older IEDriverServer 3.8.0 or with the Win32 version it worls OK (or at least, IE is started and I get a different error which I am still investigating).

Setup is through Maven with selenium-server 3.10.0. Code is a minor adaptation from https://www.seleniumhq.org/docs/03_webdriver.jsp to test a few different drivers: 
[SeleniumTester.java.txt](https://github.com/SeleniumHQ/selenium/files/1800266/SeleniumTester.java.txt)

Traces for 3.8 and 3.10 in both Win32 and x64 are attached:
[IEDriverServer_x64_3.8.0.log](https://github.com/SeleniumHQ/selenium/files/1800261/IEDriverServer_x64_3.8.0.log)
[IEDriverServer_x64_3.10.0.log](https://github.com/SeleniumHQ/selenium/files/1800262/IEDriverServer_x64_3.10.0.log)
[IEDriverServer_Win32_3.8.0.log](https://github.com/SeleniumHQ/selenium/files/1800263/IEDriverServer_Win32_3.8.0.log)
[IEDriverServer_Win32_3.10.0.log](https://github.com/SeleniumHQ/selenium/files/1800264/IEDriverServer_Win32_3.10.0.log)

**Comment by jimevans** [comment] 2018-03-11 14:54
@jochemd Thanks for the logs. I am still unable to reproduce this with the 64-bit driver executable. I've added some additional logging to the new session command handler to try to narrow down where the issue might be. Can you please retry the test, and capture the trace-level logs using 3.11.0.0 of the IE driver (available later today).

**Comment by jochemd** [comment] 2018-03-12 08:02
@jimevans Behaviour still the same for me: 3.11.0 Win32 starts the browser correctly, navigates to Google and then throws an exception because it can't find the search field (which might be another bug). 3.11.0 x64 gives a timeout before the browser is even started.
I also attached the console log from Java.

[IEDriverServer_Win32_3.11.0.console.log](https://github.com/SeleniumHQ/selenium/files/1801836/IEDriverServer_Win32_3.11.0.console.log)
[IEDriverServer_Win32_3.11.0.log](https://github.com/SeleniumHQ/selenium/files/1801837/IEDriverServer_Win32_3.11.0.log)
[IEDriverServer_x64_3.11.0.console.log](https://github.com/SeleniumHQ/selenium/files/1801838/IEDriverServer_x64_3.11.0.console.log)
[IEDriverServer_x64_3.11.0.log](https://github.com/SeleniumHQ/selenium/files/1801839/IEDriverServer_x64_3.11.0.log)

**Comment by jimevans** [comment] 2018-03-12 13:14
@joechemd Thank you for the updated logs. That does give me more information than I had before. I still can’t repro the issue, but I’ll take another look, now that I have a better sense of where the driver is crashing.

**Comment by cgoldberg** [comment] 2018-03-12 13:57
> Failed to connect to localhost/0:0:0:0:0:0:0:1:28286

^^ so that seems to indicate that client is preferring IPv6 for localhost... this kinda sounds like the server is only binding to the IPv4 socket while client is trying to connect via IPv6.   Perhaps the code is not specifying dual mode sockets? 

I am also curious about the OP's configuration...

the following would be helpful to know:

1. what is the content of the hosts file on the problematic system (specifically what is 'localhost' mapped to)?
2. are both IPv4 and IPv6 enabled, or is this a pure IPv6 setup?

**Comment by jimevans** [comment] 2018-03-12 14:02
@cgoldberg IEDriverServer.exe listens on both the IPv4 and IPv6 loopbacks. The http connection is being made, as evidenced in the logs. Something is just crashing in the driver internals.

**Comment by jimevans** [comment] 2018-03-14 01:35
Fixed in 13d8f8b.

**Closed by jimevans** 2018-03-14 01:35 UTC
Labels: C-java, D-IE

**Comment by jochemd** [comment] 2018-03-22 12:51
I just testd 3.11.1 and that fixed the issue for me.

**Comment by vishudear** [comment] 2018-03-28 05:34
I was using 64bit IE Driver - 3.9.0 and I encountered below issue.
WHen I got this issue "Exception in thread "main" org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:28286"

Issue resolved when I used 32bit IE Driver.

**Comment by yesheswini** [comment] 2018-07-04 10:14
Hi,

Even I am facing similar issue when i started using IEdriver 32 bit 3.13.0. with selenium WEBdriver 3.13.0

org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:15743 Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z' System info: host: 'QSG057', ip: '172.16.26.211', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.1' Driver info: driver.version: RemoteWebDriver at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92) at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548) at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:276) at pages.LoginPage.launchURL(LoginPage.java:78) at requirements.creatingAndManagingCoalitions.CreatingAndManagingTheCoalitionincidents.incidentIsAssociatedToCoalitionIncidentInformationIsUpdatedInRecentEventsAndEventLog_223662(CreatingAndManagingTheCoalitionincidents.java:1198) Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:15743 at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:242) at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160) at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257) at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) at okhttp3.RealCall.execute(RealCall.java:77) at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:105) at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:155) at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83) ... 30 more Caused by: java.net.ConnectException: Connection refused: connect at java.base/java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) at java.base/java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source) at java.base/java.net.PlainSocketImpl.connect(Unknown Source) at java.base/java.net.SocksSocketImpl.connect(Unknown Source) at java.base/java.net.Socket.connect(Unknown Source) at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129) at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240) ... 50 more ... Removed 26 stack frames

Can you please look into this issue?

**Comment by Nefariis** [comment] 2018-07-11 17:08
Yup same issue with IE 3.13.0 32-bit and Selenium 3.13.0

```org.openqa.selenium.WebDriverException: java.net.SocketException: Connection reset
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'MLTCFE', ip: '10.35.98.126', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_151'
Driver info: driver.version: RemoteWebDriver

	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:276)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
	at com.sun.proxy.$Proxy9.click(Unknown Source)
	at org.ghc.utils.extensions.KPAUIEveryPage.search(KPAUIEveryPage.java:590)
	at org.ghc.pages.KPAUIUnAuthenticatedHomePage.getSearchResultsPage(KPAUIUnAuthenticatedHomePage.java:195)
	at org.ghc.tests.pages.KPAUISearchTests.validateNarrowSearchByTopicLinks(KPAUISearchTests.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.net.SocketException: Connection reset
```

followed by....

```org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:7717
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'MLTCFE', ip: '10.35.98.126', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_151'
Driver info: driver.version: RemoteWebDriver

	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:438)
	at org.ghc.utils.extensions.KPAUIEveryTest.afterTest(KPAUIEveryTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:7717
```

**Comment by acgauravelly** [comment] 2018-07-12 11:13
Had same problem here.

Just figured out that  if the IEDriverServer process is kille dmanually then the tests run fine .

If the process is running before your test starts its throwing the  below

rg.openqa.selenium.WebDriverException: java.net.SocketException: Connection reset
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'UK03-101883', ip: '10.3.21.158', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_171'
Driver info: driver.version: RemoteWebDriver
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:276)
        at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
        at Pages.BasePage.tickCheckboxIfUnticked(BasePage.java:116)
        at Pages.LoginPage.login(LoginPage.java:48)
        at Pages.LoginPage.defaultLogin(LoginPage.java:38)
        at Pages.LoginPage.loginIfUserisNotLoggedIn(LoginPage.java:59)
        at Tests.LoginTests.iamLoggedIn(LoginTests.java:14)
        at ?.Iam logged in(src/test/resources/CommitDate Reset.feature:8)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:105)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:155)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:276)
        at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
        at Pages.BasePage.tickCheckboxIfUnticked(BasePage.java:116)
        at Pages.LoginPage.login(LoginPage.java:48)
        at Pages.LoginPage.defaultLogin(LoginPage.java:38)
        at Pages.LoginPage.loginIfUserisNotLoggedIn(LoginPage.java:59)
        at Tests.LoginTests.iamLoggedIn(LoginTests.java:14)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cucumber.runtime.Utils$1.call(Utils.java:40)
        at cucumber.runtime.Timeout.timeout(Timeout.java:16)
        at cucumber.runtime.Utils.invoke(Utils.java:34)
        at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:37)
        at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:40)
        at cucumber.api.TestStep.executeStep(TestStep.java:78)
        at cucumber.api.TestStep.run(TestStep.java:61)
        at cucumber.api.TestCase.run(TestCase.java:28)
        at cucumber.runner.Runner.runPickle(Runner.java:80)
        at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:99)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:41)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:108)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)

**Can anyone can confirm the same.**

**Comment by ykolodiy** [comment] 2019-02-28 22:08
the same bug for me in IE v. 3.9.
downgraded to 3.6 - works fine
