### ISSUE TITLE
java.lang.IllegalStateException: The process has not exited yet therefore no result is available ...

### ISSUE THREAD

**Issue by binodpanta** [SeleniumHQ/selenium#676] opened 2015-06-17 15:19 UTC
This is occuring with Chromedriver, Ghostdriver, IEDriver for me.

In the case of chromedriver I use

selenium 2.45
chromedriver 2.13/2.14
windows, debian linux

IS this a known issue? It looks like this happens under a certain condition in commons-exec code, and appears to be a bug. This is causing lots of sporadic failures.

The code I use to start it in the case of chromedriver is as follows

new ChromeDriverService.Builder()
				.usingDriverExecutable(chromeDriverFile).usingAnyFreePort().start();

**Comment by barancev** [comment] 2015-06-17 15:56
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by ddavison** [comment] 2015-09-01 14:58
no answer for more than two months.  closing.  if this is still an issue, feel free to reopen, but please provide an example as @barancev has specified.

**Closed by ddavison** 2015-09-01 14:58 UTC
Labels: R-awaiting answer

**Comment by GaurangB** [comment] 2015-11-05 15:09
**Same exact error here is the full stack trace..**

Method arguments: "com.xxx.xxx.xxxModule", public void com.cision.qa.cpre.tests.MediaContactsTest.VPR9204_Media_Contacts_Profile_Insights_Tab_Show_tab_for_OAuthed_datagroups_but_not_ALL_datagrup(), org.testng.TestRunner@4e66a0
com.google.inject.ProvisionException: Guice provision errors: 

1) Error in custom provider, org.openqa.selenium.WebDriverException: The process has not exited yet therefore no result is available ...
Command duration or timeout: 240.37 seconds
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'CIWINBUILD4', ip: '10.12.218.157', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.7.0_67'
Driver info: org.openqa.selenium.remote.RemoteWebDriver 
  at com.cision.framework.selenium.WebDriverModule.getWebDriver(WebDriverModule.java:35) 
  while locating java.lang.ThreadLocal<org.openqa.selenium.WebDriver> 
    for field at com.cision.framework.testbase.UITestBase.driver(UITestBase.java:28) 
  while locating com.cision.qa.cpre.tests.MediaContactsTest 

1 error
com.google.inject.internal.Errors.throwProvisionExceptionIfErrorsExist(Errors.java:451)
com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:65)
com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:944)
com.google.guiceberry.GuiceBerryUniverse$TestCaseScaffolding.injectMembersIntoTest(GuiceBerryUniverse.java:171)
com.google.guiceberry.GuiceBerryUniverse$TestCaseScaffolding.runBeforeTest(GuiceBerryUniverse.java:117)
com.google.guiceberry.testng.TestNgGuiceBerry.setUp(TestNgGuiceBerry.java:65)
com.google.guiceberry.testng.TestNgGuiceBerry.setUp(TestNgGuiceBerry.java:50)
com.cision.framework.testbase.UITestBase.startFramework(UITestBase.java:51)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:606)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.WebDriverException: The process has not exited yet therefore no result is available ...
Command duration or timeout: 240.37 seconds
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'CIWINBUILD4', ip: '10.12.218.157', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.7.0_67'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:526)
org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)
com.cision.framework.selenium.WebDriverFactory.getInstance(WebDriverFactory.java:104)
com.cision.framework.selenium.WebDriverModule.getWebDriver(WebDriverModule.java:37)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:606)
com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:104)
com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:53)
com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:75)
com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:73)
com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:73)
com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:60)
com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:944)
com.google.guiceberry.GuiceBerryUniverse$TestCaseScaffolding.injectMembersIntoTest(GuiceBerryUniverse.java:171)
com.google.guiceberry.GuiceBerryUniverse$TestCaseScaffolding.runBeforeTest(GuiceBerryUniverse.java:117)
com.google.guiceberry.testng.TestNgGuiceBerry.setUp(TestNgGuiceBerry.java:65)
com.google.guiceberry.testng.TestNgGuiceBerry.setUp(TestNgGuiceBerry.java:50)
com.cision.framework.testbase.UITestBase.startFramework(UITestBase.java:51)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:606)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: The process has not exited yet therefore no result is available ...
org.apache.commons.exec.DefaultExecuteResultHandler.getException(DefaultExecuteResultHandler.java:74)
org.openqa.selenium.os.UnixProcess.checkForError(UnixProcess.java:165)
org.openqa.selenium.os.CommandLine.checkForError(CommandLine.java:183)
org.openqa.selenium.remote.service.DriverService.start(DriverService.java:165)
org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:62)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572)
org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:171)
org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:139)
sun.reflect.GeneratedConstructorAccessor49.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:59)
org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:53)
org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:54)
org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:215)
org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
java.util.concurrent.FutureTask.run(Unknown Source)
org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:169)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)

**Comment by ddavison** [comment] 2015-11-05 15:28
@GaurangB you have the stack trace, sure.. could we have some code that was used, so we can reproduce? there's not much we can do without that.

**Comment by GaurangB** [comment] 2015-11-05 16:10
@ddavison We are using a heavy custom framework built on top of selenium.. I am not sure if I can copy everything here for you to run the code. I will try to debug and maybe narrow down on some code.

**Comment by ddavison** [comment] 2015-11-05 17:04
that's ok - the most minimal case you could think of will do, as long as it's reproducible.

**Comment by npgarcia** [comment] 2016-01-07 15:02
I was able to reproduce this using phantomjs.
This is the code we are using to create the RemoteWebDriver:

```
private WebDriver getDesktopWebDriver(PropertyReader propertyReader, DesiredCapabilities desiredCapabilities) throws MalformedURLException {
        final URL seleniumHubRemoteAddress = getSeleniumRemoteAddress(propertyReader);
        final WebDriver driver = new RemoteWebDriver(seleniumHubRemoteAddress, desiredCapabilities);

        driver.manage().window().setSize(new Dimension(width, height));
        return driver;
    }
```

To form the desired capabilities:
```
final DesiredCapabilities capabilities = DesiredCapabilities.phantomjs();
            capabilities.setCapability("phantomjs.cli.args", PHANTOM_JS_ARGS);
            capabilities.setCapability("phantomjs.page.settings.userAgent", propertyReader.getProperty("user.agent"));

            driver = getDesktopWebDriver(propertyReader, capabilities);
```

Does this help?

**Comment by harsha20011992** [comment] 2016-12-28 13:07
I am getting the same issue with selenium Chrome driver:
Chrome driver version and machine details are as follows:

> Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'xxxxx', ip: 'x.x.x.x', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_111'
Driver info: driver.version: ChromeDriver

Below I have mentioned the code base and the exception stack trace:

`  public void testOpenGoogle() {
        System.setProperty("webdriver.chrome.driver", "E:\\softwares\\geckodriver\\geckodriver.exe");
        ChromeOptions options = new ChromeOptions();
        options.setBinary("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe");
        WebDriver driver = new ChromeDriver(options);
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        driver.get("http://www.google.com");
        if (driver.findElement(By.xpath("//input[@name='q']")).isEnabled()) {
            System.out.println("Google search text box Is enabled.");
            driver.findElement(By.xpath("//input[@name='q']")).sendKeys("WebDriver Test successful.");
            driver.findElement(By.xpath("//button[@name='btnG']")).click();
            System.out.println("Google search completed.");
        } else {
            System.out.println("Google search test box Is Not enabled.");

        }
        driver.close();
    }`

The exception trace:

> Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:141)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:174)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:163)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:152)
	at browser.ChromeImpl.testOpenGoogle(ChromeImpl.java:23)
	at seleniumtestproject.SeleniumTestproject.main(SeleniumTestproject.java:33)
Caused by: java.lang.IllegalStateException: The process has not exited yet therefore no result is available ...
	at org.apache.commons.exec.DefaultExecuteResultHandler.getException(DefaultExecuteResultHandler.java:76)
	at org.openqa.selenium.os.UnixProcess.checkForError(UnixProcess.java:173)
	at org.openqa.selenium.os.CommandLine.checkForError(CommandLine.java:185)
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:177)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:166)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:78)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	... 8 more
Java Result: 1
BUILD SUCCESSFUL (total time: 21 seconds)

Help will be highly appreciated. Thank you

**Comment by ddavison** [comment] 2017-01-03 17:39
at first glance, @harsha20011992 , you are specifying `webdriver.chrome.driver` to point at Geckodriver.  `geckodriver != chromedriver`
