### ISSUE TITLE
command line server for the ie driver has stopped working

### ISSUE THREAD

**Issue by udayanem** [SeleniumHQ/selenium#2580] opened 2016-08-08 04:22 UTC
## Meta -

OS:  Windows 7
Selenium Version:  2.53.
Browser:  IE 
Browser Version:  9 and also tried in 11
Expected Behavior - Should accept certificates and proceed navigation
Actual Behavior - Unable to proceed further automation with IE

In my automation i navigate to site "https://testuat.linenhouse.com.au/" and the site opens in normal context only. When i click on Sign In Image and there is a 'Join Now', then when i click on here the page navigates to "https" context. I am attaching the screenshot of the error i am getting.

I tried two to handle certificates:

```
 DesiredCapabilities cap=DesiredCapabilities.internetExplorer();
//DesiredCapabilities cap =new DesiredCapabilities(); Tried this also but didnt help
cap.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
System.setProperty("webdriver.ie.driver","IE driver path");
WebDriver driver=newInternetExplorerDriver(cap);
```

2nd Option is:
`driver.navigate().to("javascript:document.getElementById('overridelink').click()");`
![ie error](https://cloud.githubusercontent.com/assets/10852370/17469245/cc263784-5d4d-11e6-835d-f2454b5041a1.png)

**Comment by udayanem** [comment] 2016-08-10 17:55
Hi,

I am still seeing facing this problem. Can somebody throw light on this issue, please?

Thanks,
Uday

**Comment by dekelb** [comment] 2017-07-11 13:34
Having similar issue.
After several tests that pass IE11 just crash.

Selenium hub & node version = 3.4.0
IEDriverServer version = 3.4.0
IE Version = 11

    Files that help describe the problem:
        C:\...\Temp\WER55FB.tmp.WERInternalMetadata.xml
        C:\...\Temp\WER6049.tmp.appcompat.txt
        C:\...\Temp\WER6059.tmp.mdmp

Content of the WER6049.tmp.appcompat.txt:
```
<?xml version="1.0" encoding="UTF-16"?>
<DATABASE>
<EXE NAME="SYSTEM INFO" FILTER="CMI_FILTER_SYSTEM">
    <MATCHING_FILE NAME="kernel32.dll" SIZE="872448" CHECKSUM="0x3A0A495D" BIN_FILE_VERSION="6.1.7601.23775" BIN_PRODUCT_VERSION="6.1.7601.23775" PRODUCT_VERSION="6.1.7601.18015" FILE_DESCRIPTION="Windows NT BASE API Client DLL" COMPANY_NAME="Microsoft Corporation" PRODUCT_NAME="Microsoft® Windows® Operating System" FILE_VERSION="6.1.7601.18015 (win7sp1_gdr.121129-1432)" ORIGINAL_FILENAME="kernel32" INTERNAL_NAME="kernel32" LEGAL_COPYRIGHT="© Microsoft Corporation. All rights reserved." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x40004" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0xE0278" LINKER_VERSION="0x60001" UPTO_BIN_FILE_VERSION="6.1.7601.23775" UPTO_BIN_PRODUCT_VERSION="6.1.7601.23775" LINK_DATE="04/17/2017 15:15:06" UPTO_LINK_DATE="04/17/2017 15:15:06" EXPORT_NAME="KERNEL32.dll" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
    <MATCHING_FILE NAME="ntdll.dll" SIZE="1310528" CHECKSUM="0x9B7D4C81" BIN_FILE_VERSION="6.1.7601.23807" BIN_PRODUCT_VERSION="6.1.7601.23807" PRODUCT_VERSION="6.1.7600.16385" FILE_DESCRIPTION="NT Layer DLL" COMPANY_NAME="Microsoft Corporation" PRODUCT_NAME="Microsoft® Windows® Operating System" FILE_VERSION="6.1.7600.16385 (win7_rtm.090713-1255)" ORIGINAL_FILENAME="ntdll.dll.mui" INTERNAL_NAME="ntdll.dll" LEGAL_COPYRIGHT="© Microsoft Corporation. All rights reserved." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x40004" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x146322" LINKER_VERSION="0x60001" UPTO_BIN_FILE_VERSION="6.1.7601.23807" UPTO_BIN_PRODUCT_VERSION="6.1.7601.23807" LINK_DATE="05/12/2017 18:05:03" UPTO_LINK_DATE="05/12/2017 18:05:03" EXPORT_NAME="ntdll.dll" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
</EXE>
</DATABASE>
<EXE NAME="IED6528.tmp" FILTER="CMI_FILTER_THISFILEONLY">
    <MATCHING_FILE NAME="IED6528.tmp" SIZE="2463232" CHECKSUM="0xC1DF277E" MODULE_TYPE="WIN32" PE_CHECKSUM="0x0" LINKER_VERSION="0x0" LINK_DATE="04/21/2017 14:27:27" UPTO_LINK_DATE="04/21/2017 14:27:27" EXPORT_NAME="IEDRIVER.dll" EXE_WRAPPER="0x0" />
</EXE>
</DATABASE>
```

Content of WER55FB.tmp.WERInternalMetadata.xml:
```
<?xml version="1.0" encoding="UTF-16"?>
<WERReportMetadata>
	<OSVersionInformation>
		<WindowsNTVersion>6.1</WindowsNTVersion>
		<Build>7601 Service Pack 1</Build>
		<Product>(0x4): Windows 7 Enterprise</Product>
		<Edition>Enterprise</Edition>
		<BuildString>7601.23807.x86fre.win7sp1_ldr.170512-0600</BuildString>
		<Revision>1130</Revision>
		<Flavor>Multiprocessor Free</Flavor>
		<Architecture>X86</Architecture>
		<LCID>1033</LCID>
	</OSVersionInformation>
	<ParentProcessInformation>
		<ParentProcessId>2700</ParentProcessId>
		<ParentProcessPath>C:\ProgramData\Oracle\Java\javapath_target_1134657\java.exe</ParentProcessPath>
		<ParentProcessCmdLine>&quot;C:\ProgramData\Oracle\Java\javapath\java.exe&quot; -Dwebdriver.ie.driver=C:\Windows\System32\IEDriverServer.exe -jar selenium-server-standalone-3.4.0.jar -role node -hub http://HUBIP:4444/grid/register -browser &quot;browserName=internet explorer, version=11, platform=WINDOWS, maxInstances=1&quot;</ParentProcessCmdLine>
	</ParentProcessInformation>
	<ProblemSignatures>
		<EventType>APPCRASH</EventType>
		<Parameter0>IEDriverServer.exe</Parameter0>
		<Parameter1>3.4.0.0</Parameter1>
		<Parameter2>58fa16d4</Parameter2>
		<Parameter3>IED6528.tmp</Parameter3>
		<Parameter4>0.0.0.0</Parameter4>
		<Parameter5>58fa16cf</Parameter5>
		<Parameter6>c0000005</Parameter6>
		<Parameter7>00058856</Parameter7>
	</ProblemSignatures>
	<DynamicSignatures>
		<Parameter1>6.1.7601.2.1.0.256.4</Parameter1>
		<Parameter2>1033</Parameter2>
		<Parameter22>0a9e</Parameter22>
		<Parameter23>0a9e372d3b4ad19135b953a78882e789</Parameter23>
		<Parameter24>0a9e</Parameter24>
		<Parameter25>0a9e372d3b4ad19135b953a78882e789</Parameter25>
	</DynamicSignatures>
	<SystemInformation>
		<MID>9EAE4F63-9716-4A89-BE78-B4C56F114835</MID>
		<SystemManufacturer>VMware, Inc.</SystemManufacturer>
		<SystemProductName>VMware Virtual Platform</SystemProductName>
		<BIOSVersion>6.00</BIOSVersion>
	</SystemInformation>
</WERReportMetadata>
```

**Comment by barancev** [comment] 2019-07-14 15:27
While triaging old issues I've found this one without a reproduction scenario. Is this issue still actual?

**Comment by barancev** [comment] 2019-09-29 18:11
Closing the issue, it's related to antique IE driver versions and seems to be not relevant anymore.

**Closed by barancev** 2019-09-29 18:11 UTC
Labels: D-IE, R-awaiting answer
