### ISSUE TITLE
Applied SSL Certs and started receiving the exceptions when trying to register the nodes when using Selenium Grid 4 - Beta 3. There has been an error while loading the Nodes from the Grid. Exception while fetching data (/nodesInfo/nodes) : java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by shmikkil** [SeleniumHQ/selenium#9431] opened 2021-04-30 08:09 UTC
## 🐛 Bug Report
Error while loading nodes from the Grid after applying SSL Certs

## To Reproduce

- Leveraging Selenium Grid 4 Beta 3
- Applied SSL Certs
- Setup 5 components on a linux box: Eventbus, Sessions, SessionQueuer, Distributor & Router using the files updated after getting copies of each from --config-help
- Tried registering the Node and the Router starts throwing errors as below while accessing https://<hostname>:4444/ui/index.html#/:
Exception while fetching data (/grid/totalSlots) : java.lang.reflect.InvocationTargetException Exception while fetching data (/grid/nodeCount) : java.lang.reflect.InvocationTargetException Exception while fetching data (/grid/maxSession) : java.lang.reflect.InvocationTargetException Exception while fetching data (/grid/sessionCount) : java.lang.reflect.InvocationTargetException
Accessing this URL - https://<hostname>:4444/status gives the below error:
{
  "value": {
    "ready": false,
    "message": "Unable to read distributor status."
  }
}

Detailed steps to reproduce the behavior:
Cmds executed:
Event Bus:
java -jar /path/selenium-server-4.0.0-beta-3.jar event-bus \
--https-private-key /path to key/keyfilename.pkcs8 \
--https-certificate /path to cert/certfilename/cert.pem \
--registration-secret <secret> & 

Sessions:
java -jar /path/selenium-server-4.0.0-beta-3.jar sessions \
--https-private-key /path to key/keyfilename.pkcs8 \
--https-certificate /path to cert/certfilename/cert.pem \
--registration-secret <secret>& 

Session Queuer:
java -jar /path/selenium-server-4.0.0-beta-3.jar sessionqueuer \
--https-private-key /path to key/keyfilename.pkcs8 \
--https-certificate /path to cert/certfilename/cert.pem \
--registration-secret <secret>& 

Distributor:
java -jar /path/selenium-server-4.0.0-beta-3.jar distributor \
--sessions https://<hostname>:5556 \
--sessionqueuer https://<hostname>:5559 \
--bind-bus false \
--https-private-key /path to key/keyfilename.pkcs8 \
--https-certificate /path to cert/certfilename/cert.pem \
--registration-secret <secret>& 

Router cmd:
java -jar /path/selenium-server-4.0.0-beta-3.jar router \
--https-private-key /path to key/keyfilename.pkcs8 \
--https-certificate /path to cert/certfilename/cert.pem \
--sessions https://<hostname>:5556 \
--distributor-host <hostname> \
--distributor-port 5553 \
--sessionqueuer https://<hostname>:5559 \
--registration-secret <secret> &

Node:
java -jar drive:\path\selenium-server-4.0.0-beta-3.jar node --port 443 --detect-drivers true --publish-events tcp://<hostname>:4442 --subscribe-events tcp://<hostname>:4443 --https-private-key /path to key/keyfilename.pkcs8 
--https-certificate /path to cert/certfilename/cert.pem --registration-secret <secret>

There has been an error while loading the Nodes from the Grid. Exception while fetching data (/nodesInfo/nodes) : java.lang.reflect.InvocationTargetException

## Expected behavior

All the components should be up and running based on the documentation provided

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS:  Ubuntu 18.04
Browser:  N/A
Browser version:  N/A
Browser Driver version:  N/A
Language Bindings version:  N/A
Selenium Grid version (if applicable):  4 beta 3

**Comment by diemol** [comment] 2021-04-30 08:12
@shmikkil could you please provide the commands for all the steps you are mentioning above? We need a deterministic way to reproduce the issue.

**Comment by shmikkil** [comment] 2021-04-30 08:18
Just edited and added the cmds...Thanks for looking into this!:-)

**Comment by diemol** [comment] 2021-04-30 08:22
How are you creating the certs? Are they also added to the Java store?

**Comment by shmikkil** [comment] 2021-04-30 08:28
Yes, we used digicert and our internal system to get all 3 files after
completing the conversion to pkcs8. Applying the certs seem fine but
couldn't fetch the nodes and the distributor and router throws errors.

**Comment by diemol** [comment] 2021-06-01 09:46
@shmikkil, thank you for providing the steps to reproduce the issue, I was able to see the error as well.

This is happening because the configuration URIs do not have a host, and including one fixes the issue (e.g. from `https://:5556` to `https://localhost:5556`).

Nevertheless, I added some checks to reject URIs without a host, to give early feedback to users. This extra check will be part of Beta 4, but I will do a prerelease in a couple of days, and you could grab it [here](https://github.com/seleniumhq/docker-selenium/tree/beta-jars).

**Closed as completed by diemol** 2021-06-01 09:46 UTC
Labels: B-grid

**Comment by shmikkil** [comment] 2021-06-01 13:02
Diego, Thank You So Much! I will try this and move forward...:-)

Best Regards,
Harsha.

**Comment by shmikkil** [comment] 2021-06-04 13:10
Hi Diego,

Looks like there's some improvement but the issue still persists after a
few tests...
[image: image.png]

**Comment by diemol** [comment] 2021-06-04 19:18
What is the issue you are getting? Could you please describe it (with a way to reproduce it) and then we can reopen the issue?

**Comment by shmikkil** [comment] 2021-06-04 21:21
Hi Diego,

Thank You for the prompt response! We are seeing that when we pass the
wrong version of the .jar on the node and try register it to the hub, the
eventbus seem to crash and it's understandable! This beta-4 looks really
clean! Thank You So Very Much for getting a ton of issues sorted out!

Thanks,
Harsha.

**Comment by shmikkil** [comment] 2021-06-05 16:46
We are able to reproduce this again despite making all the necessary
changes on both the router and the nodes that are on diff. platforms -
Windows & Linux. The sessions goes into "reserved" after a few hours of
getting the grid up and running...

[image: image.png]

**Comment by diemol** [comment] 2021-06-05 19:13
What you describe sounds like a complete different issue from the initial one. This "reserved" state only happens when you use https? What happens if you don't use https?

Also, how can we reproduce this issue? Narrative descriptions are not enough because they leave room for lots of assumptions.

**Comment by shmikkil** [comment] 2021-06-06 15:23
Understood, Diego! Once we applied the SSL certs, we haven’t tried it again
without it. The beta-4 seem to have initially resolved the issue over
sessions falling into reserved state by assigning sessionIDs right away.
After a grid’s been setup for a few hours however, the new sessions get
assigned with reserved status and the remaining ones stay in queue with no
tests running at all.

We have a hybrid setup were the nodes were setup on various machines (Linux
& windows at the moment with the possibility of adding Mac) in one network
zone while router and remaining components setup done on a Linux box in
another zone. We are using default timeouts from the config files generated
from —config-help argument. I can provide detailed info along with all the
config files after removing some corporate data.

Also, wondering if we can pull you into a call and see how things go? Thank
You!

Best Regards,
Harsha.

**Comment by diemol** [comment] 2021-06-07 08:44
Yes, could you please create a new issue with enough details to reproduce it? From what you describe, it seems that using ssl/https is not related to the issue.

**Comment by shmikkil** [comment] 2021-06-07 14:56
Yes, Diego! Will do shortly...What we noticed is that the eventbus stops
working after a few hours and the whole grid gets unstable and we could no
longer run the tests with the router not being able to fetch the nodes.
