### ISSUE TITLE
Command key modifier doesn't work on Mac OS

### ISSUE THREAD

**Issue by sumproxy** [SeleniumHQ/selenium#1290] opened 2015-11-20 09:02 UTC
I use selenium-webdriver (2.48.1) through watir webdriver.
Sending command key to browser together with for example 'f' key does nothing.

**Comment by lukeis** [comment] 2015-11-20 15:12
Can you provide a reproducible test case, with a page that does something with command+f

If you are expecting this to open the browser's "find" dialog, this is not possible with the project's Firefox driver. It may be possible with the driver provided by Mozilla. 

I'm assuming Firefox, but you don't mention any browser. 

Closing the issue for now until something reproducible is provided.

**Closed by lukeis** 2015-11-20 15:12 UTC

**Comment by sumproxy** [comment] 2015-11-20 17:38
I actually used chrome.
```ruby
driver.action.send_keys [:command, 'h']
```
is supposed to hide the window but does nothing

**Comment by lukeis** [comment] 2015-11-20 17:54
for chromedriver issues, please log them with the chromedriver project:
https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by titusfortner** [comment] 2015-11-20 18:03
That's this bug here: https://bugs.chromium.org/p/chromedriver/issues/detail?id=30

**Comment by sumproxy** [comment] 2015-11-20 18:04
I tried it with firfox - same story.

**Comment by lukeis** [comment] 2015-11-20 18:28
as I mentioned before, we won't be fixing this in the SeleniumHQ firefox driver, but you might be able to suggest the 'marionette' implementation by Mozilla to fix this -
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

**Comment by lukeis** [comment] 2015-11-20 18:28
(assuming this doesn't work with marionette... i haven't tried)

**Comment by sumproxy** [comment] 2015-11-20 18:39
Ok, will try my luck with @titusfortner's advice

**Comment by titusfortner** [comment] 2015-11-20 19:38
It doesn't work with marionette because interactions class isn't implemented yet.
It does not work on Safari or chrome on a Mac, but I can successfully do command 'a' and command 'x' in Firefox on Mac, so I know Firefox supports sending the key combinations at least.
