### ISSUE TITLE
[🐛 Bug]: ChromeDriverService.CreateDefaultService() + service.Start() results in ArgumentNullException

### ISSUE THREAD

**Issue by drauch** [SeleniumHQ/selenium#12805] opened 2023-09-21 12:08 UTC
### What happened?

Executing the following in a .NET 7 environment:

```
var service = ChromeDriverService.CreateDefaultService();
service.Start();
```

throws:

```
System.ArgumentNullException : Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at OpenQA.Selenium.DriverService.Start()
```

### How can we reproduce the issue?

```shell
See above.
```

### Relevant log output

```shell
-
```

### Operating System

Windows 10

### Selenium version

4.12.x

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 117.0.5938.62

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment] 2023-09-22 15:48
Diego fixed this in Java recently
https://github.com/SeleniumHQ/selenium/commit/5bce8d952c5e18454dc9face3e7e3489075adeab

Need to do something similar here.

**Comment by nvborisenko** [comment] 2023-10-19 16:15
Reproduced it with `4.14.1`.

**Comment by nvborisenko** [comment] 2023-10-19 18:43
Fixed by https://github.com/SeleniumHQ/selenium/commit/6f97b8da62bb502514b9bb641a0374e3bff745e5

**Comment by titusfortner** [comment] 2023-10-19 18:43
so, uhh, looks like I didn't assign the result to `driverServicePath` 🤦 
https://github.com/SeleniumHQ/selenium/pull/12816/files#diff-c38089621d41671b4719164b262303e275d4a4a442125fd9d4ea61eeca855c2bR267

**Closed as completed by nvborisenko** 2023-10-19 18:43 UTC
Labels: C-dotnet, I-defect, A-needs-triaging

**Comment by nvborisenko** [comment] 2023-10-19 18:46
Don't blame yourself, I approved your change.
