### ISSUE TITLE
Unable to open Mozilla Firefox using Gecko driver

### ISSUE THREAD

**Issue by Jayshree23** [SeleniumHQ/selenium#5170] opened 2017-12-05 11:07 UTC
Steps to Reproduce:-

    1.Download all selenium Jars for selenium 3.8.0
    2.use System.setProperty("webdriver.gecko.driver","path of gecko exe files");
    3.WebDriver driver=new FirefoxDriver(); //not getting any option to import Firefox and throws a    compilation error.

**Actual Result:**- Firefox browser should be opened.

**Expected Result**:- Compilation error at step 3

**Comment by barancev** [comment] 2017-12-05 11:25
Duplicate of #5169

**Closed by barancev** 2017-12-05 11:25 UTC
