### ISSUE TITLE
[🐛 Bug]: Unable to create RemoteWebdriver session after setting the browserVersion in selenium 4.11.0

### ISSUE THREAD

**Issue by cnbcbala** [SeleniumHQ/selenium#12530] opened 2023-08-10 14:19 UTC
### What happened?

I am trying to create a RemoteWebdriver session on Specific version of Chrome browser by setting the chrome Options in Selenium 4.11.0

To start the node, I am adding this parameter: --selenium-manager true

### How can we reproduce the issue?

```shell
ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.setCapability("browserName", "chrome");
String browserVersion = (System.getProperty("browserVersion");
chromeOptions.setCapability(CapabilityType.ACCEPT_INSECURE_CERTS, true);
chromeOptions.addArguments("--remote-allow-origins=*");
chromeOptions.setCapability(ChromeOptions.CAPABILITY, chromeOptions);
chromeOptions.setBrowserVersion(browserVersion);

URL url = new URL(System.getProperty("remoteurl"));
				chromeOptions.setCapability(CapabilityType.UNHANDLED_PROMPT_BEHAVIOUR, UnexpectedAlertBehaviour.IGNORE);

driver = new RemoteWebDriver(url, chromeOptions);
```

### Relevant log output

```shell
[DEBUG] 2023-08-09 20:52:48.349 - Framework : Entered initalizeDriver Method
[INFO ] 2023-08-09 20:52:48.350 - SeleniumLogs folder is already created
[DEBUG] 2023-08-09 20:52:48.357 - Framework : The execution is triggered on http://100.116.194.65:4444/wd/hub grid
[DEBUG] 2023-08-09 20:52:48.357 - Framework : The execution is triggered on chrome
Aug 09, 2023 8:52:48 PM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFO: Using OpenTelemetry for tracing
java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.remote.RemoteWebDriver.getCapabilities()" because the return value of driver is null
```

### Operating System

Windows 10

### Selenium version

Java 4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 115

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 115

### Are you using Selenium Grid?

4.11.0

**Comment by titusfortner** [comment] 2023-08-10 16:48
I'm not an expert on the grid, but `--selenium-manager true` executes when the nodes are starting up (before there is browser version information). I suspect that when you pass in `browserVersion` to the hub, it is looking for a node that matches that version and none of them do, so it doesn't find anything.

Again, not the expert, but I think if you specify a stereotype with `--driver-configuration` (https://www.selenium.dev/documentation/grid/configuration/cli_options/#node) using a specific version that Selenium Manager will download it for you? But not certain.

**Comment by cnbcbala** [comment] 2023-08-10 17:02
Thanks for your prompt response @titusfortner . I am trying to pass the available Chrome version only. As soon as I add the below line, the remotedriver is not working for any available version and unavailable version too

chromeOptions.setBrowserVersion(browserVersion);

However, it works fine on my local with available Chrome version(115) and CfT version(114, 116) too. I have Chrome version 115 on my local. The issue is only with RemoteWebdriver session.

Anyway, I will try your suggestion as well

**Comment by titusfortner** [comment] 2023-08-10 18:54
What version of Chrome is on the remote machine?

People who know grid (@diemol @krmahadevan @joerg1985) — Does browserVersion get ignored for matching purposes, or does info about version get stored during node startup, or does it require a stereotype?

**Comment by cnbcbala** [comment] 2023-08-10 18:58
> What version of Chrome is on the remote machine? @diemol is grid forgiving about what goes in the browserVersion capability, or does it need to have a matching stereotype?

Remote machine has Chrome Version of 115
As I said, If I include below line for RemoteWebDriver, it is unable to create a session at all though the Chrome version is same on the Remote machine. But, the same line of code works fine on local webdriver

chromeOptions.setBrowserVersion("115");

**Comment by diemol** [comment] 2023-08-10 19:03
Grid finds a Node based on matching the values sent as capabilities. Typically that is platformName, browserName, and browserVersion. 

In this case, if you don't configure the browser version in the Node stereotype, the Grid won't match what you are asking. Check the link Titus shared.

**Comment by titusfortner** [comment] 2023-08-10 19:21
Things that could be interesting:

1. Ignore browserVersion for matching if Selenium Manager is enabled because node will be able to get whatever it needs to during run time (I think?)
2. Have Selenium Manager return the browserVersion as well as browser location and automatically add those to the default stereotype without the user needing to do so. Not sure how this works with the various Beta/Dev/Canary/Nightly that could be on the machine. Do we check for these by default?

**Comment by titusfortner** [comment] 2023-08-10 19:22
I think there's a real feature here, even if it is low priority and I don't know exactly what it is, so I'm reopening for us to decide and track elsewhere. 😆

**Comment by diemol** [comment] 2023-08-10 19:28
I'm afraid I have to disagree because Grid is a testing infrastructure piece that relies on predetermined configuration. Ignoring parts of the matching will break backward compatibility big time. Why not configure properly the stereotype and let Selenium Manager set up the browser if it is not present? What is the real feature that does not exist now with a line of configuration?

**Comment by titusfortner** [comment] 2023-08-10 19:47
Why should we have to specify a browserVersion if *any browser version can now be dynamically added to the node?

**Comment by titusfortner** [comment] 2023-08-10 19:50
I'm not super familiar with stereotypes. Do you put all browserVersions into the stereotype? Is there a wildcard?

Grid as Infrastructure makes sense when it has to be static, things can be dynamic now, and that's a good thing, we should figure out how to better support it.

**Comment by Kananss** [comment] 2023-08-14 09:27
Selenium v4.11.0 has been released on 31-Jul23. This version can do the driver management automatically even for chrome browser v115, without setting the PATH(System.setProperty).
upgrade to Selenium v4.11.0 and use the simple code as below:

public static void main(String[] args)  {

    WebDriver driver = new ChromeDriver();
    driver.manage().window().maximize();
    driver.get("https://selenium.dev");

}

**Comment by soumyajit0905** [comment] 2023-08-26 08:22
@cnbcbala 
Can you please share your complete code? I would like to check if I am able to reproduce this issue.

**Comment by titusfortner** [comment] 2023-08-26 17:40
Diego, does this ignore `browserVersion` & `platformName` when matching, or does it fail if those values are passed in and not listed in the stereotype? 
```
[node]
detect-drivers = false
[[node.driver-configuration]]
max-sessions = 100
display-name = "Firefoxxy"
stereotype = "{\"browserName\": \"firefox\"}"
```

**Comment by diemol** [comment] 2023-08-28 11:53
I know that Selenium Manager can download these browsers now. But usually, you want to avoid having an infrastructure that behaves dynamically because things get hard to control. Which browsers are installed where? What if I have a machine I only want to use for a given browser version but suddenly is getting used much more because other browser versions are popping up dynamically? Grid Nodes usually get configured before being used. Most of the time, you want to avoid your whole Node fleet dynamically downloading a bunch of binaries (sometimes the network where the Nodes have network restrictions or incoming traffic quotas). 

The matching code is done by the [SlotMatcher](https://github.com/SeleniumHQ/selenium/blob/43eb1e5477c9ef30bf6e2097ef984dec3f25077f/java/src/org/openqa/selenium/grid/data/DefaultSlotMatcher.java#L55). In short; the matcher looks for a match for the key-value pars the user sends. For example, if you send `browserName=chrome` and `browserVersion=115` in the capabilities, then a Node must have a stereotype with both keys set with the same value (`platformName` won't be matched here).

**Comment by titusfortner** [comment] 2023-08-28 12:38
But what if a user doesn't care? 
I would prefer not to manually update versions in a node every browser release. 

We could either support a wildcard in the stereotype, or we can allow selenium manager to get all available versions and report them? 

First looks pretty easy and opt in.

**Comment by diemol** [comment] 2023-08-28 12:50
Of course, there is always a use case that can fit that idea. For now, this is different from the general use case. 

This is not what should be implemented, and the main reason is that infrastructure needs to be predictable. I believe this could be implemented in the future, but I would really wait to see a large group of users.

Again, this is my opinion, which is not counting much these days for Grid.

**Comment by jrod567** [comment] 2023-09-11 18:26
FWIW - I'm with Titus on this issue.  I surfaced here with the thought that selenium-manager would manage the requested driver version remotely, based on the supplied BrowserVersion, similar to the way it's done locally.  +1 on a future feature here.

**Comment by titusfortner** [comment] 2023-09-11 18:44
Diego comes from a more infrastructure background where the most important thing is known/consistent/reproducible settings. Something changing dynamically can break things unexpectedly and that can't happen in a production environment where people are depending on results. With that as a priority, his position makes sense and is entirely valid. Diego is also concerned about feature creep and maintainability for things like this, which is also valid.

My perspective is that the infrastructure paradigm is only one way of looking at it, and not everyone needs it to be locked down. I think if we can find a way to provide an opt-in way to do this that is obvious and maintainable, we should do it. But this code isn't my area of expertise.

I think what is supported right now is you can create a stereotype with browserVersion "stable" and it should always use the latest dynamically.

**Comment by cnbcbala** [comment] 2023-09-28 21:58
@titusfortner Thank you for your thoughts and continuous support. Quick question here is, if I start the node with below config and does not have the latest chromedriver on node machine, will selenium-manager download the corresponding stable chromedriver version on node machine?

TOML file:
[node]
detect-drivers = true
grid-url = "http://myhost:4444"

[[node.driver-configuration]]
display-name = "Chrome"
stereotype = "{\"browserName\": \"chrome\", \"browserVersion\": \"stable\", \"platformName\": \"MAC\"}"

[events]
publish = "tcp://myhost:4442"
subscribe = "tcp://myhost:4443"


Node command:
java -jar selenium-server-4.11.0.jar node --config nodeConfig.toml --selenium-manager true

**Comment by titusfortner** [comment] 2023-09-29 12:10
I think so? We've fixed a lot of bugs in the past 2 releases, though, so I recommend 4.13

**Comment by jrod567** [comment] 2023-09-29 13:18
Yes, it should.  Based on that toml, you'll have two Chrome driver configs.  Not passing browserVersion will download the latest chrome driver necessary on the node machine; passing in browserVersion of stable would grab whatever the stable tag is tied to.  That's my experience on 4.12.1.  Have not tried 4.13 just yet.

**Comment by titusfortner** [comment] 2023-09-29 13:53
Without passing `browserVersion`, though it will always use the installed version of the browser.

If you use `"stable"` and the browser on the system is no longer the stable version, Selenium will download the latest stable Chrome for Testing and use that instead of what was pre-installed.

**Comment by titusfortner** [comment] 2023-11-06 12:23
Ok, in next version, "stable" can be used without needing a stereotype, which should be good enough to close this issue.

**Closed as completed by titusfortner** 2023-11-06 12:23 UTC
Labels: I-enhancement
