### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'executable_path'

### ISSUE THREAD

**Issue by jasonyun** [SeleniumHQ/selenium#8128] opened 2020-03-23 00:15 UTC
## 🐛 Bug Report

my code：
from selenium import webdriver

driver = webdriver.Ie(executable_path='IEDriverServer.exe')
driver.get('http://www.baidu.com')
driver.switch_to.new_window('tab')
handles = driver.window_handles
driver.switch_to.window(handles[-1])
driver.get('http://www.google.com')

## To Reproduce

Traceback (most recent call last):
  File "e:\Dropbox\17.Develop\2.Code\08.网络\selenium\selenium01.py", line 3, in <module>
    driver = webdriver.Ie(executable_path='IEDriverServer.exe')
  File "E:\Dropbox\17.Develop\2.Code\08.网络\selenium\env\lib\site-packages\selenium\webdriver\ie\webdriver.py", line 91, in __init__
    service = Service()
TypeError: __init__() missing 1 required positional argument: 'executable_path'

## Environment

OS: 
Browser:  IE
Browser version: 11
Browser Driver version: 
Language Bindings version:  python 3.8.1
Selenium Grid version (if applicable): selenium-4.0.0a1

**Comment by AutomatedTester** [comment] 2020-03-27 13:07
Duplicate of #7749

**Closed by AutomatedTester** 2020-03-27 13:07 UTC
Labels: C-py
