### ISSUE TITLE
i am getting below error while working with selenium server standalone 2.53.0 ,mozila firefox 47.0 and windows 8 -64 bit..please provide soluion.it will great help for me

### ISSUE THREAD

**Issue by shubhangi5CTS** [SeleniumHQ/selenium#2308] opened 2016-06-17 11:58 UTC
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1466101976118,"updateDate":1466101976118,"applyBackgroundUpdates":1,"skinnable":true,"size":22006,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"47.0","maxVersion":"47.0"}],"targetPlatforms":[],"seen":true}
1466162425151	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1466162425156	DeferredSave.extensions.json	DEBUG	Save changes
1466162425156	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1466162425156	addons.xpi-utils	DEBUG	Updating add-on states
1466162425160	addons.xpi-utils	DEBUG	Writing add-ons list
1466162425181	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1466162425183	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1466162425183	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1466162425185	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1466162425187	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1466162425189	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1466162425265	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1466162425266	addons.manager	DEBUG	Provider finished startup: XPIProvider
1466162425266	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1466162425267	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1466162425267	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1466162425269	addons.manager	DEBUG	Starting provider: GMPProvider
1466162425288	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1466162425289	addons.manager	DEBUG	Provider finished startup: GMPProvider
1466162425289	addons.manager	DEBUG	Starting provider: PluginProvider
1466162425290	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1466162425291	addons.manager	DEBUG	Provider finished startup: PluginProvider
1466162425293	addons.manager	DEBUG	Completed startup sequence
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU (t=13.6323) [GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU (t=13.6323) |[1][GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU (t=13.6896) [GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU
1466162428413	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1466162428413	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1466162428414	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1466162430069	DeferredSave.extensions.json	DEBUG	Write succeeded
1466162430070	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1466162430070	DeferredSave.extensions.json	DEBUG	Starting timer
1466162430094	DeferredSave.extensions.json	DEBUG	Starting write
1466162430105	addons.repository	DEBUG	No addons.json found.
1466162430107	DeferredSave.addons.json	DEBUG	Save changes
1466162430114	DeferredSave.addons.json	DEBUG	Starting timer
1466162430465	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1466162430465	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1466162430466	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1466162430473	DeferredSave.addons.json	DEBUG	Starting write
1466162430633	DeferredSave.extensions.json	DEBUG	Write succeeded
1466162430839	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at FirstScript.main(FirstScript.java:9)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1466101976118,"updateDate":1466101976118,"applyBackgroundUpdates":1,"skinnable":true,"size":22006,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"47.0","maxVersion":"47.0"}],"targetPlatforms":[],"seen":true}
1466162425151	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1466162425156	DeferredSave.extensions.json	DEBUG	Save changes
1466162425156	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1466162425156	addons.xpi-utils	DEBUG	Updating add-on states
1466162425160	addons.xpi-utils	DEBUG	Writing add-ons list
1466162425181	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1466162425183	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1466162425183	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1466162425185	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1466162425187	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1466162425189	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1466162425265	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1466162425266	addons.manager	DEBUG	Provider finished startup: XPIProvider
1466162425266	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1466162425267	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1466162425267	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1466162425269	addons.manager	DEBUG	Starting provider: GMPProvider
1466162425288	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1466162425289	addons.manager	DEBUG	Provider finished startup: GMPProvider
1466162425289	addons.manager	DEBUG	Starting provider: PluginProvider
1466162425290	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1466162425291	addons.manager	DEBUG	Provider finished startup: PluginProvider
1466162425293	addons.manager	DEBUG	Completed startup sequence
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU (t=13.6323) [GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU (t=13.6323) |[1][GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU (t=13.6896) [GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU
1466162428413	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1466162428413	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1466162428414	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1466162430069	DeferredSave.extensions.json	DEBUG	Write succeeded
1466162430070	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1466162430070	DeferredSave.extensions.json	DEBUG	Starting timer
1466162430094	DeferredSave.extensions.json	DEBUG	Starting write
1466162430105	addons.repository	DEBUG	No addons.json found.
1466162430107	DeferredSave.addons.json	DEBUG	Save changes
1466162430114	DeferredSave.addons.json	DEBUG	Starting timer
1466162430465	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1466162430465	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1466162430466	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1466162430473	DeferredSave.addons.json	DEBUG	Starting write
1466162430633	DeferredSave.extensions.json	DEBUG	Write succeeded
1466162430839	DeferredSave.addons.json	DEBUG	Write succeeded

Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'Dell', ip: '192.168.1.109', os.name: 'Windows 8', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_91'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:124)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at FirstScript.main(FirstScript.java:9)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1466101976118,"updateDate":1466101976118,"applyBackgroundUpdates":1,"skinnable":true,"size":22006,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"47.0","maxVersion":"47.0"}],"targetPlatforms":[],"seen":true}
1466162425151	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1466162425156	DeferredSave.extensions.json	DEBUG	Save changes
1466162425156	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1466162425156	addons.xpi-utils	DEBUG	Updating add-on states
1466162425160	addons.xpi-utils	DEBUG	Writing add-ons list
1466162425181	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1466162425183	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1466162425183	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1466162425185	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1466162425187	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1466162425189	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1466162425265	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1466162425266	addons.manager	DEBUG	Provider finished startup: XPIProvider
1466162425266	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1466162425267	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1466162425267	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1466162425269	addons.manager	DEBUG	Starting provider: GMPProvider
1466162425288	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1466162425289	addons.manager	DEBUG	Provider finished startup: GMPProvider
1466162425289	addons.manager	DEBUG	Starting provider: PluginProvider
1466162425290	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1466162425291	addons.manager	DEBUG	Provider finished startup: PluginProvider
1466162425293	addons.manager	DEBUG	Completed startup sequence
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU (t=13.6323) [GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU (t=13.6323) |[1][GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU (t=13.6896) [GFX1-]: PossiblyBrokenSurfaceSharing_UnexpectedAMDGPU
1466162428413	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1466162428413	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1466162428414	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1466162430069	DeferredSave.extensions.json	DEBUG	Write succeeded
1466162430070	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1466162430070	DeferredSave.extensions.json	DEBUG	Starting timer
1466162430094	DeferredSave.extensions.json	DEBUG	Starting write
1466162430105	addons.repository	DEBUG	No addons.json found.
1466162430107	DeferredSave.addons.json	DEBUG	Save changes
1466162430114	DeferredSave.addons.json	DEBUG	Starting timer
1466162430465	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1466162430465	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1466162430466	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1466162430473	DeferredSave.addons.json	DEBUG	Starting write
1466162430633	DeferredSave.extensions.json	DEBUG	Write succeeded
1466162430839	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	... 7 more

**Comment by jimevans** [comment] 2016-06-17 13:16
Duplicate of #2110

**Closed by jimevans** 2016-06-17 13:16 UTC
