### ISSUE TITLE
[🐛 Bug]: Selenium 4 Node is not registering with Hub in same machine in windows 10

### ISSUE THREAD

**Issue by lakshminagandla** [SeleniumHQ/selenium#10750] opened 2022-06-09 04:43 UTC
### What happened?

When the user tried to launch the selenium 4 hub with selenium server version as 4.1.2 or 4.2.1. User is successfully able to launch the Hub without any issues.  

But something when the user tried to register the node with the Hub, the user keep on getting "sending registration event".

Hub launching: 
![image](https://user-images.githubusercontent.com/39691064/172764913-194785ed-649b-4913-b3c3-0746d6f0074f.png)

Node Lanching:
![image](https://user-images.githubusercontent.com/39691064/172765203-ca0c94de-24e2-4eaf-ae36-e93a7b769e7a.png)

Note: I have opened port number 5555 for recognition as well. 

Hence can anyone please provide the solution here. 

### How can we reproduce the issue?

```shell
1. Download the selenium server 4.1.2 or selenium standalone server 4.2.1 

2. Run the command: 
   ===============
   java -jar selenium-server-<version>.jar hub

3. Run the command:
   ===============
   java -jar selenium-server-<version>.jar node
```

### Relevant log output

```shell
D:\Grid 4>java -jar selenium-server-4.1.2.jar node
10:06:06.736 INFO [LogManager$RootLogger.log] - Using the system default encoding
10:06:06.736 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
10:06:07.238 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://0.0.0.0:4442 and tcp://0.0.0.0:4443
10:06:07.291 INFO [UnboundZmqEventBus.<init>] - Sockets created
10:06:08.294 INFO [UnboundZmqEventBus.<init>] - Event bus ready
10:06:09.245 INFO [NodeServer.createHandlers] - Reporting self as: http://192.168.1.35:5555
10:06:10.968 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
10:06:11.017 INFO [NodeOptions.discoverDrivers] - Discovered 2 driver(s)
10:06:11.050 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 8 times
10:06:11.050 INFO [NodeOptions.report] - Adding Firefox for {"browserName": "firefox"} 8 times
10:06:11.050 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative
10:06:12.676 INFO [NodeServer$1.start] - Starting registration process for node id 1707cdec-ae09-43c6-a813-f12545b9d42d
10:06:12.684 INFO [NodeServer.execute] - Started Selenium node 4.1.2 (revision 9a5a329c5a): http://192.168.1.35:5555
10:06:12.684 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:06:22.701 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:06:32.715 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:06:42.745 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:06:52.753 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:07:02.764 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:07:12.771 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:07:22.784 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:07:32.806 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:07:42.816 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:07:52.830 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:08:02.854 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:08:12.722 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
```

### Operating System

Windows 10

### Selenium version

4.1.2 or 4.2.1

### What are the browser(s) and version(s) where you see this issue?

NA

### What are the browser driver(s) and version(s) where you see this issue?

NA

### Are you using Selenium Grid?

4.1.2 or 4.2.1

**Comment by diemol** [comment] 2022-06-09 07:03
Can you please use the same version for both commands? Also, please enable log debugging to see where the issue happens.

**Comment by lakshminagandla** [comment] 2022-06-09 08:44
Hub: 

![image](https://user-images.githubusercontent.com/39691064/172804763-64f87dae-09c1-4004-ac66-dd33cb6ae343.png)


Node with structured logs:

```
D:\Grid 4>java -jar selenium-server-4.2.1.jar node --structured-logs true
14:13:14.313 INFO [LogManager$RootLogger.log] - Using the system default encoding
14:13:14.321 INFO [LogManager$RootLogger.log] - Using the system default encoding
{"class": "LogManager$RootLogger","log-level": "INFO","log-message": "Using the system default encoding","log-name": "","log-time-local": "2022-06-09T14:13:14.321+05:30","log-time-utc": "2022-06-09T08:43:14.321Z","method": "log"}
14:13:14.357 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
{"class": "OpenTelemetryTracer","log-level": "INFO","log-message": "Using OpenTelemetry for tracing","log-name": "org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer","log-time-local": "2022-06-09T14:13:14.357+05:30","log-time-utc": "2022-06-09T08:43:14.357Z","method": "createTracer"}
14:13:14.849 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://0.0.0.0:4442 and tcp://0.0.0.0:4443
{"class": "UnboundZmqEventBus","log-level": "INFO","log-message": "Connecting to tcp:\u002f\u002f0.0.0.0:4442 and tcp:\u002f\u002f0.0.0.0:4443","log-name": "org.openqa.selenium.events.EventBus","log-time-local": "2022-06-09T14:13:14.849+05:30","log-time-utc": "2022-06-09T08:43:14.849Z","method": "\u003cinit>"}
14:13:14.906 INFO [UnboundZmqEventBus.<init>] - Sockets created
{"class": "UnboundZmqEventBus","log-level": "INFO","log-message": "Sockets created","log-name": "org.openqa.selenium.events.EventBus","log-time-local": "2022-06-09T14:13:14.906+05:30","log-time-utc": "2022-06-09T08:43:14.906Z","method": "\u003cinit>"}
14:13:15.916 INFO [UnboundZmqEventBus.<init>] - Event bus ready
{"class": "UnboundZmqEventBus","log-level": "INFO","log-message": "Event bus ready","log-name": "org.openqa.selenium.events.EventBus","log-time-local": "2022-06-09T14:13:15.916+05:30","log-time-utc": "2022-06-09T08:43:15.916Z","method": "\u003cinit>"}
14:13:16.898 INFO [NodeServer.createHandlers] - Reporting self as: http://192.168.0.121:5555
{"class": "NodeServer","log-level": "INFO","log-message": "Reporting self as: http:\u002f\u002f192.168.0.121:5555","log-name": "org.openqa.selenium.grid.node.httpd.NodeServer","log-time-local": "2022-06-09T14:13:16.898+05:30","log-time-utc": "2022-06-09T08:43:16.898Z","method": "createHandlers"}
14:13:18.823 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
{"class": "NodeOptions","log-level": "INFO","log-message": "Detected {0} available processors","log-name": "org.openqa.selenium.grid.node.config.NodeOptions","log-time-local": "2022-06-09T14:13:18.823+05:30","log-time-utc": "2022-06-09T08:43:18.823Z","method": "getSessionFactories"}
14:13:18.874 INFO [NodeOptions.discoverDrivers] - Discovered 2 driver(s)
{"class": "NodeOptions","log-level": "INFO","log-message": "Discovered {0} driver(s)","log-name": "org.openqa.selenium.grid.node.config.NodeOptions","log-time-local": "2022-06-09T14:13:18.874+05:30","log-time-utc": "2022-06-09T08:43:18.874Z","method": "discoverDrivers"}
14:13:19.300 INFO [NodeOptions.report] - Adding Firefox for {"browserName": "firefox"} 8 times
{"class": "NodeOptions","log-level": "INFO","log-message": "Adding Firefox for {\"browserName\": \"firefox\"} 8 times","log-name": "org.openqa.selenium.grid.node.config.NodeOptions","log-time-local": "2022-06-09T14:13:19.3+05:30","log-time-utc": "2022-06-09T08:43:19.3Z","method": "report"}
14:13:19.300 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 8 times
{"class": "NodeOptions","log-level": "INFO","log-message": "Adding Chrome for {\"browserName\": \"chrome\"} 8 times","log-name": "org.openqa.selenium.grid.node.config.NodeOptions","log-time-local": "2022-06-09T14:13:19.3+05:30","log-time-utc": "2022-06-09T08:43:19.3Z","method": "report"}
14:13:19.316 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
{"class": "Node","log-level": "INFO","log-message": "Binding additional locator mechanisms: id, name, relative","log-name": "org.openqa.selenium.grid.node.Node","log-time-local": "2022-06-09T14:13:19.316+05:30","log-time-utc": "2022-06-09T08:43:19.316Z","method": "\u003cinit>"}
14:13:20.984 INFO [NodeServer$1.start] - Starting registration process for Node http://192.168.0.121:5555
{"class": "NodeServer$1","log-level": "INFO","log-message": "Starting registration process for Node http:\u002f\u002f192.168.0.121:5555","log-name": "org.openqa.selenium.grid.node.httpd.NodeServer","log-time-local": "2022-06-09T14:13:20.984+05:30","log-time-utc": "2022-06-09T08:43:20.984Z","method": "start"}
14:13:20.984 INFO [NodeServer.execute] - Started Selenium node 4.2.1 (revision ac4d0fdd4a): http://192.168.0.121:5555
{"class": "NodeServer","log-level": "INFO","log-message": "Started Selenium node 4.2.1 (revision ac4d0fdd4a): http:\u002f\u002f192.168.0.121:5555","log-name": "org.openqa.selenium.grid.node.httpd.NodeServer","log-time-local": "2022-06-09T14:13:20.984+05:30","log-time-utc": "2022-06-09T08:43:20.984Z","method": "execute"}
14:13:21.008 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
{"class": "NodeServer$1","log-level": "INFO","log-message": "Sending registration event...","log-name": "org.openqa.selenium.grid.node.httpd.NodeServer","log-time-local": "2022-06-09T14:13:21.008+05:30","log-time-utc": "2022-06-09T08:43:21.008Z","method": "lambda$start$1"}
14:13:31.028 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
{"class": "NodeServer$1","log-level": "INFO","log-message": "Sending registration event...","log-name": "org.openqa.selenium.grid.node.httpd.NodeServer","log-time-local": "2022-06-09T14:13:31.028+05:30","log-time-utc": "2022-06-09T08:43:31.028Z","method": "lambda$start$1"}
14:13:41.066 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
{"class": "NodeServer$1","log-level": "INFO","log-message": "Sending registration event...","log-name": "org.openqa.selenium.grid.node.httpd.NodeServer","log-time-local": "2022-06-09T14:13:41.066+05:30","log-time-utc": "2022-06-09T08:43:41.066Z","method": "lambda$start$1"}
14:13:51.084 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
{"class": "NodeServer$1","log-level": "INFO","log-message": "Sending registration event...","log-name": "org.openqa.selenium.grid.node.httpd.NodeServer","log-time-local": "2022-06-09T14:13:51.084+05:30","log-time-utc": "2022-06-09T08:43:51.084Z","method": "lambda$start$1"}
14:14:01.091 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
{"class": "NodeServer$1","log-level": "INFO","log-message": "Sending registration event...","log-name": "org.openqa.selenium.grid.node.httpd.NodeServer","log-time-local": "2022-06-09T14:14:01.091+05:30","log-time-utc": "2022-06-09T08:44:01.091Z","method": "lambda$start$1"}
14:14:11.108 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
{"class": "NodeServer$1","log-level": "INFO","log-message": "Sending registration event...","log-name": "org.openqa.selenium.grid.node.httpd.NodeServer","log-time-local": "2022-06-09T14:14:11.108+05:30","log-time-utc": "2022-06-09T08:44:11.108Z","method": "lambda$start$1"}
14:14:21.115 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
{"class": "NodeServer$1","log-level": "INFO","log-message": "Sending registration event...","log-name": "org.openqa.selenium.grid.node.httpd.NodeServer","log-time-local": "2022-06-09T14:14:21.115+05:30","log-time-utc": "2022-06-09T08:44:21.115Z","method": "lambda$start$1"}
```

**Comment by diemol** [comment] 2022-06-09 14:50
Please use `--log-level FINE`

**Comment by diemol** [comment] 2022-06-09 14:50
For the Hub

**Comment by manu141** [comment] 2022-06-09 15:05
@lakshminagandla I think you need to check all the ports are open we ran into this issue long back when one of the ports was not open and we requested to open and it started to work pls check all the ports
4442, 4443, 4444, and 5555 and (5556 only if you using multiple HUB-NODE concept like us)

**Comment by diemol** [comment] 2022-06-14 10:19
I believe @manu141 is right. I am not able to reproduce this issue. 

Hub
![image](https://user-images.githubusercontent.com/5992658/173554421-ff138a3e-c2f3-4e70-a411-03fa3dadc348.png)
Node
![image](https://user-images.githubusercontent.com/5992658/173554539-531bedac-fbc4-4b8d-bfcb-cf4fbb575cb7.png)

I'll close this issue and when fine logs are provided we can reopen.

**Closed as completed by diemol** 2022-06-14 10:19 UTC
Labels: B-grid, J-awaiting answer, C-java, I-defect
