### ISSUE TITLE
Issues with "moveToElement" with Firefox and "(new Actions(driver).click()" with Edge

### ISSUE THREAD

**Issue by Schwonsen** [SeleniumHQ/selenium#2773] opened 2016-09-14 14:10 UTC
## Meta -
OS:  Windows 10

Selenium Version:  3.0.0 beta, eclipse neon

Browser:  Firefox, Edge 

Hi,
my tests are working very good with chrome and the IE (very slow ;D ) but with the Edge and Firefox they didn´t work.

1. issue with Firefox:
i get this error message

> org.openqa.selenium.UnsupportedCommandException:
 POST /session/3feae85e-0261-411c-bd0e-35161792d53e/moveto did not match a known command (WARNING: The server did not provide any stacktrace information) 

`private static final String MENU_SELECTION = "Fahrzeugbörse";`

`System.setProperty("webdriver.gecko.driver", "mypath to/geckodriver.exe");`
`driver = new FirefoxDriver();`
`driver.get("http://www.unterberger.cc/de/");
`

`WebElement fb = driver.findElement(By.xpath(".//*[@title= '" + MENU_SELECTION + "']"));`

`// hover over menu entry, here triggers the exception`
`(new Actions(driver)).moveToElement(fb).moveToElement(fb).build().perform();`

On chrome, Edge and IE there are no problems with this code.

 -------
2. Issue with Edge

The hover over the Menu code from above works with Edge, but next the click on the submenu, throws this exception

> org.openqa.selenium.WebDriverException: Invalid argument (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 3 milliseconds
Build info: version: '3.0.0-beta3', revision: 'c7b525d', time: '2016-09-01 14:57:03 -0700'
System info: host: 'Design4', ip: '10.30.30.140', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.edge.EdgeDriver

	private static final String MENU_UNTERPUNKT = "Gebrauchtwagen";

`List<WebElement> listMenuCheck = driver.findElements(By.xpath(".//*[@id='model-link']"));`
		
		for (WebElement element : listMenuCheck) 
		{		
			if(element.getText().equalsIgnoreCase(MENU_UNTERPUNKT))
			{								
				Assert.assertEquals(element.getAttribute("title"), MENU_UNTERPUNKT);
				(new Actions(driver).click(element)).build().perform();
				break;
			}
		}

The element is visible but the click throws an exception.

**Comment by lukeis** [comment] 2016-09-14 15:23
the first issue is a duplicate of #2285

The issue with Edge, please log with Microsoft and be sure to include a way for them to reproduce the issue that includes a link to a page or recreation of a similar page (using something like jsfiddle.net ).

You can log EdgeDriver issues here:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

**Closed by lukeis** 2016-09-14 15:23 UTC
