### ISSUE TITLE
IEDriver cannot capture whole browser content in high DPI

### ISSUE THREAD

**Issue by shaka0919** [SeleniumHQ/selenium#5794] opened 2018-04-18 09:23 UTC
OS:Windows 10
Browser:IE11
Driver: 3.11
IEDriver: 3.11
my laptop resolution is 1920x1080. according to the DPI, the recommended scaling is 150%.
when I tried to get screenshot, the screenshot size is  1280x720(left-top part of the whole screen). even I set the window size with other values, the limitation is 1280x720(after set the driver in fullscreen and get screenshot).
but this problem never appear in chrome.
is there any solution for IE in high DPI environment?

**Comment by luke-hill** [comment] 2018-04-19 07:49
This is actually not an issue but a limitation of the Driver on IE10. There is a small amount of information that allows you to reproduce this. But essentially when testing in IE10, you must always have the screen scaling set to 100%. This can cause flaky issues such as elements not being clicked at the right position or even tests falling over randomly.

See this SHA for the line where it is mentioned (I admit it's one line in many)
https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver/_compare/0cf46848abd86f06876ee6ad0a41ee098c7327a0...74561c47d0300289087a9ea154164ffeb0e9b778

**Comment by GitSage** [comment] 2018-04-19 19:42
> is there any solution for IE in high DPI environment?

Here are some ideas.

- Best solution I've found is to get an external display with a lower DPI.
- Set your scaling to 100% even though 150% is recommended (everything will look small on your display)
- Run IE remotely. You can do this with a VPN or remote server (with remote desktop if you want to watch IE). Let me know if you need help figuring this out.

@luke-hill FYI the 100% scaling requirement is mentioned on the wiki page for [InternetExplorerDriver](https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver).

**Comment by luke-hill** [comment] 2018-04-20 08:08
@GitSage I know this. I linked to it?? As mentioned this is a limitation of running IE on Windows 10?

**Comment by GitSage** [comment] 2018-04-20 17:00
@luke-hill Yeah, you linked to the diff of the commit where the requirement was added to the wiki markdown. For convenience and clarity, I linked to the wiki page itself.

**Comment by jimevans** [comment] 2018-04-20 19:33
I'm going to close this issue as by design, or at least as a known limitation of the driver that won't be fixed.

**Closed by jimevans** 2018-04-20 19:33 UTC
Labels: D-IE
