### ISSUE TITLE
Javascript issue: Unable to clone node using execute_script:  selenium.common.exceptions.StaleElementReferenceException

### ISSUE THREAD

**Issue by Naumansh** [SeleniumHQ/selenium#7885] opened 2019-12-23 16:52 UTC
## 🐛 Bug Report

When we execute java script to clone node, stale element exception is always thrown. This issue is specific to this java script only while executing from execute script. This issue can be seen on web.

selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found

## To Reproduce

driver.get("https://www.google.com")
driver.execute_script("return arguments[0].cloneNode(true)", driver.findElement(rBy.name("q"));

## Environment

OS: OSX
Browser: Chrome
Browser version: 79
Browser Driver version: 79
Language Bindings version: java / python

**Comment by Naumansh** [comment] 2020-02-12 15:30
i wonder if i can get any response on this issue please.

**Comment by AutomatedTester** [comment] 2020-03-06 11:20
I have tried to replicate this and couldnt. closing this as working as intended

```
Python 3.7.5 (default, Nov  1 2019, 02:16:32)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> driver = webdriver.Firefox()
>>> driver.get("https://www.google.com")
>>> driver.execute_script("return arguments[0].cloneNode(true)", driver.find_element("name", "q"))
<selenium.webdriver.firefox.webelement.FirefoxWebElement (session="edc5b80c-2613-b248-9f5c-cbabda935794", element="53e388d4-2321-9f4c-bf9b-3bc4529b2a45")>
```

**Closed by AutomatedTester** 2020-03-06 11:20 UTC
Labels: needs-triaging

**Comment by Naumansh** [comment] 2020-03-06 15:03
@AutomatedTester i believe you missed out the browser information in the ticket. This issue is coming up on chrome and i see you executed on firefox. I will appreciate if you can give it a try on chrome to reproduce. Thanks.

**Comment by AutomatedTester** [comment] 2020-03-06 15:15
Oh yea, I see it now.

Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)

**Comment by Naumansh** [comment] 2020-03-06 15:33
@AutomatedTester gotcha. thanks man
