### ISSUE TITLE
3.5.2 Encoding problem

### ISSUE THREAD

**Issue by AlejandroKolio** [SeleniumHQ/selenium#4579] opened 2017-08-25 15:36 UTC
## Meta -
**OS:  Windows 7
Selenium Version:  3.5.2
IDE: IntelliJ IDEA 2017.2.2 Build #IC-172.3757.52, built on August 15, 2017
JRE: 1.8.0_131-b11 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation Windows 7 6.1
Browser: Internet Explorer 11** 
Browser Version:  11.0.9600.18015 
Version Update: 11.0.23

## Expected Behavior - 
getTitle() method suppose to properly get Title from page, however it refuses to read german language letters as an example  Meine Übersicht. Letter Ü cannot be recognzed so my tests falling.

## Actual Behavior -
Please check up the encoding, and fix getTitle method to read title properly.

**Comment by barancev** [comment] 2017-08-25 16:32
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by jimevans** [comment] 2017-08-25 17:38
Is this grid/remote? Might be a duplicate of #4462.

**Comment by barancev** [comment] 2017-08-29 15:38
Yes, it must be duplicate of #4462
Version 3.5.3 released that fixed encoding issue.

**Closed by barancev** 2017-08-29 15:38 UTC
Labels: R-awaiting answer

**Comment by AlejandroKolio** [comment] 2017-09-24 17:40
Issue has been fixed. Thank you
