### ISSUE TITLE
[🐛 Bug]: Machine is getting crashed after launching Selenium test case.

### ISSUE THREAD

**Issue by ms105325** [SeleniumHQ/selenium#13925] opened 2024-05-10 13:47 UTC
### What happened?

 Remote desktop is getting crashed after launching Selenium test case.
This is happening when test case is either debugged from visual studio or executed on selenium grid.
Facing this issue since last 20 days.

### How can we reproduce the issue?

```shell
Debug test cases which are using Nunit framework from visual studio.
Once Chrome Instance is created, RDP machine get freeze and user is kicked out of RDP.
```

### Relevant log output

```shell
RDP machine is crashed, no output log is present.
```

### Operating System

Windows 10

### Selenium version

4.14.0

### What are the browser(s) and version(s) where you see this issue?

Chrome-124.0.6367.201 and 123.

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver-124.0.6367.201

### Are you using Selenium Grid?

4.12.0

**Comment by diemol** [comment] 2024-05-10 13:56
What have you changed in your setting recently? What have you done to analyze the situation?

**Comment by ms105325** [comment] 2024-05-10 14:04
No setting were changed recently.
We have checked for the CPU utilization of RDP machine while launching Chrome instance, it is going up to 100% utilization. more than half of the utilization is taking up by chrome browser. Staying 100% utilization for more amount of time is making RDP machine not intractable and making it crash.

**Comment by diemol** [comment] 2024-05-10 14:06
That is what I imagined.

This is a duplicate of #13872

**Closed as not planned by diemol** 2024-05-10 14:06 UTC
Labels: J-awaiting answer, I-defect
