### ISSUE TITLE
How use javascript private proxy

### ISSUE THREAD

**Issue by 2byte** [SeleniumHQ/selenium#1025] opened 2015-09-11 10:31 UTC
```
var driver = new webdriver.Builder()
        .forBrowser('firefox')
        .withCapabilities(webdriver.Capabilities.firefox())
        .usingServer('http://localhost:4444/wd/hub')
        .setProxy(proxy.manual({http: 'username:pass@proxy:port' }))
        .build();
```

Not worked

**Comment by jleyba** [comment] 2015-09-11 16:35
Does it work with just `proxy.manual({http: 'proxy:port'})`? I'm not sure if the FirefoxDriver supports proxy auth.

**Comment by 2byte** [comment] 2015-09-12 08:19
just will work

**Comment by vinnitu** [comment] 2016-06-24 09:26
How to pass login and password?

**Comment by barancev** [comment] 2017-12-04 05:32
Duplicate of #1802

**Closed by barancev** 2017-12-04 05:32 UTC
Labels: C-nodejs
