### ISSUE TITLE
[🐛 Bug]: Second instance of IEDriverServer with attached Edge(IE mode) doesn't work properly

### ISSUE THREAD

**Issue by sargis-tovmasyan** [SeleniumHQ/selenium#10609] opened 2022-05-05 10:44 UTC
### What happened?

Opened the first instance of IEDriverServer attached to Edge, run some scripts... doesn't close the web driver/browser window,
Tried to open a second instance of IEDriverServer attached to Edge to run some scripts ... 
The second browser window hangs on the initial page and scripts are running on the first browser window ...

![image](https://user-images.githubusercontent.com/35834865/166906300-c13e9df9-ccdd-4dfa-ae4b-d59052244708.png)

Using .NET Selenium

### How can we reproduce the issue?

```shell
Steps to reproduce:
* Create program/script to automate Edge in IE mode using IEDriverServer
* Create InternetExplorerDriverService providing path to IEDriverServer
* Create InternetExplorerOptions and set this options:
  * AttachToEdgeChrome = true,
  * EdgeExecutablePath = "PATH_TO_MS_EDGE",
* Create IEDriverServer webdriver
* Run program/script twice!

Expected: Script should run on the newly opened browser window.
Actual: The new window hangs on the initial page of the web driver and scripts are running on the previously opened window.

Here is a little sample from my code:
`
            var ieService = InternetExplorerDriverService.CreateDefaultService(WEBDRIVER_DIRECTORY, WEBDRIVER_NAME);
            ieService.HideCommandPromptWindow = true;

            var ieOptions = new InternetExplorerOptions
            {
                Proxy = null,
                IntroduceInstabilityByIgnoringProtectedModeSettings = true,
                IgnoreZoomLevel = true,
                AttachToEdgeChrome = true,
                EdgeExecutablePath = "PATH_TO_MS_EDGE",
            };

            var webDriver = new InternetExplorerDriver(ieService, ieOptions, TimeSpan.FromMinutes(4));
            webDriver.Navigate().GoToUrl("bing.com");
`

```

### Relevant log output

```shell
'IEModeSAmple.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'IEModeSAmple.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\Sargis.Tovmasyan\source\repos\IEModeSAmple\IEModeSAmple\bin\Debug\IEModeSAmple.exe'. Symbols loaded.
'IEModeSAmple.exe' (CLR v4.0.30319: IEModeSAmple.exe): Loaded 'C:\Users\Sargis.Tovmasyan\source\repos\IEModeSAmple\IEModeSAmple\bin\Debug\WebDriver.dll'. 
'IEModeSAmple.exe' (CLR v4.0.30319: IEModeSAmple.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'IEModeSAmple.exe' (CLR v4.0.30319: IEModeSAmple.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'IEModeSAmple.exe' (CLR v4.0.30319: IEModeSAmple.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'IEModeSAmple.exe' (CLR v4.0.30319: IEModeSAmple.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'IEModeSAmple.exe' (CLR v4.0.30319: IEModeSAmple.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'IEModeSAmple.exe' (CLR v4.0.30319: IEModeSAmple.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'IEModeSAmple.exe' (CLR v4.0.30319: IEModeSAmple.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'IEModeSAmple.exe' (CLR v4.0.30319: IEModeSAmple.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'IEModeSAmple.exe' (CLR v4.0.30319: IEModeSAmple.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x29f8 has exited with code 0 (0x0).
The thread 0x63d8 has exited with code 0 (0x0).
The thread 0x58e0 has exited with code 0 (0x0).
The thread 0x1fe0 has exited with code 0 (0x0).
The thread 0x1db4 has exited with code 0 (0x0).
The thread 0x6854 has exited with code 0 (0x0).
The thread 0x6980 has exited with code 0 (0x0).
```

### Operating System

Windows 10 x64 21h2

### Selenium version

.NET 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Edge 101.0.1210.32

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer 4.0.0

### Are you using Selenium Grid?

4.0.0

**Comment by diemol** [comment] 2022-05-05 10:47
Duplicate of #10495

**Closed as completed by diemol** 2022-05-05 10:47 UTC
Labels: I-defect
