### ISSUE TITLE
Commands inside promise not working.

### ISSUE THREAD

**Issue by LaercioAsano** [SeleniumHQ/selenium#477] opened 2015-04-22 18:51 UTC
I seem to have found an issue while trying to use driver commands inside the "then" of a promise.
Easier to show than to explain. The gist below shows a case when this happens.

How to reproduce:
Clone: https://gist.github.com/LaercioAsano/c49f40835a95a12d5026
Run:
npm install
node .

Expected result: Open firefox, open google.com, close firefox.
Obtained result: Just open firefox.

I'm using Node v0.11.13, npm v1.4.9 and the latest selenium-webdriver from npm (although I tested with v2.44.0). Windows 7 x64.

**Comment by ddavison** [comment] 2015-04-22 18:56
this makes no sense.. please update your "Clone" part.

**Comment by LaercioAsano** [comment] 2015-04-22 18:57
Sorry. Updated.

**Comment by jleyba** [comment] 2015-04-22 23:39
Duplicate of #363

**Closed by jleyba** 2015-04-22 23:39 UTC
