### ISSUE TITLE
Unable to simulate typing of non printable character

### ISSUE THREAD

**Issue by AinslieCleverdon** [SeleniumHQ/selenium#5670] opened 2018-03-23 14:48 UTC
## Meta -
OS:  Windows Server 2012 R2 Standard
Selenium Version:  3.11.0
Browser:  Chrome
Browser Version:  65.0.3325.181 (Official Build) (64-bit)

## Expected Behavior -
I'm trying to simulate the input of a non printable character, specifically the [Group Separator Character](http://www.theasciicode.com.ar/ascii-control-characters/group-separator-ascii-code-29.html). I can manually accomplish this by holding 'Alt' and pressing '029' and thought I could get Selenium to do the same thing.

## Actual Behavior -
To confirm actual behaviour, I've got a web page that outputs the ASCII value of any input to console, I should see '29' but instead I see '0' (null character) entered three times.

## Steps to reproduce -
I've tried various combinations of keydown/up on alt/leftalt and sendkeys for the characters 0 2 and 9:
`new Actions(webDriver).KeyDown(Keys.Alt).SendKeys(Keys.NumberPad0 + Keys.NumberPad2 + Keys.NumberPad9).KeyUp(Keys.Alt).Build().Perform();`

`new Actions(webDriver).KeyDown(Keys.LeftAlt).SendKeys(Keys.NumberPad0).SendKeys(Keys.NumberPad2).SendKeys(Keys.NumberPad9).KeyUp(Keys.LeftAlt).Build().Perform();`

`new Actions(webDriver).KeyDown(Keys.Alt).SendKeys("029").KeyUp(Keys.Alt).Build().Perform();`

**Comment by jimevans** [comment] 2018-03-23 15:11
What happens if you do `element.SendKeys("\u001D");`? That should be the equivalent.

**Comment by AinslieCleverdon** [comment] 2018-03-23 16:48
@jimevans I've not got a particular element I'm trying to send the input to, instead there's some typescript that listens to onKeyPress event. So i tried this but from an Actions object (`new Actions(webDriver).SendKeys("\u001D").Perform();`) nothing is logged to the console at all, not even the null characters I was getting before.

**Comment by diemol** [comment] 2020-09-19 21:31
@AinslieCleverdon is this issue still valid with the most recent versions of the referenced components above?

**Comment by diemol** [comment] 2020-11-10 22:39
I close this for now since we did not get more information, however, if the issue is still valid with the most recent versions, please feel free to open a new issue.

**Closed by diemol** 2020-11-10 22:39 UTC
Labels: C-dotnet, R-awaiting answer
