### ISSUE TITLE
Selenium IDE does not work with Firefox version 55

### ISSUE THREAD

**Issue by AaronKlassenSSN** [SeleniumHQ/selenium#4435] opened 2017-08-10 12:23 UTC
## Meta -
OS:  Windows 7

Selenium Version:  IDE

Browser:  Firefox

Browser Version:  55.0

**Comment by barancev** [comment] 2017-08-10 12:25
Duplicate of #4406

**Closed by barancev** 2017-08-10 12:25 UTC

**Comment by skmvali** [comment] 2017-08-10 12:32
https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
