### ISSUE TITLE
Cannot resolve Selenium Java Bindings artifacts as modules (JPMS) in JDK 11

### ISSUE THREAD

**Issue by bavibm** [SeleniumHQ/selenium#7713] opened 2019-10-24 20:58 UTC
## 🐛 Bug Report
**UPDATE:** I just tried my reproducible in a Windows 10 VM with a fresh install of OpenJDK 11 (Red Hat build) and Maven 3.6.2 and I get the exact same issue. This doesn't seem to be a problem with my system and more so a compatibility issue with Java 11 JPMS and Selenium?

Firstly, this is going to sound like an issue with the IDE and tools I'm using but I'm only trying to illustrate my experience. Since the issue seems to be happening throughout all tools I'm assuming it's an issue with my system environment and install of Selenium Java bindings.

Whenever I add a `module-info.java` to my project (either handwritten or generated by IDE), my IDE and build tools are unable to resolve the Selenium dependencies as Java modules. When I require other library modules, e.g. Guice, I do not get module not found errors on those other libraries. When I remove my module-info.java, turning it into a standard Java application w/o JPMS I get no static analysis, compile time, or run time issues. Everything works.

Maven (at compile time), Eclipse, and VS Code (Java Extension Pack extensions enabled) all have issues resolving the Selenium artifacts as modules on my system. As a consequence I also get linter errors in my Java files. I've nuked my local maven repository and re-downloaded artifacts many times already, and I've ensured my environment variables point to the right JDK.

In my real project, I'm able to get Eclipse to run my application (but Maven doesn't compile) if I set my requires to
```
requires org.openqa.selenium.chrome;
requires org.openqa.selenium.core;
requires org.openqa.selenium.firefox;
requires org.openqa.selenium.ie;
requires org.openqa.selenium.remote;
requires selenium.support;
```
and Maven compiles (but Eclipse won't run and I get linter errors) if I set my requires to:
```
requires selenium.chrome.driver;
requires selenium.firefox.driver;
requires selenium.ie.driver;
requires selenium.remote.driver;
requires selenium.api;
requires selenium.support;
```
In both cases VS Code Java extensions just cannot resolve imports at all.

Removing require statements entirely results in the expected `type not accessible` errors when you have not defined a dependency in your module-info.java. For now, I can remove my module-info and just write my project as is but I'd really like to modularize it in the future.

To reproduce I've created a mini-project with a similar POM and app structure below.

## To Reproduce

Tested on Linux (Fedora 30) & Windows 10:
[https://github.com/bavibm/selenium-java-issue-reproducible](https://github.com/bavibm/selenium-java-issue-reproducible)

In this project, my issue is actually worse, Eclipse and Maven spit out errors no matter what my requires statements say.

## Expected behavior

All the modules should be resolvable and I should be able to package and run my program.

## Test script or set of commands reproducing this issue

```terminal
git clone https://github.com/bavibm/selenium-java-issue-reproducible
cd selenium-java-issue-reproducible/selenium-issue
mvn clean package
```

## Environment

OS: Linux, Fedora 30 & Windows 10
Browser: not applicable, program works when I remove module-info.java
Browser version: not applicable
Browser Driver version: not applicable
Language Bindings version: Java 3.14.59 and also tried it on 4.0.3-Alpha
Selenium Grid version (if applicable): not applicable

**Comment by neoXfire** [comment] 2020-06-25 17:44
Same issue here with Windows 10, JDK 9/11/14 and gradle build system (>=6.4 with new feature to build java modules).
How can we solve those error  : 

```
module not found: selenium.api
module not found: selenium.chrome.driver
module not found: selenium.firefox.driver
module not found: selenium.ie.driver
```

```
module not found: org.openqa.selenium.chrome
module not found: org.openqa.selenium.core
module not found: org.openqa.selenium.firefox
module not found: org.openqa.selenium.ie
```

**Comment by barancev** [comment] 2021-02-15 20:05
Can you please retest in Selenium 4.0-beta-1 (released today) if the issue is still actual.

**Comment by diemol** [comment] 2021-03-18 16:10
Closing as we did not get more information. However, if you are still facing this issue, feel free to comment or open a new one.

**Closed by diemol** 2021-03-18 16:10 UTC
Labels: C-java, R-awaiting answer
