### ISSUE TITLE
WebDriver cannot type the opening bracket. "(" symbol.

### ISSUE THREAD

**Issue by dmitryyu** [SeleniumHQ/selenium#1024] opened 2015-09-10 18:32 UTC
The issue has been raised based on the following comment:
https://code.google.com/p/selenium/issues/detail?id=1723#c35

Env: Java 1.8 FF 37, selenium 2.47.1.

The following test can reproduce the issue:
@Test
public void test1 ()  {
	WebDriver driver = new FirefoxDriver();
	driver.get("https://msdn.microsoft.com/ru-ru/library/windows/desktop/dn742442.aspx");
	WebElement customField = driver.findElement(By.xpath("//input"));
	customField.sendKeys("- ()-()-()-()-()-()-() -");
	Assert.assertEquals(customField.getAttribute("value"), "- ()-()-()-()-()-()-() -");
}

Result:
java.lang.AssertionError: 
Expected :- ()-()-()-()-()-()-() -
Actual   :- )-)-)-)-)-)-) -

**Comment by florentbr** [comment] 2015-09-10 18:46
Duplicate of #674

**Closed** 2015-09-10 18:51 UTC
