### ISSUE TITLE
[🐛 Bug]: Selenium Manager not directly usable in Ubuntu 22.04 due to missing library libssl.so.1.1

### ISSUE THREAD

**Issue by pabloFuente** [SeleniumHQ/selenium#11340] opened 2022-11-30 17:04 UTC
### What happened?

It seems that selenium-manager binary fails when trying to run it in a clean Ubuntu 22.04 machine. It is missing library **` libssl.so.1.1`**:

```console
root@ip-177-77-77-222:/home/ubuntu# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
```

```console
root@ip-177-77-77-222:/home/ubuntu# ./selenium-manager --help
./selenium-manager: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

After installing the missing library manually, it worked fine:

```console
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1.6_amd64.deb
sudo dpkg -i libssl1.1_1.1.1l-1ubuntu1.6_amd64.deb
```

```console
root@ip-172-31-21-204:/home/ubuntu# ./selenium-manager --help
selenium-manager 1.0.0-M1
Automated driver management for Selenium

Usage: selenium-manager [OPTIONS]
Options:
  -b, --browser <BROWSER>
          Browser name (chrome, firefox, or edge) [default: ]
  -d, --driver <DRIVER>
          Driver name (chromedriver, geckodriver, or msedgedriver) [default: ]
  -v, --driver-version <DRIVER_VERSION>
          Driver version (e.g., 106.0.5249.61, 0.31.0, etc.) [default: ]
  -B, --browser-version <BROWSER_VERSION>
          Major browser version (e.g., 105, 106, etc.) [default: ]
  -D, --debug
          Display DEBUG messages
  -T, --trace
          Display TRACE messages
  -c, --clear-cache
          Clear driver cache
  -h, --help
          Print help information
  -V, --version
          Print version information
```

I don't know if this is something expected, but I just find a little weird that Selenium Manager does not work out-of-the-box with the current LTS version of the most popular Linux distro.

### How can we reproduce the issue?

```shell
1) Initiate a clean Ubuntu 22.04 machine.
2) Run selenium-manager binary.
```

### Relevant log output

```shell
./selenium-manager: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

### Operating System

Ubuntu 22.04

### Selenium version

4.6.0

### What are the browser(s) and version(s) where you see this issue?

_Not relevant_

### What are the browser driver(s) and version(s) where you see this issue?

_Not relevant_

### Are you using Selenium Grid?

_Not relevant_

**Comment by titusfortner** [comment] 2022-11-30 18:34
duplicate of #11291

**Closed as completed by titusfortner** 2022-11-30 18:34 UTC
Labels: I-defect, A-needs-triaging
