### ISSUE TITLE
Unable to create RemoteWebDriver using FirefoxOptions

### ISSUE THREAD

**Issue by DimeOne** [SeleniumHQ/selenium#4613] opened 2017-08-31 13:58 UTC
## Meta -
OS:  
Windows 10
Selenium Version:  
3.5.1
Browser:  
Firefox
Selenium Binding:
.Net Binding 3.5.1
Browser Version:  
55 (64-bit)

## Expected Behavior -

I should be able to use the RemoteWebDriver without having to set the path of the binaries. The Browser should start and be controllable.

## Actual Behavior -

When trying to start a browser running with the grid ( docker containers linked with hub from selenium/ ). I am receiving exceptions. 

The first exception:
```
OpenQA.Selenium.WebDriverException: 'Cannot find Firefox binary in PATH or default install locations. Make sure Firefox is installed. OS appears to be: Vista'
```
-> When I am running a RemoteDriver, I should not have to set the filePath. This error is skipped, once the path has been added locally.

The second exception:
```
  SetUp : System.InvalidOperationException : Unable to find a matching set of capabilities
Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z'
System info: host: 'e172987874e9', ip: '172.17.0.13', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-4-amd64', java.version: '1.8.0_131'
Driver info: driver.version: unknown
remote stacktrace: stack backtrace:
   0:           0x5787ed - backtrace::backtrace::trace::h59229d13f6a8837d
   1:           0x578942 - backtrace::capture::Backtrace::new::h23089c033eded8f0
   2:           0x44bfd0 - geckodriver::marionette::MarionetteHandler::create_connection::h6f7058fccafe4367
   3:           0x425c32 - <webdriver::server::Dispatcher<T, U>>::run::h8f5348b8f5f7c053
   4:           0x40b22c - std::panicking::try::do_call::hb67c6fb6bcd96195
   5:           0x5dc20a - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
   6:           0x41b943 - <F as alloc::boxed::FnBox<A>>::call_box::h4100941edc372034
   7:           0x5d48a4 - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:650
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84 (InsecureCertificate)
   bei OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   bei OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bei OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   bei OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   bei OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
```

## Steps to reproduce -

Since the DesiredCapabilities.BROWSER() functions are obsolete, we switched to ChromeOptions / FirefoxOptions as recommended.

My docker-compose.yml for selenium hub and firefox+chrome in debug:
```
hub:
  image: selenium/hub:3.5
  restart: always
  ports:
    - "4444:4444"

chrome:
  image: selenium/node-chrome-debug:3.5
  ports:
    - "5900:5900"
  links:
    - hub

firefox:
  image: selenium/node-firefox-debug:3.5
  ports:
    - "5901:5900"
  links:
    - hub
```

Now create a new console application with .net which references the required selenium dlls and has following code executing:
```
  var driver = new RemoteWebDriver(new Uri("http://myhub:4444/wd/hub"), new FirefoxOptions());
```
or 
```
var options = new FirefoxOptions();
var driver = new RemoteWebDriver(new Uri("http://myhub:4444/wd/hub"), options.ToCapabilities());
```
Both are failing with the given exceptions, while the following still works:
```
var driver = new RemoteWebDriver(new Uri("http://myhub:4444/wd/hub"), DesiredCapabilities.Firefox());
```

The only difference I can see, is that the capabilities passed to the hub contains:
```
moz:firefoxOptions={binary=C:\Program Files\Mozilla Firefox\firefox.exe}}]
```

**Comment by barancev** [comment] 2017-08-31 14:08
Please retest with selenium server 3.5.3

**Comment by jimevans** [comment] 2017-08-31 14:10
Duplicate of #4498

**Closed by jimevans** 2017-08-31 14:10 UTC
Labels: C-dotnet, C-remote, D-firefox, R-awaiting answer

**Comment by DimeOne** [comment] 2017-08-31 14:12
Are there any dotnet bindings available for 3.5.3? Website still showing 3.5.1 for C#

**Comment by jimevans** [comment] 2017-08-31 14:18
@DimeOne The fix for this issue has not yet been publicly released. The "revision" field (the `z` portion of `x.y.z`) is not in sync between language bindings, and is not intended to be. If the fix for this issue is to be released before the next large release of Selenium (3.6), it will be in a version 3.5.2 of the .NET bindings. There are no official plans for such a release yet, and thus no time table for such a release. Thank you for the issue report.

**Comment by DimeOne** [comment] 2017-08-31 14:20
Thank you for your explanation.
