### ISSUE TITLE
The HTTP request to the remote WebDriver server for URL http://localhost:42607/session timed out after 60 seconds.

### ISSUE THREAD

**Issue by stam3333** [SeleniumHQ/selenium#9507] opened 2021-05-23 14:58 UTC
## 🐛 Bug Report

After running this simple code (c#)
        Process.Start("msedge.exe", "www.google.com" + "-remote-debugging-port=9222");
        EdgeOptions options = new EdgeOptions() { DebuggerAddress = "127.0.0.1:9222" };
        IWebDriver driver = new EdgeDriver( options );

appears error message:"The HTTP request to the remote WebDriver server for URL http://localhost:42607/session timed out after 60 seconds."

## To Reproduce

run the code above

## Expected behavior

I've developed it few days ago and it worked till today...

## Test script or set of commands reproducing this issue

        Process.Start("msedge.exe", "www.google.com" + "-remote-debugging-port=9222");
        EdgeOptions options = new EdgeOptions() { DebuggerAddress = "127.0.0.1:9222" };
        IWebDriver driver = new EdgeDriver( options );

## Environment

OS: Windows 10
Browser: Edge
Browser version: 89.0.774.45 (Official build) (64-bit)
Browser Driver version: Microsoft Edge Driver 89.0.774.45
Language Bindings version: c# 4.0.0-beta2

**Comment by jvanderwoude80** [comment] 2021-09-13 08:51
There is a lot of discussion about this online. It's been an issue for over years. I'm suddenly experiencing the same issue too on almost all of our Azure Devops nightly regression test. Weird thing is they run on different servers (with different configurations) on diferent environments, but on all of them the issue suddenly occurs (a lot more). Also with different versions of selenium, but all using ChromeDriver newest version (93.0.4577.63). I'm more and more suspecting it's ans issue with c# bindings in combination with the driver used, in this case the only thing in common is using they're using the newest ChromeDriver lately. Only thing working for me right now is increasing the time-out value when creating the webdriver: `ChromeDriver driver = new ChromeDriver(<path>, options, TimeSpan.FromMinutes(3));` 
But I don't find this a (satisfying) solution as it only fixes symptoms and not the root cause. Even worse, it means that some of the test now run for more than a minute longer (even if the test itself is only a couple of seconds). With the 2000+ tests we have that is quite a lot. 

So: if someone could really dig into this issue (don't know if it's the C# bindings or driver or combination) that would be greatly appreciated!!

http://jimevansmusic.blogspot.com/2012/11/net-bindings-whaddaymean-no-response.html
https://github.com/SeleniumHQ/selenium/issues/5457

**Comment by pujagani** [comment] 2021-09-17 05:40
> ## 🐛 Bug Report
> After running this simple code (c#)
> Process.Start("msedge.exe", "www.google.com" + "-remote-debugging-port=9222");
> EdgeOptions options = new EdgeOptions() { DebuggerAddress = "127.0.0.1:9222" };
> IWebDriver driver = new EdgeDriver( options );
> 
> appears error message:"The HTTP request to the remote WebDriver server for URL http://localhost:42607/session timed out after 60 seconds."
> 
I have attempted to reproduce it and was unable to reproduce it after multiple runs. I am running the code below : 
```
namespace SeleniumDotNetUnitTests
{
    public class RemoteDebuggerAddressTest
    {
        [Test]
        public void remoteDebuggerBrowserTest()
        {
            System.Diagnostics.Process.Start("/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge", "www.google.com" + " --remote-debugging-port=9222");
           
                EdgeOptions options = new EdgeOptions() {DebuggerAddress = "localhost:9222"};
                IWebDriver driver = new EdgeDriver("/path/to/webdriver", options);
                driver.Quit();
         }   
    }
}
```
The test below also passes on my end: 
namespace SeleniumDotNetUnitTests
{
    public class TimeoutTest
    {
        [Test]
        public void shouldNotTimeoutWhenBrowserIsCreated()
        {
            int count = 0;
           
            for (int i = 0; i < 500; i++)
            {
                try
                {
                    EdgeOptions options = new EdgeOptions();
                    options.AddArguments("headless");
                    EdgeDriver driver = new EdgeDriver("/path/to/webdriver", options);
                    driver.Navigate().GoToUrl("http://www.google.com");
                    driver.Quit();
                    Console.WriteLine("i");
                    count++;
                } catch (Exception e)
                {
                    Console.WriteLine("Exception: " + e.Message);
                }
            }

            Assert.AreEqual(500, count);
        }
         
    }
}

.csproj file contains the following packages: 

 ```
<ItemGroup>
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Include="Selenium.WebDriver" Version="4.0.0-beta2" />
  </ItemGroup>
```

OS: MacOS Big Sur 11.4
Browser: Edge
Browser version: 93.0.961.47 (Official build) (x86_64)
Browser Driver version: Microsoft Edge Driver 93.0.967.0
Language Bindings version: C# 4.0.0-beta2, C# RC-1 

Does the same error happen every time you run the code snippet you shared? or is it persistent? Can you please try the latest release RC-1 and provide feedback if the error still persists. Thank you!

**Comment by moirs** [comment] 2021-09-17 14:06
I was having similar issues to @jvanderwoude80 in that Azure DevOps builds that run our UI tests started to fail...after about a day of hacking around and searching on the web I just discovered a solution that worked for me. It was simply to add an addition ChromeOption when creating the ChromeDriver:

`options.AddArguments("--disable-gpu");`

Now all tests run on Azure build agent are running as expected.  I found above solution by digging around here:

[https://groups.google.com/g/chromedriver-users/c/COktL3U3zYk](url)
[https://groups.google.com/g/chromedriver-users/c/F6QoJkegYNc](url)

- Browser Chrome
- Browser Version 93.0.4577.82
- Selenium.WebDriver.ChromeDriver Version 93.0.4577.6300

**Comment by jvanderwoude80** [comment] 2021-09-17 15:04
@moirs Thanks, I will try that! Hope it helps. I was getting quite desperate, because almost all test runs fail now because one or more tests fail randomly with this error..

**Comment by diemol** [comment] 2021-09-21 07:40
Chrome 92 and 93 are know for having a few issues that get solved with `--disable-gpu`. It seems Chrome 94 won't need this flag.

However, this issue seems to be not related to Selenium, so I'll close it since we also did not get more info from the OP.

**Closed as completed by diemol** 2021-09-21 07:40 UTC
Labels: C-dotnet
