### ISSUE TITLE
Window not closed/quit

### ISSUE THREAD

**Issue by vebmaster** [SeleniumHQ/selenium#6978] opened 2019-02-28 08:31 UTC
## 🐛 Bug Report

Open the page and close the browser window.  
The page that I open for too long gives html (1-4 minutes), so it turns out timeout. The window does not close.

## To Reproduce
Run the script below

## Expected behavior

Browser window should close

## Test script or set of commands reproducing this issue

Webdriver: https://github.com/facebook/php-webdriver

```php
<?php

namespace Facebook\WebDriver;
use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\Exception\WebDriverException;

require_once('Selenium/vendor/autoload.php'); //Подключаем автолоадер классов

$host = 'http://localhost:4444/wd/hub'; // this is the default
$capabilities = DesiredCapabilities::chrome();
$driver = RemoteWebDriver::create($host, $capabilities, 5000, 30000);

try {
    $url_page = 'https://my.mos.ru/my/';
    $driver->navigate()->to($url_page);
    echo "Open OK \n";
} catch (WebDriverException $ex) {
    echo "1 WebDriverException! \n";
}

$driver->quit();
```

```
D:\opt\php\7.2\php.exe D:\home\NetBeansProjects\monitorLogin\1.php
1 WebDriverException! 
PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http DELETE to /session/4cc4f5f747d67c11305ca42e953e78e3

Operation timed out after 30000 milliseconds with 0 bytes received in D:\home\NetBeansProjects\monitorLogin\Selenium\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php:292
Stack trace:
#0 D:\home\NetBeansProjects\monitorLogin\Selenium\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(547): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#1 D:\home\NetBeansProjects\monitorLogin\Selenium\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(289): Facebook\WebDriver\Remote\RemoteWebDriver->execute('quit')
#2 D:\home\NetBeansProjects\monitorLogin\1.php(23): Facebook\WebDriver\Remote\RemoteWebDriver->quit()
#3 {main}
  thrown in D:\home\NetBeansProjects\monitorLogin\Selenium\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php on line 292

Fatal error: Uncaught Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http DELETE to /session/4cc4f5f747d67c11305ca42e953e78e3

Operation timed out after 30000 milliseconds with 0 bytes received in D:\home\NetBeansProjects\monitorLogin\Selenium\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php:292
Stack trace:
#0 D:\home\NetBeansProjects\monitorLogin\Selenium\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(547): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#1 D:\home\NetBeansProjects\monitorLogin\Selenium\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(289): Facebook\WebDriver\Remote\RemoteWebDriver->execute('quit')
#2 D:\home\NetBeansProjects\monitorLogin\1.php(23): Facebook\WebDriver\Remote\RemoteWebDriver->quit()
#3 {main}
  thrown in D:\home\NetBeansProjects\monitorLogin\Selenium\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php on line 292

Process finished with exit code 255
```

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 72.0.3626.119
Browser Driver version: ChromeDriver 2.46.628402
Language Bindings version: php 7.2.4
Selenium Grid version (if applicable): 3.141.59, revision: e82be7d358

**Comment by barancev** [comment] 2019-02-28 08:39
Please attach the log collected from the Selenium server (or logs from the hub and the node if you run Selenium Grid)

**Comment by barancev** [comment] 2019-02-28 08:42
I bet the driver was closed by the node after timeout. Use Selenium Server CLI options to tune timeouts.

**Comment by vebmaster** [comment] 2019-02-28 09:02
> Please attach the log collected from the Selenium server (or logs from the hub and the node if you run Selenium Grid)
```
11:58:31.181 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome"
}
11:58:31.181 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1) on port 19446
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
11:58:32.542 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
11:58:32.572 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session d5fc50a4d6ff103fdf051f6193ff018d (org.openqa.selenium.chrome.ChromeDriverService)
```

**Comment by vebmaster** [comment] 2019-02-28 10:02
Попробовал запустить вот так, эффект тот же
`java -Dwebdriver.chrome.driver=chromedriver.exe -jar selenium-server-standalone-3.141.59.jar -browserTimeout 180 -timeout 183 -sessionTimeout 183`

**Comment by barancev** [comment] 2019-03-29 15:04
It seems to be an issue in PHP binding, it must be closing the HTTP session to selenium server by timeout.

Try to report the issue to PHP binding bug tracker. I'll close the issue here, but don't hesitate to request reopening it if you have got a reproduction scenario with one of "official" bindings (C#, Java, JS, Python, Ruby)

**Closed by barancev** 2019-03-29 15:04 UTC
Labels: R-awaiting answer

**Comment by vebmaster** [comment] 2019-03-29 19:38
> Try to report the issue to PHP binding bug tracker.
А что за "PHP binding bug tracker.", можете ссылку дать на этот сервис? Спасибо.

**Comment by barancev** [comment] 2019-03-29 20:17
https://github.com/facebook/php-webdriver/issues
