### ISSUE TITLE
firefox browser hangs for downloading gmp addon, while running tests.

### ISSUE THREAD

**Issue by balrajHostAnalytics** [SeleniumHQ/selenium#5303] opened 2018-01-08 10:23 UTC
Firefox Version: 57.0.2

webdriver preferences:

FirefoxProfile profile = new FirefoxProfile();
			profile.setPreference("browser.download.lastDir", downloadFile);
			profile.setPreference("app.update.auto", false);
			profile.setPreference("extensions.update.enabled", false);
			profile.setPreference("app.update.service.enabled", false);
			profile.setPreference("app.update.auto", false);
			profile.setPreference("app.update.staging", false);
			profile.setPreference("app.update.silent", false);
			profile.setPreference("extensions.blocklist.enabled", false);
			profile.setPreference("media.gmp-manager.cert.requireBuiltIn",false);
			profile.setPreference("media.gmp-manager.cert.checkAttributes",false);
			profile.setPreference("media.gmp-provider.enabled",false);
			profile.setPreference("media.gmp-widevinecdm.enabled",false);
			profile.setPreference("media.gmp-widevinecdm.visible",false);
			profile.setPreference("media.gmp.trial-create.enabled",false);
			profile.setPreference("browser.download.dir", downloadFile);
			profile.setPreference("browser.safebrowsing.downloads.remote.enabled", false);
			profile.setPreference("browser.safebrowsing.provider.mozilla.gethashURL", "");
			profile.setPreference("browser.safebrowsing.provider.mozilla.updateURL", "");
			profile.setPreference("app.update.url", "");
			profile.setPreference("extensions.systemAddon.update.url", "");
			profile.setPreference("media.gmp-manager.url", "");

                       DesiredCapabilities capabs = DesiredCapabilities.firefox();
			capabs.setCapability("marionette", true);
                        capabs.setCapability(FirefoxDriver.PROFILE, profile);
			
			FirefoxOptions firefoxOptions=new FirefoxOptions().setProfile(profile);
			firefoxOptions.setCapability("marionette", true);
                        WebDriver driver= new FirefoxDriver(firefoxOptions));

firefox Log:

1515404964652	addons.productaddons	INFO	fetching config from: chrome://global/content/gmp-sources/openh264.json
1515404964655	addons.productaddons	INFO	fetching config from: chrome://global/content/gmp-sources/widevinecdm.json
1515404964656	addons.productaddons	INFO	found plugin: gmp-gmpopenh264
1515404964656	addons.productaddons	INFO	found plugin: gmp-widevinecdm
1515404965993	addons.productaddons	INFO	downloadXHR File download. status=200
1515404965999	addons.productaddons	INFO	Downloaded file will be saved to C:\Users\bdacha\AppData\Local\Temp\tmpaddon-1aec13
1515405089651	addons.manager	INFO	Skipping background update check
1515405114130	Marionette	DEBUG	Register listener.js for window 4294967322
1515405114664	Marionette	DEBUG	Register listener.js for window 8589934593
Unable to read VR Path Registry from C:\Users\bdacha\AppData\Local\openvr\openvrpaths.vrpath
[Child 12032, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 12032, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1515405282766	Marionette	DEBUG	Register listener.js for window 10737418241
Unable to read VR Path Registry from C:\Users\bdacha\AppData\Local\openvr\openvrpaths.vrpath
[Parent 20692, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\bdacha\AppData\Local\openvr\openvrpaths.vrpath
[Child 19824, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 19824, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1515405329671	DeferredSave.extensions.json	DEBUG	Save changes
1515405329671	DeferredSave.extensions.json	DEBUG	Starting timer
1515405329695	DeferredSave.extensions.json	DEBUG	Starting write
1515405329704	DeferredSave.extensions.json	DEBUG	Write succeeded
1515406743762	Marionette	DEBUG	Register listener.js for window 4294967325

**Comment by barancev** [comment] 2018-01-10 15:31
I can't see anything wrong in the log. And I can't reproduce the issue, the provided code works for me (Firefox 57, geckodriver 0.19)

Make sure you're using the latest geckodriver version and please describe in more details what you see and what's not working as expected.

Also increase log level
```
firefoxOptions.setLogLevel(FirefoxDriverLogLevel.DEBUG);
```
and attach the detailed log here.

**Comment by balrajHostAnalytics** [comment] 2018-01-10 15:57
Hi barancev,

Thanks for the quick response, firefox is trying to download gmp addon. My i know how to stop it getting downloaded. what is the need of gmp addon and is it required.

I am trying to run test by test, after few test it is downloading again and again.

thanks,
Balaraj

**Comment by barancev** [comment] 2018-01-11 05:03
What geckodriver version do you use? Please increase log level as explained above and attach the complete log here.

**Comment by barancev** [comment] 2018-01-11 05:08
Also note that for better performance and compatibility you can pass preferences like this:
```
FirefoxOptions firefoxOptions=new FirefoxOptions()
        .addPreference("browser.download.lastDir", downloadFile)
        .addPreference("app.update.auto", false)
        .addPreference("extensions.update.enabled", false)
        .addPreference("app.update.service.enabled", false)
        .addPreference("app.update.auto", false)
        .addPreference("app.update.staging", false)
        .addPreference("app.update.silent", false)
        .addPreference("extensions.blocklist.enabled", false)
        .addPreference("media.gmp-manager.cert.requireBuiltIn",false)
        .addPreference("media.gmp-manager.cert.checkAttributes",false)
        .addPreference("media.gmp-provider.enabled",false)
        .addPreference("media.gmp-widevinecdm.enabled",false)
        .addPreference("media.gmp-widevinecdm.visible",false)
        .addPreference("media.gmp.trial-create.enabled",false)
        .addPreference("browser.download.dir", downloadFile)
        .addPreference("browser.safebrowsing.downloads.remote.enabled", false)
        .addPreference("browser.safebrowsing.provider.mozilla.gethashURL", "")
        .addPreference("browser.safebrowsing.provider.mozilla.updateURL", "")
        .addPreference("app.update.url", "")
        .addPreference("extensions.systemAddon.update.url", "")
        .addPreference("media.gmp-manager.url", "");
WebDriver driver= new FirefoxDriver(firefoxOptions));
```
There is no need to create and pass a heavyweight FirefoxProfile object.

**Comment by HelloKitty404** [comment] 2018-02-16 15:04
Try disable this preference:
`media.gmp-gmpopenh264.autoupdate`

**Comment by barancev** [comment] 2018-03-13 07:24
@balrajHostAnalytics Does the hint in the previous comment help?

**Comment by barancev** [comment] 2018-04-05 19:35
Closing this issue, let's suppose the mentioned workaround helps.

**Closed by barancev** 2018-04-05 19:35 UTC
Labels: D-firefox, R-awaiting answer

**Comment by SubOptimal** [comment] 2018-05-11 08:25
Only to cnfirm. Setting the preference "media.gmp-gmpopenh264.autoupdate" to "false" stops Firefox from downloading the plugin.
