### ISSUE TITLE
invalid code lengths set while uploading file in remote server using protractor

### ISSUE THREAD

**Issue by raghavan85** [SeleniumHQ/selenium#729] opened 2015-07-02 21:05 UTC
Hi All,

I am using selenium webdriver version 2.45.1 and upload functionality is failing with error code  

Message:
    Failed: invalid code lengths set
  Stack:
    UnknownError: invalid code lengths set
        at Array.forEach (native)
    From: Task: WebElement.sendKeys()
        at Array.forEach (native)
        at Array.forEach (native)

code snippet:
  var fileToUpload = ('Doc1.docx'),
        absolutePath = path.resolve(__dirname, fileToUpload);

  var remote = require('../../../node_modules/protractor/node_modules/selenium-webdriver/remote');
  browser.setFileDetector(new remote.FileDetector);
  element(by.id('fileupload')).sendKeys(absolutePath);

Could someone suggest the fix? or workaround for this issue. Make a note, issue occurs only while running in remote and local runs it's perfectly alright. 

Thanks for your help in advance.

**Comment by lukeis** [comment] 2015-07-03 00:05
duplicate of #640

**Closed by lukeis** 2015-07-03 00:05 UTC
