### ISSUE TITLE
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

### ISSUE THREAD

**Issue by rajyasree** [SeleniumHQ/selenium#2677] opened 2016-08-28 17:01 UTC
## Meta -
OS:  Wndows 10
Selenium Version:  selenium_server_standalone_3.0.0-beta2.jar
Browser:  Firefox 48.0.2 64bit

## Expected Behavior -
Launch the Firefox browser while running from Selenium webdriver.

## Actual Behavior -
> org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
> Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700'
> System info: host: 'sattiieshh-PC', ip: '192.168.29.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_73'
> Driver info: driver.version: FirefoxDriver
> 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:670)
> 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:247)
> 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:232)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:220)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:215)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:124)
> 	at com.rajyasree.zenphoto.ZenPhotoLogin.setUp(ZenPhotoLogin.java:36)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
> 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
> 	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) 
> 

## Steps to reproduce -

I have tried to connect to a website and lauch the Firefox driver.But I got the below error

> Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console

So I used the new port in Firefox profile as 7056 and tried to relaunch.

Please find my code here with:

```
public void setUp() throws Exception {
		FirefoxProfile p = new FirefoxProfile();
		p.setPreference("webdriver_firefox_port", 7056);

		System.setProperty("webdriver.gecko.driver", "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe");

		driver = new FirefoxDriver(p);
		baseUrl = "http://www.google.com/";
		driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
	}

```
This gave me the above error. Please help.

I have even tried to disable firewall for Firefox on TCP. But the issue still persists.

**Comment by titusfortner** [comment] 2016-08-28 17:53
I suspect this is a duplicate of #2672 & geckodriver is not in your PATH.

**Comment by lukeis** [comment] 2016-08-29 18:13
you are setting the 'webdriver.gecko.driver' to the firefox binary... you need to set it to geckodriver, which you can download here:
https://github.com/mozilla/geckodriver/releases

**Closed by lukeis** 2016-08-29 18:13 UTC
