### ISSUE TITLE
[🐛 Bug]: Server Timeout?

### ISSUE THREAD

**Issue by spy653** [SeleniumHQ/selenium#11193] opened 2022-10-28 19:43 UTC
### What happened?

Browser opens successfully, program execution does not continue, eventually browser closes and program crashes.

The browser instance works fine during manual operation but the application cannot connect.

### How can we reproduce the issue?

```shell
Unsure, I have ran into the issue on 2 separate machines, running ubuntu 20.04 and 22.04.
Both with clean dotnet6 templates. I reinstalled chromium through snap and apt, no effect.
```

### Relevant log output

```shell
/home/spy/RiderProjects/ConsoleApp1/ConsoleApp1/bin/Debug/net6.0/ConsoleApp1
Starting ChromeDriver 107.0.5304.62 (1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}) on port 33077
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Unhandled exception. OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:33077/session timed out after 60 seconds.
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor()
   at Program.<Main>$(String[] args) in /home/spy/RiderProjects/ConsoleApp1/ConsoleApp1/Program.cs:line 2
```

### Operating System

Ubuntu 22.04

### Selenium version

C# 4.5.1

### What are the browser(s) and version(s) where you see this issue?

Chromium 106

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 106.0.5249.119

**Comment by spy653** [comment] 2022-10-28 19:48
For reference, even this blank project fails.

```
new WebDriverManager.DriverManager().SetUpDriver(new WebDriverManager.DriverConfigs.Impl.ChromeConfig());
new OpenQA.Selenium.Chrome.ChromeDriver();

Console.WriteLine("Hello, World!");
```

**Comment by titusfortner** [comment] 2022-10-28 21:36
Snap has its own chromedriver, which actually complicates things quite a bit.

To rule out issues with the driver manager, please make sure your browser & driver versions match and hard code the location of the driver.

https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/?language=csharp#3-hard-coded-location

**Comment by spy653** [comment] 2022-10-28 22:07
```
 spy  ~  RiderProjects  ConsoleApp1  chromium --version
Chromium 106.0.5249.119 snap
```

[I downloaded 106 fresh just to be sure,](https://chromedriver.chromium.org/downloads) and hard coded its location, I was then given the following:
```
Unhandled exception. System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/home/spy/RiderProjects/ConsoleApp1/ConsoleApp1/chromedriver' with working directory '/home/spy/RiderProjects/ConsoleApp1/ConsoleApp1/bin/Debug/net6.0'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at OpenQA.Selenium.DriverService.Start()
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory)
   at Program.<Main>$(String[] args) in /home/spy/RiderProjects/ConsoleApp1/ConsoleApp1/Program.cs:line 1
```

the code now looks like:
```csharp
new OpenQA.Selenium.Chrome.ChromeDriver("/home/spy/RiderProjects/ConsoleApp1/ConsoleApp1/");

Console.WriteLine("Hello, World!");
```

**Comment by titusfortner** [comment] 2022-10-29 01:19
You need to put the file in a directory your users has permissions for. (probably your user's `home` not your system `home`).

**Comment by spy653** [comment] 2022-10-29 09:42
> You need to put the file in a directory your users has permissions for. (probably your user's `home` not your system `home`).

I placed it in the project directory

**Comment by spy653** [comment] 2022-10-29 17:24
@titusfortner any recommendations for a bandaid fix? Can I feed it a specific chromedriver and chromium browser path and ports? 

Some messages have said messages along the lines of
`connection refused [::ff::127.0.0.1::]`

Forgive me, that's from memory.

**Comment by titusfortner** [comment] 2022-10-30 13:51
then apparently the project directory is not accessible to the user executing the tests.

Please read the documentation on 3 options for installing the drivers - https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/.

**Comment by spy653** [comment] 2022-10-30 14:21
```csharp
new WebDriverManager.DriverManager().SetUpDriver(new WebDriverManager.DriverConfigs.Impl.ChromeConfig());
new OpenQA.Selenium.Chrome.ChromeDriver();

Console.WriteLine("Hello, World!");
```

problem persists

log:
```
/home/spy/RiderProjects/ConsoleApp1/ConsoleApp1/bin/Debug/net6.0/ConsoleApp1
Starting ChromeDriver 107.0.5304.62 (1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}) on port 45465
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Unhandled exception. OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:45465/session timed out after 60 seconds.
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor()
   at Program.<Main>$(String[] args) in /home/spy/RiderProjects/ConsoleApp1/ConsoleApp1/Program.cs:line 2

```

error seen when navigating to `localhost:45465`
```
{"value":{"error":"unknown command","message":"unknown command: unknown command: ","stacktrace":"#0 0x56447e821463 \u003Cunknown>\n#1 0x56447e5e58d8 \u003Cunknown>\n#2 0x56447e64087e \u003Cunknown>\n#3 0x56447e64064d \u003Cunknown>\n#4 0x56447e5b66c4 \u003Cunknown>\n#5 0x56447e5b7563 \u003Cunknown>\n#6 0x56447e873dce \u003Cunknown>\n#7 0x56447e877192 \u003Cunknown>\n#8 0x56447e85893e \u003Cunknown>\n#9 0x56447e878103 \u003Cunknown>\n#10 0x56447e84bd85 \u003Cunknown>\n#11 0x56447e5b5fde \u003Cunknown>\n#12 0x7fd5f0493d90 \u003Cunknown>\n"}}
```

**Comment by MuhSchaf** [comment] 2022-12-16 09:23
Hey you dear keyboard warriors, 

my company observes the same phenomena.
We also use C# und the past chrome-driver versions gave us the white-screen of uncertainty. 
On some of our systems this occurs more often than on others. It has no pattern to it. One test execution freezes and the following works just fine.

**Stacktrace**
```
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL ... timed out after 180 seconds. ---> System.Threading.Tasks.TaskCanceledException: Eine Aufgabe wurde abgebrochen.

[2022-12-14T21:36:41.201Z]    bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

[2022-12-14T21:36:41.201Z]    bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

[2022-12-14T21:36:41.201Z]    bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

[2022-12-14T21:36:41.201Z]    bei OpenQA.Selenium.Remote.HttpCommandExecutor.<MakeHttpRequest>d__35.MoveNext()

[2022-12-14T21:36:41.201Z] --- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel”st wurde ---

[2022-12-14T21:36:41.201Z]    bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

[2022-12-14T21:36:41.201Z]    bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

[2022-12-14T21:36:41.201Z]    bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

[2022-12-14T21:36:41.201Z]    bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

[2022-12-14T21:36:41.201Z]    bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)

[2022-12-14T21:36:41.201Z]    --- Ende der internen Ausnahmestapel�berwachung ---

[2022-12-14T21:36:41.201Z]    bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)

[2022-12-14T21:36:41.201Z]    bei OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)

[2022-12-14T21:36:41.201Z]    bei OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)

[2022-12-14T21:36:41.201Z]    bei OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)

[2022-12-14T21:36:41.201Z]    bei OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)

[2022-12-14T21:36:41.201Z]    bei OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)

[2022-12-14T21:36:41.201Z]    bei OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
```
Thank you for your awesome framework and be blessed.

**Comment by paul-hammant** [comment] 2023-06-21 12:29
I wonder if this is because of security software in corporate settings.  Something is seeing an IO and blocking it or the reply to it. Maybe not even as Selenium starts, but after.  Examples are Cylance and alike. Selenium wouldn't know the response was intercepted and some timeout would happen.  Either Selenium-WebDriver's own timeout, or an underlying one from `HttpClient.Timeout`.    

Drifiting off topic slightly ... An Old IBM page on timeouts -> https://web.archive.org/web/20091008050014/https://www.ibm.com/developerworks/websphere/techjournal/0909_tost/0909_tost.html has helped me in the past with Selenium grid fine tuning.  That page is slow to load, so I copypasta here ->

![image](https://github.com/SeleniumHQ/selenium/assets/82182/c41ea049-92d9-4e6e-96ad-631b92a0762c)

**Comment by NCLnclNCL** [comment] 2023-08-22 08:49
Me troo

**Comment by diemol** [comment] 2023-08-23 14:55
Can someone share a way to reproduce this with Selenium 4.11 or higher? Please remove any third-party drivers. Other wise, we need to close this issue as "cannot reproduce".

**Comment by spy653** [comment] 2023-09-04 23:37
If others are still finding this issue: good luck. My project using this is finished and I ended up switching to puppeteer for my browser manipulation.

**Comment by diemol** [comment] 2023-11-24 15:44
I will close this as we did not get more information from the OP. We can reopen it in case more information is provided.

**Closed as not planned by diemol** 2023-11-24 15:44 UTC
Labels: C-dotnet, I-defect, J-issue-template

**Comment by heavyair** [comment] 2023-12-01 15:17
This error: "1701443566607   geckodriver     INFO    Listening on 127.0.0.1:61970
The request was canceled due to the configured HttpClient.Timeout of 5 seconds elapsing."

 can be reproduced by start a OPENVPN tap based product on windows.  as soon as the VPN is ON, dotnet webdriver will throw this error up on 

  driver = new DOMDriver(edgeService, options, TimeSpan.FromSeconds(10));
                driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);

**Comment by heavyair** [comment] 2023-12-01 15:18
Example VPN product :  CyberGhost VPN

**Comment by heavyair** [comment] 2023-12-01 15:55
found the fix:   it is the DNS that gothrough VPN.   disable reslove DNS via VPN will fix the issue.  if you don't have VPN installed.  the idea is the same, webdriver is trying to talk http://localhost:xxxx/    if something blocking that Name resolving , the call will timeout
