### ISSUE TITLE
[Python 3.5] Selenium PhantomJS webdriver fails to stop on self.process

### ISSUE THREAD

**Issue by cbdelavenne** [SeleniumHQ/selenium#1491] opened 2016-01-18 15:03 UTC
Calling self.service.stop() throws an AttributeError 'NoneType' on 'close':
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    lib\sitenav_helper.py:237: in end_session
        selenium_helper.clean_quit(driver=self._browser)
    lib\selenium_helper.py:36: in clean_quit
        driver.quit()  # Terminates selenium
    c:\program files\python 3.5\lib\site-packages\selenium\webdriver\phantomjs\webdriver.py:74: in quit
        self.service.stop()
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    
    self = <selenium.webdriver.phantomjs.service.Service object at 0x00000079F748C198>
    
        def stop(self):
            """
                Stops the service.
                """
            if self.log_file != PIPE:
                try:
                    self.log_file.close()
                except Exception:
                    pass
        
            if self.process is None:
                return
        
            self.send_remote_shutdown_command()
        
            try:
                if self.process:
    >               self.process.stdout.close()
    E               AttributeError: 'NoneType' object has no attribute 'close'
    
    c:\program files\python 3.5\lib\site-packages\selenium\webdriver\common\service.py:124: AttributeError

**Comment by davehunt** [comment] 2016-01-18 15:05
Duplicate of #1469

**Closed by davehunt** 2016-01-18 15:05 UTC
