### ISSUE TITLE
[🐛 Bug]: WSS support (Ruby)

### ISSUE THREAD

**Issue by csgbn** [SeleniumHQ/selenium#13167] opened 2023-11-17 20:36 UTC
### What happened?

This is a follow up on https://github.com/SeleniumHQ/selenium/issues/12950

We are testing the language bindings against a distributed https grid with separate nodes from the hub in AWS. The grid supports both http and https.

One simple CDP smoke test is carried out with nodes started with --grid-url https://example.com (WSS) and another test with non secure web socket --grid-url http://example.com (WS)

Our grid and method is the same, we first verify that the CDP test works with WS then we test with WSS

Findings so far

Java - Works with both WS and WSS

C# - Works for WS but not for WSS and is being fixed https://github.com/SeleniumHQ/selenium/pull/13131

Ruby - For Ruby we are seeing the same pattern as with C#, it works with WS but not WSS.

Before you asks for how are we deploying the grid and other specifics, please look into creating a test environment for testing a distributed https grid using WSS and CDP/BiDi and verify on your end, we could not find any reference that one exist and as for the case with C#, WSS path has never been tested...

We are supposed to test Python and Javascript CDP/BiDi next, please let us know if they do not yet have support for WSS CDP/BiDi, thanks.

### How can we reproduce the issue?

```shell
# CDP test
require 'selenium-webdriver'
require 'selenium/devtools'

options = Selenium::WebDriver::Options.chrome(browser_version: '119', platform_name: 'linux', web_socket_url: true)

client = Selenium::WebDriver::Remote::Http::Default.new
client.read_timeout = 400 # seconds

driver = Selenium::WebDriver.for(:remote, :url => "https://example.com/wd/hub", :http_client => client, options: options)

begin
driver.manage.timeouts.implicit_wait = 60 # seconds
driver.manage.window.size = Selenium::WebDriver::Dimension.new(1920, 1080)

driver.devtools.network.enable
credentials = Base64.strict_encode64('admin:admin')
driver.devtools.network.set_extra_http_headers(headers: {authorization: "Basic #{credentials}"})
driver.get('https://the-internet.herokuapp.com/basic_auth')

ensure
driver.quit
end
```

### Relevant log output

```shell
Capabilities:

{
  "acceptInsecureCerts": false,
  "browserName": "chrome",
  "browserVersion": "119.0.6045.105",
  "chrome": {
    "chromedriverVersion": "119.0.6045.105 (38c72552c5e15ba9b3117c0967a0fd105072d7c6-refs/branch-heads/6045@{#1103})",
    "userDataDir": "/tmp/.org.chromium.Chromium.QabCNy"
  },
  "fedcm:accounts": true,
  "goog:chromeOptions": {
    "debuggerAddress": "localhost:38293"
  },
  "networkConnectionEnabled": false,
  "pageLoadStrategy": "normal",
  "platformName": "linux",
  "proxy": {},
  "se:bidi": "wss://example.com/session/da9fb00f555e49b9a7cdfd1a3bf8f9db/se/bidi",
  "se:cdp": "wss://example.com/session/da9fb00f555e49b9a7cdfd1a3bf8f9db/se/cdp",
  "se:cdpVersion": "119.0.6045.105",
  "setWindowRect": true,
  "strictFileInteractability": false,
  "timeouts": {
    "implicit": 0,
    "pageLoad": 300000,
    "script": 30000
  },
  "unhandledPromptBehavior": "dismiss and notify",
  "webSocketUrl": "ws://localhost:29837/session/da9fb00f555e49b9a7cdfd1a3bf8f9db",
  "webauthn:extension:credBlob": true,
  "webauthn:extension:largeBlob": true,
  "webauthn:extension:minPinLength": true,
  "webauthn:extension:prf": true,
  "webauthn:virtualAuthenticators": true
}



error
Ruby32-x64/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.15.0/lib/selenium/webdriver/common/websocket_connection.rb:146:in `connect': SSL_connect returned=1 errno=0 peeraddr=76.9.274.42:443 state=error: unexpected eof while reading (OpenSSL::SSL::SSLError)
```

### Operating System

Windows 11

### Selenium version

4.15.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 119

### What are the browser driver(s) and version(s) where you see this issue?

119.0.6045.105

### Are you using Selenium Grid?

4.15.0

**Comment by csgbn** [comment] 2023-12-06 23:46
We can confirm the C# WSS path is fixed in 4.16.0, thanks!

**Comment by csgbn** [comment] 2023-12-07 00:06
Correction, fixed in 4.16.1.

Also tested Ruby with 4.16.0,  however has the exact same issue as in 4.15.0 as described in this ticket.

**Comment by titusfortner** [comment] 2023-12-07 04:24
@p0deje did we discuss this issue somewhere else, it sounds familiar?

**Comment by p0deje** [comment] 2023-12-07 14:53
In Ruby we start secure socket connection as long as it's returned in connection URL - https://github.com/SeleniumHQ/selenium/blob/a24a189764316832503851c8f0e58d77d3779a6d/rb/lib/selenium/webdriver/common/websocket_connection.rb#L142-L151. I would need to investigate why it actually fails on Grid. I think it was @pujagani who added this logic - do you have WSS working in your setup?

**Comment by pujagani** [comment] 2023-12-08 05:26
In the past I have relied on using `--self-signed-https true ` in the Grid. For some reason, that flag is present but throwing an error when used. Trying to look into it.

**Comment by pujagani** [comment] 2023-12-08 14:47
I have landed the fix. Using `--self-signed-https` should work now.

**Comment by p0deje** [comment] 2023-12-08 15:35
Thanks @pujagani!

I can now run Grid in SSL mode and I can see Ruby using `WSS` under the hood, but I cannot reproduce the issue:

```
java -jar bazel-bin/java/src/org/openqa/selenium/grid/selenium_server_deploy.jar standalone --self-signed-https
...
```

```ruby
irb(main):003> options = Selenium::WebDriver::Options.chrome(web_socket_url: true)
=> #<Selenium::WebDriver::Chrome::Options:0x000000012fa44540
irb(main):005> driver = Selenium::WebDriver.for(:remote, :url => "https://192.168.1.34:4444", options: options)
=> #<Selenium::WebDriver::Remote::Driver:0x6270e210902b1bd2 browser=:chrome>
irb(main):010> driver.devtools
=>
#<Selenium::WebDriver::DevTools:0x000000010f9f8480
 @session_id="9B7BC116F8AB06C39D3C80510149EC61",
 @ws=
  #<Selenium::WebDriver::WebSocketConnection:0x000000010f9f82a0
   ...
   @url="wss://192.168.1.34:4444/session/3503fcf2569462fc1ecf3311c26580bf/se/cdp",    # WSS URL
   ...
irb(main):006> driver.devtools.network.enable
=> {"id"=>3, "result"=>{}, "sessionId"=>"9B7BC116F8AB06C39D3C80510149EC61"}
irb(main):007> credentials = Base64.strict_encode64('admin:admin')
=> "YWRtaW46YWRtaW4="
irb(main):008> driver.devtools.network.set_extra_http_headers(headers: {authorization: "Basic #{credentials}"})
irb(main):009> driver.get('https://the-internet.herokuapp.com/basic_auth')
=> nil
```

@csgbn Any idea what is different from your setup?

**Comment by titusfortner** [comment] 2023-12-31 19:34
closing as did not get a response. Adding links for asking questions below.

**Closed as completed** 2023-12-31 19:35 UTC
Labels: B-grid, J-awaiting answer, C-rb, I-defect, I-question
