### ISSUE TITLE
selenium record buton don't work

### ISSUE THREAD

**Issue by ilsur** [SeleniumHQ/selenium#4989] opened 2017-11-01 13:51 UTC
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by ilsur** [comment] 2017-11-01 14:13
installed version ff54 and now this button is active

**Comment by ilsur** [comment] 2017-11-01 14:13
!!!

**Comment by lmtierney** [comment] 2017-11-01 14:49
Duplicate of #4406

**Closed by lmtierney** 2017-11-01 14:49 UTC
