### ISSUE TITLE
[🐛 Bug]: `application_cache.status` will never work as it references an unknown command.

### ISSUE THREAD

**Issue by symonk** [SeleniumHQ/selenium#11000] opened 2022-09-03 13:08 UTC
### What happened?

The python bindings are reference a (somewhat deprecated) HTML `ApplicationCache` that internally has a `status` property in it's public API, this will never work however as it's reference a non existing command: `Command.GET_APPLICATION_CACHE`.

Should we remove the deprecation `ApplicationCache` concept? I can't find anything in webdriver W3c indicating such an endpoint; tho I do see references in the java bindings for: `defineCommand(GET_APP_CACHE_STATUS, get(sessionId + "/application_cache/status"));` (possible relatable, but maybe not)

### How can we reproduce the issue?

```python
from selenium import webdriver

# as always; make sure chromedriver is on $PATH
with webdriver.Chrome() as driver:
    driver.application_cache.status
```

```console
     48 @property
     49 def status(self):
     50     """
     51     Returns a current status of application cache.
     52     """
---> 53     return self.driver.execute(Command.GET_APP_CACHE_STATUS)['value']

AttributeError: type object 'Command' has no attribute 'GET_APP_CACHE_STATUS'
```

### Relevant log output

```shell
N/A
```

### Operating System

Ubuntu 20.04

### Selenium version

4.4.1

### What are the browser(s) and version(s) where you see this issue?

chrome (but N/A)

### What are the browser driver(s) and version(s) where you see this issue?

chrome 104 (but N/A)

### Are you using Selenium Grid?

no.

**Comment by diemol** [comment] 2022-09-03 23:50
Duplicate of #10397

Issue will be linked for reference

**Closed as completed by diemol** 2022-09-03 23:50 UTC
Labels: C-py, I-defect
