### ISSUE TITLE
selenium-webdriver 3.3.0 - action class double_click not working

### ISSUE THREAD

**Issue by gklueh** [SeleniumHQ/selenium#3868] opened 2017-04-20 19:55 UTC
## Meta -
OS:  Win7

Selenium Version:  Selenium Webdriver Ruby Gem 3.3.0

Browser:  Chrome 

Browser Version:  55

## Steps to reproduce -

I am unable to get the double_click method within the Action class of Ruby 2.3.1's gems to work using the selenium-webdriver 3.3.0 driver and the ChromeDriver version 2.28 or 2.29 using the following code:

Sample from here:
`el = driver.find_element(id: "some_id")`
`driver.action.double_click(el).perform`

Code:
`@article_zone = @driver.find_element(:id, "viewer-zone-overlay-13B27E79C7BC32F1")`
`@driver.action.double_click(@article_zone).perform`

Note: This same code works using selenium standalone server version 3.3.1 with both ChromeDrivers above.

**Comment by lmtierney** [comment] 2017-04-20 20:41
This is working fine for me and with our travis CI tests. I'm guessing you have a timing issue. Try the code I've provided below as it works for me. Closing this unless you can provide a [concise reproducible test case](http://sscce.org/).

```
require "selenium-webdriver"
d = Selenium::WebDriver.for(:chrome)
d.get('https://api.jquery.com/dblclick/')
frame = d.find_element(css: 'iframe')
d.switch_to.frame(frame)
element = d.find_element(css: 'div')
puts element.css_value('background-color')
d.action.double_click(element).perform
puts element.css_value('background-color')
```

```
> rgba(0, 0, 255, 1)
> rgba(255, 255, 0, 1)
```

**Closed by lmtierney** 2017-04-20 20:41 UTC

**Comment by gklueh** [comment] 2017-05-09 19:12
@lmtierney Thanks for this. I AM able to take your code above and put it in my text editor and run it successfully. However when using my code with the same versions of everything locally that worked for your code,  I am having trouble still. I have attempted to streamline the code to provide you with a concise reproducible test case below, I am hoping you can reproduce my failure to make the double_click action work and provide any insight to what may be going on, or direct me to the correct forum to inquire about this... what is odd, is I can print out the Selenium Element `<Selenium::WebDriver::Element:0xf0cdb546 id="0.7323387782850805-1">` and then highlight the actual element (and visually see it highlights the article/element that requires the double_click), however when the double_click action is fired, the page just scrolls down and never double_clicks.

`
require 'rubygems'
require 'selenium-webdriver'
require 'test/unit'

class Test_Test_Tests < Test::Unit::TestCase

	def setup
		@driver = Selenium::WebDriver.for :chrome
		@driver.manage.window.maximize
	end

	def teardown
		@driver.quit
	end

	def highlight element, time = 5
		@orig_style = element.attribute("style")
		@driver.execute_script("arguments[0].setAttribute(arguments[1], arguments[2])", element, "style", "border: 2px solid yellow; color: yellow; font-weight: bold;")
		if time > 0
			sleep time
			@driver.execute_script("arguments[0].setAttribute(arguments[1], arguments[2])", element, "style", @orig_style)
	end
	
end

	def test_test
		@driver.get "http://infoweb.newsbank.com/apps/readex/openurl?ctx_ver=z39.88-2004&rft_id=info%3Asid%2Finfoweb.newsbank.com&svc_dat=ARDX&req_dat=873DC1390A424A55B3E2EE9E2C52D9F3&rft_val_format=info%3Aofi%2Ffmt%3Akev%3Amtx%3Actx&rft_dat=document_id%3Aimage%252Fv2%253A1370B42AEC50B618%2540JPRSX-13A4BABCC88C8363%25402446434-13A31BD710C5DA07%254050"
		#@article = @driver.find_element(:xpath, "//div[@id='nb-osd-viewer-d7de7bd21e3d960c0bb7acf758e851f4']/div[2]/div/div/div")
		@article = @driver.find_element(:css, "#nbviewer-zone-overlay-13B27E79C7BC32F1")
		p @article
		highlight @article
		@driver.action.double_click(@article).perform
		assert !60.times{ break if (@driver.find_element(:css, "div.search-hit-source").text == "Cairo AL-AHRAM" rescue false); sleep 1 }
		assert !60.times{ break if (@driver.find_element(:css, "h2.doc-view__title").text == "MEANS TO COMBAT TAX EVASION DISCUSSED" rescue false); sleep 1 }
	end
end
`


Thanks again for any guidance here, it is much appreciated!

**Comment by lmtierney** [comment] 2017-05-10 01:24
You're having an issue because `double_click` by default tries to click in the middle of the element. If you inspect the element, you can see that the middle of it is hidden below the viewer. To get around this, you can move to the element with an offset (from top left) and perform a double click in place:

    @driver.action.move_to(@article, 10, 10).double_click.perform

I've tried this and it appears to be working on the page you provided.

In the future, please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

**Comment by gklueh** [comment] 2017-05-10 14:22
@lmtierney Thank you for this, it indeed works great! If only I had seen in all the online documentation I reviewed while troubleshooting this issue the simple fact that "double_click by default tries to click in the middle of the element", that would have saved me (and you) this time. Thank you again!

**Comment by lmtierney** [comment] 2017-05-10 14:34
You may want to check out the official API then, it details that here:

http://seleniumhq.github.io/selenium/docs/api/rb/Selenium/WebDriver/ActionBuilder.html#double_click-instance_method
