### ISSUE TITLE
Unable to set Firefox window position

### ISSUE THREAD

**Issue by SankySyS** [SeleniumHQ/selenium#4309] opened 2017-07-13 19:48 UTC
## Meta -
OS:  
Windows  7
Selenium Version:  
3.4.0 Java
Browser:  
Firefox
Browser Version:  
54.0.1, 55.0b8; 

GeckoDriver 1.18, Java 1.8

## Expected Behavior - 
`driver.manage().window().setPosition(new Point(500, 500));` - sets window position
## Actual Behavior -
Nothing happens. But it's work in IE and Chrome browsers.
## Steps to reproduce -
Using Java try to set window position:
`driver.manage().window().setPosition(new Point(500, 500));`

GeckoDriver console output after execution setPosition method:

```
1499932060105	webdriver::server	DEBUG	-> POST /session/72883741-62b0-438b-b2b4-6af09ffe0b41/window/rect {"script":"window.screenX = arguments[0]; window.screenY = arguments[1]","args":[500,500]}
1499932060105	geckodriver::marionette	TRACE	-> 68:[0,3,"setWindowRect",{"height":null,"width":null,"x":null,"y":null}]
1499932060096	Marionette	TRACE	0 -> [0,3,"setWindowRect",{"height":null,"width":null,"x":null,"y":null}]
1499932060098	Marionette	TRACE	0 <- [1,3,null,{"x":4,"y":4,"width":1280,"height":743}]
1499932060105	geckodriver::marionette	TRACE	<- [1,3,null,{"x":4,"y":4,"width":1280,"height":743}]
1499932060105	webdriver::server	DEBUG	<- 200 OK {"value": {"x":4.0,"y":4.0,"width":1280.0,"height":743.0}}
```

According to the answer on  [https://github.com/mozilla/geckodriver/issues/822](url) problem in Selenium

**Comment by p0deje** [comment] 2017-07-14 03:32
Duplicate of #4303

**Closed by p0deje** 2017-07-14 03:32 UTC
