### ISSUE TITLE
Some site controls disappear when doing scroll using WebDriver Actions class

### ISSUE THREAD

**Issue by ai-alex** [SeleniumHQ/selenium#943] opened 2015-08-19 14:09 UTC
We have a grid in our web application.
We have a framework with selenium webdriver based test cases in it.
When next code is executed during tests:
***public void doubleClick(WebElement element)
    {
        Actions actions = new Actions(webDriver);
        actions.doubleClick(element).build().perform();
    }***
(element is a cell in a grid, which is out of screen before double click) - the page is scrolled to the cell and doing double click.
But at the same time a container above our grid (with menus, buttons etc.) just disappear. And in addition an empty rectangle appears below the grid with about the same size as disappeared container.
*Note: But when element is not out of screen before doing click - the issue does not exist. So the problem, indeed in the scrolling*

I consulted with our development team - they did some investigations and concluded that actually page is not changed. And elements should be on their places (still above the grid) and after doing 
OneLinkJQ('.OPE_Panel2').hide()
OneLinkJQ('.OPE_Panel2').show()
(.OPE_Panel2 points to the hidden part) - the container with all elements become visible again.

Issue exists on Firefox 40.0.2, IE 11 (latest updates). 
On Chrome issue is not reproduced.
Manually issue is not reproduced. Only while executing Java code.
Selenium version - 2.46.0 (and 2.47.1 as well)
OS - Windows 7 Ultimate SP1 x64

=====================================================================
See images: before executing "actions.doubleClick(element).build().perform();"
![1 before scroll](https://cloud.githubusercontent.com/assets/7655829/9358103/1092de18-4693-11e5-8489-10316a2f359f.png)
and after
![2 after scroll](https://cloud.githubusercontent.com/assets/7655829/9358104/10968b94-4693-11e5-8f12-51b286603fd3.png)

I can provide more information if needed.

**Comment by lukeis** [comment] 2015-08-19 16:59
you'll need to provide a link to the page or html sources (including javascript / css) for us to be able to reproduce this

**Comment by ai-alex** [comment] 2015-08-20 10:40
According to our security rules I can't get you neither access to our servers not html code of the application.
But actually - I can provide any logs or debug you need. Just explain how to get them.

BTW. We found a workaround for the problem.
Instead of using
**Actions actions = new Actions(driver);
actions.doubleClick(element).build().perform();**
we use JavaScript executor to do double click
**String javaScript = "var evObj = document.createEvent('MouseEvents');" +
"evObj.initMouseEvent(\"dblclick\",true, false, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);" +
"arguments[0].dispatchEvent(evObj);";
((JavascriptExecutor)driver).executeScript(javaScript, element);**
In this case table is not scrolled but the cell is double-clicked.

**Comment by lukeis** [comment] 2015-08-20 17:02
there's no logs that would help anyone trouble shoot this issue. you'll need to provide a sample representative html page to reproduce your issue. Since you say you're not willing to, I'll have to close this issue.

Glad you found a workaround, albeit one that doesn't help future users since it's not cross browser compatible

**Closed by lukeis** 2015-08-20 17:02 UTC
