### ISSUE TITLE
File upload in Selenium grid fails with JSON parse error

### ISSUE THREAD

**Issue by meeusen** [SeleniumHQ/selenium#4025] opened 2017-05-16 09:14 UTC
## Meta -
OS:  Windows 7

Selenium Version:  3.4.0 (grid/node + python bindings)

Browser:  Google Chrome (but probably all browsers/platforms)

Browser Version:  58.0.3029.110 (64-bit)

## Expected Behavior -
Local file is uploaded to the Selenium node that is part of a grid.

## Actual Behavior -
There is a JSON parse error: selenium.common.exceptions.WebDriverException: Message: Failed parsing JSON source: JsonReader at line 1 column 20712896 path $.file to Json.

The line/column offset in the error is always the same.

## Steps to reproduce -
1) Create a 20 MiB random file (e.g. dd if=/dev/urandom of=20MiB.file bs=1M count=20). It should be a file that will be >20MiB when compressed with Python's zipfile module and then base64 encoded. I don't see this problem with smaller files (files of a few megabytes).
2) Upload this file to a browser in a Selenium grid:
```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
grid = "http://<REPLACEME>:4444/wd/hub"
d = webdriver.Remote(command_executor=grid,\
                     desired_capabilities=DesiredCapabilities.CHROME)
d.get("https://fiddle.jshell.net/2f15yz1a/show/")
d.switch_to.frame(0)
e = d.find_element_by_id("f")
e.send_keys(r"C:\20MiB.file")
```
I then get this exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 345, in send_keys
    value = self._upload(local_file)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 550, in _upload
    raise e
selenium.common.exceptions.WebDriverException: Message: Failed parsing JSON source: JsonReader at line 1 column 20712896 path $.file to Json
```

**Comment by Hassan-Radi** [comment] 2017-09-22 11:21
I am also experiencing the same issue here on Firefox 53,52,51 and Also IE 11. The interesting part is that it is working for Chrome 58 for me.

**Comment by ybizeul** [comment] 2017-10-28 09:13
Same here with current `selenium/standalone-chrome` container. Anybody fixed it?

```
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 348, in send_keys
    value = self._upload(local_file)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 558, in _upload
    raise e
selenium.common.exceptions.WebDriverException: Message: Failed parsing JSON source: JsonReader at line 1 column 82851222 path $.file to Json
Stacktrace:
    at com.google.gson.JsonParser.parse (JsonParser.java:88)
    at com.google.gson.JsonParser.parse (JsonParser.java:59)
    at com.google.gson.JsonParser.parse (JsonParser.java:45)
    at org.openqa.selenium.remote.JsonToBeanConverter.convert (JsonToBeanConverter.java:197)
    at org.openqa.selenium.remote.JsonToBeanConverter.convert (JsonToBeanConverter.java:47)
    at org.openqa.selenium.remote.server.commandhandler.UploadFile.execute (UploadFile.java:47)
    at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0 (WebDriverServlet.java:232)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
```

**Comment by shs96c** [comment] 2017-10-28 11:58
We have tests around uploading files to remote, but apparently something is
going awry. Can you please include an example file that you're trying to
upload?

**Comment by ybizeul** [comment] 2017-10-28 13:04
Interesting indeed, if I upload a simple text file with a few characters in it, it works.
The file that fails is a 64M zip file that is protected by my company license so I can't distribute it

Why does it looks like selenium is opening and reading the file somehow?

**Comment by Hassan-Radi** [comment] 2017-10-28 13:17
I can reproduce the issue with this image: https://drive.google.com/open?id=0B2W_gwWNkmtnS2djakdpVHRqeTA

**Comment by ybizeul** [comment] 2017-10-28 13:33
Went as far as docker container 3.3.1 and still get the same behavior. Doesn't make much sense to me as it used to work before

**Comment by barancev** [comment] 2017-10-29 19:42
For the record: I can't reproduce the issue with grid 3.6, python binding 3.6, provided big_photo.jpg or generated random file.

**Comment by ybizeul** [comment] 2017-11-30 23:59
It seems to be memory related. I am running selenium in containers, my approach is to run more smaller container hosts (4G ram), and it looks like selenium was running under constraint.

I changed memory on the host to 8G and it works again.

It looks like the uploaded file is somehow loaded in memory, which for obvious reason should be avoided, not sure that's possible though.

**Comment by furrowb** [comment] 2018-04-26 20:33
I was uploading a 70MiB file and had to increase the Java heap size by setting `-e JAVA_OPTS=-Xmx2000M` and that seemed to alleviate the issue for me.  My container/VM only has access to 2GiB so I didn't have the option of increasing the memory for it.  I also had to increase the the shared memory by using `--shm-size 1g` which was mostly for Chrome as noted here:

https://hub.docker.com/r/chrisdaish/google-chrome/

**Comment by barancev** [comment] 2018-05-08 21:02
According to the comments, it's a duplicate of #3503

**Closed by barancev** 2018-05-08 21:02 UTC
Labels: C-grid, C-java
