### ISSUE TITLE
Documentation missing for Selenium Html Runner

### ISSUE THREAD

**Issue by juniormayhe** [SeleniumHQ/selenium#4379] opened 2017-07-26 23:36 UTC
Guys

Is there any documentation available about Selenium Html Runner or do we have to take a look everytime at HTMLLauncher.java? We have many questions on internet about how to use selenium-html-runner-x.x.x.jar and its available args (for Windows / Linux).

Also the Wiki does not help us to quickly find information regarding Selenium Html Runner, getting started, samples, etc.

**Comment by p0deje** [comment] 2017-07-27 03:31
Duplicate of #4153

**Closed by p0deje** 2017-07-27 03:31 UTC
