### ISSUE TITLE
error taking element screenshot

### ISSUE THREAD

**Issue by novoxudonoser** [SeleniumHQ/selenium#923] opened 2015-08-12 21:40 UTC
python:

```python
>>> driver = webdriver.Remote(
...     desired_capabilities=webdriver.DesiredCapabilities.FIREFOX,
...      command_executor='http://127.0.0.1:4444/wd/hub')
>>> driver.get("https://www.avito.ru/voronezh/kvartiry/1-k_kvartira_33_m_1017_et._615079583")
>>> button=driver.find_element_by_class_name("description__phone-insert")
>>> button.click()
>>> image=driver.find_element_by_class_name("description__phone-img")
>>> image.screenshot("sdf.png")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/kirrll/avito/pyt/lib/python3.4/site-packages/selenium/webdriver/remote/webelement.py", line 399, in screenshot
    png = self.screenshot_as_png
  File "/home/kirrll/avito/pyt/lib/python3.4/site-packages/selenium/webdriver/remote/webelement.py", line 386, in screenshot_as_png
    return base64.b64decode(self.screenshot_as_base64.encode('ascii'))
  File "/home/kirrll/avito/pyt/lib/python3.4/site-packages/selenium/webdriver/remote/webelement.py", line 376, in screenshot_as_base64
    return self._execute(Command.ELEMENT_SCREENSHOT)['value']
  File "/home/kirrll/avito/pyt/lib/python3.4/site-packages/selenium/webdriver/remote/webelement.py", line 448, in _execute
    return self._parent.execute(command, params)
  File "/home/kirrll/avito/pyt/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 196, in execute
    self.error_handler.check_response(response)
  File "/home/kirrll/avito/pyt/lib/python3.4/site-packages/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'kirrll-System-Product-Name', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-45-generic', java.version: '1.7.0_79'
Driver info: driver.version: unknown
Stacktrace:
>>> image.get_attribute("src")
'https://www.avito.ru/items/phone/615079583?pkey=e76d4bf4326fc82988d16b5e1e03c97f'
```

sever:
```
java -jar selenium-server-standalone-2.47.1.jar -role hub

...

00:26:00.081 INFO - Executing: [new session: Capabilities [{platform=ANY, javascriptEnabled=true, browserName=firefox, marionette=false, version=}]])
00:26:00.083 INFO - Creating a new session for Capabilities [{platform=ANY, javascriptEnabled=true, browserName=firefox, marionette=false, version=}]
00:26:03.946 INFO - Done: [new session: Capabilities [{platform=ANY, javascriptEnabled=true, browserName=firefox, marionette=false, version=}]]
00:27:17.360 INFO - Executing: [get: https://www.avito.ru/voronezh/kvartiry/1-k_kvartira_33_m_1017_et._615079583])
00:27:25.592 INFO - Done: [get: https://www.avito.ru/voronezh/kvartiry/1-k_kvartira_33_m_1017_et._615079583]
00:28:54.297 INFO - Executing: [find element: By.className: description__phone-insert])
00:28:54.416 INFO - Done: [find element: By.className: description__phone-insert]
00:29:07.373 INFO - Executing: [click: 0 [[FirefoxDriver: firefox on LINUX (56c9a8d5-0fe3-49a1-806f-eb484468f355)] -> class name: description__phone-insert]])
00:29:07.756 INFO - Done: [click: 0 [[FirefoxDriver: firefox on LINUX (56c9a8d5-0fe3-49a1-806f-eb484468f355)] -> class name: description__phone-insert]]
00:29:25.798 INFO - Executing: [find element: By.className: description__phone-img])
00:29:25.814 INFO - Done: [find element: By.className: description__phone-img]
00:32:08.410 INFO - Executing: [get element attribute: 1 [[FirefoxDriver: firefox on LINUX (56c9a8d5-0fe3-49a1-806f-eb484468f355)] -> class name: description__phone-img], src])
00:32:08.430 INFO - Done: [get element attribute: 1 [[FirefoxDriver: firefox on LINUX (56c9a8d5-0fe3-49a1-806f-eb484468f355)] -> class name: description__phone-img], src]
```

**Comment by jimevans** [comment] 2015-08-12 21:44
Duplicate of #912

**Closed by jimevans** 2015-08-12 21:44 UTC
