### ISSUE TITLE
[🐛 Bug]: drag_and_drop can't act well with canvas

### ISSUE THREAD

**Issue by zndqs** [SeleniumHQ/selenium#10618] opened 2022-05-07 03:48 UTC
### What happened?

for example with http://literallycanvas.com/:
i want to draw a line in it ,i tried `ActionChains(driver).drag_and_drop_by_offset(canvas,50,50).perform()`,but only draw a point
then i tried `ActionChains(driver).click_and_hold(canvas).move_by_offset(50, 0).release().perform()`,also draw a point
finally i draw a line with `ActionChains(driver).click_and_hold(canvas).move_by_offset(50, 0).move_by_offset(0, 0).release().perform()`
but it's not reasonable

### How can we reproduce the issue?

```shell
it seems like a holdingmouse_move action require something like 'Intermediate state',which drag_and_drop didn't provide
```

### Relevant log output

```shell
None
```

### Operating System

Window10

### Selenium version

python4.1.3

### What are the browser(s) and version(s) where you see this issue?

chrome 101

### What are the browser driver(s) and version(s) where you see this issue?

chrome 101

### Are you using Selenium Grid?

no

**Comment by diemol** [comment] 2022-05-07 06:37
Duplicate of #10601

https://github.com/SeleniumHQ/selenium/issues/10601#issuecomment-1117937743

**Closed as completed by diemol** 2022-05-07 06:37 UTC
Labels: I-defect
