### ISSUE TITLE
[🐛 Bug]: Exceptions When Switching Frames in Firefox 102.0 ESR with GeckoDriver v0.32

### ISSUE THREAD

**Issue by OtiliaRegheni** [SeleniumHQ/selenium#13644] opened 2024-03-01 07:01 UTC
### What happened?

When switching to a different frame on a webpage using Selenium WebDriver with Firefox 102.0 ESR and GeckoDriver v0.32, intermittent exceptions are encountered when attempting to interact with elements within the switched frame. Instead of receiving a TimeoutException or a relevant error indicating the frame is not ready, the following exceptions are thrown without a preceding indication of frame availability issues:

- **NoSuchWindowException**: Browsing context has been discarded.

- **StaleElementReferenceException**: The element reference is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed.

This behavior is inconsistent and complicates element interaction within frames, requiring a workaround that involves retrying the frame switch and element interaction.

### How can we reproduce the issue?

```shell
1.Initiate a Selenium WebDriver session with Firefox 102.0 ESR using GeckoDriver v0.32.
2.Navigate to a webpage that contains multiple frames.
3.Switch to a new frame using the "ExpectedConditions.frameToBeAvailableAndSwitchToIt(frameBy)" condition.
4.Attempt to select an element within the new frame context.

Expected Behavior:After switching to a new frame, elements within that frame should be selectable without errors.

Actual Behavior:When attempting to select an element within a newly switched frame, exceptions are thrown intermittently:
NoSuchWindowException: Browsing context has been discarded
StaleElementReferenceException: The element reference of [element details] is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed.
```

### Relevant log output

```shell
NoSuchWindowException: Browsing context has been discarded
StaleElementReferenceException: The element reference of [element details] is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed.
```

### Operating System

CentOS

### Selenium version

Selenium 3.14 and Selenium 4.13

### What are the browser(s) and version(s) where you see this issue?

Firefox 102.0esr  

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.32

**Comment by diemol** [comment] 2024-03-01 14:14
You should also try with Chrome and see if that also happens.

**Comment by diemol** [comment] 2024-03-11 21:13
I am closing this because we did not get more information to reproduce the issue.

**Closed as not planned by diemol** 2024-03-11 21:13 UTC
Labels: I-defect, J-issue-template

**Comment by OtiliaRegheni** [comment] 2024-03-12 07:33
Hello, I'm cannot share my code and URL/HTML. The issue is not reproducible on Chrome browser. I'm currently in progress with the creation of a POC to can reproduce this issue.
