### ISSUE TITLE
[🐛 Bug]: With SIGINT the Browser instance isn't closing [Windows]

### ISSUE THREAD

**Issue by lalith-mcw** [SeleniumHQ/selenium#11782] opened 2023-03-16 10:31 UTC
### What happened?

Trying to run a browsertest with a local flask application and when the same is running 
User is raising a `SIGINT` Signal which does leave the browser opened, and with the `SIGNAL HANDLER` not able to access the driver object, since the driver was deleted and these are windows specific.

When the same is tried in MAC it does close the browser as well. Is this due to `SIGINT` implementation in `Windows` which does close the Selenium Provider first and where the instance isn't closed properly. And `SIGINT` signal is sent to the child process first in `Windows` and the parent waits until the child is closed.

### How can we reproduce the issue?

```shell
Setup a driver and try to close that with `SIGINT` in Windows. Dump the browser members in a class and the `driver` should be an member of an instance of that class
```

### Relevant log output

```shell
WARNING  : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026E2FBDCE80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7cf89c9c68a22e14d188b06525b4cef9/window
```
After multiple debug statements as above it ends up with the below message.

```
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53321): Max retries exceeded with url: /session/7cf89c9c68a22e14d188b06525b4cef9/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026E2FBDFC40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
```
```


### Operating System

Windows 11

### Selenium version

4.8.0

### What are the browser(s) and version(s) where you see this issue?

Chrome - 111.0.5563.65

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver - 111.0.5563.64

### Are you using Selenium Grid?

_No response_

**Comment by diemol** [comment] 2023-03-16 10:39
What is handling the SIGINT signal? Not clear what the scenario looks like.

**Comment by lalith-mcw** [comment] 2023-03-16 10:50
> What is handling the SIGINT signal? Not clear what the scenario looks like.

`Ctrl+C` Interrupt by the user

**Comment by diemol** [comment] 2023-03-16 10:52
I understand how the signal is triggered, I was asking what is being interrupted. A test script? The flask application?

**Comment by diemol** [comment] 2023-03-16 11:12
I just tried on Windows and macOS and the browser closes. Please share a way to reproduce the issue.

**Comment by lalith-mcw** [comment] 2023-03-16 11:43
```
driver = None

def signal_handler(signal, frame):
	if drive:  # not none
		#Execution comes here
		driver.quit()		# This call isn't working
   	print("Program exiting SIGINT!")
	sys.exit(0)

class Browser(ABC):
	"""
	Base class for web browsers
	"""
	self.options = None

	def __init__(self, options):
		self.service = ChromeService(<Driver Path>)
		self.driver = ChromeDriver(self.service, self.options)
	
	def open(self, url) -> WebDriver:
		self.driver.get(url)
		return self.driver
	
	def reset(self):
		self.driver.quit()


class Chrome(Browser):
#Driver path and ChromeOptions are set here
...
....
.....


if __name__ == "main":
	browser = Chrome(options)
	driver = browser.open(<Website>)
	time.sleep(10)			# Will be pressing SIGINT here
	driver.quit()
	
```

Attaching a sample of what we have implemented, we do have a `custom signal handler` 
Without a signal handler we are able to close the browser window with `SIGINT` since that follows a process hierarchy but with an handler we are not able to handle those. Since the driver instance is closed

**Comment by diemol** [comment] 2023-03-16 12:17
OK, so this is Python. Then this is a duplicate of #10444.

**Closed as completed by diemol** 2023-03-16 12:17 UTC
Labels: J-awaiting answer, I-defect, J-issue-template
