### ISSUE TITLE
LoggingPreferences not working as expected.

### ISSUE THREAD

**Issue by tzah4748** [SeleniumHQ/selenium#8402] opened 2020-06-08 18:23 UTC
## 🐛 Bug Report
JAVA
LoggingPreferences is not working on selenium-server 3.141.59 but works on 4.0.0-alpha-2.

## To Reproduce
1. Create a standalone selenium server.
2. Create ChromeOptions and add the LOGGING_PREFS Capability with DRIVER (or any other type of log) enabled with Level.ALL.
3. Do something with the driver and check for any logs coming from the driver via driver.manage().logs()

## Expected behavior
Seeing the logs we added with the LOGGING_PREFS in the driver.manage().logs()

## Actual behavior
Seeing only the SERVER and CLIENT logs.

## Test script or set of commands reproducing this issue

```
public static void main(String[] args) throws MalformedURLException {

        WebDriverManager.chromedriver().setup();

        // Start Selenium
        StandaloneConfiguration configuration = new StandaloneConfiguration();
        SeleniumServer server = new SeleniumServer(configuration);
        server.boot();

        ChromeOptions options = new ChromeOptions();
        LoggingPreferences loggingPreferences = new LoggingPreferences();
        loggingPreferences.enable(LogType.DRIVER, Level.ALL);
        options.setCapability(CapabilityType.LOGGING_PREFS, loggingPreferences);

        RemoteWebDriver driver = new RemoteWebDriver(
                new URL("http://localhost:4444/wd/hub"), options);

        Runnable runnable = () -> {
            try {
                Set<String> logtypes = driver.manage().logs().getAvailableLogTypes();
                System.out.println("LOG " + Arrays.toString(logtypes.toArray()));
                while (true) {
                    logtypes.forEach(logType -> {
                        LogEntries logEntries = driver.manage().logs().get(logType);
                        logEntries.forEach(logEntry -> {
                            System.out.println(String.format("LOG [%s] - [%s]-[%s]: %s",
                                    logType, logEntry.getTimestamp(),
                                    logEntry.getLevel(), logEntry.getMessage()));
                        });
                    });
                    TimeUnit.MILLISECONDS.sleep(100);
                }
            } catch (Exception e) {
                System.out.println("LOG - DEAD");
            }
        };

        new Thread(runnable).start();

        try {
            // Do some actions with the driver...
            driver.navigate().to("https://google.com");
            TimeUnit.SECONDS.sleep(10);
        } catch (Throwable e) {
            e.printStackTrace();
        } finally {
            driver.quit();
        }
        server.stop();
        System.exit(0);
    }
```

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 83.0.4103.61
Browser Driver version: ChromeDriver 83.0.4103.39
Language Bindings version: Java 13
Selenium Grid version (if applicable): 3.141.59

**Comment by AutomatedTester** [comment] 2020-06-16 20:44
So this is working as expected in the tree?

**Comment by tzah4748** [comment] 2020-06-21 07:21
I don't think i understand what you asked... can you make it clearer? what is the tree you are referring to?

**Comment by diemol** [comment] 2020-06-29 21:41
@tzah4748 What exact version of the Java bindings are you using? (Not asking for the Java version)

**Comment by tzah4748** [comment] 2020-07-01 19:16
@diemol My project language level is 8 and i am using open jdk 13
![image](https://user-images.githubusercontent.com/37114431/86282710-6d5f7280-bbe8-11ea-9c5a-de57c5fe78e9.png)

**Comment by diemol** [comment] 2020-07-01 19:39
Java bindings version, not the Java version

**Comment by tzah4748** [comment] 2020-07-02 13:51
I am sorry @diemol, i don't know what is Java bindings version.
Can you please refer me to a guide? or explain where do i find those bindings version?

**Comment by diemol** [comment] 2020-07-02 13:56
Well, you are using Java, what dependency for Selenium do you use in your maven/Gradle configuration?

**Comment by tzah4748** [comment] 2020-07-02 14:52
@diemol 
Attaching my build.gradle, is that what you meant?


```
plugins {
    id 'java'
}

group 'io.something'
version '1.0-SNAPSHOT'

compileJava.options.encoding = 'UTF-8'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'

    // https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-server
    compile group: 'org.seleniumhq.selenium', name: 'selenium-server', version: '3.141.59'

    // https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-api
    compile group: 'org.seleniumhq.selenium', name: 'selenium-api', version: '3.141.59'

    // https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-chrome-driver
    compile group: 'org.seleniumhq.selenium', name: 'selenium-chrome-driver', version: '3.141.59'

    compile("io.github.bonigarcia:webdrivermanager:3.8.1")

}

jar {
    manifest {
        attributes(
                'Class-Path': configurations.compile.collect { it.getName() }.join(' '),
                'Main-Class': 'io.testproject.Main'
        )
    }

    from {
        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
```

**Comment by tzah4748** [comment] 2020-08-16 14:55
Up.

**Comment by john1506** [comment] 2020-09-14 11:14
I am also experiencing issues with the Logging Preferences. I am using .NET Bindings 4.0 Alpha 5, when I use 3.141.59 I don't get any performance logs at all 

If you enable more than one log provider, e.g.
`   options.SetLoggingPreference(LogType.Browser, LogLevel.All);`
`   options.SetLoggingPreference("performance", LogLevel.All);`

When I hit the session/:sessionID/se/log/types I get the following (this so far looks correct)
`{
    "value": [
        "performance",
        "browser",
        "driver"
    ]
}`

I then POST to
session/:sessionID/se/log
for performance and browser

performance response:
`{"value":[{"level":"INFO","message":"{\"message\":{\"method\":\"Page.frameResized\",\"params\":{}},\"webview\":\"C31911500512C1F05200E743F9735F01\"}","timestamp":1600078387465},{"level":"INFO","message":"{\"message\":{\"method\":\"Page.frameResized\",\"params\":{}},\"webview\":\"C31911500512C1F05200E743F9735F01\"}","timestamp":1600078387465},{"level":"INFO","message":"{\"message\":{\"method\":\"Tracing.dataCollected\",\"params\":{\"args\":{\"name\":\"CrBrowserMain\"},\"cat\":\"__metadata\",\"name\":\"thread_name\",\"ph\":\"M\",\"pid\":710,\"tid\":710,\"ts\":0}},\"webview\":\"browser\"}","timestamp":1600078407060},{"level":"INFO","message":"{\"message\":{\"method\":\"Tracing.dataCollected\",\"params\":{\"args\":{\"name\":\"Chrome_ChildIOThread\"},\"cat\":\"__metadata\",\"name\":\"thread_name\",\"ph\":\"M\",\"pid\":765,\"tid\":772,\"ts\":0}},\"webview\":\"browser\"}","timestamp":1600078407060},{"level":"INFO","message":"{\"message\":{\"method\":\"Tracing.dataCollected\",\"params\":{\"args\":{\"name\":\"CrRendererMain\"},\"cat\":\"__metadata\",\"name\":\"thread_name\",\"ph\":\"M\",\"pid\":765,\"tid\":765,\"ts\":0}},\"webview\":\"browser\"}","timestamp":1600078407060},{"level":"INFO","message":"{\"message\":{\"method\":\"Tracing.dataCollected\",\"params\":{\"args\":{\"name\":\"Chrome_HistoryThread\"},\"cat\":\"__metadata\",\"name\":\"thread_name\",\"ph\":\"M\",\"pid\":710,\"tid\":746,\"ts\":0}},\"webview\":\"browser\"}","timestamp":1600078407060},{"level":"INFO","message":"{\"message\":{\"method\":\"Tracing.dataCollected\",\"params\":{\"args\":{\"name\":\"Browser\"},\"cat\":\"__metadata\",\"name\":\"process_name\.....`

browser response:
`{
    "value": []
}`

even when there are console warnings/errors there are no browser logs provided

When I only enable the browser logging
`
   options.SetLoggingPreference(LogType.Browser, LogLevel.All);                     
`

my browser response looks like this
`{
    "value": [
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992290
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992290
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992291
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992293
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992315
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992315
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992317
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992332
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992349
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992350
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992350
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992351
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992351
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992351
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992352
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992352
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992372
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992372
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992373
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992373
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992374
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992375
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992385
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992385
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992386
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992386
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992386
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992399
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992401
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992402
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992403
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600081992418
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043318
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043330
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043331
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043331
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043331
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043331
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043332
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043332
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043332
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043332
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043333
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043333
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043334
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043334
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043334
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043335
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043335
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043336
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043336
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043337
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043337
        },
        {
            "level": "WARNING",
            "message": "https://passport-uk-pre1.airsweb.net/Js/passport-app.js?v=20200911095034 48:28 Object",
            "source": "console-api",
            "timestamp": 1600082043338
        }
    ]
}`

**Comment by tzah4748** [comment] 2020-09-16 13:47
@diemol Anything on this yet???

**Comment by diemol** [comment] 2020-09-16 13:55
@tzah4748 please provide a code to reproduce this only using Selenium, no 3rd party dependencies.

**Comment by diemol** [comment] 2020-10-10 17:44
I read all this again, and I understand that it does not work on 3.141.59, but it works in the Alphas. Which is ok since that is what will be released soon. Therefore, I will close this.

**Closed by diemol** 2020-10-10 17:44 UTC
Labels: R-awaiting answer
