### ISSUE TITLE
Actions sendKeys UnsupportedCommandException with geckodriver

### ISSUE THREAD

**Issue by kumarTech16** [SeleniumHQ/selenium#2611] opened 2016-08-14 05:50 UTC
## Meta - Unable to run the script using selenium 3.0.0 Beta 2 with geckodriver-v0.10.0-win64 driver in FF v48

OS:  Win 7 Enterprise 64 Bit

Selenium Version:  3.0.0 Beta 2, geckodriver-v0.10.0-win64, JDK 8U_102x64

Browser:  Fire Fox 48.0

Browser Version:  48.0

## Actual Behavior - The script failed with below exceptions

```
1471151803318   addons.xpi-utils    WARN    addMetadata: Add-on e10srollout@mozilla.org is invalid: [Exception... "Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]"  nsresult: "0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE)"  location: "JS frame :: resource://gre/modules/XPCOMUtils.jsm :: XPCU_serviceLambda :: line 230"  data: no] Stack trace: XPCU_serviceLambda()@resource://gre/modules/XPCOMUtils.jsm:230 < XPCU_defineLazyGetter/<.get()@resource://gre/modules/XPCOMUtils.jsm:198 < defineSyncGUID()@resource://gre/modules/addons/XPIProvider.jsm:1232 < loadManifestFromZipReader<()@resource://gre/modules/addons/XPIProvider.jsm:1440 < TaskImpl_run()@resource://gre/modules/Task.jsm:319 < Handler.prototype.process()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:937 < this.PromiseWalker.walkerLoop()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816 < this.PromiseWalker.scheduleWalkerLoop/<()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:750 < syncLoadManifestFromFile()@resource://gre/modules/addons/XPIProvider.jsm:1496 < addMetadata()@resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:1647 < processFileChanges()@resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:2011 < this.XPIProvider.checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3708 < this.XPIProvider.startup()@resource://gre/modules/addons/XPIProvider.jsm:2697 < callProvider()@resource://gre/modules/AddonManager.jsm:227 < _startProvider()@resource://gre/modules/AddonManager.jsm:778 < AddonManagerInternal.startup()@resource://gre/modules/AddonManager.jsm:962 < this.AddonManagerPrivate.startup()@resource://gre/modules/AddonManager.jsm:2934 < amManager.prototype.observe()@resource://gre/components/addonManager.js:71
1471151803319   addons.xpi-utils    WARN    Could not uninstall invalid item from locked install location
1471151803684   Marionette  INFO    Listening on port 63214
1471151804994   Marionette  INFO    startBrowser f497d69a-b705-43f8-a8c0-71627c715027
1471151805011   Marionette  INFO    sendAsync f497d69a-b705-43f8-a8c0-71627c715027
1471151805346   Marionette  INFO    sendAsync f497d69a-b705-43f8-a8c0-71627c715027
1471151805543   Marionette  INFO    sendAsync f497d69a-b705-43f8-a8c0-71627c715027
1471151817313   Marionette  INFO    sendAsync f497d69a-b705-43f8-a8c0-71627c715027
1471151817339   Marionette  INFO    sendAsync f497d69a-b705-43f8-a8c0-71627c715027
1471151817402   Marionette  INFO    sendAsync f497d69a-b705-43f8-a8c0-71627c715027
1471151817410   Marionette  INFO    sendAsync f497d69a-b705-43f8-a8c0-71627c715027
1471151817463   Marionette  INFO    sendAsync f497d69a-b705-43f8-a8c0-71627c715027
1471151817475   Marionette  INFO    sendAsync f497d69a-b705-43f8-a8c0-71627c715027
JavaScript error: resource://gre/modules/FormHistory.jsm, line 379: TypeError: Services.storage is undefined
1471151817511   Marionette  INFO    sendAsync f497d69a-b705-43f8-a8c0-71627c715027
1471151819475   Marionette  INFO    sendAsync f497d69a-b705-43f8-a8c0-71627c715027
1471151819523   Marionette  INFO    sendAsync f497d69a-b705-43f8-a8c0-71627c715027
1471151822953   Marionette  INFO    sendAsync f497d69a-b705-43f8-a8c0-71627c715027
1471151823050   Marionette  INFO    sendAsync f497d69a-b705-43f8-a8c0-71627c715027
1471151823087   Marionette  INFO    sendAsync f497d69a-b705-43f8-a8c0-71627c715027
Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: POST /session/f497d69a-b705-43f8-a8c0-71627c715027/keys did not match a known command (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5 milliseconds
Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700'
System info: host: 'IE3BLT3VB2N62', ip: '172.21.4.204', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, appBuildId=20160726073904, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, browserVersion=48.0, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: f497d69a-b705-43f8-a8c0-71627c715027
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:683)
    at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
    at org.openqa.selenium.remote.RemoteKeyboard.sendKeys(RemoteKeyboard.java:35)
    at org.openqa.selenium.interactions.SendKeysAction.perform(SendKeysAction.java:49)
    at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:50)
    at org.openqa.selenium.interactions.Actions.perform(Actions.java:373)
    at niagara4.JiraStory.main(JiraStory.java:59)
```
## Steps to reproduce - Using the below piece of code, was trying to create a story in JIRA tool, however after selecting the element called 'Story', failed to hit enter due to which the execution failed with above exception.

```
System.setProperty("webdriver.gecko.driver","C:\\Automation\\softwares\\geckodriver-v0.10.0-win64\\geckodriver.exe");       
        DesiredCapabilities capabilities = DesiredCapabilities.firefox();
        capabilities.setCapability("marionette", true);
        WebDriver driver = new FirefoxDriver(capabilities);     
        //WebDriver driver = new FirefoxDriver();
        driver.manage().timeouts().implicitlyWait(15,TimeUnit.SECONDS);
        driver.get(data00);
        WebElement uswb = driver.findElement(By.xpath("//input[@id='login-form-username']"));
        uswb.sendKeys(data01);
        WebElement pswd = driver.findElement(By.id("login-form-password"));
        pswd.sendKeys(data02);  
        driver.findElement(By.xpath("//input[@id='login']")).click();
        driver.findElement(By.xpath("//a[@href='/secure/CreateIssue!default.jspa']")).click();
        driver.findElement(By.xpath("//input[@id='issuetype-field']")).clear();
        driver.findElement(By.xpath("//input[@id='issuetype-field']")).sendKeys("Story");
        Actions act=new Actions(driver);
        act.sendKeys(Keys.ENTER).perform();
        Thread.sleep(15000);
```

**Comment by santoshchk** [comment] 2016-08-17 10:19
Same issue exits with Windows 10, 
FF = 48 
Selenium beta 3.0.0-beta2
Geockdriver =10.0
Java = 8


Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700'
System info: host: 'AUTOMATION-COE', ip: '10.129.160.99', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:670)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:247)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:232)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:220)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:215)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:124)
	at Firefox.main(Firefox.java:14)
Caused by: org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:3295 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700'
System info: host: 'AUTOMATION-COE', ip: '10.129.160.99', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:91)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:649)
	... 8 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:3295 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:142)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:88)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	... 9 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 22 more

**Comment by damorton** [comment] 2016-08-19 14:50
Same issue on Mac OSX EL Capitan

gekodriver = 10.0
selenium = 3.0.0b2
FF = 45

```
(env) macbook:test dmorton$ python test.py 
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    browser = webdriver.Firefox()
  File "/Users/dmorton/projects/spm/test/env/lib/python2.7/site-packages/selenium-3.0.0b2-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 73, in __init__
    keep_alive=True)
  File "/Users/dmorton/projects/spm/test/env/lib/python2.7/site-packages/selenium-3.0.0b2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Users/dmorton/projects/spm/test/env/lib/python2.7/site-packages/selenium-3.0.0b2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/Users/dmorton/projects/spm/test/env/lib/python2.7/site-packages/selenium-3.0.0b2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Users/dmorton/projects/spm/test/env/lib/python2.7/site-packages/selenium-3.0.0b2-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: entity not found

(env) macbook:test dmorton$ pip list
pip (8.1.2)
selenium (3.0.0b2)
setuptools (25.2.0)
wheel (0.29.0)
(env) macbook:test dmorton$ 
```

```
from selenium import webdriver

browser = webdriver.Firefox()
browser.get('http://seleniumhq.org/')

```

**Comment by lukeis** [comment] 2016-08-19 18:42
Actions end point has not been implemented in geckodriver yet. We'll need to migrate Actions class calls to the appropriate alternative in geckodriver when it's available. For the meantime I suggest attempting to use element.sendKeys rather than Actions class to type.

@santoshchk your stacktrace is completely unrelated.

**Comment by AutomatedTester** [comment] 2016-08-22 12:28
@lukeis happy for this to be dup'ed with #2285?

**Comment by lukeis** [comment] 2016-08-22 14:30
@automatedtester I'd rather not, only because the language bindings need to update their calling end points for all the actions... Unless you're volunteering to implement all of them in one bang? :)

**Comment by anukriti-chawla** [comment] 2016-10-03 12:42
It is showing the following error while using selenium 3.0.0beta4

org.openqa.selenium.WebDriverException: POST /session/4d12ff7b-ab53-4185-85a8-be3e43727838/**keys did not match a known command**

Build info: version: '3.0.0-beta4', revision: '3169782', time: '2016-09-29 10:29:23 -0700'
System info: host: 'INNOSZPC00536', ip: '10.13.64.70', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_25'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, firefoxOptions={args=[], profile=UEsDBBQACAAAAAAAAAAAAAAdXNlci5qc1BLBQYAAAAAAQABADUAAADaAwAAAAA=}, appBuildId=20160922113459, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=9360, browserVersion=49.0.1, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt, device=desktop}]
Session ID: 4d12ff7b-ab53-4185-85a8-be3e43727838
Command duration or timeout: 98 milliseconds
Build info: version: 'unknown', revision: '2aa21c1', time: '2016-08-02 14:59:43 -0700'
System info: host: 'INNOSZPC00536', ip: '10.13.64.70', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_25'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, firefoxOptions={args=[], profile=UEsAAAAAAAAAAAAAAAAAAAAAdXNlci5qc1BLBQYAAAAAAQABADUAAADaAwAAAAA=}, appBuildId=20160922113459, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=9360, webdriver.remote.sessionid=f0a1c0a6-1d22-456c-b289-ae0fde607805, browserVersion=49.0.1, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, javascriptEnabled=true, platformName=windows_nt, device=desktop, cssSelectorsEnabled=true}]
Session ID: f0a1c0a6-1d22-456c-b289-ae0fde607805

**Comment by lukeis** [comment] 2016-10-03 15:42
@anukriti-chawla the issue is still open, therefore there is no fix for it yet.

**Comment by ranjprashant** [comment] 2016-11-18 09:45
I am getting the same issue on using new Actions(driver).moveToElement(tempHeaderElement).perform();

Log:
org.openqa.selenium.UnsupportedCommandException: POST /session/58fec78f-ac07-4815-87ab-2bcd6686a200/moveto did not match a known command
Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700'
System info: host: 'DC4-QVM-TRBW-02', ip: '10.111.106.196', os.name: 'Windows Server 2012', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], profile=UEsDBBQACAgIAFsjckkAAAAAAAAAAAAAAAAHAAAAdXNlci5qc61XTW/jNhC991csfGqBmE023cv25F0nQIFgUyQbZA8BCJoaWYwpkuVQlv3vO6Ss+EuWnHZPlugZUjPz3pthheC585D/Opp5W9MbQ5FDelZmzkqha+GBgREzDdno4kMuNMJvf/5SbT0zEcjGWR+iSwFCh6J5Z2S0VHLAvz25AO3AT5xDFo9d4wQXLLdewtl+Bpb0RG4olvDdThUuyHcknNNKiqCs+b3E2vrs4sPumsTlxYcAq9A87f61NBkrcQwrCfr4H+vArEpNH1mKgGOb5xRtZmVVgqHo6TtFhgVAKDVLvxcdeztbg3dWmbB/gMvy/YXV+HAJ0x7Hhhr3F0pMAYz2E2ggUC4WrAjBMVcoLNbj+LcTiGMNZh4Kyt7HT5+68x6Do58MAsgA2a3yGCYEAqljwYKvDnFiSwLUisvC2xI4Sq9c4L4yPKgyulxfdh8UxAwZ4dDcm6/a4gAcMlsbbQWlVhgxj4gubP1cgHkkmEaIdrs7+igXMB7GS5sJPQB6WAZrNTLwniBKpbB6F+fH4aOaG2soayWUM/CP6RX7Y0FAjGUOlkjoAQlXPKcP5dILLPp9tTKLBFBOwAZvhI7FfDd181jWh8p0H1bDLPOKSMeFlEDlrAxFjgQHLsEH7M5EszUyXBvJ4trm8X+W8M1dodNiDdnN1eXjN0uIjJD5o9uYlrJ786wMHYpXl4xo6O3Tw13SjZmtwueZFmYxOsZykygutOavyCPBXOJkZ8wrp6iMZMvqQgXQCgNt8E+l/CmERXgtVGAblrapoOAixjoPeSu9oIITsfohjDGZlWMFsdHR3rwGLSMzKx+hMhoN8Cu3mvh/R5EcAytCziTossoRyoAZqkO+fiKTM+nbPkxV9BhNP7+8fH/4widVsGVStfS+fb31ooSYKf4N6peX1v2wcKcRX7lof9ObMpCVV2FNrNBATwyDVzJw69VcGe4sKe66Pz4DNUkM2+S4B2F7H9rszOLiYzUrVZKFv9PiJBHvvObcuU1vxG9KtAFLBApZnlDqreZQmHXi1DE2qEuSHYxF0+m1rflszTPIRaXDCcHYpF2i22D6nT2AbJ7bz+nwO4ZrL3NaahKPSc2DX7OmeyT7j0O2Zw1DRxHI2PmiBk6tGYj+5uluwq6Z2ALjOKWvYimaDtzbtA7L32pFP3aPY/bwmoaE3kMaasTt+3O0Uy1B9J82ivgoCXhRfK8uT/WoZlduSC+WwGlWNCc6VMfkcU+oPle5GijfJn38idq1E/dMW7lITeQsNCEIL4sNtoeiKFnDXJZVpTsLHdvIf6pWk0CcRcc93FsqtFdZd4M80u9D4b7unpAbEo5b5SI2hGpgdNvYnlDlzSg8PAPvDFiYxr/tgEXqXZ3qpjupixTpNtrRANuMLmnQ+st8bcbZ82reClRO1x4cHtJi6JsZhqdOkVEdzJyn+ndP5ln+iq3PmUDcHRwnmiZRujqQQmsYgj/d0mhGkwXIxbSh8Zfmn/fPUExkmYppFQOtvvPq/V+v3NrO53FxcyXpbe47gpIijikifs6Ujhwxal4EfWKc2XFtT3yXUrQFEk1xbn7cDAvsUbJbrtMtOjRdcRRvVR4OErwdvuMljLhLV6mB6XurnDrHyjUD4nYu/hdQSwcIZ7FvAMMEAAA5EQAAUEsBAhQAFAAICAgAWyNySWexbwDDBAAAOREAAAcAAAAAAAAAAAAAAAAAAAAAAHVzZXIuanNQSwUGAAAAAAEAAQA1AAAA+AQAAAAA}, appBuildId=20161104212021, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=8104, browserVersion=50.0, platformVersion=6.2, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt}]

**Comment by AutomatedTester** [comment] 2017-01-19 11:26
duplicate of #2285

**Closed by AutomatedTester** 2017-01-19 11:26 UTC
Labels: D-marionette, G-w3c

**Comment by xikandar** [comment] 2017-01-21 11:38
@AutomatedTester When we can expect the fix for the following issue. Also could you suggest a work around ? changing selenium to 2.x.x with older version of firefox browser would work ?

"org.openqa.selenium.UnsupportedCommandException: POST /session/96ae9ee9-6773-4b12-9967-60a8c8ee3f87/keys did not match a known command"

**Comment by shankarkc** [comment] 2017-01-21 15:43
I have seen this api was working on on Firefox 47.0.1 with selenium 2.0....
So if you rollback it should work...

**Comment by guptarajatkn** [comment] 2017-02-01 10:28
at actions.map.action (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\actions.js:124:23)
         at Array.map (native)
         at C:\UI_Automation_New\node_modules\selenium-webdriver\lib\actions.js:123:29
         at TaskQueue.execute_ (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:2970:14)
         at TaskQueue.executeNext_ (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:2953:27)
         at asyncRun (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:2860:25)
         at C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:676:7
         at process._tickCallback (internal/process/next_tick.js:103:7)
     From: Task: ActionSequence.perform
         at ActionSequence.perform (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\actions.js:122:33)
         at C:\UI_Automation_New\page-objects\addPerson_page.js:56:78
         at ManagedPromise.invokeCallback_ (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:1366:14)
         at TaskQueue.execute_ (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:2970:14)
         at TaskQueue.executeNext_ (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:2953:27)
         at asyncRun (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:2813:27)
         at C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:676:7
         at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by lmtierney** [comment] 2017-02-01 13:38
@guptarajatkn It was closed pointing to the duplicate of https://github.com/SeleniumHQ/selenium/issues/2285
