### ISSUE TITLE
Selenium 3.2 - ImplicitWait and PageLoad didn't work on FirefoxDriver

### ISSUE THREAD

**Issue by nhhphuong** [SeleniumHQ/selenium#3604] opened 2017-03-06 11:04 UTC
OS: Windows 10
Firefox: 51.0.1
Selenium WebDriver: 3.2.0

System.Environment.SetEnvironmentVariable("webdriver.gecko.driver", Directory.GetCurrentDirectory() + "\geckodriver.exe");
driver = new FirefoxDriver();
driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromMinutes(5);
driver.Manage().Timeouts().PageLoad = TimeSpan.FromSeconds(120);

==> ImplicitWait and PageLoad are work fine on ChromeDriver but it didn't work on FirefoxDriver
Result Message:	Assembly Initialization method TrainingDemo.Untitled.SetupTest threw exception. System.InvalidOperationException: System.InvalidOperationException: Missing 'type' parameter (IndexOutOfBounds). Aborting test execution.

**Comment by lmtierney** [comment] 2017-03-06 11:39
Duplicate of #3544

**Closed by lmtierney** 2017-03-06 11:39 UTC
