### ISSUE TITLE
SeleniumGrid: Unable to connect nodes to a hub that is only accessible via a hostname

### ISSUE THREAD

**Issue by timothyjmtan** [SeleniumHQ/selenium#8283] opened 2020-05-08 08:03 UTC
## 🐛 Bug Report

I have a Selenium Hub hosted on Openshift and exposed via a route, meaning that it is accessible via a hostname. 

When I attempt to launch and register a node on a different machine, I find that I am unable to register the nodes successfully if we define the hostname instead of an `<ip>:<port>` in the nodeConfig.json. 

It seems like the selenium-standalone-server-3.141.59.jar file requires a direct connection of `ip_address:4444` and cannot support hostname as a value.

The stacktrace:
```
Registering the node to the hub: http://myhostname:-1/grid/register
Couldn't register this node: Error sending the registration request: Unable to parse URL: http://myhostname:-1/grid/registerhttp://myhostname:-1/grid/register
Couldn't register this node: The hub is down or not responding: Unable to parse URL: http://myhostname:-1/grid/registerhttp://myhostname:-1/grid/api/proxyhttp://myhostname:-1/grid/registerhttp://myhostname:-1/grid/api/proxy?http://<some ip address>:80
```

I am using the node config defined here:
https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.59/java/server/src/org/openqa/grid/common/defaults/DefaultNodeWebDriver.json

## To Reproduce

Detailed steps to reproduce the behavior:
Step 1: Launch a Selenium Hub on Openshift, and expose this via a Route
Step 2: Launch a Selenium node on VDI
Step 3: In the nodeConfig.json file, define the "hub" to use the DNS instead of a port, with the syntax as `http://myhostname`

## Expected behavior

The nodes should successfully connect to the hub even if hostname instead of an ip address is defined

## Test script or set of commands reproducing this issue

I am using the nodeConfig defined here, and replacing the value of `hub` with my hostname (without port):
https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.59/java/server/src/org/openqa/grid/common/defaults/DefaultNodeWebDriver.json

## Environment

OS: Openshift (Hub) / Windows 10 (Node)
Browser: Google Chrome
Browser version: Version 80
Browser Driver version:  80.0.3987.106
Language Bindings version: OpenJDK11
Selenium Grid version (if applicable): 3.141.59

**Comment by diemol** [comment] 2020-05-22 21:41
@timothyjmtan could you please show us the actual json files used to configure the hub and node? Also the commands to start them.

**Comment by timothyjmtan** [comment] 2020-07-01 02:46
@diemol Here it is:

```
{
    "capabilities":
    [
        {
             "browserName": "chrome",
             "maxInstances": 1,
             "seleniumProtocol": "WebDriver",
             "platform": "WINDOWS",
             "version": "81.0"
         }
    ],
    "proxy": "org.openqa.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 1,
    "port": -1,
    "register": true,
    "registerCycle": 5000,
    "hub": "http://my-selenium-hub.uat.paas.xxx.com",
    "nodeStatusCheckTimeout": 60000,
    "nodePolling": 5000,
    "role": "node",
    "unregisterIfStillDownAfter": 60000,
    "downPollingLimit": 2,
    "debug": false,
    "servlets": [],
    "withoutServlets": [],
    "custom": {}
}
```

And the command was `java -jar C:\path\to\selenium-server-standalone-3.141.59.jar -role node -nodeConfig nodeConfig.json`

**Comment by diemol** [comment] 2020-07-07 12:11
@timothyjmtan why are you using `"port": -1`? That is probably the cause of the error.

**Comment by timothyjmtan** [comment] 2020-07-07 16:39
@diemol I can see why that might cause an issue, however, what should I put for the `port` then, since the hostname already fully defines the address of the hub, and there is no port number?

**Comment by diemol** [comment] 2020-07-07 16:43
You can try the default HTTP port, 80.

**Comment by diemol** [comment] 2020-07-29 21:03
Closing as we did not get more info from the OP

**Closed by diemol** 2020-07-29 21:03 UTC
Labels: C-grid, R-awaiting answer
