### ISSUE TITLE
 Timed out awaiting response to command "sendKeysToElement" after 30001 ms 

### ISSUE THREAD

**Issue by navin578** [SeleniumHQ/selenium#2249] opened 2016-06-10 05:27 UTC
I am facing timed out exception only in safari when I tried to enter value in either user-name or password field.But in same site click works fine i.e., click on Sign Up for twitter.

I have read in below link that this issue occurs when "safari is trying to access sites with CSPs (Content Security Policy) but there is no solution how to implement or how to make it work in selenium web-driver.

Link:
https://www.bountysource.com/issues/11263955-time-out-using-findelement-sendkeys-on-safari-mac-os-yosemite

I haven't found many resources regarding this issue.

When I am tried to open the link "https://api.twitter.com/oauth/authenticate?oauth_token=-Yk7MgAAAAAAXNSCAAABVTjDwx4&oauth_callback=https%3A%2F%2Fstagingbiz.bizyhood.com%2Faccounts%2Ftwitter%2Flogin%2Fcallback%2F " after that when I am trying to enter values in either password field or user-name there the exception raises.

Does this works in safari or not please help me out.

This is my first post here, please ignore if I committed any mistakes.

**Comment by jleyba** [comment] 2016-06-12 16:05
Duplicate of #458

**Closed by jleyba** 2016-06-12 16:05 UTC
