### ISSUE TITLE
[🐛 Bug]: InvalidArgumentError: unknown variant `wheel` at await driver.actions()...perform()

### ISSUE THREAD

**Issue by N1lshui** [SeleniumHQ/selenium#11253] opened 2022-11-11 11:38 UTC
### What happened?

When I try to use await driver.actions()...perform() (only with await) in firefox,
then I get error
InvalidArgumentError: unknown variant `wheel`, expected one of `none`, `key`, `pointer` at line 1 column 115
I'm not able to scroll in JS and this is a problem

### How can we reproduce the issue?

```shell
I don't know, I use normallly     await driver.actions()
                .scroll(0, 0, 0, 200)
                .perform(); for example or with pause()
That happens only in firefox
```

### Relevant log output

```shell
InvalidArgumentError: unknown variant `wheel`, expected one of `none`, `key`, `pointer` at line 1 column 115
    at Object.throwDecodedError (C:\Users\nbirken\Documents\Inside\novomind-inside\node_modules\selenium-webdriver\lib\error.js:524:15)
    at parseHttpResponse (C:\Users\nbirken\Documents\Inside\novomind-inside\node_modules\selenium-webdriver\lib\http.js:587:13)
    at Executor.execute (C:\Users\nbirken\Documents\Inside\novomind-inside\node_modules\selenium-webdriver\lib\http.js:515:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (C:\Users\nbirken\Documents\Inside\novomind-inside\node_modules\selenium-webdriver\lib\webdriver.js:741:17)
    at async Actions.perform (C:\Users\nbirken\Documents\Inside\novomind-inside\node_modules\selenium-webdriver\lib\input.js:1006:5)
...
```

### Operating System

Windows 10

### Selenium version

4.6.0

### What are the browser(s) and version(s) where you see this issue?

Firefox

### What are the browser driver(s) and version(s) where you see this issue?

Firefox

**Comment by diemol** [comment] 2022-11-11 12:32
Duplicate of #11090

**Closed as completed by diemol** 2022-11-11 12:32 UTC
Labels: C-nodejs, I-defect
