### ISSUE TITLE
[🐛 Bug]: C# Selenium 4.0 Proxy Authentication with Chrome Driver BiDi APIs freezing

### ISSUE THREAD

**Issue by yazilimprogram** [SeleniumHQ/selenium#10090] opened 2021-11-26 14:05 UTC
### What happened?

when I use the code block below, my browser does not go to the address.

```
`var options = new ChromeOptions();
options.Proxy = new Proxy {HttpProxy = "1.1.1.1:12345", SslProxy = "1.1.1.1:12345", Kind = ProxyKind.Manual};
var driver = new ChromeDriver(ChromeDriverService.CreateDefaultService(), options, TimeSpan.FromMinutes(2));

NetworkAuthenticationHandler handler = new NetworkAuthenticationHandler()
{
    UriMatcher = d => true,
    Credentials = new PasswordCredentials("proxy_user", "proxy_pass")
};

var networkInterceptor = driver.Manage().Network;
networkInterceptor.AddAuthenticationHandler(handler);
networkInterceptor.StartMonitoring();

driver.Navigate().GoToUrl("https://stackoverflow.com/");

networkInterceptor.StopMonitoring();
driver.Quit();`
```

it works if i disable this code:

`networkInterceptor.StartMonitoring();`

### How can we reproduce the issue?

```shell
but this time it doesn't verify. what can I do?

Relevant source: https://www.selenium.dev/documentation/webdriver/bidi_apis/
```

### Relevant log output

```shell
no error, freezing program.
```

### Operating System

Windows 10

### Selenium version

C#

### What are the browser(s) and version(s) where you see this issue?

Chrome 96

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Driver 96

### Are you using Selenium Grid?

4.0.0

**Comment by lopukhDA** [comment] 2021-11-29 09:39
looks like this bug [10054](https://github.com/SeleniumHQ/selenium/issues/10054)

**Comment by IlyaGav** [comment] 2021-11-30 11:18
`networkInterceptor.StartMonitoring()`  returns Task. Try to wait for it to complete first

**Comment by diemol** [comment] 2021-12-01 15:19
Duplicate of #10054

**Closed as completed by diemol** 2021-12-01 15:19 UTC
Labels: C-dotnet, I-defect
