### ISSUE TITLE
[🐛 Html Javascript Drag and Drop is not working Selenium 4.1.0]: 

### ISSUE THREAD

**Issue by kalidas3** [SeleniumHQ/selenium#10119] opened 2021-12-08 15:20 UTC
### What happened?

Hi Team,

I am trying to test drag and drop functionality with selenium but drag and drop is not working. I tried chrome & Firefox web driver latest version both are not working.

**The drop is not happening because, my mouse position is outside of browser** 

### How can we reproduce the issue?

```shell
**selenium code**
`const {Builder, By} = require('selenium-webdriver');

(async function dragAndDrop() {
  let driver = await new Builder().forBrowser('chrome').build();
  try {
    // Navigate to Url
    await driver.get('saved URL'); -- Please save the below html in your local & provide the same URL here
    // Store 'box A' as source element
    let sourceEle = driver.findElement(By.id("drag1"));
    // Store 'box B' as source element
    let targetEle = driver.findElement(By.id("div1"));
    const actions = driver.actions({async: true});
    // Performs drag and drop action of sourceEle onto the targetEle
    await actions.dragAndDrop(sourceEle, targetEle).perform();
  }
  finally {
    await driver.quit();
  }
})();`
**Html Javscript code**
`<!DOCTYPE HTML>
<html>
<head>
<style>
#div1 {
  width: 350px;
  height: 70px;
  padding: 10px;
  border: 1px solid #aaaaaa;
}
</style>
<script>
function allowDrop(ev) {
  ev.preventDefault();
}

function drag(ev) {
  ev.dataTransfer.setData("text", ev.target.id);
}

function drop(ev) {
  ev.preventDefault();
  var data = ev.dataTransfer.getData("text");
  ev.target.appendChild(document.getElementById(data));
}
</script>
</head>
<body>

<p>Drag the W3Schools image into the rectangle:</p>

<div id="div1" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
<br>
<img id="drag1" src="img_logo.gif" draggable="true" ondragstart="drag(event)" width="336" height="69">

</body>
</html>`
```

### Relevant log output

```shell
**While drag & drop Selenium web drivers is taking my system cursor - Might be the issue**
```

### Operating System

Mac

### Selenium version

Node 4.1.0

### What are the browser(s) and version(s) where you see this issue?

chrome 90

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 94

**Comment by harsha509** [comment] 2021-12-14 16:11
Hi @kalidas3,

I don't see any issue with Selenium JS bindings. The example from [here ](https://www.selenium.dev/documentation/webdriver/actions_api/mouse/#draganddrop) works fine!

Maybe the issue is with HTML code (I tried with other language bindings and the behavior is same)

Thanks,
Sri Harsha

**Comment by titusfortner** [comment] 2021-12-26 03:56
This is likely a duplicate of #9878 & #9860, all of the drivers are kind of broken on this one right now. I know it's frustrating, but there's nothing we can do in this project's code.

We just have to hope the browser vendors get this fixed soon, which we'll know when we see the tests at the bottom of the page here passing - https://wpt.fyi/results/webdriver/tests/perform_actions/pointer.py

**Closed as completed by titusfortner** 2021-12-26 03:56 UTC
Labels: J-awaiting answer, C-nodejs
