### ISSUE TITLE
[🐛 Bug]: Running Headless Chrome With Extensions in Lambda

### ISSUE THREAD

**Issue by Jonathynlee** [SeleniumHQ/selenium#13451] opened 2024-01-17 20:02 UTC
### What happened?

Hello!

I am aware this may or may not be an issue with Selenium but its a question that I would like to ask to the Selenium Community

Everything works without the chrome extension in use. Once I add in a chrome extension into options. 

driver setup
```
options.add_argument(f'--load-extension={extensionDir}')   
options.binary_location = '/opt/chrome/chrome'   
options.add_argument("--headless=new")   
options.add_argument("--disable-gpu")   
options.add_argument("--no-sandbox")   
options.add_argument("--disable-dev-shm-usage")   
options.add_argument("--disable-dev-tools")   
options.add_argument("--user-data-dir=/tmp/chrome-user-data")   
options.add_argument("--remote-debugging-port=9222")   
options.add_argument("--window-size=900,1600")   
services = webdriver.ChromeService(executable_path='/opt/chromedriver')   
driver = webdriver.Chrome(options=options, service=services)   
```
        
Logs
```
Message: session not created: Chrome failed to start: exited normally.   
(session not created: DevToolsActivePort file doesn't exist)   
(The process started from chrome location /opt/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)   
```

I have also added to the google discussion as well.

Thank you!

### How can we reproduce the issue?

```shell
options.add_argument(f'--load-extension={extensionDir}')
        options.binary_location = '/opt/chrome/chrome'
        options.add_argument("--headless=new")
        options.add_argument("--disable-gpu")
        options.add_argument("--no-sandbox")
        options.add_argument("--disable-dev-shm-usage")
        options.add_argument("--disable-dev-tools")
        options.add_argument("--user-data-dir=/tmp/chrome-user-data")
        options.add_argument("--remote-debugging-port=9222")
        options.add_argument("--window-size=900,1600")
        services = webdriver.ChromeService(executable_path='/opt/chromedriver')
        driver = webdriver.Chrome(options=options, service=services)
```

### Relevant log output

```shell
Message: session not created: Chrome failed to start: exited normally.
(session not created: DevToolsActivePort file doesn't exist)
(The process started from chrome location /opt/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

### Operating System

Linux

### Selenium version

Python 3.10.2 - Selenium 4.16.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 118.0.5993.70

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 118.0.5993.70

**Comment by titusfortner** [comment] 2024-01-17 20:14
Yeah this is a known Chrome bug.
Duplicate of #12841

**Closed as not planned by titusfortner** 2024-01-17 20:14 UTC
Labels: I-defect, A-needs-triaging

**Comment by Jonathynlee** [comment] 2024-01-17 23:17
@titusfortner how is this a duplicate of 12841?

The post you sent points to headless working fine. Additionally, they have extensions disabled. Could you please clarify?

**Comment by titusfortner** [comment] 2024-01-18 14:09
The error is a Chrome problem and the solution is linked to in the last comment of that issue. Though, looks like there is a new ticket as well — https://bugs.chromium.org/p/chromedriver/issues/detail?id=4685
