### ISSUE TITLE
[🐛 Bug]: Selenium 4.1.1 org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure

### ISSUE THREAD

**Issue by BKandukuri-clgx** [SeleniumHQ/selenium#10899] opened 2022-07-22 13:11 UTC
### What happened?

We are using serenity 3.2.4, Selenium 4.1.1 and IEDriverServer 4.3.0 for executing test cases on IE Mode of Edge. When we are executing x number of test cases in a row then in between some test cases selenium is not able to establish the connection with the browser launched by selenium. Below is the stack trace. 

### How can we reproduce the issue?

```shell
As these are in Client setup cannot share the
```

### Relevant log output

```shell
Started InternetExplorerDriver server (64-bit)
4.3.0.0
Listening on port 55336
Only local connections are allowed
00:50:25.919 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Entry count for : http://localhost:63628 : 1
00:50:25.919 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Adding Candidate expired Channel [id: 0x2634db97, L:/127.0.0.1:63314 ! R:localhost/127.0.0.1:63628] isIdleTimeoutExpired=false isRemotelyClosed=true isTtlExpired=false
00:50:25.919 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Closing Idle Channel [id: 0x2634db97, L:/127.0.0.1:63314 ! R:localhost/127.0.0.1:63628]
00:50:25.919 [AsyncHttpClient-1-1] DEBUG org.asynchttpclient.netty.channel.DefaultChannelPool - Closed 1 connections out of 1 in 0 ms
00:50:26.087 [AsyncHttpClient-1-2] DEBUG org.asynchttpclient.netty.channel.NettyConnectListener - Using new Channel '[id: 0x7378f161, L:/127.0.0.1:63319 - R:localhost/127.0.0.1:55336]' for 'POST' to '/session'
00:53:26.115 [AsyncHttpClient-1-2] DEBUG org.asynchttpclient.netty.handler.HttpHandler - Channel Closed: [id: 0x7378f161, L:/127.0.0.1:63319 ! R:localhost/127.0.0.1:55336] with attribute NettyResponseFuture{currentRetry=0,
	isDone=0,
	isCancelled=0,
	asyncHandler=org.asynchttpclient.AsyncCompletionHandlerBase@19bd2cb,
	nettyRequest=org.asynchttpclient.netty.request.NettyRequest@67a6cf53,
	future=java.util.concurrent.CompletableFuture@46c8385[Not completed],
	uri=http://localhost:55336/session,
	keepAlive=true,
	redirectCount=0,
	timeoutsHolder=org.asynchttpclient.netty.timeout.TimeoutsHolder@34ec86a1,
	inAuth=0,
	touch=1658389826087}
00:53:26.115 [AsyncHttpClient-1-2] DEBUG org.asynchttpclient.netty.request.NettyRequestSender - Trying to recover request DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
POST /session HTTP/1.1
User-Agent: selenium/4.1.2 (java windows)
Content-Length: 1108
Content-Type: application/json; charset=utf-8
host: localhost:55336
accept: */*

|-- Open browser in maximise mode
00:53:26.669 [main] INFO  - STEP ERROR: net.serenitybdd.core.exceptions.SerenityManagedException: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
      net.serenitybdd.core.exceptions.SerenityManagedException: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
	at core.EdgeIE.newDriver(EdgeIE.java:28)
	at net.serenitybdd.core.webdriver.driverproviders.ProvidedDriverProvider.newInstance(ProvidedDriverProvider.java:22)
	at net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:157)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:136)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:143)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:134)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:104)
	at net.thucydides.core.webdriver.WebDriverFacade.manage(WebDriverFacade.java:334)
	at csm_pfm.com.stepdefinitions.core.BaseSteps.openBrowserInMaximiseMode(BaseSteps.java:55)
	at csm_pfm.com.stepdefinitions.core.BaseSteps$ByteBuddy$8VEswRYF.openBrowserInMaximiseMode$accessor$hptB7YcJ(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.thucydides.core.steps.BaseMethodRunner.invokeMethod(BaseMethodRunner.java:18)
	at net.thucydides.core.steps.NormalMethodRunner.invokeMethodAndNotifyFailures(NormalMethodRunner.java:18)
	at net.thucydides.core.steps.StepInterceptor.runNormalMethod(StepInterceptor.java:406)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:191)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:84)
	at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)
	at csm_pfm.com.stepdefinitions.core.BaseSteps$ByteBuddy$8VEswRYF.openBrowserInMaximiseMode(Unknown Source)
	at csm_pfm.com.stepdefinitions.core.BaseDefinitions.setUp(BaseDefinitions.java:19)
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:585)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:248)
	at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:188)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:180)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:156)
	at core.EdgeIE.newDriver(EdgeIE.java:24)
	at net.serenitybdd.core.webdriver.driverproviders.ProvidedDriverProvider.newInstance(ProvidedDriverProvider.java:22)
	at net.thucydides.core.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:157)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:136)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:143)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:134)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:104)
	at net.thucydides.core.webdriver.WebDriverFacade.manage(WebDriverFacade.java:334)
	at csm_pfm.com.stepdefinitions.core.BaseSteps.openBrowserInMaximiseMode(BaseSteps.java:55)
	at csm_pfm.com.stepdefinitions.core.BaseSteps$ByteBuddy$8VEswRYF.openBrowserInMaximiseMode$accessor$hptB7YcJ(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.thucydides.core.steps.BaseMethodRunner.invokeMethod(BaseMethodRunner.java:18)
	at net.thucydides.core.steps.NormalMethodRunner.invokeMethodAndNotifyFailures(NormalMethodRunner.java:18)
	at net.thucydides.core.steps.StepInterceptor.runNormalMethod(StepInterceptor.java:406)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:191)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:84)
	at net.thucydides.core.steps.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:51)
	at csm_pfm.com.stepdefinitions.core.BaseSteps$ByteBuddy$8VEswRYF.openBrowserInMaximiseMode(Unknown Source)
	at csm_pfm.com.stepdefinitions.core.BaseDefinitions.setUp(BaseDefinitions.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
	at io.cucumber.java.Invoker.invoke(Invoker.java:24)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaHookDefinition.execute(JavaHookDefinition.java:64)
	at io.cucumber.core.runner.CoreHookDefinition.execute(CoreHookDefinition.java:46)
	at io.cucumber.core.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:21)
	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:86)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:57)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:89)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.lambda$run$0(PickleRunners.java:151)
	at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$3(CucumberExecutionContext.java:151)
	at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:151)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:148)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:144)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:28)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at io.cucumber.junit.FeatureRunner.run(FeatureRunner.java:137)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:258)
	at io.cucumber.junit.CucumberSerenityRunner.runChild(CucumberSerenityRunner.java:58)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at io.cucumber.junit.CucumberSerenityRunner$RunCucumber.evaluate(CucumberSerenityRunner.java:287)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:237)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'CRDQN1VQPFMAP50', ip: '10.215.104.90', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_161'
Driver info: driver.version: InternetExplorerDriver
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:72)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:51)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:124)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:102)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:567)
	... 74 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:206)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:66)
```

### Operating System

Microsoft 2012 server R2

### Selenium version

serenity 3.2.4, Selenium 4.1.1 and IEDriverServer 4.3.0

### What are the browser(s) and version(s) where you see this issue?

MSEdge - 103.0.1264.49

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer - 4.3.0

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment] 2022-07-22 17:48
I suspect there is a race condition for the driver service to stop and restart. I think Selenium could benefit by adding a toggle not to stop the service when the session is stopped. In the meantime, try adding a sleep in between stop/start and see if you still have the issue.

**Comment by diemol** [comment] 2022-08-03 12:15
Aside from what we commented above, is there a way for us to reproduce this?

**Comment by diemol** [comment] 2022-08-08 09:38
I will close this since we never got any reply from the OP.

**Closed as completed by diemol** 2022-08-08 09:38 UTC
Labels: J-awaiting answer, D-IE, I-defect, D-edge
