### ISSUE TITLE
Unable to connect to Selenium Grid  with Webdriver 3.4.0

### ISSUE THREAD

**Issue by JoseFerreiraGlintt** [SeleniumHQ/selenium#3939] opened 2017-04-28 10:52 UTC
## Meta -
OS:  
Windows 10

Selenium Version:  
3.4.0

Browser:  
N.A.

Browser Version:  
N.A.

## Expected Behavior -
Connection to the grid with sucess

## Actual Behavior -
Unable to connect to grid. Exception trown with empty text when invoking RemoteWebDriver.
![image](https://cloud.githubusercontent.com/assets/28139879/25525562/6b868d00-2c07-11e7-9644-4accca3ce424.png)

e.StackTrace:
   _at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
   at Test.Tests.Test.Initialize()_

Works with Webdriver 3.3.0
Doesn't work with Webdriver 3.4.0
![image](https://cloud.githubusercontent.com/assets/28139879/25525733/30743950-2c08-11e7-92da-2471b52a2dd9.png)

Grid: selenium-server-standalone-3.4.0
![image](https://cloud.githubusercontent.com/assets/28139879/25523175/9c9f9328-2bfd-11e7-85b3-e5af24b065de.png)

Can you please advise?
Thanks.

## Steps to reproduce -

```
Uri hub;
DesiredCapabilities capability = new DesiredCapabilities();
ChromeOptions chromeOptions = new ChromeOptions();

chromeOptions.AddArgument("--start-maximized");
chromeOptions.AddArguments("disable-infobars");
capability = chromeOptions.ToCapabilities() as DesiredCapabilities;

capability.SetCapability("browserName", "chrome");

hub = new Uri("http://localhost:4444/wd/hub");

try
{
	driver = new RemoteWebDriver(hub, capability);
	driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(30);
	driver.Navigate().GoToUrl("https://github.com/");
	driver.Quit();
}
catch (Exception e)
{
	Console.WriteLine(e);
}
```

**Comment by jimevans** [comment] 2017-04-28 17:17
Duplicate of #3929

**Closed by jimevans** 2017-04-28 17:17 UTC
