### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by rajukthomas** [SeleniumHQ/selenium#12537] opened 2023-08-11 19:24 UTC
### What happened?

When CPU usage higher on Grid Node JdkHttpClient timeout on session closure resulting in node becoming unstable and unresponsive 

### How can we reproduce the issue?

```shell
TestNG with parallel 8tests with 2 nodes with 4 vcpus on Azure
```

### Relevant log output

```shell
)"}}

17:52:25.147 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "da02754b7e4ee4318198d9117948c45a","eventTime": 1691776345146508900,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "192.0.1.15:5567","http.method": "POST","http.request_content_length": "160","http.scheme": "HTTP","http.status_code": 404,"http.target": "\u002fsession\u002f9db475830a2dd6f076a49be03e30885a\u002fexecute\u002fsync","http.user_agent": "selenium\u002f4.11.0 (java windows)"}}

18:01:16.679 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "ef4f39b18d8ee8d957dba4c703e9fada","eventTime": 1691776876677356200,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "192.0.1.15:5567","http.method": "POST","http.request_content_length": "160","http.scheme": "HTTP","http.status_code": 404,"http.target": "\u002fsession\u002ffcb38ef4af54a1606cc2d2f8b2794e17\u002fexecute\u002fsync","http.user_agent": "selenium\u002f4.11.0 (java windows)"}}

18:02:01.174 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "ef4f39b18d8ee8d957dba4c703e9fada","eventTime": 1691776921172737700,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "192.0.1.15:5567","http.method": "POST","http.request_content_length": "160","http.scheme": "HTTP","http.status_code": 404,"http.target": "\u002fsession\u002ffcb38ef4af54a1606cc2d2f8b2794e17\u002fexecute\u002fsync","http.user_agent": "selenium\u002f4.11.0 (java windows)"}}

18:02:41.432 WARN [SpanWrappedHttpHandler.execute] - Unable to execute request: java.net.http.HttpTimeoutException: request timed out
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.18'
Driver info: driver.version: unknown
org.openqa.selenium.TimeoutException: java.net.http.HttpTimeoutException: request timed out
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.18'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:381)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:347)
        at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)
        at org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:91)
        at org.openqa.selenium.grid.node.DefaultActiveSession.execute(DefaultActiveSession.java:52)
        at org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:126)
        at org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:628)
        at org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)
        at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:384)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
        at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:91)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:347)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
        at org.openqa.selenium.grid.node.Node.execute(Node.java:262)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:347)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
        at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
        at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.http.HttpTimeoutException: request timed out
        at java.net.http/jdk.internal.net.http.ResponseTimerEvent.handle(ResponseTimerEvent.java:63)
        at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1248)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:877)
18:02:42.495 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to execute request: java.net.http.HttpTimeoutException: request timed out
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.18'
Driver info: driver.version: unknown
18:02:43.486 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.TimeoutException: java.net.http.HttpTimeoutException: request timed out
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.18'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:381)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:347)
        at org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)
        at org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:91)
        at org.openqa.selenium.grid.node.DefaultActiveSession.execute(DefaultActiveSession.java:52)
        at org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:126)
        at org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:628)
        at org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)
        at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:384)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
        at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:91)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:347)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
        at org.openqa.selenium.grid.node.Node.execute(Node.java:262)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:347)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
        at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
        at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.http.HttpTimeoutException: request timed out
        at java.net.http/jdk.internal.net.http.ResponseTimerEvent.handle(ResponseTimerEvent.java:63)
        at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1248)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:877)

18:02:44.144 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "b9c7ec0b9d0af97ca9949b8e32930066","eventTime": 1691776961430570500,"eventName": "exception","attributes": {"exception.message": "Unable to execute request: java.net.http.HttpTimeoutException: request timed out\nBuild info: version: '4.11.0', revision: '040bc5406b'\nSystem info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.18'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.TimeoutException: java.net.http.HttpTimeoutException: request timed out\nBuild info: version: '4.11.0', revision: '040bc5406b'\nSystem info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.18'\nDriver info: driver.version: unknown\r\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:381)\r\n\tat org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)\r\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)\r\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:347)\r\n\tat org.openqa.selenium.remote.tracing.TracedHttpClient.execute(TracedHttpClient.java:54)\r\n\tat org.openqa.selenium.grid.web.ReverseProxyHandler.execute(ReverseProxyHandler.java:91)\r\n\tat org.openqa.selenium.grid.node.DefaultActiveSession.execute(DefaultActiveSession.java:52)\r\n\tat org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:126)\r\n\tat org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:628)\r\n\tat org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)\r\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:384)\r\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\r\n\tat org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:91)\r\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\r\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:347)\r\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\r\n\tat org.openqa.selenium.grid.node.Node.execute(Node.java:262)\r\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:347)\r\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\r\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\r\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\r\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\r\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\r\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\r\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\r\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\r\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\r\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\r\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\r\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\r\nCaused by: java.net.http.HttpTimeoutException: request timed out\r\n\tat java.net.http\u002fjdk.internal.net.http.ResponseTimerEvent.handle(ResponseTimerEvent.java:63)\r\n\tat java.net.http\u002fjdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1248)\r\n\tat java.net.http\u002fjdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:877)\r\n","exception.type": "org.openqa.selenium.TimeoutException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "192.0.1.15:5567","http.method": "POST","http.request_content_length": "160","http.scheme": "HTTP","http.target": "\u002fsession\u002f42f3cc1f9ea0a8b17e7754a61f282584\u002fexecute\u002fsync","http.user_agent": "selenium\u002f4.11.0 (java windows)"}}

18:02:59.502 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "b9c7ec0b9d0af97ca9949b8e32930066","eventTime": 1691776979500982100,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "192.0.1.15:5567","http.method": "POST","http.request_content_length": "160","http.scheme": "HTTP","http.status_code": 404,"http.target": "\u002fsession\u002f42f3cc1f9ea0a8b17e7754a61f282584\u002fexecute\u002fsync","http.user_agent": "selenium\u002f4.11.0 (java windows)"}}

18:04:21.500 INFO [OsProcess.destroy] - Unable to drain process streams. Ignoring but the exception being swallowed follows.
org.apache.commons.exec.ExecuteException: The stop timeout of 2000 ms was exceeded (Exit value: -559038737)
        at org.apache.commons.exec.PumpStreamHandler.stopThread(PumpStreamHandler.java:295)
        at org.apache.commons.exec.PumpStreamHandler.stop(PumpStreamHandler.java:180)
        at org.openqa.selenium.os.OsProcess.destroy(OsProcess.java:144)
        at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:142)
        at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:293)
        at org.openqa.selenium.grid.node.config.DriverServiceSessionFactory$1.stop(DriverServiceSessionFactory.java:203)
        at org.openqa.selenium.grid.node.DefaultActiveSession.execute(DefaultActiveSession.java:54)
        at org.openqa.selenium.grid.node.local.SessionSlot.execute(SessionSlot.java:126)
        at org.openqa.selenium.grid.node.local.LocalNode.executeWebDriverCommand(LocalNode.java:628)
        at org.openqa.selenium.grid.node.ForwardWebDriverCommand.execute(ForwardWebDriverCommand.java:35)
        at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:384)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
        at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:91)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:347)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
        at org.openqa.selenium.grid.node.Node.execute(Node.java:262)
        at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:347)
        at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
        at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
        at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
        at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
        at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
18:04:21.503 ERROR [OsProcess.destroy] - Unable to kill process Process[pid=8628, exitValue=1]
18:04:21.509 INFO [SessionSlot.stop] - Stopping session 9db475830a2dd6f076a49be03e30885a
```

### Operating System

Windows Server 2019

### Selenium version

Java 11, Selenium Grid 4.11.0

### What are the browser(s) and version(s) where you see this issue?

chrome browserVersion: 115.0.5790.171

### What are the browser driver(s) and version(s) where you see this issue?

chromedriverVersion: 115.0.5790.170

### Are you using Selenium Grid?

4.11.0

**Comment by diemol** [comment] 2023-08-23 16:21
How can we reproduce this? All I see in the log is a request that times out, and the reason could be anything. To me, it seems a valid timeout when interacting with the system under test.

We need more details to troubleshoot this.

**Comment by diemol** [comment] 2023-11-24 15:42
I will close this as we did not get more information from the OP. We can reopen it in case more information is provided.

**Closed as not planned by diemol** 2023-11-24 15:42 UTC
Labels: B-grid, I-defect, J-issue-template
