### ISSUE TITLE
[🐛 Bug]: C# unable to enable performance logging for Chrome

### ISSUE THREAD

**Issue by pgaria** [SeleniumHQ/selenium#12188] opened 2023-06-09 18:27 UTC
### What happened?

I have tried to collect the chrome performance log using latest Selenium 4.8.0 and I tried with the lower versions as well already and its not working as expected. 

This issue was present in the past but was resolved i guess but then its started happening again with the RemoteDriver. https://github.com/SeleniumHQ/selenium/issues/7335

After doing some little debug on the Build i can see that the following command calls itself are missing in the RemoteDriver Instance and this might be the Issue. 
 {DriverCommand.GetAvailableLogTypes,new HttpCommandInfo(HttpCommandInfo.GetCommand, "/session/{sessionId}/se/log/types")},
{DriverCommand.GetLog,new HttpCommandInfo(HttpCommandInfo.PostCommand, "/session/{sessionId}/se/log")}
      

### How can we reproduce the issue?

```shell
I am using the simple Chrome Option like this to enable the Performance Logs in Chrome using RemoteDriver:
ChromeOptions driverOptions= new ChromeOptions();
var perfLoggingPrefs = new ChromiumPerformanceLoggingPreferences
{
                IsCollectingNetworkEvents = true,
                IsCollectingPageEvents = false
};
driverOptions.SetLoggingPreference(LogType.Performance, LogLevel.All); 
driverOptions.PerformanceLoggingPreferences = perfLoggingPrefs;

And Trying to print the Logs 
IWebDriver driver = new RemoteWebDriver(new Uri(seleniumUri), driverOptions.ToCapabilities());
ReadOnlyCollection<LogEntry> logs = _driver.Manage().Logs.GetLog(LogType.Performance);
System.Console.WriteLine("Found Logs:" + logs.Count);

This always results as 0 count but the same code using Java Library of WebDriver works fine with same setup.
```

### Relevant log output

```shell
OpenQA.Selenium.WebDriverArgumentException : invalid argument: log type ‘performance’ not found (Session info: chrome=114.0.5735.16)
```

### Operating System

Windows 10

### Selenium version

C# 4.8.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 114

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 114.0

**Comment by titusfortner** [comment] 2023-06-10 01:12
Duplicate of #10949

**Closed as completed by titusfortner** 2023-06-10 01:12 UTC
Labels: I-defect, A-needs-triaging
