### ISSUE TITLE
After operation on the page at 1st url, the 2nd url is not loaded by webdriver leading to fails in locating elements

### ISSUE THREAD

**Issue by yashaka** [SeleniumHQ/selenium#463] opened 2015-04-17 13:26 UTC
The following java code

``` java
package ua.net.itlabs;

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class TwoUrlsTest {

    @Test
    public void test2Urls(){
        WebDriver d = new FirefoxDriver();
        d.get("http://google.com/ncr");
        d.findElement(By.cssSelector("[name='q']")).sendKeys("something");
        d.findElement(By.cssSelector("[name='q']")).sendKeys(Keys.RETURN);
        d.get("http://todomvc.com/examples/troopjs_require/#/");
        d.findElement(By.cssSelector("#new-todo")).sendKeys("task1");
    }
}
```

leads to `org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"css selector","selector":"#new-todo"}`

Full error message at: https://www.refheap.com/99721

The reason is: webdriver did not loaded 2nd url, at `d.get("http://todomvc.com/examples/troopjs_require/#/");` and did tell nothing about this. At least the latter "wordless ignoring" seems buggy.

Versions:
Selenium 2.45.0
Firefox 34

P.S.
The same in python (see example in https://www.refheap.com/99717)

**Comment by ddavison** [comment] 2015-04-17 13:51
Reproduced using bleeding edge development version of Selenium.  The problem seems to be rooted with

```java
d.findElement(By.cssSelector("[name='q']")).sendKeys(Keys.RETURN);
```

**Comment by joshbruning** [comment] 2015-05-23 01:34
For what it's worth, I was able to reproduce and at least have a clear workaround for when this is observed.

sendKeys(Keys.RETURN) causes navigation event to occur. I was able to get the test to pass consistently by waiting for the condition expected by the RETURN press to be satisfied, adding (after that sendKeys):
new WebDriverWait(d, 5).until(ExpectedConditions.presenceOfAllElementsLocatedBy(By.id("top_nav")));

**Comment by barancev** [comment] 2017-08-27 17:28
Maybe the target site has been changed, but "#new-todo" is an invalid selector at present. It should be ".new-todo", and with this selector I can't reproduce the issue, it works for me in FF 52 + legacy mode and FF nightly + geckodriver. Closing the issue as resolved.

**Closed by barancev** 2017-08-27 17:28 UTC
Labels: D-firefox
