### ISSUE TITLE
[🐛 Bug]: Selenium 4 Java does not support authenticated proxy to connect to remote webdriver

### ISSUE THREAD

**Issue by girtsn** [SeleniumHQ/selenium#10231] opened 2022-01-07 12:46 UTC
### What happened?

Hello, using Selenium 4.1.1 from Java - our setup has a corporate authenticated proxy needed to get to a Selenium grid connection

### How can we reproduce the issue?

```shell
The documented ways to do authentication with Proxy, e.g. setting system properties or Authenticator handler like below, works in the sense that it tries to use the proxy, but does not perform the authentication. Doing the same for an http connection works so must be specific to http connection implementation. netty has ProxyHandler and an authentication scheme (https://netty.io/4.1/api/io/netty/handler/proxy/ProxyHandler.html) but not sure how to apply it when setting up the remote driver

        System.getProperties().put("http.proxyHost", proxyHost);
        System.getProperties().put("http.proxyPort", proxyPort);
        System.getProperties().put("http.proxyUser", proxyUser);
        System.getProperties().put("http.proxyPassword", proxyPassword);

        System.getProperties().put("https.proxyHost", proxyHost);
        System.getProperties().put("https.proxyPort", proxyPort);
        System.getProperties().put("https.proxyUser", proxyUser);
        System.getProperties().put("https.proxyPassword", proxyPassword);

        Authenticator.setDefault(new Authenticator() {
            public PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(proxyUser, proxyPassword.toCharArray());
            }
        } );

        WebDriver driver = new RemoteWebDriver(new URL("http://10.0.0.1/wd/hub"), options);
```

### Relevant log output

```shell
no log output
```

### Operating System

Windows 10

### Selenium version

Java 4.1.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 96

### What are the browser driver(s) and version(s) where you see this issue?

Remote

### Are you using Selenium Grid?

4.1.1

**Comment by diemol** [comment] 2022-01-08 22:26
```
        Authenticator.setDefault(new Authenticator() {
            public PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(proxyUser, proxyPassword.toCharArray());
            }
        } );
```

this is meant to be used to authenticate to the system under test, not the Grid. What happens if you only use the proxy?

**Comment by girtsn** [comment] 2022-01-08 22:44
The problem here is the corporate proxy needs http basic realm authentication, when using a proxy that does not need authentication, the system properties of proxy host and proxy port indeed do the job and the tests connect to the grid behind that proxy.
However, we have to use a corporate authenticated proxy to connect to the grid.

It looks like the system properties to pass the username and password to the proxy (proxyUser & proxyPassword) are not taken into account in the way how Selenium 4 is initializing grid http connections (using Netty?), only the host and port are. Suppose there should be a way to do this with Netty but I did not find an example how.

**Comment by diemol** [comment] 2022-01-08 22:46
You can create a `ClientConfig` and pass it in the `RemoteWebDriverBuilder`.

**Comment by girtsn** [comment] 2022-01-11 18:06
> You can create a `ClientConfig` and pass it in the `RemoteWebDriverBuilder`.

I tried but it seems it is ignoring the .proxy(proxy) set even if it does not need authentication - getting a connection timeout same as without a proxy.
And, if setting the proxy via http.proxyHost and http.proxyPort system properties and using the RemoteWebDriverBuilder, it connects to the grid but then tries to talk to destination instances directly which is not possible as they are not besides the grid itself.

        ChromeOptions browserOptions = new ChromeOptions();
        //browserOptions.setAcceptInsecureCerts(true);
        Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("locahost", 8000));
        ClientConfig config = ClientConfig.defaultConfig()
                  .baseUrl(new URL("http://gridurlbehind-proxy/wd/hub"))
                  .proxy(proxy);
        System.out.println("client config: " + config.toString());
        WebDriver driver = RemoteWebDriver.builder()
                .oneOf(browserOptions)
                .config(config)
                .build();

**Comment by diemol** [comment] 2022-01-12 09:25
>it tries to talk to destination instances directly which is not possible as they are not besides the grid itself.

what does this mean?

**Comment by diemol** [comment] 2022-01-12 09:25
Also, could you provide the a code snippet to understand how things are being set? How is the proxy configured? Is there one we can use to troubleshoot this?

**Comment by girtsn** [comment] 2022-01-12 11:24
> > it tries to talk to destination instances directly which is not possible as they are not besides the grid itself.
> 
> what does this mean?
That the grid is installed in another subnet, which is only available by going through the proxy, e.g. http://10.0.0.4/wd/hub and the grid is a docker setup with nodes running in docker network with internal addresses like "172.0.0.4"
When connecting to the grid by passing ClientConfig as in the snipped above (and using non-authenticated proxy for the test as authentication does not work), it gives an exception:
org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://172.0.0.4:4444/session/c5598a895a46d210d28c64cca1218c08/se/cdp

default initialization not using the ClientConfig does not have this issue

        ChromeOptions options = new ChromeOptions();
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(ChromeOptions.CAPABILITY, options);
       WebDriver driver = new RemoteWebDriver(new URL("http://10.0.0.4/wd/hub"), options);

**Comment by diemol** [comment] 2022-01-12 11:28
You get this:
>org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://172.0.0.4:4444/session/c5598a895a46d210d28c64cca1218c08/se/cdp

Because the Grid url needs to be set, please check https://www.selenium.dev/documentation/grid/configuration/cli_options/#node

**Comment by girtsn** [comment] 2022-01-12 11:46
> Also, could you provide the a code snippet to understand how things are being set? How is the proxy configured? Is there one we can use to troubleshoot this?

I already provided the snipped used, it was not formatted well by using the code markup so I removed and now it looks better. You could use squid to test - it has to be configured with Basic authentication to have the same setup we do, https://wiki.squid-cache.org/Features/Authentication

**Comment by girtsn** [comment] 2022-01-12 11:51
> You get this:
> 
> > org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://172.0.0.4:4444/session/c5598a895a46d210d28c64cca1218c08/se/cdp
> 
> Because the Grid url needs to be set, please check https://www.selenium.dev/documentation/grid/configuration/cli_options/#node

I don't think this is about grid setup, as mentioned "default initialization not using the ClientConfig does not have this issue" - I can successfully connect to grid and execute tests if initializing the remote connection in the default way (without passing ClientConfig)

**Comment by sumanguduru** [comment] 2022-02-09 14:18
@diemol **Im having similar issues when connecting Remotewebdriver with proxy(no authenticatoin) , im using below code snippet to connect to Browserstack**

URL browserStackHubURL = new URL("https://:<>[key@hub.browserstack.com](mailto:key@hub.browserstack.com)/wd/hub");
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("browserName", "chrome");
HashMap<String, Object> browserstackOptions = new HashMap<>();
browserstackOptions.put("os", "Windows");
browserstackOptions.put("osVersion", "10");
browserstackOptions.put("buildName", "BStack-[Java] Selenium 4 Sample Test");
browserstackOptions.put("sessionName", "Selenium 4 test");
browserstackOptions.put("seleniumVersion", "4.0.0");
capabilities.setCapability("bstack:options", browserstackOptions);
capabilities.setCapability(CapabilityType.BROWSER_NAME, "Chrome");
capabilities.setCapability(CapabilityType.BROWSER_VERSION, "97");

    InetSocketAddress inetSocketAddress = new InetSocketAddress(Constants.BS_PROXY_HOST, Constants.BS_PROXY_PORT);
  
    ClientConfig config = ClientConfig.defaultConfig()
            .readTimeout(Duration.ofSeconds(60))
            .baseUrl(browserStackHubURL)
            .proxy(new Proxy(HTTP, inetSocketAddress));

    WebDriver driver = RemoteWebDriver.builder()
            .oneOf(capabilities)
            .config(config)
            .build();
            
            
            **Stacktrace**
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: java.net.ConnectException: connection timed out: hub.browserstack.com/207.254.8.8:443
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'myhost', ip: 'myip', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.49.1.el7.x86_64', java.version: '11.0.1'
Driver info: driver.version: unknown
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
at org.openqa.selenium.remote.RemoteWebDriverBuilder.getRemoteDriver(RemoteWebDriverBuilder.java:387)
at org.openqa.selenium.remote.RemoteWebDriverBuilder.build(RemoteWebDriverBuilder.java:360)
at com.mastercard.commercial.track.testrunners.RunCucumber.beforeClass(RunCucumber.java:86)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)
at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:367)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)
at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:367)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.apache.maven.surefire.junitcore.pc.ParallelComputerBuilder$PC$1.run(ParallelComputerBuilder.java:590)
at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

**Comment by sumanguduru** [comment] 2022-02-09 14:19
However if i set system proxies before the above code snippets its connecting to remoteWebdriver without any issues, But i cant use useSystemProxies because it's blocking some of the API calls i'm making inside the test suite.

   System.setProperty("java.net.useSystemProxies", "true");
    System.setProperty("http.proxyHost", Constants.BS_PROXY_HOST);
    System.setProperty("http.proxyPort", String.valueOf(Constants.BS_PROXY_PORT))

**Comment by sumanguduru** [comment] 2022-02-09 18:49
The below code snippet is from NettyClient.java (selenium)
      ```
  .setNettyTimer(TIMER)
        .setRequestTimeout(toClampedInt(config.readTimeout().toMillis()))
        .setConnectTimeout(toClampedInt(config.connectionTimeout().toMillis()))
        .setReadTimeout(toClampedInt(config.readTimeout().toMillis()));
        .setReadTimeout(toClampedInt(config.readTimeout().toMillis()))
        .setUseProxyProperties(true)
        .setUseProxySelector(true);
```

**should this be missing  proxy server details which user is passing through Client config. but im not sure though**


` .setProxyServer(new ProxyServer.Builder("config.proxy().address()",11).build())`

**Comment by diemol** [comment] 2022-02-11 08:56
I have confirmed this, setting a proxy is not working currently. I have a local fix for this and will push it soon. However, a new release will need a few days.

**Closed as completed** 2022-02-11 09:17 UTC
Labels: J-awaiting answer, C-java, I-defect

**Comment by diemol** [comment] 2022-02-11 09:24
This will be part of the next release, either 4.1.3 or 4.2.0. Here is a code snippet that will make this work:

```java
  public static void main (String[] args) throws MalformedURLException {
    ChromeOptions browserOptions = new ChromeOptions();
    // Proxy started with https://github.com/diemol/squid-with-basic-auth
    Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("localhost", 3128));
    ClientConfig config = ClientConfig.defaultConfig()
      .baseUrl(new URL("http://192.168.1.7:4444"))
      .authenticateAs(new UsernameAndPassword("docker-proxy", "selenium"))
      .proxy(proxy);
    WebDriver driver = RemoteWebDriver.builder()
      .oneOf(browserOptions)
      .config(config)
      .build();
    driver.get("https://selenium.dev");
    driver.quit();
  }
```

**Comment by sumanguduru** [comment] 2022-02-15 16:10
@diemol,  Any idea when this fix will be available?
