### ISSUE TITLE
[🐛 Bug]: wrong number of arguments for common/logger `initialize'

### ISSUE THREAD

**Issue by Pepan** [SeleniumHQ/selenium#12013] opened 2023-05-09 13:28 UTC
### What happened?

Running system tests fails with 
```
Minitest::UnexpectedError: ArgumentError: wrong number of arguments (given 2, expected 0..1)

/Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/logger.rb:51:in `initialize'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/capybara-3.39.0/lib/capybara/selenium/logger_suppressor.rb:8:in `initialize'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver.rb:99:in `new'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver.rb:99:in `logger'
...

### How can we reproduce the issue?

```shell
Just update to latest VERSION: 4.9.1 and run system tests under rails
```

### Relevant log output

```shell
Minitest::UnexpectedError: ArgumentError: wrong number of arguments (given 2, expected 0..1)
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/logger.rb:51:in `initialize'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/capybara-3.39.0/lib/capybara/selenium/logger_suppressor.rb:8:in `initialize'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver.rb:99:in `new'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver.rb:99:in `logger'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/service_manager.rb:81:in `build_process'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/service_manager.rb:103:in `start_process'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/service_manager.rb:57:in `block in start'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/socket_lock.rb:42:in `locked'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/service_manager.rb:55:in `start'
    <internal:kernel>:90:in `tap'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/service.rb:91:in `launch'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/driver.rb:334:in `service_url'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/local_driver.rb:28:in `initialize_local_driver'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/chrome/driver.rb:34:in `initialize'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/driver.rb:47:in `new'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/driver.rb:47:in `for'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver.rb:88:in `for'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/capybara-3.39.0/lib/capybara/selenium/driver.rb:83:in `browser'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/actionpack-6.1.7.3/lib/action_dispatch/system_testing/driver.rb:48:in `block in register_selenium'
    <internal:kernel>:90:in `tap'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/actionpack-6.1.7.3/lib/action_dispatch/system_testing/driver.rb:47:in `register_selenium'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/actionpack-6.1.7.3/lib/action_dispatch/system_testing/driver.rb:35:in `block in register'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/capybara-3.39.0/lib/capybara/session.rb:105:in `driver'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/capybara-3.39.0/lib/capybara/session.rb:91:in `initialize'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/capybara-3.39.0/lib/capybara.rb:421:in `new'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/capybara-3.39.0/lib/capybara.rb:421:in `block in session_pool'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/capybara-3.39.0/lib/capybara.rb:317:in `current_session'
    /Users/josefchmel/.rvm/gems/ruby-3.0.0/gems/capybara-3.39.0/lib/capybara/dsl.rb:46:in `page'
```

### Operating System

macOS Ventura

### Selenium version

Ruby selenium-webdriver 4.9.1

### What are the browser(s) and version(s) where you see this issue?

113.0.5672.92

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver: 110.0.5481.77

**Comment by Pepan** [comment] 2023-05-09 13:29
reverting back as `gem 'selenium-webdriver', '4.9.0'` solves the issue

**Comment by titusfortner** [comment] 2023-05-09 13:55
Yes, it broke how Capybara is wrapping the class; I made a PR there.
Duplicate of #12005

**Closed as completed by titusfortner** 2023-05-09 13:55 UTC
Labels: I-defect, A-needs-triaging

**Comment by ahangarha** [comment] 2023-05-11 18:34
Link to the relevant PR in Capybara: https://github.com/teamcapybara/capybara/pull/2667
