### ISSUE TITLE
how to set proxy in java ,it not running 

### ISSUE THREAD

**Issue by pangoo-reuse** [SeleniumHQ/selenium#8965] opened 2020-12-13 07:10 UTC
## To Reproduce

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment
Bug Report

here is my proxy code in java:

```
        String pxo = "175.42.68.187:9999";
        ChromeOptions options = new ChromeOptions();
        Proxy proxy = new Proxy();
        proxy.setHttpProxy(pxo);
        options.setCapability("proxy", proxy);
```
but when chrome running ,i got thoes info,look at blew:

_chrome://version/_
`
Google Chrome | 87.0.4280.88 (正式版本) （64 位） (cohort: Stable)
-- | --
修订版本 | 89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}
操作系统 | Windows 10 OS Version 1909 (Build 18363.1198)
JavaScript | V8 8.7.220.29
Flash | 33.0.0.417 C:\Windows\system32\Macromed\Flash\pepflashplayer64_33_0_0_417.dll
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
命令行 | "C:/Program Files/Google/Chrome/Application/chrome.exe" --disable-background-networking --disable-backgrounding-occluded-windows --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-blink-features=ShadowDOMV0 --enable-logging --log-level=0 --no-first-run --no-service-autorun --password-store=basic **--proxy-server=http=175.42.68.187:9999** --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir="C:\Users\yone\AppData\Local\Temp\scoped_dir41080_718675084" --flag-switches-begin --flag-switches-end data:,
可执行文件路径 | C:\Program Files\Google\Chrome\Application\chrome.exe
个人资料路径 | C:\Users\yone\AppData\Local\Temp\scoped_dir41080_718675084\Default
其他变体 | 5e3a236d-4113a79e

`
now ,i just jump a scan my ip address ,but it show me my ip is my local ip(isnt dynamic proxy ip )
,like this, 
您的iP地址是：[**139.228.171.15**] 来自：中国上海上海 联通

and set driver.getCapability().merge(option) isnt running,

please tell me how to set a right proxy,and if you know how to set dynamic proxy that not restart chorme,pelase tell me ,thx a lot.

**Comment by pujagani** [comment] 2020-12-24 11:58
Please provide the full test script to help re-create the issue.  Also, can you mention the Selenium version your facing the issue with. More details regarding the exact problem are appreciated. Seems like the problem is two-fold. For example, refer to https://www.selenium.dev/documentation/en/webdriver/http_proxies/. For understanding the issue with  `and set driver.getCapability().merge(option) isnt running,` the full test script will help. Thank you.

**Comment by diemol** [comment] 2021-01-07 16:52
Closing as we did not get more information.

**Closed as completed by diemol** 2021-01-07 16:52 UTC
Labels: J-awaiting answer
