### ISSUE TITLE
[🐛 Bug]: WebDriverException: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Browser window not found"}

### ISSUE THREAD

**Issue by kenoti** [SeleniumHQ/selenium#13114] opened 2023-11-08 09:34 UTC
### What happened?

Can not maximize browser windows cause browser session is not being detected.
Issue start this week not sure if this should be flagged as an Edge issue or a Selenium issue.

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from webdriver_manager.microsoft import EdgeChromiumDriverManager
from selenium import webdriver
from selenium.webdriver.edge.service import Service as EdgeService
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.alert import Alert
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.action_chains import ActionChains

def broswer_open():
    options = webdriver.EdgeOptions()
    options.add_argument("--remote-debugging-port=9321")
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument(r'--profile-directory=Default')
    options.add_experimental_option('excludeSwitches', ['enable-logging'])
    options.add_argument("--start-maximized")
    options.add_argument("--remote-allow-origins=*")
   
    bro = webdriver.Edge(service=EdgeService(EdgeChromiumDriverManager().install()),options=options) 
 
    return bro

bro = broswer_open()
bro.maximize_window()
```

### Relevant log output

```shell
---------------------------------------------------------------------------
WebDriverException                        Traceback (most recent call last)
Cell In[21], line 10
      6 bro = broswer_open()
      7 #bro.set_window_size(1920, 1080)
      8 #actionChains = ActionChains(bro)
      9 #actionChains.send_keys(Keys.ALT + Keys.SPACE).perform();
---> 10 bro.maximize_window()
     13 time.sleep(20)
     14 try:

File \site-packages\selenium\webdriver\remote\webdriver.py:499, in WebDriver.maximize_window(self)
    497 """Maximizes the current window that webdriver is using."""
    498 command = Command.W3C_MAXIMIZE_WINDOW
--> 499 self.execute(command, None)

File \site-packages\selenium\webdriver\remote\webdriver.py:347, in WebDriver.execute(self, driver_command, params)
    345 response = self.command_executor.execute(driver_command, params)
    346 if response:
--> 347     self.error_handler.check_response(response)
    348     response["value"] = self._unwrap_value(response.get("value", None))
    349     return response

File \site-packages\selenium\webdriver\remote\errorhandler.py:229, in ErrorHandler.check_response(self, response)
    227         alert_text = value["alert"].get("text")
    228     raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
--> 229 raise exception_class(message, screen, stacktrace)

WebDriverException: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Browser window not found"}
  (Session info: MicrosoftEdge=119.0.2151.44)
Stacktrace:
	GetHandleVerifier [0x00007FF72EBF5462+60322]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF72EB7A412+245298]
	(No symbol) [0x00007FF72E949CE9]
	(No symbol) [0x00007FF72E9335B7]
	(No symbol) [0x00007FF72E930EBE]
	(No symbol) [0x00007FF72E931D7E]
	(No symbol) [0x00007FF72E931CB0]
	(No symbol) [0x00007FF72E9213E3]
	(No symbol) [0x00007FF72E921888]
	(No symbol) [0x00007FF72E9ED6E9]
	(No symbol) [0x00007FF72E9BBADA]
	(No symbol) [0x00007FF72E98D7A6]
	(No symbol) [0x00007FF72E9D5171]
	(No symbol) [0x00007FF72E9BB8B3]
	(No symbol) [0x00007FF72E98C5C3]
	(No symbol) [0x00007FF72E98B9D3]
	(No symbol) [0x00007FF72E98CD54]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF72EDD2084+1154308]
	(No symbol) [0x00007FF72EA0E656]
	Microsoft::Applications::Events::EventProperty::clear [0x00007FF72EAD0AD3+36579]
	Microsoft::Applications::Events::EventProperty::clear [0x00007FF72EAC89FD+3597]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF72EDD0DC4+1149508]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF72EB83DC8+284648]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF72EB7FB54+267636]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF72EB7FC82+267938]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF72EB72B31+214353]
	BaseThreadInitThunk [0x00007FFC7DAF7344+20]
	RtlUserThreadStart [0x00007FFC7F8C26B1+33]

```

### Operating System

Windows 10

### Selenium version

Python 3.10

### What are the browser(s) and version(s) where you see this issue?

MicrosoftEdge=119.0.2151.44

### What are the browser driver(s) and version(s) where you see this issue?

EdgeChromiumDriverManager

**Comment by diemol** [comment] 2023-11-08 10:12
Do you have the issue if you try with Firefox or Chrome?

**Comment by kenoti** [comment] 2023-11-09 03:13
> Do you have the issue if you try with Firefox or Chrome?

Different issues when try to use Chrome. Opens with a new tab window and there after crashes.

**Comment by kenoti** [comment] 2023-11-09 03:17
Chrome Code Below
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as Service
 
def broswer_open():

    try:
        bro = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
    except:
        bro = webdriver.Chrome(ChromeDriverManager().install())

    return bro

bro = broswer_open()
bro.maximize_window()

**Comment by kenoti** [comment] 2023-11-09 03:23
Chrome Logs
---------------------------------------------------------------------------
SessionNotCreatedException                Traceback (most recent call last)
Input In [21], in broswer_open()
     13 try:
---> 14     bro = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
     15 except:

File selenium\webdriver\chrome\webdriver.py:45, in WebDriver.__init__(self, options, service, keep_alive)
     43 options = options if options else Options()
---> 45 super().__init__(
     46     DesiredCapabilities.CHROME["browserName"],
     47     "goog",
     48     options,
     49     service,
     50     keep_alive,
     51 )

File selenium\webdriver\chromium\webdriver.py:56, in ChromiumDriver.__init__(self, browser_name, vendor_prefix, options, service, keep_alive)
     55 try:
---> 56     super().__init__(
     57         command_executor=ChromiumRemoteConnection(
     58             remote_server_addr=self.service.service_url,
     59             browser_name=browser_name,
     60             vendor_prefix=vendor_prefix,
     61             keep_alive=keep_alive,
     62             ignore_proxy=options._ignore_local_proxy,
     63         ),
     64         options=options,
     65     )
     66 except Exception:

File selenium\webdriver\remote\webdriver.py:208, in WebDriver.__init__(self, command_executor, keep_alive, file_detector, options)
    207 self.start_client()
--> 208 self.start_session(capabilities)

File selenium\webdriver\remote\webdriver.py:292, in WebDriver.start_session(self, capabilities)
    291 caps = _create_caps(capabilities)
--> 292 response = self.execute(Command.NEW_SESSION, caps)["value"]
    293 self.session_id = response.get("sessionId")

File selenium\webdriver\remote\webdriver.py:347, in WebDriver.execute(self, driver_command, params)
    346 if response:
--> 347     self.error_handler.check_response(response)
    348     response["value"] = self._unwrap_value(response.get("value", None))

File selenium\webdriver\remote\errorhandler.py:229, in ErrorHandler.check_response(self, response)
    228     raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
--> 229 raise exception_class(message, screen, stacktrace)

SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
	GetHandleVerifier [0x005A72A3+45731]
	(No symbol) [0x00532D51]
	(No symbol) [0x0042880D]
	(No symbol) [0x0044DE89]
	(No symbol) [0x0044A310]
	(No symbol) [0x0047EB26]
	(No symbol) [0x0047E6BC]
	(No symbol) [0x00477DD6]
	(No symbol) [0x004531F6]
	(No symbol) [0x0045439D]
	GetHandleVerifier [0x008B0716+3229462]
	GetHandleVerifier [0x008F84C8+3523784]
	GetHandleVerifier [0x008F214C+3498316]
	GetHandleVerifier [0x00631680+611968]
	(No symbol) [0x0053CCCC]
	(No symbol) [0x00538DF8]
	(No symbol) [0x00538F1D]
	(No symbol) [0x0052B2C7]
	BaseThreadInitThunk [0x777BFCC9+25]
	RtlGetAppContainerNamedObjectPath [0x779F7C6E+286]
	RtlGetAppContainerNamedObjectPath [0x779F7C3E+238]


During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
File selenium\webdriver\common\driver_finder.py:38, in DriverFinder.get_path(service, options)
     37 try:
---> 38     path = SeleniumManager().driver_location(options) if path is None else path
     39 except Exception as err:

File selenium\webdriver\common\selenium_manager.py:75, in SeleniumManager.driver_location(self, options)
     68 """Determines the path of the correct driver.
     69 
     70 :Args:
     71  - browser: which browser to get the driver path for.
     72 :Returns: The driver path to use
     73 """
---> 75 browser = options.capabilities["browserName"]
     77 args = [str(self.get_binary()), "--browser", browser]

AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Input In [22], in <cell line: 3>()
      1 #Main running program
      2 print("Go to the view")
----> 3 bro = broswer_open()
      4 bro.maximize_window()
      7 time.sleep(20)

Input In [21], in broswer_open()
     14     bro = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
     15 except:
---> 16     bro = webdriver.Chrome(ChromeDriverManager().install())
     17 return bro

File selenium\webdriver\chrome\webdriver.py:45, in WebDriver.__init__(self, options, service, keep_alive)
     42 service = service if service else Service()
     43 options = options if options else Options()
---> 45 super().__init__(
     46     DesiredCapabilities.CHROME["browserName"],
     47     "goog",
     48     options,
     49     service,
     50     keep_alive,
     51 )

File selenium\webdriver\chromium\webdriver.py:51, in ChromiumDriver.__init__(self, browser_name, vendor_prefix, options, service, keep_alive)
     47 self.vendor_prefix = vendor_prefix
     49 self.service = service
---> 51 self.service.path = DriverFinder.get_path(self.service, options)
     53 self.service.start()
     55 try:

File selenium\webdriver\common\driver_finder.py:40, in DriverFinder.get_path(service, options)
     38     path = SeleniumManager().driver_location(options) if path is None else path
     39 except Exception as err:
---> 40     msg = f"Unable to obtain driver for {options.capabilities['browserName']} using Selenium Manager."
     41     raise NoSuchDriverException(msg) from err
     43 if path is None or not Path(path).is_file():

AttributeError: 'str' object has no attribute 'capabilities'

**Comment by diemol** [comment] 2023-11-09 09:54
`EdgeChromiumDriverManager` and `ChromeDriverManager` are not part of the Selenium project. Can you provide a code sample only using Selenium (latest version) to reproduce the issue?

**Comment by kenoti** [comment] 2023-11-13 01:56
Chrome keep getting into the issue below thats one reason prefer using Edge.
Opens Chrome in a new tab after that crashes.

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
def broswer_open():
    bro= webdriver.Chrome()
    return bro
bro = broswer_open()
bro.maximize_window()

---------------------------------------------------------------------------
SessionNotCreatedException                Traceback (most recent call last)
Cell In[22], line 6
      3 #Main running program
      4 print("Go to the view")
----> 6 bro = broswer_open()
      7 #bro.set_window_size(1920, 1080)
      8 #actionChains = ActionChains(bro)
      9 #actionChains.send_keys(Keys.ALT + Keys.SPACE).perform();
     10 bro.maximize_window()

Cell In[21], line 2, in broswer_open()
      1 def broswer_open():
----> 2     bro= webdriver.Chrome()
      3     return bro

File ~\site-packages\selenium\webdriver\chrome\webdriver.py:45, in WebDriver.__init__(self, options, service, keep_alive)
     42 service = service if service else Service()
     43 options = options if options else Options()
---> 45 super().__init__(
     46     DesiredCapabilities.CHROME["browserName"],
     47     "goog",
     48     options,
     49     service,
     50     keep_alive,
     51 )

File ~\site-packages\selenium\webdriver\chromium\webdriver.py:56, in ChromiumDriver.__init__(self, browser_name, vendor_prefix, options, service, keep_alive)
     53 self.service.start()
     55 try:
---> 56     super().__init__(
     57         command_executor=ChromiumRemoteConnection(
     58             remote_server_addr=self.service.service_url,
     59             browser_name=browser_name,
     60             vendor_prefix=vendor_prefix,
     61             keep_alive=keep_alive,
     62             ignore_proxy=options._ignore_local_proxy,
     63         ),
     64         options=options,
     65     )
     66 except Exception:
     67     self.quit()

File ~\site-packages\selenium\webdriver\remote\webdriver.py:208, in WebDriver.__init__(self, command_executor, keep_alive, file_detector, options)
    206 self._authenticator_id = None
    207 self.start_client()
--> 208 self.start_session(capabilities)

File ~\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py:292, in WebDriver.start_session(self, capabilities)
    285 """Creates a new session with the desired capabilities.
    286 
    287 :Args:
    288  - capabilities - a capabilities dict to start the session with.
    289 """
    291 caps = _create_caps(capabilities)
--> 292 response = self.execute(Command.NEW_SESSION, caps)["value"]
    293 self.session_id = response.get("sessionId")
    294 self.caps = response.get("capabilities")

File ~\site-packages\selenium\webdriver\remote\webdriver.py:347, in WebDriver.execute(self, driver_command, params)
    345 response = self.command_executor.execute(driver_command, params)
    346 if response:
--> 347     self.error_handler.check_response(response)
    348     response["value"] = self._unwrap_value(response.get("value", None))
    349     return response

File ~\site-packages\selenium\webdriver\remote\errorhandler.py:229, in ErrorHandler.check_response(self, response)
    227         alert_text = value["alert"].get("text")
    228     raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
--> 229 raise exception_class(message, screen, stacktrace)

SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
	GetHandleVerifier [0x00007FF6267282B2+55298]
	(No symbol) [0x00007FF626695E02]
	(No symbol) [0x00007FF6265505AB]
	(No symbol) [0x00007FF62657DCD8]
	(No symbol) [0x00007FF62657B30E]
	(No symbol) [0x00007FF6265BA198]
	(No symbol) [0x00007FF6265B9CB0]
	(No symbol) [0x00007FF6265B1E83]
	(No symbol) [0x00007FF62658670A]
	(No symbol) [0x00007FF626587964]
	GetHandleVerifier [0x00007FF626AA0AAB+3694587]
	GetHandleVerifier [0x00007FF626AF728E+4048862]
	GetHandleVerifier [0x00007FF626AEF173+4015811]
	GetHandleVerifier [0x00007FF6267C47D6+695590]
	(No symbol) [0x00007FF6266A0CE8]
	(No symbol) [0x00007FF62669CF34]
	(No symbol) [0x00007FF62669D062]
	(No symbol) [0x00007FF62668D3A3]
	BaseThreadInitThunk [0x00007FFA72A07344+20]
	RtlUserThreadStart [0x00007FFA745C26B1+33]

**Comment by kenoti** [comment] 2023-11-13 03:07
When try edge
def broswer_open():
    bro= webdriver.Edge()
    return bro
bro = broswer_open()
bro.maximize_window()

---------------------------------------------------------------------------
WebDriverException                        Traceback (most recent call last)
Cell In[22], line 10
      6 bro = broswer_open()
      7 #bro.set_window_size(1920, 1080)
      8 #actionChains = ActionChains(bro)
      9 #actionChains.send_keys(Keys.ALT + Keys.SPACE).perform();
---> 10 bro.maximize_window()
     13 time.sleep(20)
     14 try:

File ~site-packages\selenium\webdriver\remote\webdriver.py:499, in WebDriver.maximize_window(self)
    497 """Maximizes the current window that webdriver is using."""
    498 command = Command.W3C_MAXIMIZE_WINDOW
--> 499 self.execute(command, None)

File ~site-packages\selenium\webdriver\remote\webdriver.py:347, in WebDriver.execute(self, driver_command, params)
    345 response = self.command_executor.execute(driver_command, params)
    346 if response:
--> 347     self.error_handler.check_response(response)
    348     response["value"] = self._unwrap_value(response.get("value", None))
    349     return response

File ~site-packages\selenium\webdriver\remote\errorhandler.py:229, in ErrorHandler.check_response(self, response)
    227         alert_text = value["alert"].get("text")
    228     raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
--> 229 raise exception_class(message, screen, stacktrace)

WebDriverException: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Browser window not found"}
  (Session info: MicrosoftEdge=119.0.2151.58)
Stacktrace:
	GetHandleVerifier [0x00007FF6585025B2+60402]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF658487302+253666]
	(No symbol) [0x00007FF658259C99]
	(No symbol) [0x00007FF658243577]
	(No symbol) [0x00007FF658240E8E]
	(No symbol) [0x00007FF658241D4E]
	(No symbol) [0x00007FF658241C80]
	(No symbol) [0x00007FF6582313D3]
	(No symbol) [0x00007FF658231878]
	(No symbol) [0x00007FF6582FD689]
	(No symbol) [0x00007FF6582CBA8A]
	(No symbol) [0x00007FF65829D766]
	(No symbol) [0x00007FF6582E5111]
	(No symbol) [0x00007FF6582CB863]
	(No symbol) [0x00007FF65829C585]
	(No symbol) [0x00007FF65829B993]
	(No symbol) [0x00007FF65829CD14]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6586E3454+1161924]
	(No symbol) [0x00007FF65831E5F6]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6583DB083+37459]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6583D2C4D+3613]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6586E2194+1157124]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF658491658+295480]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF65848CB24+276228]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF65848CC52+276530]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF65847FA41+222753]
	BaseThreadInitThunk [0x00007FFA72A07344+20]
	RtlUserThreadStart [0x00007FFA745C26B1+33]
bro.__dict__

**Comment by titusfortner** [comment] 2023-11-13 11:44
Duplicate of #12889
See the suggested resolution in the linked chromedriver bug.

**Closed as not planned** 2023-11-13 11:44 UTC
Labels: J-awaiting answer, I-defect

**Comment by kenoti** [comment] 2023-11-14 07:09
> Duplicate of #12889 See the suggested resolution in the linked chromedriver bug.

Thanks starting multiple sessions worked.
from selenium import webdriver
driver1 = webdriver.Chrome()
driver2 = webdriver.Chrome()
driver2.get("http://google.com")
Worked both on Edge and Chrome so now have 1 open browser that doesnt do anything and another that covers my needs.
