### ISSUE TITLE
Driver.get(url) never works outside the function that creates the driver

### ISSUE THREAD

**Issue by dhiviyadhanasekar** [SeleniumHQ/selenium#2578] opened 2016-08-05 23:10 UTC
## Meta -
OS:  Mac OSX El Captain, Version 10.11.6
Selenium Version:  2.53.3
Browser:  Firefox 
Browser Version:  47.0.1

## Expected Behavior -
driver.get(url) should navigate to the new url anytime it is called.

## Actual Behavior -
driver.get(url) navigates only if you use it in the same function that created the driver instance. If you store driver globally and then use driver.get(url) then it doesn't navigate

## Steps to reproduce -
Set up a mocha selenium test like this:
<pre><code>
var driver; //global
function createSeleniumDriver {
      var driver = new selenium.Builder().
          withCapabilities(TestConstants.BROWSER_TO_USE).
          build();
      driver.manage().window().maximize();
      driver.manage().timeouts().implicitlyWait(10000);
      return driver;
};
 test.before(function(done){
            this.timeout(20000);
            driver = createSeleniumDriver();
            driver.get('http://localhost:3000/sign_in'); //navigates to url correctly
            // do some thing on the sign in page to sign in
            var url = 'http://localhost:3000/flow/123';
            driver.get(url); //navigates to url correctly
            done(); 
  });

  test.beforeEach(function(done){
      var url = 'http://localhost:3000/flow/456';
      driver.get(url); //this navigation never happens - ISSUE!
      done();
  });
</code></pre>

The driver.get(url) never works outside the before.

**Comment by jleyba** [comment] 2016-08-07 02:12
I'm not able to reproduce this.  Please provide a complete, reproducible test case.

**Comment by jleyba** [comment] 2016-08-21 16:58
Closing this issue. We can re-open if you can provide a complete, reproducible test case.

**Closed by jleyba** 2016-08-21 16:58 UTC
Labels: C-nodejs
