### ISSUE TITLE
[🐛 Bug]: Selenium 4, Python: ShadowRoot find_element only works with css_selector

### ISSUE THREAD

**Issue by NickAJScott** [SeleniumHQ/selenium#10107] opened 2021-12-01 12:42 UTC
### What happened?

If you use any other By type than CSS_SELECTOR with a find_element on a shadow root object you get an Invalid Locator error. It seems the tests only test this function with By.CSS_SELECTOR so unsure if this is intentional. 

Also the find_element on the ShadowRoot object has a different signature to all other find_element functions (it uses `using` rather than `by`), this makes it annoying if you are trying to call find_element with keyword arguments, as the keyword arguments might be different if you happen to be on a shadow root element.

The other find_element functions do a conversion of the different By types into equivalent By.CSS_SELECTORs so i am wondering if this is missing from the shadow root?

### How can we reproduce the issue?

```shell
Change this test:

@pytest.mark.xfail_safari
def test_can_find_element_in_a_shadowroot(driver, pages):
    pages.load("webComponents.html")
    custom_element = driver.find_element(By.CSS_SELECTOR, "custom-checkbox-element")
    shadow_root = custom_element.shadow_root
    element = shadow_root.find_element(By.CSS_SELECTOR, "input")

    assert isinstance(element, WebElement)

To access the element within the shadow_root by tag name instead.

@pytest.mark.xfail_safari
def test_can_find_element_in_a_shadowroot(driver, pages):
    pages.load("webComponents.html")
    custom_element = driver.find_element(By.CSS_SELECTOR, "custom-checkbox-element")
    shadow_root = custom_element.shadow_root
    element = shadow_root.find_element(By.TAG_NAME, "input")

    assert isinstance(element, WebElement)
```

### Relevant log output

```shell
return shadow_root.find_element(By.TAG_NAME, 'upload-button')
  File "python3.8/site-packages/selenium/webdriver/remote/shadowroot.py", line 45, in find_element
    return self._execute(Command.FIND_ELEMENT_FROM_SHADOW_ROOT, {"using": using, "value": value})['value']
  File "python3.8/site-packages/selenium/webdriver/remote/shadowroot.py", line 64, in _execute
    return self.session.execute(command, params)
  File "python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: headless chrome=96.0.4664.45)
```

### Operating System

Ubuntu

### Selenium version

Python Selenium 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome Version '96.0.4664.45'

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 96.0.4664.45

**Comment by diemol** [comment] 2021-12-01 15:41
Confirmed with @AutomatedTester that this is a duplicate of #10025, which goes all the way of being an issue with Chrome/ChromeDriver. Please check the linked issues for details.

**Closed as completed by diemol** 2021-12-01 15:41 UTC
Labels: C-py, I-defect

**Comment by NickAJScott** [comment] 2021-12-01 16:20
@diemol  Wouldn't it be nice to do what the other find_element functions already do and translate the different By locators into By.CSS_SELECTOR versions? I'm not sure why shadow root is a special case e.g. this block is run when using find_element on a regular element:
 ```
    if by == By.ID:
        by = By.CSS_SELECTOR
        value = '[id="%s"]' % value
    elif by == By.TAG_NAME:
        by = By.CSS_SELECTOR
    elif by == By.CLASS_NAME:
        by = By.CSS_SELECTOR
        value = ".%s" % value
    elif by == By.NAME:
        by = By.CSS_SELECTOR
        value = '[name="%s"]' % value
```

and its quite annoying to have to run that before any find_element that is running against a shadow root object.

**Comment by AutomatedTester** [comment] 2021-12-01 16:28
We could add that, the issue is mostly Chrome are doing the wrong thing here. I will add it for now but I suggest also raising an issue with the Chromium team.

**Comment by NickAJScott** [comment] 2021-12-01 16:35
@AutomatedTester That would be great thanks, sorry im not familiar with where to raise issues with the chromium team, if you have a link to where makes sense id be happy to.

**Comment by fenchu** [comment] 2021-12-06 13:21
Using anything except CSS_SELECTORS on web elements from execute_script or shadow_root have never worked. I assumed it was because it has to be executed. Believed it to be a limitation not a bug.
