### ISSUE TITLE
Receiving the error Window is closed with the IE driver 3.8.0 and selenium webdriver3.8.0

### ISSUE THREAD

**Issue by KS261187** [SeleniumHQ/selenium#5195] opened 2017-12-10 02:44 UTC
## Meta -
OS:  Win 10

Selenium Version:  3.8.0

Browser:  IE 11

Browser Version:

**Comment by barancev** [comment] 2017-12-10 17:53
Duplicate of #5061

**Closed by barancev** 2017-12-10 17:53 UTC
