### ISSUE TITLE
[🐛 Bug]: Python + Selenium 4.0+ (AttributeError: 'dict' object has no attribute 'click')

### ISSUE THREAD

**Issue by ElenaStepuro** [SeleniumHQ/selenium#10171] opened 2021-12-21 10:16 UTC
### What happened?

During running tests on Python  faced with issue: AttributeError: 'dict' object has no attribute 'click'
which didn't see on Selenium 3.141

### How can we reproduce the issue?

```shell
Python 3.8
Exception see with w3c=True and without

Code:
    def setup_method(self):
        options = webdriver.ChromeOptions()
        options.w3c = True
        options.add_argument('--no-sandbox')
        self.driver = webdriver.Remote(
            command_executor="http://localhost:8085",
            desired_capabilities=webdriver.DesiredCapabilities.CHROME,
            options=options)

Test code:
    def test(self, setup_method):
        self.driver.get('https://sha-test-app.herokuapp.com/')
        self.driver.find_element(By.XPATH, "//button[contains(@class,'default-btn')]").click()
```

### Relevant log output

```shell
def test(self, setup_method):
        self.driver.get('https://sha-test-app.herokuapp.com/')
        self.button=self.driver.find_element(By.XPATH, "//button[contains(@class,'default-btn')]")
>       self.button.click()
E       AttributeError: 'dict' object has no attribute 'click'
```

### Operating System

Windows 10

### Selenium version

4.0.0 and 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 94, 95, 96

### What are the browser driver(s) and version(s) where you see this issue?

Remote

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment] 2021-12-23 17:01
First, this error doesn't make sense. If Selenium is getting a return value from `find_element()` it isn't going to be a `dict` unless something is getting monkey patched somewhere.

I still tried to reproduce with a Selenium server, but this code works fine for me:
```
    options = ChromeOptions()
    options.w3c = True
    options.add_argument('--no-sandbox')
    driver = Remote(
        command_executor="http://localhost:4444",
        desired_capabilities=DesiredCapabilities.CHROME,
        options=options)
    driver.get('https://sha-test-app.herokuapp.com/')
    element = driver.find_element(By.XPATH, "//button[contains(@class,'default-btn')]")
    element.click()
```

That said, you shouldn't be setting `w3c` any longer, or using `desired_capabilities`, and you should avoid bypassing the security sandbox unless you've got a good use case for it.

What is running on port `8085`? If a Selenium server, what version? If it's a chromedriver, why not use `webdriver.Chrome()` for this instead?

**Comment by ElenaStepuro** [comment] 2021-12-28 12:48
Hello @titusfortner !
I've retried to run code without setting **w3c** and still has the same exception.
On port **8085** I'm running docker container which I have to called during my test run. 
Forget to add while opening this issue: on port 8086 I'm running container which used **Selenium Grid 4.0.0-rc-1**

**Comment by dongfangtianyu** [comment] 2021-12-30 11:42
I encountered a similar problem during the use of Appium,
![image](https://user-images.githubusercontent.com/7629022/147748224-f684249f-c472-4b23-a683-939675a0a4f7.png)

At this time, find_elenment returned a dict instead of a WebElement.

Unfortunately I cannot reproduce this problem,

Can you print out the return value of find_element, @ElenaStepuro ?
Or maybe provide an environment for others to try ？I'm afraid it's not accidental,

**Comment by titusfortner** [comment] 2021-12-30 14:22
Oh, this makes sense, this is the JSON Wire Protocol signature for elements. You aren't getting a w3c response from the driver.

**Comment by ElenaStepuro** [comment] 2021-12-30 14:42
Hello @dongfangtianyu !
This is what findElement returns 
![image](https://user-images.githubusercontent.com/20905103/147761518-b9bbee01-bd88-43d3-8f7e-49c141f8c6f8.png)

**Comment by titusfortner** [comment] 2021-12-30 15:03
Somehow you are getting a jwp session. It should default to w3c, so you're doing something weird.

Appium is slightly harder to get a w3c session.

What is standard out on your console?

**Comment by titusfortner** [comment] 2021-12-30 17:40
I can duplicate this error by setting:
```
    options.add_experimental_option('w3c', False)
```
@ElenaStepuro send the exact code you are using, and the console output from the grid. Something it is seeing wants to toggle JSON Wire Protocol, which should not be happening with what you've provided, so something is missing

@dongfangtianyu Getting w3c compliant Appium session is a little trickier. 
You can see an example of valid w3c here: https://saucelabs.com/platform/platform-configurator#/

**Comment by titusfortner** [comment] 2022-01-05 14:46
Since this is user setting issues and not a problem with Selenium code, I'm closing this. If people need additional assistance, you can `@` me here, contact us in [Chat](https://www.selenium.dev/support/#ChatRoom)

**Closed as completed by titusfortner** 2022-01-05 14:46 UTC
Labels: J-awaiting answer, C-py, I-defect

**Comment by JaapHaitsma** [comment] 2022-01-14 00:12
I had the same error. For me the solution was to update the chromedriver to latest version

**Comment by Georgepop** [comment] 2022-01-18 19:45
yeap, me too
