### ISSUE TITLE
[🐛 Bug]: File upload through SSO application is not working

### ISSUE THREAD

**Issue by ponsurya** [SeleniumHQ/selenium#13695] opened 2024-03-15 05:59 UTC
### What happened?

I have a application which requires SSO login. I am able to login using BiDi functionality. There we have a feature to upload files. I am able to select the files (using sendkeys). File name also appears. When I press upload button, upload is not happening. Even when I did manually in the same session, same error is given. In network console, I could see 400 bad request. In request header I could see content length is 0. In payload I could see file which I selected. In response, I could see 'Required request part file is not present'.

### How can we reproduce the issue?

```shell
I used below similar code for SSO login
     driver.get("https://ABC.com");
    Predicate<URI> uriPredicate = uri -> uri.toString().contains("zxzz.com");
    Supplier<Credentials> authentication = UsernameAndPassword.of("admin", "admin");

    ((HasAuthentication) driver).register(uriPredicate, authentication);


For file upload I used below code,

    WebElement fileInput = driver.findElement(By.cssSelector("input[type=file]"));
    fileInput.sendKeys(uploadFile.getAbsolutePath());
    driver.findElement(By.id("file-submit")).click();


```

### Relevant log output

```shell
No log.
```

### Operating System

Windows 10

### Selenium version

4.17

### What are the browser(s) and version(s) where you see this issue?

Chrome version 122

### What are the browser driver(s) and version(s) where you see this issue?

122.0.6261.128

**Comment by ponsurya** [comment] 2024-03-15 06:47
I have added the code which I used for SSO Authentication and file upload

**Comment by diemol** [comment] 2024-03-15 06:49
The snippet seems incomplete.

**Comment by ponsurya** [comment] 2024-03-15 07:00
Since I cannot share the complete code, i just shared similar snippet where I am suspecting the issue. SSO login and file upload.

While debugging, as a first step I opened just browser session alone from automation and take the control manually. In this case, I can upload the file. 

As a next step, i just debugged straight over login (SSO Authentication) and take the control manually. There I am getting upload failed with 400 in network console

**Comment by diemol** [comment] 2024-03-15 07:07
I am unsure if you are aware, but SSO does not work like that. You are usually redirected to a different site to do the actual authentication and the code you are using is more suited for basic authentication.

**Comment by ponsurya** [comment] 2024-03-15 07:21
I was aware of that. I provided the site in uripredicate where actual authentication takes place

**Comment by diemol** [comment] 2024-03-15 07:23
Well, we cannot do much because we need a way to reproduce your issue.

**Comment by ponsurya** [comment] 2024-03-15 07:37
I just modified the code a bit.  I will add additional details in sometime

**Comment by diemol** [comment] 2024-03-26 22:36
I will close this as we have yet to get more information.

**Closed as not planned by diemol** 2024-03-26 22:36 UTC
Labels: I-defect, J-issue-template
