### ISSUE TITLE
action.move_to(ele).perform not working with Ruby and Selenium 3.0.0

### ISSUE THREAD

**Issue by cframe87** [SeleniumHQ/selenium#3023] opened 2016-10-27 17:31 UTC
## Meta -
OS:  OSX

Selenium Version:  3.0.0

Browser:  Firefox

Browser Version:  49.0.2

## Expected Behavior - 
A Ruby command like browser.action.move_to(element).perform should succeed ala
http://www.rubydoc.info/gems/selenium-webdriver/3.0.0/Selenium/WebDriver/ActionBuilder#move_to-instance_method

## Actual Behavior - 
the same command results in an error "unknown command: :mouseMoveTo.  There is a similar known issue for Safari, but not for Firefox.

## Steps to reproduce -

1) Go to google.com
2) Run these lines
@browser = Selenium::WebDriver.for :firefox, marionette: true
ele = @browser.find_element(:xpath, "//input[@value = 'Google Search']")
@browser.action.move_to(ele).perform

**Comment by cframe87** [comment] 2016-10-27 17:39
![image](https://cloud.githubusercontent.com/assets/11842400/19778440/634e68d8-9c42-11e6-9adc-09d0674721c5.png)

**Comment by lukeis** [comment] 2016-10-27 18:30
duplicate of #2285

**Closed by lukeis** 2016-10-27 18:30 UTC
Labels: C-rb
