### ISSUE TITLE
ActionChains - drag_and_drop, move_to_element and release fail - minimal code sample provided - Chrome and Firefox

### ISSUE THREAD

**Issue by steve-swipetospin** [SeleniumHQ/selenium#2169] opened 2016-05-26 18:37 UTC
## Meta -
OS:  Ubuntu 16.04
Selenium Version: 2.53.2
Browser: Google Chrome,Firefox
Browser Version: Chrome 50.0.2661.102 (64-bit), FIrefox 46.0.1

## Expected Behavior -
Please see "expected behavior" comments in the Python code below.
## Actual Behavior -
Please see "actual behavior" comments in the Python code below.

## Steps to reproduce -
Unzip drag_test.zip, which will give you two files, test.py and test.html. Put both files in the same directory and execute test.py. WebDriver will open two Chrome windows and two Firefox windows. Each one will demonstrate a problem with one or more of the ActionChains methods.

Here are links to some similar problem reports on StackOverflow and GitHub
http://stackoverflow.com/questions/36705738/selenium-move-mouse-to-element-doesnt-work
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/1835
http://stackoverflow.com/questions/36705738/selenium-move-mouse-to-element-doesnt-work
https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/7520
https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/6468

[drag_test.zip](https://github.com/SeleniumHQ/selenium/files/285060/drag_test.zip)

**Comment by lukeis** [comment] 2016-07-27 14:09
duplicate of #1365

**Closed by lukeis** 2016-07-27 14:09 UTC
Labels: D-atoms, D-firefox
