### ISSUE TITLE
[🚀 Feature]: Grid endpoint to kill all sessions of all nodes connected to a hub

### ISSUE THREAD

**Issue by ksingha161** [SeleniumHQ/selenium#12031] opened 2023-05-12 06:33 UTC
### Feature and motivation

Motivation - 
I have a grid setup where 4 nodes are connected to 1 hub. I killed all all browsers in task manager (windows) but the sessions in my grid public url still shows as active. Is there already a feature or can we implement one where we are able to close all sessions connected to a hub? I checked some grid endpoints but they needed node uri. The below screenshot shows grid public url which says sessions as still active even after killing all browsers
![image](https://github.com/SeleniumHQ/selenium/assets/56039095/e6a1ddee-d9db-4bce-a468-c5379a885a51)

### Usage example

Steps to reproduce - 
1. Start grid with multiple nodes connected to a hub
2. kill all browsers in all the nodes
3. check grid public url, sessions would still be active

Currently if I need to kill all sessions I need to login to all machines separately and restart grid, which is not very optimal approach.

or If there could be a way to get all sessions related to a node uri then we could just hit this api in a loop to delete all sessions
`http://<node:uri>/se/grid/node/session/sessionId`

**Comment by diemol** [comment] 2023-05-12 09:19
Duplicate of #11519 

Feel free to add more information over there.

**Closed as completed by diemol** 2023-05-12 09:19 UTC
Labels: I-enhancement
