### ISSUE TITLE
[🐛 Bug]: OpenQA.Selenium.DevTools.CommandResponseException: 'Fetch.continueRequest: Invalid state for continueInterceptedRequest'

### ISSUE THREAD

**Issue by mtgnoah** [SeleniumHQ/selenium#10791] opened 2022-06-21 14:13 UTC
### What happened?

It throws this exception on driver.Navigate().GoToUrl(url). I am using proxies which require authentication and this error happens when I try to go back to the initial url after authenticating which I need to do because it is a form and we are attempting to use this form with the proxy each time and sometimes the proxy will change which is already done with other code.

### How can we reproduce the issue?

```shell
            Proxy p = new Proxy();
            p.Kind = ProxyKind.Manual;
            p.IsAutoDetect = false;
            p.SslProxy = "PROXY:PORT";
            p.HttpProxy = "PROXY:PORT";
            chromeOptions.Proxy = p;             
            if (driver.Url != url)
            {
                var handler = new NetworkAuthenticationHandler()
                {
                    UriMatcher = _ => true,
                    Credentials = new PasswordCredentials(proxy.username, proxy.password)
                };
                INetwork networkInterceptor = driver.Manage().Network;
                networkInterceptor.AddAuthenticationHandler(handler);
                networkInterceptor.StartMonitoring().Wait();
                driver.Navigate().GoToUrl(url);
                networkInterceptor.StopMonitoring().Wait();
            }
```

### Relevant log output

```shell
Fetch.continueRequest: Invalid state for continueInterceptedRequest
```

### Operating System

Windows 10

### Selenium version

.NET 6.0 and Selenium 4.2.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 102.0.5005.61

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 102.0.5005.61

### Are you using Selenium Grid?

No

**Comment by mtgnoah** [comment] 2022-06-21 14:21
> Hi, @mtgnoah. Please follow the issue template, we need more information to reproduce the issue.
> 
> Either a complete code snippet and URL/HTML (if more than one file is needed, provide a GitHub repo and instructions to run the code), the specific versions used, or a more detailed description to help us understand the issue.
> 
> Note: If you cannot share your code and URL/HTML, any complete code snippet and URL/HTML that reproduces the issue is good enough.
> 
> Reply to this issue when all information is provided, thank you.

I believe the above code is all you'll need because our url and proxies cannot be shared

**Comment by pujagani** [comment] 2022-06-27 06:30
Thank you for sharing the details. I am using the example shared below and unable to reproduce the error you are facing. 
```
[TestMethod]
        public void InterceptNetworkForAuthentication()
        {
            var handler = new NetworkAuthenticationHandler()
            {
                UriMatcher = _ => true,
                Credentials = new PasswordCredentials("admin", "admin")
            };
            INetwork networkInterceptor = driver.Manage().Network;
            networkInterceptor.AddAuthenticationHandler(handler);
            networkInterceptor.StartMonitoring().Wait();
            driver.Navigate().GoToUrl("https://the-internet.herokuapp.com/basic_auth");
            networkInterceptor.StopMonitoring().Wait();

            Assert.AreEqual("Congratulations! You must have the proper credentials.", driver.FindElement(By.TagName("p")).Text);

        }
```
Can you try and use the above example and see if you are still facing an issue? Just trying to narrow down if the proxy is the root cause of the issue or if it is related to NetworkAuthentication. Thank you!

**Comment by diemol** [comment] 2022-07-12 17:21
I am going to close this since we did not get more information. However, if more input is provided, we'd be happy to reopen and check again.

**Closed as completed by diemol** 2022-07-12 17:21 UTC
Labels: J-awaiting answer, I-defect, J-issue-template

**Comment by AndreasKarz** [comment] 2022-08-03 05:30
I have the same issue. You will ony see it, if you debug the test. When you run the test, you see only at the end that the test is shown as not running. 
I have 3 tests - if you run every test separate then all will work well. but if you run all tests , the second test brings the error.

**Comment by pujagani** [comment] 2022-08-04 04:58
@AndreasKarz Please provide a reproducible test script/code snippet and details of which browser version are you seeing this. It will help us triage the issue. Thank you!
