### ISSUE TITLE
Unable to Use Selenium IDE to capture the object

### ISSUE THREAD

**Issue by guptha10** [SeleniumHQ/selenium#4792] opened 2017-10-01 14:49 UTC
Hi Team,

I am facing the below issue whatever I do in Selenium IDE...not sure why I am getting this issue....

![image](https://user-images.githubusercontent.com/32276804/31055803-28639f68-a6e6-11e7-8a54-762211f640cc.png)

I have installed Windows 10 Professional OS,Mozilla 55.0.3(x86 en-US),Selenium IDE-2.9.1v

Please resolve this issue asap else give me the root cause of this issue.

## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:  ozilla 55.0.3(x86 en-US)

**Comment by barancev** [comment] 2017-10-01 15:59
Duplicate of #4406

**Closed by barancev** 2017-10-01 15:59 UTC

**Comment by guptha10** [comment] 2017-10-01 16:46
For issue #4792, you simply closed the issue as it is a duplicate of #4406.

But, Can you please tell me where is the solution for the below comment which you mentioned in 4406.

"I'm going to keep it open until we can provide an alternative solution, a capture-n-replay tool implemented as a WebExtentsion compatible with newest Firefox versions."

**Comment by barancev** [comment] 2017-10-01 16:50
There is no solution yet. You can use Selenium IDE in Firefox ESR 52 or older.
