### ISSUE TITLE
dragAndDrop and moveToElement are not working with Selenium 3.5.3

### ISSUE THREAD

**Issue by shagupta92042** [SeleniumHQ/selenium#8119] opened 2020-03-18 12:09 UTC
## 🐛 Bug Report

dragAndDrop and moveToElement are not working with Selenium 3.5.3

## To Reproduce
We are trying to drag and drop one element to another element but dragAndDrop mrthod does not work and it is not able to drag the first element to another element.

PSB the code for the same: 
Actions ac =new Actions(driver);
 ac.dragAndDrop(contract1,contract2).build().perform();

The above code did not work so we tried to do the same with the moveToElement method but it did not work too , it holds the first contract but it does not drag and drop it on to the second element but it selects the second element too without droping on it.

ac.clickAndHold(contract1).build().perform();
   common.fnWait("3000");
ac.moveToElement(contract2).release(contract2).build().perform();

     

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 79.0.3945.130
Browser Driver version: ChromeDriver  2.35.528161 
Language Bindings version: Open Jdk 1.8.0_232
Selenium Grid version (if applicable): 3.3.1

**Comment by AutomatedTester** [comment] 2020-03-19 09:38
Have you tried upgrading your selenium?
Is there a site that you can reproduce the error on that we can see it?

**Comment by AutomatedTester** [comment] 2020-03-25 21:36
Duplicate of #8003

**Closed by AutomatedTester** 2020-03-25 21:36 UTC
Labels: R-awaiting answer
