### ISSUE TITLE
Merging Capabilities to options does not work

### ISSUE THREAD

**Issue by boris779** [SeleniumHQ/selenium#9861] opened 2021-09-21 17:32 UTC
## 🐛 Bug Report

It seems that merging with` options.merge(caps)` is faulty in selenium 4

## To Reproduce

create some capabilities (like browsername and version)
create e.g. ChromeOptions
try to merge the caps into options, most of them gets lost.

example code snippet:

```
caps.setBrowserName("chrome");
caps.setVersion(getBrowserVersion());

HashMap chromePrefs = new HashMap();
chromePrefs.put("plugins.always_open_pdf_externally", true);
ChromeOptions options = new ChromeOptions();
options.setExperimentalOption("prefs", chromePrefs);

options.merge(caps);
```

Options are not merged:
<img width="646" alt="2021-09-21_19h23_31" src="https://user-images.githubusercontent.com/10259016/134219067-05ec5384-be9a-4114-854d-9785a21b7be8.png">

## Expected behavior

mergings capabilities to options should work as in selenium 3
When switching to selenium 3 with exact the same code (switch branch to selenium_3) merging works

<img width="572" alt="2021-09-21_19h31_27" src="https://user-images.githubusercontent.com/10259016/134219315-4ab98258-4f6f-4372-ae7a-b3816a6d7e64.png">

## Test script or set of commands reproducing this issue

Small Selenium project (run Configs are included!)
https://github.com/boris779/selenium4_caps_bug/tree/main

## Environment

OS: Ubuntu
Browser: Chromium 
Browser version: tested with 93, 92, 91
Browser Driver version: best fitting to the browsers (with webdrivermanager)
Language Bindings version: Java 4.0.0-rc-1
Selenium Grid version (if applicable): 4.0.0-rc-1

**Comment by titusfortner** [comment] 2021-09-22 02:38
`version` isn't w3c compliant. Does it work as intended if you use `browserVersion` or other w3c compliant keys?

**Comment by boris779** [comment] 2021-09-27 12:29
Hi!

It also does not work when using `browser_version`

<img width="960" alt="2021-09-27_14h26_53" src="https://user-images.githubusercontent.com/10259016/134907695-1be421c1-6718-40d1-85f4-2f5a9130084c.png">

If the capability is not W3C Compilant, then in my opinion it should be marked as deprecated or removed, maybe -setBrowserVersion should be implemented. I could change that and make an PR if you like.

**Comment by titusfortner** [comment] 2021-09-27 13:12
Ok, right. The merge() method no longer mutates the calling object, but instead returns a new object. The behavior was different in different parts of the code, and it was decided to have all merges provide a new object.

You need:
```java
ChromeOptions merge = options.merge(caps);
```

And thank you for the offer for a PR, I agree they were needed, and I have already added them for the next release: b86d8475b409e7fb27565f3312b4b67226f2f656

**Comment by titusfortner** [comment] 2021-09-28 18:23
Since this is an implementation change, I'm going to close this. Sorry for the additional hassle and we'll try to highlight this change when discussing the move to Selenium 4. Thanks again for reporting.

**Closed as completed by titusfortner** 2021-09-28 18:23 UTC
Labels: C-java
