### ISSUE TITLE
Webdriver with extended ASCII characters

### ISSUE THREAD

**Issue by mike-white-extr** [SeleniumHQ/selenium#1283] opened 2015-11-19 14:19 UTC
I am using Selenium stand-alone Build Info 2.48.2 on Linux.
I am using Caius's webdriver for TCL to interface with selenium's API.
I am trying to use the method "partial link text" with the selector "Français"  
I used wireshark to capture the interaction between TCL and the Selenium. It looks like TCL is sending the correct data I can see "Français" being represented by hex 22 46 72 61 6e e7 61 69 73 22 in the POST packet
But the returned HTTP 500 is showing incorrect data for "Français" , I see  hex 22 46 72 61 6e ef bf bd 61 69 73 5c 22" 
So at some point it looks like Selenium is not working correctly, with extended ASCII as ç (e7) is represented by   ∩ ┐ ╜ (ef bf bd) in the return message

**Comment by lukeis** [comment] 2015-11-19 17:40
find by partial link text shouldn't be replying with the locator or the content of the link, it should only be replying with the json representation of a web element.

Can you provide a reproducible test case so we can better understand what isn't working for you? You also need to let us know what browser you're running against.

Also, this could be a bug in Caius's implementation, which is not maintained here and this should be logged in that project.

**Comment by mike-white-extr** [comment] 2015-11-19 20:13
Here is a further explanation of what is going on, Selenium is being sent the following packet. to the "element" URI with json data of:
JavaScript Object Notation: application/json
    Object
        Member Key: "using"
            String value: partial link text
        Member Key: "value"
            String value: Fran?ais

[SeleniumPost.txt](https://github.com/SeleniumHQ/selenium/files/39421/SeleniumPost.txt)

Then selenium is responding with the HTTP 500 which is a stack trace (internal error) which is definitely on the Selenium side. There is a lot of Selenium source code specific information in the stack trace.

[SeleniumHTTP500.txt](https://github.com/SeleniumHQ/selenium/files/39424/SeleniumHTTP500.txt)

As for a reproducible test case... that may be difficult as the product under test is not available to the public yet. 
As for the browser it is firefox 40.0.3 and the linux version is 4.1.6-200-FC22.x86_64 (a Fedora Core 22 spin)

As for it being Caius while that is possible, it would mean that the webdriver is sending to the wrong URI (element) or formatting the JSON data incorrectly, in such a manner that Selenium is throwing a stack trace.... both of which work perfectly well if I shorten the text from  "Français" toe "Fran"

**Comment by lukeis** [comment] 2015-11-19 20:30
We'll need a reproducible test script... because this isn't broken in general with selenium, here's an example using python. I updated my comment above to include a link with the text "Français" in it. Also the 'error' response you're getting is consistent with the 'element not found' exception trace below, where I went to a page that did not have the link text present. I'm going to close this issue for now until a reproducible test case can be provided.

>>> from selenium import webdriver as w
>>> d = w.Firefox()
>>> d.get("https://github.com/SeleniumHQ/selenium/issues/1283")
>>> d.find_element_by_partial_link_text("Français")
<selenium.webdriver.remote.webelement.WebElement (session="ccc8878c-e332-4948-94ac-73e58bd9f8ad", element="{40b2bf19-1774-1048-acb6-af5a218821a3}")>
>>> d.get("https://github.com/SeleniumHQ/selenium/issues/1284")
>>> d.find_element_by_partial_link_text("Français")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 306, in find_element_by_partial_link_text
    return self.find_element(by=By.PARTIAL_LINK_TEXT, value=link_text)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 712, in find_element
    {'using': by, 'value': value})['value']
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException

**Closed by lukeis** 2015-11-19 20:30 UTC

**Comment by mike-white-extr** [comment] 2015-11-19 21:03
While I can understand needing a reproducible method. That was too quick to close.
You are basically saying because your python script fails to when it is supposed to (Français doesn't exist) that my issue isn't going to get any attention. My page under test does have the link text

![image](https://cloud.githubusercontent.com/assets/15926550/11284109/104faf22-8ed6-11e5-98d4-1adb97c10aa8.png)

Selenium Stack traces (HTTP 500) and in the stack trace it has the wrong data for the json
String value [truncated]: Unable to locate element: {"method":"partial link text","selector":"Fran???ais"}

**Comment by lukeis** [comment] 2015-11-19 21:06
provide the sample test page and we can reopen the issue

**Comment by mike-white-extr** [comment] 2015-11-19 21:51
Ok there is a page that is accessible over the internet.
I will leave creating a script to talk to the web driver to you
open your Selenium controlled firefox browser for the following url  https://www.ezcloudx.com/#/
#button to for the dropdown menu
element by_xpath "(//button[@type='button'])[2]"
element <#> click

#select Francais gets an error messages
element by_partial_link 'FranÃ§ais'

#shorten to Fran and it works
element by_partial_link 'Fran'

**Comment by lukeis** [comment] 2015-11-19 22:02
this seems like a different issue, ''FranÃ§ais" ? Seems like a character encoding issue (and not one by selenium).

Do you have a sample site that is the same as yours with a proper 'Français' character encoding?

**Comment by mike-white-extr** [comment] 2015-11-19 22:22
The page is supposed to have extended ASCII (utf-8) and in this case page that I directed you to has older UTF-8 text on it specifically it has ''FranÃ§ais”  not “Français” like in my bug report.
It’s not an issue if the page has misspelled text, can Selenium find it, currently it looks like it can’t find UTF-8 text. At least in this example which is using a drop down menu in an Angular Web page.

**Comment by lukeis** [comment] 2015-11-19 22:32
I already showed that is not universally true... since I found the 'Français' link by partial text on this same page.

**Comment by mike-white-extr** [comment] 2015-11-19 22:56
??? I already showed that is not universally true... since I found the 'Français' link by partial text on this same page. ???

You posted a link called Français sample link<https://github.com/SeleniumHQ/selenium/issues/1283> but it is a circular link back to my bug report, so I am not sure what you are trying to show me. And that was 5 hours ago.

I only forwarded you a test page moments ago, how can the above statement hold true?
While it is more than likely that Selenium works to find UTF-8 text  in most web pages, I would ask that you attempt to find the ''FranÃ§ais" on the particular link please.

**Comment by nirvdrum** [comment] 2015-11-19 23:00
I think this really depends on both the client and the programming language's String's encoding. Extended ASCII and UTF-8 are not the same thing. A byte sequence in the extended ASCII range is going to mean something completely different in UTF-8. If you're language is expecting UTF-8 chars and you provide extended ASCII, it's almost certainly going to do an internal conversion that's not what you expect. Likewise, if the client is connecting to a remote Selenium server, the encoding discrepancy can mess things up over HTTP.

**Comment by nirvdrum** [comment] 2015-11-19 23:23
FYI, I was able to find the link by partial text using "FranÃ§ais" in Ruby, but I needed to use the UTF-8 equivalents of those bytes. The byte sequence I used is `[70, 114, 97, 110, 195, 131, 194, 167, 97, 105, 115]`.
