### ISSUE TITLE
Safaridriver defaults to w3c and breaks proxyType pac

### ISSUE THREAD

**Issue by joventuraz** [SeleniumHQ/selenium#6526] opened 2018-10-12 03:24 UTC
## Meta -
OS:  OSX 
Selenium Version:  
3.14.0
Browser:  
Safari
Browser Version:  
12

## Expected Behavior -

Setting `'proxyType': 'pac'` and `'proxyAutoconfigUrl': <url>` should work.

## Actual Behavior -

Safaridriver is started and defaults to w3c, which does not have a complete implementation of the `proxy` spec. This causes `proxyAutoconfigUrl` to appear as an unknown key and the selenium server 
throws an exception.

Setting the `--legacy` option allows Safaridriver to run in JWP and the proxy settings work as expected.

## Steps to reproduce -
Have Safari 12 installed.
Start selenium-server-standalone-3.14.0.jar
Run a test with the following caps:
```
}
    'browserName': "safari",
    'browserVersion': "12",
    'proxy': {
        'proxyType': 'pac',
        'proxyAutoconfigUrl': 'http://localhost:8888'
}
```
You should see this exception thrown: `org.openqa.selenium.InvalidArgumentException: Unknown key in 'proxy' capability: 'proxyAutoconfigUrl'`

I have provided this PR https://github.com/SeleniumHQ/selenium/pull/6525 with a potential fix for those who needs the proxy settings are ok with using JWP. Setting a porperty `webdriver.safari.legacy` adds the `--legacy` argument.

**Comment by p0deje** [comment] 2018-10-12 08:49
Looks like this is a bug in SafariDriver and needs to be reported accordingly // cc @burg

**Comment by burg** [comment] 2018-10-12 20:48
Thanks for the report; it appears to be caused by a typo. I'm writing a fix now. This is being tracked internally as <rdar://problem/45236276>.

Aside from the typo, safaridriver has never respected proxy settings. We have an enhancement request open for fixing this. I don't have any other information to share at this time.

**Comment by joventuraz** [comment] 2018-10-13 20:47
@burg thank you for the clarification, is there any way I can contribute?

**Comment by burg** [comment] 2018-10-26 11:30
This is fixed as of Safari Technology Preview Release 68.

**Comment by barancev** [comment] 2019-04-14 18:32
Closing as fixed according to the previous comment.

**Closed by barancev** 2019-04-14 18:32 UTC
Labels: D-safari
