### ISSUE TITLE
error bad cert ERR_CERT_AUTHORITY_INVALID SEC_ERROR_UNKNOWN_ISSUER

### ISSUE THREAD

**Issue by JMVM** [SeleniumHQ/selenium#3548] opened 2017-02-21 14:29 UTC
## Meta -
OS:  Windows 7 64 bits

Selenium Version:  3.0.1

Browser:  Firefox 51

Browser Version:  
51.0.1 (64-bit)

## Expected Behavior -
- Skipping warning error page about connection is not secure

## Actual Behavior -
- Facing warning error page about connection is not secure
- WebDriver throwing Exception when trying to navigate to that page (note removed part of URL for company privacy) with **errors about bad cert**:

```
org.openqa.selenium.WebDriverException: Reached error page: about:certerror?e=nssBadCert<...>EC_ERROR_UNKNOWN_ISSUER%22%3ESEC_ERROR_UNKNOWN_ISSUER%3C/a%3E%0A
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'WHOL5003209', ip: '169.254.152.130', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], prefs={}}, appBuildId=20170125094131, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=20644, browserVersion=51.0.1, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt}]
Session ID: 73bbd66b-2645-417e-93a1-f81601e3bbf2
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:322)
	at 

```
- This behavior is happening even if creating FirefoxDriver with profile in which flags to accept any untrusted certficate, or even reading a well prepared one from local directory

## Steps to reproduce -

- Creating FirefoxDriver, and navigate to web page with wrong certificate, in this case, **ERR_CERT_AUTHORITY_INVALID** (for company privacy, I can not provide URL).

**Comment by JMVM** [comment] 2017-02-21 14:35
Probably related to https://github.com/SeleniumHQ/selenium/issues/3441

**Comment by lmtierney** [comment] 2017-02-26 03:48
Duplicate of #3441

**Closed by lmtierney** 2017-02-26 03:48 UTC
