### ISSUE TITLE
4.0.0.b1  chromeheadless - fails on linux ubuntu

### ISSUE THREAD

**Issue by fenchu** [SeleniumHQ/selenium#9269] opened 2021-03-12 09:54 UTC
## To Reproduce

just start with the following 
```
        elif os.environ['WEBDRIVER'] == 'ChromeHeadless':
            options = webdriver.ChromeOptions()
            options.add_argument('--no-sandbox')
            options.add_argument('--headless')
            options.add_argument('--disable-gpu')
            options.add_argument('--log-level=3')
            #options.add_argument('--incognito')
            options.add_argument('--default-shm-size=32m')
            options.add_argument('--disable-translate')
            options.add_argument('--disable-extensions')
            options.add_argument("--proxy-server='direct://'")
            options.add_argument("--proxy-bypass-list=*")
            if os.environ.get('WEBDRIVER_LANG'):
                options.add_experimental_option('prefs', {'intl.accept_languages': os.environ.get('WEBDRIVER_LANG')})
            d = DesiredCapabilities.CHROME  # for console logging
            d['goog:loggingPrefs'] = { 'browser':'ALL' }
            driver = webdriver.Chrome(options=options, desired_capabilities=d)
```

## Environment

OS:  ubuntu 16.04lts
Browser:  ChromeHeadless
Browser version:  89.0.4389.23
Browser Driver version:  chromedriver 89.0.4389.23 (latest available)
Language Bindings version:   python 3.9.1

if I install `selenium==4.0.0.a7` it works fine.

This works fine in full browser mode in windows, I do not have any running Xwindows on linux

**Comment by diemol** [comment] 2021-03-12 09:57
Duplicate of #9188
Fix will be available for `beta-2`, which should be released next week.

**Closed as completed by diemol** 2021-03-12 09:57 UTC
