### ISSUE TITLE
Google registration redirect does not work with Selenium 3.11.0

### ISSUE THREAD

**Issue by davidmhatton** [SeleniumHQ/selenium#5653] opened 2018-03-21 14:29 UTC
## Meta -
OS:
linuxkit, MacOS

Selenium Version: 
3.11.0

Browser: 
Chrome

Browser Version:  
65.0.3325.162 (Official Build) (64-bit)

## Expected Behavior -
User is expected to register Google Docs as an external service with an external LMS. The user is faced with the standard google login process - three screens, one each for user id, password, and authorization acceptance. The user provides the appropriate information on the first two screens, clicking next after populating the input, and then clicks Accept on the final input, at which point they are redirected back to the LMS having authorized its usage of their Google Drive.

## Actual Behavior -
The google username screen and password screen display as expected, however the third step where the google interface renders the Authorize permissions screen instead renders a white page.

## Steps to Reproduce -
```
from selenium import webdriver
import time

driver = webdriver.Chrome()

driver.get("https://fiddle.jshell.net/davidmhatton/vebhu27g/show/light/")
time.sleep(5)


print driver.page_source
assert "redirected" in driver.page_source

driver.quit()

```

## Other Notes -
The third stage should render a permissions dialog,  but instead the body has a `location.redirect` js call, but it is not executed, and thus it is not found. Registering with the same username and password works when performed manually.
**_Selenium versions 3.9.1 and 3.10.0 are unaffected._**

**Comment by barancev** [comment] 2018-03-22 06:35
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by davidmhatton** [comment] 2018-03-23 11:34
@barancev I have updated the comments with steps to reproduce.

**Comment by AntaninaKaltsova** [comment] 2018-03-28 08:18
We've got the same issue using 
- Windows 10, MacOS;
- Selenium-standalone 6.13.0;
- 2.33-x64-chromedriver;
- Chrome Version 65.0.3325.181 (Official Build) (64-bit).

**Comment by testphreak** [comment] 2018-03-28 23:20
The issue isn't related to Selenium from my investigation. The issue seems to have been introduced with ChromeDriver greater than v2.35. There's [2357](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2357) and [2359](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2359) on the `chromedriver` project that talks about this issue. There is an active conversation on another [thread](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2354) currently on that project, related to this issue.

**Comment by barancev** [comment] 2018-04-03 19:01
@testphreak Thank you for sharing the links to the chromedriver issues. Closing this one, there is nothing to be done in selenium client libs, the issue should be fixed in chromedriver.

**Closed by barancev** 2018-04-03 19:01 UTC
Labels: D-chrome, R-awaiting answer
