### ISSUE TITLE
Caught Exception on HTML Runner 3.6.0

### ISSUE THREAD

**Issue by bearx3f** [SeleniumHQ/selenium#4894] opened 2017-10-18 02:57 UTC
## Meta -
**OS:**  
Windows 8.1

**Selenium Version:**  
Html Runner 3.6.0

**Browser:**  
Google Chrome

**Browser Version:**  
61.0.3163.100 (Official Build) (64-bit)

**Driver Version:**
ChromeDriver 2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f)

## Expected Behavior -
Run HTML test suite exported form Selenium IDE

## Actual Behavior -
**Caught exception**
java.net.MalformedURLException: unknown protocol: d
        at java.net.URL.<init>(URL.java:600)
        at java.net.URL.<init>(URL.java:490)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.determineSuiteUrl(HTMLLauncher.java:185)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:106)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.mainInt(HTMLLauncher.java:245)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.java:273)

## Steps to reproduce -
java -Xmx1G -jar /d/Selenium/selenium-html-runner-3.6.0.jar \
  -htmlSuite \
    "*googlechrome" \
    "https://www.google.com/" \
    "/d/Selenium/testcases/test-suite.html" \
    "/d/Selenium/testcases/test-suite-result.html"

**Comment by barancev** [comment] 2017-10-18 11:46
What OS is this? What type of console do you use?

**Comment by X3STeNLiTE** [comment] 2017-10-18 11:50
**OS:** Windows 8.1
**Console:** git-bash

**Comment by barancev** [comment] 2017-10-18 12:05
Can you reproduce the issue in the regular Windows console?

**Comment by X3STeNLiTE** [comment] 2017-10-19 09:00
Yes I can reproduce with windows console.

![image](https://user-images.githubusercontent.com/9717561/31762797-8c8a8304-b4e6-11e7-8744-ec0f971ca304.png)

**Comment by X3STeNLiTE** [comment] 2017-11-01 07:19
any updates?

**Comment by barancev** [comment] 2017-11-08 15:15
I still have no idea why this error occurs, and I can't reproduce it.
There are the lines that throw:
```
URL serverUrl = server.getURI().toURL();
return new URL(serverUrl.getProtocol(), serverUrl.getHost(), serverUrl.getPort(), "/tests/");
```
If serverUrl is a valid url, how can it return invalid (unknown) protocol? Need more time for investigation.

By the way, try to upgrade JDK.

**Comment by cgoldberg** [comment] 2017-11-08 16:41
@bearx3f 
The `MalformedURLError` is happening because "/d/Selenium/testcases/test-suite.html" is not in valid URL format (including protocol).  A URL for a local file would begin with the "file" protocol, like: `file://my/local/file`.

**Comment by barancev** [comment] 2017-11-08 20:27
@cgoldberg It should not be. CLI option accepts a path, not an URL. We publish this file to an embedded web server and attempt to get URL of the published resource, and something goes wrong at this stage.

**Comment by bearx3f** [comment] 2017-11-14 06:25
@barancev, Now I can't reproduce that issue, I don't know what happened.

![image](https://user-images.githubusercontent.com/9717561/32765866-f609cfe4-c93e-11e7-8b8c-01bf6358dcab.png)

![image](https://user-images.githubusercontent.com/9717561/32765902-20a5c758-c93f-11e7-8e4e-830a1bdfaa40.png)

**Comment by barancev** [comment] 2017-11-16 14:49
If you can't reproduce the issue anymore -- yes, please close it. And feel free to reopen if it happens again.

**Closed** 2017-11-17 09:46 UTC
Labels: C-htmlrunner, I-needs investigation, R-awaiting answer
