### ISSUE TITLE
4.0.0 release does not support switch_to_frame

### ISSUE THREAD

**Issue by bnx05** [SeleniumHQ/selenium#9920] opened 2021-10-14 08:31 UTC
## 🐛 Bug Report

Switching to frames no longer works in this release.

## To Reproduce

This can be done on any site using iframes. The moment the code tries to switch to an iframe, you get the `AttributeError: 'WebDriver' object has no attribute 'switch_to_frame'` error.

Switching back to version 3.141.0 fixes the issue.

## Expected behavior

Switching to frames should still work.

## Test script or set of commands reproducing this issue

n/a

## Environment

OS: Ubuntu 18.04
Browser: Chromium
Browser version: 93.0.4577.63
Browser Driver version: ChromeDriver 93.0.4577.63
Language Bindings version: Python 3.7.4

**Comment by cvnboss** [comment] 2021-10-14 10:58
@bnx05 According to the latest documentation, you should use `driver.switch_to.frame(iframe)` instead of `driver.switch_to_frame(frame)` which was deprecated:
https://www.selenium.dev/documentation/webdriver/browser_manipulation/#frames-and-iframes

**Comment by AutomatedTester** [comment] 2021-10-14 13:23
thanks @cvnboss you are correct.

The `switch_to_frame` method had been deprecated and was removed. You can now use the `switch_to.` property and then use other methods neatly.

closing as working as intended

**Closed as completed by AutomatedTester** 2021-10-14 13:23 UTC
Labels: C-py
