### ISSUE TITLE
WebElement.getAttribute("class") does not comply with javadoc on Chrome/FF/IE + Java

### ISSUE THREAD

**Issue by acdcjunior** [SeleniumHQ/selenium#1256] opened 2015-11-16 00:22 UTC
[`WebElement#getAttribute()`](https://selenium.googlecode.com/svn/trunk/docs/api/java/org/openqa/selenium/WebElement.html#getAttribute(java.lang.String)), when using `ChromeDriver`, `FirefoxDriver` or `InternetExplorerDriver`, does not comply with its javadoc specification (bold is mine):

> Get the value of a the given attribute of the element. Will return the current value, even if this has been modified after the page has been loaded. More exactly, this method will return the value of the given attribute, unless that attribute is not present, in which case the value of the property with the same name is returned. **If neither value is set, null is returned**. The "style" attribute is (...). Finally, the following commonly mis-capitalized attribute/property names are evaluated as expected:
- "class"
-  "readonly"

> Parameters:
name - The name of the attribute.

> Returns:
The attribute's current value or null if the value is not set.

The element `<p id="no-class">an element without class attribute</p>` returns `""` for `.getAttribute("class")`, when `null` is expected.

Note: The `HtmlUnitDriver` works fine.

Other attributes, with random names (such as `"other"`), return `null`.

----
**Reproducing:**

```html
<!DOCTYPE html>
<html>
	<body>
		<p id="no-class">an element without class attribute</p>
	</body>
</html>
```

```java
WebDriver driver = new ChromeDriver();              
driver.get("...");
WebElement p = driver.findElement(By.id("no-class"));
String classAttr = p.getAttribute("class"); // classAttr is "", when it should be null
String otherAttr = p.getAttribute("other"); // otherAttr is null, as expected
```

Chrome executable is 2.20, IEDriverServer is 2.48.0. Selenium-java is 2.48.2. JDK is 7.

**Comment by lukeis** [comment] 2015-11-19 21:36
The problem is class is a 'special' attribute that also shows up as a DOM property. For these cases selenium checks on 'special' attributes for their property value. All browsers return an empty string for the className property, even if it was never set.

In this case the javadoc is accurate, since it's returning the DOM property value. HTMLUnit is an outlier and doesn't evaluate DOM Objects the same way that normal browsers do.

I'm going to close this for now as 'working as intended'.

**Closed by lukeis** 2015-11-19 21:36 UTC

**Comment by acdcjunior** [comment] 2015-11-19 22:59
Ah, of course, the `className` property! Guess I was thrown off by HtmlUnit. Anyway, makes complete sense now. Thanks!
