### ISSUE TITLE
IDE: Select Target BROKEN

### ISSUE THREAD

**Issue by jeremytipton** [SeleniumHQ/selenium#3519] opened 2017-02-15 23:00 UTC
## Meta -
OS:  Mac OS 10.12.3
Selenium Version:  IDE 2.9.1
Browser:  Firefox 51.0.1 (64-bit)

## Expected Behavior -
Using Selenium IDE with Firefox, I used to be able to click the Select button on the Selenium controller window, and then when I clicked on an element on a regular Firefox browser window, it would highlight the area on that window, and also fill in a "Target" value on the Selenium controller window.

## Actual Behavior -
Now, when I click that Select button and then click onto the regular Firefox browser window, nothing happens (no highlighting; nothing filled in for the Target value).

The following Screencast shows how this very basic feature no longer works:
https://www.screencast.com/t/SS6rWIjNevG

**Comment by samitbadle** [comment] 2017-02-17 06:48
Can you send me the diagnostic info from Selenium IDE?

**Comment by jeremytipton** [comment] 2017-02-17 17:34
Hi Samit,

 

Actually, I found a posting elsewhere advising that users of the latest Firefox version install a plugin called “Flow Control”.

I did that, and now everything seems to be working fine.

 

 

Thank you for following up.

 

-Jeremy

-- 

Jeremy Tipton | Rightsline | Quality Assurance | jtipton@rightsline.com

**Comment by barancev** [comment] 2017-03-03 22:50
A duplicate of #3435?

**Comment by jeremytipton** [comment] 2017-03-03 22:53
Yes, it does seem to be duplicate of that ticket.

The Flow Control plugin fixed this for me.

 

-- 

Jeremy Tipton | Rightsline | Quality Assurance | jtipton@rightsline.com

**Comment by MichelAmin47** [comment] 2017-03-10 11:14
Flow control fixed the targeting issue for me as well. FireFox 51.0.1 Selenium IDE 2.9.1

**Comment by barancev** [comment] 2017-08-31 13:18
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/

**Closed by barancev** 2017-08-31 13:18 UTC
Labels: C-ide
