### ISSUE TITLE
Windows reports "Firefox has stopped working" when using Java "driver = new FirefoxDriver()"

### ISSUE THREAD

**Issue by gunterfuchs** [SeleniumHQ/selenium#584] opened 2015-05-28 17:43 UTC
public void setUp() throws Exception {
    driver = new FirefoxDriver();
  }
When running the Java code above (with NetBeans / Maven Run, JDK 1.8), Windows 7 64-bit reports "Firefox has stopped working" (Firefox version 38.0.1).
Work-around: Close error box. Everything continues running fine after closing the Windows error box.

**Comment by jleyba** [comment] 2015-05-28 18:40
Duplicate of #437 

Also, in the future, please be sure to include which version of Selenium you are using.

**Closed by jleyba** 2015-05-28 18:40 UTC
