### ISSUE TITLE
Selenium not selecting multiple options On Edge Browser (Windows Build 17134)

### ISSUE THREAD

**Issue by ahmadsayeed** [SeleniumHQ/selenium#6225] opened 2018-07-30 09:25 UTC
## Meta -
OS:  Win 10.0.17134

Selenium Version:  3.13.0

Browser:  Microsoft Edge 42.17134.1.0
Microsoft EdgeHtml 17.17134

Browser Version:  Microsoft Edge 42.17134.1.0
                             Microsoft EdgeHtml 17.17134

## Steps to reproduce - 
Kindly run this script with selenium environment. 

```
import java.awt.AWTException;
import java.util.Arrays;
import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.support.ui.Select;

public class EdgeMultipleSelectFail {

	public static void main(String[] args) throws InterruptedException, AWTException {

		System.setProperty("webdriver.edge.driver", "drivers/MicrosoftWebDriver.exe");
		WebDriver driver = new EdgeDriver();

		driver.get("https://html.com/attributes/select-multiple/");
		
		WebElement element = driver.findElement(By.xpath("//*[@id='post-291']/div/div[2]/select"));
		Select selectData = new Select(element);

		try {
			String value = "American flamingo;Andean flamingo;Chilean flamingo;Greater flamingo;James's flamingo;Lesser flamingo";
			String[] values = value.split(";");
			System.out.println("********" + Arrays.toString(values));
			List<WebElement> option = element.findElements(By.tagName("option"));
			for (int i = 0; i < values.length; i++) {
				boolean match = false;
				try {
					for (WebElement webElement : option) {
						if (webElement.getText().equalsIgnoreCase(values[i])) {
							match = true;
							selectData.selectByVisibleText(values[i]);
							break;
						}

					}
					if (!match) {
						System.out.println("No Match Found");
					}

				} catch (Exception e) {
					System.out.println("No Match Found 2");
				}
			}

		} finally {
			System.out.println("@@@SID: Inside finally");
		}

		Thread.sleep(5000);

		System.out.println("Let's fetch the selected option again");
		List<WebElement> selectedOption = selectData.getAllSelectedOptions();
		for (WebElement ele : selectedOption) {
			System.out.println("After Selection: " + ele.getText());
		}
	}
}

```

I am trying to select all option of select tag using selenium. 
It is working fine at chrome and IE. It is only happening in the case of Edge browser. 
I tried to test it on other websites and getting the same response.

**Comment by GitSage** [comment] 2018-07-31 00:02
I was able to reproduce this bug. Here's a simpler SSCCE that won't attempt to cover the screen with a dialog:

```
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;
import java.util.List;

public class Main {

	public static void main(String[] args) {

		String driverPath = "C:\\dev\\tools\\selenium\\";

		System.setProperty("webdriver.edge.driver", driverPath + "edgedriver.exe");
		WebDriver driver = new EdgeDriver();
		
//		System.setProperty("webdriver.firefox.driver", driverPath + "geckodriver.exe");
//		WebDriver driver = new FirefoxDriver();
		
//		System.setProperty("webdriver.explorer.driver", driverPath + "IEDriverServer.exe");
//		WebDriver driver = new InternetExplorerDriver();
		
//		System.setProperty("webdriver.chrome.driver", driverPath + "chromedriver.exe");
//		WebDriver driver = new ChromeDriver();

		driver.get("https://www.w3schools.com/TAGs/tryit.asp?filename=tryhtml_select_multiple");
		driver.switchTo().frame(driver.findElement(By.id("iframeResult")));
		WebElement element = driver.findElement(By.name("cars"));
		Select selectData = new Select(element);

		selectData.selectByIndex(0);
		selectData.selectByIndex(1);
		selectData.selectByIndex(2);
		selectData.selectByIndex(3);

		List<WebElement> selectedOptions = selectData.getAllSelectedOptions();

		if(selectedOptions.size() != 4) {
			System.out.println("ERROR. Expected 4 options to be selected but there was only " + selectedOptions.size() + ".");
		}
		else{
			System.out.println("SUCCESS. There were 4 selected options as expected.");
		}

		driver.quit();
	}
}
```

Edge is definitely behaving differently than Chrome, FF, and IE. I have no idea what's causing the bug though. #4490 may be related.

**Comment by GitSage** [comment] 2018-07-31 22:32
In [this Microsoft Edge issue](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5437605/), an Edge dev says the following:

>The command used to select an element in your example, oSelect.SelectByIndex(i) executes a normal WebDriver click command. It doesn’t send anything special to the webdriver server to denote that the user would either be holding control or shift, which is what a user would have to do to select multiple options normally. It should however work if you create an Actions object and perform sendKeys off of that object. This way allows for modifier keys to be sent.

This agrees with what I've been able to discover [in the selenium Java source](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/ui/Select.java).

  ```
private void setSelected(WebElement option, boolean select) {
    boolean isSelected=option.isSelected();
    if ((!isSelected && select) || (isSelected && !select)) {
      option.click();
    }
  }
```

So selecting a new option simply clicks it. Edge's behavior looks to be as expected. What's confusing to me at this point is why all the other browsers don't behave the same as the Edge one.

**Comment by twalpole** [comment] 2018-07-31 22:59
@GitSage This is because Edge is not WebDriver compliant for clicking on options elements, whereas the other browser are. 
https://w3c.github.io/webdriver/#element-click - Section 14.1 Step 7.6.3 states that a click on option should just toggle the state of that option if the container has the "multiple" attribute.

**Comment by ahmadsayeed** [comment] 2018-08-01 06:35
Thank you all for the responses. It helped me to make a genuine report that MS Edge is currently not able to multiple select with the simple select call. I tried Robot class to send CTRL key but It also does not work in case of edge. Finally Action class is working to send CTRL key. Now the below program is working.

```
package com.SeleniumScript;

import java.awt.AWTException;
import java.util.List;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;

public class EdgeMultiSelectFail2 {
	public static void main(String[] args) throws InterruptedException, AWTException {

		System.setProperty("webdriver.edge.driver", "drivers/MicrosoftWebDriver.exe");
		WebDriver driver = new EdgeDriver();

		driver.get("https://www.w3schools.com/TAGs/tryit.asp?filename=tryhtml_select_multiple");
		driver.switchTo().frame(driver.findElement(By.id("iframeResult")));
		WebElement element = driver.findElement(By.name("cars"));
		Select selectData = new Select(element);
		
		//new Robot().keyPress(KeyEvent.VK_CONTROL);
		Actions builder = new Actions(driver);
		builder.keyDown(Keys.CONTROL);
		builder.perform();
			selectData.selectByIndex(0);
			selectData.selectByIndex(1);
			selectData.selectByIndex(2);
			selectData.selectByIndex(3);
		//new Robot().keyRelease(KeyEvent.VK_CONTROL);
			builder.keyUp(Keys.CONTROL);
			builder.perform();
			
		List<WebElement> selectedOptions = selectData.getAllSelectedOptions();

		if(selectedOptions.size() != 4) {
			System.out.println("ERROR. Expected 4 options to be selected but there was only " + selectedOptions.size() + ".");
		}
		else{
			System.out.println("SUCCESS. There were 4 selected options as expected.");
		}

		Thread.sleep(2000);
		driver.quit();
	}
}
```

**Comment by barancev** [comment] 2018-08-09 09:58
Closing this issue as it should be fixed in Edge driver by Microsoft.

**Closed by barancev** 2018-08-09 09:58 UTC

**Comment by sivakk2003** [comment] 2018-09-11 05:53
I too facing the same issue not able to select more than one value from list can please help us on this
package iframehandler;


import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.util.List;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;

public class EdgeMultiSelectFail {
	public static void main(String[] args) throws InterruptedException, AWTException {

		System.setProperty("webdriver.chrome.driver", "D:\\\\Eclipse\\\\Drivers\\\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();

		driver.get("http://techcanvass.com/Examples/multi-select.html");
		//driver.switchTo().frame(driver.findElement(By.id("iframeResult")));
		WebElement element = driver.findElement(By.id("multiselect"));
		Select selectData = new Select(element);
		
		new Robot().keyPress(KeyEvent.VK_CONTROL);
		Actions builder = new Actions(driver);
	//	builder.keyDown(Keys.LEFT_SHIFT).click();
	//	builder.perform();
			selectData.selectByIndex(2);
			builder.keyDown(Keys.CONTROL).sendKeys("a");
			selectData.selectByIndex(1);
			builder.keyDown(Keys.LEFT_SHIFT).click();
			selectData.selectByIndex(2);
			selectData.selectByIndex(3);
		//new Robot().keyRelease(KeyEvent.VK_CONTROL);
			builder.keyUp(Keys.CONTROL);
			builder.perform();
			
		List<WebElement> selectedOptions = selectData.getAllSelectedOptions();

		if(selectedOptions.size() != 4) {
			System.out.println("ERROR. Expected 4 options to be selected but there was only " + selectedOptions.size() + ".");
		}
		else{
			System.out.println("SUCCESS. There were 4 selected options as expected.");
		}

		Thread.sleep(2000);
		driver.quit();
	}
}

**Comment by GitSage** [comment] 2018-09-11 15:46
@sivakk2003 what else do you want to know that's not already in the comments? We've explained why it happens, exactly how Edge isn't compliant with the spec, exactly why the Edge team needs to be the ones to fix this, and the OP posted a functioning code sample of a workaround that handles the situation on Edge. 

What's your question exactly?

**Comment by ffMathy** [comment] 2019-02-25 15:17
How can this be reported to Microsoft?

**Comment by jimevans** [comment] 2019-02-25 17:11
@ffMathy There used to be regular mechanisms for this. However, given that Microsoft has announced that they're migrating [Edge to be based on Chromium](https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/), and that they've redirected all development efforts toward that effort, which implies that no development attention is being given to fixing issues in the existing implementation, I'm not sure what good reporting it would do.

**Comment by GitSage** [comment] 2019-02-25 17:15
It appears that he already posted to the Edge developer issue tracker https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/20638074/
