### ISSUE TITLE
Selenium 3.4.0 has corrupt sources and javadoc 

### ISSUE THREAD

**Issue by shoutcool** [SeleniumHQ/selenium#4340] opened 2017-07-19 19:54 UTC
The published sources and javadoc file on the central maven repository are empty: 
see: https://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-java/3.4.0/selenium-java-3.4.0-sources.jar

Due to this corrupt files. Selenium 3.4.0 is not usable with Eclipse if the "Download Sources" or "Download javadoc" checkbox is enabled in the maven preferences settings.

Disabling the "Download sources/javadoc" just because of selenium is no option. Would be nice to fix this little issue, because it affect a lot of developers, which are downloading the sources/javadoc from their dependencies

thx

**Comment by p0deje** [comment] 2017-07-26 09:13
Duplicate of #3895

**Closed by p0deje** 2017-07-26 09:13 UTC
