### ISSUE TITLE
Selenium IDE 2.9.1

### ISSUE THREAD

**Issue by folu6643** [SeleniumHQ/selenium#4427] opened 2017-08-08 21:12 UTC
Getting error on loading for Selenium IDE 2.9.1. My IDE doesn't run, I cannot add test cases or open a test suite or create or record one! Error as followings: 
There was an unexpected error. Msg: TypeError: obj is undefined
Url: chrome://implicit-wait/content/implicit-wait-ide.js?1502226081789, line: 185, column: 9
wrap@chrome://implicit-wait/content/implicit-wait-ide.js?1502226081789:185:9
ImplicitWait/<@chrome://implicit-wait/content/implicit-wait-ide.js?1502226081789:27:9 

There was an unexpected error. Msg: TypeError: obj is undefined
Url: chrome://idex/content/extensions/implicit-wait-ide.js?1502226081808, line: 217, column: 9
wrap@chrome://idex/content/extensions/implicit-wait-ide.js?1502226081808:217:9
ImplicitWait/<@chrome://idex/content/extensions/implicit-wait-ide.js?1502226081808:27:9
Function.prototype.bind/<@chrome://selenium-ide/content/selenium-core/lib/prototype.js:48:12

## Meta -
OS:  windows 10

Selenium Version:  2.9.1 IDE

Browser:  FireFox 55

Browser Version:  55 (64 bit)

**Comment by barancev** [comment] 2017-08-09 05:36
Duplicate of #4406

**Closed by barancev** 2017-08-09 05:36 UTC

**Comment by ivaylasim** [comment] 2017-08-22 06:21
I have the same issue on my side: 

> 
There was an unexpected error. Msg: TypeError: obj is undefined
Url: chrome://implicit-wait/content/implicit-wait-ide.js?1503382739677, line: 185, column: 9
> 
and it's not fixed

**Comment by SameerZaman** [comment] 2017-09-05 23:18
seeing the same issue: 

![9-5-2017 5-17-16 pm](https://user-images.githubusercontent.com/18600846/30087483-2485a6ee-925e-11e7-9984-31a145d62969.png)
