### ISSUE TITLE
Issues Screenshotting a single WebElement

### ISSUE THREAD

**Issue by frmsaul** [SeleniumHQ/selenium#3140] opened 2016-11-19 20:55 UTC
## Meta 
OS:  
MacOS El Capitan
Selenium Version:  
selenium 3.0.1

Browser Version:  
I tried running it on both with the Chrome and Firefox drivers, and got the same error on both. 
    Firefox: Version 50.0 
    Chrome: Version 54.0.2840.71 (64-bit)

## Expected Behavior 
No Exceptions, no errors thrown. full execution. 

## Actual Behavior 
Im getting this error:
`Traceback (most recent call last):
  File "test_browser_capture.py", line 17, in <module>
    image.screenshot("Google.png");
  File "/Users/saulfuhrmann/Computers/VirtualEnviroments/SalamProject/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 446, in screenshot
    png = self.screenshot_as_png
  File "/Users/saulfuhrmann/Computers/VirtualEnviroments/SalamProject/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 433, in screenshot_as_png
    return base64.b64decode(self.screenshot_as_base64.encode('ascii'))
  File "/Users/saulfuhrmann/Computers/VirtualEnviroments/SalamProject/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 423, in screenshot_as_base64
    return self._execute(Command.ELEMENT_SCREENSHOT)['value']
  File "/Users/saulfuhrmann/Computers/VirtualEnviroments/SalamProject/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "/Users/saulfuhrmann/Computers/VirtualEnviroments/SalamProject/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Users/saulfuhrmann/Computers/VirtualEnviroments/SalamProject/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: GET /session/6fb0929a-fa17-d342-be72-34250d66dd3c/screenshot/ecc4ff0c-fed2-934f-8d7c-58cf476d666a did not match a known command`

## Steps to reproduce 
You can reproduce this by running this code:
[CODE](https://gist.github.com/frmsaul/5acf493bfef548a68272cf37346aab8c)

Any idea what might be the cause and where I should look for a solution?

**Comment by lukeis** [comment] 2016-11-20 16:36
this is a duplicate of #912

It should be available with geckodriver, if it's not working there, please log a bug with mozillla.

It looks as though it hasn't been logged against chromedriver as an issue yet, i would recommend doing so here:
https://bugs.chromium.org/p/chromedriver/issues/list

**Closed by lukeis** 2016-11-20 16:36 UTC

**Comment by frmsaul** [comment] 2016-11-21 13:59
I don't think it's an issue with Firefox since I have the exact same problem with Chrome. 
Is the screenshot feature implemented in Chrome?
