### ISSUE TITLE
Error in IE11: A JavaScript error was encountered executing the findElement atom

### ISSUE THREAD

**Issue by Bantolomeus** [SeleniumHQ/selenium#1724] opened 2016-03-01 12:15 UTC
Excuse me for bad layout, especially for the code (It does not matter if I use the `` or not, looks ugly as it does right now)

## Actual Behavior - opens web page but do not type "Selenium" into the search field and throwing the following error code:

Started InternetExplorerDriver server (32-bit)
2.52.0.0
Listening on port 9308
Only local connections are allowed
Google
Exception in thread "main" org.openqa.selenium.WebDriverException: A JavaScript error was encountered executing the findElement atom. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 31 milliseconds
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'vm-gkgui1', ip: '10.16.0.11', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_73'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, pageLoadStrategy=normal, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:9308/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}]
Session ID: 3c46f5c2-933a-40eb-8857-775ebabe78e4
*** Element info: {Using=id, value=lst-ib}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:413)
	at org.openqa.selenium.By$ById.findElement(By.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
	at com.google.test.IeRunning.main(IeRunning.java:22)

## Steps to reproduce - run my Code (my Code from Eclipse):

package com.google.test;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;

public class IeRunning {

	public static void main(String[] args) throws InterruptedException {

		System.setProperty("webdriver.ie.driver",
"C:\\Users\\lokal\\workspace\\jarfiles\\IEDriverServer32.exe");
		WebDriver driver = new InternetExplorerDriver();
		
		driver.get("www.google.com");
		driver.manage().window().maximize();
		System.out.println(driver.getTitle());
		Thread.sleep(2000);
		driver.findElement(By.id("lst-ib")).sendKeys("Selenium");
		driver.close();	
		
	}
}

**Comment by jimevans** [comment] 2016-03-01 12:49
Duplicate of #1590 and #1600, fixed in dd61210, and released in 2.52.1 of `IEDriverServer.exe`.

**Closed by jimevans** 2016-03-01 12:49 UTC
