### ISSUE TITLE
[🐛 Bug]: The previously configured ChromeDriver service is still running. (wrong error message for unsupported chromedriver version?)

### ISSUE THREAD

**Issue by Ploppz** [SeleniumHQ/selenium#10683] opened 2022-05-23 09:17 UTC
### What happened?

My tests ran fine before a system upgrade. Now I get: Even if running my tests is the first thing I do after booting my computer.
```
Error: The previously configured ChromeDriver service is still running. You must shut it down before you may adjust its configuration.
    at Object.setDefaultService (/home/ploppz/oa/minos/ui/node_modules/.pnpm/selenium-webdriver@4.1.2/node_modules/selenium-webdriver/chrome.js:262:11)
    at buildChromeDriver (/home/ploppz/oa/minos/ui/tests/features/support/world.js:20:10)
```

### How can we reproduce the issue?

The code is not open source, but I have a suspicion that it has to do with my version of `chromium`. I'm on Arch Linux, and after the system update, my `chromium` version is `101`. Does Selenium support this chromium version? If not, then perhaps the error message could be improved.

### Operating System

Arch Linux

### Selenium version

4.1.2

### What are the browser(s) and version(s) where you see this issue?

chromium 101

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 101

**Comment by diemol** [comment] 2022-05-23 10:14
Yes, 101 is supported. We would need any code snippet that help us reproduce the issue. It does not need to be the exact same one you use for your work.

**Comment by titusfortner** [comment] 2022-05-23 13:55
This is the code in Selenium that results the error:
https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/chrome.js#L261-L264

I don'w know the Selenium JS code very well, but from this description here, it sounds like it matters how you are constructing your driver: https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/chrome.js#L54-L80

What code are you using to start/stop the driver?

**Comment by Ploppz** [comment] 2022-05-23 14:12
[example.zip](https://github.com/SeleniumHQ/selenium/files/8755230/example.zip)

I managed to reproduce it minimally. I'm using selenium in conjunction with `cucumber`. It works fine with one test (one .feature file), but once I have two tests, it fails:
```
$ npm test

> repr@1.0.0 test
> ./node_modules/.bin/cucumber-js tests

A
.B
.C
..Error: The previously configured ChromeDriver service is still running. You must shut it down before you may adjust its configuration.
    at Object.setDefaultService (/tmp/repr/node_modules/selenium-webdriver/chrome.js:262:11)
    at buildChromeDriver (/tmp/repr/tests/features/support/world.js:14:10)
    at buildDriver (/tmp/repr/tests/features/support/world.js:29:14)
    at new CustomWorld (/tmp/repr/tests/features/support/world.js:36:19)
```
I guess it's this that isn't quite working:
```js
After(function() {
    return this.driver.quit();
});
```
and what's puzzling is that it worked fine until my latest system update.

Edit: Missed your comment, but I guess this answers your question.

**Comment by titusfortner** [comment] 2022-05-23 15:15
Is it a race condition? If you add some sleeps does it still fail?

**Comment by Ploppz** [comment] 2022-05-24 15:38
There doesn't seem to be any way to sleep the thread in Javascript? Only callback or async sleeps.

**Comment by titusfortner** [comment] 2022-05-24 22:26
should be able to do it in Selenium?
https://stackoverflow.com/a/33905860/4072371

JS I mostly have to guess at, regardless.

**Comment by diemol** [comment] 2022-06-08 10:32
The "problem" is that the JS bindings will use a single instance of ChromeDriver for all sessions. It was previously working because a change made it possible but brought another bunch of bugs, so it was reverted. 

Ideally, we need to change the JS bindings so each Chrome session uses its own ChromeDriver, but many places need to be touched for that.

For now, if you delegate the creation of the driver entirely to the bindings, it should work.

**Comment by diemol** [comment] 2022-07-08 12:36
Closing this as https://www.npmjs.com/package/selenium-webdriver/v/4.3.1 is out and it includes the fix where a ChromeDriver per session is launched.

**Closed as completed by diemol** 2022-07-08 12:36 UTC
Labels: J-awaiting answer, C-nodejs, I-defect
