### ISSUE TITLE
[py] https://github.com/SeleniumHQ/selenium/pull/8096 broke RemoteConnection subclass selection for chrome

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#8521] opened 2020-07-14 09:40 UTC
## 🐛 Bug Report

https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/remote/webdriver.py#L106

get_remote_connection checks for browser_name
#8096 removed it from class

## To Reproduce

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by AutomatedTester** [comment] 2020-07-14 09:58
The tests are working, as in browser launch and automation happening, in the tree on our CI.

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by ghost** [comment] 2020-07-16 17:32
see https://github.com/SeleniumHQ/selenium/issues/7959

**Comment by AutomatedTester** [comment] 2020-07-16 17:45
closing as no new information has been given when asked. If you give an example of this not working I will reopen.

**Closed as completed by AutomatedTester** 2020-07-16 17:45 UTC
Labels: J-awaiting answer

**Comment by ghost** [comment] 2020-07-17 06:50
```
from selenium import webdriver
from selenium.webdriver.chromium.remote_connection import ChromiumRemoteConnection
from selenium.webdriver.firefox.remote_connection import FirefoxRemoteConnection

with webdriver.Remote("http://127.0.0.1:4444", webdriver.FirefoxOptions().to_capabilities()) as driver:
    print("FirefoxRemoteConnection?: ")
    print(isinstance(driver.command_executor,FirefoxRemoteConnection))
    
with webdriver.Remote("http://127.0.0.1:4444", webdriver.ChromeOptions().to_capabilities()) as driver:
    print("ChromiumRemoteConnection?: ")
    print(isinstance(driver.command_executor,ChromiumRemoteConnection))
```

```
FirefoxRemoteConnection?: 
True
ChromiumRemoteConnection?: 
False
```

**Comment by ggalan87** [comment] 2020-07-27 13:23
I can confirm the issue, which is obvious... The constructor for ChromiumRemoteConnection expects vendor_prefix and browser_name which for that case in the following line are not passed: https://github.com/SeleniumHQ/selenium/blob/273ce9bbc0881a0d53f11599bb8666addfe6681b/py/selenium/webdriver/remote/webdriver.py#L117 

I don't know which fix should be preferred, either having same constructor signatures or specialized for each webbrowser, because I am not aware if such two keywords are anyway probable to be different than vendor_prefix='goog', browser_name='chromium'.
