### ISSUE TITLE
[🐛 Bug]: Response code 500. Message: Could not start a new session. Could not start a new session. Timed out waiting for driver server to shutdown.

### ISSUE THREAD

**Issue by kaviraja339** [SeleniumHQ/selenium#10163] opened 2021-12-18 03:48 UTC
### What happened?

While executing the selenium automation script in docker selenium grid in facing the below issue. Please help me to resolve this issue

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not start a new session. Could not start a new session. Timed out waiting for driver server to shutdown.

### How can we reproduce the issue?

```shell
DesiredCapabilities dr1 =new DesiredCapabilities();
			dr1.setCapability("browserName", browser);
//			dr1.setBrowserName(BrowserType.CHROME);
			dr1.setCapability("platformName", Platform.LINUX);
			System.out.println(gridurl);
			DriverManager.setDriver(new RemoteWebDriver(new URL(ConfigUtil.getpropertyvalue("GRIDURL")), dr1));
			System.out.println(browser);
			System.out.println(ConfigUtil.getpropertyvalue("GRIDURL"));
		DriverManager.getDriver().get(ConfigUtil.getpropertyvalue("ApplicationURL"));
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not start a new session. Could not start a new session. Timed out waiting for driver server to shutdown.
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: '813fdc3658fa', ip: '172.23.180.150', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.27-linuxkit', java.version: '11.0.11'
Driver info: driver.version: unknown
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: '813fdc3658fa', ip: '172.23.180.150', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.27-linuxkit', java.version: '11.0.11'
Driver info: driver.version: unknown
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'ff91e36f0b77', ip: '172.23.178.249', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.27-linuxkit', java.version: '11.0.11'
Driver info: driver.version: unknown
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'LENOVO', ip: '172.17.240.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_301'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, platformName: linux}], desiredCapabilities=Capabilities {browserName: chrome, platformName: LINUX}}]
Capabilities {}
```

### Operating System

Windows 10

### Selenium version

java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 96

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 96

### Are you using Selenium Grid?

version 4

**Comment by pujagani** [comment] 2021-12-20 12:04
Thank you for providing the details. Locally, when I run a test against docker Selenium Grid in Standalone mode I am unable to reproduce the error. Can you please share a reproducible working test script/project and instructions to run the same?
Additionally, provide the details regarding which docker image are you running and steps to run the same. It will help us replicate the same setup locally and reproduce the issue you are facing. 
Are you seeing the error only on `driver.quit()`? Does it happen every time or intermittently?

**Comment by kaviraja339** [comment] 2021-12-22 04:02
When i try to execute the test script in selenium grid, it's connecting to the grid. But it's not executing the script in node.  it's not even start to execute the test script in node. Please find the my demo project in below git hub link https://github.com/kaviraja339/Automation_Practice.git

**Comment by pujagani** [comment] 2021-12-22 11:20
Thank you for providing the project. Can you help me with instructions to run the same?

**Comment by kaviraja339** [comment] 2021-12-23 02:30
1. Import the maven project in eclipse
2. Setup the grid environment using docker-compose.yml file project
3. Run the paralle-testng.xml file in project to execute the script in grid environment

**Comment by pujagani** [comment] 2021-12-28 06:45
Thank you! Also, how are you running the Grid?

**Comment by pujagani** [comment] 2021-12-28 08:34
Thank you for sharing the details. I have attempted to reproduce the problem locally and was unable to reproduce it. All the tests pass. I have used the docker composed file shared in the project. 
OS: MacOS Big Sur 
Version: 11.4 

Are you also facing the issue when using a local Grid jar or only when using Docker?

**Comment by mr-possible** [comment] 2022-01-10 17:35
Hi @kaviraja339 , I saw your code and could see that in the config.properties file, the **EXECUTION=grid** is commented out. Maybe, that is why you are facing the issue ? Please confirm.

**Comment by mr-possible** [comment] 2022-01-10 18:07
> Hi @kaviraja339 , I saw your code and could see that in the config.properties file, the **EXECUTION=grid** is commented out. Maybe, that is why you are facing the issue ? Please confirm.

Hey ! I confirmed from my end. Please uncomment the above property in your config.properties. You will see the tests running in the grid.


**Few suggestions I'd like to give :** 
1. Remove typos from your project (Keep the naming conventions also apt)
2. Maintain an understandable folder structure.
3. Give deployment/execute instructions in README. It is a good practice and highly appreciable from the community.
4. You can still clean your docker-compose file by keeping names and parameters simple and straight. Research more on this.

**Comment by diemol** [comment] 2022-01-20 21:07
Thank you for helping and troubleshooting, @mr-possible!

I will close this issue given that the above comment solves this.

**Closed as completed by diemol** 2022-01-20 21:07 UTC
Labels: B-grid, I-defect
