### ISSUE TITLE
jdk out of memory after running selenium standalone server for a long time

### ISSUE THREAD

**Issue by link89** [SeleniumHQ/selenium#9685] opened 2021-07-26 02:54 UTC
## 🐛 Bug Report

When I use the docker image to start a standalone service on a CentOS 7 node with the following command,

docker run -p 5555:4444 -v /dev/shm:/dev/shm -e SE_NODE_MAX_SESSIONS=20 -e SE_NODE_SESSION_TIMEOUT=60 -e SE_OPTS="--grid-url http://1.2.3.4:5555/wd/hub --max-threads 20" selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618

Everything is fine at the beginning, but after about 3-4 days the JVM will crash due to the out-of-memory issue. You can find the log in the attachment.

[selenum4-oom.log](https://github.com/SeleniumHQ/selenium/files/6875246/selenum4-oom.log)

docker image: selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618
os: linux (docker)

**Comment by diemol** [comment] 2021-07-26 15:56
Assuming you actually have enough memory to run 20 sessions in parallel, and due to the large amount of `Driver Service Executor` seen in the log, I would say that this was fixed in #9677. 

We will do a pre-release with this fix later this week, you can try again then.

If the issue is still present, then feel free to comment and we can reopen.

**Closed as completed by diemol** 2021-07-26 15:56 UTC

**Comment by link89** [comment] 2021-08-02 01:36
@diemol Where I can find the pre-release that contain this fix?

**Comment by diemol** [comment] 2021-08-04 14:30
You can find it in the assets section of this release
https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-rc-1-prerelease-20210804
