### ISSUE TITLE
[🐛 Bug]: Angular page hangs post using WebDriverWait, isDisplayed() or isEnabled()

### ISSUE THREAD

**Issue by surajgupta7175** [SeleniumHQ/selenium#12801] opened 2023-09-21 08:15 UTC
### What happened?

We are using Angular Page with lodash library on our website. Till Sep 1 this was working fine but post that it has started failing.

Whenever we use explicit wait, isDisplayed(), isEnabled() our website hangs and we are not able to perform any other command post that such as click etc.

angular: 1.5.11
lodash: 4.14.1
Selenium : 4.12.1

Pre - Execution of Webdriver Wait command, lodash library value 

![Screenshot 2023-09-15 at 7 07 38 PM](https://github.com/SeleniumHQ/selenium/assets/16059218/a0620553-d13a-475c-95ff-9402104454cf)

Post - Execution of Webdriver Wait command, lodash library value becomes 

![Screenshot 2023-09-15 at 7 10 50 PM](https://github.com/SeleniumHQ/selenium/assets/16059218/f403de34-4840-4860-b773-0bde4939e82f)

Test Website to replicate the issue - https://dev.test121.com/

Wait for above link to load in this state and then run isDisplayed() command from below code (line12) 
Run in debug mode to see the result

<img width="1177" alt="Screenshot 2023-09-21 at 1 39 17 PM" src="https://github.com/SeleniumHQ/selenium/assets/16059218/48de128e-7da1-417f-8c0c-41cdde759623">

### How can we reproduce the issue?

```shell
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

public class lodashIssue {

	public static void main(String[] args) throws InterruptedException {
		ChromeOptions chromeOptions = new ChromeOptions();
		ChromeDriver driver= new ChromeDriver(chromeOptions);
		
		driver.navigate().to("https://test121.pg.com/");
		boolean isSignIn = driver.findElement(By.xpath("//button[text()='Sign in']")).isDisplayed(); // or you can use isEnabled() or WeebdriverWait's any condition
		driver.findElement(By.xpath("//button[text()='Sign in']")).click();
		

	}

}
```

### Relevant log output

```shell
There is no action when driver.findElement(By.xpath("//button[text()='Sign in']")).click(); is executed post isDispalyed() line

Try removing isDisplayed() line and then run in debug mode it works fine
```

### Operating System

Windows or Mac

### Selenium version

4.12.1 but occurring in old 4.11.1 as well

### What are the browser(s) and version(s) where you see this issue?

Every Chrome and firefox

### What are the browser driver(s) and version(s) where you see this issue?

116, 115,114 Chrome and all firefox

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment] 2023-09-21 21:59
This is a duplicate of #12659. It's fixed for the next release.

**Closed as completed by titusfortner** 2023-09-21 21:59 UTC
Labels: I-defect, A-needs-triaging

**Comment by surajgupta7175** [comment] 2023-09-22 08:26
Thanks @titusfortner
