### ISSUE TITLE
[🐛 Bug]: Unable to establish websocket connection when creating a RemoteWebDriver with a ClientConfig

### ISSUE THREAD

**Issue by evertones** [SeleniumHQ/selenium#11131] opened 2022-10-15 16:34 UTC
### What happened?

Selenium Tests fail when running against a Selenium Grid with a `RemoteWebDriver` created using `ClientConfig`.
It throws an exception with an output similar to this: `org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://172.18.0.3:4444/session/62ac7350b644ef5425d989331280e26f/se/cdp`.

### How can we reproduce the issue?

I created a repo with the issue - https://github.com/evertones/selenium4-java.
It is possible to reproduce the issue by:
- cloning the repo above
- starting the grid with `<repo>/docker/docker-compose up -d` (1 node is enough)
- running the test with `./gradlew clean test -Ptest.suite=org.evertones.AppTest`

To reproduce manually:

1. Create a method to create a `RemoteWebDriver` and pass a `ClientConfig` to it (I've tried using the `RemoteWebDriver` constructor and the `RemoteWebDriverBuilder` - both present the same issue)
```
    public RemoteWebDriver createRemoteWebDriver() throws MalformedURLException{
        ClientConfig config = ClientConfig
                .defaultConfig()
                .connectionTimeout(Duration.ofSeconds(5))
                .readTimeout(Duration.ofMinutes(5));

        return (RemoteWebDriver) RemoteWebDriver.builder()
                .address(seleniumGridUrl)
                .oneOf(new ChromeOptions())
                .config(config)
                .build();
    }
```

2. Run tests against a Selenium Grid (I used the Docker Image [image 4.5.0-20221004](https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.5.0-20221004))
3. Tests will fail and a stacktrace indicating that it was not possible to establish websocket connection will the seen

### Relevant log output

```
org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://172.18.0.3:4444/session/62ac7350b644ef5425d989331280e26f/se/cdp
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.2'
Driver info: driver.version: unknown
	at app//org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:102)
	at app//org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:128)
	at app//org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:107)
	at app//org.openqa.selenium.devtools.Connection.<init>(Connection.java:77)
	at app//org.openqa.selenium.devtools.SeleniumCdpConnection.<init>(SeleniumCdpConnection.java:34)
	at app//org.openqa.selenium.devtools.SeleniumCdpConnection.lambda$create$0(SeleniumCdpConnection.java:56)
	at java.base@11.0.2/java.util.Optional.map(Optional.java:265)
	at app//org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:54)
	at app//org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:47)
	at app//org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:50)
	at app//org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:31)
	at app//org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:186)
	at app//org.openqa.selenium.remote.RemoteWebDriverBuilder.build(RemoteWebDriverBuilder.java:375)
	at app//org.evertones.selenium.WebDriverFactory.createRemoteChromeInstanceWithConfig(WebDriverFactory.java:29)
	at app//org.evertones.AppTest.setUp(AppTest.java:24)
	at java.base@11.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.2/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at app//org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at app//org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base@11.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.2/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

### Operating System

macOS Monterrey 12.4

### Selenium version

Selenium 4.5.0 with Java 11 (openjdk 11.0.2 2019-01-15)

### What are the browser(s) and version(s) where you see this issue?

Chrome 106.0.5249.91

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 106.0.5249.61

### Are you using Selenium Grid?

Selenium Grid 4.5.0 using the Docker Selenium image - Release 4.5.0-20221004

**Comment by pujagani** [comment] 2022-10-17 04:45
Thank you for providing the details. After looking at the repo shared, it seems the issue is with the setup. Please have a look at the README of docker-selenium: https://github.com/SeleniumHQ/docker-selenium#grid-url-and-session-timeout

Using `SE_NODE_GRID_URL` should solve this. Please try it out. Thank you!

**Comment by diemol** [comment] 2022-10-17 09:29
It is exactly what @pujagani says, I will close this since it is a common issue users run into when using the Docker containers.

**Closed as completed by diemol** 2022-10-17 09:29 UTC
