### ISSUE TITLE
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument

### ISSUE THREAD

**Issue by preetymavenwave** [SeleniumHQ/selenium#10965] opened 2022-08-21 11:13 UTC
### What happened?

Hi,

I was running a script on Selenium 4.2 with Webdriver Manager and encountered an issue.

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import time

driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))

driver.get("//https:www.google.com")
time.sleep(100)
driver.find_element(By.ID, "input").click()
driver.quit()


Python 3.10

Selenium 4.2

Chrome Version 104.0.5112.102 (Official Build) (64-bit)
```

### Relevant log output

```shell
------------------------------------------------------------------------- Captured stderr --------------------------------------------------------------------------
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 104.0.5112
[WDM] - Get LATEST chromedriver version for 104.0.5112 google-chrome
[WDM] - Driver [C:\Users\Preety Gupta\.wdm\drivers\chromedriver\win32\104.0.5112.79\chromedriver.exe] found in cache
===================================================================== short test summary info ======================================================================
ERROR test_sel.py - selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================= 1 error in 6.67s =========================================================================
```

### Operating System

Windows 10

### Selenium version

Selenium 4.2

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 104.0.5112.102 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Version 104.0.5112.102 

### Are you using Selenium Grid?

No

**Comment by symonk** [comment] 2022-08-21 12:24
edit: ignore this I misread your example, sorry for pre-emptively closing.

**Comment by symonk** [comment] 2022-08-21 12:27
I suspect the problem is your url to the `.get(...)` call; should be `https://` not `//https`

**Closed as completed by symonk** 2022-08-21 12:27 UTC
