### ISSUE TITLE
IE Driver Beta 3.3.99.4- UnsupportedCommandException: mouseMoveTo

### ISSUE THREAD

**Issue by hazmeister** [SeleniumHQ/selenium#3973] opened 2017-05-04 21:48 UTC
## Meta -
OS:  Windows 10.0.14393 (as node)
Selenium Version:  3.4.0
Browser:  Internet Explorer 11.1066.14393
IE Driver Version: 3.3.99.4

## Expected Behavior -
Browser on the remote node should scroll window so link is within viewport, and virtual mouse should hover over link.

## Actual Behavior -
UnsupportedCommandException is thrown:
[Exception thrown in IDE](https://gist.github.com/hazmeister/661913006e249a3e8c1c3aa1f4660d2b)
[Exception thrown on node](https://gist.github.com/hazmeister/1a4ca30be2ad5b893e693e6dea6c7ecf)

## Steps to reproduce -
    @Test
    public void defaultScroll() throws IOException {
        URL hub = null;
        try {
            hub = new URL("http://127.0.0.1:4444/wd/hub");
        } catch (MalformedURLException e) {

        }
        DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
        driver = new RemoteWebDriver(hub, capabilities);
        driver.get("http://the-internet.herokuapp.com/");
        WebElement link = driver.findElement(By.linkText("Infinite Scroll"));
        new Actions(driver).moveToElement(link).perform();    //Exception thrown here
    }

**Comment by lmtierney** [comment] 2017-05-04 21:54
Duplicate of #3693

**Comment by jimevans** [comment] 2017-05-04 21:55
This is a duplicate of the same issue regarding geckodriver where the remote server does not yet pass through the commands using the correct protocol dialect. I'll find the dupe number when I'm not on a mobile device, but I'm closing this one for now.

**Closed by lmtierney** 2017-05-04 21:54 UTC
