### ISSUE TITLE
IEDriverServer hangs (3.150.1.0)

### ISSUE THREAD

**Issue by black-snow** [SeleniumHQ/selenium#8488] opened 2020-07-07 09:03 UTC
## 🐛 Bug Report

Lately the IEDriverServer seems to hang. My tests time out and when I take a look at the remote machine I see a bunch of empty open IEs ("...should connect to <PORT>") together with a bunch of IE server processes (and conhost). The tests themselves haven't changed since the last time they were working fine. I've restarted both machines involved. No error messages except the timeouts.

> Error forwarding the new session new session request for webdriver should contain a location header or an 'application/json;charset=UTF-8' response body with the session ID. Command duration or timeout: 600.03 seconds

Had to stop the test suite because it's too flaky atm.

This is probably hard to reproduce and hard to debug. Please let me know if I can provide more information. The test details and the page under test are confidential but this doesn't seem to be an issue with the page.

## To Reproduce

Detailed steps to reproduce the behavior:

Sadly, it's hard to reproduce. It works sometimes, sometimes it doesn't.

Simple test
```java
DesiredCapabilities dc = DesiredCapabilities.internetExplorer();
dc.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
dc.setCapability("browser_version", "11.0");
dc.setCapability("requireWindowFocus", true);
dc.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
try {
    driver = new RemoteWebDriver(new URL(remoteMachineUrl), dc);
}
catch (MalformedURLException e) {
    fail("Bad remote machine URL? " + remoteMachineUrl);
    return;
}

// ... nothing fancy in the tests - they don't even load the inital URL

driver.get(url);

// ...
```

## Expected behavior

An IE11 should pop up on the remote machine and start loading the URL.

## Test script or set of commands reproducing this issue

s. a.

## Environment

OS: debian 9 (running the selenium tests) - Windows 7 x64 (running the hub and nodes)
Browser: IE 11
Browser version: 11.0.9600.19230
Browser Driver version: 3.150.1.0 x32
Language Bindings version: π (3.141.59)
Selenium Grid version (if applicable): π

**Comment by diemol** [comment] 2020-09-07 22:47
@black-snow did this happen after an upgrade of IEDriver? What has changed in the environment?

**Comment by black-snow** [comment] 2020-09-09 07:22
Phew, it's been a while. Yes, I think the only change on the remote side was an upgrade of the driver.

**Comment by Jeremy-Code-F** [comment] 2020-09-10 12:49
I am also seeing something similar, happens about once every 2 weeks very hard to reproduce
Driver version: 3.150.1.0 (32-bit)
Browser: IE 11.3866.14393.0
OS Windows 10 version 1909 x64
Fails at the exact same place that black-snow mentioned, the last thing that the driver logs show when the issue happens is 
```
...
D 2020-09-09 04:26:13:733 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(1056) Looking for 12444
D 2020-09-09 04:26:13:733 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(513) Found window handle 0078082A for window with class 'Internet Explorer_Server' belonging to process with id 12444
D 2020-09-09 04:26:13:817 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(456) Ignoring zoom setting: 0
D 2020-09-09 04:26:13:858 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(777) Browser zoom level is 100%
I 2020-09-09 04:26:13:859 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(1368) Persistent hovering set to: 1
D 2020-09-09 04:26:13:859 C:\Projects\webdriver\cpp\iedriver\ProxyManager.cpp(119) Using existing system proxy settings.
```

as opposed to this when it is successful
```
...
D 2020-09-09 08:11:49:881 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(456) Ignoring zoom setting: 0
D 2020-09-09 08:11:49:929 C:\Projects\webdriver\cpp\iedriver\BrowserFactory.cpp(777) Browser zoom level is 100%
I 2020-09-09 08:11:49:932 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(1368) Persistent hovering set to: 1
D 2020-09-09 08:11:49:932 C:\Projects\webdriver\cpp\iedriver\ProxyManager.cpp(119) Using existing system proxy settings.
D 2020-09-09 08:11:49:938 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(883) Command execution for newSession complete
D 2020-09-09 08:11:49:938 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(935) Setting serialized response to {
	"value" : 
...
```

**Comment by diemol** [comment] 2020-09-10 20:32
OK, so this only happens after upgrading the IE Server, is that correct?
The hard part here is, how to reproduce? When it happens, is it after 10 tests? 100 tests?
Perhaps the bottom line here is that we do not have a way to reproduce it, the overall comment is "it happens sometimes"... We would really appreciatte if you could give us a more deterministic way to reproduce it... Otherwise I think the issue will stale over time.

**Comment by black-snow** [comment] 2020-11-25 14:54
@diemol some more intel:

It now happens like 97.3% of the times for a new test I just added.
It seems like I cannot run two tests in parallel and to sometimes even get stuck when I run them in sequence but closely one after another.

When I start a new test while another is running the former gets stuck / killed. Is this intended? (`selenium-server-standalone-3.141.59` hub, 2 nodes on the same machine)

When running many tests in production I see several IE windows being open at their driver start page and a bunch of `IEDriverServer.exe` and `conhost.exe`. When I close the right window / kill the right `IEDriverServer.exe` the stuck tests moves on and finishes as expected.

![ieserver](https://user-images.githubusercontent.com/579733/100243593-55d9ab00-2f36-11eb-9d7d-b52ee969138f.png)

/edit: hub and node params are their defaults
/edit: I'll try to gather the stack traces from both hub and node next time
/edit: parallel issues might be due to `dc.setCapability("requireWindowFocus", true);`

**Comment by black-snow** [comment] 2020-11-26 09:05
Some stack traces that might help. I run Chrome and IE11 on the same machine:

```
22:30:29.929 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.Servi
cedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 87.0.4280.20 (c99e81631faa0b2a448e658c0dbd8311fb04ddbd-refs/branch-heads/4280@{#355}) on port 2125
1
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
22:30:32.434 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
22:30:32.434 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 94b3625662f163fcf4e1e65ac5eedf
fc (org.openqa.selenium.chrome.ChromeDriverService)
22:30:57.957 INFO [ActiveSessions$1.onStop] - Removing session 94b3625662f163fcf4e1e65ac5eedffc (org.openqa.selenium.chr
ome.ChromeDriverService)
22:46:04.197 WARN [RemoteSession$Factory.performHandshake] - Read timed out
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at org.openqa.selenium.remote.internal.OkHttpClient$Factory$1.lambda$createClient$1(OkHttpClient.java:152)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:105)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
        at org.openqa.selenium.grid.session.remote.RemoteSession$Factory.performHandshake(RemoteSession.java:147)
        at org.openqa.selenium.grid.session.remote.ServicedSession$Factory.apply(ServicedSession.java:161)
        at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$12(ActiveSessionFactory.java:180)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$11$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
        at org.openqa.selenium.remote.server.ActiveSessionFactory.apply(ActiveSessionFactory.java:183)
        at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$2(NewSessionPipeline.java:66)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.Collections$2.tryAdvance(Unknown Source)
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
        at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$3(NewSessionPipeline.java:69)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.stream.DistinctOps$1$2.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Unknown Source)
        at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Unknown Source)
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
        at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession(NewSessionPipeline.java:72)
        at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:65)
        at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:235)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
22:46:04.197 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "internet explorer",
  "platformName": "windows"
}
22:46:04.197 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.Servi
cedSession$Factory (provider: org.openqa.selenium.ie.InternetExplorerDriverService)
Started InternetExplorerDriver server (32-bit)
3.150.1.0
Listening on port 12685
```


```
22:44:02.357 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.Se
cedSession$Factory (provider: org.openqa.selenium.ie.InternetExplorerDriverService)
Started InternetExplorerDriver server (32-bit)
3.150.1.0
Listening on port 34888
Only local connections are allowed
22:44:03.667 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
22:44:03.667 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 86a8136b-128d-481d-b693-8fb
766cf5 (org.openqa.selenium.ie.InternetExplorerDriverService)
22:44:16.198 INFO [ActiveSessions$1.onStop] - Removing session 86a8136b-128d-481d-b693-8fba22766cf5 (org.openqa.selen
.ie.InternetExplorerDriverService)
22:56:04.298 WARN [RemoteSession$Factory.performHandshake] - Read timed out
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at org.openqa.selenium.remote.internal.OkHttpClient$Factory$1.lambda$createClient$1(OkHttpClient.java:152)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
...
```

```
19:56:03.711 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: internet
explorer, browser_version: 11.0, ensureCleanSession: true, ie.ensureCleanSession: true, ignoreProtectedModeSettings: tru
e, platform: WINDOWS, requireWindowFocus: true, version: }
19:56:03.727 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=590090e5-32
d5-4569-b662-33208f414cfa, seleniumProtocol=WebDriver, browserName=internet explorer, maxInstances=1, platformName=WINDO
WS, platform=WINDOWS}
20:06:03.750 INFO [RequestHandler.process] - Error forwarding the new session new session request for webdriver should c
ontain a location header or an 'application/json;charset=UTF-8' response body with the session ID.
org.openqa.grid.common.exception.GridException: new session request for webdriver should contain a location header or an
 'application/json;charset=UTF-8' response body with the session ID.
        at org.openqa.grid.internal.TestSession.updateHubIfNewWebDriverSession(TestSession.java:396)
        at org.openqa.grid.internal.TestSession.forward(TestSession.java:240)
        at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.j
ava:91)
        at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:114)
        at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
        at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:69)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Unknown Source)
```

Logging back in to the machine after a day there are 10 IE windows open and 20 `IEDriverServer.exe` running (hanging).
Hub and Nodes are running on a Win7 Pro SP1 VM.

**Comment by black-snow** [comment] 2020-11-26 12:16
Another hint: when I kill a blank IE window or kill a `IEDriverServer.exe` most of the time another one pops open as if it only waited for the former to finish.

**Comment by diemol** [comment] 2021-03-16 12:27
Apologies for the late reply, we've been busy with Selenium 4 activites. 

If I understand correctly, this issue happens when IE tests are executed concurrently on the same machine? Have you tried to run them locally to discard an issue with Grid? IE does not have the concept of profiles and that is why concurrent tests could lead to scenarios where unexpected errors happen. 
Additionally, maybe you can try with Grid 4?

**Comment by black-snow** [comment] 2021-03-16 12:40
So we should probably put a tag on "IEDriver" saying "do not run things in parallel here or there be dragons", right? Maybe Grid can deny/queue such parallel runs for IE?

**Comment by diemol** [comment] 2021-03-16 12:53
It is hard to do it because some people have been able to do it, things can work under different environments.
In Grid 4, IE is restricted to 1 execution per Node and the rest are queued.

**Comment by diemol** [comment] 2021-04-08 08:41
I will close this as in Grid 4 it is possible to run only one IE session per Node, which will fix these type of issues.

**Closed as completed by diemol** 2021-04-08 08:41 UTC
Labels: J-awaiting answer, D-IE
