### ISSUE TITLE
[🐛 Bug]: Selenium manager not found via Anaconda distribution

### ISSUE THREAD

**Issue by Fradhyle** [SeleniumHQ/selenium#11234] opened 2022-11-08 05:40 UTC
### What happened?

I tried to test new Selenium manager feature with Python 3.9.13 and Edge 107.0.1418.35 (Stable) (64bit), but the exception occurs.

The code I tried
```python
from selenium import webdriver
driver = webdriver.Edge()
```
and the message is this
`WebDriverException: Message: 'msedgedriver' executable needs to be in PATH. Please download from https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/`

If I enter `msedge` on the 'Run' window, Edge browser opens normally.

### How can we reproduce the issue?

```shell
from selenium import webdriver
driver = webdriver.Edge()
```

### Relevant log output

```shell
WebDriverException                        Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\common\service.py in start(self)
     96                 try:
---> 97                     path = SeleniumManager.driver_location(browser)
     98                 except WebDriverException as new_err:

C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\common\selenium_manager.py in driver_location(browser)
     66
---> 67         args = (str(SeleniumManager.get_binary()), "--browser", browser)
     68         result = SeleniumManager.run(args)

C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\common\selenium_manager.py in get_binary()
     51         if not path.is_file():
---> 52             raise WebDriverException("Unable to obtain Selenium Manager")
     53

WebDriverException: Message: Unable to obtain Selenium Manager


During handling of the above exception, another exception occurred:

WebDriverException                        Traceback (most recent call last)
<ipython-input-2-9e8e880ac5d1> in <cell line: 1>()
----> 1 driver = webdriver.Edge()

C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\edge\webdriver.py in __init__(self, executable_path, port, options, service_args, capabilities, service_log_path, service, keep_alive, verbose)
     71             service = Service(executable_path, port, service_args, service_log_path)
     72
---> 73         super().__init__(
     74             DesiredCapabilities.EDGE["browserName"],
     75             "ms",

C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\chromium\webdriver.py in __init__(self, browser_name, vendor_prefix, port, options, service_args, desired_capabilities, service_log_path, service, keep_alive)
    101
    102         self.service = service
--> 103         self.service.start()
    104
    105         try:

C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\common\service.py in start(self)
     98                 except WebDriverException as new_err:
     99                     logger.debug("Unable to obtain driver using Selenium Manager: " + new_err.msg)
--> 100                     raise err
    101
    102                 self._start_process(path)

C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\common\service.py in start(self)
     89         """
     90         try:
---> 91             self._start_process(self.path)
     92         except WebDriverException as err:
     93             if "executable needs to be in PATH" in err.msg:

C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\common\service.py in _start_process(self, path)
    201         except OSError as err:
    202             if err.errno == errno.ENOENT:
--> 203                 raise WebDriverException(
    204                     f"'{os.path.basename(self.path)}' executable needs to be in PATH. {self.start_error_message}"
    205                 )

WebDriverException: Message: 'msedgedriver' executable needs to be in PATH. Please download from https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
```

### Operating System

Windows 10 Enterprise 22H2

### Selenium version

Python 4.6.0

### What are the browser(s) and version(s) where you see this issue?

Edge 107.0.1418.35 (Stable) (64bit)

### What are the browser driver(s) and version(s) where you see this issue?

Selenium Manager

**Comment by titusfortner** [comment] 2022-11-08 13:18
Hmm, it's failing on conditional `if not path.is_file()`. Which is coming from:
```
Path(__file__).parent.joinpath(directory, file)
```
On my mac this is: `/Users/titusfortner/code/seleniumhq.github.io/examples/python/venv/lib/python3.9/site-packages/selenium/webdriver/common/macos/selenium-manager`

1. We should add the path to the error message so it can be investigated. 
2. @symonk maybe the way I'm setting the directory doesn't work for all the weird ways people use Python?

**Comment by symonk** [comment] 2022-11-08 13:37
@Sweetbarrow can you drop the output of this in your script:

```
import sys
print(sys.executable)
```

As a side note; we should list the files in the path etc to debug better in future.  Once you have the interpreter path above can you check the file system on disk inside its `lib/python.x/site-packages/*` to find the directories inside `selenium/webdriver/common/*` for the platform

**Comment by Fradhyle** [comment] 2022-11-08 13:43
Hi, @symonk 
This is the output you requested.
```
C:\ProgramData\Anaconda3\python.exe
```
Plus, I can see `selenium_manager.py` inside `C:\ProgramData\Anaconda3\Lib\site-packages\selenium\webdriver\common`
By the way, I tried same code on Windows 11 22H2, Edge 107.0.1418.35 (Stable) (64 bit), Python 3.9.13 and the same error has raised.

**Comment by symonk** [comment] 2022-11-08 13:48
I will get access to a windows machine and use `anaconda` to test it out thanks! I suspect its to do with that explicitly; as a work around you could manually put the edge driver on your path for now.  Thanks for the report.

@Sweetbarrow  is there a `/common/windows/selenium-manager.exe` file in there?

**Comment by Fradhyle** [comment] 2022-11-08 13:52
@symonk No.
I thought it's included in the code like [webdriver_manager by Sergey Pirogov](https://github.com/SergeyPirogov/webdriver_manager), isn't it?

**Comment by Fradhyle** [comment] 2022-11-08 13:56
@symonk I just downloaded seperate executable from Github and it works well now.
As I just said, I thought it works like [webdriver_manager](https://github.com/SergeyPirogov/webdriver_manager) and didn't think it requires seperate executable.

**Comment by titusfortner** [comment] 2022-11-08 13:57
there is a separate selenium manager executable that is distributed and it is what is figuring out which driver to get.

**Comment by Fradhyle** [comment] 2022-11-08 13:59
@titusfortner Thank you for your answer.
It was my mistake.

**Comment by symonk** [comment] 2022-11-08 14:13
this _should_ be working by default @titusfortner no? I don't think we should close it. (without requiring additional manual installs; pip install should suffice?)

**Comment by Fradhyle** [comment] 2022-11-08 14:17
As user of Selenium, I hope Selenium manager included when get package from package manager.
I don't know how [webdriver_manager](https://github.com/SergeyPirogov/webdriver_manager) works exactly, but the phrase 'batteries included' from [Selenium blog article](https://www.selenium.dev/blog/2022/introducing-selenium-manager/) makes me confused.
That's why I thought it was a bug.

**Comment by titusfortner** [comment] 2022-11-08 14:22
Sorry. I was unclear.

There are 3 selenium-manager executables (one for each of the 3 major OS's) that are bundled with the various selenium packages, including inside the whl file.

Selenium 4.6 in Python should include a `selenium\common\windows\selenium-manager.exe` file.

For some reason on your machine, it appears that it is not getting found. I know relative file path is trickier in Python than the other languages for *reasons, so it's probably a bug in how it is getting referenced. It might be related to anaconda. We should have had the path it looking for in the error message so we could more easily figure out where it is looking instead of where it should be looking.

**Comment by Fradhyle** [comment] 2022-11-08 14:26
@titusfortner Oh...
Thank you for the answer.
I'll look forward to be fixed in the future release.
For your information, I installed Selenium 4.6.0 by execute `conda update --all -c conda-forge` from Anaconda Powershell Prompt run as Administrator because I was using previous release of Selenium.

**Comment by symonk** [comment] 2022-11-09 17:10
the version shipped by `conda` does in fact not ship with the manager directory; I assume conda maybe tries to use a source distribution with setuptools directly? and we don't use that ourselves unfortunately.  Assume they are cloning and relying on `setup.cfg/setup.py` which is completely normal in the python world for most packages, as for a solution - I'm not quite sure as we rely on bazel to do things and don't support the normal python build backend machinery right now.

**Comment by titusfortner** [comment] 2022-11-10 22:35
My question is what are we doing differently with devtools that we aren't doing for Selenium-Manager?

**Comment by symonk** [comment] 2022-11-11 22:51
@titusfortner possibly [this](https://github.com/SeleniumHQ/selenium/blob/trunk/py/BUILD.bazel#L141) but I haven't a clue how bazel operates really

**Comment by AutomatedTester** [comment] 2022-11-11 23:17
Bazel likes things to be explicit. It probably needs you to specify the
module, even if it is auto generated.

It might be worth trying to add `"py.selenium.webdriver.common.linux",
"py.selenium.webdriver.common.windows",` and so on so that it links up the
python packaging ideas like if it were a `MANIFEST.in` file

**Comment by titusfortner** [comment] 2022-12-01 14:29
Fixed in #11329

**Comment by titusfortner** [comment] 2023-05-02 15:45
Did I close this incorrectly? I can't tell if there was a fix and I linked the wrong thing to close this, or if this wasn't actually fixed. We have a new report (#11980) that it is still not working.
 @symonk can you verify?

**Comment by titusfortner** [comment] 2023-05-09 17:40
@KittyMurphy in response to your question on the other thread...

Selenium Manager only works with what is bundled in the bindings.

But if you have the latest Selenium Manager built on your machine, try:
```
./selenium-manager --browser chrome --browser-path /location/to/anaconda/chrome --debug
```

**Comment by KittyMurphy** [comment] 2023-05-13 14:35
@titusfortner I don't have Selenium Manager as it seems to be missing in the conda distribution. For those that are experiencing this issue, I did a pip install instead and now everything seems to be working fine.

**Comment by titusfortner** [comment] 2023-05-13 17:36
Oh, right, the issue isn't like snap where the driver is special, the issue is that it doesn't actually show up with Selenium.

**Comment by stevetracvc** [comment] 2023-08-11 15:27
I found a workaround. Conda has a separate library, selenium-manager, that is installed in the environment's bin folder. I'll submit a PR in a few minutes

**Closed as completed** 2023-08-15 11:35 UTC
Labels: C-py, I-defect, C-rust
