### ISSUE TITLE
Set firefox profile from pre-existing browser profile or set extension protractor

### ISSUE THREAD

**Issue by tamvo94** [SeleniumHQ/selenium#3500] opened 2017-02-13 16:14 UTC
I have 2 ways set firefox profile:

> var makeFirefoxProfile = function (preferenceMap) {
>   var profile = new firefox.Profile("./ozbzfc4i.automation");
>   for (var key in preferenceMap) {
>     profile.setPreference(key, preferenceMap[key]);
>   }
>   
>   return q.resolve({
>     browserName: 'firefox',
>     marionette: true,
>     firefox_profile: profile
>   });
> };

and code load web extension:

> var makeFirefoxProfile = function (preferenceMap) {
>   var profile = new firefox.Profile();
>   for (var key in preferenceMap) {
>     profile.setPreference(key, preferenceMap[key]);
>   }
>   profile.addExtension('./firebug.xpi');
>   
>   return q.resolve({
>     browserName: 'firefox',
>     marionette: true,
>     firefox_profile: profile
>   });
> };
**But it cannot set profile and browser opens multiple tabs when run, not single tab.**
I follow this article: http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox/index.html
I don't know how wrong???

**Comment by lmtierney** [comment] 2017-02-13 20:16
What do you mean it opens multiple tabs not single tab? From your issue here (https://github.com/saadtazi/firefox-profile-js/issues/82) you were using firefox-profile-js before, since you no longer use it you don't get the default firefox preferences (https://github.com/saadtazi/firefox-profile-js/blob/master/lib/firefox_profile.js#L25) If you want it to open multiple windows instead of multiple tabs you need to set this https://github.com/saadtazi/firefox-profile-js/blob/master/lib/firefox_profile.js#L32. Default for geckodriver is 3

**Comment by tamvo94** [comment] 2017-02-14 01:42
Hi lmtierney,
I'm using `require('selenium-webdriver/firefox').Profile;`, not firefox-profile package.
The problem here is filefox cannot load profile from pre-existing browser profile.
If I declare `var profile = new firefox.Profile();` it works ok.
If I declare var profile = new firefox.Profile("./ozbzfc4i.automation"); I could not find profile ozbzfc4i.automation loaded.
I want to set firefox profile from pre-existing browser profile with param **./ozbzfc4i.automation**
Thanks

**Comment by lmtierney** [comment] 2017-02-14 01:43
I understand what you're doing. How do you know it isn't using the profile?

**Comment by tamvo94** [comment] 2017-02-14 01:48
I installed extension, edit config, whatever,... when protractor load firefox profile ./ozbzfc4i.automation, I want to see things I did earlier are shown, example: extensions I install are loaded 
Thanks :)

**Comment by lmtierney** [comment] 2017-02-14 01:51
Is it giving you an error? What do you see if you put a breakpoint in and check the `about:config` page within Firefox, do you see your preferences as you set them?

**Comment by tamvo94** [comment] 2017-02-14 01:57
It is still running normally, no error, but I cannot see extension I installed and path download file I set earlier. When I add `profile.addExtension('./firebug.xpi'); `not use pre-existing browser profile, It also show the same case. Thanks

**Comment by lmtierney** [comment] 2017-02-14 02:31
Are you sure it's not loaded? I just tried it with firebug and it's loaded but is disabled.

**Comment by lmtierney** [comment] 2017-02-14 02:45
Make sure you use the root directory of the profile you pass it and not the local directory

**Comment by tamvo94** [comment] 2017-02-14 02:48
Hi, can you help me reprodurce at [my repo](`https://github.com/tamvo94/config-firefox`) in 2 way. I want to try set firefox profile from pre-existing browser profile because load extension is disabled. Thanks.

**Comment by tamvo94** [comment] 2017-02-14 02:52
Attach image: http://www.upsieutoc.com/image/YcERRQ

**Comment by tamvo94** [comment] 2017-02-14 06:44
Hi lmtierney,
What is the root directory of the profile???

`C:\Users\...\AppData\Roaming\Mozilla\Firefox\Profiles\avbq6r8s.TamVo`
or C:\Windows, or whatever folder contains profile,....
Thanks

**Comment by lmtierney** [comment] 2017-02-26 03:56
Go to `about:profiles` in the browser and copy the path for the `Root Directory`

**Comment by tamvo94** [comment] 2017-02-28 02:53
Hi lmtierney,
I set profile `var firefoxProfile = new FirefoxProfile("C:/Users/.../AppData/Roaming/Mozilla/Firefox/Profiles/avbq6r8s.T")`;
But i have an error:
```
 WebDriverError: java.io.FileNotFoundException: C:\Users\...\AppData\Local\Temp\webdriver3207885029359577597duplicated\C:\Users\...\AppData\Local\Temp\tmp-12720YNCuK
ZQFwPPR\addons.json (The filename, directory name, or volume label syntax is incorrect)
```

**Comment by lmtierney** [comment] 2017-02-28 04:05
`FirefoxProfile("C:/Users/.../AppData/Roaming/Mozilla/Firefox/Profiles/avbq6r8s.T")` does not match your `C:\Users\...\AppData\Roaming\Mozilla\Firefox\Profiles\avbq6r8s.TamVo` that you said earlier

**Comment by tamvo94** [comment] 2017-02-28 04:11
Sorry, I edited last comment FirefoxProfile("C:/Users/.../AppData/Roaming/Mozilla/Firefox/Profiles/avbq6r8s.TamVo"), but issue still occur

**Comment by tamvo94** [comment] 2017-02-28 04:14
Attach root image:
http://www.upsieutoc.com/image/Y2emkL

**Comment by tamvo94** [comment] 2017-02-28 04:26
Error image:
http://www.upsieutoc.com/image/Y2PJtk

**Comment by barancev** [comment] 2017-08-04 14:38
We need a way to reproduce this issue without protractor, using pure official selenium client library.

**Comment by jleyba** [comment] 2017-08-05 21:02
It sounds like you are expecting webdriver changes to impact the
preexisting profile. This is not the case - when you specify an existing
profile it is copied to a new profile, so any changes made with webdriver
will not impact the original.

**Comment by barancev** [comment] 2017-08-31 20:43
Closing the issue, there is no reporoduction scenario provided.

**Closed by barancev** 2017-08-31 20:43 UTC
Labels: D-firefox, R-awaiting answer
