### ISSUE TITLE
Improper setting of window position in Safari

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#1148] opened 2015-10-14 02:32 UTC
Recording bugs for Safari failures from Ruby specs. ["it sets the position of the current window"](https://github.com/SeleniumHQ/selenium/blob/master/rb/spec/integration/selenium/webdriver/window_spec.rb#L66) fails with these commands:
```
>>> {"origin":"webdriver","type":"command","command":{"id":"2","name":"getWindowPosition","parameters":{"windowHandle":"current"}}}
<<< {"origin":0,"type":"response","id":"2","response":{"status":0,"value":{"x":523,"y":23}}}

>>> {"origin":"webdriver","type":"command","command":{"id":"3","name":"setWindowPosition","parameters":{"windowHandle":"current","x":533,"y":33}}}
<<< {"origin":0,"type":"response","id":"3","response":{"status":0}}

>>> {"origin":"webdriver","type":"command","command":{"id":"4","name":"getWindowPosition","parameters":{"windowHandle":"current"}}}
<<< {"origin":0,"type":"response","id":"4","response":{"status":0,"value":{"x":176,"y":27}}}
```

**Comment by jleyba** [comment] 2015-10-14 16:54
The SafariDriver just calls `window.moveTo`, which doesn't actually move where you tell it:

```
  console.log('position:', window.screenX, window.screenY);
  console.log('size:', window.outerHeight, window.outerWidth);

  window.moveTo(500, 300);
  setTimeout(function() {
      console.log('position:', window.screenX, window.screenY);
      console.log('size:', window.outerHeight, window.outerWidth);

      window.moveTo(0, 0);
      setTimeout(function() {
          console.log('position:', window.screenX, window.screenY);
          console.log('size:', window.outerHeight, window.outerWidth);
      });
  });
}, 100);
// position: 483 23
// size: 480 640
// position: 483 23
// size: 480 640
// position: 500 323
// size: 480 640
// position: 0 23
// size: 480 640
```

I believe the y-offset is the height of the status bar in OSX.

**Comment by titusfortner** [comment] 2015-10-15 14:30
I don't understand, are you agreeing this is a bug or saying it works as expected?

According to the [Web API for this command](https://developer.mozilla.org/en-US/docs/Web/API/Window/moveTo), window.moveTo does just that: "Moves the window to the specified coordinates." Additionally Chrome and Firefox both pass my test for this.

**Comment by jleyba** [comment] 2015-10-15 15:17
I'm saying it's a known issue caused by Safari's implementation of `window.moveTo`.

Chrome and Firefox pass b/c they don't rely on `window.moveTo` (in fact, it's a no-op on those browsers)

**Comment by uchuugaka** [comment] 2015-10-22 08:00
You will also need to be careful. The menubar and dock can push windows around a bit by default. Menubar does not allow overlap with a window normally. Dock tends to not like that either. Even a hidden dock keeps an bottom space of a few pixels. No idea what happens when the dock is on one side or the other.

**Comment by jbrower2** [comment] 2016-06-10 13:25
Same issue as in [2242](https://github.com/SeleniumHQ/selenium/issues/2242). A window cannot move/resize itself in most browsers.

**Comment by lukeis** [comment] 2016-09-23 20:18
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.

**Closed by lukeis** 2016-09-23 20:18 UTC
Labels: A-needs new owner, D-safari
