### ISSUE TITLE
Firefox WebDriver crashes with httplib.BadStatusLine

### ISSUE THREAD

**Issue by royragsdale** [SeleniumHQ/selenium#2524] opened 2016-07-26 17:13 UTC
## Meta -

OS:  Linux (Debian Jessie)
Selenium Version:  2.53.6 (python bindings)
Browser:  Firefox
Browser Version:  47.0.1
## Expected Behavior -

Selenium will successfully navigate to a page (http://taobao.com). When manually navigated in the browser this completes sucessfully.
## Actual Behavior -

The webdriver and browser crash with `httplib.BadStatusLine`.
## Steps to reproduce -

```
from selenium import webdriver                                                  

driver = webdriver.Firefox()                                                    
driver.get("http://taobao.com")                                                 
driver.close() 
```

```
Traceback (most recent call last):
  File "test_firefox.py", line 4, in <module>
    driver.get("http://taobao.com")
  File "python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 401, in execute
    return self._request(command_info[0], url, body=data)
  File "/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 433, in _request
    resp = self._conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

```

**Comment by sri85** [comment] 2016-07-26 18:00
This issue is also reproducible on MAC with firefox version 47.0 and selenium version 2.52

**Comment by HelioGuilherme66** [comment] 2016-07-26 18:47
Can't reproduce in my system:

$ cat taobao.py
from selenium import webdriver
driver = webdriver.Firefox()
driver.get("http://taobao.com")
driver.close()
$ python taobao.py
$ date
Ter Jul 26 19:36:01 WEST 2016    # This current time == GMT+1
$ python --version
Python 2.7.10
$ uname -a
Linux new-host 4.4.14-200.fc22.x86_64 #1 SMP Fri Jun 24 21:19:33 UTC
2016 x86_64 x86_64 x86_64 GNU/Linux
$ firefox --version
Mozilla Firefox 45.1.0 # This is latest Firefox ESR
$ pip list
(...)
selenium (2.53.2)
(...)

**Comment by royragsdale** [comment] 2016-07-26 19:21
Additional version information, for what it's worth:
```
$ python --version
Python 2.7.9
$ uname -a
Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jul 6 18:18:53 PDT 2016 x86_64 GNU/Linux
$ firefox --version
Mozilla Firefox 47.0.1
$ pip list |grep selenium
selenium (2.53.6)
```

I'll try with the firefox-esr and see if that works then report back.

**Comment by royragsdale** [comment] 2016-07-26 19:29
Unfortunately, @HelioGuilherme66 even when using the ESR release (45.2.0) I still have this error. 

`test_firefox.py`  is the same code I referenced above
```
$ firefox --version
Mozilla Firefox 45.2.0
$ python test_firefox.py 
Traceback (most recent call last):
  File "test_firefox.py", line 4, in <module>
    driver.get("http://taobao.com")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 401, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 433, in _request
    resp = self._conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```

**Comment by HelioGuilherme66** [comment] 2016-07-26 21:50
Looks like the problem is with httplib.py.
I have upgraded selenium to 2.53.6 and still runs OK. Differences in Python
2.7.9 vs 2.7.10?

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py",
line 433, in _request
>     resp = self._conn.getresponse()
>   File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
>     response.begin()
>   File "/usr/lib/python2.7/httplib.py", line 415, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
>     raise BadStatusLine(line)
> httplib.BadStatusLine: ''
>
>

**Comment by royragsdale** [comment] 2016-07-27 01:39
I've tried across a number of other configuration and in some cases it works fine, but I'm having difficulty pinning down what is broken on this one system (only major difference I haven't isolated is the kernel version).  I would be happy to continue trying to help trouble shoot this bug if anyone has any other ideas, otherwise feel free to close this since it is inconsistently reproducible.

To summarize

The original system still fails (even with 2.7.10), tested the following configurations:
Debian Jessie
Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jul 6 18:18:53 PDT 2016 x86_64 GNU/Linux
Mozilla Firefox 47.0.1 + (python 2.7.9 or 2.7.10)
Mozilla Firefox 45.2.0 + python 2.7.9

On a fresh testing VM everything seems to work without issue (including python 2.7.9)
Debian Stretch
Linux vagrant 4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18) x86_64 GNU/Linux
Mozilla Firefox 45.2.0 + (python 2.7.9, 2.7.10, 2.7.12)

On another system everything also seems to work without issue (python 2.7.9)
Debian Jessie
Linux tower 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
Mozilla Firefox 45.2.0 + python 2.7.9

**Comment by Ekkstein** [comment] 2016-08-01 13:53
I was just about to post that I got the same problem on my mac running Firefox 47 and Selenium 2.53.6. While checking the Firefox version (graphically) I updated to Firefox 47.0.1. Now, I don't know if it really had anything to do with it, but suddenly it works. No clue!

**Comment by generalconsensus** [comment] 2016-08-01 22:32
![Firefox 47 is failing] (https://www.evernote.com/l/AFMig-jiNV5IHoDd52bcfKe-2XqOYzrSuFoB/image.png)

**Comment by AutomatedTester** [comment] 2016-08-08 10:44
If the browser is crashing, and by crashing I mean it is no longer open (the true meaning of a crash), then there is a bigger problem than Selenium just not doing things. Can you see if you can replicate this with Selenium 3.0 beta?

**Comment by HardenDev** [comment] 2016-08-18 09:42
I've also encountered the issue with selenium 2.53.6 / Firefox 47.0.1/Python 2.7.6, do we have anything that can fix this or something workaround about this?

**Comment by makeapp007** [comment] 2016-09-06 10:39
@HardenDev I had the same environment and met the same bug as yours. I solved this bug through updating firefox to 48.0. It worked perfectly on  selenium 2.53.6 / Firefox 48.0 /Python 2.7.6.

**Comment by zqy16** [comment] 2016-11-11 09:17
@royragsdale I also have the same issue with python 2.7.11/Chrome 54.0.2840.87 m/selenium 3.0.1,do you have something to solve?thanks a lot.

**Comment by royragsdale** [comment] 2016-11-14 12:48
@zqy16 unfortunately I never did pin down a good solution.

**Comment by macdonjo** [comment] 2016-11-28 20:18
I can reproduce it on my server, but not on my Mac.

Mac: OSX El Capitan 10.11.6
Server: CentOS 7.2.1511
Both have PhantomJS version: 2.1.1
Python Mac: Python 2.7.11
Python Server: 2.7.5
Both have Selenium version: 2.53.0

**Comment by zqy16** [comment] 2016-12-02 04:02
@royragsdale ,i use Chrome 52.0.2743.82 m (64-bit),and the problem solved.

**Comment by andrewgtp** [comment] 2017-01-06 21:20
I had the same error on OSX 10.10, Chrome 55, Selenium 3.0.2. I grabbed the latest chromedriver 2.27 and its working now: https://chromedriver.storage.googleapis.com/index.html?path=2.27

**Comment by macdonjo** [comment] 2017-01-07 04:34
@andrewgtp @zqy16 please stop suggesting Chrome as a bug patch to Firefox.

**Comment by alexbegun** [comment] 2017-02-02 04:04
This is also caused by firefox not having enough memory.. I sometimes get this error also:

Error while saving screenshot: test.png, Traceback (most recent call last):
  File "screen-capture.py", line 221, in main
    browser.save_screenshot(image_file)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 798, in get_screenshot_as_f
ile
    png = self.get_screenshot_as_png()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 817, in get_screenshot_as_p
ng
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 827, in get_screenshot_as_b
ase64
    return self.execute(Command.SCREENSHOT)['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: out of memory

**Comment by cgoldberg** [comment] 2017-02-02 13:48
@alexbegun that sounds like a completely different issue... not sure why you hijacked this thread

**Comment by lagin** [comment] 2017-04-03 19:20
Can not reproduce it.
Windows 10
Python 2.7/3.4
Selenium 3.3.1
Firefox 52.0.2
geckodriver 0.15.0

**Comment by bofinbabu** [comment] 2017-04-04 09:37
Guys look at this: https://code.google.com/archive/p/httplib2/issues/250

**Comment by cgoldberg** [comment] 2017-04-04 13:23
@bofinbabu
fwiw, selenium doesn't use the http2 package.

**Comment by webjunkie01** [comment] 2017-05-31 21:05
I also experienced the same issue and found out that my server was running out of memory.

**Comment by lmtierney** [comment] 2017-12-06 02:42
Closing as this cannot be reproduced on newer versions. Please open a new issue with a reproducible test scenario of the issue is experienced again.

**Closed by lmtierney** 2017-12-06 02:42 UTC
Labels: C-py, D-firefox

**Comment by zvolsky** [comment] 2018-07-19 09:56
Need newer versions? CentOS (in VirtualBox on Debian/buster), Py 2.7.5, Selenium 3.13.0, GeckoDriver 0.21.0, Mozilla Firefox 61.0.1

**Comment by zvolsky** [comment] 2018-07-19 10:51
https://stackoverflow.com/questions/1767934/why-am-i-getting-this-error-in-python-httplib
exception httplib.BadStatusLine: Raised if a server responds with a HTTP status code that we don’t understand.
In my case I try driver.get() to python.org:
http://python.org and https://www.python.org both work well,
http://www.python.org and https://python.org both fail with BadStatusLine.

**Comment by alirezastack** [comment] 2018-07-24 12:06
It seems that problem happens when my server has low memory. On my MAC everything seems working great by the same code happens to fail on a server with `1GB` of RAM and 1 CPU Core.

Linux: Debian 9 -> `4.9.0-7-amd64 #1 SMP Debian 4.9.110-1 (2018-07-05) x86_64 GNU/Linux`
Selenium: 3.13.0
Geckodriver: 0.21.0
Firefox-ESR: 60.0

Does any one else have the sample problem when their server specification is low?
