### ISSUE TITLE
Selenium 2.53- The browser appears to have exited before we could connect.

### ISSUE THREAD

**Issue by talktokets** [SeleniumHQ/selenium#2335] opened 2016-06-22 10:31 UTC
OS:  Mac OS 10.11.5
Selenium Version:  2.53
Browser:  Firefox 

Browser Version:  
(version 47.0)

## Expected Behavior -
The browser should open and should run the test completely and it should also produce the expected result.

## Actual Behavior -
The browser is triggering. It is opening up for few seconds and then it exits abnormally. It shows the following error message in the console: 

`selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.`

## Steps to reproduce -
- Installed Firefox version 47.0 (latest update)
- Installed Selenium version 2.53
- Wrote a demo script in python using Selenium. Can be found here: https://gist.github.com/talktokets/d02b50ebec3b56cfae011e52a3fab576
- Ran the script

**Comment by lukeis** [comment] 2016-06-22 12:44
Duplicate of #2110

**Closed by lukeis** 2016-06-22 12:44 UTC
