### ISSUE TITLE
Add type hints in python codebase

### ISSUE THREAD

**Issue by hoefling** [SeleniumHQ/selenium#9480] opened 2021-05-15 19:41 UTC
## 🚀 Feature Proposal

Type hints in Python are specified by [PEP 484](https://www.python.org/dev/peps/pep-0484/) and are of a great help when developing, thus proposing to add them to Python codebase. Would this be an option if I volunteer to (gradually) add them, assuming the types are validated in the CI by a checker tool like `mypy` so the types are validated on each pull request?

I have noticed rudimentary type hints already exist here and there, for example

https://github.com/SeleniumHQ/selenium/blob/e9c738de8a587dc6bc86b55949c57b8574ec68bb/py/selenium/webdriver/remote/webdriver.py#L263

indicates that `WebDriver().name` is a string. This offers better code completions in IDEs.

I have searched for similar issues, but it seems like this wasn't discussed yet (at least not on Github). As far as I can see, the only issue mentioning type hints is #1917; however, type stubs were removed since then.

Another alternative would be maintaining a third-party stub package (as specified in [PEP 561](https://www.python.org/dev/peps/pep-0561/#stub-only-packages)). However, I don't want to start a third-party package if you are willing to keep the type hints along with the code (which is a much better option), or planning to add them already.

## Motivation

Better code completion in IDEs is surely something the end users will appreciate. Another advantage is that type hints often  intercept bugs, thus making the code more robust.

**Comment by AutomatedTester** [comment] 2021-05-17 12:08
I am all for this! Feel free to start adding PRs and then tagging me for review.

**Comment by iampopovich** [comment] 2021-11-28 12:31
I'm in

**Comment by Akuli** [comment] 2022-01-22 21:13
When are you going to add a `py.typed` file to tell type checkers to rely on what's in selenium itself, instead of using typeshed's selenium 3.x stubs?

For context, I am a maintainer of typeshed, and I'm wondering if we should upgrade our selenium 3.x stubs to selenium 4.x, or just wait until someone adds a `py.typed` file to selenium 4.x.

**Comment by AutomatedTester** [comment] 2022-01-31 14:56
I haven't got round to adding a `py.typed`. If someone fancies putting a PR up I will review and get it landed as quickly as I can.

**Comment by GergelyKalmar** [comment] 2022-02-23 18:18
I don't think this worked, the py.typed file is still missing from the latest release (4.1.1). Could we get a patch release which fixes that? It would be awesome.

**Comment by Akuli** [comment] 2022-02-24 11:51
Can someone who does the releases tell me what commit the latest pypi release 4.1.1 is based on? There's no tag in the repo (which makes sense, because the x of 4.1.x seems to be Python-specific). Looking at https://github.com/SeleniumHQ/selenium/commits/trunk/py I can see that it does include #10273, but the other two PRs after that don't modify any files that are included in the releases (if my py.typed PR doesn't work, that is).

**Comment by AutomatedTester** [comment] 2022-02-24 12:10
The issue is I forgot to update bazel to pick up the file when building the wheel. I will do that

**Comment by AutomatedTester** [comment] 2022-02-24 12:51
landed in e8e9389f6b793a51e9cf5989eab7b55982ccbf6d

**Comment by AutomatedTester** [comment] 2022-02-24 14:36
4.1.2 has been pushed to pypi with this change. I checked the wheel had the file. Let me know if it doesn't work as expected.

**Comment by Akuli** [comment] 2022-02-24 15:04
It works! Thanks!

**Comment by bersbersbers** [comment] 2022-03-14 06:26
Is there a recommended course of action to follow while this issue is open? For example, `WebDriverWait` is not typed yet, and I am getting many errors such as
> Call to untyped function "WebDriverWait" in typed context  [no-untyped-call]

with `mypy --disallow-untyped-calls`. This does not happen with `types-selenium` installed, but then I am hitting https://github.com/python/typeshed/issues/7379. Any recommendations?

**Comment by Akuli** [comment] 2022-03-14 08:52
I recommend disabling `--disallow-untyped-calls`. It's not helpful and it only generates noisy warnings. It's meant to be used in projects that want every function call type checked, which isn't yet possible if you use selenium.

Don't use `types-selenium` if you use selenium 4. It is meant to be used only with selenium 3.

You can also make pull requests that add the missing types :)

**Comment by Akuli** [comment] 2022-03-14 08:53
And I might as well mention how to disable the warning in `mypy.ini`:

```ini
[mypy]
strict = True
show_error_codes = True
disable_error_code = no-untyped-call
```

**Comment by diemol** [comment] 2022-08-12 08:01
@symonk @AutomatedTester do we need to keep this open, or can we open more specific issues so people can report punctual things they find along the way?

**Comment by AutomatedTester** [comment] 2022-08-12 09:31
Let's get specific bugs. @symonk has done a great job of getting this a lot further forward. Other issues should be raised as specific items

**Closed as completed by AutomatedTester** 2022-08-12 09:31 UTC
Labels: E-easy, C-py
