### ISSUE TITLE
Instance ChroneDriver Error: ConnectFailure

### ISSUE THREAD

**Issue by Subhacse17** [SeleniumHQ/selenium#5678] opened 2018-03-26 12:25 UTC
## Meta -
OS:  
Ubuntu 16.04.4
Linux 4.10.0
Selenium Version:  
3.9.0
Browser:  
Chrome

Browser Version:  
65.0.3325.181
ChromeDriver version 2.35

## Steps to reproduce -
After instanciating a chrome Driver as in the screenshot1 we get a list of error written "Error: ConnectFailure (Connection refused)" Screenshot2

## Screenshot1
![image](https://user-images.githubusercontent.com/33542007/37905970-4185bfc2-311e-11e8-9272-5f99a8735828.png)

## Screenshot2
![image](https://user-images.githubusercontent.com/33542007/37906043-82a65cbe-311e-11e8-869c-08cd47144deb.png)

PS : for the first instance of chromedriver we don't get this error in console but for all the rest of instanciation we ll get it.

Help as soon as possible.

**Comment by cgoldberg** [comment] 2018-03-26 13:35
> Browser Version: 65.0.3325.181
> ChromeDriver version 2.35

try a more recent version of Chromedriver.  Version 2.35 only supports Chrome v62-64.
https://chromedriver.storage.googleapis.com/2.35/notes.txt

**Comment by testphreak** [comment] 2018-03-26 21:04
@cgoldberg even with `chromedriver` v2.36 or v2.37, the issue persists. It appears the issue has been [fixed](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2340) but not released. Even tried their canary [build](https://console.cloud.google.com/storage/browser/chromedriver-data/continuous/?prefix=chromedriver_mac64_2.37) from an hour back.

The issue is being seen on all platforms.

**Comment by Subhacse17** [comment] 2018-03-27 06:50
@cgoldberg  I am getting the same with new driver also and in firefox also.

**Comment by Subhacse17** [comment] 2018-03-27 06:57
@testphreak I am not trying to signing into any google product still getting. Can you suggest me any Soln? On windows I am not getting this error.Only with Linux I have this, and more interesting things this error did not cause any block to the code. All tests are running as expectation. This error coming n numbers of time and just increasing my log file length of Jenkins.

**Comment by lmtierney** [comment] 2018-03-31 12:42
I do not have this issue on Linux, check your environment and provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment] 2018-05-03 07:18
Closing the issue as there is no reproduction scenario.

**Closed by barancev** 2018-05-03 07:18 UTC
Labels: R-awaiting answer
