### ISSUE TITLE
[🐛 Bug]: OpenQA.Selenium.WebDriverException : disconnected: not connected to DevTools (failed to check if window was closed: disconnected: not connected to DevTools) 

### ISSUE THREAD

**Issue by vndToptalAXH** [SeleniumHQ/selenium#13446] opened 2024-01-16 13:09 UTC
### What happened?

In our UI Azure test job pipeline we are using Windows Server 2022 image windows-2022 [image](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md). which image is default version for the Azure Pipelines Microsoft-hosted agents. 
It has latest Selenium and Web Browser included and updating regularly, in our case we are using Edge.

After update to v4.16.0 our tests started to fail with error: OpenQA.Selenium.WebDriverException : disconnected: Unable to receive message from renderer
2024-01-08T14:36:20.3149641Z   (failed to check if window was closed: disconnected: not connected to DevTools)
2024-01-08T14:36:20.3150111Z   (Session info: MicrosoftEdge=120.0.2210.77)

Before the update this configuration worked as expected: 
Microsoft Edge WebDriver 119.0.2151.97
Microsoft Edge Driver 119.0.2151.97
Selenium server 4.15.0
in version 4.16.0 you did some changes to the DevTools, and now looks like it broken our tests. 
![image](https://github.com/SeleniumHQ/selenium/assets/153848990/827c74b4-c66b-4988-a208-c573a4f75109)
![image](https://github.com/SeleniumHQ/selenium/assets/153848990/686464d5-b529-4ce0-94d7-18ced5c61911)
<img width="534" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/153848990/cdedbea2-a4d0-4fb4-8491-26b23dba3fcd">
![image](https://github.com/SeleniumHQ/selenium/assets/153848990/5dfc4bf0-94e0-4779-9889-33147366b1be)
![image](https://github.com/SeleniumHQ/selenium/assets/153848990/5127b961-b8c5-496e-ab1f-5b76696c3c0c)

### How can we reproduce the issue?

```shell
/// <summary>
    /// Verify a popout link has opened a new page.
    /// </summary>
    /// <param name="pageHeader">Page header to look for.</param>
    /// <param name="closeNewTab">If the new tab shouold be closed after the test.</param>
    protected void VerifyPopOutLink(string pageHeader, bool closeNewTab = true)
    {
        var parentHandle = _webDriver.Driver.CurrentWindowHandle;
        _webDriver.WaitUntilNewWindowIsOpened(2);
        var childwindows = _webDriver.Driver.WindowHandles.GetEnumerator();
        while (childwindows.MoveNext())
        {
            if (childwindows.Current != parentHandle)
            {
                _webDriver.Driver.SwitchTo().Window(childwindows.Current);
                var pageHeaderText = _webDriver.WaitUntilElementIsVisible(By.CssSelector(".navbar-brand > div:nth-child(1) > span:nth-child(2)")).Text;
                Assert.Equal(pageHeader, pageHeaderText);
                if (closeNewTab)
                {
                    _webDriver.Driver.Close();
                }

                _webDriver.Driver.SwitchTo().Window(parentHandle);
            }
        }
    }
```

### Relevant log output

```shell
##[error][xUnit.net 00:03:15.53]     Pricing.UI.Tests.RetailFamilyTests.FamilyMembers_PromoteFamilyMemberToLead [FAIL]
2024-01-08T14:36:43.3083074Z [xUnit.net 00:03:15.53]       OpenQA.Selenium.WebDriverException : disconnected: not connected to DevTools
2024-01-08T14:36:43.3181106Z   (failed to check if window was closed: disconnected: not connected to DevTools)
2024-01-08T14:36:43.3213866Z   (Session info: MicrosoftEdge=120.0.2210.77)
2024-01-08T14:36:43.3291729Z [xUnit.net 00:03:15.53]       Stack Trace:
2024-01-08T14:36:43.3298230Z [xUnit.net 00:03:15.53]            at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
2024-01-08T14:36:43.3304886Z [xUnit.net 00:03:15.53]            at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2024-01-08T14:36:43.3348846Z [xUnit.net 00:03:15.53]            at OpenQA.Selenium.WebDriver.Close()
2024-01-08T14:36:43.3366922Z [xUnit.net 00:03:15.53]         D:\a\1\s\src\ui\Pricing.UI.Tests\FunctionUITests\FunctionalTestsBase.cs(564,0): at Pricing.UI.Tests.FunctionalTestsBase.Dispose(Boolean disposing)
2024-01-08T14:36:43.3407768Z [xUnit.net 00:03:15.53]         D:\a\1\s\src\ui\Pricing.UI.Tests\FunctionUITests\FunctionalTestsBase.cs(266,0): at Pricing.UI.Tests.FunctionalTestsBase.Dispose()
2024-01-08T14:36:43.3433634Z [xUnit.net 00:03:15.53]         C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs(79,0): at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
2024-01-08T14:36:43.3442413Z   Failed Pricing.UI.Tests.RetailFamilyTests.FamilyMembers_PromoteFamilyMemberToLead [49 s]
2024-01-08T14:36:43.3453501Z   Error Message:
2024-01-08T14:36:43.3474913Z    OpenQA.Selenium.WebDriverException : disconnected: not connected to DevTools
2024-01-08T14:36:43.3563296Z   (failed to check if window was closed: disconnected: not connected to DevTools)
2024-01-08T14:36:43.3590042Z   (Session info: MicrosoftEdge=120.0.2210.77)
2024-01-08T14:36:43.3624142Z   Stack Trace:
2024-01-08T14:36:43.3633889Z      at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
2024-01-08T14:36:43.3640140Z    at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2024-01-08T14:36:43.3649255Z    at OpenQA.Selenium.WebDriver.Close()
2024-01-08T14:36:43.3665741Z    at Pricing.UI.Tests.FunctionalTestsBase.Dispose(Boolean disposing) in D:\a\1\s\src\ui\Pricing.UI.Tests\FunctionUITests\FunctionalTestsBase.cs:line 564
2024-01-08T14:36:43.3740507Z    at Pricing.UI.Tests.FunctionalTestsBase.Dispose() in D:\a\1\s\src\ui\Pricing.UI.Tests\FunctionUITests\FunctionalTestsBase.cs:line 266
2024-01-08T14:36:43.3757107Z    at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 79
```

### Operating System

Windows Server 2022

### Selenium version

v4.16.0

### What are the browser(s) and version(s) where you see this issue?

Microsoft Edge 120.0.2210.61

### What are the browser driver(s) and version(s) where you see this issue?

Microsoft Edge Driver 120.0.2210.121, Microsoft Edge Driver 120.0.2210.61

**Comment by diemol** [comment] 2024-01-16 14:34
@nvborisenko didn't we have this reported in another issue? I did not find it.

**Comment by nvborisenko** [comment] 2024-01-16 15:25
This issue is not related to .net binding or CDP (DevTools session). There were many issues in the past https://github.com/SeleniumHQ/selenium/issues?q=is%3Aissue+disconnected%3A+not+connected+to+DevTools+is%3Aclosed+ like this.

As I understand the cause might be an incompatibility between driver and browser, or something related to browser arguments.

**Comment by vndToptalAXH** [comment] 2024-01-16 15:35
@nvborisenko @diemol I need to open bug in EdgeWebDriver support? Because I haven't changed anything on my side, but tests stopped work, and you are saying it's not on Selenium side.

**Comment by titusfortner** [comment] 2024-01-17 15:01
Selenium & Chrome are getting released at the same time, which is both good and bad here.

How are drivers being managed?
If you specify `BrowserVersion = 119` in capabilities, Selenium should automatically obtain that browser and the applicable driver. If it works then it is an issue with v120 and not Selenium 4.16.

Does it work for Firefox?

Because Edge driver is based on Chromium, it's probably something that needs to be addressed by Google.
It looks like it might be fixed by this in Chrome 122 — https://github.com/chromium/chromium/commit/03ae0c131e6876d723032246d011a5b84467a61d

**Comment by vndToptalAXH** [comment] 2024-01-19 12:41
@titusfortner with firefox we don't have such issue. 
We don't have such issue locally (our org policy has always up to date edge browser so we limited in reproducing issues with browser, we can't downgrade it).

**Comment by titusfortner** [comment] 2024-01-19 14:45
If it's working for Firefox, then it likely isn't an issue with Selenium 4.16, and it's an issue with something in Chrome v120.
Hopefully your settings aren't so locked down that you can't make changes to test things? You can try testing with Chrome v122 to see if it includes the fix you want.

**Closed as completed** 2024-01-19 14:46 UTC
Labels: I-defect, G-chromedriver
