### ISSUE TITLE
[🐛 Bug]: Click() function is not working while running the code but in debug mode it is working fine.

### ISSUE THREAD

**Issue by UnileverGithub** [SeleniumHQ/selenium#13829] opened 2024-04-16 13:09 UTC
### What happened?

Issue is with the click() function of selenium for chrome browser. I am automating an ecommerce site where I am facing this issue that while clicking in ATC button it is not clicking only in run mode but in debug mode it is click the element. I have tried multiple solutions but nothing is working. 
![image](https://github.com/SeleniumHQ/selenium/assets/125889311/3dcb1cf6-2d36-4988-b6d2-323fe02d05d5)
I have tried js.executeScript(), tried to add every kind of waits either implicit or explicit, tried to click with actions class as well.

### How can we reproduce the issue?

```shell
Steps to reproduce:
1) Go to https://www.a-squad.in/collections/all
2) Under all product we have so many Add to cart button.
3) I have created a dynamic locator to click on the add to cart button which I want to click.
//section[@class='collection collection-all']//div[@data-variant-id='46424522260753']//button[@data-collection-handle='all']
4) Try to click on it.
I have tried 
//Point location = btn_addToBag.getLocation();
//System.out.println("location X:" +location.getX() +"location Y:" +location.getY());
Thread.sleep(10000);
waitTillElementIsClickable(btn_addToBag);
hover(btn_addToBag);
jsClick(btn_addToBag);
btn_addToBag.click();
new Actions(driver).moveToLocation(location.getX(),location.getY()).click().build().perform();
```

### Relevant log output

```shell
It is not clicking on the respective element but not throwing any exception as well and moving to the next line and then failing on that point as because of the previous action next action has not performed.
```

### Operating System

Windows 10

### Selenium version

4.11.0

### What are the browser(s) and version(s) where you see this issue?

latest version only 

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 122.0.6261.69

### Are you using Selenium Grid?

no

**Comment by UnileverGithub** [comment] 2024-04-16 13:59
Hi @diemol ,
https://www.a-squad.in/collections/all this is the URL 

<java.version>11.0.19</java.version>
selenium
<version>4.11.0</version>
<artifactId>cucumber-java</artifactId>
<version>7.6.0</version>
<artifactId>webdrivermanager</artifactId>
<version>5.4.1</version>

**Comment by diemol** [comment] 2024-04-16 14:02
As the comment above says, we need a way to reproduce this. We cannot just build the code. Please provide the code so we can triage this issue.

**Comment by UnileverGithub** [comment] 2024-04-17 04:51
Here is the code:

```java
package com.qa.PBBUsteps;

import java.time.Duration;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class ClickIssue {
	
	
	public static ThreadLocal<WebDriver> tlDriver = new ThreadLocal<>();
	
	
	public static void main(String[] args) throws InterruptedException
	{
		System.setProperty("webdriver.chrome.driver",
				"C:\\Users\\HX957FH\\Downloads\\chromedriver-win64\\chromedriver.exe");
		ChromeOptions options = new ChromeOptions();
		options.addArguments("--remote-allow-origins=*");
		
		tlDriver.set(new ChromeDriver(options));
		
		getDriver().manage().deleteAllCookies();
		getDriver().manage().window().maximize();
		getDriver().get("https://www.a-squad.in/");
		getDriver().manage().timeouts().pageLoadTimeout(Duration.ofSeconds(50));
		
		WebElement lnk_MenuOption = getDriver().findElement(By.xpath("//nav[@class='header__menu']//a[contains(@class,'SHOP ALL')]"));
		waitTillElementIsClickable(lnk_MenuOption);
		Actions actions = new Actions(getDriver());
		actions.moveToElement(lnk_MenuOption).build().perform();;
		
		WebElement txt_cartSkuPrice = getDriver().findElement(By.xpath("//nav[@class='header__menu']//a[contains(@class,'SHOP ALL')]/following-sibling::div//div[@class='header__dropdown__inner_text']//div[contains(@class,'a-squad_nav')]//span/a[text()='View All']"));
		waitTillElementIsClickable(txt_cartSkuPrice);
		txt_cartSkuPrice.click();
		
		for(int i=0;i<4;i++)
		{
			JavascriptExecutor js = (JavascriptExecutor) getDriver();
			js.executeScript("window.scrollBy(0,500)", "");
			Thread.sleep(2000);
		}
		WebElement btn_addToBag = getDriver().findElement(By.xpath("//section[@class='collection collection-all']//div[@data-variant-id='46424522260753']//button[@data-collection-handle='all']"));
		Thread.sleep(10000);
		waitTillElementIsClickable(btn_addToBag);
		btn_addToBag.click();
		
		WebElement cartSlider = getDriver().findElement(By.xpath("//div[@id='cart-dropdown' and @class[contains(.,'is-open')]]"));
		cartSlider.isDisplayed();
	}
	
	public static void waitTillElementIsClickable(WebElement element)
	{
		WebDriverWait wait = new WebDriverWait(getDriver(), Duration.ofSeconds(20));
		wait.until(ExpectedConditions.elementToBeClickable(element));
	}
	
	public static synchronized WebDriver getDriver() {
		return tlDriver.get();
	}

}
```

Sorry for the delay.

**Comment by UnileverGithub** [comment] 2024-04-18 06:20
Hi @diemol , 
Any Finding?

**Comment by pujagani** [comment] 2024-04-18 09:50
Hey! Thank you for the example. I am looking into it currently. I will provide updates or findings here.

**Comment by pujagani** [comment] 2024-04-18 10:04
I can reproduce the issue, but not the part where it works in the debug mode. 
I can reproduce this bit "It is not clicking on the respective element but not throwing any exception as well and moving to the next line and then failing on that point as because of the previous action next action has not performed." 
Triaging it further.

**Comment by UnileverGithub** [comment] 2024-04-18 10:28
Hey! 
If you put debugger at btn_addToBag.click(); point then you can see the difference.

**Comment by pujagani** [comment] 2024-04-18 11:36
I tried that earlier and now again and did not see it work. Also, the selector shared in the example was not working, so I updated it locally. What test framework are you using the run the test?

**Comment by UnileverGithub** [comment] 2024-04-18 12:49
I am using BDD-cucumber

**Comment by pujagani** [comment] 2024-04-22 05:00
Please help with a reproducible test script to reproduce this without any testing framework or dependency.

**Comment by pujagani** [comment] 2024-04-22 05:13
Also, can you check the console logs when you click the "add to bag" button? I am seeing some errors that might not be allowing the click to function as expected.

**Comment by UnileverGithub** [comment] 2024-04-22 06:07
> Please help with a reproducible test script to reproduce this without any testing framework or dependency.

I have already added the script in above comment and that doesnt have any dependency in it.

**Comment by pujagani** [comment] 2024-04-22 06:53
I am unable to see that the test passes in the debug step, which might be related to the threading model of using Cucumber. I am not sure how to help further regarding this without reproducing it exactly. I would recommend please check the error logs in the console, in case they help you out.

**Comment by pujagani** [comment] 2024-04-22 08:21
I think the tests are flaky and that is related to the backend and not Selenium. One fix that is required is adding a wait after clicking the add to cart button.  I have seen the tests pass after adding it but sporadically. 

```
                WebElement btn_addToBag = driver.findElement(By.xpath("//section[@class='collection collection-all']//div[@data-variant-id='46424522260753']//button[@data-collection-handle='all']"));
                Thread.sleep(10000);
                waitTillElementIsClickable(driver,btn_addToBag);
                btn_addToBag.click();

                Thread.sleep(20000);

                WebElement cartSlider = driver.findElement(By.xpath("//div[@id='cart-dropdown' and @class[contains(.,'is-open')]]"));
                cartSlider.isDisplayed();

```

<img width="560" alt="Screenshot 2024-04-22 at 1 31 23 PM" src="https://github.com/SeleniumHQ/selenium/assets/10705590/9789caea-c85c-4e6c-a81b-78daf4657dfc">

After trying a few times in the debug mode, I am seeing these error logs irrespective of debug mode when the test fails.
<img width="548" alt="Screenshot 2024-04-22 at 1 37 29 PM" src="https://github.com/SeleniumHQ/selenium/assets/10705590/6f2f0baf-08ca-4792-9d0d-9858331aefba">

But other times,  when the test passes, I see this:

<img width="1430" alt="Screenshot 2024-04-22 at 1 46 17 PM" src="https://github.com/SeleniumHQ/selenium/assets/10705590/ce9da754-1cbd-4a11-a9e8-c2e2c031cf7b">

If you notice the difference, the difference is the missing event log in the failing test. 
I am closing the issue, since the root cause is not Selenium-related. I have also tested this with Firefox and works as expected.

**Closed as completed by pujagani** 2024-04-22 08:21 UTC
Labels: I-defect, J-issue-template

**Comment by UnileverGithub** [comment] 2024-04-22 09:15
> I am unable to see that the test passes in the debug step, which might be related to the threading model of using Cucumber. I am not sure how to help further regarding this without reproducing it exactly. I would recommend please check the error logs in the console, in case they help you out.

okay I will check the error logs in console.
