### ISSUE TITLE
Unable to upload file using sendkeys command in IE

### ISSUE THREAD

**Issue by YeRaghuRam** [SeleniumHQ/selenium#1604] opened 2016-02-08 11:02 UTC
findeleement("locator").sendkeys("filepath")

In IE 
when executing above command "Browse" dialog is opened and path is not entered it stays upto 360 mins (6 hrs)
Provided correct file path and after execution of about 360 mins(6 hrs) no error is displayed
and to close(or quit) the driver it takes 180 min(3 hrs) showing unreachablebrowser exception for closing the driver.

For Browser dialog - no error displayed - 6 hrs
after 6 hrs
To quit or close - unreachablebrowser exception displayed - 3hrs

**Comment by jimevans** [comment] 2016-02-08 11:06
Please provide a log from `IEDriverServer.exe` containing the error, preferably one captured at ‘TRACE` level.

**Comment by smathistad** [comment] 2016-02-15 20:22
I am seeing the exact same issue as YeRaghuRam.

How do we generate a log from the <code>IEDriverServer.exe</code> executable?

**Comment by YeRaghuRam** [comment] 2016-02-16 05:35
@jimevans 

Below is the log

2016-02-15 11:42:19 INFO  Sync:133 - Sync waitElementVisible completed successfully
2016-02-15 17:42:23 INFO  Common:1823 - No WerFault.exe processes to kill
2016-02-15 20:42:24 INFO  Common:1837 - Exception in close all is org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.49.0', revision: '365eeb4', time: '2016-01-13 18:33:29'
System info: host: 'HYD-ATMT4', ip: '192.168.139.113', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_65'
Driver info: driver.version: RemoteWebDriver
Capabilities [{browserAttachTimeout=0, enablePersistentHover=false, ie.forceCreateProcessApi=false, pageLoadStrategy=normal, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=https://qasandbox.haicpm.com/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=accept}]
Session ID: eb1134bf-3f87-4cf4-bbe5-f86f9453593b
FAILED: ftest
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.49.0', revision: '365eeb4', time: '2016-01-13 18:33:29'
System info: host: 'HYD-ATMT4', ip: '192.168.139.113', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_65'
Driver info: driver.version: InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, enablePersistentHover=false, ie.forceCreateProcessApi=false, pageLoadStrategy=normal, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=https://qasandbox.haicpm.com/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=accept}]
Session ID: eb1134bf-3f87-4cf4-bbe5-f86f9453593b
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:701)
	at org.openqa.selenium.ie.InternetExplorerDriver.getScreenshotAs(InternetExplorerDriver.java:194)
	at HA.SeleniumLib.Common.screenShot(Common.java:1687)
	at HA.TestAutomation.Component.Common.screenShot(Common.java:629)
	at HA.TestExecute.Reporting.REP_CPM_408.ftest(REP_CPM_408.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: org.openqa.selenium.WebDriverException: java.net.SocketTimeoutException: Read timed out
Build info: version: '2.49.0', revision: '365eeb4', time: '2016-01-13 18:33:29'
System info: host: 'HYD-ATMT4', ip: '192.168.139.113', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_65'
Driver info: driver.version: InternetExplorerDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:91)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 29 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at org.apache.http.impl.conn.LoggingInputStream.read(LoggingInputStream.java:87)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:143)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:89)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	... 30 more

**Comment by jimevans** [comment] 2016-02-16 09:11
Thank you for providing additional information. However, you have provided the log from the Selenium server. We need the log from `IEDriverServer.exe`. Until and unless we have that, there is no further help we can provide.

**Comment by YeRaghuRam** [comment] 2016-02-16 10:58
@jimevans  how can we can get log from IEDriverServer.exe

**Comment by godlark** [comment] 2016-02-16 11:01
Sorry for not responding
[ie_logs.txt](https://github.com/SeleniumHQ/selenium/files/132292/ie_logs.txt) - logs from Windows Server
[ie_logs.txt](https://github.com/SeleniumHQ/selenium/files/132293/ie_logs.txt) - logs from Windows 7

There is about 200 requests do IEDriverServer.exe. The average time is 240ms for Windows Server and 190ms for Windows 7. There is only 184 requests on Windows Server, because the test fails, because the webpage is not valid anymore.

**Comment by godlark** [comment] 2016-02-16 11:22
@jimevans 
My logs from the same situation
[ie_logs (2).txt](https://github.com/SeleniumHQ/selenium/files/132338/ie_logs.2.txt)

**Comment by jimevans** [comment] 2016-02-16 12:35
@godlark The log you provided indicates that the file upload dialog timeout you attempted to specify was not sent to the driver executable. Either (1) the language bindings you are using didn't transmit that capability, or (2) the code you provided above isn't the code you actually used to generate the log.

**Comment by YeRaghuRam** [comment] 2016-02-16 12:53
@jimevans  The "ie.fileUploadDialogTimeout" capability is supported by Gridlastic from selenium version 2.48.2.  but i am not using selenium grid , hence that capability is not sent to driver executable
what is the work around?

**Comment by jimevans** [comment] 2016-02-16 13:28
@YeRaghuRam The sending of the capability is not dependent on grid. I'm not sure where you'd get the idea that it is. You can send the capability even when directly creating a local IE driver. The exact mechanism differs based on what language binding you use, so see the language documentation for the exact syntax.

**Comment by smathistad** [comment] 2016-02-18 15:30
@jimevans
I have attached a log from <code>IEDriverServer.exe</code> with TRACE level.

I started my scenario around 5:10pm last night and it finished 15 hours later.  There appears to be 5 consecutive "3 hour timeouts".

I noticed a line that states <code>IESession.cpp(233) Beginning wait for response length to be not zero</code>.  If that refers to a parameter, it would really be nice to know where to set a value less than 3 hours.

[ie_log.txt](https://github.com/SeleniumHQ/selenium/files/136410/ie_log.txt)

**Comment by jimevans** [comment] 2016-02-18 20:52
@smathistad Thanks for that. I still cannot reproduce the issue you're experiencing, but the log you  provided has pointed out where we need additional logging around file uploading, which I've now added. Please grab 2.52.0.1 of `IEDriverServer.exe` (you should be able to find it [here](https://github.com/SeleniumHQ/selenium/blob/master/cpp/prebuilt/Win32/Release/IEDriverServer.exe?raw=true)), and retry your test. There is no need to leave it running for 15 hours. you can simply execute to the point where the file upload fails.

**Comment by smathistad** [comment] 2016-02-18 21:08
I didn't let it run 15 hours on purpose. I started it when I left work and examined the log file the next morning.  Anyway, thanks. I will grab the new driver and restart my tests.

**Comment by smathistad** [comment] 2016-02-19 15:01
@jimevans
I have attached a new log from IEDriverServer.exe (V2.52.0.1) with TRACE level.

[ie_log_2.52.0.1.txt](https://github.com/SeleniumHQ/selenium/files/138163/ie_log_2.52.0.1.txt)

**Comment by jimevans** [comment] 2016-02-19 15:06
@smathistad Can you please join the Selenium IRC channel (#selenium on Freenode.net)? I have further questions, but would like to ask them in real-time rather than the back-and-forth of the issue tracker. It looks like the driver isn't finding the file open dialog at all, which is different than what the earlier logs indicated.

**Comment by smathistad** [comment] 2016-02-19 15:26
I just got on freenode.net.

**Comment by smathistad** [comment] 2016-02-19 15:46
@jimevans
Thanks again for your help. 
I will set the value of <code>ie.fileUploadDialogTimeout</code> capability to 10000.  I will give you an update (success or fail) after I have had time to rerun my tests

**Comment by smathistad** [comment] 2016-02-19 19:54
@jimevans
I have attached a new log from IEDriverServer.exe (V2.52.0.1) with TRACE level and changing the <code>ie.fileUploadDialogTimeout</code> to 10000.

I am still running on my laptop.  I ran a test and saw the dialog hang for about 9+ seconds, but it did eventually populate the filename and return to the webpage successfully.

Here is my question: Is that 10000ms wait a "hard wait" (always 10 sec) or a "dynamic wait" (wait up to 10sec, but may be shorter)?

[ie_log_2.52.0.1_timeout_10k.txt](https://github.com/SeleniumHQ/selenium/files/138606/ie_log_2.52.0.1_timeout_10k.txt)

**Comment by jimevans** [comment] 2016-02-19 20:04
@smathistad It's (in your words) a "dynamic wait." However, you should double-check the version of the IE driver you're using. You mentioned that you used 2.52.0.1, but the log you posted indicates 2.52.0.0. To wit,

> I 2016-02-19 13:39:14:616 server.cc(86) Starting WebDriver server on port: '7558' on host: ''
> T 2016-02-19 13:39:14:616 server.cc(630) Entering Server::PopulateCommandRepository
> T 2016-02-19 13:39:14:617 IEServer.cpp(31) Entering IEServer::IEServer
> I 2016-02-19 13:39:14:617 IEServer.cpp(32) Driver version: 2.52.0.0 (32-bit)
> T 2016-02-19 13:39:14:617 server.cc(121) Entering Server::Start
> D 2016-02-19 13:39:14:617 server.cc(148) Civetweb ACL is -0.0.0.0/0,+127.0.0.1

I suspect you won't see the full 10-second timeout if you use 2.52.0.1.

**Comment by smathistad** [comment] 2016-02-19 20:09
Crap! You are correct about the version. I had to switch back to 2.52.0.0 to set up our overnight test suite.  I will retry with 2.52.0.1.  Thanks.

**Comment by smathistad** [comment] 2016-02-23 19:05
@jimevans     Thanks again for your help.
Setting the value of <code>ie.fileUploadDialogTimeout</code> capability to 10000 seems to have fixed my issue. I have not been able to reproduce it (out of approx. 50k attempts) since I made the change.

**Comment by jimevans** [comment] 2016-02-23 19:34
Thanks very much for your continued investigation of this issue, @smathistad. Given that, I'm going to close this issue, as it appears there is a supported mechanism for preventing its occurrence.

**Closed by jimevans** 2016-02-23 19:34 UTC
Labels: D-IE
