### ISSUE TITLE
Empty file upload causes error "unknown error: unable to unzip 'file'"

### ISSUE THREAD

**Issue by olegbaslak** [SeleniumHQ/selenium#6529] opened 2018-10-12 10:03 UTC
## Meta
OS:   Windows 10
Selenium Version:  3.14.0
Browser:  Chrome
Browser Version:  69.0.3497.100

Currently I'm not able to upload empty file of 0 bytes size with RemoteWebDriver (on Selenium Grid). But it works correctly for local run on ChromeDriver.

## Expected Behavior
File is sent successfully

## Actual Behavior
On file uploading exception is thrown:
> Message: OpenQA.Selenium.WebDriverException : unknown error: unable to unzip 'file'
from unknown error: archive error: (unknown error: could not unzip archive), entry error: (unknown error: could not unzip archive)
(Session info: chrome=69.0.3497.81)
(Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.4.0-130-generic x86_64)

## Steps to reproduce
`driver.Find(inputLocator).SendKeys(emptyFilePath)`

Edit 1:  The issue is reproduced for C#

**Comment by barancev** [comment] 2019-04-14 16:11
I couldn't reproduce the issue using Selenium .Net binding 3.14.0 and Selenium Server 3.14.0

What Selenium Server did you use? Can you collect a log from Selenium Server console and provide it for investigation?

**Comment by diemol** [comment] 2019-06-23 17:15
Closing as we didn't get any more replies from the OP.

**Closed by diemol** 2019-06-23 17:15 UTC
Labels: C-grid, C-java, R-awaiting answer
