### ISSUE TITLE
python selenium geckodriver proxy not work .

### ISSUE THREAD

**Issue by wuyue92tree** [SeleniumHQ/selenium#3963] opened 2017-05-03 07:04 UTC
## Meta -
OS:  Ubuntu 16.04

Selenium Version:  3.4.1

Browser:  Firefox

Browser Version:  53.0

## Expected Behavior -
I'd like to set proxy with geckodriver 0.16.0; but is not work ~

Python 2.7.12

myProxy = "host:port"
 proxy = Proxy({
        'proxyType': ProxyType.MANUAL,
        'httpProxy': myProxy,
        'ftpProxy': myProxy,
        'sslProxy': myProxy,
        'noProxy': ''  # set this value as desired
})

driver = webdriver.Firefox(proxy=proxy)

## Actual Behavior -
The address that outside is not changed!

**Comment by AutomatedTester** [comment] 2017-05-29 09:35
duplicate of #4046

**Closed by AutomatedTester** 2017-05-29 09:35 UTC
