### ISSUE TITLE
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms

### ISSUE THREAD

**Issue by waiting0729** [SeleniumHQ/selenium#2736] opened 2016-09-08 03:11 UTC
dear all,
          when i run selenium test in eclipse, it occurs : 
    org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
nsion","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":"chrome://fiddlerhook/content/about.xul","icons":{},"iconURL":"chrome://fiddlerhook/content/fiddlerhook.png","icon64URL":null,"defaultLocale":{"name":"FiddlerHook","description":"Integrate Fiddler into Firefox","creator":"Telerik","homepageURL":"https://fiddler2.com/r/?FIDDLERHOOKHELP"},"visible":true,"active":false,"userDisabled":true,"appDisabled":true,"descriptor":"F:\\installsoftware\\Fiddler2\\FiddlerHook","installDate":1466393970310,"updateDate":1466393970310,"applyBackgroundUpdates":1,"bootstrap":false,"skinnable":false,"size":33877,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"4.0","maxVersion":"37.*"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":0,"seen":true}
1473301845325	DeferredSave.extensions.json	DEBUG	Save changes
1473301845325	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1473301845325	addons.xpi-utils	DEBUG	Updating add-on states
1473301845326	addons.xpi-utils	DEBUG	Writing add-ons list
1473301845329	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1473301845329	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.1
1473301845329	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1473301845330	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1473301845331	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1473301845331	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.4.4
1473301845373	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1473301845374	addons.manager	DEBUG	Provider finished startup: XPIProvider
1473301845374	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1473301845374	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1473301845374	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1473301845374	addons.manager	DEBUG	Starting provider: GMPProvider
1473301845379	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1473301845380	addons.manager	DEBUG	Provider finished startup: GMPProvider
1473301845380	addons.manager	DEBUG	Starting provider: PluginProvider
1473301845380	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1473301845380	addons.manager	DEBUG	Provider finished startup: PluginProvider
1473301845380	addons.manager	DEBUG	Completed startup sequence
1473301846213	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1473301846213	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1473301846214	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1473301847220	DeferredSave.extensions.json	DEBUG	Write succeeded
1473301847220	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1473301847221	DeferredSave.extensions.json	DEBUG	Starting timer
1473301847233	addons.repository	DEBUG	No addons.json found.
1473301847233	DeferredSave.addons.json	DEBUG	Save changes
1473301847267	DeferredSave.addons.json	DEBUG	Starting timer
1473301848053	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1473301848054	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1473301848054	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1473301848058	DeferredSave.extensions.json	DEBUG	Starting write
1473301848061	DeferredSave.addons.json	DEBUG	Starting write
1473301848107	DeferredSave.extensions.json	DEBUG	Write succeeded
1473301848124	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:314)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:231)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:219)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:214)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:210)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:123)
	at com.Test1.main(Test1.java:12)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
nsion","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":"chrome://fiddlerhook/content/about.xul","icons":{},"iconURL":"chrome://fiddlerhook/content/fiddlerhook.png","icon64URL":null,"defaultLocale":{"name":"FiddlerHook","description":"Integrate Fiddler into Firefox","creator":"Telerik","homepageURL":"https://fiddler2.com/r/?FIDDLERHOOKHELP"},"visible":true,"active":false,"userDisabled":true,"appDisabled":true,"descriptor":"F:\\installsoftware\\Fiddler2\\FiddlerHook","installDate":1466393970310,"updateDate":1466393970310,"applyBackgroundUpdates":1,"bootstrap":false,"skinnable":false,"size":33877,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"4.0","maxVersion":"37.*"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":0,"seen":true}
1473301845325	DeferredSave.extensions.json	DEBUG	Save changes
1473301845325	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1473301845325	addons.xpi-utils	DEBUG	Updating add-on states
1473301845326	addons.xpi-utils	DEBUG	Writing add-ons list
1473301845329	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1473301845329	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.1
1473301845329	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1473301845330	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1473301845331	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1473301845331	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.4.4
1473301845373	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1473301845374	addons.manager	DEBUG	Provider finished startup: XPIProvider
1473301845374	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1473301845374	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1473301845374	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1473301845374	addons.manager	DEBUG	Starting provider: GMPProvider
1473301845379	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1473301845380	addons.manager	DEBUG	Provider finished startup: GMPProvider
1473301845380	addons.manager	DEBUG	Starting provider: PluginProvider
1473301845380	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1473301845380	addons.manager	DEBUG	Provider finished startup: PluginProvider
1473301845380	addons.manager	DEBUG	Completed startup sequence
1473301846213	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1473301846213	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1473301846214	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1473301847220	DeferredSave.extensions.json	DEBUG	Write succeeded
1473301847220	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1473301847221	DeferredSave.extensions.json	DEBUG	Starting timer
1473301847233	addons.repository	DEBUG	No addons.json found.
1473301847233	DeferredSave.addons.json	DEBUG	Save changes
1473301847267	DeferredSave.addons.json	DEBUG	Starting timer
1473301848053	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1473301848054	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1473301848054	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1473301848058	DeferredSave.extensions.json	DEBUG	Starting write
1473301848061	DeferredSave.addons.json	DEBUG	Starting write
1473301848107	DeferredSave.extensions.json	DEBUG	Write succeeded
1473301848124	DeferredSave.addons.json	DEBUG	Write succeeded

Build info: version: 'unknown', revision: 'c7b525d', time: '2016-09-01 14:52:30 -0700'
System info: host: '*******', ip: '***.***.***.***', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_51'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:314)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:231)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:219)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:214)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:210)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:123)
	at com.Test1.main(Test1.java:12)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
nsion","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":"chrome://fiddlerhook/content/about.xul","icons":{},"iconURL":"chrome://fiddlerhook/content/fiddlerhook.png","icon64URL":null,"defaultLocale":{"name":"FiddlerHook","description":"Integrate Fiddler into Firefox","creator":"Telerik","homepageURL":"https://fiddler2.com/r/?FIDDLERHOOKHELP"},"visible":true,"active":false,"userDisabled":true,"appDisabled":true,"descriptor":"F:\\installsoftware\\Fiddler2\\FiddlerHook","installDate":1466393970310,"updateDate":1466393970310,"applyBackgroundUpdates":1,"bootstrap":false,"skinnable":false,"size":33877,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"4.0","maxVersion":"37.*"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":0,"seen":true}
1473301845325	DeferredSave.extensions.json	DEBUG	Save changes
1473301845325	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1473301845325	addons.xpi-utils	DEBUG	Updating add-on states
1473301845326	addons.xpi-utils	DEBUG	Writing add-ons list
1473301845329	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1473301845329	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.1
1473301845329	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1473301845330	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1473301845331	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1473301845331	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.4.4
1473301845373	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1473301845374	addons.manager	DEBUG	Provider finished startup: XPIProvider
1473301845374	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1473301845374	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1473301845374	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1473301845374	addons.manager	DEBUG	Starting provider: GMPProvider
1473301845379	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1473301845380	addons.manager	DEBUG	Provider finished startup: GMPProvider
1473301845380	addons.manager	DEBUG	Starting provider: PluginProvider
1473301845380	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1473301845380	addons.manager	DEBUG	Provider finished startup: PluginProvider
1473301845380	addons.manager	DEBUG	Completed startup sequence
1473301846213	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1473301846213	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1473301846214	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1473301847220	DeferredSave.extensions.json	DEBUG	Write succeeded
1473301847220	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1473301847221	DeferredSave.extensions.json	DEBUG	Starting timer
1473301847233	addons.repository	DEBUG	No addons.json found.
1473301847233	DeferredSave.addons.json	DEBUG	Save changes
1473301847267	DeferredSave.addons.json	DEBUG	Starting timer
1473301848053	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1473301848054	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1473301848054	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1473301848058	DeferredSave.extensions.json	DEBUG	Starting write
1473301848061	DeferredSave.addons.json	DEBUG	Starting write
1473301848107	DeferredSave.extensions.json	DEBUG	Write succeeded
1473301848124	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	... 8 more

OS:  win7 x64

Selenium Version:  selenium-java-3.0.0-beta3
Browser:  48.0.2

At same time my GECKODRIVER version is geckodriver-v0.10.0-win64.

My code is : 
    package com;

import org.openqa.selenium.WebDriver;

import org.openqa.selenium.firefox.FirefoxDriver;

public class Test1 {
    public static void main(String[] args) {
        System.setProperty("webdriver.firefox.marionette", "F:\\压测\\selenium\\geckodriver.exe");
        WebDriver driver = new FirefoxDriver();
        driver.get("http://www.baidu.com");
        driver.quit();
        }
}
I am is tiro,Who can help me?

**Comment by TwelveBaud** [comment] 2016-09-14 13:43
Firefox has added several new security and stability features in the past few years that make using projects like Selenium more difficult. You might want to make the following changes to your setup:

- Use [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/), since it can load unsigned add-ons like WebDriver.
- Set the profile preference that [disables add-on compatibility checking](http://kb.mozillazine.org/Extensions.checkCompatibility).
- Set the profile preferences that disable "Electrolysis" (`browser.tabs.remote (and friends) = false`). Although Firefox will pop up a message saying it does this automatically, Selenium uses a temporary profile, so those automatic changes are not saved.
- Create a `FirefoxBinary` object that points to Firefox Developer Edition, and a `FirefoxProfile` object that sets the prefs I just mentioned. Use those when you create the `FirefoxDriver`.

**Comment by aluzardo** [comment] 2016-09-29 13:05
I had the same problem and I fixed downloading and installing a previous version of firefox https://ftp.mozilla.org/pub/firefox/releases/47.0.1/

I would like that selenium will fix this in next releases. 

Please keep me updated when I can use selenium with firefox >47.0.1

**Comment by TwelveBaud** [comment] 2016-09-29 13:31
@aluzardo: Mozilla has decided not to allow the Selenium extension to be installed at all in Firefox 48 or above. The Selenium team cannot fix this.

You have three options:
- Use Firefox 47, or preferably Firefox 45 ESR. _This option goes away June 13, 2017._
- Use Firefox Developer Edition, or Firefox Nightly, along with the prefs to disable multiprocess, disable addon signing enforcement, and disable compatibility checks. _This option could go away at any time._
- Use an up-to-date copy of GeckoDriver, and tell FirefoxDriver to use the Marionette system. _This option is officially recommended by Mozilla and (grudgingly) SeleniumHQ, but often does not work, and does not offer everything Selenium's native extension supports._

Good luck!

@waiting0729: There may be a problem with your "压测" directory name. Depending on how your file is compiled and where it is run, it may be interpreted as "åŽ‹æµ‹" or "??", which would cause FirefoxDriver to ignore it. Try using a directory name with only Latin letters or numbers.

**Comment by davehunt** [comment] 2016-09-29 14:42
> Use an up-to-date copy of GeckoDriver, and tell FirefoxDriver to use the Marionette system. This option is officially recommended by Mozilla and (grudgingly) SeleniumHQ

There's nothing grudgingly about this recommendation. Marionette is Mozilla's official implementation of the WebDriver specification, and therefore will ultimately provide a better user experience and support than the legacy Firefox driver provided by the Selenium project. This is the same as the existing Chrome, Edge, and Safari drivers, which are provided by the browser vendors.

As the WebDriver specification is still in draft, and Marionette does not yet fully support everything in the draft, there are certainly some differences between the legacy driver and Marionette. I would encourage anyone experiencing issues to [check the status](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status) of the WebDriver specification support in Firefox, and [raise bugs](https://bugzilla.mozilla.org/enter_bug.cgi?product=Testing&component=Marionette) if you experience issues.

**Comment by davehunt** [comment] 2016-09-29 14:45
Duplicate of #2750

**Closed by davehunt** 2016-09-29 14:45 UTC

**Comment by Jayasharma004** [comment] 2018-11-21 04:32
I am getting the below error -

org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
-stream@mozilla.org.xpi

Please suggest how can I resolve this error.


Details of my project:
1)Using  firefox - 62.0.1
2)Gecko Driver – 0.21.0
3)Added Selenium dependencies – 2.53.0 (Ideally I should put 3 or above selenium dependencies as gecko driver 0.21.0 demands for that)
**(Note: Whenever I am trying to increase this version to 3.14, It is showing missing artifacts error.)**
4)Also tried adding the jars explicitly
5)Eclipse - Added Library – JDK 1.8.0_91
6)Eclipse - Added Maven – Preferences – Installations – 3.3.9 
7)Created new firefox profile 
8)Done the changes in Settings.xml 



here is my pom.xml

<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>2.53.0</version>
			<scope>provided</scope>
		</dependency>
	 	<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>2.53.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-remote-driver</artifactId>
			<version>2.53.0</version>
			<scope>provided</scope>
		</dependency> 

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-firefox-driver</artifactId>
			<version>2.53.0</version>
			<scope>provided</scope>
		</dependency>
