### ISSUE TITLE
Element is not clickable at point (X,Y) with Firefox driver

### ISSUE THREAD

**Issue by benjefferies** [SeleniumHQ/selenium#1543] opened 2016-01-27 14:45 UTC
I am experiencing a difference in behaviour between versions `2.48.2` and `2.49.0`. 

##### Setting the scene
Using Firefox driver for testing. 
The window is at the size 1024x768.
Using bootstrap with a 'fixed' footer navbar.
The page which is being tested has a drop down element which expands beyond the bottom of the screen (Under fixed footer navbar).

##### Scenario using 2.48.2
The drop down is selected
The drop down pop over extends off bottom of the screen
Tell web driver to select off screen elements in drop down pop over
Web driver scrolls down to select off screen elements

##### Scenario using 2.49.0
The drop down is selected
The drop down pop over extends off bottom of the screen
Tell web driver to select off screen elements in drop down pop over
Element is not clickable at point X,Y
```
org.openqa.selenium.WebDriverException: Element is not clickable at point (336.1666717529297, 645). Other element would receive the click: <div class="container" ng-transclude=""></div>
Command duration or timeout: 74 milliseconds
```

Could this be caused by #1211

**Comment by benjefferies** [comment] 2016-01-27 14:54
Possibly duplicate of #1533?

**Comment by lukeis** [comment] 2016-01-27 16:16
duplicate of #1202

**Closed by lukeis** 2016-01-27 16:16 UTC
