### ISSUE TITLE
ShadowJar can not be extracted

### ISSUE THREAD

**Issue by kevinwee0712** [SeleniumHQ/selenium#7061] opened 2019-03-27 10:21 UTC
## 🐛 Bug Report

org.gradle.api.UncheckedIOException: Cannot create directory META-INF/versions/9 as it already exists, but is not a directory

![image](https://user-images.githubusercontent.com/14109577/55067702-0d287980-50e5-11e9-8235-fe8e3a1ec897.png)

## To Reproduce

Detailed steps to reproduce the behaviour:

1.Create a gradle project.
2.Depend on selenium 3.141.+
3.Trigger shadow jar gradle task.
4.Find fat jar under build/libs folder.
5.Extract that fat jar.

## Expected behavior

Shadow jar should be extracted successfully.

## Test script or set of commands reproducing this issue

1. Project depends on selenium version large than 3.141.0:
ext {
    seleniumVersion = '3.141.+'
}

dependencies {
    compile "org.seleniumhq.selenium:selenium-java:${seleniumVersion}"
    compile "org.seleniumhq.selenium:selenium-support:${seleniumVersion}"
}

2. Use  com.github.jengelman.gradle.plugins:shadow:4.0.3 to create a shadow jar

buildscript {
    dependencies {
        classpath 'com.github.jengelman.gradle.plugins:shadow:4.0.3'
    }
}
apply plugin: 'com.github.johnrengelman.shadow'

3. Extract shadow jar.

This bug is introduced by this pr: 

[https://github.com/seleniumhq/selenium/commit/199f9388b3cf953ba5d3a79846dadd08a7dc2824?diff=unified](url)

**Comment by barancev** [comment] 2019-03-29 16:52
Could you please provide a complete sample project instead of a narrative description?

**Comment by barancev** [comment] 2019-03-29 17:10
OK, nevermind, I've found the root cause.

**Comment by barancev** [comment] 2019-03-29 21:28
Fixed by commit 0ff52db67a6287620ad138f3aa08a503cb7d2908

**Closed by barancev** 2019-03-29 21:28 UTC
Labels: C-java
