### ISSUE TITLE
[🐛 Bug]: drag_and_drop_by_offset() cannot work correctly, but follows(displays at) the real location of Mouse in fact

### ISSUE THREAD

**Issue by Vchenhailong** [SeleniumHQ/selenium#10617] opened 2022-05-07 03:23 UTC
### What happened?

invoke method `drag_and_drop_by_offset(self, source, xoffset, yoffset)` , that it does not work correctly.

### How can we reproduce the issue?

```shell
i.e.
xoffset, yoffset = 500, 500

and the mouse at somewhere, maybe 1000, 300

when invoking the method, confirm the real offset result.
```

### Relevant log output

```shell
N/A
```

### Operating System

macOS

### Selenium version

Python3.9.7 (selenium-3.141.0.dist-info)

### What are the browser(s) and version(s) where you see this issue?

chrome 99

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Driver 100.0.4896.60

### Are you using Selenium Grid?

no

**Comment by diemol** [comment] 2022-05-07 06:38
Duplicate of #10601

https://github.com/SeleniumHQ/selenium/issues/10601#issuecomment-1117937743

**Closed as completed by diemol** 2022-05-07 06:38 UTC
Labels: I-defect
