### ISSUE TITLE
RemoteWebDriver doesn't clean Firefox profiles from node's /tmp folder after quit

### ISSUE THREAD

**Issue by Lusine4504** [SeleniumHQ/selenium#3932] opened 2017-04-28 07:05 UTC
## Meta -
OS:  

Selenium Version:  

Browser:  

## Expected Behavior -
To delete tmp profiles  on node
## Actual Behavior -
Profiles still remaining 
## NOTE .
We have seen that there are several reported issues for this case for older versions but issue still exist in new release . 
The files are being  deleted when we replace          
   Iterator iterator = this.temporaryFiles.iterator();
 ###    _with_
   Iterator iterator = instance.temporaryFiles.iterator();
In method org.openqa.selenium.io.TemporaryFilesystem.deleteTemporaryFiles   

Please provide better solution for this ASAP .
Thanks .

**Comment by p0deje** [comment] 2017-06-08 05:01
Duplicate of #3046

**Closed by p0deje** 2017-06-08 05:01 UTC
