### ISSUE TITLE
First CSS selector after using a CSS selector returns incorrect values.

### ISSUE THREAD

**Issue by Peilonrayz** [SeleniumHQ/selenium#8572] opened 2020-07-25 14:15 UTC
## 🐛 Bug Report

CSS selectors don't work correctly on the first object returned by `find_elements_by_css_selector`.

(**Note**: actual order and numbers subject to change)

Expected output:

```none
8: Close Votes
0: First Posts
0: Late Answers
0: Low Quality Posts
0: Reopen Votes
0: Suggested Edits
```
Actual output:

```
8
questions: 8
questions
0: First Posts
0: Late Answers
0: Low Quality Posts
0: Reopen Votes
0: Suggested Edits
```

Notice that the first result is nothing like the rest.

## To Reproduce

Below is attached a basic Python script that I consistently reproduce the error on. I have tested both Chrome and Firefox which can be found in the `get_driver` function.

```python
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

_REVIEW_QUEUES = '#content > :nth-child(2) > :nth-child(1) > .grid'
_REVIEW_QUEUE_AMOUNT = ':nth-child(1) > :nth-child(1)'
_REVIEW_QUEUE_TITLE = ':nth-child(2) > :nth-child(1) > :nth-child(1) > :nth-child(1)'


def get_queues(driver):
    driver.get('https://codereview.stackexchange.com/review')
    queues = driver.find_elements_by_css_selector(_REVIEW_QUEUES)
    for queue in queues:
        amount = queue.find_element_by_css_selector(_REVIEW_QUEUE_AMOUNT)
        title = queue.find_element_by_css_selector(_REVIEW_QUEUE_TITLE)
        print(f'{amount.text}: {title.text}')


def get_driver():
    # binary = FirefoxBinary('/usr/bin/firefox')
    # return webdriver.Firefox(firefox_binary=binary)
    options = webdriver.ChromeOptions()
    options.add_argument('--ignore-certificate-errors')
    options.add_argument("--test-type")
    return webdriver.Chrome(options=options)


def main():
    driver = get_driver()
    get_queues(driver)


if __name__ == '__main__':
    main()
```

## Expected behaviour

I have shown the expected behaviour and I have verified that this is how both Chrome and Firefox work when using JQuery's `$` with the following script.

If you run the following in either browsers console it will output the expected values.

```javascript
let _REVIEW_QUEUES = '#content > :nth-child(2) > :nth-child(1) > .grid';
let _REVIEW_QUEUE_AMOUNT = ':nth-child(1) > :nth-child(1)';
let _REVIEW_QUEUE_TITLE = ':nth-child(2) > :nth-child(1) > :nth-child(1) > :nth-child(1)';

let queues = $(_REVIEW_QUEUES);
for (let queue of queues) {
    let amount = $(_REVIEW_QUEUE_AMOUNT, queue)[0];
    let title = $(_REVIEW_QUEUE_TITLE, queue)[0];
    console.log(`${amount.textContent}: ${title.textContent}`);
}
```

## Environment

OS: Arch Linux
Kernel: 5.7.9-arch1-1
Language Bindings version: Python 3.141.0

Browser: Firefox
Browser version: 78.0.2 (64-bit)
Browser Driver version: geckodriver 0.26.0

Browser: Chromium
Browser version: 84.0.4147.89 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 84.0.4147.89

**Comment by SalmonMode** [comment] 2020-08-15 17:02
Unfortunately, we can't reproduce what you're seeing using the snippet provided (as we'd need a web page to run it against). But, I don't believe this is a bug. 

Your locators seem very inaccurate and fragile, as there's nothing particularly distinguishing about them. It may be helpful to modify the source for the page (assuming you have some means of influencing it) in a way that makes your target elements easier to locate (e.g. differing classes for the title and amount elements).

However, aside from the locator issue, you're also using jQuery's selector and `textContent`, which presents a couple issues. `textContent` is quite different than `innerText`, which is more akin to what Selenium, or rather the WebDriver protocol would use. jQuery's selector also doesn't do things the same way that `document.querySelectorAll` (or `el.querySelectorAll`) would, which is basically what the WebDriver protocol uses. These are subtle differences, but extremely important, and could definitely explain what you're experiencing.

I'm closing this for now, and I recommend trying `document/element.querySelectorAll` along with `innerText` instead and seeing if there's still an inconsistency. If there is, please comment here again along with a link to the page, or another page where this can be recreated, and the issue can be reopened.

**Closed as completed by SalmonMode** 2020-08-15 17:02 UTC
Labels: C-py, I-question

**Comment by Peilonrayz** [comment] 2020-08-15 17:19
> Unfortunately, we can't reproduce what you're seeing using the snippet provided (as we'd need a web page to run it against).

The snippet is an MCVE and the web page is provided in the code. "`driver.get('https://codereview.stackexchange.com/review')`" I very much doubt "we can't reproduce" as I just copied and pasted the above Python code and reproduced this perfectly, as the webpage is included. Is there some other issue that's preventing you from verifying this?

> Your locators seem very inaccurate and fragile

Maybe you're seeing something that I'm not. But they are very stable, except with Selenium. Since I'm using [the child combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator) and [nth child](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) I'm guaranteed to walk the path I specify.  
How are these "inaccurate and fragile"?

The problem has very little to do with the text. The text is the only semi-decent way I can show that Selenium is picking the wrong nodes.

> I recommend trying document/element.querySelectorAll

That isn't very helpful as the problematic selectors should only ever select one value.

**Comment by Peilonrayz** [comment] 2020-08-15 18:05
@SalmonMode Can you reopen this as it seems like it's been closed due to a misunderstanding.

**Comment by SalmonMode** [comment] 2020-08-15 18:20
Ah, my mistake, I missed the URL in the snippet.

And sorry, I should have said "unspecific and fragile" in regards to your locators. Like I said, there's nothing distinguished about them, which is what makes them unspecific and fragile. If it changes at all in that area, your locators would never work (assuming they worked before). When locators are designed to follow a very rigid path through the DOM, they are fragile. When they don't use anything unique (or a combination of semi-unique things), they aren't specific. By sticking so closely to a direct chain of elements, you are beholden to that specific structure of the page.

Also, if you want to only ever select one value, `$()` isn't what you're looking for anyway. There's also the `document/element.querySelector` variant for grabbing only the first matching element.

All that said, I tried your JS snippet on that page, and got this:
```
3:
0:
0:
0:
0:
0:
```

so I'm not sure it works as you expected.

But as you can see here:

<img width="896" alt="querySelector" src="https://user-images.githubusercontent.com/13908130/90318550-4098bd80-deff-11ea-9cd2-a340c0bad5f7.PNG">

When switching to the query selector variant, it explains where your issue is coming from, and confirms this is not a bug in Selenium.

Here's a modified version that gets the job done in JS with some more distinguished selectors:

```javascript
let queues = document.querySelector('#content .ai-start');
let amounts = queues.querySelectorAll( '.fs-subheading[title]');
let titles = queues.querySelectorAll( '.fs-subheading:not([title])');

let maxLength = Math.max(amounts.length, titles.length)
for (let i = 0; i < maxLength; i++) {
    console.log(`${amounts.item(i).innerText}: ${titles.item(i).innerText}`);
}
```

and here's more or less the Python equivalent (I didn't try this one out):

```python
queues = driver.find_element(By.CSS_SELECTOR, '#content .ai-start')
amounts = queues.find_elements(By.CSS_SELECTOR, '.fs-subheading[title]')
titles = queues.find_elements(By.CSS_SELECTOR, '.fs-subheading:not([title])')

items = zip(amounts, titles)
for amount, title in items:
    print(f'{amount.text}: {title.text}')
```

The locators now target something specific about each thing without also being so heavily dependent to the structure of the page.

**Comment by Peilonrayz** [comment] 2020-08-16 01:55
No problem @SalmonMode thank you for taking the time to explain this to me.

Yes, I certainly agree they are fragile in that sense. Rigidly walking the DOM is not the most desirable solution, and certainly prone to breaking over time.

You are certainly right at some point between pulling my hair out from not understanding the cause of the issue, I changed the `_REVIEW_QUEUE_TITLE` query so it no longer works when you are logged out.
Sorry, I failed to notice that upon posting here.

I have verified that your code snippet copied below doesn't work in my Chrome and so this is certainly not a Selenium issue.

I am sorry to have been a bother.
Thank you very much for taking the time to explain this to me and providing me with a fix. It's much appreciated.

> ```javascript
> let _REVIEW_QUEUES = '#content > :nth-child(2) > :nth-child(1) > .grid'
> let _REVIEW_QUEUE_AMOUNT = ':nth-child(1) > :nth-child(1)'
> let _REVIEW_QUEUE_TITLE = ':nth-child(2) > :nth-child(1) > :nth-child(1) > :nth-child(1)'
> 
> let queues = document.querySelectorAll(_REVIEW_QUEUES);
> for (let queue of queues) {
>     let amount = queue.querySelector(_REVIEW_QUEUE_AMOUNT);
>     let title = queue.querySelector(_REVIEW_QUEUE_TITLE);
>     console.log(`${amount.textContent}: ${title.textContent}`);
>     console.log(amount);
> }
> ```
