### ISSUE TITLE
Firefox 36 not launching on Linux with selenium 2.45.0

### ISSUE THREAD

**Issue by nvnvenki** [SeleniumHQ/selenium#431] opened 2015-04-08 16:07 UTC
Hi,

I'm using selenium java(version selenium-2.45.0) to run the test cases(cucumber features).
I'm unable to launch firefox (version 36.0) on linux OS (Oracle Enterprise Linux 6 u5).
Its working fine in firefox 36.0 in windows 7 with same version of selenium

Its throwing below exception

```
org.openqa.selenium.UnsupportedCommandException: Bad request
 Command duration or timeout: 331 milliseconds
 Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
 System info: host: '', ip: '', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.39-400.211.1.el6uek.x86_64', java.version: '1.7.0_51'
 Driver info: org.openqa.selenium.firefox.FirefoxDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:193)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:182)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:99)
```

Firefox is launched using below code

``` java
FirefoxProfile profile = new FirefoxProfile();
profile.setEnableNativeEvents(true);
WebDriver driver = new FirefoxDriver(profile);
```

Version of tools used.
Selenium: Selenium-java-2.45.0
Browser: Firefox 36.0
OS: Oracle Enterprise Linux 6 u5 64bit

Please let me know if i'm missing something here or is it a known issue.

Thanks
Venki

**Comment by lukeis** [comment] 2015-04-08 16:47
I don't think anyone here will be able to reproduce the problem since we don't have that OS. Does it reproduce in an Ubuntu environment? (That's mainly where we test).

Otherwise can you pull more info, like the full output in the debug console from firefox itself

**Comment by AutomatedTester** [comment] 2015-04-08 16:52
Perhaps the same #423?



—

**Comment by adiroiban** [comment] 2015-04-15 12:03
I think that #423 is a different issue.

I got the same error with Firefox 37 on Ubuntu 14.04 x64

Reading the changelog I see that only Firefox 35 is supported
https://github.com/SeleniumHQ/selenium/blob/master/py/CHANGES#L2

I am using selenium for more than 2 years and this is is a common problem. Each new release of Firefox broke support for selenium.

For now we have pinpointed the Firefox version in our test runner VM.

**Comment by binodpanta** [comment] 2015-07-20 15:26
Is this issue still open, meaning with 2.46. we are gated to Firefox v37 and no higher? Or rather, what is the highest Firefox release we can use with 2.46.0?

**Comment by adiroiban** [comment] 2015-07-21 06:36
Check the CHANGES file https://github.com/SeleniumHQ/selenium/blob/master/py/CHANGES#L17 ... it state that Firefox 38 is now supported...

I have tested/using 2.46.0 with Firefox 39 and it works.

**Comment by umairmm** [comment] 2015-07-29 08:55
I am trying selenium 2.46.2 with Firefox 38 & 39 but it gives error: 
[2015-07-28T03:01:26.652346 #30143] FATAL -- : 
Selenium::WebDriver::Error::WebDriverError (unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055)):
app/models/site.rb:488:in new' app/models/site.rb:488:inscrape'
app/controllers/sites_controller.rb:171:in block in scrape' app/controllers/sites_controller.rb:170:inscrape'


my code is:
Selenium::WebDriver::Firefox::Binary.path='/usr/bin/firefox'
browser = Watir::Browser.new :firefox # should open a new Firefox window
browser.goto self.url

**Comment by replicat0r** [comment] 2015-07-30 16:34
I have the same issue as above 

F, [2015-07-30T15:50:42.038465 #32145] FATAL -- : 
Selenium::WebDriver::Error::WebDriverError (unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055)):
  app/controllers/concerns/bill_company_parser.rb:133:in `new'
  app/controllers/concerns/bill_company_parser.rb:133:in `process_company'


I am using FF 33.0 and on selenium 2.47 with Watir 0.8

**Comment by KaptenJansson** [comment] 2015-08-13 12:13
Out of curiosity why are you still using FF 33? It's over 1 year old and missing lots of security and other fixes.

**Comment by nabedge** [comment] 2015-08-23 06:34
I have the same issue.
But I changed my "/etc/hosts" file and solved it.

/etc/hosts BEFORE

127.0.0.1 localhost.localdomain ..... localhost ....

AFTER:
127.0.0.1 localhost localhost.localdomain .....

**Comment by Nakilon** [comment] 2015-09-25 10:11
@nabedge yay it solved my problem I couldn't resolve for two days!

**Comment by jifeon** [comment] 2015-10-24 21:19
Thanks @nabedge! Can somebody explain why it's matter?

**Comment by andyfinity** [comment] 2015-11-19 19:38
I'll say it too: that solution worked for me. I have no idea why the order in which hostnames are listed would change things. @nabedge: how did you figure that out?!

**Comment by javabrett** [comment] 2015-12-04 00:28
This is definitely still a problem, with the /etc/hosts workaround effective for:

`Selenium 2.48.2 + Firefox Driver, Firefox ESR 38.4.0, RHEL 6.4 x64, kernel 2.6.39, glibc 2.12`

I plan to also test on RHEL7.

Does anyone know the root cause in the code?

**Comment by AutomatedTester** [comment] 2017-06-06 12:36
Closing as this is old and lots of this code has been rewritten

**Closed by AutomatedTester** 2017-06-06 12:36 UTC
Labels: D-firefox, I-needs investigation
