### ISSUE TITLE
ElementClickInterceptedException: Element not clickable 

### ISSUE THREAD

**Issue by KRuptPanda** [SeleniumHQ/selenium#5805] opened 2018-04-19 09:46 UTC
## Meta -
OS:  Windows 7, 10, 2012 Servers

Selenium Version:  3.11.0

Browser:  IE 

Browser Version:  11.371.16299.0

Driver: IE Driver 3.11.1 , 3.11.0

## Expected Behavior -
When we call selenium click function, then webdriver should perform click operation on the element in IE browser.

## Actual Behavior -
The click operation fails with exception "Element is not clickable". This issue is observed in IE Driver 3.11.0 and 3.11.1 . The same click operation works with older version of IEDriver(3.10). 

## Steps to reproduce -
Uncheck "Enable Protected Mode" for all Security zones of IE.
Turn off pop up blocker in IE.

Run the attached java code. 

The java code tries to navigate to "https://in.reuters.com/" and click on "MARKETS" hyperlink.

`
System.setProperty("webdriver.ie.driver", "C:\\IEDriverServer_Win32_3.11.0\\IEDriverServer.exe");
WebDriver driver = new InternetExplorerDriver();
driver.get("https://in.reuters.com/");
driver.findElement(By.xpath("//a[@href='/finance/markets']")).click();
`

The click operation fails with below exception log.
 

_Exception in thread "main" org.openqa.selenium.ElementClickInterceptedException: Element not clickable at point (262,74). Other element would receive the click: `<li>
                    <div class="item"><a href="//ara.reuters.com">????</a></div>
                    <div class="item"><a href="//ar.reuters.com">Argentina</a></div>
                </li>`
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:15.31Z'
System info: host: 'L37428WIN', ip: '192.168.13.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {acceptInsecureCerts: false, browserName: internet explorer, browserVersion: 11, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enablePersistentHover: true, ie.browserCommandLineSwitches: , ie.ensureCleanSession: false, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ignoreProtectedModeSettings: false, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:28840/, nativeEvents: true, requireWindowFocus: false}, setWindowRect: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: b34a33ec-5f14-4913-a40f-e3b9ff9a984d
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstan

ce(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
	at IETest.main(IETest.java:12)_

**Comment by KRuptPanda** [comment] 2018-04-19 11:40
[IETest.zip](https://github.com/SeleniumHQ/selenium/files/1927919/IETest.zip)
PFA

**Comment by jimevans** [comment] 2018-04-19 15:53
Duplicate of #5668.

**Closed by jimevans** 2018-04-19 15:53 UTC
