### ISSUE TITLE
 Firefox crashing on selenium tests after upgrade (46 to 47)

### ISSUE THREAD

**Issue by gabbork** [SeleniumHQ/selenium#2280] opened 2016-06-14 09:06 UTC
## Meta -
OS:  
OS X 10.8.5
Selenium Version:  
2.53.2
Browser:  
Firefox 47

Running simple tests working with Firefox 46, cause crash after upgrade to Firefox 47.

Temporary fix: downgrade to Firefox 46

**Comment by ArunSakthivel** [comment] 2016-06-14 11:53
Yes. I'm also having same problem

**Comment by bodrovis** [comment] 2016-06-14 12:16
Seems like I'm experiencing the same problem. Windows, FF 47. Tests used to work before, but now browser window opens and instantly shuts down. After some time I get

```
unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055) (Selenium::WebDriver::Error::WebDriverError)
```

in the console.

**Comment by jimevans** [comment] 2016-06-14 12:56
Duplicate of #2110

**Closed by jimevans** 2016-06-14 12:56 UTC
