### ISSUE TITLE
Selenium grid tests lose frame focus intermittently with Webdriver 2.45.0 and Firefox 37.0.1

### ISSUE THREAD

**Issue by ramviv** [SeleniumHQ/selenium#472] opened 2015-04-20 19:17 UTC
The issue started happening when firefox web browser got updated from 35,0.1 to 37.0.1. All of the tests that were working before stated failing and then we noticed that this happened because the tests seems to be losing frame focus.  The only way we could get the tests to work again was by using this section of code below

			if (strBrowser.equals("firefox"))
			{
				driver.switchTo().defaultContent();
				// Move into Appframe
				myHtml.waitAndSwitchFrame("AppFrame") ;
			}

waitAndSwitchFrame method is below

	public void waitAndSwitchFrame(String frameName)
	
	{
		BaseTest myBaseTest = new BaseTest();
		if (frameName == null)
		{
			myBaseTest.log.error(" Class: html | Function: waitAndSwitchFrame : Frame name is null or invalid.");
			return;
		}
		WebDriverWait wait = new WebDriverWait(driver, explicitWaitTime);
		wait.until(ExpectedConditions.frameToBeAvailableAndSwitchToIt(frameName));
		try
		{
			Thread.sleep(1000);
		} 
		catch (InterruptedException e)
		{
			myBaseTest.log.error(e.getMessage(), e);
		}
		
		myBaseTest.log.info(" Class: html | Function: waitAndSwitchFrame : Frame switch completed");
		driver.manage().timeouts().implicitlyWait(implicitWaitTime, TimeUnit.SECONDS);
	}
   When we tried again the same code without the update on the hosts that were still on 35.0.1, the tests work without the switch Frame. This also seems intermittent that this works sometimes and not others.

**Comment by nirvdrum** [comment] 2015-04-20 20:05
Just to clarify, I don't see how grid can affect this.  Good info to have, but I think it's a red herring.  It looks like a potential regression in FirefoxDriver.

**Comment by barancev** [comment] 2015-04-21 10:48
Please provide a [concise reproducible test case](http://sscce.org/).

**Comment by ramviv** [comment] 2015-04-22 17:36
Since our application is an internal application we are trying to see if we can reproduce this in a public website.

**Comment by ddavison** [comment] 2015-09-01 14:59
no answer for more than 3 months.  closing. 

If this is still an issue, please go ahead and reopen but please provide a reproducible test case in a "public website" as you had specified; if you do so.

**Closed by ddavison** 2015-09-01 14:59 UTC
Labels: D-firefox, R-awaiting answer
