### ISSUE TITLE
Timeouts in selenium while loading a URL

### ISSUE THREAD

**Issue by rj-max** [SeleniumHQ/selenium#8383] opened 2020-06-03 00:17 UTC
## 💥 Regression Report
Selenium UI Timeout after 60 seconds while making a HTTP call to an internal page.
OpenQA.Selenium.Support.UI.DefaultWait`1 .ThrowTimeoutException(String exceptionMessage, Exception lastException) 

This happens sporadically but has consistently been happening on one of the test servers today. 

I don't believe this is an issue specific to Geckodriver or Chromedriver because we are seeing this timeout issue across both platforms which leads me to believe it's something specific to Selenium. 

## Last working Selenium version

Worked up to version:
3.141.0 

Stopped working in version:
3.141.0

## To Reproduce

Detailed steps to reproduce the behavior:

## Test script reproducing this issue (when applicable)
```
               if (firefoxInstall)
                {
                    string firefoxManifestFile = Path.Combine(manifestPath, "Firefox", manifestFileName);

                    //Read the firefox manifest file to get the browser extension name 
                    EnterpriseHostManifest manifest = JsonConvert.DeserializeObject<EnterpriseHostManifest>(File.ReadAllText(firefoxManifestFile));

                    //Dependent on the manifest file structure. But if that changes, the canary will also change and that is expected
                    string firefoxExtensionName = manifest.AllowedExtensions[0];

                    //Assume one browser profile per test machine. Not built to test multiple browser profiles.
                    string pathToCurrentUserProfiles = Path.Combine(Environment.ExpandEnvironmentVariables("%APPDATA%"), @"Mozilla\Firefox\Profiles");
                    string[] pathsToProfiles = Directory.GetDirectories(pathToCurrentUserProfiles);
                    string pathToBrowserExtension = Path.Combine(pathsToProfiles[0], "extensions", String.Concat(firefoxExtensionName, ".xpi"));

                    //Check if firefox extension is installed 
                    if (!File.Exists(pathToBrowserExtension))
                    {
                        FirefoxInfrastructure = false;
                    }
                    else
                    {
                        FirefoxProfile profile = new FirefoxProfile(pathsToProfiles[0]);
                        FirefoxOptions options = new FirefoxOptions()
                        {
                            Profile = profile,                            
                        };
                firefoxDriver = new FirefoxDriver("C:\\Path", options, TimeSpan.FromSeconds(180));
                WebDriverWait wait = new WebDriverWait(driver, new TimeSpan(0, 0, 180)); ---> Times out here
                driver.Navigate().GoToUrl(homePage);

```

## Environment

OS: Windows 10
Browser:  Chrome and Firefox 
Browser version:  firefox.: 68.8.0 esr, Chrome: 83.0.4103.61
Browser Driver version: e.g.: ChromeDriver 83.0.0, GeckoDriver 
Language Bindings version: e.g.: C# 0.24.0 (Firefox)
Selenium Grid version (if applicable):

**Comment by diemol** [comment] 2020-06-14 11:45
@rj-max how can we reproduce this?
The attached code has dependencies that we don't know where they come from...

Could you please provide an automated script that reproduces this only using Selenium WebDriver?

**Comment by diemol** [comment] 2020-07-04 13:32
I'll close this due to the lack of information, if this is actually an issue, feel free to reopen while providing a way to reproduce it only using Selenium WebDriver.

**Closed by diemol** 2020-07-04 13:32 UTC
Labels: R-awaiting answer
