### ISSUE TITLE
[🐛 Bug]: Exception when browser is undefined

### ISSUE THREAD

**Issue by sgavila** [SeleniumHQ/selenium#11148] opened 2022-10-19 21:56 UTC
### What happened?

The page show black and console show error.

### How can we reproduce the issue?

```shell
Running a node in Selenium Grid 4 without browser config name.
```

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'length')
    at Zf (browser-logo.tsx:12:15)
    at Of (BrowserLogo.tsx:29:12)
    at Sa (react-dom.production.min.js:167:137)
    at xl (react-dom.production.min.js:290:337)
    at bu (react-dom.production.min.js:280:389)
    at gu (react-dom.production.min.js:280:320)
    at mu (react-dom.production.min.js:280:180)
    at ou (react-dom.production.min.js:271:88)
    at iu (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
```

### Operating System

All

### Selenium version

4.4.0

### What are the browser(s) and version(s) where you see this issue?

All

### What are the browser driver(s) and version(s) where you see this issue?

All

### Are you using Selenium Grid?

4.4.0

**Comment by diemol** [comment] 2022-10-20 10:09
Duplicate of #10907

**Closed as completed by diemol** 2022-10-20 10:09 UTC
Labels: I-defect
