### ISSUE TITLE
C# Error saving the screenshot file selenium 3.6.0

### ISSUE THREAD

**Issue by Nicronic** [SeleniumHQ/selenium#4900] opened 2017-10-18 15:54 UTC
## Meta -
OS:  
Windows 8.1
Selenium Version:  
3.6.0
Browser:  
Google Chrome 
Browser Version:  
61.0.3163.100 (Official Build) (64-bit)

## Actual Behavior -
System.Runtime.InteropServices.ExternalException : A generic error occurred in GDI+.
Результат Трассировка стека:	
at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at System.Drawing.Image.Save(String filename, ImageFormat format)
   at OpenQA.Selenium.Screenshot.SaveAsFile(String fileName, ScreenshotImageFormat format)
## Steps to reproduce -
Screenshot ss = ((ITakesScreenshot)driver).GetScreenshot();
ss.SaveAsFile("c:\\test.png", ScreenshotImageFormat.Png);

**Comment by bitterpeanut** [comment] 2017-10-21 01:05
Hi. Thanks for reporting this issue. Can provide some more details? Which driver are you using? Which browser are you using? Can you supply full code on reproducing?

I tried reproducing this on my system.
* Chrome: Version 62.0.3202.62 (Official Build) (64-bit)
* ChromeDriver: 2.33.506120
* Selenium WebDriver: 3.6.0

Code:
``` C#
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;

namespace SeleniumIssue4900
{
    class Program
    {
        static void Main(string[] args)
        {
            IWebDriver driver = new ChromeDriver();
            driver.Navigate().GoToUrl("https://www.google.com");
            var ss = ((ITakesScreenshot) driver).GetScreenshot();
            ss.SaveAsFile("C:\\tmp\\test.png", ScreenshotImageFormat.Png);
            driver.Quit();
        }
    }
}
```

This produced the screenshot as expected.

**Comment by bitterpeanut** [comment] 2017-10-24 21:55
@Nicronic any update? Have you checked your permissions of the directory which you are attempted to write your file?

```
Get-Acl C:\ | Format-List
```

Can you try writing to your home directory? I'd like to help, but I'm not sure I have the full picture. This looks to be a problem with your environment and not Selenium.

**Comment by barancev** [comment] 2017-11-16 14:45
Seems to be a duplicate of #4645

**Closed by barancev** 2017-11-16 14:45 UTC
Labels: C-dotnet, R-awaiting answer
