### ISSUE TITLE
[🐛 Bug]: "java.lang.UnsupportedOperationException: Select element is disabled and may not be used" exception thrown while accessing Dropdown element which is disabled

### ISSUE THREAD

**Issue by VikramMokallaTR** [SeleniumHQ/selenium#11125] opened 2022-10-14 07:29 UTC
### What happened?

**Scenario:** Access a disabled Dropdown element and fetch the text of the selected option.
**Issue:** On providing a **dropdown element which is disabled** to Select class, "java.lang.UnsupportedOperationException: Select element is disabled and may not be used" exception is thrown. After looking into the Select class in org.openqa.selenium.support.ui.Select, there is an update in 4.5.0 which is checking whether the element is enabled or not (not included in 4.3.0):

**Method in Selenium 4.5.0: org.openqa.selenium.support.ui.Select:53**
```
public Select(WebElement element) {
    String tagName = element.getTagName();

    if (!"select".equalsIgnoreCase(tagName)) {
      throw new UnexpectedTagNameException("select", tagName);
    }

    **if (!element.isEnabled()) {
      throw new UnsupportedOperationException("Select element is disabled and may not be used.");
    }**

    this.element = element;

    String value = element.getDomAttribute("multiple");

    // The atoms normalize the returned value, but check for "false"
    isMulti = (value != null && !"false".equals(value));
  }

```

**Method in Selenium 4.3.0: org.openqa.selenium.support.ui.Select:53**

```
public Select(WebElement element) {
    String tagName = element.getTagName();

   if (null == tagName || !"select".equals(tagName.toLowerCase())) {
      throw new UnexpectedTagNameException("select", tagName);
    }

   this.element = element;

   String value = element.getDomAttribute("multiple");

   // The atoms normalize the returned value, but check for "false"
    isMulti = (value != null && !"false".equals(value));
  }
```

### How can we reproduce the issue?

```shell
Provide a disabled dropdown element to Select class with Selenium version [4.5.0].
```

### Relevant log output

```shell
java.lang.UnsupportedOperationException: Select element is disabled and may not be used.
	at org.openqa.selenium.support.ui.Select.<init>(Select.java:53)
```

### Operating System

Windows 10

### Selenium version

Java Selenium 4.5.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 106

### What are the browser driver(s) and version(s) where you see this issue?

106.0.5249.61

### Are you using Selenium Grid?

No

**Comment by diemol** [comment] 2022-10-14 07:31
Duplicate of #10812

**Closed as completed by diemol** 2022-10-14 07:31 UTC
