### ISSUE TITLE
[🚀 Feature]: a capability to set the process priority

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#10317] opened 2022-02-02 16:37 UTC
### Feature and motivation

A capability to set the process priority of the drivers and browsers could help to orchestrate important and not so important tests in shared environments. For example we are running 24/7 performance tests in a 15 minutes intervall. The performance tests will measure the time spent for some operations on the website. The regular regression tests are executed on demand and will run on the same system. To minimize the impact of the regression tests to the times measured in the performance tests it would be good to set the process priority while creation of the session.

### Usage example

This could help to reduce the amount of reserved hardware only for collecting performance numbers.

**Comment by diemol** [comment] 2022-02-04 11:03
Maybe this is a duplicate of #9407?

**Comment by joerg1985** [comment] 2022-02-04 11:47
i have seen the other issue before opening this one, i would not call it a duplicate more an addition. 
the other issue is about the internal rounting and this ticket is about process priority in the OS.

**Comment by diemol** [comment] 2022-02-04 12:55
Thanks for the clarification.

Being able to configure the OS process priority adds quite some complexity to the Grid, in exchange to support a not common use case. 

In addition to that, we might be able to set the process priority for the browser driver (ChromeDriver, GeckoDriver, etc...), but we have no control over the way the browser is launched, given that this is done by the browser driver.

Regarding the specific scenario you describe, ideally performance tests should run on infrastructure only being used for that purpose, or at least have window frames where those tests can run exclusively. Setting a OS process priority is probably not the right solution for this scenario, which could be solved by a different way of planning.

**Closed as completed by diemol** 2022-02-04 12:55 UTC
