### ISSUE TITLE
Selenium 3: Firefox 47 getting Crashed with Selenium 3 Beta Jar

### ISSUE THREAD

**Issue by abhinav1708** [SeleniumHQ/selenium#2373] opened 2016-06-25 05:58 UTC
## Meta -
OS:  Win 7 64

Selenium Version:  3 Beta

Browser:  FireFox 47

Browser Version:  

## Expected Behavior -
Firefox Should Launch Successfully
## Actual Behavior -
Firefox Crashes while Launching
Exception
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.42.2', revision: '75f266f', time: '2014-07-30 09:11:33'
System info: host: 'NOI1-CIS616', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_73'
Driver info: driver.version: Driver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:670)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:247)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:219)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:214)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:131)
## Steps to reproduce -

Set Marionette Capability to false and Launch Firefox Driver
Sample Code
```
DesiredCapabilities des = new DesiredCapabilities();
		des.setCapability(FirefoxDriver.MARIONETTE, false);
      	driver = new FirefoxDriver(des);
```

**Comment by lukeis** [comment] 2016-06-25 06:33
47 can't run with of FirefoxDriver, you must use 46 or earlier  duplicate of #2110

**Closed by lukeis** 2016-06-25 06:33 UTC
