### ISSUE TITLE
Selenium::WebDriver::Element#send_keys no longer works as expected

### ISSUE THREAD

**Issue by twalpole** [SeleniumHQ/selenium#2704] opened 2016-09-01 21:33 UTC
OS:  
OSX/linux
Selenium Version:  
Head - 3.0.0.beta2.1
Browser:  
Firefox
Browser Version:  
49 beta
## Expected Behavior -

Expect modifier keys to be released when passed in an array
## Actual Behavior -

Modifier keys are no longer released 
## Steps to reproduce -

Using the ruby bindings (selenium-webdriver gem)

```
element.send_keys([:shift, 'a'], 'bcdef'
```

In previous (2.x) versions of selenium-webdriver with Firefox < 48 this would cause element to be sent the keys 'Abcdef'.  When used with the current head version and geckodriver/marionette it ends up sending "A&lt;null>BCDEF" to the element.  This appears to be because the Webdriver spec has removed the previous requirement that a NULL being sent should be interpreted as releasing key modifiers.  This also prevents things like `element.send_keys([:ctrl, 'a'], :backspace, 'abcd') for selecting the current contents of a field and sending new content.   The NULL is currently inserted by selenium [here](https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/common/keys.rb#L114).  Splitting up the passed items into multiple send key requests may solve this issue, although the current webdriver spec for [Element Send Keys](https://www.w3.org/TR/webdriver/#element-send-keys) requires using set selection range to set the insertion caret which could break things the [:ctrl, 'a'] shown above.

**Comment by lukeis** [comment] 2016-09-01 23:00
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net

**Comment by twalpole** [comment] 2016-09-02 00:31
@lukeis This isn't a geckodriver issue -- geckodriver is adhering to the current webdriver spec.  It's selenium that's sticking extra nulls into the keys being sent

**Comment by lmtierney** [comment] 2017-01-18 15:05
@twalpole can you see if #3375 works for this? I tried it with the latest geckodriver & Nightly and it seems to be working for your examples

**Comment by lmtierney** [comment] 2017-01-18 15:16
If the spec updates to handle null characters then I we can just strip it out, but until then this should provide the functionality

**Comment by twalpole** [comment] 2017-01-19 00:01
@lmtierney As I commented on the PR - this isn't a great solution since it still won't match the previous behavior due to selection and caret position being reset between each call - hopefully something happens with https://github.com/w3c/webdriver/issues/553 to get the spec to support the original behavior

**Comment by lmtierney** [comment] 2017-01-19 01:54
@twalpole Where does it say that the caret position is reset between each call? This does currently work with geckodriver 0.13.0 and Firefox Nightly for:

    element.send_keys([:shift, 'a'], 'bcdef')

 and the spec states:

    Set the text insertion caret using set selection range with using current text length as the 2 parameters passed in.

Which if I'm understanding that correctly, will send the length of the current text in the element to [setSelectionRange()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange) as both parameters; therefore putting the carat at the end? Or am I misinterpreting it all?

Code I used:

```
caps = {firefox_options: {binary: '/Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin'}}
driver = Selenium::WebDriver.for :firefox, desired_capabilities: caps
driver.get('http://the-internet.herokuapp.com/login')
driver.find_element(id: 'username').send_keys([:shift, 'a'], 'bcdef')
sleep(3)
driver.find_element(id: 'username').send_keys([:command, 'a'], :backspace, 'abcde')
```

**Comment by titusfortner** [comment] 2017-01-19 01:55
@twalpole - do you have a failing spec we can use as reference?

**Comment by twalpole** [comment] 2017-01-19 02:24
Start with a field with content "ello",  send the keys ctrl-left arrow (or cmd depending on platform) followed by 'h'  --  The field should then have 'hello' - if split into multiple send_keys it will have 'elloh'

**Comment by lmtierney** [comment] 2017-01-19 02:39
I see what you're saying now. Is this a normal use case for people? I guess if the spec doesn't pick up the handling of null then people would need to use actions

**Comment by twalpole** [comment] 2017-01-19 02:42
I guess "normal" depends on what people are testing.  It would be a shame to lose the ability to send key strokes that a user could use just because someone doesn't want to provide a way to release the modifier keys.  Yes, actions could be used but that seems like massive overkill for something that should be relatively to easy support in marionette/webdriver, was supported in FirefoxDriver, and is supported by ChromeDriver.

**Comment by titusfortner** [comment] 2017-01-19 02:49
I can't reproduce what you say is current behavior in Chrome.

This:

`send_keys 'ello', [:command, :arrow_left], 'h'`

Gives: `elloh`

**Comment by titusfortner** [comment] 2017-01-19 02:51
Spoke too soon, for some reason replacing `:command` with `:alt` works

**Comment by twalpole** [comment] 2017-01-19 03:37
@titusfortner Ah -- maybe [:alt, :left] works on all platforms -- that would make tests easier

**Comment by lmtierney** [comment] 2017-01-19 11:50
`:alt` on macOS will typically move one word back so it may not be the same functionality. `[:command, :left]` *should* be the macOS equivalent of `[:alt, :left]` on Windows. It does work that way manually but not through Chromedriver

**Comment by lmtierney** [comment] 2017-01-19 16:58
That was a quick merge, will keep an eye out for w3c/webdriver#578 and if it doesn't get added I can re-open that PR

**Comment by twalpole** [comment] 2017-01-22 22:09
https://github.com/w3c/webdriver/pull/578 was merged, so the null separators should be good again when geckodriver/marionette get around to implementing it. Not sure if there may be changes needed in selenium around the change in the spec to grapheme clusters.

**Comment by p0deje** [comment] 2017-09-04 07:18
So now spec correctly defines null separators and it looks like there is nothing to do on Selenium side. GeckoDriver still doesn't implement it correctly (see mozilla/geckodriver#245), so I've added regression test to track the progress bb73a56e4e0d34d3d69a6e0f2d7c1f45105a5301.

At this point I feel we can just close this issue. @twalpole are you ok with that?

**Comment by twalpole** [comment] 2017-09-04 07:24
@p0deje  Sure, this is definitely a geckodriver issue now, with no real way to work around it until they become spec compliant.

**Closed** 2017-09-04 07:25 UTC
Labels: C-rb
