### ISSUE TITLE
[py] set_page_load_timeout() crashes with firefox: unknown field `sessionId` (v61 → v62 regression)

### ISSUE THREAD

**Issue by martinpitt** [SeleniumHQ/selenium#6420] opened 2018-09-17 20:05 UTC
## Meta -
OS:  Fedora  28
Selenium Version:  3.14
Browser:  Firefox
Browser Version:  v62.0
selenium-python version: 3.7.0-3.fc28

## Steps to reproduce -

Run selenium in containers (current :3 tag points to 3.14.0):

     docker run -d -p 4444:4444 --name selenium-hub selenium/hub:3
     docker run -d --link selenium-hub:hub selenium/node-firefox:3

Things generally work with Python:
```
# python
>>> import selenium.webdriver
>>> driver = selenium.webdriver.Remote(command_executor='http://10.111.112.10:4444/wd/hub', desired_capabilities={'browserName': 'firefox'})
>>> driver
<selenium.webdriver.remote.webdriver.WebDriver (session="975c7096-105b-436e-a5b5-6506ed332bcb")>
>>> driver.get_window_size()
{'width': 1224, 'height': 918}
>>> driver.set_window_size(1400, 1200)
>>> driver.get_window_size()
{'width': 1400, 'height': 1200}
```

But trying to call `set_page_load_timeout()` fails:
```
>>> driver.set_page_load_timeout(90)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 830, in set_page_load_timeout
    'type': 'page load'})
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown field `sessionId`, expected one of `implicit`, `pageLoad`, `script` at line 1 column 12
```

This does not happen with other drivers like selenium/node-chrome:3 or MS Edge (https://docs.microsoft.com/en-us/microsoft-edge/webdriver), and it also still works with the (ancient) selenium/node-firefox:2.53.1.

The code around "def execute()" and "def set_page_load_timeout" doesn't seem to have changed at all in current upstream master: https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py

So somehow firefox doesn't stomach the extra `sessionId` parameter that execute() adds.

**Comment by martinpitt** [comment] 2018-09-17 20:11
I tried to take `def execute()` out of the equation, by running

        driver.command_executor.execute(Command.SET_TIMEOUTS, {'pageLoad': 90000})

but this then fails with
```
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 458, in execute
    path = string.Template(command_info[1]).substitute(params)
  File "/usr/lib64/python2.7/string.py", line 176, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/lib64/python2.7/string.py", line 166, in convert
    val = mapping[named]
KeyError: 'sessionId'
```

**Comment by martinpitt** [comment] 2018-09-17 20:43
This works with selenium/node-firefox:3.0 (2 years old), so I bisected this. versions up to 3.14.0-dubnium ( v:61.0.2) work fine, so the regression is in 3.14.0-europium (v62.0).

**Comment by lmtierney** [comment] 2018-09-17 20:59
I cannot reproduce this with a fresh download of the latest nodes.

**Comment by martinpitt** [comment] 2018-09-17 21:04
@lmtierney : I downloaded the containers today as well, and I have the explicit tags that surround the regression. Perhaps something subtle changed in selenium-python, then? Which version are you using?

**Comment by lmtierney** [comment] 2018-09-17 21:04
`3.14`

**Comment by lmtierney** [comment] 2018-09-17 21:07
Are you sure you're not using an older python version? You stated in the issue template that you're using python `3.7` but in the error it is showing `2.7`

**Comment by martinpitt** [comment] 2018-09-17 21:10
I'm using Python 2.7. Fedora 28 only has a Python 2 package for selenium. *Its* version is 3.7.0, not Python's. Fedora 29 has a newer python-selenium (3.12), I'll try that. I was just wondering how you get your's, from pip or somewhere else?

**Comment by lmtierney** [comment] 2018-09-17 21:10
```
$ docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
selenium/node-firefox   3                   fbdcbad98f63        35 hours ago        741MB
selenium/hub            3                   c399b4d42308        35 hours ago        295MB
```
```
>>> import selenium.webdriver
>>> driver = selenium.webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities={'browserName': 'firefox'})
>>> driver
<selenium.webdriver.remote.webdriver.WebDriver (session="685334c8-14d0-4421-889d-4e51d3f14918")>
>>> driver.get_window_size()
{'width': 1224, 'height': 918}
>>> driver.set_page_load_timeout(90)
>>> driver.capabilities
{'acceptInsecureCerts': False, 'browserName': 'firefox', 'browserVersion': '62.0', 'moz:accessibilityChecks': False, 'moz:geckodriverVersion': '0.22.0', 'moz:headless': False, 'moz:processID': 80, 'moz:profile': '/tmp/rust_mozprofile.0CDP2SwgjDFm', 'moz:useNonSpecCompliantPointerOrigin': False, 'moz:webdriverClick': True, 'pageLoadStrategy': 'normal', 'platformName': 'linux', 'platformVersion': '4.15.0-34-generic', 'rotatable': False, 'timeouts': {'implicit': 0, 'pageLoad': 300000, 'script': 30000}, 'webdriver.remote.sessionid': 'c468c2ad-e147-48f6-b6d8-a3f46ea09e90'}
>>> driver.quit()
```

**Comment by lmtierney** [comment] 2018-09-17 21:11
Oh whoops, I missed that. I glazed over it when I saw `3.7`. Yes I install from pip.

**Comment by lmtierney** [comment] 2018-09-17 21:15
Can you verify the selenium version installed at `/usr/lib/python2.7/site-packages/selenium`is `3.14`? The error message in your trace:

>   File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 830, in set_page_load_timeout
    'type': 'page load'})

Is suspect as the line number is not right for that code.

**Comment by lmtierney** [comment] 2018-09-17 21:28
I can confirm this was fixed with the above mentioned commit, released in `3.9.0`

**Closed by lmtierney** 2018-09-17 21:28 UTC

**Comment by martinpitt** [comment] 2018-09-17 21:33
That commit makes a lot of sense, thanks! I'll forward that to the Fedora downstream bug (https://bugzilla.redhat.com/show_bug.cgi?id=1629909)

**Comment by martinpitt** [comment] 2018-09-17 21:47
Confirmed that it works with 3.12. Thanks!
