### ISSUE TITLE
Element is not clickable at point - C# - Chrome Driver

### ISSUE THREAD

**Issue by gabernardone** [SeleniumHQ/selenium#4801] opened 2017-10-03 12:34 UTC
## Meta -
OS:  Windows 10

Selenium Version:  3.6.0, Visual Studio, C#

Browser:  Google Chrome

Browser Version:  2.31.488763 (32-bit)

## Expected Behavior - 
Click on found element

## Actual Behavior -
 I have an automation project using Selenium WebDriver in version 3.6 and the Chrome Driver. The software was working fine until it started to display the error

> Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.
> 
> unknown error: Element is not clickable at point (25, -9) (Session info: chrome=61.0.3163.100) (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 6.1.7601 SP1 x86_64).

  I'm using the .click () method to click on the element, and this always worked, I've never had any problems with the software running for months
> 

Searching the internet I found methods that even worked like using .SendKey () and IJavaScriptExecutor to give a scroll to the element. But the point is I never had to do this ..

Could it be some bug in this version of Selenium? Maybe Chrome Driver?

**Comment by Vijayabaskar03** [comment] 2017-10-04 04:01
This seems to be already fixed in V 2.32. The changelog says:
Fixes a bug where Chromedriver fails to click due to page scrolling changes in Chrome 61+.

Did you try updating your driver?

**Comment by javiervg** [comment] 2017-10-04 04:27
I can confirm that updating to V 2.32 solved my clickable issues. Thanks for posting your comment Vijayabaskar03

**Closed** 2017-10-04 06:40 UTC

**Comment by padi** [comment] 2017-10-16 05:11
Can confirm that upgrading works i.e. selenium is now able to scroll down pages in Chrome 61 with chromedriver v2.33.

**Comment by meet-sapu** [comment] 2017-11-25 17:59
This issue was headache to me while writing a web scraping script in python , I solution for this came out to be simple , I simply scrolled down(or it could be up in your case) the webpage and then clicking the button worked for , as it turns out it the webdriver is firefox or internet explorer this is not n issue but it's an issue for chrome webdriver .

**Comment by kaloyragalag** [comment] 2018-06-29 10:58
Hi this still persist in ChromeDriver 2.35.528161
