### ISSUE TITLE
Selenium-hub 2.52.0 crashes after updating webdriver

### ISSUE THREAD

**Issue by cristim** [SeleniumHQ/selenium#1646] opened 2016-02-16 17:08 UTC
We recently updated all our Selenium infrastructure from 2.43.1 to 2.52.0, and the browsers from Firefox 33 to 44. The last piece we updated was the selenium-webdriver npm module, which we updated from 2.48.2 to 2.52.0.

Once this change was implemented, we started observing complete test failures and the selenium hub logs are full of errors like this:

```
        at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:126)
        at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:67)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Unknown Source)
Caused by: 
java.lang.IllegalStateException: Not a JSON Object: [["browserName","firefox"],["firefox_profile","UEsDBBQACAAIALiBUEgAAAAAAAAAAAAAAAAHAAAAdXNlci5qc5VWyW7bMBC99ysKn1qgJpK4vbSnNGmBAgVyCIIeCYoaSYwpkiCHVvz3HUqWYy3ebrLx3uzzhjGA585D8WkhnGPR5QKBiYh28eVjIXSAzz8+xFkQGJFpyOdxmbcNsVhuG6OtyFktjCjpj1DZ5l8F5hmFR2XK0/RfL3/vmd2A9yoHgqKPo4B6Ry1yxYSU4LCN6jhWK7Nm1oHh8IbgjdBk+m6YaG/3HWugaZShhI6DbVEQPgU6U7reYhAFtN+UPbuoiAGEl9WuOfPGUyImKGsCy7SVa60CXmo8tDy0HpiHEGvghbc1l16Eat7bPpUKtGayArl+hEJEjT+7vp+mocgCa4Q3T+ZB23CmXgfoJ+rZadMhjVV0zNGwEfJmvqmDFtRCUyxwulq93crWkGzzBrSkbx59Gp6FyGzE75kWZr0Y+sxhg9bqwGiIrZfUIasPnU3HNLc1y1VI28XbKc2jp1nhaY/msz/oflrdx478LIkdiHE7KsMBXNuyHM7hNJ4D+E4fTk7tFG4sqmL7QnowH74BbKxf7zRiuduiJdUcY4p/Zpl6SoXoiPe2pMIakJg2YOnAL8kZycZM8gOmq1SotsskcE6EsNRgSkxDf/ft27CNfVCkkoEJrW3Dsy3Pu6knwrRsjpbIYWA0v7y2udBnJgwktRm3rFAa6ItZr6g13Fmt5JY8rIYBhTE+oFcS+Zg2U7w9Ne0gB0MamOar/fvIMp6ktKLOrZHXkRsQa8rr8gAT4TpfGsTmutSGjOu8hZjVCrkyl1dyo4COSslr9XbslA5LPyCcDU+VxhpS9RrqDPxz+/PIRiWRWitku/3o7/VOiGYnvKcgaPKAfnt6wqfwbkXaxEfnd4r18Er7feSyv4qNCNIrh3TXWxFoS/PHPHR6Oxt+f8WS3naXneWxdgdJTJe6gSz3ipSFdy8NHg2BAsXFJXhMtT1F6oSTG4Fkg8OGdu8chWQpneR3P4r+aJVt6ihlQmLIu1JwHw1HVaetXI1OQJ87aUxFGrVqy5Vu69ToHgoiTy86wLYPv5UPeE9vOKmTg+O8yens33OsDmjb19Li9usduxkdTmVQM3rLCDqXtUBZPT2Tnxm1KMGAJ3lNKk6n2eCORegFmGWZjQzvL3IAXbyFwKSl6hL69mZUpTaEXaPptJeRzKd+vZv9D1BLBwh8EksBaQMAAEALAABQSwECLQMUAAgACAC4gVBIfBJLAWkDAABACwAABwAAAAAAAAAAACAApIEAAAAAdXNlci5qc1BLBQYAAAAAAQABADUAAACeAwAAAAA="]]

```

We can always reproduce it and reverting webdriver to  2.48.2 is a workaround for our issue.
We also use the latest version of the firefox-profile npm module, which hasn't been changed for about a year now.

**Comment by lukeis** [comment] 2016-02-16 17:22
are you running into the same issue as #1627 ?

**Comment by barancev** [comment] 2016-02-16 18:34
Yes, it's a duplicate of #1627

**Closed by barancev** 2016-02-16 18:34 UTC

**Comment by cristim** [comment] 2016-02-16 18:38
My issue is happening with Firefox,  while #1627 is about the manifestation in Chrome.

 Considering this, does it still count as a duplicate?

**Comment by lukeis** [comment] 2016-02-16 18:48
@cristim yes, it has to do with how the node libraries are not serializing the JSON properly

**Comment by barancev** [comment] 2016-02-16 18:49
The mentioned issue is not related to a specific browser, it's a serialization problem.
