### ISSUE TITLE
'LOCATOR_DETECTION_FAILED' appears when trying to upload file from desktop.

### ISSUE THREAD

**Issue by AwniBaggio** [SeleniumHQ/selenium#1361] opened 2015-12-09 12:18 UTC
trying to upload file from my desktop to continue recording a scenario, but LOCATOR_DETECTION_FAILED appears in target.

ple see the attached img.
![ideissue](https://cloud.githubusercontent.com/assets/16224100/11685167/b6701bcc-9e7f-11e5-8f16-97fc35c03857.png)

** can I make any changes on 'source' tab may helps??

**Comment by ddavison** [comment] 2015-12-10 14:43
could you share the source where this is happening?  my guess is that there is nothing that can uniquely identify this field.  I cannot reproduce thi.

**Comment by barancev** [comment] 2016-01-27 05:49
Closing the issue as there is no responce from the author for long period.

**Closed by barancev** 2016-01-27 05:49 UTC
Labels: C-ide, R-awaiting answer
