### ISSUE TITLE
Selenium IDE - Not able to install in latest Firefox 56.0.x

### ISSUE THREAD

**Issue by kpassoubady** [SeleniumHQ/selenium#4515] opened 2017-08-20 19:02 UTC
Not able to install Selenium IDE latest version (2.9.1.1-signed) into latest version of Firefox.

Please see the attached image below for more information.
<img width="590" alt="selenium-ide-not-compatible-with-firefox2017-08-20_12-06-16" src="https://user-images.githubusercontent.com/1095193/29497571-4f403d5c-859f-11e7-89f7-b366a6ec4f13.png">

**Comment by barancev** [comment] 2017-08-20 19:30
Duplicate of #4406

**Closed by barancev** 2017-08-20 19:30 UTC
