### ISSUE TITLE
Selenium IDE record button not working

### ISSUE THREAD

**Issue by lalith2378** [SeleniumHQ/selenium#4401] opened 2017-08-03 05:48 UTC
Hi,

I have updated firefox to the latest version and when I try to work with Selenium IDE it is not recording the actions. Record button highlights as it is in recording mode but it is not recording anything..
i get the below error.

"There was an unexpected error. Msg: TypeError: curSuite is null
Url: chrome://sidefavorites/content/logic/Favorites.js?1501738112151, line: 138, column: 1
Favorites.prototype.isCurSuiteFavorite@chrome://sidefavorites/content/logic/Favorites.js?1501738112151:138:1
Favorites.prototype.populateMenuPopup@chrome://sidefavorites/content/logic/Favorites.js?1501738112151:45:17
onpopupshowing@chrome://selenium-ide/content/selenium-ide.xul:1:1"]

Can someone assist me on this?
thanks

**Comment by barancev** [comment] 2017-08-04 06:25
Duplicate of #4406

**Closed by barancev** 2017-08-04 06:25 UTC
Labels: C-ide

**Comment by vigneshraj** [comment] 2017-10-09 15:58
I have an error in selenium IDE..
""There was an unexpected error. Msg: TypeError: curSuite is null
Url: chrome://sidefavorites/content/logic/Favorites.js?1506357448057, line: 138, column: 1
Favorites.prototype.isCurSuiteFavorite@chrome://sidefavorites/content/logic/Favorites.js?1506357448057:138:1
Favorites.prototype.populateMenuPopup@chrome://sidefavorites/content/logic/Favorites.js?1506357448057:45:17
onpopupshowing@chrome://selenium-ide/content/selenium-ide.xul:1:1"" - this is an error please help me what i do??

**Comment by vigneshraj** [comment] 2017-10-09 16:03
And also i have this error in opening of Selenium ide 
There was an unexpected error. Msg: TypeError: obj is undefined
Url: chrome://implicit-wait/content/implicit-wait-ide.js?1506357448055, line: 185, column: 9
wrap@chrome://implicit-wait/content/implicit-wait-ide.js?1506357448055:185:9
ImplicitWait/<@chrome://implicit-wait/content/implicit-wait-ide.js?1506357448055:27:9

- what i do for this error??

**Comment by lmtierney** [comment] 2017-10-09 16:18
@vigneshraj read #4406, IDE is not compatibile with Firefox 55+ https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/

**Comment by vigneshraj** [comment] 2017-10-10 14:11
thank u so much for ur guideline...

**Comment by nextbigdata** [comment] 2017-11-02 10:38
Hi,
  I'm using firefox version 56.0 and selenium 2.9.0.
 I facing the issue is
        1.Table view is not available in this format
        2.Record is not working
If any one please provide solution to this given below mail
       arunram860@gmail.com

**Comment by naveenram8** [comment] 2018-02-05 10:30
Hi,
I'm using firefox version 56.0 and selenium 2.9.0.
I facing the issue is
1.Table view is not available in this format
2.Record is not working
If any one please provide solution to this given below mail
naveenram8@gmail.com
