### ISSUE TITLE
Screenshot from webElement

### ISSUE THREAD

**Issue by AndrushaBystrik** [SeleniumHQ/selenium#1284] opened 2015-11-19 15:16 UTC
In changelog i read, that i can take screenshot to WebElement ( Added TakesScreenshot to WebElement. ).

And on selenium-2.48.2.jar i can't take screenshot

simple code :

EventFiringWebDriver driver = new EventFiringWebDriver(new FirefoxDriver());
		driver.get("http://google.com");
		try
		{
			WebElement content = driver.findElement(By.className("content"));
			File file = content.getScreenshotAs(OutputType.FILE);
			BufferedImage read = ImageIO.read(file);
			System.out.println(read.getMinX());
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
		finally
		{
			driver.quit();
		}

and stacktrace :

org.openqa.selenium.UnsupportedCommandException: Unrecognized command: GET /session/7db796c3-249a-47a5-adcf-0b1f5bd4c456/screenshot/%7Bb5785d01-f56d-45c3-b3f4-2a9c18b694e0%7D
Command duration or timeout: 14 milliseconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:55:52'
System info: host: 'myMachine', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.8.0-44-generic', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=42.0, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 7db796c3-249a-47a5-adcf-0b1f5bd4c456
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:326)
	at org.openqa.selenium.remote.RemoteWebElement.getScreenshotAs(RemoteWebElement.java:436)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:334)
	at com.sun.proxy.$Proxy2.getScreenshotAs(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.getScreenshotAs(EventFiringWebDriver.java:458)
	at asd.TempMainClass.main(TempMainClass.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by lukeis** [comment] 2015-11-19 17:57
The open source project's FirefoxDriver does not support taking a screen shot by webelement (yet? ever?)

duplicate of #912

**Closed by lukeis** 2015-11-19 17:57 UTC
