### ISSUE TITLE
Send Keys do not send "password123" to any text field . While using Javascript i am able to fill

### ISSUE THREAD

**Issue by asjadtariq** [SeleniumHQ/selenium#5086] opened 2017-11-20 17:29 UTC
## Meta -
OS:  OSX

Selenium Version:  3.5.2

Browser:  Chrome

Browser Version:  

## Expected Behavior - Below is code which I run and its not passing exact string to text field on any website

 I am passing value to textfield using sendkeys function it should send the exact value e.g. **password123** Its really strange this string can be tried with any type of text field issue remains

## Actual Behavior -
If you check on the website it will only send text **password12** its very strange as it work with all other string e.g. if i pass 
driver.findElement(By.id("user[login]")).sendKeys("password456"); it enter in field as expected : **password456**

## Steps to reproduce -

**JAVA Code**

WebDriver driver = new ChromeDriver();
	driver.get("https://github.com/");
	driver.findElement(By.id("user[login]")).sendKeys("password123");
	Thread.sleep(2000);

_**I have actually overcome the issue by using javascript which is as below:**_

	JavascriptExecutor  js= (JavascriptExecutor) driver;
	js.executeScript(String.format("document.getElementById('user[login]').value='password123';"));

**Comment by twalpole** [comment] 2017-11-20 17:34
You're probably running into https://bugs.chromium.org/p/chromedriver/issues/detail?id=1771&q=send_keys&colspec=ID%20Status%20Pri%20Owner%20Summary

**Comment by barancev** [comment] 2017-11-20 20:35
Yes, it's either a duplicate of the mentioned issue, or a new issue that should be reported to chromedriver tracker too.

**Closed by barancev** 2017-11-20 20:35 UTC
