### ISSUE TITLE
Selenium 3.0.1 - html-runner not able to find test suite (URL form) 

### ISSUE THREAD

**Issue by JackoLanternRz** [SeleniumHQ/selenium#3467] opened 2017-02-06 09:15 UTC
## Meta -
OS: 

- Windows 7

Selenium Version:  

- selenium-server-standalone-3.0.1 & selenium-html-runner-3.0.1 

Browser:  

- Firefox

Browser Version:  

- Firefox 51.0

## Expected Behavior -

- See my suite running

## Actual Behavior -

- Errors is thrown

I'm trying to run my suite on Firefox, according to this issue
[https://github.com/SeleniumHQ/selenium/issues/2706](https://github.com/SeleniumHQ/selenium/issues/2706)
I struggled some days and figured out that I need to launch the standalone server, then I'm able to feed the html-runner with an URL suite source so that I won't get an error message of Address already in use.
However, now I get new error message said that the html runner is not able to find my suite

This is the commands and the content of mySuite.html I'm running:

Server:
`java -jar "D:\JAVA\selenium-java-3.0.1\selenium-server-standalone-3.0.1.jar"`

Htmlrunner:
`java -jar "D:\JAVA\selenium-java-3.0.1\selenium-html-runner-3.0.1.jar" -htmlSuite "*firefox" http://targetwebpage "http://localhost:4444/mySuite.html" "D:\JAVA\selenium-java-3.0.1\result"`

mySuite.html:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="content-type" />
  <title>Test Suite</title>
</head>
<body>
<table id="suiteTable" cellpadding="1" cellspacing="1" border="1" class="selenium"><tbody>
<tr><td><b>Test Suite</b></td></tr>
<tr><td><a href="172.21.128.191_8090.html">172.21.128.191_8090</a></td></tr>
<tr><td><a href="172.21.128.191_8100.html">172.21.128.191_8100</a></td></tr>
<tr><td><a href="172.21.128.191_8110.html">172.21.128.191_8110</a></td></tr>
<tr><td><a href="172.21.128.191_8120.html">172.21.128.191_8120</a></td></tr>
<tr><td><a href="172.21.128.191_8130.html">172.21.128.191_8130</a></td></tr>
<tr><td><a href="172.21.128.191_8140.html">172.21.128.191_8140</a></td></tr>
<tr><td><a href="172.21.128.191_8150.html">172.21.128.191_8150</a></td></tr>
<tr><td><a href="172.21.128.191_8160.html">172.21.128.191_8160</a></td></tr>
<tr><td><a href="172.21.128.192_8090.html">172.21.128.192_8090</a></td></tr>
<tr><td><a href="172.21.128.192_8100.html">172.21.128.192_8100</a></td></tr>
<tr><td><a href="172.21.128.192_8110.html">172.21.128.192_8110</a></td></tr>
<tr><td><a href="172.21.128.192_8120.html">172.21.128.192_8120</a></td></tr>
<tr><td><a href="172.21.128.192_8130.html">172.21.128.192_8130</a></td></tr>
<tr><td><a href="172.21.128.192_8140.html">172.21.128.192_8140</a></td></tr>
<tr><td><a href="172.21.128.192_8150.html">172.21.128.192_8150</a></td></tr>
<tr><td><a href="172.21.128.192_8160.html">172.21.128.192_8160</a></td></tr>
<tr><td><a href="172.21.128.209_8090.html">172.21.128.209_8090</a></td></tr>
<tr><td><a href="172.21.128.209_8100.html">172.21.128.209_8100</a></td></tr>
<tr><td><a href="172.21.128.209_8110.html">172.21.128.209_8110</a></td></tr>
<tr><td><a href="172.21.128.209_8120.html">172.21.128.209_8120</a></td></tr>
<tr><td><a href="172.21.128.209_8130.html">172.21.128.209_8130</a></td></tr>
<tr><td><a href="172.21.128.209_8140.html">172.21.128.209_8140</a></td></tr>
<tr><td><a href="172.21.128.209_8150.html">172.21.128.209_8150</a></td></tr>
<tr><td><a href="172.21.128.209_8160.html">172.21.128.209_8160</a></td></tr>
<tr><td><a href="172.21.128.210.8090.html">172.21.128.210.8090</a></td></tr>
<tr><td><a href="172.21.128.210_8100.html">172.21.128.210_8100</a></td></tr>
<tr><td><a href="172.21.128.210_8110.html">172.21.128.210_8110</a></td></tr>
<tr><td><a href="172.21.128.210_8120.html">172.21.128.210_8120</a></td></tr>
<tr><td><a href="172.21.128.210_8130.html">172.21.128.210_8130</a></td></tr>
<tr><td><a href="172.21.128.210_8140.html">172.21.128.210_8140</a></td></tr>
<tr><td><a href="172.21.128.210_8150.html">172.21.128.210_8150</a></td></tr>
<tr><td><a href="172.21.128.210_8160.html">172.21.128.210_8160</a></td></tr>
</tbody></table>
</body>
</html>
````

And I got the following error messages:
```
二月 06, 2017 4:42:12 下午 org.openqa.selenium.remote.ProtocolHandshake createSe
ssion
資訊: Detected dialect: W3C
[Child 708] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/
m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056
二月 06, 2017 4:42:14 下午 org.openqa.selenium.os.UnixProcess destroy
嚴重: Unable to kill process with PID 9172
二月 06, 2017 4:42:14 下午 org.openqa.selenium.server.htmlrunner.HTMLLauncher ma
inInt
警告: Test of browser failed: *firefox
java.lang.RuntimeException: Unable to find suite table: <html lang="en"><head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="/assets/displayhelpservlet.css" m
edia="all">
  <script src="/assets/jquery-1.6.1.min.js" type="text/javascript"></script>
  <script src="/assets/displayhelpservlet.js" type="text/javascript"></script>
  <script type="text/javascript">
    var json = Object.freeze('{"version":"3.0.1","type":"Standalone","consoleLin
k":"/wd/hub"}');
  </script>
<title>Selenium Standalone v.3.0.1</title></head>
<body>

<div id="content">
  <div id="help-heading">
    <h1><span id="logo"></span></h1>
    <h2>Selenium <span class="se-type">Standalone</span>&nbsp;v.<span class="se-
version">3.0.1</span></h2>
  </div>
  ...
```

I put my suite, related test files (htmls), geckodriver, standalone server jar and html runner jar in same directory. 

Questions:

- Where should I put my suite and related test files so the html-runner could find and run them successfully?

- Or if there exist any mistakes in my steps, please let me know so I can correct it

Thanks for the spent time and patient in advance. 

## Ps :
My previous commands and the following address already used error message:

Only run html-runner with the command:
`java -jar "D:\JAVA\selenium-java-3.0.1\selenium-html-runner-3.0.1.jar" -htmlSuite "*firefox" http://targetwebpage "D:\JAVA\selenium-java-3.0.1\mySuite.html" "D:\JAVA\selenium-java-3.0.1\result"`

Address already in use error message:
```
2017-02-06 17:03:29.788:INFO:osjs.Server:main: Started @2821ms
2017-02-06 17:03:29.790:INFO:osjs.ServerConnector:main: Stopped ServerConnector@
49e53c76{HTTP/1.1}{0.0.0.0:26580}
2017-02-06 17:03:29.791:INFO:osjsh.ContextHandler:main: Stopped o.s.j.s.h.Contex
tHandler@52e6fdee{/tests,null,UNAVAILABLE}
[Child 2264] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave
/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056

二月 06, 2017 5:03:31 下午 org.openqa.selenium.os.UnixProcess destroy
嚴重: Unable to kill process with PID 12128
二月 06, 2017 5:03:31 下午 org.openqa.selenium.server.htmlrunner.HTMLLauncher ma
inInt
警告: Test of browser failed: *firefox
java.io.IOException: java.lang.RuntimeException: java.net.BindException: Address
 already in use: JVM_Bind
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.determineSuiteUrl(
HTMLLauncher.java:180)
        at org.openqa.selenium.server.htmlrunnerHTMLLauncher.runHTMLSuite(HTMLL
auncher.java:108)
        at org.openqa.selenium.server.htmlrunner.HTMLLaun>her.mainInt(HTMLLaunch
er.java:245)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.
java:273)
Caused by: java.lang.RuntimeException: java.net.BindException: Address already i
n use: JVM_Bind
        at org.openqa.selenium.net.PortProber.pollPort(PortProber.java:154)
        at org.openqa.selenium.net.PortProber.pollPort(PortProber.java:137)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.determineSuiteUrl(
HTMLLauncher.java:174)
        ... 3 more
Caused by: java.net.BindException: Address already in use: JVM_Bind
```

## Steps to reproduce -

- put suite, all test files, geckodriver, standalone server and html runner in same directory
  [http://imgur.com/a/ojOA1](http://imgur.com/a/ojOA1)

- launch the standalone server
  [http://imgur.com/a/Wv6Ze](http://imgur.com/a/Wv6Ze)

- run the html-runner command (in another terminal)

**Comment by barancev** [comment] 2017-08-02 10:36
First reported issue is related to a wrong path (Selenium can't run a suite by URL).
Second reported issue is a duplicate of #2978.

**Closed by barancev** 2017-08-02 10:36 UTC
