### ISSUE TITLE
SafariDriver should implement requireWindowFocus capability similar to IE 

### ISSUE THREAD

**Issue by SamuraiJack** [SeleniumHQ/selenium#1052] opened 2015-09-18 07:01 UTC
I've noticed, that Safari driver opens the browser window behind the other opened windows. 

Launched this way, Safari does not have focus, which leads to certain problems in the test. 

Notably, the CSS queries with ":focus" modifier does not return any element and because of that some of our tests fails. 

This behaviour does not match the behaviour of other webdrivers on mac - Chrome and Firefox windows are brought by their drivers to the front. It should be an easy fix I assume, the workaround is described in this (prematurely closed) ticket: https://code.google.com/p/selenium/issues/detail?id=4801

**Comment by lukeis** [comment] 2015-09-18 15:47
Please provide a reproducible test case for us where the :focus does not work. Note that we may never be able to handle this because the Safari Driver works with pure synthetic JavaScript events. 

As for bringing the browser into the foreground, this is not a requirement of webdriver and shouldn't be. The drivers are expected to behave the same in the background or foreground. But there are cases where it may be necessary, so I'll leave this bug open only to implement the Require Window Focus capability that IEDriver implements.

**Comment by SamuraiJack** [comment] 2015-09-19 07:07
Thank you, I'll prepare a reproducible test case for you soon.

**Comment by SamuraiJack** [comment] 2016-08-03 09:34
Here's a test case. Basically the ":focus" selector does not work when browser is in background state.

This is a browser behavior, not a webdriver, so, at least for Safari, the concept "drivers are expected to behave the same in the background or foreground" is physically not possible.

```
var webdriver = require('selenium-webdriver')

var builder = new webdriver.Builder()
    .forBrowser('safari')

var driver = builder.build();
    
driver.get('http://google.com');

driver.executeScript(function () {
    var queryWithoutFocus   = document.querySelectorAll("input[type=text]")
    var queryWithFocus      = document.querySelectorAll("input[type=text]:focus")
    
    return JSON.stringify({ withFocus : queryWithFocus.length, withoutFocus : queryWithoutFocus.length })
}).then(function (res) {
    console.log(res)
})

driver.quit()
```

**Comment by lukeis** [comment] 2016-09-23 20:17
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.

**Closed by lukeis** 2016-09-23 20:17 UTC
Labels: A-needs new owner, D-safari
