### ISSUE TITLE
Unable to tap webElement in Chrome Mobile Emulation ( org.openqa.selenium.UnsupportedCommandException: touchSingleTap)

### ISSUE THREAD

**Issue by makenshikuro** [SeleniumHQ/selenium#7920] opened 2020-01-09 11:19 UTC
## 🐛 Bug Report

When the Chrome browser with mobile emulation is enabled, the TouchActions don't work propertly. Selenium throws the next exception:

```
org.openqa.selenium.UnsupportedCommandException: touchDoubleTap
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-C8PO3TV', ip: '192.168.193.7', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
Driver info: driver.version: RemoteWebDriver
```
or
```
org.openqa.selenium.UnsupportedCommandException: touchSingleTap
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-C8PO3TV', ip: '192.168.193.7', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
Driver info: driver.version: RemoteWebDriver
```
with this StackTrace:

```
at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:218)
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:117)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:152)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteTouchScreen.singleTap(RemoteTouchScreen.java:36)
	at org.openqa.selenium.interactions.touch.SingleTapAction.perform(SingleTapAction.java:36)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:34)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:634)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:595)
```

## To Reproduce

1. Open browser with ChromeDriver in Mobile Emulation 
2. Navigate to URL
3. Tap element

## Expected behavior

The WebElement ("weButton" in this case), should be tapped.

## Test script or set of commands reproducing this issue

```
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.touch.TouchActions;
import org.testng.annotations.Test;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

public class ChromeMobileTest {
    @Test
    public void testGoogleSearch() throws InterruptedException{
        System.setProperty("webdriver.chrome.verboseLogging", "false");
        System.setProperty("webdriver.chrome.driver", ".\chromedriver.exe");

        String browserType = "chrome";
        String browserId = "Mozilla/5.0 (Linux; Android 7.0; SM-G930V Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.3";
        Optional<String> browserIdString = Optional.ofNullable(browserId).filter(s -> !s.isEmpty());

        ChromeOptions options = new ChromeOptions();
        browserIdString.ifPresent(idString -> options.addArguments(String.format("--user-agent=%s", idString)));
        options.addArguments("--ignore-certificate-errors");

        Map<String, Object> mobileEmulation = new HashMap<>();
        mobileEmulation.put("deviceName", "Nexus 5");
        options.setExperimentalOption("mobileEmulation", mobileEmulation);

        WebDriver driver = new ChromeDriver(options);
        driver.get("http://www.google.com/");
        Thread.sleep(5000);

        WebElement weButton = driver.findElement(By.cssSelector("button.Tg7LZd"));
        WebElement weSearchBar = driver.findElement(By.name("q"));
        weSearchBar.sendKeys("ChromeDriver");

        TouchActions tapAction = new TouchActions(driver);
        tapAction.singleTap(weButton);
        tapAction.perform();

        Thread.sleep(5000);
        driver.quit();
    }
}

```

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 79.0.3945.117
Browser Driver version: ChromeDriver 79.0.3945.36
Language Bindings version: Java 8 
Selenium Grid version: 3.141.59

**Comment by pujagani** [comment] 2021-03-30 08:09
Thank you for sharing the details. I was able to reproduce it for Selenium 3.141.59. However, the issue is fixed in the latest version of Selenium. Please use the latest Beta-2 bindings. https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.0.0-beta-2

**Comment by makenshikuro** [comment] 2021-03-30 08:33
Hi. Thank you for all! ^^

**Closed** 2021-03-30 08:33 UTC
Labels: C-java
