### ISSUE TITLE
[🐛 Bug]: Method register() in HasAuthentication interface not working as expected on Linux/Chrome

### ISSUE THREAD

**Issue by koko89kt** [SeleniumHQ/selenium#9968] opened 2021-10-21 14:58 UTC
### What happened?

Using register() method from HasAuthentication interface in Java 16 not working as expected on Chrome on Linux. Everything looks fine on Chrome for Windows.

It seems that if you passing credentials like:

((HasAuthentication) driver).register(UsernameAndPassword.of("username123", "password123"));

it will always pass the same (the first one) parameter for username and password, so in my example username will be set to "username123" and password will be set to "username123" as well.

### How can we reproduce the issue?

Execute register() method on any web application that requires authentication through authentication pop-up.
```shell
((HasAuthentication) driver).register(UsernameAndPassword.of("username123", "password123"));

```

In a case where username and password are the same, everything will work fine.

### Relevant log output

Currently unable to log this problem on relevant environment (Chrome in Linux Docker image)

### Operating System

Linux/amd64 under Docker image (markhobson/maven-chrome:jdk-16)

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 93

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 93.0.4577.63

**Comment by koko89kt** [comment] 2021-10-21 15:12
Please note that problem is mentioned here as well:
https://pl.euro-linux.com/blog/statyczne-testy-interfejsu-graficznego-przy-uzyciu-junit-selenium-i-ashot-na-przykladzie-euroap/#pll_switcher

(translate from Polish to English)

**Comment by koko89kt** [comment] 2021-10-22 06:45
@AutomatedTester - please note that problem occurs in Java, not in .NET.
Thank you.

**Comment by pujagani** [comment] 2021-10-28 12:58
Thank you for providing the details. I went over the code and nothing seems to be glaringly problematic. Apologies if I missed something while checking the code.
I first attempted to recreate the issue using the local ChromeDriver running on my machine (MacOs, Big Sur 11.4, Java 16). Then I attempted to recreate the issue by using the Grid in a Hub-Node mode using our docker images. I used https://github.com/SeleniumHQ/docker-selenium/blob/trunk/docker-compose-v3.yml  to spawn the Grid locally.  After running the example shared below I am unable to reproduce it. 

```
public class ChromeDevToolsAugmenterAuthenticationHttpBin {

  public static void main(String[] args) throws MalformedURLException, InterruptedException {
    ChromeOptions chromeOptions = new ChromeOptions();
    WebDriver driver = RemoteWebDriver.builder()
      .oneOf(chromeOptions)
      .address("http://localhost:4444")
      .build();

    DevTools devTools = ((HasDevTools) driver).getDevTools();
    devTools.createSession();

    Augmenter augmenter = new Augmenter();

    driver = augmenter
      .addDriverAugmentation("chrome",
                             HasAuthentication.class,
                             (caps, exec) -> (whenThisMatches, useTheseCredentials) ->
                               devTools.getDomains()
                                 .network()
                                 .addAuthHandler(whenThisMatches, useTheseCredentials))
      .augment(driver);

    ((HasAuthentication) driver).register(UsernameAndPassword.of("foo", "bar"));

    driver.get("http://httpbin.org/basic-auth/foo/bar");

    String pageSource = driver.getPageSource();

    if(pageSource.contains("authenticated")) {
      System.out.println("True");
    } else {
      System.out.println("False");
    }
    driver.quit();
  }
}
```
I have looked at the docker image that you shared but was unable to see the demo maven repo it mentions. The link keeps directing me to the docker image download page. I would really appreciate it you could share a reproducible test script/project setup. Thank you!

**Comment by diemol** [comment] 2021-12-01 15:43
Closing this issue as we didn't get a reply from the original poster. 

If someone is facing this issue, feel free to comment and provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

If you have any questions or need help, join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well.

**Closed as completed by diemol** 2021-12-01 15:43 UTC
Labels: C-java, I-defect
