### ISSUE TITLE
Unable to click at a specific position in a chart or on a canvas starting with selenium 3.5

### ISSUE THREAD

**Issue by eusebiuplosnita** [SeleniumHQ/selenium#6572] opened 2018-10-24 11:14 UTC
OS:  Windows 7, 10
Selenium Version:  3.5+
Browser:  Chrome

We have an issue with the latest selenium server version, starting with 3.5. We can reproduce the issue when we try to interact with a chart or a canvas. So to identify the elements in a canvas and a chart we get a json from the client side that specifies the coordinates of the element and based on those we move the mouse to the element and click on it. This works perfectly with selenium-server 3.4 but if we try to upgrade the version all tests that are trying to interact with a chart and a canvas start failing. I've tried all the chromedriver versions and the issue is not related to the browser or the driver. Also, I don't get any error in the selenium console, by clicking on an element in a chart or canvas we should be able to see a new dialog and the tests are failing because the dialog is not visible.

**Comment by diemol** [comment] 2018-10-24 16:08
Hi @eusebiuplosnita, why did you delete the issue template? Without that no one can help since there is no valuable info provided.

Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by barancev** [comment] 2018-12-10 11:02
Closing the issue as there is no reproduction scenario provided.

**Closed by barancev** 2018-12-10 11:02 UTC
Labels: R-awaiting answer
