### ISSUE TITLE
driver.switchTo.activeElement() throws ClassCast exception (IE 10 & 11 especially, 32 bit IEDriver)

### ISSUE THREAD

**Issue by irileydev** [SeleniumHQ/selenium#1759] opened 2016-03-07 18:09 UTC
## Expected Behavior -

Calls  of the driver.switchTo().activeElement() variety should be seamless
## Steps to reproduce -

**Summary-**
Calls to driver.switchTo.activeElement() throws ClassCastExceptions

**Setup**
WebDriver Java Bindings 2.52.0
Affected Browsers: IE10 & 11 primarily (IEDriver 32 bit)

Attempts to switch to a modal using the call "driver.switchTo().activeElement();" throws the ClassCast Exception. Code snippet ...:

clickElement(driver, xButton); // which is really a call to driver.findElement(By) wrapped with a WebDriverWait
driver.switchTo().activeElement();
## Actual Behavior -

After the call to switch to the modal, we get:

java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to org.openqa.selenium.WebElement
at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.activeElement(RemoteWebDriver.java:1045)
at com.automatedTesting.redesigned.pageObjects.NotesModal.closeNotesModal(NotesModal.java:87)
at com.automatedTesting.redesigned.testcases.Notes_testAddAcknowledgeButtonPresence.assertAddAcknowledgeBtnAbsence(Notes_testAddAcknowledgeButtonPresence.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

**Comment by barancev** [comment] 2017-08-23 10:06
I understand that we're too late, but...

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by barancev** [comment] 2017-09-06 07:00
Closing the issue, let's suppose the issue has been fixed because there are no other bug reports on this command.

**Closed by barancev** 2017-09-06 07:00 UTC
Labels: C-java, C-server, D-IE, R-awaiting answer
