### ISSUE TITLE
drop not working

### ISSUE THREAD

**Issue by iamkabulov** [SeleniumHQ/selenium#9004] opened 2020-12-28 09:18 UTC
## 🐛 Bug Report

Not dropping element to destination.

## To Reproduce

**1. Record test in selenium IDE
2. Then save .side file
3. After run in CL selenium-side-runner**

> NOTE: Tried to run test in pytest and NUnit C# there is the same problem.

## Expected behavior
I put two console.log() with messages "drag begins" and "drag end" on each event respectively. So when testing by console, it shows nothing, but in log we can see that test passed.

## Test script or set of commands reproducing this issue
```
{
  "id": "81bf1079-9a17-40f4-8388-71ed9634f9a8",
  "version": "2.0",
  "name": "dnd",
  "url": "https://codesandbox.io/s/great-montalcini-8cs99",
  "tests": [{
    "id": "7b7ed6d6-bdfd-435a-a227-4384f261cae8",
    "name": "dnd",
    "commands": [{
      "id": "66ac3b45-e9dc-44a6-b350-f7bda3e197a9",
      "comment": "",
      "command": "open",
      "target": "https://codesandbox.io/s/great-montalcini-8cs99",
      "targets": [],
      "value": ""
    }, {
      "id": "e423e5db-dbef-4ac0-9f26-f59a4ef30fda",
      "comment": "",
      "command": "setWindowSize",
      "target": "1552x840",
      "targets": [],
      "value": ""
    }, {
      "id": "0320ee04-5fbd-4d7b-9805-1eeae80f7945",
      "comment": "",
      "command": "selectFrame",
      "target": "index=0",
      "targets": [
        ["index=0"]
      ],
      "value": ""
    }, {
      "id": "5fbedec6-4dc9-4acb-8759-3f76b038d226",
      "comment": "",
      "command": "dragAndDropToObject",
      "target": "xpath=//div[@id='root']/div/div/div/div/div/div/div/table/tbody/tr/td",
      "targets": [
        ["css=.ant-table-row:nth-child(1) > td:nth-child(1)", "css:finder"],
        ["xpath=//div[@id='root']/div/div/div/div/div/div/div/table/tbody/tr/td", "xpath:idRelative"],
        ["xpath=//td", "xpath:position"],
        ["xpath=//td[contains(.,'Alice')]", "xpath:innerText"]
      ],
      "value": "css=.ant-table-row:nth-child(2) > td:nth-child(1)"
    }, {
      "id": "383c54e0-f6ae-4779-9d15-82b1aec42d44",
      "comment": "",
      "command": "pause",
      "target": "15000",
      "targets": [],
      "value": ""
    }, {
      "id": "202779fe-ae81-4cf9-a5f2-873735276158",
      "comment": "",
      "command": "close",
      "target": "",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "1530b2aa-2bed-4593-ab65-fe5313c340a5",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["7b7ed6d6-bdfd-435a-a227-4384f261cae8"]
  }],
  "urls": ["https://codesandbox.io/s/great-montalcini-8cs99"],
  "plugins": []
}
```

## Environment

OS: Windows 10 64x
Browser: Chrome
Browser version: 87.0.4280.88
Browser Driver version: ChromeDriver 87.0.4280.88
Selenium-side-runner v 3.17.0

**Comment by diemol** [comment] 2020-12-28 19:33
Where can I see the `console.log()` statement? 
Is the problem that the exported code from the IDE does not do what you expect?

**Comment by iamkabulov** [comment] 2020-12-29 06:14
> Where can I see the `console.log()` statement?
> Is the problem that the exported code from the IDE does not do what you expect?

yeah, and it is strange that test does not fail. it reports passed

**Comment by iamkabulov** [comment] 2020-12-29 06:16
in console 

> Where can I see the `console.log()` statement?
> Is the problem that the exported code from the IDE does not do what you expect?

in console. For it you need to open developer tool

**Comment by diemol** [comment] 2020-12-29 07:43
I am still confused. You mention at the beginning that you put two `console.log()` statements, where did you put them?

And if I understand correctly, the issue is with the exported code from the IDE. So this issue should be placed in the IDE repo. Is that right?

**Comment by iamkabulov** [comment] 2020-12-29 09:25
> I am still confused. You mention at the beginning that you put two `console.log()` statements, where did you put them?
> 
> And if I understand correctly, the issue is with the exported code from the IDE. So this issue should be placed in the IDE repo. Is that right?

In front-end. I put 2 console.log() in order to understand what is wrong. when you are starting drag in console, you can see the message "drag begins". After dropping element also in console will be message "drag end".

I want to say that drop function is invalid, cause I don't receive these messages. When I make it manually it works well.

**Comment by diemol** [comment] 2020-12-29 10:15
Does it work well when you play the SIDE file in the Selenium IDE?

**Comment by iamkabulov** [comment] 2020-12-29 10:22
> Does it work well when you play the SIDE file in the Selenium IDE?

yeah.

**Comment by mercurial20** [comment] 2020-12-30 05:28
> Does it work well when you play the SIDE file in the Selenium IDE?

Yes, playing SIDE works with Selenium IDE.
React-dnd is used for drag and drop.
We exported side code to python and run with pytest. It does not work. It begins dragging (shows hover color), but it doesn't drop. We placed console.log() on events drag and drop, to see where is the problem. And as we thought it doesn't fire drop event. 
![image](https://user-images.githubusercontent.com/46921335/103331666-223bf480-4a91-11eb-8634-24f0dff547a0.png).

We added js script to see if it works, and it worked :) It will be awesome to test drag and drop without external js script.
Sorry for poor English, not a native speaker.
Codesandbox link : https://codesandbox.io/s/great-montalcini-8cs99 .

**Comment by diemol** [comment] 2021-01-07 16:51
No need to say sorry, English is not my native language either :)

It is know that the code export of the IDE is not perfect and due to some limitations, for now, the code exported sometimes needs to be adjusted for your needs. Please think of the IDE as something that can help you started and get you an automation script, but depending on the complexity of the recorded test, some adjustments might be needed.

If you need some help on adjusting the script, feel free to drop by our Slack/IRC channel, check the links here https://www.selenium.dev/support/.

I will close this issue as it is not an issue with Selenium WebDriver itself, but a further improvement that could be done in the Selenium IDE.

**Closed as completed by diemol** 2021-01-07 16:51 UTC
Labels: J-awaiting answer
