### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by paul11123** [SeleniumHQ/selenium#12896] opened 2023-10-07 13:11 UTC
### What happened?

I am Webscaping with scrapy in python 3.11.5. It is a general (normal/default spider)
I use anaconda for virtual environments. Selenium and Selenium manager is installed (channel: conda-forge)

### How can we reproduce the issue?

```shell
I am scraping amazon. To reproduce the scraping of amazon you need a Header rotation and a proxy which I think is too much to ask, so scraping a normal scrap-website is enough.
```

### Relevant log output

```shell
scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.amazon.de/gp/bestsellers/lighting/165179011/ref=pd_zg_hrsr_lighting> (referer: None)
2023-10-07 15:00:04 [selenium.webdriver.common.driver_finder] WARNING: Unable to obtain driver using Selenium Manager: /home/user/anaconda3/envs/webscaping/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager is missing.  Please open an issue on https://github.com/SeleniumHQ/selenium/issues
2023-10-07 15:00:04 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.amazon.de/gp/bestsellers/lighting/165179011/ref=pd_zg_hrsr_lighting> (referer: None)
Traceback (most recent call last):

....

File "/home/user/anaconda3/envs/webscaping/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 61, in get_binary
    raise SeleniumManagerException(f"{path} is missing.  Please open an issue on {tracker}")
selenium.common.exceptions.SeleniumManagerException: Message: /home/user/anaconda3/envs/webscaping/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager is missing.  Please open an issue on https://github.com/SeleniumHQ/selenium/issues
```

### Operating System

Ubunut 22.04 LTS

### Selenium version

selenium  4.9.0   selenium-manager 4.13.0 selenium-requests   1.3 

### What are the browser(s) and version(s) where you see this issue?

every browser

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver-v0.33.0-linux64

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment] 2023-10-07 13:48
Duplicate of #11980
Update to the latest version of Selenium.

**Closed as not planned by titusfortner** 2023-10-07 13:48 UTC
Labels: I-defect, A-needs-triaging
