### ISSUE TITLE
Driver not locating element with certain xpaths

### ISSUE THREAD

**Issue by MarioStoilov** [SeleniumHQ/selenium#2502] opened 2016-07-21 11:51 UTC
## Meta -
OS:  
OS X 10.11.6
Selenium Version:  
2.53.4
Browser:  
Chrome  51.0.2704.106 (64-bit)

## Steps to reproduce -
Use this html:

```
<tr id="element.checkbox_container_f5f86d3c37f06e005f4963d2b3990e5a" name="checkbox_container" style="">
<td class="iotd">
<div class="row sc-row">
<div id="variable_IO:50b58506254216808fa60643fcf6b609" class="form-group sc-row">
<fieldset>
<input id="sys_original.IO:50b58506254216808fa60643fcf6b609" class="cat_item_option" type="HIDDEN" name="sys_original.IO:50b58506254216808fa60643fcf6b609" container_id="f5f86d3c37f06e005f4963d2b3990e5a"/>
<div id="label_IO:50b58506254216808fa60643fcf6b609" name="checkbox_container_label" nowrap="true" oncontextmenu="return contextQuestionLabel(event, '50b58506254216808fa60643fcf6b609');">
<legend class="col-xs-12 control-label" for="IO:c346a79125c6d2808fa60643fcf6b61d">
<span id="status.IO:50b58506254216808fa60643fcf6b609" class="changed required-marker label_description required-marker label_description" mandatory="false" aria-label="" title="" oclass="changed required-marker label_description required-marker label_description" data-original-title=""/>
<img id="section508.IO:50b58506254216808fa60643fcf6b609" style="width:1px; margin-right:0px; margin-left:0px" src="images/s.gifx" title="" data-original-title=""/>
<span class="sn-tooltip-basic" data-toggle="tooltip" data-placement="auto" data-original-title="" title="">What client is the user using?</span>
</legend>
</div>
<div class="io_table col-xs-6 form-field input_controls">
</fieldset>
</div>
</div>
</td>
</tr>
```

Use this ruby code:
```
field_full_question_xpath = './/tr[@id=\'element.checkbox_container_f5f86d3c37f06e005f4963d2b3990e5a\']/td//div/div//*[contains(@class, \'control-label\')]/span[2]'
driver.find_element(:xpath, field_full_question_xpath).text
```

get this error:

> Selenium::WebDriver::Error::NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":".//tr[@id='element.checkbox_container_f5f86d3c37f06e005f4963d2b3990e5a']/td//div/div//*[contains(@class, 'control-label')]/span[2]"}
>   (Session info: chrome=51.0.2704.106)
>   (Driver info: chromedriver=2.22.397929 (fb72fb249a903a0b1041ea71eb4c8b3fa0d9be5a),platform=Mac OS X 10.11.6 x86_64)

xpath tested with external tool (firepath) on the same html and works. It also works in other html snippets, will give them here if required (they are a little big).

**Comment by lukeis** [comment] 2016-07-21 14:37
this is not a bug... your xpath is horrendous, the spans inside your 'control-label' are actually nested so instead of /span[2] it's really /span/span   because the first span isn't closed with </span> The markup show's the author attempting to self-close a span with:
    <span ... />

This is not valid HTML markup, only ["void elements"](https://www.w3.org/TR/html5/syntax.html#void-elements) are allowed to be self-closing.

Because of this it seems you've encountered a browser quirk, where chrome doesn't respect the self-closing tag, yet firefox does. Changing the xpath for chrome is an option, or having the author of the application you're executing against provide valid markup is another :)

**Closed by lukeis** 2016-07-21 14:37 UTC

**Comment by MarioStoilov** [comment] 2016-07-21 14:51
Those self-closing tags are the result of the smart-ass "copy HTML" function of the browser, they are actually closed as they should (i.e. <span></span>), will edit it later when I can (the whole document is far too large to be a viable option).

I know the xpath is horrendous, but it can't any other way (trust me on that), neither is that the point here. The app is not in my control, and most of the html is dynamically generated.

**Comment by lukeis** [comment] 2016-07-21 15:03
use something like jsfiddle.net to provide an accurate DOM example, otherwise I can't reproduce any actual issue here

**Comment by MarioStoilov** [comment] 2016-07-21 15:10
Edited the main post (cut out some unnecessary stuff)

**Comment by lukeis** [comment] 2016-07-21 15:18
that's now just very invalid html... please create and then link an example using jsfiddle.net

**Comment by MarioStoilov** [comment] 2016-07-21 15:39
Alright, linking it.

**Comment by lukeis** [comment] 2016-07-21 16:04
so.. umm.. that works for me :)  (python, what i'm used to, but basically the same as ruby...)

    from selenium import webdriver as w
    d = w.Chrome()
    d.get("https://jsfiddle.net/rk8acdg4/")
    d.switch_to.frame(d.find_element_by_css_selector("#result iframe"))
    d.find_element_by_xpath('.//tr[@id=\'element.checkbox_container_f5f86d3c37f06e005f4963d2b3990e5a\']/td//div/div//*[contains(@class, \'control-label\')]/span[2]')
    <selenium.webdriver.remote.webelement.WebElement (session="b7265ce8c1369cfc966b9ea6b87ee5fd", element="0.3914036223786215-1")>

**Comment by MarioStoilov** [comment] 2016-07-21 18:37
Hm, strange. I'm not on my work machine atm, but will look if I missed anything asap. For now, all I can provide is a glance at what the real html looks like (atachement), but that shouldn't be affecting the result
![capture](https://cloud.githubusercontent.com/assets/3836061/17034431/579e2d1a-4f8b-11e6-80c0-c902d090441d.PNG)

**Comment by MarioStoilov** [comment] 2016-07-22 07:11
Ok, discard this, turns out that app discriminated users and generates different container ids for different users.
