### ISSUE TITLE
[🐛 Bug]: Edge IE Mode - org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by kurpt** [SeleniumHQ/selenium#10824] opened 2022-06-28 15:18 UTC
### What happened?

Facing Timeout issue with Edge - IE Mode automation with needed configuration. 

- Using 32 bit driver and made below updates to registry 
For 32-bit Windows, the key is at HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE .

Able to open the browser but getting timeout issue with driver.navigate (url);

### How can we reproduce the issue?

```shell
System.setProperty("webdriver.ie.driver",System.getProperty("user.dir") + "/drivers/IEDriverServer.exe");
InternetExplorerOptions edgeIe11Options = new InternetExplorerOptions();
					Map<String, Object> ops = (Map<String, Object>) edgeIe11Options.getCapability("se:ieOptions");
					ops.put("ie.edgechromium", true);
					ops.put("ie.edgepath", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");     // Edge Browser directory path

					edgeIe11Options.introduceFlakinessByIgnoringSecurityDomains();
					edgeIe11Options.ignoreZoomSettings();
					edgeIe11Options.enablePersistentHovering();
					edgeIe11Options.takeFullPageScreenshot();
					edgeIe11Options.disableNativeEvents();
					edgeIe11Options.requireWindowFocus();
					edgeIe11Options.destructivelyEnsureCleanSession();
			edgeIe11Options.setUnhandledPromptBehaviour(UnexpectedAlertBehaviour.ACCEPT);
					driver = new InternetExplorerDriver(edgeIe11Options);
```

### Relevant log output

```shell
org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.3.0', revision: 'a4995e2c09*'

Capabilities {acceptInsecureCerts: false, browserName: internet explorer, browserVersion: 11, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enablePersistentHover: false, ie.browserCommandLineSwitches: , ie.edgechromium: true, ie.edgepath: C:\Program Files (x86)\Micr..., ie.ensureCleanSession: true, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ignoreProtectedModeSettings: true, ignoreZoomSetting: true, initialBrowserUrl: http://localhost:60629/, nativeEvents: false, requireWindowFocus: true}, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept}
```

### Operating System

Windows 10

### Selenium version

4.3.0

### What are the browser(s) and version(s) where you see this issue?

Edge - 103.0.1264.37 

### What are the browser driver(s) and version(s) where you see this issue?

IE Driver - 4.2.0.0

### Are you using Selenium Grid?

N

**Comment by diemol** [comment] 2022-06-28 15:43
This seems like a duplicate of https://github.com/SeleniumHQ/selenium/issues/10497, can you please check the links in that issue, check your settings and share them here?

**Comment by sathiyakumars2308** [comment] 2022-06-30 12:49
Iedriverserver 4.0,0.0 works good  in "edge in ie mode" till the edge version 102.0.1245.39 . (Configurations of IE11 is intact with setting provided in "https://www.selenium.dev/documentation/ie_driver_server/")

But now, after Edge is automatically updated with version 103.0.1264.37 ,  unable to get any property of driver once application launched . example unable to get window handle . Due to this issue, browser closed immediately once it is launched with application first page , with out doing any action which supposed to do .

Hence upgraded the IEDriverserver to 4.2.0.0 , with same IE11 configuration . But getting timeout error after 60 seconds in Initial start up page itself .

**Log  for IEDriverserver 4.2.0.0 with edge version 103.0.1264.37** (Selenium with C#)
 OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:63155/session timed out after 60 seconds. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
![Timeout error](https://user-images.githubusercontent.com/108467810/176677458-1d804839-6aab-449e-ae8b-66e199db602e.png)

**Comment by titusfortner** [comment] 2022-07-05 19:24
I was able to duplicate this, and there's nothing we can do in the Selenium code. I opened that ticket with EdgeWebDriver to track it.

**Closed as completed by titusfortner** 2022-07-05 19:24 UTC
Labels: J-awaiting answer, I-defect
