### ISSUE TITLE
HTTP Basic Authentication with Selenium Remote Webdriver Issue in Linux with Firefox and Python

### ISSUE THREAD

**Issue by umeshchhabra** [SeleniumHQ/selenium#3057] opened 2016-11-03 20:21 UTC
To bypass the basic http authentication dialog, I am construction URL as mentioned in the previous posts i.e.

http://username:pwd@domain.com/ or
http://username:pwd@domain.com

Here is the configuration I am using:

Selenium Server:            v2.53.1 O/S Linux
Node 1:                          Linux Mint / Firefox v48
Node 2:                          Linux Mint / Firefox v45.4
Node 3:                          Windows 7 / Firefox v49.0.1
Python 2.7

**At no time, I am running more than 1 node.**

From the above configurations, **Only Windows 7 is working**; the **Firefox on Linux mint is not bypassing the authentication dialog**.

I understand that the website under test is using basic http auth but still I have tried the following options in the Firefox PROFILE too:

self.fp.set_preference("signon.autologin.proxy", True)
self.fp.set_preference("network.automatic-ntlm-auth.trusted-uris", "http://%s.domainname.com" %(self.applicationName))
self.fp.set_preference("network.automatic-ntlm-auth.allow-non-fqdn", True)
self.fp.set_preference("network.negotiate-auth.delegation-uris", "http://%s.domainname.com" %(self.applicationName))
self.fp.set_preference("network.negotiate-auth.trusted-uris", "http://%s.domainname.com" %(self.applicationName))
self.fp.set_preference("network.http.phishy-userpass-length", 255)
self.fp.set_preference("security.csp.enable", False)

Just wanted to understand if this is a known issue or I need to do some settings on my Linux mint and Firefox.

Another thing I want to mention here. Once the URL is opened and auth dialog is displayed, I am not able to type anything in the user name or password field but I am able to click on the Login / Cancel buttons.

Please note: This is working fine with Standalone and Webdriver.

**Comment by lukeis** [comment] 2016-11-03 21:33
basic auth isn't technically supported yet.

see #453

closing this as a duplicate of that one.

Also, this is an issue tracker, if you have questions or are looking for support, ask on the selenium-users google group.

**Closed by lukeis** 2016-11-03 21:33 UTC
