### ISSUE TITLE
IEDriverServer 3.5.1 Typing 'à' instead of '@'

### ISSUE THREAD

**Issue by chenry35** [SeleniumHQ/selenium#4741] opened 2017-09-22 09:54 UTC
Hello

With the IEDriverServer 3.5.1 (32bits), im trying to input text with a email but the automate is typing 'à' instead of '@'.

I dont have the problem when im using a lower version than 3.5.

Im also using the last version of the selenium standalone server.

**Comment by jimevans** [comment] 2017-09-22 11:19
Duplicate of #4523

**Closed by jimevans** 2017-09-22 11:19 UTC
