### ISSUE TITLE
2.48 doesn't trigger javascript in link's href on click()

### ISSUE THREAD

**Issue by merike** [SeleniumHQ/selenium#1234] opened 2015-11-10 09:26 UTC
Please see https://drive.google.com/file/d/0Bzx3gCDqfzVdQUFoWHdzdWlFYVU/view?usp=sharing and https://drive.google.com/file/d/0Bzx3gCDqfzVdUmhhckFkWVFlbTQ/view?usp=sharing

The test case there alerts with 2.47.1 but not with 2.48.0 or 2.48.2. This is with Firefox 42.0 32bit on 64bit machine.

**Comment by doberkofler** [comment] 2015-11-23 06:05
+1

**Comment by barancev** [comment] 2016-01-25 21:08
Can't reproduce the issue with Selenium 2.49.1 and Firefox 43.0.4, please retest with the latest Selenium version.

**Comment by merike** [comment] 2016-02-01 11:52
Strange, for me 43.0.4 and 2.50.1 still don't trigger the alert. Wait.. except when Firefox is in the background. Why would it work differently when Firefox is the foreground application? Unless it's a reverse bug of #825?

**Comment by barancev** [comment] 2016-03-02 06:12
Closing the issue as there is no reproduction case provided.

**Closed by barancev** 2016-03-02 06:12 UTC
Labels: D-firefox, R-awaiting answer
