### ISSUE TITLE
[🐛 Bug]: Could not start a new session.

### ISSUE THREAD

**Issue by polRk** [SeleniumHQ/selenium#13183] opened 2023-11-21 22:22 UTC
### What happened?

I use helm chart and deploy selenium-grid as distributed service.

I created about 1_000_000 sessions in an hour and i see a lot of fails of `POST /session`

My setup:

selenium-grid-node-chrome | 800 of 800 pods

Selenium components version: 4.15.0-20231110

Traces

```json
{
    "data": [
        {
            "traceID": "4386b515fb4b20695620e6c7762fe367",
            "spans": [
                {
                    "traceID": "4386b515fb4b20695620e6c7762fe367",
                    "spanID": "6dfb70a703666bbe",
                    "operationName": "distributor.new_session",
                    "references": [
                        {
                            "refType": "CHILD_OF",
                            "traceID": "4386b515fb4b20695620e6c7762fe367",
                            "spanID": "2082b435ba597313"
                        }
                    ],
                    "startTime": 1700604706067150,
                    "duration": 67568,
                    "tags": [
                        {
                            "key": "otel.library.name",
                            "type": "string",
                            "value": "default"
                        },
                        {
                            "key": "error",
                            "type": "bool",
                            "value": true
                        },
                        {
                            "key": "span.kind",
                            "type": "string",
                            "value": "internal"
                        },
                        {
                            "key": "otel.status_code",
                            "type": "string",
                            "value": "ERROR"
                        },
                        {
                            "key": "error",
                            "type": "bool",
                            "value": true
                        },
                        {
                            "key": "otel.status_description",
                            "type": "string",
                            "value": "Kind: ABORTED Description:"
                        },
                        {
                            "key": "internal.span.format",
                            "type": "string",
                            "value": "proto"
                        }
                    ],
                    "logs": [
                        {
                            "timestamp": 1700604706067206,
                            "fields": [
                                {
                                    "key": "event",
                                    "type": "string",
                                    "value": "Session request received by the Distributor"
                                },
                                {
                                    "key": "logger",
                                    "type": "string",
                                    "value": "org.openqa.selenium.grid.distributor.local.LocalDistributor"
                                },
                                {
                                    "key": "request.payload",
                                    "type": "string",
                                    "value": "[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-field-trial-config, --disable-background-networ..., --enable-features=NetworkSe..., --disable-background-timer-..., --disable-backgrounding-occ..., --disable-back-forward-cache, --disable-breakpad, --disable-client-side-phish..., --disable-component-extensi..., --disable-component-update, --no-default-browser-check, --disable-default-apps, --disable-dev-shm-usage, --disable-extensions, --disable-features=Improved..., --allow-pre-commit-input, --disable-hang-monitor, --disable-ipc-flooding-prot..., --disable-popup-blocking, --disable-prompt-on-repost, --disable-renderer-backgrou..., --force-color-profile=srgb, --metrics-recording-only, --no-first-run, --enable-automation, --password-store=basic, --use-mock-keychain, --no-service-autorun, --export-tagged-pdf, --disable-search-engine-cho..., --headless, --hide-scrollbars, --mute-audio, --blink-settings=primaryHov..., --no-sandbox, -–headless=new, --force-device-scale-factor=1, --remote-debugging-port=0]}}]"
                                }
                            ]
                        },
                        {
                            "timestamp": 1700604706134712,
                            "fields": [
                                {
                                    "key": "event",
                                    "type": "string",
                                    "value": "exception"
                                },
                                {
                                    "key": "exception.message",
                                    "type": "string",
                                    "value": "Unable to create session: Could not start a new session. Could not start a new session. Unable to obtain: Capabilities {browserName: chrome, browserVersion: 119.0, goog:chromeOptions: {args: [--disable-field-trial-config, --disable-background-networ..., --enable-features=NetworkSe..., --disable-background-timer-..., --disable-backgrounding-occ..., --disable-back-forward-cache, --disable-breakpad, --disable-client-side-phish..., --disable-component-extensi..., --disable-component-update, --no-default-browser-check, --disable-default-apps, --disable-dev-shm-usage, --disable-extensions, --disable-features=Improved..., --allow-pre-commit-input, --disable-hang-monitor, --disable-ipc-flooding-prot..., --disable-popup-blocking, --disable-prompt-on-repost, --disable-renderer-backgrou..., --force-color-profile=srgb, --metrics-recording-only, --no-first-run, --enable-automation, --password-store=basic, --use-mock-keychain, --no-service-autorun, --export-tagged-pdf, --disable-search-engine-cho..., --headless, --hide-scrollbars, --mute-audio, --blink-settings=primaryHov..., --no-sandbox, -–headless=new, --force-device-scale-factor=1, --remote-debugging-port=0]}, platformName: linux, se:noVncPort: 7900, se:vncEnabled: true}, error Failed to parse json output, executed: [--browser, chrome, --output, json, --browser-version, 119.0]\n\nBuild info: version: '4.15.0', revision: '1d14b5521b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.0.12-300.fc37.x86_64', java.version: '11.0.20.1'\nDriver info: driver.version: unknown \nHost info: host: 'selenium-grid-node-chrome-8596449fc9-pxdh5', ip: '29.64.4.217'\nBuild info: version: '4.15.0', revision: '1d14b5521b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.0.12-300.fc37.x86_64', java.version: '11.0.20.1'\nDriver info: driver.version: unknown\nBuild info: version: '4.15.0', revision: '1d14b5521b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.0.12-300.fc37.x86_64', java.version: '11.0.20.1'\nDriver info: driver.version: unknown"
                                },
                                {
                                    "key": "exception.stacktrace",
                                    "type": "string",
                                    "value": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Could not start a new session. Unable to obtain: Capabilities {browserName: chrome, browserVersion: 119.0, goog:chromeOptions: {args: [--disable-field-trial-config, --disable-background-networ..., --enable-features=NetworkSe..., --disable-background-timer-..., --disable-backgrounding-occ..., --disable-back-forward-cache, --disable-breakpad, --disable-client-side-phish..., --disable-component-extensi..., --disable-component-update, --no-default-browser-check, --disable-default-apps, --disable-dev-shm-usage, --disable-extensions, --disable-features=Improved..., --allow-pre-commit-input, --disable-hang-monitor, --disable-ipc-flooding-prot..., --disable-popup-blocking, --disable-prompt-on-repost, --disable-renderer-backgrou..., --force-color-profile=srgb, --metrics-recording-only, --no-first-run, --enable-automation, --password-store=basic, --use-mock-keychain, --no-service-autorun, --export-tagged-pdf, --disable-search-engine-cho..., --headless, --hide-scrollbars, --mute-audio, --blink-settings=primaryHov..., --no-sandbox, -–headless=new, --force-device-scale-factor=1, --remote-debugging-port=0]}, platformName: linux, se:noVncPort: 7900, se:vncEnabled: true}, error Failed to parse json output, executed: [--browser, chrome, --output, json, --browser-version, 119.0]\n\nBuild info: version: '4.15.0', revision: '1d14b5521b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.0.12-300.fc37.x86_64', java.version: '11.0.20.1'\nDriver info: driver.version: unknown \nHost info: host: 'selenium-grid-node-chrome-8596449fc9-pxdh5', ip: '29.64.4.217'\nBuild info: version: '4.15.0', revision: '1d14b5521b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.0.12-300.fc37.x86_64', java.version: '11.0.20.1'\nDriver info: driver.version: unknown\nBuild info: version: '4.15.0', revision: '1d14b5521b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.0.12-300.fc37.x86_64', java.version: '11.0.20.1'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.node.remote.RemoteNode.newSession(RemoteNode.java:151)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:645)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:564)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:824)\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:784)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\n"
                                },
                                {
                                    "key": "exception.type",
                                    "type": "string",
                                    "value": "org.openqa.selenium.SessionNotCreatedException"
                                },
                                {
                                    "key": "logger",
                                    "type": "string",
                                    "value": "org.openqa.selenium.grid.distributor.local.LocalDistributor"
                                },
                                {
                                    "key": "request.payload",
                                    "type": "string",
                                    "value": "[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-field-trial-config, --disable-background-networ..., --enable-features=NetworkSe..., --disable-background-timer-..., --disable-backgrounding-occ..., --disable-back-forward-cache, --disable-breakpad, --disable-client-side-phish..., --disable-component-extensi..., --disable-component-update, --no-default-browser-check, --disable-default-apps, --disable-dev-shm-usage, --disable-extensions, --disable-features=Improved..., --allow-pre-commit-input, --disable-hang-monitor, --disable-ipc-flooding-prot..., --disable-popup-blocking, --disable-prompt-on-repost, --disable-renderer-backgrou..., --force-color-profile=srgb, --metrics-recording-only, --no-first-run, --enable-automation, --password-store=basic, --use-mock-keychain, --no-service-autorun, --export-tagged-pdf, --disable-search-engine-cho..., --headless, --hide-scrollbars, --mute-audio, --blink-settings=primaryHov..., --no-sandbox, -–headless=new, --force-device-scale-factor=1, --remote-debugging-port=0]}}]"
                                }
                            ]
                        }
                    ],
                    "processID": "p1",
                    "warnings": null
                },
                {
                    "traceID": "4386b515fb4b20695620e6c7762fe367",
                    "spanID": "2082b435ba597313",
                    "operationName": "distributor.poll_queue",
                    "references": [
                        {
                            "refType": "CHILD_OF",
                            "traceID": "4386b515fb4b20695620e6c7762fe367",
                            "spanID": "05e1ef9fbe82b066"
                        }
                    ],
                    "startTime": 1700604706067000,
                    "duration": 69952,
                    "tags": [
                        {
                            "key": "otel.library.name",
                            "type": "string",
                            "value": "default"
                        },
                        {
                            "key": "request.id",
                            "type": "string",
                            "value": "bff2c9d4-b1d0-45f5-86c1-9807df051da9"
                        },
                        {
                            "key": "span.kind",
                            "type": "string",
                            "value": "internal"
                        },
                        {
                            "key": "internal.span.format",
                            "type": "string",
                            "value": "proto"
                        }
                    ],
                    "logs": [],
                    "processID": "p1",
                    "warnings": null
                },
                {
                    "traceID": "4386b515fb4b20695620e6c7762fe367",
                    "spanID": "dd0ecbd4a53e1126",
                    "operationName": "httpclient.execute",
                    "references": [
                        {
                            "refType": "CHILD_OF",
                            "traceID": "4386b515fb4b20695620e6c7762fe367",
                            "spanID": "6dfb70a703666bbe"
                        }
                    ],
                    "startTime": 1700604706069000,
                    "duration": 64751,
                    "tags": [
                        {
                            "key": "otel.library.name",
                            "type": "string",
                            "value": "default"
                        },
                        {
                            "key": "http.method",
                            "type": "string",
                            "value": "POST"
                        },
                        {
                            "key": "http.status_code",
                            "type": "int64",
                            "value": 200
                        },
                        {
                            "key": "span.kind",
                            "type": "string",
                            "value": "client"
                        },
                        {
                            "key": "http.target",
                            "type": "string",
                            "value": "/se/grid/node/session"
                        },
                        {
                            "key": "span.kind",
                            "type": "string",
                            "value": "internal"
                        },
                        {
                            "key": "otel.status_code",
                            "type": "string",
                            "value": "OK"
                        },
                        {
                            "key": "otel.status_description",
                            "type": "string",
                            "value": "Kind: OK Description:"
                        },
                        {
                            "key": "internal.span.format",
                            "type": "string",
                            "value": "proto"
                        }
                    ],
                    "logs": [],
                    "processID": "p1",
                    "warnings": null
                },
                {
                    "traceID": "4386b515fb4b20695620e6c7762fe367",
                    "spanID": "ca1c9d591e33e036",
                    "operationName": "httpclient.execute",
                    "references": [
                        {
                            "refType": "CHILD_OF",
                            "traceID": "4386b515fb4b20695620e6c7762fe367",
                            "spanID": "2082b435ba597313"
                        }
                    ],
                    "startTime": 1700604706136000,
                    "duration": 1251,
                    "tags": [
                        {
                            "key": "otel.library.name",
                            "type": "string",
                            "value": "default"
                        },
                        {
                            "key": "http.method",
                            "type": "string",
                            "value": "POST"
                        },
                        {
                            "key": "http.status_code",
                            "type": "int64",
                            "value": 200
                        },
                        {
                            "key": "span.kind",
                            "type": "string",
                            "value": "client"
                        },
                        {
                            "key": "http.target",
                            "type": "string",
                            "value": "/se/grid/newsessionqueue/session/bff2c9d4-b1d0-45f5-86c1-9807df051da9/failure"
                        },
                        {
                            "key": "span.kind",
                            "type": "string",
                            "value": "internal"
                        },
                        {
                            "key": "otel.status_code",
                            "type": "string",
                            "value": "OK"
                        },
                        {
                            "key": "otel.status_description",
                            "type": "string",
                            "value": "Kind: OK Description:"
                        },
                        {
                            "key": "internal.span.format",
                            "type": "string",
                            "value": "proto"
                        }
                    ],
                    "logs": [],
                    "processID": "p1",
                    "warnings": [
                        "clock skew adjustment disabled; not applying calculated delta of -34.649643ms"
                    ]
                },
                {
                    "traceID": "4386b515fb4b20695620e6c7762fe367",
                    "spanID": "48e818abd8fdc41d",
                    "operationName": "sessionqueue.completed",
                    "references": [
                        {
                            "refType": "CHILD_OF",
                            "traceID": "4386b515fb4b20695620e6c7762fe367",
                            "spanID": "05e1ef9fbe82b066"
                        }
                    ],
                    "startTime": 1700604706136000,
                    "duration": 40,
                    "tags": [
                        {
                            "key": "otel.library.name",
                            "type": "string",
                            "value": "default"
                        },
                        {
                            "key": "span.kind",
                            "type": "string",
                            "value": "internal"
                        },
                        {
                            "key": "internal.span.format",
                            "type": "string",
                            "value": "proto"
                        }
                    ],
                    "logs": [],
                    "processID": "p2",
                    "warnings": null
                },
                {
                    "traceID": "4386b515fb4b20695620e6c7762fe367",
                    "spanID": "0f75511db0d76c43",
                    "operationName": "sessionqueue.created_bad",
                    "references": [
                        {
                            "refType": "CHILD_OF",
                            "traceID": "4386b515fb4b20695620e6c7762fe367",
                            "spanID": "ca1c9d591e33e036"
                        }
                    ],
                    "startTime": 1700604706136000,
                    "duration": 217,
                    "tags": [
                        {
                            "key": "otel.library.name",
                            "type": "string",
                            "value": "default"
                        },
                        {
                            "key": "http.method",
                            "type": "string",
                            "value": "POST"
                        },
                        {
                            "key": "http.target",
                            "type": "string",
                            "value": "/se/grid/newsessionqueue/session/bff2c9d4-b1d0-45f5-86c1-9807df051da9/failure"
                        },
                        {
                            "key": "http.status_code",
                            "type": "int64",
                            "value": 200
                        },
                        {
                            "key": "span.kind",
                            "type": "string",
                            "value": "internal"
                        },
                        {
                            "key": "otel.status_code",
                            "type": "string",
                            "value": "OK"
                        },
                        {
                            "key": "otel.status_description",
                            "type": "string",
                            "value": "Kind: OK Description:"
                        },
                        {
                            "key": "internal.span.format",
                            "type": "string",
                            "value": "proto"
                        }
                    ],
                    "logs": [],
                    "processID": "p2",
                    "warnings": null
                },
                {
                    "traceID": "4386b515fb4b20695620e6c7762fe367",
                    "spanID": "8906c5e99bec08d3",
                    "operationName": "sessionqueue.add_to_queue",
                    "references": [
                        {
                            "refType": "CHILD_OF",
                            "traceID": "4386b515fb4b20695620e6c7762fe367",
                            "spanID": "05e1ef9fbe82b066"
                        }
                    ],
                    "startTime": 1700604706064000,
                    "duration": 74060,
                    "tags": [
                        {
                            "key": "otel.library.name",
                            "type": "string",
                            "value": "default"
                        },
                        {
                            "key": "span.kind",
                            "type": "string",
                            "value": "internal"
                        },
                        {
                            "key": "internal.span.format",
                            "type": "string",
                            "value": "proto"
                        }
                    ],
                    "logs": [],
                    "processID": "p2",
                    "warnings": null
                },
                {
                    "traceID": "4386b515fb4b20695620e6c7762fe367",
                    "spanID": "4c077063ad694b61",
                    "operationName": "sessionqueue.add",
                    "references": [
                        {
                            "refType": "CHILD_OF",
                            "traceID": "4386b515fb4b20695620e6c7762fe367",
                            "spanID": "8d6812a7808dad24"
                        }
                    ],
                    "startTime": 1700604706064000,
                    "duration": 74226,
                    "tags": [
                        {
                            "key": "otel.library.name",
                            "type": "string",
                            "value": "default"
                        },
                        {
                            "key": "http.method",
                            "type": "string",
                            "value": "POST"
                        },
                        {
                            "key": "http.target",
                            "type": "string",
                            "value": "/se/grid/newsessionqueue/session"
                        },
                        {
                            "key": "http.status_code",
                            "type": "int64",
                            "value": 500
                        },
                        {
                            "key": "span.kind",
                            "type": "string",
                            "value": "internal"
                        },
                        {
                            "key": "otel.status_code",
                            "type": "string",
                            "value": "ERROR"
                        },
                        {
                            "key": "error",
                            "type": "bool",
                            "value": true
                        },
                        {
                            "key": "otel.status_description",
                            "type": "string",
                            "value": "Kind: INTERNAL Description:"
                        },
                        {
                            "key": "internal.span.format",
                            "type": "string",
                            "value": "proto"
                        }
                    ],
                    "logs": [],
                    "processID": "p2",
                    "warnings": null
                },
                {
                    "traceID": "4386b515fb4b20695620e6c7762fe367",
                    "spanID": "05e1ef9fbe82b066",
                    "operationName": "session_queue",
                    "references": [],
                    "startTime": 1700604706061000,
                    "duration": 78085,
                    "tags": [
                        {
                            "key": "otel.library.name",
                            "type": "string",
                            "value": "default"
                        },
                        {
                            "key": "http.method",
                            "type": "string",
                            "value": "POST"
                        },
                        {
                            "key": "http.status_code",
                            "type": "int64",
                            "value": 500
                        },
                        {
                            "key": "random.key",
                            "type": "string",
                            "value": "9b022e7f-0213-46f9-9877-b52b94822c85"
                        },
                        {
                            "key": "span.kind",
                            "type": "string",
                            "value": "server"
                        },
                        {
                            "key": "http.target",
                            "type": "string",
                            "value": "/session"
                        },
                        {
                            "key": "span.kind",
                            "type": "string",
                            "value": "internal"
                        },
                        {
                            "key": "otel.status_code",
                            "type": "string",
                            "value": "ERROR"
                        },
                        {
                            "key": "error",
                            "type": "bool",
                            "value": true
                        },
                        {
                            "key": "otel.status_description",
                            "type": "string",
                            "value": "Kind: INTERNAL Description:"
                        },
                        {
                            "key": "internal.span.format",
                            "type": "string",
                            "value": "proto"
                        }
                    ],
                    "logs": [
                        {
                            "timestamp": 1700604706139078,
                            "fields": [
                                {
                                    "key": "event",
                                    "type": "string",
                                    "value": "HTTP request execution complete"
                                },
                                {
                                    "key": "http.client_ip",
                                    "type": "string",
                                    "value": "29.64.0.180"
                                },
                                {
                                    "key": "http.flavor",
                                    "type": "int64",
                                    "value": 1
                                },
                                {
                                    "key": "http.handler_class",
                                    "type": "string",
                                    "value": "org.openqa.selenium.grid.sessionqueue.remote.RemoteNewSessionQueue"
                                },
                                {
                                    "key": "http.host",
                                    "type": "string",
                                    "value": "se-grid.apps.ajjp53b9.k8s.delta.sbrf.ru"
                                },
                                {
                                    "key": "http.method",
                                    "type": "string",
                                    "value": "POST"
                                },
                                {
                                    "key": "http.request_content_length",
                                    "type": "string",
                                    "value": "1503"
                                },
                                {
                                    "key": "http.scheme",
                                    "type": "string",
                                    "value": "HTTP"
                                },
                                {
                                    "key": "http.status_code",
                                    "type": "int64",
                                    "value": 500
                                },
                                {
                                    "key": "http.target",
                                    "type": "string",
                                    "value": "/session"
                                }
                            ]
                        }
                    ],
                    "processID": "p3",
                    "warnings": null
                },
                {
                    "traceID": "4386b515fb4b20695620e6c7762fe367",
                    "spanID": "8d6812a7808dad24",
                    "operationName": "httpclient.execute",
                    "references": [
                        {
                            "refType": "CHILD_OF",
                            "traceID": "4386b515fb4b20695620e6c7762fe367",
                            "spanID": "05e1ef9fbe82b066"
                        }
                    ],
                    "startTime": 1700604706063000,
                    "duration": 76305,
                    "tags": [
                        {
                            "key": "otel.library.name",
                            "type": "string",
                            "value": "default"
                        },
                        {
                            "key": "http.method",
                            "type": "string",
                            "value": "POST"
                        },
                        {
                            "key": "http.status_code",
                            "type": "int64",
                            "value": 500
                        },
                        {
                            "key": "span.kind",
                            "type": "string",
                            "value": "client"
                        },
                        {
                            "key": "http.target",
                            "type": "string",
                            "value": "/se/grid/newsessionqueue/session"
                        },
                        {
                            "key": "span.kind",
                            "type": "string",
                            "value": "internal"
                        },
                        {
                            "key": "otel.status_code",
                            "type": "string",
                            "value": "ERROR"
                        },
                        {
                            "key": "error",
                            "type": "bool",
                            "value": true
                        },
                        {
                            "key": "otel.status_description",
                            "type": "string",
                            "value": "Kind: INTERNAL Description:"
                        },
                        {
                            "key": "internal.span.format",
                            "type": "string",
                            "value": "proto"
                        }
                    ],
                    "logs": [],
                    "processID": "p3",
                    "warnings": [
                        "clock skew adjustment disabled; not applying calculated delta of -1.110391ms"
                    ]
                }
            ],
            "processes": {
                "p1": {
                    "serviceName": "selenium-distributor",
                    "tags": [
                        {
                            "key": "telemetry.sdk.language",
                            "type": "string",
                            "value": "java"
                        },
                        {
                            "key": "telemetry.sdk.name",
                            "type": "string",
                            "value": "opentelemetry"
                        },
                        {
                            "key": "telemetry.sdk.version",
                            "type": "string",
                            "value": "1.28.0"
                        }
                    ]
                },
                "p2": {
                    "serviceName": "selenium-session-queue",
                    "tags": [
                        {
                            "key": "telemetry.sdk.language",
                            "type": "string",
                            "value": "java"
                        },
                        {
                            "key": "telemetry.sdk.name",
                            "type": "string",
                            "value": "opentelemetry"
                        },
                        {
                            "key": "telemetry.sdk.version",
                            "type": "string",
                            "value": "1.28.0"
                        }
                    ]
                },
                "p3": {
                    "serviceName": "selenium-router",
                    "tags": [
                        {
                            "key": "telemetry.sdk.language",
                            "type": "string",
                            "value": "java"
                        },
                        {
                            "key": "telemetry.sdk.name",
                            "type": "string",
                            "value": "opentelemetry"
                        },
                        {
                            "key": "telemetry.sdk.version",
                            "type": "string",
                            "value": "1.28.0"
                        }
                    ]
                }
            },
            "warnings": null
        }
    ],
    "total": 0,
    "limit": 0,
    "offset": 0,
    "errors": null
}
```

### How can we reproduce the issue?

```shell
Deploy helm chart as distributed selenium grid, connect components to jaeger and run a lot of screenshot tests (1_000+)
```

### Relevant log output

```shell
See traces above
```

### Operating System

Kubernetes Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.11-dirty", GitCommit:"832310b96a670b5c01cef096b506ed0223c04279", GitTreeState:"dirty", BuildDate:"2023-08-11T12:09:43Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}

### Selenium version

4.15.0-20231110

### What are the browser(s) and version(s) where you see this issue?

4.15.0-20231110

### What are the browser driver(s) and version(s) where you see this issue?

4.15.0-20231110

### Are you using Selenium Grid?

Yes. Components version 4.15.0-20231110

**Comment by polRk** [comment] 2023-11-21 22:25
I use playwright and spawn chromes

<img width="837" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/39828645/4e0c9afc-cf49-481a-9c37-e14e6143ac3b">

**Comment by diemol** [comment] 2023-11-21 22:25
Duplicate of #13091

**Closed as not planned by diemol** 2023-11-21 22:25 UTC
Labels: I-defect
