### ISSUE TITLE
"Unable to take screenshot" error on web console

### ISSUE THREAD

**Issue by rdonuk** [SeleniumHQ/selenium#7926] opened 2020-01-10 12:54 UTC
## 🐛 Bug Report

Clicking "take screenshot" button for an active session causing an error. And no screenshot displays on the browser. The error is: 
```
Unable to take screenshot.
UnknownError: iVBORw0KGgoAAAANSUhEUgAAA/AAAAJ8CAYAAABZWkoZAAAAAXNSR0IArs4c6QAAIABJREFUeJzs3Xl8VOXB9vFrZpIJCVkgGwwEAmEJO4Z...
```
Screenshot:
![Capture](https://user-images.githubusercontent.com/770179/72154237-2921b100-33c1-11ea-950e-cd4e517e889a.JPG)

## To Reproduce
Use selenium standalone server 3.141.59. Create a remote session with a java client. Click Take Screenshot button for that session from web console.

Detailed steps to reproduce the behavior:

## Expected behavior

Display the screen shot.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 79.0.3945.117
Browser Driver version: 78.0.3904.70
Language Bindings version: Java 8

**Comment by tetramin** [comment] 2020-02-20 12:02
I have the same issue with selenium-standalone (and hub+nodes variant) docker image:

Browser: chrome
Browser and driver versions: 80.0.3987.106

**Comment by diemol** [comment] 2020-04-21 15:34
I've spent a while understanding where this comes from, and the issue is how the session gets created (JWP or W3C I believe), but most importantly, the UI [part](https://github.com/SeleniumHQ/selenium/blob/master/javascript/remote/hub.html) uses this [client.js](https://github.com/SeleniumHQ/selenium/blob/master/javascript/remote/ui/client.js#L337) to parse the response after the screenshot is created. Since it expects a different structure, then the error is prompted.

In any case, the code for Grid 3 (and therefore the UI) is not being worked anymore, and we are still defining how the UI for Grid 4 will look like, but probably it won't have this features which are hard to maintain and it is not clear how much is used. 

Sadly I have to write that we are closing this as a wont-fix since Grid 3 is not under development anymore.

**Closed by diemol** 2020-04-21 15:34 UTC
Labels: C-grid, D-chrome

**Comment by diemol** [comment] 2020-04-21 15:37
I've spent a while understanding where this comes from, and the issue is how the session gets created (JWP or W3C I believe), but most importantly, the UI [part](https://github.com/SeleniumHQ/selenium/blob/master/javascript/remote/hub.html) uses this [client.js](https://github.com/SeleniumHQ/selenium/blob/master/javascript/remote/ui/client.js#L337) to parse the response after the screenshot is created. Since it expects a different structure, then the error is prompted.

In any case, the code for Grid 3 (and therefore the UI) is not being worked anymore, and we are still defining how the UI for Grid 4 will look like, but probably it won't have these features which are hard to maintain and it is not clear how much they are used. 

Sadly I have to write that we are closing this as a wont-fix since Grid 3 is not under development anymore.

**Comment by diemol** [comment] 2020-04-21 17:13
I've spent a while understanding where this comes from, and the issue is how the session gets created (JWP or W3C I believe), but most importantly, the UI [part](https://github.com/SeleniumHQ/selenium/blob/master/javascript/remote/hub.html) uses this [client.js](https://github.com/SeleniumHQ/selenium/blob/master/javascript/remote/ui/client.js#L337) to parse the response after the screenshot is created. Since it expects a different structure, then the error is prompted.

In any case, the code for Grid 3 (and therefore the UI) is not being worked anymore, and we are still defining how the UI for Grid 4 will look like, but probably it won't have these features which are hard to maintain and it is not clear how much they are used. 

Sadly I have to write that we are closing this as a wont-fix since Grid 3 is not under development anymore.
