### ISSUE TITLE
In remote firefox while uploading file it gives error 'HTTP method not allowed'.

### ISSUE THREAD

**Issue by hgupta481994** [SeleniumHQ/selenium#8570] opened 2020-07-24 08:42 UTC
## 🐛 Bug Report

Unable to upload file with remote firefox on selenoid.

While using rspec, selenium-webdriver, capybara and selenoid for remote firefox, script is failing to upload file with "JSON::ParserError:    784: unexpected token at 'HTTP method not allowed'" error message.

## To Reproduce

Create a rspec scenario using selenium-webdriver and capybara gem. Use selenoid  [https://aerokube.com/selenoid/latest/#_uploading_files_to_browser](url) remote firefox browser and upload file using capybara method attach_file.

## Expected behavior
File should be uploaded

## Test script or set of commands reproducing this issue
In scenario visit page and call
`rspec.attach_file("attach_file_element_id", file_path)`

In configuration use following:
```
if ENV['BROWSER'] == 'firefox'
    caps = Selenium::WebDriver::Remote::Capabilities.new
    caps['browserName'] = 'firefox'
    # caps['moz:firefoxOptions'] = {w3c: false} ## It is not working
  else
    caps = Selenium::WebDriver::Remote::Capabilities.new
    caps["browserName"] = "chrome"
    caps["version"] = "81.0"
    caps['goog:chromeOptions'] = {w3c: false}
  end
    caps["enableVNC"] = true
    caps["screenResolution"] = "1280x800"
    caps['sessionTimeout'] = '15m'

  Capybara.register_driver :selenium do |app|  
    Capybara::Selenium::Driver.new(app, browser: :remote,
    :desired_capabilities => caps,
    :url => ENV["REMOTE_URL"] || "http://*.*.*.*:4444/wd/hub"
    )
  end

  Capybara.configure do |config|  
   config.default_driver = :selenium
  end
```

## Environment

OS: Ubuntu 18
Browser: Firefox
Browser version: 77.0
Language Bindings version: ruby-2.5.5

## Detail

I am using selenoid for remote browser testing in ruby. In that I am using 'selenium-webdriver', 'capybara', 'rspec' for automation. And I am using attach_file method for uploading file to browser I want to upload file on Firefox and Chrome browser but it raises error on both;
In chrome:
`Selenium::WebDriver::Error::UnknownCommandError: unknown command: unknown command: session/***8d32e045e3***/se/file`
In Firefox:
` HTTP method not allowed`

So After searching I found the solution for chrome which is to set w3c option false in caps['goog:chromeOptions'] > `caps['goog:chromeOptions'] = {w3c: false}` 
So now chrome is using OSS bridge for handshaking but I don't know how to do it in Firefox. Similar solution is not working for Firefox.

**Comment by barancev** [comment] 2020-07-24 09:25
Fixed by commit 7fda3b6f250ae36a5aa99506347f4221485ba185

**Closed as completed by barancev** 2020-07-24 09:25 UTC
Labels: A-needs-triaging

**Comment by hgupta481994** [comment] 2020-07-24 10:12
Commit has changes in java but I am using ruby gem

**Comment by barancev** [comment] 2020-07-24 12:46
Yes, but you told about "remote browser" that means you're using Selenium Server (that is written in Java and that was fixed by the mentioned commit)

**Comment by titusfortner** [comment] 2020-07-24 17:07
@hgupta481994 this is a duplicate of the issue I raised #8524 
I've verified that the commit Simon made fixed it.

**Comment by hgupta481994** [comment] 2020-07-27 05:20
Thanks @titusfortner and @barancev I have changed my  `lib\selenium\webdriver\remote\w3c\commands.rb` for now and used upload_file: [:post, 'session/:session_id/file'] instead of upload_file: [:post, 'session/:session_id/se/file']
