### ISSUE TITLE
Selenium Grid on Selenium-server-standalone-3.5.3 SendKeys command enters double charachters in IE 

### ISSUE THREAD

**Issue by bored002** [SeleniumHQ/selenium#5139] opened 2017-11-29 12:29 UTC
## Meta -
OS:  
 Windows 10 64Bit 
Selenium Version:  
3.5.3
**Browser:**  
Internet Explorer - 11

Browser Version:  
11.1106.10586.0

## Expected Behavior -
Selenium via grid should populate the provided value 

## Actual Behavior -

the value is produced duplicatly for example if the given value is face it will be actually 'ffaaccee'

## Steps to reproduce -
Launch selenium grid . hub and node
navigate to a url (https://www.google.com )
identify the search field 
enter the value selenium in the search field using SendKeys() method

**Comment by barancev** [comment] 2017-11-30 18:23
Duplicate of #5103

**Closed by barancev** 2017-11-30 18:23 UTC
