### ISSUE TITLE
[🐛 Bug]: File upload error on AWS Device Farm

### ISSUE THREAD

**Issue by cmarquez5** [SeleniumHQ/selenium#12236] opened 2023-06-21 19:30 UTC
### What happened?

Getting error below after updating to Selenium 4.
We are using Selenium 3 until four months ago when we decided to upgrade.
Our tests are made to run locally, and on AWS Device Farm.
After updating to Selenium 4, the file upload still works on local run but now it fails on AWS Device Farm. 
I saw related issues with the /se/file endpoint, but I didn't see any particular solution that may apply. We didn't change anything with regards the file upload test code, but it just didn't work after the upgrade.

Error is below:

  Message: 
Test method Tests.BCConnectTests.BCConnectRegressionTests.ProjectUploadAttachments threw exception: 
System.NotImplementedException: unknown command: unknown command: session/9a128717523b7c5ecc9da2a231ec5085/se/file

Just to give some context on filedetector, this is how it is setup
                var allowsDetection = driver as IAllowsFileDetection;
                if (allowsDetection != null)
                {
                    allowsDetection.FileDetector = new LocalFileDetector();
                }

### How can we reproduce the issue?

```shell
ChromeOptions options = WebDriverFactory.GetDefaultChromeOptions();
                options.AddArgument("disable-infobars");
                options.AddArgument("--start-maximized");
                options.AddAdditionalOption("aws:idleTimeoutSecs", IdleTimeoutSecs);
                options.AddAdditionalOption("aws:maxDurationSecs", MaxDurationSecs);
                options.AddAdditionalOption("se:downloadsEnabled", true);
                options.BrowserVersion = Config.GetValueForSection("AWSDeviceFarm", "BrowserVersion");

                driver = new RemoteWebDriver(DeviceFarmSetup.TestGridUrl, options.ToCapabilities(), SeleniumConfig.GetCommandTimeout());


var allowsDetection = driver as IAllowsFileDetection;
                if (allowsDetection != null)
                {
                    allowsDetection.FileDetector = new LocalFileDetector();
                }
```

### Relevant log output

```shell
 ProjectUploadAttachments
   Source: BCConnectRegressionTests.cs line 137
   Duration: 3.1 min

  Message: 
Test method Tests.BCConnectTests.BCConnectRegressionTests.ProjectUploadAttachments threw exception: 
System.NotImplementedException: unknown command: unknown command: session/9a128717523b7c5ecc9da2a231ec5085/se/file

  Stack Trace: 
WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
WebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
WebElement.Execute(String commandToExecute, Dictionary`2 parameters)
WebElement.UploadFile(String localFile)
WebElement.SendKeys(String text)
EventFiringWebElement.SendKeys(String text)
ElementHelper.HeadlessAttachFile(IWebDriver webDriver, By element, String fileName) line 1382
ProjectAttachmentsTab`1.HeadlessFileAttachment(String filename) line 223
BCConnectRegressionTests.ProjectUploadAttachments() line 165

  Standard Output: 

unknown command: unknown command: session/9a128717523b7c5ecc9da2a231ec5085/se/file
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.UploadFile(String localFile)
   at OpenQA.Selenium.WebElement.SendKeys(String text)
   at OpenQA.Selenium.Support.Events.EventFiringWebDriver.EventFiringWebElement.SendKeys(String text)
   at PageModel.Base.ElementHelper.HeadlessAttachFile(IWebDriver webDriver, By element, String fileName) in C:\Projects\Boise_Cascade\BoiseCascadeAutomation_9_0\BoiseCascadeAutomation\Models\Base\ElementHelper.cs:line 1382
   at PageModel.BCConnect.ProjectAttachmentsTab`1.HeadlessFileAttachment(String filename) in C:\Projects\Boise_Cascade\BoiseCascadeAutomation_9_0\BoiseCascadeAutomation\Models\BCConnect\Projects\ProjectAttachmentsTab.cs:line 223
   at Tests.BCConnectTests.BCConnectRegressionTests.ProjectUploadAttachments() in C:\Projects\Boise_Cascade\BoiseCascadeAutomation_9_0\BoiseCascadeAutomation\Tests\BCConnectTests\BCConnectRegressionTests.cs:line 165
Test failed


  Attachments: 
 Tests.BCConnectTests.BCConnectRegressionTests.ProjectUploadAttachments - 2023-06-21-06-59-38-6348.txt
 Tests.BCConnectTests.BCConnectRegressionTests.ProjectUploadAttachments - 2023-06-21-06-59-38-6348 Final.Png
```

### Operating System

Windows

### Selenium version

C# Selenium 4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome latest

### What are the browser driver(s) and version(s) where you see this issue?

Chrome latest, Selenium webdriver latest

**Comment by diemol** [comment] 2023-06-21 20:02
Where are you running those tests? Grid?

**Comment by cmarquez5** [comment] 2023-06-22 02:04
> Where are you running those tests? Grid?

AWS Device Farm

**Comment by diemol** [comment] 2023-06-22 05:09
OK, so this is a duplicate of #9350 

You need to reach out to them and share the info in the linked issue. In short, Selenium 4 uses the W3C WebDriver endpoints, and since `file` is not a W3C WebDriver standard endpoint, it needs to be prefixed, in this case with `/se/`,

**Closed as not planned by diemol** 2023-06-22 05:09 UTC
Labels: I-defect

**Comment by cmarquez5** [comment] 2023-06-22 06:31
> OK, so this is a duplicate of #9350
> 
> You need to reach out to them and share the info in the linked issue. In short, Selenium 4 uses the W3C WebDriver endpoints, and since `file` is not a W3C WebDriver standard endpoint, it needs to be prefixed, in this case with `/se/`,

Thanks for the response @diemol. Will reach out to AWS

**Comment by gautam-nutalapati** [comment] 2023-10-30 23:04
An update for the community:
We reached out to AWS about same issue, and they have it on their roadmap.
We were suggested to use `org.seleniumhq.selenium:selenium-java:4.0.0-alpha-1` version (version that was released in Feb 2021!)
