### ISSUE TITLE
[🐛 Bug]: Selenium Java API: In the [Cookie] class, the 'hashCode' method only incorporates [name], but 'equals' also checks [value]

### ISSUE THREAD

**Issue by sbabcoc** [SeleniumHQ/selenium#14041] opened 2024-05-26 19:12 UTC
### What happened?

The contract for `equals` and `hashCode` states that two objects considered to be equal should have the same hash code. In the current implementation, `equals` compares both [name] and [value], but `hashCode` is based only on [name]. This will result in bad behavior in collections where object hash code is significant (e.g. - **HashMap**, **HashSet**).

### How can we reproduce the issue?

Crack open **Cookie.java** and examine the implementations of `equals` and `hashCode`:

```
  /** Two cookies are equal if the name and value match */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof Cookie)) {
      return false;
    }

    Cookie cookie = (Cookie) o;

    if (!name.equals(cookie.name)) {
      return false;
    }
    return Objects.equals(value, cookie.value);
  }

  @Override
  public int hashCode() {
    return name.hashCode();
  }
```

### Relevant log output

There's no specific log output for this issue. The existing implementation will just produce unexpected results in contexts where object hash codes are significant.  

### Operating System

Immaterial

### Selenium version

Java 4.21.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

N/A

**Comment by diemol** [comment] 2024-05-26 19:52
This is kind of a duplicate of #13840

The spec only matches by name; hence, the hash only has the name.

**Closed as not planned by diemol** 2024-05-26 19:52 UTC

**Comment by sbabcoc** [comment] 2024-05-31 22:23
The issue is not that the hash code checks just the name; the issue is that the `equals` method also checks the value. Consequently, two cookies with the same name but different values will have the same hash code, but they will not be considered equal. We either need to add the value to the hash code computation, or remove it from `equals`.

**Comment by sbabcoc** [comment] 2024-05-31 22:25
https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Object.html#hashCode()

**Comment by titusfortner** [comment] 2024-06-01 00:10
Is that the common pattern for what is added to the hash? It doesn't make intuitive sense to me that two objects get considered equal based on how the spec indexes it.
