### ISSUE TITLE
Elements index Element

### ISSUE THREAD

**Issue by GodStar88** [SeleniumHQ/selenium#5597] opened 2018-03-12 09:18 UTC
var post = driver.FindElements(By.XPath("//div[@class='_5pcr userContentWrapper']"));
for (int i = 0; i < post.Count; i++)
{
       string str = post.ElementAt(i).FindElement(By.XPath("//div[@class='_5pbx userContent _3576']")).Text;
}

Hello. I just used this code
I got the same result (str).
please help me

**Comment by lmtierney** [comment] 2018-03-12 12:28
Duplicate of #5501

**Closed by lmtierney** 2018-03-12 12:28 UTC

**Comment by GodStar88** [comment] 2018-03-12 17:32
I can't find the way. Please help me
