### ISSUE TITLE
selenium==2.52 version says that it is 2.51 

### ISSUE THREAD

**Issue by drobota** [SeleniumHQ/selenium#1777] opened 2016-03-09 23:33 UTC
## Expected Behavior -
Selenium python package version is 2.51 where it should be 2.52 
```
In [2]: selenium.webdriver.__version__
Out[2]: '2.51.0'
In [5]: selenium.__version__
Out[5]: '2.51.0'
```

## Actual Behavior -
Version should be 2.52

## Steps to reproduce -
Install the latest selenium using pip or easy_install

**Comment by lukeis** [comment] 2016-03-09 23:43
duplicate of #1660

**Closed by lukeis** 2016-03-09 23:43 UTC
