### ISSUE TITLE
issue of using selenium IDE to record in firefox

### ISSUE THREAD

**Issue by AiolosYang** [SeleniumHQ/selenium#4923] opened 2017-10-22 04:29 UTC
## Meta -
OS:  Windows 10

Selenium Version:  2.9.1

Browser:  FireFox

Browser Version:  33.0

## Expected Behavior -
guide how to install IDE to record action
## Steps to reproduce -

Hi Export,
i am not possible to use selenium IDE to record in firefox, could you please suggest what's the exact issue is? thanks.
![image](https://user-images.githubusercontent.com/32993851/31858200-67a9ff8e-b724-11e7-80cd-1e85aec63f15.png)
![image](https://user-images.githubusercontent.com/32993851/31858201-6ec82bec-b724-11e7-8c83-b74c94f59788.png)

**Comment by barancev** [comment] 2017-10-23 20:23
Duplicate of #4406

**Closed by barancev** 2017-10-23 20:23 UTC
