### ISSUE TITLE
[selenium-webdriver-js] 'driver.wait' throws error when passing 'until.alertIsPresent'

### ISSUE THREAD

**Issue by nombrekeff** [SeleniumHQ/selenium#6537] opened 2018-10-15 12:02 UTC
## Meta -
OS: **Windows 10**
Selenium-webdriver: **3.6.0**
Browser: **Firefox x64**
Browser Version:  **62.0.3**
Geckodriver Version: **0.20.1**

## Expected Behavior -
Okey im trying to waint until an alert is present, using: `driver.wait(until.alertIsPresent())`
The problem is it throws the following error, although im passing in a condition: 
```
TypeError: Wait condition must be a promise-like object, function, or a Condition object
    at Driver.wait (...\node_modules\selenium-webdriver\lib\webdriver.js:928:13)
```

## Actual Behavior -
I would expect it to work as it says in the docs, maybe im doing something wrong. Or versions are not correct.

## Steps to reproduce -
1. Create firefox builder
2. Build driver
3. Open page that shows an alert
4. Set the wait until alert present
5. Throws unexpected error

## Additional info -
If I print the result of `until.alertIsPresent()` it shows:
```js
WebElementCondition {
  description_: 'Waiting for element to be located By(css selector, .FriendRequestAdd.addButton)',
  fn: [Function] }
```

If more info is needed, I will suply it.

**Comment by nombrekeff** [comment] 2018-10-15 12:14
PD:
It also happens with: `.wait(until.elementLocated(By.css('.class')));`

**Comment by Ugoku** [comment] 2018-12-05 10:56
I'm running into the same issue, hoping there's a solution for this.

Error:
```
TypeError: Wait condition must be a promise-like object, function, or a Condition object
        at thenableWebDriverProxy.wait (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:928:13)
        at UserContext.<anonymous> (/usr/src/app/test/selenium/myTest.js:88:23)
```

code:
```
it('shows a popup after the form is submitted', function(done) {
    return driver.wait(until.alertIsPresent(), 10000).then(function() {
        const confirm = browser.switchTo().alert();
        confirm.accept();

        done();
    });
});
```

**Comment by Ugoku** [comment] 2019-01-03 14:05
We managed to fix it using the workaround provided here: https://github.com/SeleniumHQ/selenium/issues/5560#issuecomment-436051503

**Comment by nombrekeff** [comment] 2019-01-03 14:08
Nice! I will try it later!

**Comment by barancev** [comment] 2019-04-14 12:28
Duplicate of #5749

**Closed by barancev** 2019-04-14 12:28 UTC
Labels: C-nodejs
