### ISSUE TITLE
C# Selenium 3.5.0 and 3.6.0 not able to load e10s extensions in Firefox 56.0

### ISSUE THREAD

**Issue by guygagnon** [SeleniumHQ/selenium#4903] opened 2017-10-18 19:21 UTC
## Meta -
OS:  Windows 10 x64

Selenium Version:  3.5.0 and 3.6.0

Browser:  Firefox 56.0 x64

## Expected Behavior -
Extension gets loaded

## Actual Behavior -
"FileNotFoundException is thrown "Could not find file '.\appdata\local\temp\anymous.hash.webdriver\[extensionname]\install.rdf'. "
This is a non-e10s format. The e10s format doesn't require this file and hence it looks like selenium is not yet e10s compatible.

## Steps to reproduce -

Environment:
Selenium 3.5.0 or 3.6.0
Windows 10 x64
FF56.0  x64
e10s extension
Geckodriver v0.19
Coding language c#

If you use this c# code with the proper E10SExtensionLocation , GeckoDriverLocationPath, BrowserExecutableLocation

FirefoxOptions options = new FirefoxOptions();
FirefoxProfileManager pm = new FirefoxProfileManager();
string pn = pm.ExistingProfiles.Where(profiles => profiles.Contains("default")).Single();
options.Profile = pm.GetProfile(pn);
option.BrowserExecutableLocation = BrowserExecutableLocation;
options.Profile.AddExtension(E10SExtensionLocation);
FirefoxDriverService fds = FirefoxDriverService.CreateDefaultService(GeckoDriverLocationPath);
FirefoxDriver driver = new FirefoxDriver(fds, options, TimeSpan.FromSeconds(30));

This code used to work for legacy extensions but now we need to start using e10s moving forward as per requirement from Firefox.

**Comment by barancev** [comment] 2017-10-19 05:14
Duplicate of #4093

**Closed by barancev** 2017-10-19 05:14 UTC
