### ISSUE TITLE
[🐛 Bug]: Error - org.openqa.selenium.UnsupportedCommandException: getElementDomAttribute Build info: version: '4.1.1'

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#10179] opened 2021-12-24 13:35 UTC
### What happened?

Getting error only while executing in Sauce. Local Machine its working as expected.

All the select class xpath are failing after updating selenium 4.1.1

Updated Remote webdriver as ChromeOptions options=new New ChromeOptions();

browser pick ki up correctly in sauce, but dropdown values not selecting.

### How can we reproduce the issue?

```shell
Trying select Dropdown values by using select elememt

public void selectByVisisibleText(Sting arg0, String arg1){
Select select = new Select(driver.findelement(By.xpath(arg0));
select.selectByviibleText(arg1);
}
tried different ByXpath/ID/Name
none of the worked.
```

### Relevant log output

```shell
java.lang.AssertionError: Element Not Found//select[@id='example']| Error - org.openqa.selenium.UnsupportedCommandException: getElementDomAttribute
Build info: version: '4.1.1',
, java.version: '1.8.0_231'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
```

### Operating System

Windows 10

### Selenium version

4.1.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 96, Edge 96 all latest 

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 96, Edge 96 all latest 

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment] 2021-12-24 18:10
This looks like a duplicate of #10131 

If you have a stack trace, please post it there, thanks.

**Closed as completed by titusfortner** 2021-12-24 18:10 UTC
Labels: I-defect, A-needs-triaging
