### ISSUE TITLE
Grid4-beta4: Caught exception while polling for event bus messages: Unable to determine type

### ISSUE THREAD

**Issue by KrzysztofC** [SeleniumHQ/selenium#9586] opened 2021-06-16 11:12 UTC
## 🐛 Bug Report

The issue was originally posted in Group (https://groups.google.com/g/selenium-users/c/OCiizPvTbJk), but since it is an exception error, there was no responses from other users.
 
The issue is that Node running outside of OpenShift does not register with Hub which is running in OpenShift, exception error is shown. If Hub is running on a different VM (outside of OpenShift), then the exact same Node is able to register.
 
Hub is running in OpenShift, command to start:
```
java -jar /opt/selenium/selenium-server-4.0.0-beta-4.jar hub --session-request-timeout ${SE_SESSION_REQUEST_TIMEOUT} --session-retry-interval ${SE_SESSION_RETRY_INTERVAL} --relax-checks ${SE_RELAX_CHECKS}
```
 
Node is run on a separate VM outside of OpenShift, command to start Node:
```
java -jar selenium-server-4.0.0-beta-4.jar node --publish-events tcp://selenium-grid4-hub-4442.xxxxx:80 --subscribe-events tcp://selenium-grid4-hub-4443.xxxx:80 --host xyzxyz --port 5555
```
 
This is Log output from Node:
```
06:44:29.838 INFO [LogManager$RootLogger.log] - Using the system default encoding
06:44:29.838 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
06:44:30.135 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-grid4-hub-4442.xxxxx:80 and tcp://selenium-grid4-hub-4443.xxxxx:80
06:44:30.213 INFO [UnboundZmqEventBus.<init>] - Sockets created
06:44:31.229 INFO [UnboundZmqEventBus.<init>] - Event bus ready
06:44:31.291 INFO [NodeServer.createHandlers] - Reporting self as: http://xxxxx:5555
06:44:31.307 INFO [NodeOptions.getSessionFactories] - Detected 4 available processors
06:44:31.338 INFO [NodeOptions.discoverDrivers] - Discovered 2 driver(s)
06:44:31.369 INFO [NodeOptions.report] - Adding Internet Explorer for {"browserName": "internet explorer","platformName": "XP"} 1 times
06:44:31.369 INFO [NodeOptions.report] - Adding Edge for {"browserName": "MicrosoftEdge","platformName": "XP"} 4 times
06:44:31.385 INFO [Node.<init>] - Binding additional locator mechanisms: name, id
06:44:32.026 INFO [NodeServer$1.start] - Starting registration process for node id 7dfb77a5-24bb-49ad-bb80-efa9ff8177e7
06:44:32.041 INFO [NodeServer.execute] - Started Selenium node 4.0.0-beta-4 (revision 29f46d02dd): http://xxxxx:5555
06:44:32.088 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
06:44:42.120 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
```
 
This is Log output from Hub running in OpenShift, the exception happens at the time when Node tries to register:
 
```
10:27:33.078 INFO [LogManager$RootLogger.log] - Using the system default encoding
10:27:33.083 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
10:27:33.373 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://10.57.12.200:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://10.57.12.200:4443]
10:27:33.500 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://10.57.12.200:4442 and tcp://10.57.12.200:4443
10:27:33.582 INFO [UnboundZmqEventBus.<init>] - Sockets created
10:27:34.584 INFO [UnboundZmqEventBus.<init>] - Event bus ready
10:27:35.880 INFO [Hub.execute] - Started Selenium Hub 4.0.0-beta-4 (revision 29f46d02dd): http://10.57.12.200:4444
10:33:10.159 WARN [UnboundZmqEventBus$PollingRunnable.run] - Caught exception while polling for event bus messages: Unable to determine type from: :. Last 1 characters read: :
Build info: version: '4.0.0-beta-4', revision: '29f46d02dd'
System info: host: 'selenium-grid-4-hub-1-k5cl8', ip: '10.57.12.200', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.24.1.el7.x86_64', java.version: '1.8.0_291'
Driver info: driver.version: unknown
org.openqa.selenium.json.JsonException: Unable to determine type from: :. Last 1 characters read: :
Build info: version: '4.0.0-beta-4', revision: '29f46d02dd'
System info: host: 'selenium-grid-4-hub-1-k5cl8', ip: '10.57.12.200', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.24.1.el7.x86_64', java.version: '1.8.0_291'
Driver info: driver.version: unknown
                at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:126)
                at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:141)
                at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
                at org.openqa.selenium.json.Json.toType(Json.java:69)
                at org.openqa.selenium.json.Json.toType(Json.java:55)
                at org.openqa.selenium.json.Json.toType(Json.java:50)
                at org.openqa.selenium.events.zeromq.UnboundZmqEventBus$PollingRunnable.run(UnboundZmqEventBus.java:229)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
```

The same was tried with Distributed Grid, where each component was running in separate container. The issue was the same and the error message was the same, it was observed in Event Bus Log.

Expected behavior: Node should be able to register with Hub running in OpenShift if all required ports are exposed.
 
Additional details:
 
Hub has ports 4442, 4443, 4444 exposed to outside of OpenShift via Service and Routes as below:
```
- apiVersion: v1
  kind: Service
  metadata:
    name: selenium-grid-4-hub
    labels:
      name: selenium-grid-4-hub
      component: "selenium-grid-4"
  spec:
    selector:
      app: selenium-grid-4-hub
    ports:
      - name: web
        protocol: TCP
        port: 4444
        targetPort: 4444
      - name: publish
        protocol: TCP
        port: 4442
        targetPort: 4442
      - name: subscribe
        protocol: TCP
        port: 4443
        targetPort: 4443
- apiVersion: v1
  kind: Route
  metadata:
    name: selenium-grid4-hub
    labels:
      app: selenium-grid4-hub
      name: selenium-grid4-hub
  spec:
    port:
      targetPort: web
    to:
      kind: Service
      name: selenium-grid-4-hub
      weight: 100
  wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    name: selenium-grid4-hub-4442
    labels:
      app: selenium-grid4-hub-4442
      name: selenium-grid4-hub-4442
  spec:
    port:
      targetPort: publish
    to:
      kind: Service
      name: selenium-grid-4-hub
      weight: 100
  wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    name: selenium-grid4-hub-4443
    labels:
      app: selenium-grid4-hub-4443
      name: selenium-grid4-hub-4443
  spec:
    port:
      targetPort: subscribe
    to:
      kind: Service
      name: selenium-grid-4-hub
      weight: 100
  wildcardPolicy: None
 ```

Hub UI is confirmed to be accessible via browser on: http://selenium-grid4-hub.xxxxxxxxxx:80/ui/index.html#/
UI works fine and does not show any errors, only "The Grid has no registered Nodes yet."

**Comment by diemol** [comment] 2021-07-13 14:57
The error happens because the Hub running inside OpenShift needs to query the `/status` endpoint of the Node before registering it. Have you checked that the network rules allow that?

**Comment by KrzysztofC** [comment] 2021-07-14 14:44
Node runs on a VM that has open network, meaning there is no firewall between Node and OpenShift.
Hub which is running in OpenShift has open outgoing connectivity, so is able to freely connect to any IP/port on the same network.
To verify, I opened terminal session in container which is running the Hub. I run:
curl http://NODE_HOSTNAME:5555/status

Result is (I replaced actual hostname with NODE_HOSTNAME):
{
  "value": {
    "ready": true,
    "message": "Ready",
    "node": {
      "availability": "UP",
      "heartbeatPeriod": 60000,
      "id": "85610cde-f649-4c78-a082-5151b931238b",
      "maxSessions": 1,
      "osInfo": {
        "arch": "amd64",
        "name": "Windows Server 2019",
        "version": "10.0"
      },
      "slots": [
        {
          "lastStarted": "1970-01-01T00:00:00Z",
          "id": {
            "hostId": "85610cde-f649-4c78-a082-5151b931238b",
            "id": "0b42b2be-9d40-43b4-b6cd-c0202a4b50ae"
          },
          "stereotype": {
            "browserName": "MicrosoftEdge",
            "browserVersion": "88",
            "platformName": "Windows"
          }
        }
      ],
      "uri": "http:\u002f\u002fNODE_HOSTNAME:5555",
      "version": "4.0.0-beta-4 (revision 29f46d02dd)"
    }
  }
}

**Comment by diemol** [comment] 2021-07-28 21:28
I will try to set up a local MiniShift because I do not have access to a OpenShift cluster to try this. What is the full manifest I can use to try to reproduce this?

Also, before I try to reproduce... Can you please try with the most recent prerelease? Both the [docker image](https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-rc-1-prerelease-20210713) and the [Selenium jar](https://github.com/SeleniumHQ/docker-selenium/releases/download/4.0.0-rc-1-prerelease-20210713/selenium-server-4.0.0-prerelease-rc-1-74745cf081.jar).

**Comment by KrzysztofC** [comment] 2021-08-04 17:14
Hi, I can't try your docker image, we have a policy preventing that, so I can only use Images I build myself, but there isn't much in it, all ports exposed, 3 ENV variables added, then sh script executed, details down below.

how can I check connectivity on ports 4442 and 4443? Those ports are exposed as separate URLs on port 80. Can't seem to be able to attach here a screenshot of OpenShift Service page showing all 3 ports routing into the Pod running the Hub.

I tried curls below executed on Node VM:
```
C:\Users\xyz>curl -I http://selenium-grid4-hub-4443-cto-cate-testautomation-163333.openshift_hostname_FQDN/
HTTP/1.0 502 Bad Gateway
Cache-Control: no-cache
Content-Type: text/html
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Date: Wed, 04 Aug 2021 16:51:52 GMT
 ```

```
C:\Users\xyz>curl -I http://selenium-grid4-hub-4442-cto-cate-testautomation-163333.openshift_hostname_FQDN/
HTTP/1.0 502 Bad Gateway
Cache-Control: no-cache
Content-Type: text/html
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Date: Wed, 04 Aug 2021 16:52:01 GMT
 ```

this one is main UI port 4444 exposed:
```
C:\Users\xyz>curl -I http://selenium-grid4-hub-cto-cate-testautomation-163333.openshift_hostname_FQDN/
HTTP/1.1 302 Found
content-length: 0
Location: /ui/index.html
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Set-Cookie: 0db327b82d6ad0d584139e424b8f2279=2ee9bc8dfc6366df8fe4229d8eb7f50f; path=/; HttpOnly
Date: Wed, 04 Aug 2021 16:51:39 GMT
```
 
-------------------------------------------------------------------------------------------------------------------
 
Node startup command:
```
java -jar C:\Users\xyz\Desktop\selenium-server-4.0.0-prerelease-rc-1-74745cf081.jar node --publish-events tcp://selenium-grid4-hub-4442-cto-cate-testautomation-163333.openshift_hostname_FQDN:80 --subscribe-events tcp://selenium-grid4-hub-4443-cto-cate-testautomation-163333.openshift_hostname_FQDN:80 --host node_VM_hostname --port 5555
```
 
Also tried using Node toml (notice how [server] and [node] appear to be swapped, [server] section has node details, but it's ptobably just confusing labeling:
```toml
[events]
publish="tcp://selenium-grid4-hub-4442-cto-cate-testautomation-163333.openshift_hostname_FQDN:80"
subscribe="tcp://selenium-grid4-hub-4443-cto-cate-testautomation-163333.openshift_hostname_FQDN:80"
 
[server]
host = "node_VM_hostname"
port = 5555
 
[node]
grid-url="http://selenium-grid4-hub-cto-cate-testautomation-163333.openshift_hostname_FQDN:80"
detect-drivers = false
 
[[node.driver-configuration]]
name = "Edge"
max-sessions = 1
stereotype = '{"browserName": "MicrosoftEdge", "browserVersion": "88", "platformName": "Windows"}'
 ```
-------------------------------------------------------------------------------------------------------------------
 
Grid Node started on a VM without using toml:
```
C:\Users\xyz\Desktop>java -jar C:\Users\xyz\Desktop\selenium-server-4.0.0-prerelease-rc-1-74745cf081.jar node --publish-events tcp://selenium-grid4-hub-4442-cto-cate-testautomation-163333.openshift_hostname_FQDN:80 --subscribe-events tcp://selenium-grid4-hub-4443-cto-cate-testautomation-163333.openshift_hostname_FQDN:80 --host node_VM_hostname --port 5555
12:13:46.809 INFO [LogManager$RootLogger.log] - Using the system default encoding
12:13:46.825 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
12:13:47.075 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-grid4-hub-4442-cto-cate-testautomation-163333.openshift_hostname_FQDN:80 and tcp://selenium-grid4-hub-4443-cto-cate-testautomation-163333.openshift_hostname_FQDN:80
12:13:47.169 INFO [UnboundZmqEventBus.<init>] - Sockets created
12:13:48.184 INFO [UnboundZmqEventBus.<init>] - Event bus ready
12:13:48.247 INFO [NodeServer.createHandlers] - Reporting self as: http://node_VM_hostname:5555
12:13:48.263 INFO [NodeOptions.getSessionFactories] - Detected 4 available processors
12:13:48.294 INFO [NodeOptions.discoverDrivers] - Discovered 1 driver(s)
12:13:48.325 INFO [NodeOptions.report] - Adding Internet Explorer for {"browserName": "internet explorer"} 1 times
12:13:48.341 INFO [Node.<init>] - Binding additional locator mechanisms: id, name
12:13:48.747 INFO [NodeServer$1.start] - Starting registration process for node id e97e360e-c152-4cc3-a35a-c360c9c13541
12:13:48.747 INFO [NodeServer.execute] - Started Selenium node 4.0.0-rc-1 (revision 74745cf081): http://node_VM_hostname:5555
12:13:48.747 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:13:58.763 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:14:08.779 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:14:18.779 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:14:28.781 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:14:38.796 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:14:48.804 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:14:58.813 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:15:08.814 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:15:18.815 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:15:28.817 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
12:15:38.817 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
 ```
-------------------------------------------------------------------------------------------------------------------
 
On OpenShift side Hub Pod Logs:
```
16:11:06.276 INFO [LogManager$RootLogger.log] - Using the system default encoding
16:11:06.280 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
16:11:06.491 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://10.57.6.151:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://10.57.6.151:4443]
16:11:06.653 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://10.57.6.151:4442 and tcp://10.57.6.151:4443
16:11:06.738 INFO [UnboundZmqEventBus.<init>] - Sockets created
16:11:07.739 INFO [UnboundZmqEventBus.<init>] - Event bus ready
16:11:08.959 INFO [Hub.execute] - Started Selenium Hub 4.0.0-rc-1 (revision 74745cf081): http://10.57.6.151:4444
16:26:59.110 WARN [UnboundZmqEventBus$PollingRunnable.run] - Caught exception while polling for event bus messages: Unable to read true. Saw : at position 1. Last 2 characters read: t:
Build info: version: '4.0.0-rc-1', revision: '74745cf081'
System info: host: 'selenium-grid-4-hub-2-6k89h', ip: '10.57.6.151', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.31.1.el7.x86_64', java.version: '1.8.0_291'
Driver info: driver.version: unknown
org.openqa.selenium.json.JsonException: Unable to read true. Saw : at position 1. Last 2 characters read: t:
Build info: version: '4.0.0-rc-1', revision: '74745cf081'
System info: host: 'selenium-grid-4-hub-2-6k89h', ip: '10.57.6.151', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.31.1.el7.x86_64', java.version: '1.8.0_291'
Driver info: driver.version: unknown
                at org.openqa.selenium.json.JsonInput.read(JsonInput.java:338)
                at org.openqa.selenium.json.JsonInput.nextBoolean(JsonInput.java:132)
                at org.openqa.selenium.json.StringCoercer.lambda$apply$0(StringCoercer.java:35)
                at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
                at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
                at org.openqa.selenium.json.JsonInput.read(JsonInput.java:296)
                at org.openqa.selenium.json.StaticInitializerCoercer.lambda$apply$0(StaticInitializerCoercer.java:51)
                at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:145)
                at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
                at org.openqa.selenium.json.Json.toType(Json.java:69)
                at org.openqa.selenium.json.Json.toType(Json.java:55)
                at org.openqa.selenium.json.Json.toType(Json.java:50)
                at org.openqa.selenium.events.zeromq.UnboundZmqEventBus$PollingRunnable.run(UnboundZmqEventBus.java:229)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
 ```
sometimes the error is different:
 ```
16:49:04.452 INFO [LogManager$RootLogger.log] - Using the system default encoding
16:49:04.457 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
16:49:04.726 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://10.57.10.215:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://10.57.10.215:4443]
16:49:04.930 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://10.57.10.215:4442 and tcp://10.57.10.215:4443
16:49:05.016 INFO [UnboundZmqEventBus.<init>] - Sockets created
16:49:06.017 INFO [UnboundZmqEventBus.<init>] - Event bus ready
16:49:07.485 INFO [Hub.execute] - Started Selenium Hub 4.0.0-rc-1 (revision 74745cf081): http://10.57.10.215:4444
16:50:53.922 WARN [UnboundZmqEventBus$PollingRunnable.run] - Caught exception while polling for event bus messages: Unable to determine type from: c. Last 1 characters read: c
Build info: version: '4.0.0-rc-1', revision: '74745cf081'
System info: host: 'selenium-grid-4-hub-5-m7wj4', ip: '10.57.10.215', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.31.1.el7.x86_64', java.version: '1.8.0_291'
Driver info: driver.version: unknown
org.openqa.selenium.json.JsonException: Unable to determine type from: c. Last 1 characters read: c
Build info: version: '4.0.0-rc-1', revision: '74745cf081'
System info: host: 'selenium-grid-4-hub-5-m7wj4', ip: '10.57.10.215', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.31.1.el7.x86_64', java.version: '1.8.0_291'
Driver info: driver.version: unknown
                at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:126)
                at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:141)
                at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:127)
                at org.openqa.selenium.json.Json.toType(Json.java:69)
                at org.openqa.selenium.json.Json.toType(Json.java:55)
                at org.openqa.selenium.json.Json.toType(Json.java:50)
                at org.openqa.selenium.events.zeromq.UnboundZmqEventBus$PollingRunnable.run(UnboundZmqEventBus.java:229)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
 ```
-------------------------------------------------------------------------------------------------------------------
 
Grid Hub start command: /opt/bin/start-selenium-grid-hub.sh
 ```shell
#!/usr/bin/env bash
 
# set -e: exit asap if a command exits with a non-zero status
set -e
 
if [ ! -z "$SE_OPTS" ]; then
  echo "Appending Selenium options: ${SE_OPTS}"
fi
 
if [ ! -z "$SE_HUB_HOST" ]; then
  echo "Using SE_HUB_HOST: ${SE_HUB_HOST}"
  HOST_CONFIG="--host ${SE_HUB_HOST}"
fi
 
if [ ! -z "$SE_HUB_PORT" ]; then
  echo "Using SE_HUB_PORT: ${SE_HUB_PORT}"
  PORT_CONFIG="--port ${SE_HUB_PORT}"
fi
 
 
java ${JAVA_OPTS} -jar /opt/selenium/selenium-server.jar hub \
  --session-request-timeout ${SE_SESSION_REQUEST_TIMEOUT} \
  --session-retry-interval ${SE_SESSION_RETRY_INTERVAL} \
  --relax-checks ${SE_RELAX_CHECKS} \
  ${HOST_CONFIG} \
  ${PORT_CONFIG} \
  ${SE_OPTS}
 ```
 
Docker Image has:
```dockerfile
# In seconds, maps to "--session-request-timeout"
ENV SE_SESSION_REQUEST_TIMEOUT 300
# In seconds, maps to "--session-retry-interval"
ENV SE_SESSION_RETRY_INTERVAL 5
# Boolean value, maps "--relax-checks"
ENV SE_RELAX_CHECKS true
```
 
-------------------------------------------------------------------------------------------------------------------
 
Grid Hub yaml deployment is simple, 1 service with 3 ports, 3 routes:
```yaml
apiVersion: v1
kind: Template
metadata:
  name: selenium-grid-4
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: selenium-grid-4-hub
    labels:
      app: selenium-grid-4-hub
      name: selenium-grid-4-hub
      component: "selenium-grid-4"
  spec:
    replicas: 1
    selector:
      type: selenium-grid-4-hub
    template:
      metadata:
        labels:
          app: selenium-grid-4-hub
          type: selenium-grid-4-hub
          name: selenium-grid-4-hub
          component: "selenium-grid-4"
      spec:
        containers:
            - env:
              - name: START_GRID_HUB
                value: "false"
              - name: START_XVFB
                value: "false"
              envFrom:
                - secretRef:
                    name: artifsecretforgrid
              image: >-
                xyz:2.1
              imagePullPolicy: IfNotPresent
              command:
                - /opt/bin/start-selenium-grid-hub.sh
              name: selenium-grid-4-hub
              resources:
                limits:
                  cpu: 1000m
                  memory: 4G
                requests:
                  cpu: 100m
                  memory: 1G
              ports:
              - containerPort: 4442
                protocol: TCP
              - containerPort: 4443
                protocol: TCP
              - containerPort: 4444
                protocol: TCP
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        imagePullSecrets:
          - name: artifsecretforgrid
        terminationGracePeriodSeconds: 30
    triggers:
      - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    name: selenium-grid-4-hub
    labels:
      name: selenium-grid-4-hub
      component: "selenium-grid-4"
  spec:
    selector:
      app: selenium-grid-4-hub
    ports:
      - name: web
        protocol: TCP
        port: 4444
        targetPort: 4444
      - name: publish
        protocol: TCP
        port: 4442
        targetPort: 4442
      - name: subscribe
        protocol: TCP
        port: 4443
        targetPort: 4443
- apiVersion: v1
  kind: Route
  metadata:
    name: selenium-grid4-hub
    labels:
      app: selenium-grid4-hub
      name: selenium-grid4-hub
  spec:
    port:
      targetPort: web
    to:
      kind: Service
      name: selenium-grid-4-hub
      weight: 100
  wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    name: selenium-grid4-hub-4442
    labels:
      app: selenium-grid4-hub-4442
      name: selenium-grid4-hub-4442
  spec:
    port:
      targetPort: publish
    to:
      kind: Service
      name: selenium-grid-4-hub
      weight: 100
  wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    name: selenium-grid4-hub-4443
    labels:
      app: selenium-grid4-hub-4443
      name: selenium-grid4-hub-4443
  spec:
    port:
      targetPort: subscribe
    to:
      kind: Service
      name: selenium-grid-4-hub
      weight: 100
  wildcardPolicy: None
```

**Comment by KrzysztofC** [comment] 2021-08-04 17:15
![Grid4HubService](https://user-images.githubusercontent.com/30735798/128225145-74b4f556-2ca5-4b61-8bd3-69523dd92611.jpg)

**Comment by KrzysztofC** [comment] 2021-08-04 17:25
[Selenium_Grid_Deployment DEV IE Grid 4 Hub.txt](https://github.com/SeleniumHQ/selenium/files/6933301/Selenium_Grid_Deployment.DEV.IE.Grid.4.Hub.txt)

**Comment by diemol** [comment] 2021-08-06 12:19
This `curl` command show that somehow those ports are not accesible

>I tried curls below executed on Node VM:
> ```
> C:\Users\xyz>curl -I http://selenium-grid4-hub-4443-cto-cate-testautomation-163333.openshift_hostname_FQDN/
> HTTP/1.0 502 Bad Gateway
> Cache-Control: no-cache
> Content-Type: text/html
> Proxy-Connection: Keep-Alive
> Connection: Keep-Alive
> Date: Wed, 04 Aug 2021 16:51:52 GMT
>  ```
> 
> ```
> C:\Users\xyz>curl -I http://selenium-grid4-hub-4442-cto-cate-testautomation-163333.openshift_hostname_FQDN/
> HTTP/1.0 502 Bad Gateway
> Cache-Control: no-cache
> Content-Type: text/html
> Proxy-Connection: Keep-Alive
> Connection: Keep-Alive
> Date: Wed, 04 Aug 2021 16:52:01 GMT
>  ```

It is hard for me to say what the problem is because I have never done a setup like that one. What I would try is to setup the Hub exposing the three ports separately, not using the same port `80`, but actually each port being reachable, and if this works you can discard that there is a network issue between the VMs and your OpenShift instance, so you could focus on figuring out how to expose propery the ports with the logic you currently have.

**Comment by KrzysztofC** [comment] 2021-08-09 16:13
Yes I wonder why those 2 return bad gateway, while third (4444) one works fine.
If you look closely, all 3 ports are exposed in exactly same way, all 3 are exposed on port 80, each on a different URL.
So we have all ports exposed as:
selenium-grid4-hub-4442-cto-cate-testautomation-163333.openshift_hostname_FQDN:80
selenium-grid4-hub-4443-cto-cate-testautomation-163333.openshift_hostname_FQDN:80
selenium-grid4-hub-cto-cate-testautomation-163333.openshift_hostname_FQDN:80
That third one above, that is port 4444 exposed as a URL on port 80 and it works as expected.
I can't use other ports, OpenShift creates outside Routes/Services on port 80. But since each port is exposed as different URL, it is fine.

I was wondering if ports 4442 and 4443 require some specific POST/GET to get a proper response, BUT the fact we are getting bad gateway already means we are getting through, because otherwise you simply get "Application is not available" page served by OpenShift.
Also, I just tried the same on a local VM, I tried accessing hostname:4442 and hostname:4443 and got "Page can not be displayed, invalid HTTP response". So it means what I get from Openshift is similar, but shows as bad gateway instead of direct error message.
Also, if connectivity was not working I think I would not get errors in Hub Pod console log after trying to connect an outside Node to it.

I guess I could go back to Grid 3 if this does not work, but would prefer use latest.
The reason I want to run Hub in OpenShift is because I get Kibana reports out of the box allowing me to create quite detailed Grid usage reports out of the Logs it outputs into Console. We need to know how many times a browser session was created for the past 3 months. If I run Hub on local VM, that becomes a big problem. We need past Grid usage data rather than just current state of it.

**Comment by KrzysztofC** [comment] 2021-08-24 11:21
UPDATE: Since we already have Selenium Grid 3 Hub running in the same OpenShift and it is configured in similar way as Grid4 (port 4444 exposed with Service/Route as a URL), I tried to register Grid3 Node running on the same standalone VM as was used for Grid4, and it connected without issues. I also run tests without issues too.
So to sum up: Grid3 Hub running in OpenShift, Service and Route is created to expose port 4444 as a URL with port 80, then that URL is used on standalone VM to start a Node with -hub parameter, and all that works as expected.
It is exact same setup I'm trying to replicate with Grid4, and that doesn't work.

**Comment by AutomatedTester** [comment] 2021-10-23 21:10
Is this still an issue now that Selenium 4 is out

**Comment by diemol** [comment] 2021-10-25 11:28
This is a duplicate of #9959, the fix will be part of the next release.

**Closed as completed by diemol** 2021-10-25 11:28 UTC
Labels: B-grid, J-awaiting answer
