### ISSUE TITLE
I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect

### ISSUE THREAD

**Issue by EldarAgalarov** [SeleniumHQ/selenium#1188] opened 2015-10-23 09:01 UTC
After updating WebDriver from 2.47.1 to 2.48.2 I'm getting exception below.
If I rolling back to 2.47.1 version - no exception and works fine. Why this happens?

Oct 23, 2015 11:53:05 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:05 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:05 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:05 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:05 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:05 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:08 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:08 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:08 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:08 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:08 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:08 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:08 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:08 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:08 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:08 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:10 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:10 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:10 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:10 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:10 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:10 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:10 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:10 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:10 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:10 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:10 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:10 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:12 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:12 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:12 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:12 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:12 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:12 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:14 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:14 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:14 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:14 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:14 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:14 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:14 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:14 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:14 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:14 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:16 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:16 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:16 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:16 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:16 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:16 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:18 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:18 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:18 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:18 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:18 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:18 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:18 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:18 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:20 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:20 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:20 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:20 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:20 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:20 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:22 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:22 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:22 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:22 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:22 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:22 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:24 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:24 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:24 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:24 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Oct 23, 2015 11:53:24 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:7056: Address already in use: connect
Oct 23, 2015 11:53:24 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:7056
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:55:52'
System info: host: 'ELDAR-PC', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_66'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:641)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:326)
	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:178)
	at GetLinkList.getStrings(GetLinkList.java:100)
	at GetLinkList.main(GetLinkList.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.net.BindException: Address already in use: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:161)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:89)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.execute(NewProfileExtensionConnection.java:170)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.execute(FirefoxDriver.java:380)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:620)
	... 9 more

**Comment by lukeis** [comment] 2015-10-23 17:39
can you please provide a way to reproduce this?

Otherwise I think it's a duplicate of #878  and will close for now as such unless you show it is different in some way.

**Closed by lukeis** 2015-10-23 17:39 UTC

**Comment by kothawadeprasanna** [comment] 2017-06-21 15:27
I am also getting the same exception 
2017/06/20 19:04:20 INFO  - org.apache.http.impl.execchain.RetryExec: I/O exception (java.net.BindException) caught when processing request to {}->http://XXXXXX.xxxxx.cloud:80: Address already in use: connect
