### ISSUE TITLE
Opening a chrome page with a chrome profile in python selenium

### ISSUE THREAD

**Issue by sskk10101** [SeleniumHQ/selenium#5482] opened 2018-02-11 12:01 UTC
I have got python to open up my chrome profile however when doing this it does not get the page i want it to get. However when i remove the added argument of my profile it gets the specific page
Here is my code:
`from selenium import webdriver

options = webdriver.ChromeOptions() 
options.add_argument(r"user-data-dir=C:\Users\Karim\AppData\Local\Google\Chrome\User Data") #Path to your chrome profile
chrome_path= r"C:\\Users\\chromedriver.exe"
driver = webdriver.Chrome(chrome_path, chrome_options=options)
driver.get("https://github.com/")`

**Comment by lmtierney** [comment] 2018-02-11 18:36
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by p0deje** [comment] 2018-02-12 07:28
It's not clear what is wrong here.

**Comment by sskk10101** [comment] 2018-02-12 07:38
The issue is when I add the argument of my chrome profile it opens it in chrome but then the program does not continue and anything I write after that does not happen for example loading the GitHub page. However when I remove the line that adds my chrome profile as an argument the program continues and does not stop

**Comment by p0deje** [comment] 2018-02-12 07:54
You might see this behavior if Chrome is already running. In this case, ChromeDriver might try to attach to the running browser and hang. If it's not running, it works fine. I've just tried using Ruby bindings:

```ruby
options = Selenium::WebDriver::Chrome::Options.new
options.add_argument '--user-data-dir=/Users/p0deje/Library/Application Support/Google/Chrome'
driver = Selenium::WebDriver.for(:chrome, options: options)
driver.get 'http://github.com'
```

Closing as cannot reproduce.

**Closed by p0deje** 2018-02-12 07:54 UTC
Labels: R-awaiting answer

**Comment by ZAM-** [comment] 2018-03-22 06:57
I also see this behavior with my tests.

**Comment by masterhimanshupoddar** [comment] 2019-06-14 16:13
I am unable to understand the Ruby bindings. Can you suggest any pythonic way to do this
