### ISSUE TITLE
Can't add firefox web-extension to profile

### ISSUE THREAD

**Issue by flamencist** [SeleniumHQ/selenium#3251] opened 2016-12-14 14:55 UTC
## Meta
OS:  
Windows 10
Selenium Version:  
3.0.1
Browser:  
Firefox 50
Language:
C# (dotnet)

## Problem
I can't add firefox web-extension (https://developer.mozilla.org/en/Add-ons/WebExtensions) for Firefox Driver.
The extension is signed by AMO.

## Code:
``` var options = new FirefoxOptions();
    var profile = new FirefoxProfile();
    profile.AddExtension("MyExtension.xpi");
    options.Profile = profile;
    var firefoxDriver = new FirefoxDriver(options); 
```

## Error:
```  
Could not find file 'C:\Users\TestUser\AppData\Local\Temp\anonymous.9da76164678e4f169142c80ccccebc4c.webdriver-profile.staging\MyExtension.xpi\install.rdf'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Threading.CompressedStack.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at OpenQA.Selenium.Firefox.FirefoxExtension.ReadIdFromInstallRdf(String root)
```
## PS
Firefox web-extension don't use update\install rdf file for updating\installing.

**Comment by datatooldev** [comment] 2017-01-06 21:06
I have the same problem. The web-extension is signed and can be loaded manually. 
The web-extension is added to the profile but it does not contain the install.rdf file, because it is not a part of the web-extension standard. The error happens when the driver is instantiated.

**Comment by 1212091** [comment] 2017-02-17 06:33
Could I ask this questions, I also have the same problem with web-extension on Firefox. When will this problem be fixed ?

**Comment by hheexx** [comment] 2017-12-03 23:57
vb.net code to add method to web driver for web extension installation

`Imports OpenQA.Selenium.Remote

Public Class MyFirefoxDriver
    Inherits OpenQA.Selenium.Firefox.FirefoxDriver

    Public Sub New(fo As OpenQA.Selenium.Firefox.FirefoxOptions)
        MyBase.New(fo)
        MyBase.CommandExecutor.CommandInfoRepository.TryAddCommand("moz-install-web-ext", New CommandInfo(CommandInfo.PostCommand, "/session/{sessionId}/moz/addon/install"))
    End Sub


    Public Sub InstallWebExtension(path As String)
        Dim params As New Dictionary(Of String, Object)
        params.Add("path", path)
        params.Add("temporary", True)
        MyBase.Execute("moz-install-web-ext", params)
    End Sub
End Class
`

**Comment by barancev** [comment] 2017-12-04 05:26
Duplicate of #4093

**Closed by barancev** 2017-12-04 05:26 UTC
Labels: C-dotnet, D-firefox
