### ISSUE TITLE
Selenium cannot make connetion firefox when options set Python

### ISSUE THREAD

**Issue by digiboons** [SeleniumHQ/selenium#6633] opened 2018-11-08 15:46 UTC
I am setting the profile of geckodriver by using Options 

Expected:
Open firefox with the profile assigned and remote control

Happining:
Open the firefox with profile assigned but not able to remote control
connection refused 

```
from selenium.webdriver.firefox.options import Options

options.add_argument("-profile")
options.add_argument("C:/Users/<USER>/AppData/Roaming/Mozilla/Firefox/Profiles/ji8rbij6.test")

browser=webdriver.Firefox(options=options)
```

Thanks in advance

**Comment by cgoldberg** [comment] 2018-11-09 05:32
dupe of #6592

**Closed by cgoldberg** 2018-11-09 05:32 UTC
