### ISSUE TITLE
[🐛 Bug]: Update dotnet API documentation

### ISSUE THREAD

**Issue by jrod567** [SeleniumHQ/selenium#11659] opened 2023-02-14 22:18 UTC
### What happened?

Not exactly a bug, but the dotnet API documentation is out of date and based on Selenium v3.1.0 - here: https://seleniumhq.github.io/selenium/docs/api/dotnet/

Are there plans to re-generate this documentation on v4.8+?

### How can we reproduce the issue?

```shell
Dotnet API documentation here:
https://seleniumhq.github.io/selenium/docs/api/dotnet/
```

### Relevant log output

```shell
N/A
```

### Operating System

Windows 10

### Selenium version

C#, 4.8

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

N/A

**Comment by titusfortner** [comment] 2023-02-15 00:55
Thanks for raising the issue. This is a duplicate of #10126 and the answer is that we need to transition to new Bazel rules for .NET in order to make it work, and we don't currently have resources for it.

**Closed as completed by titusfortner** 2023-02-15 00:55 UTC
Labels: I-defect, A-needs-triaging
