### ISSUE TITLE
Firefox 38 exception when running with the latest selenium sources

### ISSUE THREAD

**Issue by niranjala** [SeleniumHQ/selenium#601] opened 2015-06-02 14:04 UTC
I have pulled down the latest selenium source code build and released the jars. Using this I run my test for FF 38. I get a firefox exception "Firefox has stopped working" and had the following details in the error

Once I click debug on the error message the firefox browser launches and the test executes.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	firefox.exe
  Application Version:	38.0.1.5611
  Application Timestamp:	55540a1a
  Fault Module Name:	xul.dll
  Fault Module Version:	38.0.1.5611
  Fault Module Timestamp:	55541969
  Exception Code:	c0000005
  Exception Offset:	0035669b
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by oatesp** [comment] 2015-06-03 15:04
I have also encountered this issue with FireFox 38. I have rolled back to FF37 in order to continue running tests with selenium.

**Comment by yriart** [comment] 2015-06-03 21:25
I have also encountered this and Firefox 37 still works.

**Comment by jleyba** [comment] 2015-06-04 19:10
Duplicate of #437

**Closed by jleyba** 2015-06-04 19:10 UTC
