### ISSUE TITLE
Firefox driver for Python 2.7 raises exception quit 

### ISSUE THREAD

**Issue by jwb** [SeleniumHQ/selenium#434] opened 2015-04-08 21:13 UTC
The symptom is that the exception `CannotSendRequest` is encountered when the program executes the quit method of a Firefox WebDriver instance (example stack trace shown below). It appears that the code was written to handle exceptions emitted from `http.client`, but the version of `httplib` in Python 2.7 is raising exceptions that are subclasses of `HTTPException`.

  File "/workspace/SERVICES/tg.hdp-tests/HDPTests/hdp_tests/tools/run_firefox.py", line 53, in method
    driver.quit()
  File "/workspace/SERVICES/tg.hdp-tests/eggs/selenium-2.45.0-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 67, in quit
    RemoteWebDriver.quit(self)
  File "/workspace/SERVICES/tg.hdp-tests/eggs/selenium-2.45.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 457, in quit
    self.execute(Command.QUIT)
  File "/workspace/SERVICES/tg.hdp-tests/eggs/selenium-2.45.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 173, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/workspace/SERVICES/tg.hdp-tests/eggs/selenium-2.45.0-py2.7.egg/selenium/webdriver/remote/remote_connection.py", line 349, in execute
    return self._request(command_info[0], url, body=data)
  File "/workspace/SERVICES/tg.hdp-tests/eggs/selenium-2.45.0-py2.7.egg/selenium/webdriver/remote/remote_connection.py", line 379, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/usr/local/Cellar/python/2.7.7_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 995, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.7_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1023, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/Cellar/python/2.7.7_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 886, in putrequest
    raise CannotSendRequest()
CannotSendRequest:

**Comment by nikolas** [comment] 2016-05-24 14:40
Does this still happen to you? I've been using selenium 2.53.1 with python 2.7.11 without seeing this problem.

**Comment by AutomatedTester** [comment] 2016-09-26 11:19
Closing as can't reproduce and we have come a long way since then

**Closed by AutomatedTester** 2016-09-26 11:19 UTC
Labels: C-py, D-firefox
