### ISSUE TITLE
SendKeys doesnot work on on Mac OSX with latest Firefox and selenium 3.5.

### ISSUE THREAD

**Issue by parshudhole** [SeleniumHQ/selenium#5953] opened 2018-05-29 16:47 UTC
## Meta -
OS:  
Mac OSX 10.12 
Selenium Version:  
3.5 
Python 2.7 
Browser:  
Firefox 60.0.1

Gecko driver version: 0.20.1 

Browser Version:  
Firefox 60.0.1

## Expected Behavior -
Sendkeys should work on Firefox.

## Actual Behavior -
sendKeys is not working.

## Steps to reproduce -
1.Copy some data from text file.
2.Launch firefox through selenium.
3.Launch URL of any website having textarea.
4.Through selenium (Python binding) send keys send the key 'cmd+v' on firefox.

Please find the attached logs for details.
[geckodriver.log](https://github.com/SeleniumHQ/selenium/files/2049291/geckodriver.log)

This was working with earlier selenium version and Firefox versions(prior versions like Firefox 46 or 48).
Please note I also tested the same with Geckodriver 0.18.0 and Firefox 57 ,but the same problem persists.

**Comment by lmtierney** [comment] 2018-05-29 17:50
I cannot reproduce this. See the following working example:

```
from selenium.webdriver import ActionChains, Firefox
from selenium.webdriver.common.keys import Keys
d = Firefox()
d.get('https://text-compare.com/')
textbox1 = d.find_element_by_css_selector('#inputText1')
textbox2 = d.find_element_by_css_selector('#inputText2')
textbox1.send_keys('abcd')
actions = ActionChains(d)
actions.double_click(textbox1).key_down(Keys.COMMAND).send_keys('c').perform()
actions.reset_actions()
actions.click(textbox2).key_down(Keys.COMMAND).send_keys('v').perform()
print(textbox2.text)
d.quit()
```

**Comment by barancev** [comment] 2018-06-12 17:47
Closing the issue as there is no reproduction case provided.

**Closed by barancev** 2018-06-12 17:47 UTC
Labels: C-py, R-awaiting answer
